"""Beat-7 worked complement on the real tape — the realistic-spread test, name by name.

The headline charges one blended cost against the basket. The honest follow-up is per-instrument: IBS
is a microstructure edge, so it must clear *each* ETF's own bid-ask — and the bounce is biggest exactly
where the spread is widest (thin country funds). So we line each name's break-even up against a
*plausible* round-trip spread for its liquidity tier and count how many actually clear. We also re-price
the edge in the recent window, where the decay bites.

    python examples/extension.py            # cache-only
    python examples/extension.py --fetch    # populate the basket cache first (network)

Writes `docs/extension.md`.
"""

import argparse
import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from rubber_band import data, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")

# plausible round-trip spread (bps) by liquidity tier — generous for the liquid names, realistic for thin ones
SPREAD_GUESS = {
    "SPY": 1.0, "QQQ": 1.0, "TLT": 2.0, "GLD": 2.0, "USO": 3.0, "UUP": 3.0,
    "EWG": 6.0, "EWH": 8.0, "EWJ": 6.0, "EWQ": 8.0, "EWU": 8.0, "EWZ": 8.0, "FXI": 6.0, "INDA": 10.0,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()

    basket = data.fetch_basket(fetch=args.fetch)
    if not basket:
        print("[skip] no cached ETF basket -- run with --fetch first.")
        return
    basket = {tk: as_of(df, DEFAULT_AS_OF) for tk, df in basket.items()}
    closes = pd.DataFrame({tk: df["Close"] for tk, df in basket.items()})
    fp = fingerprint(closes.round(6))

    pn = extension.per_name_breakeven(basket)
    pn["spread_guess"] = [SPREAD_GUESS.get(tk, 8.0) for tk in pn.index]
    pn["clears"] = pn["breakeven_bps"] > pn["spread_guess"]
    n_clear = int(pn["clears"].sum())

    gross = strategy.timing_panel_returns(basket, cost_bps=0.0)
    last5 = gross[gross.index >= gross.index.max() - pd.Timedelta(days=365 * 5)]
    rows = []
    for sp in (0, 1, 2, 3, 5):
        net = strategy.timing_panel_returns(basket, cost_bps=sp)
        net5 = net[net.index >= net.index.max() - pd.Timedelta(days=365 * 5)]
        rows.append((sp, strategy.summary(net)["sharpe"], strategy.summary(net5)["sharpe"]))
        print(f"spread {sp}bps: full Sharpe {rows[-1][1]:+.2f}, last-5y {rows[-1][2]:+.2f}")

    _write(OUT, pn, n_clear, rows, fp, DEFAULT_AS_OF,
           closes.index.min().date(), closes.index.max().date(), len(basket))
    print(f"\nwrote {OUT}")


def _write(path, pn, n_clear, rows, fp, asof, lo, hi, n_names):
    pn_rows = "\n".join(
        f"| {tk} | {r['gross_sharpe']:+.2f} | {r['breakeven_bps']:.1f} | ~{r['spread_guess']:.0f} | "
        f"{'✅' if r['clears'] else '❌'} |"
        for tk, r in pn.iterrows()
    )
    sweep_rows = "\n".join(f"| {sp} | {full:+.2f} | {l5:+.2f} |" for sp, full, l5 in rows)
    text = f"""# Beat 7 — worked complement: the realistic-spread test (Study 19, Rubber-Band)

*Generated by [`examples/extension.py`](../examples/extension.py) on the cached ETF basket. As-of
**{asof}**, {n_names} names, fingerprint `{fp}`.*

## Does any single name clear its *own* spread?

The IBS bounce is a microstructure effect, so the fair test is per-instrument: each ETF's break-even
cost against a plausible round-trip spread for its liquidity tier. The cruel pattern — the strongest
bounce is in the thinnest, widest-spread country funds — means break-even and spread rise *together*.

| ETF | gross Sharpe | break-even (bps) | ~spread (bps) | clears? |
|---|---|---|---|---|
{pn_rows}

**{n_clear} of {n_names}** names clear their own assumed spread — and the ones that do are the thin
country funds where the "spread" is itself an optimistic guess and capacity is tiny.

## And the edge is fading

Basket IBS timing net Sharpe, full sample vs the last five years, as the round-trip spread rises:

| spread (bps) | full-sample Sharpe | last-5y Sharpe |
|---|---|---|
{sweep_rows}

**Takeaway.** Even granting a tight spread, the last-five-year edge is gone by a few bps; granting each
name its *real* spread, almost nothing clears. The bounce is real and was once strong — but it is a
museum piece, competed away exactly as a well-publicised microstructure edge should be. `REAL` /
`MIRAGE` / `DECAYED` survives the worked complement; the complement is what earns it.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
