"""Real-data run — is the IBS bounce real on a live ETF basket, and is it still tradable?

One signal, four questions (the offline core proves the machine; this points it at the market):

  * **Is the bounce real?** IBS-bucketed next-day returns and a Newey-West t-stat on the basket timing
    stream — a low close really does earn more tomorrow.
  * **Does it clear a spread?** The break-even cost (slippage that zeroes the net Sharpe) against the
    bid-ask you'd actually pay, name by name.
  * **Is it still alive?** First-half vs second-half vs last-5-year Sharpe — the decay of a once-strong,
    now-famous microstructure edge.
  * **Where does it live?** Per-ETF gross Sharpe and break-even — the strongest bounce sits in the
    thinnest, widest-spread names.

    python examples/verify.py --fetch     # populate the basket cache (network)
    python examples/verify.py             # offline, cache-only

Network lives only behind `--fetch`. Without it the run is cache-only. The sample is pinned with
`quantlab.repro.as_of` and stamped with a content fingerprint. Data choice: split-only OHLC (IBS is a
daily intraday-shape signal; dividends are immaterial at a one-day horizon) — stated, not hidden.
"""

import argparse
import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from rubber_band import data, ibs, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "results.md")
LIQUID = ["SPY", "QQQ", "TLT", "GLD"]


def _slice(basket, asof):
    return {tk: as_of(df, asof) for tk, df in basket.items()}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true", help="populate the ETF basket cache (network)")
    args = ap.parse_args()

    basket = data.fetch_basket(fetch=args.fetch)
    if not basket:
        print("[skip] no cached ETF basket -- run with --fetch first.")
        return
    basket = _slice(basket, DEFAULT_AS_OF)

    gross = strategy.timing_panel_returns(basket, cost_bps=0.0)
    rs = ibs.reversal_strength(basket["SPY"])              # SPY as the representative engine picture
    t = decompose.mean_tstat_hac(gross)
    s = strategy.summary(gross)
    be = decompose.breakeven_cost(basket)
    pn = extension.per_name_breakeven(basket)
    net2 = extension.basket_net_at_spread(basket, spread_bps=2.0)

    # decay
    mid = len(gross) // 2
    sh1 = strategy.summary(gross.iloc[:mid])["sharpe"]
    sh2 = strategy.summary(gross.iloc[mid:])["sharpe"]
    last5 = gross[gross.index >= gross.index.max() - pd.Timedelta(days=365 * 5)]
    last5_gross = strategy.summary(last5)["sharpe"]
    net3_full = strategy.timing_panel_returns(basket, cost_bps=3.0)
    last5_net3 = strategy.summary(net3_full[net3_full.index >= net3_full.index.max() - pd.Timedelta(days=365 * 5)])["sharpe"]

    liq = {k: basket[k] for k in LIQUID if k in basket}
    liq_gross = strategy.summary(strategy.timing_panel_returns(liq))["sharpe"]
    liq_be = decompose.breakeven_cost(liq)["breakeven_bps"]

    closes = pd.DataFrame({tk: df["Close"] for tk, df in basket.items()})
    fp = fingerprint(closes.round(6))

    print(f"basket {list(basket.keys())}")
    print(f"gross Sharpe {s['sharpe']:+.2f} (HAC t={t['t_stat']:+.1f}), break-even {be['breakeven_bps']:.1f}bps")
    print(f"decay: {sh1:+.2f} -> {sh2:+.2f}; last5y gross {last5_gross:+.2f}, net@3bps {last5_net3:+.2f}")

    _write(OUT, dict(
        tickers=list(basket.keys()), n=s["n_days"], fp=fp,
        lo=closes.index.min().date(), hi=closes.index.max().date(),
        rs=rs, t=t, s=s, be=be, pn=pn, net2=net2,
        sh1=sh1, sh2=sh2, last5_gross=last5_gross, last5_net3=last5_net3,
        liq_gross=liq_gross, liq_be=liq_be,
    ), DEFAULT_AS_OF)
    print(f"\nwrote {OUT}")


def _verdict(d):
    signal = "REAL" if (d["t"]["t_stat"] > 3 and d["s"]["sharpe"] > 0) else "WEAK"
    # tradable only if the *recent* edge survives a realistic spread
    trad = "MIRAGE" if d["last5_net3"] <= 0.1 else "FRAGILE"
    return signal, trad


def _write(path, d, asof):
    signal, trad = _verdict(d)
    pn_rows = "\n".join(
        f"| {tk} | {row['gross_sharpe']:+.2f} | {row['breakeven_bps']:.1f} |"
        for tk, row in d["pn"].iterrows()
    )
    bt = d["rs"]["table"]
    bucket_rows = "\n".join(
        f"| {int(b)} | {r['ibs']:.2f} | {r['next_ret_bps']:+.1f} | {int(r['n'])} |"
        for b, r in bt.iterrows()
    )
    text = f"""# Results — Study 19 (Rubber-Band) on a real ETF basket

*Generated by [`examples/verify.py`](../examples/verify.py). Daily split-only OHLC for {len(d['tickers'])}
liquid ETFs; the strategy is the single-asset IBS timing overlay (`w = 1 - 2*IBS`, long after a low
close) averaged equal-weight across the basket. The offline core proves the machinery on a synthetic
tape with a known IBS->next-day reversal; this is the measurement on the market. As-of **{asof}**; match
the fingerprint below to confirm you hold the same tape. Data choice: split-only (IBS is a one-day
intraday-shape signal, dividends immaterial at that horizon). Early years are thin on names — the
basket grows as ETFs list — so the *recent* sub-samples are the tradability-relevant ones.*

## The verdict, earned — Signal `{signal}` · Tradability `{trad}` · Still alive? `DECAYED`

The bounce is **real**: bucket days by Internal Bar Strength and a low close (IBS near 0) earns far
more the next session than a high one, with a basket Newey-West *t* of **{d['t']['t_stat']:+.1f}** on a
gross Sharpe of **{d['s']['sharpe']:+.2f}**. But you can't bank it today. It **trades every day**
(~170x/yr turnover) and the gross edge has **decayed** as it became famous — basket gross Sharpe
**{d['sh1']:+.2f}** in the first half of the sample, **{d['sh2']:+.2f}** in the second, and just
**{d['last5_gross']:+.2f}** over the last five years, where **net of a 3 bp round-trip it is
{d['last5_net3']:+.2f}** — under water. Worse, the strongest bounce sits in the *thinnest* names
(country ETFs with the widest real spreads), while the liquid names you *could* trade cheaply carry a
small edge and a low break-even. A genuine microstructure effect, competed away.

## Data stamp

- **Basket** ({len(d['tickers'])} ETFs): {d['lo']} -> {d['hi']}, {d['n']} basket-days, fingerprint `{d['fp']}`

## The bounce is real (SPY, IBS buckets -> next-day return)

Average next-day return by IBS bucket (0 = closed near the low). Low-IBS days bounce:

| IBS bucket | mean IBS | next-day return (bps) | n |
|---|---|---|---|
{bucket_rows}

- Low-minus-high next-day spread **{d['rs']['low_minus_high_bps']:+.1f} bps/day**; IBS->next-return
  slope **{d['rs']['ibs_slope']:+.4f}** (negative ⇒ low close bounces).
- Basket timing gross: Sharpe **{d['s']['sharpe']:+.2f}**, ann return **{d['s']['ann_return']:+.1%}**,
  Newey-West *t* = **{d['t']['t_stat']:+.1f}** ⇒ Signal `REAL`.

## Tradability — it lives inside the spread, and it's fading

- **Break-even cost** (basket net Sharpe → 0): **{d['be']['breakeven_bps']:.1f} bps** per unit traded.
  Net of a tight 2 bp spread the Sharpe is **{d['net2']['net_sharpe']:+.2f}** full-sample —
  but **{d['last5_net3']:+.2f}** net of 3 bp over the last five years.
- **Decay**: gross Sharpe **{d['sh1']:+.2f} → {d['sh2']:+.2f}** (first → second half), last-5y
  **{d['last5_gross']:+.2f}**.
- **Liquid-only** (SPY/QQQ/TLT/GLD, where you *can* trade tight): gross Sharpe **{d['liq_gross']:+.2f}**,
  break-even **{d['liq_be']:.1f} bps** — small edge, thin margin.

### Where the bounce lives (per-ETF gross Sharpe & break-even)

| ETF | gross Sharpe | break-even (bps) |
|---|---|---|
{pn_rows}

The biggest bounce is in the thinnest, widest-spread names — exactly the ones you can't trade at the
break-even they'd need. Signal `REAL`, Tradability `{trad}`, Still alive? `DECAYED`.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
