"""Build the two narrative notebooks for Study 52 (Smoke-Screen).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the shared EDGAR cache (_edgar_NetIncomeLoss + _CFO + _Assets + _yrret)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (smoke_screen/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from smoke_screen import data, strategy as st
sig, fwd = data.fetch_panel()                  # cache-first (shared EDGAR pull)
h = st.quantile_hedge(sig, fwd, q=0.2, long_high=False)   # long low accruals
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Accrual anomaly replicates?: Confirmed](https://img.shields.io/badge/Accrual_anomaly_replicates%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Smoke-Screen 💨\n### Earnings the cash doesn't back — and the firms that disappoint\n\n"
           + VERDICT +
           "Profit on the income statement and cash in the bank aren't the same thing. The gap — "
           "*accruals* — is the smoke: accounting estimates that can reverse. Sloan showed firms with "
           "high accruals subsequently underperform, and on real SEC filings the effect replicates "
           "cleanly: cash-backed earners beat accrual-heavy ones by ~6%/year.\n\n"
           "> 📓 **Plain-language layer.** The t-stat and the caveats are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The claim | The data (~2007–2025) |\n|---|---|\n"
           "| \"High-accruals firms underperform\" | True: hedge **+5.9%/yr**, hit **72%**. |\n"
           "| \"Cash-backed earners win\" | Long leg **+25.0%** vs market +19.6%. |\n"
           "| \"Significant?\" | Yes — Sharpe **0.64 (t ≈ 2.7)**. |"),
        md("## 1 · The claim\n\nSloan (1996): split earnings into a cash part and an accrual part. The "
           "accrual part (receivables, inventory, deferrals) is less persistent and the market over-trusts "
           "it — so high-accruals firms disappoint. Long low-accruals, short high-accruals."),
        md("## 2 · So what?\n\nIt's a clean, economically sensible signal you can read straight off the "
           "cash-flow statement: does the reported profit show up as cash? If 'quality of earnings' "
           "predicts returns, that's a real, fundamental edge — and a rare one that isn't priced away."),
        md("## 3 · How would we even know?\n\nCompute accruals = (net income − operating cash flow) / "
           "assets from SEC filings, sort firms, go long the cash-backed (low-accruals) and short the "
           "accrual-heavy, and measure the annual hedge and its significance."),
        code("disp=h[['low','high','hedge']].rename(columns={'low':'low-accruals (long)','high':'high-accruals (short)'})\n"
             "ax=(disp*100).plot(title='Annual returns: cash-backed vs accrual-heavy, and the hedge',lw=1.4)\n"
             "ax.axhline(0,color='k',lw=.8); ax.set_ylabel('%/yr'); plt.show()\n"
             "s=st.summary(h['hedge']); print(f\"hedge mean {s['mean']:+.2%}/yr, Sharpe {s['sharpe']:.2f}, t≈{s['tstat']:.1f}, hit {s['hit_rate']:.0%}\")"),
        md("## 4 · The teardown\n\nThe low-accruals (cash-backed) leg wins most years — and beats the "
           "market, not just the short leg. A genuine, significant edge."),
        code("eq=(1+h['hedge']).cumprod()\n"
             "ax=eq.plot(title='Growth of $1 in the accruals long-short (annual)',lw=1.8)\n"
             "ax.axhline(1.0,color='k',lw=.8,ls='--'); ax.set_ylabel('growth of $1'); plt.show()"),
        md("**Read it plainly.** A steady climb — quality of earnings really does predict returns. The "
           "rare bench result that's *real* and points the right way, not a mirage."),
        md("## 5 · The verdict\n\n**Signal: Real** — +5.9%/yr, t ≈ 2.7, 72% hit. **Tradability: Fragile** — "
           "short-side frictions, documented post-2000 fade. **Accrual anomaly replicates?: Confirmed.**"),
        md("## 6 · Could you actually trade it?\n\nThe long leg (own cash-backed earners) is easy and even "
           "beats the market. The full hedge needs shorting accrual-heavy names — costlier — and the edge "
           "is known to have faded since ~2003 as quants piled in. Real, but handle with care."),
        md("## 7 · Going further 🚪\n\nThe companion fundamental study is [Study 51 Blue-Chip](../../51-blue-chip/) "
           "(quality / gross profitability). Together they show real fundamental signals do survive on large "
           "caps — unlike the inverted [53 Jackpot](../../53-jackpot/) / [54 Static](../../54-static/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Smoke-Screen — a quantitative teardown 🔬\n### The accruals long-short on real EDGAR data · the t-stat · the long leg beating the market · the short-side & decay caveats\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We show the "
           "accruals anomaly replicates significantly on SEC data.\n\n"
           "> ⚠️ **Not investment advice.** EDGAR NetIncome/CFO/Assets + Yahoo annual returns, current "
           "S&P 500 members, ~2007–2025 (survivorship-biased, large-cap, short). Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | hedge +5.9%/yr, Sharpe 0.64, t ≈ 2.7, 72% hit |\n"
           "| Tradability | **Fragile** | short-side cost, post-2000 fade, short sample |\n"
           "| Replicates? | **Confirmed** | clean Sloan (1996) replication |\n\n"
           "> 💡 *In plain words:* a real fundamental edge — cash beats accounting."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** low-accruals firms out-earn high-accruals firms.\n"
           "- **H₂:** it's significant.\n- **H₃:** the long leg (cash-backed) beats the market."),
        md("## 2 · So what? — what rides on each\n\nIf all hold, quality-of-earnings is a confirmed, "
           "partly long-only-tradable edge. The short-side and decay caveats decide how much you keep."),
        md("## 3 · How we'd know — the protocol\n\nAccruals = (NI − CFO)/Assets → annual long-low/short-high "
           "→ the hedge's mean, Sharpe, t-stat, hit rate → the long leg vs the universe."),
        md("## 4 · The teardown"),
        md("### 4.1 The hedge"),
        code("display(h.round(3))\n"
             "s=st.summary(h['hedge']); print(f\"hedge: mean {s['mean']:+.2%}/yr  Sharpe {s['sharpe']:.2f}  t≈{s['tstat']:.1f}  hit {s['hit_rate']:.0%}  n={s['n']}\")"),
        md("> 💡 *In plain words:* +5.9%/yr, t ≈ 2.7 over ~18 years — **H₁ and H₂ hold.** A genuine signal."),
        md("### 4.2 The long leg beats the market"),
        code("print('low-accruals (long) : %+.2f%%' % (st.summary(h['low'])['mean']*100))\n"
             "print('high-accruals (short): %+.2f%%' % (st.summary(h['high'])['mean']*100))\n"
             "print('universe            : %+.2f%%' % (st.summary(st.market_annual(fwd).reindex(h.index))['mean']*100))"),
        md("> 💡 *In plain words:* cash-backed earners beat the market outright. **H₃ holds** — the edge isn't only on the short side."),
        md("### 4.3 The caveats that make it Fragile"),
        md("1. **Short-side cost.** Shorting accrual-heavy names carries borrow and is the harder leg.\n"
           "2. **Post-2000 fade.** Green-Hand-Soliman (2011) find the anomaly weakened markedly after "
           "~2003 — a decay a ~18-year window can't reveal.\n3. **Survivorship + large-cap.** A "
           "conservative test corner; a t of 2.7 here is, if anything, an under-statement."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all hold → Signal `REAL`, Tradability `FRAGILE`, replication "
           "`CONFIRMED`."),
        md("## 6 · Could you trade it?\n\nThe long-only version (own cash-backed earners) is clean and "
           "beats the market; the full long-short needs the costlier short and faces a known fade. A real "
           "edge, traded with care."),
        md("## 7 · Going further\n\nForks: (a) a longer Compustat history to see the post-2000 decay "
           "directly; (b) the percent-accruals / cash-flow variants (Hafzalla et al.); (c) combine with "
           "quality ([51 Blue-Chip](../../51-blue-chip/)). Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
