"""Build the two narrative notebooks for Study 49 (Black-Gold).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/black_gold_pair.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (black_gold/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from black_gold import data, strategy as st
d = data.fetch_pair()                          # cache-first; built by examples/verify.py --fetch
reg = st.predict_regression(d["oil"], d["eq"])
timing, bh = st.oil_timing(d["oil"], d["eq"]), st.buy_hold(d["eq"])
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Replicates out of sample?: Busted](https://img.shields.io/badge/Replicates_out_of_sample%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Black-Gold 🛢️\n### Does the price of oil predict the stock market?\n\n"
           + VERDICT +
           "A famous, intriguing claim: when oil rises this month, stocks fall next month — a delayed "
           "reaction you could trade. We test it on every month of tradable oil-futures data since 2000. "
           "The relationship is gone: not just weak, but the *wrong sign* and not significant — and a "
           "rule built on it badly trails simply buying and holding.\n\n"
           "> 📓 **Plain-language layer.** The regression and the sub-period slopes are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The claim | The data (2000–2026) |\n|---|---|\n"
           "| \"Oil up → stocks down next month\" | Slope **+0.017** (wrong sign), **t = 0.6** (insignificant). |\n"
           "| \"Trade it with an oil timer\" | Timing Sharpe **0.26** vs buy-and-hold **0.42**. |\n"
           "| \"A robust cross-asset signal\" | Absent in 2000–2008 *and* 2009-on. |"),
        md("## 1 · The claim\n\nDriesprong, Jacobsen & Maat (2008): oil-price changes negatively forecast "
           "next month's equity returns — markets underreact to oil, so last month's oil move leaks into "
           "this month's stocks. Documented across many countries, 1973–2003."),
        md("## 2 · So what?\n\nA single, public commodity price predicting the whole stock market would be "
           "a remarkable, tradable cross-asset edge. But a predictability documented on 1973–2003 is a "
           "*bet about the future* — and the only honest test is whether it still works on data you could trade."),
        md("## 3 · How would we even know?\n\nRegress this month's S&P return on last month's oil return "
           "(is the slope negative and significant?), then build the timing rule — long equities after "
           "oil falls — and race it against buy-and-hold."),
        code("fig,ax=plt.subplots(figsize=(7,5))\n"
             "ax.scatter(d['oil'].shift(1)*100, d['eq']*100, s=10, alpha=.5)\n"
             "xs=np.linspace(d['oil'].min()*100, d['oil'].max()*100, 50)\n"
             "ax.plot(xs, (reg['slope']*xs/100 + 0)*100, color='#c0392b', lw=2, label=f\"slope {reg['slope']:+.3f} (t={reg['tstat']:.1f})\")\n"
             "ax.set_xlabel('last month oil return (%)'); ax.set_ylabel('this month S&P return (%)')\n"
             "ax.set_title('No relationship — and the slope leans the wrong way'); ax.legend(); plt.show()"),
        md("## 4 · The teardown\n\nThe scatter is a cloud. The timing rule, holding cash whenever oil rose, "
           "simply gives up half the market's return."),
        code("rows={'oil timing':st.summary(timing),'buy & hold S&P':st.summary(bh)}\n"
             "t=pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown']]\n"
             "display(t.style.format({'cagr':'{:.1%}','sharpe':'{:.2f}','max_drawdown':'{:.0%}'}))\n"
             "eqT=(1+timing).cumprod(); eqB=(1+bh).cumprod()\n"
             "ax=eqB.plot(label='buy & hold S&P',lw=1.5); eqT.plot(ax=ax,label='oil timing',lw=1.5)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, 2000-2026'); ax.legend(); plt.show()"),
        md("**Read it plainly.** Conditioning on oil doesn't dodge anything — it just keeps you out of the "
           "market for no reason. The cross-asset crystal ball is cloudy."),
        md("## 5 · The verdict\n\n**Signal: None** — insignificant, wrong sign. **Tradability: Mirage** — "
           "the timer trails buy-and-hold. **Replicates out of sample?: Busted.**"),
        md("## 6 · Could you actually trade it?\n\nYou could code the oil timer in five lines — and you'd "
           "underperform a do-nothing index investor while taking on whipsaw risk. There's no edge to "
           "extract from last month's oil price."),
        md("## 7 · Going further 🚪\n\nThe quants notebook shows the slope is insignificant in every "
           "sub-period. This closes the second five-study bench. Next up (if you continue): the 52-week "
           "high effect — [Study 50 High-Water](../../50-high-water/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Black-Gold — a quantitative teardown 🔬\n### The predictive regression with a t-stat · timing vs buy-and-hold · sub-period slopes\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test "
           "oil→equity predictability on all tradable data and find none.\n\n"
           "> ⚠️ **Not investment advice.** WTI (CL=F) + S&P 500 (^GSPC) monthly, 2000–2026 (Yahoo). "
           "CL=F begins 2000, so Driesprong's 1973–2003 window isn't testable here — but the value is "
           "out-of-sample survival. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | slope +0.017, t +0.6, wrong sign |\n"
           "| Tradability | **Mirage** | timing Sharpe 0.26 < buy-and-hold 0.42 |\n"
           "| Replicates OOS? | **Busted** | insignificant in 2000–2008 and 2009-on |\n\n"
           "> 💡 *In plain words:* a documented predictor that vanished out of sample."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** the slope of equity_t on oil_(t−1) is negative and "
           "significant.\n- **H₂:** the oil-timing rule beats buy-and-hold.\n- **H₃:** it holds across sub-periods."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, a public price forecasts the market — a "
           "tradable cross-asset edge. If they fail OOS, it's a 1973–2003 in-sample artifact."),
        md("## 3 · How we'd know — the protocol\n\nOLS equity_t ~ oil_(t−1) with an analytic t-stat → "
           "timing vs buy-and-hold → 2000–2008 / 2009-on slope split."),
        md("## 4 · The teardown"),
        md("### 4.1 The predictive regression"),
        code("print({k:(round(v,3) if isinstance(v,float) else v) for k,v in reg.items()})\n"
             "print(f\"slope {reg['slope']:+.3f} (Driesprong: negative), t = {reg['tstat']:+.2f} (need |t|>2)\")"),
        md("> 💡 *In plain words:* t 0.6 and a positive slope — no relationship, and the wrong way. **H₁ rejected.**"),
        md("### 4.2 Timing vs buy-and-hold"),
        code("display(pd.DataFrame({'oil timing':st.summary(timing),'buy & hold':st.summary(bh)}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "print('time in market:', f\"{st.time_in_market(d['oil']):.0%}\")"),
        md("> 💡 *In plain words:* lower return, lower Sharpe, half the time in cash. **H₂ rejected.**"),
        md("### 4.3 Sub-period slopes"),
        code("for lab,sl in [('2000-2008',d[d.index.year<=2008]),('2009-on',d[d.index.year>=2009])]:\n"
             "    rr=st.predict_regression(sl['oil'],sl['eq']); print(f\"{lab}: slope {rr['slope']:+.3f}  t={rr['tstat']:+.2f}  n={rr['n']}\")"),
        md("> 💡 *In plain words:* insignificant and positive in both halves. **H₃ rejected** — never there in the tradable era."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all rejected → Signal `NONE`, Tradability `MIRAGE`, "
           "out-of-sample replication `BUSTED`."),
        md("## 6 · Could you trade it?\n\nNo edge to trade. The oil timer underperforms buy-and-hold and "
           "adds whipsaw. If oil matters for equities, it's contemporaneous and already priced — not a "
           "one-month-ahead signal."),
        md("## 7 · Going further\n\nForks: (a) a longer WTI spot series (pre-2000) to check the original "
           "window; (b) oil *shocks* (structural decomposition, Kilian 2009) vs raw returns; (c) "
           "sector-level (energy vs the rest) where a contemporaneous oil beta is real. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
