"""Notebook builder for Study 966 — Forecasting Tomorrow's Vol.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Forecasting Tomorrow's Vol \U0001F52E
### You cannot predict the return. You can absolutely predict the size of it.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

Nobody can tell you whether the market goes up or down tomorrow. Everybody can tell you
whether it will be a quiet day or a wild one — volatility clusters, and that is the most
reliable pattern in finance. So four models line up to forecast it: a plain 21-day average, a
one-line exponential filter, a Nobel-winning GARCH, and the realised-volatility literature's
workhorse. This notebook asks which one you should actually use.

> \U0001F4D3 **This is the plain-language layer.** The likelihood fitting, the QLIKE scores
> and the Diebold-Mariano tests are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is volatility forecastable? | Overwhelmingly yes — far more so than returns will ever be. |
| Does the Nobel-winning model beat the spreadsheet average? | Yes, out of sample, on most tapes. |
| By a lot? | No. And a single line of exponential smoothing gets most of the way there. |
| So what should you use? | EWMA if you want free and good; GARCH or HAR if the last few percent matter. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Returns are unpredictable, but risk is not. Fit a proper conditional-volatility model and
> your risk numbers will be sharper than anything a rolling window can give you."*

This is the mainstream position of forty years of econometrics, and it is broadly right. The
part worth testing is *how much* sharper.
"""
        ),
        md(
            r"""

## 2 · So what?

Every position size, every stop, every risk limit and every option price is a function of a
volatility number. If the fancy model is 20% better, that is worth having. If it is 2% better,
the extra machinery is a liability — one more thing to fit, monitor and misconfigure.
"""
        ),
        code(
            r"""
from vol_forecast import data, strategy as st

px = data.load_prices()
rets = {tk: px[tk].dropna().pct_change().dropna() for tk in data.TICKERS}
spy = rets["SPY"]
print(f"as-of {data.AS_OF} | SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} returns, annualised vol {spy.std() * np.sqrt(252):.1%})")
"""
        ),
        md(
            r"""

### Volatility clusters. Here is the whole premise, in one picture.
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True)
axes[0].plot(spy.index, spy * 100, lw=0.4, color="#8b949e")
axes[0].set_ylabel("daily return (%)"); axes[0].set_title("SPY daily returns")
roll = np.sqrt(st.rolling_sd_var(spy) * 252) * 100
axes[1].plot(roll.index, roll, lw=0.9, color="#c0392b")
axes[1].set_ylabel("21-day realised vol (annualised %)")
axes[1].set_title("Calm and storm arrive in stretches, not at random")
plt.show()
print(f"autocorrelation of |returns| at lag 1: {spy.abs().autocorr(1):.3f}   "
      f"at lag 21: {spy.abs().autocorr(21):.3f}")
print(f"autocorrelation of returns themselves at lag 1: {spy.autocorr(1):+.3f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** That contrast — a big number for |r| and a rounding error for
> r — is the entire justification for the volatility-modelling industry.
"""
        ),
        md(
            r"""

## 3 · How would we even know?

Each model gets the same data, is refitted every quarter on everything available up to that
point, and forecasts the next day, week or month. Then we score the forecasts on data the
model never saw. No peeking, and the scoring rule (QLIKE) is one that does not fall apart when
the thing being predicted is measured with noise.
"""
        ),
        md(
            r"""

## 4 · The teardown
"""
        ),
        code(
            r"""
ALL = {tk: st.tournament(r, 1, 756, 126) for tk, r in rets.items()}   # reused below
t = ALL["SPY"]
show = t[["qlike", "mse", "dm_vs_rolling", "p_vs_rolling"]].copy()
show.index = [st.MODEL_LABEL[m] for m in show.index]
fig, ax = plt.subplots(figsize=(9, 4.5))
colors = ["#8b949e" if m == "rolling21" else "#2ea44f" for m in t.index]
ax.bar([st.MODEL_LABEL[m].split(" (")[0] for m in t.index], t["qlike"], color=colors)
ax.set_ylabel("QLIKE loss (lower is better)")
ax.set_title("SPY, one-day-ahead, out of sample")
plt.setp(ax.get_xticklabels(), rotation=12, ha="right")
plt.show()
show.round(4)
"""
        ),
        md(
            r"""

The bars are close together. That is the finding: every sensible model knows the same thing,
and the difference between the best and the baseline is a few percent of a loss function, not
a different worldview.
"""
        ),
        md(
            r"""

### What the models actually look like when they disagree
"""
        ),
        code(
            r"""
f = st.forecasts(spy, horizon=1, burn=756, refit_every=126)
win = f.loc["2020-01-01":"2020-12-31"]
fig, ax = plt.subplots(figsize=(11, 5))
for m in st.MODELS:
    ax.plot(win.index, np.sqrt(win[m] * 252) * 100, lw=1.2, label=st.MODEL_LABEL[m])
realised = np.sqrt(st.rolling_sd_var(spy) * 252) * 100
ax.plot(realised.loc[win.index].index, realised.loc[win.index], color="k", lw=0.8, ls="--",
        label="realised (21d, hindsight)")
ax.set_ylabel("annualised volatility (%)")
ax.set_title("2020: four forecasts and what actually happened")
ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

The rolling window is the slow one — it steps up a month late and steps down a month late,
because every observation inside it has the same weight. That lag is precisely what the other
three models are built to remove.
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** Out of sample at the one-day horizon, **GARCH(1,1) QML** is the best model on **5 of 6** tapes, and something beats the 21-day rolling baseline on **6 of 6** — pooled Diebold-Mariano **+4.65** against a baseline that costs nothing to compute. The ordering is stable across horizons (1 / 5 / 21 days) and reproduced on simulated data where the true variance is observable.

**Usefulness: Fragile.** The pooled QLIKE improvement over the rolling window is **3.5%**. EWMA — one parameter, never fitted — captures 89% of what the fitted GARCH achieves, and the fitted models cost a maximum-likelihood optimisation every quarter. The gap between the best and worst *sensible* model is smaller than the gap between using any of them and using none.
"""
        ),
        md(
            r"""

## 6 · Is it worth the machinery?
"""
        ),
        code(
            r"""
rows = []
for tk, tt in ALL.items():
    base = tt.loc["rolling21", "qlike"]
    rows.append({"ticker": tk,
                 **{st.MODEL_LABEL[m]: 1 - tt.loc[m, "qlike"] / base for m in st.MODELS}})
gain = pd.DataFrame(rows).set_index("ticker").drop(columns=[st.MODEL_LABEL["rolling21"]])
fig, ax = plt.subplots(figsize=(10, 4.5))
(gain * 100).plot.bar(ax=ax)
ax.axhline(0, color="k", lw=0.8)
ax.set_ylabel("QLIKE improvement over the rolling window (%)")
ax.set_title("Every tape: how much the extra machinery buys")
ax.legend(title="", fontsize=8)
plt.show()
(gain * 100).round(1)
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Combine them.** The forecasting literature's most durable result is that a simple average
  of models beats the best single model. It would beat everything above, too.
- **Asymmetry.** GJR-GARCH and EGARCH let a fall raise volatility more than a rise — this
  desk's study **993** measures that effect directly.
- **Intraday data** replaces the noisy target with realised variance and roughly doubles
  everyone's apparent skill.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Forecasting Tomorrow's Vol — a quantitative teardown \U0001F52C
### QML GARCH · HAR-RV · EWMA · expanding-window out-of-sample · QLIKE · Diebold-Mariano

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Two
methodological points carry this study: the **target is a noisy proxy** (squared daily
returns), so the tournament is repeated in simulation where the true variance is observable;
and the **null must be run**, because a scoring rule that rewards complexity will reward it on
constant-volatility data too.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance, pinned as-of the date
> in [`docs/results.md`](../docs/results.md); literature map in
> [`docs/references.md`](../docs/references.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from vol_forecast import data, strategy as st

px = data.load_prices()
rets = {tk: px[tk].dropna().pct_change().dropna() for tk in data.TICKERS}
spy = rets["SPY"]
print(f"as-of {data.AS_OF} | SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} returns, annualised vol {spy.std() * np.sqrt(252):.1%})")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Out of sample at the one-day horizon, **GARCH(1,1) QML** is the best model on **5 of 6** tapes, and something beats the 21-day rolling baseline on **6 of 6** — pooled Diebold-Mariano **+4.65** against a baseline that costs nothing to compute. The ordering is stable across horizons (1 / 5 / 21 days) and reproduced on simulated data where the true variance is observable. |
| **Usefulness** | Fragile | The pooled QLIKE improvement over the rolling window is **3.5%**. EWMA — one parameter, never fitted — captures 89% of what the fitted GARCH achieves, and the fitted models cost a maximum-likelihood optimisation every quarter. The gap between the best and worst *sensible* model is smaller than the gap between using any of them and using none. |

> \U0001F4A1 **In plain words.** Everything with memory beats everything without. Among the
> models with memory, the differences are small enough that implementation risk probably
> dominates model risk.
"""
        ),
        md(
            r"""

## 1 · The claim, steelmanned

- **H₁.** A conditional-variance model (GARCH/HAR/EWMA) attains lower out-of-sample QLIKE than
  a 21-day rolling variance, on a majority of tapes, with DM |*t*| ≥ 2.
- **H₂.** The ranking is stable across horizons (1, 5, 21 days) — a model that only wins at one
  horizon has found a feature of the scoring, not of the market.
- **H₃.** The ranking obtained against the noisy squared-return proxy matches the ranking
  against the *true* conditional variance in a simulation calibrated to the same tape.
"""
        ),
        md(
            r"""

## 2 · So what? — the quantitative stakes

A volatility forecast that is 10% too low at the 99% quantile understates VaR by 10%. Over a
year of daily risk reporting that is the difference between a limit that binds and a limit
that does not. The stakes are in the risk system, not in the P&L.
"""
        ),
        md(
            r"""

## 3 · How we'd know — the protocol

1. **Expanding-window refits** every 63 sessions after a 756-session burn-in; the GARCH state
   is rolled forward between refits without re-estimating.
2. **Strict alignment**: forecast at *t* is scored against realised variance over
   *t+1 … t+h*. `test_forecasts_are_strictly_out_of_sample` mangles the future and checks that
   no earlier forecast moves.
3. **QLIKE and MSE** (Patton 2011), **HAC Diebold-Mariano** for the comparisons.
4. **A simulation with observable variance** to measure what the proxy costs, and a
   **constant-volatility null** to check the tournament does not reward complexity by default.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 The fitted GARCH, and what its persistence means
"""
        ),
        code(
            r"""
rows = []
for tk, r in rets.items():
    f = st.fit_garch11(r)
    rows.append({"ticker": tk, "alpha": f["alpha"], "beta": f["beta"],
                 "persistence": f["persistence"],
                 "half-life (days)": np.log(0.5) / np.log(max(f["persistence"], 1e-9)),
                 "uncond ann vol": np.sqrt(f["uncond_var"] * 252),
                 "converged": f["converged"]})
pd.DataFrame(rows).set_index("ticker").round(4)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Persistence just under 1 means a volatility shock decays over
> months, not days. It is also why GARCH and a long rolling window end up agreeing so often:
> both are, in the end, weighted averages of the recent past.
"""
        ),
        md(
            r"""

### 4.2 The full tournament, every tape
"""
        ),
        code(
            r"""
all_t = {tk: st.tournament(r, 1, 756, 126) for tk, r in rets.items()}
q = pd.DataFrame({tk: t["qlike"] for tk, t in all_t.items()}).T
q.columns = [st.MODEL_LABEL[m] for m in q.columns]
fig, ax = plt.subplots(figsize=(10, 4.5))
im = ax.imshow(q.rank(axis=1).values, cmap="RdYlGn_r", aspect="auto", vmin=1, vmax=4)
ax.set_xticks(range(q.shape[1])); ax.set_xticklabels(q.columns, rotation=15, ha="right", fontsize=8)
ax.set_yticks(range(q.shape[0])); ax.set_yticklabels(q.index)
for i in range(q.shape[0]):
    for j in range(q.shape[1]):
        ax.text(j, i, f"{q.values[i, j]:.4f}", ha="center", va="center", fontsize=8)
ax.set_title("Out-of-sample QLIKE (green = better rank)")
plt.show()
pd.DataFrame({tk: t["dm_vs_rolling"] for tk, t in all_t.items()}).T.round(2)
"""
        ),
        md(
            r"""

### 4.3 Horizon robustness
"""
        ),
        code(
            r"""
rows = []
for hz in st.HORIZONS:
    t = all_t["SPY"] if hz == 1 else st.tournament(spy, hz, 756, 126)
    base = t.loc["rolling21", "qlike"]
    for m in st.MODELS:
        rows.append({"horizon": hz, "model": st.MODEL_LABEL[m].split(" (")[0],
                     "gain vs rolling": 1 - t.loc[m, "qlike"] / base})
d = pd.DataFrame(rows).pivot(index="horizon", columns="model", values="gain vs rolling")
fig, ax = plt.subplots(figsize=(9, 4.5))
(d * 100).plot.bar(ax=ax)
ax.axhline(0, color="k", lw=0.8)
ax.set_ylabel("QLIKE improvement over rolling (%)"); ax.set_title("SPY: 1, 5 and 21 days ahead")
ax.legend(title="", fontsize=8)
plt.show()
(d * 100).round(2)
"""
        ),
        md(
            r"""

### 4.4 What the noisy proxy costs

On the real tape the target is a squared daily return — an unbiased estimate of the day's
variance whose own standard error exceeds the quantity it estimates. In simulation the true
conditional variance is available, so both scoreboards can be printed side by side.
"""
        ),
        code(
            r"""
r_sim, sigma, tr = data.synthetic_vol_path(n_years=20, signal_strength=1.0, seed=966)
proxy = st.tournament(r_sim, 1, 756, 126)
truth = st.truth_scored_tournament(r_sim, sigma, 1, 756, 126)
cmp = pd.DataFrame({"QLIKE vs proxy": proxy["qlike"],
                    "QLIKE vs truth": truth["qlike_vs_truth"],
                    "corr with truth": truth["corr_with_truth"]})
cmp.index = [st.MODEL_LABEL[m] for m in cmp.index]
print(cmp.round(4).to_string())
print(f"\nsame winner under both scoreboards: "
      f"{proxy['qlike'].idxmin() == truth['qlike_vs_truth'].idxmin()}")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The noisy target inflates *everyone's* loss by roughly the
> same amount, so the podium survives. What it destroys is the illusion that any of these
> models is bad: correlations with the true variance are high even where QLIKE looks poor.
"""
        ),
        md(
            r"""

### 4.5 The null: constant volatility
"""
        ),
        code(
            r"""
r_null, _, _ = data.synthetic_vol_path(n_years=20, signal_strength=0.0, seed=966)
tn = st.tournament(r_null, 1, 756, 126)
f_null = st.forecasts(r_null, 1, 756, 126)
f_real = st.forecasts(spy, 1, 756, 126)
flat = pd.Series({st.MODEL_LABEL[m]: np.log(f_null[m].dropna()).std()
                  / np.log(f_real[m].dropna()).std() for m in st.MODELS},
                 name="forecast dispersion, null / SPY")
out = tn[["qlike", "dm_vs_rolling"]].copy()
out.index = [st.MODEL_LABEL[m] for m in out.index]
print(out.round(4).to_string())
print()
print(flat.round(2).to_string())
print("\nThe naive reading — 'a fitted model beats the rolling window here, so the")
print("tournament rewards complexity' — is wrong. With constant volatility the optimal")
print("forecast IS the unconditional variance, which is exactly what a variance-targeted")
print("GARCH converges to, while a 21-day window keeps re-estimating it from 21 noisy")
print("observations. What would be damning is invented dynamics, and the dispersion")
print("column shows there are none.")
"""
        ),
        md(
            r"""

## 5 · The verdict
"""
        ),
        code(
            r"""
summary = []
for tk, t in all_t.items():
    base = t.loc["rolling21", "qlike"]
    best = t["qlike"].idxmin()
    summary.append({"ticker": tk, "best model": st.MODEL_LABEL[best].split(" (")[0],
                    "gain vs rolling": 1 - t.loc[best, "qlike"] / base,
                    "DM": t.loc[best, "dm_vs_rolling"],
                    "EWMA gain": 1 - t.loc["ewma94", "qlike"] / base})
s = pd.DataFrame(summary).set_index("ticker")
print(s.round(4).to_string())
print(f"\nbest model wins on {(s['gain vs rolling'] > 0).sum()}/{len(s)} tapes | "
      f"mean gain {s['gain vs rolling'].mean():.2%} | mean DM {s['DM'].mean():+.2f} | "
      f"EWMA alone gets {s['EWMA gain'].mean():.2%}")
"""
        ),
        md(
            r"""

## 6 · Is it worth it?

Cost of the baseline: one line of pandas. Cost of GARCH: a numerical optimisation that can fail
to converge, needs a refit schedule, and has three parameters to monitor. The QLIKE difference
between them is a few percent. Whether that trade is worth making depends entirely on what sits
downstream of the number — which is a governance question, not an econometric one.
"""
        ),
        md(
            r"""

## 7 · Going further

- **Forecast combination** (equal-weight average of the four) — the single most reliable
  improvement available, and a one-line fork of this notebook.
- **Asymmetric models** (GJR, EGARCH) and the leverage effect — study **993** on this desk.
- **Student-t likelihood** instead of QML: better tail fit, slower optimisation.
- **Model Confidence Set** (Hansen, Lunde & Nason 2011) instead of pairwise DM tests, which is
  the right tool once the number of competitors grows.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
