"""Beat-7 worked complement on the real tape — the top-k sweep.

A rotation rule that only beats the equal-weight basket at one hand-picked number of held sectors is a
data-mined artefact. This script sweeps top_k on the real SPDR sectors and writes `docs/extension.md`.

    python examples/extension.py            # cache-only
    python examples/extension.py --fetch
"""

import argparse
import os
import sys

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from carousel import data, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")
COST_BPS = 3.0


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    rets = data.fetch_sectors(fetch=args.fetch)
    if rets.empty:
        print("[skip] no cached sector ETFs -- run with --fetch first."); return
    rets = as_of(rets, DEFAULT_AS_OF)
    fp = fingerprint(rets.round(6))
    sw = extension.topk_sweep(rets, cost_bps=COST_BPS)
    print(sw["matrix"].round(3).to_string())
    _write(OUT, sw, fp, DEFAULT_AS_OF, rets.index.min().date(), rets.index.max().date(), rets.shape[1])
    print(f"\nwrote {OUT}")


def _write(path, sw, fp, asof, lo, hi, n_sec):
    rows = "\n".join(f"| {int(k)} | {r['rotation_sharpe']:+.2f} | {r['gain_over_ew']:+.2f} |"
                     for k, r in sw["matrix"].iterrows())
    text = f"""# Beat 7 — worked complement: the top-k sweep (Study 28, Carousel)

*Generated by [`examples/extension.py`](../examples/extension.py) on the {n_sec} real SPDR sectors. As-of
**{asof}**, {lo} → {hi}, fingerprint `{fp}`.*

## Was holding 3 sectors the lucky pick?

If sector momentum were a real edge, rotation would beat the equal-weight basket whether you held the
top 2 sectors or the top 5. We sweep the number held and read the gain over the basket:

| sectors held (top-k) | rotation Sharpe | gain over equal-weight |
|---|---|---|
{rows}

Rotation beats the basket on **{sw['frac_beat_ew']:.0%}** of these choices (mean gain
**{sw['mean_gain']:+.2f}**); the best, k = **{sw['best_k']}**, is just the luckiest cell. A rule that
helps at one concentration and hurts at the others is fitting the past, not finding a signal.

**Takeaway.** `WEAK` / `MIRAGE` / `Not supported` survives the worked complement — the sweep is what
exposes the cherry-pick behind every sector-rotation success story. Pick the number of sectors after
seeing the result and you can always narrate a win; demand it work *out of sample, at an unchosen
concentration*, and it's a coin flip with extra turnover.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
