"""Build the two narrative notebooks for Study 50 (High-Water).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/high_water_panel.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (high_water/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from high_water import data, strategy as st
# Opt-in, stated: current S&P 500 members + a >=20y-history filter = a survivor panel. Here the
# bias hits the SIGN: the short leg (fallen names) is guaranteed survivors, so the negative hedge
# is partly manufactured. The momentum correlation is the bias-robust number.
ret = data.fetch_panel(allow_survivorship_bias=True)   # cache-first; built by examples/verify.py --fetch
hi = st.cross_section_hedge(ret, st.nearness(ret))
mo = st.cross_section_hedge(ret, st.momentum(ret))     # standard 12-2 momentum (skips the last month)
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![A distinct anomaly?: Busted](https://img.shields.io/badge/A_distinct_anomaly%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# High-Water 🏔️\n### \"Buy stocks near their 52-week high\" — a distinct edge, or just momentum?\n\n"
           + VERDICT +
           "There's a famous idea that stocks trading near their one-year high keep climbing — an "
           "*anchoring* story said to be different from plain momentum. We test both halves on large-cap "
           "stocks: no premium showed up (the long-short lost on our panel — though the panel itself, "
           "made of today's survivors, pushes the sign that way), and it turns out to be 0.82 correlated "
           "with ordinary 12-2 momentum — the same factor with a behavioural label. That correlation, "
           "not the loss, is the finding that doesn't depend on the panel.\n\n"
           "> 📓 **Plain-language layer.** The correlation and the t-stats are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The claim | The data (1996–2026, large caps) |\n|---|---|\n"
           "| \"Near-high stocks out-earn\" | No premium: the long-short showed **−8.4%/yr** (Sharpe −0.40) — a loss on *this survivor panel*, whose short leg (fallen names that we know rebounded into today's index) partly manufactures the sign. |\n"
           "| \"It's distinct from momentum\" | It's **0.82 correlated** with the standard 12-2 momentum hedge — and that number doesn't care about the panel's bias. |\n"
           "| \"A free anchoring edge\" | Nothing positive gross, so costs only deepen the hole. |"),
        md("## 1 · The claim\n\nGeorge & Hwang (2004): a stock's **nearness to its 52-week high** (price ÷ "
           "one-year high) predicts its return — investors anchor on the high and underreact — and this "
           "beats, and is *separate from*, Jegadeesh-Titman momentum."),
        md("## 2 · So what?\n\nIf it's a distinct, durable edge, it's another factor for the toolbox. If "
           "it's momentum relabelled — and momentum that didn't even pay on large caps — then it's a "
           "story dressed as a discovery."),
        md("## 3 · How would we even know?\n\nBuild the nearness long-short, measure its return and "
           "t-stat, then **correlate it with a standard 12-2 momentum long-short** (trailing year, "
           "skipping the most recent month). High correlation means same factor; no positive return "
           "means no premium to begin with. One warning before reading any level: our panel is "
           "**today's index members with 20+ years of history** — survivors — and here that bias has "
           "teeth, because the short side holds beaten-down names we *know* came back. The correlation "
           "between the two hedges is the measurement that survives this; the minus sign is not."),
        code("h,m=st.stats(hi),st.stats(mo)\n"
             "fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['52-week-high\\nnearness','12-2\\nmomentum'],[h['mean_ann']*100,m['mean_ann']*100],color=['#c0392b','#8b949e'])\n"
             "ax.set_ylabel('long-short return (%/yr)'); ax.axhline(0,color='k',lw=.8)\n"
             "ax.set_title(f\"No premium on large caps; and they're {st.signal_overlap(ret):.2f} correlated\"); plt.show()"),
        md("## 4 · The teardown\n\nThe two hedges move together — because they *are* the same bet. The "
           "nearness book got crushed in the 2000 and 2008 rebounds — exactly when the survivor effect "
           "bites hardest, since the fallen names in our short leg are, by construction, the ones that "
           "came back."),
        code("eqH=(1+hi).cumprod(); eqM=(1+mo).cumprod()\n"
             "ax=eqH.plot(label='52-week-high nearness',lw=1.8); eqM.plot(ax=ax,label='12-2 momentum',lw=1.4,alpha=.8)\n"
             "ax.set_title('Growth of $1 in the long-short, 1996-2026 (they track each other; survivor panel)'); ax.legend(); plt.show()\n"
             "print(f\"correlation of the two hedges: {st.signal_overlap(ret):+.2f}\")"),
        md("**Read it plainly.** Two lines tracking each other, neither going anywhere good. The "
           "52-week-high signal isn't a new edge — it's momentum. And the 'it lost money' part should be "
           "read with the panel in mind: a universe of guaranteed survivors makes shorting fallen names "
           "look worse than it really was. What the panel *can't* fake is that there's no positive "
           "premium and no separate factor."),
        md("## 5 · The verdict\n\n**Signal: None** — no positive premium anywhere; the measured loss is "
           "partly the survivor panel's doing, but a manufactured-negative is still not a positive. "
           "**Tradability: Mirage** — nothing gross to keep, and one-way turnover digs. **A distinct "
           "anomaly?: Busted** — 0.82 correlated with standard 12-2 momentum, and that's the "
           "bias-insensitive number."),
        md("## 6 · Could you actually trade it?\n\nThere's nothing to trade: no positive gross hedge, "
           "and to the extent the signal captures anything, it's the momentum factor you could get more "
           "cleanly (and which also struggled here — see [Study 24 Stampede](../../24-stampede/))."),
        md("## 7 · Going further 🚪\n\nThe quants notebook shows the 0.82 correlation, the survivor-sign "
           "caveat and the decay. This closes the second five-study bench (46–50). The rebound mechanics "
           "behind the negative sign tie to [Study 33 Slingshot](../../33-slingshot/) — reversal on the "
           "S&P cross-section."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# High-Water — a quantitative teardown 🔬\n### The nearness hedge with a Lo t-stat · the 0.82 correlation to 12-2 momentum · the survivor-sign caveat · costs\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test "
           "whether the 52-week-high effect pays and whether it's distinct from momentum.\n\n"
           "> ⚠️ **Not investment advice.** 398 *current* S&P 500 names with ≥20y history (Yahoo), "
           "1996–2026 — a **survivor panel** (`fetch_panel` requires an explicit "
           "`allow_survivorship_bias=True`), and here the bias is load-bearing: the short leg holds "
           "fallen names guaranteed to have survived, so the hedge's negative *level* is partly an "
           "artifact. The momentum *correlation* is the bias-insensitive statistic. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | no positive premium; the measured −8.4%/yr (t −2.2) is partly the survivor panel's manufacture |\n"
           "| Tradability | **Mirage** | nothing gross to keep; one-way costs (3.2× NAV/mo) dig |\n"
           "| Distinct anomaly? | **Busted** | 0.82 correlated with standard 12-2 momentum — bias-robust |\n\n"
           "> 💡 *In plain words:* momentum relabelled, and no premium on top — the half of the verdict "
           "that doesn't depend on our flawed panel is the correlation, and it's damning enough."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** the nearness long-short earns a significant "
           "positive premium.\n- **H₂:** it is distinct from 12-2 momentum (low correlation).\n"
           "- **H₃:** it's stable over time.\n\n"
           "**Known bias, named up front:** current membership × a ≥20y-history filter = survivors. For "
           "H₂ (a correlation between two hedges run on the same panel) the bias is near-neutral; for "
           "H₁'s *level* it is not — it pushes the short-the-fallen book down, i.e. the hedge's sign "
           "toward negative."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, it's a new tradable factor. If H₂ "
           "fails, it's momentum with a story; if H₁ fails too, there's no premium at all."),
        md("## 3 · How we'd know — the protocol\n\nNearness long-short + Lo t-stat → correlation with the "
           "standard 12-2 momentum hedge (trailing year, skipping the most recent month) → decade split "
           "→ one-way cost sweep."),
        md("## 4 · The teardown"),
        md("### 4.1 The nearness hedge vs the 12-2 momentum control"),
        code("display(pd.DataFrame({'52-week-high':st.stats(hi),'12-2 momentum':st.stats(mo)}).T[['mean_ann','sharpe','tstat','hit_rate','n']].round(3))\n"
             "print(f\"corr(nearness hedge, 12-2 momentum hedge) = {st.signal_overlap(ret):+.2f}\")\n"
             "mo_naive = st.cross_section_hedge(ret, st.momentum(ret, skip=0))   # includes the last month\n"
             "import pandas as _pd\n"
             "print(f\"corr vs naive trailing-12 (incl. last month): \"\n"
             "      f\"{_pd.concat([hi.rename('h'),mo_naive.rename('m')],axis=1).dropna().corr().iloc[0,1]:+.2f}\")"),
        md("> 💡 *In plain words:* nearness shows no premium (−8.4%/yr, t −2.2 — read the sign with the "
           "survivor caveat) and is **0.82 correlated** with standard 12-2 momentum (0.87 against the "
           "naive trailing-12 — the redundancy doesn't hinge on the momentum convention). **H₁ rejected "
           "(no premium), H₂ rejected (same factor).**"),
        md("### 4.2 Decay"),
        code("for lab,sl in [('1996-2012',hi.loc[:'2012']),('2013-on',hi.loc['2013':])]:\n"
             "    print(f'{lab}: Sharpe {st.stats(sl)[\"sharpe\"]:+.2f}, mean {st.stats(sl)[\"mean_ann\"]:+.2%}/yr')"),
        md("> 💡 *In plain words:* strongly negative early — the 2000/2008 rebounds, where the survivor "
           "panel's guaranteed comebacks hit the short leg hardest — drifting to zero since. **H₃** — no "
           "stable positive regime anywhere."),
        md("### 4.3 Cost sweep — one-way, and a non-positive book only gets worse"),
        code("rows={'gross':st.stats(hi)['sharpe']}\n"
             "for c in (5,10,20): rows[f'{c}bp']=st.stats(st.net_of_cost(hi,c))['sharpe']\n"
             "display(pd.Series(rows, name='net Sharpe (one-way bp)').round(3))"),
        md("> 💡 *In plain words:* replacing ~80% of a two-sided book monthly is ~3.2× NAV of one-way "
           "trades; with nothing positive to start from, costs just compound the loss."),
        md("## 5 · The verdict\n\nH₁ rejected (no premium — the negative level partly panel-made, the "
           "absence of a positive one not), H₂ rejected (0.82 with momentum, bias-robust), H₃ rejected → "
           "Signal `NONE`, Tradability `MIRAGE`, distinct-anomaly claim `BUSTED`."),
        md("## 6 · Could you trade it?\n\nNo — and if you wanted the momentum exposure it proxies, you'd "
           "use momentum directly (cleaner, and itself fragile on large caps — Study 24 Stampede). The "
           "52-week-high label adds a narrative, not an edge."),
        md("## 7 · Going further\n\nForks: (a) a point-in-time universe — the single change that would "
           "let the hedge's *level* be read at face value (and the panel guard dropped); (b) double-sort "
           "nearness × momentum to confirm there's no residual; (c) the momentum-crash overlay "
           "(Daniel-Moskowitz 2016) on the near-high book. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
