"""Beat-7 worked complement on the real tape — the no-shorting test, and a robustness sweep.

The headline verdict flags exactly one place the anomaly *could* still pay a real-money investor: the
**long-only** low-vol book, which needs no borrow. So we isolate that slice on the real S&P 500 and ask
what it actually delivers — and, because a single (lookback, decile) choice could be a fluke, we sweep
a few sensible variants so the conclusion can't hinge on one knob.

    python examples/extension.py            # cache-only; uses the shared S&P 500 panel
    python examples/extension.py --fetch    # populate the panel cache first (network)

Writes `docs/extension.md`. Same survivorship caveat as the main run: current membership only.
"""

import argparse
import os
import sys

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from dull_roar import data, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")
VARIANTS = [
    (126, 0.10), (252, 0.10), (126, 0.20), (252, 0.20),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true", help="populate the S&P 500 panel cache (network)")
    args = ap.parse_args()

    rets = data.fetch_panel(fetch=args.fetch)
    if rets.empty:
        print("[skip] no cached S&P 500 panel -- run with --fetch first.")
        return
    rets = as_of(rets, DEFAULT_AS_OF)
    market = rets.mean(axis=1).rename("market")
    fp = fingerprint(rets.round(6))

    base_sd = extension.shorting_decomposition(rets, market=market)
    base_be = extension.borrow_breakeven(rets, market=market)
    base_tilt = decompose.beta_tilt_test(rets, market=market)

    rows = []
    for lb, dec in VARIANTS:
        sd = extension.shorting_decomposition(rets, market=market, lookback=lb, decile_frac=dec)
        cmp = strategy.compare(rets, market=market, lookback=lb, decile_frac=dec)
        be = extension.borrow_breakeven(rets, market=market, lookback=lb, decile_frac=dec)
        rows.append((lb, dec, cmp, sd, be))
        print(f"lookback {lb}, decile {dec:.0%}: long-only SR gain {cmp['low_minus_market_sharpe']:+.2f}, "
              f"defensive alpha {sd['alpha_defensive']:+.1f}% (t{sd['alpha_defensive_t']:+.1f}), "
              f"breakeven {be['breakeven_bps']:.0f}bps")

    _write(OUT, base_sd, base_be, base_tilt, rows, fp, DEFAULT_AS_OF,
           market.index.min().date(), market.index.max().date(), rets.shape[1], len(rets))
    print(f"\nwrote {OUT}")


def _write(path, sd, be, tilt, rows, fp, asof, lo, hi, n_stocks, n_days):
    var_rows = "\n".join(
        f"| {lb} | {dec:.0%} | {c['low_minus_market_sharpe']:+.2f} | {s['alpha_defensive']:+.1f}% "
        f"({s['alpha_defensive_t']:+.1f}) | {b['breakeven_bps']:.0f} |"
        for (lb, dec, c, s, b) in rows
    )
    text = f"""# Beat 7 — worked complement: the no-shorting test (Study 18, Dull-Roar)

*Generated by [`examples/extension.py`](../examples/extension.py) on the current S&P 500 cross-section.
As-of **{asof}**, {n_stocks} names, {n_days} sessions, fingerprint `{fp}`. Survivorship caveat as in
[`results.md`](results.md): current membership only.*

## The one thing a real-money investor could keep

The clean, beta-neutral anomaly needs shorting the high-vol decile — the names you can't cheaply
borrow. Strip the short away and you're left with the **long-only** low-vol book. On this tape that
slice is honest but thin:

- Long-only low-vol **beta {tilt['low_beta']:.2f}** — it simply runs less market risk.
- Its CAPM alpha is **{sd['alpha_defensive']:+.1f}%/yr** (HAC *t* = {sd['alpha_defensive_t']:+.1f}) —
  not distinguishable from zero.
- Levered back to beta 1 (matched market risk) it adds **{tilt['excess_cagr_at_beta1_pct']:+.1f}%/yr**
  excess CAGR — a number that lives inside its own confidence interval.
- The one durable benefit is the ride, not the return: max drawdown
  **{sd['market_maxdd']:.0%} → {sd['low_only_maxdd']:.0%}** (market → low-vol). Defensive equity does
  what it says — shallower crashes — which is exactly what the real min-vol products (USMV, SPLV) sell.
- The dollar-neutral book's borrow break-even is **{be['breakeven_bps']:.0f} bps/yr**: it is under
  water before the short even costs anything.

## It isn't one unlucky knob

Sweeping the lookback and the decile width, the verdict holds across the board — no setting resurrects
a tradable spread:

| lookback (d) | decile | long-only Sharpe gain | defensive alpha (t) | borrow break-even (bps) |
|---|---|---|---|---|
{var_rows}

**Takeaway.** The most-cited anomaly in finance, on the modern large-cap tape, reduces to a
*defensive tilt*: lower beta, shallower drawdowns, no free alpha — and its textbook long-short form is
fragile to exactly the short-leg borrow it can't avoid. `WEAK` / `MIRAGE` / `BETA-TILT` survives the
worked complement; if anything, the complement is what *earns* it.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
