"""Beat-7 worked complement on the real tape — does covariance shrinkage rescue the optimizer?

Shrinking the noisy sample covariance toward its diagonal (Ledoit-Wolf) is the textbook fix for an
unstable inverse. This script sweeps the shrinkage intensity on the real S&P 500 and asks whether the
optimizer ever beats the naive book — writing `docs/extension.md`.

    python examples/extension.py            # cache-only
    python examples/extension.py --fetch
"""

import argparse
import os
import sys

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from sand_castle import data, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")
COST_BPS = 5.0


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    rets = data.fetch_panel(fetch=args.fetch)
    if rets.empty:
        print("[skip] no cached S&P 500 panel -- run with --fetch first."); return
    rets = as_of(rets, DEFAULT_AS_OF)
    fp = fingerprint(rets.round(6))
    sw = extension.shrink_sweep(rets, cost_bps=COST_BPS)
    print(sw.round(3).to_string())
    _write(OUT, sw, fp, DEFAULT_AS_OF, rets.index.min().date(), rets.index.max().date(), rets.shape[1])
    print(f"\nwrote {OUT}")


def _write(path, sw, fp, asof, lo, hi, n_stocks):
    rows = "\n".join(f"| {k:.1f} | {r['optimized_net_sharpe']:+.2f} | {r['naive_net_sharpe']:+.2f} |"
                     for k, r in sw.iterrows())
    naive = float(sw["naive_net_sharpe"].iloc[0])
    best_opt = float(sw["optimized_net_sharpe"].max())
    text = f"""# Beat 7 — worked complement: does shrinkage rescue the optimizer? (Study 26, Sand-Castle)

*Generated by [`examples/extension.py`](../examples/extension.py) on the current S&P 500
({n_stocks} names). As-of **{asof}**, {lo} → {hi}, fingerprint `{fp}`.*

## The textbook fix, and why it isn't enough

The standard cure for an unstable ``C^{{-1}}`` is **shrinkage** (Ledoit & Wolf 2004): blend the noisy
sample covariance toward a stable target — here its diagonal — before inverting. It tames the extreme
weights, so the fair question is whether it finally lets the optimizer beat the naive signal-weighted
book.

| shrink | optimized net Sharpe | naive net Sharpe |
|---|---|---|
{rows}

The optimizer's net Sharpe climbs as shrinkage rises — from the raw inverse toward the naive line — but
its best (**{best_opt:+.2f}**) never decisively clears the naive book (**{naive:+.2f}**), and at full
shrink the two **converge by construction**: a diagonal covariance makes ``C^{{-1}}E`` proportional to
``E``, i.e. the naive portfolio. So shrinkage's gift is to make the optimizer behave *more like not
optimizing*.

**Takeaway.** `REAL` / `MIRAGE` / `Busted` survives the worked complement. The reversion signal is real;
the mean-variance machinery wrapped around it is a sand castle. The best thing covariance optimization
can do for a daily, ill-conditioned stat-arb book is get out of the way — and even then, the daily
turnover cost leaves the whole thing under water.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
