"""Real-data run — is the stat-arb reversion real, and does optimizing the portfolio help or hurt?

Three questions (the offline core proves the machine; this points it at the market):

  * **Is the reversion real?** The cross-sectional information coefficient and the *gross* Sharpe of the
    book — a stretched residual really does bounce.
  * **Does it survive cost?** Net Sharpe after daily-turnover cost.
  * **Does the optimization help?** Optimized (``C^{-1}E``) vs naive (``E``) net Sharpe, the sample
    covariance's condition number, and the in-sample-vs-causal overfit gap.

    python examples/verify.py --fetch     # populate the S&P 500 panel cache (network)
    python examples/verify.py             # offline, cache-only

Network only behind `--fetch`. Pinned with `quantlab.repro.as_of` and fingerprinted. Total-return closes;
current S&P 500 membership, capped to the longest histories so the sample covariance is estimable.
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from sand_castle import data, statarb, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "results.md")
COST_BPS = 5.0


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    rets = data.fetch_panel(fetch=args.fetch)
    if rets.empty:
        print("[skip] no cached S&P 500 panel -- run with --fetch first."); return
    rets = as_of(rets, DEFAULT_AS_OF)
    fp = fingerprint(rets.round(6))

    sq = statarb.signal_quality(rets)
    ov = decompose.optimizer_vs_naive(rets, cost_bps=COST_BPS)
    wi = decompose.weight_instability(rets)
    gv = decompose.gross_vs_net(rets, cost_bps=COST_BPS)
    sw = extension.shrink_sweep(rets, cost_bps=COST_BPS)

    print(f"IC {sq['mean_ic']:+.3f} (t{sq['ic_t']:+.1f}); opt gross {ov['optimized_gross_sharpe']:+.2f} "
          f"-> net {ov['optimized_net_sharpe']:+.2f}; naive net {ov['naive_net_sharpe']:+.2f}; cond# {wi['condition_number']:.1e}")
    _write(OUT, dict(sq=sq, ov=ov, wi=wi, gv=gv, sw=sw, fp=fp,
                     lo=rets.index.min().date(), hi=rets.index.max().date(),
                     n_stocks=rets.shape[1], n_days=len(rets)), DEFAULT_AS_OF)
    print(f"\nwrote {OUT}")


def _verdict(d):
    ov, sq = d["ov"], d["sq"]
    signal = "REAL" if (sq["mean_ic"] > 0 and ov["optimized_gross_sharpe"] > 0) else "WEAK"
    trad = "MIRAGE" if ov["optimized_net_sharpe"] <= 0 else "FRAGILE"
    helps = "Confirmed" if ov["opt_minus_naive_net"] > 0 else "Busted"
    return signal, trad, helps


def _write(path, d, asof):
    signal, trad, helps = _verdict(d)
    ov, wi, gv, sw, sq = d["ov"], d["wi"], d["gv"], d["sw"], d["sq"]
    shr = "\n".join(f"| {k:.1f} | {r['optimized_net_sharpe']:+.2f} | {r['naive_net_sharpe']:+.2f} |"
                    for k, r in sw.iterrows())
    text = f"""# Results — Study 26 (Sand-Castle) on the real S&P 500 cross-section

*Generated by [`examples/verify.py`](../examples/verify.py). Daily total-return closes for {d['n_stocks']}
S&P 500 names (the longest histories, so the sample covariance is estimable); the strategy is a daily,
causal residual mean-reversion book, weighted either by mean-variance optimization (``w ∝ C^{{-1}}E``) or
naively (``w ∝ E``), {COST_BPS:.0f} bp per unit traded. The offline core proves the machinery on a
synthetic mean-reverting panel; this is the measurement on the market. As-of **{asof}**; match the
fingerprint below. Survivorship caveat as elsewhere.*

## The verdict, earned — Signal `{signal}` · Tradability `{trad}` · Does optimization help? `{helps}`

The reversion is **real**: a stretched-up residual does bounce (cross-sectional IC
**{sq['mean_ic']:+.3f}**, *t* = **{sq['ic_t']:+.1f}**), and *gross* of cost the optimized book earns a
Sharpe of **{ov['optimized_gross_sharpe']:+.2f}**. But the portfolio is a **sand castle**. Two things wash
it away. First, it trades **every day** (~{ov['optimized_turnover']:.0f}×/yr turnover), so net of a
realistic cost the Sharpe is **{ov['optimized_net_sharpe']:+.2f}** — deeply under water. Second, the
*optimization itself backfires*: the sample covariance is near-singular (condition number
**{wi['condition_number']:.1e}**), so ``C^{{-1}}`` amplifies estimation noise, and the optimized book
(net **{ov['optimized_net_sharpe']:+.2f}**) is **worse** than the naive signal-weighted book (net
**{ov['naive_net_sharpe']:+.2f}**) — Michaud's "optimization is error-maximization", measured. The gross
Sharpe (**{gv['gross_sharpe']:+.2f}**) a costless backtest would show is the sand castle; the cost of
building it daily (**{gv['cost_gap']:+.2f}** of Sharpe) washes it away.

## Data stamp

- **Universe**: {d['n_stocks']} names, {d['lo']} → {d['hi']}, {d['n_days']} sessions, fingerprint `{d['fp']}`

## The reversion is real (gross), the cost kills it (net)

| book | gross Sharpe | net Sharpe | turnover |
|---|---|---|---|
| optimized (``C⁻¹E``) | {ov['optimized_gross_sharpe']:+.2f} | {ov['optimized_net_sharpe']:+.2f} | {ov['optimized_turnover']:.0f}×/yr |
| naive (``E``) | {ov['naive_gross_sharpe']:+.2f} | {ov['naive_net_sharpe']:+.2f} | {ov['naive_turnover']:.0f}×/yr |

Cross-sectional information coefficient **{sq['mean_ic']:+.3f}** (*t* = **{sq['ic_t']:+.1f}**) — a small
but real daily reversal. Gross, it's an edge; net of ~{ov['optimized_turnover']:.0f}×/yr turnover, it's gone.

## The optimization is the problem

- **Ill-conditioned covariance**: condition number **{wi['condition_number']:.1e}** — the sample ``C``
  is effectively singular, so its inverse is dominated by noise.
- **Optimized minus naive (net Sharpe): {ov['opt_minus_naive_net']:+.2f}** — inverting ``C`` makes the
  book *worse*, not better.
- **Gross vs net**: the costless backtest shows **{gv['gross_sharpe']:+.2f}**; net of the daily turnover
  it is **{gv['net_sharpe']:+.2f}** — a sand castle, washed away by the cost of building it.

## Does shrinking the covariance rescue it? (beat-7 preview)

Optimized net Sharpe across covariance-shrinkage intensities, vs the naive book:

| shrink | optimized net Sharpe | naive net Sharpe |
|---|---|---|
{shr}

Shrinkage helps the optimizer climb back *toward* the naive book — and at full shrink the two converge
(a diagonal ``C`` makes ``C^{{-1}}E ∝ E``). The best the optimization can do is stop optimizing. Signal
`{signal}`, Tradability `{trad}`, Does optimization help? `{helps}`.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
