# Study 807 — Salience-Theory Returns ✨📉

**Do stocks whose recent *salient* days were UP go on to earn *less*?**

Cosemans & Frehen (2021), applying the **Bordalo-Gennaioli-Shleifer salience** model, argue
that investors over-weight a stock's most **salient** (attention-grabbing) days. Over the
trailing month each day's salience versus the market is
`σ = |rᵢ−rₘ| / (|rᵢ|+|rₘ|+θ)`, θ=0.1; the days are ranked and given declining decision
weights `δ^rank` (δ≈0.7); the **salience-theory value** `ST` is the salience-weighted mean of
market-excess returns. A **high** ST — the salient days were *up* — marks an over-priced name
that should **under-earn**, so a long **low-ST** / short **high-ST** book should earn a
positive spread. We take the self-contained daily version on a liquid US cross-section
(2010-01-04 → 2026-06-30, 50 names).

*Numbers below are the frozen headline (`docs/results.md`); the live cells run the fast
synthetic control. Survivorship: current-membership mega-caps — magnitudes are an upper
bound.*


## 1. The idea in one picture

Salience theory says a few big, attention-grabbing days do the thinking for us. If a stock's most *salient* recent days were **up** (versus the market), salience-loving investors over-value it — so its *future* return should be lower. Rank each name's month by day-salience, over-weight the salient days, and measure whether they were up or down: buy the low-ST names, sell the high-ST ones.

In [1]:
import numpy as np, pandas as pd
R = dict(spread_bps=-1.0, t_nw=-0.78, lo_bps=7.49, hi_bps=8.49, gross_sharpe=-0.18)
print('long low-ST / short high-ST spread: %+.2f bps/day (NW t = %+.2f)'
      % (R['spread_bps'], R['t_nw']))
print('  low-ST book %+.2f bps vs high-ST book %+.2f bps'
      % (R['lo_bps'], R['hi_bps']))
print('  gross spread Sharpe (before cost): %.2f' % R['gross_sharpe'])

long low-ST / short high-ST spread: -1.00 bps/day (NW t = -0.78)
  low-ST book +7.49 bps vs high-ST book +8.49 bps
  gross spread Sharpe (before cost): -0.18


## 2. Is the machinery honest? A live synthetic control

We plant the effect in a seeded toy world (`edge>0`) and check the detector recovers it — and that it stays *silent* on the null (`edge=0`, salience present but unpriced). No network.

In [2]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from salience_theory import data, strategy as st
null = st.synthetic_detect(data.synthetic_panel(edge=0.0, seed=807, n_assets=40, n_days=1200))
planted = st.synthetic_detect(data.synthetic_panel(edge=0.0016, seed=807, n_assets=40, n_days=1500))
print('null world   : spread NW t = %+.2f  (should be ~0)' % null['t_nw'])
print('planted world: spread NW t = %+.2f  (should light up)' % planted['t_nw'])

null world   : spread NW t = +0.84  (should be ~0)
planted world: spread NW t = +4.31  (should light up)


## 3. The honest verdict — the edge does *not* show up here

On this liquid mega-cap tape the long-low-ST / short-high-ST spread is **-1.00 bps/day** with NW *t* = **-0.78** — statistically **indistinguishable from zero**. The low-ST book (+7.49 bps) and the high-ST book (+8.49 bps) earn essentially the same; the permutation null centres at zero (sd 0.90 bps) and the observed value sits a mere ~1.1σ away (p = 0.87). The seeded synthetic control recovers a *planted* salience relation cleanly, so the flat real-tape result is a genuine null, not a broken detector — the Cosemans-Frehen premium is documented on the *broad* cross-section (including small, illiquid names) and simply does not appear on 50 mega-caps. **Signal: None**, and after costs **Tradability: Mirage**.