"""Build the two narrative notebooks for Study 41 (Hangover).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Same seven desk beats at two altitudes; figures inline from the cached real run
(_cache/hangover_sp500_monthly.parquet, built by examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (hangover/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from hangover import data, strategy as st
ret = data.fetch_index()              # cache-first; built by examples/verify.py --fetch
tbl = st.annual_table(ret)
cm  = st.conditional_means(tbl)
bar, bh = st.barometer_returns(tbl), st.buy_hold_roy(tbl)
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Predicts the year?: Not supported](https://img.shields.io/badge/Predicts_the_year%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Hangover 🥂\n### \"As goes January, so goes the year\" — does the omen actually know anything?\n\n"
           + VERDICT +
           "Wall Street's oldest calendar superstition says a green January means a bullish year. The "
           "headline sounds airtight — *up 87% of the time after an up January!* — but the rest of the "
           "year is up most of the time **no matter what January did**. We check whether the omen beats "
           "simply betting \"stocks go up\".\n\n"
           "> 📓 **Plain-language layer.** The base-rate maths and the decay are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The pitch | The catch |\n|---|---|\n"
           "| \"Up 87% of the time after an up January\" | The rest of the year is up **76% of the time anyway**. |\n"
           "| \"January predicts the year\" | Its accuracy (**68%**) is **worse** than always saying \"up\" (76%). |\n"
           "| \"So trade the omen\" | Going to cash after a down January just **holds less stock** — not timing. |"),
        md("## 1 · The claim\n\nYale Hirsch, 1972: if the S&P 500 rises in January, the remaining eleven "
           "months are bullish; if January is red, watch out. Quoted every February on financial TV."),
        md("## 2 · So what?\n\nIf a single month genuinely forecasts the next eleven, that's a free "
           "market-timing signal anyone can run. If it's a statistical mirage dressed up by the fact that "
           "markets mostly rise, then millions anchor each year on noise."),
        md("## 3 · How would we even know?\n\nThe trap is the **base rate**. \"Up 87% after an up "
           "January\" means nothing unless you compare it to how often the year is up *regardless*. So we "
           "score the omen's **directional accuracy** against the base rate of always predicting \"up\", "
           "on the S&P 500 back to 1950."),
        code("ax = cm[['roy_mean']].mul(100).plot.bar(legend=False, rot=0,\n"
             "        title='Rest-of-year return by what January did')\n"
             "ax.set_ylabel('mean rest-of-year return (%)'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print('P(rest-of-year up):', {k: round(cm.loc[k,'p_up'],3) for k in cm.index})"),
        md("## 4 · The teardown\n\nThe rest of the year is positive after an up January **and** after a "
           "down one. The only real difference is *how* positive."),
        code("acc, base = st.barometer_accuracy(tbl), st.base_rate(tbl)\n"
             "print(f'Barometer directional accuracy: {acc:.1%}')\n"
             "print(f'Always predict \"up\" base rate:  {base:.1%}')\n"
             "print('The omen is %s the constant.' % ('BEATEN BY' if acc < base else 'better than'))"),
        code("eq_bar=(1+bar).cumprod(); eq_bh=(1+bh).cumprod()\n"
             "ax=eq_bh.plot(label='Buy & hold (Feb-Dec)',lw=1.6)\n"
             "eq_bar.plot(ax=ax,label='Barometer (cash if Jan down)',lw=1.8)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, rest-of-year only'); ax.set_ylabel('growth of $1'); ax.legend(); plt.show()"),
        md("## 5 · The verdict\n\n**Signal: Weak** — a down January does flag a softer year, faintly. "
           "**Tradability: Mirage** — \"trading\" it just means owning less stock that year. **Predicts "
           "the year?: Not supported** — as a forecaster it loses to a constant."),
        md("## 6 · Could you actually trade it?\n\nYou could (one decision a year, trivial), but you "
           "shouldn't expect timing: the cash-after-down-January rule gives up return for less risk "
           "purely by being out of the market — exactly what holding a smaller equity weight does, minus "
           "the suspense."),
        md("## 7 · Going further 🚪\n\nThe quants notebook splits 1950–1972 vs 1973-on (the omen faded "
           "after Hirsch named it) and shows why the exposure-reduction \"edge\" isn't one. Next on the "
           "calendar-anomaly bench: [Study 42 Last-Call](../../42-last-call/) — the turn-of-the-month effect, "
           "which is *real* but too small to trade."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Hangover — a quantitative teardown 🔬\n### Base-rate vs conditional accuracy · the only informative cell · the exposure illusion · post-publication decay\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We score the "
           "January Barometer the only honest way — against the base rate — on the S&P 500, 1950–2025.\n\n"
           "> ⚠️ **Not investment advice.** S&P 500 (^GSPC) monthly TR (Yahoo, daily→month-end), "
           "1950–2025. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | only the down-January cell informs (+2% vs +12%) |\n"
           "| Tradability | **Mirage** | the rule just cuts equity exposure once a year |\n"
           "| Predicts the year? | **Not supported** | 68% accuracy < 76% always-up base rate |\n\n"
           "> 💡 *In plain words:* the omen's famous hit-rate is the market's hit-rate; it adds almost nothing."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** rest-of-year mean and P(up) differ by the sign of January.\n"
           "- **H₂ (the pitch):** sign(January) predicts sign(rest-of-year) better than the base rate.\n"
           "- **H₃:** trading the omen beats simply holding the index."),
        md("## 2 · So what? — what rides on each\n\nIf H₂ holds, one month forecasts eleven — a free "
           "timing signal. If only a weak H₁ holds, it's a decayed seasonal tic mistaken for a forecast."),
        md("## 3 · How we'd know — the protocol\n\nCollapse months → yearly (Jan, rest-of-year) → "
           "conditional means & P(up) → **directional accuracy vs base rate** → tradable cash-after-down "
           "rule vs buy-and-hold → pre/post-1972 decay split."),
        md("## 4 · The teardown"),
        md("### 4.1 Conditional means and the base rate"),
        code("display(cm.round(4))\n"
             "print(f\"base rate P(up) = {st.base_rate(tbl):.1%}; accuracy = {st.barometer_accuracy(tbl):.1%}\")"),
        md("> 💡 *In plain words:* after a down January the year still averages **+2%** and is up **60%** "
           "of the time. The 'bad omen' is barely bad."),
        md("### 4.2 The base-rate illusion, quantified"),
        code("acc, base = st.barometer_accuracy(tbl), st.base_rate(tbl)\n"
             "fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['Barometer\\n(sign of Jan)','Always predict\\n\"up\"'],[acc*100,base*100],color=['#c0392b','#2ea44f'])\n"
             "ax.set_ylabel('directional accuracy (%)'); ax.set_title('A forecaster that loses to a constant'); ax.axhline(50,color='k',lw=.6,ls='--'); plt.show()"),
        md("> 💡 *In plain words:* if your predictor is beaten by a sticky note that says \"up\", it isn't a predictor. **H₂ rejected.**"),
        md("### 4.3 The tradable version — it just holds less stock"),
        code("rows={'Buy & hold (Feb-Dec)':st.summary(bh),'Barometer (cash if Jan down)':st.summary(bar)}\n"
             "display(pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown','hit_rate']].round(3))\n"
             "yrs_in_cash=int((tbl['jan']<=0).sum()); print(f'years the rule sits in cash: {yrs_in_cash}/{len(tbl)}')"),
        md("> 💡 *In plain words:* higher Sharpe, lower drawdown — bought entirely by being out of the "
           "market ~40% of down-January years. A permanently lower equity weight does the same. **H₃ rejected.**"),
        md("### 4.4 Post-publication decay"),
        code("for lab,sl in [('1950-1972',tbl[tbl.index<=1972]),('1973-on',tbl[tbl.index>1972])]:\n"
             "    s=sl; print(f'{lab}: accuracy {st.barometer_accuracy(s):.1%}, jan-down rest-of-year {s[s.jan<=0][\"roy\"].mean():+.2%}')"),
        md("> 💡 *In plain words:* sharpest before Hirsch named it (a down January once preceded a flat "
           "year), faded after — the McLean–Pontiff fade."),
        md("## 5 · The verdict\n\nH₁ weakly holds, H₂ and H₃ rejected → Signal `WEAK`, Tradability "
           "`MIRAGE`, the year-ahead claim `NOT SUPPORTED`."),
        md("## 6 · Could you trade it?\n\nOnly as a once-a-year de-risking switch — which is not timing, "
           "and is dominated by simply choosing your equity weight on purpose."),
        md("## 7 · Going further\n\nForks: (a) the \"Other January Effect\" (Cooper et al. 2006) on a "
           "size cross-section; (b) condition on January *magnitude* not just sign; (c) multiple-testing "
           "correction across all twelve \"X-month barometers\" — the calendar is full of them. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
