"""Build the two narrative notebooks for Study 57 (Yield-Trap).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/yield_trap_pairs.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (yield_trap/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from yield_trap import data, strategy as st
ret = data.fetch_pairs()                       # cache-first
sp = st.spread(ret, "VYM", "SPY")
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![High-dividend tilt beats?: Busted](https://img.shields.io/badge/High--dividend_tilt_beats%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Yield-Trap 🪤\n### \"Buy high-dividend stocks for better returns\" — an accounting illusion\n\n"
           + VERDICT +
           "Income investors love high-dividend stocks — steady cash, a 'safer' way to own equities. On a "
           "total-return basis it's a trap: a high-dividend ETF trailed the plain market on both return "
           "and Sharpe over two decades. A dividend is just your own money handed back; it isn't a premium.\n\n"
           "> 📓 **Plain-language layer.** The numbers and the why are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The belief | The total-return data (2007–2026) |\n|---|---|\n"
           "| \"High dividends → better returns\" | VYM **+9.3%/yr** vs SPY **+10.8%**. |\n"
           "| \"…and lower risk\" | Lower Sharpe (0.67 vs 0.76), *deeper* drawdown. |\n"
           "| \"Income is a free lunch\" | A dividend is just selling shares for you. |"),
        md("## 1 · The claim\n\nThe popular wisdom: tilt to high-dividend-yield stocks for superior, "
           "income-rich returns — 'dividend aristocrats', 'get paid to wait'. Tested on total return "
           "(dividends reinvested), VYM vs SPY."),
        md("## 2 · So what?\n\nMillions of income investors overweight dividends on the belief it beats "
           "the market. If it doesn't — if it's just a sector bet with a comforting story — that's a "
           "widespread, costly misconception worth puncturing."),
        md("## 3 · How would we even know?\n\nCompare the high-dividend ETF to the market on **total "
           "return** — the only fair basis — leg by leg (CAGR, Sharpe, drawdown) and as a spread."),
        code("v,m=st.leg_summary(ret,'VYM'),st.leg_summary(ret,'SPY')\n"
             "import pandas as pd\n"
             "display(pd.DataFrame({'VYM (high div)':v,'SPY (market)':m}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "eqV=(1+ret['VYM'].dropna()).cumprod(); eqS=(1+ret['SPY'].dropna()).cumprod()\n"
             "ax=eqS.plot(label='SPY (market)',lw=1.6); eqV.plot(ax=ax,label='VYM (high dividend)',lw=1.6)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, total return, 2007-2026'); ax.legend(); plt.show()"),
        md("## 4 · The teardown\n\nThe high-dividend line sits *below* the market — less wealth, lower "
           "Sharpe, no extra safety. The 'income' was never extra money."),
        code("s=st.spread_stats(sp); print(f\"spread VYM-SPY: {s['mean_ann']:+.2%}/yr, Sharpe {s['sharpe']:.2f}, t {s['tstat']:.2f}, hit {s['hit_rate']:.0%}\")"),
        md("**Read it plainly.** Higher yield bought lower total return. The dividend tilt is really a bet "
           "on banks, utilities and energy — the sectors that lagged the growth-led market."),
        md("## 5 · The verdict\n\n**Signal: None** — high-div trailed on return and Sharpe. **Tradability: "
           "Mirage** — deeper drawdown too. **High-dividend tilt beats?: Busted.**"),
        md("## 6 · Could you actually trade it?\n\nYou can buy VYM cheaply — but you'd own a value/sector "
           "tilt, not a premium, and you'd have trailed a plain index fund. If you want income from an "
           "index, sell a few shares: a 'home-made dividend' with no tilt and no story."),
        md("## 7 · Going further 🚪\n\nContrast with the *real* fundamental edges on the bench — "
           "[51 Blue-Chip](../../51-blue-chip/) (quality) and [52 Smoke-Screen](../../52-smoke-screen/) "
           "(accruals) — which point the right way, unlike the dividend tilt."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Yield-Trap — a quantitative teardown 🔬\n### Leg-by-leg total return · the spread t-stat · the value/sector explanation\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We show the "
           "high-dividend tilt trailed the market on total return.\n\n"
           "> ⚠️ **Not investment advice.** VYM vs SPY, monthly total return (Yahoo), 2007–2026. Sources "
           "in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | VYM Sharpe 0.67 < SPY 0.76; spread −1.5%/yr |\n"
           "| Tradability | **Mirage** | lower return, deeper drawdown |\n"
           "| Tilt beats? | **Busted** | payout form ≠ premium (Miller-Modigliani) |\n\n"
           "> 💡 *In plain words:* a sector bet wearing an income halo."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** high-dividend total return beats the market.\n"
           "- **H₂:** it does so risk-adjusted (higher Sharpe / lower drawdown).\n- **H₃:** the spread is positive."),
        md("## 2 · So what? — what rides on each\n\nIf any hold, the income tilt is justified. If none do, "
           "it's a costly behavioural preference for the *form* of returns."),
        md("## 3 · How we'd know — the protocol\n\nLeg CAGR/Sharpe/drawdown → the spread and its Lo t-stat."),
        md("## 4 · The teardown"),
        md("### 4.1 The two legs"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'VYM':st.leg_summary(ret,'VYM'),'SPY':st.leg_summary(ret,'SPY')}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))"),
        md("> 💡 *In plain words:* VYM trails on CAGR *and* Sharpe, with a deeper drawdown. **H₁, H₂ rejected.**"),
        md("### 4.2 The spread"),
        code("print({k:round(v,3) for k,v in st.spread_stats(sp).items()})"),
        md("> 💡 *In plain words:* −1.5%/yr, negative more than half the months. **H₃ rejected.**"),
        md("### 4.3 Why — dividends are payout form, not a premium"),
        md("Miller-Modigliani (1961): payout policy doesn't create value. A high yield changes the *form* "
           "of return (cash vs capital gain), not the amount — and a total-return investor is indifferent. "
           "The high-yield *screen*, meanwhile, loads on mature value sectors (banks, utilities, energy) "
           "that lagged the tech-led 2007–2026 market. A sector bet, not an edge."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all rejected → Signal `NONE`, Tradability `MIRAGE`, the tilt "
           "`BUSTED`."),
        md("## 6 · Could you trade it?\n\nNo edge. For index income, a 'home-made dividend' (selling "
           "shares) gives the same cash without the value/sector tilt or the yield-trap risk."),
        md("## 7 · Going further\n\nForks: (a) dividend *growth* (aristocrats) vs high *yield* — the "
           "former is a quality proxy; (b) sector-neutralise the yield screen — does anything survive? "
           "(c) after-tax comparison (dividends are tax-disadvantaged for many). Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
