"""Build the two narrative notebooks for Study 98 (High-Noon).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``high_noon`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=8400, start="1993-01-29", end="2026-06-12", fp="eb1569cc9e97",
    near_pct=1, frac_at=29.0,
    # forward-return differences (at - not-at), HAC t
    d1=-0.42, t1=-1.34, d3=-0.31, t3=-0.36, d12=1.44, t12=0.38,
    # win-rates
    w12_at=84.6, w12_not=80.5, w1_at=65.4, w1_not=65.9, w3_at=76.1, w3_not=69.9,
    # avoid-highs timer vs buy-and-hold
    t_cagr=9.12, t_vol=17.8, t_sharpe=0.580, t_dd=-54.7, t_tim=71, t_sw=641,
    b_cagr=10.82, b_vol=18.6, b_sharpe=0.646, b_dd=-55.2,
    cagr_gap=-1.70, sharpe_gap=-0.066, wealth_ratio=0.60,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (high_noon/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from high_noon import data, strategy

AS_OF = "2026-06-12"
NEAR_PCT = 0.01
M = strategy.MONTH
frame = data.load_real("SPY", mode="total_return").loc[:AS_OF]
close = frame["close"]
flag = strategy.at_ath(close, NEAR_PCT)
print(f"SPY total return: {len(close):,} rows  {close.index[0].date()} -> {close.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(f"days within 1% of the running all-time high: {flag.mean()*100:.1f}%")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![ATH a sell signal?: Busted](https://img.shields.io/badge/ATH_a_sell_signal%3F-Busted-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# High Noon 🏔️\n"
            "### Is buying at an all-time high really the riskiest moment?\n\n"
            + HERO_BADGES +
            "Every time an index prints a record, someone says *\"don't buy the high — wait for a "
            "pullback.\"* We take the rule literally: we look at every day SPY sat within 1% of its "
            "all-time high and ask what happened *next* — over the following month, quarter and year — "
            "versus the days it was **not** near a high. The answer is the opposite of the folklore.\n\n"
            "> 📓 **This is the plain-language layer.** The HAC *t*-stats, the Wilson intervals and the "
            "backtest are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below is "
            "generated by the code beside it. House style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            "| Question | Answer |\n|---|---|\n"
            f"| Are returns *worse* after an all-time high? | **No** — over the next year the high day "
            f"actually does a touch *better* (**+{R['d12']:.1f} points** on average). |\n"
            f"| Is a record a 'sell signal'? | **No** — a year out, **{R['w12_at']}%** of at-high days "
            f"were higher vs **{R['w12_not']}%** of off-high days. |\n"
            f"| Does *waiting for a pullback* pay? | **No** — sitting out the highs earns "
            f"**{abs(R['cagr_gap']):.1f} points/yr less** and leaves you with **{R['wealth_ratio']}x** the "
            f"money, with no less drawdown. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Never buy at an all-time high — it's the riskiest moment, a classic sell signal. Wait for "
            "a pullback.\"* The instinct is that a record means 'expensive', 'overbought', 'due to fall' — "
            "so buying there is buying the top."
        ),
        md(
            "## 2 · So what?\n\n"
            "If it were true, the discipline would be obvious: never add at a record, always wait for a "
            "dip. Whole investing habits are built on this fear. So it's worth checking whether the data "
            "agrees — or whether a generation of investors talked themselves out of the best days."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We flag every day SPY closed within **1%** of its running all-time high, then measure the "
            "**forward 1-, 3- and 12-month return** of those days and compare them to the days that were "
            "*not* near a high. If the folklore is right, the at-high days should show clearly **worse** "
            "forward returns. If they don't, the rule is busted."
        ),
        md("## 4 · The teardown — what actually happens after a record\n\nFirst, the average forward return, at-high vs off-high, at each horizon."),
        code(
            "rows = []\n"
            "for h, lab in [(M, '1-month'), (3*M, '3-month'), (12*M, '12-month')]:\n"
            "    s = strategy.conditional_forward_stats(close, h, NEAR_PCT)\n"
            "    rows.append((lab, s['at']['mean']*100, s['not_at']['mean']*100))\n"
            "labs = [r[0] for r in rows]; xs = np.arange(len(labs)); w=0.38\n"
            "plt.bar(xs-w/2, [r[1] for r in rows], w, label='bought AT an all-time high')\n"
            "plt.bar(xs+w/2, [r[2] for r in rows], w, label='bought NOT near a high')\n"
            "plt.xticks(xs, labs); plt.ylabel('average forward return %'); plt.legend()\n"
            "plt.title('Forward return after buying SPY — at a high vs not'); plt.show()\n"
            "for lab, a, n in rows: print(f'{lab:>9}:  at-high {a:+6.2f}%   off-high {n:+6.2f}%   diff {a-n:+5.2f} pts')"
        ),
        md(
            "The bars are basically the same height — and at **12 months** the all-time-high bar is "
            "*taller*. Buying the record did not hurt you; over a year it helped a little. Highs happen "
            "in uptrends, and uptrends tend to continue."
        ),
        md("Now the **win-rate** — how often were you simply *up* a year later?"),
        code(
            "s12 = strategy.conditional_forward_stats(close, 12*M, NEAR_PCT)\n"
            "at, no = s12['at'], s12['not_at']\n"
            "plt.bar(['at a high','not near a high'], [at['win_rate']*100, no['win_rate']*100],\n"
            "        yerr=[[(at['win_rate']-at['win_lo'])*100,(no['win_rate']-no['win_lo'])*100],\n"
            "              [(at['win_hi']-at['win_rate'])*100,(no['win_hi']-no['win_rate'])*100]],\n"
            "        capsize=6, color=['C2','C0'])\n"
            "plt.ylabel('% of buys that were higher 12 months later'); plt.ylim(70, 90)\n"
            "plt.title('One-year win-rate (Wilson 95% intervals)'); plt.show()\n"
            "print(f\"at a high:  {at['win_rate']*100:.1f}%  [{at['win_lo']*100:.1f}, {at['win_hi']*100:.1f}]\")\n"
            "print(f\"off a high: {no['win_rate']*100:.1f}%  [{no['win_lo']*100:.1f}, {no['win_hi']*100:.1f}]\")"
        ),
        md(
            f"Buying at an all-time high was higher a year later **{R['w12_at']}%** of the time — *better* "
            f"than the **{R['w12_not']}%** for off-high buys, and the error bars don't overlap. The 'risky "
            "moment' was, if anything, the slightly *safer* one."
        ),
        md("Finally, the rule as a **strategy**: sit in cash whenever you're near a high. Did 'waiting for the pullback' pay?"),
        code(
            "pos = strategy.avoid_highs_position(close, NEAR_PCT, lag=1)\n"
            "timer = strategy.backtest(close, pos, cost_bps=5.0)\n"
            "bh = strategy.buy_and_hold(close)\n"
            "plt.plot(bh['equity'], label=f\"Buy & hold ({bh['cagr']*100:.1f}%/yr)\", lw=1.3)\n"
            "plt.plot(timer['equity'], label=f\"Avoid the highs ({timer['cagr']*100:.1f}%/yr)\", lw=1.3)\n"
            "plt.yscale('log'); plt.ylabel('Growth of $1 (log)'); plt.legend()\n"
            "plt.title('Avoiding all-time highs vs just holding SPY'); plt.show()\n"
            "print(f\"avoid-highs ends at {timer['final']/bh['final']:.2f}x buy-and-hold\")"
        ),
        md(
            f"The avoid-the-highs line ends **below** buy-and-hold — **{R['wealth_ratio']}x** the wealth — "
            f"because every time you sat out a record you sat out the trend that followed. You paid "
            f"**{abs(R['cagr_gap']):.1f} points a year** for the privilege, and got *no* less drawdown for it."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Is an ATH a sell signal? → Busted.** Forward returns are as good (and a year out, "
            f"*better*) after a record; the one-year win-rate is **{R['w12_at']}%** vs **{R['w12_not']}%**.\n"
            f"- **Signal → None.** The at-minus-off difference never clears the noise bar at any horizon.\n"
            f"- **Waiting for the pullback? → Mirage.** It costs **{abs(R['cagr_gap']):.1f} pts/yr** and "
            f"leaves you with **{R['wealth_ratio']}x** the money, for no risk reduction."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You *can* run 'avoid the highs' — it's just SPY — but it's a losing trade: it underperforms "
            "buy-and-hold while sitting in cash 29% of the time, with the same drawdown. The thing it "
            "asks you to dodge (records) is exactly where the trend lives. There's nothing to harvest."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Tighten or widen the band (exactly-a-new-high vs within 5%) — does the (non-)effect move?\n"
            "- Try the **52-week** high instead of the all-time high (the George–Hwang momentum signal).\n"
            "- Does the *opposite* rule — buy **only** at highs — earn the momentum premium? Fork it and try."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# High Noon — a quantitative teardown 🔬\n"
            "### Real total-return tape · conditional forward returns · HAC inference · Wilson CIs\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim now carrying its standard error.* We split SPY days into *at-ATH* (within "
            "1% of the running high) and *not-at-ATH*, compare forward 1/3/12-month returns with HAC "
            "*t*-stats and Wilson win-rate intervals, test the **difference**, and run the avoid-the-highs "
            "rule as a strategy.\n\n"
            "> ⚠️ **Not investment advice.** SPY daily, total-return adjusted (`quantlab.data`, Yahoo); "
            "overlapping forward returns → HAC lags set to the horizon; cash earns 0% (conservative); "
            "5 bps/switch; one-day execution lag. Sources in [`docs/references.md`](../docs/references.md), "
            "reproducible run in [`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `NONE` | at-minus-not forward-return difference = "
            f"**{R['d1']:+.2f} / {R['d3']:+.2f} / {R['d12']:+.2f} pts** at 1/3/12 mo, HAC *t* = "
            f"**{R['t1']:+.2f} / {R['t3']:+.2f} / {R['t12']:+.2f}** — none clears \\|t\\|=2, and 12-mo is "
            f"*positive*. |\n"
            f"| **Tradability** | `MIRAGE` | avoid-highs trails buy-and-hold by **{abs(R['cagr_gap']):.1f} "
            f"pts/yr** ({R['t_cagr']}% vs {R['b_cagr']}%), Sharpe {R['sharpe_gap']:+.3f}, **{R['wealth_ratio']}x** "
            f"wealth, no drawdown relief. |\n"
            f"| **ATH a sell signal?** | `BUSTED` | 12-mo win-rate **{R['w12_at']}%** at-ATH vs "
            f"**{R['w12_not']}%** not (Wilson intervals disjoint). |\n\n"
            "> 💡 **In plain words:** the 'riskiest moment' is statistically an *ordinary* moment — and at "
            "a one-year horizon a slightly *above-average* one."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (the folk rule):** forward returns conditional on being at/near an ATH are "
            "**significantly lower** than when not near a high.\n"
            "- **H₀ (the null we expect):** they are indistinguishable (highs cluster in uptrends).\n"
            "- **H₂ (the momentum inversion):** they might even be *higher* (George–Hwang 52-week-high)."
        ),
        md("## 2 · So what? — what rides on the answer\n\nIf H₁ held, a record would be a tradable fade "
           "and 'wait for the pullback' would be a free option. It doesn't — and the cost of believing it "
           "is the upside you skip."),
        md("## 3 · How we'd know — the protocol\n\nConditional forward-return means (HAC *t*, lag = horizon) "
           "· win-rates with Wilson 95% intervals · a HAC test of the **difference** (at − not) · the "
           "avoid-the-highs backtest vs buy-and-hold. Mirage trigger: the difference is not significantly "
           "negative at any horizon."),
        md("## 4 · The teardown\n\nConditional forward-return table — means, win-rates (Wilson 95%), and HAC *t* on each arm:"),
        code(
            "out = []\n"
            "for h, lab in [(M,'1-month'),(3*M,'3-month'),(12*M,'12-month')]:\n"
            "    s = strategy.conditional_forward_stats(close, h, NEAR_PCT)\n"
            "    for arm, nm in [(s['at'],'at-ATH'),(s['not_at'],'not-ATH')]:\n"
            "        out.append([lab, nm, arm['n'], arm['mean']*100, arm['win_rate']*100,\n"
            "                    arm['win_lo']*100, arm['win_hi']*100, arm['hac_t']])\n"
            "tbl = pd.DataFrame(out, columns=['horizon','arm','n','mean%','win%','win_lo','win_hi','HAC t'])\n"
            "tbl.round(2)"
        ),
        md("**The test of the difference** — at-ATH minus not-at-ATH, with a HAC *t* (this is the line that decides Signal):"),
        code(
            "for h, lab in [(M,'1-month'),(3*M,'3-month'),(12*M,'12-month')]:\n"
            "    s = strategy.conditional_forward_stats(close, h, NEAR_PCT)\n"
            "    verdict = 'bearish' if s['diff_hac_t']<=-2 else 'NOT bearish'\n"
            "    print(f\"{lab:>9}: diff {s['diff_mean']*100:+5.2f} pts   HAC t {s['diff_hac_t']:+5.2f}   -> {verdict}\")"
        ),
        md(
            "> 💡 **In plain words:** at no horizon is the all-time-high day a worse bet than the "
            "off-high day — the differences are noise, and the only one with a clear sign (12 months) is "
            "*positive*. The 'sell signal' isn't there."
        ),
        md("**The rule as a strategy** — avoid the highs vs buy-and-hold, net of 5 bps/switch:"),
        code(
            "pos = strategy.avoid_highs_position(close, NEAR_PCT, lag=1)\n"
            "timer = strategy.backtest(close, pos, cost_bps=5.0)\n"
            "bh = strategy.buy_and_hold(close)\n"
            "stt = pd.DataFrame({\n"
            "  'CAGR %':[timer['cagr']*100, bh['cagr']*100],\n"
            "  'Vol %':[timer['vol']*100, bh['vol']*100],\n"
            "  'Sharpe':[timer['sharpe'], bh['sharpe']],\n"
            "  'MaxDD %':[timer['max_dd']*100, bh['max_dd']*100],\n"
            "  'TiM %':[timer['time_in_market']*100, bh['time_in_market']*100],\n"
            "}, index=['Avoid-highs timer','Buy & hold'])\n"
            "print(f\"avoid-highs ends at {timer['final']/bh['final']:.2f}x buy-and-hold\")\n"
            "stt.round(2)"
        ),
        md(
            "> 💡 **In plain words:** the rule sheds 29% of the days — and they were disproportionately "
            "*good* days — so it loses on return and Sharpe while buying *no* drawdown protection."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `NONE` (difference HAC *t* {R['t1']:+.2f}/{R['t3']:+.2f}/{R['t12']:+.2f}, none below "
            f"−2), Tradability `MIRAGE` (−{abs(R['cagr_gap']):.1f} pts/yr, Sharpe {R['sharpe_gap']:+.3f}, "
            f"{R['wealth_ratio']}x wealth), ATH a sell signal? `BUSTED` (12-mo win {R['w12_at']}% vs "
            f"{R['w12_not']}%). The folklore inverts the data."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (SPY). The binding fact is economic: 'avoid the highs' is a "
            "**negative-edge** filter — it removes the trending days that carry the index's return while "
            "leaving the full drawdown intact. Adding taxes on 641 switches only widens the gap. There is "
            "nothing here to scale."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Sweep the band (0% = strict new highs, 5%, 10%) and the horizon — confirm the null is robust.\n"
            "- Swap the all-time high for the **52-week high** and test the George–Hwang (2004) momentum claim directly.\n"
            "- Block-bootstrap the 12-month difference for a CI on the (mildly positive) +1.4 pts."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
