"""Build the two narrative notebooks for Study 227 (Natgas-Winter).

    python notebooks/build_notebooks.py

Figures inline from the cached real run (_cache/natgas_winter_ung.parquet, built by
examples/verify.py --fetch).

Key numbers pinned from the real run (fingerprint 68346ee6801f, as-of 2026-06-01):
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Real-run numbers — pinned from examples/verify.py (2026-06-01, fp 68346ee6801f)
# ---------------------------------------------------------------------------
REAL_NUMBERS = {
    "ticker": "UNG",
    "n_months": 229,
    "date_start": "2007-05-31",
    "date_end": "2026-05-31",
    "fingerprint": "68346ee6801f",
    "as_of": "2026-06-01",
    # winter-dummy regression
    "slope": -0.0352,
    "tstat": -1.96,
    "mean_winter": -0.0356,   # -3.56%/month
    "mean_nonwinter": -0.0004,  # -0.04%/month
    # seasonal strategy
    "seasonal_cagr": -0.2448,
    "seasonal_sharpe": -0.60,
    "seasonal_maxdd": -0.9976,
    # buy-and-hold
    "bh_cagr": -0.2821,
    "bh_sharpe": -0.45,
    "bh_maxdd": -0.9987,
    # sub-periods
    "early_slope": -0.0201,
    "early_tstat": -0.99,
    "early_n": 104,
    "late_slope": -0.0483,
    "late_tstat": -1.72,
    "late_n": 125,
}

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (natgas_winter/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from natgas_winter import data, strategy as st
from quantlab import repro
d = repro.as_of(data.fetch_ung())   # cache-first; hole-free monthly grid, pinned as-of
reg = st.winter_premium(d["ung"])
seasonal = st.seasonal_returns(d["ung"])
bh = st.buy_hold_returns(d["ung"])
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Winter is a tailwind?: Busted](https://img.shields.io/badge/Winter_tailwind%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Natgas-Winter\n### Is the winter natural-gas spike a tradable season?\n\n"
           + VERDICT +
           "Every winter, natural-gas demand peaks as homes and businesses crank up the heat. "
           "Folk wisdom says: buy UNG in October, ride the spike through March, sell. It sounds "
           "intuitive — but UNG is not natural gas. It is a monthly futures roll, and when the "
           "futures curve slopes upward (contango), each roll costs you real money. This is the "
           "widow-maker of commodity ETFs: the spot might spike, but the ETF loses anyway.\n\n"
           "> This is the plain-language notebook. The regression and sub-period slopes are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first\n\n"
           "| The claim | The data (UNG 2007-2026, 229 months) |\n|---|---|\n"
           "| \"Winter demand lifts natgas prices\" | True for spot. But UNG average **-3.56%/month** in winter vs **-0.04%/month** in summer. |\n"
           "| \"Buy Oct, sell Mar\" | Seasonal strategy CAGR **-24.5%**, Sharpe **-0.60** — worse than buy-and-hold (-28.2%, Sharpe -0.45). |\n"
           "| \"A durable seasonal edge\" | Negative slope in both 2007-2015 (t = -0.99) and 2016-2026 (t = -1.72). |\n\n"
           "> The widow-maker earns its name."),
        md("## 1 · The claim\n\nNatural gas demand peaks in winter. Heating degree-days drive consumption "
           "above injection capacity. Folk traders say: capture this in UNG (the largest retail natgas "
           "vehicle), buy in fall, sell when winter ends."),
        md("## 2 · What UNG actually holds\n\nUNG does not hold physical natural gas. It holds "
           "**front-month futures contracts** and rolls them before expiry into the next contract. When "
           "the futures curve is in **contango** (distant months more expensive than nearby), rolling "
           "means selling cheap and buying dear — a guaranteed monthly loss independent of where spot "
           "goes. In natural gas, contango is the default condition: the market pays a premium for "
           "future delivery (storage costs, weather optionality). Winter is precisely when the contango "
           "is steepest — and when roll drag is worst."),
        md("## 3 · How would we even know?\n\nRegress monthly UNG returns on a winter dummy (1 = Oct-Mar, "
           "0 = Apr-Sep): positive slope + significant t-stat would support the claim. Then race the "
           "seasonal strategy (in during Oct-Mar, cash=0 otherwise) against buy-and-hold UNG on Sharpe."),
        code("# Winter vs non-winter returns by month\n"
             "sig = st.seasonal_signal(pd.DatetimeIndex(d.index))\n"
             "monthly_means = d.groupby(d.index.month)['ung'].mean() * 100\n"
             "colors = ['#c0392b' if m in st.WINTER_MONTHS else '#2ea44f' for m in monthly_means.index]\n"
             "fig, ax = plt.subplots(figsize=(10, 5))\n"
             "bars = ax.bar(monthly_means.index, monthly_means.values, color=colors)\n"
             "ax.axhline(0, color='k', lw=0.8)\n"
             "ax.set_xticks(range(1, 13))\n"
             "ax.set_xticklabels(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])\n"
             "ax.set_ylabel('Mean monthly UNG return (%)')\n"
             "ax.set_title('UNG average return by calendar month (red=winter Oct-Mar)')\n"
             "plt.tight_layout(); plt.show()\n"
             "print(f'Winter (Oct-Mar) mean: {d[sig==1][\"ung\"].mean()*100:.2f}%/month')\n"
             "print(f'Non-winter (Apr-Sep) mean: {d[sig==0][\"ung\"].mean()*100:.2f}%/month')"),
        md("## 4 · The teardown\n\nThe chart says it all: the 'winter spike' in natural-gas *demand* "
           "does not translate into positive UNG *returns*. Winter months average −3.56%/month — the "
           "worst cluster of the calendar. Summer months (Apr-Sep) are nearly flat (−0.04%/month). "
           "The seasonal trade concentrates exposure in the worst months."),
        code("rows = {'seasonal (Oct-Mar)': st.summary(seasonal), 'buy & hold UNG': st.summary(bh)}\n"
             "t = pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown']]\n"
             "display(t.style.format({'cagr':'{:.1%}','sharpe':'{:.2f}','max_drawdown':'{:.0%}'}))\n"
             "eq_s = (1 + seasonal).cumprod(); eq_b = (1 + bh).cumprod()\n"
             "ax = eq_b.plot(label='buy & hold UNG', lw=1.5, color='steelblue')\n"
             "eq_s.plot(ax=ax, label='seasonal (Oct-Mar)', lw=1.5, color='#c0392b')\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1 — UNG since inception (log scale)')\n"
             "ax.legend(); plt.show()"),
        md("**Read it plainly.** Both lines go to near-zero — UNG has lost ~99.8% since inception. "
           "The seasonal strategy (red) trails the already-terrible buy-and-hold (blue) because it "
           "concentrates its exposure in the worst calendar months. The widow-maker lives up to its name."),
        md("## 5 · The verdict\n\n**Signal: None** — the winter slope is −0.035 (t = −1.96), wrong "
           "sign, wrong significance. **Tradability: Mirage** — seasonal Sharpe −0.60 versus "
           "buy-and-hold −0.45. **Winter is a tailwind?: Busted.**"),
        md("## 6 · Could you actually trade it?\n\nYou could set a calendar reminder every October to "
           "buy UNG. You'd lose roughly a quarter of your stake every year. The fundamental demand "
           "season is real — but the futures market prices it in, and then the roll drag extracts a "
           "monthly toll on top. There is no edge here; only a slow and predictable destruction of capital."),
        md("## 7 · Going further\n\nFor actual natgas exposure, researchers look at: (a) backwardated "
           "regimes (rare in natgas, but real carry exists then); (b) natural-gas producer equities "
           "(EQT, CHK) which carry operational leverage to spot without roll drag; (c) calendar spread "
           "strategies that earn the roll yield *from the other side*. The seasonal long in UNG is not "
           "among them."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Natgas-Winter — a quantitative teardown\n"
           "### Winter-dummy regression · seasonal vs buy-and-hold race · sub-period slope splits\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test "
           "the winter-demand seasonality thesis on all live UNG data and find none — and explain why "
           "mechanically (contango roll drag).\n\n"
           "> **Not investment advice.** UNG monthly, 2007-05 → 2026-05, 229 months (Yahoo, daily "
           "closes resampled to month-end, hole-free grid). Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | slope −0.035, t −1.96 — wrong sign, not significant |\n"
           "| Tradability | **Mirage** | seasonal Sharpe −0.60 < buy-and-hold −0.45 (both catastrophic) |\n"
           "| Winter tailwind? | **Busted** | negative slope in 2007-2015 (t −0.99) and 2016-2026 (t −1.72) |\n\n"
           "> *In plain words:* winter is the worst season for UNG. The widow-maker earns its name."),
        md("## 1 · The claim, steelmanned\n\n"
           "- **H₁:** the regression slope of UNG_t on winter-dummy is positive and significant (|t| ≥ 2).\n"
           "- **H₂:** the seasonal strategy (long Oct-Mar, cash otherwise) beats buy-and-hold on Sharpe.\n"
           "- **H₃:** the winter premium is present in both sub-periods."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, a simple calendar rule would "
           "extract a real seasonal edge from retail natgas. If they fail, the thesis is folklore — "
           "and the mechanism (contango drag) actively punishes the seasonal trader."),
        md("## 3 · How we know — the protocol\n\nOLS of monthly UNG return on intercept + winter dummy "
           "(1 = Oct-Mar, 0 = Apr-Sep) with analytic t-stat → seasonal (Oct-Mar long, cash=0) vs "
           "buy-and-hold race on raw Sharpe → 2007-2015 / 2016-2026 sub-period slope split."),
        md("## 4 · The teardown"),
        md("### 4.1 The winter-dummy regression (n = 229)"),
        code("print({k: (round(v, 4) if isinstance(v, float) else v) for k, v in reg.items()})\n"
             "print(f\"slope {reg['slope']:+.4f} (positive = winter outperforms), t = {reg['tstat']:+.2f} (need |t|>2)\")"),
        md("> In plain words: the slope is **negative** (t = −1.96) — winter months underperform summer "
           "months by about 3.5 percentage points per month. A t of −1.96 with the wrong sign means "
           "the claim fails on both counts: no significance, and the wrong direction. **H₁ rejected.**"),
        md("### 4.2 Monthly return distribution by season"),
        code("sig = st.seasonal_signal(pd.DatetimeIndex(d.index))\n"
             "w_ret = d['ung'][sig == 1] * 100\n"
             "s_ret = d['ung'][sig == 0] * 100\n"
             "fig, axes = plt.subplots(1, 2, figsize=(12, 4), sharey=False)\n"
             "axes[0].hist(w_ret, bins=30, color='#c0392b', alpha=0.8, edgecolor='white')\n"
             "axes[0].axvline(w_ret.mean(), color='k', lw=2, label=f'mean {w_ret.mean():.1f}%')\n"
             "axes[0].set_title('Winter (Oct-Mar) UNG monthly returns'); axes[0].legend()\n"
             "axes[1].hist(s_ret, bins=30, color='steelblue', alpha=0.8, edgecolor='white')\n"
             "axes[1].axvline(s_ret.mean(), color='k', lw=2, label=f'mean {s_ret.mean():.1f}%')\n"
             "axes[1].set_title('Non-winter (Apr-Sep) UNG monthly returns'); axes[1].legend()\n"
             "plt.tight_layout(); plt.show()\n"
             "print(f'Winter mean: {w_ret.mean():.2f}%/month  n={len(w_ret)}')\n"
             "print(f'Non-winter mean: {s_ret.mean():.2f}%/month  n={len(s_ret)}')"),
        md("### 4.3 Seasonal vs buy-and-hold — raw Sharpe race"),
        code("s_seas = st.summary(seasonal); s_bh = st.summary(bh)\n"
             "display(pd.DataFrame({'seasonal (Oct-Mar)': s_seas, 'buy & hold UNG': s_bh}).T[\n"
             "    ['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "eq_s = (1 + seasonal).cumprod(); eq_b = (1 + bh).cumprod()\n"
             "ax = eq_b.plot(label='buy & hold UNG', lw=1.5, color='steelblue')\n"
             "eq_s.plot(ax=ax, label='seasonal (Oct-Mar)', lw=1.5, color='#c0392b')\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1 (log scale, UNG inception → 2026)')\n"
             "ax.legend(); plt.show()"),
        md("> In plain words: both strategies destroy capital. The seasonal strategy (CAGR −24.5%, "
           "Sharpe −0.60) is *worse* than buy-and-hold (CAGR −28.2%, Sharpe −0.45) because it "
           "concentrates losses in the worst months. **H₂ rejected.**"),
        md("### 4.4 Sub-period slope splits"),
        code("for lab, sl in [('2007-2015', d[d.index.year <= 2015]), ('2016-2026', d[d.index.year >= 2016])]:\n"
             "    rr = st.winter_premium(sl['ung'])\n"
             "    print(f\"{lab}: slope {rr['slope']:+.4f}  t = {rr['tstat']:+.2f}  n={rr['n']}\")"),
        md("> In plain words: both sub-periods show a negative slope (winter worse than summer) and "
           "neither is significant with the right sign. The 2016–2026 period actually has a larger "
           "negative slope, suggesting roll drag has intensified. **H₃ rejected.**"),
        md("## 5 · The widow-maker mechanism\n\nContango roll drag in natural-gas futures:\n"
           "- Front-month contract: expires in ~30 days, priced near $X\n"
           "- Next-month contract: priced at $X + contango premium\n"
           "- UNG roll: sell front at $X, buy second at $X + premium = monthly loss\n"
           "- In winter, the curve is most steeply sloped (storage scarcity + demand peak)\n"
           "- Result: roll drag peaks precisely when the 'seasonal trade' is active\n\n"
           "The spot price may spike in February — but UNG paid away that spike in advance through "
           "five months of negative roll yield buying into it."),
        md("## 6 · The verdict\n\nH₁, H₂, H₃ all rejected → Signal `NONE`, Tradability `MIRAGE`, "
           "winter tailwind `BUSTED`. The widow-maker is a mechanical, structural drag that makes "
           "long UNG in winter worse than long UNG year-round."),
        md("## 7 · Could you trade it?\n\nNot this. Adjacent ideas that have real (though decayed) "
           "literature support: (a) natgas producer equities with spot exposure but no roll drag; "
           "(b) calendar spread strategies (sell the nearby, buy the later) to earn the contango "
           "*from the other side*; (c) backwardation timing — when the natgas curve inverts (rare), "
           "roll yield turns positive and a long ETP position has structural tailwind. None of these "
           "is the 'buy UNG in October' folk trade."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
