"""Generate the two narrative notebooks for Study 24 (Stampede) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the **offline synthetic panel** (a baked-momentum tape + a no-momentum null).
The synthetic proves the machinery (the WML premium is real by construction and the null kills it); the
**real verdict** (a faint, crash-prone premium on the modern S&P 500) is quoted from
[`docs/results.md`](../docs/results.md). Both notebooks walk the SAME seven desk beats (see ../../../METHODOLOGY.md).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from stampede import data, momentum, strategy, decompose, extension

# Offline synthetic panel: a MOMENTUM tape (persistent relative drift -> winners keep winning) and a
# no-momentum NULL. The real S&P 500 verdict is in ../docs/results.md.
panel,  market,  truth = data.synthetic_panel(mom_strength=0.0015, seed=24)   # the momentum tape
panel0, market0, _     = data.synthetic_panel(mom_strength=0.0,    seed=24)   # the no-momentum null
print(f"{truth.n_stocks} stocks x {truth.n_bars} days | baked mom_strength={truth.mom_strength} | null=0")
"""

R = dict(
    n_stocks="263", lo="2010", hi="2026", fp="12af7604edc8",
    wml_alpha="+4.4", wml_t="+0.9", wml_sr="+0.10", wml_beta="-0.13", turn="7",
    win_sr="+0.99", mkt_sr="+0.97", wml_spread="+10",
    skew="+0.15", worst="-22.5", worst5="-14.4", maxdd="-61",
    sub1="+0.31", sub2="-0.40", sub3="+0.49",
    mgd_sr="+0.16", mgd_dd="-32",
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Crash risk?: Severe](https://img.shields.io/badge/Crash_risk%3F-Severe-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Stampede 🐂\n"
            "### Buy what's been winning, short what's been losing. Does the herd pay — and what happens when it turns?\n\n"
            + BADGES +
            "This is the big one — **momentum**, the most stubbornly robust anomaly in all of finance. "
            "Rank stocks by how they've done over the past year, buy the **winners**, short the "
            "**losers**, refresh monthly. Decades of data, dozens of markets, a Nobel-adjacent literature "
            "(Jegadeesh & Titman 1993) all say the same thing: the winners keep winning, the losers keep "
            "losing, and the spread pays a large premium.\n\n"
            "This is the desk's seventh idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§3.1). We prove our tools on a synthetic market where we bake the momentum in (and a null "
            "where there's none), then run it on the real S&P 500 — where we find the famous premium has "
            "gone **faint**, and the herd, when it turns, **tramples** you: a single month down 22%, a "
            "drawdown past 60%. The signature *momentum crash*.\n\n"
            "> 📓 **Plain-language layer.** The HAC alpha, the crash skew and the risk-managed overlay are "
            "in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** panel, so the real-S&P numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Do past winners keep winning? | 🟡 **In the long-run data, overwhelmingly; on the modern "
            f"S&P 500, faintly** — a WML alpha of **{R['wml_alpha']}%/yr** at *t* = **{R['wml_t']}**, not "
            "significant here. |\n"
            "| Can you just hold the winners? | ⚪ **Barely beats the market** (Sharpe "
            f"**{R['win_sr']}** vs **{R['mkt_sr']}**). |\n"
            "| What's the catch? | 🐂 **The crash.** Worst month **{R0}%**, max drawdown "
            f"**{R['maxdd']}%** — when losers rebound, the short leg detonates. |\n\n"
            "> Desk shorthand: **Signal `WEAK` · Tradability `FRAGILE` · Crash risk? `SEVERE`** — a real "
            "premium in principle, decayed and dangerous in practice.".replace("{R0}", R["worst"])
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Sort the cross-section by the trailing 12-month return (skipping the last month, to dodge "
            "short-term reversal), and the top decile out-earns the bottom over the next month. On our "
            "synthetic momentum market, here's the forward return by momentum decile — a clean upward "
            "staircase:"
        ),
        code(
            "sp = momentum.momentum_spread(panel)\n"
            "d = sp['decile_fwd_ann']\n"
            "fig, ax = plt.subplots()\n"
            "ax.bar(d.index, d.values, color='#2ea44f', alpha=.85)\n"
            "ax.set_xlabel('momentum decile (0 = losers, 9 = winners)'); ax.set_ylabel('forward return (annualised %)')\n"
            "ax.set_title(f\"Winners keep winning: WML spread {sp['wml_ann_pct']:+.0f}%/yr (synthetic)\")\n"
            "plt.show()"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "Momentum is the crown jewel of factor investing — it shows up in stocks, bonds, "
            "commodities, currencies, and back to the Victorian era. If it's real and harvestable, it's "
            "one of the most valuable facts in markets. But it has a dark twin: because you're *short* "
            "the losers, a violent rebound in beaten-down names — the kind that happens at a bear-market "
            "bottom — turns the strategy inside out. That asymmetry is the whole story."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Four checks:\n\n"
            "1. **Do winners out-earn losers?** The decile profile and the WML alpha, with a *t*-stat.\n"
            "2. **Can a long-only investor capture it?** Winners vs the market.\n"
            "3. **What's the tail?** The crash — skew, worst months, deepest drawdown.\n"
            "4. **Can it be managed?** Vol-scaling the factor. And the **null**: no persistence ⇒ no "
            "premium.\n\n"
            "**Fragile line:** a real premium, but a catastrophic left tail and (on the modern sample) a "
            "thin, insignificant standalone return."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · Momentum tape vs the null\n"
            "Run the WML factor on both synthetic panels."
        ),
        code(
            "for label, p in [('momentum', panel), ('no-momentum null', panel0)]:\n"
            "    cmp = strategy.compare(p, cost_bps=5.0); a = decompose.capm_alpha(p, cost_bps=5.0)\n"
            "    print(f\"{label:18s}: WML Sharpe {cmp['wml']['sharpe']:+.2f}, alpha {a['alpha_ann_pct']:+.1f}%/yr \"\n"
            "          f\"(HAC t {a['alpha_t']:+.1f}), turnover {cmp['turnover_ann']:.0f}x/yr\")"
        ),

        md(
            "### 4b · The crash — momentum's dark twin\n"
            "Even on the relatively gentle synthetic tape, the WML drawdown is the thing you feel. On the "
            "real S&P 500 it's brutal. Here's the equity curve and its underwater plot (synthetic):"
        ),
        code(
            "wml = strategy.books(panel, cost_bps=5.0)['wml']\n"
            "eq = (1+wml).cumprod(); dd = eq/eq.cummax()-1\n"
            "fig, (a1, a2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)\n"
            "a1.plot(eq.index, eq.values, color='#2ea44f'); a1.set_yscale('log'); a1.set_ylabel('growth of $1 (WML)')\n"
            "a1.set_title('Momentum compounds -- until it crashes')\n"
            "a2.fill_between(dd.index, dd.values, 0, color='#c0392b', alpha=.5); a2.set_ylabel('drawdown')\n"
            "plt.tight_layout(); plt.show()\n"
            f"print('On the REAL S&P 500: worst month {R['worst']}%, worst-5 avg {R['worst5']}%, max drawdown {R['maxdd']}%.')"
        ),

        md(
            "### 4c · On the real market — faint and crash-prone\n"
            "On the current S&P 500 (quoted from [`../docs/results.md`](../docs/results.md)):\n\n"
            f"- The WML alpha is **{R['wml_alpha']}%/yr** at *t* = **{R['wml_t']}** — not distinguishable "
            "from zero on this large-cap, post-2009, survivorship-biased sample. Momentum has *decayed* "
            "in US large caps.\n"
            f"- Long-only winners (Sharpe **{R['win_sr']}**) barely beat the market (**{R['mkt_sr']}**).\n"
            f"- And the crash is real: worst month **{R['worst']}%**, max drawdown **{R['maxdd']}%**, with "
            "the premium swinging sub-period to sub-period (Sharpe "
            f"**{R['sub1']} → {R['sub2']} → {R['sub3']}**)."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            "- **Real in principle** — our control recovers a WML alpha at *t* ≈ 14; the long-run "
            "literature is overwhelming.\n"
            f"- **Faint here** — modern-S&P alpha {R['wml_alpha']}%/yr (*t* {R['wml_t']}), decayed.\n"
            f"- **Crash-prone** — worst month {R['worst']}%, drawdown {R['maxdd']}%.\n\n"
            "> **Signal `WEAK` · Tradability `FRAGILE` · Crash risk? `SEVERE`.** The crown jewel, dimmed "
            "by decay and weighed down by a catastrophic tail."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            f"- **The standalone premium is thin** on the investable large-cap sample (Sharpe {R['wml_sr']}), "
            "and you'd need to *short* the losers — the hard-to-borrow, beaten-down names.\n"
            f"- **The crash is the real cost.** A {R['maxdd']}% drawdown ends most books; a single "
            f"{R['worst']}% month ends most careers.\n"
            "- **It turns over fast** (the winners list churns), so costs compound.\n\n"
            "> Tradability **`FRAGILE`**; the crash is `SEVERE` — but the worked complement "
            "([`../docs/extension.md`](../docs/extension.md)) shows it's the *manageable* part."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **Risk-managed momentum** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): the crashes cluster when the factor's own "
            f"vol is high, so vol-scaling it (the [Study 16](../../16-storm-shy/) overlay) cuts the "
            f"drawdown from **{R['maxdd']}% to {R['mgd_dd']}%** and lifts the Sharpe to **{R['mgd_sr']}**.\n"
            "- **Residual momentum** (§3.7) — strip the market/factor exposure and momentum on the "
            "residuals is cleaner and less crash-prone; the desk's next candidate.\n"
            "- **Longer, delisted-inclusive data.** The famous premium lives in the broad, all-cap, "
            "pre-2010 cross-section; a CRSP-style panel would show it alive where our large-cap window is "
            "faint, and date the decay.\n\n"
            "PRs welcome — resurrect the premium on honest long-run data, or push the crash-management "
            "further."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Stampede — a quantitative teardown 🔬\n"
            "### The 12-1 decile profile · WML CAPM alpha (HAC) · the momentum-crash tail · sub-sample decay · risk-managed momentum\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim with its standard error.* The steelman is §3.1 cross-sectional "
            "momentum (Jegadeesh & Titman 1993): long winners, short losers, monthly. We prove the "
            "apparatus on a synthetic momentum panel (and a null), then read the real verdict off the S&P "
            "500.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — do winners out-earn losers? | 🟡 `WEAK` | Overwhelming in the long-run "
            "literature and on our control (WML alpha at HAC *t* ≈ 14); but on the modern S&P 500 the WML "
            f"alpha is **{R['wml_alpha']}%/yr** (*t* = **{R['wml_t']}**) — decayed to insignificance. |\n"
            "| **Tradability** | 🟡 `FRAGILE` | Thin standalone Sharpe "
            f"(**{R['wml_sr']}**), fast turnover, and you must short the losers; salvageable only with "
            "risk management. |\n"
            "| **Crash risk?** | ⚪ `Severe` | Worst month "
            f"**{R['worst']}%**, max drawdown **{R['maxdd']}%** — the loser-rebound crash. |\n\n"
            "> **In one sentence:** the most robust anomaly in finance, real in principle and on our "
            "control, but faint on the modern large-cap sample and carrying a catastrophic, if "
            "forecastable, left tail.\n\n"
            "*(This notebook executes on synthetic panels; the real S&P numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Momentum score $m_{i,t} = \\prod_{s=t-252}^{t-21}(1+r_{i,s}) - 1$ (the 12-1 return). WML = "
            "top-decile minus bottom-decile, equal-weight, dollar-neutral, monthly. The premium is "
            "$\\mathbb{E}[r_{\\text{WML}}] > 0$ with a positive CAPM alpha. The synthetic bakes a "
            "persistent per-stock relative drift $\\theta_{i,t}$ (AR(1), $\\phi\\to1$); "
            "$\\text{mom\\_strength}=0$ is the null."
        ),
        code(
            "sp = momentum.momentum_spread(panel)\n"
            "print(f\"winners {sp['winners_ann_pct']:+.1f}%/yr vs losers {sp['losers_ann_pct']:+.1f}%/yr \"\n"
            "      f\"-> WML spread {sp['wml_ann_pct']:+.1f}%/yr (synthetic)\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Momentum's alpha is large and pervasive, but it is *conditionally* risky: its volatility and "
            "crash risk spike in panicked, post-crash markets (Daniel & Moskowitz 2016). So the open "
            "questions are: is the premium significant on the sample you can trade, how fat is the left "
            "tail, and can the tail be managed? Beats 4–6 (and the beat-7 complement) answer all three."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Decile profile + WML alpha** (`momentum.momentum_spread`, `decompose.capm_alpha`): "
            "HAC *t*. Pre-registered: strongly positive on the momentum tape, ~0 on the null.\n"
            "2. **Crash** (`decompose.crash_profile`): skew, worst months, drawdown.\n"
            "3. **Decay + bootstrap** (`decompose.subsample_sharpe`, `sharpe_bootstrap`).\n"
            "4. **Risk management** (`extension.crash_comparison`): vol-scaled WML.\n\n"
            "**Verdict logic:** `WEAK`/`FRAGILE` if the modern premium is thin/insignificant and the tail "
            "is severe; the third axis records the crash."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · WML alpha, momentum vs null"),
        code(
            "for label, p in [('momentum', panel), ('null', panel0)]:\n"
            "    a = decompose.capm_alpha(p, cost_bps=5.0)\n"
            "    print(f\"{label:9s}: alpha {a['alpha_ann_pct']:+.1f}%/yr (HAC t {a['alpha_t']:+.1f}), \"\n"
            "          f\"beta {a['beta']:+.2f}, Sharpe {a['sharpe']:+.2f}, skew {a['skew']:+.2f}\")"
        ),

        md("### 4b · The crash profile"),
        code(
            "cr = decompose.crash_profile(panel, cost_bps=5.0)\n"
            "print(f\"synthetic WML: monthly skew {cr['monthly_skew']:+.2f}, worst month {cr['worst_month_pct']:+.1f}%, \"\n"
            "      f\"worst-5 avg {cr['worst5_months_mean_pct']:+.1f}%, max drawdown {cr['max_drawdown_pct']:.0f}%\")\n"
            f"print('On the REAL S&P 500: worst month {R['worst']}%, max drawdown {R['maxdd']}% -- the loser-rebound crash.')"
        ),
        md(
            "> 💡 **In plain words.** Momentum's average is good but its distribution is lopsided: a few "
            "months — when the market violently reverses and the worst losers rip higher — give back years "
            "of gains. The drawdown, not the Sharpe, is what makes it hard to hold."
        ),

        md("### 4c · Decay and bootstrap"),
        code(
            "display(decompose.subsample_sharpe(panel, cost_bps=5.0, n_chunks=3).round(3))\n"
            "bs = decompose.sharpe_bootstrap(panel, n_boot=2000, cost_bps=5.0)\n"
            "print(f\"synthetic WML Sharpe {bs['sharpe']:+.2f}, 95% CI [{bs['ci_low']:+.2f}, {bs['ci_high']:+.2f}]\")\n"
            f"print('Real S&P sub-sample Sharpe: {R['sub1']} -> {R['sub2']} -> {R['sub3']} -- it comes and goes.')"
        ),

        md("## Beat 5 · The verdict\n\n"
           "- **Real in principle** (4a): control WML alpha at *t* ≈ 14.\n"
           f"- **Faint here**: modern-S&P alpha {R['wml_alpha']}%/yr (*t* {R['wml_t']}).\n"
           f"- **Severe tail** (4b): worst month {R['worst']}%, drawdown {R['maxdd']}%.\n\n"
           "> **Signal `WEAK` · Tradability `FRAGILE` · Crash risk? `Severe`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           f"- **Thin standalone** (Sharpe {R['wml_sr']}) on the investable sample; you must short losers.\n"
           f"- **The crash** ({R['maxdd']}% drawdown, {R['worst']}% month) is the binding constraint.\n"
           f"- **Fast turnover** ({R['turn']}×/yr) compounds cost.\n\n"
           "Tradability **`FRAGILE`**; the crash is `Severe` but manageable (beat 7)."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — risk-managed momentum\n"
            "The crashes cluster when the WML factor's own recent vol is high (Barroso–Santa-Clara 2015), "
            "so scale the position by inverse trailing WML vol — the [Study 16](../../16-storm-shy/) "
            "overlay — and compare."
        ),
        code(
            "cc = extension.crash_comparison(panel, cost_bps=5.0)\n"
            "for k in ['plain', 'managed']:\n"
            "    c = cc[k]; print(f\"{k:8s}: Sharpe {c['sharpe']:+.2f}, skew {c['skew']:+.2f}, \"\n"
            "                     f\"worst month {c['worst_month_pct']:+.1f}%, max drawdown {c['max_drawdown_pct']:.0f}%\")\n"
            f"print('On the REAL S&P 500 (../docs/extension.md): drawdown {R['maxdd']}% -> {R['mgd_dd']}%, "
            f"Sharpe {R['wml_sr']} -> {R['mgd_sr']}.')"
        ),
        md(
            "**The result.** Vol-scaling sidesteps the worst of the crash — on the real S&P 500 the "
            f"drawdown shrinks from **{R['maxdd']}% to {R['mgd_dd']}%** and the Sharpe lifts to "
            f"**{R['mgd_sr']}** — because the tail is *forecastable* (it clusters in high-vol regimes). "
            "The same risk-management insight that earned [Study 16](../../16-storm-shy/) the desk's only "
            "green turns momentum's catastrophic tail into a merely uncomfortable one. The deeper problem "
            "stays: the *premium* is faint on the modern large-cap sample; the crash is the part you can "
            "engineer around (at the cost of leverage in calm regimes). Full run in "
            "[`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **Residual momentum** (§3.7) — momentum on factor-residual returns is cleaner and less "
            "crash-prone (Blitz et al.); the desk's natural next study.\n"
            "- **Delisted-inclusive, all-cap history** — where the academic premium lives; date the "
            "decay.\n"
            "- **Constant-volatility / dynamic-weighting momentum** (Daniel–Moskowitz) — push the "
            "crash-timing further.\n\n"
            "PRs welcome — resurrect the premium on honest long-run data, or sharpen the crash management."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
