"""Build the two narrative notebooks for Study 340 (Bank-Loans).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. The BOOT cell tries the real total-return
tapes and, if the network is blocked, falls back to the offline synthetic control — clearly
bannering which tape every cell is showing. The frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen REAL-tape headline numbers — mirror of docs/results.md (as-of 2026-05-31).
R = dict(
    n=3833, start="2011-03-03", end="2026-05-29", fp="a4d0ad1fb115",
    bkln_cagr=3.73, bkln_vol=5.8, bkln_sharpe=0.660, bkln_dd=-24.2,
    tlt_cagr=2.51, tlt_vol=14.9, tlt_sharpe=0.241, tlt_dd=-48.4,
    ief_cagr=2.37, ief_vol=6.5, ief_sharpe=0.393, ief_dd=-23.9,
    spy_cagr=14.10, spy_vol=17.1, spy_sharpe=0.856, spy_dd=-33.7,
    beta_tlt=-0.055, t_tlt=-2.95, beta_ief=-0.100, t_ief=-2.62,
    beta_spy=0.202, t_spy=4.48, dbeta_spy=0.39, dbeta_tlt=0.18,
    boot_diff=0.257, boot_lo=0.175, boot_hi=0.349, boot_wins=100,
    rate_tlt=-48.4, rate_bkln=13.9, rate_ief=-23.9,  # 2020-2023 great repricing
    covid_spy=-33.7, covid_bkln=-23.8, covid_tlt=14.2,
    crashes_bkln_fell=7, crashes_total=7,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (bank_loans/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from bank_loans import data, strategy

AS_OF = "2026-05-31"
# Try the REAL total-return tapes; fall back to the offline synthetic control if the
# network is blocked. Every cell prints which TAPE it is showing.
try:
    prices = data.load_real(("BKLN", "TLT", "IEF", "SPY")).loc[:AS_OF]
    TAPE = "REAL"
except Exception as e:
    print("network/cache miss -> SYNTHETIC control tape:", type(e).__name__)
    prices, _truth = data.synthetic_four_asset(dur=0.05, credit_beta=0.65, seed=340)
    TAPE = "SYNTHETIC"

BKLN, TLT, IEF, SPY = "BKLN", "TLT", "IEF", "SPY"
rets = strategy.to_returns(prices)
BANNER = ("REAL total-return tape (BKLN/TLT/IEF/SPY, 2011-2026)" if TAPE == "REAL"
          else "SYNTHETIC control tape (dur=0.05, credit_beta=0.65) -- NOT market data")
print(f"[{TAPE}] {BANNER}")
print(f"panel: {len(prices):,} rows  {prices.index[0].date()} -> {prices.index[-1].date()}  fingerprint={data.fingerprint(prices)}")
for c in (BKLN, TLT, IEF, SPY):
    s = strategy.stats(rets[c])
    print(f"  {c}: CAGR {s['cagr']*100:6.2f}%  vol {s['vol']*100:5.1f}%  Sharpe {s['sharpe']:.3f}  maxDD {s['max_dd']*100:6.1f}%")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Free lunch?: Busted](https://img.shields.io/badge/Free_lunch%3F-Busted-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# Bank Loans 🏦\n"
            "### \"Rate-proof high yield\" — do floating-rate bank loans actually protect you when rates rise?\n\n"
            + HERO_BADGES +
            "Senior bank loans (and the ETF that holds a basket of them, **BKLN**) are sold as a "
            "*rate-proof* income sleeve: the coupon **floats** with short-term rates, so unlike a bond "
            "fund the price barely falls when rates rise. We line BKLN up next to long Treasuries "
            "(TLT), intermediate Treasuries (IEF) and stocks (SPY) and ask two questions: does the "
            "rate protection actually work — and, if it does, where did the risk *go*?\n\n"
            "> 📓 **This is the plain-language layer.** The betas, the HAC *t* and the bootstrap are "
            "in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below is "
            "generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            "| Question | Answer |\n|---|---|\n"
            f"| Does BKLN shrug off rate moves? | **Yes** — its beta to long Treasuries is "
            f"**{R['beta_tlt']}** (≈ zero). In the 2020–2023 rate rout that cost TLT **{R['rate_tlt']}%**, "
            f"BKLN *gained* **+{R['rate_bkln']}%**. |\n"
            f"| So it's low-risk? | **No** — the risk *moved to credit*. BKLN fell in "
            f"**{R['crashes_bkln_fell']} of {R['crashes_total']}** stock-market crashes; in 2020 it lost "
            f"**{R['covid_bkln']}%** while bonds *rose* **+{R['covid_tlt']}%**. |\n"
            f"| Is it a free lunch vs bonds? | **No** — you swapped *interest-rate* risk for "
            f"*credit + liquidity* risk. A modest real sleeve ({R['bkln_cagr']}%/yr, vol "
            f"{R['bkln_vol']}%), not a safe haven. |\n\n"
            "> *Headline numbers are the **real** 2011–2026 tape (`docs/results.md`, fingerprint "
            f"`{R['fp']}`). If the executed cells below show a SYNTHETIC banner, the live data was "
            "blocked and the harness fell back to the offline control — the prose numbers still refer "
            "to the real run.*"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Worried about rising rates? Rotate out of bond funds into **floating-rate senior bank "
            "loans**. The coupon resets with short-term rates, so the price barely moves when rates go "
            "up — you get a fat yield with almost none of the interest-rate risk that hammers a normal "
            "bond fund.\"* It's the pitch every advisor reaches for in a hiking cycle — and BKLN is "
            "filed in the *income* bucket, right next to the bonds it's meant to replace."
        ),
        md(
            "## 2 · So what?\n\n"
            "If the pitch is true, BKLN is the perfect place to hide from a bond bear market — high "
            "income, no duration drama. If the rate protection is real *but the risk simply moved "
            "somewhere else*, then investors fleeing duration into loans are walking into a different "
            "trap — one that springs in a recession instead of a rate hike. The label decides where "
            "you put it, and when it hurts you."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "Two clean tests. **Rate test:** every time long bonds (TLT) sold off because rates rose, "
            "what did BKLN do — fall with them, or shrug? **Credit test:** every time stocks fell more "
            "than 10%, did BKLN cushion (like a safe bond) or pile on (like risky credit)? If BKLN "
            "passes the first and *fails* the second, the rate protection is real but the safety isn't."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the four equity curves. Watch the calm "
           "BKLN line — and watch what it does in 2020."),
        code(
            "stats = {c: strategy.stats(rets[c]) for c in (BKLN, TLT, IEF, SPY)}\n"
            "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True, height_ratios=[2, 1])\n"
            "for c, style in [(SPY, dict(lw=1.2, alpha=.7)), (TLT, dict(lw=1.2, alpha=.7)), (IEF, dict(lw=1.2, alpha=.7)), (BKLN, dict(lw=1.8))]:\n"
            "    ax1.plot(stats[c]['equity'], label=f\"{c} (vol {stats[c]['vol']*100:.0f}%)\", **style)\n"
            "ax1.set_yscale('log'); ax1.set_ylabel('Growth of $1 (log)'); ax1.legend()\n"
            "ax1.set_title(f'BKLN vs Treasuries vs stocks -- total return  [{TAPE} tape]')\n"
            "for c in (SPY, TLT, IEF, BKLN):\n"
            "    eq = stats[c]['equity']; dd = eq/eq.cummax()-1\n"
            "    ax2.plot(dd, label=f\"{c} (max {dd.min()*100:.0f}%)\", lw=1.1)\n"
            "ax2.set_ylabel('Drawdown'); ax2.legend(ncol=2); ax2.set_xlabel('')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "BKLN's line is *calm* — far smoother than TLT, smoother even than IEF. That low volatility "
            "is the whole sales pitch, and it's not a lie. But notice the one place the BKLN drawdown "
            "line plunges: it isn't a rate event, it's a *risk-off* event (2020)."
        ),
        md("Now the **rate test**. Every time long bonds fell more than 5% on rising rates, here's what "
           "BKLN did over the same window:"),
        code(
            "eps = strategy.asset_drawdowns(rets[[TLT, BKLN, IEF, SPY]], TLT, thresh=-0.05)\n"
            "rows = [{'peak':e['peak'].date(),'trough':e['trough'].date(),\n"
            "         f'{TLT} %':e['driver_loss']*100, f'{BKLN} %':e['others'][BKLN]*100, f'{IEF} %':e['others'][IEF]*100} for e in eps]\n"
            "dd = pd.DataFrame(rows)\n"
            "print(f'[{TAPE}] in TLT (rate) selloffs, BKLN rose in {(dd[f\"{BKLN} %\"]>0).sum()}/{len(dd)} episodes')\n"
            "dd.round(1)"
        ),
        md(
            f"BKLN passes the rate test cleanly: in the 2020–2023 great repricing TLT lost "
            f"**{R['rate_tlt']}%** and IEF **{R['rate_ief']}%**, while BKLN **gained +{R['rate_bkln']}%**. "
            "The floating coupon does exactly what the brochure says."
        ),
        md("Now the **credit test**. Every time stocks fell more than 10%, what did BKLN do?"),
        code(
            "eps = strategy.asset_drawdowns(rets[[SPY, BKLN, TLT, IEF]], SPY, thresh=-0.10)\n"
            "rows = [{'peak':e['peak'].date(),'trough':e['trough'].date(),\n"
            "         f'{SPY} %':e['driver_loss']*100, f'{BKLN} %':e['others'][BKLN]*100, f'{TLT} %':e['others'][TLT]*100} for e in eps]\n"
            "dd = pd.DataFrame(rows)\n"
            "bkln_fell = (dd[f'{BKLN} %']<0).sum()\n"
            "print(f'[{TAPE}] BKLN fell in {bkln_fell}/{len(dd)} equity crashes')\n"
            "dd.round(1)"
        ),
        md(
            f"On the real tape BKLN fell in **{R['crashes_bkln_fell']} of {R['crashes_total']}** equity "
            f"crashes. The headline case is COVID: BKLN lost **{R['covid_bkln']}%** — a liquidity gap, "
            f"not a rate move — while Treasuries *gained +{R['covid_tlt']}%*. The risk didn't disappear; "
            "it changed costume from *duration* to *credit + liquidity*."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Signal → Real.** BKLN's rate sensitivity really is ≈ zero (beta to long bonds "
            f"{R['beta_tlt']}, HAC *t* {R['t_tlt']}), and it *rose* through the worst Treasury bear "
            "market in decades. The rate protection is statistically real.\n"
            f"- **Tradability → Fragile.** A modest, real income sleeve ({R['bkln_cagr']}%/yr, vol "
            f"{R['bkln_vol']}%) — but it fell in {R['crashes_bkln_fell']}/{R['crashes_total']} crashes "
            "and gapped −24% in 2020. Thin in stress, credit-risky, not a safe haven.\n"
            "- **Free lunch? → Busted.** Low duration is real; *low risk* is not. You traded rate risk "
            "for credit risk, and the bill comes due in a recession, not a rate hike."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You *can* buy BKLN in one click, and in calm markets it's liquid and low-vol. The catch is "
            "structural: the underlying **leveraged loans** are sub-investment-grade corporate credit "
            "that settles in *weeks*, not days, so the ETF rides on top of an illiquid market. In a "
            "risk-off shock the fund can gap to a discount — which is exactly what 2020 was. As a "
            "*tactical* dodge of duration risk it's defensible; as a *safe* bond substitute it isn't."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Split BKLN's return into **coupon vs price**: how much of the 3.7%/yr is the fat coupon "
            "vs price erosion in the 2020/2022 stress?\n"
            "- Compare to **SRLN** (an actively-managed loan ETF) and to **high-yield bonds** (HYG): is "
            "the credit-tail behaviour structural to leveraged credit, or fund-specific?\n"
            "- Build the honest **duration + credit** two-factor regression and read off how much of "
            "each BKLN carries — the quants notebook does the single-factor version."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Bank Loans — a quantitative teardown 🔬\n"
            "### Real total-return tapes · rate-beta vs credit-beta · HAC + block-bootstrap · crash co-movement\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We decompose what BKLN "
            "*actually is*: a near-zero-**duration** instrument (the rate protection is real) that "
            "loads on **equity/credit** (the catch), via its beta to long Treasuries vs to stocks, in "
            "the body and in the tail.\n\n"
            "> ⚠️ **Not investment advice.** BKLN/TLT/IEF/SPY daily, **total-return** adjusted "
            "(`bank_loans.data`, yfinance `auto_adjust=True`); betas via OLS with a HAC *t* and a "
            "circular block bootstrap on the difference. BKLN inception bounds the window at "
            "2011-03-03. Sources in [`docs/references.md`](../docs/references.md), reproducible run in "
            "[`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `REAL` | Beta of BKLN to long Treasuries **{R['beta_tlt']}** (HAC *t* "
            f"**{R['t_tlt']}**) — rate risk ≈ 0; it gained **+{R['rate_bkln']}%** through the 2020–2023 "
            "TLT rout. The rate-protection claim clears the *t*≥2 bar. |\n"
            f"| **Tradability** | `FRAGILE` | Real but modest (CAGR **{R['bkln_cagr']}%**, vol "
            f"**{R['bkln_vol']}%**); fell in {R['crashes_bkln_fell']}/{R['crashes_total']} equity "
            f"crashes, gapped **{R['covid_bkln']}%** in 2020. Credit + liquidity risk, thin in stress. |\n"
            f"| **Free lunch?** | `BUSTED` | Risk moved from duration to credit: beta to SPY "
            f"**+{R['beta_spy']}** (HAC *t* **+{R['t_spy']}**); equity-beta − rate-beta = "
            f"**+{R['boot_diff']}**, CI **[{R['boot_lo']}, {R['boot_hi']}]**. |\n\n"
            "> 💡 **In plain words:** BKLN does dodge rate risk — that part is true and certified. But "
            "it is a high-yield *credit* asset, not a safe bond; the risk didn't vanish, it changed "
            "costume."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (rate protection):** BKLN's beta to the rate factor (long Treasuries) is ≈ 0 — it "
            "does not fall when rates rise.\n"
            "- **H₂ (low risk):** therefore BKLN is a low-risk, bond-like income sleeve.\n"
            "- **H₃ (free lunch):** you get the high yield without taking on a *new* risk in exchange "
            "for giving up duration.\n\n"
            "H₁ is **true** (and certified below). H₂/H₃ are **false** — BKLN loads on equity/credit, "
            "and the loading shows up exactly in the tail."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₂/H₃ held, BKLN would be the dominant "
           "fixed-income holding in a hiking cycle. If the risk merely *moved* to credit, then a "
           "duration-fleeing investor has re-loaded the same portfolio with a recession-timed bomb — "
           "and a 'bond replacement' that fails in a stock crash is mis-filed. This is the same 'is "
           "this asset what the brochure says?' question the desk asked of preferreds "
           "([Study 338](../../338-preferred-stocks/))."),
        md("## 3 · How we'd know — the protocol\n\nReturn/vol/drawdown on the total-return tape · "
           "full-sample beta of BKLN to TLT and IEF (the rate factor) and to SPY, each with a **HAC "
           "*t*** on the OLS-slope influence series · **downside** beta on the worst 10% of equity "
           "days · co-movement in every >5% TLT (rate) drawdown and every >10% SPY (equity) drawdown · "
           "a **circular block bootstrap** CI on the beta *difference* (equity − rate)."),
        md("## 4 · The teardown\n\nHeadline stats — low vol is real, but read it next to the crashes:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [strategy.stats(rets[c])['cagr']*100 for c in (BKLN, TLT, IEF, SPY)],\n"
            "  'Vol %':   [strategy.stats(rets[c])['vol']*100 for c in (BKLN, TLT, IEF, SPY)],\n"
            "  'Sharpe':  [strategy.stats(rets[c])['sharpe'] for c in (BKLN, TLT, IEF, SPY)],\n"
            "  'MaxDD %': [strategy.stats(rets[c])['max_dd']*100 for c in (BKLN, TLT, IEF, SPY)],\n"
            "}, index=[BKLN, f'{TLT} (long bonds)', f'{IEF} (int bonds)', f'{SPY} (equity)'])\n"
            "print(f'[{TAPE}] tape')\n"
            "tbl.round(2)"
        ),
        md("**Rate sensitivity** — OLS beta of BKLN to the duration legs, each with a HAC *t* on the "
           "slope's influence series (mean of the influence series = the OLS slope)."),
        code(
            "b_tlt, t_tlt = strategy.hac_beta_t(rets[BKLN], rets[TLT])\n"
            "b_ief, t_ief = strategy.hac_beta_t(rets[BKLN], rets[IEF])\n"
            "print(f'[{TAPE}]  beta BKLN~{TLT} = {b_tlt:+.3f}  (HAC t {t_tlt:+.2f})')\n"
            "print(f'[{TAPE}]  beta BKLN~{IEF} = {b_ief:+.3f}  (HAC t {t_ief:+.2f})')\n"
            "print(f'downside beta to {TLT} (worst 10% TLT days) = {strategy.downside_beta(rets[BKLN], rets[TLT]):.3f}')"
        ),
        md(
            f"> 💡 **In plain words:** the beta to long Treasuries is **{R['beta_tlt']}** with a HAC *t* "
            f"of **{R['t_tlt']}** — past the *t*=2 bar and *negative*. BKLN's price is essentially "
            "immune to the level of rates. The rate-protection claim is real and certified."
        ),
        md("**Where the risk hides** — BKLN's beta to *equities*, in the body and in the tail."),
        code(
            "b_spy, t_spy = strategy.hac_beta_t(rets[BKLN], rets[SPY])\n"
            "print(f'[{TAPE}]  beta BKLN~{SPY} = {b_spy:+.3f}  (HAC t {t_spy:+.2f})')\n"
            "print(f'downside beta to {SPY} (worst 10% SPY days) = {strategy.downside_beta(rets[BKLN], rets[SPY]):.3f}')"
        ),
        md(
            f"> 💡 **In plain words:** BKLN's beta to *stocks* is **+{R['beta_spy']}** (HAC *t* "
            f"**+{R['t_spy']}**) and the downside beta climbs to **{R['dbeta_spy']}** on the worst "
            "equity days. The risk didn't vanish when duration did — it moved to credit, and it "
            "*intensifies* in the tail."
        ),
        md("**Block-bootstrap on the difference** — is BKLN reliably more of an equity/credit bet than "
           "a duration bet? We resample the three series jointly in blocks and report the CI."),
        code(
            "boot = strategy.bootstrap_beta_diff(rets[BKLN], rets[TLT], rets[SPY], block=21, n_boot=2000, seed=340)\n"
            "print(f'[{TAPE}] beta-to-{SPY} minus beta-to-{TLT} = {boot[\"point\"]:+.3f}')\n"
            "print(f'  95% block-bootstrap CI [{boot[\"ci95\"][0]:+.3f}, {boot[\"ci95\"][1]:+.3f}]')\n"
            "print(f'  BKLN more equity-like in {boot[\"frac_equity_wins\"]*100:.0f}% of resamples')"
        ),
        md(
            f"> 💡 **In plain words:** the point difference is **+{R['boot_diff']}**, the CI "
            f"**[{R['boot_lo']}, {R['boot_hi']}]** excludes zero, and BKLN is the more equity-like asset "
            f"in **{R['boot_wins']}%** of resamples. The duration-for-credit swap is unambiguous."
        ),
        md("**Co-movement, both regimes** — rate selloffs (BKLN survives) and equity crashes (BKLN "
           "piles on):"),
        code(
            "rate_eps = strategy.asset_drawdowns(rets[[TLT, BKLN, IEF, SPY]], TLT, thresh=-0.05)\n"
            "rate = pd.DataFrame([{'peak':e['peak'].date(),'trough':e['trough'].date(),\n"
            "  f'{TLT} %':e['driver_loss']*100, f'{BKLN} %':e['others'][BKLN]*100} for e in rate_eps])\n"
            "crash_eps = strategy.asset_drawdowns(rets[[SPY, BKLN, TLT, IEF]], SPY, thresh=-0.10)\n"
            "crash = pd.DataFrame([{'peak':e['peak'].date(),'trough':e['trough'].date(),\n"
            "  f'{SPY} %':e['driver_loss']*100, f'{BKLN} %':e['others'][BKLN]*100, f'{TLT} %':e['others'][TLT]*100} for e in crash_eps])\n"
            "print(f'[{TAPE}] RATE selloffs (>5% TLT): BKLN rose in {(rate[f\"{BKLN} %\"]>0).sum()}/{len(rate)}')\n"
            "print(f'[{TAPE}] EQUITY crashes (>10% SPY): BKLN fell in {(crash[f\"{BKLN} %\"]<0).sum()}/{len(crash)}')\n"
            "display(rate.round(1)); display(crash.round(1))"
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `REAL` (beta to long bonds {R['beta_tlt']}, HAC *t* {R['t_tlt']}; +{R['rate_bkln']}% "
            f"through the 2020–2023 TLT rout). Tradability `FRAGILE` (real but modest: CAGR "
            f"{R['bkln_cagr']}%, vol {R['bkln_vol']}%; fell {R['crashes_bkln_fell']}/{R['crashes_total']} "
            f"crashes, −24% gap in 2020). Free-lunch? `BUSTED` (beta to equity +{R['beta_spy']}, HAC *t* "
            f"+{R['t_spy']}; equity−rate beta diff +{R['boot_diff']}, CI [{R['boot_lo']}, {R['boot_hi']}])."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Liquidity and capacity are fine in calm markets — BKLN trades heavily. The reservations "
            "are structural: (1) the underlying **leveraged loans** are sub-IG credit settling in "
            "*weeks*, so the ETF sits on an illiquid market and can gap to a discount in a shock "
            "(2020); (2) the fat coupon is compensation for **default + spread + liquidity** risk, not "
            "a free premium for shedding duration; (3) the credit-tail beta means it correlates with "
            "your stocks exactly when you'd want a diversifier. As a tactical duration hedge: "
            "defensible. As a *safe* bond substitute: a mirage of the kind this desk keeps finding."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Run the **two-factor** (duration + credit) regression jointly and read off the loadings "
            "with HAC errors — the single-factor cut here already tells the story, but the joint fit "
            "quantifies the swap.\n"
            "- Decompose BKLN total return into **coupon vs price** to see how much of the 3.7%/yr is "
            "carry being clawed back by 2020/2022 capital losses.\n"
            "- Add **HYG** (high-yield bonds) and **SRLN** (active loans): is the credit-tail behaviour "
            "structural to leveraged credit, or fund-specific?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
