"""Build the two narrative notebooks for Study 99 (Safety-Net — the trailing stop-loss).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``safety_net`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=8400, start="1993-01-29", end="2026-06-12", fp="eb1569cc9e97",
    b_cagr=10.82, b_vol=18.6, b_sharpe=0.646, b_dd=-55.2,
    # per-threshold: 5 / 10 / 15 / 20
    x5_cagr=6.05, x5_vol=12.6, x5_sharpe=0.530, x5_dd=-48.0, x5_tim=76, x5_sw=195,
    x5_edge=-0.116, x5_beats=93, x5_hac=-2.66, x5_gap=-4.77, x5_ddcut=7.1,
    x10_cagr=10.80, x10_vol=15.2, x10_sharpe=0.752, x10_dd=-43.9, x10_tim=92, x10_sw=63,
    x10_edge=0.106, x10_beats=200, x10_hac=-0.39, x10_gap=-0.02, x10_ddcut=11.3,
    x15_cagr=10.85, x15_vol=16.2, x15_sharpe=0.719, x15_dd=-46.7, x15_tim=96, x15_sw=35,
    x15_edge=0.073, x15_beats=200, x15_hac=-0.29, x15_gap=0.03, x15_ddcut=8.5,
    x20_cagr=10.05, x20_vol=16.9, x20_sharpe=0.650, x20_dd=-54.7, x20_tim=98, x20_sw=19,
    x20_edge=0.004, x20_beats=156, x20_hac=-1.06, x20_gap=-0.77, x20_ddcut=0.5,
    beats_n=200,
    # synthetic controls
    syn_trend_stop=0.596, syn_trend_bh=0.422, syn_mr_stop=0.207, syn_mr_bh=0.428,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (safety_net/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from safety_net import data, strategy

AS_OF = "2026-06-12"
COOLDOWN, COST = 21, 5.0
STOPS = (5.0, 10.0, 15.0, 20.0)
frame = data.load_real("SPY", mode="total_return").loc[:AS_OF]
close = frame["close"]
bh = strategy.buy_and_hold(close)
runs = {x: strategy.backtest(close, strategy.trailing_stop_position(close, x, COOLDOWN), cost_bps=COST) for x in STOPS}
stop10 = runs[10.0]
print(f"SPY total return: {len(close):,} rows  {close.index[0].date()} -> {close.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(f"B&H        Sharpe {bh['sharpe']:.3f}  maxDD {bh['max_dd']*100:.1f}%  CAGR {bh['cagr']*100:.2f}%")
print(f"stop 10%   Sharpe {stop10['sharpe']:.3f}  maxDD {stop10['max_dd']*100:.1f}%  CAGR {stop10['cagr']*100:.2f}%  TiM {stop10['time_in_market']*100:.0f}%")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Cuts drawdown?: Mixed](https://img.shields.io/badge/Cuts_drawdown%3F-Mixed-dab617?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# The Safety-Net 🛑\n"
            "### \"Always use a stop-loss\" — does cutting your losses at X% really protect (and pay)?\n\n"
            + HERO_BADGES +
            "The most-repeated rule in retail trading: *cut your losses, let your winners run* — set a "
            "**trailing stop** that sells when price falls X% from its peak. We take it literally on SPY, "
            "sweep the threshold (5 / 10 / 15 / 20%), and ask the two questions that matter: does it "
            "**cut the drawdown** (sometimes — it depends entirely on X), and does it **make you more "
            "money than just holding** (no).\n\n"
            "> 📓 **This is the plain-language layer.** The statistics, the matched-coin control and the "
            "trending-vs-mean-reverting theory are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** "
            "— same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below is "
            "generated by the code beside it. House style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            "| Question | Answer |\n|---|---|\n"
            f"| Does a stop-loss cut the big drawdown? | **Only at the right width.** A **10%** stop trims "
            f"the worst drop to **{R['x10_dd']}%** from **{R['b_dd']}%** (an **{R['x10_ddcut']:.0f}-point** "
            f"cut) — but a **20%** stop cuts almost nothing and a **5%** stop whipsaws. |\n"
            f"| Does it make you more money than holding? | **No.** The best width *matches* buy-and-hold "
            f"(**{R['x10_cagr']}%/yr** vs **{R['b_cagr']}%/yr**); a tight 5% stop **loses "
            f"{abs(R['x5_gap']):.1f} points/yr**. |\n"
            "| So what *is* a stop-loss? | Insurance you pay for in foregone upside — risk control that "
            "works in a narrow band, never a money machine. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Always use a stop-loss. Cut your losses and let your winners run. A trailing stop — exit "
            "when price falls X% from its peak — protects your capital, limits your drawdown, and improves "
            "your returns.\"* You'll find it in every broker tutorial and trading book."
        ),
        md(
            "## 2 · So what?\n\n"
            "If a mechanical stop *both* lowered risk *and* raised return, it would be a free lunch every "
            "investor should take. That's a strong claim — so it deserves a fair, literal test across "
            "several thresholds rather than one flattering chart of 2008."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We hold SPY (dividends included), track its running peak, and **sell to cash the day it falls "
            "X% below that peak**; we wait a **21-day cooldown**, then buy back and reset the peak. We act "
            "**one day after** the trigger (no peeking) and pay **5 bps** per switch. Then we line each X up "
            "against two yardsticks: **buy-and-hold**, and a **random coin** that's out of the market for the "
            "*same total time, in similar-length stretches*, but on random dates. If the stop is just *\"be in "
            "cash sometimes\"*, it won't beat the coin."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the X-sweep: return, risk, and the drawdown each width really cuts."),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [bh['cagr']*100] + [runs[x]['cagr']*100 for x in STOPS],\n"
            "  'Vol %':   [bh['vol']*100]  + [runs[x]['vol']*100 for x in STOPS],\n"
            "  'Sharpe':  [bh['sharpe']]   + [runs[x]['sharpe'] for x in STOPS],\n"
            "  'MaxDD %': [bh['max_dd']*100]+ [runs[x]['max_dd']*100 for x in STOPS],\n"
            "  'TiM %':   [bh['time_in_market']*100] + [runs[x]['time_in_market']*100 for x in STOPS],\n"
            "  'Switches':[bh['switches']] + [runs[x]['switches'] for x in STOPS],\n"
            "}, index=['Buy & hold'] + [f'Stop {int(x)}%' for x in STOPS])\n"
            "tbl.round(2)"
        ),
        md("Now the equity curves and drawdowns — the **10% stop** (its best width) against buy-and-hold."),
        code(
            "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True, height_ratios=[2, 1])\n"
            "ax1.plot(stop10['equity'], label=f\"Trailing stop 10% (Sharpe {stop10['sharpe']:.2f})\", lw=1.3)\n"
            "ax1.plot(bh['equity'], label=f\"Buy & hold (Sharpe {bh['sharpe']:.2f})\", lw=1.3, alpha=.8)\n"
            "ax1.set_yscale('log'); ax1.set_ylabel('Growth of $1 (log)'); ax1.legend(); ax1.set_title('SPY total return - 10% trailing stop vs buy-and-hold')\n"
            "for d, lab in [(stop10, 'stop 10%'), (bh, 'B&H')]:\n"
            "    eq = d['equity']; dd = eq/eq.cummax()-1\n"
            "    ax2.plot(dd, label=f\"{lab} (max {dd.min()*100:.0f}%)\", lw=1.1)\n"
            "ax2.set_ylabel('Drawdown'); ax2.legend(); ax2.set_xlabel('')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "The stop's drawdown is shallower — it ducks part of 2008 — but the two curves **end at "
            "essentially the same place**. You bought a calmer ride; you did not buy more money."
        ),
        md("Now the **matched random coin** at each X — is the stop's *timing* better than random in/out of the same amount?"),
        code(
            "fig, ax = plt.subplots(figsize=(10,4.5))\n"
            "colors = ['C0','C1','C2','C3']\n"
            "for x, c in zip(STOPS, colors):\n"
            "    pos = strategy.trailing_stop_position(close, x, COOLDOWN)\n"
            "    rand = np.array([strategy.backtest(close, strategy.matched_random_position(pos, seed=s), cost_bps=COST)['sharpe'] for s in range(200)])\n"
            "    beats = int((runs[x]['sharpe']>rand).sum())\n"
            "    ax.scatter([x], [runs[x]['sharpe']], color=c, s=90, zorder=3, label=f'stop {int(x)}% (beats {beats}/200)')\n"
            "    ax.errorbar([x], [rand.mean()], yerr=[[rand.mean()-rand.min()],[rand.max()-rand.mean()]], fmt='o', color=c, alpha=.4)\n"
            "ax.axhline(bh['sharpe'], color='k', ls='--', lw=1, label=f\"buy & hold = {bh['sharpe']:.3f}\")\n"
            "ax.set_xlabel('Trailing-stop width X (%)'); ax.set_ylabel('Sharpe'); ax.legend(fontsize=8)\n"
            "ax.set_title('Stop (dot) vs its matched random-exit coins (range) vs buy-and-hold'); plt.show()"
        ),
        md(
            f"At **10% and 15%** the stop beats its random coin **{R['beats_n']}/{R['beats_n']}** times — the "
            f"exit *dates* carry information. But the tight **5%** stop loses to random (**{R['x5_beats']}/{R['beats_n']}**) "
            "— too jumpy, it fires on noise. And **not one width** beats buy-and-hold on return."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Cuts drawdown? → Mixed.** A 10% stop cuts **{R['x10_ddcut']:.0f} points** of drawdown; a "
            f"20% stop cuts **{R['x20_ddcut']:.0f}**; a 5% stop cuts some but **bleeds "
            f"{abs(R['x5_gap']):.1f} pts/yr** doing it. Protection is real only in a middle band.\n"
            f"- **Signal → Weak.** No width out-earns the market: the best (15%) is **+{R['x15_gap']:.2f} "
            f"pts/yr** (a rounding error), 10% *matches* it. The Sharpe gain is lower exposure, not skill.\n"
            f"- **Improves returns? → Mirage.** As a way to *make more money*, the stop-loss doesn't — at "
            "best it trades return for a smoother ride you could buy more cheaply by just holding less stock."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You can — it's just SPY, infinitely liquid. The problem isn't capacity: it's that the product "
            "is *less return (or equal) for less risk*, with the catch that **picking the wrong width hurts** "
            "(5% whipsaws away nearly half your return). Add the **taxes** on dozens of switches and the case "
            "for *\"a stop-loss that improves returns\"* collapses to a mirage."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Does earning the **T-bill** in cash (instead of 0%) close the gap? (It helps, but it's still "
            "de-risking, not alpha.)\n"
            "- A **volatility-scaled** stop (X in units of recent vol) instead of a fixed %.\n"
            "- The theory says stops *help trending assets*: try the same engine on a trend-following CTA "
            "tape or a single momentum name. Fork it and test the Kaminski-Lo split yourself."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# The Safety-Net — a quantitative teardown 🔬\n"
            "### Real total-return tape · X-sweep · HAC inference · exposure-matched placebo · Kaminski-Lo\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim now carrying its standard error.* We separate the two things a trailing stop "
            "does — **reduce drawdown** (real, but only in a width band) and **forecast return** (not "
            "certifiable) — and show the result is exactly the **Kaminski & Lo (2014)** dichotomy: stops help "
            "trending tapes and hurt mean-reverting ones, and a long-biased index sits in the unhelpful zone.\n\n"
            "> ⚠️ **Not investment advice.** SPY daily, total-return adjusted (`quantlab.data`, Yahoo); cash "
            "earns 0% (conservative); 5 bps/switch; 21-day re-entry cooldown; one-day execution lag. Sources "
            "in [`docs/references.md`](../docs/references.md), reproducible run in "
            "[`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `WEAK` | No threshold out-earns buy-and-hold: best is 15% at **+{R['x15_gap']:.2f} "
            f"pts/yr**, 10% matches at **{R['x10_gap']:+.2f}**, 5% is **{R['x5_gap']:+.2f}**. HAC *t* on the "
            f"daily return difference runs **{R['x5_hac']} (5%) to {R['x10_hac']} (10%)** — never a significant "
            f"positive edge. The 10/15% stops beat a matched random-exit coin {R['x10_beats']}/{R['beats_n']}, "
            "so the timing isn't pure noise — but it doesn't pay. |\n"
            f"| **Tradability** | `MIRAGE` | As a *return improver* it fails: best case equals B&H, tight "
            f"stops destroy return ({abs(R['x5_gap']):.1f} pts/yr at 5%). Any Sharpe gain is lower beta, "
            "obtainable more cheaply by holding less stock. |\n"
            f"| **Cuts drawdown?** | `MIXED` | maxDD cut is **{R['x10_ddcut']:.0f} pts at 10%** but only "
            f"**{R['x20_ddcut']:.0f} pts at 20%**; the 5% stop cuts drawdown yet whipsaws return. Protection "
            "is genuine only in a middle width band. |\n\n"
            "> 💡 **In plain words:** the stop-loss is a *drawdown reducer that works at one dial setting* "
            "wearing the costume of a *return booster that doesn't exist*."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (risk):** a trailing stop lowers drawdown and volatility vs buy-and-hold.\n"
            "- **H₂ (skill):** the stop's *exit dates* beat an exposure-matched random schedule.\n"
            "- **H₃ (the sold claim):** the stop *improves returns* / risk-adjusted return.\n\n"
            "Kaminski & Lo (2014): the stopping premium has the **sign of the return autocorrelation** — "
            "positive (helps) for trending assets, negative (hurts) for mean-reverting ones. A long-biased "
            "index with short-horizon mean reversion should land near or below zero on H₃."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₃ held, the simplest risk rule on Earth would "
           "be a return engine too. It doesn't — and seeing *why* (the V-shaped rebounds the stop sells into) "
           "is the Kaminski-Lo lesson made concrete."),
        md("## 3 · How we'd know — the protocol\n\nSweep X over 5/10/15/20% · HAC inference on each return "
           "difference · exposure-matched random-exit placebo at each X · the trending-vs-mean-reverting "
           "synthetic controls that pin the theory."),
        md("## 4 · The teardown\n\nThe full X-sweep, all net of 5 bps/switch:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [bh['cagr']*100] + [runs[x]['cagr']*100 for x in STOPS],\n"
            "  'Vol %':   [bh['vol']*100]  + [runs[x]['vol']*100 for x in STOPS],\n"
            "  'Sharpe':  [bh['sharpe']]   + [runs[x]['sharpe'] for x in STOPS],\n"
            "  'MaxDD %': [bh['max_dd']*100]+ [runs[x]['max_dd']*100 for x in STOPS],\n"
            "  'TiM %':   [bh['time_in_market']*100] + [runs[x]['time_in_market']*100 for x in STOPS],\n"
            "}, index=['Buy & hold'] + [f'Stop {int(x)}%' for x in STOPS])\n"
            "tbl.round(3)"
        ),
        md("**HAC inference + matched random-exit placebo** at each threshold — is any edge real, and does the timing beat random?"),
        code(
            "rows = []\n"
            "for x in STOPS:\n"
            "    pos = strategy.trailing_stop_position(close, x, COOLDOWN)\n"
            "    st = runs[x]\n"
            "    diff = (st['net']-bh['net']).to_numpy()\n"
            "    t = strategy.hac_tstat(diff)\n"
            "    rand = np.array([strategy.backtest(close, strategy.matched_random_position(pos, seed=s), cost_bps=COST)['sharpe'] for s in range(200)])\n"
            "    rows.append({'X %': int(x), 'Sharpe-B&H': st['sharpe']-bh['sharpe'], 'HAC t (ret diff)': t,\n"
            "                 'beats coin /200': int((st['sharpe']>rand).sum()), 'CAGR gap pts': (st['cagr']-bh['cagr'])*100,\n"
            "                 'DD cut pts': (st['max_dd']-bh['max_dd'])*100})\n"
            "pd.DataFrame(rows).set_index('X %').round(3)"
        ),
        md(
            "> 💡 **In plain words:** at 10–15% the stop's exits land in genuinely better spots than random "
            "(beats the coin 200/200) — but the *return* difference's HAC *t* is near zero or negative, so it "
            "never out-earns the market. The 5% stop has a *significantly negative* edge (t = "
            f"{R['x5_hac']}): too tight, it whipsaws."
        ),
        md("**The Kaminski-Lo dichotomy, on synthetic tapes** — the machinery proof that the engine banks the edge where it should and not where it shouldn't:"),
        code(
            "trend, _ = data.synthetic_trending(n_days=6000, seed=99)\n"
            "mr, _ = data.synthetic_meanrev(n_days=6000, seed=99)\n"
            "for label, fr in [('TRENDING (stops help)', trend), ('MEAN-REVERTING (stops hurt)', mr)]:\n"
            "    c = fr['close']\n"
            "    st = strategy.backtest(c, strategy.trailing_stop_position(c, 10.0, COOLDOWN), cost_bps=COST)\n"
            "    b = strategy.buy_and_hold(c)\n"
            "    win = 'stop WINS' if st['sharpe']>b['sharpe'] else 'stop LOSES'\n"
            "    print(f\"{label:30s}  stop Sharpe {st['sharpe']:.3f}  vs  B&H {b['sharpe']:.3f}   -> {win}\")"
        ),
        md(
            "> 💡 **In plain words:** plant a persistent downtrend and the stop escapes it (wins); plant "
            "mean reversion and the stop sells every dip into the rebound (loses). SPY behaves like the "
            "second case — which is why the real stop doesn't pay. *(Synthetic Sharpes are a positive "
            "control for the harness, never market evidence for the stamp.)*"
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `WEAK` (no width out-earns B&H; HAC *t* on the return diff {R['x5_hac']} to "
            f"{R['x10_hac']}; 10/15% beat the matched coin {R['x10_beats']}/{R['beats_n']}), Tradability "
            f"`MIRAGE` (best case equals B&H, tight stops lose {abs(R['x5_gap']):.1f} pts/yr), Cuts drawdown? "
            f"`MIXED` ({R['x10_ddcut']:.0f} pts at 10% vs {R['x20_ddcut']:.0f} pts at 20%). The drawdown cut is "
            "lower exposure; the return claim is the mean-reversion the index keeps handing back."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (SPY). The binding facts are economic: (1) the strategy delivers **equal "
            "or less return for less risk** — a lower-beta book a 90/10 stock/cash blend reproduces without "
            "dozens of taxable switches; and (2) **width risk is real** — a plausibly-chosen 5% stop costs "
            "4.8 pts/yr. Net of tax the gap to buy-and-hold only widens."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Replace 0% cash with the **T-bill** (`^IRX`) and recompute excess-of-cash for both arms.\n"
            "- A **volatility-targeted** trailing stop (X in ATR / realised-vol units) vs the fixed %.\n"
            "- Test the engine on **trending** assets (managed-futures, single-name momentum) where "
            "Kaminski-Lo predict the stop *should* earn its keep — does the desk's harness confirm it live?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
