"""Notebook builder for Study 1001 — The Leaky Fold.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Leaky Fold \U0001F9EA
### Your model passed cross-validation. That is not the good news it sounds like.

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Split the data into five folds, train on four, test on the fifth, repeat. It is the first thing
anyone learns about model evaluation and it is *wrong* on time series — for two separate
reasons, only one of which is the one everybody warns you about.

> \U0001F4D3 **This is the plain-language layer.** The scheme implementations, the leak
> decomposition and the planted-signal control are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does shuffled cross-validation overstate a time-series model? | Substantially. |
| Is "don't shuffle" enough? | No — it fixes less than half the problem. |
| What is the other half? | Overlapping labels. |
| Is there a fix? | Yes, and it costs data rather than accuracy. |
"""
        ),
        md(
            r"""

## 1 · A model that knows nothing
"""
        ),
        code(
            r"""
from leakyfold import data, strategy as st

px_all = data.load_prices()
px = px_all[data.EQUITY].dropna()
F = st.make_features(px)
L = st.make_labels(px, 20)
common = F.index.intersection(L.index)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(common):,} observations, "
      f"{F.shape[1]} features")
print(f"label: the next 20 sessions' return")
print(f"two adjacent labels share {st.overlap_fraction(20, 1):.0%} of their days")
"""
        ),
        code(
            r"""
w = st.synthetic_panel(n=4000, predictability=0.0, horizon=20)
print("Data where the features are GUARANTEED to have no predictive power at all.")
c = st.compare_schemes(w["features"], w["labels"], k=5)
print()
print(c[["ic", "r2", "mean_train_size"]].round(4).to_string())
"""
        ),
        md(
            r"""

The first row is what a tutorial would print. There is nothing to find — the features were
generated independently of the labels — and it reports skill anyway.
"""
        ),
        md(
            r"""

## 2 · Why: the two leaks
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
n = 300
for ax, (name, folds) in zip(axes, [
        ("shuffled k-fold", st.kfold_shuffled(n, 5)),
        ("sequential k-fold", st.kfold_sequential(n, 5)),
        ("walk-forward", st.walk_forward(n, 5))]):
    train, test = folds[2]
    strip = np.full(n, 0.0)
    strip[np.asarray(train)] = 1.0
    strip[np.asarray(test)] = 2.0
    ax.imshow(strip.reshape(1, -1), aspect="auto", cmap="RdYlGn",
              extent=[0, n, 0, 1], vmin=0, vmax=2)
    ax.set_yticks([]); ax.set_ylabel(name, fontsize=8, rotation=0, ha="right",
                                     va="center")
axes[-1].set_xlabel("time -->")
axes[0].set_title("green = training, red = test, pale = unused (fold 3 of 5)")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

**Leak one** is visible in the top strip: green appears to the right of red. The model trains on
the future.

**Leak two** is invisible in any of these pictures, and it is the bigger one.
"""
        ),
        code(
            r"""
print("Predicting the next 20 days means observation t and t+1 share 19 of 20 days.")
for hz in (1, 5, 20, 60, 120):
    print(f"  a {hz:3d}-day label overlaps its neighbour by "
          f"{st.overlap_fraction(hz, 1):5.1%}")
print()
print("So the training point immediately before the test block is, for practical purposes,")
print("the first test point. No date is out of order. The answer still leaked.")
"""
        ),
        md(
            r"""

## 3 · The fix, and what it costs
"""
        ),
        code(
            r"""
L = w["labels"]
n = len(L)
plain = st.kfold_sequential(n, 5)
purged = st.purged_kfold(L, 5, embargo=0.0)
emb = st.purged_kfold(L, 5, embargo=0.05)
fig, axes = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
for ax, (name, folds) in zip(axes, [("sequential", plain), ("purged", purged),
                                     ("purged + embargo", emb)]):
    train, test = folds[2]
    strip = np.full(n, 0.0)
    strip[np.asarray(train)] = 1.0
    strip[np.asarray(test)] = 2.0
    ax.imshow(strip.reshape(1, -1), aspect="auto", cmap="RdYlGn",
              extent=[0, n, 0, 1], vmin=0, vmax=2)
    ax.set_yticks([])
    ax.set_ylabel(f"{name}\n({len(train):,} train)", fontsize=7, rotation=0,
                  ha="right", va="center")
axes[-1].set_xlabel("time -->")
axes[0].set_title("The pale bands around the test block are what purging removes")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The gap on the *left* of the test block is purging — training
> labels that reach into the test period. The gap on the *right* is the embargo — training
> points whose features are still correlated with the test period.
"""
        ),
        md(
            r"""

## 4 · Does it work?
"""
        ),
        code(
            r"""
rows = []
for pred in (0.0, 0.5, 1.0, 2.0, 3.0):
    ww = st.synthetic_panel(n=6000, predictability=pred, horizon=20)
    cc = st.compare_schemes(ww["features"], ww["labels"], k=5, embargo=0.01)
    rows.append({"planted": pred, "shuffled": cc.loc["k-fold, shuffled", "ic"],
                 "purged + embargo": cc.loc["purged + embargo", "ic"],
                 "walk-forward": cc.loc["walk-forward", "ic"]})
d = pd.DataFrame(rows).set_index("planted")
fig, ax = plt.subplots(figsize=(10, 5))
d.plot(ax=ax, marker="o", color=["#c0392b", "#2ea44f", "#1f6feb"])
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("how much real predictability was planted")
ax.set_ylabel("reported information coefficient"); ax.legend(fontsize=9, title="")
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

Look at the left edge, where nothing was planted. The red line is well above zero — that is the
illusion. The green and blue lines are at zero, which is correct. Then follow them right: they
rise with the real signal, so the fix has not simply blinded the model.
"""
        ),
        md(
            r"""

## 5 · On the real market
"""
        ),
        code(
            r"""
c = st.compare_schemes(F, L, 5, 0.01)
fig, ax = plt.subplots(figsize=(10, 4.5))
colors = ["#c0392b", "#f0b429", "#2ea44f", "#2ea44f", "#1f6feb"]
ax.barh(range(len(c)), c["ic"], color=colors[:len(c)])
ax.axvline(0, color="k", lw=1)
ax.set_yticks(range(len(c))); ax.set_yticklabels(c.index, fontsize=9)
ax.set_xlabel("information coefficient reported")
plt.show()
d = st.leakage_decomposition(F, L, 5, 0.01)
print(f"shuffled says:      {d['shuffled_ic']:+.4f}")
print(f"walk-forward says:  {d['walk_forward_ic']:+.4f}")
print(f"  of the gap, {d['temporal_leak']:+.4f} is seeing the future")
print(f"  and {d['overlap_leak']:+.4f} is overlapping labels "
      f"({d['overlap_share']:.0%} of the total)")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Confirmed.** On SPY with a 20-day forward label, ordinary shuffled five-fold cross-validation reported an information coefficient of **+0.078** (R² +0.005). Walk-forward validation — the only scheme that resembles how a model is actually used — reported **-0.021**. The gap is **+0.099**, and it splits into two quite different causes. Letting the model see the future at all (shuffled minus sequential) is worth +0.052. **Label overlap** — neighbouring observations sharing 95% of their label days, with no date out of order whatsoever — is worth -0.002, which is **-2% of the total illusion**. That second channel is invisible to the usual advice about not shuffling time series, and at long label horizons it is the bigger one: the sweep shows it growing from +0.000 at a one-day label to +0.005 at 120 days.

**Tradability: Partial.** The fix works and it is cheap. Purging training observations whose label windows touch the test block brought the estimate to +0.028; adding a 1% embargo brought it to **+0.029** against walk-forward's -0.021 — a residual difference of 0.0501. And it does not achieve that by destroying everything: on synthetic data with a **planted** information coefficient of 1.00, purged-and-embargoed cross-validation recovered +0.855, so it still finds real signal. The cost is data: purging removed 0% of the training set at this horizon, which is the real reason people skip it.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Shorten your labels.** A one-day label has no overlap and nothing to purge. Much of this
  problem is a consequence of predicting long horizons with daily observations.
- **Walk-forward if you can afford it.** It uses less data, which is a real cost, but it needs
  no correction and cannot be got wrong.
- **Purge the features too.** This study purges on label windows. Features built from long
  lookbacks reach backward across the boundary as well, and a fully rigorous version would
  handle both.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Leaky Fold — a quantitative teardown \U0001F52C
### Five schemes on identical data · temporal vs overlap leakage · purging and embargo

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The finding that
matters is the decomposition: most of the illusion at realistic label horizons comes from
**overlapping labels**, not from shuffling — so a sequential split, which most people believe is
the fix, leaves the larger half of the problem in place.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from leakyfold import data, strategy as st

px_all = data.load_prices()
px = px_all[data.EQUITY].dropna()
F = st.make_features(px)
L = st.make_labels(px, 20)
common = F.index.intersection(L.index)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(common):,} observations, "
      f"{F.shape[1]} features")
print(f"label: the next 20 sessions' return")
print(f"two adjacent labels share {st.overlap_fraction(20, 1):.0%} of their days")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | On SPY with a 20-day forward label, ordinary shuffled five-fold cross-validation reported an information coefficient of **+0.078** (R² +0.005). Walk-forward validation — the only scheme that resembles how a model is actually used — reported **-0.021**. The gap is **+0.099**, and it splits into two quite different causes. Letting the model see the future at all (shuffled minus sequential) is worth +0.052. **Label overlap** — neighbouring observations sharing 95% of their label days, with no date out of order whatsoever — is worth -0.002, which is **-2% of the total illusion**. That second channel is invisible to the usual advice about not shuffling time series, and at long label horizons it is the bigger one: the sweep shows it growing from +0.000 at a one-day label to +0.005 at 120 days. |
| **Tradability** | Partial | The fix works and it is cheap. Purging training observations whose label windows touch the test block brought the estimate to +0.028; adding a 1% embargo brought it to **+0.029** against walk-forward's -0.021 — a residual difference of 0.0501. And it does not achieve that by destroying everything: on synthetic data with a **planted** information coefficient of 1.00, purged-and-embargoed cross-validation recovered +0.855, so it still finds real signal. The cost is data: purging removed 0% of the training set at this horizon, which is the real reason people skip it. |

> \U0001F4A1 **In plain words.** The leak everyone warns about is the smaller one.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** On data with *zero* predictability, shuffled k-fold reports a positive information
  coefficient.
- **H₂ (decomposition).** The illusion splits into temporal leakage (shuffled − sequential) and
  label overlap (sequential − purged), and at a 20-day horizon the second is the larger.
- **H₃ (scaling).** The overlap leak grows with the label horizon and vanishes at a one-day
  label.
- **H₄ (the fix works).** Purging plus embargo agrees with walk-forward.
- **H₅ (the fix does not overcorrect).** It still detects a planted signal, and its estimate
  rises with the planted strength.
"""
        ),
        md(
            r"""

## 2 · The schemes, verified

Before measuring anything, the fold constructions are checked for the properties they claim.
"""
        ),
        code(
            r"""
# NB: a distinct name. `L` holds the REAL labels from the load cell and later cells
# still need it; shadowing it here with the synthetic ones breaks them silently.
n = 2000
w = st.synthetic_panel(n=n, horizon=20)
Lsim = w["labels"]
checks = []
for name, folds in (("shuffled", st.kfold_shuffled(len(Lsim), 5)),
                    ("sequential", st.kfold_sequential(len(Lsim), 5)),
                    ("purged", st.purged_kfold(Lsim, 5, 0.0)),
                    ("purged+embargo", st.purged_kfold(Lsim, 5, 0.02)),
                    ("walk-forward", st.walk_forward(len(Lsim), 5))):
    overlaps = sum(len(np.intersect1d(t, te)) for t, te in folds)
    future = sum(int((np.asarray(t) > np.asarray(te).min()).sum() > 0) for t, te in folds)
    starts = Lsim["label_start"].to_numpy(); ends = Lsim["label_end"].to_numpy()
    touch = 0
    for t, te in folds:
        t0, t1 = starts[np.asarray(te)[0]], ends[np.asarray(te)[-1]]
        touch += int(((ends[np.asarray(t)] >= t0) & (starts[np.asarray(t)] <= t1)).sum())
    checks.append({"scheme": name, "train/test overlap": overlaps,
                   "folds training on the future": future,
                   "training labels touching the test window": touch,
                   "mean train size": int(np.mean([len(t) for t, _ in folds]))})
print(pd.DataFrame(checks).set_index("scheme").to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The third column is the one that matters and the one that is
> almost never checked. Sequential k-fold scores zero on "training on the future" and thousands
> on "training labels touching the test window" — which is why it is not the fix people think it
> is.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Five schemes, zero true signal
"""
        ),
        code(
            r"""
rows = []
for k in range(6):
    ww = st.synthetic_panel(n=5000, predictability=0.0, horizon=20, seed=1001 + k)
    cc = st.compare_schemes(ww["features"], ww["labels"], k=5, embargo=0.01)
    for name, r in cc.iterrows():
        rows.append({"run": k, "scheme": name, "ic": r["ic"], "r2": r["r2"]})
d = pd.DataFrame(rows)
summary = d.groupby("scheme")[["ic", "r2"]].agg(["mean", "std"])
print(summary.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 5))
order = ["k-fold, shuffled", "k-fold, sequential", "purged k-fold", "purged + embargo",
         "walk-forward"]
data_by = [d[d["scheme"] == s]["ic"].to_numpy() for s in order]
ax.boxplot(data_by, tick_labels=[s.replace(", ", ",\n") for s in order])
ax.axhline(0, color="#c0392b", lw=2, ls="--", label="the truth (no signal)")
ax.set_ylabel("reported information coefficient"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), fontsize=7)
plt.show()
"""
        ),
        md(
            r"""

### 3.2 The decomposition
"""
        ),
        code(
            r"""
rows = []
for hz in (1, 5, 10, 20, 40, 60, 120):
    ww = st.synthetic_panel(n=6000, predictability=0.0, horizon=hz)
    dd = st.leakage_decomposition(ww["features"], ww["labels"], k=5, embargo=0.01)
    if not dd:
        continue
    rows.append({"horizon": hz, "overlap": st.overlap_fraction(hz, 1),
                 "temporal leak": dd["temporal_leak"],
                 "overlap leak": dd["overlap_leak"],
                 "total illusion": dd["total_illusion"]})
d = pd.DataFrame(rows).set_index("horizon")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
d[["temporal leak", "overlap leak"]].plot.bar(ax=axes[0], stacked=True,
                                              color=["#f0b429", "#c0392b"])
axes[0].plot(range(len(d)), d["total illusion"], "ko-", lw=2, label="total")
axes[0].set_ylabel("information coefficient"); axes[0].legend(fontsize=8)
plt.setp(axes[0].get_xticklabels(), rotation=0)
share = (d["overlap leak"] / d["total illusion"]).clip(0, 1)
axes[1].plot(d.index, share * 100, "o-", lw=2, color="#c0392b")
axes[1].set_xlabel("label horizon (sessions)")
axes[1].set_ylabel("overlap's share of the illusion (%)")
axes[1].set_title("the leak nobody warns about, as the horizon grows")
plt.tight_layout(); plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.3 On the real tape, every asset
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    if tk == data.CASH or tk not in px_all.columns:
        continue
    s = px_all[tk].dropna()
    if len(s) < 1500:
        continue
    f2, l2 = st.make_features(s), st.make_labels(s, 20)
    dd = st.leakage_decomposition(f2, l2, 5, 0.01)
    if dd:
        rows.append({"asset": tk, **dd})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(11, 5))
d[["shuffled_ic", "sequential_ic", "purged_ic", "embargo_ic",
   "walk_forward_ic"]].plot.bar(ax=ax)
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("information coefficient"); ax.legend(fontsize=7, title="")
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
"""
        ),
        md(
            r"""

### 3.4 The cost of purging
"""
        ),
        code(
            r"""
rows = []
for hz in (1, 5, 20, 60, 120, 250):
    ww = st.synthetic_panel(n=6000, horizon=hz)
    LL = ww["labels"]
    plain = np.mean([len(t) for t, _ in st.kfold_sequential(len(LL), 5)])
    purged = np.mean([len(t) for t, _ in st.purged_kfold(LL, 5, 0.0)])
    emb = np.mean([len(t) for t, _ in st.purged_kfold(LL, 5, 0.05)])
    rows.append({"horizon": hz, "plain": plain, "purged": purged, "with embargo": emb,
                 "purged loss": 1 - purged / plain, "embargo loss": 1 - emb / plain})
d = pd.DataFrame(rows).set_index("horizon")
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.plot(d.index, d["purged loss"] * 100, "o-", lw=2, color="#c0392b", label="purging")
ax.plot(d.index, d["embargo loss"] * 100, "s-", lw=2, color="#f0b429",
        label="purging + 5% embargo")
ax.set_xlabel("label horizon (sessions)")
ax.set_ylabel("training data removed (%)"); ax.legend(fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

### 3.5 The planted-signal control
"""
        ),
        code(
            r"""
rows = []
for pred in (0.0, 0.25, 0.5, 1.0, 1.5, 2.0, 3.0):
    for k in range(3):
        ww = st.synthetic_panel(n=6000, predictability=pred, horizon=20, seed=1001 + k)
        cc = st.compare_schemes(ww["features"], ww["labels"], k=5, embargo=0.01)
        rows.append({"planted": pred, "shuffled": cc.loc["k-fold, shuffled", "ic"],
                     "purged+embargo": cc.loc["purged + embargo", "ic"],
                     "walk-forward": cc.loc["walk-forward", "ic"]})
d = pd.DataFrame(rows).groupby("planted").mean()
fig, ax = plt.subplots(figsize=(10, 5.5))
d.plot(ax=ax, marker="o", color=["#c0392b", "#2ea44f", "#1f6feb"])
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("planted predictability"); ax.set_ylabel("reported IC")
ax.legend(fontsize=9, title="")
ax.set_title("At zero: the red line is the illusion. Rightward: all three should rise.")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** A fix is only a fix if it satisfies both ends of this chart:
> zero when there is nothing, and rising when there is something. Reporting zero always would be
> easy and useless.
"""
        ),
        md(
            r"""

### 3.6 Folds, embargo, and how much they matter
"""
        ),
        code(
            r"""
rows = []
for k in (3, 5, 10, 20):
    for e in (0.0, 0.005, 0.01, 0.02, 0.05, 0.10):
        cc = st.compare_schemes(F, L, k, e)
        rows.append({"k": k, "embargo": e,
                     "purged+embargo": cc.loc["purged + embargo", "ic"],
                     "walk-forward": cc.loc["walk-forward", "ic"],
                     "gap": cc.loc["purged + embargo", "ic"]
                     - cc.loc["walk-forward", "ic"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5))
piv = d.pivot(index="embargo", columns="k", values="gap")
piv.plot(ax=ax, marker="o")
ax.axhline(0, color="k", lw=1.5, label="agrees with walk-forward")
ax.set_xlabel("embargo (fraction of the sample)")
ax.set_ylabel("purged+embargo IC minus walk-forward IC")
ax.legend(fontsize=8, title="folds")
plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

### 3.7 A harder model leaks harder
"""
        ),
        code(
            r"""
rows = []
for ridge in (1e-6, 1e-3, 1e-1, 1.0, 10.0):
    cc = st.compare_schemes(F, L, 5, 0.01, ridge=ridge)
    rows.append({"ridge": ridge, "shuffled": cc.loc["k-fold, shuffled", "ic"],
                 "purged+embargo": cc.loc["purged + embargo", "ic"],
                 "walk-forward": cc.loc["walk-forward", "ic"],
                 "illusion": cc.loc["k-fold, shuffled", "ic"]
                 - cc.loc["walk-forward", "ic"]})
d = pd.DataFrame(rows).set_index("ridge")
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.semilogx(d.index, d["illusion"], "o-", lw=2, color="#c0392b")
ax.set_xlabel("ridge penalty (less regularisation to the left)")
ax.set_ylabel("size of the illusion")
ax.set_title("A less constrained model exploits the leak harder")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
dd = st.leakage_decomposition(F, L, 5, 0.01)
plain = np.mean([len(t) for t, _ in st.kfold_sequential(len(common), 5)])
purged = np.mean([len(t) for t, _ in st.purged_kfold(L.loc[common], 5, 0.0)])
ww = st.synthetic_panel(n=6000, predictability=1.0, horizon=20)
cc = st.compare_schemes(ww["features"], ww["labels"], 5, 0.01)
pd.DataFrame({
    "shuffled CV says": [dd["shuffled_ic"]],
    "walk-forward says": [dd["walk_forward_ic"]],
    "the illusion": [dd["total_illusion"]],
    "from seeing the future": [dd["temporal_leak"]],
    "from overlapping labels": [dd["overlap_leak"]],
    "overlap's share": [dd["overlap_share"]],
    "purged+embargo says": [dd["embargo_ic"]],
    "its gap to walk-forward": [dd["embargo_ic"] - dd["walk_forward_ic"]],
    "training data purging costs": [1 - purged / plain],
    "planted IC=1.0 recovered by purged CV": [cc.loc["purged + embargo", "ic"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Combinatorial purged CV** (López de Prado 2018, ch. 12) generates many train/test paths
  rather than one, giving a *distribution* of out-of-sample performance instead of a point
  estimate. It is the natural upgrade and it costs only compute.
- **Purge on features as well as labels.** A 63-day momentum feature reaches 63 days backward
  across a fold boundary. This study purges label windows only, so its estimates remain slightly
  optimistic.
- **hv-block CV** (Racine 2000) reached essentially the same construction eighteen years earlier
  from the statistics side; comparing the two conventions on the same data would be a useful
  short note.
- **Add hyperparameter tuning.** Real pipelines select on the validation folds, which compounds
  everything here — the interaction between leakage and selection is larger than either alone.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
