"""Real-data run — does cross-sectional momentum still pay on the S&P 500, and at what tail cost?

Four questions (the offline core proves the machine on a baked-momentum panel; this points it at the
market):

  * **Do winners out-earn losers?** The decile forward-return profile and the WML CAPM alpha (HAC).
  * **Can a long-only investor capture it?** Winners vs the equal-weight market.
  * **What does it cost when the herd turns?** The crash profile — skew, worst months, deepest drawdown.
  * **Can the crash be managed?** Vol-scaling the WML factor (Barroso-Santa-Clara / Study 16's overlay).

    python examples/verify.py --fetch     # populate the S&P 500 panel cache (network)
    python examples/verify.py             # offline, cache-only

Network lives only behind `--fetch`. Pinned with `quantlab.repro.as_of` and fingerprinted. Data choices:
total-return closes; current S&P 500 membership (survivorship bias — ranking robust, magnitudes not).
"""

import argparse
import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from stampede import data, momentum, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "results.md")
COST_BPS = 5.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()

    rets = data.fetch_panel(fetch=args.fetch)
    if rets.empty:
        print("[skip] no cached S&P 500 panel -- run with --fetch first.")
        return
    rets = as_of(rets, DEFAULT_AS_OF)

    sp = momentum.momentum_spread(rets)
    cmp = strategy.compare(rets, cost_bps=COST_BPS)
    a = decompose.capm_alpha(rets, cost_bps=COST_BPS)
    cr = decompose.crash_profile(rets, cost_bps=COST_BPS)
    sub = decompose.subsample_sharpe(rets, cost_bps=COST_BPS)
    boot = decompose.sharpe_bootstrap(rets, n_boot=2000, seed=0, cost_bps=COST_BPS)
    cc = extension.crash_comparison(rets, cost_bps=COST_BPS)
    fp = fingerprint(rets.round(6))

    print(f"WML alpha {a['alpha_ann_pct']:+.1f}% (t{a['alpha_t']:+.1f}) SR {cmp['wml']['sharpe']:+.2f} | "
          f"crash maxDD {cr['max_drawdown_pct']:.0f}%, worst month {cr['worst_month_pct']:+.1f}%")
    _write(OUT, dict(sp=sp, cmp=cmp, a=a, cr=cr, sub=sub, boot=boot, cc=cc, fp=fp,
                     lo=rets.index.min().date(), hi=rets.index.max().date(),
                     n_stocks=rets.shape[1], n_days=len(rets)), DEFAULT_AS_OF)
    print(f"\nwrote {OUT}")


def _verdict(d):
    a = d["a"]
    signal = "REAL" if a["alpha_t"] > 2.0 and a["alpha_ann_pct"] > 0 else "WEAK"
    # severe crash + thin standalone -> FRAGILE (salvageable by vol-management, so not MIRAGE)
    trad = "FRAGILE" if d["cmp"]["wml"]["sharpe"] < 0.5 else "INVESTABLE"
    crash = "Severe" if d["cr"]["max_drawdown_pct"] < -40 else "Moderate"
    return signal, trad, crash


def _write(path, d, asof):
    signal, trad, crash = _verdict(d)
    deciles = d["sp"]["decile_fwd_ann"]
    dec_rows = "\n".join(f"| {int(b)} | {v:+.1f} |" for b, v in deciles.items())
    sub_rows = "\n".join(f"| {r['start']} → {r['end']} | {r['sharpe']:+.2f} |" for _, r in d["sub"].iterrows())
    a, cmp, cr, cc = d["a"], d["cmp"], d["cr"], d["cc"]
    text = f"""# Results — Study 24 (Stampede) on the real S&P 500 cross-section

*Generated by [`examples/verify.py`](../examples/verify.py). Daily split/dividend-adjusted closes for
the **current** S&P 500 (≥2,500 sessions), differenced to returns; the strategy is the 12-1 momentum
WML factor (long the top decile, short the bottom, monthly rebalance), {COST_BPS:.0f} bp per unit
traded. The offline core proves the machinery on a synthetic momentum panel; this is the measurement on
the market. As-of **{asof}**; match the fingerprint below. **Survivorship caveat:** current membership
excludes delisted names — the ranking is robust, precise magnitudes are not.*

## The verdict, earned — Signal `{signal}` · Tradability `{trad}` · Crash risk? `{crash}`

Momentum is the most robust anomaly in finance — and our synthetic control recovers it overwhelmingly
(a WML alpha at HAC *t* ≈ 14). But on the modern S&P 500 it is **faint and dangerous**. The 12-1 WML
factor earns an alpha of **{a['alpha_ann_pct']:+.1f}%/yr** (HAC *t* = **{a['alpha_t']:+.1f}**) — not
distinguishable from zero on this large-cap, post-2009, survivorship-biased sample — at a standalone
Sharpe of **{cmp['wml']['sharpe']:+.2f}**. And it carries a brutal tail: a worst month of
**{cr['worst_month_pct']:+.1f}%**, a worst-five-month average of **{cr['worst5_months_mean_pct']:+.1f}%**,
and a maximum drawdown of **{cr['max_drawdown_pct']:.0f}%** — the signature momentum crash, when crushed
losers violently rebound and the short leg detonates. The one good news: the crash is *forecastable* —
vol-scaling the factor cuts the drawdown from **{cc['plain']['max_drawdown_pct']:.0f}%** to
**{cc['managed']['max_drawdown_pct']:.0f}%**. A real premium in principle, decayed and crash-prone in
practice.

## Data stamp

- **Universe**: {d['n_stocks']} names, {d['lo']} → {d['hi']}, {d['n_days']} sessions, fingerprint `{d['fp']}`

## Do winners out-earn losers? (forward return by 12-1 momentum decile)

| decile (0 = losers, 9 = winners) | forward return (annualised %) |
|---|---|
{dec_rows}

Top-minus-bottom (WML) spread **{d['sp']['wml_ann_pct']:+.1f}%/yr** before risk adjustment; winners
long-only Sharpe **{cmp['winners']['sharpe']:+.2f}** vs the equal-weight market **{cmp['market']['sharpe']:+.2f}**.

## Is the premium real here?

- **WML CAPM alpha** **{a['alpha_ann_pct']:+.1f}%/yr** (HAC *t* = **{a['alpha_t']:+.1f}**), beta
  **{a['beta']:+.2f}**, turnover **{cmp['turnover_ann']:.0f}×/yr**.
- **Bootstrap WML Sharpe** **{d['boot']['sharpe']:+.2f}**, 95% CI
  **[{d['boot']['ci_low']:+.2f}, {d['boot']['ci_high']:+.2f}]**.
- **Sub-sample Sharpe**:

| sub-period | WML net Sharpe |
|---|---|
{sub_rows}

## The crash — momentum's defining flaw

- Monthly skew **{cr['monthly_skew']:+.2f}**; worst month **{cr['worst_month_pct']:+.1f}%**; worst-5
  average **{cr['worst5_months_mean_pct']:+.1f}%**; max drawdown **{cr['max_drawdown_pct']:.0f}%**.
- **Risk-managed** (vol-scaled WML): Sharpe **{cc['plain']['sharpe']:+.2f} → {cc['managed']['sharpe']:+.2f}**,
  max drawdown **{cc['plain']['max_drawdown_pct']:.0f}% → {cc['managed']['max_drawdown_pct']:.0f}%** — the
  crash is forecastable and can be tamed, at the cost of leverage in calm regimes (cf. [Study 16](../../16-storm-shy/)).

Signal `{signal}`, Tradability `{trad}`, Crash risk? `{crash}`.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
