"""Real-data run — the headline numbers behind Study 08's verdict.

Loads the cached liquid US universe (the parquets Study 04 cached, split-only), winsorizes
bad prints, and runs the full gauntlet:

    machinery sanity (synthetic structure recall)  ->  level collinearity of the three
    z-scored oscillators  ->  is the TSI spanned by MACD+RSI? (incremental-information R²)
    ->  do the positions agree? (sign agreement)  ->  are the equity curves the same curve?
    ->  the broker statement (default TSI crossover, the table QuantifiedStrategies quotes)
    ->  Reality Check on the 24-variant TSI grid  ->  cost sweep.

    python examples/verify_real.py

Prints every table and writes a reproducible results doc (as-of date + a content fingerprint
of the price inputs) to docs/results.md. Cache-only: names with no parquet are skipped.
"""

import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from true_strength import backtest, collinearity, data
from quantlab.repro import DEFAULT_AS_OF, fingerprint

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 20)
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")

OUT = os.path.join(_STUDY, "docs", "results.md")
COST_BPS = 10.0          # round-trip turnover cost, large-cap US (swept in the cost table)


def main():
    asof = DEFAULT_AS_OF

    # 0) Machinery sanity on ground truth — oscillators agree on structure, not on noise.
    syn_frames, truth = data.synthetic_universe(seed=0)
    recall = collinearity.structure_recall(syn_frames, truth)

    # 1) Real universe.
    frames = data.load_universe(mode=data.DEFAULT_MODE, min_rows=750, asof=asof)
    panel = data.close_panel(frames)
    fp = fingerprint(panel.fillna(0.0), round_dp=4)
    print(f"universe: {len(frames)} names, {panel.index.min().date()} -> {panel.index.max().date()}")
    print(f"synthetic sanity (agree structured vs noise): {recall}")

    # 2) Are the three oscillators the same shape?
    lc = collinearity.level_collinearity(frames)
    inc = collinearity.incremental_information(frames)
    print("\n[level collinearity — z-scored oscillators]\n", lc.round(3).to_string())
    print("[is TSI spanned by MACD+RSI? incremental-information R²]", {k: round(v, 3) if isinstance(v, float) else v for k, v in inc.items()})

    # 3) Do the positions / equity curves agree?
    agr_zero = collinearity.sign_agreement(frames, rule="zero")
    agr_sig = collinearity.sign_agreement(frames, rule="signal")
    eq = collinearity.equity_collinearity(frames, cost_bps=COST_BPS)
    print("[sign agreement, zero-cross]", {k: round(v, 3) for k, v in agr_zero.items()})
    print("[sign agreement, signal-cross]", {k: round(v, 3) for k, v in agr_sig.items()})
    print("[equity-curve correlation]", {k: round(v, 3) for k, v in eq.items()})

    # 4) The broker statement — the default TSI crossover, equal-weight across the universe.
    stats = backtest.universe_stats(frames, lambda c: backtest.tsi_position(c, rule="signal"), cost_bps=COST_BPS)
    print("\n[TSI crossover — broker statement, EW universe, net of costs]\n",
          {k: (round(v, 4) if isinstance(v, float) else v) for k, v in stats.items()})

    # 5) Reality Check on the grid, and the cost sweep.
    rc = collinearity.reality_check_grid(frames, cost_bps=COST_BPS, rule="signal")
    sweep = collinearity.cost_sweep(frames, rule="signal")
    print("[Reality Check on 24-variant TSI grid]", {k: (round(v, 4) if isinstance(v, float) else v) for k, v in rc.items()})
    print("\n[cost sweep — TSI crossover]\n", sweep.round(3).to_string())

    # 6) The closing argument — trade the residual of TSI orthogonalised on MACD+RSI.
    resid = collinearity.orthogonalised_tsi_edge(frames, cost_bps=COST_BPS)
    print("[orthogonalised TSI residual — does the unique part trade?]",
          {k: (round(v, 4) if isinstance(v, float) else v) for k, v in resid.items()})

    _write_results(OUT, frames, panel, recall, lc, inc, agr_zero, agr_sig, eq, stats, rc, sweep, resid, asof, fp)
    print(f"\nwrote {OUT}")


def _write_results(path, frames, panel, recall, lc, inc, agr_zero, agr_sig, eq, stats, rc, sweep, resid, asof, fp):
    def md(df):
        return "```\n" + df.round(3).to_string() + "\n```"

    def d(x, nd=3):
        return {k: (round(v, nd) if isinstance(v, float) else v) for k, v in x.items()}

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"""# Results — Study 08 (True-Strength) on the cached liquid universe

*Generated by [`examples/verify_real.py`](../examples/verify_real.py). Universe: the cached
deep-history US names (split-only prices — see the data-mode note in
[`true_strength/data.py`](../true_strength/data.py)). Oscillators on default settings —
**TSI 25/13/13**, **MACD 12/26/9**, **RSI 14** — each read as a zero-centred momentum level
and z-scored within its own name. Round-trip turnover cost **{COST_BPS:g} bps**.
As-of **{asof}**. Price fingerprint **`{fp}`** ({len(frames)} names,
{panel.index.min().date()} → {panel.index.max().date()}).*

> **Machinery sanity first.** On the offline synthetic universe (trend/cycle names hidden
> among random walks) the three oscillators' positions agree **{recall['agree_structured']:.0%}**
> of the time on the *structured* names vs **{recall['agree_noise']:.0%}** on the noise names —
> so the comparison machinery recovers real shared structure where it is planted and doesn't
> manufacture agreement out of noise. Whatever the real data says below is the market talking.

## Headline 1 — are the three oscillators the same *shape*?
*Per-name Pearson correlation between the z-scored momentum levels, pooled (median, IQR).*

{md(lc)}

- **Is the TSI spanned by the other two?** Regress z(TSI) on z(MACD) and z(RSI): pooled
  R² = **{inc['pooled_r2']:.3f}**, median per-name R² = **{inc['median_name_r2']:.3f}**
  ({inc['n_names']} names). The double smoothing's "true strength" is, to that R², a linear
  combination of the MACD line and the RSI.

## Headline 2 — do the *positions* and *equity curves* agree?
- sign agreement, **zero-cross** rule: `{d(agr_zero)}`
- sign agreement, **signal-cross** rule: `{d(agr_sig)}`
- equity-curve correlation (EW, long/short, net of {COST_BPS:g} bps): `{d(eq)}`

## The broker statement — default TSI crossover, EW universe, net of costs
*The table QuantifiedStrategies quotes for their GLD backtest, recomputed honestly across the
whole universe (signal-line crossover, long/flat).*
`{d(stats, 4)}`

## Reality Check — the best TSI of a 24-variant grid
*White (2000): null distribution of the best Sharpe across the grid; p = P(luck ≥ observed).*
`{d(rc, 4)}`

## Cost sweep — round-trip bps → mean net daily return & Sharpe
{md(sweep)}

## The closing argument — trade the TSI's residual over MACD+RSI
*Regress z(TSI) on z(MACD)+z(RSI) per name (full-sample, the generous steelman) and trade the
**residual** long/short. If the part of the TSI the other two can't reproduce earns ≈ 0, its
unique content is worthless — and the raw long/short TSI is already ≈ 0 (the 0.61 was beta).*
`{d(resid, 4)}`
""")


if __name__ == "__main__":
    main()
