"""Notebook builder for Study 1002 — The Ten Best Days.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Ten Best Days \U0001F4C6
### The statistic is true. The argument built on it is not.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)

You have seen the chart. A bar for buy-and-hold, then shorter bars for missing the best 10, 20,
30 days, and a caption about the perils of market timing. Every number on it is right. Three
things are missing, and each of them points the other way.

> \U0001F4D3 **This is the plain-language layer.** The shuffle test, the synthetic control and
> the break-even calculation are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is the ten-best-days number true? | Yes. |
| Is there a ten-worst-days number? | Yes, and it is bigger. |
| Can you miss one set without the other? | No — they are days apart. |
| So should you time the market? | Almost certainly not, for a better reason. |
"""
        ),
        md(
            r"""

## 1 · The chart you have seen
"""
        ),
        code(
            r"""
from bestdays import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"buy and hold: {st.annualised(r):.2%} a year")
"""
        ),
        code(
            r"""
t = st.missed_days_table(r, counts=(0, 10, 20, 30, 40, 50))
fig, ax = plt.subplots(figsize=(10, 5))
ax.bar([str(i) for i in t.index], t["miss_best_cagr"] * 100, color="#c0392b")
ax.set_xlabel("best days missed"); ax.set_ylabel("annualised return (%)")
ax.set_title("The brochure chart. Every bar is correct.")
plt.show()
print(t[["miss_best_cagr"]].round(4).to_string())
"""
        ),
        md(
            r"""

## 2 · The chart you have not seen
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 5))
x = np.arange(len(t)); w = 0.38
ax.bar(x - w/2, t["miss_best_cagr"] * 100, w, color="#c0392b", label="miss the BEST days")
ax.bar(x + w/2, t["miss_worst_cagr"] * 100, w, color="#2ea44f",
       label="miss the WORST days")
ax.axhline(st.annualised(r) * 100, color="k", ls="--", lw=1.5, label="buy and hold")
ax.set_xticks(x); ax.set_xticklabels([str(i) for i in t.index])
ax.set_xlabel("days missed"); ax.set_ylabel("annualised return (%)")
ax.legend(fontsize=9)
plt.show()
a = st.asymmetry(r, 10)
print(f"missing the 10 best costs  {a['cost_of_missing_best']:.2%} a year")
print(f"missing the 10 worst gains {a['benefit_of_missing_worst']:.2%} a year")
print(f"the omitted half is {a['ratio']:.2f}x the size of the quoted one")
"""
        ),
        md(
            r"""

The green bars are the same calculation with the sign flipped. They are taller, because the
worst days are bigger than the best days. Nobody prints the green bars.
"""
        ),
        md(
            r"""

## 3 · You cannot have one without the other
"""
        ),
        code(
            r"""
ex = st.extreme_days(r, 10)
fig, ax = plt.subplots(figsize=(13, 4))
eq = (1 + r).cumprod()
ax.semilogy(eq.index, eq.to_numpy(), color="#8b949e", lw=0.8)
for _, row in ex.iterrows():
    ax.axvline(row["date"], color="#2ea44f" if row["kind"] == "best" else "#c0392b",
               lw=1.4, alpha=0.85)
ax.set_ylabel("growth of $1 (log)")
ax.set_title("green = the 10 best days, red = the 10 worst. Look how they pair up.")
plt.show()
print(ex.assign(date=ex["date"].dt.date).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The next notebook shuffles the same returns — keeping every
> value, and the fat tail with it — and shows the median best-to-worst distance jumping from a
> handful of sessions to hundreds. The proximity is in the *order*, not the distribution.
"""
        ),
        md(
            r"""

## 4 · Missing days at random costs nothing
"""
        ),
        code(
            r"""
oc = st.out_of_market_cost(r, fractions=(0.001, 0.005, 0.01, 0.05), n_draws=250)
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(oc)); w = 0.38
ax.bar(x - w/2, oc["random_cost"] * 100, w, color="#8b949e", label="days chosen at random")
ax.bar(x + w/2, oc["worst_case_cost"] * 100, w, color="#c0392b",
       label="the specifically BEST days")
ax.set_xticks(x)
ax.set_xticklabels([f"{int(d):,}\n({f:.1%})" for f, d in zip(oc.index, oc["days"])])
ax.set_xlabel("days missed"); ax.set_ylabel("cost, % a year"); ax.legend(fontsize=9)
plt.show()
oc[["days", "random_cost", "worst_case_cost"]].round(4)
"""
        ),
        md(
            r"""

The grey bars are what happens to someone who is out of the market for reasons unrelated to
returns. The red bars are the brochure. They are not the same claim.
"""
        ),
        md(
            r"""

## 5 · The question worth asking
"""
        ),
        code(
            r"""
rate = st.down_day_share(r)
f = st.timing_frontier(r, 0.20, np.arange(0.35, 0.76, 0.05), n_draws=250)
base = f["buy_and_hold"].iloc[0]
be = st.breakeven_hit_rate(r, 0.20)
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(f.index * 100, f["median_cagr"] * 100, "o-", lw=2, color="#1f6feb")
ax.fill_between(f.index * 100, f["p10"] * 100, f["p90"] * 100, alpha=0.18,
                color="#1f6feb")
ax.axhline(base * 100, color="#2ea44f", ls="--", lw=2, label="buy and hold")
ax.axvline(rate * 100, color="#8b949e", ls=":", lw=2,
           label=f"choosing at random ({rate:.1%})")
ax.axvline(be * 100, color="#c0392b", ls="-", lw=2, label=f"break-even ({be:.1%})")
ax.set_xlabel("% of sit-out days that turn out to be down days")
ax.set_ylabel("annualised return (%)"); ax.legend(fontsize=9)
plt.show()
print(f"a timer sitting out 20% of days needs {be:.2%} accuracy to break even")
print(f"picking at random already gives {rate:.2%} -- so the edge required is "
      f"{(be - rate) * 100:.1f} percentage points")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Real.** The arithmetic is correct. On SPY over 33 years, missing the ten best sessions cuts the annualised return from 10.83% to 8.10% — a loss of **2.74% a year** from ten days out of 8,410. The brochure stops there. Missing the ten **worst** sessions raises it to 13.78%, a gain of **2.94% a year** — **1.07× the size of the loss**. The reason is not the one you would guess. In percentage terms the ten best days are the *bigger* ones (+8.74% against -8.36%), so "crashes are larger than rallies" is simply false here. The asymmetry survives because compounding is multiplicative: removing a day multiplies the result by 1/(1+x), so the quantity that matters is log(1+x) — and in log terms the worst days are the larger (-0.0875 against +0.0835). And the two sets are not scattered through history: the median distance from a best day to the nearest worst day is **6 sessions**, against 290 when the same returns are shuffled (p = 0.000). They arrive in the same storms — the best days occurred at a median drawdown of -34.7% and in volatility 5.8× normal. Being absent for all ten best days while present for all ten worst is not an outcome any rule can produce.

**Tradability: Fragile.** Which makes the interesting question the one nobody asks: how accurate would a timer need to be? Take a rule that sits out 20% of all sessions — 1,682 days — and score it on the share of those days that turn out to be down days. **Choosing at random already achieves 45.2%**, the unconditional down-day frequency, so that and not 50% is the benchmark. Break-even against buy-and-hold arrives at **47.7%**, an edge of only **2.5 percentage points** over random. That sounds modest, and the modesty is the trap: the frontier is savagely steep on both sides. Random selection — sitting out 20% of days with no skill whatsoever — returns 8.59% against buy-and-hold's 10.83%, and a timer 5 points *below* random gets 4.40%. The edge must be small, positive, and sustained across every one of 1,682 decisions; being slightly wrong is far more expensive than being slightly right is profitable. For scale, missing 84 days chosen at random costs 0.12% a year while missing the 84 *best* costs 11.93% — the brochure quotes the worst case of a selection no process generates.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **The conclusion survives.** Staying invested is very probably right. It just is not right for
  the reason the chart gives, and an argument that collapses under its own symmetric twin is
  worth replacing with one that does not.
- **The real argument** is section 5: a timer needs an accuracy that essentially nobody has
  demonstrated, and the best days arrive at the bottom of crashes when a nervous investor is
  least likely to be present.
- **Ask for the other column.** Any time a table shows what happens when you miss the best of
  something, the same table for the worst exists and was not shown.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Ten Best Days — a quantitative teardown \U0001F52C
### The omitted symmetric statistic · a shuffle test for clustering · the break-even hit rate

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The load-bearing
measurement is the shuffle test in §3.2: it preserves every return and destroys only the order,
which separates *fat tails* from *clustering* and shows the brochure's counterfactual to be
structurally unavailable rather than merely improbable.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from bestdays import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"buy and hold: {st.annualised(r):.2%} a year")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | The arithmetic is correct. On SPY over 33 years, missing the ten best sessions cuts the annualised return from 10.83% to 8.10% — a loss of **2.74% a year** from ten days out of 8,410. The brochure stops there. Missing the ten **worst** sessions raises it to 13.78%, a gain of **2.94% a year** — **1.07× the size of the loss**. The reason is not the one you would guess. In percentage terms the ten best days are the *bigger* ones (+8.74% against -8.36%), so "crashes are larger than rallies" is simply false here. The asymmetry survives because compounding is multiplicative: removing a day multiplies the result by 1/(1+x), so the quantity that matters is log(1+x) — and in log terms the worst days are the larger (-0.0875 against +0.0835). And the two sets are not scattered through history: the median distance from a best day to the nearest worst day is **6 sessions**, against 290 when the same returns are shuffled (p = 0.000). They arrive in the same storms — the best days occurred at a median drawdown of -34.7% and in volatility 5.8× normal. Being absent for all ten best days while present for all ten worst is not an outcome any rule can produce. |
| **Tradability** | Fragile | Which makes the interesting question the one nobody asks: how accurate would a timer need to be? Take a rule that sits out 20% of all sessions — 1,682 days — and score it on the share of those days that turn out to be down days. **Choosing at random already achieves 45.2%**, the unconditional down-day frequency, so that and not 50% is the benchmark. Break-even against buy-and-hold arrives at **47.7%**, an edge of only **2.5 percentage points** over random. That sounds modest, and the modesty is the trap: the frontier is savagely steep on both sides. Random selection — sitting out 20% of days with no skill whatsoever — returns 8.59% against buy-and-hold's 10.83%, and a timer 5 points *below* random gets 4.40%. The edge must be small, positive, and sustained across every one of 1,682 decisions; being slightly wrong is far more expensive than being slightly right is profitable. For scale, missing 84 days chosen at random costs 0.12% a year while missing the 84 *best* costs 11.93% — the brochure quotes the worst case of a selection no process generates. |

> \U0001F4A1 **In plain words.** True statistic, false inference, and a better argument
> available.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (arithmetic).** Missing the ten best sessions materially reduces the annualised return.
- **H₂ (omitted half).** Missing the ten worst helps by *more* than missing the ten best hurts,
  in a majority of markets.
- **H₃ (clustering).** The median distance from a best day to the nearest worst day is far
  smaller than under a shuffle of the same returns.
- **H₄ (mechanism).** Volatility clustering, not the fat tail, is what produces H₃ — testable
  because the two can be varied independently in synthetic data.
- **H₅ (the honest question).** The hit rate a switching rule needs to break even is far above a
  coin flip.
"""
        ),
        md(
            r"""

## 2 · Data and construction
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    if tk not in px.columns:
        continue
    s = px[tk].dropna().pct_change().dropna()
    rows.append({"asset": tk, "n": len(s), "from": s.index[0].date(),
                 "cagr": st.annualised(s), "vol": s.std() * np.sqrt(252),
                 "skew": s.skew(), "excess kurtosis": s.kurtosis()})
print(pd.DataFrame(rows).set_index("asset").round(4).to_string())
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Both halves of the statistic, every market
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    if tk == data.CASH or tk not in px.columns:
        continue
    s = px[tk].dropna().pct_change().dropna()
    if len(s) < 1500:
        continue
    for n in (5, 10, 20, 30):
        a = st.asymmetry(s, n)
        rows.append({"asset": tk, "n_days": n, "cost_best": a["cost_of_missing_best"],
                     "gain_worst": a["benefit_of_missing_worst"], "ratio": a["ratio"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(11, 5))
piv = d.pivot(index="n_days", columns="asset", values="ratio")
piv.plot(ax=ax, marker="o", lw=2)
ax.axhline(1.0, color="k", ls="--", lw=2, label="the two halves are equal")
ax.set_xlabel("days missed")
ax.set_ylabel("(gain from missing worst) / (cost of missing best)")
ax.legend(fontsize=8, ncol=2)
plt.show()
print(piv.round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Every line above 1.0 is a market where the unquoted half of the
> statistic is the bigger half.
"""
        ),
        md(
            r"""

### 3.2 The shuffle test — the load-bearing measurement
"""
        ),
        code(
            r"""
r_np = r.to_numpy()
n_ex = 10
def gap_of(x):
    o = np.argsort(x); b = np.sort(o[-n_ex:]); w = np.sort(o[:n_ex])
    return float(np.median(np.abs(b[:, None] - w[None, :]).min(axis=1)))
rng = np.random.default_rng(1002)
null = np.array([gap_of(rng.permutation(r_np)) for _ in range(2000)])
actual = gap_of(r_np)
fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(null, bins=50, color="#8b949e", alpha=0.85,
        label="same returns, order shuffled")
ax.axvline(actual, color="#c0392b", lw=3, label=f"actual: {actual:.0f} sessions")
ax.set_xlabel("median sessions from a best day to the nearest worst day")
ax.set_ylabel("frequency"); ax.legend(fontsize=9)
plt.show()
print(f"actual {actual:.0f}, shuffled median {np.median(null):.0f}, "
      f"p = {(null <= actual).mean():.4f}")
print("The shuffle keeps every return. Only the ORDER changes.")
"""
        ),
        md(
            r"""

### 3.3 The mechanism, isolated
"""
        ),
        code(
            r"""
rows = []
for clustered in (True, False):
    for k in range(8):
        sim = st.synthetic_returns(n=8000, clustered=clustered, seed=1002 + k)
        c = st.clustering_stats(sim, 10, 200, seed=1002 + k)
        rows.append({"clustering": "on" if clustered else "off",
                     "gap": c["median_gap"], "ratio": c["ratio"],
                     "kurtosis": sim.kurtosis()})
d = pd.DataFrame(rows)
print(d.groupby("clustering")[["gap", "ratio", "kurtosis"]].mean().round(3).to_string())
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
for i, col in enumerate(["kurtosis", "ratio"]):
    axes[i].boxplot([d[d["clustering"] == c][col] for c in ("on", "off")],
                    tick_labels=["clustering on", "clustering off"])
    axes[i].set_ylabel(col)
axes[0].set_title("the fat tail is the SAME in both worlds")
axes[1].set_title("only clustering brings best and worst days together")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Fat tails alone do not put the best days next to the worst
> days. Volatility clustering does. This is why the effect is a fact about crashes, not a fact
> about the return distribution.
"""
        ),
        md(
            r"""

### 3.4 Volatility and drawdown context
"""
        ),
        code(
            r"""
ex = st.extreme_days(r, 30)
vol = r.rolling(21).std().shift(1) * np.sqrt(252)
eq = (1 + r).cumprod(); dd = eq / eq.cummax() - 1
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for kind, col in (("best", "#2ea44f"), ("worst", "#c0392b")):
    dts = ex[ex["kind"] == kind]["date"]
    axes[0].scatter(vol.reindex(dts) * 100, dd.reindex(dts) * 100, s=45, color=col,
                    label=kind, alpha=0.85)
axes[0].axvline(vol.median() * 100, color="k", ls="--", lw=1, label="typical volatility")
axes[0].set_xlabel("trailing volatility, annualised (%)")
axes[0].set_ylabel("drawdown at the time (%)"); axes[0].legend(fontsize=8)
ctx = pd.DataFrame([st.volatility_context(r, n) for n in (5, 10, 20, 30, 50)],
                   index=[5, 10, 20, 30, 50])
axes[1].plot(ctx.index, ctx["best_vol_ratio"], "o-", color="#2ea44f", label="best days")
axes[1].plot(ctx.index, ctx["worst_vol_ratio"], "s-", color="#c0392b", label="worst days")
axes[1].axhline(1.0, color="k", ls="--", lw=1)
axes[1].set_xlabel("how many extreme days")
axes[1].set_ylabel("volatility, × normal"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(pd.DataFrame([st.drawdown_context(r, n) for n in (10, 20, 30)],
                   index=[10, 20, 30]).round(4).to_string())
"""
        ),
        md(
            r"""

### 3.5 The random-days null
"""
        ),
        code(
            r"""
oc = st.out_of_market_cost(r, fractions=(0.0005, 0.001, 0.005, 0.01, 0.05, 0.10,
                                          0.25), n_draws=400)
fig, ax = plt.subplots(figsize=(10, 5))
ax.loglog(oc["days"], oc["random_cost"] * 100, "o-", lw=2, color="#8b949e",
          label="days chosen at random")
ax.loglog(oc["days"], oc["worst_case_cost"] * 100, "s-", lw=2, color="#c0392b",
          label="the specifically best days")
ax.set_xlabel("days missed (log)"); ax.set_ylabel("cost, % a year (log)")
ax.legend(fontsize=9)
plt.show()
oc.assign(ratio=oc["worst_case_cost"] / oc["random_cost"]).round(4)
"""
        ),
        md(
            r"""

### 3.6 The break-even frontier, and how it moves
"""
        ),
        code(
            r"""
rate = st.down_day_share(r)
rows = []
for frac in (0.05, 0.10, 0.20, 0.35, 0.50):
    f = st.timing_frontier(r, frac, np.arange(0.35, 0.81, 0.05), n_draws=200)
    be = st.breakeven_hit_rate(r, frac)
    for hr, row in f.iterrows():
        rows.append({"out": frac, "hit_rate": hr, "cagr": row["median_cagr"],
                     "breakeven": be})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for fr, g in d.groupby("out"):
    axes[0].plot(g["hit_rate"] * 100, g["cagr"] * 100, "o-", label=f"{fr:.0%} out")
axes[0].axhline(st.annualised(r) * 100, color="k", ls="--", lw=2, label="buy and hold")
axes[0].axvline(rate * 100, color="#8b949e", ls=":", lw=2)
axes[0].set_xlabel("hit rate, % of sit-out days that are down days")
axes[0].set_ylabel("annualised return (%)"); axes[0].legend(fontsize=8)
be = d.groupby("out")["breakeven"].first()
axes[1].plot(be.index * 100, (be - rate) * 100, "o-", lw=2, color="#c0392b")
axes[1].axhline(0, color="#8b949e", ls=":", lw=1.5, label="no edge over random")
axes[1].set_xlabel("% of sessions sat out")
axes[1].set_ylabel("edge required, percentage points")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print((be - rate).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The more a timer trades, the more accurate it has to be. That is
> the real headwind, and it is a statement about the timer rather than about ten particular
> days.
"""
        ),
        md(
            r"""

### 3.7 Does the whole thing rest on 2008?
"""
        ),
        code(
            r"""
rows = []
for lo, hi in [(1993, 2007), (2003, 2013), (2010, 2020), (2015, 2026), (1993, 2026)]:
    s = r[(r.index.year >= lo) & (r.index.year <= hi)]
    if len(s) < 750:
        continue
    a = st.asymmetry(s, 10)
    c = st.clustering_stats(s, 10, 200)
    rows.append({"window": f"{lo}-{hi}", "n": len(s), "cagr": a["base_cagr"],
                 "cost_best": a["cost_of_missing_best"],
                 "gain_worst": a["benefit_of_missing_worst"], "ratio": a["ratio"],
                 "gap": c["median_gap"], "shuffled_gap": c["shuffled_median_gap"],
                 "p": c["p_value"]})
d = pd.DataFrame(rows).set_index("window")
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The asymmetry ratio moves around with the sample — it is the
> weaker of the two findings and depends on whether a crash is in the window. The clustering
> result holds in every sub-period, which is why the verdict leans on it.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
a = st.asymmetry(r, 10)
c = st.clustering_stats(r, 10, 400)
dc = st.drawdown_context(r, 10)
vc = st.volatility_context(r, 10)
oc1 = st.out_of_market_cost(r, fractions=(0.01,), n_draws=300).iloc[0]
pd.DataFrame({
    "buy and hold, % a year": [a["base_cagr"]],
    "cost of missing the 10 best": [a["cost_of_missing_best"]],
    "gain from missing the 10 worst": [a["benefit_of_missing_worst"]],
    "ratio (omitted / quoted)": [a["ratio"]],
    "median best-to-worst gap, sessions": [c["median_gap"]],
    "the same, shuffled": [c["shuffled_median_gap"]],
    "clustering p-value": [c["p_value"]],
    "median drawdown on a best day": [dc["best_median_drawdown"]],
    "volatility on a best day, x normal": [vc["best_vol_ratio"]],
    "cost of missing 1% of days at random": [oc1["random_cost"]],
    "cost of missing the best 1% of days": [oc1["worst_case_cost"]],
    "10 best days, mean % return": [a["mean_best"]],
    "10 worst days, mean % return": [a["mean_worst"]],
    "10 best days, mean log return": [a["log_best"]],
    "10 worst days, mean log return": [a["log_worst"]],
    "random timer's hit rate": [st.down_day_share(r)],
    "break-even hit rate for a timer": [st.breakeven_hit_rate(r, 0.20)],
    "edge required over random": [st.breakeven_hit_rate(r, 0.20)
                                  - st.down_day_share(r)],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Estrada (2008)** runs the two-sided version across fifteen markets and over a century in
  places; this study adds the clustering test and the synthetic control that identifies its
  mechanism.
- **Sharpe (1975)** computed a break-even timing accuracy of roughly 74% under a different
  parameterisation. Reconciling his monthly bull/bear formulation with the daily sit-out
  formulation here would make a clean short note.
- **Condition on the rule.** The frontier here treats hit rate as a free parameter. Mapping an
  actual rule — a moving-average cross, a volatility target — onto its realised hit rate would
  turn the frontier into a verdict on that rule, which is what **211-market-timing** does from
  the other direction.
- **Add costs and taxes.** Both raise the break-even, and a realistic version would report the
  after-tax threshold for a taxable account, which is materially higher again.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
