"""Generate the two narrative notebooks for Study 21 (Fools-Gold) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the **offline synthetic tape** (a persistent-drift trend, plus a driftless
null), because the cached real closes are git-ignored and the reproducible core must run with no
network. The synthetic proves the machinery; the **real verdict** (it 'works' on the S&P everyone
quotes and nowhere else) is quoted from [`docs/results.md`](../docs/results.md). Both notebooks walk the
SAME seven desk beats (see ../../../METHODOLOGY.md).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from fools_gold import data, cross, strategy, decompose, extension

# Offline synthetic close: a persistent-drift TREND (so a crossover can ride runs) and a driftless
# NULL (random walk). The real ETF verdict is in ../docs/results.md.
close, truth = data.synthetic_prices(trend_strength=0.0006, seed=21)   # the trend tape
close0, _    = data.synthetic_prices(trend_strength=0.0,    seed=21)   # the driftless null
print(f"{truth.n_bars} bars | baked trend_strength={truth.trend_strength} | null=0")
"""

R = dict(
    n="8", lo="1993", hi="2026", fp="3d45c07989be",
    spy_spread_t="+2.7", beat="3", median="-0.01",
    spy_beta="0.52", spy_alpha_t="+2.2",
    spy_grid="76", fxi_grid="0",
    spy_tim="+0.65", spy_bh="+0.55", spy_gain="+0.10",
    d1_t="+0.74", d1_b="+0.36", d2_t="+0.57", d2_b="+0.76",
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Generalises?: Not supported](https://img.shields.io/badge/Generalises%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Fools-Gold ✨\n"
            "### The 'golden cross' — when the 50-day average crosses above the 200-day, is it really a buy signal?\n\n"
            + BADGES +
            "It's the single most-quoted pattern on financial TV: the **golden cross**, when a fast "
            "moving average (50-day) crosses *above* a slow one (200-day), supposedly signals a new "
            "bull market — and the **death cross** the reverse. Generations of chartists swear by it.\n\n"
            "This is the desk's fourth idea from Kakushadze & Serur's *151 Trading Strategies* "
            "(strategies §3.11–3.13), and it's the textbook *folk* specimen. We prove our tools on a "
            "synthetic tape where we bake a real trend in (and a driftless null where a crossover can "
            "catch nothing), then point them at a basket of real ETFs — and find the golden cross is "
            "**fool's gold**: it shines on the one asset everyone quotes, and nowhere else.\n\n"
            "> 📓 **Plain-language layer.** The Newey–West *t*, the alpha-vs-buy-and-hold and the "
            "parameter grid are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** tape, so the real-ETF numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does the golden cross beat buy-and-hold? | 🟡 **On the S&P, barely; elsewhere, no.** It "
            f"wins on **{R['beat']} of {R['n']}** ETFs (median gain **{R['median']}**). |\n"
            "| Is it skill, or just less exposure? | ⚪ **Mostly less exposure** — it sits in cash a lot "
            f"(beta **{R['spy_beta']}**); a plain cash blend captures most of the calm. |\n"
            "| Does it generalise? | 🚫 **No.** It 'works' on "
            f"**{R['spy_grid']}%** of parameter pairs for the S&P and **{R['fxi_grid']}%** for a "
            "different index — a cherry-pick, not an edge. |\n\n"
            "> Desk shorthand: **Signal `WEAK` · Tradability `MIRAGE` · Generalises? `NOT SUPPORTED`** — a "
            "trend filter dressed up as a magic buy signal."
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "The folk claim is specific and testable: **once you're in a 'golden' state, future returns "
            "are higher than in a 'death' state.** Not just \"trends exist\" — the crossover *event* is "
            "supposed to carry information. On our synthetic trending tape we baked a real trend in; "
            "split days by yesterday's crossover state and look at the next day's return:"
        ),
        code(
            "sv = cross.signal_value(close)\n"
            "fig, ax = plt.subplots()\n"
            "ax.bar(['golden', 'death'], [sv['golden_ann_pct'], sv['death_ann_pct']], color=['#2ea44f','#c0392b'], alpha=.85)\n"
            "ax.set_ylabel('avg next-day return (annualised %)')\n"
            "ax.set_title(f\"Baked trend: golden days out-return death days by {sv['spread_ann_pct']:+.0f}%/yr\")\n"
            "plt.show()\n"
            "print(f\"golden {sv['golden_ann_pct']:+.0f}%/yr vs death {sv['death_ann_pct']:+.0f}%/yr; time golden {sv['frac_golden']:.0%}\")"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "If the crossover truly timed bull and bear markets, it would be the holy grail: ride the "
            "ups, dodge the crashes, beat buy-and-hold with less stress. That's exactly the promise sold "
            "in every \"golden cross alert\" headline. The catch the desk always checks: a rule that "
            "holds *cash* part of the time will *automatically* look calmer — so the only fair question "
            "is whether it beats buy-and-hold once you account for simply taking less risk."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Four checks, up front:\n\n"
            "1. **Is the crossover informative?** Golden-minus-death next-day spread, with a *t*-stat.\n"
            "2. **Does it beat buy-and-hold**, net of cost — across many assets, not one?\n"
            "3. **Is it more than de-risking?** Alpha & beta vs buy-and-hold; a risk-matched cash blend.\n"
            "4. **Does it generalise** across parameters and assets? And the **null**: a random walk "
            "must yield nothing.\n\n"
            "**Mirage line:** it beats buy-and-hold on only a handful of assets, the 'edge' is just lower "
            "exposure, and it falls apart at un-cherry-picked parameters."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · Trend tape vs null — and the random-walk trap\n"
            "Run the crossover on both synthetic tapes. Watch the null carefully: a *single* random walk "
            "can drift by chance, making the crossover look good — the data-mining trap in miniature."
        ),
        code(
            "for label, c in [('trend', close), ('driftless null', close0)]:\n"
            "    cmp = strategy.compare(c, cost_bps=2.0); sp = decompose.spread_tstat(c)\n"
            "    print(f\"{label:16s}: timing Sharpe {cmp['timing']['sharpe']:+.2f} vs B&H {cmp['buy_hold']['sharpe']:+.2f} \"\n"
            "          f\"(gain {cmp['sharpe_gain']:+.2f}), golden−death t {sp['t_stat']:+.1f}\")"
        ),

        md(
            "### 4b · The real tape — fool's gold\n"
            "On a basket of real ETFs (quoted from [`../docs/results.md`](../docs/results.md)):\n\n"
            f"- On **SPY** the golden−death spread is real (*t* = **{R['spy_spread_t']}**) and timing "
            f"edges buy-and-hold (Sharpe **{R['spy_tim']}** vs **{R['spy_bh']}**, +{R['spy_gain'].lstrip('+')}).\n"
            f"- But across **{R['n']}** instruments it beats buy-and-hold on only **{R['beat']}**, median "
            f"gain **{R['median']}** — a coin flip.\n"
            f"- On SPY the 'edge' is mostly *less exposure*: beta **{R['spy_beta']}**, and a constant cash "
            "blend at the same average exposure captures most of the calm.\n"
            "- It doesn't generalise: it beats buy-and-hold on "
            f"**{R['spy_grid']}%** of (fast, slow) pairs for SPY but **{R['fxi_grid']}%** for another "
            "index."
        ),

        md(
            "### 4c · And even on the S&P, it stopped working\n"
            "The golden cross looked great when it dodged 2008 — and has *lagged* buy-and-hold through "
            "the long bull since, because it kept sitting out the dips."
        ),
        md(
            f"On real SPY: first half Sharpe **{R['d1_t']}** (timing) vs **{R['d1_b']}** (buy-and-hold) — "
            f"timing won by dodging the crash; second half **{R['d2_t']}** vs **{R['d2_b']}** — buy-and-"
            "hold won as the filter sat in cash through every dip. The 'signal' is a bet on *when* a "
            "crash happens to land, not a repeatable edge."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **Weak & non-general** — significant golden−death spread only on the trending US indices; "
            f"a coin flip across {R['n']} assets.\n"
            "- **Mostly de-risking** — low beta; a cash blend matches it.\n"
            "- **Doesn't generalise** — works on 76% of params for SPY, 0% for another index.\n\n"
            "> **Signal `WEAK` · Tradability `MIRAGE` · Generalises? `NOT SUPPORTED`.** A trend filter, "
            "re-discovered on the one asset everyone cherry-picks."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "- **It barely beats buy-and-hold** where it 'works', and loses elsewhere — net of the cost "
            "of every whipsaw.\n"
            "- **The calm is just cash.** You could replicate most of the lower drawdown by simply "
            "holding less and keeping the rest in T-bills — no crossover required.\n"
            "- **You'd be timing the next crash.** Its whole record is dodging *one* bear market; miss "
            "the timing and you spend years underperforming in cash.\n\n"
            "> Tradability **`MIRAGE`**; generalises? **`NOT SUPPORTED`** — the parameter grid "
            "([`../docs/extension.md`](../docs/extension.md)) shows the cherry-pick."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **The parameter-robustness test** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): the % of (fast, slow) pairs that beat "
            "buy-and-hold, asset by asset — near-total on the trending index, zero elsewhere.\n"
            "- **A real trend filter, done honestly.** Time-series momentum across many markets "
            "([Study 20](../../20-freight-train/)) is the grown-up version; the single-asset 50/200 is "
            "its folk cartoon.\n"
            "- **As a de-risking overlay** (à la [Study 16](../../16-storm-shy/)) rather than a buy "
            "signal — does a crossover add anything to inverse-vol sizing, or is it strictly worse?\n\n"
            "PRs welcome — find an asset/parameter where it survives out-of-sample, or show it's strictly "
            "a worse trend filter than the alternatives."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Fools-Gold — a quantitative teardown 🔬\n"
            "### Golden−death spread (HAC) · timing vs buy-and-hold · alpha & beta · the cash-blend control · the parameter grid\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim with its standard error.* The steelman is the 50/200 moving-average "
            "crossover (Kakushadze–Serur §3.11–3.13): golden cross = buy, death cross = sell. We prove "
            "the apparatus on a synthetic trend (and a driftless null), then read the real verdict off an "
            "ETF basket.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — is the crossover informative? | 🟡 `WEAK` | A significant golden−death spread "
            f"only on the trending US indices (SPY *t* = **{R['spy_spread_t']}**); across {R['n']} ETFs it "
            f"beats buy-and-hold on **{R['beat']}** (median gain **{R['median']}**). |\n"
            "| **Tradability** | 🔴 `MIRAGE` | The 'edge' is mostly less exposure (SPY beta "
            f"**{R['spy_beta']}**, alpha *t* **{R['spy_alpha_t']}**); a cash blend matches it, and it "
            "loses on most assets net of cost. |\n"
            "| **Generalises?** | ⚪ `Not supported` | Beats buy-and-hold on "
            f"**{R['spy_grid']}%** of (fast, slow) pairs for SPY, **{R['fxi_grid']}%** for another index. |\n\n"
            "> **In one sentence:** a crude trend filter whose only significant signal lives on the one "
            "secularly-trending index everyone quotes, mostly captures lower exposure, and falls apart at "
            "un-chosen parameters and assets.\n\n"
            "*(This notebook executes on the synthetic tape; the real ETF numbers that set the stamps are "
            "in [`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Let $s_t = \\text{sign}(\\text{MA}_f - \\text{MA}_s)$ be the crossover state (+1 golden, −1 "
            "death). The folk claim is $\\mathbb{E}[r_{t+1}\\mid s_t=+1] > \\mathbb{E}[r_{t+1}\\mid "
            "s_t=-1]$ — the state predicts the next return. The long/flat book is $w_t = \\mathbb{1}[s_{t-1}"
            ">0]$. The synthetic bakes a persistent drift (trends to ride); $\\text{trend\\_strength}=0$ "
            "is the driftless null."
        ),
        code(
            "sv = cross.signal_value(close)\n"
            "print(f\"golden {sv['golden_ann_pct']:+.1f}%/yr vs death {sv['death_ann_pct']:+.1f}%/yr \"\n"
            "      f\"(spread {sv['spread_ann_pct']:+.1f}%), time golden {sv['frac_golden']:.0%}\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "A long/flat rule trivially lowers vol and drawdown by being out of the market — so Sharpe, "
            "drawdown and 'it dodged 2008' are *not* evidence of skill. The only decisive tests are "
            "**(i)** does the state carry information (golden−death spread *t*), **(ii)** is there alpha "
            "after the beta drop, and **(iii)** does any of it survive out of the cherry-picked "
            "asset/parameter. Beats 4–6 run all three."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Spread** (`cross.signal_value` / `decompose.spread_tstat`): HAC *t* on golden−death.\n"
            "2. **vs buy-and-hold** (`strategy.compare`): net Sharpe gain, average exposure, turnover.\n"
            "3. **Alpha/beta** (`decompose.vs_buy_hold`) + **cash-blend** control (`decompose.risk_matched`).\n"
            "4. **Generalisation** (`extension.param_grid`): % of pairs beating buy-and-hold.\n"
            "5. **Null:** every leg flat on the driftless tape.\n\n"
            "**Mirage line:** alpha insignificant after the beta drop, *and* the win rate across "
            "assets/params near a coin flip."
        ),

        md(
            "## Beat 4 · The teardown\n\n"
            "### 4a · Spread and timing, trend vs null"
        ),
        code(
            "for label, c in [('trend', close), ('null', close0)]:\n"
            "    sp = decompose.spread_tstat(c); cmp = strategy.compare(c, cost_bps=2.0)\n"
            "    print(f\"{label:6s}: golden−death {sp['spread_ann_pct']:+.1f}%/yr (t {sp['t_stat']:+.1f}) | \"\n"
            "          f\"timing Sharpe {cmp['timing']['sharpe']:+.2f} vs B&H {cmp['buy_hold']['sharpe']:+.2f} \"\n"
            "          f\"(gain {cmp['sharpe_gain']:+.2f}), exposure {cmp['avg_exposure']:.0%}\")"
        ),

        md(
            "### 4b · Alpha, beta, and the cash-blend control\n"
            "Is the calmer ride skill, or just a smaller bet?"
        ),
        code(
            "vb = decompose.vs_buy_hold(close, cost_bps=2.0); rm = decompose.risk_matched(close, cost_bps=2.0)\n"
            "print(f\"vs buy-&-hold: beta {vb['beta']:.2f}, alpha {vb['alpha_ann_pct']:+.1f}%/yr (t {vb['alpha_t']:+.1f})\")\n"
            "print(f\"risk-matched: timing Sharpe {rm['timing_sharpe']:+.2f} vs cash-blend at \"\n"
            "      f\"{rm['avg_exposure']:.0%} exposure {rm['cash_blend_sharpe']:+.2f} (edge {rm['sharpe_edge_over_blend']:+.2f})\")"
        ),
        md(
            "> 💡 **In plain words.** A book that's in cash a third of the time has a beta well below 1, so "
            "its lower vol is mostly *less exposure*. The honest test is whether it beats a constant "
            "position at that same average exposure — and on the real cherry-picked index the edge over "
            "that cash blend is small."
        ),

        md(
            "### 4c · Generalisation — the parameter grid\n"
            "Sweep (fast, slow) pairs; a real edge helps across most of them."
        ),
        code(
            "pg = extension.param_grid(close, cost_bps=2.0)\n"
            "import numpy as np\n"
            "m = pg['matrix']\n"
            "fig, ax = plt.subplots(figsize=(6.5,4.2))\n"
            "im = ax.imshow(m.values.astype(float), cmap='RdYlGn', vmin=-0.5, vmax=0.5, aspect='auto')\n"
            "ax.set_xticks(range(len(m.columns))); ax.set_xticklabels(m.columns); ax.set_yticks(range(len(m.index))); ax.set_yticklabels(m.index)\n"
            "ax.set_xlabel('slow MA'); ax.set_ylabel('fast MA'); fig.colorbar(im, label='Sharpe gain vs B&H')\n"
            "ax.set_title(f\"Synthetic trend: {pg['frac_beat_buy_hold']:.0%} of pairs beat B&H\")\n"
            "plt.show()\n"
            "print(f\"trend tape: {pg['frac_beat_buy_hold']:.0%} of pairs beat B&H, mean gain {pg['mean_gain']:+.2f}\")"
        ),

        md(
            "### 4d · The driftless null\n"
            "No baked trend ⇒ no informative spread, no reliable edge (though one path can drift by luck)."
        ),
        code(
            "sp0 = decompose.spread_tstat(close0); cmp0 = strategy.compare(close0, cost_bps=2.0)\n"
            "print(f\"null: golden−death t {sp0['t_stat']:+.1f} | timing gain vs B&H {cmp0['sharpe_gain']:+.2f}\")\n"
            "print('the spread is the honest test; a single random walk can still drift, which is the data-mining trap itself.')"
        ),

        md(
            "## Beat 5 · The verdict\n\n"
            f"- **Weak signal** (4a): significant golden−death only on trending indices; coin flip across {R['n']} assets.\n"
            f"- **Mostly beta** (4b): SPY beta {R['spy_beta']}, alpha *t* {R['spy_alpha_t']}, cash blend matches it.\n"
            f"- **No generalisation** (4c): {R['spy_grid']}% of params for SPY, {R['fxi_grid']}% for another index.\n\n"
            "> **Signal `WEAK` · Tradability `MIRAGE` · Generalises? `Not supported`.**"
        ),

        md(
            "## Beat 6 · Could you trade it?\n\n"
            "- **Net of whipsaw cost** it loses to buy-and-hold on most assets.\n"
            "- **The de-risking is free elsewhere** — a static cash blend replicates the calmer ride.\n"
            "- **Its record is one dodged crash**; out-of-sample it's a timing bet, not an edge.\n\n"
            "Tradability **`MIRAGE`**; generalises? **`Not supported`**."
        ),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — the parameter-robustness test\n"
            "The % of (fast, slow) pairs that beat buy-and-hold, asset by asset — the spread between the "
            "cherry-picked index and the rest."
        ),
        code(
            "pg = extension.param_grid(close, cost_bps=2.0)\n"
            "print(f\"synthetic trend: {pg['frac_beat_buy_hold']:.0%} of pairs beat B&H (best {pg['best_pair']}).\")\n"
            f"print('On the REAL basket (../docs/extension.md): ~{R['spy_grid']}% of pairs beat B&H on SPY, {R['fxi_grid']}% on another index --')\n"
            "print('a rule that "
            "works on 76% of parameters for one asset and 0% for another is a trend, not an edge.')"
        ),
        md(
            "**The result.** The parameter grid is decisive: the crossover's success rate ranges from "
            f"near-total on the secularly-trending US index to **{R['fxi_grid']}%** elsewhere. Pick the "
            "asset and parameters after the fact and you can always narrate a golden-cross win; demand "
            "it work *out of sample, across instruments, at an unchosen parameter*, and it's a coin flip. "
            "That is exactly the cherry-pick the `Not supported` stamp records. Full run in "
            "[`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **Proper trend-following** ([Study 20](../../20-freight-train/)) across many markets is the "
            "honest version; quantify how much the single-asset 50/200 gives up.\n"
            "- **De-risking overlay** vs a buy signal — does a crossover add anything to inverse-vol "
            "sizing (à la [Study 16](../../16-storm-shy/))?\n"
            "- **Out-of-sample parameter selection** — pick (fast, slow) on a training window, test on "
            "the next; does any selection rule beat buy-and-hold live?\n\n"
            "PRs welcome — make it survive out of sample, or confirm it's strictly a worse trend filter."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
