"""Notebook builder for Study 984 — A Dollar Off.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# A Dollar Off \U0001F4B8
### On the ex-dividend day the price should fall by the dividend. Does it?

![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

It is nearly an accounting identity. A share about to pay you a dollar is worth a dollar more
than the same share after it has paid. So the morning the dividend detaches, the price should
open a dollar lower. In 1970 two economists measured it, found 78 cents, and started an argument
that is still running.

> \U0001F4D3 **This is the plain-language layer.** The estimator comparison, the bootstrap and
> the planted-truth control are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Should the price fall by the dividend? | Yes — it is close to an accounting identity. |
| Does it? | Roughly, but see how wide the uncertainty is. |
| Can you measure it precisely? | No, and that is the study's actual finding. |
| Is there a trade? | The gross edge is a few basis points; costs eat most of it. |
"""
        ),
        md(
            r"""

## 1 · The mechanics

Three dates matter. On the **declaration** date the company announces. On the **ex-date** the
stock starts trading *without* the right to the payment — buy it that morning and the dividend
goes to whoever sold it to you. On the **pay date** the cash arrives.

The ex-date is the interesting one. Overnight the share loses something worth exactly the
dividend, so the price should open lower by exactly the dividend.
"""
        ),
        code(
            r"""
from exday import data, strategy as st

bars = data.load_bars()
px = data.load_prices()
ev = st.build_events(bars, data.MARKET)
print(f"as-of {data.AS_OF} | {len(ev)} ex-dates on {ev['ticker'].nunique()} payers, "
      f"{ev.index[0].date()} -> {ev.index[-1].date()}")
print(f"median yield per event {ev['yield'].median():.3%}   "
      f"typical daily move {px[list(data.PAYERS)].pct_change().stack().std():.2%}")
print(ev.head()[["ticker", "price_cum", "price_ex", "dividend", "raw_ratio",
                 "adjusted_ratio"]].round(4).to_string())
"""
        ),
        md(
            r"""

## 2 · The scale problem, in one picture

Here is the difficulty in a single chart: the thing we are trying to measure is much smaller
than the daily noise it is hiding inside.
"""
        ),
        code(
            r"""
daily = px[list(data.PAYERS)].pct_change().stack().dropna()
fig, ax = plt.subplots(figsize=(11, 4.5))
ax.hist(daily * 100, bins=200, range=(-5, 5), color="#8b949e", alpha=0.7,
        label="ordinary daily moves for these stocks")
ax.axvline(-ev["yield"].median() * 100, color="#c0392b", lw=2.5,
           label=f"a typical dividend: {ev['yield'].median():.2%}")
ax.set_xlabel("one day's move (%)"); ax.legend()
ax.set_title("The dividend is the red line. The noise is everything else.")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** This is why the per-event ratio `(P_cum − P_ex) / D` is such a
> hostile statistic: a numerator with a 1.2% standard deviation over a denominator of 0.7%. Its
> tails are heavy enough that averaging them is close to meaningless.
"""
        ),
        md(
            r"""

## 3 · What the individual events look like
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].hist(ev["adjusted_ratio"].clip(-5, 6), bins=80, color="#2ea44f", edgecolor="white")
axes[0].axvline(1.0, color="k", lw=2, label="theory: 1.0")
axes[0].axvline(st.ELTON_GRUBER_1970, color="#c0392b", lw=2, ls="--",
                label=f"Elton-Gruber: {st.ELTON_GRUBER_1970}")
axes[0].set_xlabel("drop ratio for one event (clipped)"); axes[0].legend(fontsize=8)
axes[0].set_title("Every ex-date, individually")
axes[1].scatter(ev["dividend"], ev["adjusted_drop"], s=12, alpha=0.35, color="#2ea44f")
lim = ev["dividend"].max() * 1.1
axes[1].plot([0, lim], [0, lim], color="k", lw=1.5, label="a full drop")
axes[1].set_xlabel("dividend ($)"); axes[1].set_ylabel("price drop ($)")
axes[1].set_ylim(-lim * 3, lim * 3); axes[1].legend(fontsize=8)
axes[1].set_title("The regression the verdict is built on")
plt.show()
"""
        ),
        md(
            r"""

## 4 · Four answers to one question
"""
        ),
        code(
            r"""
tbl = st.estimator_table(ev)
print(tbl.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 4))
tbl["value"].plot.barh(ax=ax, color="#2ea44f")
ax.axvline(1.0, color="k", lw=2, label="a full drop")
ax.axvline(st.ELTON_GRUBER_1970, color="#c0392b", lw=2, ls="--", label="Elton-Gruber 1970")
ax.set_xlabel("drop ratio"); ax.legend(fontsize=8)
plt.setp(ax.get_yticklabels(), fontsize=8)
plt.show()
print(f"\nSpread between the four: {tbl['value'].max() - tbl['value'].min():.3f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** That spread is the study. It is larger than the difference
> between "a full drop" and the famous 0.778 — so a paper that quotes a drop ratio without
> saying which of these four it computed has not told you very much.
"""
        ),
        md(
            r"""

## 5 · Could you trade it?
"""
        ),
        code(
            r"""
for c in (0.0, 1.0, 2.0, 5.0, 10.0):
    r = st.capture_trade(ev, cost_bps=c)
    print(f"cost {c:5.1f} bps/side -> net {r['mean_net_bps']:+7.1f} bps/event, "
          f"t {r['t']:+5.2f}, hit rate {r['hit_rate']:.0%}")
r = st.capture_trade(ev, cost_bps=2.0)
print(f"\nper-event dispersion: {r['sd_bps']:.0f} bps against a mean of "
      f"{r['mean_net_bps']:+.1f} bps")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: None.** Across **1025 ex-dates** on 12 mega-cap payers (2005-01-06 → 2026-06-15), a dollar of dividend took **1.003** of a dollar out of the price once that day's market move is removed (HC1 *t* against 1.0 = **+0.14**; against zero +53.13). The four defensible summaries of the same events disagree by more than the effect anyone is arguing about: the mean per-event ratio is +1.13, the median 1.13, total-drop-over-total-dividend 1.133, the regression slope 1.003. That spread is not sloppiness — the per-event ratio divides a 1.4% daily move by a 0.85% dividend, so 29% of individual events land outside the range [0, 2] entirely. Elton and Gruber's 0.778 sits outside the bootstrap interval [1.052, 1.218].

**Tradability: Mirage.** Buying at the cum close and selling at the ex close, keeping the dividend, earned **-11.9 bps** gross per event and **-15.9 bps** after 2 bps a side (*t* = -4.04, 45% of events profitable, dispersion 126 bps). The trade breaks even at -5.9 bps of round-trip cost, and at the 15% qualified-dividend rate a taxable holder nets -31.8 bps. The edge, if it is one, is smaller than the noise on a single event by a factor of 8.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Use the opening price.** The drop happens at the auction; measuring to the ex-day *close*
  adds a whole day of noise for nothing.
- **High-yield names and REITs**, where the dividend is large enough to measure against the
  noise and where tax clienteles should bite hardest.
- **Special dividends**, which are big, irregular, and the cleanest natural experiment of all.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# A Dollar Off — a quantitative teardown \U0001F52C
### Corporate-actions audit · market-adjusted events · four estimators against a planted truth

![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The interesting
result here is not the drop ratio. It is that four defensible ways of computing the drop ratio
disagree by more than the quantity anyone is arguing about.

> ⚠️ **Not investment advice.** Raw, **dividend-unadjusted** closes plus Yahoo's
> corporate-actions feed, pinned as-of the date in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from exday import data, strategy as st

bars = data.load_bars()
px = data.load_prices()
ev = st.build_events(bars, data.MARKET)
print(f"as-of {data.AS_OF} | {len(ev)} ex-dates on {ev['ticker'].nunique()} payers, "
      f"{ev.index[0].date()} -> {ev.index[-1].date()}")
print(f"median yield per event {ev['yield'].median():.3%}   "
      f"typical daily move {px[list(data.PAYERS)].pct_change().stack().std():.2%}")
print(ev.head()[["ticker", "price_cum", "price_ex", "dividend", "raw_ratio",
                 "adjusted_ratio"]].round(4).to_string())
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | None | Across **1025 ex-dates** on 12 mega-cap payers (2005-01-06 → 2026-06-15), a dollar of dividend took **1.003** of a dollar out of the price once that day's market move is removed (HC1 *t* against 1.0 = **+0.14**; against zero +53.13). The four defensible summaries of the same events disagree by more than the effect anyone is arguing about: the mean per-event ratio is +1.13, the median 1.13, total-drop-over-total-dividend 1.133, the regression slope 1.003. That spread is not sloppiness — the per-event ratio divides a 1.4% daily move by a 0.85% dividend, so 29% of individual events land outside the range [0, 2] entirely. Elton and Gruber's 0.778 sits outside the bootstrap interval [1.052, 1.218]. |
| **Tradability** | Mirage | Buying at the cum close and selling at the ex close, keeping the dividend, earned **-11.9 bps** gross per event and **-15.9 bps** after 2 bps a side (*t* = -4.04, 45% of events profitable, dispersion 126 bps). The trade breaks even at -5.9 bps of round-trip cost, and at the 15% qualified-dividend rate a taxable holder nets -31.8 bps. The edge, if it is one, is smaller than the noise on a single event by a factor of 8. |

> \U0001F4A1 **In plain words.** The price does fall, by roughly the dividend. Pinning down
> "roughly" is harder than the literature's confidence suggests.
"""
        ),
        md(
            r"""

## 1 · The data, audited before it is used

This study cannot use a total-return tape: an `auto_adjust=True` close has already had the
ex-day drop removed, so measuring the drop in it returns 1.000 by construction. It therefore
keeps its own cache of raw closes plus the corporate-actions dividend column — and audits that
feed before trusting it.
"""
        ),
        code(
            r"""
sr = data.sanity_report()
print(sr.round(4).to_string())
print(f"\ntotal ex-dates: {int(sr['ex_days'].sum())}")
print(f"tickers with odd payment spacing: {int((sr['suspicious_gaps'] > 0).sum())} of {len(sr)}")
"""
        ),
        md(
            r"""

## 2 · Hypotheses

- **H₁.** The dollar drop equals the dollar dividend: the regression slope is 1.0.
- **H₂ (Elton-Gruber).** It is materially below 1.0 — about 0.78 — and that shortfall is the
  marginal holder's tax rate.
- **H₃ (measurement).** The four standard estimators of the same quantity disagree by more than
  the difference between H₁ and H₂, in which case neither is established by this data.
- **H₄.** The shortfall, whatever it is, is not large enough to trade after costs.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Event construction and the market adjustment
"""
        ),
        code(
            r"""
print(ev[["price_cum", "price_ex", "dividend", "yield", "beta", "market_return",
           "raw_ratio", "adjusted_ratio"]].describe().round(4).to_string())
fig, ax = plt.subplots(figsize=(11, 4.5))
ax.hist(ev["raw_ratio"].clip(-6, 8), bins=100, alpha=0.55, color="#8b949e",
        label=f"raw (sd {ev['raw_ratio'].std():.2f})")
ax.hist(ev["adjusted_ratio"].clip(-6, 8), bins=100, alpha=0.65, color="#2ea44f",
        label=f"market-adjusted (sd {ev['adjusted_ratio'].std():.2f})")
ax.axvline(1.0, color="k", lw=2)
ax.set_xlabel("drop ratio (clipped to [-6, 8])"); ax.legend()
ax.set_title("Removing the ex-day market move is the single most useful correction")
plt.show()
"""
        ),
        md(
            r"""

### 3.2 The dispersion diagnostic
"""
        ),
        code(
            r"""
print(pd.DataFrame({"market-adjusted": st.ratio_dispersion(ev),
                    "raw": st.ratio_dispersion(ev, "raw_ratio")}).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Read the gap between `mean` and `trimmed_mean`, and the share
> of events outside [0, 2]. A sample in which a third of the observations are wilder than
> "the price moved twice the dividend, or the wrong way" is not one whose mean estimates a drop
> ratio.
"""
        ),
        md(
            r"""

### 3.3 The four estimators, and bootstrap intervals for each
"""
        ),
        code(
            r"""
print(st.estimator_table(ev).round(4).to_string())
print()
rows = []
for label, est in (("total drop / total dividend", st.ratio_of_sums),
                   ("regression slope", lambda e: st.regression_slope(e)["slope"]),
                   ("median ratio", st.median_of_ratios),
                   ("mean ratio", st.mean_of_ratios)):
    ci = st.bootstrap_ci(ev, est, n_boot=1500)
    rows.append({"estimator": label, "point": ci["point"], "lo": ci["lo"], "hi": ci["hi"],
                 "width": ci["hi"] - ci["lo"]})
d = pd.DataFrame(rows).set_index("estimator")
fig, ax = plt.subplots(figsize=(10, 4))
ax.errorbar(d["point"], range(len(d)),
            xerr=[d["point"] - d["lo"], d["hi"] - d["point"]], fmt="o", capsize=5,
            color="#2ea44f")
ax.axvline(1.0, color="k", lw=2, label="a full drop")
ax.axvline(st.ELTON_GRUBER_1970, color="#c0392b", lw=2, ls="--", label="Elton-Gruber")
ax.set_yticks(range(len(d))); ax.set_yticklabels(d.index, fontsize=8)
ax.legend(fontsize=8)
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.4 Cuts: yield, name, era
"""
        ),
        code(
            r"""
print(st.yield_buckets(ev).round(4).to_string())
print()
print(st.by_group(ev, "ticker").round(4).to_string())
e2 = ev.copy()
e2["era"] = np.where(e2.index < pd.Timestamp("2013-01-01"), "2005-2012",
                     np.where(e2.index < pd.Timestamp("2019-01-01"), "2013-2018", "2019-"))
print()
print(st.by_group(e2, "era").round(4).to_string())
"""
        ),
        code(
            r"""
yb = st.yield_buckets(ev)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
yb["slope"].plot.bar(ax=axes[0], color="#2ea44f")
axes[0].axhline(1.0, color="k", lw=1.5)
axes[0].set_ylabel("regression slope"); axes[0].set_title("by dividend size")
plt.setp(axes[0].get_xticklabels(), rotation=0)
by_tk = st.by_group(ev, "ticker").sort_values("slope")
by_tk["slope"].plot.barh(ax=axes[1], color="#8b949e")
axes[1].axvline(1.0, color="k", lw=1.5)
axes[1].set_xlabel("regression slope"); axes[1].set_title("by name")
plt.setp(axes[1].get_yticklabels(), fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

### 3.5 Which estimator would have found a planted truth?

The generator plants a known drop fraction under realistic noise. Everything above is opinion
until this table says which estimator to believe.
"""
        ),
        code(
            r"""
rows = []
for frac in (0.4, 0.6, 0.8, 1.0, 1.2):
    acc = {"mean": [], "median": [], "sums": [], "slope": []}
    for s in range(5):
        sb = data.synthetic_panel(n=3000, n_tickers=12, drop_fraction=frac, seed=984 + s)
        se = st.build_events(sb, "MKT")
        acc["mean"].append(st.mean_of_ratios(se))
        acc["median"].append(st.median_of_ratios(se))
        acc["sums"].append(st.ratio_of_sums(se))
        acc["slope"].append(st.regression_slope(se)["slope"])
    rows.append({"planted": frac, **{k: float(np.mean(v)) for k, v in acc.items()}})
d = pd.DataFrame(rows).set_index("planted")
fig, ax = plt.subplots(figsize=(9.5, 5))
for c, col in zip(d.columns, ["#c0392b", "#f0b429", "#2ea44f", "#1f6feb"]):
    ax.plot(d.index, d[c], marker="o", label=c, color=col)
ax.plot(d.index, d.index, color="k", ls="--", lw=1.5, label="truth")
ax.set_xlabel("planted drop fraction"); ax.set_ylabel("estimate"); ax.legend(fontsize=8)
ax.set_title("Only the estimators that hug the dashed line can be trusted here")
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

### 3.6 The capture trade, priced
"""
        ),
        code(
            r"""
rows = []
for c in (0.0, 1.0, 2.0, 5.0, 10.0, 20.0):
    for tax in (0.0, 0.15, 0.37):
        r = st.capture_trade(ev, cost_bps=c, div_tax=tax)
        rows.append({"cost_bps": c, "tax": tax, "net_bps": r["mean_net_bps"], "t": r["t"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 4.5))
d.pivot(index="cost_bps", columns="tax", values="net_bps").plot(ax=ax, marker="o")
ax.axhline(0, color="k", lw=1.5)
ax.set_ylabel("net per event (bps)"); ax.legend(title="dividend tax", fontsize=8)
plt.show()
d.round(2).to_string(index=False)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
reg = st.regression_slope(ev)
ci = st.bootstrap_ci(ev, st.ratio_of_sums, n_boot=1500)
tbl = st.estimator_table(ev)
tr = st.capture_trade(ev, cost_bps=2.0)
pd.DataFrame({
    "events": [len(ev)],
    "regression slope": [reg["slope"]],
    "t vs a full drop": [reg["t_vs_one"]],
    "total drop / total dividend": [st.ratio_of_sums(ev)],
    "bootstrap 95% low": [ci["lo"]],
    "bootstrap 95% high": [ci["hi"]],
    "spread across four estimators": [tbl["value"].max() - tbl["value"].min()],
    "share of events outside [0,2]": [st.ratio_dispersion(ev)["share_outside_0_2"]],
    "capture trade net (bps)": [tr["mean_net_bps"]],
    "capture trade t": [tr["t"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Open prices.** The ex-day adjustment happens in the opening auction. A close-to-close
  measurement adds ~1.2% of noise to a 0.7% signal for no reason; open-to-previous-close would
  roughly halve the standard error and is the single best available improvement.
- **Fieller intervals** rather than a percentile bootstrap for the ratio estimators — the
  textbook treatment for a ratio whose denominator is uncertain.
- **High-yield and special dividends**, where the denominator finally exceeds the noise.
- **Cross-country**: markets with no dividend tax (Frank & Jagannathan 1998) separate the tax
  story from the microstructure one.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
