"""Notebook builder for Study 994 — The Rounding Tax.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Rounding Tax \U0001FA99
### Your model portfolio says 40% SPY. Your $3,000 account says four shares.

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Every asset-allocation article in the world is written in percentages. Percentages assume you
can buy 3.7 shares. For most of investing history, and still today in most retirement plans and
most non-US brokerages, you cannot — so the portfolio you own is the rounded one.

> \U0001F4D3 **This is the plain-language layer.** The allocation algorithm, the drag/noise
> decomposition and the escapes are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does whole-share rounding matter? | Below about $25,000, yes, visibly. |
| Does it cost you money? | Much less than it costs you *precision*. |
| Why the difference? | Being overweight is as likely as underweight. It cancels. |
| What actually fixes it? | Holding fewer funds — more than fractional shares do. |
"""
        ),
        md(
            r"""

## 1 · The portfolio on paper
"""
        ),
        code(
            r"""
from roundingtax import data, strategy as st

px = data.load_prices()
target = dict(data.TARGET)
names = [t for t in target if t in px.columns]
panel = px[names].dropna()
last = panel.iloc[-1]
print(f"as-of {data.AS_OF} | {len(panel):,} sessions, "
      f"{panel.index[0].date()} -> {panel.index[-1].date()}")
for t in names:
    print(f"  {t:6s} target {target[t]:>4.0%}   ${last[t]:8.2f} per share")
print(f"\none share of everything: ${st.one_share_cost(target, last):,.2f}")
"""
        ),
        md(
            r"""

## 2 · The portfolio you can actually buy
"""
        ),
        code(
            r"""
for cap in (1000, 3000, 10_000, 100_000):
    a = st.whole_share_allocation(target, last, float(cap))
    e = st.allocation_error(a)
    print(f"\n${cap:,} account:")
    for t in names:
        sh = a["shares"].get(t, 0.0)
        print(f"  {t:6s} {sh:6.0f} shares = ${sh * last[t]:9,.2f}  "
              f"= {a['weights'].get(t, 0):5.1%}   (target {target[t]:.0%})")
    print(f"  cash left over: ${a['cash']:,.2f} ({e['cash_share']:.1%})")
    print(f"  total miss: {e['l1']:.1%}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The allocator uses **largest remainder**, not naive flooring.
> Flooring each position independently would leave far more cash idle and would overstate the
> cost of being small — the direction this study must not err in.
"""
        ),
        md(
            r"""

## 3 · How big does an account need to be?
"""
        ),
        code(
            r"""
ev = st.error_vs_capital(target, last)
fig, ax = plt.subplots(figsize=(10, 5))
ax.semilogx(ev.index, ev["l1_error"] * 100, "o-", lw=2, color="#c0392b",
            label="total allocation miss")
ax.semilogx(ev.index, ev["cash_share"] * 100, "s-", lw=2, color="#f0b429",
            label="uninvested cash")
ax.axhline(1, ls="--", color="#8b949e", lw=1, label="1 percentage point")
ax.set_xlabel("account size ($)"); ax.set_ylabel("% of the portfolio")
ax.legend(fontsize=8)
plt.show()
print(f"one share of each:                   ${st.one_share_cost(target, last):>10,.0f}")
print(f"enough to hit every weight within 1pp: ${st.min_viable_capital(target, last):>10,.0f}")
"""
        ),
        md(
            r"""

Those two numbers are usually confused. Buying one share of everything gets you *a* portfolio.
Its weights are decided by the share prices, not by you.
"""
        ),
        md(
            r"""

## 4 · Twenty years later, what did it cost?
"""
        ),
        code(
            r"""
cash_rate = px[data.CASH].pct_change().reindex(panel.index).fillna(0.0)
cmp = st.compare_to_ideal(panel, target, 3000.0, cash_rate, cost_bps=5.0)
whole = st.rebalance_simulation(panel, target, 3000.0, cash_rate, cost_bps=5.0)
frac = st.rebalance_simulation(panel, target, 3000.0, cash_rate, cost_bps=5.0,
                               allow_fractional=True)
fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(whole["value"].index, whole["value"], lw=1.8, color="#c0392b",
        label=f"whole shares ({cmp['cagr_whole']:+.2%}/yr)")
ax.plot(frac["value"].index, frac["value"], lw=1.8, color="#2ea44f",
        label=f"fractional shares ({cmp['cagr_fractional']:+.2%}/yr)")
ax.set_ylabel("value of a $3,000 account ($)"); ax.legend(fontsize=9)
plt.show()
print(f"gap: {cmp['cagr_gap']:+.2%}/yr, tracking error {cmp['tracking_error']:.2%}/yr")
print(f"after {cmp['years']:.0f} years the whole-share account ended "
      f"{cmp['final_gap_pct']:+.1%} vs the ideal")
"""
        ),
        md(
            r"""

## 5 · The bit that matters: is that a cost, or a coin flip?
"""
        ),
        code(
            r"""
dec = st.decompose_shortfall(cmp, 0.02, 0.06)
fig, ax = plt.subplots(figsize=(9.5, 4.5))
parts = ["cash_drag", "trading_costs", "unexplained_noise"]
labels = ["cash drag\n(compounds)", "trading costs\n(compounds)",
          "noise\n(cancels)"]
colors = ["#c0392b", "#f0b429", "#8b949e"]
ax.bar(labels, [dec[p] * 100 for p in parts], color=colors)
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("contribution to the annual gap (%)")
plt.show()
for p, l in zip(parts, labels):
    print(f"{l.splitlines()[0]:16s} {dec[p]:+.3%}/yr")
print(f"\ntotal gap {dec['total_gap']:+.3%}/yr, of which {dec['drag_share']:.0%} is genuine "
      f"drag")
"""
        ),
        md(
            r"""

The grey bar is the one everyone counts as a cost. It is not: being accidentally overweight
equities is as likely as accidentally underweight, and across many accounts and many years it
averages out. Only the red and amber bars are money you never see again.
"""
        ),
        md(
            r"""

## 6 · What actually helps
"""
        ),
        code(
            r"""
esc_panel = px[[c for c in px.columns if c != data.CASH]].dropna()
swaps = {data.CORE: data.CHEAP_CORE} if data.CHEAP_CORE in px.columns else None
esc = st.escape_table(esc_panel, target, 3000.0, cash_rate, swaps, cost_bps=5.0)
fig, ax = plt.subplots(figsize=(10, 4.5))
e = esc.sort_values("mean_l1_error")
ax.barh(range(len(e)), e["mean_l1_error"] * 100, color="#2ea44f")
ax.set_yticks(range(len(e))); ax.set_yticklabels(e.index, fontsize=8)
ax.set_xlabel("average distance from the target allocation (%)")
plt.show()
print(esc.round(4).to_string())
"""
        ),
        md(
            r"""

## 7 · The verdict

**Signal: Weak.** A **$3,000** account holding the 6-fund target could not place it: the achieved weights missed the plan by **5.4%** in total absolute terms on average, worst position off by 17.2%, and **0.6%** of the account sat in uninvested residue. Against a fractional-share portfolio running the identical plan, the tracking error was **0.28%/yr** over 15 years. Two numbers put that in proportion. One share of each fund costs $1,518 — the figure usually quoted — but the account that actually *hits* the target weights to within one percentage point is **$38,857**, an order of magnitude more, because owning one of everything gives you a portfolio whose weights are set by share prices rather than by your plan.

**Tradability: Partial.** But the shortfall is mostly **noise, not drag**, and the difference decides the advice. Over 15 years the whole-share portfolio compounded at +9.10% against the fractional ideal's +9.20% — a gap of **-0.10%/yr**, of which cash drag explains -0.03% and trading costs -0.01%, leaving -0.06% that is simply which way the dice fell. Allocation error is mean-zero — you are as likely to be overweight as under — so it produces tracking error without an expected cost; only the cash residue is one-directional. The fix that works is not fractional shares but **fewer funds**: cutting the target to its three largest positions dropped the allocation error from 5.4% to **3.4%**.
"""
        ),
        md(
            r"""

## 8 · Going further \U0001F6AA

- **Regular contributions fix most of this.** New money can be directed at whichever sleeve is
  furthest below target, which is a free rebalancing mechanism. This study deliberately omits
  it, and it is the single largest omission.
- **Fractional shares** now exist at most large US brokers — but not in most retirement plans,
  most non-US brokers, or inside most wrappers.
- **A target-date fund** solves the whole problem by doing the rounding inside a single share,
  at the cost of an expense ratio. Comparing that fee against the numbers above is the real
  decision.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Rounding Tax — a quantitative teardown \U0001F52C
### Largest-remainder allocation · error-versus-capital · drag vs mean-zero noise

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The central
distinction is between a shortfall that **compounds** and one that **cancels**, because they
lead to opposite advice and are almost always quoted as one number.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from roundingtax import data, strategy as st

px = data.load_prices()
target = dict(data.TARGET)
names = [t for t in target if t in px.columns]
panel = px[names].dropna()
last = panel.iloc[-1]
print(f"as-of {data.AS_OF} | {len(panel):,} sessions, "
      f"{panel.index[0].date()} -> {panel.index[-1].date()}")
for t in names:
    print(f"  {t:6s} target {target[t]:>4.0%}   ${last[t]:8.2f} per share")
print(f"\none share of everything: ${st.one_share_cost(target, last):,.2f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | A **$3,000** account holding the 6-fund target could not place it: the achieved weights missed the plan by **5.4%** in total absolute terms on average, worst position off by 17.2%, and **0.6%** of the account sat in uninvested residue. Against a fractional-share portfolio running the identical plan, the tracking error was **0.28%/yr** over 15 years. Two numbers put that in proportion. One share of each fund costs $1,518 — the figure usually quoted — but the account that actually *hits* the target weights to within one percentage point is **$38,857**, an order of magnitude more, because owning one of everything gives you a portfolio whose weights are set by share prices rather than by your plan. |
| **Tradability** | Partial | But the shortfall is mostly **noise, not drag**, and the difference decides the advice. Over 15 years the whole-share portfolio compounded at +9.10% against the fractional ideal's +9.20% — a gap of **-0.10%/yr**, of which cash drag explains -0.03% and trading costs -0.01%, leaving -0.06% that is simply which way the dice fell. Allocation error is mean-zero — you are as likely to be overweight as under — so it produces tracking error without an expected cost; only the cash residue is one-directional. The fix that works is not fractional shares but **fewer funds**: cutting the target to its three largest positions dropped the allocation error from 5.4% to **3.4%**. |

> \U0001F4A1 **In plain words.** The constraint is real and the *cost* is smaller than it looks,
> because most of the shortfall is a coin flip rather than a leak.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** Whole-share rounding produces allocation error that scales roughly as 1/capital.
- **H₂.** It produces tracking error against a fractional-share twin running the same plan.
- **H₃ (the sharp one).** Most of the realised CAGR gap is **mean-zero noise**, not drag: the
  explainable components (cash residue, trading costs) account for a minority of it, and the
  residual changes sign across account sizes.
- **H₄.** Share *price level*, not returns, is the mechanism — provable by holding returns fixed
  and varying only the price.
- **H₅.** Reducing the number of funds helps more than fractional shares do.
"""
        ),
        md(
            r"""

## 2 · The allocator, checked by hand
"""
        ),
        code(
            r"""
# a case with an exact answer
p = pd.Series({"A": 100.0, "B": 50.0})
a = st.whole_share_allocation({"A": 0.5, "B": 0.5}, p, 1000.0)
print("clean case:", a["shares"], "cash", a["cash"])

# largest remainder against naive flooring
p2 = pd.Series({"A": 99.0, "B": 98.0, "C": 97.0})
t2 = {"A": 1 / 3, "B": 1 / 3, "C": 1 / 3}
a2 = st.whole_share_allocation(t2, p2, 1000.0)
naive = {t: float(np.floor(1000 / 3 / p2[t])) for t in t2}
naive_cash = 1000 - sum(naive[t] * p2[t] for t in t2)
print(f"\nnaive flooring:      {naive}, ${naive_cash:.2f} idle")
print(f"largest remainder:   {a2['shares']}, ${a2['cash']:.2f} idle")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** This is the apportionment problem — the same arithmetic used to
> turn vote shares into whole parliamentary seats. Using the naive method would have made the
> whole-share case look worse than it is.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Error against capital, at several dates
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(10, 5.5))
for frac_i, colour in ((0.0, "#8b949e"), (0.5, "#1f6feb"), (1.0, "#c0392b")):
    i = int(frac_i * (len(panel) - 1))
    row = panel.iloc[i]
    ev = st.error_vs_capital(target, row)
    ax.loglog(ev.index, ev["l1_error"] * 100, "o-", lw=1.6, ms=4, color=colour,
              label=str(panel.index[i].date()))
ax.axhline(1, ls="--", color="k", lw=1)
ax.set_xlabel("account size ($)"); ax.set_ylabel("allocation error (%, log)")
ax.legend(fontsize=8, title="prices as of")
plt.show()
rows = []
for frac_i in (0.0, 0.25, 0.5, 0.75, 1.0):
    i = int(frac_i * (len(panel) - 1))
    row = panel.iloc[i]
    rows.append({"date": panel.index[i].date(),
                 "one share of each": st.one_share_cost(target, row),
                 "viable at 1pp": st.min_viable_capital(target, row, 0.01),
                 "viable at 0.5pp": st.min_viable_capital(target, row, 0.005)})
pd.DataFrame(rows).set_index("date").round(0)
"""
        ),
        md(
            r"""

### 3.2 The forward simulation, many account sizes
"""
        ),
        code(
            r"""
cash_rate = px[data.CASH].pct_change().reindex(panel.index).fillna(0.0)
rows = []
for cap in (1000, 2000, 3000, 5000, 10_000, 25_000, 50_000, 100_000, 500_000):
    c = st.compare_to_ideal(panel, target, float(cap), cash_rate, cost_bps=5.0)
    rows.append({"capital": cap, **{k: c[k] for k in
                 ("tracking_error", "cagr_gap", "mean_l1_error", "mean_cash_share")}})
d = pd.DataFrame(rows).set_index("capital")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].loglog(d.index, d["tracking_error"] * 100, "o-", lw=2, color="#c0392b")
axes[0].set_xlabel("account size ($)"); axes[0].set_ylabel("tracking error (%/yr)")
axes[0].set_title("falls roughly as 1/capital")
axes[1].semilogx(d.index, d["cagr_gap"] * 100, "o-", lw=2, color="#1f6feb")
axes[1].axhline(0, color="k", lw=1.5)
axes[1].set_xlabel("account size ($)"); axes[1].set_ylabel("CAGR gap (%/yr)")
axes[1].set_title("but the RETURN gap is noisy and changes sign")
plt.tight_layout(); plt.show()
d.round(5)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Two panels, two different stories. Tracking error is a clean
> monotone function of size — that is the constraint biting. The return gap wanders around zero
> — that is the constraint being mean-zero. Confusing the two is the mistake this study exists
> to prevent.
"""
        ),
        md(
            r"""

### 3.3 The decomposition
"""
        ),
        code(
            r"""
rows = []
for cap in (1000, 2000, 3000, 5000, 10_000, 25_000):
    c = st.compare_to_ideal(panel, target, float(cap), cash_rate, cost_bps=5.0)
    dd = st.decompose_shortfall(c, 0.02, 0.06)
    rows.append({"capital": cap, **{k: dd[k] for k in
                 ("total_gap", "cash_drag", "trading_costs", "unexplained_noise")}})
d = pd.DataFrame(rows).set_index("capital")
fig, ax = plt.subplots(figsize=(10.5, 5))
bottom_pos = np.zeros(len(d))
for col, colour in (("cash_drag", "#c0392b"), ("trading_costs", "#f0b429"),
                    ("unexplained_noise", "#8b949e")):
    ax.bar([str(i) for i in d.index], d[col] * 100, bottom=bottom_pos * 100,
           color=colour, label=col.replace("_", " "))
    bottom_pos = bottom_pos + d[col]
ax.plot(range(len(d)), d["total_gap"] * 100, "ko-", lw=2, ms=6, label="total gap")
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("account size ($)"); ax.set_ylabel("annual contribution (%)")
ax.legend(fontsize=8)
plt.show()
d.round(5)
"""
        ),
        md(
            r"""

### 3.4 The mechanism, isolated
"""
        ),
        code(
            r"""
rows = []
for level in (10, 20, 40, 60, 100, 150, 250, 400, 600, 900):
    sp = st.synthetic_prices(n=2520, price_levels=(float(level),) * 6)
    tgt6 = {f"F{k}": 1 / 6 for k in range(6)}
    for cap in (2000, 10_000, 50_000):
        c = st.compare_to_ideal(sp, tgt6, float(cap))
        rows.append({"share_price": level, "capital": cap,
                     "mean_l1_error": c["mean_l1_error"],
                     "tracking_error": c["tracking_error"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for cap, g in d.groupby("capital"):
    axes[0].loglog(g["share_price"], g["mean_l1_error"] * 100, "o-", lw=1.6,
                   label=f"${cap:,}")
    axes[1].loglog(g["share_price"], g["tracking_error"] * 100, "o-", lw=1.6,
                   label=f"${cap:,}")
axes[0].set_xlabel("share price ($)"); axes[0].set_ylabel("allocation error (%)")
axes[1].set_xlabel("share price ($)"); axes[1].set_ylabel("tracking error (%/yr)")
for a in axes:
    a.legend(fontsize=8, title="account")
plt.tight_layout(); plt.show()
print("Identical return series in every point. Only the price LEVEL differs.")
"""
        ),
        md(
            r"""

### 3.5 Number of funds, and the diversification it costs
"""
        ),
        code(
            r"""
esc_panel = px[[c for c in px.columns if c != data.CASH]].dropna()
rows = []
for keep in (2, 3, 4, 5, 6):
    tgt_k = st.fewer_funds_variant(target, keep)
    for cap in (2000, 5000, 20_000):
        s = st.rebalance_simulation(esc_panel, tgt_k, float(cap), cash_rate, cost_bps=5.0)
        if "cagr" not in s:
            continue
        rows.append({"funds": keep, "capital": cap, "cagr": s["cagr"], "vol": s["vol"],
                     "error": s["mean_l1_error"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for cap, g in d.groupby("capital"):
    axes[0].plot(g["funds"], g["error"] * 100, "o-", lw=1.8, label=f"${cap:,}")
axes[0].set_xlabel("number of funds held"); axes[0].set_ylabel("allocation error (%)")
axes[0].legend(fontsize=8)
for cap, g in d.groupby("capital"):
    axes[1].plot(g["funds"], g["vol"] * 100, "o-", lw=1.8, label=f"${cap:,}")
axes[1].set_xlabel("number of funds held"); axes[1].set_ylabel("portfolio volatility (%)")
axes[1].legend(fontsize=8)
axes[1].set_title("the price of simplifying")
plt.tight_layout(); plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The left panel is the benefit of holding fewer funds; the right
> panel is the cost. For a small account the left panel moves a lot and the right panel barely
> moves — which is the whole argument for a simple portfolio, made quantitatively rather than
> as a slogan.
"""
        ),
        md(
            r"""

### 3.6 No-trade bands
"""
        ),
        code(
            r"""
rows = []
for band in (0.0, 0.01, 0.02, 0.05, 0.10, 0.20, 0.30):
    for cap in (3000, 20_000):
        s = st.rebalance_simulation(panel, target, float(cap), cash_rate,
                                    cost_bps=5.0, band=band)
        rows.append({"band": band, "capital": cap, "cagr": s["cagr"],
                     "rebalances": s["n_rebalances"], "costs": s["cost_share"],
                     "error": s["mean_l1_error"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for cap, g in d.groupby("capital"):
    axes[0].plot(g["band"] * 100, g["costs"] * 100, "o-", lw=1.8, label=f"${cap:,}")
    axes[1].plot(g["band"] * 100, g["error"] * 100, "o-", lw=1.8, label=f"${cap:,}")
axes[0].set_xlabel("no-trade band (%)"); axes[0].set_ylabel("lifetime costs (% of capital)")
axes[1].set_xlabel("no-trade band (%)"); axes[1].set_ylabel("allocation error (%)")
for a in axes:
    a.legend(fontsize=8)
plt.tight_layout(); plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
cmp = st.compare_to_ideal(panel, target, 3000.0, cash_rate, cost_bps=5.0)
dec = st.decompose_shortfall(cmp, 0.02, 0.06)
esc = st.escape_table(esc_panel, target, 3000.0, cash_rate,
                      {data.CORE: data.CHEAP_CORE} if data.CHEAP_CORE in px.columns else None,
                      cost_bps=5.0)
alt = esc.drop(["whole shares, as specified", "fractional shares"], errors="ignore")
pd.DataFrame({
    "one share of everything": [st.one_share_cost(target, last)],
    "account needed for 1pp accuracy": [st.min_viable_capital(target, last)],
    "allocation error at $3,000": [cmp["mean_l1_error"]],
    "tracking error at $3,000": [cmp["tracking_error"]],
    "annual CAGR gap": [cmp["cagr_gap"]],
    "of which cash drag": [dec["cash_drag"]],
    "of which trading costs": [dec["trading_costs"]],
    "of which mean-zero noise": [dec["unexplained_noise"]],
    "best escape": [alt["mean_l1_error"].idxmin() if len(alt) else "none"],
    "its allocation error": [alt["mean_l1_error"].min() if len(alt) else np.nan],
}).T.rename(columns={0: "value"})
"""
        ),
        md(
            r"""

## 5 · Going further

- **Model regular contributions.** New cash directed at the most-underweight sleeve is a free
  rebalancing mechanism and would shrink almost every number here. Its omission is the largest
  in the study and it biases against small accounts.
- **Unadjusted prices.** Section 1 flags that adjusted closes understate historical share prices
  and therefore understate the constraint. Reconstructing true trade prices would strengthen the
  finding.
- **Integer programming.** `whole_share_allocation` uses largest remainder, which is a good
  heuristic and not the optimum. Solving the actual mixed-integer problem (Mansini & Speranza
  1999) would put a lower bound on the achievable error.
- **Compare against a target-date fund's expense ratio.** That is the decision a real small
  investor faces, and it is a straight comparison between the numbers here and a fee.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
