# Study 951 — The Crossover Rung 🪜

**Is the BBB/BB boundary the best-paid rung on the credit ladder?**

Credit is sold as a ladder — aggregate, investment grade, *crossover*, high yield — and the
folklore says the best-paid step is the **boundary** between investment grade and junk.
The story is institutional: when an issuer is downgraded out of investment grade, mandates
and insurance capital rules *force* holders to sell, while the natural buyers are slow or
constrained. Somebody should be collecting the discount.

We race the whole ladder on daily **total-return** closes — **AGG → LQD → ANGL → HYG** —
every rung **excess of cash** (BIL) and then adjusted for **duration** (IEF) and **equity
beta** (SPY), so the winner is not simply whoever carries the most risk.
Window 2012-04-11 → 2026-06-30 (3,575 days), gated by ANGL's inception.

*Real-tape numbers below are the frozen headline (`docs/results.md`, Fingerprint
`b2e46afc7601`); the live cells run the offline **synthetic** control only. As-of 2026-06-30.*


## 1. The rungs, and what each one actually paid

Excess-of-cash **Sharpe** is reward per unit of risk — how much you were paid for the bumps you wore. Walk up the ladder and it rises, peaks on the crossover rung, and then *falls* as you go deeper into high yield. The ladder has a hump, and the hump is on the boundary. That much of the folklore is simply true.

In [1]:
R = dict(agg=(0.113, 0.55, 4.86, -18.4, -0.48, -0.94, 0.71, 0.07, 0.84), lqd=(0.241, 1.89, 7.82, -25.0, -0.67, -0.49, 0.97, 0.18, 0.67), angl=(0.602, 5.57, 9.25, -29.3, 0.84, 0.42, 0.34, 0.35, 0.39), hyg=(0.437, 3.42, 7.82, -22.0, -1.67, -1.23, 0.27, 0.37, 0.62))
names = {'agg':'AGG  aggregate     ', 'lqd':'LQD  investment grade',
         'angl':'ANGL crossover     ', 'hyg':'HYG  broad high yield'}
for k in ('agg','lqd','angl','hyg'):
    s, exr, vol, dd = R[k][0], R[k][1], R[k][2], R[k][3]
    bar = '#' * int(round(s * 30))
    print('%s  Sharpe %+.3f  %-20s  earned %+.2f%%/yr, worst fall %.1f%%'
          % (names[k], s, bar, exr, dd))

AGG  aggregate       Sharpe +0.113  ###                   earned +0.55%/yr, worst fall -18.4%
LQD  investment grade  Sharpe +0.241  #######               earned +1.89%/yr, worst fall -25.0%
ANGL crossover       Sharpe +0.602  ##################    earned +5.57%/yr, worst fall -29.3%
HYG  broad high yield  Sharpe +0.437  #############         earned +3.42%/yr, worst fall -22.0%


> 🔬 **For the quants** — Sharpe here is *excess of cash*: each rung's daily total return minus BIL's, so the 2023-2026 era of 5% short rates does not flatter a bond fund that merely earned the bill rate. Drawdowns are *absolute* (what you lived through), not excess.

## 2. Why the raw ladder is a rigged race

The crossover rung earned more *because it took different risks*: more equity-like credit risk than investment grade, longer duration than deep high yield. To ask whether the boundary is genuinely **better paid** you have to strip both out — hold a matching amount of Treasuries (IEF) and stocks (SPY) against each rung and see what is left over. That leftover is the *alpha*.

In [2]:
R = dict(ah_alpha=2.51, ah_t=2.01, ah_raw=2.15, al_alpha=1.51, al_t=1.15, al_raw=3.68,
         hl_alpha=-1.0, hl_t=-0.83)
print('crossover vs broad high yield : raw %+.2f%%/yr -> adjusted %+.2f%%/yr  (t = %+.2f)'
      % (R['ah_raw'], R['ah_alpha'], R['ah_t']))
print('crossover vs investment grade : raw %+.2f%%/yr -> adjusted %+.2f%%/yr  (t = %+.2f)'
      % (R['al_raw'], R['al_alpha'], R['al_t']))
print('broad high yield vs IG        :                    adjusted %+.2f%%/yr  (t = %+.2f)'
      % (R['hl_alpha'], R['hl_t']))
print()
print('t = 2 is the desk bar. One leg lands ON it; the other does not land at all.')

crossover vs broad high yield : raw +2.15%/yr -> adjusted +2.51%/yr  (t = +2.01)
crossover vs investment grade : raw +3.68%/yr -> adjusted +1.51%/yr  (t = +1.15)
broad high yield vs IG        :                    adjusted -1.00%/yr  (t = -0.83)

t = 2 is the desk bar. One leg lands ON it; the other does not land at all.


So the claim splits, and only half of it half-survives. Against **broad high yield** the boundary pays **+2.51%/yr** — but at *t* = **+2.01**, sitting *on* the significance bar rather than past it. Against **investment grade** — the half that would make it a genuine *rung* rather than just a better high-yield fund — it pays **+1.51%/yr at *t* = +1.15**. Nothing. And the step from investment grade to broad high yield paid **-1.00%/yr** on the same window (and **+0.05%/yr** on its own longer 19-year one): once you adjust for the risks, that rung was free money for nobody, whichever sample you read it on.

## 3. Two years carry the whole thing

Look at the crossover rung's advantage over broad high yield, year by year. It is not a steady drip of carry. It is two enormous years surrounded by noise — **2016** (the energy and mining downgrade wave recovering off the February lows) and **2020** (the COVID fallen-angel wave: Ford, Occidental, Kraft Heinz). That is the forced-seller mechanism firing, exactly as the theory says — and it says nothing about the years in between.

In [3]:
cal = [(2012, 2.12), (2013, 1.15), (2014, 0.63), (2015, 3.6), (2016, 10.65), (2017, 3.41), (2018, -3.92), (2019, 3.48), (2020, 8.48), (2021, 2.98), (2022, -3.74), (2023, 0.82), (2024, -1.77), (2025, 0.47), (2026, 0.58)]
for y, v in cal:
    mark = '  <-- downgrade wave' if v > 6 else ''
    bar = ('+' if v >= 0 else '-') * max(1, int(round(abs(v))))
    print('%d  %+6.2f%%  %-12s%s' % (y, v, bar, mark))

2012   +2.12%  ++          
2013   +1.15%  +           
2014   +0.63%  +           
2015   +3.60%  ++++        
2016  +10.65%  +++++++++++   <-- downgrade wave
2017   +3.41%  +++         
2018   -3.92%  ----        
2019   +3.48%  +++         
2020   +8.48%  ++++++++      <-- downgrade wave
2021   +2.98%  +++         
2022   -3.74%  ----        
2023   +0.82%  +           
2024   -1.77%  --          
2025   +0.47%  +           
2026   +0.58%  +           


## 4. Delete a year and the significance evaporates

The honest stress test: remove one calendar year at a time and re-estimate. A broad premium barely notices. This one **survives only 5 of 15** single-year deletions. Take out 2016 alone and it falls to **+1.84%/yr at *t* = +1.43**; take out both wave years and it is **+1.55%/yr at *t* = +1.61** over the remaining 3,069 days. Same sign, a third smaller, and no longer distinguishable from luck.

The era cut says the same thing in a different voice: **+4.47%/yr (*t* = +2.63)** before 2019, **+1.50%/yr (*t* = +0.92)** after. And the recent era is *not* a quiet one for the mechanism — it contains the largest downgrade wave in history. The engine fired and the premium still did not show up.

## 5. Swap the funds and it disappears

ANGL is not the crossover rung; it is *one fund's version of it*. There is a second fallen-angel fund (**FALN**) and a second broad high-yield fund (**USHY**). Run the identical race on the sibling pair and the premium is **+0.63%/yr at *t* = +0.48** — the right sign, and essentially nothing.

But be careful how much of that you charge to the *funds*. The sibling pair only exists from 2017, and on that same window the **headline** pair reads +0.96%/yr (*t* = +0.67) as well. Most of the collapse is the calendar, not the holdings — this is section 4 wearing a different hat, not a second, independent piece of bad news.

## 6. What you would actually be buying

The cheap way to own this is not a hedge fund trade — it is a **fund swap**: hold ANGL instead of HYG inside a high-yield sleeve you already have. One trade, pennies of spread, fees already inside the tape, and over the full window it bought **+0.165** of excess Sharpe.

The price of admission is written in the drawdown column of the first table: **−29.3%** for the crossover fund against **−22.0%** for broad high yield in March 2020, and 18% more day-to-day volatility. You are not being handed a premium; you are changing what kind of risk you own, and being paid a contested amount for it.

## 7. Is the measuring stick honest? (live, synthetic)

Before believing a borderline number, check the instrument. We build a fake credit ladder where we *know* the crossover rung is paid an extra 3%/yr, and a second one where we know it is paid nothing. The same estimator must find the first and stay quiet on the second. **This cell is synthetic — it is a proof about the tool, never evidence about credit.**

In [4]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
import numpy as np
from crossover_credit import data, strategy as st
planted, truth = data.synthetic_panel(signal_strength=1.0, seed=951)
d = st.synthetic_detect(planted)
print('planted %+.2f%%/yr  ->  recovered %+.2f%%/yr (t = %+.2f)'
      % (truth['alpha_planted']*100, d['alpha_ann']*100, d['t_alpha']))
nulls = [st.synthetic_detect(data.synthetic_panel(signal_strength=0.0, seed=951+s)[0])
         for s in range(8)]
a = np.array([x['alpha_ann'] for x in nulls]) * 100
t = np.array([x['t_alpha'] for x in nulls])
print('null x8: alpha mean %+.2f%%/yr (sd %.2f), |t| >= 2 fires %d/8'
      % (a.mean(), a.std(ddof=1), (abs(t) >= 2).sum()))

planted +3.00%/yr  ->  recovered +3.58%/yr (t = +4.64)


null x8: alpha mean +0.10%/yr (sd 0.60), |t| >= 2 fires 0/8


## Verdict

- **Signal — Weak.** The ladder really does hump on the boundary by raw reward-per-risk, and the premium's sign is positive everywhere we look. But it beats broad high yield only *at* the bar (*t* = +2.01), survives only 5/15 year deletions, and is three times smaller after 2018. (The sibling-fund pair reads *t* = +0.48, but that is mostly the same late window rather than a separate failure.) Against investment grade there is nothing at all. Right shape, unproven premium.
- **Tradability — Fragile.** The switch is genuinely cheap — no borrow, no timing, one trade — so this is not a cost mirage. But what you buy is a 7.3 pp deeper worst drawdown in exchange for an episodic, downgrade-wave payoff. A tilt worth holding if you want that exposure; not a premium to size.