"""Build the two narrative notebooks for Study 307 (Coffee-Seasonality).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace 01_for_the_curious.ipynb 02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/coffee_seasonality.parquet, built by
examples/verify.py --fetch). Every code cell falls back to the synthetic tape OFFLINE and banners
which tape it is showing. Real headline numbers live ONLY in RESULTS below, mirroring docs/results.md."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# ── Real numbers from the fingerprinted run (docs/results.md, fp 89301021ccad) ──────────────────
RESULTS = {
    "date_start": "2000-02-29",
    "date_end": "2026-05-31",
    "n_months": 316,
    "fingerprint": "89301021ccad",
    "frost_mean": 0.43,       # Jun–Aug, %
    "harvest_mean": -0.13,    # May/Sep, %
    "spread": 0.57,           # frost − harvest, %
    "spread_t": 0.34,
    "ci_lo": -3.47,
    "ci_hi": 4.46,
    "best_month": "Nov",
    "best_month_t": 1.82,
    "june_mean": -1.18,       # the supposedly-bullish frost month is the most negative
    "timer_cagr": 0.5,
    "timer_sharpe": 0.04,
    "timer_maxdd": -75,
    "net_sharpe": 0.02,
    "bh_cagr": 3.4,
    "bh_sharpe": 0.20,
    "bh_maxdd": -69,
    "sub_early_frost": -0.49,    # 2000-2012 frost mean
    "sub_early_harvest": 1.18,
    "sub_early_t": -0.64,
    "sub_late_frost": 1.35,      # 2013-on
    "sub_late_harvest": -1.40,
    "sub_late_t": 1.26,
}

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (coffee_seasonality/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from coffee_seasonality import data, strategy as st

# Cache-first real tape; fall back to the synthetic control OFFLINE and banner which tape we show.
try:
    from quantlab import repro
    d = repro.as_of(data.fetch_data())   # cache-first (examples/verify.py --fetch)
    if d.empty:
        raise RuntimeError("cache miss")
    TAPE = "REAL  (KC=F monthly, 2000-02..2026-05, 316 months, fp 89301021ccad)"
except Exception as e:
    d, _ = data.synthetic_world(frost_premium=0.0, seed=307)  # the NULL synthetic world
    TAPE = f"SYNTHETIC NULL control (offline fallback: {e}) -- NOT the real tape"
print("TAPE:", TAPE)
rf = d["tbill"]
timer = st.seasonal_timer(d["coffee"], tbill=rf)
net   = st.apply_costs(timer, n_trades_per_year=4, cost_bps_one_way=10)
bh    = st.buy_hold(d["coffee"])
ms    = st.month_stats(d["coffee"])
fh    = st.frost_harvest_tstat(d["coffee"])
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Frost premium?: Busted](https://img.shields.io/badge/Frost_premium%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Coffee-Seasonality ☕\n### A frost can double the price overnight — so can you trade the calendar?\n\n"
           + VERDICT +
           "The story is irresistible: coffee is a Southern-Hemisphere crop, Brazil grows a third of the "
           "world's beans, and a single overnight frost in the Brazilian winter (Jun–Aug) can wipe out a "
           "harvest and send prices soaring. Surely you buy ahead of frost season and sell into the May–Sep "
           "harvest glut? We checked 26 years of Arabica futures. The answer is a flat no — and the reason "
           "is the very thing that makes the story exciting.\n\n"
           "> **Plain-language layer.** The HAC t-stats, the bootstrap CI and the timer math are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ Not investment advice. Every chart is generated by the code beside it; the cell banners "
           "say whether it is the real KC=F tape or the offline synthetic control."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The claim | The data (KC=F, 2000–2026, 316 months) |\n|---|---|\n"
           "| \"Frost season is reliably bullish\" | Frost (Jun–Aug) mean **+0.43%**, harvest (May/Sep) "
           "−0.13%, spread **t = 0.34** — a coin flip, CI **[−3.5%, +4.5%]**. |\n"
           "| \"Trade it with a calendar rule\" | Long-frost/short-harvest timer Sharpe **0.04** vs "
           "buy-and-hold **0.20** (excess of T-bill) — total destruction of edge. |\n"
           "| \"Every year\" | The frost premium is *negative* in 2000–2012 and flips sign after. No month "
           "is significant; the most bullish month (Nov) isn't even part of the story. |"),
        md("## 1 · The claim\n\nArabica coffee grows in the Southern Hemisphere, concentrated in Brazil. "
           "From June to August — the Brazilian winter — a cold snap in the highlands can freeze the trees "
           "and destroy the next crop; the 1975, 1994 and 2021 frosts all sent prices vertical. Meanwhile "
           "the main harvest runs May–September, flooding the market with fresh beans. So the folklore: "
           "**buy coffee into the frost-risk window, short it into the harvest glut.**"),
        md("## 2 · So what?\n\nIf the calendar were real, you would not need to forecast the weather — you "
           "would just be long every June and short every September and collect a seasonal premium. Coffee "
           "is one of the most-traded soft commodities, so a reliable calendar edge would be worth real "
           "money. The catch: is the *average* June actually up, or do we just remember the years a frost "
           "hit?"),
        md("## 3 · How would we even know?\n\nWe line up every January, every February, … and ask whether "
           "each month's average return is reliably different from zero (with an autocorrelation-robust "
           "t-stat). We compare the frost months (Jun–Aug) against the harvest shoulders (May/Sep) and put "
           "an honest confidence interval on the gap. Then we build the obvious calendar timer and race it "
           "against just buying and holding. **If the gap's confidence interval straddles zero and the timer "
           "loses to buy-and-hold, it's a mirage.**"),
        code("month_names = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']\n"
             "means = [ms.loc[m,'mean']*100 for m in range(1,13)]\n"
             "tstats = [ms.loc[m,'tstat'] for m in range(1,13)]\n"
             "frost = [6,7,8]; harvest=[5,9]\n"
             "colors = []\n"
             "for m in range(1,13):\n"
             "    if abs(tstats[m-1])>=2: colors.append('#2ea44f')\n"
             "    elif m in frost: colors.append('#1f77b4')\n"
             "    elif m in harvest: colors.append('#d62728')\n"
             "    else: colors.append('#8b949e')\n"
             "fig,ax = plt.subplots(figsize=(10,4))\n"
             "ax.bar(month_names, means, color=colors)\n"
             "ax.axhline(0, color='black', lw=0.8)\n"
             "ax.set_ylabel('Mean monthly return (%)')\n"
             "ax.set_title(f'KC=F per-month mean returns (blue=frost Jun-Aug, red=harvest May/Sep)\\nTAPE: {TAPE}')\n"
             "plt.tight_layout(); plt.show()\n"
             "print(f\"Frost (Jun-Aug): {fh['frost_mean']*100:+.2f}%  n={fh['n_frost']}\")\n"
             "print(f\"Harvest (May/Sep): {fh['harvest_mean']*100:+.2f}%  n={fh['n_harvest']}\")\n"
             "print(f\"Frost - Harvest spread: {fh['spread']*100:+.2f}%  t={fh['tstat']:.2f}\")"),
        md("## 4 · The teardown — let's actually look\n\nLook at the blue (frost) bars. June — the heart of "
           "the frost window — is the **single most negative month** on the chart. The frost-minus-harvest "
           "spread on the real tape is **+0.57%/month with t = 0.34**: indistinguishable from zero, and its "
           "confidence interval runs from **−3.5% to +4.5%**. The vivid frost story leaves no fingerprint in "
           "the *average* month, because frost is a rare tail event — it happens in a handful of years and "
           "the calendar can't tell you which."),
        code("res = {\n"
             "    'frost/harvest timer (gross)': st.summary(timer, rf=rf),\n"
             "    'timer (net 10bp/leg)':        st.summary(net,   rf=rf),\n"
             "    'buy & hold KC=F':             st.summary(bh,    rf=rf),\n"
             "}\n"
             "display(pd.DataFrame(res).T[['cagr','sharpe','max_drawdown']].round(3))\n"
             "eq_bh = (1+bh).cumprod(); eq_t = (1+timer).cumprod()\n"
             "ax = eq_bh.plot(label='buy & hold KC=F', lw=1.5)\n"
             "eq_t.plot(ax=ax, label='frost/harvest timer', lw=1.5)\n"
             "ax.set_yscale('log'); ax.legend()\n"
             "ax.set_title(f'Growth of $1 (log) -- TAPE: {TAPE}'); plt.show()\n"
             "print('Sharpe = excess of T-bill, both legs, like-for-like')"),
        md("**Read it plainly.** The calendar timer turns an already-mediocre commodity into a worse one: "
           "Sharpe 0.04 against buy-and-hold's 0.20 on the real tape. Being short coffee in September is a "
           "great way to get run over by an occasional frost spike."),
        md("## 5 · The verdict\n\n**Signal: None** — the frost-vs-harvest spread is t = 0.34 with a CI that "
           "straddles zero; no month is significant. **Tradability: Mirage** — the timer earns Sharpe 0.04 "
           "vs 0.20 for buy-and-hold. **\"Frost premium\"? Busted** — it's negative in the first half of the "
           "sample and flips sign after."),
        md("## 6 · Could you actually trade it?\n\nNo. You'd give back the entire (small) risk-adjusted "
           "return of just holding coffee, and costs only deepen the hole. The frost risk is real — but it's "
           "a weather lottery, not a date you can put in your calendar."),
        md("## 7 · Going further 🚪\n\nForks: (a) test a *frost-conditioned* rule using actual Brazilian "
           "minimum-temperature data instead of the calendar; (b) the harvest glut may show up in the "
           "futures *term structure* (contango/backwardation) rather than spot returns; (c) compare to "
           "[226 Crude-Seasonality](../../226-crude-seasonality/) — another commodity calendar that the "
           "desk found Weak/Mirage."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Coffee-Seasonality — a quantitative teardown 🔬\n"
           "### Per-month HAC t-stats · Bonferroni · frost-vs-harvest spread + block-bootstrap CI · timer race · sub-period split\n\n"
           + VERDICT +
           "The deep companion to [the notebook for the curious](01_for_the_curious.ipynb) — *same seven "
           "beats, every claim now carrying its standard error.* We test Arabica monthly seasonality on 316 "
           "months and find no signal, a sign-flipping sub-period premium, and a timer that destroys "
           "buy-and-hold.\n\n"
           "> ⚠️ Not investment advice. KC=F (Arabica front future, price-only, roll-naive) + 13-week T-bill "
           "(^IRX) monthly, 2000-02 → 2026-05, 316 months (Yahoo Finance, daily closes resampled to "
           "month-end, grid asserted hole-free). Offline, every cell falls back to the synthetic NULL and "
           "banners the tape. Sources in [`docs/references.md`](../docs/references.md).\n>\n"
           "> 💡 The `💡 In plain words` notes translate each result back into intuition."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | frost−harvest spread t = 0.34, 95% CI [−3.47%, +4.46%]; no month \\|t\\| ≥ 2 |\n"
           "| Tradability | **Mirage** | timer Sharpe 0.04 vs buy-and-hold 0.20 (excess of T-bill), 0.02 net |\n"
           "| Frost premium? | **Busted** | −0.49% in 2000–2012 (t = −0.64), flips to +1.35% 2013-on (t = 1.26) |\n\n"
           "> 💡 In plain words: the most romantic seasonal story in commodities leaves no statistical "
           "fingerprint, because frost is a tail event, not a calendar event."),
        md("## 1 · The claim, steelmanned\n\n"
           "- **H₁:** at least one frost month (Jun–Aug) has a significantly positive mean return.\n"
           "- **H₂:** the frost group (Jun–Aug) has a significantly higher mean than the harvest group "
           "(May/Sep) — Welch t-test on pooled groups.\n"
           "- **H₃:** the frost-minus-harvest spread's block-bootstrap 95% CI excludes zero.\n"
           "- **H₄:** the long-frost / short-harvest calendar timer beats buy-and-hold (excess Sharpe).\n"
           "- **H₅:** the pattern is stable across sub-periods."),
        md("## 2 · So what? — what rides on each\n\nIf H₁–H₅ hold, a fixed-month rule harvests a weather "
           "premium with no forecasting required. If they fail, the frost narrative is folklore: a few "
           "spectacular years (1975, 1994, 2021 frosts) we over-remember, with no tradable calendar."),
        md("## 3 · How we'd know — the protocol\n\nOne-sample t-stats (naive **and** Newey-West HAC) for "
           "each of the 12 calendar months vs 0 (Bonferroni threshold |t| ≈ 3 for α = 0.05/12); Welch "
           "two-sample test for frost (Jun–Aug) vs harvest (May/Sep); a circular block-bootstrap (12-month "
           "blocks, to respect the annual seasonal structure) 95% CI on the spread; the calendar timer "
           "(long frost, short harvest, T-bill otherwise — calendar-known, **no execution lag**) vs "
           "buy-and-hold, Sharpe in **excess of the T-bill on both legs**, gross and net of 10 bp/leg; and a "
           "2000–2012 / 2013-on sub-period split."),
        md("## 4 · The teardown"),
        md("### 4.1 Per-month t-stats, naive and HAC (H₁)"),
        code("month_names = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']\n"
             "print(f'TAPE: {TAPE}\\n')\n"
             "print(f'{\"Month\":6s}  {\"Mean\":>8s}  {\"t-naive\":>8s}  {\"t-HAC\":>8s}  {\"n\":>4s}  Signal?')\n"
             "for m in range(1,13):\n"
             "    row = ms.loc[m]\n"
             "    sig = '|t|>=3 (Bonferroni)' if abs(row['tstat_hac'])>=3 else (\n"
             "          '|t|>=2 (nominal)' if abs(row['tstat_hac'])>=2 else 'noise')\n"
             "    print(f'{month_names[m-1]:6s}  {row[\"mean\"]*100:+7.2f}%  {row[\"tstat\"]:+8.2f}  '\n"
             "          f'{row[\"tstat_hac\"]:+8.2f}  {int(row[\"n\"]):4d}  {sig}')"),
        md("> 💡 In plain words: not one month clears |t| ≥ 2 on either statistic. The largest mean "
           "(November, t ≈ 1.82) isn't even part of the frost/harvest thesis, and wouldn't survive "
           "Bonferroni for 12 tests. The supposedly bullish frost month June is the most *negative* month. "
           "**H₁ rejected.**"),
        md("### 4.2 Frost vs Harvest spread + block-bootstrap CI (H₂, H₃)"),
        code("print(f'Frost (Jun-Aug):  {fh[\"frost_mean\"]*100:+.2f}%  n={fh[\"n_frost\"]}')\n"
             "print(f'Harvest (May/Sep): {fh[\"harvest_mean\"]*100:+.2f}%  n={fh[\"n_harvest\"]}')\n"
             "print(f'Spread: {fh[\"spread\"]*100:+.2f}%  Welch t={fh[\"tstat\"]:.2f}')\n"
             "ci = st.spread_bootstrap_ci(d['coffee'], n_boot=5000, seed=307)\n"
             "print(f'Block-bootstrap 95% CI on spread: [{ci[\"lo\"]*100:.2f}%, {ci[\"hi\"]*100:.2f}%]  '\n"
             "      f'(point {ci[\"point\"]*100:+.2f}%, n_boot={ci[\"n_boot\"]})')\n"
             "print('CI straddles 0:', ci['lo'] < 0 < ci['hi'])"),
        md("> 💡 In plain words: the Welch t is 0.34 and the bootstrap CI runs roughly −3.5% to +4.5% — it "
           "swamps the 0.57% point estimate. The spread is noise. **H₂ and H₃ rejected.**"),
        md("### 4.3 Calendar timer vs buy-and-hold, gross and net (H₄)"),
        code("res = {\n"
             "    'frost/harvest timer (gross)': st.summary(timer, rf=rf),\n"
             "    'timer (net 10bp/leg)':        st.summary(net,   rf=rf),\n"
             "    'buy & hold KC=F':             st.summary(bh,    rf=rf),\n"
             "}\n"
             "display(pd.DataFrame(res).T[['cagr','sharpe','vol_ann','max_drawdown','n']].round(3))\n"
             "print('Sharpe = excess of T-bill (^IRX), both legs, like-for-like; calendar-known rule, no lag')"),
        md("> 💡 In plain words: on the real tape the timer earns Sharpe ~0.04 vs ~0.20 for buy-and-hold — it "
           "destroys the (already poor) risk-adjusted return, and costs make it worse. Being systematically "
           "short into September periodically eats a frost spike. **H₄ rejected.**"),
        md("### 4.4 Sub-period stability (H₅)"),
        code("d.index = pd.DatetimeIndex(d.index)\n"
             "for lab, yr in [('2000-2012',(2000,2012)), ('2013-on',(2013,2030))]:\n"
             "    sl = d[(d.index.year>=yr[0]) & (d.index.year<=yr[1])]\n"
             "    r = st.frost_harvest_tstat(sl['coffee'])\n"
             "    print(f'{lab}: frost={r[\"frost_mean\"]*100:+.2f}%  harvest={r[\"harvest_mean\"]*100:+.2f}%  '\n"
             "          f't={r[\"tstat\"]:.2f}  n_fr={r[\"n_frost\"]}  n_ha={r[\"n_harvest\"]}')\n"
             "print('\\nThe frost premium FLIPS SIGN across halves -> not a stable seasonal law')"),
        md("> 💡 In plain words: the frost premium is *negative* in 2000–2012 (t = −0.64) and only nominally "
           "positive 2013-on (t = 1.26, still short of the bar). A premium that changes sign between halves "
           "of the sample is indistinguishable from a chance pattern. **H₅ rejected.**"),
        md("## 5 · The verdict\n\nH₁ rejected (no significant month). H₂/H₃ rejected (spread t = 0.34, CI "
           "[−3.47%, +4.46%]). H₄ rejected (timer Sharpe 0.04 vs 0.20). H₅ rejected (sign-flipping "
           "sub-periods). → Signal `NONE`, Tradability `MIRAGE`, frost premium `BUSTED`."),
        md("## 6 · Could you trade it?\n\nNo. Net of a conservative 10 bp/leg the timer is Sharpe ~0.02 and "
           "still carries the full −75% commodity drawdown. The break-even cost question is moot: there is no "
           "gross edge to defend. The whole apparatus that would harvest the frost premium instead pays you "
           "to stand in front of the occasional frost spike."),
        md("## 7 · Going further\n\nForks: (a) a *frost-conditioned* rule keyed to Brazilian minimum-"
           "temperature / GDD data rather than the calendar — the tail event, not the date; (b) seasonality "
           "in the KC=F **term structure** (the harvest glut may price into the curve, not spot returns); "
           "(c) cross-check Robusta (RC=F, a different geography/harvest). Companion: "
           "[226 Crude-Seasonality](../../226-crude-seasonality/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
