"""Notebook builder for Study 997 — The Rebalance Lottery.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Rebalance Lottery \U0001F3B0
### Same strategy, same data, same rules. Different Tuesday.

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Two people read the same paper and implement the same rule. One rebalances on the first of the
month, the other on the fifteenth. Twenty years later one of them has substantially more money
than the other, and neither did anything differently.

> \U0001F4D3 **This is the plain-language layer.** The mechanism, the period sweep and the fix
> are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does the rebalance day matter? | For a selection rule, enormously. |
| How much? | More than the strategy's whole edge. |
| Is it avoidable? | Yes, completely, and cheaply. |
| Does anyone do it? | Almost nobody. |
"""
        ),
        md(
            r"""

## 1 · The experiment
"""
        ),
        code(
            r"""
from lottery import data, strategy as st

px_all = data.load_prices()
universe = [t for t in data.UNIVERSE if t in px_all.columns]
px = px_all[universe].dropna()
cash = px_all[data.CASH].pct_change().reindex(px.index).fillna(0.0)
mom_rule = lambda: st.momentum_rule(126, 3)
print(f"as-of {data.AS_OF} | {len(universe)} assets, "
      f"{px.index[0].date()} -> {px.index[-1].date()} ({len(px) / 252:.1f} years)")
print(f"rule: hold the 3 best 126-day performers, rebalance every 21 sessions")
print(f"-> 21 possible offsets, all of them equally defensible")
"""
        ),
        code(
            r"""
curves = st.variant_curves(px, mom_rule(), period=21, cost_bps=5.0, cash=cash)
fig, ax = plt.subplots(figsize=(12, 6))
for off in curves.columns:
    ax.plot(curves.index, curves[off], lw=1.0, alpha=0.65)
best = curves.iloc[-1].idxmax()
worst = curves.iloc[-1].idxmin()
ax.plot(curves.index, curves[best], lw=2.5, color="#2ea44f",
        label=f"luckiest offset ({best})")
ax.plot(curves.index, curves[worst], lw=2.5, color="#c0392b",
        label=f"unluckiest offset ({worst})")
ax.set_yscale("log"); ax.set_ylabel("growth of $1 (log)"); ax.legend(fontsize=9)
ax.set_title("21 runs of the identical rule. The only difference is the start day.")
plt.show()
print(f"luckiest ended at ${curves[best].iloc[-1]:.2f}, "
      f"unluckiest at ${curves[worst].iloc[-1]:.2f} "
      f"({curves[best].iloc[-1] / curves[worst].iloc[-1]:.2f}x)")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Nobody chose these offsets. They are all equally defensible, and
> a backtest picks one silently. The spread between them is a standard error the reader never
> sees.
"""
        ),
        md(
            r"""

## 2 · The numbers
"""
        ),
        code(
            r"""
v = st.run_variants(px, mom_rule(), 21, 5.0, cash)
print(v.round(4).to_string())
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
axes[0].bar(v.index, v["cagr"] * 100, color="#1f6feb")
axes[0].axhline(v["cagr"].mean() * 100, color="k", ls="--", lw=1.5, label="mean")
axes[0].set_xlabel("rebalance offset"); axes[0].set_ylabel("CAGR (%)")
axes[0].legend(fontsize=8)
axes[1].bar(v.index, v["sharpe"], color="#2ea44f")
axes[1].axhline(v["sharpe"].mean(), color="k", ls="--", lw=1.5)
axes[1].set_xlabel("rebalance offset"); axes[1].set_ylabel("Sharpe")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

## 3 · Compared with the edge it is supposed to demonstrate
"""
        ),
        code(
            r"""
equal = px.pct_change().mean(axis=1).fillna(0.0)
bench = float((1 + equal).prod() ** (252 / len(equal)) - 1)
lv = st.luck_vs_signal(v, bench)
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.barh(["the edge over\nbuy-and-hold", "the timing luck"],
        [lv["mean_edge"] * 100, lv["luck_spread"] * 100],
        color=["#2ea44f", "#c0392b"])
ax.set_xlabel("percentage points per year")
plt.show()
print(f"edge:  {lv['mean_edge']:+.2%}/yr")
print(f"luck:  {lv['luck_spread']:.2%} spread")
print(f"{lv['share_beating_benchmark']:.0%} of the offsets beat buy-and-hold; "
      f"{1 - lv['share_beating_benchmark']:.0%} did not")
"""
        ),
        md(
            r"""

## 4 · Why it happens

The clue is in what happens when the rule *doesn't* choose between assets.
"""
        ),
        code(
            r"""
fw = st.run_variants(px, st.fixed_weight_rule(px, {data.EQUITY: 0.6, data.BONDS: 0.4}),
                     21, 5.0, cash)
fig, ax = plt.subplots(figsize=(10, 4.5))
w = 0.35
ax.bar(np.arange(len(fw)) - w / 2, (fw["cagr"] - fw["cagr"].mean()) * 100, w,
       label="60/40 (holds the same things)", color="#2ea44f")
ax.bar(np.arange(len(v)) + w / 2, (v["cagr"] - v["cagr"].mean()) * 100, w,
       label="momentum (picks different things)", color="#c0392b")
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("rebalance offset"); ax.set_ylabel("CAGR minus its own mean (pp)")
ax.legend(fontsize=8)
plt.show()
print(f"60/40 spread:    {fw['cagr'].max() - fw['cagr'].min():.2%}")
print(f"momentum spread: {v['cagr'].max() - v['cagr'].min():.2%}")
"""
        ),
        md(
            r"""

A 60/40 rebalanced on the 3rd and one rebalanced on the 17th own **the same two funds**. They
differ only by a little drift. A momentum rule ranked on the 3rd and one ranked on the 17th own
**different funds** for weeks at a time. That is the whole mechanism, and it means timing luck
is a problem of *selection*, not of rebalancing.
"""
        ),
        md(
            r"""

## 5 · The fix
"""
        ),
        code(
            r"""
ov = st.overlapping_portfolios(px, mom_rule(), 21, 5.0, cash)
fig, ax = plt.subplots(figsize=(12, 6))
for off in curves.columns:
    ax.plot(curves.index, curves[off], lw=0.8, alpha=0.3, color="#8b949e")
ax.plot(ov["value"].index, ov["value"], lw=3, color="#1f6feb",
        label="all 21 offsets held at once")
ax.set_yscale("log"); ax.set_ylabel("growth of $1 (log)"); ax.legend(fontsize=10)
ax.set_title("Rebalance 1/21 of the book every day. No offset to choose.")
plt.show()
print(f"blended:               CAGR {ov['cagr']:+.2%}, Sharpe {ov['sharpe']:.2f}, "
      f"maxDD {ov['max_dd']:.1%}")
print(f"average single offset: CAGR {ov['mean_variant_cagr']:+.2%}, "
      f"Sharpe {ov['mean_variant_sharpe']:.2f}, maxDD {ov['mean_variant_dd']:.1%}")
"""
        ),
        md(
            r"""

Not only is the timing luck gone — there is only one portfolio now — but the volatility is lower
and the drawdown shallower, because the twenty-one sleeves are not perfectly correlated with one
another. This is one of the rare cases where the careful thing to do is also the profitable
one.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Confirmed.** The identical momentum rule, run at all **21 possible rebalance offsets** over 19 years, produced CAGRs from **+6.50% to +9.92%** — a spread of **3.42%** and a terminal-wealth ratio of **1.85×** between the luckiest and unluckiest start day. Nothing about the rule differed; only the day of the month it happened to trade. For scale, the rule's average edge over buy-and-hold was +0.29%/yr, so the luck is **11.6×** the edge, and 62% of the offsets beat the benchmark. A fixed-weight 60/40 shows far less — a spread of only 0.22% — because both variants hold the *same assets* and differ only in drift, while a ranking rule's variants hold different assets entirely. Any backtest of a selection rule that reports one rebalance date is reporting one draw from a distribution this wide.

**Tradability: Useful.** The fix is real and it is cheap. Running all 21 offsets at once — rebalancing 1/21 of the book each day — removes the dispersion by construction, and it does not cost return: the blended portfolio delivered **+8.66%/yr at a Sharpe of 0.65**, against the average single-offset variant's +8.54% and 0.62. It also cut volatility by 0.78% and improved the worst drawdown by 2.3% against the average variant, because the sleeves are imperfectly correlated with each other. The catch a practitioner should know: it is operationally more demanding — a daily trade instead of a monthly one — and section 6 confirms it preserves genuine signal rather than diluting it away.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Check your own backtests.** Any rule that *selects* is exposed. Rerun it at every offset
  before believing the headline number.
- **Report the range, not the point.** A shaded band across offsets is more honest than a single
  line and costs nothing to produce.
- **Jegadeesh & Titman did this in 1993.** The original momentum paper used overlapping
  portfolios for precisely this reason. The practice got dropped somewhere along the way.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Rebalance Lottery — a quantitative teardown \U0001F52C
### All 21 offsets · selection vs drift · period scaling · overlapping portfolios

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The key
observation is that timing luck is a **selection** phenomenon: a fixed-weight rule barely
suffers, a ranking rule suffers enormously, and the difference tells you exactly where to look
for it in your own work.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from lottery import data, strategy as st

px_all = data.load_prices()
universe = [t for t in data.UNIVERSE if t in px_all.columns]
px = px_all[universe].dropna()
cash = px_all[data.CASH].pct_change().reindex(px.index).fillna(0.0)
mom_rule = lambda: st.momentum_rule(126, 3)
print(f"as-of {data.AS_OF} | {len(universe)} assets, "
      f"{px.index[0].date()} -> {px.index[-1].date()} ({len(px) / 252:.1f} years)")
print(f"rule: hold the 3 best 126-day performers, rebalance every 21 sessions")
print(f"-> 21 possible offsets, all of them equally defensible")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | The identical momentum rule, run at all **21 possible rebalance offsets** over 19 years, produced CAGRs from **+6.50% to +9.92%** — a spread of **3.42%** and a terminal-wealth ratio of **1.85×** between the luckiest and unluckiest start day. Nothing about the rule differed; only the day of the month it happened to trade. For scale, the rule's average edge over buy-and-hold was +0.29%/yr, so the luck is **11.6×** the edge, and 62% of the offsets beat the benchmark. A fixed-weight 60/40 shows far less — a spread of only 0.22% — because both variants hold the *same assets* and differ only in drift, while a ranking rule's variants hold different assets entirely. Any backtest of a selection rule that reports one rebalance date is reporting one draw from a distribution this wide. |
| **Tradability** | Useful | The fix is real and it is cheap. Running all 21 offsets at once — rebalancing 1/21 of the book each day — removes the dispersion by construction, and it does not cost return: the blended portfolio delivered **+8.66%/yr at a Sharpe of 0.65**, against the average single-offset variant's +8.54% and 0.62. It also cut volatility by 0.78% and improved the worst drawdown by 2.3% against the average variant, because the sleeves are imperfectly correlated with each other. The catch a practitioner should know: it is operationally more demanding — a daily trade instead of a monthly one — and section 6 confirms it preserves genuine signal rather than diluting it away. |

> \U0001F4A1 **In plain words.** Timing luck is a standard error that backtests do not report,
> and for selection rules it is larger than the effect being reported.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** A selection rule's CAGR varies materially across rebalance offsets.
- **H₂ (mechanism).** A fixed-weight rule does not, because its variants hold the same assets.
- **H₃ (scaling).** Timing luck grows with the rebalance period.
- **H₄ (the comparison that matters).** The offset spread exceeds the rule's edge over its
  benchmark.
- **H₅ (the fix).** Overlapping portfolios remove the dispersion without costing return, and
  preserve genuine signal — testable against a synthetic world with planted momentum.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 Every offset, both rule families
"""
        ),
        code(
            r"""
v = st.run_variants(px, mom_rule(), 21, 5.0, cash)
fw = st.run_variants(px, st.fixed_weight_rule(px, {data.EQUITY: 0.6, data.BONDS: 0.4}),
                     21, 5.0, cash)
print("momentum:")
print(v.round(4).to_string())
print()
print("fixed weight 60/40:")
print(fw.round(4).to_string())
print()
print(pd.DataFrame({"momentum": st.luck_summary(v),
                    "60/40": st.luck_summary(fw)}).round(4).to_string())
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
for ax, (tbl, name) in zip(axes, ((v, "momentum"), (fw, "60/40"))):
    ax.scatter(tbl["vol"] * 100, tbl["cagr"] * 100, s=70, c=tbl.index, cmap="viridis")
    for off, r in tbl.iterrows():
        ax.annotate(str(off), (r["vol"] * 100, r["cagr"] * 100), fontsize=7,
                    xytext=(3, 2), textcoords="offset points")
    ax.set_xlabel("volatility (%)"); ax.set_ylabel("CAGR (%)")
    ax.set_title(f"{name}: each point is one rebalance offset")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The 60/40 panel is a tight cluster; the momentum panel is a
> cloud. Same machinery, same data, same twenty-one offsets. The difference is whether the rule
> chooses what to hold.
"""
        ),
        md(
            r"""

### 2.2 Luck against edge
"""
        ),
        code(
            r"""
equal = px.pct_change().mean(axis=1).fillna(0.0)
bench = float((1 + equal).prod() ** (252 / len(equal)) - 1)
rows = []
for lb in (63, 126, 252):
    for nh in (1, 3, 5):
        vv = st.run_variants(px, st.momentum_rule(lb, nh), 21, 5.0, cash)
        lv = st.luck_vs_signal(vv, bench)
        rows.append({"lookback": lb, "n_hold": nh, "edge": lv["mean_edge"],
                     "spread": lv["luck_spread"], "ratio": lv["luck_spread"]
                     / abs(lv["mean_edge"]) if lv["mean_edge"] else np.nan,
                     "share beating": lv["share_beating_benchmark"]})
d = pd.DataFrame(rows)
print(d.round(4).to_string(index=False))
fig, ax = plt.subplots(figsize=(10, 5))
ax.scatter(d["edge"] * 100, d["spread"] * 100, s=90, c=d["n_hold"], cmap="viridis")
lim = [0, max(d["spread"].max(), abs(d["edge"]).max()) * 110]
ax.plot(lim, lim, "k--", lw=1.5, label="luck = edge")
for _, r in d.iterrows():
    ax.annotate(f"{int(r['lookback'])}/{int(r['n_hold'])}",
                (r["edge"] * 100, r["spread"] * 100), fontsize=7,
                xytext=(4, 3), textcoords="offset points")
ax.set_xlabel("edge over buy-and-hold (pp/yr)")
ax.set_ylabel("timing-luck spread (pp/yr)"); ax.legend(fontsize=8)
ax.set_title("Above the line: the luck is bigger than the finding")
plt.show()
"""
        ),
        md(
            r"""

### 2.3 Scaling with the rebalance period
"""
        ),
        code(
            r"""
sw = st.period_sweep(px, lambda: st.momentum_rule(126, 3),
                     periods=(5, 10, 21, 42, 63), cost_bps=5.0, cash=cash)
print(sw.round(4).to_string())
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.plot(sw.index, sw["cagr_spread"] * 100, "o-", lw=2, color="#c0392b",
        label="CAGR spread")
ax.plot(sw.index, sw["cagr_sd"] * 100, "s-", lw=2, color="#1f6feb", label="SD across offsets")
ax.set_xlabel("rebalance period (sessions)"); ax.set_ylabel("percentage points per year")
ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

### 2.4 The fix, and what it costs
"""
        ),
        code(
            r"""
rows = []
for period in (5, 10, 21, 42, 63):
    vv = st.run_variants(px, mom_rule(), period, 5.0, cash)
    oo = st.overlapping_portfolios(px, mom_rule(), period, 5.0, cash)
    rows.append({"period": period, "spread": vv["cagr"].max() - vv["cagr"].min(),
                 "mean variant CAGR": vv["cagr"].mean(), "blended CAGR": oo["cagr"],
                 "mean variant Sharpe": vv["sharpe"].mean(),
                 "blended Sharpe": oo["sharpe"],
                 "vol reduction": oo["vol_reduction"]})
d = pd.DataFrame(rows).set_index("period")
print(d.round(4).to_string())
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d[["mean variant Sharpe", "blended Sharpe"]].plot(ax=axes[0], marker="o",
                                                  color=["#8b949e", "#2ea44f"])
axes[0].set_ylabel("Sharpe"); axes[0].legend(fontsize=8)
axes[1].plot(d.index, d["vol reduction"] * 100, "o-", lw=2, color="#1f6feb")
axes[1].axhline(0, color="k", lw=1)
axes[1].set_xlabel("rebalance period"); axes[1].set_ylabel("volatility removed (pp)")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.5 Does the fix keep the signal?
"""
        ),
        code(
            r"""
rows = []
for m in (0.0, 0.5, 1.0, 2.0, 3.0):
    sim = st.synthetic_prices(n=3500, n_assets=10, momentum=m)
    vv = st.run_variants(sim, mom_rule(), 21, 5.0)
    oo = st.overlapping_portfolios(sim, mom_rule(), 21, 5.0)
    eq = sim.pct_change().mean(axis=1).fillna(0.0)
    b = float((1 + eq).prod() ** (252 / len(eq)) - 1)
    rows.append({"planted momentum": m, "spread": vv["cagr"].max() - vv["cagr"].min(),
                 "mean variant Sharpe": vv["sharpe"].mean(),
                 "blended Sharpe": oo["sharpe"],
                 "edge over benchmark": vv["cagr"].mean() - b})
d = pd.DataFrame(rows).set_index("planted momentum")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d[["mean variant Sharpe", "blended Sharpe"]].plot(ax=axes[0], marker="o",
                                                  color=["#8b949e", "#2ea44f"])
axes[0].set_ylabel("Sharpe"); axes[0].legend(fontsize=8)
axes[0].set_title("the blend never loses to the average variant")
d["spread"].mul(100).plot(ax=axes[1], marker="o", color="#c0392b")
axes[1].set_ylabel("timing-luck spread (pp)")
axes[1].set_title("...and the luck is there whether or not signal is")
plt.tight_layout(); plt.show()
d.round(4)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Read the right panel at zero planted momentum. There is nothing
> to find, and the offsets still spread by a wide margin — every bit of it luck. The fix removes
> that without touching the left panel, which is the whole case for it.
"""
        ),
        md(
            r"""

### 2.6 How many offsets does an honest report need?
"""
        ),
        code(
            r"""
rng = np.random.default_rng(997)
cagrs = v["cagr"].to_numpy()
rows = []
for k in range(1, 22):
    draws = [float(np.mean(rng.choice(cagrs, k, replace=False))) for _ in range(3000)]
    rows.append({"offsets averaged": k, "sd of reported CAGR": np.std(draws, ddof=1)})
d = pd.DataFrame(rows).set_index("offsets averaged")
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.plot(d.index, d["sd of reported CAGR"] * 100, "o-", lw=2, color="#1f6feb")
ax.set_xlabel("number of offsets averaged"); ax.set_ylabel("SD of the reported CAGR (pp)")
ax.set_title("Reporting one offset is the leftmost point")
plt.show()
d.round(4).head(8)
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
ov = st.overlapping_portfolios(px, mom_rule(), 21, 5.0, cash)
lv = st.luck_vs_signal(v, bench)
s = st.luck_summary(v)
pd.DataFrame({
    "offsets tested": [s["n_offsets"]],
    "momentum CAGR spread": [s["cagr_spread"]],
    "terminal wealth ratio": [s["final_ratio"]],
    "60/40 CAGR spread": [fw["cagr"].max() - fw["cagr"].min()],
    "edge over buy-and-hold": [lv["mean_edge"]],
    "luck / edge": [lv["luck_spread"] / abs(lv["mean_edge"])],
    "blended Sharpe": [ov["sharpe"]],
    "average variant Sharpe": [ov["mean_variant_sharpe"]],
    "volatility removed": [ov["vol_reduction"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 4 · Going further

- **Hoffstein, Faber & Braun (2020)** derive the timing-luck variance analytically as a function
  of turnover and holding period. Comparing this study's measured spread against their formula
  would turn an observation into a validated model.
- **Calendar-month offsets** add a second effect on top: months differ in length, so the
  variants are not evenly spaced. Worth separating.
- **Apply it to your own factor.** The machinery is generic: pass any rule with the same
  signature and it will tell you how much of your backtest was the calendar.
- **Costs are the missing piece.** Overlapping portfolios trade daily in small size, which is
  cheaper per unit than monthly block trades. Modelling that properly would strengthen the fix
  further.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
