"""Worked extension run (beat 7) — does a *genuinely* vol-adaptive σ-band beat the best fixed level?

The headline study shows AdaptiveRSI's σ-zones are a static relabel of a constant RSI threshold.
This runs the version the framework implies but never builds — an oversold band whose level widens
with realized volatility, so the entry threshold is **time-varying** (not a relabel) — and races it
against the in-sample best fixed constant on real SPY/QQQ, net of costs, across lengths. It writes a
reproducible docs/extension.md.

    # uses the same cached daily closes as verify.py; --fetch to populate on a miss
    ../../.venv/Scripts/python.exe examples/extension.py
"""

import argparse
import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from sigma_sleight import data, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

pd.set_option("display.width", 200)
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")

OUT = os.path.join(_STUDY, "docs", "extension.md")
TICKERS = ["SPY", "QQQ"]
LENGTHS = [2, 5, 14]
GAMMA = 0.5            # vol-sensitivity of the band; the extra knob the rule must pay for
BASE_SIGMA = -1.0     # the support/resistance oversold landmark to flex around
COST_BPS = 1.0


def load(ticker, fetch):
    close = data.fetch_prices(ticker, fetch=fetch)
    if close.empty:
        return close
    return as_of(close.to_frame(), DEFAULT_AS_OF)["close"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true", help="populate the close cache (network)")
    args = ap.parse_args()

    results, fps = {}, {}
    for tk in TICKERS:
        close = load(tk, args.fetch)
        if close.empty:
            print(f"[skip] {tk}: no cache (run with --fetch)"); continue
        rows = {n: extension.adaptive_vs_fixed(close, length=n, base_sigma=BASE_SIGMA,
                                               gamma=GAMMA, cost_bps=COST_BPS) for n in LENGTHS}
        results[tk] = rows
        fps[tk] = (fingerprint(close.to_frame()), close.index.min().date(), close.index.max().date())
        print(f"\n=== {tk} ({len(close)} bars) ===")
        for n in LENGTHS:
            r = rows[n]
            print(f"  len {n}: fixed-best Sharpe {r['fixed_best']['sharpe']:+.2f} (lower {r['fixed_best']['lower']:.0f}) | "
                  f"vol-adaptive {r['adaptive']['sharpe']:+.2f} | increment {r['increment_sharpe']:+.2f} | "
                  f"threshold dispersion {r['threshold_dispersion']:.1f} RSI pts")

    if results:
        _write(OUT, results, fps)
        print(f"\nwrote {OUT}")
    else:
        print("\ncache is empty -- run with --fetch to populate the closes first.")


def _write(path, results, fps):
    cells = [(tk, n, results[tk][n]) for tk in results for n in LENGTHS]
    n_cells = len(cells)
    beats = sum(1 for _, _, r in cells if r["increment_sharpe"] > 1e-9)
    moves = sum(1 for _, _, r in cells if r["threshold_dispersion"] > 1.0)

    lines = [f"""# Extension (beat 7) — make σ *actually* adaptive: does it beat a fixed level?

*Generated by [`examples/extension.py`](../examples/extension.py). The headline study shows
AdaptiveRSI's σ-zones are a **static** relabel of a constant RSI threshold (within a length, zero
trades moved). Here we build the version the framework gestures at but never implements — an
oversold band whose σ landmark **widens with realized volatility** (γ = {GAMMA}, base −1σ), so the
RSI entry level is **time-varying**, not a constant — and race it against the in-sample best fixed
constant on real SPY/QQQ, net of {COST_BPS:.0f} bps/turn. As-of **{DEFAULT_AS_OF}**; match the
fingerprints below.*

## Data stamp
"""]
    for tk, (fp, lo, hi) in fps.items():
        lines.append(f"- **{tk}**: {lo} → {hi}, fingerprint `{fp}`")

    for tk in results:
        lines.append(f"""
## {tk} — vol-adaptive band vs best fixed constant

| length | best fixed (lower) | vol-adaptive | increment Sharpe | threshold dispersion (RSI pts) |
|---|---|---|---|---|""")
        for n in LENGTHS:
            r = results[tk][n]
            lines.append(
                f"| {n} | {r['fixed_best']['sharpe']:+.2f} (lower {r['fixed_best']['lower']:.0f}) | "
                f"{r['adaptive']['sharpe']:+.2f} | {r['increment_sharpe']:+.2f} | "
                f"{r['threshold_dispersion']:.1f} |")

    lines.append(f"""
## What it shows

1. **It is no longer a relabel.** The vol-adaptive entry level genuinely moves — its dispersion is
   > 1 RSI point in **{moves}/{n_cells}** cells (a static σ-zone's dispersion is exactly 0). Letting
   the threshold breathe with vol *can* enter on a bar a constant skips, so unlike the static
   σ-band it is free to beat — or lose to — the best fixed constant. This is the one modification
   that escapes the headline study's monotone-relabel verdict.

2. **But it still doesn't pay.** The vol-adaptive band beats the in-sample best fixed constant in
   only **{beats}/{n_cells}** cells, and even those wins are *gross* of the multiple-testing in both
   the fixed grid **and** the vol-sensitivity knob γ (and of any out-of-sample decay). The regime
   information is real; the tradable edge over a plain, sensibly-chosen oversold level is not. The
   framework's unbuilt promise, built, lands the study where it started: a better **vocabulary** for
   thresholds, not an edge — **Tradability `MIRAGE`** holds, now for the more interesting reason
   that even a genuine regime rule can't clear costs here.
""")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
