"""Build the two narrative notebooks for Study 94 (Level-Pegging).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``level_pegging`` package on the cached real tapes; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=5817, start="2003-05-01", end="2026-06-12", fp="5d3261d7897c",
    ew_fee=20, cw_fee=9, split="2015-01-01",
    # full sample, net
    ew_cagr=11.07, ew_vol=19.8, ew_sharpe=0.630, ew_dd=-60.1,
    cw_cagr=11.39, cw_vol=18.5, cw_sharpe=0.675, cw_dd=-55.2,
    gap_cagr=-0.32, hac_t=-0.04, boot_lo=-0.90, boot_hi=0.85,
    # gross
    ew_cagr_g=11.29, cw_cagr_g=11.49, gap_cagr_g=-0.20,
    # alpha-beta
    alpha_ann=-0.23, t_alpha=-0.21, beta=1.02, r2=0.92,
    # regime split
    early_ann=2.60, early_t=1.97, late_ann=-2.74, late_t=-1.57,
    dod=5.34, p_boot=0.0188,
    early_sh_ew=0.622, early_sh_cw=0.552, late_sh_ew=0.644, late_sh_cw=0.814,
    # relative wealth
    rel_peak=1.305, rel_peak_date="2011-05-20", rel_end=0.936,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (level_pegging/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from level_pegging import data, strategy

AS_OF = "2026-06-12"
EW_FEE, CW_FEE, SPLIT = 20.0, 9.0, "2015-01-01"
frame = data.load_real("RSP", "SPY", mode="total_return").loc[:AS_OF]
net = strategy.race(frame, EW_FEE, CW_FEE)
ew, cw = net["ew"], net["cw"]
print(f"RSP (EW) + SPY (CW) total return: {len(frame):,} rows  {frame.index[0].date()} -> {frame.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(f"EW  Sharpe {ew['sharpe']:.3f}  maxDD {ew['max_dd']*100:.1f}%  CAGR {ew['cagr']*100:.2f}%")
print(f"CW  Sharpe {cw['sharpe']:.3f}  maxDD {cw['max_dd']*100:.1f}%  CAGR {cw['cagr']*100:.2f}%")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Mixed](https://img.shields.io/badge/Signal-Mixed-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Always wins?: Busted](https://img.shields.io/badge/Always_wins%3F-Busted-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# Level-Pegging ⚖️\n"
            "### Does equal-weighting the S&P *always* beat cap-weighting?\n\n"
            + HERO_BADGES +
            "You'll hear it everywhere: the equal-weight S&P (RSP) beats the regular cap-weight "
            "S&P (SPY) because it leans toward smaller companies and quietly *sells high, buys low* "
            "every rebalance. *Just buy RSP.* We hold both, dividends and fees included, and ask the "
            "one thing the word **always** can't survive: did equal-weight win **every** kind of "
            "market, or only some?\n\n"
            "> 📓 **This is the plain-language layer.** The statistics, the alpha-vs-beta split and "
            "the regime test are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same "
            "story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below "
            "is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Does equal-weight *always* beat cap-weight? | **No.** It *led* from 2003-2015 "
            f"(**+{R['early_ann']:.1f}%/yr**) and *lagged* from 2015-2026 (**{R['late_ann']:.1f}%/yr**). |\n"
            f"| Over RSP's whole life, who won? | **Cap-weight (SPY)** — equal-weight earned "
            f"**{R['gap_cagr']:.2f} pts/yr less** ({R['ew_cagr']}% vs {R['cw_cagr']}%/yr, net of fees). |\n"
            f"| So what *is* equal-weighting? | A **bet on small caps and broad markets** — it pays "
            f"when leadership widens and loses when a few giants run. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Equal-weighting **always** beats cap-weighting. RSP tilts to smaller names and harvests "
            "a rebalancing premium — sell what went up, buy what went down. Just buy RSP and forget "
            "the cap-weight index.\"* It's the standard pitch for equal-weight funds, and the academic "
            "version (Plyakha, Uppal & Vilkov) found a real edge in long US history."
        ),
        md(
            "## 2 · So what?\n\n"
            "If a different *weighting* of the **same 500 stocks** reliably beat the index everyone "
            "owns, the default choice — cap-weighted indexing — would be a mistake worth trillions. "
            "That's a big enough claim to deserve a fair, literal test on the real investable fund "
            "rather than a back-fitted index."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We hold **RSP** (equal-weight) and **SPY** (cap-weight), both total return (dividends in), "
            f"net each of its fee (RSP **{R['ew_fee']} bps/yr**, SPY **{R['cw_fee']} bps/yr**), and "
            "compare. The catch the word *always* hides: a single full-sample average can hide a sign "
            "**flip**. So we also cut the history at the start of the mega-cap era (**2015**) and ask "
            "whether the two halves really tell different stories. If equal-weight wins one half and "
            "loses the other, *\"always\"* is dead."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the two equity curves."),
        code(
            "fig, ax = plt.subplots(figsize=(10, 5.5))\n"
            "ax.plot(ew['equity'], label=f\"RSP equal-weight (Sharpe {ew['sharpe']:.2f})\", lw=1.3)\n"
            "ax.plot(cw['equity'], label=f\"SPY cap-weight (Sharpe {cw['sharpe']:.2f})\", lw=1.3, alpha=.85)\n"
            "ax.set_yscale('log'); ax.set_ylabel('Growth of $1 (log)')\n"
            "ax.set_title('Equal-weight vs cap-weight S&P 500 — total return, net of fees'); ax.legend()\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "The lines are almost on top of each other — *level-pegging* — for years. The real story "
            "isn't the levels, it's **who's ahead, when**. So plot the ratio: RSP's wealth divided by "
            "SPY's. Up = equal-weight winning; down = cap-weight winning."
        ),
        code(
            "rel = ew['equity'] / cw['equity']\n"
            "fig, ax = plt.subplots(figsize=(10, 5))\n"
            "ax.plot(rel, color='C4', lw=1.4)\n"
            "ax.axhline(1.0, color='k', lw=.8, ls=':')\n"
            "ax.axvline(pd.Timestamp(SPLIT), color='C3', lw=1.2, ls='--', label='mega-cap era begins (2015)')\n"
            "peak = rel.idxmax()\n"
            "ax.scatter([peak], [rel.max()], color='C2', zorder=5, label=f'EW peak {rel.max():.2f} ({peak.date()})')\n"
            "ax.set_ylabel('RSP wealth / SPY wealth'); ax.set_title('Equal-weight leads, then loses the lead')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print(f'relative wealth: peak {rel.max():.3f} on {peak.date()}  ->  end {rel.iloc[-1]:.3f}')"
        ),
        md(
            f"There it is. Equal-weight climbed to **{R['rel_peak']}×** SPY by **{R['rel_peak_date']}** — "
            "it really *was* winning through the broad 2000s recovery. Then the mega-caps took over and "
            f"the line fell all the way back to **{R['rel_end']}**: today RSP has earned **less** than "
            "SPY over its whole life. The premium didn't vanish into noise — it *reversed*."
        ),
        md("Split the history at 2015 and the two halves disagree out loud:"),
        code(
            "early = frame.loc[:SPLIT]; late = frame.loc[SPLIT:]\n"
            "re_, rl = strategy.race(early, EW_FEE, CW_FEE), strategy.race(late, EW_FEE, CW_FEE)\n"
            "tbl = pd.DataFrame({\n"
            "  'EW CAGR %': [re_['ew']['cagr']*100, rl['ew']['cagr']*100],\n"
            "  'CW CAGR %': [re_['cw']['cagr']*100, rl['cw']['cagr']*100],\n"
            "  'EW-CW pts': [re_['ew_minus_cw_cagr']*100, rl['ew_minus_cw_cagr']*100],\n"
            "  'winner':    ['EW' if re_['ew_minus_cw_cagr']>0 else 'CW', 'EW' if rl['ew_minus_cw_cagr']>0 else 'CW'],\n"
            "}, index=['2003-2015 (broadening)', '2015-2026 (mega-cap)'])\n"
            "tbl.round(2)"
        ),
        md(
            f"Equal-weight **wins the first half and loses the second**. That's not a free lunch — "
            "it's a *bet on which companies lead*."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Always wins? → Busted.** EW led to a {R['rel_peak']}× lead by 2011, then gave it all "
            f"back to end at {R['rel_end']}× — it has *underperformed* SPY over its full investable life.\n"
            f"- **Signal → Mixed.** Real-ish edge early (+{R['early_ann']:.1f}%/yr), negative late "
            f"({R['late_ann']:.1f}%/yr); the full-sample number is the wrong sign and statistically zero.\n"
            f"- **Just buy RSP? → Mirage.** Net of its higher fee it earns **{R['gap_cagr']:.2f} pts/yr "
            "less**. The tilt only pays if you correctly time the breadth regime."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You can trade both — RSP and SPY are liquid funds. The catch isn't capacity, it's that "
            "*\"just buy RSP\"* is a **bet on market breadth in disguise**. It pays when small caps and "
            "the average stock lead, and it loses — as it did for a decade — when a handful of giants "
            "carry the index. Net of RSP's higher fee and quarterly rebalancing turnover, the "
            "full-sample scoreboard favours plain cap-weight."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Does an equal-weight tilt pay better **outside the US**, where indices are less mega-cap "
            "concentrated?\n"
            "- Is there a **breadth signal** (advance/decline, top-10 weight) that times *when* to hold "
            "equal-weight?\n"
            "- How much of the early-2000s EW win was just the **small-cap value** rally? Fork it and "
            "strip the factors."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Level-Pegging — a quantitative teardown 🔬\n"
            "### Real total-return tapes · HAC inference · alpha-vs-beta · a block-bootstrapped regime split\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We separate the two things "
            "equal-weighting does — **tilt to a factor** (a beta you can buy) and **earn an alpha** "
            "(what the marketing sells) — and show the alpha is zero over the full sample and only the "
            "tilt's *direction* pays, and only in the right regime.\n\n"
            "> ⚠️ **Not investment advice.** RSP (equal-weight) & SPY (cap-weight) daily, total-return "
            "adjusted (`quantlab.data`, Yahoo); RSP-bounded window from 2003; fees 20 vs 9 bps/yr; 0% "
            "cash (nets out of the difference). Sources in [`docs/references.md`](../docs/references.md), "
            "reproducible run in [`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `MIXED` | Regime-split: EW−CW **+{R['early_ann']:.2f}%/yr** (HAC *t* "
            f"+{R['early_t']:.2f}) in 2003-2015, **{R['late_ann']:.2f}%/yr** (HAC *t* {R['late_t']:.2f}) "
            f"in 2015-2026; difference-of-differences **{R['dod']:.2f} pts/yr**, block-boot *p* = "
            f"**{R['p_boot']:.3f}**. Full-sample alpha **{R['alpha_ann']:.2f}%/yr** (HAC *t* {R['t_alpha']:.2f}). |\n"
            f"| **Tradability** | `MIRAGE` | As *\"just buy RSP and always win\"*: EW−CW = "
            f"**{R['gap_cagr']:.2f} pts/yr** net over the full sample; the tilt is β≈{R['beta']:.2f} to "
            f"the cap-weight market, not skill. |\n"
            f"| **Always wins?** | `BUSTED` | RSP/SPY relative wealth peaked **{R['rel_peak']}** "
            f"({R['rel_peak_date']}) then fell to **{R['rel_end']}**. |\n\n"
            "> 💡 **In plain words:** equal-weighting is a *factor tilt wearing a free-lunch costume*; "
            "the tilt's payoff flips sign with the market's breadth."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (tilt):** EW is a mechanical small-cap / anti-concentration tilt — it should have "
            "β≈1 to the cap-weight market plus a size loading.\n"
            "- **H₂ (alpha):** beyond the tilt, the *rebalancing* earns a positive alpha (Plyakha, "
            "Uppal & Vilkov).\n"
            "- **H₃ (the sold claim):** EW therefore **always** beats CW.\n\n"
            "We find H₁ true, H₂ ≈ 0 over the full investable sample, and H₃ false — the edge **flips "
            "sign** across a justified regime split."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₃ held, cap-weighted indexing — the "
           "default for trillions — would be dominated by a re-weighting of the *same names*. It "
           "isn't; seeing *why* (a breadth bet, not alpha) is the lesson."),
        md("## 3 · How we'd know — the protocol\n\nFull-sample race (net of fees) · HAC inference on "
           "the daily EW−CW difference · block-bootstrap CI on the mean difference · alpha-vs-beta "
           "regression of EW on CW · a **regime split** at 2015-01-01 with a block-bootstrap test of "
           "the difference-of-differences (a justified, not snooped, split)."),
        md("## 4 · The teardown\n\nHeadline stats, full sample, net of each arm's fee:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [ew['cagr']*100, cw['cagr']*100],\n"
            "  'Vol %':   [ew['vol']*100, cw['vol']*100],\n"
            "  'Sharpe':  [ew['sharpe'], cw['sharpe']],\n"
            "  'MaxDD %': [ew['max_dd']*100, cw['max_dd']*100],\n"
            "  'Final x': [ew['final'], cw['final']],\n"
            "}, index=['RSP equal-weight', 'SPY cap-weight'])\n"
            "tbl.round(3)"
        ),
        md("**HAC inference** on the daily EW−CW return difference, plus a block-bootstrap CI on its mean:"),
        code(
            "diff = net['diff'].to_numpy()\n"
            "t = strategy.hac_tstat(diff)\n"
            "lo, hi = strategy.block_bootstrap_mean_ci(diff)\n"
            "print(f'mean daily EW-CW = {diff.mean()*1e4:+.3f} bps/day   HAC t = {t:+.2f}')\n"
            "print(f'block-boot 95% CI on the mean = [{lo*1e4:+.3f}, {hi*1e4:+.3f}] bps/day (straddles 0)')\n"
            "print('=> over the full RSP era the difference is statistically indistinguishable from zero.')"
        ),
        md(
            "> 💡 **In plain words:** day to day, equal-weight and cap-weight are the same bet plus "
            "noise; the full-sample winner is decided by *which regime ran longer*, not by a steady edge."
        ),
        md("**Alpha vs beta** — regress EW's daily return on CW's. Beta is the market exposure; the "
           "intercept is what's left:"),
        code(
            "ab = strategy.alpha_beta(frame)\n"
            "print(f\"alpha = {ab['alpha_ann']*100:+.2f}%/yr (HAC t {ab['t_alpha']:+.2f})\")\n"
            "print(f\"beta  = {ab['beta']:.3f}   R^2 = {ab['r2']:.3f}\")\n"
            "print('=> EW is ~the cap-weight market (beta ~1, R^2 ~0.92) with NO certifiable alpha over the full sample.')"
        ),
        md(
            "> 💡 **In plain words:** strip out the part of RSP that's just *the market*, and there's "
            "nothing reliable left over — the 'rebalancing premium' is not visible in the investable "
            "fund's full history."
        ),
        md("**The regime split** — the heart of it. Cut at 2015, race each half, and test whether the "
           "two halves' EW−CW means really differ (block bootstrap on the difference-of-differences):"),
        code(
            "sc = strategy.split_contrast(net['diff'], SPLIT)\n"
            "early = frame.loc[:SPLIT]; late = frame.loc[SPLIT:]\n"
            "re_, rl = strategy.race(early, EW_FEE, CW_FEE), strategy.race(late, EW_FEE, CW_FEE)\n"
            "print(f\"early 2003-2015 : EW-CW {sc['early_ann']*100:+.2f}%/yr (HAC t {sc['early_t']:+.2f})  \"\n"
            "      f\"Sharpe EW {re_['ew']['sharpe']:.3f} vs CW {re_['cw']['sharpe']:.3f}\")\n"
            "print(f\"late  2015-2026 : EW-CW {sc['late_ann']*100:+.2f}%/yr (HAC t {sc['late_t']:+.2f})  \"\n"
            "      f\"Sharpe EW {rl['ew']['sharpe']:.3f} vs CW {rl['cw']['sharpe']:.3f}\")\n"
            "print(f\"difference-of-differences = {sc['obs_gap_ann']*100:+.2f} pts/yr   block-boot p = {sc['p_boot']:.4f}\")"
        ),
        code(
            "# Rolling 1-year EW-CW outperformance: the regime flip made visible.\n"
            "roll = net['diff'].rolling(252).mean() * 252 * 100\n"
            "fig, ax = plt.subplots(figsize=(10, 5))\n"
            "ax.fill_between(roll.index, 0, roll, where=roll>=0, color='C0', alpha=.6, label='EW ahead')\n"
            "ax.fill_between(roll.index, 0, roll, where=roll<0, color='C3', alpha=.6, label='CW ahead')\n"
            "ax.axhline(0, color='k', lw=.8)\n"
            "ax.axvline(pd.Timestamp(SPLIT), color='k', lw=1.0, ls='--', label='split (2015)')\n"
            "ax.set_ylabel('rolling 1y EW-CW (%/yr)'); ax.set_title('Rolling 1-year equal-weight outperformance — the regime flip')\n"
            "ax.legend(); plt.tight_layout(); plt.show()"
        ),
        md(
            "> 💡 **In plain words:** the blue (EW-ahead) years cluster early; the red (CW-ahead) years "
            "cluster after 2015. The block-bootstrap *p* on the gap says that clustering is unlikely to "
            "be luck — the regimes are real, which is exactly why *\"always\"* is the wrong word."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `MIXED` (early EW−CW +{R['early_ann']:.2f}%/yr at *t* +{R['early_t']:.2f}; late "
            f"{R['late_ann']:.2f}%/yr; difference-of-differences {R['dod']:.2f} pts/yr at *p* "
            f"{R['p_boot']:.3f}; full-sample alpha {R['alpha_ann']:.2f}%/yr, *t* {R['t_alpha']:.2f}). "
            f"Tradability `MIRAGE` for *\"just buy RSP and always win\"* (EW−CW {R['gap_cagr']:.2f} pts/yr "
            f"net, β≈{R['beta']:.2f}). Always wins? `BUSTED` (relative wealth {R['rel_peak']} → "
            f"{R['rel_end']})."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (RSP and SPY are deep). The binding fact is economic: equal-weight "
            "is a **conditional bet on breadth**, β≈1 to the cap-weight market, with no full-sample "
            "alpha and a higher fee/turnover drag. To make *\"always\"* true you would have to **time "
            "the regime** — hold EW when leadership broadens, CW when it narrows — which is a different, "
            "harder strategy than the buy-and-hold the claim sells."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Decompose the early-era EW win into **Fama-French SMB/HML** loadings — how much is just "
            "small-cap value?\n"
            "- Build a **top-10-weight (concentration) signal** and test whether it times the EW vs CW "
            "switch out of sample.\n"
            "- Re-run on **equal- vs cap-weight outside the US** (less mega-cap concentration) — does "
            "the tilt earn its fee there?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
