"""Build the two narrative notebooks for Study 61 (Slow-Burn).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/slow_burn_pair.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (slow_burn/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from slow_burn import data, strategy as st
ret = data.fetch_pair()                        # cache-first
g = st.decay_gap(ret["QQQ"], L=3.0)
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Leverage is a free amplifier?: Busted](https://img.shields.io/badge/Leverage_is_a_free_amplifier%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Slow-Burn 🔥\n### Do 3× leveraged ETFs decay, or triple your money?\n\n"
           + VERDICT +
           "Two opposite folk beliefs about leveraged ETFs: \"they decay to zero\" and \"they triple your "
           "returns\". Both miss it. TQQQ turned QQQ's +20%/yr into +44% over 2010–2026 — but at no "
           "risk-adjusted gain, an −82% drawdown, and −79% in 2022. The decay is real arithmetic; the "
           "free-money is the myth.\n\n"
           "> 📓 **Plain-language layer.** The decay-vs-theory match and the regimes are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The belief | The data (2010–2026) |\n|---|---|\n"
           "| \"3× decays to zero\" | Overstated: TQQQ **+43.7%/yr** (it 50×'d in the bull). |\n"
           "| \"3× triples returns\" | No risk-adjusted gain: Sharpe **0.90 vs QQQ 0.98**. |\n"
           "| \"It's a free multiplier\" | −82% drawdown; **−79% in 2022**; ~8–13%/yr vol drag. |"),
        md("## 1 · The claim\n\nA 3× leveraged ETF rebalances daily to 3× the index's exposure. The "
           "warnings say 'volatility drag' grinds it down; the hype says it triples your gains. Which is true?"),
        md("## 2 · So what?\n\nLeveraged ETFs are among the most-traded retail products. If they're a free "
           "multiplier, lever up; if they're a decay trap, avoid; if they're a path-dependent regime bet, "
           "you'd better know which regime you're in."),
        md("## 3 · How would we even know?\n\nCompare TQQQ to QQQ on return *and* risk (Sharpe, drawdown); "
           "measure the realized decay against the textbook 0.5·L·(L−1)·σ² formula; and split by regime "
           "(the 2010s bull vs 2022)."),
        code("rows={'QQQ (1x)':st.summary(ret['QQQ']),'TQQQ (3x)':st.summary(ret['TQQQ'])}\n"
             "display(pd.DataFrame(rows).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "eqQ=(1+ret['QQQ']).cumprod(); eqT=(1+ret['TQQQ']).cumprod()\n"
             "ax=eqT.plot(label='TQQQ (3x)',lw=1.4); eqQ.plot(ax=ax,label='QQQ (1x)',lw=1.4)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, 2010-2026 (log)'); ax.legend(); plt.show()"),
        md("## 4 · The teardown — the drag is real, the Sharpe isn't there\n\nThe leveraged book compounds "
           "below 3× the index's CAGR by the volatility drag — and matches the formula."),
        code("print(f\"naive 3x(QQQ CAGR) = {g['naive_Lx_cagr']:+.1%}\")\n"
             "print(f\"3x daily-rebalanced realized = {g['levered_cagr']:+.1%}\")\n"
             "print(f\"volatility decay = {g['decay']:+.1%}/yr   vs theory 0.5*L(L-1)*vol^2 = {g['drag_theory']:.1%}/yr\")\n"
             "print(f\"TQQQ Sharpe {st.summary(ret['TQQQ'])['sharpe']:.2f} vs QQQ {st.summary(ret['QQQ'])['sharpe']:.2f}\")"),
        md("**Read it plainly.** A 3× book bleeds ~8–13%/yr to drag (matching theory), and even gross of "
           "that, its Sharpe isn't higher than the index. The bigger CAGR is just bigger risk."),
        md("## 5 · The verdict\n\n**Signal: Real** — drag matches theory. **Tradability: Mirage** — no "
           "Sharpe gain, −82% drawdown. **Free amplifier?: Busted.**"),
        md("## 6 · Could you actually trade it?\n\nAs a *tactical* bull-trend bet, sized small, maybe — "
           "the daily reset compounds gains in a sustained uptrend. As a buy-and-hold, no: you'd take "
           "triple the risk for no extra Sharpe, lose the drag every year, and risk −80% in a bad one (2022)."),
        md("## 7 · Going further 🚪\n\nThe quants notebook shows the regime path-dependence. A "
           "product-mechanics cousin of the leverage-cost studies [30 House-Edge](../../30-house-edge/) and "
           "[43 Free-Lunch](../../43-free-lunch/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Slow-Burn — a quantitative teardown 🔬\n### Decay vs the 0.5·L·(L−1)·σ² formula · Sharpe/drawdown · the regime path-dependence\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The drag is "
           "real and matches theory; the leverage adds no Sharpe.\n\n"
           "> ⚠️ **Not investment advice.** TQQQ vs QQQ, daily total return (Yahoo), 2010–2026. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | decay ~8–13%/yr matches 0.5·L·(L−1)·σ² |\n"
           "| Tradability | **Mirage** | Sharpe 0.90 < 0.98, −82% DD, −79% in 2022 |\n"
           "| Free amplifier? | **Busted** | more vol/tail, not more return-per-risk |\n\n"
           "> 💡 *In plain words:* the drag is arithmetic; the free money is the myth."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** a 3× ETF realizes below 3×(index CAGR) by the "
           "volatility drag.\n- **H₂:** the drag matches 0.5·L·(L−1)·σ².\n- **H₃:** the leverage improves "
           "the Sharpe (the 'free amplifier' claim)."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂ are the mechanics; H₃ is the investment question. "
           "If H₃ fails, the product is risk for risk's sake plus a drag."),
        md("## 3 · How we'd know — the protocol\n\nRealized 3×-daily CAGR vs 3×(index CAGR) → the drag vs "
           "the formula → Sharpe/drawdown comparison → regime split."),
        md("## 4 · The teardown"),
        md("### 4.1 The drag matches theory"),
        code("import pandas as pd\n"
             "print({k:round(v,3) for k,v in g.items()})\n"
             "print(f\"realized decay {g['decay']:+.1%}/yr vs theory {g['drag_theory']:.1%}/yr\")"),
        md("> 💡 *In plain words:* ~8–13%/yr, in line with 0.5·L·(L−1)·σ². **H₁, H₂ hold** — the drag is real."),
        md("### 4.2 No Sharpe gain"),
        code("display(pd.DataFrame({'QQQ':st.summary(ret['QQQ']),'TQQQ':st.summary(ret['TQQQ'])}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))"),
        md("> 💡 *In plain words:* TQQQ Sharpe 0.90 < QQQ 0.98, −82% drawdown. **H₃ rejected** — leverage "
           "amplified risk, not return-per-risk."),
        md("### 4.3 The regime path-dependence"),
        code("for lab,sl in [('2010-2021 bull',ret['TQQQ'].loc[:'2021']),('2022 bear',ret['TQQQ'].loc['2022']),('2022-on',ret['TQQQ'].loc['2022':])]:\n"
             "    s=st.summary(sl); print(f'{lab}: CAGR {s[\"cagr\"]:+.0%}, maxDD {s[\"max_drawdown\"]:.0%}')"),
        md("> 💡 *In plain words:* +56%/yr in the bull, −79% in 2022 — it doesn't 'decay to zero', it's a "
           "violent regime bet. The drag is the steady cost; the regime is the gamble."),
        md("## 5 · The verdict\n\nH₁/H₂ hold, H₃ rejected → Signal `REAL` (the drag), Tradability `MIRAGE`, "
           "the free-amplifier claim `BUSTED`."),
        md("## 6 · Could you trade it?\n\nTactically, in a confirmed uptrend, sized for the −80% tail — "
           "not as a buy-and-hold. The arithmetic guarantees a drag; the regime decides whether you're up "
           "10× or down 80%."),
        md("## 7 · Going further\n\nForks: (a) a vol-targeted leverage (scale L by inverse vol) — does "
           "managing the drag help? (b) 2× vs 3× (the drag scales L·(L−1)); (c) inverse ETFs (SQQQ), where "
           "the drag plus a falling-market base is doubly punishing. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
