"""Notebook builder for Study 965 — The Range Estimators.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Range Estimators \U0001F4CF
### The high and the low know more than the close — until the market gaps

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

Every volatility textbook says the same thing: stop throwing away the day's high and low,
because the range measures volatility about five times better than the closing price does.
It is a theorem, it is correct, and the market it was proved in never closes for the night.
This notebook checks the claim where the answer is known, then finds the hole.

> \U0001F4D3 **This is the plain-language layer.** The estimator algebra, the QLIKE race and
> the Diebold-Mariano tests are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is the five-times efficiency claim true? | **Yes** — in a simulated market that never closes, which is where it was proved. |
| Does it survive on a real market? | Only in part. Parkinson, Garman-Klass and Rogers-Satchell cannot see the overnight gap, and for an equity ETF that gap is a large slice of the day's variance. |
| So which estimator should you use? | **Yang-Zhang**, the only one built to contain the gap — or a rescaled range estimator if you know what you are correcting for. |
| Is the gain worth chasing? | It is real and it is modest. Nobody's P&L was ever saved by a better variance estimator; a few risk limits were. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Squared close-to-close returns waste the whole day. You watched the price travel from
> the low to the high and back and then you recorded one number. Use the range: Parkinson
> (1980) proved it is five times as efficient, so you get five years of information out of
> one."*

That is not marketing — it is a theorem, and the theorem is right. The interesting part is
its footnote: it assumes the price follows a continuous random walk **all the time**, with no
overnight jump.
"""
        ),
        md(
            r"""

## 2 · So what?

Volatility is the input to nearly everything downstream: position sizing, risk limits, option
pricing, stop distances. An estimator that is five times more efficient means your risk
system reacts to a real change in five days instead of twenty-five. And an estimator that
quietly reports 60% of the truth means your risk limits are wrong by 40%.
"""
        ),
        md(
            r"""

## 3 · How would we even know?

Efficiency is a statement about how close an estimate is to the truth — so we need a world
where the truth exists. That world is a simulation: we generate bars from a known daily
sigma, with a controllable overnight gap, and score every estimator against it.
"""
        ),
        code(
            r"""
from range_vol import data, strategy as st

bars = data.load_all()
spy = bars["SPY"]
print(f"as-of {data.AS_OF} | SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} bars, {data.bad_bar_count('SPY')} dropped as broken)")
print(f"overnight share of SPY's daily variance: {st.overnight_share(spy):.0%}")
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 The claim, in the world where it was proved
"""
        ),
        code(
            r"""
sim, tr = data.synthetic_ohlc(n_years=40, overnight_share=0.0, seed=965)
eff = st.efficiency_table(sim, tr["sigma"])
fig, ax = plt.subplots(figsize=(9, 4.5))
lbl = [st.ESTIMATOR_LABEL[c].split(" (")[0] for c in eff.index]
ax.bar(lbl, eff["efficiency_vs_cc"], color=["#8b949e", "#2ea44f", "#2ea44f", "#2ea44f", "#dab617"])
ax.axhline(1.0, color="k", lw=1, ls="--")
ax.set_ylabel("efficiency vs close-to-close (higher is better)")
ax.set_title("Simulated market that never closes: the textbook is right")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
eff.round(3)
"""
        ),
        md(
            r"""

### 4.2 Now let the market close for the night
"""
        ),
        code(
            r"""
sim2, tr2 = data.synthetic_ohlc(n_years=40, overnight_share=0.35, seed=965)
eff2 = st.efficiency_table(sim2, tr2["sigma"])
comp = pd.DataFrame({"no gap": eff["mean_ratio_to_truth"],
                     "35% of variance overnight": eff2["mean_ratio_to_truth"]})
fig, ax = plt.subplots(figsize=(9, 4.5))
comp.plot.bar(ax=ax, color=["#2ea44f", "#c0392b"])
ax.axhline(1.0, color="k", lw=1, ls="--")
ax.set_ylabel("average estimate / truth")
ax.set_title("The same estimators, once the price is allowed to jump overnight")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
ax.legend(title="")
plt.show()
comp.round(3)
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Notice what is *not* happening: the range estimators do not
> become noisy. They stay precise — precisely wrong. A biased-but-tight estimator is more
> dangerous than a noisy unbiased one, because it never looks unreliable.
"""
        ),
        md(
            r"""

### 4.3 The real tape agrees
"""
        ),
        code(
            r"""
rows = []
for tk, b in bars.items():
    t = st.bias_table(b)
    rows.append({"ticker": tk, "overnight share": st.overnight_share(b),
                 **{st.ESTIMATOR_LABEL[c].split(" (")[0]: t.loc[c, "ratio_to_cc"]
                    for c in st.ESTIMATORS}})
tbl = pd.DataFrame(rows).set_index("ticker")
fig, ax = plt.subplots(figsize=(10, 4.5))
tbl.drop(columns=["overnight share"]).plot.bar(ax=ax)
ax.axhline(1.0, color="k", lw=1, ls="--")
ax.set_ylabel("average variance / close-to-close variance")
ax.set_title("Five real tapes: what each estimator would have you believe")
ax.legend(title="", fontsize=8)
plt.show()
tbl.round(2)
"""
        ),
        md(
            r"""

Gold and Treasuries are the interesting cases: GLD's underlying trades around the clock, so a
large share of its "daily" variance lands outside the US session and the gap-blind estimators
miss even more of it.
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** On simulated bars where the day's true sigma is known, Parkinson's estimator has **4.9x** the efficiency of close-to-close against the truth (Garman-Klass 6.8x, Rogers-Satchell 5.5x) — the textbook claim survives, in the textbook's own world. On the real tape that world does not exist: the overnight gap carries **33%** of SPY's daily variance and none of the three can see it, so they report **69%** of the close-to-close level.

**Usefulness: Useful.** Rescaled to remove that level error, the best range estimator (Yang-Zhang (2000)) beat close-to-close on QLIKE on **5 of 5** tapes with a pooled Diebold-Mariano *t* of **+3.73** — a real but modest improvement in forecasting the next month's realised variance (22.4% lower QLIKE on SPY). Yang-Zhang, the only gap-aware estimator, needs no rescaling and is the honest default.
"""
        ),
        md(
            r"""

## 6 · Could you actually use it?

Fix the level error — multiply each estimator by a scale factor learned on the first two
years only — and ask the practical question: does the extra information in the bar predict
next month's realised variance better?
"""
        ),
        code(
            r"""
t = st.scaled_forecast_race(spy, burn=504)
fig, ax = plt.subplots(figsize=(9, 4.5))
lbl = [st.ESTIMATOR_LABEL[c].split(" (")[0] for c in t.index]
colors = ["#8b949e" if c == "close_close" else "#2ea44f" for c in t.index]
ax.bar(lbl, t["qlike"], color=colors)
ax.set_ylabel("QLIKE loss (lower is better)")
ax.set_title("SPY: forecasting the next month's variance, level error removed")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
t.round(4)
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Intraday data** turns this from a forecast comparison into a real efficiency measurement:
  with 5-minute bars there is a realised-variance benchmark and the whole simulation section
  becomes unnecessary.
- **The high and low you can trade.** Consolidated-tape extremes include prints nobody could
  have hit; a study on NBBO-filtered extremes would shrink every range estimator slightly.
- **Position sizing.** The interesting downstream question is whether a better variance
  estimate improves a vol-targeted portfolio — a different study, and a harder one.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Range Estimators — a quantitative teardown \U0001F52C
### Parkinson · Garman-Klass · Rogers-Satchell · Yang-Zhang · QLIKE · Diebold-Mariano

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The design
problem here is that **efficiency cannot be measured on real data**: there is no truth to
compare an estimator against without intraday prices. So the study splits in two — the
efficiency claim is tested in simulation where sigma is known, and the real tape is used for
the two questions it *can* answer: how much variance do the gap-blind estimators miss, and do
they forecast better once that level error is removed?

> ⚠️ **Not investment advice.** OHLC bars from Yahoo! Finance, pinned as-of the date in
> [`docs/results.md`](../docs/results.md); literature map in
> [`docs/references.md`](../docs/references.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from range_vol import data, strategy as st

bars = data.load_all()
spy = bars["SPY"]
print(f"as-of {data.AS_OF} | SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} bars, {data.bad_bar_count('SPY')} dropped as broken)")
print(f"overnight share of SPY's daily variance: {st.overnight_share(spy):.0%}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | On simulated bars where the day's true sigma is known, Parkinson's estimator has **4.9x** the efficiency of close-to-close against the truth (Garman-Klass 6.8x, Rogers-Satchell 5.5x) — the textbook claim survives, in the textbook's own world. On the real tape that world does not exist: the overnight gap carries **33%** of SPY's daily variance and none of the three can see it, so they report **69%** of the close-to-close level. |
| **Usefulness** | Useful | Rescaled to remove that level error, the best range estimator (Yang-Zhang (2000)) beat close-to-close on QLIKE on **5 of 5** tapes with a pooled Diebold-Mariano *t* of **+3.73** — a real but modest improvement in forecasting the next month's realised variance (22.4% lower QLIKE on SPY). Yang-Zhang, the only gap-aware estimator, needs no rescaling and is the honest default. |

> \U0001F4A1 **In plain words.** The theorem is fine. The application is where the money is
> lost: three of the four range estimators are systematically low on any market that gaps, and
> the fix is either Yang-Zhang or an explicit rescaling.
"""
        ),
        md(
            r"""

## 1 · The claim, steelmanned

- **H₁ (efficiency).** Var(Parkinson) ≈ Var(close-to-close)/5 under the estimator's own
  assumptions — a driftless diffusion observed continuously, no gaps.
- **H₂ (bias).** On a market with an overnight gap of share *g*, the gap-blind estimators
  estimate (1 − *g*) of the daily variance, not all of it.
- **H₃ (usefulness).** After correcting the level, the range estimators forecast future
  realised variance better than close-to-close, and the improvement is statistically
  distinguishable by Diebold-Mariano.
"""
        ),
        md(
            r"""

## 2 · So what? — the quantitative stakes

A risk system that under-measures variance by 40% under-measures 99% VaR by the same 40%. A
vol-targeting overlay calibrated on Parkinson runs systematically hotter than its mandate.
Neither shows up as an error anywhere — the estimator is *precise*, so it never looks broken.
"""
        ),
        md(
            r"""

## 3 · How we'd know — the protocol

1. **Simulation with known sigma** (`data.synthetic_ohlc`), with the overnight share as a dial:
   the only setting where MSE-against-truth is computable.
2. **Level bias on the real tape**: each estimator's long-run mean against close-to-close,
   next to the measured overnight share of variance.
3. **A forecast race** on the real tape, raw and after a burn-in-only rescaling, scored with
   QLIKE (scale-free, robust to a noisy proxy — Patton 2011) and MSE.
4. **HAC Diebold-Mariano** on the loss differentials, because overlapping 21-day targets make
   them strongly autocorrelated.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 Efficiency against a known sigma, as a function of the gap
"""
        ),
        code(
            r"""
rows = []
for g in (0.0, 0.1, 0.2, 0.35, 0.5):
    sim, tr = data.synthetic_ohlc(n_years=30, overnight_share=g, seed=965)
    e = st.efficiency_table(sim, tr["sigma"])
    for c in ("parkinson", "garman_klass", "rogers_satchell"):
        rows.append({"gap share": g, "estimator": st.ESTIMATOR_LABEL[c].split(" (")[0],
                     "efficiency": e.loc[c, "efficiency_vs_cc"],
                     "ratio to truth": e.loc[c, "mean_ratio_to_truth"]})
grid = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
for name, sub in grid.groupby("estimator"):
    axes[0].plot(sub["gap share"], sub["efficiency"], marker="o", label=name)
    axes[1].plot(sub["gap share"], sub["ratio to truth"], marker="o", label=name)
axes[0].axhline(1, color="k", ls="--", lw=1); axes[0].set_title("Efficiency vs close-to-close")
axes[1].axhline(1, color="k", ls="--", lw=1); axes[1].set_title("Estimate / truth")
for a in axes:
    a.set_xlabel("share of daily variance arriving overnight"); a.legend(fontsize=8)
plt.show()
grid.pivot(index="gap share", columns="estimator", values="ratio to truth").round(3)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** As the gap grows, the range estimators keep *looking*
> excellent by their own standard — low variance of the estimate — while drifting further from
> the number you actually wanted.
"""
        ),
        md(
            r"""

### 4.2 The bias on five real tapes, against the measured gap share
"""
        ),
        code(
            r"""
rows = []
for tk, b in bars.items():
    t = st.bias_table(b)
    for c in st.GAP_BLIND:
        rows.append({"ticker": tk, "estimator": st.ESTIMATOR_LABEL[c].split(" (")[0],
                     "ratio": t.loc[c, "ratio_to_cc"], "gap": st.overnight_share(b)})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(9, 5))
for name, sub in d.groupby("estimator"):
    ax.scatter(sub["gap"], sub["ratio"], s=60, label=name)
xs = np.linspace(d["gap"].min() * 0.9, d["gap"].max() * 1.1, 50)
ax.plot(xs, 1 - xs, color="k", ls="--", lw=1, label="prediction: 1 - gap share")
for _, r in d.iterrows():
    ax.annotate(r["ticker"], (r["gap"], r["ratio"]), fontsize=7,
                xytext=(3, 3), textcoords="offset points")
ax.set_xlabel("overnight share of daily variance"); ax.set_ylabel("estimator / close-to-close")
ax.set_title("The missing variance is exactly the variance that arrives overnight")
ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

### 4.3 The raw forecast race — and why it is unfair
"""
        ),
        code(
            r"""
raw = st.forecast_race(spy, burn=504)
scaled = st.scaled_forecast_race(spy, burn=504)
cmp = pd.DataFrame({"QLIKE raw": raw["qlike"], "QLIKE rescaled": scaled["qlike"],
                    "scale applied": scaled["scale"]})
cmp.index = [st.ESTIMATOR_LABEL[c] for c in cmp.index]
print(cmp.round(4).to_string())
print("\nThe raw column mostly measures who has the right average level;")
print("the rescaled column measures who has the right shape.")
"""
        ),
        md(
            r"""

### 4.4 Diebold-Mariano, with and without the HAC correction
"""
        ),
        code(
            r"""
est = st.rolling_variance(spy, 21)
target = st.realised_forward_var(spy, 21).shift(-1)
idx = est.index[504:]
train = est.iloc[:504].dropna()
rows = []
for c in st.ESTIMATORS:
    scale = train["close_close"].mean() / train[c].mean()
    pair = pd.concat([target.reindex(idx), est[c].reindex(idx) * scale], axis=1).dropna()
    ql_c = st.qlike(pair.iloc[:, 0], pair.iloc[:, 1])
    base_pair = pd.concat([target.reindex(idx), est["close_close"].reindex(idx)], axis=1).dropna()
    ql_b = st.qlike(base_pair.iloc[:, 0], base_pair.iloc[:, 1])
    rows.append({"estimator": st.ESTIMATOR_LABEL[c],
                 "DM (HAC)": st.diebold_mariano(ql_b, ql_c)["dm"],
                 "DM (no lags, wrong)": st.diebold_mariano(ql_b, ql_c, lags=0)["dm"]})
pd.DataFrame(rows).set_index("estimator").round(2)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Ignore the overlap and every difference looks decisive. The
> HAC column is the one to read.
"""
        ),
        md(
            r"""

### 4.5 Does the answer survive the window choice?
"""
        ),
        code(
            r"""
rows = []
for w in (5, 10, 21, 63):
    t = st.scaled_forecast_race(spy, window=w, burn=504)
    best = t.drop(index=["close_close"])["qlike"].idxmin()
    rows.append({"window": w, "best estimator": st.ESTIMATOR_LABEL[best],
                 "QLIKE gain vs CC": 1 - t.loc[best, "qlike"] / t.loc["close_close", "qlike"],
                 "DM": t.loc[best, "dm_vs_cc"]})
pd.DataFrame(rows).set_index("window").round(4)
"""
        ),
        md(
            r"""

## 5 · The verdict

Efficiency: confirmed where it is defined. Bias: confirmed, and it is the size of the
overnight gap. Usefulness: positive, modest, and only after the level is corrected.
"""
        ),
        code(
            r"""
summary = []
for tk, b in bars.items():
    t = st.scaled_forecast_race(b, burn=504)
    best = t.drop(index=["close_close"])["qlike"].idxmin()
    summary.append({"ticker": tk, "overnight share": st.overnight_share(b),
                    "best estimator": st.ESTIMATOR_LABEL[best].split(" (")[0],
                    "QLIKE gain": 1 - t.loc[best, "qlike"] / t.loc["close_close", "qlike"],
                    "DM": t.loc[best, "dm_vs_cc"]})
s = pd.DataFrame(summary).set_index("ticker")
print(s.round(4).to_string())
print(f"\nbeats close-to-close on {(s['QLIKE gain'] > 0).sum()}/{len(s)} tapes; "
      f"mean DM {s['DM'].mean():+.2f}")
"""
        ),
        md(
            r"""

## 6 · Could you use it?

Yes, with one instruction: **use Yang-Zhang, or rescale**. The estimator that is theoretically
best is the one that answers the question you asked — and "how much did this thing move today,
including while I was asleep" is a different question from "how much did it move during the
session".
"""
        ),
        md(
            r"""

## 7 · Going further

- **Realised variance from intraday bars** (Andersen & Bollerslev 1998) replaces the whole
  simulation section with a measurement.
- **Alizadeh, Brandt & Diebold (2002)**: the log-range is nearly Gaussian, which makes it a
  better *state variable* for a stochastic-volatility filter than a squared return — a natural
  fork of this study.
- **Microstructure-filtered extremes**: rebuild the high and low from NBBO-eligible prints.
- **Downstream cost**: run a vol-targeting overlay on each estimator and measure the tracking
  error against the mandate — the version of this question that has money attached.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
