"""Build the two narrative notebooks for Study 40 (Paper-Tiger).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Same seven desk beats at two altitudes. Figures are drawn inline from the cached real run
(_cache/paper_tiger_etfs.parquet, built by examples/verify.py --fetch); the synthetic world backs the
offline tests. _write convention preserved (see ../../_TEMPLATE/notebooks/build_notebooks.py)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (paper_tiger/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from paper_tiger import data, strategy as st

prices, tbill = data.fetch_etfs()          # cache-first; built by examples/verify.py --fetch
gem  = st.gem_returns(prices, tbill, cost_bps=20.0)
gem0 = st.gem_returns(prices, tbill, cost_bps=0.0)
spy  = st.buy_and_hold(prices, "US").loc[gem.index]
b40  = st.blend(prices).loc[gem.index]
def curve(s): return (1+s).cumprod()
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Paper-Tiger 🐯\n"
            "### A backtest that \"beats the market\" — does it, really?\n\n"
            "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
            "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
            "![Beats the market?: Not supported](https://img.shields.io/badge/Beats_the_market%3F-Not_supported-8b949e?style=flat-square)\n\n"
            "A vendor sells a dual-momentum strategy with a shiny backtest: ride the strongest stock "
            "market, flee to bonds before crashes, beat buy-and-hold. We rebuild it faithfully on real "
            "ETFs and check the headline against the benchmarks a sceptic would actually use. The "
            "strategy is *real* — but the reason it sells turns out to be a paper tiger.\n\n"
            "> 📓 **This is the plain-language layer.** The statistics, the decay test and the "
            "portfolio maths live in the companion **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** "
            "— same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it. House style "
            "in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            "| You might think… | The numbers say… |\n|---|---|\n"
            "| \"It beats the market\" | It **ties** buy-and-hold and **loses to a plain 60/40** on Sharpe. |\n"
            "| \"…because it's clever timing\" | Its only real gift is a **shallower drawdown** (−23% vs −51%). |\n"
            "| \"So I should hold it\" | A 60/40 you already own gives **more** risk-adjusted return for less effort. |\n\n"
            "It isn't a fraud — it makes money, reliably. It just doesn't do the one thing the headline promises."
        ),
        md("## 1 · The claim\n\nGary Antonacci's **dual momentum**: each month, hold whichever of US or "
           "foreign stocks has the stronger 12-month return — but only if that return beat Treasury bills; "
           "otherwise sit in bonds. The pitch: equity-like returns, **half the drawdown**, beats buy-and-hold."),
        md("## 2 · So what?\n\nThis is one of the most-cited retail quant strategies on the internet, sold "
           "in books and replicated on every backtest site. If \"beats the market with less risk\" is real, "
           "it's a free lunch. If it's a benchmarking illusion, millions are anchored on a number that "
           "doesn't hold up. Worth ten minutes to check."),
        md("## 3 · How would we even know?\n\nRebuild it on **real ETFs** (SPY, EFA, AGG) back to 2003, "
           "charge a realistic 20 bp every time it switches doors, and line it up against the two "
           "benchmarks that matter: **just owning SPY**, and a **boring monthly-rebalanced 60/40**. "
           "Then look at the equity curve *and* the drawdowns — because the whole sales pitch is about the drawdowns."),
        code(
            "fig, ax = plt.subplots()\n"
            "curve(gem).plot(ax=ax, label='GEM (dual momentum, net)', lw=2)\n"
            "curve(spy).plot(ax=ax, label='Buy & Hold SPY', lw=1.5, alpha=.8)\n"
            "curve(b40).plot(ax=ax, label='60/40 SPY/AGG', lw=1.5, alpha=.8)\n"
            "ax.set_yscale('log'); ax.set_title('Growth of \\$1 — GEM vs the benchmarks (log scale)')\n"
            "ax.set_ylabel('growth of \\$1'); ax.legend(); plt.show()"
        ),
        md("## 4 · The teardown — let's actually look\n\nThe headline table, and the picture that explains it."),
        code(
            "rows = {'GEM (net)': st.summary(gem), 'Buy & Hold SPY': st.summary(spy), '60/40 SPY/AGG': st.summary(b40)}\n"
            "tbl = pd.DataFrame(rows).T[['sharpe','cagr','vol_ann','max_drawdown']]\n"
            "tbl.columns = ['Sharpe','CAGR','vol','max drawdown']\n"
            "display(tbl.style.format({'CAGR':'{:.1%}','vol':'{:.1%}','max drawdown':'{:.1%}','Sharpe':'{:.2f}'}))"
        ),
        code(
            "def underwater(s): c = curve(s); return c/c.cummax() - 1\n"
            "fig, ax = plt.subplots()\n"
            "(underwater(gem)*100).plot(ax=ax, label='GEM', lw=1.8)\n"
            "(underwater(spy)*100).plot(ax=ax, label='Buy & Hold SPY', lw=1.2, alpha=.8)\n"
            "ax.set_title('Drawdown — the one place GEM clearly wins'); ax.set_ylabel('drawdown (%)'); ax.legend(); plt.show()"
        ),
        md("**Read it plainly.** Same ballpark wealth as SPY, but the red 2008 canyon is half as deep — "
           "because GEM was sitting in bonds. That crash-cushion is real. It just isn't *extra return*: "
           "the 60/40 line in the first chart gets a higher Sharpe without any timing at all."),
        md("## 5 · The verdict\n\n**Signal: Real** — it genuinely makes money (the quants notebook puts a "
           "t-stat of 3.4 on it). **Tradability: Fragile** — its edge is one-dimensional crash protection "
           "that leans on a single 2008 and has faded since. **Beats the market?: Not supported** — it "
           "ties SPY and loses to 60/40. A real strategy wearing a paper-tiger headline."),
        md("## 6 · Could you actually trade it?\n\nYes — and that's the seductive part. It trades ~1.5×/year, "
           "costs are trivial (20 bp/switch barely dents it), and it's genuinely defensive. But \"can you "
           "trade it\" isn't the question; \"does it beat the lazy alternative\" is — and a 60/40 index "
           "portfolio wins on Sharpe with zero effort."),
        md("## 7 · Going further 🚪\n\nThe deep companion — [02_for_the_quants](02_for_the_quants.ipynb) — "
           "puts standard errors on every claim, shows the post-publication decay, and runs the portfolio "
           "test: does adding a GEM sleeve to a 60/40 help? (It trims drawdown but doesn't lift Sharpe.) "
           "Contrast with [Study 31 Trade-Winds](../../31-trade-winds/), where a trend sleeve *does* raise "
           "portfolio Sharpe — that's the difference between real diversification and a paper tiger."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Paper-Tiger — a quantitative teardown 🔬\n"
            "### Faithful replication · the right benchmark · robust inference · post-publication decay · portfolio test\n\n"
            "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
            "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
            "![Beats the market?: Not supported](https://img.shields.io/badge/Beats_the_market%3F-Not_supported-8b949e?style=flat-square)\n\n"
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim now carrying its standard error.* We replicate Antonacci's Global Equities "
            "Momentum on real ETFs and ask whether the vendor's headline survives a fair benchmark, honest "
            "inference, and a portfolio context.\n\n"
            "> ⚠️ **Not investment advice.** Monthly total-return SPY/EFA/AGG + ^IRX (Yahoo), 2003–2026, "
            "20 bp/switch. Inference via `quantlab.analytics` (Lo 2002, Newey-West 1987). Sources in "
            "[`docs/references.md`](../docs/references.md).\n>\n"
            "> 💡 **The `In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT + "from quantlab.analytics import sharpe_with_se, mean_tstat_hac\n"),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            "| Signal | **Real** | net Sharpe 0.74, Lo t=3.4, HAC t=3.6 |\n"
            "| Tradability | **Fragile** | edge = crash protection only; one crisis; decays; no portfolio-Sharpe lift |\n"
            "| Beats the market? | **Not supported** | 0.74 ties SPY (0.77), loses to 60/40 (0.86) |\n\n"
            "> 💡 *In plain words:* it's a real return stream, but the thing that sells it — beating "
            "buy-and-hold — isn't there once you benchmark honestly."
        ),
        md("## 1 · The claim, steelmanned\n\n"
           "- **H₁ (signal):** GEM's net monthly return has a positive mean that survives autocorrelation-robust inference.\n"
           "- **H₂ (the pitch):** GEM beats buy-and-hold *and* a naïve 60/40 on Sharpe.\n"
           "- **H₃ (the real value):** GEM's edge is decorrelated crash protection that improves a portfolio."),
        md("## 2 · So what? — what rides on each answer\n\nIf H₂ holds, dual momentum is a free lunch and "
           "every 60/40 investor is leaving Sharpe on the table. If only H₁ and a weak H₃ hold, it's a "
           "defensive overlay whose marketing oversells it — useful to know before anchoring on a backtest."),
        md("## 3 · How we'd know — the protocol\n\nReplicate faithfully → benchmark against SPY and 60/40 "
           "→ Lo (2002) Sharpe SE and Newey-West HAC mean t-stat → split the sample pre/post-publication "
           "for decay → decompose returns in the worst-decile equity months → test a 30% GEM sleeve in a 60/40."),
        md("## 4 · The teardown"),
        md("### 4.1 GEM vs the benchmarks that matter"),
        code(
            "rows = {'GEM gross': st.summary(gem0), 'GEM net (20bp)': st.summary(gem),\n"
            "        'Buy & Hold SPY': st.summary(spy), '60/40 SPY/AGG': st.summary(b40)}\n"
            "tbl = pd.DataFrame(rows).T[['sharpe','cagr','vol_ann','max_drawdown','skew']]\n"
            "display(tbl.round(3))\n"
            "print('GEM net Sharpe %.2f  |  SPY %.2f  |  60/40 %.2f' % (st.summary(gem)['sharpe'], st.summary(spy)['sharpe'], st.summary(b40)['sharpe']))"
        ),
        md("> 💡 *In plain words:* GEM's 0.74 is statistically fine but **economically unremarkable** — "
           "it doesn't beat the lazy 60/40. H₂ already looks dead."),
        md("### 4.2 Is the signal real? Lo & Newey-West"),
        code(
            "lo = sharpe_with_se(gem, periods_per_year=12); hac = mean_tstat_hac(gem)\n"
            "print(f\"Lo (2002):  Sharpe {lo['sharpe_ann']:.2f}  ±{lo['se_ann']:.2f}  t={lo['tstat']:.2f}  (n={lo['n']})\")\n"
            "print(f\"Newey-West: mean {hac['mean_bps']:.0f} bp/mo  t={hac['tstat']:.2f}  (lags={hac['lags']})\")"
        ),
        md("> 💡 *In plain words:* t ≈ 3.4–3.6, comfortably significant. **H₁ holds** — the return is real. "
           "The story is what *kind* of real."),
        md("### 4.3 What's real: crash protection (worst-decile SPY months)"),
        code(
            "crisis = spy <= spy.quantile(0.10)\n"
            "comp = pd.DataFrame({'GEM': [gem[crisis].mean()*100, gem[~crisis].mean()*100],\n"
            "                     'SPY': [spy[crisis].mean()*100, spy[~crisis].mean()*100]},\n"
            "                    index=['worst-decile SPY months','the rest'])\n"
            "display(comp.round(2))\n"
            "print('n crisis months =', int(crisis.sum()), '| corr GEM~SPY in crises = %.2f' % gem[crisis].corr(spy[crisis]))\n"
            "ax = comp.plot.bar(rot=0, title='Mean monthly return — GEM cushions the worst months'); ax.set_ylabel('%/month'); plt.show()"
        ),
        md("> 💡 *In plain words:* in the months that hurt, GEM loses ~2.7 pts/month less than SPY and is "
           "uncorrelated to it (it's in bonds). **H₃'s cushion is real** — now, is it *fragile*?"),
        md("### 4.4 Why it's fragile: post-publication decay"),
        code(
            "sub = {'2004–2013': st.summary(gem.loc['2004':'2013'])['sharpe'],\n"
            "       '2014–2026': st.summary(gem.loc['2014':'2026'])['sharpe']}\n"
            "print('Sub-period Sharpe:', {k: round(v,2) for k,v in sub.items()})\n"
            "from quantlab.analytics import rolling_sharpe\n"
            "rs = rolling_sharpe(gem, window=36, periods_per_year=12)\n"
            "ax = rs.plot(title='Rolling 3-year Sharpe — the edge softens after Antonacci published (~2013)')\n"
            "ax.axhline(0, color='k', lw=.8); ax.set_ylabel('rolling Sharpe'); plt.show()"
        ),
        md("> 💡 *In plain words:* Sharpe 0.87 → 0.65 across the publication line — the textbook "
           "McLean–Pontiff fade. The cushion also leans heavily on **one** crisis (2008), so the "
           "independent-observation count behind the 23-year chart is thin."),
        md("### 4.5 The portfolio test: does a GEM sleeve help a 60/40?"),
        code(
            "mix = 0.7*b40 + 0.3*gem\n"
            "port = pd.DataFrame({'60/40 only': st.summary(b40), '70% 60/40 + 30% GEM': st.summary(mix)}).T\n"
            "display(port[['sharpe','max_drawdown']].round(3))\n"
            "print('Sharpe %.2f -> %.2f  (no lift) ; maxDD %.0f%% -> %.0f%% (trimmed)' % (\n"
            "    st.summary(b40)['sharpe'], st.summary(mix)['sharpe'], 100*st.summary(b40)['max_drawdown'], 100*st.summary(mix)['max_drawdown']))"
        ),
        md("> 💡 *In plain words:* the sleeve trims drawdown (−32% → −27%) but **doesn't raise Sharpe** "
           "(0.86 → 0.86). Compare Study 31's trend sleeve, which *lifts* Sharpe 0.48 → 0.56 — that's the "
           "difference between decorrelated alpha and a defensive overlay. **H₃ is real but thin.**"),
        md("## 5 · The verdict\n\nH₁ **holds** (t≈3.5). H₂ **rejected** (ties SPY, loses to 60/40). H₃ "
           "**weakly holds** (real cushion, but one crisis, decaying, no Sharpe lift). → Signal `REAL`, "
           "Tradability `FRAGILE`, market-beating claim `NOT SUPPORTED`."),
        md("## 6 · Could you trade it?\n\nEasily — ~1.5 switches/year, 20 bp barely registers (gross 0.77 → "
           "net 0.74), no capacity issue on SPY/EFA/AGG. The constraint isn't tradability; it's that the "
           "fair benchmark (60/40) already wins, so the strategy has to justify itself purely as drawdown "
           "insurance — and a cheaper insurance (just hold more bonds) does much the same."),
        md("## 7 · Going further\n\nForks: (a) substitute VEU/IEFA for EFA and BND for AGG — does the thin "
           "edge survive the proxy choice? (b) add the GEM cushion to the desk's other defensive studies; "
           "(c) re-run on a point-in-time membership to kill any residual survivorship in the equity proxies. "
           "The backlog of vendor strategies to mirror this way is in "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
