"""Build the two narrative notebooks for Study 40 (Paper-Tiger).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Same seven desk beats at two altitudes. Figures are drawn inline from the cached real run
(_cache/paper_tiger_etfs.parquet, built by examples/verify.py --fetch); the synthetic world backs the
offline tests. _write convention preserved (see ../../_TEMPLATE/notebooks/build_notebooks.py)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (paper_tiger/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from paper_tiger import data, strategy as st

prices, tbill = data.fetch_etfs()          # cache-first; built by examples/verify.py --fetch
gem  = st.gem_returns(prices, tbill, cost_bps=20.0)
gem0 = st.gem_returns(prices, tbill, cost_bps=0.0)
spy  = st.buy_and_hold(prices, "US").loc[gem.index]
b40  = st.blend(prices).loc[gem.index]
rf   = tbill.reindex(gem.index)            # the cash leg — Sharpe is quoted raw AND excess of this
def curve(s): return (1+s).cumprod()
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Beats the market?: Not supported](https://img.shields.io/badge/Beats_the_market%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Paper-Tiger 🐯\n"
            "### A backtest that \"beats the market\" — does it, really?\n\n"
            + VERDICT +
            "A vendor sells a dual-momentum strategy with a shiny backtest: ride the strongest stock "
            "market, flee to bonds before crashes, beat buy-and-hold. We rebuild it faithfully on real "
            "ETFs and check the headline against the benchmarks a sceptic would actually use. The book "
            "makes money — but the statistics turn out to belong to the *assets it holds*, not to the "
            "switching rule, and the reason it sells is a paper tiger.\n\n"
            "> 📓 **This is the plain-language layer.** The statistics, the spanning test and the "
            "portfolio maths live in the companion **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** "
            "— same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it. House style "
            "in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            "| You might think… | The numbers say… |\n|---|---|\n"
            "| \"It beats the market\" | It **trails** buy-and-hold and **loses to a plain 60/40** on Sharpe — in both conventions (raw and excess-of-cash). |\n"
            "| \"…because it's clever timing\" | Regress it on its own ingredients: the timing adds **+10 bp/month, t ≈ 0.5** — statistically nothing. |\n"
            "| \"But the equity curve is so smooth\" | Its only real gift is a **shallower drawdown** (−23% vs −51%) — riding on one crisis (2008). |\n"
            "| \"So I should hold it\" | A 60/40 you already own gives **more** risk-adjusted return for less effort. |\n\n"
            "It isn't a fraud — it makes money the way anything long stocks and bonds made money. It just "
            "doesn't do the one thing the headline promises."
        ),
        md("## 1 · The claim\n\nGary Antonacci's **dual momentum**: each month, hold whichever of US or "
           "foreign stocks has the stronger 12-month return — but only if that return beat Treasury bills; "
           "otherwise sit in bonds. The pitch: equity-like returns, **half the drawdown**, beats buy-and-hold."),
        md("## 2 · So what?\n\nThis is one of the most-cited retail quant strategies on the internet, sold "
           "in books and replicated on every backtest site. If \"beats the market with less risk\" is real, "
           "it's a free lunch. If it's a benchmarking illusion, millions are anchored on a number that "
           "doesn't hold up. Worth ten minutes to check."),
        md("## 3 · How would we even know?\n\nRebuild it on **real ETFs** (SPY, EFA, AGG) back to 2003, "
           "charge a realistic 20 bp every time it switches doors, and line it up against the two "
           "benchmarks that matter: **just owning SPY**, and a **boring monthly-rebalanced 60/40** — "
           "comparing like with like (the quants notebook also strips out the cash rate, so a strategy "
           "can't look good just for existing while rates were positive). Then ask the killer question: "
           "if you'd held a *fixed* mix of the same three ETFs, would you have done any worse?"),
        code(
            "fig, ax = plt.subplots()\n"
            "curve(gem).plot(ax=ax, label='GEM (dual momentum, net)', lw=2)\n"
            "curve(spy).plot(ax=ax, label='Buy & Hold SPY', lw=1.5, alpha=.8)\n"
            "curve(b40).plot(ax=ax, label='60/40 SPY/AGG', lw=1.5, alpha=.8)\n"
            "ax.set_yscale('log'); ax.set_title('Growth of \\$1 — GEM vs the benchmarks (log scale)')\n"
            "ax.set_ylabel('growth of \\$1'); ax.legend(); plt.show()"
        ),
        md("## 4 · The teardown — let's actually look\n\nThe headline table — Sharpe quoted both ways "
           "(raw, and after subtracting the T-bill return, which is the honest yardstick) — and the "
           "picture that explains it."),
        code(
            "rows = {'GEM (net)': (gem,), 'Buy & Hold SPY': (spy,), '60/40 SPY/AGG': (b40,)}\n"
            "tbl = pd.DataFrame({nm: {'Sharpe (raw)': st.summary(x)['sharpe'],\n"
            "                         'Sharpe (excess of cash)': st.summary(x, rf=rf)['sharpe'],\n"
            "                         'CAGR': st.summary(x)['cagr'],\n"
            "                         'max drawdown': st.summary(x)['max_drawdown']}\n"
            "                    for nm, (x,) in rows.items()}).T\n"
            "display(tbl.style.format({'CAGR':'{:.1%}','max drawdown':'{:.1%}',\n"
            "                          'Sharpe (raw)':'{:.2f}','Sharpe (excess of cash)':'{:.2f}'}))"
        ),
        code(
            "def underwater(s): c = curve(s); return c/c.cummax() - 1\n"
            "fig, ax = plt.subplots()\n"
            "(underwater(gem)*100).plot(ax=ax, label='GEM', lw=1.8)\n"
            "(underwater(spy)*100).plot(ax=ax, label='Buy & Hold SPY', lw=1.2, alpha=.8)\n"
            "ax.set_title('Drawdown — the one place GEM clearly wins'); ax.set_ylabel('drawdown (%)'); ax.legend(); plt.show()"
        ),
        md("**Read it plainly.** Same ballpark wealth as SPY, but the red 2008 canyon is half as deep — "
           "because GEM was sitting in bonds. That crash-cushion is real. It just isn't *extra return*: "
           "in both Sharpe conventions GEM trails SPY and the 60/40 line gets there without any timing "
           "at all."),
        md("## 5 · The verdict\n\n**Signal: Weak** — the book makes money, but so does anything long "
           "stocks for 23 years; strip it down to the timing decision (the quants notebook regresses GEM "
           "on its own ingredients) and the added return is **t ≈ 0.5** — statistically nothing. "
           "**Tradability: Fragile** — its edge is one-dimensional crash protection that leans on a "
           "single 2008 and has faded since. **Beats the market?: Not supported** — it trails SPY and "
           "loses to 60/40, raw or excess. A sensible defensive rule wearing a paper-tiger headline."),
        md("## 6 · Could you actually trade it?\n\nYes — and that's the seductive part. It trades ~1.5×/year, "
           "costs are trivial (20 bp/switch barely dents it), and it's genuinely defensive. But \"can you "
           "trade it\" isn't the question; \"does it beat the lazy alternative\" is — and a 60/40 index "
           "portfolio wins on Sharpe with zero effort."),
        md("## 7 · Going further 🚪\n\nThe deep companion — [02_for_the_quants](02_for_the_quants.ipynb) — "
           "puts standard errors on every claim, runs the spanning regression that isolates the timing "
           "skill, shows the post-publication decay, and runs the portfolio test: does adding a GEM sleeve "
           "to a 60/40 help? (It trims drawdown; the Sharpe barely moves.) Contrast with "
           "[Study 31 Trade-Winds](../../31-trade-winds/), where a trend sleeve *does* lift a portfolio — "
           "that's the difference between real diversification and a paper tiger."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Paper-Tiger — a quantitative teardown 🔬\n"
            "### Faithful replication · both Sharpe conventions · the spanning-alpha test · post-publication decay · portfolio test\n\n"
            + VERDICT +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim now carrying its standard error.* We replicate Antonacci's Global Equities "
            "Momentum on real ETFs and ask whether the vendor's headline survives a fair benchmark, honest "
            "inference, and a portfolio context — and, crucially, whether the *switching* itself carries "
            "any alpha once you regress the book on its own ingredients.\n\n"
            "> ⚠️ **Not investment advice.** Monthly total-return SPY/EFA/AGG + ^IRX (Yahoo), 2003–2026, "
            "20 bp/switch. Inference via `quantlab.analytics` (Lo 2002, Newey-West 1987). Sources in "
            "[`docs/references.md`](../docs/references.md).\n>\n"
            "> 💡 **The `In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT + "from quantlab.analytics import sharpe_with_se, mean_tstat_hac\n"),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            "| Signal | **Weak** | spanning alpha on SPY/AGG: +10 bp/mo, HAC t **0.49** — the raw t≈3.5 belongs to the assets |\n"
            "| Tradability | **Fragile** | edge = crash protection only; one crisis; decays; no real portfolio-Sharpe lift |\n"
            "| Beats the market? | **Not supported** | trails SPY raw (0.76 vs 0.79) and excess (0.62 vs 0.67); loses to 60/40 (0.87 / 0.68) |\n\n"
            "> 💡 *In plain words:* it's a real return stream, but the part that's statistically solid is "
            "the equity-and-bond premium it carries — the timing decision itself adds nothing you can "
            "distinguish from zero."
        ),
        md("## 1 · The claim, steelmanned\n\n"
           "- **H₁ (signal):** the *switching* adds value — GEM's alpha over a fixed mix of its own "
           "ingredients (SPY/AGG) is positive under autocorrelation-robust inference.\n"
           "- **H₂ (the pitch):** GEM beats buy-and-hold *and* a naïve 60/40 on Sharpe (any convention).\n"
           "- **H₃ (the real value):** GEM's edge is decorrelated crash protection that improves a portfolio."),
        md("## 2 · So what? — what rides on each answer\n\nIf H₂ holds, dual momentum is a free lunch and "
           "every 60/40 investor is leaving Sharpe on the table. If only a weak H₃ holds, it's a "
           "defensive overlay whose marketing oversells it — useful to know before anchoring on a backtest. "
           "And H₁ is the trap this study exists to spring: a t-stat on the raw mean of an always-invested "
           "book *cannot* test the strategy, because holding anything with a premium passes it."),
        md("## 3 · How we'd know — the protocol\n\nReplicate faithfully → benchmark against SPY and 60/40 "
           "in **both Sharpe conventions** (raw and excess of ^IRX) → the **spanning regression** of GEM's "
           "excess return on its ingredients' excess returns, HAC t on the intercept (the timing alpha) → "
           "Lo (2002) / Newey-West book-level inference for the record → split the sample pre/post-publication "
           "for decay → decompose returns in the worst-decile equity months → test a 30% GEM sleeve in a 60/40."),
        md("## 4 · The teardown"),
        md("### 4.1 GEM vs the benchmarks that matter — raw and excess of cash\n\n"
           "A raw Sharpe on an always-invested book silently pockets the cash rate. The excess-of-cash "
           "convention is what Lo's t-stat actually speaks, and with 2023–26 bills near 5% the difference "
           "is material. Both, side by side:"),
        code(
            "names = {'GEM gross': gem0, 'GEM net (20bp)': gem, 'Buy & Hold SPY': spy, '60/40 SPY/AGG': b40}\n"
            "tbl = pd.DataFrame({nm: {'sharpe_raw': st.summary(x)['sharpe'],\n"
            "                         'sharpe_excess': st.summary(x, rf=rf)['sharpe'],\n"
            "                         'cagr': st.summary(x)['cagr'], 'vol_ann': st.summary(x)['vol_ann'],\n"
            "                         'max_drawdown': st.summary(x)['max_drawdown'], 'skew': st.summary(x)['skew']}\n"
            "                    for nm, x in names.items()}).T\n"
            "display(tbl.round(3))\n"
            "print('excess Sharpe: GEM net %.2f  |  SPY %.2f  |  60/40 %.2f' % (\n"
            "    st.summary(gem, rf=rf)['sharpe'], st.summary(spy, rf=rf)['sharpe'], st.summary(b40, rf=rf)['sharpe']))"
        ),
        md("> 💡 *In plain words:* in **both** conventions GEM trails SPY and loses to the lazy 60/40. "
           "**H₂ is dead on arrival** — there is no benchmark under which the headline survives."),
        md("### 4.2 Is the *signal* real? The spanning test\n\n"
           "Regress GEM's excess return on the excess returns of its own doors:\n"
           "$$r_{GEM} - r_f = \\alpha + \\beta_1 (r_{SPY} - r_f) + \\beta_2 (r_{AGG} - r_f) + \\varepsilon$$\n"
           "The intercept is the return the *switching* added that a fixed mix of the same ETFs could not "
           "have earned — the only number that measures dual-momentum skill. HAC (Newey-West) errors."),
        code(
            "rets = st.to_returns(prices)\n"
            "fac = pd.DataFrame({'SPY': rets['US'], 'AGG': rets['BOND']}).sub(tbill, axis=0).loc[gem.index]\n"
            "sp = st.spanning_alpha((gem - rf).dropna(), fac)\n"
            "print(f\"alpha {sp['alpha_bps_m']:.0f} bp/mo ({sp['alpha_ann_pct']:.1f}%/yr)  HAC t={sp['tstat']:.2f}  \"\n"
            "      f\"betas SPY {sp['betas']['SPY']:.2f} / AGG {sp['betas']['AGG']:.2f}  R2={sp['r2']:.2f}  (n={sp['n']})\")\n"
            "sp40 = st.spanning_alpha((gem - rf).dropna(), (b40 - rf).dropna().rename('60/40').to_frame())\n"
            "print(f\"vs the 60/40 directly: alpha {sp40['alpha_bps_m']:.0f} bp/mo  HAC t={sp40['tstat']:.2f}  beta {sp40['betas']['60/40']:.2f}\")"
        ),
        md("> 💡 *In plain words:* **t ≈ 0.5.** The timing alpha is statistically indistinguishable from "
           "zero. **H₁ fails** — and this is the test that the seductive \"t = 3.5 on the mean\" was "
           "standing in for."),
        md("### 4.3 …then what was the t = 3.5 measuring? The asset premium\n\n"
           "For the record, the book-level inference in both conventions — and the same test applied to "
           "plain SPY, which 'passes' it too:"),
        code(
            "ex = (gem - rf).dropna()\n"
            "lo_x, hac_x = sharpe_with_se(gem, periods_per_year=12, rf=rf), mean_tstat_hac(ex)\n"
            "lo_r, hac_r = sharpe_with_se(gem, periods_per_year=12), mean_tstat_hac(gem)\n"
            "spy_x = sharpe_with_se(spy, periods_per_year=12, rf=rf)\n"
            "print(f\"GEM excess-of-cash: Lo Sharpe {lo_x['sharpe_ann']:.2f} t={lo_x['tstat']:.2f} | HAC mean {hac_x['mean_bps']:.0f} bp/mo t={hac_x['tstat']:.2f}\")\n"
            "print(f\"GEM raw:            Lo Sharpe {lo_r['sharpe_ann']:.2f} t={lo_r['tstat']:.2f} | HAC mean {hac_r['mean_bps']:.0f} bp/mo t={hac_r['tstat']:.2f}\")\n"
            "print(f\"SPY excess-of-cash: Lo Sharpe {spy_x['sharpe_ann']:.2f} t={spy_x['tstat']:.2f}  <- buy-and-hold passes the same bar\")"
        ),
        md("> 💡 *In plain words:* yes, GEM's mean clears t = 2 — but so does just owning SPY, with a "
           "*higher* excess Sharpe. A significance test that a do-nothing benchmark passes can't certify "
           "a strategy. The signal stamp is **Weak**: real return stream, no demonstrable timing skill."),
        md("### 4.4 What's real: crash protection (worst-decile SPY months)"),
        code(
            "crisis = spy <= spy.quantile(0.10)\n"
            "comp = pd.DataFrame({'GEM': [gem[crisis].mean()*100, gem[~crisis].mean()*100],\n"
            "                     'SPY': [spy[crisis].mean()*100, spy[~crisis].mean()*100]},\n"
            "                    index=['worst-decile SPY months','the rest'])\n"
            "display(comp.round(2))\n"
            "print('n crisis months =', int(crisis.sum()), '| corr GEM~SPY in crises = %.2f' % gem[crisis].corr(spy[crisis]))\n"
            "ax = comp.plot.bar(rot=0, title='Mean monthly return — GEM cushions the worst months'); ax.set_ylabel('%/month'); plt.show()"
        ),
        md("> 💡 *In plain words:* in the months that hurt, GEM loses ~2.8 pts/month less than SPY and is "
           "uncorrelated to it (it's in bonds). **H₃'s cushion is real** — now, is it *fragile*?"),
        md("### 4.5 Why it's fragile: post-publication decay"),
        code(
            "sub = pd.DataFrame({'2004–2013': {'raw': st.summary(gem.loc['2004':'2013'])['sharpe'],\n"
            "                                  'excess': st.summary(gem.loc['2004':'2013'], rf=rf)['sharpe']},\n"
            "                    '2014–2026': {'raw': st.summary(gem.loc['2014':'2026'])['sharpe'],\n"
            "                                  'excess': st.summary(gem.loc['2014':'2026'], rf=rf)['sharpe']}})\n"
            "display(sub.round(2))\n"
            "from quantlab.analytics import rolling_sharpe\n"
            "rs = rolling_sharpe(gem, window=36, periods_per_year=12)\n"
            "ax = rs.plot(title='Rolling 3-year Sharpe — the edge softens after Antonacci published (~2013)')\n"
            "ax.axhline(0, color='k', lw=.8); ax.set_ylabel('rolling Sharpe'); plt.show()"
        ),
        md("> 💡 *In plain words:* excess Sharpe 0.74 → 0.52 across the publication line — the textbook "
           "McLean–Pontiff fade. The cushion also leans heavily on **one** crisis (2008), so the "
           "independent-observation count behind the 23-year chart is thin."),
        md("### 4.6 The portfolio test: does a GEM sleeve help a 60/40?"),
        code(
            "mix = 0.7*b40 + 0.3*gem\n"
            "port = pd.DataFrame({'60/40 only': {'sharpe_excess': st.summary(b40, rf=rf)['sharpe'],\n"
            "                                    'max_drawdown': st.summary(b40)['max_drawdown']},\n"
            "                     '70% 60/40 + 30% GEM': {'sharpe_excess': st.summary(mix, rf=rf)['sharpe'],\n"
            "                                             'max_drawdown': st.summary(mix)['max_drawdown']}}).T\n"
            "display(port.round(3))\n"
            "print('excess Sharpe %.2f -> %.2f ; maxDD %.0f%% -> %.0f%% (trimmed)' % (\n"
            "    st.summary(b40, rf=rf)['sharpe'], st.summary(mix, rf=rf)['sharpe'],\n"
            "    100*st.summary(b40)['max_drawdown'], 100*st.summary(mix)['max_drawdown']))"
        ),
        md("> 💡 *In plain words:* the sleeve trims drawdown (−32% → −27%) and nudges the excess Sharpe "
           "0.68 → 0.70 — a rounding-error lift, consistent with a zero-alpha sleeve that's merely "
           "defensive. Compare Study 31's trend sleeve, which lifts a 60/40 0.48 → 0.56 — that's what "
           "genuinely decorrelated alpha looks like. **H₃ is real but thin.**"),
        md("## 5 · The verdict\n\nH₁ **fails** (spanning alpha t ≈ 0.5 — the raw t ≈ 3.5 belongs to the "
           "asset premium). H₂ **rejected** (trails SPY, loses to 60/40, both conventions). H₃ "
           "**weakly holds** (real cushion, but one crisis, decaying, no meaningful Sharpe lift). → "
           "Signal `WEAK`, Tradability `FRAGILE`, market-beating claim `NOT SUPPORTED`."),
        md("## 6 · Could you trade it?\n\nEasily — ~1.5 switches/year, 20 bp barely registers (gross 0.79 → "
           "net 0.76 raw), no capacity issue on SPY/EFA/AGG. The constraint isn't tradability; it's that the "
           "fair benchmark (60/40) already wins, so the strategy has to justify itself purely as drawdown "
           "insurance — and a cheaper insurance (just hold more bonds) does much the same."),
        md("## 7 · Going further\n\nForks: (a) substitute VEU/IEFA for EFA and BND for AGG — does the thin "
           "edge survive the proxy choice? (b) bootstrap the spanning alpha's distribution rather than "
           "relying on the HAC asymptotics; (c) re-run on a point-in-time membership to kill any residual "
           "survivorship in the equity proxies. The backlog of vendor strategies to mirror this way is in "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
