"""Notebook builder for Study 996 — The Palindrome Portfolio.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Palindrome Portfolio \U0001FA9E
### A market pattern based on absolutely nothing, and how significant we can make it look

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

Every other study on this desk tries to avoid finding things that are not there. This one goes
looking on purpose. Palindromic dates — 22/02/2022 — cannot possibly move markets, which makes
them the perfect measuring stick: whatever we find is exactly what a search of this size
produces when there is nothing to find.

> \U0001F4D3 **This is the plain-language layer.** The distribution of the maximum, the shuffle
> test and the corrections are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do palindromic dates move markets? | No. Obviously not. |
| Can we find a calendar rule that looks significant? | Easily. |
| How significant? | Around *t* = 3.4 — "one in a thousand". |
| Is that surprising? | No. A random walk gives the same. |
"""
        ),
        md(
            r"""

## 1 · A hypothesis with nothing behind it
"""
        ),
        code(
            r"""
from palindrome import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
lead = assets[data.EQUITY]
preds = st.date_predicates()
print(f"as-of {data.AS_OF} | {len(assets)} assets, {len(preds)} calendar rules")
print(f"total tests to be run: {len(assets) * len(preds)}")
"""
        ),
        code(
            r"""
pal = st.apply_predicate(lead.index, preds["palindrome DDMMYYYY"])
print(f"palindromic trading days in the sample: {int(pal.sum())}")
print("examples:", ", ".join(str(d.date()) for d in lead.index[pal][:8]))
out = st.test_rule(lead, pal)
if "mean_hit" in out:
    print(f"\nreturn on those days:      {out['mean_hit'] * 100:+.4f}%")
    print(f"return on every other day: {out['mean_miss'] * 100:+.4f}%")
    print(f"t-statistic: {out['t']:+.2f}")
else:
    print(f"\nOnly {out['n_hit']} of them. The module refuses to compute a t-statistic on")
    print("that few observations rather than reporting one -- which is the first lesson here:")
    print("the rarest rules produce the wildest 'findings', so a minimum sample size is not a")
    print("technicality, it is the main defence.")
"""
        ),
        md(
            r"""

Nothing there, as expected — and note what happened if the count was small. The rules that
select the fewest days are the ones most able to produce a spectacular *t*, which is exactly
why they need a floor on the sample size.

But we only tried *one* rule.
"""
        ),
        md(
            r"""

## 2 · So we try a hundred more
"""
        ),
        code(
            r"""
panel = st.scan_panel(assets, preds)
print(f"{len(panel)} tests run")
print(f"significant at the 5% level: {int((panel['t'].abs() > 1.96).sum())}")
print()
print("the top ten:")
print(panel.head(10)[["asset", "t", "ann_difference", "n_hit"]].round(4).to_string())
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 5))
ax.hist(panel["t"], bins=60, density=True, color="#8b949e", edgecolor="white",
        label="our 'findings'")
grid = np.linspace(-4.5, 4.5, 300)
ax.plot(grid, np.exp(-grid ** 2 / 2) / np.sqrt(2 * np.pi), lw=2.5, color="#c0392b",
        label="what pure noise gives")
for x in (-1.96, 1.96):
    ax.axvline(x, ls="--", color="k", lw=1)
ax.set_xlabel("t-statistic"); ax.legend(fontsize=9)
ax.set_title("Every one of these is a false positive by construction")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The histogram sits on top of the standard normal, as it must.
> The tails are the "discoveries". There is no anomaly here — only the arithmetic of trying
> several hundred things.
"""
        ),
        md(
            r"""

## 3 · The winner, presented as a finding would be
"""
        ),
        code(
            r"""
best = panel.iloc[0]
rule = panel.index[0]
mask = st.apply_predicate(lead.index, preds[rule])
print(f"RULE: '{rule}' on {best['asset']}")
print(f"  t = {best['t']:+.2f}  ({int(best['n_hit'])} observations)")
print(f"  worth {best['ann_difference']:+.1%} per year")
from scipy import stats as sps
p = 2 * (1 - sps.norm.cdf(abs(best['t'])))
print(f"  p-value: {p:.5f}  -> a 1-in-{1/p:,.0f} event")
print("\nWritten up confidently, that is a publishable-looking paragraph.")
"""
        ),
        md(
            r"""

## 4 · The correction nobody applies

If you try one thing, a *t* of 2 is surprising. If you try seven hundred, the *best* one is
expected to be around 3 — not as a lucky outcome, but as the **median**.
"""
        ),
        code(
            r"""
rows = []
for k in (1, 5, 20, 100, 300, len(panel), 5000):
    e = st.expected_max_t(k, n_sims=4000)
    rows.append({"tries": k, "median best |t|": e["median"], "90th pct": e["p90"],
                 "chance of beating 2": e["share_above_2"]})
d = pd.DataFrame(rows).set_index("tries")
fig, ax = plt.subplots(figsize=(10, 5))
ax.semilogx(d.index, d["median best |t|"], "o-", lw=2, color="#c0392b",
            label="median best |t| from pure noise")
ax.axhline(1.96, ls="--", color="#8b949e", lw=1.5, label="the 5% threshold")
ax.axhline(abs(best["t"]), ls=":", color="#2ea44f", lw=2,
           label=f"our 'discovery' ({abs(best['t']):.2f})")
ax.set_xlabel("number of hypotheses tried"); ax.set_ylabel("expected best |t|")
ax.legend(fontsize=8)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

Our headline result sits almost exactly on the red line. It is the *expected* outcome of trying
this many things, not an unusual one.
"""
        ),
        md(
            r"""

## 5 · The test that settles it

Shuffle the returns so that any calendar link is destroyed by construction, then run the
identical search again. Repeat. If the real search does no better than the shuffled ones, there
is nothing there.
"""
        ),
        code(
            r"""
bd = st.best_rule_distribution(lead, preds, n_shuffles=100)
print(f"observed best |t|:               {bd['observed_max_t']:.2f}")
print(f"median best |t| after shuffling: {bd['null_median_max_t']:.2f}")
print(f"95th percentile:                 {bd['null_p95_max_t']:.2f}")
print(f"p-value:                         {bd['p_value']:.3f}")
"""
        ),
        md(
            r"""

## 6 · And out of sample
"""
        ),
        code(
            r"""
oos = st.split_sample_check(lead, preds)
fig, ax = plt.subplots(figsize=(10, 5))
xs = np.arange(len(oos))
ax.bar(xs - 0.2, oos["t_in_sample"], 0.4, label="in sample (where we picked them)",
       color="#2ea44f")
ax.bar(xs + 0.2, oos["t_out_of_sample"], 0.4, label="out of sample", color="#c0392b")
ax.axhline(0, color="k", lw=1)
for y in (-1.96, 1.96):
    ax.axhline(y, ls="--", color="#8b949e", lw=1)
ax.set_xticks(xs); ax.set_xticklabels([r[:22] for r in oos.index], rotation=35,
                                      ha="right", fontsize=7)
ax.set_ylabel("t-statistic"); ax.legend(fontsize=8)
plt.show()
print(oos.round(3).to_string())
"""
        ),
        md(
            r"""

## 7 · The verdict

**Signal: Busted.** Searching **98 meaningless calendar rules** across 6 assets — 531 tests in total — produced **25 results significant at 5%**, against 27 expected by pure luck. The best was *day is a power of two* on SPY at *t* = **+3.22**, worth +28.8% a year. On a *t*-table that is a one-in-786 event. It is nothing of the sort. Reshuffling the returns and rerunning the identical search produced a best |*t*| of **2.63** at the median and 3.42 at the 95th percentile, so the observed maximum has a shuffle *p*-value of **0.10**. Bonferroni would have required *t* > 3.91; **0** rules cleared it. The correct reading of the headline number is that it is a draw from the distribution of the *maximum* of 531 tries, whose median is 3.22 — not from a *t*-distribution, whose median is 0.67.

**Tradability: Mirage.** Selecting the ten best rules on the first half of the sample and testing them on the second half is the whole story in one table: their in-sample *t* averaged **-0.59** and their out-of-sample *t* averaged **+0.65**, with 6 of 10 keeping the same sign. Traded with costs, the single best rule turned +28.8% a year of apparent edge into -5.88% against simply holding the index. That is the price of believing a pattern with no mechanism, and it is charged in full.
"""
        ),
        md(
            r"""

## 8 · The lesson \U0001F6AA

Everything above was done with a hypothesis that is *definitely* false. The same procedure, on a
hypothesis that merely *might* be false, produces the same numbers — and there is no way to tell
from the numbers alone which case you are in.

Three defences, in ascending order of strength:

1. **Count your tests and say so.** Bonferroni is crude but honest.
2. **Shuffle and re-run the whole search.** This handles overlapping tests, which the formulas
   cannot.
3. **Hold out data you have never looked at.** The only defence that cannot be gamed.

And one that beats all three: **have a mechanism first**.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Palindrome Portfolio — a quantitative teardown \U0001F52C
### ~700 tests · the distribution of the maximum · a shuffle test that respects overlap

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The point is not
that palindromes do nothing — it is the *size* of the effect a search this size manufactures, and
the fact that it is indistinguishable from what the same search finds on a random walk.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from palindrome import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
lead = assets[data.EQUITY]
preds = st.date_predicates()
print(f"as-of {data.AS_OF} | {len(assets)} assets, {len(preds)} calendar rules")
print(f"total tests to be run: {len(assets) * len(preds)}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Busted | Searching **98 meaningless calendar rules** across 6 assets — 531 tests in total — produced **25 results significant at 5%**, against 27 expected by pure luck. The best was *day is a power of two* on SPY at *t* = **+3.22**, worth +28.8% a year. On a *t*-table that is a one-in-786 event. It is nothing of the sort. Reshuffling the returns and rerunning the identical search produced a best |*t*| of **2.63** at the median and 3.42 at the 95th percentile, so the observed maximum has a shuffle *p*-value of **0.10**. Bonferroni would have required *t* > 3.91; **0** rules cleared it. The correct reading of the headline number is that it is a draw from the distribution of the *maximum* of 531 tries, whose median is 3.22 — not from a *t*-distribution, whose median is 0.67. |
| **Tradability** | Mirage | Selecting the ten best rules on the first half of the sample and testing them on the second half is the whole story in one table: their in-sample *t* averaged **-0.59** and their out-of-sample *t* averaged **+0.65**, with 6 of 10 keeping the same sign. Traded with costs, the single best rule turned +28.8% a year of apparent edge into -5.88% against simply holding the index. That is the price of believing a pattern with no mechanism, and it is charged in full. |

> \U0001F4A1 **In plain words.** "Busted" is the correct answer and the intended one. The stamps
> grade the demonstration, not the pattern.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

Inverted, because the null is known true:

- **H₁.** A search over ~700 meaningless tests produces results significant at 5% at
  approximately the nominal rate.
- **H₂.** Its maximum \|*t*\| matches the theoretical distribution of the maximum of that many
  draws.
- **H₃.** Because the rules overlap, the *shuffle* null exceeds the independent-tests
  calculation — so the correct threshold is higher than Bonferroni's.
- **H₄.** No rule survives out of sample.
- **H₅ (calibration).** The best \|*t*\| on the real tape is indistinguishable from the best
  \|*t*\| on a random walk.
"""
        ),
        md(
            r"""

## 2 · The rule catalogue
"""
        ),
        code(
            r"""
rows = []
for name, pred in preds.items():
    m = st.apply_predicate(lead.index, pred)
    rows.append({"rule": name, "days": int(m.sum()), "share": float(m.mean())})
d = pd.DataFrame(rows).set_index("rule").sort_values("days")
print(f"{len(d)} rules, selecting between {d['days'].min()} and {d['days'].max()} days")
print()
print("the rarest ten:")
print(d.head(10).to_string())
print()
print("the most common ten:")
print(d.tail(10).to_string())
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.hist(d["share"] * 100, bins=40, color="#8b949e", edgecolor="white")
ax.set_xlabel("share of days each rule selects (%)"); ax.set_ylabel("rules")
ax.set_title("A rule selecting very few days has a noisy t — which is where extremes come from")
plt.show()
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The full scan
"""
        ),
        code(
            r"""
panel = st.scan_panel(assets, preds)
summ = st.multiple_testing_summary(panel["t"])
print(pd.Series(summ).round(4).to_string())
print()
print(panel.head(15)[["asset", "t", "ann_difference", "n_hit"]].round(4).to_string())
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].hist(panel["t"], bins=70, density=True, color="#8b949e", edgecolor="white")
grid = np.linspace(-5, 5, 400)
axes[0].plot(grid, np.exp(-grid ** 2 / 2) / np.sqrt(2 * np.pi), lw=2, color="#c0392b")
axes[0].set_xlabel("t"); axes[0].set_title("observed vs the standard normal")
from scipy import stats as sps
p = 2 * (1 - sps.norm.cdf(np.abs(panel["t"].dropna())))
axes[1].plot(np.sort(p), np.linspace(0, 1, len(p)), lw=2, color="#1f6feb",
             label="observed")
axes[1].plot([0, 1], [0, 1], "k--", lw=1.5, label="uniform (the null)")
axes[1].set_xlabel("p-value"); axes[1].set_ylabel("empirical CDF"); axes[1].legend(fontsize=8)
axes[1].set_title("a p-value QQ plot: on the diagonal means nothing is there")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The right panel is the cleanest single diagnostic in the whole
> study. Under a true null, *p*-values are uniform and the curve lies on the diagonal. A real
> effect bends it upward at the left. Ours does not bend.
"""
        ),
        md(
            r"""

### 3.2 The distribution of the maximum
"""
        ),
        code(
            r"""
rows = []
for k in (1, 2, 5, 10, 25, 50, 100, 250, 500, len(panel), 2000, 10000):
    e = st.expected_max_t(k, n_sims=4000)
    rows.append({"tries": k, **{kk: e[kk] for kk in ("median", "p90", "p99",
                                                     "share_above_2", "share_above_3")}})
d = pd.DataFrame(rows).set_index("tries")
fig, ax = plt.subplots(figsize=(10, 5.5))
ax.semilogx(d.index, d["median"], "o-", lw=2, color="#1f6feb", label="median")
ax.fill_between(d.index, d["median"], d["p99"], alpha=0.15, color="#1f6feb",
                label="median to 99th pct")
ax.axhline(1.96, ls="--", color="#8b949e", lw=1.5, label="'significant'")
ax.axhline(3.0, ls="--", color="#f0b429", lw=1.5, label="Harvey/Liu/Zhu's suggested bar")
ax.axvline(len(panel), ls=":", color="#c0392b", lw=1.5, label="our search")
ax.set_xlabel("hypotheses tried"); ax.set_ylabel("best |t| obtainable from noise")
ax.legend(fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

### 3.3 Corrections
"""
        ),
        code(
            r"""
t = panel["t"].dropna()
p = 2 * (1 - sps.norm.cdf(np.abs(t)))
n = len(p)
order = np.argsort(p)
p_sorted = p[order]
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(np.arange(1, n + 1), p_sorted, lw=1.8, color="#1f6feb", label="sorted p-values")
ax.axhline(0.05, ls="--", color="#8b949e", lw=1.5, label="nominal 5%")
ax.axhline(0.05 / n, ls="--", color="#c0392b", lw=1.5, label=f"Bonferroni (0.05/{n})")
ax.plot(np.arange(1, n + 1), 0.05 * np.arange(1, n + 1) / n, ls="--", color="#2ea44f",
        lw=1.5, label="Benjamini-Hochberg line")
ax.set_xlim(0, min(120, n)); ax.set_ylim(0, 0.08)
ax.set_xlabel("rank"); ax.set_ylabel("p-value"); ax.legend(fontsize=8)
plt.show()
print(f"survive nominal 5%: {int((p < 0.05).sum())}")
print(f"survive Bonferroni: {summ['n_surviving_bonferroni']}")
print(f"survive BH:         {summ['n_surviving_bh']}")
"""
        ),
        md(
            r"""

### 3.4 The shuffle test, which handles overlap
"""
        ),
        code(
            r"""
bd = st.best_rule_distribution(lead, preds, n_shuffles=120)
# Build the mask matrix ONCE. Every predicate is a function of the date, so shuffling the
# returns does not change it -- rebuilding it inside the loop turns a 15-second cell into a
# 20-minute one, which is how a study like this quietly becomes unrunnable.
rng = np.random.default_rng(996)
vals = lead.dropna().to_numpy(dtype=float)
names, M = st.build_mask_matrix(lead.dropna().index, preds)
maxes = []
for _ in range(120):
    t_all = st.scan_matrix(rng.permutation(vals), names, M)
    if np.isfinite(t_all).any():
        maxes.append(float(np.nanmax(np.abs(t_all))))
maxes = np.array(maxes)
fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(maxes, bins=30, color="#8b949e", edgecolor="white", label="best |t| after shuffling")
ax.axvline(bd["observed_max_t"], color="#c0392b", lw=2.5,
           label=f"the real tape ({bd['observed_max_t']:.2f})")
theo = st.expected_max_t(len(preds), n_sims=4000)["median"]
ax.axvline(theo, color="#2ea44f", ls="--", lw=2,
           label=f"independent-tests theory ({theo:.2f})")
ax.set_xlabel("best |t| from a full search"); ax.legend(fontsize=8)
plt.show()
print(f"shuffle median {np.median(maxes):.2f} vs independent-test theory {theo:.2f}")
print(f"p-value: {(maxes >= bd['observed_max_t']).mean():.3f}")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The green line is what the arithmetic predicts if the tests are
> independent. The grey histogram is what actually happens when they overlap. Which of the two
> is higher tells you whether Bonferroni is conservative or optimistic for your particular
> search — and it is not always the answer people assume.
"""
        ),
        md(
            r"""

### 3.5 Out-of-sample decay, several splits
"""
        ),
        code(
            r"""
rows = []
for split in (0.3, 0.5, 0.7):
    d = st.split_sample_check(lead, preds, split=split)
    for rule, r in d.iterrows():
        rows.append({"split": split, "rule": rule, "t_in": r["t_in_sample"],
                     "t_out": r["t_out_of_sample"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(9, 6))
for split, g in d.groupby("split"):
    ax.scatter(g["t_in"], g["t_out"], s=60, alpha=0.7, label=f"split at {split:.0%}")
lim = [d[["t_in", "t_out"]].min().min() - 0.5, d[["t_in", "t_out"]].max().max() + 0.5]
ax.plot(lim, lim, "k--", lw=1.5, label="if the effect were real")
ax.axhline(0, color="#8b949e", lw=1); ax.axvline(0, color="#8b949e", lw=1)
ax.set_xlabel("t in sample (where the rule was chosen)")
ax.set_ylabel("t out of sample"); ax.legend(fontsize=8)
plt.show()
print(d.groupby("split")[["t_in", "t_out"]].mean().round(3).to_string())
print(f"\ncorrelation between in- and out-of-sample t: {d['t_in'].corr(d['t_out']):+.3f}")
"""
        ),
        md(
            r"""

### 3.6 Calibration against a random walk
"""
        ),
        code(
            r"""
rows = []
cache = st.build_mask_matrix(lead.dropna().index, preds)
for k in range(8):
    sim = st.synthetic_returns(n=len(lead), seed=996 + k)
    sim.index = lead.dropna().index          # same calendar, so the same cached masks apply
    dd = st.scan(sim, preds, cache=cache)
    s2 = st.multiple_testing_summary(dd["t"])
    rows.append({"source": f"random walk {k}", "n_significant": s2["n_significant"],
                 "max_t": s2["max_abs_t"]})
real = st.scan(lead, preds, cache=cache)
s_real = st.multiple_testing_summary(real["t"])
rows.append({"source": "THE REAL TAPE", "n_significant": s_real["n_significant"],
             "max_t": s_real["max_abs_t"]})
d = pd.DataFrame(rows).set_index("source")
fig, ax = plt.subplots(figsize=(10, 4.8))
colors = ["#8b949e"] * (len(d) - 1) + ["#c0392b"]
ax.bar(range(len(d)), d["max_t"], color=colors)
ax.axhline(d["max_t"].iloc[:-1].mean(), ls="--", color="k", lw=1.5,
           label="average on noise")
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index, rotation=30, ha="right",
                                                 fontsize=8)
ax.set_ylabel("best |t| found by the same search"); ax.legend(fontsize=8)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

### 3.7 And what trading it costs
"""
        ),
        code(
            r"""
cash = rets[data.CASH].reindex(lead.index).fillna(0.0)
rows = []
for rule in panel.index[:5]:
    mask = st.apply_predicate(lead.index, preds[rule])
    tc = st.tradable_check(lead, mask, cash, 2.0)
    rows.append({"rule": rule, "invested": tc["share_invested"],
                 "switches/yr": tc["switches_per_year"],
                 "strategy CAGR": tc["strategy"]["cagr"],
                 "buy-hold CAGR": tc["buy_hold"]["cagr"],
                 "gap": tc["strategy"]["cagr"] - tc["buy_hold"]["cagr"]})
d = pd.DataFrame(rows).set_index("rule")
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
pd.DataFrame({
    "rules tried": [len(preds)],
    "total tests": [len(panel)],
    "significant at 5%": [summ["n_significant"]],
    "expected by luck": [summ["expected_by_luck"]],
    "best |t| observed": [summ["max_abs_t"]],
    "expected best |t| from noise": [st.expected_max_t(len(panel), n_sims=3000)["median"]],
    "deflated t": [st.deflated_t(summ["max_abs_t"], len(panel))],
    "Bonferroni threshold": [summ["bonferroni_t"]],
    "surviving Bonferroni": [summ["n_surviving_bonferroni"]],
    "shuffle p-value": [bd["p_value"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **White's (2000) Reality Check** and **Romano-Wolf (2005)** are the formal versions of section
  3.4, with proper asymptotics and stepwise power. Implementing them would upgrade the shuffle
  test from a demonstration to a procedure.
- **Count the community's tests, not yours.** Lo & MacKinlay (1990) and Harvey, Liu & Zhu (2016)
  argue the relevant *k* is every test anyone ever ran on the same data — which is why the
  suggested hurdle is 3.0 and not 2.0.
- **A block shuffle.** The permutation here destroys volatility clustering along with the
  calendar link. A block permutation would preserve clustering and give a slightly higher, more
  honest null.
- **Run it on your own strategy.** The machinery is generic: replace `date_predicates` with your
  parameter grid and the shuffle test tells you what your best backtest is worth.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
