"""Build the two narrative notebooks for Study 48 (Groundhog).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/groundhog_panel.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (groundhog/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from groundhog import data, strategy as st
ret = data.fetch_panel()                       # cache-first; built by examples/verify.py --fetch
same = st.seasonal_hedge(ret, same_month=True)
ctrl = st.seasonal_hedge(ret, same_month=False)
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Genuinely same-month seasonal?: Confirmed](https://img.shields.io/badge/Genuinely_same--month_seasonal%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Groundhog 🔁\n### Do stocks have 'favourite months'? Absurd — and it's real\n\n"
           + VERDICT +
           "Here's a claim that sounds like astrology: a stock tends to repeat its **calendar-month** "
           "performance — a name that's done well in past Marches keeps doing well in Marches. It should "
           "be nonsense. Instead it's one of the most robust effects on this bench: significant, "
           "specific to the same month, and it hasn't faded in 26 years.\n\n"
           "> 📓 **Plain-language layer.** The control, the t-stat and the cost sweep are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| You'd assume | The data says |\n|---|---|\n"
           "| \"Calendar months are noise\" | Long-short on same-month history: **+7.3%/yr, t = 4.1**. |\n"
           "| \"It's just momentum\" | Ranking on *other* months earns **−3.3%/yr** — it's the same month, specifically. |\n"
           "| \"Surely it's decayed\" | Sharpe **0.81** in both halves of the sample. |"),
        md("## 1 · The claim\n\nHeston & Sadka (2008): a stock's average return in a given calendar month "
           "predicts its return in that same month in future years. Rank by same-month history, long the "
           "winners, short the losers — a pure cross-sectional seasonal."),
        md("## 2 · So what?\n\nIf returns carry a stable calendar-month fingerprint, that's a free, "
           "decorrelated source of cross-sectional alpha — and a genuine puzzle for efficient markets. "
           "But 'a stock likes March' is exactly the kind of pattern that screams data-mining, so the "
           "test has to be airtight."),
        md("## 3 · How would we even know?\n\nThe airtight test is a **control**: rank stocks by their "
           "*other*-month history instead of the same month. If only the same month predicts, it's a "
           "real seasonal; if other months predict too, it's just generic persistence."),
        code("s, c = st.stats(same), st.stats(ctrl)\n"
             "fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['same-month\\nhistory','other-month\\nhistory (control)'],[s['mean_ann']*100,c['mean_ann']*100],color=['#2ea44f','#8b949e'])\n"
             "ax.set_ylabel('long-short return (%/yr)'); ax.axhline(0,color='k',lw=.8)\n"
             "ax.set_title(f\"It's the SAME month: +{s['mean_ann']*100:.0f}%/yr (t={s['tstat']:.1f}) vs {c['mean_ann']*100:.0f}%/yr control\"); plt.show()"),
        md("## 4 · The teardown\n\nThe same-month book compounds; the control bleeds. And the effect is as "
           "strong in the second half of the sample as the first."),
        code("eq=(1+same).cumprod(); eqc=(1+ctrl).cumprod()\n"
             "ax=eq.plot(label='same-month seasonality',lw=1.8); eqc.plot(ax=ax,label='control (other months)',lw=1.4,alpha=.8)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1 in the long-short, 2000-2026'); ax.legend(); plt.show()\n"
             "for lab,sl in [('1999-2012',same.loc[:'2012']),('2013-on',same.loc['2013':])]:\n"
             "    print(f'{lab}: Sharpe {st.stats(sl)[\"sharpe\"]:+.2f}')"),
        md("**Read it plainly.** The weird thing is true. A stock really does carry a same-month "
           "fingerprint, and it's persisted for a generation — the opposite of the decayed mirages "
           "elsewhere on this bench."),
        md("## 5 · The verdict\n\n**Signal: Real** — t 4.1, undecayed. **Tradability: Fragile** — it "
           "survives moderate costs but reshuffles monthly and needs a big short book. **Same-month "
           "seasonal?: Confirmed** — the control fails."),
        md("## 6 · Could you actually trade it?\n\nMaybe — and that's the honest 'fragile'. Break-even is "
           "~38 bp/trade and net Sharpe is still 0.59 at 10 bp; but the book turns over fully each month, "
           "you must short ~80 names (borrow costs, hard-to-borrow), and our large-cap survivor universe "
           "flatters it. The signal is real; the *net you keep* is the open question."),
        md("## 7 · Going further 🚪\n\nThe quants notebook has the cost sweep and break-even. Next: "
           "[Study 49 Black-Gold](../../49-black-gold/) — does the price of oil predict the stock market?"),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Groundhog — a quantitative teardown 🔬\n### The same-month vs other-month control · the Lo t-stat · no decay · the cost sweep\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We confirm "
           "return seasonality is real and same-month-specific, then ask what survives turnover.\n\n"
           "> ⚠️ **Not investment advice.** 398 S&P 500 names with ≥20y history (Yahoo), 2000–2026; "
           "survivorship-biased, large-cap. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | +7.3%/yr, Sharpe 0.81, Lo t 4.1, no decay |\n"
           "| Tradability | **Fragile** | break-even 38 bp but monthly full turnover + short book |\n"
           "| Same-month seasonal? | **Confirmed** | other-month control earns −3.3%/yr |\n\n"
           "> 💡 *In plain words:* a genuinely strange effect that passes every guard."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** the same-month long-short earns a significant "
           "positive return.\n- **H₂:** it's specific to the same month (the other-month control fails).\n"
           "- **H₃:** it survives realistic costs."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, calendar seasonality is a real, "
           "decorrelated alpha and a puzzle for efficient markets. H₃ decides whether it's investable or "
           "merely true."),
        md("## 3 · How we'd know — the protocol\n\nScore by same-month history → long-short → Lo t-stat → "
           "the other-month control → decade split → cost sweep and break-even."),
        md("## 4 · The teardown"),
        md("### 4.1 The effect and the control"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'same-month':st.stats(same),'control (other months)':st.stats(ctrl)}).T[['mean_ann','sharpe','tstat','hit_rate','n']].round(3))"),
        md("> 💡 *In plain words:* +7.3%/yr at t 4.1 for the same month; the control is negative. "
           "**H₁ and H₂ hold** — real, and specifically seasonal."),
        md("### 4.2 No decay"),
        code("for lab,sl in [('1999-2012',same.loc[:'2012']),('2013-on',same.loc['2013':])]:\n"
             "    print(f'{lab}: Sharpe {st.stats(sl)[\"sharpe\"]:+.2f}, mean {st.stats(sl)[\"mean_ann\"]:+.2%}/yr')"),
        md("> 💡 *In plain words:* identical across halves — the hallmark of a real effect, not a mined one."),
        md("### 4.3 The cost sweep — what survives turnover"),
        code("rows={'gross':st.stats(same)['sharpe']}\n"
             "for c in (5,10,20,30): rows[f'{c}bp']=st.stats(st.net_of_cost(same,c))['sharpe']\n"
             "import pandas as pd; display(pd.Series(rows, name='net Sharpe').round(3))\n"
             "print(f'break-even ≈ {st.breakeven_cost_bps(same):.0f} bp/trade')"),
        md("> 💡 *In plain words:* clears realistic large-cap costs (net 0.59 at 10 bp, break-even 38 bp) "
           "— but the sweep ignores short-borrow, full monthly turnover and the survivorship flatter. "
           "**H₃ partially holds → Fragile.**"),
        md("## 5 · The verdict\n\nH₁/H₂ hold, H₃ partial → Signal `REAL`, seasonality `CONFIRMED`, "
           "Tradability `FRAGILE`."),
        md("## 6 · Could you trade it?\n\nPlausibly, as a market-neutral overlay — but the practical drag "
           "(short borrow, monthly turnover, capacity) and the survivorship flatter mean the realised net "
           "is uncertain. It's the rare *real* one here; the honest caveat is the implementation, not the signal."),
        md("## 7 · Going further\n\nForks: (a) a point-in-time / small-cap universe (the effect is "
           "stronger but less tradable); (b) the seasonal *factor* (Keloharju-Linnainmaa-Nyberg 2016) vs "
           "stock-level; (c) a long-only tilt to drop the short book. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
