"""Build the two narrative notebooks for Study 48 (Groundhog).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/groundhog_panel.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (groundhog/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from groundhog import data, strategy as st
# Opt-in, stated: current S&P 500 members + a >=20y-history filter = a twice-survivor panel.
# Magnitudes below are upper bounds; the same-month-vs-other-month control shares the bias.
ret = data.fetch_panel(allow_survivorship_bias=True)   # cache-first; built by examples/verify.py --fetch
same = st.seasonal_hedge(ret, same_month=True)
ctrl = st.seasonal_hedge(ret, same_month=False)
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Genuinely same-month seasonal?: Confirmed](https://img.shields.io/badge/Genuinely_same--month_seasonal%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Groundhog 🔁\n### Do stocks have 'favourite months'? Absurd — and it's real\n\n"
           + VERDICT +
           "Here's a claim that sounds like astrology: a stock tends to repeat its **calendar-month** "
           "performance — a name that's done well in past Marches keeps doing well in Marches. It should "
           "be nonsense. Instead it's the most robust effect on this bench: significant, specific to the "
           "same month, and it hasn't faded in 26 years. One honesty flag carried throughout: we measure "
           "it on **today's S&P 500 survivors**, which inflates the size of the win — the *existence* "
           "rests on a control that shares that bias (and on the original study's bias-free data).\n\n"
           "> 📓 **Plain-language layer.** The control, the t-stat and the cost sweep are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| You'd assume | The data says |\n|---|---|\n"
           "| \"Calendar months are noise\" | Long-short on same-month history: **+7.3%/yr, t = 4.1** — on a survivor panel, so read the size as an upper bound. |\n"
           "| \"It's just momentum\" | Ranking on *other* months earns **−3.3%/yr** — it's the same month, specifically (and this control shares the panel's bias). |\n"
           "| \"Surely it's decayed\" | Sharpe **0.81** in both halves of the sample. |\n"
           "| \"Then it's free money\" | Counted one-way, break-even is **~19 bp/trade** — thin. |"),
        md("## 1 · The claim\n\nHeston & Sadka (2008): a stock's average return in a given calendar month "
           "predicts its return in that same month in future years. Rank by same-month history, long the "
           "winners, short the losers — a pure cross-sectional seasonal."),
        md("## 2 · So what?\n\nIf returns carry a stable calendar-month fingerprint, that's a free, "
           "decorrelated source of cross-sectional alpha — and a genuine puzzle for efficient markets. "
           "But 'a stock likes March' is exactly the kind of pattern that screams data-mining, so the "
           "test has to be airtight."),
        md("## 3 · How would we even know?\n\nThe airtight test is a **control**: rank stocks by their "
           "*other*-month history instead of the same month. If only the same month predicts, it's a "
           "real seasonal; if other months predict too, it's just generic persistence. The control does "
           "double duty here: our panel is **today's index members with 20+ years of history** — "
           "survivors — which flatters any long-short you run on it. But the control runs on the *same* "
           "survivors, so the bias cancels out of the *comparison*, even though it doesn't cancel out of "
           "the headline magnitude."),
        code("s, c = st.stats(same), st.stats(ctrl)\n"
             "fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['same-month\\nhistory','other-month\\nhistory (control)'],[s['mean_ann']*100,c['mean_ann']*100],color=['#2ea44f','#8b949e'])\n"
             "ax.set_ylabel('long-short return (%/yr)'); ax.axhline(0,color='k',lw=.8)\n"
             "ax.set_title(f\"It's the SAME month: +{s['mean_ann']*100:.0f}%/yr (t={s['tstat']:.1f}) vs {c['mean_ann']*100:.0f}%/yr control\"); plt.show()"),
        md("## 4 · The teardown\n\nThe same-month book compounds; the control bleeds. And the effect is as "
           "strong in the second half of the sample as the first."),
        code("eq=(1+same).cumprod(); eqc=(1+ctrl).cumprod()\n"
             "ax=eq.plot(label='same-month seasonality',lw=1.8); eqc.plot(ax=ax,label='control (other months)',lw=1.4,alpha=.8)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1 in the long-short, 2000-2026 (survivor panel)'); ax.legend(); plt.show()\n"
             "for lab,sl in [('2000-2012',same.loc[:'2012']),('2013-on',same.loc['2013':])]:\n"
             "    print(f'{lab}: Sharpe {st.stats(sl)[\"sharpe\"]:+.2f}')"),
        md("**Read it plainly.** The weird thing is true. A stock really does carry a same-month "
           "fingerprint, and it's persisted for a generation — the opposite of the decayed mirages "
           "elsewhere on this bench. Just don't bank the +7.3%/yr literally: a panel made of today's "
           "winners overstates how much any long-short earned."),
        md("## 5 · The verdict\n\n**Signal: Real** — t 4.1, undecayed, same-month-specific; the "
           "*magnitude* is inflated by the survivor panel, the *existence* is what the control (which "
           "shares the bias) and the original CRSP study support. **Tradability: Fragile** — counted "
           "one-way it breaks even at ~19 bp and needs a big short book. **Same-month seasonal?: "
           "Confirmed** — the control fails."),
        md("## 6 · Could you actually trade it?\n\nOnly just — and that's the honest 'fragile'. The book "
           "replaces ~80% of both sides each month, which is ~3.2× your capital in one-way trades: "
           "break-even **~19 bp per trade**, net Sharpe **0.38 at 10 bp**, and shorting ~80 names costs "
           "borrow on top (25–50 bp/yr trims it to ~0.33–0.36) — all on a survivor universe that "
           "flatters the gross. The effect is real; the *net you keep* is thin and uncertain."),
        md("## 7 · Going further 🚪\n\nThe quants notebook has the cost sweep and break-even. Next: "
           "[Study 49 Black-Gold](../../49-black-gold/) — does the price of oil predict the stock market?"),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Groundhog — a quantitative teardown 🔬\n### The same-month vs other-month control · the Lo t-stat · no decay · the cost sweep\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We confirm "
           "return seasonality is real and same-month-specific, then ask what survives turnover.\n\n"
           "> ⚠️ **Not investment advice.** 398 *current* S&P 500 names with ≥20y history (Yahoo), "
           "2000–2026 — a **twice-survivor panel** (current membership × long-history filter; "
           "`fetch_panel` requires an explicit `allow_survivorship_bias=True`). Magnitudes are upper "
           "bounds; the Signal call leans on the bias-sharing control and on Heston-Sadka's CRSP "
           "evidence. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | +7.3%/yr, Sharpe 0.81, Lo t 4.1, no decay — survivor panel, so magnitude inflated; existence backed by the bias-sharing control + CRSP |\n"
           "| Tradability | **Fragile** | one-way break-even ≈19 bp; net Sharpe 0.38 at 10 bp, 0.33–0.36 after borrow |\n"
           "| Same-month seasonal? | **Confirmed** | other-month control earns −3.3%/yr |\n\n"
           "> 💡 *In plain words:* a genuinely strange effect that passes every guard we can run — "
           "measured on a universe of winners, so we trust the *that*, not the *how much*."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** the same-month long-short earns a significant "
           "positive return.\n- **H₂:** it's specific to the same month (the other-month control fails).\n"
           "- **H₃:** it survives realistic costs.\n\n"
           "**Known bias, named up front:** the panel is current S&P 500 membership *and* a ≥20y-history "
           "filter — conditioned on the future twice. H₂'s control shares the bias (it differences out of "
           "the comparison); H₁'s *magnitude* does not get that protection."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, calendar seasonality is a real, "
           "decorrelated alpha and a puzzle for efficient markets. H₃ decides whether it's investable or "
           "merely true."),
        md("## 3 · How we'd know — the protocol\n\nScore by same-month history (trailing **up to** 20 "
           "years, ≥5 same-month obs — the early sample ranks on 5–12 observations) → long-short → Lo "
           "t-stat → the other-month control → decade split → one-way cost sweep, break-even, borrow."),
        md("## 4 · The teardown"),
        md("### 4.1 The effect and the control"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'same-month':st.stats(same),'control (other months)':st.stats(ctrl)}).T[['mean_ann','sharpe','tstat','hit_rate','n']].round(3))"),
        md("> 💡 *In plain words:* +7.3%/yr at t 4.1 for the same month; the control is negative. "
           "**H₁ and H₂ hold** — with the caveat split where it belongs: both arms run on the same "
           "survivor panel, so the *contrast* (H₂) is bias-robust while the *level* (H₁'s +7.3%/yr) is "
           "an upper bound. The vendor lists this strategy at Sharpe **0.340** on a broader, honest "
           "universe — our 0.81 is what a large-cap twice-survivor panel shows, not what you'd have "
           "earned; the truth likely sits nearer 0.34."),
        md("### 4.2 No decay"),
        code("for lab,sl in [('2000-2012',same.loc[:'2012']),('2013-on',same.loc['2013':])]:\n"
             "    print(f'{lab}: Sharpe {st.stats(sl)[\"sharpe\"]:+.2f}, mean {st.stats(sl)[\"mean_ann\"]:+.2%}/yr')"),
        md("> 💡 *In plain words:* identical across halves — the hallmark of a real effect, not a mined "
           "one. (Sample starts 2000-01 after the 60-month warmup on a 1995 panel.)"),
        md("### 4.3 The cost sweep — turnover counted one-way"),
        code("rows={'gross':st.stats(same)['sharpe']}\n"
             "for c in (5,10,20): rows[f'{c}bp']=st.stats(st.net_of_cost(same,c))['sharpe']\n"
             "import pandas as pd; display(pd.Series(rows, name='net Sharpe (one-way bp)').round(3))\n"
             "print(f'break-even ≈ {st.breakeven_cost_bps(same):.0f} bp one-way (3.2x NAV traded/mo)')\n"
             "for b in (25,50):\n"
             "    print(f'10 bp + {b} bp/yr short borrow: net Sharpe {st.stats(st.net_of_borrow(st.net_of_cost(same,10),b))[\"sharpe\"]:+.2f}')"),
        md("> 💡 *In plain words:* replacing ~80% of a two-sided book is ~3.2× NAV of one-way trades a "
           "month, so break-even is **~19 bp one-way** (an earlier draft charged round-trip and said 38). "
           "Net Sharpe is 0.38 at 10 bp and the ~80-name short book's borrow (25–50 bp/yr) trims that to "
           "0.33–0.36. Alive at a few bp; dead by 20. **H₃ barely holds → Fragile.**"),
        md("## 5 · The verdict\n\nH₂ holds outright; H₁ holds on existence (magnitude inflated by the "
           "survivor panel); H₃ barely → Signal `REAL` *with the magnitude caveat*, seasonality "
           "`CONFIRMED`, Tradability `FRAGILE`."),
        md("## 6 · Could you trade it?\n\nOnly as a tightly-costed market-neutral overlay — at "
           "institutional one-way costs (≲5 bp) it keeps a net Sharpe ~0.6 *on this flattered panel*; at "
           "retail costs it's gone, and short borrow, monthly 3.2× turnover and capacity all bite before "
           "that. It's the rare *real* one here; the honest caveats are the panel and the implementation."),
        md("## 7 · Going further\n\nForks: (a) a point-in-time / small-cap universe (the effect is "
           "stronger but less tradable); (b) the seasonal *factor* (Keloharju-Linnainmaa-Nyberg 2016) vs "
           "stock-level; (c) a long-only tilt to drop the short book. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
