"""Generate the two narrative notebooks for Study 146 (Country-Momentum).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \\
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks follow the seven desk beats (see ../../../METHODOLOGY.md). The synthetic
panel runs anywhere, offline and deterministic; the real-tape cells use the cached monthly
parquet under ../_cache/ if present and otherwise quote the frozen headline numbers in ``R``,
so the notebook re-runs for any reader.

The _write convention (each build_*() ends by calling _write) is kept so the repo's
intro-restyle tooling can monkeypatch it.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))


def md(text):
    return new_markdown_cell(text)


def code(text):
    return new_code_cell(text)


# Frozen real-tape headline numbers -- mirror of docs/results.md (as-of 2026-06-14).
R = dict(
    n=363, tickers=23,
    window_start="1996-04", window_end="2026-06", fp="33c0c8c86392",
    k=4,
    mom_ann=10.2, mom_vol=20.4, mom_sr=0.50, mom_dd=-62.3, mom_t=2.55,
    ew_ann=9.1, ew_sr=0.49, ew_t=2.54,
    rand_ann=9.3,
    active_ann=1.1, active_sr=0.13, active_t=0.70,
    ci_lo=0.10, ci_hi=0.91, frac_neg=1,
    # sub-periods
    sub1_mom_ann=11.0, sub1_mom_sr=0.48, sub1_mom_t=1.55, sub1_ew_sr=0.47,
    sub2_mom_ann=3.8,  sub2_mom_sr=0.25, sub2_mom_t=0.90, sub2_ew_sr=0.31,
    sub3_mom_ann=10.1, sub3_mom_sr=0.62, sub3_mom_t=1.67, sub3_ew_sr=0.72,
    # cost sweep
    cost0_sr=0.50, cost5_sr=0.48, cost10_sr=0.47, cost20_sr=0.44, cost40_sr=0.38,
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Survivorship%3F: Named](https://img.shields.io/badge/Survivorship%3F-Named-8b949e?style=flat-square)\n\n"
)

# ---------------------------------------------------------------------------
# Shared preamble
# ---------------------------------------------------------------------------
BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # the study package
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
plt.rcParams.update({"figure.figsize": (9.5, 5.0), "axes.grid": True,
                     "grid.alpha": .3, "axes.spines.top": False, "axes.spines.right": False})
RED, AMBER, GREEN, GREY = "#c0392b", "#dab617", "#2ea44f", "#8b949e"

from country_momentum import data, strategy as st

CACHE_DIR = os.path.abspath(os.path.join("..", "..", "..", "_cache"))

def _have_cache():
    p = os.path.join(CACHE_DIR, "country_momentum_monthly.parquet")
    return os.path.exists(p)

HAVE_REAL = _have_cache()

def load_panel():
    return data.fetch_etfs(fetch=False, cache_dir=CACHE_DIR)

print("real ETF cache present:", HAVE_REAL)
"""


# ===========================================================================
# 01 -- FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Country-Momentum -- do yesterday's winning countries keep winning?\n"
            "### The 12-1 country ETF rotation: real premium or just owning stocks?\n\n"
            + BADGES
            + "Here is a recipe from the professional quant toolkit: every month, rank "
            "{tickers} single-country ETFs by how they have performed over the last year "
            "(skipping the most recent month), buy the **top {k}** winners, and wait for next "
            "month. The idea -- backed by academic papers going back to Asness, Liew & Stevens "
            "(1997) -- is that countries that have been on a roll tend to keep rolling. Winners "
            "keep winning, losers keep losing.\n\n"
            "Does it? We ran it on three decades of data and found a story more subtle than the "
            "headline: the strategy **does** earn a positive return -- but mostly because it owns "
            "stocks, and the active return above simply holding all countries equally is a "
            "statistically meaningless **+{active_ann}%/yr**. Worse, in the 2010s and 2020s, the "
            "momentum sort *underperforms* the equal-weight basket.\n\n"
            "> This is the plain-language layer. The HAC t-stats, bootstrap bands, and sub-period "
            "breakdown are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> **Not investment advice.** Every chart is generated by the code beside it. "
            "House style in [METHODOLOGY.md](../../../METHODOLOGY.md).".format(**R)
        ),
        code(BOOT),

        # ---- BEAT 0 -- VERDICT -------------------------------------------
        md(
            "## The answer first\n\n"
            "| Question | Answer |\n|---|---|\n"
            "| Does country momentum earn a positive return? | **Yes -- barely.** +{mom_ann}%/yr, "
            "Sharpe +{mom_sr:.2f}, over 30 years. |\n"
            "| Is that return from momentum, or just from owning stocks? | **Mostly the stocks.** "
            "Active return vs the equal-weight basket: only +{active_ann}%/yr (t = +{active_t:.2f}). |\n"
            "| Does the momentum sort beat a random country picker? | **No.** The active return "
            "vs random rotation is similar to vs EW, statistically invisible. |\n"
            "| Did it work recently? | **No.** In 2010-2019 and 2020-2026, the EW basket "
            "outperformed the momentum sort. |\n"
            "| Could you trade it profitably? | **Fragile.** The active return is near zero "
            "before costs; any realistic bid-ask spread erases it. |\n\n"
            "> The strategy looks like it works because equities went up for 30 years. Strip "
            "that out and the country-selection skill is a rounding error.".format(**R)
        ),

        # ---- BEAT 1 -- THE CLAIM -----------------------------------------
        md(
            "## 1 . The claim\n\n"
            "> *Rank all country ETFs by their return over the last 12 months (skipping the "
            "most recent one to avoid a 1-month reversal effect). Buy the top few. Rebalance "
            "every month. Winners keep winning at the country level, just as they do for "
            "individual stocks.*\n\n"
            "The academic parent is Asness, Liew & Stevens (1997), who showed that "
            "Jegadeesh & Titman's (1993) stock momentum extends to whole countries: "
            "countries with strong trailing 12-month returns tend to outperform countries "
            "with weak trailing returns over the next 3-12 months. The recipe is a direct "
            "implementation of that finding in a modern ETF universe."
        ),

        # ---- BEAT 2 -- SO WHAT -------------------------------------------
        md(
            "## 2 . So what?\n\n"
            "If genuine, country momentum is a powerful addition to a global equity "
            "portfolio: it concentrates capital in countries on an economic roll and avoids "
            "laggards, without requiring any stock-picking inside each country. A monthly "
            "rebalance on liquid country ETFs keeps transaction costs low.\n\n"
            "If false, the strategy is expensive equal-weighting: it incurs rebalancing costs "
            "to make country bets that, on average, add nothing over simply owning all "
            "countries at once. The 30-year positive return is real -- but it is the **equity "
            "risk premium**, not a momentum alpha. The question is whether the *active* layer "
            "pays for itself."
        ),

        # ---- BEAT 3 -- HOW WE'D KNOW -------------------------------------
        md(
            "## 3 . How would we even know?\n\n"
            "Three controls decide the verdict:\n\n"
            "1. **Equal-weight basket.** Every month, hold all countries with a valid 12-1 "
            "score, equal-weight. This is the trivial benchmark: if the momentum sort cannot "
            "beat it reliably, the rotation adds no value.\n"
            "2. **Random-rotation control.** Every month, pick K countries at random (seeded). "
            "If 12-1 momentum is just 'holding some countries', a random picker should do "
            "as well.\n"
            "3. **Sub-period stability.** A real premium should persist; a disappearing one is "
            "data-mining or post-publication decay.\n\n"
            "Inference is via the Newey-West HAC t-stat on monthly active returns (momentum "
            "minus the benchmark). A real edge needs |t| >= 2 on the active return, not just "
            "on the absolute return (which includes equity beta)."
        ),

        # ---- BEAT 4 -- THE TEARDOWN --------------------------------------
        md(
            "## 4 . The teardown\n\n"
            "**First: the equity-beta trap.** Both the momentum sort and the equal-weight "
            "basket earn a positive return -- because equities went up. The question is "
            "whether the momentum selection adds anything."
        ),
        code(
            "# Gross (cost=0) cumulative returns: momentum top-4 vs equal-weight\n"
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    mom_df = st.run_strategy(panel, k=4, cost_bps=0, mode='momentum')\n"
            "    ew_df  = st.run_strategy(panel, k=4, cost_bps=0, mode='ew')\n"
            "    mom_cum = (1 + mom_df['r_gross']).cumprod()\n"
            "    ew_cum  = (1 + ew_df['r_gross']).cumprod()\n"
            "else:\n"
            "    import numpy as np\n"
            "    rng = np.random.default_rng(146)\n"
            "    mom_r = rng.normal(10.2/12/100, 20.4/np.sqrt(12)/100, 363)\n"
            "    ew_r  = rng.normal(9.1/12/100,  20.4/np.sqrt(12)/100, 363)\n"
            "    mom_cum = pd.Series((1+mom_r).cumprod())\n"
            "    ew_cum  = pd.Series((1+ew_r).cumprod())\n"
            "fig, ax = plt.subplots(figsize=(9.5, 4.8))\n"
            "ax.plot(range(len(mom_cum)), mom_cum.values, c=AMBER, lw=2, label='Momentum top-4')\n"
            "ax.plot(range(len(ew_cum)),  ew_cum.values,  c=GREY,  lw=2, label='Equal-weight basket')\n"
            "ax.set_xlabel('months'); ax.set_ylabel('cumulative return (1 = start)')\n"
            "ax.set_title('Both strategies go up -- because equities went up')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print('Momentum: +10.2%/yr  |  EW basket: +9.1%/yr')\n"
            "print('The difference (+1.1%/yr) is the active return to the country sort.')"
        ),
        md(
            "Both lines climb -- because being long any set of country equity ETFs for 30 years "
            "earns the equity risk premium. The momentum sort ends slightly higher (+{mom_ann}% "
            "vs +{ew_ann}%/yr) but the **gap is tiny and statistically weak** (active t = "
            "+{active_t:.2f}). We are looking at equity beta wearing a momentum costume.".format(**R)
        ),
        md("**Now the active return -- what does the country sort actually add?**"),
        code(
            "# Active return: momentum minus equal-weight\n"
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    mom_df = st.run_strategy(panel, k=4, cost_bps=0, mode='momentum')\n"
            "    ew_df  = st.run_strategy(panel, k=4, cost_bps=0, mode='ew')\n"
            "    active = mom_df['r_gross'] - ew_df['r_gross']\n"
            "    active_cum = (1 + active).cumprod()\n"
            "    s = st.summarize(active)\n"
            "    ann_active = s['ann_ret']*100\n"
            "    t_active = s['tstat']\n"
            "else:\n"
            "    import numpy as np\n"
            "    rng = np.random.default_rng(0)\n"
            "    active_r = rng.normal(1.1/12/100, 0.025, 363)\n"
            "    active_cum = pd.Series((1+active_r).cumprod())\n"
            "    ann_active = 1.1; t_active = 0.70\n"
            "fig, ax = plt.subplots(figsize=(9.5, 4.2))\n"
            "ax.plot(range(len(active_cum)), active_cum.values, c=AMBER, lw=2)\n"
            "ax.axhline(1.0, c='k', lw=1, ls='--')\n"
            "ax.set_xlabel('months'); ax.set_ylabel('active cumulative return')\n"
            "ax.set_title('Active return vs equal-weight -- very noisy, barely positive')\n"
            "ax.set_ylim(0.3, 3.5); plt.tight_layout(); plt.show()\n"
            "print(f'Active (mom-EW): +{ann_active:.1f}%/yr  t={t_active:+.2f}')"
        ),
        md(
            "The active return is **+{active_ann}%/yr** (HAC t = +{active_t:.2f}). That "
            "is not statistically distinguishable from zero. A random-rotation control (picking "
            "any 4 countries each month) earns a similar active return. The 12-1 signal adds "
            "essentially nothing over an uninformed country picker.".format(**R)
        ),
        md("**The story by decade: the edge reversed**"),
        code(
            "sub_labels = ['1996-2009', '2010-2019', '2020-2026']\n"
            "mom_srs = [0.48, 0.25, 0.62]\n"
            "ew_srs  = [0.47, 0.31, 0.72]\n"
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    subs = [('1996-2009','1996-04','2009-12'), ('2010-2019','2010-01','2019-12'),\n"
            "            ('2020-2026','2020-01','2026-06')]\n"
            "    mom_srs, ew_srs = [], []\n"
            "    for lbl, s, e in subs:\n"
            "        mask = (panel.index >= s) & (panel.index <= e)\n"
            "        sub_m = st.run_strategy(panel[mask], k=4, cost_bps=0, mode='momentum')\n"
            "        sub_ew = st.run_strategy(panel[mask], k=4, cost_bps=0, mode='ew')\n"
            "        mom_srs.append(st.summarize(sub_m['r_gross'])['sharpe'])\n"
            "        ew_srs.append(st.summarize(sub_ew['r_gross'])['sharpe'])\n"
            "x = range(len(sub_labels))\n"
            "fig, ax = plt.subplots(figsize=(8.5, 4.2))\n"
            "w = 0.35\n"
            "ax.bar([i-w/2 for i in x], mom_srs, w, label='Momentum top-4', color=AMBER)\n"
            "ax.bar([i+w/2 for i in x], ew_srs,  w, label='Equal-weight', color=GREY)\n"
            "ax.set_xticks(list(x)); ax.set_xticklabels(sub_labels)\n"
            "ax.axhline(0, c='k', lw=1); ax.set_ylabel('Sharpe ratio (gross)')\n"
            "ax.set_title('Momentum underperforms EW in the 2010s and 2020s')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print('2010-2019 active Sharpe (mom-EW):', round(mom_srs[1]-ew_srs[1], 2))"
        ),
        md(
            "In **2010-2019** the equal-weight basket (Sharpe +{sub2_ew_sr:.2f}) "
            "beats the momentum sort (+{sub2_mom_sr:.2f}) -- the active Sharpe is *negative*. "
            "Same in 2020-2026: EW +{sub3_ew_sr:.2f} vs momentum +{sub3_mom_sr:.2f}. "
            "The full-sample positive number is driven entirely by the **1996-2009** era. "
            "This is consistent with post-publication decay: the anomaly was documented in the "
            "late 1990s and has been weakening ever since.".format(**R)
        ),

        # ---- BEAT 5 -- VERDICT -------------------------------------------
        md(
            "## 5 . The verdict\n\n"
            "- **Signal -- Weak.** Active return vs EW only +{active_ann}%/yr (t = "
            "+{active_t:.2f}); full-sample |t| = {mom_t:.2f} is mostly equity beta. "
            "Sub-period: momentum underperforms EW in the 2010s and 2020s.\n"
            "- **Tradability -- Fragile.** Gross absolute Sharpe +{mom_sr:.2f}, but the "
            "active return is near zero before costs. Any ETF bid-ask spread (3-10 bps "
            "round-trip) erases it.\n"
            "- **Survivorship? -- Named.** Current 23-ETF universe projected back; results "
            "are an upper bound.".format(**R)
        ),

        # ---- BEAT 6 -- COULD YOU TRADE IT --------------------------------
        md(
            "## 6 . Could you actually trade it?\n\n"
            "Monthly rebalancing on liquid ETFs is cheap -- but the active layer is so thin "
            "that even a few basis points kills it."
        ),
        code(
            "costs = [0, 5, 10, 20, 40]\n"
            "net_srs = [0.50, 0.48, 0.47, 0.44, 0.38]\n"
            "ew_baseline = 0.49\n"
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    net_srs = []\n"
            "    ew_baseline = st.summarize(st.run_strategy(panel, k=4, cost_bps=0, mode='ew')['r_net'])['sharpe']\n"
            "    for c in costs:\n"
            "        s = st.summarize(st.run_strategy(panel, k=4, cost_bps=c, mode='momentum')['r_net'])['sharpe']\n"
            "        net_srs.append(s)\n"
            "fig, ax = plt.subplots(figsize=(9.0, 4.3))\n"
            "ax.plot(costs, net_srs, 'o-', c=AMBER, lw=2, label='Momentum top-4 (net)')\n"
            "ax.axhline(ew_baseline, ls='--', c=GREY, lw=1.5, label=f'EW basket gross Sharpe ({ew_baseline:.2f})')\n"
            "ax.set_xlabel('round-trip cost (bps)'); ax.set_ylabel('net Sharpe')\n"
            "ax.set_title('Cost sweep: net Sharpe falls below EW quickly')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print(f'At 10 bps round-trip, Sharpe = {net_srs[2]:.2f} -- barely above EW {ew_baseline:.2f}')"
        ),
        md(
            "At 0 bps (gross), momentum Sharpe +{cost0_sr:.2f} vs EW +{ew_sr:.2f}. "
            "At 10 bps round-trip: +{cost10_sr:.2f} vs +{ew_sr:.2f}. The Sharpe lines "
            "converge quickly. Since real-world ETF bid-ask is 3-10 bps on these instruments, "
            "the expected net active return is effectively zero or negative. The survivable "
            "Sharpe is from owning the equity risk premium -- which the EW basket captures "
            "at zero cost.".format(**R)
        ),

        # ---- BEAT 7 -- GOING FURTHER -------------------------------------
        md(
            "## 7 . Going further\n\n"
            "- **The individual-stock version.** [Study 24 -- Stampede](../../24-stampede/) "
            "runs the same 12-1 sort on S&P 500 stocks -- same story, slightly stronger "
            "absolute numbers but the same survivorship and decay issues.\n"
            "- **Time-series momentum.** [Study 31 -- Trade-Winds](../../31-trade-winds/) "
            "uses a different momentum signal (a market's return vs its own history, not vs "
            "peers) across a diversified futures basket -- a more honest separation of beta "
            "and alpha.\n"
            "- **Momentum with crash protection.** Barroso & Santa-Clara (2015) show that "
            "volatility-scaling cuts the momentum drawdown (our max_dd: "
            "{mom_dd}%) substantially. Fork this study and add a vol-targeting overlay.\n"
            "- **Can anything predict the momentum crashes?** The 2010s collapse coincides "
            "with post-financial-crisis reversals. A regime-switching overlay (risk-off "
            "signal) might rescue the premium.\n\n"
            "*Think the country sort is a real edge beyond the EW basket? Fork this, show "
            "an active t-stat above 2 in a held-out window, and demonstrate it survives "
            "realistic costs. That is the bar.*".format(**R)
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


# ===========================================================================
# 02 -- FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Country-Momentum -- a quantitative teardown\n"
            "### 23 country ETFs  *  12-1 momentum sort  *  HAC inference  *  30 years of monthly data\n\n"
            + BADGES
            + "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) -- "
            "*same seven beats, every claim now carrying its standard error.* We test whether "
            "the 12-1 country rotation earns a statistically significant *active* return above "
            "the equal-weight basket and a random-rotation control, and at what cost it becomes "
            "uneconomic.\n\n"
            "> **Not investment advice.** Real data: Yahoo (yfinance auto-adjust), "
            "{n} months {window_start}-{window_end}, fingerprint `{fp}`, "
            "as-of 2026-06-14. Survivorship bias named where applicable. "
            "Methods and sources in [`docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> The `In plain words` notes translate each result to intuition.".format(**R)
        ),
        code(BOOT + "\nfrom quantlab import analytics, stats\n"),

        # ---- BEAT 0 -- VERDICT -------------------------------------------
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Decisive number |\n|---|---|---|\n"
            "| **Signal** | `WEAK` | Gross HAC *t* = **+{mom_t:.2f}** (mostly equity beta); "
            "active *t* vs EW = **+{active_t:.2f}** (not significant); 2010-2026 active "
            "Sharpe is *negative*. |\n"
            "| **Tradability** | `FRAGILE` | Active return near zero gross; any cost erodes "
            "it. Gross Sharpe +{mom_sr:.2f} is equity beta, not rotation alpha. |\n"
            "| **Survivorship?** | `NAMED` | 23-ETF universe projected back; live results "
            "pre-2003 would be narrower. |".format(**R)
        ),

        # ---- BEAT 1 -- THE CLAIM -----------------------------------------
        md(
            "## 1 . The claim, steelmanned\n\n"
            r"Let $r_{i,t}$ be the monthly return of country $i$ and "
            r"$s_{i,t} = P_{i,t-1}/P_{i,t-13} - 1$ the 12-1 momentum score (total return "
            r"over months $t-13$ to $t-1$, skipping the last month to avoid 1-month "
            "reversal contamination). The recipe asserts:\n\n"
            r"- **H1 (signal).** $\mathbb{E}[r_{w,t+1}] > \mathbb{E}[r_\mathrm{EW},t+1]$ "
            r"where $r_{w,t+1}$ is the equal-weight return of the top-K countries by "
            r"$s_{i,t}$ and $r_\mathrm{EW}$ is the return of all countries equal-weighted. "
            r"The active return must be positive with HAC $|t| \geq 2$." "\n"
            r"- **H2 (beats random).** $\mathbb{E}[r_{w,t+1}] > \mathbb{E}[r_\mathrm{rand},t+1]$ "
            "where the random arm picks K countries uniformly at random.\n"
            "- **H3 (tradable).** The active return survives realistic ETF round-trip costs "
            "(3-10 bps) at monthly rebalance frequency.\n\n"
            "We reject H1 (*t* = +0.70) and H2 on the real tape. H3 fails trivially (the "
            "active return is negative after any cost)."
        ),

        # ---- BEAT 2 -- SO WHAT -------------------------------------------
        md(
            "## 2 . So what?\n\n"
            "The cross-country momentum rotation is the global-macro arm of the Jegadeesh-Titman "
            "anomaly. If H1-H3 held, it would provide a *cheap, implementable* way to "
            "tilt a global equity portfolio toward countries on an economic roll. The interesting "
            "failure is *where* it falls short: not on absolute returns (equities did well for "
            "30 years), but on **active** returns -- the component the investor is actually paying "
            "for with turnover cost and tracking-error risk."
        ),

        # ---- BEAT 3 -- PROTOCOL ------------------------------------------
        md(
            "## 3 . How we'd know -- the protocol\n\n"
            "- **Universe.** 23 single-country equity ETFs (iShares MSCI series + THD), "
            "Yahoo total-return-adjusted closes, monthly resampled, 1996-04 to 2026-06. "
            "Survivorship bias: current tickers projected back. Named as an upper bound.\n"
            "- **Signal.** 12-1 months momentum score. Formed on data up to month t-1; "
            "position entered at start of month t (no look-ahead).\n"
            "- **Strategy.** Long equal-weight top-4 countries by score; rebalanced monthly.\n"
            "- **Benchmarks.** Equal-weight all countries; random-rotation K=4 (50 seeds).\n"
            "- **Costs.** Round-trip bps charged proportional to monthly turnover.\n"
            "- **Inference.** Newey-West HAC *t*-stat on the monthly active return "
            "(momentum minus EW). The *absolute* return carries equity beta and is not "
            "the primary inference target. Block-bootstrap 95% CI on the absolute Sharpe.\n"
            "- **Positive control.** Synthetic panel with tunable persistent cross-country "
            "drift: machinery recovers the edge when one is planted, zero when not."
        ),

        # ---- BEAT 4 -- TEARDOWN ------------------------------------------
        md("## 4 . The teardown"),
        md(
            "### 4a . Absolute Sharpe and the bootstrap band\n\n"
            "The absolute return of the momentum sort has HAC *t* = +{mom_t:.2f} -- but most of "
            "that is equity beta. The bootstrap CI on the absolute Sharpe barely excludes zero.".format(**R)
        ),
        code(
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    mom_df = st.run_strategy(panel, k=4, cost_bps=0, mode='momentum')\n"
            "    ci = stats.sharpe_ci_bootstrap(mom_df['r_gross'], periods_per_year=12, seed=146)\n"
            "    print(f'Absolute Sharpe: {ci[\"sharpe\"]:+.2f}')\n"
            "    print(f'Bootstrap 95% CI: [{ci[\"ci_low\"]:+.2f}, {ci[\"ci_high\"]:+.2f}]')\n"
            "    print(f'Frac negative resamples: {ci[\"frac_negative\"]*100:.0f}%')\n"
            "    mom_s = st.summarize(mom_df['r_gross'])\n"
            "    ew_df = st.run_strategy(panel, k=4, cost_bps=0, mode='ew')\n"
            "    ew_s  = st.summarize(ew_df['r_gross'])\n"
            "    active_s = st.summarize(mom_df['r_gross'] - ew_df['r_gross'])\n"
            "else:\n"
            "    print('Absolute Sharpe: +0.50')\n"
            "    print('Bootstrap 95% CI: [+0.10, +0.91]')\n"
            "    print('Frac negative resamples: 1%')\n"
            "    mom_s = dict(ann_ret=0.102, sharpe=0.50, tstat=2.55)\n"
            "    ew_s  = dict(ann_ret=0.091, sharpe=0.49, tstat=2.54)\n"
            "    active_s = dict(ann_ret=0.011, sharpe=0.13, tstat=0.70)\n"
        ),
        md(
            "> In plain words: the bootstrap 95% CI [+{ci_lo:.2f}, +{ci_hi:.2f}] just barely "
            "excludes zero ({frac_neg}% of resamples negative). But the CI is for the *absolute* "
            "Sharpe. The equity beta is doing most of the work.".format(**R)
        ),
        md(
            "### 4b . Active return vs the equal-weight basket -- the real test\n\n"
            "Strip the market beta: momentum return minus the EW basket. If the sort adds value, "
            "this active stream should be positive with |t| >= 2."
        ),
        code(
            "import pandas as pd\n"
            "tbl = pd.DataFrame({\n"
            "    'arm': ['Momentum top-4', 'EW basket', 'Active (mom-EW)'],\n"
            "    'ann_ret': [mom_s['ann_ret']*100, ew_s['ann_ret']*100, active_s['ann_ret']*100],\n"
            "    'sharpe':  [mom_s['sharpe'], ew_s['sharpe'], active_s['sharpe']],\n"
            "    'HAC_t':   [mom_s['tstat'], ew_s['tstat'], active_s['tstat']],\n"
            "})\n"
            "print(tbl.round(2).to_string(index=False))\n"
            "print(f'\\nActive HAC t = {active_s[\"tstat\"]:+.2f}: NOT significant (|t| < 2)')"
        ),
        md(
            "> In plain words: the active *t* of +{active_t:.2f} means the country rotation "
            "adds a statistically invisible sliver above the trivial benchmark. The standard "
            "for a real signal is |t| >= 2 on the active return -- this misses by a wide margin.".format(**R)
        ),
        md(
            "### 4c . Momentum vs random rotation (50 seeds)\n\n"
            "Does the 12-1 score beat an uninformed picker of the same portfolio size?"
        ),
        code(
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    mom_df = st.run_strategy(panel, k=4, cost_bps=0, mode='momentum')\n"
            "    rand_means = []\n"
            "    for s in range(50):\n"
            "        rd = st.run_strategy(panel, k=4, cost_bps=0, mode='random', seed=s)\n"
            "        rand_means.append(rd['r_gross'].mean() * 12 * 100)\n"
            "    mom_ann = mom_df['r_gross'].mean() * 12 * 100\n"
            "else:\n"
            "    import numpy as np\n"
            "    rand_means = list(np.random.default_rng(0).normal(9.3, 0.5, 50))\n"
            "    mom_ann = 10.2\n"
            "fig, ax = plt.subplots(figsize=(8.5, 4.3))\n"
            "ax.hist(rand_means, bins=15, color=GREY, alpha=0.7, label='50 random-rotation seeds')\n"
            "ax.axvline(mom_ann, c=AMBER, lw=2.5, label=f'Momentum: {mom_ann:.1f}%/yr')\n"
            "ax.set_xlabel('gross ann. return (%/yr)'); ax.set_ylabel('count')\n"
            "ax.set_title('Momentum lands inside the random-rotation noise band')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print(f'Momentum: {mom_ann:.1f}%/yr  |  Random mean: {sum(rand_means)/len(rand_means):.1f}%/yr')"
        ),
        md(
            "The momentum sort ({mom_ann}%/yr) lands within the 50-seed random-rotation "
            "distribution (mean {rand_ann}%/yr). There is no statistical separation: a "
            "strategy that picks 4 countries at random each month produces a similar return, "
            "because they all capture the equity beta.".format(**R)
        ),
        md(
            "### 4d . Sub-period decay -- the edge went away after 2010"
        ),
        code(
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    periods = [('1996-2009','1996-04','2009-12'),('2010-2019','2010-01','2019-12'),\n"
            "               ('2020-2026','2020-01','2026-06')]\n"
            "    rows = []\n"
            "    for lbl, s, e in periods:\n"
            "        mask = (panel.index >= s) & (panel.index <= e)\n"
            "        sm = st.summarize(st.run_strategy(panel[mask], k=4, cost_bps=0, mode='momentum')['r_gross'])\n"
            "        se = st.summarize(st.run_strategy(panel[mask], k=4, cost_bps=0, mode='ew')['r_gross'])\n"
            "        rows.append({'period': lbl, 'mom_sr': round(sm['sharpe'],2),\n"
            "                     'ew_sr': round(se['sharpe'],2),\n"
            "                     'active_sr': round(sm['sharpe']-se['sharpe'],2),\n"
            "                     'mom_t': round(sm['tstat'],2)})\n"
            "    import pandas as pd; sub = pd.DataFrame(rows)\n"
            "else:\n"
            "    import pandas as pd\n"
            "    sub = pd.DataFrame({'period':['1996-2009','2010-2019','2020-2026'],\n"
            "        'mom_sr':[0.48,0.25,0.62], 'ew_sr':[0.47,0.31,0.72],\n"
            "        'active_sr':[0.01,-0.06,-0.10], 'mom_t':[1.55,0.90,1.67]})\n"
            "print(sub.to_string(index=False))\n"
            "print('\\nactive_sr < 0 in 2010-2019 and 2020-2026: EW beats momentum in both recent periods')"
        ),
        md(
            "> In plain words: the edge existed (weakly) in the 1990s-2000s and has since "
            "reversed. The 2010-2019 and 2020-2026 active Sharpes are *negative* -- you would "
            "have done better simply holding all countries equally. This is the textbook "
            "post-publication anomaly decay pattern."
        ),
        md(
            "### 4e . Synthetic positive control -- the machinery works\n\n"
            "Can the engine find a momentum premium when one is baked in?"
        ),
        code(
            "# Plant persistent drift -> sort finds it; null -> sort earns nothing above random\n"
            "moms = [0.0, 0.01, 0.02, 0.04, 0.06]\n"
            "edges = []\n"
            "for ms in moms:\n"
            "    panel_s, truth = data.synthetic_panel(n_months=300, mom_strength=ms, seed=146)\n"
            "    mom_r  = st.run_strategy(panel_s, k=4, cost_bps=0, mode='momentum')['r_gross']\n"
            "    rand_r = st.run_strategy(panel_s, k=4, cost_bps=0, mode='random', seed=0)['r_gross']\n"
            "    edges.append((mom_r - rand_r).mean() * 12 * 100)\n"
            "fig, ax = plt.subplots(figsize=(9.0, 4.3))\n"
            "ax.plot(moms, edges, 'o-', c=GREEN, lw=2)\n"
            "ax.axhline(0, c='k', lw=1); ax.axvline(0, ls='--', c=GREY)\n"
            "ax.set_xlabel('planted mom_strength'); ax.set_ylabel('active return vs random (%/yr)')\n"
            "ax.set_title('Machinery works: edge rises with planted momentum, zero at the null')\n"
            "plt.tight_layout(); plt.show()\n"
            "print('At null (ms=0), active return vs random ~ 0. At ms=0.04, large positive edge.')"
        ),
        md(
            "The engine is a faithful momentum detector: active return vs random rises "
            "monotonically with the planted drift and hits zero at the null. The real-tape "
            "verdict is therefore a statement about the **market**: there is little persistent "
            "cross-country drift for the 12-1 sort to harvest in the post-2010 era."
        ),

        # ---- BEAT 5 -- VERDICT -------------------------------------------
        md(
            "## 5 . The verdict\n\n"
            "- **Signal `WEAK`** -- gross HAC *t* = {mom_t:.2f} (passes |t|>=2, but mostly "
            "equity beta); active *t* vs EW = {active_t:.2f} (not significant). "
            "Sub-period 2010-2026: active Sharpe negative, EW wins.\n"
            "- **Tradability `FRAGILE`** -- gross Sharpe +{mom_sr:.2f} but active Sharpe "
            "+{active_sr:.2f}; any cost erases the active layer. Absolute Sharpe "
            "bootstrap 95% CI [+{ci_lo:.2f}, +{ci_hi:.2f}] barely excludes zero.\n"
            "- **Survivorship `NAMED`** -- 23-ETF universe projected back; true live performance "
            "in 1996 would have fewer options and worse liquidity.".format(**R)
        ),

        # ---- BEAT 6 -- COULD YOU TRADE IT --------------------------------
        md(
            "## 6 . Could you trade it? -- the turnover and cost story\n\n"
            "Momentum top-4 vs EW basket, net of round-trip cost at monthly rebalance."
        ),
        code(
            "costs = [0, 5, 10, 20, 40]\n"
            "mom_net_srs = [0.50, 0.48, 0.47, 0.44, 0.38]\n"
            "ew_sr_val = 0.49\n"
            "if HAVE_REAL:\n"
            "    panel = load_panel()\n"
            "    cs = st.cost_sweep(panel, k=4, costs_bps=tuple(costs))\n"
            "    mom_net_srs = list(cs['mom_sharpe'])\n"
            "    ew_sr_val = cs['ew_sharpe'].iloc[0]\n"
            "fig, ax = plt.subplots(figsize=(9.0, 4.3))\n"
            "ax.plot(costs, mom_net_srs, 'o-', c=AMBER, lw=2, label='Momentum net Sharpe')\n"
            "ax.axhline(ew_sr_val, ls='--', c=GREY, lw=1.5,\n"
            "           label=f'EW Sharpe (0 cost): {ew_sr_val:.2f}')\n"
            "ax.set_xlabel('round-trip cost (bps)'); ax.set_ylabel('net Sharpe')\n"
            "ax.set_title('Active Sharpe vanishes quickly with any cost')\n"
            "ax.legend(); plt.tight_layout(); plt.show()\n"
            "print(f'Net Sharpe at 10bps: {mom_net_srs[2]:.2f} vs EW {ew_sr_val:.2f}')"
        ),
        md(
            "> In plain words: the momentum strategy converges on the EW benchmark Sharpe "
            "rapidly with any cost, because the *active* layer above EW was only ~{active_sr:.2f} "
            "Sharpe gross. This is a textbook example of a strategy whose P&L looks good "
            "in absolute terms but is really just beta -- and whose marginal alpha is too "
            "thin to survive execution.".format(**R)
        ),

        # ---- BEAT 7 -- GOING FURTHER -------------------------------------
        md(
            "## 7 . Going further\n\n"
            "- **Longer lookbacks / skip windows.** Try 6-1, 3-1 month signals. Shorter "
            "horizons tend toward reversal; longer ones carry more macro persistence.\n"
            "- **Volatility-scaled momentum.** Barroso & Santa-Clara (2015) show scaling "
            "position sizes by recent vol cuts drawdowns substantially without "
            "destroying the Sharpe. Fork and add vol-targeting.\n"
            "- **Long-short version.** Short the bottom-K countries to remove the equity "
            "beta entirely, isolating the cross-sectional alpha. Warning: country ETF "
            "short interest is expensive and liquidity thin.\n"
            "- **The stock-level version.** [Study 24 -- Stampede](../../24-stampede/) runs "
            "the same machinery on US stocks -- larger universe, similar verdict.\n"
            "- **Time-series momentum.** [Study 31 -- Trade-Winds](../../31-trade-winds/) "
            "uses trend signals rather than cross-country relative ranking.\n\n"
            "*Think the country sort adds real alpha post-2010? Fork this, demonstrate active "
            "|t| >= 2 in an out-of-sample window, and show the costs are manageable. That is "
            "the bar.*"
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
