"""Build the two narrative notebooks for Study 102 (Free-Rebalance).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``free_rebalance`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=6007, start="2002-07-30", end="2026-06-12",
    fp_spy="2c834b0b5249", fp_tlt="a9b98e52a010", fp_basket="e9e0c3c36702",
    a_cagr=8.22, a_vol=9.6, a_sharpe=0.875, a_dd=-28.9, a_reb=25,
    q_cagr=8.22, q_vol=9.7, q_sharpe=0.861, q_dd=-29.0, q_reb=96,
    d_cagr=8.82, d_vol=10.3, d_sharpe=0.874, d_dd=-26.9,
    bonus_a=-0.59, bonus_q=-0.60,
    dr=0.90, var_red=1.81,
    hac_t=-1.19, ci_lo=-0.660, ci_hi=0.132,
    sub_early=1.27, sub_late=-1.74,
    spine_mr=0.77, spine_tr=-3.90,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (free_rebalance/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from free_rebalance import data, strategy

AS_OF = "2026-06-12"
frame = data.load_real(("SPY", "TLT"), mode="total_return").loc[:AS_OF]
annual    = strategy.run_portfolio(frame, freq="annual",    cost_bps=10.0)
quarterly = strategy.run_portfolio(frame, freq="quarterly", cost_bps=10.0)
drift     = strategy.run_portfolio(frame, freq="drift",     cost_bps=10.0)
bonus_a = annual['cagr'] - drift['cagr']
print(f"basket SPY/TLT total return: {len(frame):,} rows  {frame.index[0].date()} -> {frame.index[-1].date()}  fp={data.fingerprint(frame)}")
print(f"rebalanced(A) CAGR {annual['cagr']*100:.2f}%  vol {annual['vol']*100:.1f}%  Sharpe {annual['sharpe']:.3f}")
print(f"drift (B&H)   CAGR {drift['cagr']*100:.2f}%  vol {drift['vol']*100:.1f}%  Sharpe {drift['sharpe']:.3f}")
print(f"realised rebalancing bonus (annual) = {bonus_a*100:+.2f} pts/yr CAGR")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Controls risk?: Confirmed](https://img.shields.io/badge/Controls_risk%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# The Rebalancing Bonus ♻️\n"
            "### Is rebalancing really a *free lunch* that adds return on top of the risk control?\n\n"
            + HERO_BADGES +
            "You'll hear it everywhere: rebalancing your portfolio back to its target weights "
            "*pays you* — a **rebalancing bonus**, *volatility harvesting*, *Shannon's Demon*. "
            "Sell high, buy low, automatically, forever. We take a plain 50/50 stocks/bonds book "
            "(SPY + long Treasuries, dividends included), rebalance it, and ask the only two "
            "questions that matter: does it **add return** (no), and does it **control risk** (yes).\n\n"
            "> \U0001f4d3 **This is the plain-language layer.** The variance identity, the *t*-stats and "
            "the bootstrap are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, "
            "deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below "
            "is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first \U0001f3af\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Does rebalancing add return vs just holding the basket? | **No** — the rebalanced book "
            f"earned **{R['a_cagr']}%/yr** vs **{R['d_cagr']}%/yr** for drift, about "
            f"**{abs(R['bonus_a']):.1f} points/yr *less*** (net of 10 bps/rebalance). |\n"
            f"| Is the risk-adjusted return any better? | **No** — Sharpe **{R['a_sharpe']}** vs "
            f"**{R['d_sharpe']}**, a dead heat. |\n"
            f"| So what *does* rebalancing buy you? | **Risk control** — lower volatility "
            f"({R['a_vol']}% vs {R['d_vol']}%) and a book that stays at its target mix instead of "
            f"drifting stock-heavy. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Rebalancing is a free lunch. By selling whatever went up and buying whatever went "
            "down, you mechanically **harvest volatility** — the **rebalancing bonus** — so you get "
            "*extra return* on top of the risk control. Even Claude Shannon showed two assets can "
            "compound upward this way (*Shannon's Demon*).\"* It's one of the most-repeated ideas in "
            "portfolio construction."
        ),
        md(
            "## 2 · So what?\n\n"
            "If rebalancing reliably *added* return, it would be the rarest thing in finance: a free "
            "lunch with no risk attached. Every investor should crank up the frequency and harvest "
            "away. The stakes are exactly that big — so it deserves a fair, literal test against the "
            "honest alternative: *just holding the basket and never trading.*"
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We build a 50/50 SPY/TLT portfolio (total return) and run it two ways: **rebalanced** "
            "back to 50/50 each year (and each quarter), paying **10 bps** on whatever we trade, vs "
            "**drift** — the same starting weights left completely alone. The *rebalancing bonus* is "
            "simply: rebalanced return minus drift return. If the bonus is positive, the free lunch "
            "is real. If it's zero or negative, it isn't."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the two equity curves — rebalanced vs left to drift."),
        code(
            "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True, height_ratios=[2, 1])\n"
            "ax1.plot(annual['equity'], label=f\"Rebalanced annually (CAGR {annual['cagr']*100:.2f}%)\", lw=1.4)\n"
            "ax1.plot(drift['equity'], label=f\"Drift / buy & hold (CAGR {drift['cagr']*100:.2f}%)\", lw=1.4, alpha=.85)\n"
            "ax1.set_yscale('log'); ax1.set_ylabel('Growth of $1 (log)'); ax1.legend()\n"
            "ax1.set_title('50/50 SPY/TLT total return -- rebalanced vs drift')\n"
            "for d, lab in [(annual, 'rebalanced'), (drift, 'drift')]:\n"
            "    eq = d['equity']; dd = eq/eq.cummax()-1\n"
            "    ax2.plot(dd, label=f\"{lab} (max {dd.min()*100:.0f}%)\", lw=1.1)\n"
            "ax2.set_ylabel('Drawdown'); ax2.legend(); ax2.set_xlabel('')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "Look at the **end point**: the *drift* line finishes **higher**. Over this window the "
            "free lunch cost you money — the rebalanced book trailed by about "
            f"**{abs(R['bonus_a']):.1f} points a year**. Why? Stocks (SPY) ran away from bonds (TLT) "
            "for much of the period, and rebalancing kept *trimming the winner*."
        ),
        md("Now the **bonus by sub-period** — does it flip with the regime?"),
        code(
            "yrs = frame.index.year\n"
            "rows = []\n"
            "for mask, lab in [(yrs <= 2013, '2002-2013'), (yrs >= 2014, '2014-2026')]:\n"
            "    sub = frame.loc[mask]\n"
            "    ra = strategy.run_portfolio(sub, freq='annual', cost_bps=10.0)\n"
            "    rd = strategy.run_portfolio(sub, freq='drift',  cost_bps=10.0)\n"
            "    rows.append((lab, (ra['cagr']-rd['cagr'])*100))\n"
            "labels = [r[0] for r in rows]; vals = [r[1] for r in rows]\n"
            "colors = ['C2' if v>0 else 'C3' for v in vals]\n"
            "plt.bar(labels, vals, color=colors); plt.axhline(0, color='k', lw=.8)\n"
            "plt.ylabel('Rebalancing bonus (CAGR pts/yr)'); plt.title('The bonus flips sign by regime')\n"
            "for i,v in enumerate(vals): plt.text(i, v, f'{v:+.2f}', ha='center', va='bottom' if v>0 else 'top')\n"
            "plt.show()\n"
            "print('bonus by sub-period:', [(l, round(v,2)) for l,v in rows])"
        ),
        md(
            f"There it is: **+{R['sub_early']:.2f} pts/yr** in 2002–13 (a choppy, mean-reverting "
            f"decade where harvesting paid), then **{R['sub_late']:.2f} pts/yr** in 2014–26 (when "
            "stocks trended away and trimming them hurt). The bonus isn't a constant of nature — it's "
            "**regime-dependent**, and it can be negative."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Controls risk? → Confirmed.** Volatility {R['a_vol']}% vs {R['d_vol']}%, and the "
            "weights stay pinned at the target mix instead of drifting stock-heavy. *That* is the "
            "real product.\n"
            f"- **Signal → Weak.** The realised bonus is **{R['bonus_a']:+.2f} pts/yr** and isn't "
            f"statistically distinguishable from zero (it even flips sign by regime).\n"
            f"- **Free lunch / adds return? → Mirage.** Rebalancing earned **{abs(R['bonus_a']):.1f} "
            "pts/yr less** than just holding the basket, and the Sharpe was a wash."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "Sure — SPY and TLT are infinitely liquid and the trades are tiny. The catch isn't "
            "capacity, it's that there's **no return bonus to capture**. What rebalancing gives you "
            "— keeping your risk at the level you chose — is genuinely valuable, but it's *risk "
            "management*, not a money machine. Crank the frequency up to quarterly and you just pay "
            "more in costs for no extra reward."
        ),
        md(
            "## 7 · Going further \U0001f6aa\n\n"
            "- Add **GLD** (from 2004-11) for a 3-asset book — does a third, low-correlation leg "
            "revive the bonus?\n"
            "- **Threshold** rebalancing (only when a weight drifts >5 pts) instead of calendar — "
            "fewer trades, same discipline?\n"
            "- Try **mean-reverting** asset pairs (the synthetic control shows the bonus *is* positive "
            "when assets revert). When does a real pair behave that way? Fork it and test."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# The Rebalancing Bonus — a quantitative teardown \U0001f52c\n"
            "### Real multi-asset total-return tape · Booth-Fama identity · HAC + block-bootstrap · sign controls\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We separate the two things "
            "rebalancing does — **reduce variance** (a real, exact identity) and **add return vs "
            "drift** (not certifiable, regime-dependent) — and show the famous +0.9 pts/yr "
            "\"diversification return\" answers a *different question* than the investor's.\n\n"
            "> ⚠️ **Not investment advice.** SPY + TLT daily, total-return adjusted "
            "(`quantlab.data`, Yahoo); aligned common window from TLT's 2002-07 inception; 10 bps "
            "one-way per rebalance. Sources in [`docs/references.md`](../docs/references.md), "
            "reproducible run in [`docs/results.md`](../docs/results.md).\n>\n"
            "> \U0001f4a1 **The `\U0001f4a1 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `WEAK` | Realised bonus over drift **{R['bonus_a']:+.2f} pts/yr** "
            f"(annual); HAC *t* on the daily bonus = **{R['hac_t']}**, block-bootstrap 95% CI "
            f"**[{R['ci_lo']:+.3f}, {R['ci_hi']:+.3f}] bps/day** straddles 0. Flips sign by regime. |\n"
            f"| **Tradability** | `MIRAGE` | Trails drift by **{abs(R['bonus_a']):.1f} pts/yr** "
            f"({R['a_cagr']}% vs {R['d_cagr']}%); Sharpe a wash ({R['a_sharpe']} vs {R['d_sharpe']}). "
            f"The +{R['dr']} pts/yr Booth-Fama \"bonus\" is vs the weighted-avg of assets, not vs drift. |\n"
            f"| **Controls risk?** | `CONFIRMED` | Vol **{R['a_vol']}%** vs **{R['d_vol']}%**; the book "
            f"stays at target weights instead of drifting. |\n\n"
            "> \U0001f4a1 **In plain words:** rebalancing is a *risk control that works* wearing the "
            "costume of a *return booster that doesn't*."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (variance):** a fixed-weight rebalanced portfolio has lower variance than the "
            "weighted average of its constituents — the Booth-Fama diversification return, "
            "`DR = 0.5(Σ wᵢσᵢ² − σ_p²) ≥ 0`.\n"
            "- **H₂ (the sold claim):** therefore rebalancing *adds return* over **buy-and-hold / "
            "drift** — a free lunch.\n\n"
            "H₁ is an **exact identity** and always holds. H₂ does **not** follow, because the drift "
            "portfolio is a different (and also-diversified) baseline. That gap is the whole study."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₂ held, the optimal policy would be "
           "*rebalance as often as costs allow*. It doesn't — and seeing *why* (the bonus's baseline "
           "isn't your benchmark; trends punish trimming) is the lesson."),
        md("## 3 · How we'd know — the protocol\n\nRebalanced vs drift on the real tape · the exact "
           "Booth-Fama identity · HAC *t* + circular block-bootstrap CI on the **daily bonus** · the "
           "sub-period sign · two synthetic sign controls (mean-revert → +, trend → −)."),
        md("## 4 · The teardown\n\nHeadline stats, all net of 10 bps one-way per rebalance:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [annual['cagr']*100, quarterly['cagr']*100, drift['cagr']*100],\n"
            "  'Vol %':   [annual['vol']*100, quarterly['vol']*100, drift['vol']*100],\n"
            "  'Sharpe':  [annual['sharpe'], quarterly['sharpe'], drift['sharpe']],\n"
            "  'MaxDD %': [annual['max_dd']*100, quarterly['max_dd']*100, drift['max_dd']*100],\n"
            "  'Rebal':   [annual['n_rebal'], quarterly['n_rebal'], drift['n_rebal']],\n"
            "}, index=['Rebalanced (annual)', 'Rebalanced (quarterly)', 'Drift (B&H)'])\n"
            "tbl.round(3)"
        ),
        md("**The Booth-Fama / Willenbrock identity** — the textbook 'bonus', and its real baseline:"),
        code(
            "dr = strategy.diversification_return(frame)\n"
            "print(f\"diversification return DR = 0.5*(wavg_var - var_p) = {dr['dr_annual']*100:+.2f} pts/yr\")\n"
            "print(f\"  weighted-avg variance {dr['wavg_var']*100:.2f}  -  portfolio variance {dr['var_p']*100:.2f}  =  var reduction {dr['var_reduction']*100:.2f} pts\")\n"
            "print(f\"realised bonus vs DRIFT (annual)    = {(annual['cagr']-drift['cagr'])*100:+.2f} pts/yr\")\n"
            "print('=> the identity is >=0 by construction, but its baseline is the weighted-avg of assets,')\n"
            "print('   NOT the drift portfolio -- which is why the honest bonus can be (and is) negative.')"
        ),
        md(
            "> \U0001f4a1 **In plain words:** the +0.9 pts/yr is real — but it's the gap between rebalancing "
            "and an investor who already split the difference between the two assets *every day by "
            "hand*. Nobody does that. The real-world alternative is to **buy and hold**, and against "
            "*that* the bonus vanishes."
        ),
        md("**HAC inference + block-bootstrap CI** on the daily bonus (annual rebalanced − drift):"),
        code(
            "diff = (annual['net'] - drift['net']).to_numpy()\n"
            "t = strategy.hac_tstat(diff)\n"
            "lo, hi = strategy.block_bootstrap_ci(diff, block=63, n_boot=2000)\n"
            "print(f'mean daily bonus = {diff.mean()*1e4:+.3f} bps/day   HAC t = {t:+.2f}')\n"
            "print(f'block-bootstrap 95% CI on mean daily bonus = [{lo*1e4:+.3f}, {hi*1e4:+.3f}] bps/day')\n"
            "print('=> CI straddles 0: the daily bonus is not statistically distinguishable from zero.')"
        ),
        md(
            "> \U0001f4a1 **In plain words:** day to day, rebalanced and drift are the same bet within the "
            "noise. There is no reliably-signed edge to harvest."
        ),
        md("**The bonus by sub-period** — the regime dependence, quantified:"),
        code(
            "yrs = frame.index.year\n"
            "for mask, lab in [(yrs <= 2013, '2002-2013'), (yrs >= 2014, '2014-2026')]:\n"
            "    sub = frame.loc[mask]\n"
            "    ra = strategy.run_portfolio(sub, freq='annual', cost_bps=10.0)\n"
            "    rd = strategy.run_portfolio(sub, freq='drift',  cost_bps=10.0)\n"
            "    print(f'{lab}: realised bonus {(ra[\"cagr\"]-rd[\"cagr\"])*100:+.2f} pts/yr')"
        ),
        md(
            "**The synthetic sign controls** — proof the harness reads the *sign* correctly:"),
        code(
            "for label, (fr, truth) in [('mean-revert (Shannon)', data.synthetic_meanrevert(seed=102)),\n"
            "                           ('one asset trends',      data.synthetic_trend(seed=102))]:\n"
            "    r = strategy.rebalancing_bonus(fr, freq='quarterly', cost_bps=10.0)\n"
            "    exp = '+' if truth['expected_bonus_sign'] > 0 else '-'\n"
            "    got = '+' if r['bonus_cagr'] >= 0 else '-'\n"
            "    print(f\"{label:24s} bonus {r['bonus_cagr']*100:+.2f} pts/yr  (got {got}, expected {exp})  {'OK' if got==exp else 'WRONG'}\")"
        ),
        md(
            "> \U0001f4a1 **In plain words:** plant mean-reversion and the harness banks a positive bonus; "
            "plant a trend and it correctly reports a negative one. So the negative real-tape reading "
            "is a *finding about the regime*, not a broken measurement."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `WEAK` (bonus {R['bonus_a']:+.2f} pts/yr, HAC *t* {R['hac_t']}, CI straddles 0, "
            f"sign flips by regime), Tradability `MIRAGE` for the free-lunch claim "
            f"(−{abs(R['bonus_a']):.1f} pts/yr vs drift, Sharpe a wash), Controls risk? `CONFIRMED` "
            f"(vol {R['a_vol']}% vs {R['d_vol']}%). The +{R['dr']} pts/yr diversification return is a "
            "variance identity vs the wrong baseline, not a bankable edge over buy-and-hold."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (SPY/TLT). The binding fact is economic: there is **no signed "
            "return bonus** to capture over buy-and-hold, and higher rebalancing frequency only "
            "raises costs. The defensible reason to rebalance is **risk discipline** — keeping the "
            "book at its chosen risk level — which is worth doing, but it is not the advertised free "
            "lunch."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Add **GLD** and recompute the bonus on a 3-asset book — more low-correlation legs raise "
            "the Booth-Fama DR, but does the *realised* bonus over drift turn positive?\n"
            "- **Threshold** (tolerance-band) rebalancing vs calendar — trade only on drift, compare "
            "cost-adjusted bonus.\n"
            "- Condition the bonus on a **dispersion/mean-reversion** regime statistic and test the "
            "split formally (the sub-period flip suggests it's predictable in part)."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
