"""Notebook builder for Study 1003 — The 1% Allocation.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The 1% Allocation ₿
### Everyone has a number. Nobody can defend it.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

1%. Or 2%. Or 5%. The recommendations arrive with charts and optimisers and a great deal of
confidence. Here is the awkward part: **feed bitcoin's actual record into an optimiser and it
asks for far more than any of them.** So the published numbers are not what the history says.
This study works out what they *are* saying.

> \U0001F4D3 **This is the plain-language layer.** The bootstrap, the sample-size arithmetic and
> the known-truth control are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Did a bitcoin sleeve help, in hindsight? | Enormously. |
| What weight does the history recommend? | A large double-digit one. |
| So where does "1%" come from? | Not from the history. |
| What does a 2% sleeve assume? | That bitcoin earns roughly nothing. |

> This study set out to show that the data cannot tell 1% from 5%. It found the opposite, and
> the opposite is more interesting: fed bitcoin's actual record, the optimiser recommends far
> **more** than anyone publishes. The published numbers come from overriding the record — which
> is reasonable, and worth saying out loud.
"""
        ),
        md(
            r"""

## 1 · A housekeeping step that is not housekeeping
"""
        ),
        code(
            r"""
from onepercent import data, strategy as st

px = data.load_prices()
rets = st.align_to_equity_calendar(px, data.EQUITY).pct_change()
base = st.sixty_forty(rets, data.EQUITY, data.BONDS)
btc = rets[data.BTC].dropna()
common = base.index.intersection(btc.index)
base, btc = base.loc[common], btc.loc[common]
print(f"as-of {data.AS_OF} | {len(common):,} common sessions from "
      f"{common[0].date()} ({len(common)/252:.1f} years)")
b = st.stats(base)
print(f"the 60/40 alone: {b['cagr']:.2%} a year, {b['vol']:.1%} vol, "
      f"Sharpe {b['sharpe']:.2f}")
"""
        ),
        code(
            r"""
raw = px[data.BTC].dropna().pct_change().dropna()
v252 = raw.std(ddof=1) * np.sqrt(252)
v365 = raw.std(ddof=1) * np.sqrt(365)
print(f"bitcoin volatility, annualised over 252 trading days: {v252:.1%}")
print(f"                    annualised over 365 calendar days: {v365:.1%}")
print(f"difference: {v365/v252 - 1:.0%}")
print()
print("Bitcoin trades every day; SPY does not. Using 365 for one and 252 for the other")
print("makes bitcoin look better on every risk-adjusted measure. Everything here uses")
print("the equity calendar, with weekend moves folded into Monday.")
"""
        ),
        md(
            r"""

## 2 · What a sleeve did
"""
        ),
        code(
            r"""
sw = st.weight_sweep(base, btc, (0.0, 0.01, 0.02, 0.05, 0.10, 0.20, 0.50))
fig, axes = plt.subplots(1, 3, figsize=(14, 4.2))
for ax, col, lbl in zip(axes, ["cagr", "vol", "max_drawdown"],
                         ["annual return", "volatility", "worst drawdown"]):
    ax.bar([f"{w:.0%}" for w in sw.index], sw[col] * 100,
           color="#1f6feb" if col != "max_drawdown" else "#c0392b")
    ax.set_title(lbl, fontsize=10); ax.set_xlabel("bitcoin sleeve")
plt.tight_layout(); plt.show()
sw[["cagr", "vol", "sharpe", "max_drawdown"]].round(4)
"""
        ),
        md(
            r"""

## 3 · Where is the peak?
"""
        ),
        code(
            r"""
curve = st.objective_curve(base, btc, 0.30, n=61)
f = st.flatness(curve, 0.01)
fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(curve.index * 100, curve["value"], lw=2.5, color="#1f6feb")
ax.axvspan(f["plateau_lo"] * 100, f["plateau_hi"] * 100, alpha=0.18, color="#2ea44f",
           label=f"within 1% of the best: {f['plateau_lo']:.1%}-{f['plateau_hi']:.1%}")
ax.axvline(f["best_weight"] * 100, color="#c0392b", lw=2,
           label=f"the 'optimum': {f['best_weight']:.1%}")
for w, lbl in ((1, "1%"), (2, "2%"), (5, "5%"), (10, "10%")):
    ax.annotate(lbl, (w, curve["value"].min()), fontsize=8, ha="center", color="#57606a")
ax.set_xlabel("bitcoin sleeve (%)"); ax.set_ylabel("Sharpe ratio")
ax.legend(fontsize=9)
plt.show()
print(f"the optimiser's answer: {f['best_weight']:.1%}")
print(f"the dotted lines at 1%, 2%, 5% are what allocators actually recommend.")
print("They are nowhere near the peak.")
"""
        ),
        md(
            r"""

The peak is a long way to the right of every number anyone publishes. That gap is the study.
It is not caused by statistical caution — the next two sections show the data pointing firmly
at the large allocation — so it must be caused by something else.
"""
        ),
        md(
            r"""

## 3b · Inverting the question
"""
        ),
        code(
            r"""
imp = st.implied_mean_for_weight(base, btc, (0.01, 0.02, 0.05, 0.10, 0.15))
realised = np.expm1(np.log1p(btc).sum() * 252 / len(btc))
curve = st.weight_vs_assumed_mean(base, btc, np.linspace(-0.25, 0.60, 40))
fig, ax = plt.subplots(figsize=(11, 5.5))
ax.plot(curve.index * 100, curve["optimal_weight"] * 100, lw=2.5, color="#1f6feb")
for w, row in imp.iterrows():
    ax.plot([row["implied_mean"] * 100, row["implied_mean"] * 100], [0, w * 100],
            color="#c0392b", lw=1, ls=":")
    ax.annotate(f"{w:.0%} sleeve <- assume {row['implied_mean']:+.0%}/yr",
                (row["implied_mean"] * 100, w * 100), fontsize=8,
                xytext=(8, -2), textcoords="offset points", color="#c0392b")
ax.axvline(0, color="#8b949e", lw=1.5, ls="--", label="bitcoin earns nothing")
ax.set_xlabel("expected annual return you assume for bitcoin (%)")
ax.set_ylabel("mean-variance optimal sleeve (%)")
ax.legend(fontsize=9)
plt.show()
print(f"bitcoin actually returned {realised:.0%} a year over this sample.")
print(imp.round(4).to_string())
"""
        ),
        md(
            r"""

Read the dashed vertical line. **A 2% bitcoin allocation is the mean-variance answer if you
assume bitcoin's expected return is zero.** A 1% allocation assumes it is *negative*.

That is a perfectly reasonable prior to hold. It is just not a conclusion drawn from the
historical chart printed next to it.
"""
        ),
        md(
            r"""

## 4 · Why the override is defensible: the arithmetic of estimating a mean
"""
        ),
        code(
            r"""
rows = []
for tk, label in ((data.BTC, "bitcoin"), (data.EQUITY, "equities"),
                  (data.GOLD, "gold"), (data.BONDS, "bonds")):
    s = px[tk].dropna().pct_change().dropna()
    vol = s.std(ddof=1) * np.sqrt(252)
    rows.append({"asset": label, "volatility": vol,
                 "years to pin the mean to +/-2pp": st.sample_needed(0, vol, 0.02)
                 ["years_needed"]})
d = pd.DataFrame(rows).set_index("asset")
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.bar(d.index, d["years to pin the mean to +/-2pp"],
       color=["#c0392b", "#1f6feb", "#f0b429", "#2ea44f"])
ax.set_yscale("log"); ax.set_ylabel("years of data needed (log scale)")
plt.show()
print(d.round(1).to_string())
print()
print("The years needed scale with the SQUARE of volatility. Bitcoin is about six times")
print("as volatile as equities, so it needs about thirty-six times the data.")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** This is Merton (1980): the standard error of a mean is
> σ/√T and no amount of higher-frequency sampling helps, because σ scales with √T too. Variances
> can be estimated quickly. Means cannot. Optimisers need means.
"""
        ),
        md(
            r"""

## 5 · A world where we know the answer
"""
        ),
        code(
            r"""
rows = []
for years in (3, 10, 30, 100):
    found = [st.optimal_weight(w["base"], w["asset"], 0.30) for w in
             (st.synthetic_pair(n=int(years * 252), true_weight=0.05, seed=1003 + k)
              for k in range(12))]
    for x in found:
        rows.append({"years": years, "answer": x})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5))
ax.boxplot([d[d["years"] == y]["answer"] * 100 for y in (3, 10, 30, 100)],
           tick_labels=["3 years", "10 years", "30 years", "100 years"])
ax.axhline(5.0, color="#2ea44f", lw=2.5, ls="--", label="the TRUE answer: 5%")
ax.set_ylabel("what the optimiser recommends (%)"); ax.legend(fontsize=9)
ax.set_title("A simulated world where the correct allocation is exactly 5%")
plt.show()
print(d.groupby("years")["answer"].agg(["mean", "std", "min", "max"]).round(4).to_string())
"""
        ),
        md(
            r"""

Read the 10-year box, which is roughly how much bitcoin history exists. The optimiser is
centred near the truth — it is not biased — and its answers still range across everything from
zero to a fifth of the portfolio.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Real.** Emphatically, in sample. Over 11.8 years to 2026-06-30, a 60/40 returned 9.31% a year at 10.9% volatility, Sharpe 0.85. The Sharpe-maximising bitcoin sleeve was **16.5%** — not 1%, not 2% — lifting the ratio to 1.18 on a 18.68% return, at the cost of a -31.2% maximum drawdown against the base portfolio's -21.7%. That number is what the historical record says, and the gap between it and every published recommendation is the whole subject of this study. One correction along the way: bitcoin trades 365 days a year and the rest of a portfolio does not, so everything here is aligned to the equity calendar; skipping that step changes bitcoin's annualised volatility by 20% and every ratio built on it.

**Tradability: Mirage.** So why does nobody recommend 16%? Because nobody believes the realised mean. Bitcoin returned 51% a year over this sample; inverting the optimiser shows what each published allocation is really assuming. A **1% sleeve is optimal if you expect bitcoin to return -5.0% a year**. A 2% sleeve implies -2.0% — essentially nothing. A 5% sleeve implies +8.0%, about what equities are expected to do. These are not cautious readings of the data; they are the answers you get **after discarding it**, which is a defensible position and an entirely different one from what the accompanying backtests imply. The override is justified by the standard error: at 55% volatility, pinning bitcoin's expected return to ±2 percentage points takes **765 years**, and 12 years leaves a standard error of 16% — so the 51% is not knowledge. Out of sample the walk-forward allocator returned 15.11% against the base portfolio's 10.00%, with its chosen weight swinging from 4.7% to 20.0%. The honest form of a bitcoin recommendation states the expected return it assumes; the weight then follows, and can be argued with.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Ask what return a recommendation assumes.** Any bitcoin allocation can be converted into
  the expected return that justifies it, and that number is arguable in a way a weight is not.
  If an adviser's 2% implies zero expected return, they are entitled to that view — but then
  the historical chart in the deck is doing no work.
- **The override is defensible.** Section 4 is why: at bitcoin's volatility, its realised
  return is not evidence of its expected return in any useful sense. Discarding the historical
  mean is the right instinct. Presenting the result as though the history supported it is not.
- **Rebalancing decides what you actually own.** A 2% sleeve left alone becomes something much
  larger after a good run. Whatever number you choose, the discipline matters more than the
  number.
- **This generalises to every volatile asset.** For anything with a large σ, the historical
  mean carries almost no information about the future mean, so allocations to it are
  necessarily prior-driven. That is not a criticism; it is a description of what the exercise
  can and cannot be.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The 1% Allocation — a quantitative teardown \U0001F52C
### Inverting the optimiser · bootstrapping it · σ²/SE² years of data

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The decisive
section is **§3.4b**, which inverts the optimiser: instead of asking what weight the data
implies, it asks what expected return each *published* weight implies. §1 records the
pre-registered hypothesis this study rejected on the way there.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md), bitcoin aligned to the equity calendar.
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from onepercent import data, strategy as st

px = data.load_prices()
rets = st.align_to_equity_calendar(px, data.EQUITY).pct_change()
base = st.sixty_forty(rets, data.EQUITY, data.BONDS)
btc = rets[data.BTC].dropna()
common = base.index.intersection(btc.index)
base, btc = base.loc[common], btc.loc[common]
print(f"as-of {data.AS_OF} | {len(common):,} common sessions from "
      f"{common[0].date()} ({len(common)/252:.1f} years)")
b = st.stats(base)
print(f"the 60/40 alone: {b['cagr']:.2%} a year, {b['vol']:.1%} vol, "
      f"Sharpe {b['sharpe']:.2f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Emphatically, in sample. Over 11.8 years to 2026-06-30, a 60/40 returned 9.31% a year at 10.9% volatility, Sharpe 0.85. The Sharpe-maximising bitcoin sleeve was **16.5%** — not 1%, not 2% — lifting the ratio to 1.18 on a 18.68% return, at the cost of a -31.2% maximum drawdown against the base portfolio's -21.7%. That number is what the historical record says, and the gap between it and every published recommendation is the whole subject of this study. One correction along the way: bitcoin trades 365 days a year and the rest of a portfolio does not, so everything here is aligned to the equity calendar; skipping that step changes bitcoin's annualised volatility by 20% and every ratio built on it. |
| **Tradability** | Mirage | So why does nobody recommend 16%? Because nobody believes the realised mean. Bitcoin returned 51% a year over this sample; inverting the optimiser shows what each published allocation is really assuming. A **1% sleeve is optimal if you expect bitcoin to return -5.0% a year**. A 2% sleeve implies -2.0% — essentially nothing. A 5% sleeve implies +8.0%, about what equities are expected to do. These are not cautious readings of the data; they are the answers you get **after discarding it**, which is a defensible position and an entirely different one from what the accompanying backtests imply. The override is justified by the standard error: at 55% volatility, pinning bitcoin's expected return to ±2 percentage points takes **765 years**, and 12 years leaves a standard error of 16% — so the 51% is not knowledge. Out of sample the walk-forward allocator returned 15.11% against the base portfolio's 10.00%, with its chosen weight swinging from 4.7% to 20.0%. The honest form of a bitcoin recommendation states the expected return it assumes; the weight then follows, and can be argued with. |

> \U0001F4A1 **In plain words.** Unbiased and useless are not the same thing.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

Stated as they were **before** the run, including the one that failed — which is where the
study's actual thesis came from.

- **H₁ (in-sample).** A bitcoin sleeve raised the realised Sharpe ratio of a 60/40.
- **H₂ (the optimiser's answer).** It is far larger than any published recommendation.
- **H₃ (interval).** A block bootstrap of the optimiser gives a wide 90% interval.
- **H₄ (power) — ✗ REJECTED.** *Pre-registered as "the sample cannot rank a 1% sleeve against a
  5% one".* It can, decisively: 5% wins in nearly every bootstrap draw. Conditioned on
  bitcoin's realised return the data is not ambiguous, and the small published allocations
  therefore cannot be defended as statistical caution. §3.4b replaces the question with the one
  that survives: *what expected return does each recommendation assume?*
- **H₅ (arithmetic).** The years needed to pin the mean to ±2pp exceed any available history
  and scale with σ² — which is what makes overriding the realised mean the correct instinct.
- **H₆ (control).** On planted data with a *known* optimum, the optimiser is unbiased at long
  samples and has a standard deviation comparable to the answer at realistic ones.
"""
        ),
        md(
            r"""

## 2 · Data, and the calendar correction
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    if tk not in px.columns:
        continue
    s = px[tk].dropna()
    r = s.pct_change().dropna()
    span_years = (s.index[-1] - s.index[0]).days / 365.25
    rows.append({"ticker": tk, "n": len(s), "from": s.index[0].date(),
                 "obs/year": len(s) / span_years,
                 "vol (252)": r.std(ddof=1) * np.sqrt(252),
                 "vol (365)": r.std(ddof=1) * np.sqrt(365)})
d = pd.DataFrame(rows).set_index("ticker")
print(d.round(3).to_string())
print()
print("Every series has ~252 observations a year because bitcoin has been reindexed onto")
print("the equity calendar. The two volatility columns show what the alternative costs.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The full sweep, several objectives
"""
        ),
        code(
            r"""
rows = []
for w in np.linspace(0, 0.5, 51):
    s = st.stats(st.sleeve(base, btc, w))
    if s:
        rows.append({"weight": w, **s})
d = pd.DataFrame(rows).set_index("weight")
fig, axes = plt.subplots(2, 2, figsize=(13, 8))
for ax, col in zip(axes.ravel(), ["sharpe", "sortino", "calmar", "max_drawdown"]):
    ax.plot(d.index * 100, d[col], lw=2, color="#1f6feb")
    if col != "max_drawdown":
        ax.axvline(d[col].idxmax() * 100, color="#c0392b", ls="--", lw=1.5)
        ax.set_title(f"{col}: peaks at {d[col].idxmax():.1%}", fontsize=10)
    else:
        ax.set_title("maximum drawdown", fontsize=10)
    ax.set_xlabel("bitcoin sleeve (%)")
plt.tight_layout(); plt.show()
print({c: f"{d[c].idxmax():.2%}" for c in ("sharpe", "sortino", "calmar")})
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Three reasonable objectives, three different "optimal"
> allocations. Before any statistical uncertainty is considered at all.
"""
        ),
        md(
            r"""

### 3.2 The plateau, at several tolerances
"""
        ),
        code(
            r"""
curve = st.objective_curve(base, btc, 0.30, n=121)
rows = [{"tolerance": t, **st.flatness(curve, t)}
        for t in (0.002, 0.005, 0.01, 0.02, 0.05, 0.10)]
d = pd.DataFrame(rows).set_index("tolerance")
fig, ax = plt.subplots(figsize=(11, 5))
for t, row in d.iterrows():
    ax.plot([row["plateau_lo"] * 100, row["plateau_hi"] * 100], [t * 100, t * 100],
            lw=6, alpha=0.7, color="#1f6feb", solid_capstyle="butt")
ax.axvline(d["best_weight"].iloc[0] * 100, color="#c0392b", lw=2, label="argmax")
for w in (1, 2, 5, 10):
    ax.axvline(w, color="#8b949e", ls=":", lw=1)
ax.set_yscale("log"); ax.set_xlabel("bitcoin sleeve (%)")
ax.set_ylabel("within this % of optimal"); ax.legend(fontsize=9)
plt.show()
print(d[["best_weight", "plateau_lo", "plateau_hi", "plateau_width"]].round(4).to_string())
"""
        ),
        md(
            r"""

### 3.3 Bootstrapping the optimiser
"""
        ),
        code(
            r"""
boot = st.weight_standard_error(base, btc, 0.50, n_boot=400)
fig, ax = plt.subplots(figsize=(11, 5))
ax.hist(boot["draws"] * 100, bins=50, color="#1f6feb", alpha=0.85)
ax.axvline(boot["median"] * 100, color="#c0392b", lw=2.5,
           label=f"median {boot['median']:.1%}")
ax.axvspan(boot["p05"] * 100, boot["p95"] * 100, alpha=0.15, color="#c0392b",
           label=f"90%: {boot['p05']:.1%}-{boot['p95']:.1%}")
ax.set_xlabel("optimiser's recommended weight (%)"); ax.set_ylabel("bootstrap draws")
ax.legend(fontsize=9)
plt.show()
print({k: round(v, 4) for k, v in boot.items() if k != "draws"})
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Resampled in blocks, so volatility clustering survives. An
> i.i.d. bootstrap would give a narrower interval and a falsely confident recommendation.
"""
        ),
        md(
            r"""

### 3.4b The inversion — the study's actual finding
"""
        ),
        code(
            r"""
imp = st.implied_mean_for_weight(base, btc, (0.005, 0.01, 0.02, 0.05, 0.10, 0.15))
curve = st.weight_vs_assumed_mean(base, btc, np.linspace(-0.30, 0.70, 60))
realised = np.expm1(np.log1p(btc).sum() * 252 / len(btc))
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(curve.index * 100, curve["optimal_weight"] * 100, lw=2.5, color="#1f6feb")
axes[0].axvline(0, color="#8b949e", ls="--", lw=1.5, label="zero expected return")
axes[0].axvline(realised * 100, color="#2ea44f", ls="--", lw=1.5,
                label=f"realised: {realised:.0%}")
for w in (0.01, 0.02, 0.05):
    axes[0].axhline(w * 100, color="#c0392b", ls=":", lw=1)
axes[0].set_xlabel("assumed expected return (%)")
axes[0].set_ylabel("optimal sleeve (%)"); axes[0].legend(fontsize=8)
axes[1].barh([f"{w:.1%}" for w in imp.index], imp["implied_mean"] * 100,
             color=["#c0392b" if m < 0 else "#1f6feb" for m in imp["implied_mean"]])
axes[1].axvline(0, color="k", lw=1.5)
axes[1].axvline(realised * 100, color="#2ea44f", ls="--", lw=1.5,
                label=f"realised {realised:.0%}")
axes[1].set_xlabel("expected return the sleeve implies (%)")
axes[1].set_ylabel("recommended sleeve"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(imp.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The right-hand bars are the punchline. A 2% allocation is the
> optimiser's answer *if you assume bitcoin earns nothing*; a 1% allocation assumes it loses
> money. Those are priors, not inferences, and §3.5 shows why holding such a prior is
> reasonable — the realised return simply is not evidence about the expected one at this
> volatility. What is not reasonable is illustrating the recommendation with the chart it
> contradicts.
"""
        ),
        md(
            r"""

### 3.4c Sampling uncertainty cannot get you there
"""
        ),
        code(
            r"""
boot = st.weight_standard_error(base, btc, 0.50, n_boot=300)
mu = st.weight_with_mean_uncertainty(base, btc, 0.50, n_draws=300)
fig, ax = plt.subplots(figsize=(11, 5))
ax.hist(boot["draws"] * 100, bins=40, alpha=0.6, color="#1f6feb",
        label=f"block bootstrap: {boot['p05']:.1%}-{boot['p95']:.1%}")
ax.hist(mu["draws"] * 100, bins=40, alpha=0.6, color="#f0b429",
        label=f"mean drawn from N(realised, SE): {mu['p05']:.1%}-{mu['p95']:.1%}")
for w, col in ((1, "#c0392b"), (2, "#c0392b")):
    ax.axvline(w, color=col, lw=2, ls=":")
ax.annotate("what allocators\nrecommend", (2, ax.get_ylim()[1] * 0.7), fontsize=9,
            color="#c0392b", xytext=(20, 0), textcoords="offset points")
ax.set_xlabel("optimal sleeve (%)"); ax.set_ylabel("draws"); ax.legend(fontsize=9)
plt.show()
print(f"standard error on bitcoin's mean return: {mu['mean_se']:.1%} a year")
print("Neither distribution reaches down to 1-2%. No treatment of SAMPLING uncertainty")
print("does, because every draw still carries a mean within a couple of standard errors")
print(f"of {mu['realised_mean']:.0%}. Only a different prior gets you there.")
"""
        ),
        md(
            r"""

### 3.4 Can the sample rank two allocations?
"""
        ),
        code(
            r"""
rows = []
for wa, wb in ((0.01, 0.02), (0.01, 0.05), (0.01, 0.10), (0.02, 0.05), (0.05, 0.10),
               (0.0, 0.05), (0.0, 0.50)):
    p = st.power_to_distinguish(base, btc, wa, wb, n_boot=250)
    rows.append({"pair": f"{wa:.0%} vs {wb:.0%}", **p})
d = pd.DataFrame(rows).set_index("pair")
fig, ax = plt.subplots(figsize=(10, 5))
y = np.arange(len(d))
ax.errorbar(d["mean_diff"], y, xerr=[d["mean_diff"] - d["p05"], d["p95"] - d["mean_diff"]],
            fmt="o", capsize=4, color="#1f6feb")
ax.axvline(0, color="#c0392b", lw=2)
ax.set_yticks(y); ax.set_yticklabels(d.index, fontsize=9)
ax.set_xlabel("Sharpe difference (larger sleeve minus smaller), 90% interval")
plt.show()
print(d[["mean_diff", "sd_diff", "share_b_wins", "distinguishable"]].round(4).to_string())
"""
        ),
        md(
            r"""

### 3.5 Merton's arithmetic
"""
        ),
        code(
            r"""
vols = np.linspace(0.05, 0.90, 60)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for target in (0.01, 0.02, 0.05):
    axes[0].plot(vols * 100, [(v / target) ** 2 for v in vols],
                 lw=2, label=f"pin the mean to +/-{target:.0%}")
axes[0].set_yscale("log"); axes[0].set_xlabel("annualised volatility (%)")
axes[0].set_ylabel("years of data required (log)"); axes[0].legend(fontsize=8)
for tk, label, col in ((data.BTC, "bitcoin", "#c0392b"),
                       (data.EQUITY, "equities", "#1f6feb"),
                       (data.GOLD, "gold", "#f0b429")):
    s = px[tk].dropna().pct_change().dropna()
    v = s.std(ddof=1) * np.sqrt(252)
    axes[0].axvline(v * 100, color=col, ls=":", lw=1.5)
    axes[0].annotate(label, (v * 100, 5), rotation=90, fontsize=7, color=col)
yrs = np.arange(1, 101)
for tk, label, col in ((data.BTC, "bitcoin", "#c0392b"),
                       (data.EQUITY, "equities", "#1f6feb")):
    s = px[tk].dropna().pct_change().dropna()
    v = s.std(ddof=1) * np.sqrt(252)
    axes[1].plot(yrs, v / np.sqrt(yrs) * 100, lw=2, color=col, label=label)
axes[1].axhline(2, color="k", ls="--", lw=1.5, label="+/-2pp")
axes[1].set_xlabel("years of history")
axes[1].set_ylabel("standard error of the mean (pp)"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 3.6 Out of sample, with costs
"""
        ),
        code(
            r"""
wf = st.walk_forward_weights(base, btc, 3.0, 63, 0.20, 30.0)
ws = st.walk_forward_series(base, btc, 3.0, 63, 0.20, 30.0)
fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True,
                         gridspec_kw={"height_ratios": [1, 2]})
axes[0].step(wf.index, wf["weight"] * 100, where="post", lw=2, color="#c0392b")
axes[0].set_ylabel("chosen weight (%)")
axes[0].set_title("what the allocator recommended, quarter by quarter", fontsize=10)
for name, col in (("walk_forward", "#1f6feb"), ("base", "#8b949e")):
    axes[1].plot(ws.index, (1 + ws[name]).cumprod(), lw=2, color=col, label=name)
for w, col in ((0.01, "#2ea44f"), (0.05, "#f0b429")):
    fx = st.sleeve(ws["base"], btc.reindex(ws.index), w)
    axes[1].plot(fx.index, (1 + fx).cumprod(), lw=1.5, ls="--", color=col,
                 label=f"fixed {w:.0%}")
axes[1].set_yscale("log"); axes[1].set_ylabel("growth of $1 (log)")
axes[1].legend(fontsize=9)
plt.tight_layout(); plt.show()
print(pd.DataFrame({n: st.stats(ws[n]) for n in ("walk_forward", "base")}).round(4)
      .to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The top panel is the point. An allocator whose recommendation
> swings across the whole admissible range every few quarters is not learning; it is resampling
> noise, exactly as §3.3 predicts it must.
"""
        ),
        md(
            r"""

### 3.7 The control — a known truth
"""
        ),
        code(
            r"""
rows = []
for true_w in (0.02, 0.05, 0.10):
    for years in (3, 10, 30, 100):
        found = [st.optimal_weight(w["base"], w["asset"], 0.30) for w in
                 (st.synthetic_pair(n=int(years * 252), true_weight=true_w,
                                    seed=1003 + k) for k in range(10))]
        rows.append({"true": true_w, "years": years, "mean": np.mean(found),
                     "sd": np.std(found), "bias": np.mean(found) - true_w})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for tw, g in d.groupby("true"):
    axes[0].plot(g["years"], g["bias"] * 100, "o-", label=f"true = {tw:.0%}")
    axes[1].plot(g["years"], g["sd"] * 100, "o-", label=f"true = {tw:.0%}")
axes[0].axhline(0, color="k", lw=1.5)
axes[0].set_xscale("log"); axes[0].set_xlabel("years of data")
axes[0].set_ylabel("bias (pp)"); axes[0].legend(fontsize=8)
axes[0].set_title("unbiased at every sample size", fontsize=10)
axes[1].set_xscale("log"); axes[1].set_xlabel("years of data")
axes[1].set_ylabel("standard deviation of the answer (pp)"); axes[1].legend(fontsize=8)
axes[1].set_title("and useless at realistic ones", fontsize=10)
plt.tight_layout(); plt.show()
print(d.round(4).to_string(index=False))
"""
        ),
        md(
            r"""

### 3.8 Rebalancing, which decides what you own
"""
        ),
        code(
            r"""
rb = st.rebalancing_matters(base, btc, 0.02, (1, 5, 21, 63, 252, 10_000))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
lbl = ["daily", "weekly", "monthly", "quarterly", "yearly", "never"]
axes[0].bar(lbl, rb["max_weight_reached"] * 100, color="#c0392b")
axes[0].axhline(2, color="k", ls="--", lw=1.5, label="the nominal 2%")
axes[0].set_ylabel("peak weight actually held (%)"); axes[0].legend(fontsize=8)
axes[1].bar(lbl, rb["sharpe"], color="#1f6feb")
axes[1].set_ylabel("Sharpe ratio")
for ax in axes:
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right", fontsize=8)
plt.tight_layout(); plt.show()
rb[["max_weight_reached", "cagr", "vol", "sharpe", "max_drawdown"]].round(4)
"""
        ),
        md(
            r"""

### 3.9 Is bitcoin special, or is this every volatile diversifier?
"""
        ),
        code(
            r"""
rows = []
for tk in (data.BTC, data.GOLD, data.LONG_BONDS):
    a = rets[tk].reindex(common).dropna()
    bb = base.reindex(a.index)
    cu = st.objective_curve(bb, a, 0.30, n=41)
    ff = st.flatness(cu, 0.01)
    bs = st.weight_standard_error(bb, a, 0.50, n_boot=150)
    rows.append({"asset": tk, "corr": bb.corr(a), "vol": a.std(ddof=1) * np.sqrt(252),
                 "best": ff["best_weight"], "plateau": ff["plateau_width"],
                 "boot_sd": bs["sd"], "boot_span": bs["p95"] - bs["p05"]})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.scatter(d["vol"] * 100, d["boot_span"] * 100, s=140, color="#1f6feb")
for tk, row in d.iterrows():
    ax.annotate(tk, (row["vol"] * 100, row["boot_span"] * 100), fontsize=9,
                xytext=(6, 4), textcoords="offset points")
ax.set_xlabel("asset volatility (%)")
ax.set_ylabel("width of the 90% interval on the optimal weight (pp)")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Nothing here is about bitcoin specifically. It is about
> volatility, and bitcoin simply has the most of it.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
curve = st.objective_curve(base, btc, 0.30, n=61)
f = st.flatness(curve, 0.01)
boot = st.weight_standard_error(base, btc, 0.50, n_boot=300)
p = st.power_to_distinguish(base, btc, 0.01, 0.05, n_boot=250)
vol = btc.std(ddof=1) * np.sqrt(252)
pd.DataFrame({
    "60/40 Sharpe alone": [st.stats(base)["sharpe"]],
    "Sharpe-maximising sleeve": [f["best_weight"]],
    "its Sharpe": [f["best_value"]],
    "weights within 1% of optimal": [f["plateau_width"]],
    "bootstrap 5th percentile": [boot["p05"]],
    "bootstrap 95th percentile": [boot["p95"]],
    "draws landing at zero": [boot["share_at_zero"]],
    "5% beats 1% in this share of draws": [p["share_b_wins"]],
    "1% vs 5% distinguishable": [float(p["distinguishable"])],
    "bitcoin's realised return": [np.expm1(np.log1p(btc).sum() * 252 / len(btc))],
    "expected return a 1% sleeve implies": [
        st.implied_mean_for_weight(base, btc, (0.01,))["implied_mean"].iloc[0]],
    "expected return a 2% sleeve implies": [
        st.implied_mean_for_weight(base, btc, (0.02,))["implied_mean"].iloc[0]],
    "bitcoin volatility (252d)": [vol],
    "years to pin its mean to +/-2pp": [st.sample_needed(0, vol, 0.02)["years_needed"]],
    "standard error on the mean today": [vol / np.sqrt(len(btc) / 252)],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Bayesian shrinkage** (Black-Litterman, or a simple prior of zero excess return) is the
  standard response to §3.3, and it works by making the answer depend on the prior rather than
  the data — which is honest, and worth stating plainly rather than presenting as an
  improvement in estimation.
- **Resampled efficiency** (Michaud) averages the optimiser over bootstrap draws. On the numbers
  in §3.3 that average would land near the middle of a nearly uniform distribution, which is a
  reasonable default and not a discovery.
- **Utility other than Sharpe.** Bitcoin's contribution to the left tail exceeds its
  contribution to variance, so a CRRA or drawdown-constrained investor gets a smaller answer.
  Repeating §3.1 under a power utility would be a clean extension.
- **The estimability frame generalises.** Any allocation recommendation for a high-volatility
  asset can be checked against §3.5 before its backtest is read, and most will not survive it.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
