"""Notebook builder for Study 1011 — The Half-Life of an Edge.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Half-Life of an Edge \U000023F1
### Every signal has an expiry date. Almost nobody prints it.

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Two signals with identical predictive strength can be completely different businesses. One
decays in a week and needs constant trading; the other lasts a quarter and can be run patiently
at a fraction of the cost. The number that separates them is rarely reported and is not hard to
measure.

> \U0001F4D3 **This is the plain-language layer.** The calibrated decay estimator, the breadth
> correction and the trading-rate sweep are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do signals decay at different rates? | Yes, by a large factor. |
| Can you measure the rate? | Yes — with a wide error bar. |
| How often should you trade? | Roughly at the decay rate. |
| Does the textbook breadth formula work? | Only after two corrections. |
"""
        ),
        md(
            r"""

## 1 · What a decaying signal looks like
"""
        ),
        code(
            r"""
from halflife import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2500]
R = px[cols].pct_change().dropna()
sigs = st.make_signals(R)
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} sessions from "
      f"{R.index[0].date()}")
print(f"signals: {', '.join(sigs)}")
"""
        ),
        code(
            r"""
profiles, cum = {}, {}
for name, s in sigs.items():
    d = st.lag_profile(s, R)
    if not d.empty:
        profiles[name] = d
        cum[name] = st.ic_decay(s, R, (1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 126, 252))
fig, ax = plt.subplots(figsize=(11, 5.5))
for name, d in profiles.items():
    ax.plot(d.index, d["ic"], "o-", lw=2, label=name)
ax.axhline(0, color="k", lw=1.5)
ax.set_xscale("log")
ax.set_xlabel("days after the signal is measured (log)")
ax.set_ylabel("predictive power on THAT day")
ax.legend(fontsize=9)
plt.show()
for name, d in profiles.items():
    f = st.fit_half_life(d)
    print(f"{name:14s} half-life {f.get('half_life', float('nan')):7.1f} days")
"""
        ),
        md(
            r"""

Reversal is nearly gone within days. Momentum and low volatility keep working for months. Those
are different businesses, and no Sharpe ratio distinguishes them.
"""
        ),
        md(
            r"""

## 2 · The mistake that makes everything look durable
"""
        ),
        code(
            r"""
name = min(profiles, key=lambda k: st.fit_half_life(profiles[k]).get(
    "half_life", np.inf))
d = cum[name]
m = st.marginal_ic(d)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(d.index, d["ic"], "o-", lw=2.5, color="#1f6feb")
axes[0].set_xlabel("holding period (days)")
axes[0].set_ylabel("cumulative information coefficient")
axes[0].set_title("looks like it never decays", fontsize=10)
axes[1].plot(d.index, m["marginal_ic_per_day"], "o-", lw=2.5, color="#c0392b")
axes[1].axhline(0, color="k", lw=1.5)
axes[1].set_xlabel("holding period (days)")
axes[1].set_ylabel("information earned PER DAY")
axes[1].set_title("and here it is decaying", fontsize=10)
plt.tight_layout(); plt.show()
print(f"{name}: cumulative IC rises from {d['ic'].iloc[0]:+.4f} to {d['ic'].iloc[-1]:+.4f}")
print(f"        per-day IC falls from {m['marginal_ic_per_day'].iloc[0]:+.5f} to "
      f"{m['marginal_ic_per_day'].iloc[-1]:+.5f}")
"""
        ),
        md(
            r"""

Both panels are the same signal. Hold something longer and the *total* predicted return grows,
even as the signal itself dies. Fitting a decay curve to the left-hand chart would report every
strategy as far more patient than it is.
"""
        ),
        md(
            r"""

## 3 · How precisely do we know the number?
"""
        ),
        code(
            r"""
u = st.decay_uncertainty(sigs[name], R, n_boot=50)
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.barh([0], [u["p95"] - u["p05"]], left=[u["p05"]], height=0.4, color="#1f6feb",
        alpha=0.5, label="90% interval")
ax.plot([u["median"]], [0], "o", ms=14, color="#c0392b", label="point estimate")
ax.set_yticks([]); ax.set_xlabel("fitted half-life (days)")
ax.legend(fontsize=9)
plt.show()
print(f"half-life: {u['median']:.1f} days, but plausibly anywhere from "
      f"{u['p05']:.1f} to {u['p95']:.1f}")
print(f"that is a factor of {u['ratio_95_05']:.1f} between the ends of the interval")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** This matters because the optimal trading rate is a smooth
> function of the half-life. Tuning it to three decimal places against an input known to within
> a factor of several is fitting noise with extra steps.
"""
        ),
        md(
            r"""

## 4 · So how often should you trade?
"""
        ),
        code(
            r"""
f = st.fit_half_life(profiles[name])
hl = f["half_life"]
rs = st.rebalance_sweep(sigs[name], R, hl,
                        periods=(1, 2, 3, 5, 8, 13, 21, 42, 63, 126), cost_bps=10.0)
fig, ax = plt.subplots(figsize=(10, 5.5))
ax.plot(rs.index, rs["ir"], "o-", lw=2.5, color="#1f6feb")
ax.axvline(hl, color="#c0392b", lw=2, ls="--",
           label=f"the signal's half-life ({hl:.0f} days)")
best = rs["ir"].idxmax()
ax.scatter([best], [rs.loc[best, "ir"]], s=150, color="#2ea44f", zorder=5,
           label=f"best: {best} days")
ax.set_xscale("log"); ax.set_xlabel("days between rebalances (log)")
ax.set_ylabel("information ratio after costs"); ax.legend(fontsize=9)
plt.show()
print(rs[["ir", "turnover_pa", "cost_drag"]].round(4).to_string())
"""
        ),
        md(
            r"""

Trade much faster and you pay for a view that has not changed. Trade much slower and the view
has expired before you act on it. The peak sits near the half-life, which is the whole practical
point of measuring it.
"""
        ),
        md(
            r"""

## 5 · The formula everyone misuses
"""
        ),
        code(
            r"""
resid = st._residual_correlation(R)
raw = R.corr().to_numpy()
raw_off = np.nanmean(raw[~np.eye(len(raw), dtype=bool)])
rows = []
for nm, pr in profiles.items():
    ff = st.fit_half_life(pr)
    h2 = ff.get("half_life", np.nan)
    if not np.isfinite(h2):
        continue
    b = st.effective_breadth(len(cols), int(max(h2, 1)), correlation=max(resid, 0))
    rows.append({"signal": nm, "naive breadth": b["naive_breadth"],
                 "honest breadth": b["breadth"], "overstated by": b["overstatement"]})
d2 = pd.DataFrame(rows).set_index("signal")
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(d2)); w = 0.38
ax.bar(x - w/2, d2["naive breadth"], w, color="#c0392b", label="counting every trade")
ax.bar(x + w/2, d2["honest breadth"], w, color="#2ea44f",
       label="counting independent bets")
ax.set_yscale("log"); ax.set_xticks(x)
ax.set_xticklabels(d2.index, rotation=20, ha="right", fontsize=8)
ax.set_ylabel("breadth (log scale)"); ax.legend(fontsize=9)
plt.show()
print(f"average raw correlation between these names:      {raw_off:.3f}")
print(f"average correlation after removing the market:    {resid:.3f}")
print(d2.round(1).to_string())
"""
        ),
        md(
            r"""

Grinold's law says your information ratio is your skill times the square root of your breadth.
Counting breadth as "50 stocks × 252 days" is wrong twice over: a signal with a month-long
half-life gives you about twelve fresh views a year, not 252, and fifty correlated stocks are
not fifty independent bets.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Weak.** Yes, and the differences are large. Measuring the rank information coefficient at every horizon from one day to a year across 50 names, the fitted half-lives ran from **57 days** (reversal_5d) to **114 days** (momentum_12m) — a factor of 2.0 between signals whose headline ICs differ by far less. That is the number that should appear beside a backtest and almost never does. Two measurement points are worth making. The fit is to the **marginal** IC, not the cumulative one: a cumulative IC can keep rising simply because the horizon is longer, which flatters every decay profile. And the half-life is estimated with real uncertainty — bootstrapping whole years of the panel puts a 90% interval of **8 to 566 days** on the headline signal, a ratio of 70.0×. Any formula that turns a half-life into a trading rate inherits that interval, which is a good reason not to tune one to three decimal places.

**Tradability: Useful.** Trading at roughly the decay rate wins, and the two ways of getting there agree. Sweeping the rebalancing period on reversal_5d at 10bp, the best information ratio came at **42 days** against a fitted half-life of 57 — 0.73× the half-life. Rebalancing 1× faster gave -1.75 and 126× slower gave -0.37, against -0.18 at the optimum. The Gârleanu-Pedersen partial-trading rule reaches the same place from the other direction: its closed form recommends trading 42% of the way each period, and the brute-force sweep put the optimum at 20%. Grinold's law is the piece that needs handling with care. Counting bets naively — 50 names × 252 days — gives a breadth of 12,600 and predicts an IR of -0.27. Correcting for the decay rate *and* for the -0.02 residual correlation between names brings breadth to 221 and the prediction to -0.04, against a realised -0.34. The naive count overstates breadth by **57×**, and since IR scales with its square root, that is a 8× exaggeration of the achievable information ratio.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Measure the half-life before the Sharpe ratio.** It tells you the capacity, the cost
  tolerance and the rebalancing schedule, none of which a backtest headline conveys.
- **Trade partway, not all the way.** Gârleanu and Pedersen's result is that moving a fraction
  toward the target each period beats both full rebalancing and infrequent rebalancing. It is a
  one-line change to most systems.
- **Be suspicious of large claimed breadth.** If a manager's information ratio implies thousands
  of independent bets a year, ask what the signal's half-life is and how correlated the
  positions are. The two corrections in section 5 usually remove most of the claim.
- **The half-life shrinks after publication.** McLean and Pontiff (2016) found anomaly returns
  fall by about half once documented. Anything measured on historical data is an upper bound.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Half-Life of an Edge — a quantitative teardown \U0001F52C
### Marginal IC decay · breadth corrected twice over · closed form against brute force

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). **§3.1**
calibrates the decay estimator on known half-lives before using it. **§3.2** shows why the fit
must use the *marginal* IC — a cumulative profile rises with horizon and flatters every signal.
**§3.4** corrects Grinold breadth for both decay and residual correlation, which together
shrink it by a large factor.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from halflife import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2500]
R = px[cols].pct_change().dropna()
sigs = st.make_signals(R)
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} sessions from "
      f"{R.index[0].date()}")
print(f"signals: {', '.join(sigs)}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Yes, and the differences are large. Measuring the rank information coefficient at every horizon from one day to a year across 50 names, the fitted half-lives ran from **57 days** (reversal_5d) to **114 days** (momentum_12m) — a factor of 2.0 between signals whose headline ICs differ by far less. That is the number that should appear beside a backtest and almost never does. Two measurement points are worth making. The fit is to the **marginal** IC, not the cumulative one: a cumulative IC can keep rising simply because the horizon is longer, which flatters every decay profile. And the half-life is estimated with real uncertainty — bootstrapping whole years of the panel puts a 90% interval of **8 to 566 days** on the headline signal, a ratio of 70.0×. Any formula that turns a half-life into a trading rate inherits that interval, which is a good reason not to tune one to three decimal places. |
| **Tradability** | Useful | Trading at roughly the decay rate wins, and the two ways of getting there agree. Sweeping the rebalancing period on reversal_5d at 10bp, the best information ratio came at **42 days** against a fitted half-life of 57 — 0.73× the half-life. Rebalancing 1× faster gave -1.75 and 126× slower gave -0.37, against -0.18 at the optimum. The Gârleanu-Pedersen partial-trading rule reaches the same place from the other direction: its closed form recommends trading 42% of the way each period, and the brute-force sweep put the optimum at 20%. Grinold's law is the piece that needs handling with care. Counting bets naively — 50 names × 252 days — gives a breadth of 12,600 and predicts an IR of -0.27. Correcting for the decay rate *and* for the -0.02 residual correlation between names brings breadth to 221 and the prediction to -0.04, against a realised -0.34. The naive count overstates breadth by **57×**, and since IR scales with its square root, that is a 8× exaggeration of the achievable information ratio. |

> \U0001F4A1 **In plain words.** The decay rate sets the trading rate, and the decay rate is
> known to within a factor of several.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (calibration).** The estimator recovers a planted half-life across a wide range.
- **H₂ (marginal vs cumulative).** Cumulative IC rises with horizon even for a fast-decaying
  signal, so the fit must use the marginal profile.
- **H₃ (spread).** Real signals differ in half-life by a large factor.
- **H₄ (uncertainty).** The bootstrap interval on a half-life is wide enough to bound how
  precisely any derived trading rate can be specified.
- **H₅ (breadth).** Correcting for decay *and* residual correlation shrinks Grinold breadth by
  more than an order of magnitude.
- **H₆ (trading rate).** The rebalancing period maximising after-cost IR sits near the fitted
  half-life, and moves slower as costs rise.
"""
        ),
        md(
            r"""

## 2 · The signals
"""
        ),
        code(
            r"""
profiles, cum = {}, {}
for nm, s in sigs.items():
    d = st.lag_profile(s, R)
    if not d.empty:
        profiles[nm] = d
        cum[nm] = st.ic_decay(s, R, (1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 126, 252))
rows = []
for nm, s in sigs.items():
    v = s.dropna(how="all")
    rows.append({"signal": nm, "first date": v.index[0].date(),
                 "coverage": float(s.notna().sum(axis=1).median()),
                 "autocorr(1d)": float(s.mean(axis=1).autocorr(1)),
                 "cross-sectional sd": float(s.std(axis=1).median())})
print(pd.DataFrame(rows).set_index("signal").round(3).to_string())
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Calibrating the estimator before using it
"""
        ),
        code(
            r"""
rows = []
for true_hl in (2, 3, 5, 10, 21, 42, 63):
    for seed in range(3):
        sim = st.synthetic_panel(n_assets=60, n_days=8000, half_life=true_hl,
                                 ic=0.08, seed=1011 + seed)
        f = st.fit_half_life(st.lag_profile(sim["signal"], sim["returns"],
                                         (1, 2, 3, 5, 8, 13, 21, 34, 55, 89)))
        rows.append({"true": true_hl, "fitted": f.get("half_life", np.nan),
                     "r2": f.get("r2", np.nan)})
d = pd.DataFrame(rows).groupby("true").mean()
fig, ax = plt.subplots(figsize=(9.5, 5))
ax.loglog(d.index, d["fitted"], "o-", lw=2.5, color="#1f6feb", label="fitted")
ax.loglog(d.index, d.index, "k--", lw=2, label="truth")
ax.set_xlabel("planted half-life (days, log)")
ax.set_ylabel("fitted half-life (days, log)"); ax.legend(fontsize=9)
plt.show()
print(d.round(2).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The estimator tracks the truth across an order of magnitude. It
> is not exact — an exponential fit to a non-exponential profile never will be — but it ranks
> and scales correctly, which is what the rest of the study needs from it.
"""
        ),
        md(
            r"""

### 3.2 Marginal versus cumulative
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
for nm, d in cum.items():
    m = st.marginal_ic(d)
    axes[0].plot(d.index, d["ic"], "o-", lw=2, label=nm)
for nm, d in profiles.items():
    axes[1].plot(d.index, d["ic"], "o-", lw=2, label=nm)
axes[0].set_xscale("log"); axes[0].set_xlabel("horizon (days, log)")
axes[0].set_ylabel("cumulative IC"); axes[0].legend(fontsize=7)
axes[0].set_title("cumulative: rises for everything", fontsize=10)
axes[1].axhline(0, color="k", lw=1.5)
axes[1].set_xscale("log"); axes[1].set_xlabel("horizon (days, log)")
axes[1].set_ylabel("IC against that single day"); axes[1].legend(fontsize=7)
axes[1].set_title("per-lag: THIS is the decay", fontsize=10)
plt.tight_layout(); plt.show()
print(pd.DataFrame({
    "from the lag profile (correct)": {nm: st.fit_half_life(d).get("half_life", np.nan)
                                       for nm, d in profiles.items()},
    "from the cumulative profile (wrong)": {
        nm: st.fit_half_life(st.marginal_ic(c).rename(
            columns={"marginal_ic_per_day": "ic"})).get("half_life", np.nan)
        for nm, c in cum.items()},
}).round(1).to_string())
"""
        ),
        md(
            r"""

### 3.3 Uncertainty in the half-life
"""
        ),
        code(
            r"""
rows = []
for nm in profiles:
    u = st.decay_uncertainty(sigs[nm], R, n_boot=40)
    if u:
        rows.append({"signal": nm, **u})
d = pd.DataFrame(rows).set_index("signal")
fig, ax = plt.subplots(figsize=(10, 5))
y = np.arange(len(d))
ax.errorbar(d["median"], y, xerr=[d["median"] - d["p05"], d["p95"] - d["median"]],
            fmt="o", capsize=5, ms=10, color="#1f6feb")
ax.set_yticks(y); ax.set_yticklabels(d.index, fontsize=9)
ax.set_xscale("log"); ax.set_xlabel("fitted half-life, days (log) with 90% interval")
plt.show()
print(d.round(2).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** These intervals are wide because a half-life is estimated from
> a decay curve which is itself estimated from noisy cross-sectional correlations. Two layers of
> estimation error compound, and the Gârleanu-Pedersen formula inherits both.
"""
        ),
        md(
            r"""

### 3.4 Breadth, corrected twice
"""
        ),
        code(
            r"""
resid = st._residual_correlation(R)
rows = []
for nm, d in profiles.items():
    hl = st.fit_half_life(d).get("half_life", np.nan)
    if not np.isfinite(hl):
        continue
    naive = st.effective_breadth(len(cols), 1, correlation=0.0)
    decay_only = st.effective_breadth(len(cols), int(max(hl, 1)), correlation=0.0)
    both = st.effective_breadth(len(cols), int(max(hl, 1)), correlation=max(resid, 0))
    rows.append({"signal": nm, "half_life": hl,
                 "naive": naive["breadth"], "decay corrected": decay_only["breadth"],
                 "and correlation corrected": both["breadth"]})
d = pd.DataFrame(rows).set_index("signal")
fig, ax = plt.subplots(figsize=(11, 5))
x = np.arange(len(d)); w = 0.26
for i, (c, col) in enumerate((("naive", "#c0392b"),
                              ("decay corrected", "#f0b429"),
                              ("and correlation corrected", "#2ea44f"))):
    ax.bar(x + (i - 1) * w, d[c], w, color=col, label=c)
ax.set_yscale("log"); ax.set_xticks(x)
ax.set_xticklabels(d.index, rotation=20, ha="right", fontsize=8)
ax.set_ylabel("breadth (log)"); ax.legend(fontsize=8)
plt.show()
print(d.round(1).to_string())
print(f"\nresidual correlation used: {resid:.4f}")
"""
        ),
        md(
            r"""

### 3.5 Predicted against realised IR
"""
        ),
        code(
            r"""
rows = []
for nm, d in profiles.items():
    hl = st.fit_half_life(d).get("half_life", np.nan)
    if not np.isfinite(hl):
        continue
    for rebal in (1, 5, 21, 63):
        g = st.grinold_check(sigs[nm], R, hl, rebalance=rebal, cost_bps=0.0)
        if g:
            rows.append({"signal": nm, "rebalance": rebal, **g})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5.5))
ax.scatter(d["predicted_ir"], d["realised_ir"], s=90, color="#1f6feb",
           label="decay + correlation corrected")
ax.scatter(d["predicted_ir_naive"], d["realised_ir"], s=60, color="#c0392b",
           alpha=0.7, label="naive breadth")
lim = [0, max(d["predicted_ir_naive"].max(), d["realised_ir"].max()) * 1.1]
ax.plot(lim, lim, "k--", lw=2, label="the law holds exactly")
ax.set_xlabel("predicted information ratio")
ax.set_ylabel("realised information ratio"); ax.legend(fontsize=8)
plt.show()
print(d[["signal", "rebalance", "ic_at_rebalance", "predicted_ir",
         "predicted_ir_naive", "realised_ir"]].round(3).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The red points sit far to the right of the dashed line: the
> naive breadth count predicts information ratios nobody achieves. The blue points are much
> closer, and where they still miss, the gap is the transfer coefficient — the cost of
> constraints, which Clarke, de Silva and Thorley added to the law for exactly this reason.
"""
        ),
        md(
            r"""

### 3.6 The rebalancing sweep, every signal
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
for nm, d0 in profiles.items():
    hl = st.fit_half_life(d0).get("half_life", np.nan)
    if not np.isfinite(hl):
        continue
    sw = st.rebalance_sweep(sigs[nm], R, hl,
                            periods=(1, 2, 3, 5, 8, 13, 21, 42, 63, 126),
                            cost_bps=10.0)
    axes[0].plot(sw.index, sw["ir"], "o-", lw=2, label=nm)
    axes[1].plot(sw["vs_half_life"], sw["ir"], "o-", lw=2, label=nm)
axes[0].set_xscale("log"); axes[0].set_xlabel("rebalance period (days, log)")
axes[0].set_ylabel("IR after costs"); axes[0].legend(fontsize=7)
axes[1].axvline(1.0, color="k", ls="--", lw=2, label="= the half-life")
axes[1].set_xscale("log")
axes[1].set_xlabel("rebalance period / half-life (log)")
axes[1].set_ylabel("IR after costs"); axes[1].legend(fontsize=7)
plt.tight_layout(); plt.show()
print("If the framework is right, the right-hand curves should peak near 1.")
"""
        ),
        md(
            r"""

### 3.7 Closed form against brute force
"""
        ),
        code(
            r"""
rows = []
for hl in (2, 5, 10, 21, 63, 126):
    for c in (1.0, 10.0, 50.0, 200.0):
        rows.append({"half_life": hl, "cost_bps": c,
                     "gp_rate": st.gp_trade_rate(hl, c)})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for c, g in d.groupby("cost_bps"):
    axes[0].semilogx(g["half_life"], g["gp_rate"] * 100, "o-", lw=2,
                     label=f"{c:.0f}bp")
axes[0].set_xlabel("signal half-life (days, log)")
axes[0].set_ylabel("recommended trade rate (%)"); axes[0].legend(fontsize=8)
axes[0].set_title("the closed form", fontsize=10)
nm = min(profiles, key=lambda k: st.fit_half_life(profiles[k]).get("half_life", np.inf))
hl = st.fit_half_life(profiles[nm])["half_life"]
for c in (2.0, 10.0, 50.0):
    tr = st.trade_rate_sweep(sigs[nm], R, rebalance=max(int(round(hl)), 1),
                             cost_bps=c,
                             rates=(0.05, 0.1, 0.2, 0.35, 0.5, 0.7, 0.85, 1.0))
    axes[1].plot(tr.index * 100, tr["ir"], "o-", lw=2, label=f"{c:.0f}bp")
    axes[1].axvline(st.gp_trade_rate(hl, c) * 100, ls=":", lw=1.5, alpha=0.6)
axes[1].set_xlabel("trade rate (%)"); axes[1].set_ylabel("realised IR")
axes[1].set_title("brute force (dotted = closed form)", fontsize=10)
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.pivot(index="half_life", columns="cost_bps", values="gp_rate").round(3)
      .to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The closed form's *shape* is right — the dotted lines move the
> way the peaks move. Its *level* depends on a risk-aversion parameter nobody can observe, so it
> should be read as "trade roughly this fast" rather than as a setting.
"""
        ),
        md(
            r"""

### 3.8 Costs decide how far from the half-life you land
"""
        ),
        code(
            r"""
rows = []
for nm, d0 in profiles.items():
    hl = st.fit_half_life(d0).get("half_life", np.nan)
    if not np.isfinite(hl):
        continue
    for c in (0.0, 2.0, 5.0, 10.0, 25.0, 50.0, 100.0):
        sw = st.rebalance_sweep(sigs[nm], R, hl,
                                periods=(1, 2, 5, 10, 21, 42, 63, 126), cost_bps=c)
        if sw.empty:
            continue
        b = int(sw["ir"].idxmax())
        rows.append({"signal": nm, "cost_bps": c, "best_rebalance": b,
                     "ratio": b / max(hl, 1e-9), "ir": float(sw.loc[b, "ir"])})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5))
for nm, g in d.groupby("signal"):
    ax.plot(g["cost_bps"], g["ratio"], "o-", lw=2, label=nm)
ax.axhline(1.0, color="k", ls="--", lw=2, label="rebalance = half-life")
ax.set_yscale("log"); ax.set_xlabel("trading cost (bp of turnover)")
ax.set_ylabel("best rebalance period / half-life (log)"); ax.legend(fontsize=8)
plt.show()
print(d.pivot(index="cost_bps", columns="signal", values="best_rebalance")
      .to_string())
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
nm = min(profiles, key=lambda k: st.fit_half_life(profiles[k]).get(
    "half_life", np.inf))
d0 = profiles[nm]
f = st.fit_half_life(d0)
u = st.decay_uncertainty(sigs[nm], R, n_boot=40)
resid = st._residual_correlation(R)
g = st.grinold_check(sigs[nm], R, f["half_life"],
                     rebalance=max(int(round(f["half_life"])), 1))
sw = st.rebalance_sweep(sigs[nm], R, f["half_life"],
                        periods=(1, 2, 3, 5, 8, 13, 21, 42, 63, 126), cost_bps=10.0)
hls = {k: st.fit_half_life(v).get("half_life", np.nan) for k, v in profiles.items()}
hls = {k: v for k, v in hls.items() if np.isfinite(v)}
pd.DataFrame({
    "fastest signal": [min(hls, key=hls.get)],
    "its half-life (days)": [min(hls.values())],
    "slowest signal": [max(hls, key=hls.get)],
    "its half-life (days)": [max(hls.values())],
    "spread": [max(hls.values()) / min(hls.values())],
    "half-life 90% interval, low": [u["p05"]],
    "half-life 90% interval, high": [u["p95"]],
    "residual correlation": [resid],
    "naive breadth": [g["naive_breadth"]],
    "honest breadth": [g["breadth"]],
    "overstatement": [g["naive_breadth"] / g["breadth"]],
    "predicted IR (naive)": [g["predicted_ir_naive"]],
    "predicted IR (corrected)": [g["predicted_ir"]],
    "realised IR": [g["realised_ir"]],
    "best rebalance (days)": [int(sw["ir"].idxmax())],
    "GP closed-form trade rate": [st.gp_trade_rate(f["half_life"], 10.0)],
}).T.rename(columns={0: "value"})
"""
        ),
        md(
            r"""

## 5 · Going further

- **Clarke, de Silva & Thorley (2002)** add the transfer coefficient to Grinold's law, which is
  what remains of the gap in §3.5 once breadth is counted properly. Estimating it directly —
  the correlation between the signal and the actual positions taken — would close the loop.
- **Non-exponential decay.** Reversal decays faster than exponential at short horizons and
  momentum slower at long ones. A two-parameter fit would describe both better, at the cost of
  a half-life that no longer summarises anything.
- **Gârleanu-Pedersen with a real cost model.** Their result assumes quadratic costs. Almgren-
  Chriss market impact is concave in participation, which would push the optimal rate lower for
  large books and is where capacity enters the story.
- **Combine signals with different half-lives.** The interesting portfolio problem is not
  choosing a trading rate for one signal but blending a fast and a slow one, where the fast
  signal's turnover is partly offset by the slow one's stability. That is the natural sequel and
  it needs the machinery here as its input.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
