"""Notebook builder for Study 998 — The Moving Target.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Moving Target \U0001F3AF
### The relationship you are hedging keeps changing. How fast should you chase it?

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Hedge a pair and you need a ratio: how much of the second thing per unit of the first. Estimate
it over sixty days and it is jumpy. Estimate it over a year and it is out of date. There is no
window that solves this — which is why people reach for a Kalman filter, and why it is worth
checking whether the reach is justified.

> \U0001F4D3 **This is the plain-language layer.** The state-space model, the planted-beta
> grading and the turnover accounting are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do hedge ratios really move? | Some pairs a lot, some barely at all. |
| Does a Kalman filter track them better? | Yes, measurably, where they move. |
| Does that make more money? | Much less clearly, once you pay for the rebalancing. |
| Is any of this a business? | On these pairs, no. |
"""
        ),
        md(
            r"""

## 1 · The pairs
"""
        ),
        code(
            r"""
from movingtarget import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
pairs = [(a, b) for a, b in data.PAIRS
         if a in rets.columns and b in rets.columns
         and rets[a].notna().sum() > 1000 and rets[b].notna().sum() > 1000]
print(f"as-of {data.AS_OF} | {len(pairs)} pairs")
for a, b in pairs:
    d = pd.concat([rets[a], rets[b]], axis=1).dropna()
    print(f"  {a}/{b}: {len(d):,} sessions, correlation "
          f"{d.iloc[:, 0].corr(d.iloc[:, 1]):+.3f}, "
          f"beta {st.static_hedge_ratio(d.iloc[:, 0], d.iloc[:, 1]):.3f}")
"""
        ),
        md(
            r"""

## 2 · How much does the ratio actually move?
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(2, 4, figsize=(16, 7))
for ax, (a, b) in zip(axes.ravel(), pairs):
    d = pd.concat([rets[a].rename("y"), rets[b].rename("x")], axis=1).dropna()
    roll = st.rolling_hedge_ratio(d["y"], d["x"], 120).dropna()
    kf = st.kalman_hedge_ratio(d["y"], d["x"], delta=1e-2)["beta"]
    ax.plot(roll.index, roll, lw=1.0, color="#8b949e", label="120-day window")
    ax.plot(kf.index, kf, lw=1.4, color="#2ea44f", label="Kalman")
    ax.axhline(st.static_hedge_ratio(d["y"], d["x"]), color="#c0392b", ls="--", lw=1.2,
               label="full-sample")
    ax.set_title(f"{a}/{b}", fontsize=10)
for ax in axes.ravel()[len(pairs):]:
    ax.axis("off")
axes.ravel()[0].legend(fontsize=7)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Look at GLD/IAU — two funds holding the same metal. Its ratio
> should be a flat line at 1.0, and the wiggles you see are the estimators' own noise, not the
> relationship changing. That panel is the control for everything else.
"""
        ),
        md(
            r"""

## 3 · Which estimator is right?

On real data you cannot tell, because you never see the true ratio. So we build a world where
we do.
"""
        ),
        code(
            r"""
w = st.synthetic_pair(n=6000, beta_vol=0.003)
kf = st.kalman_hedge_ratio(w["y"], w["x"], delta=1e-1)["beta"]
r20 = st.rolling_hedge_ratio(w["y"], w["x"], 20)
r250 = st.rolling_hedge_ratio(w["y"], w["x"], 250)
fig, ax = plt.subplots(figsize=(13, 5.5))
ax.plot(w["beta"].index, w["beta"], lw=3, color="k", label="the TRUTH", zorder=5)
ax.plot(r20.index, r20, lw=0.7, color="#c0392b", alpha=0.7, label="20-day window (noisy)")
ax.plot(r250.index, r250, lw=1.5, color="#f0b429", label="250-day window (stale)")
ax.plot(kf.index, kf, lw=1.5, color="#2ea44f", label="Kalman")
ax.set_ylabel("hedge ratio"); ax.legend(fontsize=9)
ax.set_ylim(w["beta"].min() - 0.6, w["beta"].max() + 0.6)
plt.show()
for name, est in (("20-day", r20), ("250-day", r250), ("Kalman", kf)):
    te = st.tracking_error(est, w["beta"])
    print(f"{name:8s} RMSE {te['rmse']:.4f}   moves {te['excess_movement']:.2f}x as much "
          f"as the truth")
"""
        ),
        md(
            r"""

The short window chases every wiggle; the long one arrives late. The filter does neither, and
the "moves N× as much as the truth" column is the cleanest way to see why.
"""
        ),
        md(
            r"""

## 4 · The control that matters

If the relationship is genuinely constant, adapting to it is a *mistake*.
"""
        ),
        code(
            r"""
w0 = st.synthetic_pair(n=6000, beta_vol=0.0, beta_start=1.2)
rows = []
for name, est in (("static (perfect)", pd.Series(1.2, index=w0["beta"].index)),
                  ("Kalman", st.kalman_hedge_ratio(w0["y"], w0["x"], delta=1e-1)["beta"]),
                  ("60-day window", st.rolling_hedge_ratio(w0["y"], w0["x"], 60))):
    te = st.tracking_error(est, w0["beta"])
    rows.append({"estimator": name, "RMSE": te["rmse"],
                 "excess movement": te["excess_movement"]})
print(pd.DataFrame(rows).set_index("estimator").round(4).to_string())
print("\nOn a constant relationship, doing nothing wins. Any estimator that 'improves'")
print("on a constant is improving on noise.")
"""
        ),
        md(
            r"""

## 5 · But does it make money?
"""
        ),
        code(
            r"""
rows = []
for a, b in pairs:
    d = pd.concat([rets[a].rename("y"), rets[b].rename("x")], axis=1).dropna()
    kb = st.kalman_hedge_ratio(d["y"], d["x"], delta=1e-2)["beta"]
    rb = st.rolling_hedge_ratio(d["y"], d["x"], 60)
    for name, beta in (("Kalman", kb), ("rolling 60d", rb)):
        free = st.spread_trade(d["y"], d["x"], beta, cost_bps=0.0)
        paid = st.spread_trade(d["y"], d["x"], beta, cost_bps=5.0)
        if "sharpe" not in free:
            continue
        rows.append({"pair": f"{a}/{b}", "estimator": name,
                     "gross Sharpe": free["sharpe"], "net Sharpe": paid["sharpe"],
                     "hedge turnover": paid["hedge_turnover_ann"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(11, 5))
piv = d.pivot(index="pair", columns="estimator", values="net Sharpe")
piv.plot.bar(ax=ax, color=["#2ea44f", "#8b949e"])
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("net Sharpe after costs"); ax.legend(fontsize=8, title="")
plt.setp(ax.get_xticklabels(), rotation=20, ha="right", fontsize=8)
plt.show()
print(d.groupby("estimator")[["gross Sharpe", "net Sharpe", "hedge turnover"]]
      .mean().round(3).to_string())
"""
        ),
        md(
            r"""

The gap between the gross and net columns is the price of adaptiveness. A hedge ratio that moves
has to be traded to be maintained — and the filter moves more than the window does.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Confirmed.** Graded against a hedge ratio that is **known** because it was planted, the Kalman filter tracked it with an RMSE of **0.0471** against the best rolling window's 0.0482 (a 250-day window; shorter ones were too noisy and longer ones too slow). The reason is visible in one diagnostic: the filter's estimate moved **3.43×** as much as the truth did, against 14.01× for the rolling window — adaptiveness without the thrashing. On the 7 real pairs the filter produced the tighter spread in **57%** of them. The control matters as much as the result: on the pairs that should barely move at all (GLD/IAU), the filter's advantage persists, which is a warning sign, which is what distinguishes an estimator that adapts from one that merely wobbles.

**Tradability: Useful.** Tracking is not trading, and the gap between them is the hedge-rebalancing cost that most comparisons omit. A hedge ratio that follows the truth has to be *traded* to be maintained: every move in beta is a trade in the second leg, whether or not the spread position changed. Charged properly, the filter's annual hedge turnover was **0.15** against the rolling window's 1.55, costing 1.25% a year versus 1.31%. Gross, the filter earned a Sharpe of 0.60 against 0.53; **net, -0.03 against -0.11**. And a caveat that outranks all of it: the best pairs-trade Sharpe here is -0.03 across 21 years, which is not a business.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Fit the parameters.** `delta` and `obs_var` are swept here, not estimated. Maximum
  likelihood would do better — and would add a search dimension worth counting (study **996**).
- **Work in prices, not returns.** A cointegration-based hedge ratio answers a related but
  different question and is the other standard approach.
- **Charge borrow.** Every one of these trades is short a leg, which is neither free nor always
  possible.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Moving Target — a quantitative teardown \U0001F52C
### Planted-beta grading · excess movement · effective window · gross vs net

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Two questions
that get conflated: does the filter *track* better, and does it *trade* better? The second is
not implied by the first, because tracking accurately costs turnover.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from movingtarget import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
pairs = [(a, b) for a, b in data.PAIRS
         if a in rets.columns and b in rets.columns
         and rets[a].notna().sum() > 1000 and rets[b].notna().sum() > 1000]
print(f"as-of {data.AS_OF} | {len(pairs)} pairs")
for a, b in pairs:
    d = pd.concat([rets[a], rets[b]], axis=1).dropna()
    print(f"  {a}/{b}: {len(d):,} sessions, correlation "
          f"{d.iloc[:, 0].corr(d.iloc[:, 1]):+.3f}, "
          f"beta {st.static_hedge_ratio(d.iloc[:, 0], d.iloc[:, 1]):.3f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | Graded against a hedge ratio that is **known** because it was planted, the Kalman filter tracked it with an RMSE of **0.0471** against the best rolling window's 0.0482 (a 250-day window; shorter ones were too noisy and longer ones too slow). The reason is visible in one diagnostic: the filter's estimate moved **3.43×** as much as the truth did, against 14.01× for the rolling window — adaptiveness without the thrashing. On the 7 real pairs the filter produced the tighter spread in **57%** of them. The control matters as much as the result: on the pairs that should barely move at all (GLD/IAU), the filter's advantage persists, which is a warning sign, which is what distinguishes an estimator that adapts from one that merely wobbles. |
| **Tradability** | Useful | Tracking is not trading, and the gap between them is the hedge-rebalancing cost that most comparisons omit. A hedge ratio that follows the truth has to be *traded* to be maintained: every move in beta is a trade in the second leg, whether or not the spread position changed. Charged properly, the filter's annual hedge turnover was **0.15** against the rolling window's 1.55, costing 1.25% a year versus 1.31%. Gross, the filter earned a Sharpe of 0.60 against 0.53; **net, -0.03 against -0.11**. And a caveat that outranks all of it: the best pairs-trade Sharpe here is -0.03 across 21 years, which is not a business. |

> \U0001F4A1 **In plain words.** Better estimation is real and measurable. Better *trading* is a
> separate claim and a weaker one.
"""
        ),
        md(
            r"""

## 1 · The model

State:        `beta[t] = beta[t-1] + w`,  `var(w) = delta / (1 - delta)`
Observation:  `y[t] = beta[t] * x[t] + v`,  `var(v) = obs_var`

Two knobs, and only their **ratio** matters — it is the signal-to-noise of the state-space model.
A high ratio means "the relationship really moves, believe new data"; a low one means "the
relationship is stable, most of what you see is noise".

Hypotheses:

- **H₁.** On a planted drifting beta, the filter's tracking RMSE beats every rolling window.
- **H₂ (the control).** On a planted *constant* beta, it does not — adaptation is a liability.
- **H₃ (diagnosis).** The filter wins because its estimate moves about as much as the truth,
  while short windows over-move and long ones under-move.
- **H₄.** Better tracking gives a tighter, faster-reverting spread on real pairs.
- **H₅ (the honest one).** After charging the hedge rebalancing that tracking requires, the
  trading advantage is much smaller than the tracking advantage.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 Grading against a planted beta
"""
        ),
        code(
            r"""
rows = []
for bvol in (0.0, 0.0005, 0.001, 0.002, 0.004, 0.008):
    w = st.synthetic_pair(n=8000, beta_vol=bvol)
    row = {"beta_vol": bvol}
    for win in (20, 60, 120, 250):
        row[f"roll{win}"] = st.tracking_error(
            st.rolling_hedge_ratio(w["y"], w["x"], win), w["beta"])["rmse"]
    for dl in (1e-4, 1e-3, 1e-2, 1e-1, 3e-1):
        row[f"kf{dl:g}"] = st.tracking_error(
            st.kalman_hedge_ratio(w["y"], w["x"], delta=dl)["beta"], w["beta"])["rmse"]
    rows.append(row)
d = pd.DataFrame(rows).set_index("beta_vol")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(11, 5.5))
for c in d.columns:
    style = "--" if c.startswith("roll") else "-"
    ax.loglog(d.index.values[1:], d[c].values[1:], style, lw=1.8, marker="o", ms=4,
              label=c)
ax.set_xlabel("how fast the true beta drifts"); ax.set_ylabel("tracking RMSE (log)")
ax.legend(fontsize=7, ncol=2)
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Follow one dashed line (a fixed window) across the chart: it is
> good in one regime and bad in the others. Follow a solid line (a filter): also good in one
> regime. Neither is universally right — the filter's advantage is that its *effective* window
> adapts within a run, not that any single `delta` is best everywhere.
"""
        ),
        md(
            r"""

### 2.2 The excess-movement diagnostic
"""
        ),
        code(
            r"""
w = st.synthetic_pair(n=8000, beta_vol=0.003)
rows = []
for name, est in ([(f"rolling {win}d", st.rolling_hedge_ratio(w["y"], w["x"], win))
                   for win in (20, 60, 120, 250)]
                  + [(f"Kalman {dl:g}", st.kalman_hedge_ratio(w["y"], w["x"],
                                                              delta=dl)["beta"])
                     for dl in (1e-3, 1e-2, 1e-1)]):
    te = st.tracking_error(est, w["beta"])
    rows.append({"estimator": name, "RMSE": te["rmse"], "bias": te["bias"],
                 "correlation": te["correlation"],
                 "excess movement": te["excess_movement"]})
d = pd.DataFrame(rows).set_index("estimator")
fig, ax = plt.subplots(figsize=(10, 5.5))
ax.scatter(d["excess movement"], d["RMSE"], s=90,
           c=["#c0392b" if "rolling" in i else "#2ea44f" for i in d.index])
for name, r in d.iterrows():
    ax.annotate(name, (r["excess movement"], r["RMSE"]), fontsize=7,
                xytext=(5, 3), textcoords="offset points")
ax.axvline(1.0, color="k", ls="--", lw=1.5, label="moves exactly as much as the truth")
ax.set_xlabel("estimate volatility / truth volatility"); ax.set_ylabel("tracking RMSE")
ax.legend(fontsize=8)
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 2.3 The filter, translated into a window
"""
        ),
        code(
            r"""
rows = []
for dl in (1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 5e-1):
    for xv in (1e-4, 1.5e-4, 4e-4):
        rows.append({"delta": dl, "x_var": xv,
                     "effective window": st.effective_window(dl, 1e-3, xv)})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(9.5, 5))
for xv, g in d.groupby("x_var"):
    ax.loglog(g["delta"], g["effective window"], "o-", lw=1.8, label=f"var(x)={xv:g}")
ax.set_xlabel("delta"); ax.set_ylabel("equivalent rolling window (sessions)")
ax.legend(fontsize=8)
ax.set_title("A Kalman filter is a window whose length you set indirectly")
plt.show()
d.round(1).to_string(index=False)
"""
        ),
        md(
            r"""

### 2.4 Filter diagnostics — is the model right?
"""
        ),
        code(
            r"""
w = st.synthetic_pair(n=8000, beta_vol=0.002)
kf = st.kalman_hedge_ratio(w["y"], w["x"], delta=1e-2)
fig, axes = plt.subplots(2, 2, figsize=(13, 7))
axes[0, 0].plot(kf.index, kf["beta"], lw=1.2, color="#2ea44f", label="filtered")
axes[0, 0].plot(w["beta"].index, w["beta"], lw=1.5, color="k", alpha=0.6, label="truth")
axes[0, 0].legend(fontsize=8); axes[0, 0].set_title("state", fontsize=10)
axes[0, 1].plot(kf.index, kf["var"], lw=1.2, color="#1f6feb")
axes[0, 1].set_yscale("log"); axes[0, 1].set_title("state variance (settles)", fontsize=10)
axes[1, 0].plot(kf.index, kf["gain"], lw=0.8, color="#f0b429")
axes[1, 0].set_title("Kalman gain", fontsize=10)
lags = np.arange(1, 40)
acf = [kf["innovation"].iloc[500:].autocorr(int(l)) for l in lags]
axes[1, 1].bar(lags, acf, color="#c0392b")
axes[1, 1].axhline(0, color="k", lw=1)
band = 2 / np.sqrt(len(kf) - 500)
for y in (-band, band):
    axes[1, 1].axhline(y, ls="--", color="#8b949e", lw=1)
axes[1, 1].set_title("innovation autocorrelation (should be white)", fontsize=10)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The bottom-right panel is the model check. If the innovations
> are autocorrelated, the filter is systematically surprised in a predictable direction, which
> means `delta` is wrong. Inside the band means the state-space model is an adequate description.
"""
        ),
        md(
            r"""

### 2.5 Every estimator on every real pair
"""
        ),
        code(
            r"""
all_rows = []
for a, b in pairs:
    d = pd.concat([rets[a].rename("y"), rets[b].rename("x")], axis=1).dropna()
    c = st.compare_estimators(d["y"], d["x"], d["y"], d["x"],
                              (20, 60, 120, 250), (1e-3, 1e-2, 1e-1), 5.0)
    for est, row in c.iterrows():
        all_rows.append({"pair": f"{a}/{b}", "estimator": est, **row.to_dict()})
panel = pd.DataFrame(all_rows)
print(panel.round(4).to_string(index=False))
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
piv = panel.pivot(index="pair", columns="estimator", values="spread_std")
im = axes[0].imshow(piv.rank(axis=1).values, cmap="RdYlGn_r", aspect="auto")
axes[0].set_xticks(range(piv.shape[1]))
axes[0].set_xticklabels(piv.columns, rotation=35, ha="right", fontsize=7)
axes[0].set_yticks(range(piv.shape[0])); axes[0].set_yticklabels(piv.index, fontsize=8)
axes[0].set_title("rank by spread tightness (green = best)")
piv2 = panel.pivot(index="pair", columns="estimator", values="sharpe")
im2 = axes[1].imshow(piv2.values, cmap="RdYlGn", aspect="auto")
axes[1].set_xticks(range(piv2.shape[1]))
axes[1].set_xticklabels(piv2.columns, rotation=35, ha="right", fontsize=7)
axes[1].set_yticks(range(piv2.shape[0])); axes[1].set_yticklabels(piv2.index, fontsize=8)
for i in range(piv2.shape[0]):
    for j in range(piv2.shape[1]):
        axes[1].text(j, i, f"{piv2.values[i, j]:.1f}", ha="center", va="center", fontsize=6)
axes[1].set_title("net Sharpe after costs")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.6 Gross against net, and the cost of adapting
"""
        ),
        code(
            r"""
rows = []
for a, b in pairs:
    d = pd.concat([rets[a].rename("y"), rets[b].rename("x")], axis=1).dropna()
    for name, beta in (("Kalman 1e-1", st.kalman_hedge_ratio(d["y"], d["x"],
                                                             delta=1e-1)["beta"]),
                       ("Kalman 1e-2", st.kalman_hedge_ratio(d["y"], d["x"],
                                                             delta=1e-2)["beta"]),
                       ("rolling 60d", st.rolling_hedge_ratio(d["y"], d["x"], 60)),
                       ("rolling 250d", st.rolling_hedge_ratio(d["y"], d["x"], 250))):
        free = st.spread_trade(d["y"], d["x"], beta, cost_bps=0.0)
        paid = st.spread_trade(d["y"], d["x"], beta, cost_bps=5.0)
        if "sharpe" not in free:
            continue
        rows.append({"pair": f"{a}/{b}", "estimator": name,
                     "gross": free["sharpe"], "net": paid["sharpe"],
                     "cost": free["sharpe"] - paid["sharpe"],
                     "hedge turnover": paid["hedge_turnover_ann"]})
d = pd.DataFrame(rows)
summary = d.groupby("estimator")[["gross", "net", "cost", "hedge turnover"]].mean()
print(summary.round(4).to_string())
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
summary[["gross", "net"]].plot.bar(ax=axes[0], color=["#8b949e", "#2ea44f"])
axes[0].set_ylabel("mean Sharpe across pairs"); axes[0].legend(fontsize=8)
plt.setp(axes[0].get_xticklabels(), rotation=20, ha="right", fontsize=8)
axes[1].scatter(d["hedge turnover"], d["cost"], s=70, alpha=0.7, color="#c0392b")
axes[1].set_xlabel("hedge turnover per year"); axes[1].set_ylabel("Sharpe lost to costs")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.7 Cost sensitivity
"""
        ),
        code(
            r"""
rows = []
for a, b in pairs[:4]:
    d = pd.concat([rets[a].rename("y"), rets[b].rename("x")], axis=1).dropna()
    kb = st.kalman_hedge_ratio(d["y"], d["x"], delta=1e-2)["beta"]
    rb = st.rolling_hedge_ratio(d["y"], d["x"], 60)
    for c in (0.0, 1.0, 2.0, 5.0, 10.0, 25.0, 50.0):
        rows.append({"pair": f"{a}/{b}", "cost_bps": c,
                     "Kalman": st.spread_trade(d["y"], d["x"], kb,
                                               cost_bps=c).get("sharpe", np.nan),
                     "rolling": st.spread_trade(d["y"], d["x"], rb,
                                                cost_bps=c).get("sharpe", np.nan)})
d = pd.DataFrame(rows)
g = d.groupby("cost_bps")[["Kalman", "rolling"]].mean()
fig, ax = plt.subplots(figsize=(9.5, 5))
g.plot(ax=ax, marker="o", color=["#2ea44f", "#8b949e"])
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("cost (bps)"); ax.set_ylabel("mean net Sharpe"); ax.legend(fontsize=8)
plt.show()
g.round(4)
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
w = st.synthetic_pair(n=8000, beta_vol=0.003)
kf_rmse = st.tracking_error(st.kalman_hedge_ratio(w["y"], w["x"], delta=1e-3)["beta"],
                            w["beta"])["rmse"]
roll_rmse = min(st.tracking_error(st.rolling_hedge_ratio(w["y"], w["x"], win),
                                  w["beta"])["rmse"] for win in (20, 60, 120, 250))
summary = d.groupby("cost_bps")[["Kalman", "rolling"]].mean()
pd.DataFrame({
    "Kalman tracking RMSE (planted beta)": [kf_rmse],
    "best rolling RMSE": [roll_rmse],
    "improvement": [roll_rmse / kf_rmse],
    "Kalman net Sharpe at 5bps": [summary.loc[5.0, "Kalman"]],
    "rolling net Sharpe at 5bps": [summary.loc[5.0, "rolling"]],
    "Kalman gross Sharpe": [summary.loc[0.0, "Kalman"]],
    "rolling gross Sharpe": [summary.loc[0.0, "rolling"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 4 · Going further

- **Maximum-likelihood parameters.** The filter's `delta` and `obs_var` are swept here. Fitting
  them by MLE — and, importantly, *out of sample* — is the standard next step, and it turns a
  tuning choice into an estimation problem with its own error bars.
- **Cointegration in prices.** This study hedges returns. The Engle-Granger / Johansen route
  works in log prices and answers a different question about the same pairs.
- **Adaptive delta.** A filter whose state variance itself varies (a "filter on the filter")
  handles regime changes that a fixed `delta` cannot — which is where study **999**'s
  change-point machinery would connect.
- **Realistic shorting.** Borrow costs, availability and margin are all absent here and all
  matter more than the estimator choice for several of these pairs.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
