"""Notebook builder for Study 1016 — Stairs Up, Elevator Down.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    python -m jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes: 01 is the
plain-language layer, 02 carries the inference, the nulls, the mechanism and the costs. The
verdict badges in the heroes are the ones the real run earned, and every real-tape number
quoted in prose lives in the single ``RESULTS`` dict below, copied from ``docs/results.md``
(regenerated by ``examples/verify.py``) — never typed by hand into a sentence. The code cells
recompute the figures live from the frozen tapes; the heavier Monte Carlo runs use fewer
replications than ``verify.py``, so their p-values are quoted from ``RESULTS``.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Real-tape headline, mirrored from docs/results.md (as-of 2022-11-30).
RESULTS = {
    "signal": "Mixed", "trad": "Mirage",
    "gm_down10": "18.5", "gm_up10": "13.4", "elev10": "0.73", "elev05": "0.72",
    "elev20": "0.59", "elev10_p_rev": "0.010", "elev10_p": "0.995",
    "nq_elev10": "0.82", "ff_elev10": "0.77",
    "speed10": "1.76", "speed10_p": "0.07", "speed05": "1.49", "speed05_p": "0.01",
    "tr_sum": "-2.85", "tr_t_nw": "-3.39", "tr_t_boot": "-4.04", "tr_t_wins": "-5.19",
    "nq_tr_t": "-3.63", "ff_tr_t": "-1.88", "ff_tr_t_boot": "-2.56", "wk_tr_t": "-2.76",
    "skew_d": "-0.40", "skew_d_ci": "[-0.76, -0.05]", "skew_m": "-0.74",
    "skew_m_ci": "[-1.07, -0.36]", "kelly_d": "-0.043",
    "gjr_gamma_t": "+9.6", "share_tr_gjr": "72%", "share_tr_egarch": "65%",
    "share_tr_garch": "6%", "share_tr_iid": "0%", "share_elev_gjr": "106%",
    "d_sp": "-0.30", "d_nq": "-0.22", "d_ff": "+0.14", "p_ff": "0.03", "d_ff45": "+0.08",
    "p_ff45": "0.23", "d_ff_sym10": "+0.12", "sharpe_sp_rule": "0.04", "sharpe_sp_bh": "0.34",
    "as_of": "2022-11-30",
    # numeric copies for the one chart drawn from the verify.py simulation
    "share_tr_gjr_num": 0.723, "share_tr_egarch_num": 0.651, "share_tr_garch_num": 0.055,
    "share_tr_iid_num": 0.0,
}
R = RESULTS

BADGES = (
    "![Signal: Mixed](https://img.shields.io/badge/Signal-Mixed-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b"
    "?style=flat-square)"
)

BOOT = r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.2)
plt.rcParams["figure.dpi"] = 80
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
pd.set_option("display.width", 160)
from stairs import data, strategy as st
UP, DOWN, GREY = "#2ea44f", "#c0392b", "#8b949e"
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(f"""
# Stairs Up, Elevator Down \U0001F6D7
### "Markets take the stairs up and the elevator down." We timed both.

{BADGES}

Every trader has heard it: rallies are slow and orderly, crashes are sudden. We checked the
saying on three real tapes — the S&P 500 since 1990, the Nasdaq since 1999 and a century of US
market returns since 1926 — and found something more interesting than a yes or a no. The market
really is **lopsided in time**. But the fastest ten percent on the tape is not the fall from the
top. It is the bounce off the bottom.

> \U0001F4D3 **This is the plain-language layer.** The statistics, the null worlds and the
> trading race are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it, from
> frozen, fingerprinted tapes (as-of {R['as_of']}).
"""),
        code(BOOT),
        md(f"""
## The answer first \U0001F6D7

| Question | Answer |
|---|---|
| Is the index path lopsided in time? | **Yes** — run it backwards and it looks measurably different. |
| Do falls cover 10% faster than rises do? | **No — the reverse.** Losing 10% from a peak took ~{R['gm_down10']} sessions; regaining 10% off a low took ~{R['gm_up10']}. |
| So where does the proverb come from? | Whole bull runs last a long time; whole sell-offs are short and steep. |
| What causes the lopsidedness? | Volatility jumps after a fall — and stays high right at the bottom. |
| Can you trade it? | Not as a holder: a "get out fast, get back in slowly" rule lost to buy-and-hold on daily data. |
"""),
        md("""
## 1 · The claim

*"Stocks take the stairs up and the elevator down."* It's a line from trading floors and
financial TV, and it means more than "crashes happen". It says the **shape** of a market's path
has a direction: a slow, steady climb of small steps, then a drop that does in days what the
climb did in months. If you filmed the index and played the film backwards, you'd notice —
slow slides and sudden rockets.

That last sentence is the strongest form of the claim, and the one we test: the index path is
**not the same forwards and backwards**.
"""),
        md("""
## 2 · So what?

If it's true, three things follow. Risk is lopsided — the next 10% down arrives faster than the
next 10% up, which matters for anyone with a stop-loss or a margin call. It explains why
**insurance against a fall (a put option) costs more** than a bet on a rise of the same size.
And it hints at a rule: if falls are fast and rises slow, you could step out quickly and step
back in at leisure, missing little of the climb.
"""),
        md("""
## 3 · How we'd know

We decided the tests before running them:

- **Time it.** Cut the price path into rises and falls of at least 5%, 10% or 20%. For each, count
  the trading days it took to cover the first 10% (gaining from a low, or losing from a high).
- **Play it backwards.** A standard statistic (Ramsey & Rothman, 1996) is exactly zero for a path
  that looks the same in both directions, and flips sign when you reverse the tape.
- **Make fake markets.** Build worlds where we *know* the cause — with and without "volatility
  jumps after a fall" — and see which ones look like the real thing.
- **Trade it**, with a rule fixed in advance, after costs, against just holding.

*Mirage* would be: no difference forwards and backwards, or a difference no fake world can
explain, or a rule that only works before costs.
"""),
        md("""
## 4 · The teardown

### 4.1 The film, forwards and backwards
"""),
        code(r"""
sp = data.load_sp500()
lp = np.log(sp)
rev = pd.Series(lp.to_numpy()[::-1], index=lp.index)     # the same film, run backwards
fig, ax = plt.subplots(1, 2, figsize=(13, 4.6), sharey=True)
ax[0].plot(lp.index, lp, color="k", lw=0.9)
ax[0].set_title("S&P 500 (log scale), as it happened")
ax[1].plot(rev.index, rev, color=GREY, lw=0.9)
ax[1].set_title("the same path, played backwards")
for a in ax:
    a.set_xticks([])
ax[0].set_ylabel("log price")
plt.tight_layout(); plt.show()
print(f"{len(sp):,} sessions, {sp.index[0].date()} to {sp.index[-1].date()} (price index, no dividends)")
"""),
        md("""
Look at 2008 and 2020 on the left: cliff edges. On the right they become sudden rockets, and the
long climbs become long slides. Your eye already says the two films differ. The rest of this
notebook asks how much, in which direction, and why.
"""),
        md("""
### 4.2 How long does it take to gain 10%, and to lose 10%?
"""),
        code(r"""
L = st.legs(lp.to_numpy(), np.log1p(0.10))
up, dn = L[L["dir"] == 1]["fp_days"], L[L["dir"] == -1]["fp_days"]
fig, ax = plt.subplots(figsize=(10, 4.8))
bins = np.logspace(0, np.log10(max(up.max(), dn.max()) + 1), 18)
ax.hist(dn, bins=bins, alpha=0.6, color=DOWN, label=f"lose 10% from a peak ({len(dn)} falls)")
ax.hist(up, bins=bins, alpha=0.6, color=UP, label=f"gain 10% off a low ({len(up)} rises)")
ax.set_xscale("log"); ax.set_xlabel("trading days to cover the first 10%")
ax.set_ylabel("count"); ax.legend()
plt.show()
gm = lambda s: float(np.exp(np.log(s).mean()))
print(f"typical time to LOSE 10% from a peak: {gm(dn):.1f} sessions")
print(f"typical time to GAIN 10% off a low:   {gm(up):.1f} sessions")
"""),
        md(f"""
Here is the surprise. Measured like-for-like — the same 10%, timed from the turning point — the
**rebound is faster than the fall**: about {R['gm_up10']} sessions to gain it against
{R['gm_down10']} to lose it. The same holds at 5% and 20%, on the Nasdaq, and on a century of
monthly data. Compared with fake markets that have the same day sizes in random directions, the
real tape sits at the "rebounds are fast" end (only {R['elev10_p_rev']} of fake worlds go that
far).

> \U0001F52C **For the quants.** Elevator ratio = geometric-mean up time ÷ down time =
> {R['elev10']}× at 10%. Sign-flip Monte Carlo null (keeps |r_t|, drift and vol clustering):
> one-sided p = {R['elev10_p']} in the elevator direction, {R['elev10_p_rev']} in the reverse one.
"""),
        md("""
### 4.3 Then where does the proverb come from?
"""),
        code(r"""
full = L.dropna(subset=["dur_days"]).copy()
full["speed"] = full["move"].abs() / full["dur_days"] * 100
fig, ax = plt.subplots(1, 2, figsize=(13, 4.6))
for d, c, lab in ((1, UP, "whole rises"), (-1, DOWN, "whole falls")):
    f = full[full["dir"] == d]
    ax[0].scatter(f["dur_days"], f["move"].abs() * 100, color=c, s=40, alpha=0.8, label=lab)
ax[0].set_xscale("log"); ax[0].set_xlabel("length of the whole move (sessions)")
ax[0].set_ylabel("size of the whole move (%, log)"); ax[0].legend()
ax[1].boxplot([full[full["dir"] == 1]["speed"], full[full["dir"] == -1]["speed"]])
ax[1].set_xticks([1, 2]); ax[1].set_xticklabels(["whole rises", "whole falls"])
ax[1].set_ylabel("average speed (% per session)")
plt.tight_layout(); plt.show()
print(full.groupby("dir")[["dur_days", "speed"]].median().rename(index={1: "rises", -1: "falls"}))
"""),
        md(f"""
The proverb is about the **whole** move. Bull runs go on for months and years, so their
*average* pace is slow; sell-offs end sooner, so their average pace is steep — about
{R['speed10']}× faster per day. That is the stairs and the elevator people remember. But the
first 10% of a bounce off a bottom is quicker than the first 10% of a slide off a top.
"""),
        md("""
### 4.4 Played backwards, the numbers flip
"""),
        code(r"""
r = st.log_returns(sp).to_numpy()
tr = st.tr_stats(r, K=10, n_boot=200)
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.bar(tr["per_lag"].index, tr["per_lag"]["tr"], color=DOWN, label="forwards (the real tape)")
x_rev = st.standardise(r)[::-1]
rev_lag = st.tr_products(x_rev, 10).mean(axis=0)
ax.bar(tr["per_lag"].index, rev_lag, color=GREY, alpha=0.6, label="backwards")
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("days apart"); ax.set_ylabel("time-asymmetry score")
ax.legend(); plt.show()
print(f"total score forwards {tr['tr_sum']:+.2f}, backwards {tr['tr_sum_reversed']:+.2f}")
"""),
        md(f"""
A path that looked the same both ways would score zero on every bar. The real tape scores
negative on all ten — and exactly the mirror image when reversed. The odds of that by luck are
tiny: the robust t-statistic is {R['tr_t_nw']} (the desk's bar is 2), and the Nasdaq says the
same ({R['nq_tr_t']}). So the market **is** lopsided in time. Just not in the way the proverb
says.
"""),
        md("""
### 4.5 What makes it lopsided? Build fake markets and see
"""),
        code(r"""
mech = [("volatility jumps after a fall\n(GJR-GARCH)", __GJR__), ("same, EGARCH form", __EG__),
        ("volatility clusters,\nno direction (GARCH)", __GA__), ("pure coin flips\n(i.i.d.)", __IID__)]
fig, ax = plt.subplots(figsize=(10, 4.4))
ax.barh([m[0] for m in mech][::-1], [100 * m[1] for m in mech][::-1],
        color=[GREY, GREY, DOWN, DOWN])
ax.axvline(100, color="k", ls="--", lw=1.5, label="the real tape")
ax.set_xlabel("% of the real time-asymmetry the fake market reproduces"); ax.legend()
plt.show()
""".replace("__GJR__", str(R["share_tr_gjr_num"])).replace("__EG__", str(R["share_tr_egarch_num"]))
          .replace("__GA__", str(R["share_tr_garch_num"])).replace("__IID__", str(R["share_tr_iid_num"]))),
        md(f"""
*(Shares quoted from the simulation in `docs/results.md`; the quants notebook re-runs it.)*

Only worlds where **volatility rises more after a fall than after a rise** — the "leverage
effect" — look like the real thing: they reproduce about {R['share_tr_gjr']} of the asymmetry
score, and they even get the fast-rebound surprise right. A world where calm and storm come in
clusters but don't care about direction reproduces none of it ({R['share_tr_garch']}); neither
do coin flips. The bottom of a sell-off is where volatility peaks, and high volatility moves
prices quickly — in both directions. That's why the first 10% off the low is fast.
"""),
        md(f"""
## 5 · The verdict

{BADGES}

**Signal — Mixed.** The index path is genuinely irreversible in time (t = {R['tr_t_nw']}),
caused by volatility reacting to falls. But the literal saying — the same distance covered faster
down than up — runs backwards on every tape we have. The verdict splits by which reading of the
proverb you take, and the desk stamps that split as Mixed.

**Tradability — Mirage.** See below.
"""),
        md("""
## 6 · Could you trade it?
"""),
        code(r"""
ff = data.load_ff_market()
sp_t = sp[sp.index <= pd.Timestamp(data.FF_AS_OF)]
rf = data.daily_rf(sp_t.index, ff)
sig = st.zigzag_rule(sp_t, 0.05, 0.10)
bt = st.backtest(sp_t, rf, sig, cost=0.0005, lag=1)
fig, ax = plt.subplots(figsize=(10, 4.8))
ax.plot((1 + bt["ex_bh"]).cumprod(), color="k", lw=1.2, label="just hold (above cash)")
ax.plot((1 + bt["ex_net"]).cumprod(), color=DOWN, lw=1.2,
        label="out fast at -5%, back in slowly at +10% (net)")
ax.set_yscale("log"); ax.set_ylabel("growth of $1 above cash (log)"); ax.legend()
plt.show()
print(f"Sharpe above cash: rule {bt['sharpe_net']:.2f} vs hold {bt['sharpe_bh']:.2f}; "
      f"time invested {bt['time_in']:.0%}")
"""),
        md(f"""
We fixed the rule before looking: **get out after a 5% drop, get back in only after a 10%
rebound** — fast out because the elevator is fast, slow in because the stairs are slow. One day
of delay, realistic costs, cash earning T-bill interest while out. On the S&P 500 it scored a
Sharpe of {R['sharpe_sp_rule']} against {R['sharpe_sp_bh']} for just holding, and it lost on the
Nasdaq too — even though these price-only tapes leave out dividends, which *helps* a rule that
sits in cash. The reason is the study's own finding: the sharpest rallies start right at the
lows, exactly when a "wait for confirmation" rule is sitting out.

On a century of monthly data the rule did beat holding ({R['d_ff']} Sharpe), but almost all of
that is sitting out 1929-32, and a plain symmetric 10%-in/10%-out rule did as well — so the
stairs-and-elevator shape isn't what earned it. What the rule really buys is a smaller worst
drawdown: insurance, paid for in return. **Mirage.**

> \U0001F52C **For the quants.** Paired block-bootstrap of the net excess-Sharpe difference,
> rule − hold: S&P 500 {R['d_sp']}, Nasdaq {R['d_nq']}, Fama-French 1926-2018 {R['d_ff']}
> (p = {R['p_ff']}), 1946-2018 {R['d_ff45']} (p = {R['p_ff45']}).
"""),
        md("""
## 7 · Going further

- **Options.** The desk's frozen tapes carry no option prices. The natural next step is to show
  that the irreversibility measured here lines up with the steepness of the index put skew.
- **Single stocks.** Individual shares are often *positively* skewed. Are they still
  irreversible in the leverage direction?
- **Intraday.** Does the fast-rebound effect hold at the hourly scale, where the 2010 and 2015
  flash events live?

Fork it, change the thresholds in `stairs/strategy.py`, and send a PR.
"""),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(f"""
# Stairs Up, Elevator Down \U0001F6D7 — the machinery
### First passage, Ramsey-Rothman, skew by horizon, a leverage mechanism check, and a pre-registered rule

{BADGES}

The S&P 500 path is time-irreversible at robust t = {R['tr_t_nw']} (block bootstrap
{R['tr_t_boot']}), in the leverage direction, and a fitted GJR-GARCH reproduces ~{R['share_tr_gjr']}
of it while symmetric GARCH and i.i.d. reproduce none. But the literal proverb fails: the first
10% off a trough is covered faster than the first 10% off a peak (elevator ratio
{R['elev10']}×, sign-flip p = {R['elev10_p_rev']} in the reverse tail). The pre-registered
fast-exit / slow-entry rule loses to buy-and-hold on both daily tapes after costs.

> \U0001F4D3 Companion: **[01_for_the_curious.ipynb](01_for_the_curious.ipynb)**. Headline run:
> [`docs/results.md`](../docs/results.md). ⚠️ **Not investment advice.**
"""),
        code(BOOT),
        code(r"""
sp, nq, ff = data.load_sp500(), data.load_nasdaq(), data.load_ff_market()
fi = data.ff_index(ff)
r_sp, r_nq = st.log_returns(sp).to_numpy(), st.log_returns(nq).to_numpy()
r_ff = np.log(fi).diff().dropna().to_numpy()
for k, v in data.PROVENANCE.items():
    print(f"{k:7s} {v['package']:38s} {v['tape']:12s} {v['kind']:52s} sha256 {v['sha256'][:12]}")
print(f"fingerprints: sp {data.fingerprint(sp)}  nq {data.fingerprint(nq)}  ff {data.fingerprint(ff)}")
print(f"S&P {sp.index[0].date()}→{sp.index[-1].date()} | Nasdaq {nq.index[0].date()}→"
      f"{nq.index[-1].date()} | FF {ff.index[0]:%Y-%m}→{ff.index[-1]:%Y-%m}")
"""),
        md("""
## 1 · The claim, formally

Let `p_t` be the log index. The proverb is a statement about the joint law of the path, not its
marginal: `(p_1, …, p_T)` and `(p_T, …, p_1)` differ in distribution (**time irreversibility**),
and the difference has a direction — conditional on a move of a given size, declines are covered
in less time than advances. Negative skewness is neither necessary nor sufficient: an i.i.d.
skewed process is time-reversible, and a sign-symmetric process with a leverage term is not.

Two operational readings, both tested:

1. **First passage.** Inside zig-zag legs at a log-symmetric reversal `h = log(1+X)`, the
   geometric-mean time to traverse `+h` from a trough vs `−h` from a peak. Ratio > 1 = elevator.
2. **Ramsey-Rothman (1996).** On standardised returns `x`, `TR(k) = E[x_t² x_{t−k}] − E[x_t x_{t−k}²]`,
   zero for every k under reversibility, sign-flipped by reversal.
"""),
        md("""
## 2 · So what?

A reliably faster downside would (i) make symmetric risk budgets understate the speed of
losses, (ii) rationalise the index put skew, and (iii) suggest an asymmetric timing rule: exits
must be fast, entries can afford to wait. (iii) is the only claim that pays a holder directly,
and it is the one that has to survive one lag and costs.
"""),
        md("""
## 3 · How we'd know — pre-registered

`strategy.verdict`, fixed before the real run and unit-tested both ways:

| | Condition |
|---|---|
| `tr_ok` | TR sum (K = 10, S&P 500 daily) < 0 with NW t ≤ −2 **and** block-bootstrap t ≤ −2 |
| `dur_ok` | 10% elevator ratio > 1 with sign-flip Monte Carlo p < 0.05 |
| Signal | **Real** both · **Mixed** exactly one · **Weak** neither but both point the elevator way · **None** otherwise |
| Investable | FF 1926-2018: rule beats B&H on net excess Sharpe at p < 0.05 **and** beats its 5%/5% twin, **and** net edge > 0 on both daily tapes |
| Fragile | net edge > 0 on ≥ 2 of 3 tapes |
| Mirage | otherwise |

Nulls: **sign-flip** (keep `|r_t − μ|`, the drift and the volatility clustering; randomise signs
— kills all sign asymmetry) and **permutation** (keep each day, destroy the order — kills
irreversibility, keeps marginal skew).
"""),
        md("""
## 4 · The teardown

### 4.1 First passage: time to gain X% vs time to lose X%
"""),
        code(r"""
rows = []
for name, r in (("S&P 500", r_sp), ("Nasdaq", r_nq), ("FF monthly", r_ff)):
    lp = np.concatenate([[0.0], np.cumsum(r)])
    for x in st.THRESHOLDS:
        s = st.leg_stats(lp, x)
        rows.append({"tape": name, "X": x, "n_up": s["n_up"], "n_down": s["n_down"],
                     "gm_up": s["gm_up"], "gm_down": s["gm_down"],
                     "elevator": s["elevator_ratio"], "speed_ratio": s["speed_ratio"]})
legs_tbl = pd.DataFrame(rows).set_index(["tape", "X"])
legs_tbl
"""),
        code(r"""
# sign-flip null for the S&P 500 at 10% (fewer replications than verify.py — shape, not p-values)
t = st.leg_null_test(r_sp, xs=(0.10,), kind="signflip", n_rep=60, seed=1016)
lp0 = np.concatenate([[0.0], np.cumsum(r_sp)])
null = [st.leg_stats(p, 0.10)["elevator_ratio"] for p in st._null_paths(r_sp, "signflip", 60, 1016)]
fig, ax = plt.subplots(figsize=(10, 4.4))
ax.hist(null, bins=20, color=GREY, alpha=0.8, label="sign-flip null (|r|, drift, clustering kept)")
ax.axvline(t.loc[0.10, "elevator_ratio"], color=UP, lw=3, label="S&P 500")
ax.axvline(1.0, color="k", ls="--", lw=1)
ax.set_xlabel("elevator ratio at 10% (>1: falls faster)"); ax.legend(); plt.show()
"""),
        md(f"""
> \U0001F4A1 **In plain words.** Grey: worlds with the same day sizes, the same calm and stormy
> spells and the same drift, but random up/down signs. Green: the real tape. It sits on the
> *fast-rebound* side of almost every fake world.

From `verify.py` ({200} sign-flip paths): elevator ratio {R['elev10']}× at 10%
({R['elev05']}× at 5%, {R['elev20']}× at 20%); elevator-direction p = {R['elev10_p']}, reverse
p = {R['elev10_p_rev']}. Nasdaq {R['nq_elev10']}×, FF monthly {R['ff_elev10']}×. The permutation
null (skew kept, order destroyed) also sits above 1, so the real tape's rebound speed is an
*order* effect.
"""),
        md("""
### 4.2 The completed leg — the steelman's best reading
"""),
        code(r"""
L = st.legs(lp0, np.log1p(0.10)).dropna(subset=["dur_days"])
L["speed_bp"] = L["move"].abs() / L["dur_days"] * 1e4
fig, ax = plt.subplots(1, 2, figsize=(13, 4.4))
for d, c in ((1, UP), (-1, DOWN)):
    f = L[L["dir"] == d]
    ax[0].scatter(f["start"], f["dur_days"], color=c, s=30, label="up" if d == 1 else "down")
    ax[1].scatter(f["start"], f["speed_bp"], color=c, s=30)
ax[0].set_yscale("log"); ax[0].set_ylabel("leg length (sessions)"); ax[0].legend()
ax[1].set_yscale("log"); ax[1].set_ylabel("|move| per session (bp)")
for a in ax: a.set_xlabel("session index of leg start")
plt.tight_layout(); plt.show()
print(L.groupby("dir")[["dur_days", "speed_bp"]].median())
"""),
        md(f"""
Completed declines are shorter and steeper: median-speed ratio {R['speed10']}× at 10% (sign-flip
p = {R['speed10_p']}) and {R['speed05']}× at 5% (p = {R['speed05_p']}). This is the reading the
proverb survives on — but it is a statement about how long bull legs last, which the drift and
the zig-zag's end-point selection both feed, not about how quickly a given distance is covered.

> \U0001F4A1 **In plain words.** "The whole climb took two years, the whole fall took two months"
> is true. "The first 10% down is quicker than the first 10% back up" is false.
"""),
        md("""
### 4.3 Ramsey-Rothman time reversibility, three tapes
"""),
        code(r"""
res = {"S&P 500 daily": st.tr_stats(r_sp, 10, n_boot=300, block=20),
       "Nasdaq daily": st.tr_stats(r_nq, 10, n_boot=300, block=20),
       "FF monthly": st.tr_stats(r_ff, 6, n_boot=300, block=6)}
fig, ax = plt.subplots(1, 3, figsize=(14, 4.2), sharey=False)
for a, (k, v) in zip(ax, res.items()):
    pl = v["per_lag"]
    se = pl["tr"] / pl["t_nw"]
    a.bar(pl.index, pl["tr"], color=DOWN, yerr=1.96 * se.abs(), capsize=3)
    a.axhline(0, color="k", lw=1); a.set_title(k); a.set_xlabel("lag k")
ax[0].set_ylabel("TR(k), NW 95% band"); plt.tight_layout(); plt.show()
pd.DataFrame({k: {"TR sum": v["tr_sum"], "NW t": v["t_nw"], "boot t": v["t_boot"],
                  "reversed": v["tr_sum_reversed"]} for k, v in res.items()}).T
"""),
        md(f"""
Headline (1,000 block-bootstrap draws in `verify.py`): S&P 500 TR sum {R['tr_sum']}, NW t =
{R['tr_t_nw']}, block-bootstrap t = {R['tr_t_boot']}; with the 0.5% tails clipped t =
{R['tr_t_wins']} — so it is not three crash days. Weekly {R['wk_tr_t']}; Nasdaq {R['nq_tr_t']};
FF monthly {R['ff_tr_t']} (bootstrap {R['ff_tr_t_boot']}). `tr_ok` holds.

> \U0001F4A1 **In plain words.** Negative TR(k) means a down day is followed by bigger moves
> (either way) than an up day is. That is the leverage effect, and it is what makes the film look
> different backwards.
"""),
        md("""
### 4.4 Skewness by horizon — the weaker witness
"""),
        code(r"""
lsp = np.log(sp)
ser = {"daily": r_sp, "weekly": st.aggregate(lsp, "W-FRI").to_numpy(),
       "monthly": st.aggregate(lsp, "ME").to_numpy()}
sk = st.skew_table(ser, {"daily": 21, "weekly": 8, "monthly": 6}, n_boot=300)
fig, ax = plt.subplots(1, 2, figsize=(12, 4.2))
xs = np.arange(len(sk))
ax[0].errorbar(xs, sk["skew"], yerr=[sk["skew"] - sk["skew_lo"], sk["skew_hi"] - sk["skew"]],
               fmt="o", color=DOWN, capsize=5)
ax[1].errorbar(xs, sk["kelly"], yerr=[sk["kelly"] - sk["kelly_lo"], sk["kelly_hi"] - sk["kelly"]],
               fmt="o", color=GREY, capsize=5)
for a, t in zip(ax, ("moment skewness", "Kelly quantile skewness")):
    a.axhline(0, color="k", lw=1); a.set_xticks(xs); a.set_xticklabels(sk.index); a.set_title(t)
plt.tight_layout(); plt.show()
sk
"""),
        md(f"""
S&P 500 daily skew {R['skew_d']} {R['skew_d_ci']}, monthly {R['skew_m']} {R['skew_m_ci']}
(block-bootstrap 95%). The Nasdaq daily and FF monthly intervals straddle zero (see
`docs/results.md`). Kelly skew is small and *negative* ({R['kelly_d']} daily): the "many small
steps up" picture would need it positive. Skewness carries no information about order.
"""),
        md("""
### 4.5 Mechanism — GJR / EGARCH vs symmetric GARCH vs i.i.d.
"""),
        code(r"""
fits = st.fit_models(r_sp)
pd.DataFrame(fits).T
"""),
        code(r"""
mc = st.mechanism_check(r_sp, fits, n_paths=30, seed=1016)
show = mc[["tr_sum", "skew_monthly", "elevator_ratio", "share_tr", "share_elevator"]]
fig, ax = plt.subplots(figsize=(10, 4.2))
w = show.drop(index="REAL TAPE")
ax.barh(w.index[::-1], 100 * w["share_tr"][::-1],
        color=[UP if "leverage" in i else GREY for i in w.index[::-1]])
ax.axvline(100, color="k", ls="--", label="real tape"); ax.legend()
ax.set_xlabel("% of real TR sum reproduced (median of 30 simulated paths)"); plt.show()
show
"""),
        md(f"""
`verify.py` (100 paths per world): GJR {R['share_tr_gjr']} of the TR sum, EGARCH
{R['share_tr_egarch']}, symmetric GARCH {R['share_tr_garch']}, i.i.d. {R['share_tr_iid']}. The
GJR leverage term is t = {R['gjr_gamma_t']}. The GJR world also reproduces the *reversed*
elevator ratio ({R['share_elev_gjr']} of its log): leverage puts peak volatility at the trough, so
the first leg up is fast — the mechanism explains the anti-proverb too.

> \U0001F4A1 **In plain words.** The only fake markets that look like the real one are those where
> falls make the market jumpier. Markets that are merely "sometimes calm, sometimes stormy" don't.
"""),
        md("""
### 4.6 Positive control — the planted world *(synthetic, not market evidence)*
"""),
        code(r"""
rows = []
for s in (0.0, 0.25, 0.5, 0.75, 1.0):
    df, truth = data.synthetic_returns(8000, s, seed=1016)
    tr = st.tr_stats(df["logret"].to_numpy(), 10, n_boot=100)
    rows.append({"signal_strength": s, "gamma": truth["gamma_eff"], "TR sum": tr["tr_sum"],
                 "NW t": tr["t_nw"], "boot t": tr["t_boot"],
                 "elevator 5%": st.leg_stats(np.log(df["price"].to_numpy()), 0.05)["elevator_ratio"]})
ctl = pd.DataFrame(rows).set_index("signal_strength")
fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(ctl.index, ctl["NW t"], "o-", color=DOWN, label="NW t of TR sum")
ax.axhline(-2, color="k", ls="--", label="desk bar"); ax.legend()
ax.set_xlabel("signal_strength (leverage term scale)"); plt.show()
ctl
"""),
        md("""
> \U0001F4A1 **In plain words.** With the leverage term switched off (0.0) the detector is quiet;
> switched on, it fires. That proves the machinery can see the effect — it says nothing about the
> market, which is what sections 4.1-4.5 are for.
"""),
        md(f"""
## 5 · The verdict

{BADGES}

`tr_ok` = True (t = {R['tr_t_nw']}, bootstrap {R['tr_t_boot']}); `dur_ok` = False (elevator
ratio {R['elev10']}× < 1). Exactly one → **Mixed**: the path is irreversible in the leverage
direction; the literal "same distance, faster down" reading is reversed.
"""),
        md("""
## 6 · Could you trade it?
"""),
        code(r"""
races = {}
sp_t, nq_t = (s[s.index <= pd.Timestamp(data.FF_AS_OF)] for s in (sp, nq))
races["S&P 500 daily"] = st.race(sp_t, data.daily_rf(sp_t.index, ff), 0.0005, n_boot=200)
races["Nasdaq daily"] = st.race(nq_t, data.daily_rf(nq_t.index, ff), 0.0005, n_boot=200)
races["FF monthly TR"] = st.race(fi, ff["rf"].reindex(fi.index).fillna(0.0), 0.0010,
                                 periods=12, block=6, n_boot=200)
tbl = pd.concat({k: v[["sharpe_gross", "sharpe_net", "sharpe_bh", "d_vs_bh", "p_vs_bh",
                       "time_in", "trades_per_year"]] for k, v in races.items()})
tbl
"""),
        code(r"""
costs = [0, 2, 5, 10, 20, 40]
fig, ax = plt.subplots(figsize=(10, 4.2))
for name, (ex, en) in st.RULES.items():
    sig = st.zigzag_rule(sp_t, ex, en)
    d = [st.backtest(sp_t, data.daily_rf(sp_t.index, ff), sig, c / 1e4)["sharpe_net"]
         - st.backtest(sp_t, data.daily_rf(sp_t.index, ff), sig, 0)["sharpe_bh"] for c in costs]
    ax.plot(costs, d, "o-", label=name)
ax.axhline(0, color="k", lw=1); ax.set_xlabel("one-way cost (bp)")
ax.set_ylabel("net excess Sharpe minus buy-and-hold"); ax.set_title("S&P 500 1990-2018, one lag")
ax.legend(fontsize=8); plt.show()
"""),
        md(f"""
Headline (`verify.py`, 500 paired block-bootstrap draws): net Sharpe edge of the pre-registered
5%/10% rule over buy-and-hold **{R['d_sp']}** on the S&P 500, **{R['d_nq']}** on the Nasdaq (both
price-only, which flatters a rule that holds cash), **{R['d_ff']}** on FF 1926-2018 (p =
{R['p_ff']}) shrinking to {R['d_ff45']} (p = {R['p_ff45']}) after 1945. The symmetric 10%/10% twin
matches it on FF ({R['d_ff_sym10']}), so the asymmetry is not the source of whatever a drawdown
rule earns. Only one of three tapes positive → **Mirage**.

Even at zero cost the asymmetric rule loses on daily data: the cost of a slow re-entry is
missing the fastest move on the tape, the rebound off the low — the section 4.1 finding, priced.

> \U0001F4A1 **In plain words.** Knowing that the market is lopsided in time tells you what
> insurance should cost. It doesn't tell you when to sell.
"""),
        md("""
## 7 · Going further

- **Option-implied check.** Map the realised TR statistic, rolling, against the slope of the
  index implied-vol skew (needs an options tape the desk does not ship).
- **Intraday first passage.** At 5-minute resolution the fast-rebound effect should be visible
  inside single sessions if volatility feedback is the mechanism.
- **Cross-section.** Single stocks have positive skew but may still be leverage-irreversible —
  a cleaner separation of skew from order than an index allows.
- **Conditional rules.** A rule that *re-enters fast when volatility is high* (the opposite of
  slow entry) is the trade this study's mechanism suggests; it would need its own
  pre-registration and a fresh tape.
"""),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
