"""Notebook builder for Study 1010 — Mostly Noise.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Mostly Noise \U0001F9F1
### Your risk model has 1,275 numbers in it. Perhaps five of them are real.

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Every optimiser, every risk report and every "diversified" portfolio rests on a correlation
matrix. Nobody prints an error bar on one. There is a sixty-year-old piece of mathematics that
says exactly how much of it can possibly be real, and it needs no data at all — only how many
assets you have and how many days you measured them over.

> \U0001F4D3 **This is the plain-language layer.** The eigenvalue spectrum, the known-factor
> control and the estimator race are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| How much of the matrix is measurable? | A handful of numbers out of a thousand. |
| Can you know that in advance? | Yes — from N and T alone. |
| Does it look stable? | Only because stocks move together. |
| Does cleaning help? | Yes, mostly by stopping the optimiser fooling itself. |
"""
        ),
        md(
            r"""

## 1 · The problem, in one calculation
"""
        ),
        code(
            r"""
from corrnoise import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2500]
R = px[cols].pct_change().dropna()
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} common sessions from "
      f"{R.index[0].date()}")
p = st.parameters_vs_observations(len(cols), 252)
print(f"a {len(cols)}x{len(cols)} covariance matrix = {p['n_parameters']:,} parameters")
print(f"a 252-day window = {p['n_observations']:,} observations "
      f"({p['observations_per_parameter']:.1f} per parameter)")
"""
        ),
        code(
            r"""
b = st.marchenko_pastur_bounds(len(cols), 252)
print(f"q = number of assets / number of days = {b['q']:.4f}")
print()
print("Marchenko & Pastur (1967) proved that if the assets were COMPLETELY UNRELATED,")
print("the eigenvalues of the measured correlation matrix would still scatter across")
print(f"    [{b['lambda_minus']:.3f}, {b['lambda_plus']:.3f}]")
print()
print("Anything landing in that range tells you nothing. And note: computing it did")
print("not require a single price. Only N and T.")
"""
        ),
        md(
            r"""

## 2 · The picture
"""
        ),
        code(
            r"""
s = st.spectrum_analysis(R.iloc[-252:])
ev = s["eigenvalues"]
fig, ax = plt.subplots(figsize=(12, 5))
ax.hist(ev, bins=40, color="#8b949e", density=True, alpha=0.85,
        label="measured eigenvalues")
xs = np.linspace(s["lambda_minus"], s["lambda_plus"], 400)
ax.plot(xs, st.mp_density(xs, s["q"]), lw=3, color="#c0392b",
        label="what PURE NOISE would look like")
ax.axvspan(s["lambda_minus"], s["lambda_plus"], alpha=0.12, color="#c0392b")
ax.set_xlim(0, min(max(ev) * 1.05, s["lambda_plus"] * 4))
ax.set_xlabel("eigenvalue"); ax.set_ylabel("density"); ax.legend(fontsize=9)
plt.show()
print(f"{s['n_above']} eigenvalues escape the noise band. {s['n_inside']} do not.")
print(f"the largest is {s['largest']:.1f} -- that is 'the stock market', "
      f"{s['largest_share']:.0%} of all variance")
"""
        ),
        md(
            r"""

The red curve is what you would see if these fifty companies had **nothing whatsoever** to do
with each other. Almost the whole histogram sits under it.
"""
        ),
        md(
            r"""

## 3 · Checking the tool before believing it
"""
        ),
        code(
            r"""
rows = []
for k in (0, 1, 3, 6, 10):
    sim = st.synthetic_returns(len(cols), 252, n_factors=k, factor_strength=1.0)
    sp = st.spectrum_analysis(sim)
    rows.append({"factors planted": k, "eigenvalues above the band": sp["n_above"],
                 "share inside": sp["share_inside"]})
d = pd.DataFrame(rows).set_index("factors planted")
fig, ax = plt.subplots(figsize=(9.5, 4.8))
ax.plot(d.index, d["eigenvalues above the band"], "o-", lw=2.5, color="#1f6feb",
        label="detected")
ax.plot(d.index, d.index, "k--", lw=2, label="planted")
ax.set_xlabel("number of real factors planted")
ax.set_ylabel("eigenvalues escaping the band"); ax.legend(fontsize=9)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

On simulated data where we *know* the answer, the method finds the right number of real factors
— and finds nothing when there is nothing. Only then is it worth pointing at a market.
"""
        ),
        md(
            r"""

## 4 · The "but correlations are stable" objection
"""
        ),
        code(
            r"""
per = st.matrix_persistence(R, window=252, step=63)
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(per["start"], per["pairwise_corr"], "o-", lw=2, color="#1f6feb",
        label="how well this year predicts next year")
ax.plot(per["start"], per["residual_corr"], "s-", lw=2, color="#c0392b",
        label="...after removing 'stocks move together'")
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("agreement between consecutive years"); ax.legend(fontsize=9)
plt.show()
ps = st.persistence_summary(per)
print(f"raw agreement:                    {ps['pairwise']:.3f}")
print(f"agreement after removing market:  {ps['residual']:.3f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The blue line is the statistic people cite for "correlations
> are stable". Nearly all of it is the single fact that equities co-move. The red line is what
> is left of the matrix's *structure*, and it is much less encouraging.
"""
        ),
        md(
            r"""

## 5 · Does any of this matter for a portfolio?
"""
        ),
        code(
            r"""
summ = st.race_summary(st.portfolio_horse_race(R, 252, 63))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].bar(summ.index, summ["realised_vol"] * 100, color="#1f6feb")
axes[0].set_ylabel("realised volatility (%)")
plt.setp(axes[0].get_xticklabels(), rotation=30, ha="right", fontsize=8)
axes[1].bar(summ.index, summ["calibration"],
            color=["#c0392b" if abs(c - 1) > 0.15 else "#2ea44f"
                   for c in summ["calibration"]])
axes[1].axhline(1.0, color="k", ls="--", lw=2, label="forecast was honest")
axes[1].set_ylabel("realised risk / forecast risk"); axes[1].legend(fontsize=8)
plt.setp(axes[1].get_xticklabels(), rotation=30, ha="right", fontsize=8)
plt.tight_layout(); plt.show()
print(summ.round(4).to_string())
"""
        ),
        md(
            r"""

The right-hand chart is the important one. Fed the raw matrix, the optimiser builds a portfolio
and tells you its risk — and is wrong by a large factor, always in the same direction. It picks
exactly the positions where the noise happened to look reassuring.

Note the **diagonal** bar: that is throwing away every correlation and using only individual
volatilities. It is a much harder benchmark than it sounds.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Confirmed.** Most of it, and the amount is calculable before any data is collected. Estimating a 50×50 covariance matrix means fitting **1,275 parameters** from 252 observations per asset; at q = N/T = 0.198, Marchenko-Pastur puts the pure-noise eigenvalue band at [0.308, 2.089]. On the real matrix, **31 of 50 eigenvalues fall inside it** — 62% of the spectrum, carrying 48% of the total variance and indistinguishable from a matrix of random numbers. Only **5 escape upward**, and the largest of those is simply the market: it alone accounts for 20% of the variance. A further 14 fall *below* the band, which is not signal either — those are the near-degenerate directions that make the matrix ill-conditioned, and an optimiser is drawn to precisely them because a tiny variance estimate looks like a free lunch. Lengthening the estimation window does not fix this: at 2520 days the informative count is still only 4. More data narrows the band; it does not manufacture factors that were never there. The synthetic control confirms the machinery rather than the story — with **independent** assets by construction, 99% of the spectrum lands inside the band as it must, and planting 3 factors puts 3.0 eigenvalues above it. Persistence tells the same story from another direction: consecutive windows' pairwise correlations agree at 0.64, which sounds reassuring until the market factor is removed, after which the residual agreement is **0.62**. Almost all the apparent stability is the single fact that stocks move together.

**Tradability: Useful.** Cleaning helps, mostly by stopping the optimiser lying to itself. Fed the raw sample matrix, a minimum-variance portfolio forecast 9.2% volatility and realised 12.7% — a calibration ratio of **1.46**, because the optimiser selects precisely the directions where noise made the variance look smallest. ledoit_wolf brought that to 1.36 while realising 12.5%. The honest benchmark is the diagonal matrix — throwing every correlation away — which realised 13.4% at a calibration of 4.24; the cleaned estimators earn their place against it. Ledoit-Wolf shrank toward its target with an average intensity of **0.37**, i.e. the estimator itself concluded that roughly that fraction of the sample matrix was not worth keeping. Two practical readings. First, the estimation window is a real choice with a computable cost: at 63 days the band swallows 90% of the spectrum against 14% at 2520. Second, a long-only constraint removes much of the damage on its own — gross leverage falls from 3.0× to 1.0× — so a good deal of what cleaning buys is available for free to anyone who cannot short anyway.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Compute q before choosing a lookback.** If N/T is not small, no amount of care with the
  estimator recovers what was never measured. That calculation costs nothing and is skipped
  almost universally.
- **Shrink, or constrain, or both.** Ledoit-Wolf shrinkage is a one-line change to most
  pipelines. A long-only constraint achieves much of the same thing for free — which is
  Jagannathan and Ma's (2003) result, and section 8 of the results reproduces it.
- **Be suspicious of a risk number without a calibration record.** "This portfolio has 6%
  volatility" is a forecast. Whether the last twenty such forecasts came true is the only thing
  that makes it worth hearing.
- **The market factor is the honest part.** One eigenvalue is real, large and stable. Most of
  the rest of the matrix is decoration, and a model built on a handful of factors plus a
  diagonal is not a crude approximation — it is close to all the information there is.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Mostly Noise — a quantitative teardown \U0001F52C
### Marchenko-Pastur against the empirical spectrum · a known-factor control · calibration scoring

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). **§3.2**
calibrates the tool on a world with a *known* number of factors before pointing it at anything
real. **§3.4** removes the market factor before measuring persistence, which is where the
comfortable answer stops being comfortable. **§3.6** scores estimators on whether their own risk
forecast survives the next quarter, with a diagonal matrix as the benchmark that has to be
beaten.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from corrnoise import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2500]
R = px[cols].pct_change().dropna()
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} common sessions from "
      f"{R.index[0].date()}")
p = st.parameters_vs_observations(len(cols), 252)
print(f"a {len(cols)}x{len(cols)} covariance matrix = {p['n_parameters']:,} parameters")
print(f"a 252-day window = {p['n_observations']:,} observations "
      f"({p['observations_per_parameter']:.1f} per parameter)")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | Most of it, and the amount is calculable before any data is collected. Estimating a 50×50 covariance matrix means fitting **1,275 parameters** from 252 observations per asset; at q = N/T = 0.198, Marchenko-Pastur puts the pure-noise eigenvalue band at [0.308, 2.089]. On the real matrix, **31 of 50 eigenvalues fall inside it** — 62% of the spectrum, carrying 48% of the total variance and indistinguishable from a matrix of random numbers. Only **5 escape upward**, and the largest of those is simply the market: it alone accounts for 20% of the variance. A further 14 fall *below* the band, which is not signal either — those are the near-degenerate directions that make the matrix ill-conditioned, and an optimiser is drawn to precisely them because a tiny variance estimate looks like a free lunch. Lengthening the estimation window does not fix this: at 2520 days the informative count is still only 4. More data narrows the band; it does not manufacture factors that were never there. The synthetic control confirms the machinery rather than the story — with **independent** assets by construction, 99% of the spectrum lands inside the band as it must, and planting 3 factors puts 3.0 eigenvalues above it. Persistence tells the same story from another direction: consecutive windows' pairwise correlations agree at 0.64, which sounds reassuring until the market factor is removed, after which the residual agreement is **0.62**. Almost all the apparent stability is the single fact that stocks move together. |
| **Tradability** | Useful | Cleaning helps, mostly by stopping the optimiser lying to itself. Fed the raw sample matrix, a minimum-variance portfolio forecast 9.2% volatility and realised 12.7% — a calibration ratio of **1.46**, because the optimiser selects precisely the directions where noise made the variance look smallest. ledoit_wolf brought that to 1.36 while realising 12.5%. The honest benchmark is the diagonal matrix — throwing every correlation away — which realised 13.4% at a calibration of 4.24; the cleaned estimators earn their place against it. Ledoit-Wolf shrank toward its target with an average intensity of **0.37**, i.e. the estimator itself concluded that roughly that fraction of the sample matrix was not worth keeping. Two practical readings. First, the estimation window is a real choice with a computable cost: at 63 days the band swallows 90% of the spectrum against 14% at 2520. Second, a long-only constraint removes much of the damage on its own — gross leverage falls from 3.0× to 1.0× — so a good deal of what cleaning buys is available for free to anyone who cannot short anyway. |

> \U0001F4A1 **In plain words.** How much of a covariance matrix is knowable is decided by N and
> T before any data is seen.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (arithmetic).** At a realistic estimation window, the majority of the sample spectrum
  falls inside the Marchenko-Pastur band.
- **H₂ (control).** In a synthetic world with zero factors the spectrum matches the theoretical
  density; with k factors, k eigenvalues escape.
- **H₃ (persistence).** Pairwise correlation persistence is high but collapses once the first
  principal component is removed.
- **H₄ (calibration).** A min-variance portfolio built on the raw sample matrix realises
  materially more volatility than it forecast.
- **H₅ (baseline).** Cleaned estimators beat the diagonal matrix out of sample; if they do not,
  the correlations are not worth estimating at all.
"""
        ),
        md(
            r"""

## 2 · The band, as a function of the choices you make
"""
        ),
        code(
            r"""
rows = []
for n_assets in (10, 25, 50, 100, 200):
    for window in (63, 126, 252, 504, 1260):
        b = st.marchenko_pastur_bounds(n_assets, window)
        rows.append({"n_assets": n_assets, "window": window, "q": b["q"],
                     "band_width": b["lambda_plus"] - b["lambda_minus"],
                     "lambda_plus": b["lambda_plus"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5))
for n, g in d.groupby("n_assets"):
    ax.plot(g["window"], g["band_width"], "o-", lw=2, label=f"{n} assets")
ax.set_xscale("log"); ax.set_xlabel("estimation window, days (log)")
ax.set_ylabel("width of the pure-noise eigenvalue band"); ax.legend(fontsize=8)
plt.show()
print(d.pivot(index="window", columns="n_assets", values="q").round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** This chart is free. Every allocator can read their own N and
> lookback off it before running anything, and most of the disappointment in covariance
> estimation is visible here in advance.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The empirical spectrum against the theoretical density
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
for ax, w in zip(axes, (126, 252, 1260)):
    if len(R) < w:
        continue
    s = st.spectrum_analysis(R.iloc[-w:])
    ax.hist(s["eigenvalues"], bins=35, density=True, color="#8b949e", alpha=0.85)
    xs = np.linspace(s["lambda_minus"], s["lambda_plus"], 400)
    ax.plot(xs, st.mp_density(xs, s["q"]), lw=2.5, color="#c0392b")
    ax.axvspan(s["lambda_minus"], s["lambda_plus"], alpha=0.12, color="#c0392b")
    ax.set_xlim(0, s["lambda_plus"] * 2.5)
    ax.set_title(f"{w}-day window: {s['share_inside']:.0%} inside", fontsize=10)
    ax.set_xlabel("eigenvalue")
plt.tight_layout(); plt.show()
print(st.spectrum_by_window(R, windows=(63, 126, 252, 504, 1260, 2520)).round(4)
      .to_string())
"""
        ),
        md(
            r"""

### 3.2 The control — calibrating before believing
"""
        ),
        code(
            r"""
rows = []
for k in (0, 1, 2, 3, 5, 8, 12):
    for seed in range(4):
        sim = st.synthetic_returns(len(cols), 252, n_factors=k, factor_strength=1.0,
                                   seed=1010 + seed)
        s = st.spectrum_analysis(sim)
        rows.append({"planted": k, "detected": s["n_above"],
                     "share_inside": s["share_inside"]})
d = pd.DataFrame(rows).groupby("planted").mean()
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(d.index, d["detected"], "o-", lw=2.5, color="#1f6feb", label="detected")
axes[0].plot(d.index, d.index, "k--", lw=2, label="planted")
axes[0].set_xlabel("true number of factors")
axes[0].set_ylabel("eigenvalues above the band"); axes[0].legend(fontsize=8)
sim0 = st.synthetic_returns(len(cols), 252, n_factors=0)
s0 = st.spectrum_analysis(sim0)
axes[1].hist(s0["eigenvalues"], bins=30, density=True, color="#8b949e", alpha=0.85,
             label="simulated, ZERO true structure")
xs = np.linspace(s0["lambda_minus"], s0["lambda_plus"], 400)
axes[1].plot(xs, st.mp_density(xs, s0["q"]), lw=2.5, color="#c0392b",
             label="theory")
axes[1].set_xlabel("eigenvalue"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

### 3.3 What the surviving eigenvectors actually are
"""
        ),
        code(
            r"""
s = st.spectrum_analysis(R.iloc[-1260:])
C = np.corrcoef(R.iloc[-1260:].to_numpy().T)
vals, vecs = np.linalg.eigh(C)
order = np.argsort(vals)[::-1]
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
for i, ax in enumerate(axes):
    v = vecs[:, order[i]]
    v = v * np.sign(v.sum())
    srt = np.argsort(v)
    ax.barh(range(len(v)), v[srt], color="#1f6feb")
    ax.set_yticks(range(len(v)))
    ax.set_yticklabels([cols[j] for j in srt], fontsize=4)
    ax.set_title(f"eigenvector {i+1} (lambda={vals[order[i]]:.2f})", fontsize=10)
plt.tight_layout(); plt.show()
print("The first is all one sign -- that is 'the market'. The next two, if they escape")
print("the band at all, are usually sector tilts. Beyond that there is nothing to name.")
"""
        ),
        md(
            r"""

### 3.4 Persistence, with and without the market
"""
        ),
        code(
            r"""
rows = []
for w in (126, 252, 504):
    p = st.matrix_persistence(R, window=w, step=max(w // 4, 21))
    s = st.persistence_summary(p)
    if s:
        rows.append({"window": w, **s})
d = pd.DataFrame(rows).set_index("window")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
x = np.arange(len(d)); wd = 0.26
axes[0].bar(x - wd, d["pairwise"], wd, color="#1f6feb", label="pairwise")
axes[0].bar(x, d["top_overlap"], wd, color="#2ea44f", label="top eigenvector")
axes[0].bar(x + wd, d["residual"], wd, color="#c0392b", label="after removing market")
axes[0].set_xticks(x); axes[0].set_xticklabels([f"{w}d" for w in d.index])
axes[0].set_ylabel("agreement between consecutive windows")
axes[0].legend(fontsize=8)
p = st.matrix_persistence(R, window=252, step=63)
axes[1].plot(p["start"], p["mean_corr_a"], lw=2, color="#8b949e",
             label="mean pairwise correlation")
axes[1].set_ylabel("average correlation in the window"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The green bars are high at every window: the market factor is
> genuinely stable and genuinely useful. The red bars are what remains of the matrix once you
> stop being impressed by that.
"""
        ),
        md(
            r"""

### 3.5 Scored against a known truth
"""
        ),
        code(
            r"""
rows = []
for n_obs in (60, 100, 252, 504, 1260, 2520):
    for seed in range(4):
        sim = st.synthetic_returns(len(cols), n_obs, n_factors=3, factor_strength=1.0,
                                   seed=1010 + seed)
        truth = st.true_covariance(len(cols), n_factors=3, factor_strength=1.0,
                                   seed=1010 + seed)
        rows.append({"n_obs": n_obs, **st.estimator_error(sim, truth)})
d = pd.DataFrame(rows).groupby("n_obs").mean()
fig, ax = plt.subplots(figsize=(10, 5))
for c in d.columns:
    ax.loglog(d.index, d[c], "o-", lw=2, label=c)
ax.axvline(len(cols), color="k", ls=":", lw=2, label=f"T = N = {len(cols)}")
ax.set_xlabel("observations (log)")
ax.set_ylabel("relative distance to the TRUE covariance (log)")
ax.legend(fontsize=8)
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

### 3.6 The horse race, scored on calibration
"""
        ),
        code(
            r"""
rows = []
for w, hd in ((126, 63), (252, 63), (504, 126), (1008, 126)):
    if len(R) < w + hd + 10:
        continue
    s = st.race_summary(st.portfolio_horse_race(R, w, hd))
    for m, row in s.iterrows():
        rows.append({"window": w, "method": m, **row.to_dict()})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for m, g in d.groupby("method"):
    axes[0].plot(g["window"], g["calibration"], "o-", lw=2, label=m)
    axes[1].plot(g["window"], g["realised_vol"] * 100, "o-", lw=2, label=m)
axes[0].axhline(1.0, color="k", ls="--", lw=2)
axes[0].set_xlabel("estimation window (days)")
axes[0].set_ylabel("realised / forecast risk"); axes[0].legend(fontsize=7)
axes[1].set_xlabel("estimation window (days)")
axes[1].set_ylabel("realised volatility (%)"); axes[1].legend(fontsize=7)
plt.tight_layout(); plt.show()
print(d.pivot(index="window", columns="method", values="calibration").round(3)
      .to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** A calibration above one means the optimiser under-forecast its
> own risk. It is not random error — the direction is systematic, because minimising a noisy
> variance estimate is the same operation as searching for the largest downward error in it.
"""
        ),
        md(
            r"""

### 3.7 What a constraint achieves for free
"""
        ),
        code(
            r"""
free = st.race_summary(st.portfolio_horse_race(R, 252, 63, long_only=False))
cons = st.race_summary(st.portfolio_horse_race(R, 252, 63, long_only=True))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
x = np.arange(len(free)); w = 0.38
order = free.index
axes[0].bar(x - w/2, free.loc[order, "realised_vol"] * 100, w, color="#c0392b",
            label="unconstrained")
axes[0].bar(x + w/2, cons.loc[order, "realised_vol"] * 100, w, color="#2ea44f",
            label="long only")
axes[0].set_xticks(x); axes[0].set_xticklabels(order, rotation=30, ha="right",
                                               fontsize=7)
axes[0].set_ylabel("realised volatility (%)"); axes[0].legend(fontsize=8)
axes[1].bar(x - w/2, free.loc[order, "gross_leverage"], w, color="#c0392b",
            label="unconstrained")
axes[1].bar(x + w/2, cons.loc[order, "gross_leverage"], w, color="#2ea44f",
            label="long only")
axes[1].set_xticks(x); axes[1].set_xticklabels(order, rotation=30, ha="right",
                                               fontsize=7)
axes[1].set_ylabel("gross leverage"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(pd.DataFrame({"unconstrained": free["realised_vol"],
                    "long only": cons["realised_vol"]}).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Jagannathan & Ma (2003) proved a no-shorting constraint is
> mathematically equivalent to shrinking the covariance matrix. The right-hand panel is that
> theorem showing up in a bar chart: the constraint does most of the cleaning by itself, and
> the estimators then have far less left to disagree about.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
s = st.spectrum_analysis(R.iloc[-252:])
ps = st.persistence_summary(st.matrix_persistence(R, 252, 63))
summ = st.race_summary(st.portfolio_horse_race(R, 252, 63))
p = st.parameters_vs_observations(len(cols), 252)
err = (summ["calibration"] - 1).abs()
pd.DataFrame({
    "assets": [len(cols)],
    "free parameters in the matrix": [p["n_parameters"]],
    "observations per parameter": [p["observations_per_parameter"]],
    "q = N/T": [s["q"]],
    "noise band, lower": [s["lambda_minus"]],
    "noise band, upper": [s["lambda_plus"]],
    "eigenvalues above the band": [s["n_above"]],
    "share of spectrum inside the band": [s["share_inside"]],
    "variance carried by the noise bulk": [s["variance_inside"]],
    "largest eigenvalue's share": [s["largest_share"]],
    "pairwise persistence": [ps["pairwise"]],
    "persistence after removing the market": [ps["residual"]],
    "raw matrix calibration": [summ.loc["sample", "calibration"]],
    "best-calibrated estimator": [str(err.idxmin())],
    "its calibration": [summ.loc[err.idxmin(), "calibration"]],
    "diagonal baseline calibration": [summ.loc["diagonal", "calibration"]],
}).T.rename(columns={0: "value"})
"""
        ),
        md(
            r"""

## 5 · Going further

- **Bun, Bouchaud & Potters (2017)** give rotationally-invariant estimators that dominate the
  simple eigenvalue-clipping filter used in §3.6. Implementing one is the obvious upgrade and
  would probably change the ranking.
- **Marchenko-Pastur assumes i.i.d. Gaussian entries**, which returns are not. The true noise
  band under fat tails and volatility clustering is *wider*, so every "share inside the band"
  reported here is conservative. Deriving the correct band for a Student-t world would sharpen
  the whole study.
- **Jagannathan & Ma (2003)** explains §3.7 analytically: a no-short constraint is equivalent to
  shrinking the covariance matrix by a specific amount. Working out the implied shrinkage on
  this panel and comparing it against Ledoit-Wolf's δ would connect the two halves neatly.
- **Dynamic conditional correlation.** Everything here uses static windows. A DCC-GARCH model
  makes correlations time-varying by construction, and testing it on §3.6's calibration
  criterion — rather than on in-sample likelihood, which is how it is usually sold — would be a
  genuinely informative comparison.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
