"""Notebook builder for Study 967 — Window Shopping.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Window Shopping \U0001FA9F
### How much history should an estimate use? It depends what you are estimating.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

Five years, because that is what the terminal shows. Or everything, because more data must be
better. Nobody ever tests it. This notebook does: three things a portfolio needs — a beta, an
expected return, a covariance matrix — estimated from six different windows and then judged by
the year that came next.

> \U0001F4D3 **This is the plain-language layer.** The paired-error tests and the
> observations-per-parameter arithmetic are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Estimating... | Best window | Why |
|---|---|---|
| **A beta** | medium, then shrink | Betas move, but slowly; a short window is mostly noise and a long one is mostly stale. |
| **An expected return** | as much as possible — and even then, don't | Means are so imprecise that the cross-sectional average beats a sector's own history. |
| **A covariance matrix** | long enough to have rows per parameter | Below that line the optimiser stops estimating risk and starts amplifying error. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Use five years of monthly data."* — every risk textbook, and every terminal's default.
>
> *"No, use everything you have; more data is more information."* — every statistician who has
> not thought about structural change.

Both are answers to a question nobody states precisely: *more information about what?*
"""
        ),
        md(
            r"""

## 2 · So what?

The window choice is invisible and consequential. It sets your hedge ratio, your risk limits
and — through the covariance matrix — the entire shape of an optimised portfolio. And unlike a
strategy, it is never backtested: it is inherited.
"""
        ),
        code(
            r"""
from window_choice import data, strategy as st

px = data.load_prices()
rets = st.to_returns(px)
sectors = tuple(s for s in data.SECTORS if rets[s].notna().sum() > 500)
print(f"as-of {data.AS_OF} | {len(sectors)} sectors | "
      f"{px.index[0].date()} -> {px.index[-1].date()}")
print("inceptions:", ", ".join(f"{s}:{px[s].dropna().index[0].year}" for s in data.SECTORS))
"""
        ),
        md(
            r"""

## 3 · How would we even know?

Stand at the end of each year. Estimate the thing from the last 1, 2, 3, 5, 10 years, and from
everything you have. Then wait a year and see which estimate was closest. Repeat for every
year in the sample.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 Beta
"""
        ),
        code(
            r"""
bexp = st.beta_experiment(rets, sectors, data.MARKET)
bsc = st.score(bexp)
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.bar([str(w) for w in bsc.index], bsc["mse"], color="#2ea44f")
ax.set_ylabel("mean squared error vs next year's realised beta")
ax.set_xlabel("estimation window (years)")
ax.set_title("Beta: there is an interior optimum, and it is not 'everything'")
plt.show()
bsc.round(5)
"""
        ),
        md(
            r"""

### 4.2 The mean return, and a very humbling benchmark
"""
        ),
        code(
            r"""
mexp = st.mean_experiment(rets, sectors)
gm = st.grand_mean_benchmark(rets, sectors)
msc = st.score(pd.concat([mexp, gm], ignore_index=True))
fig, ax = plt.subplots(figsize=(9, 4.5))
colors = ["#c0392b" if w == "grand mean" else "#8b949e" for w in msc.index]
ax.bar([str(w) for w in msc.index], msc["mse"], color=colors)
ax.set_ylabel("MSE vs next year's realised mean daily return")
ax.set_title("Expected returns: the red bar uses none of the sector's own history")
plt.show()
msc.round(8)
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Merton (1980): the standard error of a mean depends on the
> calendar span, not the number of observations, so sampling daily instead of monthly buys you
> nothing at all on this parameter. Twenty-eight years of data still leaves the sector means
> statistically indistinguishable from one another.
"""
        ),
        md(
            r"""

### 4.3 The covariance matrix, judged by the portfolio it builds
"""
        ),
        code(
            r"""
cexp = st.covariance_experiment(rets, sectors)
csc = cexp.groupby("window").agg(realised=("realised_vol", "mean"),
                                 predicted=("predicted_vol", "mean"),
                                 max_w=("max_weight", "mean"))
order = [w for w in list(st.WINDOWS_YEARS) + [st.EXPANDING] if w in csc.index]
csc = csc.loc[order]
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].bar([str(w) for w in csc.index], csc["realised"] * 100, color="#2ea44f",
            label="realised next year")
axes[0].bar([str(w) for w in csc.index], csc["predicted"] * 100, color="#c0392b",
            alpha=0.6, label="promised in sample")
axes[0].set_ylabel("annualised volatility (%)"); axes[0].legend()
axes[0].set_title("What the optimiser promised vs what it delivered")
axes[1].bar([str(w) for w in csc.index], csc["max_w"] * 100, color="#8b949e")
axes[1].set_title("Average largest single weight (%)")
for a in axes:
    a.set_xlabel("estimation window (years)")
plt.show()
csc.round(4)
"""
        ),
        md(
            r"""

The short-window optimiser is confident and wrong: it promises the lowest volatility and
delivers the highest, while concentrating the portfolio into whichever sector happened to look
quietest last year.
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** Yes, and by more than habit would suggest. Across estimation windows the MSE spread is **72%** for beta, **92%** for the mean return and **3%** for the volatility of the minimum-variance portfolio; the strongest pairwise Diebold-Mariano across the three experiments is **+3.45**. The three quantities do not agree with each other: beta wants **2**, the mean wants **10**, the covariance matrix wants **3**.

**Usefulness: Fragile.** There is no single default. The mean is the extreme case: even the *best* window of a sector's own history is beaten by the **grand mean across all sectors** (MSE ratio 1.54), which is the empirical way of saying individual expected returns are not estimable from price history at all. Beta is estimable and mildly non-stationary — Blume shrinkage cuts its MSE by a further **-10%**. The covariance matrix is the one place where a short window is actively dangerous: at 11 assets, a one-year window has about 42.0 observations per estimated parameter.
"""
        ),
        md(
            r"""

## 6 · What should you actually do?

- **Beta:** a few years, then shrink toward 1 (Blume). The shrinkage is worth more than the
  window choice.
- **Expected returns:** do not estimate them per asset from price history. Use a cross-sectional
  anchor, or a model, or an assumption you are willing to defend.
- **Covariance:** count your parameters before you choose your window; if rows-per-parameter
  is in single digits, shrink the matrix (study 975) or reduce the cross-section.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Structural-break tests** (Bai-Perron) to choose the window *endogenously* instead of by
  grid search.
- **Exponential weighting** instead of a hard cut-off: a half-life is a smoother version of the
  same trade-off.
- **A wider cross-section.** Eleven sectors is a friendly matrix; at 500 stocks every effect
  here becomes dramatic.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Window Shopping — a quantitative teardown \U0001F52C
### Three parameters · six windows · out-of-sample scoring · paired Diebold-Mariano · Blume shrinkage

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The
organising idea is bias-variance: a window is a bet that the recent past resembles the near
future more than the distant past does, and how good that bet is depends entirely on how
precisely the parameter can be estimated in the first place.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance, pinned as-of the date
> in [`docs/results.md`](../docs/results.md); literature map in
> [`docs/references.md`](../docs/references.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from window_choice import data, strategy as st

px = data.load_prices()
rets = st.to_returns(px)
sectors = tuple(s for s in data.SECTORS if rets[s].notna().sum() > 500)
print(f"as-of {data.AS_OF} | {len(sectors)} sectors | "
      f"{px.index[0].date()} -> {px.index[-1].date()}")
print("inceptions:", ", ".join(f"{s}:{px[s].dropna().index[0].year}" for s in data.SECTORS))
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Yes, and by more than habit would suggest. Across estimation windows the MSE spread is **72%** for beta, **92%** for the mean return and **3%** for the volatility of the minimum-variance portfolio; the strongest pairwise Diebold-Mariano across the three experiments is **+3.45**. The three quantities do not agree with each other: beta wants **2**, the mean wants **10**, the covariance matrix wants **3**. |
| **Usefulness** | Fragile | There is no single default. The mean is the extreme case: even the *best* window of a sector's own history is beaten by the **grand mean across all sectors** (MSE ratio 1.54), which is the empirical way of saying individual expected returns are not estimable from price history at all. Beta is estimable and mildly non-stationary — Blume shrinkage cuts its MSE by a further **-10%**. The covariance matrix is the one place where a short window is actively dangerous: at 11 assets, a one-year window has about 42.0 observations per estimated parameter. |

> \U0001F4A1 **In plain words.** "How much history?" is really "how precisely can this thing be
> estimated, and how fast does it move?" — and those two answers are different for a mean, a
> beta and a covariance matrix.
"""
        ),
        md(
            r"""

## 1 · The claim, steelmanned

- **H₁.** Out-of-sample MSE is a U-shaped function of window length for a parameter that drifts
  (beta) and monotonically decreasing for one that does not (the mean).
- **H₂.** For the covariance matrix the binding constraint is **rows per parameter**, so the
  realised volatility of a minimum-variance portfolio falls with window length far past the
  point where a beta would want to stop.
- **H₃.** Shrinkage dominates window selection: Blume for beta, the grand mean for expected
  returns.
"""
        ),
        md(
            r"""

## 2 · So what? — the quantitative stakes

A minimum-variance portfolio built on a one-year window and one built on ten years are
*different portfolios* — different concentration, different turnover, different realised risk.
None of that difference is a view about markets; all of it is a consequence of an unexamined
default.
"""
        ),
        md(
            r"""

## 3 · How we'd know — the protocol

1. Decision dates are **year-ends**; the evaluation period is the following calendar year.
2. `train_slice` cuts strictly at the decision date;
   `test_beta_experiment_is_out_of_sample` mangles the future and checks nothing earlier moves.
3. Covariance is scored on the **realised volatility of the portfolio it produced**, not on a
   matrix distance — the loss function a user actually has.
4. Comparisons use **paired** squared errors (same sector, same year) and a HAC
   Diebold-Mariano, because two windows share most of their data.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 Beta: the U-shape, and what shrinkage does to it
"""
        ),
        code(
            r"""
bexp = st.beta_experiment(rets, sectors, data.MARKET)
bsc = st.score(bexp)
bexp["shrunk_error"] = bexp["estimate"].map(st.blume_shrunk) - bexp["realised"]
shr = bexp.groupby("window")["shrunk_error"].apply(lambda s: float((s ** 2).mean()))
comp = pd.DataFrame({"raw": bsc["mse"], "Blume-shrunk": shr}).loc[bsc.index]
fig, ax = plt.subplots(figsize=(9, 4.5))
comp.plot.bar(ax=ax, color=["#8b949e", "#2ea44f"])
ax.set_ylabel("MSE vs next year's beta"); ax.set_xlabel("window (years)")
ax.set_title("Shrinking toward 1.0 helps at every window length")
ax.legend(title="")
plt.show()
print(comp.round(5).to_string())
print()
for w in bsc.index:
    if w != st.EXPANDING:
        d = st.pairwise_dm(bexp, w, st.EXPANDING)
        print(f"DM({w} vs expanding) = {d['dm']:+.2f}  p={d['p_value']:.3f}  n={d['n']}")
"""
        ),
        md(
            r"""

### 4.2 The dispersion of realised betas — is there anything to track?
"""
        ),
        code(
            r"""
piv = bexp[bexp["window"] == 5].pivot_table(index="date", columns="sector",
                                             values="realised")
fig, ax = plt.subplots(figsize=(11, 5))
for c in piv.columns:
    ax.plot(piv.index, piv[c], marker="o", ms=3, lw=1, label=c)
ax.axhline(1.0, color="k", lw=1, ls="--")
ax.set_ylabel("realised beta over the year"); ax.set_title("Sector betas do move — slowly")
ax.legend(ncol=6, fontsize=7)
plt.show()
piv.std().round(3).to_frame("sd of realised beta across years").T
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** If betas never moved, the expanding window would win outright.
> They move enough to punish a ten-year memory and not enough to reward a one-year one.
"""
        ),
        md(
            r"""

### 4.3 Means: the estimator that ignores your data wins
"""
        ),
        code(
            r"""
mexp = st.mean_experiment(rets, sectors)
gm = st.grand_mean_benchmark(rets, sectors)
both = pd.concat([mexp, gm], ignore_index=True)
msc = st.score(both)
best_own = msc.drop(index=["grand mean"])["mse"].idxmin()
d = st.pairwise_dm(both, "grand mean", best_own)
print(msc.assign(annualised_bias=lambda x: x["bias"] * 252).round(8).to_string())
print(f"\nDM(grand mean vs best own-history window '{best_own}') = {d['dm']:+.2f} "
      f"(p={d['p_value']:.3f}); negative means the grand mean is better")
fig, ax = plt.subplots(figsize=(9, 4.5))
sub = both[both["window"].isin([best_own, "grand mean"])]
for name, g in sub.groupby("window"):
    ax.scatter(g["realised"] * 252 * 100, g["estimate"] * 252 * 100, s=18, alpha=0.7,
               label=str(name))
lim = [-40, 60]
ax.plot(lim, lim, color="k", lw=1, ls="--")
ax.set_xlabel("realised next-year return (%)"); ax.set_ylabel("estimate (%)")
ax.set_title("Predicted versus realised annual returns — neither estimator predicts anything")
ax.legend()
plt.show()
"""
        ),
        md(
            r"""

### 4.4 Covariance: optimism versus rows per parameter
"""
        ),
        code(
            r"""
cexp = st.covariance_experiment(rets, sectors)
csc = cexp.groupby("window").agg(realised=("realised_vol", "mean"),
                                 predicted=("predicted_vol", "mean"),
                                 shorts=("short_weight", "mean"),
                                 turnover=("turnover", "mean"),
                                 n_assets=("n_assets", "mean"))
order = [w for w in list(st.WINDOWS_YEARS) + [st.EXPANDING] if w in csc.index]
csc = csc.loc[order]
csc["optimism"] = csc["predicted"] / csc["realised"] - 1
n = len(sectors); n_params = n * (n + 1) / 2
csc["rows_per_param"] = [(w * 252 / n_params) if w != st.EXPANDING else np.nan
                         for w in csc.index]
print(csc.round(4).to_string())
fig, ax = plt.subplots(figsize=(9, 5))
sub = csc.dropna(subset=["rows_per_param"])
ax.plot(sub["rows_per_param"], sub["optimism"] * 100, marker="o", color="#c0392b")
for w, r in sub.iterrows():
    ax.annotate(f"{w}y", (r["rows_per_param"], r["optimism"] * 100),
                xytext=(4, 4), textcoords="offset points", fontsize=8)
ax.axhline(0, color="k", lw=1)
ax.set_xlabel("observations per covariance parameter")
ax.set_ylabel("in-sample optimism (%)")
ax.set_title("Michaud's error maximisation, in one line")
plt.show()
"""
        ),
        md(
            r"""

### 4.5 The synthetic control: a world with no structural change
"""
        ),
        code(
            r"""
rows = []
for ss, tag in ((1.0, "stationary, planted"), (0.0, "stationary, pure noise")):
    p, _, _ = data.synthetic_panel(n_assets=8, n_years=25, signal_strength=ss, seed=967)
    r = st.to_returns(p)
    sc = st.score(st.mean_experiment(r, tuple(p.columns), windows=(1, 3, 5)))
    for w in sc.index:
        rows.append({"world": tag, "window": str(w), "mse": sc.loc[w, "mse"]})
piv = pd.DataFrame(rows).pivot(index="window", columns="world", values="mse")
print(piv.round(9).to_string())
print("\nIn a world with no structural change the expanding window must win the mean,")
print("and it does. On the real tape it wins too — which tells you sector means are")
print("closer to stationary-and-unknowable than to drifting-and-trackable.")
"""
        ),
        md(
            r"""

## 5 · The verdict
"""
        ),
        code(
            r"""
summary = pd.DataFrame({
    "best window": [st.best_window(st.score(bexp)),
                    st.best_window(st.score(mexp)),
                    csc["realised"].idxmin()],
    "spread (worst/best - 1)": [
        st.score(bexp)["mse"].max() / st.score(bexp)["mse"].min() - 1,
        st.score(mexp)["mse"].max() / st.score(mexp)["mse"].min() - 1,
        csc["realised"].max() / csc["realised"].min() - 1],
}, index=["beta", "mean return", "covariance (portfolio vol)"])
summary.round(3)
"""
        ),
        md(
            r"""

## 6 · Is there one default?

No — and a study that produced one would be hiding the mechanism. The defensible default is a
*rule*: estimate how many observations per parameter your estimator needs, use at least that
many, and shrink whatever is left over.
"""
        ),
        md(
            r"""

## 7 · Going further

- **Endogenous windows** via Bai-Perron break tests, or the Pesaran-Timmermann optimal-window
  criterion, instead of a grid.
- **Exponential weighting** (a half-life rather than a cliff) — smoother, one parameter.
- **Ledoit-Wolf shrinkage** on the covariance matrix, which is study **975** and which mostly
  removes the window question by making short windows safe.
- **A ragged, wide cross-section** with delistings, where the observations-per-parameter
  arithmetic becomes binding rather than merely instructive.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
