"""Generate the two narrative notebooks for Study 25 (Clean-Slate) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the offline synthetic panel (momentum baked into the residual + a null). The
synthetic proves the machinery; the real verdict (the premium stays faint on the modern S&P 500, the
"cleaner cousin" claim fails a paired test, and what tames the crash is the stacked vol-management) is
quoted from [`docs/results.md`](../docs/results.md). Both notebooks walk the SAME seven desk beats
(see ../../../METHODOLOGY.md).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from clean_slate import data, momentum, strategy, decompose, extension

# Offline synthetic panel: a MOMENTUM tape (persistent idiosyncratic drift -> the *residual* carries the
# momentum) and a no-momentum NULL. The real S&P 500 verdict is in ../docs/results.md.
panel,  market,  truth = data.synthetic_panel(mom_strength=0.0016, seed=25)   # the momentum tape
panel0, market0, _     = data.synthetic_panel(mom_strength=0.0,    seed=25)   # the null
print(f"{truth.n_stocks} stocks x {truth.n_bars} days | baked mom_strength={truth.mom_strength} | null=0")
"""

R = dict(
    n_stocks="467", fp="cefc21b0fb14",
    res_alpha="+5.0", res_t="+1.0", res_sr="-0.01", turn="12", beta="-0.29",
    tot_alpha="+4.4", tot_t="+0.9",
    tot_skew="-0.04", tot_dd="-67", tot_worst="-22.2",
    res_skew="-0.23", res_dd="-70", res_worst="-22.3",
    stack_dd="-30", stack_sr="+0.16",
    pskew="-0.19", pskew_ci="[-0.88, +0.44]", pskew_p="36%",
    psr="-0.12", psr_ci="[-0.28, +0.02]", psr_p="5%", pmonths="174",
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Cleaner than total?: Unproven here](https://img.shields.io/badge/Cleaner_than_total%3F-Unproven_here-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Clean-Slate 🧼\n"
            "### Momentum crashes hard. What if you run it on the part of the return that *isn't* the market?\n\n"
            + BADGES +
            "[Study 24](../../24-stampede/) left momentum bruised: the famous premium has gone faint on "
            "the modern S&P 500, and it still carries a catastrophic crash. This study asks whether a "
            "clever tweak fixes the worst of it. **Residual momentum** (Blitz, Huij & Martens 2011): "
            "instead of ranking stocks by their *total* return, first strip out the part explained by "
            "the market — the systematic, beta-driven bit — and rank on the **residual**, the "
            "idiosyncratic leftover. The thesis: the tradable momentum lives in the residual, while the "
            "*crash* lives in the systematic exposure you just removed.\n\n"
            "This is the desk's eighth idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§3.7). We prove the engine on a synthetic panel where momentum is baked into the residual "
            "(and a null), then run it on the real S&P 500 — where the premium stays faint, the "
            "\"cleaner cousin\" claim **fails a paired test**, and what reliably collapses the crash is "
            "stacking vol-management on top.\n\n"
            "> 📓 **Plain-language layer.** The residualisation, the HAC alpha, the null-seed battery and "
            "the paired bootstrap are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** panel, so the real-S&P numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Is residual momentum real? | 🟡 **A higher point estimate than total** — residual-WML "
            f"alpha **{R['res_alpha']}%/yr** (*t* **{R['res_t']}**) vs total's {R['tot_alpha']}% (*t* "
            f"{R['tot_t']}) — but both are indistinguishable from zero on the modern S&P 500. |\n"
            "| Is it *cleaner* than total momentum? | ⚪ **Unproven here** — \"cleaner\" is a claim about "
            "a *difference*, so the gaps get a paired block-bootstrap: skew gap "
            f"**{R['pskew']}** (95% CI **{R['pskew_ci']}**), Sharpe gap **{R['psr']}** (95% CI "
            f"**{R['psr_ci']}**). Neither clears zero, and both lean the *wrong* way. |\n"
            "| What actually tames the crash? | ✅ **The stack** — residualise *and* vol-manage and the "
            f"drawdown collapses to **{R['stack_dd']}%** at a Sharpe of **{R['stack_sr']}**. |\n\n"
            "> Desk shorthand: **Signal `WEAK` · Tradability `FRAGILE` · Cleaner than total momentum? "
            "`UNPROVEN HERE`** — the crash is the engineerable part; the \"cleaner cousin\" billing "
            "doesn't survive a paired test on this tape."
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Decompose each stock's return into a market part and an idiosyncratic residual: "
            "$r_i = \\beta_i\\,r_{\\text{mkt}} + \\varepsilon_i$. Rank on the 12-1 momentum of the "
            "**residual** $\\varepsilon_i$, not the total $r_i$. Here's the residual-momentum decile "
            "profile on our synthetic tape — residual winners out-earn residual losers:"
        ),
        code(
            "sp = momentum.momentum_spread(panel, market, residual=True)\n"
            "d = sp['decile_fwd_ann']\n"
            "fig, ax = plt.subplots(); ax.bar(d.index, d.values, color='#2ea44f', alpha=.85)\n"
            "ax.set_xlabel('residual-momentum decile (0=losers, 9=winners)'); ax.set_ylabel('forward return (annualised %)')\n"
            "ax.set_title(f\"Residual winners keep winning: WML spread {sp['wml_ann_pct']:+.0f}%/yr (synthetic)\")\n"
            "plt.show()"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "If the momentum premium survives residualisation but the crash doesn't, you get the prize "
            "[Study 24](../../24-stampede/) couldn't bank: momentum's return without momentum's gut-"
            "wrenching tail. That's why residual (and its cousin, industry-neutral) momentum is what "
            "serious factor shops actually run. The desk's question is always the same: how much of the "
            "improvement is real on the sample you'd trade, and how much needs more than we've got?"
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Three checks:\n\n"
            "1. **Is the residual premium real?** The residual-WML alpha, with a *t*-stat — and a "
            "**null battery** (no persistence ⇒ no premium, checked across seeds, because one tape is "
            "one draw).\n"
            "2. **Is it cleaner than total momentum?** Not by eyeballing two point estimates — "
            "\"cleaner\" is a claim about a *difference*, so the skew and Sharpe gaps get a **paired "
            "block-bootstrap** on the books' common window.\n"
            "3. **Can the tail be tamed further?** Stack residualisation with vol-management.\n\n"
            "**Confirmed line:** the residual premium is significant *and* the paired gaps clear zero — "
            "anything less is directional, not proven."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · Residual momentum vs the null\n"
            "Run the residual-WML factor on both synthetic panels."
        ),
        code(
            "for label, (p, mk) in [('momentum', (panel, market)), ('null', (panel0, market0))]:\n"
            "    cmp = strategy.compare(p, mk, cost_bps=5.0); a = decompose.capm_alpha(p, mk, cost_bps=5.0)\n"
            "    print(f\"{label:9s}: residual Sharpe {cmp['residual']['sharpe']:+.2f} (total {cmp['total']['sharpe']:+.2f}), \"\n"
            "          f\"alpha {a['alpha_ann_pct']:+.1f}%/yr (HAC t {a['alpha_t']:+.1f})\")"
        ),
        md(
            "The momentum tape lights up (alpha HAC *t* ≈ 16) — the machine works. The null tape reads a "
            "*negative* alpha (≈ −4%/yr, *t* ≈ −2): alarming until you remember a single 16-year "
            "no-momentum tape is **one draw** plus a cost drag. The quants notebook runs a five-seed "
            "null battery and shows the spread is centred on ≈ 0 — this seed is just a tail draw."
        ),

        md(
            "### 4b · On the real market — the paired test ⚖️\n"
            "On the current S&P 500 (quoted from [`../docs/results.md`](../docs/results.md)):\n\n"
            f"- Residual-WML alpha **{R['res_alpha']}%/yr** (*t* **{R['res_t']}**) vs total momentum's "
            f"{R['tot_alpha']}% (*t* {R['tot_t']}) — a higher point estimate, but **both are noise-level**, "
            "and comparing two insignificant point estimates proves nothing.\n"
            f"- Head-to-head on the same months the residual book is *not* better behaved: monthly skew "
            f"**{R['res_skew']}** vs total's **{R['tot_skew']}**, drawdown **{R['res_dd']}%** vs "
            f"**{R['tot_dd']}%**, standalone Sharpe **{R['res_sr']}**, turnover **{R['turn']}×/yr**.\n"
            f"- The **paired block-bootstrap** of the differences settles it: skew gap **{R['pskew']}** "
            f"(95% CI **{R['pskew_ci']}**), Sharpe gap **{R['psr']}** (95% CI **{R['psr_ci']}**) — "
            "neither clears zero, and both lean the *wrong* way.\n\n"
            "Here is the same paired test on our synthetic tape, where the momentum *is* baked into the "
            "residual — so the residual book must win, and the test must see it:"
        ),
        code(
            "pb = decompose.paired_crash_bootstrap(panel, market, n_boot=2000, seed=0, cost_bps=5.0)\n"
            "print(f\"paired gaps (residual - total) on {pb['n_months']} synthetic months:\")\n"
            "print(f\"  Sharpe gap {pb['sharpe_diff']:+.2f}  95% CI [{pb['sharpe_ci_low']:+.2f}, {pb['sharpe_ci_high']:+.2f}]\"\n"
            "      f\"  -> {'clears zero' if pb['sharpe_significant'] else 'straddles zero'}\")\n"
            "print(f\"  skew   gap {pb['skew_diff']:+.2f}  95% CI [{pb['skew_ci_low']:+.2f}, {pb['skew_ci_high']:+.2f}]\"\n"
            "      f\"  -> {'clears zero' if pb['skew_significant'] else 'straddles zero'}\")\n"
            f"print('On the REAL S&P 500: skew gap {R['pskew']} {R['pskew_ci']}, Sharpe gap {R['psr']} {R['psr_ci']} -- nothing clears zero.')"
        ),

        md(
            "### 4c · The real fix — stack the defences\n"
            "Residualise *and* vol-manage. On the real S&P 500 the drawdown collapses:"
        ),
        code(
            "st = extension.defence_stack(panel, market, cost_bps=5.0)\n"
            "labels = ['total', 'residual', 'residual\\n+ vol-managed']\n"
            "dds = [st['total']['max_drawdown_pct'], st['residual']['max_drawdown_pct'], st['residual_vol_managed']['max_drawdown_pct']]\n"
            "fig, ax = plt.subplots(); ax.bar(labels, dds, color=['#c0392b','#dab617','#2ea44f'], alpha=.85)\n"
            "ax.set_ylabel('max drawdown (%)'); ax.set_title('The defence stack on the synthetic tape (gentle by construction)')\n"
            "plt.show()\n"
            f"print('On the REAL S&P 500: drawdown {R['tot_dd']}% (total) -> {R['res_dd']}% (residual alone) -> {R['stack_dd']}% (stacked).')"
        ),
        md(
            "The synthetic tape has only a mild, beta-driven tail, so there is little crash to engineer "
            "away there. The stack's value shows on the **real** tape: residualising *alone* does not "
            f"dent the drawdown (**{R['res_dd']}%** vs total **{R['tot_dd']}%**), but residualise *and* "
            f"vol-manage and it collapses to **{R['stack_dd']}%** at a Sharpe of **{R['stack_sr']}** — "
            "though that is the overlay's engineering as much as the residual's."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **Higher point estimate, still faint** — residual alpha {R['res_alpha']}%/yr (*t* "
            f"{R['res_t']}); both books are noise-level.\n"
            f"- **\"Cleaner\" is unproven** — the paired gaps (skew {R['pskew']}, Sharpe {R['psr']}) "
            "straddle zero and lean the wrong way.\n"
            f"- **The stack works** — residual + vol-managed cuts the drawdown to {R['stack_dd']}% at a "
            f"Sharpe of {R['stack_sr']}.\n\n"
            "> **Signal `WEAK` · Tradability `FRAGILE` · Cleaner than total momentum? `UNPROVEN HERE`.** "
            "The crash is the engineerable part; the cleaner-cousin billing didn't survive the paired test."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            f"- **The standalone book earns nothing** (Sharpe {R['res_sr']}) and you must short losers at "
            f"**{R['turn']}×/yr** turnover.\n"
            "- **But the ride is improvable.** Residual momentum is a clean *platform* for crash "
            f"management; stacked with vol-targeting the drawdown drops to **{R['stack_dd']}%**.\n"
            "- **Costs bite** (fast turnover), and the 1-factor residual leaves value-driven crash risk "
            "on the table — full FF3 residuals would help.\n\n"
            "> Tradability **`FRAGILE`**; \"cleaner than total\" is **`UNPROVEN HERE`** — the worked "
            "complement ([`../docs/extension.md`](../docs/extension.md)) stacks the defences."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **The defence stack** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): total → residual → residual + vol-managed — "
            "the tail only yields once both defences stack.\n"
            "- **Full Fama-French residuals.** A 1-factor (market) residual misses the *value* rebound "
            "that drives momentum crashes; FF3 (MKT, SMB, HML) residuals — the source's recipe — should "
            "shed more of the tail. Rerun the paired test on them.\n"
            "- **Industry-neutral momentum.** Another route to the same end (strip sector bets); does it "
            "beat residualisation?\n\n"
            "PRs welcome — add the FF3 residual, or find which neutralisation best tames the crash."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Clean-Slate — a quantitative teardown 🔬\n"
            "### Causal residualisation · residual-WML CAPM alpha (HAC) · null-seed battery · paired residual-vs-total bootstrap · the defence stack\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its standard error.* The steelman is §3.7 residual momentum (Blitz, "
            "Huij & Martens 2011): 12-1 momentum on factor-residual returns. We use a 1-factor (market) "
            "residual — a stated simplification — prove the engine on a synthetic panel, then compare to "
            "total momentum on the real S&P 500, **as a paired test of the differences**, not a beauty "
            "contest of two insignificant point estimates.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — is residual momentum real? | 🟡 `WEAK` | Strong on the control (alpha HAC *t* "
            f"≈ 16); on the modern S&P 500 the residual-WML alpha is **{R['res_alpha']}%/yr** (*t* = "
            f"**{R['res_t']}**) — a higher point estimate than total momentum ({R['tot_alpha']}%/t{R['tot_t']}) "
            "but still insignificant. |\n"
            "| **Tradability** | 🟡 `FRAGILE` | Standalone Sharpe "
            f"(**{R['res_sr']}**), fast turnover (**{R['turn']}×/yr**), short-the-losers. |\n"
            "| **Cleaner than total?** | ⚪ `Unproven here` | The paired block-bootstrap of the gaps on the "
            f"books' common {R['pmonths']} months: skew gap **{R['pskew']}** (95% CI **{R['pskew_ci']}**), "
            f"Sharpe gap **{R['psr']}** (95% CI **{R['psr_ci']}**) — neither clears zero, and both lean "
            "the *wrong* way. |\n\n"
            "> **In one sentence:** residualising momentum raises the alpha point estimate and gives a "
            "clean platform for crash management — but under a paired test the \"cleaner cousin\" "
            "advantage doesn't clear zero on this tape, and what reliably tames the crash "
            f"(**{R['tot_dd']}% → {R['stack_dd']}%**) is the vol-management stacked on top.\n\n"
            "*(This notebook executes on synthetic panels; the real S&P numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Residualise with a trailing (causal) regression: $\\hat\\varepsilon_{i,t} = r_{i,t} - "
            "\\hat\\beta_{i,t-1}\\,r_{\\text{mkt},t}$, $\\hat\\beta$ a rolling slope. Score "
            "$m_i = \\prod_{t-252}^{t-21}(1+\\hat\\varepsilon_i)-1$; WML = top-minus-bottom residual "
            "decile. The synthetic bakes the persistent drift into $\\theta$ (the residual); the market "
            "carries beta dispersion. The source uses FF3 residuals — we use 1-factor (market)."
        ),
        code(
            "rr = momentum.residual_returns(panel, market)\n"
            "print(f\"residual market-correlation {rr.mean(axis=1).corr(market):+.2f} \"\n"
            "      f\"vs raw {panel.mean(axis=1).corr(market):+.2f} -- the residual strips most of the market\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Momentum's crash is concentrated in its *systematic* exposure: after a market crash, the "
            "winners are low-beta defensives and the losers high-beta cyclicals, so a momentum book ends "
            "up implicitly short the market right before it rebounds (Daniel–Moskowitz 2016). "
            "Residualising removes exactly that bet. The open questions: how much premium survives, "
            "whether the residual book is *measurably* cleaner than the total book on the same window, "
            "and whether stacking vol-management finishes the job. Beats 4–6 answer all three."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Residual premium** (`decompose.capm_alpha`): residual-WML alpha + HAC *t*.\n"
            "2. **Cleaner?** (`decompose.crash_comparison` + `decompose.paired_crash_bootstrap`): the "
            "side-by-side profiles, then a **paired** circular block-bootstrap of the skew and Sharpe "
            "gaps on the books' common months — the third-axis stamp rests on the paired test, never on "
            "two standalone point estimates.\n"
            "3. **Stack** (`extension.defence_stack`): total → residual → residual + vol-managed.\n"
            "4. **Null calibration** (`decompose.null_alpha_battery`): no persistence ⇒ no premium, "
            "asserted on a *battery* of no-momentum seeds (one tape is one draw).\n\n"
            "**Confirmed line:** the residual premium is significant, *and* a paired gap clears zero in "
            "the residual's favour, *and* the stack tames the drawdown."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · Residual alpha, momentum vs null"),
        code(
            "for label, (p, mk) in [('momentum', (panel, market)), ('null', (panel0, market0))]:\n"
            "    a = decompose.capm_alpha(p, mk, cost_bps=5.0)\n"
            "    print(f\"{label:9s}: residual alpha {a['alpha_ann_pct']:+.1f}%/yr (HAC t {a['alpha_t']:+.1f}), \"\n"
            "          f\"beta {a['beta']:+.2f}, Sharpe {a['sharpe']:+.2f}, skew {a['skew']:+.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** The momentum tape's alpha (*t* ≈ 16) is the machine working. The "
            "null tape's *negative* alpha (≈ −4%/yr, *t* ≈ −2) is **not** a broken harness: a single "
            "16-year no-momentum tape is one draw (per-seed alpha sd ≈ 1.6%/yr, *t* sd ≈ 0.9), and the "
            "net book pays a ~0.7%/yr cost drag at 12×/yr turnover. Calibrate, don't eyeball — the "
            "battery below includes both observed tail seeds (24 and 25) and must centre on ≈ 0 gross:"
        ),
        code(
            "bat = decompose.null_alpha_battery(seeds=(0, 1, 2, 24, 25), cost_bps=5.0)\n"
            "display(bat.round(2))\n"
            "print(f\"null battery: mean alpha {bat['alpha_ann_pct'].mean():+.2f}%/yr (mean HAC t {bat['alpha_t'].mean():+.2f}) \"\n"
            "      f\"-- centred on ~0 net of the cost drag; max |t| {bat['alpha_t'].abs().max():.2f}\")"
        ),

        md("### 4b · Residual vs total — the crash comparison, then the paired test"),
        code(
            "cc = decompose.crash_comparison(panel, market, cost_bps=5.0)\n"
            "display(pd.DataFrame(cc).T.round(2))\n"
            f"print('On the REAL S&P 500: residual skew {R['res_skew']} (vs total {R['tot_skew']}), drawdown {R['res_dd']}% (vs {R['tot_dd']}%).')"
        ),
        md(
            "Side-by-side profiles invite eyeballing — but \"cleaner\" is a claim about a **difference** "
            "between two books that trade the same names on the same days, so it gets a **paired** "
            "circular block-bootstrap (6-month blocks — momentum-book months are autocorrelated) of the "
            "aligned monthly pairs. On the baked tape the residual book *must* win, and the test must "
            "see it:"
        ),
        code(
            "pb = decompose.paired_crash_bootstrap(panel, market, n_boot=2000, seed=0, cost_bps=5.0)\n"
            "print(f\"paired gaps (residual - total), {pb['n_months']} months, {pb['n_boot']} resamples, {pb['block_months']}-mo blocks:\")\n"
            "print(f\"  Sharpe gap {pb['sharpe_diff']:+.2f}  95% CI [{pb['sharpe_ci_low']:+.2f}, {pb['sharpe_ci_high']:+.2f}]  \"\n"
            "      f\"P(residual better) {pb['sharpe_frac_residual_better']:.0%}  significant: {pb['sharpe_significant']}\")\n"
            "print(f\"  skew   gap {pb['skew_diff']:+.2f}  95% CI [{pb['skew_ci_low']:+.2f}, {pb['skew_ci_high']:+.2f}]  \"\n"
            "      f\"P(residual better) {pb['skew_frac_residual_better']:.0%}  significant: {pb['skew_significant']}\")\n"
            f"print('On the REAL S&P 500 ({R['pmonths']} months): skew gap {R['pskew']} {R['pskew_ci']} (P {R['pskew_p']}), '\n"
            f"      'Sharpe gap {R['psr']} {R['psr_ci']} (P {R['psr_p']}) -- neither clears zero.')"
        ),
        md(
            "> 💡 **In plain words.** On the synthetic tape — where the momentum is planted in the "
            "residual by construction — the paired Sharpe gap clears zero (the residual book wins in "
            "~98% of resamples); the skew gap is directional only. On the **real** S&P 500 *nothing* "
            f"clears zero, and both gaps lean the wrong way (skew {R['pskew']}, Sharpe {R['psr']}). The "
            f"higher residual *alpha* there reflects the book's negative market beta ({R['beta']}) in a "
            "rising market as much as any extra momentum content. That is why the third axis reads "
            "`Unproven here`, not `Confirmed`."
        ),

        md("### 4c · The defence stack"),
        code(
            "st = extension.defence_stack(panel, market, cost_bps=5.0)\n"
            "display(pd.DataFrame(st).T.round(2))\n"
            f"print('On the REAL S&P 500: drawdown {R['tot_dd']}% (total) -> {R['res_dd']}% (residual alone) -> {R['stack_dd']}% (stacked, Sharpe {R['stack_sr']}).')"
        ),

        md("## Beat 5 · The verdict\n\n"
           f"- **Real on control** (4a): residual alpha HAC *t* ≈ 16; the null battery is centred on ≈ 0.\n"
           f"- **Faint here** (4b): alpha {R['res_alpha']}%/yr (*t* {R['res_t']}); the paired gaps "
           f"(skew {R['pskew']}, Sharpe {R['psr']}) straddle zero and lean the wrong way.\n"
           f"- **Stack tames the tail** (4c): drawdown {R['tot_dd']}% → {R['stack_dd']}% at Sharpe {R['stack_sr']}.\n\n"
           "> **Signal `WEAK` · Tradability `FRAGILE` · Cleaner than total momentum? `Unproven here`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           f"- **The standalone book earns nothing** (Sharpe {R['res_sr']}); short-the-losers; "
           f"{R['turn']}×/yr turnover.\n"
           "- **The right platform for crash management** — stacking vol-targeting drops the drawdown to "
           f"**{R['stack_dd']}%** — though [Study 24](../../24-stampede/) shows vol-management alone gets "
           "most of the way on the total book (−61% → −32% on its full window).\n"
           "- **A 1-factor residual under-cleans** — FF3 residuals would shed more of the value-driven crash.\n\n"
           "Tradability **`FRAGILE`**; cleaner than total `Unproven here`."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — the defence stack\n"
            "Total-WML vs residual-WML vs vol-managed residual-WML: where the tail actually yields."
        ),
        code(
            "st = extension.defence_stack(panel, market, cost_bps=5.0)\n"
            "for k in ['total', 'residual', 'residual_vol_managed']:\n"
            "    p = st[k]; print(f\"{k:22s}: Sharpe {p['sharpe']:+.2f}, skew {p['skew']:+.2f}, \"\n"
            "                     f\"worst month {p['worst_month_pct']:+.1f}%, max drawdown {p['max_drawdown_pct']:.0f}%\")\n"
            f"print('On the REAL S&P 500 (../docs/extension.md): drawdown {R['tot_dd']}% -> {R['res_dd']}% -> {R['stack_dd']}%.')"
        ),
        md(
            "**The result.** Residualising alone does not dent the real-tape drawdown "
            f"(**{R['res_dd']}%** vs total **{R['tot_dd']}%** — the value-driven part of the crash needs "
            "factors we don't have); vol-scaling removes the regime-clustered tail; and **stacked** the "
            f"drawdown falls from **{R['tot_dd']}%** to **{R['stack_dd']}%** while the Sharpe *rises* to "
            f"**{R['stack_sr']}**. The crash, the thing that made [Study 24](../../24-stampede/) "
            "`FRAGILE`, is engineerable — but that is the overlay's work as much as the residual's, and "
            "the faint *premium* on the modern large-cap sample is the part that isn't. Full run in "
            "[`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **FF3 residuals** (MKT, SMB, HML) — the source's recipe; should shed the value-driven crash "
            "the 1-factor residual leaves behind. Rerun `paired_crash_bootstrap` on them.\n"
            "- **Industry-/sector-neutral momentum** — an alternative neutralisation; compare the crash.\n"
            "- **Constant-volatility momentum** (Barroso–Santa-Clara) applied to the residual factor.\n\n"
            "PRs welcome — add the FF3 residual, or benchmark the neutralisations head-to-head."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
