"""Build the two narrative notebooks for Study 70 (Digital-Gold).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (BTC/SPY/GLD pull)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (digital_gold/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from digital_gold import data, strategy as st
ret = data.fetch_panel()                       # cache-first (BTC/SPY/GLD pull)
corr = st.correlations(ret)
monthly = (1 + ret).resample("ME").prod() - 1
cb = st.crisis_behavior(monthly)
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Bitcoin is digital gold?: Not supported](https://img.shields.io/badge/Bitcoin_is_digital_gold%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Digital-Gold ₿\n### Is bitcoin really 'digital gold' — a store of value that protects you?\n\n"
           + VERDICT +
           "Bitcoin's biggest selling point is that it's the new gold: scarce, a hedge against inflation "
           "and chaos, a safe haven. We checked. Bitcoin doesn't move like gold at all — it moves "
           "*increasingly like the stock market*, and in a crash it falls **harder** than stocks and "
           "never rises. It's been a phenomenal bet, but it's the opposite of a haven.\n\n"
           "> 📓 **Plain-language layer.** The correlations, their drift and the crash behaviour are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every number is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (BTC/SPY/GLD, 2014–2026) |\n|---|---|\n"
           "| \"Does BTC move like gold?\" | No: correlation with gold just **+0.09**. |\n"
           "| \"Is it a safe haven?\" | No: in crashes **−18% vs stocks −10%**, up **0%** of the time. |\n"
           "| \"So what is it?\" | A **high-beta risk asset** (+64%/yr, but −83% drawdown). |"),
        md("## 1 · The claim\n\nBitcoin is 'digital gold' — a scarce, decentralized store of value that "
           "hedges inflation and crisis, a modern substitute for the metal. The folk version: *when the "
           "system wobbles, bitcoin (like gold) protects you.*"),
        md("## 2 · So what?\n\nIf true, BTC would deserve a place beside gold as portfolio insurance. If "
           "instead it's just a very volatile risk asset, then owning it is a *return* bet — and sizing it "
           "as 'insurance' would be exactly backwards when a crisis hits."),
        md("## 3 · How would we even know?\n\nCompare BTC's correlation with gold and with stocks (and how "
           "that's changed over time), then watch what BTC does in the worst months for equities — the "
           "moment a haven is supposed to earn its keep."),
        code("bars=pd.Series({'BTC vs gold':corr['btc_gold'],'BTC vs stocks':corr['btc_stock']})\n"
             "ax=bars.plot.bar(rot=0,color=['#dab617','#c0392b'],title='What does bitcoin move with? (daily return correlation)')\n"
             "ax.set_ylabel('correlation'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print(f\"BTC-stock correlation: {corr['btc_stock_first']:+.2f} (early) -> {corr['btc_stock_second']:+.2f} (recent)\")"),
        md("## 4 · The teardown — it crashes *with* stocks, not against them\n\nIn the worst equity months, "
           "a haven holds or rises. Bitcoin did the opposite — it fell nearly twice as hard."),
        code("bars=pd.Series({'BTC':cb['btc_in_crash'],'gold':cb['gold_in_crash'],'stocks':cb['eq_in_crash']})*100\n"
             "ax=bars.plot.bar(rot=0,color=['#c0392b','#dab617','#8b949e'],title='Return in equity-crash months (SPY < -8%)')\n"
             "ax.set_ylabel('%/month'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print(f\"BTC rose in {cb['btc_up_share']:.0%} of {cb['n_crash']} crash months; gold in {cb['gold_up_share']:.0%}\")"),
        md("**Read it plainly.** Bitcoin is near-uncorrelated with *gold* and increasingly correlated with "
           "*stocks* — and when stocks crashed it fell harder and never rallied. It's a leveraged risk-on "
           "asset. It's also returned ~64%/yr, so a small sleeve flattered a portfolio — but that's a bet "
           "on the trend continuing, carrying an 83% drawdown, not a hedge."),
        md("## 5 · The verdict\n\n**Signal: None** (as digital gold) — uncorrelated with gold, falls in "
           "crashes. **Tradability: Fragile** — a small sleeve helped, but on a huge, drawdown-heavy "
           "trend. **Bitcoin is digital gold?: Not supported.**"),
        md("## 6 · Could you actually trade it?\n\nOnly as a high-risk *growth* sleeve, sized for an 80%+ "
           "drawdown — never as the haven it's marketed to be. If you want crisis ballast, that's gold's "
           "(imperfect) job ([69 Safe-Haven](../../69-safe-haven/)); bitcoin is the thing you'd want "
           "*less* of going into a storm."),
        md("## 7 · Going further 🚪\n\nThe counterpart to [69 Safe-Haven](../../69-safe-haven/) (the gold "
           "it's pitched to replace) and a diversification cousin of [68 All-Weather](../../68-all-weather/). "
           "Forks: vol-targeted BTC sizing, the post-ETF (2024) correlation regime, BTC vs gold across "
           "specific crises (COVID, 2022)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Digital-Gold — a quantitative teardown 🔬\n### Correlations and their drift · crash-month behaviour · the small-sleeve overlay\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The 'digital "
           "gold' thesis, measured — a high-beta risk asset wearing a safe-haven costume.\n\n"
           "> ⚠️ **Not investment advice.** BTC-USD / SPY / GLD daily total returns, 2014–2026 (Yahoo). "
           "Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal (digital gold) | **None** | corr w/ gold +0.09; falls in crashes |\n"
           "| Tradability (sleeve) | **Fragile** | 5% BTC Sharpe 0.82→0.95, on −83% DD |\n"
           "| Is digital gold? | **Not supported** | rising stock corr, no haven |\n\n"
           "> 💡 *In plain words:* a return bet dressed as insurance."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** BTC behaves like gold (correlated with gold, "
           "uncorrelated with stocks).\n- **H₂:** BTC is a safe haven (holds/rises when equities crash).\n"
           "- **H₃:** it's a store of value (stable enough to be insurance, not a leveraged bet)."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂/H₃ are the 'digital gold' case. If they fail, "
           "BTC is a risk asset, and any portfolio role is a *return* decision (with tail risk), not a "
           "hedging one — the difference between sizing it as insurance vs as a speculative sleeve."),
        md("## 3 · How we'd know — the protocol\n\nCorrelations (BTC–gold, BTC–stock, first vs second "
           "half) → crash-month returns vs gold and stocks → a small-sleeve overlay to see *why* it "
           "helped (return, not hedging)."),
        md("## 4 · The teardown"),
        md("### 4.1 Correlations and their drift — H₁"),
        code("print({k:round(v,3) for k,v in corr.items()})"),
        md("> 💡 *In plain words:* BTC–gold +0.09 (not gold-like), BTC–stock rising +0.13→+0.36 "
           "(increasingly a risk asset). **H₁ rejected.**"),
        md("### 4.2 Crash-month behaviour — H₂"),
        code("print({k:(round(v,3) if isinstance(v,float) else v) for k,v in cb.items()})"),
        md("> 💡 *In plain words:* in equity-crash months BTC −17.7% vs stocks −10.1%, up in **0%** of "
           "them; gold held flat. BTC falls *harder* than the thing it's meant to hedge. **H₂ rejected.**"),
        md("### 4.3 The sleeve — why it still 'helped' (and H₃)"),
        code("sl = st.sleeve_effect(ret['SPY'], ret['BTC-USD'])\n"
             "show = sl.copy()\n"
             "for c in ['ann','vol','max_drawdown']: show[c] = (show[c]*100).round(1)\n"
             "show['sharpe'] = show['sharpe'].round(2)\n"
             "display(show[['ann','vol','sharpe','max_drawdown']])"),
        md("A 5–10% sleeve raised Sharpe (0.82→0.95→1.05) — but read the source: BTC returned +64%/yr. "
           "The 'improvement' is a **return** contribution riding a historic trend, with an −83% asset "
           "drawdown underneath. That's not stability; **H₃ rejected** — it's a leveraged growth bet, not "
           "a store of value."),
        md("## 5 · The verdict\n\nH₁/H₂/H₃ all rejected → Signal `NONE` (as digital gold), Tradability "
           "`FRAGILE` (a return sleeve, not a hedge), is-digital-gold `NOT SUPPORTED`. The fingerprinted "
           "run is in [`docs/results.md`](../docs/results.md)."),
        md("## 6 · Could you trade it?\n\nAs a small, vol-aware *growth* sleeve sized for catastrophic "
           "drawdown — yes; as a haven or inflation hedge — no. The crash-month evidence (Conlon-McGee "
           "2020 on COVID; our 2014–2026 sample) is unambiguous: BTC is risk-on, not insurance."),
        md("## 7 · Going further\n\nForks: (a) vol-target BTC sizing; (b) the post-spot-ETF (2024) "
           "correlation regime; (c) BTC vs gold across named crises; (d) BTC's beta to the Nasdaq / "
           "liquidity. Backlog: [`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
