"""Notebook builder for Study 977 — Maximum Diversification.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Maximum Diversification \U0001F9ED
### Not "how little risk can I run" but "how much of the risk I hold cancels out"

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Mirage](https://img.shields.io/badge/Usefulness-Mirage-c0392b?style=flat-square)

A minimum-variance optimiser will happily put everything in the quietest asset it can find and
call the result diversified. Choueifaty's answer is to maximise a *ratio* instead: the average
volatility of what you hold, divided by the volatility of the portfolio. This notebook builds
it, checks it is genuinely different, and races it against the version that needs no maths.

> \U0001F4D3 **This is the plain-language layer.** The closed form, the degenerate case and the
> paired tests are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is it really a different portfolio? | Yes — a quarter of the book differs from minimum variance, and it holds far more names. |
| Does it deliver the diversification it promises? | Mostly. The ratio slips out of sample, and the slippage is the estimation error made visible. |
| Does it beat plain inverse-volatility weighting? | Barely, and not everywhere. That is the finding. |
| When are the two objectives the same thing? | When every asset has the same volatility. Then maximising the ratio *is* minimising variance. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Minimum variance is not diversification — it is concentration in whatever happens to be
> quiet. Diversification is holding risky things whose risks cancel."*

Written down, that is the diversification ratio: the average volatility you hold, divided by the
volatility you end up running.
"""
        ),
        code(
            r"""
from max_div import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
panels = {"sectors": [c for c in data.SECTORS if rets[c].notna().sum() > 1500],
          "multi-asset": [c for c in data.MULTI if rets[c].notna().sum() > 3000]}
print(f"as-of {data.AS_OF}")
for tag, cols in panels.items():
    sub = rets[cols].dropna(how="any")
    v = sub.std() * np.sqrt(252)
    print(f"  {tag:12s} {len(cols):2d} assets, vol {v.min():.1%} to {v.max():.1%}, "
          f"{len(sub):,} sessions")
"""
        ),
        md(
            r"""

## 2 · What the ratio measures
"""
        ),
        code(
            r"""
cols = panels["multi-asset"]
sub = rets[cols].dropna(how="any")
cov = np.cov(sub.iloc[-756:].to_numpy(), rowvar=False, ddof=1)
rows = []
for rho in (0.0, 0.2, 0.4, 0.6, 0.8, 1.0):
    n = len(cols)
    corr = np.full((n, n), rho); np.fill_diagonal(corr, 1.0)
    sd = np.sqrt(np.diag(cov))
    c = np.outer(sd, sd) * corr
    rows.append({"correlation": rho,
                 "DR of 1/N": st.diversification_ratio(st.equal_weights(c), c),
                 "DR of the MDP": st.diversification_ratio(st.max_div_weights(c), c)})
d = pd.DataFrame(rows).set_index("correlation")
fig, ax = plt.subplots(figsize=(9, 4.5))
d.plot(ax=ax, marker="o", color=["#8b949e", "#2ea44f"])
ax.axhline(1.0, color="k", lw=1, ls="--")
ax.set_ylabel("diversification ratio")
ax.set_title("Perfectly correlated assets cannot be diversified, whatever the weights")
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

## 3 · The portfolio it builds
"""
        ),
        code(
            r"""
w_md = st.max_div_weights(cov)
w_mv = st.min_variance_weights(cov)
w_iv = st.inverse_vol_weights(cov)
W = pd.DataFrame({"most diversified": w_md, "minimum variance": w_mv,
                  "inverse volatility": w_iv}, index=cols)
fig, ax = plt.subplots(figsize=(11, 4.5))
W.plot.bar(ax=ax, color=["#2ea44f", "#c0392b", "#8b949e"])
ax.set_ylabel("weight"); ax.legend(title="")
ax.set_title("Three long-only answers to the same covariance matrix")
plt.show()
print(f"share of the book that differs from minimum variance: "
      f"{np.abs(w_md - w_mv).sum() / 2:.1%}")
print(f"diversification ratio — MDP {st.diversification_ratio(w_md, cov):.3f}, "
      f"min-var {st.diversification_ratio(w_mv, cov):.3f}, "
      f"inv-vol {st.diversification_ratio(w_iv, cov):.3f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Minimum variance piles into the bond sleeves; the MDP keeps a
> real position in the volatile assets because their volatility is the numerator of its
> objective. Same matrix, different question.
"""
        ),
        md(
            r"""

## 4 · Out of sample
"""
        ),
        code(
            r"""
wf = st.walk_forward(sub, window=252, step=63, cost_bps=5.0)
s = st.summarise(wf)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].bar([st.METHOD_LABEL[m][:14] for m in s.index], s["realised_vol"] * 100,
            color="#2ea44f")
axes[0].set_ylabel("realised volatility (%)"); axes[0].set_title("What each book actually ran")
axes[1].bar([st.METHOD_LABEL[m][:14] for m in s.index], s["dr_in"], color="#8b949e",
            label="promised")
axes[1].bar([st.METHOD_LABEL[m][:14] for m in s.index], s["dr_out"], color="#c0392b",
            alpha=0.75, label="delivered")
axes[1].set_ylabel("diversification ratio"); axes[1].legend()
axes[1].set_title("Promised versus delivered")
for a in axes:
    plt.setp(a.get_xticklabels(), rotation=20, ha="right", fontsize=8)
plt.show()
s[["realised_vol", "sharpe", "dr_in", "dr_out", "dr_slippage", "turnover",
   "effective_n"]].round(3)
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** It is a genuinely different objective. The most diversified portfolio's weights differ from the minimum-variance ones by **100%** of the book on the multi-asset panel and 35% on sectors, and it achieves an in-sample diversification ratio of **1.78** against 1.21 — by construction, but it is worth confirming the implementation does what the formula says. On a panel of equal-volatility assets the two objectives collapse into one, and the two weight vectors agree to 1.9e-16, which is the boundary of the distinction.

**Usefulness: Mirage.** The objective is delivered but the advantage is not free money. Out of sample the realised diversification ratio slips to 1.79 (+1% of the in-sample value), realised volatility is **9.95%** against 7.23% for plain inverse volatility (paired *t* = -2.96) and 9.58% for 1/N, and it turns over 0.32 a rebalance against 0.08. It beats the free competitor on **0 of 2** panels.
"""
        ),
        md(
            r"""

## 6 · Going further \U0001F6AA

- **The economic claim** — that the MDP is the maximum-Sharpe portfolio when expected returns
  scale with volatility — is testable and is not tested here.
- **Shrunk covariance** (study 975) inside the MDP is the obvious upgrade; risk-based methods
  inherit whatever the matrix gets wrong.
- **Factor decomposition** (Scherer 2011): how much of any risk-based portfolio's record is
  just a low-volatility tilt?
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Maximum Diversification — a quantitative teardown \U0001F52C
### Closed form on the correlation matrix · brute-force check · the equal-volatility collapse · out-of-sample DR

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Mirage](https://img.shields.io/badge/Usefulness-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Two controls
carry the study: the **degenerate case**, where equal volatilities make maximum diversification
and minimum variance the same problem (so the implementation can be proved correct), and
**inverse-volatility weighting**, the free competitor that decides whether the correlation
matrix is earning anything.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date
> in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from max_div import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
panels = {"sectors": [c for c in data.SECTORS if rets[c].notna().sum() > 1500],
          "multi-asset": [c for c in data.MULTI if rets[c].notna().sum() > 3000]}
print(f"as-of {data.AS_OF}")
for tag, cols in panels.items():
    sub = rets[cols].dropna(how="any")
    v = sub.std() * np.sqrt(252)
    print(f"  {tag:12s} {len(cols):2d} assets, vol {v.min():.1%} to {v.max():.1%}, "
          f"{len(sub):,} sessions")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | It is a genuinely different objective. The most diversified portfolio's weights differ from the minimum-variance ones by **100%** of the book on the multi-asset panel and 35% on sectors, and it achieves an in-sample diversification ratio of **1.78** against 1.21 — by construction, but it is worth confirming the implementation does what the formula says. On a panel of equal-volatility assets the two objectives collapse into one, and the two weight vectors agree to 1.9e-16, which is the boundary of the distinction. |
| **Usefulness** | Mirage | The objective is delivered but the advantage is not free money. Out of sample the realised diversification ratio slips to 1.79 (+1% of the in-sample value), realised volatility is **9.95%** against 7.23% for plain inverse volatility (paired *t* = -2.96) and 9.58% for 1/N, and it turns over 0.32 a rebalance against 0.08. It beats the free competitor on **0 of 2** panels. |

> \U0001F4A1 **In plain words.** The objective is real and distinct. What it buys, out of
> sample, is mostly available for free.
"""
        ),
        md(
            r"""

## 1 · The claim, as algebra

- **H₁.** ``DR(w) = (w'σ)/√(w'Σw)`` is maximised by ``w ∝ diag(σ)⁻¹ C⁻¹ 1`` (unconstrained),
  where ``C`` is the correlation matrix.
- **H₂.** With equal volatilities, ``DR`` is a monotone decreasing function of portfolio
  variance, so the MDP **is** the minimum-variance portfolio.
- **H₃.** With dispersed volatilities the two differ materially.
- **H₄.** Out of sample, the MDP's realised volatility beats inverse-volatility weighting.
"""
        ),
        md(
            r"""

## 2 · The closed form, checked by brute force
"""
        ),
        code(
            r"""
cov3 = np.outer([0.10, 0.18, 0.30], [0.10, 0.18, 0.30]) *        (np.full((3, 3), 0.25) + 0.75 * np.eye(3))
w_star = st.max_div_weights(cov3)
grid = np.linspace(0, 1, 201)
best, best_dr = None, -np.inf
for a in grid:
    for b in grid:
        if a + b > 1:
            continue
        w = np.array([a, b, 1 - a - b])
        dr = st.diversification_ratio(w, cov3)
        if dr > best_dr:
            best, best_dr = w, dr
print(f"closed form : {np.round(w_star, 4)}  DR {st.diversification_ratio(w_star, cov3):.6f}")
print(f"brute force : {np.round(best, 4)}  DR {best_dr:.6f}")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The degenerate case — where the two objectives are one
"""
        ),
        code(
            r"""
rows = []
for spread in (0.0, 0.05, 0.1, 0.2, 0.3):
    n = 10
    vols = np.linspace(0.15 - spread / 2, 0.15 + spread / 2, n)
    corr = np.full((n, n), 0.35); np.fill_diagonal(corr, 1.0)
    c = np.outer(vols, vols) * corr
    gap = np.abs(st.max_div_weights(c) - st.min_variance_weights(c)).sum() / 2
    rows.append({"volatility spread": spread, "share of book differing": gap})
d = pd.DataFrame(rows).set_index("volatility spread")
fig, ax = plt.subplots(figsize=(9, 4.5))
(d * 100).plot(ax=ax, marker="o", color="#2ea44f", legend=False)
ax.set_ylabel("% of the book that differs from minimum variance")
ax.set_title("At zero volatility dispersion the two objectives are the same problem")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** This is the honest boundary of the "different objective"
> claim. Everything the MDP does differently comes from *volatility dispersion*, not from
> correlations alone.
"""
        ),
        md(
            r"""

### 3.2 The full scoreboard, both panels
"""
        ),
        code(
            r"""
all_wf = {}
for tag, cols in panels.items():
    all_wf[tag] = st.walk_forward(rets[cols].dropna(how="any"), window=252, step=63,
                                  cost_bps=5.0)
    print(f"--- {tag} ---")
    print(st.summarise(all_wf[tag])[["realised_vol", "sharpe", "dr_in", "dr_out",
                                     "dr_slippage", "turnover", "effective_n"]]
          .round(4).to_string())
    print()
"""
        ),
        md(
            r"""

### 3.3 Paired tests, and the free competitor
"""
        ),
        code(
            r"""
rows = []
for tag, wf in all_wf.items():
    for o in ("min_var", "inv_vol", "equal", "risk_parity"):
        p = st.paired_test(wf, "max_div", o)
        rows.append({"panel": tag, "vs": st.METHOD_LABEL[o], "vol diff": p["diff"],
                     "t (MDP quieter > 0)": -p["t"], "MDP wins": p["win_rate"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 4.5))
d.pivot(index="vs", columns="panel", values="t (MDP quieter > 0)").plot.bar(ax=ax)
ax.axhline(0, color="k", lw=1); ax.axhline(2, color="#c0392b", ls="--", lw=1)
ax.set_ylabel("paired t"); ax.legend(title="")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.4 The ratio, promised and delivered
"""
        ),
        code(
            r"""
wf = all_wf["multi-asset"]
piv_in = wf.pivot(index="date", columns="method", values="dr_in")
piv_out = wf.pivot(index="date", columns="method", values="dr_out")
fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(piv_in.index, piv_in["max_div"], lw=1.5, color="#2ea44f", label="MDP, in sample")
ax.plot(piv_out.index, piv_out["max_div"], lw=1.5, color="#c0392b", label="MDP, delivered")
ax.plot(piv_out.index, piv_out["equal"], lw=1, color="#8b949e", label="1/N, delivered")
ax.set_ylabel("diversification ratio"); ax.legend()
ax.set_title("Optimising a quantity and delivering it are different things")
plt.show()
print((piv_out / piv_in - 1).describe().round(3).to_string())
"""
        ),
        md(
            r"""

### 3.5 Concentration and turnover
"""
        ),
        code(
            r"""
s = st.summarise(all_wf["multi-asset"])
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].bar([st.METHOD_LABEL[m][:14] for m in s.index], s["effective_n"], color="#2ea44f")
axes[0].set_ylabel("effective number of positions")
axes[1].bar([st.METHOD_LABEL[m][:14] for m in s.index], s["turnover"], color="#c0392b")
axes[1].set_ylabel("turnover per rebalance")
for a in axes:
    plt.setp(a.get_xticklabels(), rotation=20, ha="right", fontsize=8)
plt.show()
s[["effective_n", "max_weight", "turnover"]].round(3)
"""
        ),
        md(
            r"""

### 3.6 Window sensitivity
"""
        ),
        code(
            r"""
rows = []
sub = rets[panels["multi-asset"]].dropna(how="any")
for w in (126, 252, 504, 756):
    s_ = st.summarise(st.walk_forward(sub, window=w, step=63, cost_bps=5.0))
    rows.append({"window": w, **{st.METHOD_LABEL[m]: s_.loc[m, "realised_vol"]
                                 for m in st.METHODS}})
d = pd.DataFrame(rows).set_index("window")
fig, ax = plt.subplots(figsize=(9, 4.5))
(d * 100).plot(ax=ax, marker="o")
ax.set_ylabel("realised volatility (%)"); ax.legend(fontsize=8, title="")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
summary = {}
for tag, wf in all_wf.items():
    s_ = st.summarise(wf)
    summary[tag] = {"MDP vol": s_.loc["max_div", "realised_vol"],
                    "inv-vol vol": s_.loc["inv_vol", "realised_vol"],
                    "min-var vol": s_.loc["min_var", "realised_vol"],
                    "1/N vol": s_.loc["equal", "realised_vol"],
                    "t vs inv-vol": -st.paired_test(wf, "max_div", "inv_vol")["t"],
                    "DR delivered": s_.loc["max_div", "dr_out"],
                    "DR slippage": s_.loc["max_div", "dr_slippage"]}
pd.DataFrame(summary).T.round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **The maximum-Sharpe interpretation**: the MDP is optimal if expected return is proportional
  to volatility. Test that assumption directly and the study becomes a return study.
- **Shrinkage inside the MDP** (study 975), and **hierarchical clustering** (study 976): the
  three risk-based schemes are rarely compared on the same panel with the same estimator, and
  this desk now has all three.
- **Factor attribution** of the MDP's returns (Scherer 2011) — how much is low-volatility, how
  much is genuinely the construction?
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
