"""Build the two narrative notebooks for Study 44 (Growth-Spurt).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/growth_spurt_ag.parquet + _ret.parquet,
built by examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (growth_spurt/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from growth_spurt import data, strategy as st
ag, fwd = data.fetch_panel()                  # cache-first; built by examples/verify.py --fetch
h = st.quantile_hedge(ag, fwd, q=0.2)
mkt = st.market_annual(fwd).reindex(h.index)
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Sharpe 0.835 replicates?: Busted](https://img.shields.io/badge/Sharpe_0.835_replicates%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Growth-Spurt 📈\n### The best-looking number on the list (Sharpe 0.835) — on real, tradable stocks\n\n"
           + VERDICT +
           "The asset-growth effect — buy firms that grow their assets *slowly*, short the fast growers "
           "— carries the highest headline Sharpe in the whole vendor backlog. We rebuild it on real "
           "balance-sheet data (total assets from SEC filings) for large, liquid stocks. It doesn't just "
           "weaken — the sign flips.\n\n"
           "> 📓 **Plain-language layer.** The construction and the three reasons it fails are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The pitch | On tradable large caps |\n|---|---|\n"
           "| \"Slow growers beat fast growers (Sharpe 0.835)\" | The hedge earns **−1.6%/yr** — the sign is backwards. |\n"
           "| \"A robust accounting anomaly\" | Fast growers **out**-earned slow ones (+21.4% vs +19.8%). |\n"
           "| \"Just sort and hold\" | The effect hides in micro-caps you can't trade at scale. |"),
        md("## 1 · The claim\n\nCooper, Gulen & Schill (2008): companies that expand their balance sheets "
           "fast — big capex, acquisitions, share issuance — subsequently disappoint, while frugal firms "
           "outperform. Sort on year-on-year **total-asset growth**, long the bottom, short the top."),
        md("## 2 · So what?\n\nA 0.835 Sharpe from a number every company files annually would be a gift. "
           "But headline Sharpes from accounting anomalies famously come from the market's smallest, least "
           "tradable names. Does this one survive where you could actually put money?"),
        md("## 3 · How would we even know?\n\nPull **real total assets from SEC EDGAR** for ~400 large-cap "
           "names, compute each firm's asset growth, sort into a long-low / short-high book, and measure "
           "the hedge against the equal-weight universe — on stocks you could actually hold."),
        code("leg = pd.DataFrame({'low-growth (long)':[st.summary(h['low_growth'])['mean']],\n"
             "                    'high-growth (short)':[st.summary(h['high_growth'])['mean']]}, index=['mean annual return'])\n"
             "ax = (leg.T*100).plot.bar(legend=False, rot=0, color=['#2ea44f','#c0392b'],\n"
             "        title='The sign is backwards: fast growers OUT-earned slow ones')\n"
             "ax.set_ylabel('mean annual return (%)'); plt.show()\n"
             "print('hedge (low - high): %+.2f%%/yr  Sharpe %.2f' % (st.summary(h['hedge'])['mean']*100, st.summary(h['hedge'])['sharpe']))"),
        md("## 4 · The teardown\n\nThe long-short loses money over 2005–2025 — not because the year was "
           "unlucky, but because on liquid large caps the premium isn't there to harvest."),
        code("eq=(1+h['hedge']).cumprod()\n"
             "ax=eq.plot(title='Growth of $1 in the asset-growth long-short (large caps)',lw=1.8)\n"
             "ax.axhline(1.0,color='k',lw=.8,ls='--'); ax.set_ylabel('growth of $1'); plt.show()"),
        md("**Read it plainly.** A line that drifts *down*. The vendor's 0.835 came from a corner of the "
           "market — tiny, illiquid stocks — that a tradable strategy can't reach. Move to names you "
           "could hold and the edge is gone."),
        md("## 5 · The verdict\n\n**Signal: None** — no premium on tradable large caps (the sign even "
           "flips). **Tradability: Mirage** — 0.835 lives where you can't trade. **Replicates?: Busted.**"),
        md("## 6 · Could you actually trade it?\n\nNot the headline version. To get the advertised Sharpe "
           "you'd need to short hundreds of micro-caps — wide spreads, hard-to-borrow, and the exact "
           "names most prone to survivorship and data errors. The liquid version doesn't pay."),
        md("## 7 · Going further 🚪\n\nThe quants notebook gives the three reasons (micro-cap "
           "concentration, the investment factor, survivorship) and the numbers. Next: "
           "[Study 45 Vanishing-Act](../../45-vanishing-act/) — the size premium, the anomaly that "
           "*defined* post-publication decay."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Growth-Spurt — a quantitative teardown 🔬\n### The long-short on real EDGAR data · the backwards sign · micro-caps, the investment factor, survivorship\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We rebuild the "
           "asset-growth long-short on SEC balance-sheet data for large caps and explain why the highest "
           "headline Sharpe on the list doesn't replicate.\n\n"
           "> ⚠️ **Not investment advice.** EDGAR `Assets` (10-K) + Yahoo annual returns, ~399 current "
           "S&P 500 members (survivorship-biased, large-cap — both stated), 2005–2025. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | hedge −1.6%/yr, Sharpe −0.12, sign reversed |\n"
           "| Tradability | **Mirage** | 0.835 lives in micro-caps, not large caps |\n"
           "| Replicates? | **Busted** | even a survivorship-flattered test can't find it |\n\n"
           "> 💡 *In plain words:* the most attractive number on the list is the least tradable."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** low-asset-growth firms out-earn high-growth ones "
           "(positive hedge).\n- **H₂ (the pitch):** the hedge delivers a Sharpe near the vendor's 0.835 "
           "on a tradable universe.\n- **H₃:** the effect is a standalone anomaly, not a known factor."),
        md("## 2 · So what? — what rides on each\n\nIf H₂ holds, an annual balance-sheet sort beats the "
           "market handsomely. If it fails on large caps, the headline is a micro-cap artifact."),
        md("## 3 · How we'd know — the protocol\n\nEDGAR `Assets` → fiscal-year asset growth → annual "
           "long-bottom-20% / short-top-20% → hedge vs equal-weight universe → inspect the leg means and "
           "the sign → weigh the three standard explanations."),
        md("## 4 · The teardown"),
        md("### 4.1 The long-short, by year"),
        code("display(h.round(3))\n"
             "s=st.summary(h['hedge']); print(f\"hedge: mean {s['mean']:+.2%}/yr  Sharpe {s['sharpe']:.2f}  hit {s['hit_rate']:.0%}  n={s['n']}\")"),
        md("> 💡 *In plain words:* a negative mean and a sub-50% hit rate. **H₁ rejected** on large caps."),
        md("### 4.2 The backwards sign"),
        code("print('long  (low growth) mean: %+.2f%%' % (st.summary(h['low_growth'])['mean']*100))\n"
             "print('short (high growth) mean: %+.2f%%' % (st.summary(h['high_growth'])['mean']*100))\n"
             "print('vendor headline Sharpe: 0.835  |  our hedge Sharpe: %.2f' % st.summary(h['hedge'])['sharpe'])"),
        md("> 💡 *In plain words:* high-growth firms *beat* low-growth ones here — the opposite of the "
           "anomaly. **H₂ rejected.**"),
        md("### 4.3 Why it fails — three standard reasons"),
        md("1. **Micro-cap concentration.** Hou-Xue-Zhang (2020) show accounting anomalies, asset growth "
           "included, concentrate in the smallest names; a large-cap universe is the wrong place.\n"
           "2. **The investment factor.** In Fama-French five-factor, asset growth *is* the CMA factor — "
           "already priced, not a free anomaly. **H₃ rejected.**\n"
           "3. **Survivorship flatters the wrong way.** Current members exclude delisted growth blow-ups "
           "that would *help* the short — so even this biased test, which should favour the strategy, "
           "still finds nothing."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all rejected on tradable names → Signal `NONE`, Tradability "
           "`MIRAGE`, headline `BUSTED`."),
        md("## 6 · Could you trade it?\n\nOnly by shorting hundreds of micro-caps — illiquid, "
           "hard-to-borrow, survivorship- and data-fragile. The liquid version is flat-to-negative. The "
           "0.835 is a property of the untradable tail."),
        md("## 7 · Going further\n\nForks: (a) add a small/mid-cap ETF-of-stocks universe to see the "
           "effect strengthen toward the micro-cap end; (b) residualise asset growth against the CMA "
           "factor — does anything remain? (c) point-in-time membership to kill the survivorship flatter. "
           "Backlog: [`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
