"""Build the two narrative notebooks for Study 67 (Fed-Drift).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (shared SPY pull)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (fed_drift/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from fed_drift import data, strategy as st
ret, fomc = data.fetch_panel()                 # cache-first (shared SPY pull)
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Still an edge after publication?: Not supported](https://img.shields.io/badge/Still_an_edge_after_publication%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Fed-Drift 🏦\n### Do stocks quietly drift up the day before a Fed meeting?\n\n"
           + VERDICT +
           "One of the strangest facts in markets: for two decades, almost all of the stock market's "
           "gains arrived in the 24 hours *before* scheduled Fed announcements. Just ~3% of trading days "
           "— the day before each FOMC meeting — carried a *fifth* of the market's entire return. Then "
           "academics published it, and it vanished.\n\n"
           "> 📓 **Plain-language layer.** The drift table, the t-stat, and the pre/post-publication split "
           "are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every number is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (SPY, 1993–2026) |\n|---|---|\n"
           "| \"Do stocks drift up pre-FOMC?\" | Yes: **+0.17%/day vs +0.04%**, 3% of days = 11.5% of return. |\n"
           "| \"Was it big?\" | Pre-2011, those ~3% of days earned **19.8%** of the market's total return. |\n"
           "| \"Can you trade it now?\" | No — post-2011 it decayed to a normal day (t 0.4). |"),
        md("## 1 · The claim\n\nLucca & Moench (2015): in the 24 hours before a scheduled FOMC statement, "
           "equities earn an outsized, oddly reliable return — enough to explain most of the post-1994 "
           "equity premium. The folk version: *something leaks, or risk gets repriced, right before the "
           "Fed speaks.*"),
        md("## 2 · So what?\n\nIf true and persistent, it's a calendar you could trade with a known "
           "schedule years in advance — be long into the pre-FOMC day, flat otherwise. The question is "
           "whether it survived being one of the most-cited findings in modern finance."),
        md("## 3 · How would we even know?\n\nTag the trading session just before each of 264 scheduled "
           "FOMC announcements since 1993, compare SPY's return on those days to every other day, and "
           "split the sample at 2011 (when the paper circulated) to see if the edge decayed."),
        code("t=st.drift_table(ret,fomc,lead=1)\n"
             "bars=pd.Series({'pre-FOMC day':t['pre_mean'],'every other day':t['rest_mean']})*100\n"
             "ax=bars.plot.bar(rot=0,color=['#2ea44f','#8b949e'],title='Average SPY return: pre-FOMC day vs the rest')\n"
             "ax.set_ylabel('%/day'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print(f\"{t['n_pre']} pre-FOMC days = {t['n_pre']/t['n_total']:.1%} of sessions, {t['pre_share']:.1%} of cumulative return\")"),
        md("## 4 · The teardown — it was real, then it died\n\nSplit at the 2011 publication era: before, "
           "the pre-FOMC day was a giant; after, it's just another day."),
        code("sp=st.split_by_date(ret,fomc,cut='2011-01-01')\n"
             "tab=pd.DataFrame({e:{'pre-FOMC %/day':v['pre_mean']*100,'other %/day':v['rest_mean']*100,'share of return %':v['pre_share']*100} for e,v in sp.items()}).T\n"
             "display(tab.round(2))\n"
             "for e,v in sp.items(): print(f\"{e}: diff t~{v['tstat']:.2f}\")"),
        md("**Read it plainly.** 1993–2010: the pre-FOMC day averaged +0.24% and ~3% of sessions earned "
           "**19.8%** of the market's whole return. 2011–2026: +0.09%, a difference t of 0.4, just 5% of "
           "return. The anomaly was front-run into oblivion once everyone knew the schedule."),
        md("## 5 · The verdict\n\n**Signal: Real** — a documented, economically enormous historical "
           "drift. **Tradability: Fragile** — it decayed on publication. **Still an edge after "
           "publication?: Not supported.** Textbook post-publication decay."),
        md("## 6 · Could you actually trade it?\n\nNot anymore. It was real and huge — but it was also "
           "famous, and a schedule everyone can see is the easiest thing in the world to arbitrage. The "
           "money was made by those holding the position *before* the 2011 paper; after, the edge is gone."),
        md("## 7 · Going further 🚪\n\nA post-publication-decay cousin of the timing studies [56 "
           "Tide-Table](../../56-tide-table/) (CAPE) and [66 Inverted](../../66-inverted/) (yield curve), "
           "and a calendar sibling of [55 Summer-Lull](../../55-summer-lull/). Forks: the FOMC-cycle "
           "even-week pattern (Cieslak et al.), intraday windows, other scheduled macro releases."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Fed-Drift — a quantitative teardown 🔬\n### The pre-FOMC drift table · the Welch t · the pre/post-publication decay\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). A real, "
           "economically enormous calendar effect — and a clean case of publication killing an anomaly.\n\n"
           "> ⚠️ **Not investment advice.** SPY daily returns vs 264 scheduled FOMC announcements, "
           "1993–2026 (Yahoo + Fed calendar). Daily close-to-close understates the intraday drift. "
           "Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | 3% of days → 11.5% of return (19.8% pre-2011) |\n"
           "| Tradability | **Fragile** | pre-FOMC mean +0.24%→+0.09%, t 1.7→0.4 |\n"
           "| Edge after publication? | **Not supported** | McLean-Pontiff decay |\n\n"
           "> 💡 *In plain words:* a real giant, arbitraged away in plain sight."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** pre-FOMC days have higher mean returns than other "
           "days.\n- **H₂:** the effect is economically large (carries a big share of total return).\n"
           "- **H₃:** it persists post-publication (still tradable today)."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂ confirm a real, scheduled calendar effect. H₃ "
           "decides whether it's a live trade or an economic-history footnote. A decayed anomaly is the "
           "single most common fate of a published one."),
        md("## 3 · How we'd know — the protocol\n\nTag the session before each FOMC announcement → Welch t "
           "of pre-FOMC vs rest → the share of cumulative return on pre-FOMC days → split at 2011 to test "
           "decay. Daily close-to-close is a conservative (noisy) proxy for the intraday window."),
        md("## 4 · The teardown"),
        md("### 4.1 The full-sample drift"),
        code("t=st.drift_table(ret,fomc,lead=1)\n"
             "print({k:(round(v,5) if isinstance(v,float) else v) for k,v in t.items()})"),
        md("> 💡 *In plain words:* pre-FOMC +0.174%/day vs +0.043%, diff t≈1.6 (noisy daily data), but "
           "**3.1% of sessions carry 11.5% of cumulative return**. **H₁ and H₂ hold.**"),
        md("### 4.2 The pre/post-publication split — H₃ fails"),
        code("sp=st.split_by_date(ret,fomc,cut='2011-01-01')\n"
             "display(pd.DataFrame({e:v for e,v in sp.items()}).T[['pre_mean','rest_mean','tstat','pre_share','n_pre']].round(4))"),
        md("Before 2011 the pre-FOMC day averaged +0.243%/day (t≈1.7) and its ~3% of sessions earned "
           "**19.8%** of the market's total return. After 2011: +0.094%/day, t≈0.4, just **5.2%** of "
           "return. **H₃ rejected** — publication front-ran the drift into insignificance, the textbook "
           "McLean-Pontiff (2016) decay."),
        md("## 5 · The verdict\n\nH₁/H₂ hold, H₃ rejected → Signal `REAL`, Tradability `FRAGILE`, "
           "edge-after-publication `NOT SUPPORTED`. The fingerprinted run is in "
           "[`docs/results.md`](../docs/results.md)."),
        md("## 6 · Could you trade it?\n\nOnly with a time machine to before 2011. The drift was real and "
           "large, but a publicly-scheduled, widely-published calendar is trivially front-run — which is "
           "exactly what the post-2011 collapse shows. Today it's risk-management trivia, not a trade."),
        md("## 7 · Going further\n\nForks: (a) the intraday 2pm-to-2pm window (the true effect); (b) the "
           "FOMC even-week cycle (Cieslak-Morse-Vissing-Jørgensen); (c) other scheduled releases (CPI, "
           "NFP); (d) the international spillover Lucca-Moench document. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
