"""Notebook builder for Study 1019 — The Market Runs on Volume Time.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python build_notebooks.py
    python -m jupyter nbconvert --to notebook --execute --inplace \
        01_for_the_curious.ipynb 02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes: 01 is the
plain-language layer, 02 carries the inference, the confounds and the costs. The verdict —
stamps and prose — is **read from `docs/results.md`** (written by `examples/verify.py`) into the
single ``REAL`` dict below, so the hero badges are the ones the real run earned and are never
chosen by hand. Every other number in the notebooks is recomputed live from the frozen tapes.
"""

from __future__ import annotations

import os
import re

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "..", "docs", "results.md")

COLOURS = {"Real": "2ea44f", "Investable": "2ea44f", "Weak": "dab617", "Mixed": "dab617",
           "Fragile": "dab617", "None": "c0392b", "Mirage": "c0392b"}


def _read_verdict(path: str = RESULTS) -> dict:
    """The real run's verdict, parsed from docs/results.md (the single source of truth)."""
    with open(path, encoding="utf-8") as fh:
        txt = fh.read()
    sig = re.search(r"\*\*Signal: (\w+)\.\*\* (.+)", txt)
    trd = re.search(r"\*\*Tradability: (\w+)\.\*\* (.+)", txt)
    one = re.search(r"> \*\*In one sentence:\*\* (.+)", txt)
    asof = re.search(r"As-of\s+\*\*([0-9-]+)\*\*", txt)
    return {"signal": sig.group(1), "signal_why": sig.group(2).strip(),
            "trad": trd.group(1), "trad_why": trd.group(2).strip(),
            "one_sentence": one.group(1).strip(), "as_of": asof.group(1)}


REAL = _read_verdict()


def badges() -> str:
    s, t = REAL["signal"], REAL["trad"]
    return (f"![Signal: {s}](https://img.shields.io/badge/Signal-{s}-{COLOURS[s]}"
            f"?style=flat-square)\n"
            f"![Tradability: {t}](https://img.shields.io/badge/Tradability-{t}-{COLOURS[t]}"
            f"?style=flat-square)")


BOOT = r"""
import sys, os, warnings
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.2)
plt.rcParams["figure.dpi"] = 80
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
pd.set_option("display.width", 160)
from volclock import data, strategy as st
tapes = data.load_all()
print(f"as-of {data.AS_OF} | source: {data.SOURCE}")
for n, t in tapes.items():
    print(f"  {data.TAPE_LABELS[n]:32s} {t.index[0].date()} -> {t.index[-1].date()}  "
          f"{len(t):,} sessions  fingerprint {data.fingerprint(t)}")
"""

C_SP, C_NQ = "#1f6feb", "#8250df"
GREEN, RED, AMBER, GREY = "#2ea44f", "#c0392b", "#dab617", "#8b949e"


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(f"""
# The Market Runs on Volume Time ⏱️
### Are fat tails just normal returns measured on the wrong clock?

{badges()}

A busy day is not one day — it is many quiet days' worth of trading squeezed into one session.
Fifty years ago Peter Clark proposed that if you measured time by *trading volume* rather than
by the calendar, the wild, fat-tailed behaviour of daily prices would melt into a plain bell
curve. We tested it on twenty years of the S&P 500 and the Nasdaq.

> \U0001F4D3 **This is the plain-language layer.** The bootstrap intervals, the forecast race
> and the cost sweep are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it,
> from frozen data tapes shipped inside the `arch` Python package.
"""),
        code(BOOT),
        md(f"""
## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do volume and volatility move together? | Yes — strongly, and on the same day. |
| Does the volume clock turn daily returns into a bell curve? | No. It trims the tails a little. |
| What does explain most of the fat tails? | Volatility *clustering* — calm and stormy spells. |
| Can you use yesterday's volume to forecast tomorrow? | Not beyond what the price range already tells you. |

**Signal: {REAL['signal']} · Tradability: {REAL['trad']}.** {REAL['one_sentence']}
"""),
        md("""
## 1 · The claim

Daily stock-market returns have **fat tails**: crashes and melt-ups happen far more often than a
bell curve would allow. The usual reaction is to reach for a fatter-tailed distribution. Clark
(1973) proposed something more elegant: the bell curve is fine, **the clock is wrong**. Prices
move one small random step per trade, so a day with three times the usual trading packs three
days of steps into one session. Mix quiet days and frantic days together and you get fat tails
— even though, trade by trade, everything is perfectly normal.

Ané & Geman (2000) pushed the idea further and reported near-normal returns once time was
counted in trades. The believer's version: **"divide each day's move by the square root of how
much trading happened, and the fat tails disappear."**
"""),
        md("""
## 2 · So what?

If it were true, risk management would get much simpler: measure the volume clock and the
bell-curve arithmetic works again. And a trader who could see the clock ticking fast would know
that big moves are coming — if, and it is a big *if*, the clock can be read before the moves
happen.
"""),
        md("""
## 3 · How we'd know

Written down before the real data were touched:

1. **Measure.** Divide each day's return by the square root of that day's volume (relative to the
   volume of the previous three months, so the 2000s volume boom does not swamp everything). If
   Clark is right, most of the excess "tail-heaviness" (the *kurtosis*) should vanish. Bar: at
   least a quarter of it, with a confidence interval above zero, on **both** indices.
2. **Compare.** Two yardsticks: dividing by the day's own high-low range (the best case — it *is*
   the day's volatility) and by a standard forecasting model that only uses the past (GARCH).
3. **The catch.** Today's volume is only known after today's close. So: does **yesterday's**
   volume help forecast **tomorrow's** turbulence, and does a strategy built on that forecast earn
   more after costs? If not, it is a mirage.
"""),
        md("""
## 4 · The teardown

### 4.1 The raw volume number is useless as it stands
"""),
        code(r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.6))
for (n, t), c in zip(tapes.items(), ("#1f6feb", "#8250df")):
    axes[0].plot(t.index, t["volume"] / 1e9, lw=0.6, color=c, label=data.TAPE_LABELS[n])
    rv = st.relative_volume(t["volume"])
    axes[1].plot(rv.index, rv.rolling(21).median(), lw=1.0, color=c, label=data.TAPE_LABELS[n])
axes[0].set_title("reported index volume (billions of shares)")
axes[1].set_title("volume relative to its own past 3 months (21-day median)")
axes[1].axhline(1, color="k", lw=1)
for a in axes:
    a.legend(fontsize=8)
plt.tight_layout(); plt.show()
"""),
        md("""
On the left, S&P volume quadruples between 1999 and 2009 for reasons that have little to do with
how much news arrived. On the right, the same series measured against its own recent past —
the version of the clock used throughout.
"""),
        md("""
### 4.2 Do volume and turbulence move together?
"""),
        code(r"""
t = tapes["sp500"]
r = st.log_returns(t["close"])
lv = np.log(st.relative_volume(t["volume"]))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.6), sharey=True)
for ax, k, title in ((axes[0], 0, "same day"), (axes[1], 1, "the NEXT day")):
    d = pd.concat([lv.rename("v"), (r.abs() * 100).shift(-k).rename("a")], axis=1).dropna()
    ax.scatter(d["v"], d["a"], s=3, alpha=0.25, color="#1f6feb")
    bins = pd.qcut(d["v"], 20)
    g = d.groupby(bins, observed=True).mean()
    ax.plot(g["v"], g["a"], "o-", color="#c0392b", lw=2, label="average by volume bucket")
    ax.set_title(f"S&P 500: today's volume vs {title}'s move (corr {d['v'].corr(d['a']):+.2f})")
    ax.set_xlabel("log volume relative to past 3 months"); ax.legend(fontsize=8)
axes[0].set_ylabel("absolute daily return, %")
axes[1].set_ylim(0, 6)
plt.tight_layout(); plt.show()
"""),
        md("""
On the same day, high-volume sessions are clearly the turbulent ones. One day later the red line
is much flatter. That gap — strong today, weak tomorrow — is the whole study in one picture.
"""),
        md("""
### 4.3 Does the volume clock make the bell curve appear?
"""),
        code(r"""
P = st.clock_panel(tapes["sp500"])
fig, ax = plt.subplots(figsize=(10, 5))
grid = np.linspace(-7, 7, 141)
for c, col, lab in (("raw", "#8b949e", "raw daily returns"),
                    ("volume", "#c0392b", "measured on the volume clock"),
                    ("garch", "#1f6feb", "measured against a past-only GARCH")):
    h, e = np.histogram(P[c], bins=grid, density=True)
    ax.semilogy(0.5 * (e[1:] + e[:-1]), np.where(h > 0, h, np.nan), lw=2, color=col, label=lab)
ax.semilogy(grid, np.exp(-grid ** 2 / 2) / np.sqrt(2 * np.pi), "k--", lw=1.5, label="bell curve")
ax.set_ylim(1e-4, 1); ax.set_xlabel("standardised daily move"); ax.legend(fontsize=9)
ax.set_title("S&P 500, log scale: the tails are where a bell curve and the market disagree")
plt.show()
"""),
        md("""
On a log scale, a bell curve is the dashed parabola. Raw returns (grey) spread far beyond it. The
volume clock (red) barely pulls them in; a model that simply remembers whether the market has been
calm or stormy lately (blue) does much more.

> \U0001F52C **For the quants.** The blue line uses only *past* data — it is a forecast. The red
> line uses *same-day* volume, information the blue line does not have, and still does worse.
"""),
        code(r"""
rows = []
for n, t in tapes.items():
    K = st.kurtosis_removed(st.clock_panel(t), n_boot=300)
    for c in ("volume", "garch", "garch_volume", "range"):
        rows.append({"tape": data.TAPE_LABELS[n].split(" (")[0], "clock": st.CLOCK_LABELS[c],
                     "share": K.loc[c, "share_removed"], "lo": K.loc[c, "share_ci_lo"],
                     "hi": K.loc[c, "share_ci_hi"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(11, 5))
clocks = d["clock"].unique()
x = np.arange(len(clocks))
for i, (tp, col) in enumerate(zip(d["tape"].unique(), ("#1f6feb", "#8250df"))):
    s = d[d["tape"] == tp].set_index("clock").loc[clocks]
    ax.bar(x + (i - 0.5) * 0.38, s["share"] * 100, 0.38, color=col, label=tp,
           yerr=[(s["share"] - s["lo"]) * 100, (s["hi"] - s["share"]) * 100], capsize=3)
ax.axhline(25, color="k", ls="--", lw=1.2, label="pre-registered bar for the volume clock (25%)")
ax.axhline(100, color="#2ea44f", ls=":", lw=1.5, label="tails fully normal")
ax.set_xticks(x); ax.set_xticklabels(clocks, fontsize=9)
ax.set_ylabel("% of the excess kurtosis removed"); ax.legend(fontsize=8)
plt.show()
d.round(3)
"""),
        md("""
The volume clock removes a sliver of the tail-heaviness — under the bar we set in advance. The day's
own range removes all of it, but that is cheating on purpose: it *is* the day's turbulence,
measured. The honest comparison is the past-only model, which removes three-quarters, and adding
same-day volume *on top of it* helps a little more.
"""),
        md(f"""
## 5 · The verdict

**Signal: {REAL['signal']}.** {REAL['signal_why']}

**Tradability: {REAL['trad']}.** {REAL['trad_why']}
"""),
        md("""
## 6 · Could you trade it?

The tradable version: a "volatility-targeting" strategy that holds more of the index when the
forecast says calm and less when it says storm. We build it twice — with and without yesterday's
volume in the forecast — and trade one day late, as anyone using end-of-day volume would have to.
"""),
        code(r"""
rf = data.load_daily_rf(tapes["sp500"].index)
fc = st.forecast_race(tapes["sp500"])
r_s = tapes["sp500"]["close"].pct_change()
fig, ax = plt.subplots(figsize=(11, 5))
for m, col, lab in (("har", "#1f6feb", "forecast from the price range"),
                    ("harx", "#c0392b", "... plus yesterday's volume")):
    ov = st.overlay(r_s, fc[f"{m}_r2"], rf, cost_bps=2.0)
    ax.plot((1 + ov["net"]).cumprod(), lw=2 if m == "har" else 1.2, color=col,
            ls="-" if m == "har" else "--", label=f"{lab} (Sharpe {st.sharpe(ov['net']):.2f})")
ax.plot((1 + ov["bh"]).cumprod(), color="#8b949e", lw=1, label="just hold the index")
ax.set_yscale("log"); ax.set_ylabel("growth of 1 above cash (price-only, after 2 bp costs)")
ax.set_title("S&P 500: the two forecast-driven strategies are almost the same line")
ax.legend(fontsize=9); plt.show()
"""),
        md("""
The two lines sit on top of each other. Volatility targeting itself does something — it smooths the
ride compared with holding the index — but yesterday's volume adds nothing to it, because by the
next morning the price range has already told the forecast what the volume knew.
"""),
        md("""
## 7 · Going further \U0001F6AA

- **A better clock.** Index volume is a sum of share counts across hundreds of stocks; Ané & Geman
  counted *trades* on single stocks, intraday. A trade-count or dollar-volume clock on futures or
  single names is the natural fork.
- **Unexpected volume.** The part of today's volume that a model did not expect is where the
  information lives; §3 of the quants notebook shows it helps on top of GARCH on the same day.
- **Intraday.** The theory is about ticks, not days. A study on intraday bars could test the
  clock where it was meant to run.
- **Fork it.** Everything here runs offline from tapes frozen inside the `arch` package — swap in
  your own clock in `volclock/strategy.py` and rerun `examples/verify.py`.
"""),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(f"""
# The Market Runs on Volume Time — a quantitative teardown \U0001F52C
### Kurtosis removed per clock · contemporaneous vs lagged · HAR-X vs HAR · a lagged overlay

{badges()}

The companion to the [notebook for the curious](01_for_the_curious.ipynb). §1 measures how much
excess kurtosis Clark's volume clock removes against a range (upper) and GARCH (usual) benchmark
with paired block-bootstrap intervals; §2 separates the contemporaneous volume–volatility relation
from the lagged one; §3 races a range-based log-HAR against the same model with lagged volume, out
of sample, with HAC Diebold–Mariano tests; §4 builds the overlay with one execution lag and a cost
sweep; §5 is the synthetic positive/negative control.

> ⚠️ **Not investment advice.** S&P 500 and Nasdaq Composite **price indices**
> (dividends excluded), composite index volume, frozen inside `arch` and SHA-256 pinned via
> `quantlab.bundled`; as-of **{REAL['as_of']}**. The reproducible run is
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `In plain words` notes** translate each result back into intuition.
"""),
        code(BOOT),
        md(f"""
## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | {REAL['signal']} | {REAL['signal_why']} |
| **Tradability** | {REAL['trad']} | {REAL['trad_why']} |

> \U0001F4A1 **In plain words.** {REAL['one_sentence']}
"""),
        md("""
## 0 · Hypotheses (fixed before the run — `strategy.verdict`)

- **H₁ (clock).** `r_t / sqrt(V_t / median(V_{t-63..t-1}))` removes ≥ 25% of the raw excess
  kurtosis with a block-bootstrap 95% CI above zero, on **both** tapes.
- **H₂ (link).** Contemporaneous corr(log relative volume, |r|) has a Newey–West t ≥ 2.
- **H₁ ∧ H₂ on both tapes → Real**; holds on one while the other removes nothing → Mixed; positive
  removal everywhere but the bar missed somewhere → Weak.
- **H₃ (forecast).** Lagged log relative volume added to a log-HAR on Parkinson variance lowers
  next-day QLIKE on r² with DM t ≤ −2.
- **H₄ (overlay).** The HAR-X vol-target overlay beats the HAR overlay net of 2 bp with block-
  bootstrap p < 0.05. H₃ ∧ H₄ on both tapes → Investable; H₃ and a positive net gain on one tape →
  Fragile; else Mirage.
"""),
        md("""
## 1 · Kurtosis removed per clock

All five series on the same sessions (two years of burn for the past-only GARCH), each rescaled
to unit variance. Paired circular block bootstrap, 21-day blocks.
"""),
        code(r"""
panels, K = {}, {}
for n, t in tapes.items():
    panels[n] = st.clock_panel(t)
    K[n] = st.kurtosis_removed(panels[n], n_boot=500)
    print(f"\n{data.TAPE_LABELS[n]} — {len(panels[n]):,} sessions from {panels[n].index[0].date()}")
    print(K[n][["excess_kurtosis", "kurt_ci_lo", "kurt_ci_hi", "share_removed",
                "share_ci_lo", "share_ci_hi", "jb", "jb_p"]].round(3).to_string())
"""),
        md("""
> \U0001F4A1 **In plain words.** The volume clock removes a seventh to a fifth of the fat-tailedness;
> its interval touches zero on the S&P. Jarque–Bera rejects normality under every clock — even the
> range clock, which over-corrects into *thin* tails on the S&P because a close-to-close move
> cannot exceed the day's range when there is no overnight gap.
"""),
        code(r"""
for n in tapes:
    print(f"\n{data.TAPE_LABELS[n]} — tails of each clock (unit variance) against N(0,1)")
    print(st.tail_table(panels[n]).round(2).to_string())
"""),
        md("""
### 1.1 Robustness: exponent, detrending window, sub-periods
"""),
        code(r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.6))
for (n, t), c in zip(tapes.items(), ("#1f6feb", "#8250df")):
    E = st.exponent_curve(t)
    axes[0].plot(E.index, E.values, "o-", ms=3, color=c, label=data.TAPE_LABELS[n])
    W = st.window_sensitivity(t, windows=(21, 42, 63, 126, 189, 252))
    axes[1].plot(W.index, W["share_removed"] * 100, "o-", color=c, label=data.TAPE_LABELS[n])
axes[0].axvline(1.0, color="k", ls="--", lw=1, label="Clark: b = 1")
axes[0].set_xlabel("exponent b in r / relvol^(b/2)"); axes[0].set_ylabel("excess kurtosis")
axes[0].set_title("in-sample: the best b is near 1, but the floor is high")
axes[1].axhline(25, color="k", ls="--", lw=1, label="pre-registered bar")
axes[1].set_xlabel("past-only median window (sessions)")
axes[1].set_ylabel("% of excess kurtosis removed"); axes[1].set_title("detrending window")
for a in axes:
    a.legend(fontsize=8)
plt.tight_layout(); plt.show()
for n in tapes:
    print(data.TAPE_LABELS[n]); print(st.by_period(panels[n]).round(2).to_string()); print()
"""),
        md("""
> \U0001F4A1 **In plain words.** Clark's square-root exponent is roughly the right shape — the
> kurtosis curve bottoms out near b ≈ 1.2 — but the bottom is high. A slower detrend (a year
> rather than a quarter) helps the S&P clock, which says part of what the 63-day median calls
> "unusual volume" is really a slow level shift in how the index volume is counted. Even the most
> favourable window — chosen *after* looking — stays near a third.
"""),
        md("""
### 1.2 Does volume add anything *on top of* GARCH?

Lamoureux & Lastrapes (1990) found that putting same-day volume into the GARCH variance equation
absorbs much of the GARCH persistence. Here: excess kurtosis of the GARCH residual minus that of the
GARCH residual divided by sqrt(volume surprise), paired bootstrap.
"""),
        code(r"""
pd.DataFrame({data.TAPE_LABELS[n]: st.incremental_removal(panels[n], n_boot=500)
              for n in tapes}).T
"""),
        md("""
## 2 · The volume–volatility correlation: same day vs later

Standardised series, so the HAC slope is the correlation. The cross-correlogram shows how fast
the link decays.
"""),
        code(r"""
fig, ax = plt.subplots(figsize=(10, 4.8))
for (n, t), c in zip(tapes.items(), ("#1f6feb", "#8250df")):
    C = st.volume_vol_correlation(t, lags=tuple(range(0, 11)))
    for tgt, ls in (("|r|", "-"), ("log range var", "--")):
        s = C[C["target"] == tgt]
        ax.plot(s["lag"], s["corr"], ls, marker="o", ms=4, color=c,
                label=f"{data.TAPE_LABELS[n].split(' (')[0]} — {tgt}")
ax.axhline(0, color="k", lw=0.8)
ax.set_xlabel("lag k: volume at t vs volatility at t + k (sessions)")
ax.set_ylabel("correlation"); ax.legend(fontsize=8); plt.show()
for n, t in tapes.items():
    print(data.TAPE_LABELS[n])
    print(st.volume_vol_correlation(t).round(3).to_string(index=False)); print()
"""),
        md("""
> \U0001F4A1 **In plain words.** The same-day link has a t-statistic above 8 on both tapes. It halves
> or worse by the next day, and what remains is the slow tail that every volatility measure shares
> — the part a range-based HAR already sees.
"""),
        md("""
## 3 · Does *lagged* volume improve tomorrow's forecast?

Out of sample from 2002. HAR = log-HAR on Parkinson variance (day / week / month); HAR-X adds
log relative volume at the forecast day's close. Monthly refits on an expanding window, the same
past-only calibration to the variance level. GARCH(1,1) refitted yearly. QLIKE in Patton's
`a/f + log f` form; HAC Diebold–Mariano; negative t favours HAR-X.
"""),
        code(r"""
races, fcs = {}, {}
for n, t in tapes.items():
    fcs[n] = st.forecast_race(t)
    races[n] = st.score_race(fcs[n])
    print(data.TAPE_LABELS[n])
    print(races[n][["target", "loss", "vs", "n", "mean_diff", "dm_t", "p"]]
          .round(4).to_string(index=False)); print()
"""),
        code(r"""
fig, ax = plt.subplots(figsize=(11, 4.8))
for (n, fc), c in zip(fcs.items(), ("#1f6feb", "#8250df")):
    d = fc[["har_r2", "harx_r2", "garch_r2", "target_r2"]].dropna()
    a = d["target_r2"].to_numpy()
    for other, ls in (("har", "-"), ("garch", ":")):
        diff = st.qlike(a, d["harx_r2"]) - st.qlike(a, d[f"{other}_r2"])
        ax.plot(d.index, np.cumsum(diff), ls, color=c, lw=1.6,
                label=f"{data.TAPE_LABELS[n].split(' (')[0]}: HAR-X minus {other.upper()}")
ax.axhline(0, color="k", lw=0.8)
ax.set_ylabel("cumulative QLIKE difference (below 0 = HAR-X better)")
ax.set_title("against GARCH the range-based HAR wins steadily; against HAR, volume adds nothing")
ax.legend(fontsize=8); plt.show()
pd.DataFrame({data.TAPE_LABELS[n]: st.har_in_sample(t) for n, t in tapes.items()}).T
"""),
        md("""
> \U0001F4A1 **In plain words.** The dotted lines fall steadily: a model built on the daily price
> range beats GARCH, as study 965 found for range estimators generally. The solid lines wander
> around zero: once the range is in the model, yesterday's volume tells it nothing new. Even
> in-sample, with every advantage, the volume coefficient's Newey–West t stays under 2.
"""),
        md("""
## 4 · The overlay — one execution lag, costs, Sharpe race

Weight `min(1.5, 15% / forecast vol)`; forecast at close t, **traded at close t+1** (the day's
composite volume is published after the close), earning t+2. Cash at Fama–French RF (December 2018
carries November); costs one-way × |Δweight|; price-only excess returns.
"""),
        code(r"""
ovs = {}
for n, t in tapes.items():
    rf = data.load_daily_rf(t.index)
    ovs[n] = st.overlay_race(t, fcs[n], rf, n_boot=500)
    print(f"{data.TAPE_LABELS[n]}  {ovs[n]['start']} -> {ovs[n]['end']}  ({ovs[n]['n']:,} sessions)")
    print(ovs[n]["table"].round(3).to_string(index=False))
    print(ovs[n]["tests"].round(3).to_string(index=False)); print()
"""),
        code(r"""
fig, ax = plt.subplots(figsize=(10, 4.8))
for (n, o), c in zip(ovs.items(), ("#1f6feb", "#8250df")):
    tb = o["table"]
    for m, ls in (("har", "-"), ("harx", "--"), ("garch", ":")):
        s = tb[tb["model"] == m]
        ax.plot(s["cost_bps"], s["sharpe"], ls, marker="o", color=c,
                label=f"{data.TAPE_LABELS[n].split(' (')[0]} {m.upper()}")
ax.set_xlabel("one-way cost, bp of traded NAV"); ax.set_ylabel("Sharpe of excess return")
ax.set_title("HAR and HAR-X overlays coincide at every cost"); ax.legend(fontsize=8, ncol=2)
plt.show()
for n, t in tapes.items():
    la = st.lookahead_clock_sharpe(t, fcs[n], data.load_daily_rf(t.index))
    print(f"{data.TAPE_LABELS[n]:32s} zero-lag HAR {la['sharpe_zero_lag']:.2f} -> "
          f"x SAME-DAY volume (look-ahead, impossible) {la['sharpe_gross']:.2f}")
"""),
        md("""
> \U0001F4A1 **In plain words.** Sizing by *today's* volume — information that does not exist until
> after the close — would add about a tenth of a Sharpe point. Lag it by the one day reality
> imposes and the gain is ±0.001, with a bootstrap interval that straddles zero at every cost. The
> clock is real; its value is on the wrong side of the close.
"""),
        md("""
## 5 · Synthetic control — machinery, not evidence

`data.synthetic_tape`: returns N(0, σ²·m_t) realised on an intraday Brownian path (so high and low
exist), with `signal_strength` the share of `log m_t` carried by the volume clock. Raw tails are the
same at every setting; only the link to volume moves.
"""),
        code(r"""
rows = []
for s in (0.0, 0.25, 0.5, 0.75, 1.0):
    tp, truth = data.synthetic_tape(n_days=4000, signal_strength=s, seed=1019)
    Ps = st.clock_panel(tp)
    kr = st.moments(Ps["raw"])["excess_kurtosis"]
    kv = st.moments(Ps["volume"])["excess_kurtosis"]
    S = st.score_race(st.forecast_race(tp))
    dm = S[(S["target"] == "pk") & (S["loss"] == "qlike") & (S["vs"] == "har")]["dm_t"].iloc[0]
    rows.append({"signal_strength": s, "k_raw": kr, "k_volume": kv,
                 "share_removed": 1 - kv / kr, "dm_t_harx_vs_har": dm})
syn = pd.DataFrame(rows).set_index("signal_strength")
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.plot(syn.index, syn["share_removed"] * 100, "o-", color="#c0392b", lw=2)
ax.axhline(0, color="k", lw=0.8); ax.axhline(25, color="k", ls="--", lw=1, label="the real-tape bar")
ax.set_xlabel("signal_strength (share of variance running through the volume clock)")
ax.set_ylabel("% of excess kurtosis removed"); ax.legend(fontsize=8)
ax.set_title("SYNTHETIC: the harness finds a planted clock and punishes an unrelated one")
plt.show()
syn.round(3)
"""),
        md("""
> \U0001F4A1 **In plain words.** Where Clark is true by construction, the same code removes most of
> the excess kurtosis and finds a forecast gain; where the clock is unrelated, dividing by it makes
> the tails *fatter*. The real tapes sit near the low end of this dial — and these synthetic numbers
> say nothing about markets, only that the machinery can see what it is looking for.
"""),
        md("""
## 6 · Could you trade it?

Venue: index futures or a large ETF, where one-way costs of 1–2 bp are realistic and capacity is
not the constraint. Risk: the overlay is long the index ~90–110% of the time; vol-targeting itself
is a known, modest improvement over buy-and-hold on these tapes (both HAR overlays beat holding on
Sharpe), and that improvement belongs to the range-based forecast, not to volume. The volume-aware
version changes turnover and Sharpe by amounts too small to measure. Nothing here is a reason to
pay for a volume feed.
"""),
        md("""
## 7 · Going further

- **Trade-count clock on single names, intraday** — the Ané–Geman setting, which daily index data
  cannot reach. The desk's `quantlab/hf_data.py` is the place to start.
- **Volume surprise as a same-day risk signal.** §1.2 shows volume surprise thins the GARCH
  residual's tails on the Nasdaq. For *ex-post* risk attribution (why was today's P&L large?) that
  is useful even though it does not forecast.
- **Asymmetry.** Volume rises more on down days; a signed clock combined with the leverage effect
  (study 993) is an obvious fork.
- **Challenge us:** the 25% bar, the 63-day window and the log-HAR form are all choices; each is a
  one-line change in `volclock/strategy.py`, and `examples/verify.py` regenerates everything.
"""),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
