# Study 910 — Managed-Distribution CEF — the teardown

The excess-of-cash Sharpe race vs SPY, the HAC *t*'s, the excess-vs-excess CAPM β/α, the bootstrap Sharpe CI, the 2022 rate-hike era cut, the cost math, and the planted-carry / return-of-capital-trap synthetic control. All excess of cash (BIL).

In [1]:
R = {'fp': 'cae85d4d2cca', 'asof': '2026-06-30', 'b_n': 140, 'b_start': '2014-11', 'b_end': '2026-06', 'b_ann': 11.5, 'spy_ann': 13.8, 'b_vol': 17, 'b_exret': 88.3, 'b_t': 2.63, 'b_sharpe': 0.61, 'spy_sharpe': 0.82, 'b_adv': -0.21, 'b_vsspy': -13.6, 'b_t_vsspy': -0.69, 'b_alpha': -1.6, 'b_talpha': -0.59, 'b_beta': 1.0, 'b_r2': 0.73, 'b_maxdd': -28, 'b_boot_lo': 0.12, 'b_boot_hi': 1.17, 'b_boot_fn': 0.005, 'p_n': 196, 'p_exret': 49.3, 'p_t': 2.48, 'p_sharpe': 0.51, 'p_adv': -0.41, 'p_alpha': -3.3, 'p_talpha': -1.96, 'p_beta': 0.69, 'p_boot_lo': 0.08, 'p_boot_hi': 1.03, 'rqi_maxdd': -87, 'rqi_alpha': -4.7, 'bst_exret': 138.5, 'pdi_exret': 75.4, 'pre_n': 86, 'pre_exret': 123.9, 'pre_t': 2.94, 'pre_sharpe': 0.9, 'pre_adv': -0.1, 'pre_alpha': 1.2, 'post_n': 54, 'post_exret': 31.6, 'post_t': 0.62, 'post_sharpe': 0.2, 'post_adv': -0.36, 'post_alpha': -5.5, 'post_talpha': -1.62, 'pcef_post_alpha': -5.0, 'pcef_post_talpha': -2.78, 'gross_exret': 88.3, 'net_exret': 88.0, 'charge': 0.25, 'cy2022': -24.4, 'syn_null_alpha': -1.46, 'syn_null_t': -0.86, 'syn_plant_alpha': 3.54, 'syn_plant_t': 2.1, 'syn_beta': 1.11, 'syn_null_fire': '2/20'}

## The headline — equal-weight basket (PDI/UTF/BST/RQI), excess of cash

A real return over cash — but a **negative** Sharpe advantage vs SPY and a zero-to-negative alpha once you net out the (levered) beta.

In [2]:
print(f"basket : n={R['b_n']}  {R['b_start']}->{R['b_end']}  ann {R['b_ann']:+.1f}% vs SPY {R['spy_ann']:+.1f}%  vol {R['b_vol']}%")
print(f"excess-of-cash : {R['b_exret']:+.1f} bps/mo  (HAC t = {R['b_t']:+.2f})")
print(f"Sharpe race    : basket {R['b_sharpe']:.2f}  vs SPY {R['spy_sharpe']:.2f}  -> advantage {R['b_adv']:+.2f}")
print(f"basket - SPY   : {R['b_vsspy']:+.1f} bps/mo  (HAC t = {R['b_t_vsspy']:+.2f})")
print(f"CAPM vs SPY    : alpha {R['b_alpha']:+.1f}%/yr (t = {R['b_talpha']:+.2f})  beta {R['b_beta']:.2f}  R2 {R['b_r2']:.2f}")
print(f"max drawdown   : {R['b_maxdd']}%   (RQI alone {R['rqi_maxdd']}% - the mREIT trap in miniature)")

basket : n=140  2014-11->2026-06  ann +11.5% vs SPY +13.8%  vol 17%
excess-of-cash : +88.3 bps/mo  (HAC t = +2.63)
Sharpe race    : basket 0.61  vs SPY 0.82  -> advantage -0.21
basket - SPY   : -13.6 bps/mo  (HAC t = -0.69)
CAPM vs SPY    : alpha -1.6%/yr (t = -0.59)  beta 1.00  R2 0.73
max drawdown   : -28%   (RQI alone -87% - the mREIT trap in miniature)


## Bootstrap Sharpe CI (moving-block) — positive, but the whole interval sits below SPY

In [3]:
print(f"basket excess-of-cash Sharpe {R['b_sharpe']:.2f}  95%% CI [{R['b_boot_lo']:.2f}, {R['b_boot_hi']:.2f}]  frac_neg={R['b_boot_fn']:.3f}")
print(f"PCEF   excess-of-cash Sharpe {R['p_sharpe']:.2f}  95%% CI [{R['p_boot_lo']:.2f}, {R['p_boot_hi']:.2f}]")
print(f"SPY excess-of-cash Sharpe on the same months: {R['spy_sharpe']:.2f}  (above both intervals' centre)")

basket excess-of-cash Sharpe 0.61  95%% CI [0.12, 1.17]  frac_neg=0.005
PCEF   excess-of-cash Sharpe 0.51  95%% CI [0.08, 1.03]
SPY excess-of-cash Sharpe on the same months: 0.82  (above both intervals' centre)


## PCEF — the diversified CEF-of-CEFs, 16 years: same story, sharper

Longer history, and the alpha is *significantly* negative.

In [4]:
print(f"PCEF: n={R['p_n']}  excess-of-cash {R['p_exret']:+.1f} bps/mo (t {R['p_t']:+.2f})  Sharpe adv {R['p_adv']:+.2f}")
print(f"      CAPM alpha {R['p_alpha']:+.1f}%/yr (t {R['p_talpha']:+.2f})  beta {R['p_beta']:.2f}")

PCEF: n=196  excess-of-cash +49.3 bps/mo (t +2.48)  Sharpe adv -0.41
      CAPM alpha -3.3%/yr (t -1.96)  beta 0.69


## Era cut at 2022-01 — the rate-hike regime broke it

Leverage got expensive, discounts blew out. The excess return halved to statistical zero and the alpha turned sharply negative — basket *and* PCEF.

In [5]:
print(f"basket pre  (n={R['pre_n']}) : {R['pre_exret']:+.1f} bps/mo (t {R['pre_t']:+.2f})  Sharpe {R['pre_sharpe']:.2f}  adv {R['pre_adv']:+.2f}  alpha {R['pre_alpha']:+.1f}%/yr")
print(f"basket post (n={R['post_n']}) : {R['post_exret']:+.1f} bps/mo (t {R['post_t']:+.2f})  Sharpe {R['post_sharpe']:.2f}  adv {R['post_adv']:+.2f}  alpha {R['post_alpha']:+.1f}%/yr (t {R['post_talpha']:+.2f})")
print(f"PCEF   post : alpha {R['pcef_post_alpha']:+.1f}%/yr (t {R['pcef_post_talpha']:+.2f})  -- significantly negative")
print(f"calendar 2022 basket return: {R['cy2022']:+.1f}%")

basket pre  (n=86) : +123.9 bps/mo (t +2.94)  Sharpe 0.90  adv -0.10  alpha +1.2%/yr
basket post (n=54) : +31.6 bps/mo (t +0.62)  Sharpe 0.20  adv -0.36  alpha -5.5%/yr (t -1.62)
PCEF   post : alpha -5.0%/yr (t -2.78)  -- significantly negative
calendar 2022 basket return: -24.4%


## Tradability — costs are NOT the killer; a hidden levered beta is

In [6]:
print(f"gross {R['gross_exret']:+.1f} bps/mo -> net {R['net_exret']:+.1f} bps/mo (charge {R['charge']:.2f} bps/mo; buy-and-hold)")
print(f"net Sharpe still {R['b_sharpe']:.2f} < SPY {R['spy_sharpe']:.2f}: you get a better risk-adjusted return just holding SPY.")
print('The edge dies in the factor regression (beta ~1.0, R2 0.73), not at the trading desk -> Mirage.')

gross +88.3 bps/mo -> net +88.0 bps/mo (charge 0.25 bps/mo; buy-and-hold)
net Sharpe still 0.61 < SPY 0.82: you get a better risk-adjusted return just holding SPY.
The edge dies in the factor regression (beta ~1.0, R2 0.73), not at the trading desk -> Mirage.


## Synthetic control — the machinery is unbiased *(never market evidence)*

Live: the null (pure levered beta) must NOT fire; a planted net carry must be recovered as alpha; a 100%-return-of-capital payout must yield no alpha.

In [7]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
import numpy as np
from md_cef import data, strategy as st
for carry, leak, tag in [(0.0,0.0,'null'), (0.05,0.0,'planted +5%'), (0.05,0.05,'ROC trap')]:
    d = st.synthetic_detect(data.synthetic_world(carry_annual=carry, roc_leak_annual=leak, seed=910))
    print(f"{tag:<12s}: alpha {d['alpha_ann_pct']:+.2f}%/yr (t {d['t_alpha']:+.2f})  beta {d['beta']:.2f}")
null_t = np.array([st.synthetic_detect(data.synthetic_world(carry_annual=0.0, seed=910+s))['t_alpha'] for s in range(20)])
print(f"null over 20 seeds: |t|>=2 in {(np.abs(null_t)>=2).sum()}/20  (~5% false-positive rate)")

null        : alpha -1.46%/yr (t -0.86)  beta 1.11
planted +5% : alpha +3.54%/yr (t +2.10)  beta 1.11
ROC trap    : alpha -1.46%/yr (t -0.86)  beta 1.11
null over 20 seeds: |t|>=2 in 2/20  (~5% false-positive rate)


## Verdict

- **Signal — Weak.** The payout is a *real* excess-of-cash return (basket **+88.3 bps/mo**, HAC *t* = **+2.63**, bootstrap Sharpe CI [0.12, 1.17] clear of zero) — not the capital shredder an mREIT is. But the **asset-class edge fails**: the excess-vs-excess Sharpe trails SPY in every fund and sub-era (basket adv **-0.21**, -0.10 pre / -0.36 post; PCEF -0.41), the CAPM alpha is ~0-to-negative (-1.6 %/yr; PCEF -3.3 %/yr, *t* = -1.96), and β ≈ 1.00 exposes a levered-beta income clone. The synthetic control confirms the machinery is unbiased.
- **Tradability — Mirage.** Net ≈ gross (+88.0 bps; buy-and-hold), so costs don't kill it — a **hidden levered equity beta** does: SPY's Sharpe (0.82) beats the basket's (0.61), and the 2022 rate shock turned the excess return to +32 bps (*t* = +0.62) with a -5.5 %/yr alpha and a -24.4 % year.