"""Generate the two narrative notebooks for Study 29 (Hedgers-Toll) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the offline synthetic commodity panel (baked hedging premium + a null). The
synthetic proves the machinery; the real verdict (the premium has faded on the modern CFTC-COT + futures
tape) is quoted from [`docs/results.md`](../docs/results.md). Both notebooks walk the SAME seven beats.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from hedgers_toll import data, hedging, strategy, decompose, extension

# Offline synthetic commodities: a PREMIUM panel (hedging pressure predicts returns) and a NULL. The
# real CFTC-COT + futures verdict is in ../docs/results.md.
r,  hp,  truth = data.synthetic_commodities(hp_strength=0.0045, seed=29)   # the premium panel
r0, hp0, _     = data.synthetic_commodities(hp_strength=0.0,    seed=29)   # the null
print(f"{truth.n_comm} synthetic commodities x {truth.n_weeks} weeks | baked hp_strength={truth.hp_strength} | null=0")
"""

R = dict(
    n_comm="12", lo="2015", hi="2026", fp="ab3ff5e16b24", n_weeks="569",
    ic="-0.020", ic_t="-1.4", tb="-7.7", ls_sr="-0.42", ls_t="-1.4", turn="5.1",
    lo_top="+0.18", basket="+0.70", corr="+0.02", sub1="-0.79", sub2="-0.99", sub3="+0.60",
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Premium today?: Faded](https://img.shields.io/badge/Premium_today%3F-Faded-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Hedgers-Toll 🌾\n"
            "### Producers pay to offload price risk — are you, the speculator, really collecting the toll?\n\n"
            + BADGES +
            "A wheat farmer wants to lock in next year's price, so they *sell* wheat futures today. An oil "
            "driller does the same. Someone has to take the other side of all that hedging — and the old "
            "theory (Keynes' *normal backwardation*; Cootner 1960) says that someone, the speculator, is "
            "**paid a premium** for it: a toll the hedgers hand over for the insurance. You can read who's "
            "hedging straight off the government's **Commitments of Traders** report — so the trade writes "
            "itself: go long the commodities where commercial hedgers are most net short.\n\n"
            "This is the desk's twelfth idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§9.2). We prove the engine on a synthetic market where the toll is baked in (and a null), then "
            "run it on real CFTC positioning and commodity futures — and find the toll booth has been "
            "abandoned.\n\n"
            "> 📓 **Plain-language layer.** The information coefficient, the Newey–West *t* and the window "
            "sweep are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** panel, so the real numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does hedging pressure predict commodity returns? | 🟡 **In theory yes; lately no.** Real on "
            f"our control (IC *t* > 11) and in the literature, but **{R['ic']}** (*t* **{R['ic_t']}**) on "
            "the modern tape. |\n"
            "| Does the trade pay? | 🚫 **No** — the long-short hedging-pressure factor *loses*: Sharpe "
            f"**{R['ls_sr']}** (*t* **{R['ls_t']}**), negative across every signal window. |\n"
            "| Is the premium still there? | ⚪ **Faded** — negative through most of the modern sample. |\n\n"
            "> Desk shorthand: **Signal `WEAK` · Tradability `MIRAGE` · Premium today? `FADED`** — a real "
            "risk premium a present-day trader can't collect."
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Hedging pressure: `HP = (commercial short − commercial long) / total`. When it's high, "
            "producers are heavily net short — paying speculators to be long — and the claim is the long "
            "speculator earns a premium next period. On our synthetic market we baked exactly that: the "
            "hedging pressure predicts the next return."
        ),
        code(
            "pr = hedging.hedging_premium(r, hp)\n"
            "print(f\"hedging-pressure information coefficient {pr['mean_ic']:+.3f} (t {pr['ic_t']:+.1f}) -- it predicts.\")\n"
            "print(f\"null IC {hedging.hedging_premium(r0, hp0)['mean_ic']:+.3f} -- nothing.\")"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "A genuine, positioning-driven risk premium would be gold: it's *structural* (someone always "
            "needs to hedge), uncorrelated with stocks, and readable from free public data. It's the "
            "backbone of commodity risk-premia funds. The desk's question is the usual one — is the toll "
            "still being paid on the markets you can actually trade, or did everyone crowd the booth until "
            "it closed?"
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Three checks:\n\n"
            "1. **Does hedging pressure predict returns?** The cross-sectional IC and the top-minus-bottom "
            "spread.\n"
            "2. **Does the long-short factor pay**, net of cost?\n"
            "3. **Is it robust / still alive** — across signal windows and sub-periods? And the **null:** "
            "no information ⇒ no premium.\n\n"
            "**Mirage line:** the factor is flat-to-negative on the real tape, at every window."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · Premium tape vs the null\n"
            "Run the hedging-pressure factor on both synthetic panels."
        ),
        code(
            "for label, (rr, hh) in [('premium', (r, hp)), ('null', (r0, hp0))]:\n"
            "    cmp = strategy.compare(rr, hh, cost_bps=10.0); pt = decompose.premium_tstat(rr, hh, cost_bps=10.0)\n"
            "    print(f\"{label:8s}: long-short Sharpe {cmp['long_short']['sharpe']:+.2f}, ann {cmp['long_short']['ann_return']:+.1%} \"\n"
            "          f\"(HAC t {pt['t_stat']:+.1f}), turnover {cmp['turnover_ann']:.1f}x/yr\")"
        ),

        md(
            "### 4b · On the real market — the booth is empty\n"
            "On real CFTC positioning + commodity futures (quoted from "
            "[`../docs/results.md`](../docs/results.md)):\n\n"
            f"- Hedging pressure predicts the next week with an IC of **{R['ic']}** (*t* **{R['ic_t']}**) — "
            f"a *negative* top-minus-bottom spread (**{R['tb']}%/yr**).\n"
            f"- The long-short factor **loses**: Sharpe **{R['ls_sr']}** (*t* **{R['ls_t']}**), turnover "
            f"**{R['turn']}×/yr**.\n"
            f"- And it's negative across *every* signal window, with sub-period Sharpes "
            f"**{R['sub1']} / {R['sub2']} / {R['sub3']}** — gone for most of the modern sample."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **Real mechanism** — control IC *t* > 11; decades of academic evidence.\n"
            f"- **Absent here** — real IC {R['ic']} (*t* {R['ic_t']}), factor Sharpe {R['ls_sr']}.\n"
            "- **Not a window artefact** — negative across the board.\n\n"
            "> **Signal `WEAK` · Tradability `MIRAGE` · Premium today? `FADED`.** A toll that producers "
            "still pay *somewhere*, but not on the liquid futures you'd trade today."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "- **The signal doesn't predict** on the modern tape — the long-short factor loses before you "
            "even sweat the costs.\n"
            "- **Crowding is the likely culprit** — commodity risk-premia products and CTAs all read the "
            "same COT report; a structural premium that everyone harvests stops being one.\n"
            "- **It may live in breadth** — the original studies used decades and dozens of contracts; our "
            "12-commodity, 10-year window is thinner.\n\n"
            "> Tradability **`MIRAGE`**; premium today? **`FADED`** — the worked complement "
            "([`../docs/extension.md`](../docs/extension.md)) shows it's gone at every window."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **The robustness sweep** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): the factor is negative across signal "
            "windows and in both legs — not a tuning miss, an absence.\n"
            "- **More breadth, more history.** The disaggregated COT (Producer/Merchant vs Managed Money) "
            "and a 30-contract, 1990s-on sample is where the academic premium lives; does it survive "
            "there where our liquid-12 window doesn't?\n"
            "- **Combine with the futures basis / roll yield (§9.1).** Hedging pressure and term-structure "
            "carry are two reads on the same backwardation — does the *basis* still pay where positioning "
            "doesn't?\n\n"
            "PRs welcome — widen the universe and history, or test the basis-based cousin."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Hedgers-Toll — a quantitative teardown 🔬\n"
            "### Hedging-pressure IC · the long-short factor (HAC) · vs the commodity basket · the window sweep · the null\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its standard error.* The steelman is §9.2: net hedger short-"
            "positioning (CFTC COT) predicts commodity returns. We prove the engine on a synthetic panel "
            "with a baked premium, then show it's absent on the modern CFTC-COT + futures tape.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — does hedging pressure predict? | 🟡 `WEAK` | Strong on the control (IC HAC *t* "
            f"> 11) and in the literature; on the modern tape IC **{R['ic']}** (*t* **{R['ic_t']}**). |\n"
            "| **Tradability** | 🔴 `MIRAGE` | The long-short factor *loses*: Sharpe "
            f"**{R['ls_sr']}** (*t* **{R['ls_t']}**), negative across windows. |\n"
            "| **Premium today?** | ⚪ `Faded` | Sub-period Sharpes "
            f"**{R['sub1']} / {R['sub2']} / {R['sub3']}** — negative through most of 2015–2025. |\n\n"
            "> **In one sentence:** the hedging-pressure / normal-backwardation premium is real in the "
            "long-run record and on our control, but absent at every parameter on the liquid commodity "
            "futures a trader faces today.\n\n"
            "*(This notebook executes on the synthetic control; the real numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "$\\text{HP}_i = (\\text{CommShort}_i - \\text{CommLong}_i)/(\\text{CommShort}_i + "
            "\\text{CommLong}_i)$ from the weekly COT; the tradable signal is its trailing z-score (lagged). "
            "The claim is $\\mathbb{E}[r_{i,t+1}\\mid \\text{HP}_{i,t}\\text{ high}] > 0$ — a long premium "
            "where hedgers are net short. The synthetic bakes $r_{t+1}=\\text{hp\\_strength}\\cdot "
            "\\text{HP}_t + \\text{noise}$; $\\text{hp\\_strength}=0$ is the null."
        ),
        code(
            "pr = hedging.hedging_premium(r, hp)\n"
            "print(f\"top-minus-bottom tercile spread {pr['top_minus_bottom_ann_pct']:+.1f}%/yr (synthetic); \"\n"
            "      f\"null {hedging.hedging_premium(r0, hp0)['top_minus_bottom_ann_pct']:+.1f}%/yr\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Normal backwardation (Keynes-Hicks) and its modern cross-sectional form (Gorton-Hayashi-"
            "Rouwenhorst 2013; Basu-Miffre 2013) make hedging pressure a *structural* commodity risk "
            "premium — compensation for absorbing hedgers' inventory/price risk. The open questions: is "
            "the IC positive and significant, does the long-short factor pay net of cost, and is it stable "
            "across windows and time. Beats 4–6 answer all three; the answer here is no, no, and no."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **IC** (`hedging.hedging_premium`): pooled cross-sectional IC + *t*. Real ⇔ >0, |t|>2.\n"
            "2. **Factor** (`decompose.premium_tstat`): long-short HAC *t*.\n"
            "3. **vs basket** (`decompose.vs_basket`) + **window sweep** (`extension.window_sweep`).\n"
            "4. **Null** collapses.\n\n"
            "**Mirage line:** factor flat-to-negative on the real tape at every window."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · IC and the factor, premium vs null"),
        code(
            "for label, (rr, hh) in [('premium', (r, hp)), ('null', (r0, hp0))]:\n"
            "    pr = hedging.hedging_premium(rr, hh); pt = decompose.premium_tstat(rr, hh, cost_bps=10.0)\n"
            "    print(f\"{label:8s}: IC {pr['mean_ic']:+.3f} (t {pr['ic_t']:+.1f}); long-short {pt['mean_ann_pct']:+.1f}%/yr (HAC t {pt['t_stat']:+.1f})\")"
        ),

        md("### 4b · The window sweep (on the synthetic premium)"),
        code(
            "sw = extension.window_sweep(r, hp, cost_bps=10.0)\n"
            "display(sw.round(3))\n"
            f"print('On the REAL tape (../docs/results.md): the long-short Sharpe is NEGATIVE at every window (IC {R['ic']}, factor {R['ls_sr']}).')"
        ),
        md(
            "> 💡 **In plain words.** On the synthetic, where the premium is real, the factor pays across "
            "every lookback. On the real commodities it loses at every lookback — so it isn't a tuning "
            "problem, the premium simply isn't being paid on this tape."
        ),

        md("## Beat 5 · The verdict\n\n"
           "- **Real on control** (4a): IC HAC *t* > 11.\n"
           f"- **Absent here** (real): IC {R['ic']} (*t* {R['ic_t']}), factor Sharpe {R['ls_sr']}.\n"
           "- **Not a window artefact** (4b): negative across windows.\n\n"
           "> **Signal `WEAK` · Tradability `MIRAGE` · Premium today? `Faded`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           "- **No predictive signal** on the modern tape.\n"
           "- **Likely crowded away** — every commodity risk-premia book reads the same COT.\n"
           "- **May need breadth/history** the liquid-12, 10-year window lacks.\n\n"
           "Tradability **`MIRAGE`**; premium today? **`Faded`**."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — robustness of the absence\n"
            "The window sweep and the long-only-vs-long-short leg split on the real tape."
        ),
        code(
            "sw = extension.window_sweep(r, hp, cost_bps=10.0)\n"
            "ls = extension.leg_split(r, hp, cost_bps=10.0)\n"
            "print('synthetic premium -> factor positive across windows:', dict(sw['ls_sharpe'].round(2)))\n"
            f"print('Real tape (../docs/extension.md): negative across every window; long-only-top {R['lo_top']}, basket {R['basket']}.')"
        ),
        md(
            "**The result.** On the real CFTC-COT + futures tape the hedging-pressure factor is negative at "
            "every signal window and in both legs — it is not a lookback that needs tuning, the premium is "
            "absent. Real in the long-run academic record and on our control; competed away (or specific "
            "to the broader, deeper samples the original studies used) on the liquid commodities a trader "
            "faces today. Full run in [`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **Disaggregated COT + breadth** — Producer/Merchant vs Managed Money over 30 contracts since "
            "the 1990s, where the academic premium lives.\n"
            "- **The basis cousin (§9.1)** — term-structure roll yield is the other read on backwardation; "
            "does it pay where positioning doesn't?\n"
            "- **Time-series, not cross-section** — own-commodity hedging pressure as a timing signal.\n\n"
            "PRs welcome — widen the universe and history, or test the basis-based version."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
