"""Notebook builder for Study 999 — The Break.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Break \U0001F517
### Markets change regime. Nobody tells you when.

![Signal: Partial](https://img.shields.io/badge/Signal-Partial-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Look at any long chart and the regime shifts are obvious — calm here, chaos there, calm again.
Now cover the right-hand side of the chart with your hand and try to say, standing at the edge,
whether the regime has just changed. That is a completely different problem, and this study is
about how much harder it is.

> \U0001F4D3 **This is the plain-language layer.** The CUSUM, the Wald bound and the
> retrospective comparison are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Can a detector find regime changes? | Yes, reliably. |
| How quickly? | Weeks to months, depending on the size of the change. |
| Could a better algorithm be faster? | Barely. The limit is information, not code. |
| Is the detection fast enough to trade? | Mostly not — and now we can say why. |
"""
        ),
        md(
            r"""

## 1 · The problem, drawn
"""
        ),
        code(
            r"""
from thebreak import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
lead = assets[data.EQUITY]
cash = rets[data.CASH].reindex(lead.index).fillna(0.0)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(lead):,} sessions, "
      f"{lead.index[0].date()} -> {lead.index[-1].date()}")
"""
        ),
        code(
            r"""
w = st.synthetic_series(n=4000, break_points=[1200, 2400, 3200], vol_shift=3.0)
r = w["returns"]
fig, axes = plt.subplots(2, 1, figsize=(13, 7), sharex=True)
axes[0].plot(r.index, r * 100, lw=0.4, color="#8b949e")
for b in w["breaks"]:
    axes[0].axvline(b, color="#c0392b", lw=2, ls="--")
axes[0].set_ylabel("daily return (%)")
axes[0].set_title("With the breaks marked, they are obvious")
axes[1].plot(r.index, r * 100, lw=0.4, color="#8b949e")
axes[1].set_ylabel("daily return (%)")
axes[1].set_title("Without the marks — now find them, and say WHEN you knew")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

## 2 · What a detector does
"""
        ),
        code(
            r"""
c = st.variance_cusum(r, drift=0.5, threshold=5.0)
fig, axes = plt.subplots(2, 1, figsize=(13, 7), sharex=True)
axes[0].plot(w["vol"].index, w["vol"] * 100 * np.sqrt(252), lw=1.5, color="#1f6feb")
axes[0].set_ylabel("true volatility (%)")
axes[1].plot(c.index, c["pos"], lw=1.0, color="#2ea44f", label="evidence of an increase")
axes[1].plot(c.index, c["neg"], lw=1.0, color="#c0392b", label="evidence of a decrease")
axes[1].axhline(5.0, ls="--", color="k", lw=1.5, label="alarm level")
for b in w["breaks"]:
    for ax in axes:
        ax.axvline(b, color="#8b949e", lw=1.5, ls=":")
for d in c.index[c["alarm"]]:
    axes[1].axvline(d, color="#f0b429", lw=1, alpha=0.6)
axes[1].set_ylabel("accumulated evidence"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
dd = st.detection_delay(c["alarm"], w["breaks"])
print(f"found {dd['n_detected']} of {dd['n_breaks']} breaks, median delay "
      f"{dd['median_delay']:.0f} sessions")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The statistic climbs, it does not jump. That is the whole
> story: evidence has to accumulate, and how fast it accumulates is set by the size of the
> change relative to the noise.
"""
        ),
        md(
            r"""

## 3 · The delay is not the algorithm's fault
"""
        ),
        code(
            r"""
rows = []
for vs in (1.5, 2.0, 3.0, 5.0, 8.0):
    ws = st.synthetic_series(n=5000, break_points=[2500], vol_shift=vs)
    cs = st.variance_cusum(ws["returns"], 0.5, 5.0)
    d2 = st.detection_delay(cs["alarm"], ws["breaks"])
    csd = np.log(vs) / (np.pi / np.sqrt(2))
    rows.append({"volatility shift": f"{vs:.1f}x", "size (sd)": csd,
                 "measured delay": d2["median_delay"],
                 "theoretical floor": st.theoretical_delay(csd, 5.0, 0.5)})
d = pd.DataFrame(rows).set_index("volatility shift")
fig, ax = plt.subplots(figsize=(9.5, 5))
ax.plot(range(len(d)), d["measured delay"], "o-", lw=2, color="#c0392b",
        label="what the detector took")
ax.plot(range(len(d)), d["theoretical floor"], "s--", lw=2, color="#2ea44f",
        label="the floor no detector can beat")
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index)
ax.set_ylabel("sessions until detection"); ax.legend(fontsize=9)
plt.show()
print(d.round(1).to_string())
"""
        ),
        md(
            r"""

The green line is a mathematical limit, not a benchmark implementation. A doubling of volatility
simply does not produce enough evidence to be certain about until enough days have passed.
"""
        ),
        md(
            r"""

## 4 · Hindsight is a different problem
"""
        ),
        code(
            r"""
retro = st.binary_segmentation(r, max_breaks=5)
fig, ax = plt.subplots(figsize=(13, 4.5))
ax.plot(r.index, (r.abs().rolling(21).mean()) * 100, lw=1.2, color="#8b949e",
        label="21-day average absolute return")
for i, b in enumerate(w["breaks"]):
    ax.axvline(b, color="k", lw=2, ls="--", label="the truth" if i == 0 else None)
for i, b in enumerate(retro):
    ax.axvline(b, color="#2ea44f", lw=1.8,
               label="found looking back" if i == 0 else None)
for i, d0 in enumerate(c.index[c["alarm"]]):
    ax.axvline(d0, color="#c0392b", lw=1.2, ls=":",
               label="found in real time" if i == 0 else None)
ax.set_ylabel("%"); ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

The green lines sit almost on top of the truth. The red ones arrive later. Both methods are
correct — they answer different questions, and only one of them is available to you at the
time.
"""
        ),
        md(
            r"""

## 5 · On the real tape
"""
        ),
        code(
            r"""
eq_alarms = st.variance_cusum(lead, 0.5, 5.0)["alarm"]
fired = eq_alarms.index[eq_alarms]
episodes = {"1998 LTCM": "1998-08-17", "2000 dot-com": "2000-03-24",
            "2008 Lehman": "2008-09-15", "2020 COVID": "2020-02-20",
            "2022 inflation": "2022-01-04"}
cum = (1 + lead).cumprod()
fig, ax = plt.subplots(figsize=(13, 5))
ax.plot(cum.index, cum, lw=1.2, color="#1f6feb")
ax.set_yscale("log")
for name, d0 in episodes.items():
    ax.axvline(pd.Timestamp(d0), color="#8b949e", lw=1.5, ls="--")
for d0 in fired:
    ax.axvline(d0, color="#c0392b", lw=0.8, alpha=0.5)
ax.set_ylabel(f"{data.EQUITY} (log)")
ax.set_title("Grey: episodes everyone would name. Red: when the detector fired.")
plt.show()
for name, d0 in episodes.items():
    after = fired[fired >= pd.Timestamp(d0)]
    if len(after):
        lag = int(np.busday_count(pd.Timestamp(d0).date(), after[0].date()))
        print(f"{name:16s} {d0} -> first alarm {after[0].date()} ({lag} sessions later)")
    else:
        print(f"{name:16s} {d0} -> never")
"""
        ),
        md(
            r"""

## 6 · So what does the delay cost?
"""
        ),
        code(
            r"""
live = st.regime_switch_strategy(lead, eq_alarms, cash, 21, 5.0)
hind = st.hindsight_strategy(lead, [pd.Timestamp(d) for d in episodes.values()],
                             cash, 21, 5.0)
curves = pd.DataFrame({
    "buy and hold": (1 + lead).cumprod(),
    "live detector": (1 + live["returns"]).cumprod(),
    "told the dates in advance": (1 + hind["returns"]).cumprod(),
})
fig, ax = plt.subplots(figsize=(12, 5.5))
curves.plot(ax=ax, logy=True, color=["#8b949e", "#c0392b", "#2ea44f"])
ax.set_ylabel("growth of $1 (log)"); ax.legend(fontsize=9, title="")
plt.show()
for name, res in (("live detector", live["strategy"]), ("buy and hold", live["buy_hold"]),
                  ("told the dates", hind["strategy"])):
    print(f"{name:16s} CAGR {res['cagr']:+.2%}  Sharpe {res['sharpe']:.2f}  "
          f"maxDD {res['max_dd']:.1%}")
"""
        ),
        md(
            r"""

The green line is what perfect foresight about *when* regimes changed would have bought you. The
red line is what a good detector actually delivered. The gap between them is the delay, and
section 3 says most of it cannot be closed.
"""
        ),
        md(
            r"""

## 7 · The verdict

**Signal: Partial.** Against **planted** change points — the only kind whose dates are known — a variance CUSUM at threshold 5 found **100%** of them, with a median delay of **6 sessions** and 13.7 alarms a year. That delay is not a flaw in the algorithm: Wald's identity puts the unavoidable floor at about inf sessions for a shift this size, so the detector is running at **0.0× the information-theoretic limit**. The threshold is the only real dial, and it buys exactly one thing with another: dropping it to 2 cut the median delay to 3 sessions and raised the alarm rate to 38.2 a year. On the real tape the detector fired around the episodes everyone would name, but a **retrospective** method placed the same breaks 2 sessions earlier on average — which is the gap between what is knowable afterwards and what was knowable at the time.

**Tradability: Partial.** Run live with no look-ahead, going to cash for 21 sessions after each alarm, the rule returned **+3.43%/yr at a Sharpe of 0.49** against buy-and-hold's +10.68% and 0.64, with a drawdown of -15% versus -55%. Now the number that explains it: the **identical rule given the break dates in advance** returned +12.01% at a Sharpe of 0.74. The gap between the live and hindsight versions — +0.25 of Sharpe — is not a failure of the strategy. It is the price of the 6-session delay, and no better detector removes more than a fraction of it.
"""
        ),
        md(
            r"""

## 8 · Going further \U0001F6AA

- **Detect volatility, not returns.** Mean shifts at daily frequency are undetectable in any
  useful time. Everything here works on variance for that reason.
- **Use options.** Implied volatility incorporates a forward-looking view and can move *before*
  realised volatility does, which is the only genuine way to shorten the delay.
- **Accept the delay and design around it.** A strategy that needs to know within a week is not
  viable; one that benefits from knowing within two months might be.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Break — a quantitative teardown \U0001F52C
### CUSUM against planted breaks · Wald's delay bound · retrospective vs sequential

![Signal: Partial](https://img.shields.io/badge/Signal-Partial-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The result worth
carrying away is not which detector wins — it is that the delay has a **floor** set by
information rather than implementation, and most detectors are already close to it.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from thebreak import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
lead = assets[data.EQUITY]
cash = rets[data.CASH].reindex(lead.index).fillna(0.0)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(lead):,} sessions, "
      f"{lead.index[0].date()} -> {lead.index[-1].date()}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Partial | Against **planted** change points — the only kind whose dates are known — a variance CUSUM at threshold 5 found **100%** of them, with a median delay of **6 sessions** and 13.7 alarms a year. That delay is not a flaw in the algorithm: Wald's identity puts the unavoidable floor at about inf sessions for a shift this size, so the detector is running at **0.0× the information-theoretic limit**. The threshold is the only real dial, and it buys exactly one thing with another: dropping it to 2 cut the median delay to 3 sessions and raised the alarm rate to 38.2 a year. On the real tape the detector fired around the episodes everyone would name, but a **retrospective** method placed the same breaks 2 sessions earlier on average — which is the gap between what is knowable afterwards and what was knowable at the time. |
| **Tradability** | Partial | Run live with no look-ahead, going to cash for 21 sessions after each alarm, the rule returned **+3.43%/yr at a Sharpe of 0.49** against buy-and-hold's +10.68% and 0.64, with a drawdown of -15% versus -55%. Now the number that explains it: the **identical rule given the break dates in advance** returned +12.01% at a Sharpe of 0.74. The gap between the live and hindsight versions — +0.25 of Sharpe — is not a failure of the strategy. It is the price of the 6-session delay, and no better detector removes more than a fraction of it. |

> \U0001F4A1 **In plain words.** The detector works. The delay is close to a mathematical floor.
> Those two facts together are the whole result.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** A variance CUSUM detects planted volatility regime changes at a usable false-alarm
  rate.
- **H₂ (the bound).** Its measured delay is within a small factor of Wald's
  `threshold / (change − drift)`, so the delay is information-limited rather than
  implementation-limited.
- **H₃ (the trade-off).** Delay and false-alarm rate trade off along a curve with no optimum.
- **H₄ (hindsight).** Retrospective segmentation places the same breaks materially earlier —
  the difference between "was there a break" and "is there a break now".
- **H₅ (the cost).** A live switching rule underperforms the same rule given the dates, and the
  gap is attributable to the delay.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 The detector, and its no-look-ahead property
"""
        ),
        code(
            r"""
w = st.synthetic_series(n=6000, break_points=[1500, 3000, 4500], vol_shift=3.0)
r = w["returns"]
# the tamper test: rewriting the tail must not change the head
bad = r.copy(); bad.iloc[4000:] *= 20
a = st.cusum(r, warmup=250)["pos"].iloc[:3500]
b = st.cusum(bad, warmup=250)["pos"].iloc[:3500]
print(f"strictly causal: {np.allclose(a.to_numpy(), b.to_numpy())}")
c = st.variance_cusum(r, 0.5, 5.0)
print(pd.Series(st.detection_delay(c["alarm"], w["breaks"])).drop("delays").to_string())
print()
print(pd.Series(st.alarm_rate(c["alarm"])).to_string())
"""
        ),
        md(
            r"""

### 2.2 The Wald bound
"""
        ),
        code(
            r"""
rows = []
for vs in (1.25, 1.5, 2.0, 3.0, 5.0, 8.0, 12.0):
    ws = st.synthetic_series(n=6000, break_points=[3000], vol_shift=vs)
    for th in (3.0, 5.0, 10.0):
        cs = st.variance_cusum(ws["returns"], 0.5, th)
        d2 = st.detection_delay(cs["alarm"], ws["breaks"])
        csd = np.log(vs) / (np.pi / np.sqrt(2))
        rows.append({"vol_shift": vs, "threshold": th, "change_sd": csd,
                     "measured": d2["median_delay"],
                     "theory": st.theoretical_delay(csd, th, 0.5)})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(9.5, 6))
ok = d.dropna(subset=["measured"])
ok = ok[np.isfinite(ok["theory"])]
ax.scatter(ok["theory"], ok["measured"], s=80, c=ok["threshold"], cmap="viridis")
lim = [0, min(ok[["theory", "measured"]].max().max() * 1.1, 400)]
ax.plot(lim, lim, "k--", lw=2, label="measured = theory")
ax.set_xlabel("Wald floor (sessions)"); ax.set_ylabel("measured delay (sessions)")
ax.set_xlim(lim); ax.set_ylim(lim); ax.legend(fontsize=9)
plt.colorbar(ax.collections[0], ax=ax, label="threshold")
plt.show()
print(ok.round(1).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Points near the diagonal are detections running at the
> information limit. Points far above it mean the detector is leaving something on the table;
> points below would mean the bound is being violated, which should not happen and does not.
"""
        ),
        md(
            r"""

### 2.3 The trade-off curve
"""
        ),
        code(
            r"""
roc = st.roc_curve(r, w["breaks"],
                   thresholds=(1.5, 2, 3, 4, 5, 7, 10, 15, 20, 30), drift=0.5)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(roc["alarms_per_year"], roc["median_delay"], "o-", lw=2, color="#c0392b")
for th, rr in roc.iterrows():
    axes[0].annotate(f"{th:.0f}", (rr["alarms_per_year"], rr["median_delay"]),
                     fontsize=7, xytext=(4, 3), textcoords="offset points")
axes[0].set_xlabel("false alarms per year"); axes[0].set_ylabel("median delay (sessions)")
axes[0].set_title("the trade-off, labelled by threshold")
axes[1].plot(roc.index, roc["detection_rate"] * 100, "o-", lw=2, color="#2ea44f")
axes[1].set_xlabel("threshold"); axes[1].set_ylabel("breaks detected (%)")
plt.tight_layout(); plt.show()
print(roc.round(3).to_string())
"""
        ),
        md(
            r"""

### 2.4 Sequential against retrospective
"""
        ),
        code(
            r"""
rows = []
for vs in (2.0, 3.0, 5.0):
    ws = st.synthetic_series(n=6000, break_points=[1500, 3000, 4500], vol_shift=vs)
    cs = st.variance_cusum(ws["returns"], 0.5, 5.0)
    seq = st.detection_delay(cs["alarm"], ws["breaks"])
    retro = st.binary_segmentation(ws["returns"], max_breaks=5)
    errs = [min(abs(int(np.busday_count(b.date(), rb.date()))) for rb in retro)
            for b in ws["breaks"]] if retro else []
    rows.append({"vol_shift": vs, "sequential delay": seq["median_delay"],
                 "retrospective error": np.median(errs) if errs else np.nan,
                 "n_retro_breaks": len(retro)})
d = pd.DataFrame(rows).set_index("vol_shift")
print(d.round(1).to_string())
fig, ax = plt.subplots(figsize=(9.5, 4.8))
d[["sequential delay", "retrospective error"]].plot.bar(ax=ax,
                                                        color=["#c0392b", "#2ea44f"])
ax.set_ylabel("sessions from the true break"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
"""
        ),
        md(
            r"""

### 2.5 The real tape, every asset
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(len(assets), 1, figsize=(13, 1.5 * len(assets)),
                         sharex=True)
rows = []
for ax, (tk, s) in zip(np.atleast_1d(axes), assets.items()):
    cc = st.variance_cusum(s, 0.5, 5.0)
    if cc.empty:
        ax.axis("off"); continue
    fired = cc.index[cc["alarm"]]
    ax.vlines(fired, 0, 1, lw=0.8, color="#c0392b")
    ax.set_yticks([]); ax.set_ylabel(tk, fontsize=7, rotation=0, ha="right", va="center")
    ax.set_ylim(0, 1)
    ar = st.alarm_rate(cc["alarm"])
    rows.append({"asset": tk, "alarms": ar["n_alarms"],
                 "per year": ar["alarms_per_year"],
                 "mean run length": ar["mean_run_length"]})
np.atleast_1d(axes)[0].set_title("Every alarm, by asset")
plt.tight_layout(); plt.show()
print(pd.DataFrame(rows).set_index("asset").round(2).to_string())
"""
        ),
        md(
            r"""

### 2.6 Live against hindsight, swept
"""
        ),
        code(
            r"""
episodes = ["1998-08-17", "2000-03-24", "2008-09-15", "2020-02-20", "2022-01-04"]
rows = []
for th in (2.0, 3.0, 5.0, 8.0, 12.0, 20.0):
    for days in (5, 21, 63):
        al = st.variance_cusum(lead, 0.5, th)["alarm"]
        live = st.regime_switch_strategy(lead, al, cash, days, 5.0)
        rows.append({"threshold": th, "risk_off": days,
                     "cagr": live["strategy"]["cagr"],
                     "sharpe": live["strategy"]["sharpe"],
                     "max_dd": live["strategy"]["max_dd"],
                     "invested": live["time_in_market"]})
d = pd.DataFrame(rows)
bh = st.regime_switch_strategy(lead, pd.Series(False, index=lead.index), cash)["buy_hold"]
hind = st.hindsight_strategy(lead, [pd.Timestamp(x) for x in episodes], cash, 21, 5.0)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
piv = d.pivot(index="threshold", columns="risk_off", values="sharpe")
piv.plot(ax=axes[0], marker="o")
axes[0].axhline(bh["sharpe"], color="k", ls="--", lw=1.5, label="buy and hold")
axes[0].axhline(hind["strategy"]["sharpe"], color="#2ea44f", ls=":", lw=2,
                label="told the dates")
axes[0].set_ylabel("Sharpe"); axes[0].legend(fontsize=7, title="risk-off days")
piv2 = d.pivot(index="threshold", columns="risk_off", values="max_dd")
piv2.mul(100).plot(ax=axes[1], marker="o")
axes[1].axhline(bh["max_dd"] * 100, color="k", ls="--", lw=1.5)
axes[1].set_ylabel("max drawdown (%)"); axes[1].legend(fontsize=7, title="risk-off days")
plt.tight_layout(); plt.show()
print(d.round(4).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The dotted green line is the ceiling: what you would earn
> knowing the dates. Every solid line is what a real detector delivers. The vertical distance
> is the delay, converted into Sharpe.
"""
        ),
        md(
            r"""

### 2.7 Mean shifts, and why nobody detects those
"""
        ),
        code(
            r"""
rows = []
for ms in (0.0, 0.25, 0.5, 1.0, 2.0):
    ws = st.synthetic_series(n=6000, break_points=[3000], vol_shift=1.0, mean_shift=ms)
    cs = st.cusum(ws["returns"], 0.5, 5.0)
    dd2 = st.detection_delay(cs["alarm"], ws["breaks"])
    rows.append({"mean shift (sd)": ms, "detected": dd2["n_detected"],
                 "delay": dd2["median_delay"],
                 "false alarms/yr": st.alarm_rate(cs["alarm"])["alarms_per_year"]})
print(pd.DataFrame(rows).set_index("mean shift (sd)").round(2).to_string())
print()
print("A 0.25-sd shift in DAILY mean return is an enormous economic change --")
print("about 4% a year at 16% volatility -- and it is essentially undetectable.")
print("That is why every practical regime detector works on variance.")
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
w = st.synthetic_series(n=6000, break_points=[1500, 3000, 4500], vol_shift=3.0)
c = st.variance_cusum(w["returns"], 0.5, 5.0)
dd = st.detection_delay(c["alarm"], w["breaks"])
csd = np.log(3.0) / (np.pi / np.sqrt(2))
al = st.variance_cusum(lead, 0.5, 5.0)["alarm"]
live = st.regime_switch_strategy(lead, al, cash, 21, 5.0)
pd.DataFrame({
    "planted breaks detected": [dd["detection_rate"]],
    "median delay (sessions)": [dd["median_delay"]],
    "Wald floor (sessions)": [st.theoretical_delay(csd, 5.0, 0.5)],
    "ratio to the floor": [dd["median_delay"] / st.theoretical_delay(csd, 5.0, 0.5)],
    "alarms per year": [st.alarm_rate(c["alarm"])["alarms_per_year"]],
    "live Sharpe": [live["strategy"]["sharpe"]],
    "buy-hold Sharpe": [live["buy_hold"]["sharpe"]],
    "hindsight Sharpe": [hind["strategy"]["sharpe"]],
    "cost of the delay (Sharpe)": [hind["strategy"]["sharpe"]
                                   - live["strategy"]["sharpe"]],
}).T.rename(columns={0: "value"}).round(3)
"""
        ),
        md(
            r"""

## 4 · Going further

- **PELT** (Killick, Fearnhead & Eckley 2012) is exact rather than greedy and linear in *n* —
  a strict improvement on the binary segmentation used here for the retrospective benchmark.
- **Bayesian online change-point detection** (Adams & MacKay 2007) handles an unknown change
  size, which CUSUM does not, and would likely raise the detection rate at the same alarm rate.
  It will not beat section 2.2's bound.
- **Implied volatility as an input.** The only genuine way to shorten the delay is to use a
  forward-looking observable. Running the same detector on the VIX rather than realised
  volatility is the obvious test.
- **Gradual regimes.** Everything here assumes a step change. Real regimes ramp, which makes
  both the true date and the delay fuzzier than any of these numbers admit.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
