"""Notebook builder for Study 964 — All-Time High.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# All-Time High 🏔
### "Never buy at a record" — so what happened to the money that did?

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The advice is universal and it feels like prudence: wait for a pullback, don't buy the top.
This notebook takes every day the market closed at a record and follows the money forward —
one month, three months, a year — and then prices the alternative the advice implies:
sitting in Treasury bills until the market is cheaper than it was.

> 📓 **This is the plain-language layer.** The inference (and the reason a
> twelve-month claim has about thirty independent observations, not eight thousand) is in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it. House
> style in [METHODOLOGY.md](../../../METHODOLOGY.md).
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""
## The answer first 🎯

| Question | Answer |
|---|---|
| Is a record high rare? | No. Roughly one session in fourteen closes at one, and they arrive in clusters. |
| Did money invested at records do worse? | No — over the next twelve months it did slightly **better** than money invested on an average day. |
| Should you wait for a dip, then? | Waiting cost more compounding than the drawdown it avoided, on five of six tapes. |
| Is that a law of nature? | No. Every tape here survived and trended up. That caveat is the honest half of this study. |
"""
        ),
        md(
            r"""
## 1 · The claim

> *"Never buy at an all-time high. That's where everyone who wanted in is already in. Wait
> for the pullback — there's always a pullback."*

The claim has a real mechanism behind it: **anchoring**. The old high is a reference point,
and paying more than anyone has ever paid feels like a mistake in a way that paying 10% less
than last month's price does not (Barberis & Thaler 2003).
"""
        ),
        md(
            r"""
## 2 · So what?

If the advice is right, a simple rule — sit in bills until the market is below its peak —
should beat owning the thing. If it is wrong, the advice quietly costs its followers years
of compounding while they wait. There is no third option where it doesn't matter: it is a
rule about *when to own the market at all*.
"""
        ),
        code(
            r"""
from ath_buy import data, strategy as st

px = data.load_prices()
cash = px[data.CASH].dropna()
spy = px["SPY"].dropna()
print(f"as-of {data.AS_OF}  |  SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} sessions)")
print(f"share of SPY sessions closing at a record high: "
      f"{st.share_of_days_at_high(spy):.1%}")
print(f"today's distance from the peak: {st.drawdown(spy).iloc[-1]:+.2%}")
"""
        ),
        md(
            r"""
### First, how unusual is a record?
"""
        ),
        code(
            r"""
dd = st.drawdown(spy)
hi = st.at_high(spy)
fig, ax = plt.subplots(figsize=(11, 5))
ax.fill_between(dd.index, dd * 100, 0, color="#c0392b", alpha=0.35, lw=0)
ax.scatter(spy.index[hi], np.zeros(hi.sum()), s=3, color="#2ea44f", label="record-high close")
ax.set_ylabel("distance below the running peak (%)")
ax.set_title(f"SPY total return: {hi.mean():.0%} of sessions close at a record — in clusters")
ax.legend(loc="lower left")
plt.show()
"""
        ),
        md(
            r"""
Records are not a rare event at the top of a bubble; they are what a rising market
*does*, day after day, for years at a time. Any rule that avoids them is a rule that avoids
most of the good years.
"""
        ),
        md(
            r"""
## 3 · How would we even know?

Mark every record-high close. Then look at what the next month, quarter and year did — and
compare it not to some abstraction but to the alternative: buying on a day when the market
was 2%, 5%, 10% or 20% below its peak.
"""
        ),
        md(
            r"""
## 4 · The teardown
"""
        ),
        code(
            r"""
tbl = st.forward_table(spy)
out = pd.DataFrame({
    "from a record high": tbl["mean_state"],
    "from every other day": tbl["mean_other"],
    "gap": tbl["diff"],
    "HAC t": tbl["t_diff"],
    "win rate at a high": tbl["win_state"],
    "win rate elsewhere": tbl["win_other"],
})
out.index = [st.HORIZON_LABEL[i] for i in out.index]
fig, ax = plt.subplots(figsize=(9, 4.5))
out[["from a record high", "from every other day"]].mul(100).plot.bar(
    ax=ax, color=["#2ea44f", "#8b949e"], edgecolor="none")
ax.set_ylabel("mean forward total return (%)")
ax.set_title("SPY: buying at a record versus buying on any other day")
ax.legend(title="")
plt.show()
out.round(4)
"""
        ),
        md(
            r"""
> 🔬 **For the quants.** Those *t*-statistics already carry a Hansen-Hodrick
> HAC correction at the horizon lag. Without it they roughly triple, which is how this kind
> of table usually gets published.
"""
        ),
        md(
            r"""
### The comparison that actually matters

"Don't buy at the high" means "buy somewhere else". Here is what *somewhere else* paid.
"""
        ),
        code(
            r"""
bt = st.drawdown_bucket_table(spy, 252)
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.bar(range(len(bt)), bt["mean_fwd"] * 100, color="#2ea44f", alpha=0.85)
ax.set_xticks(range(len(bt)))
ax.set_xticklabels(bt.index, rotation=20, ha="right")
ax.set_ylabel("mean 12-month forward return (%)")
ax.set_title("SPY: forward returns by how far below the peak the money went in")
plt.show()
bt.round(4)
"""
        ),
        md(
            r"""
## 5 · The verdict

**Signal: Weak.** Money invested on a record-high close earned **+12.4%** over the next twelve months against **+10.2%** from every other day — a gap of **+2.3%** (HAC *t* = +0.17 at the horizon lag; the non-overlapping cross-check gives -0.6%). Record highs are also not rare: **11%** of SPY's sessions closed at one. The direction is the finding — it is not negative — and every tape here is a survivor, which flatters it.

**Tradability: Mirage.** Waiting for a **5%** dip and sitting in bills otherwise was invested only 41% of the time and gave up **-5.08%/yr** of compounding on SPY (excess-Sharpe gap -0.22, *t* = -2.54); it won on excess Sharpe on **0 of 6** tapes. The drawdown it buys back is real — the return it gives up is larger.
"""
        ),
        md(
            r"""
## 6 · Could you actually trade it?

The rule, made literal: own the market only when it is at least 5% below its peak, hold
T-bills otherwise, pay 2 bps every time you switch.
"""
        ),
        code(
            r"""
c = cash.reindex(spy.index).ffill().dropna()
s = spy.reindex(c.index)
f = st.dip_strategy(s, c, dip_pct=0.05, cost_bps=2.0)
curves = pd.DataFrame({
    "wait for a 5% dip": (1 + f["strategy"]).cumprod(),
    "buy and hold": (1 + f["buy_hold"]).cumprod(),
    "T-bills": (1 + f["cash"]).cumprod(),
})
fig, ax = plt.subplots(figsize=(11, 5.5))
curves.plot(ax=ax, logy=True, color=["#c0392b", "#2ea44f", "#8b949e"])
ax.set_ylabel("growth of $1 (log scale)")
ax.set_title("The advice, made literal")
ax.legend(title="")
plt.show()
r = st.race(s, c, 0.05, 2.0)
print(f"invested {r['time_invested']:.0%} of the time, {r['switches_per_year']:.1f} switches/yr")
print(f"CAGR {r['strategy']['cagr']:+.2%} vs buy-and-hold {r['buy_hold']['cagr']:+.2%} "
      f"({r['cagr_gap']:+.2%}/yr)")
print(f"worst drawdown {r['strategy']['max_dd']:+.1%} vs {r['buy_hold']['max_dd']:+.1%}")
"""
        ),
        md(
            r"""
The rule does what it promises — it is out of the market for the worst of the
falls, and its worst drawdown is smaller. It just costs more than it saves, because being out
of the market also means being out of it for the recoveries and for the long, boring,
record-setting stretches in between.
"""
        ),
        md(
            r"""
## 7 · Going further 🚪

- Run the same test on the **Nikkei from 1990** or any index that spent a generation below
  its peak. That is the honest stress test of everything above, and it is the one this
  study's six survivors cannot provide.
- The rule with a **valuation** condition instead of a price condition (buy dips only when
  the market is also cheap) is the version practitioners actually mean.
- What happens if you invest at records but **hedge**? Trading a little return for the tail
  is a different question from staying out.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# All-Time High — a quantitative teardown 🔬
### Conditional forward returns · Hansen-Hodrick lags · non-overlapping cross-check · the rule as a portfolio

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Two things
make this study harder than it looks: forward returns at every session **overlap** almost
perfectly, and every tape in the sample is a **survivor**. Both are handled explicitly below
— one with statistics, the other with a declaration, because it cannot be handled with
statistics.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance, pinned as-of the
> date in [`docs/results.md`](../docs/results.md); literature map in
> [`docs/references.md`](../docs/references.md).
>
> 💡 **The `💡 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from ath_buy import data, strategy as st

px = data.load_prices()
cash = px[data.CASH].dropna()
spy = px["SPY"].dropna()
print(f"as-of {data.AS_OF}  |  SPY {spy.index[0].date()} -> {spy.index[-1].date()} "
      f"({len(spy):,} sessions)")
print(f"share of SPY sessions closing at a record high: "
      f"{st.share_of_days_at_high(spy):.1%}")
print(f"today's distance from the peak: {st.drawdown(spy).iloc[-1]:+.2%}")
"""
        ),
        md(
            r"""
## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Money invested on a record-high close earned **+12.4%** over the next twelve months against **+10.2%** from every other day — a gap of **+2.3%** (HAC *t* = +0.17 at the horizon lag; the non-overlapping cross-check gives -0.6%). Record highs are also not rare: **11%** of SPY's sessions closed at one. The direction is the finding — it is not negative — and every tape here is a survivor, which flatters it. |
| **Tradability** | Mirage | Waiting for a **5%** dip and sitting in bills otherwise was invested only 41% of the time and gave up **-5.08%/yr** of compounding on SPY (excess-Sharpe gap -0.22, *t* = -2.54); it won on excess Sharpe on **0 of 6** tapes. The drawdown it buys back is real — the return it gives up is larger. |

> 💡 **In plain words.** The data does not support "records are bad"; it weakly
> supports "records are fine, slightly better than average". The dip rule loses because being
> out of the market is expensive, not because the timing signal is perverse.
"""
        ),
        md(
            r"""
## 1 · The claim, steelmanned

- **H₁.** E[r(t → t+h) | close at a record] < E[r(t → t+h) | otherwise], for h ∈ {21, 63, 252}.
- **H₂ (the practical form).** A rule that holds the asset only below its peak earns a higher
  *excess-of-cash Sharpe* than buy-and-hold, net of switching costs.
- **H₃ (the fallback).** Even if H₁ fails on means, records precede *worse tails* — a lower
  win rate or a deeper worst case.
"""
        ),
        md(
            r"""
## 2 · So what? — the quantitative stakes

Being out of the market has a price and it is not small: the cash-versus-equity gap over this
sample runs several percent a year. A timing rule must therefore be *right often enough to pay
for its own absence*, which is a far higher bar than "sometimes avoids a crash".
"""
        ),
        md(
            r"""
## 3 · How we'd know — the protocol

1. **Total-return peaks.** A price-index record and a wealth-index record are different sets
   of days; the folklore is about money, so the running maximum is computed on total return.
2. **Horizon-lag HAC.** Overlapping windows share all but one observation
   (`conditional_stats` sets `lags = horizon`).
3. **A non-overlapping cross-check** that keeps one observation per horizon and discards the
   rest — the sample size that a twelve-month claim actually has.
4. **The counterfactual as buckets**, not as an average: at the high, 2%, 5%, 10%, 20% below.
5. **The rule as a portfolio**, with one day of lag and costs on every switch.
6. **A synthetic control** on a planted trend and on a random walk.
"""
        ),
        md(
            r"""
## 4 · The teardown

### 4.1 Every tape, every horizon
"""
        ),
        code(
            r"""
rows = []
for tk in data.RISKY:
    s = px[tk].dropna()
    t = st.forward_table(s)
    for hz, r in t.iterrows():
        rows.append({"ticker": tk, "horizon": st.HORIZON_LABEL[hz], "gap": r["diff"],
                     "t": r["t_diff"], "n_high": int(r["n_state"])})
grid = pd.DataFrame(rows)
pv = grid.pivot(index="ticker", columns="horizon", values="gap")[
    ["1 month", "3 months", "12 months"]]
fig, ax = plt.subplots(figsize=(9, 4.5))
im = ax.imshow(pv.values * 100, cmap="RdYlGn", vmin=-6, vmax=6, aspect="auto")
ax.set_xticks(range(pv.shape[1])); ax.set_xticklabels(pv.columns)
ax.set_yticks(range(pv.shape[0])); ax.set_yticklabels(pv.index)
for i in range(pv.shape[0]):
    for j in range(pv.shape[1]):
        ax.text(j, i, f"{pv.values[i, j] * 100:+.1f}", ha="center", va="center", fontsize=9)
ax.set_title("Forward-return gap, record high minus everywhere else (pp)")
fig.colorbar(im, ax=ax, label="percentage points")
plt.show()
grid.round(4)
"""
        ),
        md(
            r"""
### 4.2 What the overlap is doing to the standard errors
"""
        ),
        code(
            r"""
from quantlab.analytics import mean_tstat_hac
f = st.forward_return(spy, 252).dropna()
m = st.at_high(spy).reindex(f.index).fillna(False)
comp = pd.DataFrame({
    "lags = 0 (wrong)": [mean_tstat_hac(f[m], lags=0)["tstat"]],
    "lags = 21": [mean_tstat_hac(f[m], lags=21)["tstat"]],
    "lags = 252 (Hansen-Hodrick)": [mean_tstat_hac(f[m], lags=252)["tstat"]],
}, index=["t on the mean 12m return after a record"])
non = st.nonoverlap_stats(spy, 252)
print(f"non-overlapping: {non['n_state']} record-year observations vs {non['n_other']} others, "
      f"gap {non['diff']:+.2%}, t {non['t_diff']:+.2f}")
comp.round(2)
"""
        ),
        md(
            r"""
> 💡 **In plain words.** The same data can produce a *t* of 8 or a *t* of 1
> depending only on whether you admit that overlapping years are not independent. This is the
> most common way a long-horizon claim gets published.
"""
        ),
        md(
            r"""
### 4.3 The distribution, not the mean
"""
        ),
        code(
            r"""
f12 = st.forward_return(spy, 252).dropna()
m = st.at_high(spy).reindex(f12.index).fillna(False)
fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(f12[~m] * 100, bins=60, alpha=0.6, density=True, color="#8b949e", label="any other day")
ax.hist(f12[m] * 100, bins=60, alpha=0.6, density=True, color="#2ea44f", label="at a record")
ax.axvline(0, color="k", lw=1)
ax.set_xlabel("12-month forward total return (%)"); ax.set_ylabel("density")
ax.set_title("SPY: the whole distribution, not just its mean")
ax.legend()
plt.show()
pd.DataFrame({
    "at a record": [f12[m].mean(), f12[m].std(), f12[m].quantile(0.05), (f12[m] > 0).mean()],
    "any other day": [f12[~m].mean(), f12[~m].std(), f12[~m].quantile(0.05), (f12[~m] > 0).mean()],
}, index=["mean", "sd", "5th pct", "win rate"]).round(4)
"""
        ),
        md(
            r"""
### 4.4 The rule, priced properly
"""
        ),
        code(
            r"""
c = cash.reindex(spy.index).ffill().dropna()
s = spy.reindex(c.index)
sw = st.dip_sweep(s, c, dips=(0.0, 0.02, 0.05, 0.10, 0.20), cost_bps=2.0)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].bar([f"{d:.0%}" for d in sw.index], sw["cagr_gap"] * 100, color="#c0392b")
axes[0].axhline(0, color="k", lw=0.8)
axes[0].set_title("CAGR given up versus buy-and-hold (pp/yr)")
axes[1].bar([f"{d:.0%}" for d in sw.index], sw["time_invested"] * 100, color="#8b949e")
axes[1].set_title("Share of the time actually invested (%)")
for a in axes:
    a.set_xlabel("wait for a dip of at least")
plt.show()
sw.round(4)
"""
        ),
        md(
            r"""
### 4.5 Costs are not the binding constraint — absence is
"""
        ),
        code(
            r"""
rows = []
for cb in (0.0, 2.0, 5.0, 20.0):
    r = st.race(s, c, 0.05, cb)
    rows.append({"cost_bps": cb, "cagr_gap": r["cagr_gap"], "sharpe_gap": r["sharpe_gap"],
                 "switches_per_year": r["switches_per_year"]})
pd.DataFrame(rows).set_index("cost_bps").round(4)
"""
        ),
        md(
            r"""
> 💡 **In plain words.** Take the trading costs to zero and the rule still
> loses. What it pays for is the *time out of the market*, and no broker can discount that.
"""
        ),
        md(
            r"""
## 5 · The verdict

The decisive numbers: the pooled 12-month gap and its honest *t*, the non-overlapping
cross-check, and the rule's CAGR gap.
"""
        ),
        code(
            r"""
pool = []
for tk in data.RISKY:
    s_ = px[tk].dropna()
    t = st.forward_table(s_).loc[252]
    n = st.nonoverlap_stats(s_, 252)
    c_ = cash.reindex(s_.index).ffill().dropna()
    r = st.race(s_.reindex(c_.index), c_, 0.05, 2.0)
    pool.append({"ticker": tk, "12m gap": t["diff"], "HAC t": t["t_diff"],
                 "non-overlap gap": n["diff"], "dip-rule CAGR gap": r["cagr_gap"],
                 "dip-rule Sharpe gap": r["sharpe_gap"]})
summary = pd.DataFrame(pool).set_index("ticker")
print(summary.round(4).to_string())
print(f"\npooled 12m gap {summary['12m gap'].mean():+.2%} | "
      f"mean HAC t {summary['HAC t'].mean():+.2f} | "
      f"positive on {(summary['12m gap'] > 0).sum()}/6 tapes | "
      f"dip rule wins Sharpe on {(summary['dip-rule Sharpe gap'] > 0).sum()}/6")
"""
        ),
        md(
            r"""
## 6 · Could you trade it?

There is nothing to trade on the long side: "keep owning it" is not a trade. The tradable
question is whether the *avoidance* rule pays, and it does not — before costs, after costs, or
at any patience threshold tested.
"""
        ),
        md(
            r"""
## 7 · Going further

- **A non-survivor tape.** The Nikkei 1990-2024, or the FTSE 100 in real terms, is the
  experiment that would falsify the comfortable reading of this study.
- **Conditioning on valuation** (CAPE, excess CAPE yield) rather than on price level — the
  version of the claim that has actual academic support (studies 118, 120 on this desk).
- **Path dependence:** records reached after a long grind versus records reached in a vertical
  melt-up may behave differently; a hazard model on time-since-last-record would test it.
- **Options overlay** at records instead of cash: same fear, much smaller opportunity cost.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
