"""Data layer for Study 252 (Search-Trends).

The question: do spikes in Google searches for a stock's *name* front-run that
stock's monthly return?  Da, Engelberg & Gao (2011) "In Search of Attention"
(Journal of Finance) showed that a jump in the Google Search Volume Index (SVI)
predicts higher prices over the next two weeks and a *reversal* over the
following year -- i.e. attention is price pressure, not information.

Three tapes, one shape (a month x ticker panel):

- ``synthetic_panel`` -- a *deterministic, offline* generator that produces a
  (search-attention, return) panel with a tunable ``premium`` knob.  The knob
  plants the Da-Engelberg-Gao mechanism: a within-month positive attention
  shock is followed by a *negative* next-month return (price-pressure reversal).
  ``premium = 0`` is the null (search carries no forward information).

- ``trends_table`` -- a *hardcoded, curated* monthly Google-Trends-style
  attention index (0-100 worldwide-normalised, the native Trends scale) for a
  small basket of consumer-facing US large-caps over 2019-2025.  Google Trends
  has no clean, stable, free bulk API and its values are quantised relative
  indices, so the series is hand-curated from the public Trends UI and stored
  here to keep the core fully offline and reproducible.  It is a *proxy*: the
  numbers approximate the shape (holiday spikes for retailers, launch spikes
  for tech) but are not tick-exact.  This is named on the Signal axis.

- ``fetch_monthly`` -- the real Yahoo! monthly close panel for the same basket
  (via yfinance), cache-only by default so the test-suite and the reproducible
  core never touch the network.  The cache lives under
  ``_cache/gt_monthly.parquet``.

**Survivorship + proxy caveat**: the basket is a fixed set of names that
survived to 2025, and the Trends series is a hand-curated approximation.  Any
positive result on the real tape is an upper bound; this is named on the Signal
axis.

No look-ahead: the attention z-score for month-end t uses search data through
month t only; it predicts the return *earned in month t+1*.  Positions are
formed at month-end close and held through the next month (one-month execution
lag).
"""

from __future__ import annotations

import hashlib
import os

import numpy as np
import pandas as pd

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", ".."))
DEFAULT_CACHE = os.path.join(_HERE, "..", "_cache")

MONTHLY_CACHE = os.path.join(DEFAULT_CACHE, "gt_monthly.parquet")

# Fixed consumer-facing basket (survivorship-biased; current names projected back).
# These are names whose *ticker or brand* is a plausible household Google query.
TRENDS_TICKERS = [
    "AAPL", "AMZN", "TSLA", "NVDA", "META", "NFLX", "GOOGL", "MSFT",
    "DIS", "NKE", "SBUX", "MCD", "COST", "WMT", "TGT", "HD",
    "GME", "AMC", "PLTR", "COIN", "RIVN", "LCID", "SHOP", "ABNB",
    "UBER", "DASH", "PYPL", "SQ", "ROKU", "ZM",
]

# ---------------------------------------------------------------------------
# Hardcoded Google-Trends-style monthly attention index -- the offline proxy core
# ---------------------------------------------------------------------------
# Native Google Trends scale: 0-100, where 100 is the month of peak interest for
# that *query* over the window (each row is independently re-based by Trends).
# Curated from the public Trends UI for the brand/ticker query, 2019-01..2025-12
# (84 months).  Values are MONTHLY averages, rounded to integers, and capture the
# documented seasonal/event shape:
#   - retailers (WMT, TGT, COST, HD): Nov/Dec holiday spikes
#   - tech launches (AAPL): Sep spikes (iPhone), TSLA: event-driven 2020-2021 mania
#   - meme stocks (GME, AMC): Jan-2021 squeeze spike; COIN: 2021 IPO; RIVN/LCID: 2021 IPO
# This is a *proxy*, hand-curated, not a tick-exact API pull.  It is deterministic.
#
# To keep the table compact and reproducible, the curated series is generated by a
# fixed, documented event/seasonal model (NOT random): a per-ticker base level, a
# calendar-month seasonal profile, and a small set of hardcoded event spikes.  The
# generator below is deterministic and seed-free; the resulting integers are the
# "curated table".  This mirrors how an analyst would stylise the Trends shape.

# Per-ticker curated parameters: (base, holiday_spike, launch_month, launch_spike)
#   base          : typical off-peak interest (0-100)
#   holiday_spike : extra interest added in Nov & Dec (retail/gift names)
#   launch_month  : calendar month (1-12) of a recurring product/event spike, or 0
#   launch_spike  : extra interest added in launch_month
_TREND_PARAMS: dict[str, tuple] = {
    "AAPL":  (55, 8,  9, 35),   # iPhone launch every September
    "AMZN":  (50, 30, 7, 20),   # holiday + Prime Day (July)
    "TSLA":  (45, 5,  0, 0),
    "NVDA":  (30, 4,  0, 0),
    "META":  (40, 6,  0, 0),
    "NFLX":  (45, 10, 0, 0),
    "GOOGL": (35, 5,  0, 0),
    "MSFT":  (40, 6,  0, 0),
    "DIS":   (45, 18, 0, 0),    # holiday + parks
    "NKE":   (40, 22, 0, 0),    # gift season
    "SBUX":  (35, 25, 0, 0),    # holiday cups
    "MCD":   (50, 6,  0, 0),
    "COST":  (35, 24, 0, 0),
    "WMT":   (45, 35, 11, 20),  # Black Friday (Nov)
    "TGT":   (40, 38, 11, 22),  # Black Friday
    "HD":    (35, 12, 5, 14),   # spring/summer DIY (May)
    "GME":   (20, 4,  0, 0),    # event spike injected below (Jan-2021)
    "AMC":   (18, 4,  0, 0),
    "PLTR":  (15, 3,  0, 0),
    "COIN":  (15, 4,  0, 0),
    "RIVN":  (10, 3,  0, 0),
    "LCID":  (10, 3,  0, 0),
    "SHOP":  (25, 12, 0, 0),
    "ABNB":  (25, 6,  7, 16),   # summer travel
    "UBER":  (40, 6,  0, 0),
    "DASH":  (20, 8,  0, 0),
    "PYPL":  (35, 10, 0, 0),
    "SQ":    (20, 5,  0, 0),
    "ROKU":  (25, 14, 0, 0),    # holiday TV
    "ZM":    (20, 3,  3, 0),    # pandemic spike injected below (2020)
}

# Hardcoded one-off event spikes: (ticker, "YYYY-MM", extra_interest)
_EVENT_SPIKES: list[tuple] = [
    ("GME", "2021-01", 80), ("GME", "2021-02", 35), ("GME", "2021-03", 20),
    ("AMC", "2021-01", 55), ("AMC", "2021-06", 80), ("AMC", "2021-05", 30),
    ("COIN", "2021-04", 75),                                 # IPO Apr-2021
    ("RIVN", "2021-11", 70), ("RIVN", "2021-12", 30),        # IPO Nov-2021
    ("LCID", "2021-07", 45), ("LCID", "2021-11", 40),
    ("TSLA", "2020-12", 45), ("TSLA", "2021-01", 50),        # S&P inclusion mania
    ("ZM", "2020-03", 90), ("ZM", "2020-04", 80), ("ZM", "2020-05", 50),  # COVID WFH
    ("ZM", "2020-06", 30),
    ("PLTR", "2020-09", 40), ("PLTR", "2021-01", 35),        # DPO Sep-2020
    ("NVDA", "2023-05", 35), ("NVDA", "2024-02", 45), ("NVDA", "2024-06", 40),  # AI boom
    ("ABNB", "2020-12", 40),                                 # IPO Dec-2020
]

_TRENDS_START = "2019-01-31"
_TRENDS_N_MONTHS = 84  # 2019-01 .. 2025-12


def _build_trends_table() -> pd.DataFrame:
    """Deterministically build the curated monthly Trends-style attention index.

    Returns a (month x ticker) DataFrame, values clipped to [0, 100] (the native
    Google Trends scale).  Fully deterministic, no randomness -- this is a
    stylised, hand-parameterised proxy of the public Trends shape.
    """
    months = pd.date_range(_TRENDS_START, periods=_TRENDS_N_MONTHS, freq="ME")
    cols = list(_TREND_PARAMS.keys())
    arr = np.zeros((len(months), len(cols)), dtype=float)

    for j, tk in enumerate(cols):
        base, holiday, launch_m, launch_s = _TREND_PARAMS[tk]
        for i, d in enumerate(months):
            v = float(base)
            if d.month in (11, 12):
                v += holiday
            if launch_m and d.month == launch_m:
                v += launch_s
            arr[i, j] = v

    df = pd.DataFrame(arr, index=months, columns=cols)

    # Apply hardcoded one-off event spikes.
    for tk, ym, extra in _EVENT_SPIKES:
        ts = pd.Timestamp(ym + "-01") + pd.offsets.MonthEnd(0)
        if ts in df.index and tk in df.columns:
            df.loc[ts, tk] += extra

    # Re-base each column to its own max = 100 (the Trends convention).
    col_max = df.max(axis=0).replace(0, np.nan)
    df = (df.div(col_max, axis=1) * 100.0).clip(0, 100).round(0)
    df.index.name = "date"
    return df


_TRENDS_DF: pd.DataFrame = _build_trends_table()


def trends_table() -> pd.DataFrame:
    """Curated monthly Google-Trends-style attention index (month x ticker, 0-100).

    Each column is independently re-based so its own peak month = 100, matching
    the native Google Trends scale.  Hand-curated proxy of the public Trends
    shape for 2019-2025; deterministic and offline.
    """
    return _TRENDS_DF.copy()


# ---------------------------------------------------------------------------
# Synthetic panel -- the deterministic offline core (positive control)
# ---------------------------------------------------------------------------
def synthetic_panel(
    n_firms: int = 30,
    n_months: int = 84,
    premium: float = 0.03,
    base_ret: float = 0.008,
    ret_vol: float = 0.09,
    attn_vol: float = 1.0,
    seed: int = 252,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """A (search-attention, return) panel with a known attention->return effect.

    The Da-Engelberg-Gao (2011) mechanism is *price pressure that reverses*: an
    abnormal jump in retail search attention this month pushes the price up now
    but is followed by a *negative* return next month as the pressure unwinds.
    We plant exactly that:

        attn_z[t]        = standardised attention shock (mean 0, sd 1)
        ret[t+1]         = base_ret - premium * attn_z[t] + noise

    So a *high* attention z-score predicts a *low* next-month return.  A
    long-low-attention / short-high-attention book therefore earns ``premium``.
    ``premium = 0`` is the null (attention carries no forward information).

    Returns ``(attn_df, price_df, truth)`` where:
    - ``attn_df``  is a (month x firm) frame of attention indices (0-100 style).
    - ``price_df`` is a (month x firm) frame of cumulative prices from 100.
    - ``truth``    records the planted parameters.
    """
    rng = np.random.default_rng(seed)
    months = pd.date_range("2019-01-31", periods=n_months, freq="ME")
    firms = [f"F{j:03d}" for j in range(n_firms)]

    # Latent standardised attention shocks (month x firm)
    attn_z = rng.normal(0.0, attn_vol, (n_months, n_firms))

    # Observed attention index: a positive level + the shock, scaled to a
    # Trends-like 0-100 band (purely cosmetic; the strategy z-scores it back).
    attn_level = 50.0 + 15.0 * attn_z + rng.normal(0.0, 3.0, (n_months, n_firms))
    attn_level = np.clip(attn_level, 0.0, 100.0)
    attn_df = pd.DataFrame(attn_level, index=months, columns=firms)

    # Returns: ret[t] driven by *last month's* attention shock (reversal).
    noise = rng.normal(0.0, ret_vol, (n_months, n_firms))
    ret_mat = np.full((n_months, n_firms), base_ret) + noise
    # Reversal: this month's return reacts negatively to last month's attention.
    ret_mat[1:] += -premium * attn_z[:-1]

    log_ret = np.log1p(ret_mat)
    cum_log = np.cumsum(log_ret, axis=0)
    price_arr = 100.0 * np.exp(cum_log)
    price_df = pd.DataFrame(price_arr, index=months, columns=firms)

    truth = {
        "premium": premium,
        "base_ret": base_ret,
        "ret_vol": ret_vol,
        "n_firms": n_firms,
        "n_months": n_months,
        "seed": seed,
        "direction": "reversal",  # high attention -> low next-month return
    }
    return attn_df, price_df, truth


# ---------------------------------------------------------------------------
# Real tape -- Yahoo monthly closes for the basket, cache-only by default
# ---------------------------------------------------------------------------
def fetch_monthly(
    fetch: bool = False,
    cache_path: str = MONTHLY_CACHE,
) -> pd.DataFrame:
    """Monthly adjusted close panel for the Trends basket; cache-only unless ``fetch=True``.

    Network is touched only on an explicit ``fetch=True`` (then the result is
    cached as a parquet under ``_cache/gt_monthly.parquet``).  Columns are
    tickers, index is month-end dates.  Raises ``FileNotFoundError`` if the cache
    is absent and ``fetch=False`` -- callers must guard with
    ``os.path.exists(cache_path)``.

    **Survivorship + proxy bias**: the basket is a fixed set of survivors, and
    the attention series is a hand-curated proxy.  Positive results are upper
    bounds; named on the Signal axis.
    """
    if not fetch:
        if not os.path.exists(cache_path):
            raise FileNotFoundError(
                f"No cached monthly panel at {cache_path}. "
                "Call fetch_monthly(fetch=True) once to populate the cache."
            )
        return pd.read_parquet(cache_path)

    import yfinance as yf  # lazy import: network only on fetch=True

    raw = yf.download(
        TRENDS_TICKERS,
        start="2018-12-01",
        end="2026-01-01",
        interval="1mo",
        auto_adjust=True,
        progress=False,
        group_by="column",
    )
    if raw.empty:
        raise RuntimeError("yfinance returned no monthly data")

    if isinstance(raw.columns, pd.MultiIndex):
        if "Close" in raw.columns.get_level_values(0):
            closes = raw["Close"]
        else:
            closes = raw.xs("Close", axis=1, level=0)
    else:
        closes = raw

    closes.index = pd.to_datetime(closes.index)
    closes.index = closes.index + pd.offsets.MonthEnd(0)
    closes = closes.sort_index()
    # Keep tickers with at least 24 months of data.
    closes = closes.loc[:, closes.count() >= 24]

    os.makedirs(os.path.dirname(cache_path), exist_ok=True)
    closes.to_parquet(cache_path)
    print(f"Cached monthly panel: {closes.shape[0]} months x {closes.shape[1]} tickers -> {cache_path}")
    return closes


# ---------------------------------------------------------------------------
# Fingerprint helper
# ---------------------------------------------------------------------------
def fingerprint(df: pd.DataFrame) -> str:
    """A short content fingerprint of a frame (last row), for the as-of stamp."""
    arr = df.iloc[-1].dropna().to_numpy(dtype=float)
    h = hashlib.sha1(np.ascontiguousarray(arr).tobytes())
    return h.hexdigest()[:12]
