"""Notebook builder for Study 989 — The One-Way Beta.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The One-Way Beta \U0001F3A2
### Altcoins promise leverage on Bitcoin. Do they deliver it in both directions?

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

"It's a high-beta bet on Bitcoin." Nobody ever finishes that sentence with "in both
directions" — but that is how it is heard. This study measures the up-beta and the down-beta
separately, and spends most of its effort on why a gap between them is so easy to conjure from
nothing at all.

> \U0001F4D3 **This is the plain-language layer.** The bootstrap, the normal-benchmark tail
> correlations and the false-positive rate are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do altcoins have a higher beta on down days? | On the point estimate, mostly yes. |
| Is the gap statistically solid? | Far less than the usual test claims. |
| Would a symmetric world produce the same finding? | A surprising share of the time. |
| Does any of it change what you should do? | Less than the plain volatility already does. |
"""
        ),
        md(
            r"""

## 1 · The claim, measured
"""
        ),
        code(
            r"""
from onewaybeta import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
bench = rets[data.BENCHMARK].dropna()
alts = {tk: rets[tk].dropna() for tk in data.ALTS if rets[tk].notna().sum() > 800}
panel = st.panel_summary(alts, bench)
print(f"as-of {data.AS_OF} | {len(alts)} altcoins vs {data.BENCHMARK}")
print(panel[["beta", "beta_up", "beta_down", "difference", "naive_t"]].round(3).to_string())
"""
        ),
        md(
            r"""

The `difference` column is the whole argument, and the `naive_t` column is why people believe
it. The rest of this notebook is about that second column.
"""
        ),
        md(
            r"""

## 2 · What the split actually looks like
"""
        ),
        code(
            r"""
lead = list(alts)[0]
df = st.align(alts[lead], bench)
fig, ax = plt.subplots(figsize=(8.5, 7))
up, down = df[df["x"] > 0], df[df["x"] <= 0]
ax.scatter(up["x"] * 100, up["y"] * 100, s=6, alpha=0.3, color="#2ea44f", label="Bitcoin up")
ax.scatter(down["x"] * 100, down["y"] * 100, s=6, alpha=0.3, color="#c0392b",
           label="Bitcoin down")
cb = st.conditional_betas(alts[lead], bench)
xs_u = np.linspace(0, df["x"].max(), 20)
xs_d = np.linspace(df["x"].min(), 0, 20)
ax.plot(xs_u * 100, cb["beta_up"] * xs_u * 100, color="#2ea44f", lw=2.5,
        label=f"up-beta {cb['beta_up']:.2f}")
ax.plot(xs_d * 100, cb["beta_down"] * xs_d * 100, color="#c0392b", lw=2.5,
        label=f"down-beta {cb['beta_down']:.2f}")
ax.axhline(0, color="k", lw=0.8); ax.axvline(0, color="k", lw=0.8)
ax.set_xlabel(f"{data.BENCHMARK} daily return (%)"); ax.set_ylabel(f"{lead} (%)")
ax.legend(fontsize=8); ax.set_title(f"{lead}: two lines through one cloud")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Look at how much of each line is determined by a handful of
> extreme days at the edges of the cloud. That is the sampling variability the naive test
> ignores.
"""
        ),
        md(
            r"""

## 3 · The trap

Here is the same experiment run on a world I built myself, where the up-beta and the down-beta
are **identical by construction**. There is no asymmetry to find.
"""
        ),
        code(
            r"""
rows = []
for s in range(12):
    sim = st.synthetic_world(n=len(df), beta_up=1.5, beta_down=1.5, seed=989 + s)
    cb = st.conditional_betas(sim["alt"], sim["bench"])
    rows.append({"run": s, "up": cb["beta_up"], "down": cb["beta_down"],
                 "difference": cb["difference"], "naive t": st.naive_two_sample_t(cb)})
d = pd.DataFrame(rows).set_index("run")
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.bar(d.index, d["difference"], color=np.where(np.abs(d["naive t"]) >= 2, "#c0392b",
                                                "#8b949e"))
ax.axhline(0, color="k", lw=1.2)
ax.set_xlabel("simulation run (all symmetric by construction)")
ax.set_ylabel("measured down-beta minus up-beta")
ax.set_title("Red bars are runs the naive test called significant")
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

Every one of those bars should be zero. They are not, and some of them pass the significance
test. Now go back and look at the real table again.
"""
        ),
        md(
            r"""

## 4 · The honest test
"""
        ),
        code(
            r"""
rows = []
for name, r in alts.items():
    at = st.asymmetry_test(r, bench, n_boot=500)
    cb = st.conditional_betas(r, bench)
    rows.append({"asset": name, "difference": at["difference"],
                 "naive t": st.naive_two_sample_t(cb), "bootstrap t": at["t"]})
d = pd.DataFrame(rows).set_index("asset")
fig, ax = plt.subplots(figsize=(10, 4.5))
d[["naive t", "bootstrap t"]].plot.bar(ax=ax, color=["#c0392b", "#2ea44f"])
ax.axhline(0, color="k", lw=1)
for y in (-2, 2):
    ax.axhline(y, ls="--", color="#8b949e", lw=1)
ax.set_ylabel("t-statistic on the up/down difference")
plt.setp(ax.get_xticklabels(), rotation=0, fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

## 5 · And what it actually cost you
"""
        ),
        code(
            r"""
rows = []
for name, r in alts.items():
    c = st.capture_ratios(r, bench)
    dd = st.drawdown_comparison(px[name].dropna(), px[data.BENCHMARK].dropna())
    rows.append({"asset": name, "up capture": c["up_capture"],
                 "down capture": c["down_capture"], "max drawdown": dd["max_dd"],
                 "Bitcoin's drawdown": dd["bench_max_dd"]})
d = pd.DataFrame(rows).set_index("asset")
fig, ax = plt.subplots(figsize=(10, 4.5))
d[["up capture", "down capture"]].plot.bar(ax=ax, color=["#2ea44f", "#c0392b"])
ax.axhline(1.0, color="k", ls="--", lw=1.5, label="matched Bitcoin")
ax.set_ylabel("compounded capture"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=0, fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Real.** Across 6 majors against Bitcoin over 8.6 years, the median altcoin's beta is **0.77 on Bitcoin's up days and 1.13 on its down days** — a difference of **+0.37**. The naive two-sample *t* on that difference averages +4.23; the block-bootstrapped one, which also accounts for the randomness in *which days count as down days*, is **+5.06** — smaller by a factor of 0.8. The corroborating measurement: 100% of the panel has negative coskewness, the third-moment fingerprint of the same phenomenon. And the control that matters most — under a symmetric simulated world with one beta, a naive split still declares asymmetry in **5%** of runs.

**Tradability: Partial.** Compounded rather than averaged, the median altcoin captured **107% of Bitcoin's up days and 109% of its down days**, and ran a maximum drawdown of -95% against Bitcoin's -83% (1.14×). That gap is large enough to matter to position sizing: the leverage you are buying is not the leverage you are paying for.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **The coins that died.** Every altcoin here survived to 2026. The ones that went to zero had
  the highest down-betas of all and are in none of these tables. That bias runs one way and it
  is large.
- **Intraday.** A crash is a few hours, not a few days. Daily data may be too coarse to see the
  moment the correlation actually goes to one.
- **Copulas rather than betas.** Tail dependence has a proper statistical machinery; a beta
  split is the crude version of it.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The One-Way Beta — a quantitative teardown \U0001F52C
### Conditional betas · block-bootstrapped differences · Longin-Solnik benchmarks · coskewness

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The object of
study is not really the altcoins; it is the up/down beta split, which is among the most
reliable ways to find something that is not there.

> ⚠️ **Not investment advice.** Daily closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from onewaybeta import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
bench = rets[data.BENCHMARK].dropna()
alts = {tk: rets[tk].dropna() for tk in data.ALTS if rets[tk].notna().sum() > 800}
panel = st.panel_summary(alts, bench)
print(f"as-of {data.AS_OF} | {len(alts)} altcoins vs {data.BENCHMARK}")
print(panel[["beta", "beta_up", "beta_down", "difference", "naive_t"]].round(3).to_string())
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Across 6 majors against Bitcoin over 8.6 years, the median altcoin's beta is **0.77 on Bitcoin's up days and 1.13 on its down days** — a difference of **+0.37**. The naive two-sample *t* on that difference averages +4.23; the block-bootstrapped one, which also accounts for the randomness in *which days count as down days*, is **+5.06** — smaller by a factor of 0.8. The corroborating measurement: 100% of the panel has negative coskewness, the third-moment fingerprint of the same phenomenon. And the control that matters most — under a symmetric simulated world with one beta, a naive split still declares asymmetry in **5%** of runs. |
| **Tradability** | Partial | Compounded rather than averaged, the median altcoin captured **107% of Bitcoin's up days and 109% of its down days**, and ran a maximum drawdown of -95% against Bitcoin's -83% (1.14×). That gap is large enough to matter to position sizing: the leverage you are buying is not the leverage you are paying for. |

> \U0001F4A1 **In plain words.** The point estimates lean the way the folklore says. The error
> bars, once computed properly, are wide enough to swallow the claim.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** For a typical altcoin, β⁻ > β⁺.
- **H₂ (inference).** The difference survives a block bootstrap that re-derives the up/down
  split inside each resample.
- **H₃ (corroboration).** Coskewness is negative and the Bawa-Lindenberg / Hogan-Warren downside
  betas exceed the unconditional beta — three independent measurements of one phenomenon.
- **H₄ (artefact control).** Tail correlation exceeds what a bivariate normal with the same
  overall correlation would produce.
- **H₅ (not time-varying betas).** The difference survives fitting within eras.
- **H₆ (size).** The procedure's false-positive rate on a symmetric world is small.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 The panel, every measurement
"""
        ),
        code(
            r"""
print(st.panel_summary(alts, bench).round(3).to_string())
"""
        ),
        code(
            r"""
panel = st.panel_summary(alts, bench)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
w = 0.35
xs = np.arange(len(panel))
axes[0].bar(xs - w / 2, panel["beta_up"], w, label="up-beta", color="#2ea44f")
axes[0].bar(xs + w / 2, panel["beta_down"], w, label="down-beta", color="#c0392b")
axes[0].axhline(1.0, color="k", ls="--", lw=1)
axes[0].set_xticks(xs); axes[0].set_xticklabels(panel.index, rotation=20, ha="right",
                                                fontsize=8)
axes[0].set_ylabel("beta"); axes[0].legend(fontsize=8)
axes[1].scatter(panel["difference"], panel["coskewness"], s=60, color="#1f6feb")
for name, r in panel.iterrows():
    axes[1].annotate(name.replace("-USD", ""), (r["difference"], r["coskewness"]),
                     fontsize=7, xytext=(3, 3), textcoords="offset points")
axes[1].axhline(0, color="k", lw=1); axes[1].axvline(0, color="k", lw=1)
axes[1].set_xlabel("down-beta minus up-beta"); axes[1].set_ylabel("coskewness")
axes[1].set_title("Two measurements of one alleged phenomenon")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The right panel is the corroboration test. If the asymmetry is
> real, points should sit in the bottom-right quadrant — a positive beta gap *and* negative
> coskewness. Scatter across all four quadrants means the two measurements disagree, and two
> disagreeing measurements of one phenomenon is a warning.
"""
        ),
        md(
            r"""

### 2.2 The naive test against the bootstrap
"""
        ),
        code(
            r"""
rows = []
for name, r in alts.items():
    cb = st.conditional_betas(r, bench)
    at = st.asymmetry_test(r, bench, n_boot=800)
    rows.append({"asset": name, "difference": at["difference"],
                 "naive SE": np.sqrt(cb["se_up"] ** 2 + cb["se_down"] ** 2),
                 "bootstrap SE": at["boot_sd"],
                 "naive t": st.naive_two_sample_t(cb), "bootstrap t": at["t"],
                 "lo": at["lo"], "hi": at["hi"]})
d = pd.DataFrame(rows).set_index("asset")
d["SE inflation"] = d["bootstrap SE"] / d["naive SE"]
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.errorbar(d["difference"], range(len(d)),
            xerr=[d["difference"] - d["lo"], d["hi"] - d["difference"]],
            fmt="o", capsize=5, color="#2ea44f")
ax.axvline(0, color="k", lw=1.5)
ax.set_yticks(range(len(d))); ax.set_yticklabels(d.index, fontsize=8)
ax.set_xlabel("down-beta minus up-beta, with block-bootstrap 95% interval")
plt.show()
"""
        ),
        md(
            r"""

### 2.3 Tail correlation against the Longin-Solnik benchmark
"""
        ),
        code(
            r"""
rows = []
for name, r in alts.items():
    tc = st.tail_correlation(r, bench)
    if "down_tail" not in tc:
        continue
    rows.append({"asset": name, "overall": tc["overall"], "down tail": tc["down_tail"],
                 "normal would give": tc["normal_down_tail"], "excess": tc["excess_down"],
                 "up tail": tc["up_tail"], "normal up": tc["normal_up_tail"]})
d = pd.DataFrame(rows).set_index("asset")
fig, ax = plt.subplots(figsize=(11, 4.5))
xs = np.arange(len(d))
ax.bar(xs - 0.2, d["down tail"], 0.4, label="measured down-tail correlation",
       color="#c0392b")
ax.bar(xs + 0.2, d["normal would give"], 0.4, label="a normal would give this",
       color="#8b949e")
ax.axhline(d["overall"].mean(), color="k", ls="--", lw=1.2, label="overall correlation")
ax.set_xticks(xs); ax.set_xticklabels(d.index, rotation=20, ha="right", fontsize=8)
ax.set_ylabel("correlation"); ax.legend(fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The grey bars are what you would measure with *no* tail
> dependence whatsoever, just from cutting a normal distribution at its tenth percentile. Only
> the amount by which red exceeds grey is evidence of anything.
"""
        ),
        md(
            r"""

### 2.4 Thresholds and eras
"""
        ),
        code(
            r"""
lead = list(alts)[0]
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
sw = st.threshold_sweep(alts[lead], bench)
sw[["beta_up", "beta_down"]].plot(ax=axes[0], marker="o", color=["#2ea44f", "#c0392b"])
axes[0].set_xlabel("threshold defining a 'big' day"); axes[0].set_ylabel("beta")
axes[0].set_title(f"{lead}: how the answer moves with the definition")
rows = []
for name, r in alts.items():
    e = st.time_varying_control(r, bench, n_eras=4)
    for era, rr in e.iterrows():
        rows.append({"asset": name, "era": era[:10], "difference": rr["difference"]})
d = pd.DataFrame(rows)
d.pivot(index="era", columns="asset", values="difference").plot.bar(ax=axes[1])
axes[1].axhline(0, color="k", lw=1)
axes[1].set_ylabel("down-beta minus up-beta"); axes[1].legend(fontsize=6, ncol=2, title="")
plt.setp(axes[1].get_xticklabels(), rotation=20, ha="right", fontsize=7)
plt.tight_layout(); plt.show()
print(f"median within-era difference: {d['difference'].median():+.3f}")
print(f"share of era-asset cells with a positive difference: "
      f"{(d['difference'] > 0).mean():.0%}")
"""
        ),
        md(
            r"""

### 2.5 Size and power
"""
        ),
        code(
            r"""
rows = []
for bu, bd, tag in ((1.5, 1.5, "symmetric (null)"), (1.4, 1.6, "small asymmetry"),
                    (1.2, 1.8, "moderate"), (1.0, 2.0, "large")):
    naive, boot = [], []
    for s in range(15):
        sim = st.synthetic_world(n=len(st.align(alts[lead], bench)), beta_up=bu,
                                 beta_down=bd, seed=989 + s)
        cb = st.conditional_betas(sim["alt"], sim["bench"])
        naive.append(abs(st.naive_two_sample_t(cb)) >= 2)
        boot.append(abs(st.asymmetry_test(sim["alt"], sim["bench"],
                                          n_boot=200)["t"]) >= 2)
    rows.append({"world": tag, "naive rejects": np.mean(naive),
                 "bootstrap rejects": np.mean(boot)})
d = pd.DataFrame(rows).set_index("world")
fig, ax = plt.subplots(figsize=(10, 4.5))
d.mul(100).plot.bar(ax=ax, color=["#c0392b", "#2ea44f"])
ax.axhline(5, ls="--", color="k", lw=1, label="nominal 5% size")
ax.set_ylabel("share declaring asymmetry (%)"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=15, ha="right", fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Read the top row: that is the false-positive rate on a world
> with no asymmetry at all. Read the bottom row: that is the power. A test is only worth
> quoting when both are acceptable, and the naive one fails the first.
"""
        ),
        md(
            r"""

### 2.6 What a holder actually experienced
"""
        ),
        code(
            r"""
rows = []
for name, r in alts.items():
    c = st.capture_ratios(r, bench)
    dd = st.drawdown_comparison(px[name].dropna(), px[data.BENCHMARK].dropna())
    rows.append({"asset": name, **{k: c[k] for k in ("up_capture", "down_capture")},
                 **{k: dd[k] for k in ("max_dd", "bench_max_dd", "dd_ratio",
                                       "dd_at_bench_worst", "recovery_ratio")}})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(3).to_string())
fig, ax = plt.subplots(figsize=(10, 5))
for name in alts:
    s = px[name].dropna()
    ax.plot(s.index, (s / s.cummax() - 1) * 100, lw=1.0, alpha=0.75, label=name)
b = px[data.BENCHMARK].dropna()
ax.plot(b.index, (b / b.cummax() - 1) * 100, lw=2.2, color="k", label="Bitcoin")
ax.set_ylabel("drawdown (%)"); ax.legend(fontsize=7, ncol=2)
plt.show()
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
panel = st.panel_summary(alts, bench)
boot_ts = [st.asymmetry_test(r, bench, n_boot=500)["t"] for r in alts.values()]
caps = [st.capture_ratios(r, bench) for r in alts.values()]
pd.DataFrame({
    "altcoins": [len(alts)],
    "median up-beta": [panel["beta_up"].median()],
    "median down-beta": [panel["beta_down"].median()],
    "median difference": [panel["difference"].median()],
    "median naive t": [panel["naive_t"].median()],
    "median bootstrap t": [np.nanmedian(boot_ts)],
    "share with negative coskewness": [(panel["coskewness"] < 0).mean()],
    "median up capture": [np.median([c["up_capture"] for c in caps])],
    "median down capture": [np.median([c["down_capture"] for c in caps])],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 4 · Going further

- **Survivorship is the elephant.** Constructing the panel from a *historical* listing snapshot
  rather than a current one would probably change the sign of the conclusion, and it is the
  single most valuable thing anyone could add here.
- **Copulas.** Tail dependence has a proper machinery (Joe, Nelsen); a beta split is its crude
  ancestor. A *t*-copula's tail-dependence coefficient would answer the question directly and
  without the conditioning artefact.
- **Exceedance correlation profiles** in the Ang & Chen (2002) form, plotted against the
  normal benchmark across every threshold rather than at one decile.
- **Intraday.** Crypto crashes resolve in hours. Daily bars may simply be the wrong resolution
  for the question.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
