"""Generate the two narrative notebooks for Study 19 (Rubber-Band) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the **offline synthetic tape** — daily OHLC bars with a *baked-in*
IBS->next-day reversal — because the cached real ETF closes are git-ignored and the desk's reproducible
core must run with no network. The synthetic proves the machinery (the bounce is real by construction
and a random-walk null kills it), so the **real verdict** (a live ETF basket, quoted from
[`docs/results.md`](../docs/results.md) via `examples/verify.py`) is a fact about the market: a real
bounce that has *decayed* and lives inside the bid-ask spread. Both notebooks walk the SAME seven desk
beats (see ../../../METHODOLOGY.md).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))           # study root (rubber_band/ lives there)
sys.path.insert(0, os.path.abspath("../../.."))      # repo root, for quantlab
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from rubber_band import data, ibs, strategy, decompose, extension

# Offline synthetic OHLC: bars with a BAKED-IN IBS->next-day reversal (a close near the low today is
# followed by a positive return tomorrow). The NULL (kappa=0) is a random walk where IBS is noise.
# The real ETF-basket verdict is in ../docs/results.md.
ohlc,  truth = data.synthetic_ohlc(kappa=0.0035, seed=19)     # the reversal tape
ohlc0, _     = data.synthetic_ohlc(kappa=0.0,    seed=19)     # the random-walk null
print(f"{truth.n_bars} synthetic bars | baked reversal kappa={truth.kappa} | null kappa=0")
"""

# Real headline numbers (from docs/results.md via examples/verify.py; cells below EXECUTE on synthetic).
# 14 ETFs, 1993-2026, as-of 2026-06-01, fingerprint 3a6209745876.
R = dict(
    n_etf="14", lo="1993", hi="2026", fp="3a6209745876",
    ibs_slope="-0.0018", low_high="+20.8", gross_sr="+1.56", hac_t="+8.6",
    breakeven="8.1", net2="+1.18",
    sh1="+2.09", sh2="+0.88", last5="+0.40", last5_net3="-0.37",
    liq_sr="+0.50", liq_be="3.3", turn="170",
    ewh_be="17.8", spy_be="4.2",
)

BADGES = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Still alive?: Decayed](https://img.shields.io/badge/Still_alive%3F-Decayed-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Rubber-Band 🪀\n"
            "### A stock that closes near its low \"snaps back\" the next day — true? And can you still cash it?\n\n"
            + BADGES +
            "Here's a trader's-lore classic with real teeth. Look at where a stock closes *within* its "
            "day — near the high, or near the low. The folk rule (and a genuine academic effect): a bar "
            "that closes near its **low** tends to **bounce** the next session. The number that captures "
            "it is **Internal Bar Strength**, `IBS = (Close − Low) / (High − Low)` — 0 means closed dead "
            "on the low, 1 means dead on the high. Buy the 0s, sell the 1s.\n\n"
            "This is the desk's second idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§4.4), and it's a different *kind* of specimen from the last one: not a famous theory that "
            "fails, but a humble signal that's **genuinely real** — and then runs into two walls every "
            "short-term edge meets. We prove the machinery on a synthetic tape where we bake the bounce "
            "in (and a random-walk null where it can't exist), then point it at a basket of real ETFs.\n\n"
            "> 📓 **Plain-language layer.** The Newey–West *t*-stat, the break-even-cost maths and the "
            "decay curve are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** tape with a *baked-in* bounce, so the real-ETF numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does a low close really bounce? | ✅ **Yes — strongly.** A low-IBS day earns far more "
            f"tomorrow than a high-IBS day (real-ETF Newey–West *t* = **{R['hac_t']}**). |\n"
            "| Could you have traded it? | 🚫 **Not for free.** It trades **every day** "
            f"(~{R['turn']}×/yr turnover); the edge lives inside a few bps of bid-ask. |\n"
            "| Is it still alive today? | ⚪ **Barely.** It's **decayed** — gross Sharpe "
            f"**{R['sh1']} → {R['sh2']}** across the sample, and the last five years are negative net of "
            "3 bp. |\n\n"
            "> Desk shorthand: **Signal `REAL` · Tradability `MIRAGE` · Still alive? `DECAYED`** — a real "
            "bounce, competed away."
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Stated plainly: **where a bar closes inside its range predicts the next day.** Close near "
            "the low (the day's sellers exhausted themselves) and tomorrow tends to recover; close near "
            "the high (everyone already piled in) and tomorrow tends to give a little back. It's a "
            "short-horizon *mean-reversion* / liquidity-provision story — you're paid for stepping in "
            "when others are dumping. On our synthetic tape we baked exactly this in. Sort days into IBS "
            "buckets and look at the **next** day's return:"
        ),
        code(
            "rs = ibs.reversal_strength(ohlc)\n"
            "t = rs['table']\n"
            "fig, ax = plt.subplots()\n"
            "ax.bar(t.index, t['next_ret_bps'].values, color='#2ea44f', alpha=.85)\n"
            "ax.axhline(0, c='grey', lw=.8); ax.set_xlabel('IBS bucket (0 = closed near the low)')\n"
            "ax.set_ylabel('next-day return (bps)')\n"
            "ax.set_title(f\"Low closes bounce: next-day return falls as IBS rises (slope {rs['ibs_slope']:+.4f})\")\n"
            "plt.show()\n"
            "print(f\"low-IBS minus high-IBS next-day return: {rs['low_minus_high_bps']:+.1f} bps/day\")"
        ),
        md(
            "A clean downward staircase: the lower the close, the bigger the bounce. *That* is the edge — "
            "and it's the same shape on the real ETF tape."
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "A reliable one-day edge is the holy grail of short-term trading: high hit-rate, fast "
            "compounding, market-neutral if you long the lows and short the highs. If a low close really "
            "pays tomorrow, you'd trade it across hundreds of instruments and harvest a steady drip. The "
            "catch every such edge meets: *one-day* means you **re-trade constantly**, and constant "
            "trading meets the bid-ask spread — over and over."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Four checks, up front:\n\n"
            "1. **Is the bounce real?** Does a low IBS predict a higher next-day return, with a *t*-stat "
            "that says it isn't luck?\n"
            "2. **Does it survive costs?** The book turns over daily — what's the **break-even** slippage, "
            "and does it clear a real spread?\n"
            "3. **Is it still alive?** Compare the early years to the recent ones — has it decayed?\n"
            "4. **The null:** on a random-walk tape (no baked bounce) every test must come up empty.\n\n"
            "**Mirage line:** the gross edge is real but the **net-of-spread** edge — especially "
            "*recently* — is gone."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · The bounce is real — and the null is flat\n"
            "Same buckets, two synthetic tapes: the baked reversal and the random-walk null. The "
            "staircase must appear in one and vanish in the other."
        ),
        code(
            "a = ibs.reversal_strength(ohlc)['table']['next_ret_bps']\n"
            "b = ibs.reversal_strength(ohlc0)['table']['next_ret_bps']\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(a.index, a.values, 'o-', color='#2ea44f', label='reversal baked in')\n"
            "ax.plot(b.index, b.values, 's--', color='#8b949e', label='random-walk null')\n"
            "ax.axhline(0, c='grey', lw=.8); ax.set_xlabel('IBS bucket (0 = low)'); ax.set_ylabel('next-day bps'); ax.legend()\n"
            "ax.set_title('Tools work: a clear bounce with the effect, flat without it')\n"
            "plt.show()"
        ),

        md(
            "### 4b · Trade it, before costs\n"
            "Run the rule — long when yesterday closed near its low (`w = 1 − 2·IBS`), short near the "
            "high — and look at the equity curve, gross of costs."
        ),
        code(
            "g = strategy.timing_returns(ohlc, cost_bps=0.0)\n"
            "eq = (1+g).cumprod()\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(eq.index, eq.values, color='#2ea44f')\n"
            "ax.set_ylabel('growth of $1 (gross)'); ax.set_title(f\"Gross, the bounce looks glorious — Sharpe {strategy.summary(g)['sharpe']:+.2f}\")\n"
            "plt.show()\n"
            "print(f\"gross Sharpe {strategy.summary(g)['sharpe']:+.2f}, turnover {strategy.turnover_ann(ohlc):.0f}x/yr \"\n"
            "      f\"-- note that turnover: it trades essentially every day.\")"
        ),

        md(
            "### 4c · Now charge the spread\n"
            "Because it trades daily, even a tiny per-trade cost compounds into a big drag. Watch the "
            "Sharpe fall as we charge a few bps per unit traded — the break-even is *low*."
        ),
        code(
            "sweep = strategy.cost_sweep({'A': ohlc})\n"
            "be = decompose.breakeven_cost({'A': ohlc})\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(sweep.index, sweep['sharpe'].values, 'o-'); ax.axhline(0, ls=':', c='grey')\n"
            "ax.set_xlabel('cost per unit traded (bps)'); ax.set_ylabel('net Sharpe')\n"
            "ax.set_title(f\"The whole edge lives inside ~{be['breakeven_bps']:.0f} bps of cost\")\n"
            "plt.show()\n"
            "print(f\"break-even cost {be['breakeven_bps']:.1f} bps -- a real bid-ask spread is in this range.\")"
        ),

        md(
            "### 4d · The real tape — real, but fading\n"
            "On a basket of 14 real ETFs (quoted from [`../docs/results.md`](../docs/results.md)):\n\n"
            f"- The bounce is **real**: low-minus-high next-day spread **{R['low_high']} bps/day**, basket "
            f"gross Sharpe **{R['gross_sr']}**, Newey–West *t* = **{R['hac_t']}**.\n"
            f"- But it has **decayed**: gross Sharpe **{R['sh1']}** in the first half of the sample → "
            f"**{R['sh2']}** in the second → just **{R['last5']}** over the last five years.\n"
            f"- And **net of 3 bp over the last five years it is {R['last5_net3']}** — under water.\n"
            f"- The strongest bounce sits in the *thinnest* ETFs (break-evens like **{R['ewh_be']} bps** "
            f"for a country fund) — the ones with the *widest* real spreads. The liquid names you could "
            f"trade cheaply carry a small edge (Sharpe **{R['liq_sr']}**, break-even **{R['liq_be']} bps**)."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **The bounce is real** — *t* = {R['hac_t']} on the real basket, clean null on the "
            "synthetic.\n"
            f"- **But it's a museum piece** — decayed from Sharpe {R['sh1']} to {R['last5']}, and the "
            "recent edge is negative once you pay a realistic spread.\n\n"
            "> **Signal `REAL` · Tradability `MIRAGE` · Still alive? `DECAYED`.** A genuine microstructure "
            "edge, arbitraged away exactly as a well-known one should be."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "Two walls, both fatal:\n\n"
            f"- **It lives inside the spread.** ~{R['turn']}×/yr turnover means a few bps per trade "
            f"compounds into a wall of cost; the basket break-even is **{R['breakeven']} bps**, and net "
            f"of a tight 2 bp the recent edge is gone.\n"
            "- **The edge is where the spread is widest.** The biggest bounce is in thin country ETFs "
            "(break-evens of 10–18 bps) whose *real* spreads are just as wide — so the names that pay "
            "are the names you can't trade cheaply, and the liquid names barely pay at all.\n\n"
            "> Tradability **`MIRAGE`**; \"still alive?\" **`DECAYED`** — the worked complement "
            "([`../docs/extension.md`](../docs/extension.md)) shows 9 of 14 names clear their own assumed "
            "spread full-sample, but the clears sit in the thin country funds where the spread is itself "
            "an optimistic guess — and the recent net edge is negative."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **The realistic-spread test** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): charge each ETF its *own* plausible spread "
            "and count how many clear — 9 of 14 do over the full sample, but mostly the thin country "
            "funds whose assumed spread is an optimistic guess, and the recent-window edge is negative "
            "by a few bps.\n"
            "- **Intraday execution.** IBS is a close-to-close signal; entering on the close and exiting "
            "on the *open* (or mid) might dodge some cost — does any version survive at a real venue?\n"
            "- **Single names & longer history.** The bounce is strongest in volatile instruments; does "
            "it still live in single stocks pre-2010, and can you date when it died?\n\n"
            "PRs welcome — find the execution that keeps a sliver of it, or pin the year the crowd ate it."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Rubber-Band — a quantitative teardown 🔬\n"
            "### IBS→next-day reversal · Newey–West t-stat · break-even cost · the decay curve · the random-walk null\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its standard error.* The steelman is short-horizon mean reversion "
            "via Internal Bar Strength (Kakushadze–Serur §4.4; Connors & Alvarez): `IBS = (Close−Low)/"
            "(High−Low)`, low-IBS days bounce. We prove the apparatus on a synthetic tape with a baked "
            "reversal (and a random-walk null), then read the real verdict off a live ETF basket.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on the synthetic tape; the real ETF run is "
            "in [`../docs/results.md`](../docs/results.md) via `examples/verify.py`, sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — is the bounce real? | 🟢 `REAL` | Low-IBS days earn far more next session; "
            f"real-ETF basket gross Sharpe **{R['gross_sr']}**, Newey–West *t* = **{R['hac_t']}**; the "
            "random-walk null is flat. |\n"
            "| **Tradability** | 🔴 `MIRAGE` | ~"
            f"{R['turn']}×/yr turnover; break-even **{R['breakeven']} bps**; net of a tight 2 bp the "
            "*last-five-year* Sharpe is negative. The edge lives inside the spread. |\n"
            "| **Still alive?** | ⚪ `DECAYED` | Gross Sharpe "
            f"**{R['sh1']} → {R['sh2']}** (first → second half), **{R['last5']}** last 5y — competed away "
            "as it became well-known. |\n\n"
            "> **In one sentence:** a genuine one-day mean-reversion edge that is real at *t* > 8 gross, "
            "but turns over daily, lives inside the bid-ask spread, and has decayed to negative net "
            "returns in the recent sample.\n\n"
            "*(This notebook executes on the synthetic tape — the real ETF numbers that set the stamps "
            "are in [`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "$\\text{IBS}_t = (C_t - L_t)/(H_t - L_t) \\in [0,1]$. The claim is "
            "$\\mathbb{E}[r_{t+1}\\mid \\text{IBS}_t]$ **decreasing** in $\\text{IBS}_t$: a low close "
            "predicts a positive next-day return. The book trades $w_t = 1 - 2\\,\\text{IBS}_{t-1}$ "
            "(long the lows, short the highs), earning $w_t r_t$. The synthetic bakes "
            "$r_{t+1} = \\mu - \\kappa(\\text{IBS}_t - \\tfrac12) + \\sigma\\varepsilon$, so $\\kappa>0$ "
            "is the reversal and $\\kappa=0$ the null."
        ),
        code(
            "print(f\"baked kappa = {truth.kappa} (reversal strength); null kappa = 0\")\n"
            "print(f\"turnover {strategy.turnover_ann(ohlc):.0f}x/yr -- a one-day signal churns the whole book daily\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "A high-*t* one-day edge is enormously valuable *if* net of costs. The entire question "
            "collapses to one ratio: the **per-trade edge** versus the **per-trade spread**. With daily "
            "turnover, even a 1–2 bp spread is charged ~250×/yr, so a gross edge of tens of bps/day can "
            "still net to nothing. Beats 4–6 measure both sides and the trend in the gap over time."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Reversal** (`ibs.reversal_strength`): IBS-bucketed next-day returns + the OLS slope. "
            "Pre-registered: negative slope on the reversal tape, ≈0 on the null.\n"
            "2. **Significance** (`decompose.mean_tstat_hac`): Newey–West *t* on the timing stream.\n"
            "3. **Break-even** (`decompose.breakeven_cost`): the slippage that zeroes the net Sharpe.\n"
            "4. **Decay**: first-half vs second-half vs last-5y Sharpe (real tape).\n"
            "5. **Null:** every leg flat on the random-walk tape.\n\n"
            "**Mirage line:** the break-even is below a realistic spread, *and/or* the recent net edge is ≤ 0."
        ),

        md(
            "## Beat 4 · The teardown\n\n"
            "### 4a · The reversal, reversal tape vs null"
        ),
        code(
            "for label, o in [('reversal', ohlc), ('null', ohlc0)]:\n"
            "    rs = ibs.reversal_strength(o)\n"
            "    print(f\"{label:9s}: IBS slope {rs['ibs_slope']:+.4f} | low-minus-high {rs['low_minus_high_bps']:+.1f} bps/day | present={rs['reversal_present']}\")\n"
            "display(ibs.reversal_strength(ohlc)['table'].round(2))"
        ),

        md(
            "### 4b · Significance — Newey–West t on the timing stream\n"
            "HAC because daily strategy returns are autocorrelated."
        ),
        code(
            "g = strategy.timing_returns(ohlc, cost_bps=0.0); g0 = strategy.timing_returns(ohlc0, cost_bps=0.0)\n"
            "t = decompose.mean_tstat_hac(g); t0 = decompose.mean_tstat_hac(g0)\n"
            "bs = decompose.sharpe_bootstrap(g, n_boot=2000)\n"
            "print(f\"reversal: mean {t['mean_ann_pct']:+.1f}%/yr, HAC t = {t['t_stat']:+.1f}, \"\n"
            "      f\"bootstrap Sharpe {bs['sharpe']:+.2f} CI [{bs['ci_low']:+.2f},{bs['ci_high']:+.2f}]\")\n"
            "print(f\"null    : mean {t0['mean_ann_pct']:+.1f}%/yr, HAC t = {t0['t_stat']:+.1f}\")"
        ),
        md(
            "> 💡 **In plain words.** Gross, the bounce is unmistakable — a *t* well past any luck "
            "threshold and a bootstrap interval clear of zero. The null produces nothing. The signal is "
            "`REAL`; the fight is entirely about costs."
        ),

        md(
            "### 4c · Break-even cost\n"
            "The slippage at which the net Sharpe hits zero — small, because turnover is ~daily."
        ),
        code(
            "sweep = strategy.cost_sweep({'A': ohlc})\n"
            "be = decompose.breakeven_cost({'A': ohlc})\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(sweep.index, sweep['sharpe'].values, 'o-'); ax.axhline(0, ls=':', c='grey')\n"
            "ax.set_xlabel('cost per unit traded (bps)'); ax.set_ylabel('net Sharpe')\n"
            "ax.set_title(f\"break-even ~ {be['breakeven_bps']:.1f} bps\")\n"
            "plt.show()\n"
            "print(f\"synthetic break-even {be['breakeven_bps']:.1f} bps; on the real basket it is \"\n"
            f"      f\"{R['breakeven']} bps -- inside a real ETF spread, and the recent net edge is below zero.\")"
        ),

        md(
            "### 4d · The null collapses\n"
            "Random-walk tape: no reversal, no significance, zero break-even."
        ),
        code(
            "print(f\"null: reversal slope {ibs.reversal_strength(ohlc0)['ibs_slope']:+.4f} | \"\n"
            "      f\"timing Sharpe {strategy.summary(g0)['sharpe']:+.2f} | \"\n"
            "      f\"break-even {decompose.breakeven_cost({'A': ohlc0})['breakeven_bps']:.1f} bps\")\n"
            "print('nothing to find when nothing is baked in -- the apparatus measures the effect, not itself.')"
        ),

        md(
            "## Beat 5 · The verdict\n\n"
            f"- **Real bounce** (4a–4b): real-ETF basket *t* = {R['hac_t']}, clean null.\n"
            f"- **Cost-bound & decayed** (4c, real tape): break-even {R['breakeven']} bps; gross Sharpe "
            f"{R['sh1']} → {R['sh2']} → {R['last5']} (last 5y), net of 3 bp recently {R['last5_net3']}.\n\n"
            "> **Signal `REAL` · Tradability `MIRAGE` · Still alive? `DECAYED`.**"
        ),

        md(
            "## Beat 6 · Could you trade it?\n\n"
            "The usual killers, all landing:\n\n"
            f"- **Costs.** ~{R['turn']}×/yr turnover; break-even {R['breakeven']} bps; recent net edge ≤ 0 "
            "at a 2 bp spread.\n"
            "- **Adverse liquidity.** The bounce is biggest in the thinnest, widest-spread names — the "
            "edge and the spread you'd pay rise together.\n"
            "- **Decay.** A well-publicised microstructure edge, competed down over the sample.\n\n"
            "Tradability **`MIRAGE`**; \"still alive?\" **`DECAYED`**."
        ),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — the realistic-spread test\n"
            "Charge each ETF its *own* plausible round-trip spread (tight for SPY/QQQ, wide for thin "
            "country funds) and count how many names clear their break-even — and re-price the edge in "
            "the recent window."
        ),
        code(
            "be_basket = decompose.breakeven_cost({'A': ohlc})\n"
            "print(f\"synthetic single-name break-even {be_basket['breakeven_bps']:.1f} bps (illustrative).\")\n"
            "print('On the REAL basket (../docs/extension.md): 9 of 14 names clear their own assumed spread full-sample --')\n"
            "print('but the clears are the thin country funds where the spread is itself an optimistic guess, and')\n"
            f"print('the last-5y net Sharpe is negative by a few bps -- gross {R['last5']}, net@3bps {R['last5_net3']}.')"
        ),
        md(
            "**The result.** On the real basket the per-name table is decisive: the names with the "
            "biggest bounce (thin country ETFs, break-evens of 10–18 bps) are the ones with the *widest* "
            "real spreads, while the liquid names that *could* be traded tight carry a small edge and a "
            f"low break-even ({R['spy_be']} bps for SPY). On the assumed spreads, 9 of 14 names clear "
            "full-sample — but the clears are exactly where the spread is an optimistic guess and "
            "capacity is tiny; and the last-five-year edge is already negative net of a tight cost. The "
            "constraint a real desk faces — paying the spread, every day — is exactly the one that turns "
            "this `REAL` signal into a `MIRAGE`. Full run in [`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **Execution tricks.** Enter on close, exit on next open or VWAP — does dodging part of the "
            "round-trip rescue a sliver?\n"
            "- **Single stocks, longer history.** The effect is strongest in volatile names; date its "
            "decay on a pre-2010, all-stock sample.\n"
            "- **Regime conditioning.** Is the bounce concentrated in high-vol regimes (where it overlaps "
            "Study 16's storm-shy logic)?\n\n"
            "PRs welcome — keep a sliver alive through execution, or pin the year it died."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
