"""Notebook builder for Study 1006 — Most Stocks Lose.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Most Stocks Lose \U0001F3B2
### Except these ones. Which turned out to be the more useful finding.

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The best-known statistic in this corner of finance says most stocks lose to Treasury bills. We
went to check it on fifty large US companies and it **was not there** — the longer you held, the
*more* likely you were to win. Chasing down why produced a single inequality that says exactly
when the famous result holds and when it does not.

> \U0001F4D3 **This is the plain-language layer.** The drag decomposition, the odds table and
> the one-knob control are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does the typical *surviving large cap* beat cash? | Yes — more often the longer you hold. |
| So is the famous result wrong? | No. It is about a different population. |
| What separates the two? | One number: volatility versus √(2·(drift−cash)). |
| Does anything from it survive here? | Yes — the concentration of the gains. |

> This study was written expecting to confirm "most stocks lose". On this basket it **failed**,
> and chasing down why produced something better: the exact condition under which the result
> holds.
"""
        ),
        md(
            r"""

## 1 · Fifty stocks, thirty years
"""
        ),
        code(
            r"""
from moststocks import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2000]
R = px[cols].pct_change().dropna()
cash = (px[data.BILLS].pct_change().reindex(R.index).fillna(0.0)
        if data.BILLS in px.columns
        else pd.Series(np.full(len(R), 0.02/252), index=R.index))
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} sessions from "
      f"{R.index[0].date()} ({len(R)/252:.1f} years)")
print("All of them survived to 2026 -- the hardest possible place to find this effect.")
"""
        ),
        code(
            r"""
finals = np.expm1(np.log1p(R).sum())
cash_total = np.expm1(np.log1p(cash).sum())
s = finals.sort_values()
fig, ax = plt.subplots(figsize=(13, 5))
ax.bar(range(len(s)), s, color=["#c0392b" if v < cash_total else "#2ea44f" for v in s])
ax.axhline(cash_total, color="#1f6feb", lw=2.5, ls="--",
           label=f"cash: {cash_total:.1f}x")
ax.axhline(s.median(), color="#f0b429", lw=2, label=f"median stock: {s.median():.1f}x")
ax.axhline(s.mean(), color="#8b949e", lw=2, ls=":", label=f"mean stock: {s.mean():.1f}x")
ax.set_yscale("symlog"); ax.set_xticks(range(len(s)))
ax.set_xticklabels(s.index, rotation=90, fontsize=6)
ax.set_ylabel("what $1 became (log scale)"); ax.legend(fontsize=9)
plt.show()
print(f"median {s.median():.1f}x, mean {s.mean():.1f}x -- the mean is dragged up by a few")
"""
        ),
        md(
            r"""

## 2 · The result that did not appear
"""
        ),
        code(
            r"""
sw = st.horizon_sweep(R, cash, horizons_years=(0.25, 1, 3, 5, 10, 15))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(sw.index, sw["share_beat_cash"] * 100, "o-", lw=2.5, color="#c0392b")
axes[0].axhline(50, color="k", ls="--", lw=1.5, label="a coin flip")
axes[0].set_xlabel("years held"); axes[0].set_ylabel("% of holdings beating bills")
axes[0].legend(fontsize=8)
axes[1].plot(sw.index, sw["mean_return"] * 100, "o-", lw=2.5, color="#2ea44f",
             label="mean return")
axes[1].plot(sw.index, sw["median_return"] * 100, "s-", lw=2.5, color="#f0b429",
             label="median return")
axes[1].set_xlabel("years held"); axes[1].set_ylabel("return over the period (%)")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(sw[["share_beat_cash", "median_return", "mean_return", "skew"]].round(3).to_string())
"""
        ),
        md(
            r"""

The left panel was supposed to slope **down**. It slopes up: on these fifty survivors, holding
longer makes you *more* likely to beat bills, not less.

So the famous result is not a general property of stocks. What is it a property of?
"""
        ),
        md(
            r"""

## 2b · The one number that decides it
"""
        ),
        code(
            r"""
cond = st.median_beats_cash_condition(R, cash)
tab = cond["table"]
fig, ax = plt.subplots(figsize=(11, 5.5))
ax.scatter(tab["vol"] * 100, tab["breakeven_vol"] * 100, s=45, color="#1f6feb")
lim = [0, max(tab["breakeven_vol"].max(), tab["vol"].max()) * 105]
ax.plot(lim, lim, "k--", lw=2, label="the line: vol = sqrt(2*(drift - cash))")
ax.fill_between(lim, lim, lim[1], alpha=0.10, color="#2ea44f")
ax.fill_between(lim, 0, lim, alpha=0.10, color="#c0392b")
ax.annotate("median BEATS cash", (lim[1]*0.15, lim[1]*0.8), fontsize=11,
            color="#2ea44f")
ax.annotate("median LOSES to cash", (lim[1]*0.45, lim[1]*0.15), fontsize=11,
            color="#c0392b")
ax.set_xlabel("the volatility this name actually had (%)")
ax.set_ylabel("the volatility it could have tolerated (%)")
ax.legend(fontsize=9)
plt.show()
print(f"average drift {cond['mean_drift']:.1%}, cash {cond['cash_log_growth']:.1%}")
print(f"-> breakeven volatility {cond['mean_breakeven']:.0%}, "
      f"actual {cond['mean_vol']:.0%}")
print(f"only {cond['share_above_threshold']:.0%} of these names are on the wrong side")
"""
        ),
        md(
            r"""

Every point above the dashed line is a stock whose median holder wins. Almost all of them are.

The condition is simply **σ < √(2 × (drift − cash))**. Raise a company's volatility or lower its
drift and it crosses the line. Bessembinder's universe — small companies, and companies on their
way to being delisted — lives on the other side of it.
"""
        ),
        md(
            r"""

## 3 · Why: compounding is multiplication
"""
        ),
        code(
            r"""
rows = []
for vol in (0.01, 0.15, 0.30, 0.45, 0.60):
    sim = st.synthetic_cross_section(n_stocks=400, n_days=6000, drift=0.08, vol=vol)
    f = np.expm1(np.log1p(sim).sum())
    rows.append({"volatility": vol, "expected return": sim.mean().mean() * 252,
                 "median outcome": f.median(), "mean outcome": f.mean()})
d = pd.DataFrame(rows).set_index("volatility")
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(d.index * 100, d["median outcome"], "o-", lw=2.5, color="#f0b429",
        label="median stock")
ax.plot(d.index * 100, d["mean outcome"], "s-", lw=2.5, color="#2ea44f",
        label="mean stock")
ax.set_xlabel("volatility (%)"); ax.set_ylabel("what $1 became after ~24 years")
ax.legend(fontsize=9)
ax.set_title("every point has the SAME expected return", fontsize=10)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Nothing changes across that chart except volatility. The
> expected return is identical by construction. Volatility alone drives the median down and the
> mean up, by σ²/2 a year — no story about business models required.
"""
        ),
        md(
            r"""

## 4 · So how does the index win?
"""
        ),
        code(
            r"""
rec = st.index_reconciliation(R, cash)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
labels = ["cash", "median\nsingle name", "buy & hold\nthe basket",
          "rebalanced\nequal weight"]
vals = [rec["cash"], rec["median_single"], rec["buy_and_hold_basket"],
        rec["rebalanced_equal_weight"]]
axes[0].bar(labels, vals, color=["#1f6feb", "#c0392b", "#f0b429", "#2ea44f"])
axes[0].set_ylabel("what $1 became")
plt.setp(axes[0].get_xticklabels(), fontsize=8)
axes[1].bar(["average\nsingle stock", "the\nportfolio"],
            [rec["single_drag"] * 100, rec["portfolio_drag"] * 100],
            color=["#c0392b", "#2ea44f"])
axes[1].set_ylabel("compounding drag, % a year")
axes[1].set_title(f"diversification saves {rec['drag_saved']:.2%} a year", fontsize=10)
plt.tight_layout(); plt.show()
print(f"average single-name volatility {rec['single_vol']:.1%} -> drag "
      f"{rec['single_drag']:.2%}/yr")
print(f"portfolio volatility           {rec['portfolio_vol']:.1%} -> drag "
      f"{rec['portfolio_drag']:.2%}/yr")
"""
        ),
        md(
            r"""

The drag is proportional to variance. Diversification cuts variance. So an index of the same
fifty names pays a much smaller compounding penalty than any of them does individually — and
that saving, compounded over decades, is the entire gap.
"""
        ),
        md(
            r"""

## 5 · What this means if you hold a few names
"""
        ),
        code(
            r"""
odds = st.concentrated_portfolio_odds(R, cash, sizes=(1, 2, 3, 5, 10, 20, 50),
                                      horizon_years=10, n_draws=500)
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(odds.index, odds["share_beat_index"] * 100, "o-", lw=2.5, color="#c0392b",
        label="beat the index")
ax.plot(odds.index, odds["share_beat_cash"] * 100, "s-", lw=2.5, color="#1f6feb",
        label="beat cash")
ax.axhline(50, color="k", ls="--", lw=1.5)
ax.set_xlabel("number of stocks held")
ax.set_ylabel("% of 10-year periods (%)"); ax.legend(fontsize=9)
plt.show()
odds.round(3)
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Busted.** **Not on this basket, and the failure is the finding.** These 50 names all survived to 2026 — the exact opposite of Bessembinder's universe, which is every firm that ever listed and mostly delisted. Here **91%** of 10-year holding periods beat Treasury bills, against 67% at one year: the share beating cash **rises** with horizon, the reverse of the headline. So the claim is not a universal law about equities, and the useful question becomes what it takes to produce it. The mechanism is real and verified — measured drag across these names averaged 5.87% a year against a theoretical 5.90%, a correlation of 1.00 name by name — but the median compounds at roughly drift minus σ²/2, and these names' drift is large enough to absorb it. The condition is exact: the median beats cash while σ < sqrt(2·(drift − cash)). At an average drift of 16.8% against cash's 1.3%, that threshold is **55% volatility**, and these names average 33% — a headroom of 22%, with 2% of them over the line. Bessembinder's population — small caps and firms on their way to delisting — sits on the other side of that threshold. The synthetic control quantifies the survivorship half of the gap: removing simulated failures raises the median terminal wealth by 0.86×.

**Tradability: Mirage.** The implication is not "don't buy stocks", it is "don't buy few stocks", and the reconciliation makes that precise. Over the full sample the median single name returned 15.3× against cash's 0.6×, while the **rebalanced equal-weight basket of those same names** returned 414.2×. The index does not escape variance drag; it escapes most of it, because drag is proportional to σ² and diversification cuts the average single-name volatility of 33% to a portfolio 20% — worth 3.52% a year, compounding. Rebalancing is doing real work rather than housekeeping. Priced as odds over 10 years: a five-stock portfolio beat the index 43% of the time, a twenty-stock 51%, the full basket 14%. A concentrated book is not a slightly worse diversified one — it is a different bet, on the right tail, that most often loses.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **This is not an argument against stocks.** The mean is excellent and the index captures it.
  It is an argument against *few* stocks.
- **Rebalancing is not housekeeping.** It is the mechanism that keeps the portfolio's variance
  low, and variance is what the drag is charged on. A buy-and-hold basket slowly turns into a
  concentrated bet and loses that advantage.
- **The real cross-section is worse than this one.** These fifty all survived. Include the
  companies that did not and the median falls further — which is Bessembinder's actual sample.
- **If you concentrate anyway, know the price.** It is not extra risk in exchange for extra
  expected return. Expected return is unchanged; you are trading a likely small loss for an
  unlikely large gain.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Most Stocks Lose — a quantitative teardown \U0001F52C
### σ²/2 verified name by name · a rejected hypothesis · the breakeven inequality

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The pre-registered hypothesis in §1 was
**rejected** by this basket, and §3.2b is what replaced it: the median holder beats cash exactly
while σ < √(2·(drift − cash)). §3.1 verifies the σ²/2 identity first, and §3.8 reproduces the
whole Bessembinder result from a single parameter in a world where every stock has *identical*
expected return.

> ⚠️ **Not investment advice.** Survivorship runs *against* this finding and is quantified in
> §3.7 rather than footnoted. Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from moststocks import data, strategy as st

px = data.load_prices()
cols = [c for c in data.NAMES if c in px.columns and px[c].dropna().shape[0] > 2000]
R = px[cols].pct_change().dropna()
cash = (px[data.BILLS].pct_change().reindex(R.index).fillna(0.0)
        if data.BILLS in px.columns
        else pd.Series(np.full(len(R), 0.02/252), index=R.index))
print(f"as-of {data.AS_OF} | {len(cols)} names, {len(R):,} sessions from "
      f"{R.index[0].date()} ({len(R)/252:.1f} years)")
print("All of them survived to 2026 -- the hardest possible place to find this effect.")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Busted | **Not on this basket, and the failure is the finding.** These 50 names all survived to 2026 — the exact opposite of Bessembinder's universe, which is every firm that ever listed and mostly delisted. Here **91%** of 10-year holding periods beat Treasury bills, against 67% at one year: the share beating cash **rises** with horizon, the reverse of the headline. So the claim is not a universal law about equities, and the useful question becomes what it takes to produce it. The mechanism is real and verified — measured drag across these names averaged 5.87% a year against a theoretical 5.90%, a correlation of 1.00 name by name — but the median compounds at roughly drift minus σ²/2, and these names' drift is large enough to absorb it. The condition is exact: the median beats cash while σ < sqrt(2·(drift − cash)). At an average drift of 16.8% against cash's 1.3%, that threshold is **55% volatility**, and these names average 33% — a headroom of 22%, with 2% of them over the line. Bessembinder's population — small caps and firms on their way to delisting — sits on the other side of that threshold. The synthetic control quantifies the survivorship half of the gap: removing simulated failures raises the median terminal wealth by 0.86×. |
| **Tradability** | Mirage | The implication is not "don't buy stocks", it is "don't buy few stocks", and the reconciliation makes that precise. Over the full sample the median single name returned 15.3× against cash's 0.6×, while the **rebalanced equal-weight basket of those same names** returned 414.2×. The index does not escape variance drag; it escapes most of it, because drag is proportional to σ² and diversification cuts the average single-name volatility of 33% to a portfolio 20% — worth 3.52% a year, compounding. Rebalancing is doing real work rather than housekeeping. Priced as odds over 10 years: a five-stock portfolio beat the index 43% of the time, a twenty-stock 51%, the full basket 14%. A concentrated book is not a slightly worse diversified one — it is a different bet, on the right tail, that most often loses. |

> \U0001F4A1 **In plain words.** The median and the mean of a compounding distribution are
> different numbers, and the gap is σ²/2 per year.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

Stated as pre-registered, including the one that failed — which is where the study's actual
contribution came from.

- **H₁ (mechanism).** The arithmetic-minus-log-growth gap equals σ²/2 name by name, on real
  data.
- **H₂ (paradox) — ✗ REJECTED.** *Pre-registered as "the share of holding periods beating bills
  falls with horizon".* It **rises**, from roughly two-thirds at one year to nearly all at
  fifteen. On surviving large caps the drift outruns the drag comfortably. §3.2b replaces the
  hypothesis with the condition that governs it: the median beats cash exactly while
  σ < √(2·(drift − cash)).
- **H₃ (control).** In a world where every stock has *identical* expected return, raising
  volatility alone produces the effect — and setting volatility near zero eliminates it. This
  is what identifies the mechanism despite H₂ failing on this sample.
- **H₄ (concentration).** A small fraction of names accounts for the great majority of dollar
  wealth creation.
- **H₅ (reconciliation).** The rebalanced index beats its own median member, and the gap is
  accounted for by the difference in variance drag.
- **H₆ (survivorship).** Restricting to survivors *raises* the median, so this basket
  understates the effect.
"""
        ),
        md(
            r"""

## 2 · Data, and the direction of the bias
"""
        ),
        code(
            r"""
finals = np.expm1(np.log1p(R).sum())
cash_total = np.expm1(np.log1p(cash).sum())
print(pd.DataFrame({
    "terminal": finals, "ann. vol": R.std(ddof=1) * np.sqrt(252),
    "beat cash": finals > cash_total,
}).sort_values("terminal").round(3).to_string())
print()
print(f"cash over the same period: {cash_total:.2f}x")
print(f"{(finals > cash_total).mean():.0%} of these SURVIVORS beat it")
print("Bessembinder's universe includes every firm that ever listed. This one includes")
print("only firms that lasted 30 years. Section 3.7 measures what that is worth.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The mechanism, verified before anything is built on it
"""
        ),
        code(
            r"""
dt = st.drag_table(R)
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].scatter(dt["predicted_drag"] * 100, dt["measured_drag"] * 100, s=45,
                color="#1f6feb")
lim = [0, max(dt[["predicted_drag", "measured_drag"]].max()) * 105]
axes[0].plot(lim, lim, "k--", lw=1.5, label="measured = sigma^2/2")
axes[0].set_xlabel("predicted drag, sigma^2/2 (%)")
axes[0].set_ylabel("measured drag, arithmetic - geometric (%)")
axes[0].legend(fontsize=8)
axes[1].scatter(dt["vol"] * 100, dt["measured_drag"] * 100, s=45, color="#c0392b")
xs = np.linspace(dt["vol"].min(), dt["vol"].max(), 50)
axes[1].plot(xs * 100, xs ** 2 / 2 * 100, "k--", lw=1.5, label="sigma^2/2")
axes[1].set_xlabel("annualised volatility (%)")
axes[1].set_ylabel("measured drag (%)"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(f"correlation between measured and predicted: "
      f"{dt['measured_drag'].corr(dt['predicted_drag']):.4f}")
print(dt.sort_values("vol", ascending=False).head(8).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The points sit on the line. The gap between what a stock
> averages and what it compounds at is not a mystery to be explained — it is σ²/2, and it can
> be computed before looking at any outcome.
"""
        ),
        md(
            r"""

### 3.2 The horizon paradox
"""
        ),
        code(
            r"""
sw = st.horizon_sweep(R, cash, horizons_years=(0.25, 0.5, 1, 2, 3, 5, 7, 10, 15))
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
axes[0].plot(sw.index, sw["share_beat_cash"] * 100, "o-", lw=2.5, color="#c0392b")
axes[0].axhline(50, color="k", ls="--", lw=1.5)
axes[0].set_xlabel("years"); axes[0].set_ylabel("% beating bills")
axes[1].plot(sw.index, sw["median_return"] * 100, "s-", lw=2, color="#f0b429",
             label="median")
axes[1].plot(sw.index, sw["mean_return"] * 100, "o-", lw=2, color="#2ea44f",
             label="mean")
axes[1].set_xlabel("years"); axes[1].set_ylabel("return (%)"); axes[1].legend(fontsize=8)
axes[1].set_yscale("symlog")
axes[2].plot(sw.index, sw["skew"], "o-", lw=2.5, color="#1f6feb")
axes[2].set_xlabel("years"); axes[2].set_ylabel("skew of log outcomes")
plt.tight_layout(); plt.show()
print(sw[["n", "share_beat_cash", "share_lost_money", "median_return", "mean_return",
          "skew"]].round(4).to_string())
"""
        ),
        md(
            r"""

### 3.2b The breakeven condition, and where each name sits
"""
        ),
        code(
            r"""
cond = st.median_beats_cash_condition(R, cash)
tab = cond["table"].sort_values("headroom")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].scatter(tab["vol"] * 100, tab["drift"] * 100, s=50, color="#1f6feb")
vols = np.linspace(0.05, max(tab["vol"].max() * 1.2, 0.7), 120)
axes[0].plot(vols * 100, (cond["cash_log_growth"] + vols ** 2 / 2) * 100, "k--", lw=2,
             label="drift = cash + sigma^2/2")
axes[0].fill_between(vols * 100, (cond["cash_log_growth"] + vols ** 2 / 2) * 100,
                     max(tab["drift"].max() * 120, 40), alpha=0.10, color="#2ea44f")
axes[0].set_xlabel("annualised volatility (%)")
axes[0].set_ylabel("arithmetic drift (%)"); axes[0].legend(fontsize=8)
axes[0].set_title("above the curve: the median holder wins", fontsize=10)
colors = ["#c0392b" if hh < 0 else "#2ea44f" for hh in tab["headroom"]]
axes[1].barh(range(len(tab)), tab["headroom"] * 100, color=colors)
axes[1].axvline(0, color="k", lw=1.5)
axes[1].set_yticks(range(len(tab)))
axes[1].set_yticklabels(tab.index, fontsize=5)
axes[1].set_xlabel("headroom: tolerable volatility minus actual (pp)")
plt.tight_layout(); plt.show()
print({k: round(v, 4) for k, v in cond.items() if k != "table"})
print(tab.head(8).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The curve in the left panel is the whole result. A stock is
> above it — median holder wins — when its drift exceeds cash plus half its variance. The
> quadratic is why volatility matters so disproportionately: doubling σ quadruples the drift you
> need to stay above the line. Bessembinder's small caps and delisting candidates fail on both
> terms at once.
"""
        ),
        md(
            r"""

### 3.3 Dollar wealth concentration
"""
        ),
        code(
            r"""
wc = st.wealth_concentration(R, cash)
ranked = wc["ranked"]
cum = ranked.cumsum() / ranked.sum()
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(np.arange(1, len(cum) + 1) / len(cum) * 100, cum * 100, lw=2.5,
             color="#1f6feb")
axes[0].plot([0, 100], [0, 100], "k--", lw=1.5, label="if all names contributed equally")
for p in (10, 25, 50):
    k = max(int(np.ceil(len(ranked) * p / 100)), 1)
    axes[0].annotate(f"top {p}%: {cum.iloc[k-1]:.0%}", (p, cum.iloc[k-1] * 100),
                     fontsize=8, xytext=(6, -10), textcoords="offset points")
axes[0].set_xlabel("% of names, best first")
axes[0].set_ylabel("% of total excess wealth over cash"); axes[0].legend(fontsize=8)
axes[1].bar(range(len(ranked)), ranked,
            color=["#2ea44f" if v > 0 else "#c0392b" for v in ranked])
axes[1].set_xticks(range(len(ranked)))
axes[1].set_xticklabels(ranked.index, rotation=90, fontsize=5)
axes[1].set_ylabel("excess wealth created over cash ($ per $1 staked)")
plt.tight_layout(); plt.show()
print({k: (round(v, 4) if isinstance(v, (int, float)) else v)
       for k, v in wc.items() if k != "ranked"})
"""
        ),
        md(
            r"""

### 3.4 The reconciliation, decomposed
"""
        ),
        code(
            r"""
rec = st.index_reconciliation(R, cash)
years = len(R) / 252
rows = []
for k in (1, 2, 5, 10, 20, 50):
    sub = R.iloc[:, :min(k, R.shape[1])]
    eq = sub.mean(axis=1)
    rows.append({"n": min(k, R.shape[1]),
                 "portfolio vol": eq.std(ddof=1) * np.sqrt(252),
                 "drag": st.variance_drag(0, eq.std(ddof=1) * np.sqrt(252))})
d = pd.DataFrame(rows).set_index("n")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(d.index, d["portfolio vol"] * 100, "o-", lw=2.5, color="#1f6feb")
axes[0].set_xlabel("stocks in the portfolio")
axes[0].set_ylabel("portfolio volatility (%)")
axes[1].plot(d.index, d["drag"] * 100, "o-", lw=2.5, color="#c0392b")
axes[1].set_xlabel("stocks in the portfolio")
axes[1].set_ylabel("compounding drag paid, % a year")
plt.tight_layout(); plt.show()
print(pd.DataFrame({
    "cash": [rec["cash"]], "median single name": [rec["median_single"]],
    "buy and hold basket": [rec["buy_and_hold_basket"]],
    "rebalanced equal weight": [rec["rebalanced_equal_weight"]],
    "single-name vol": [rec["single_vol"]], "portfolio vol": [rec["portfolio_vol"]],
    "drag saved per year": [rec["drag_saved"]],
    "compounded over the sample": [np.expm1(np.log1p(rec["drag_saved"]) * years)],
}).T.rename(columns={0: "value"}).round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Both panels are the same curve, because drag is variance over
> two. Whatever diversification does to the left-hand chart, it does quadratically to the
> right-hand one — which is why the first few names matter so much.
"""
        ),
        md(
            r"""

### 3.5 Rebalancing, and what happens without it
"""
        ),
        code(
            r"""
bh = st.buy_and_hold_index(R)
fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True,
                         gridspec_kw={"height_ratios": [2, 1]})
axes[0].plot(bh.index, bh["buy_and_hold"], lw=2, color="#f0b429", label="buy and hold")
axes[0].plot(bh.index, bh["rebalanced"], lw=2, color="#2ea44f", label="rebalanced")
axes[0].set_yscale("log"); axes[0].set_ylabel("growth of $1 (log)")
axes[0].legend(fontsize=9)
axes[1].plot(bh.index, bh["effective_n"], lw=2, color="#c0392b")
axes[1].set_ylabel("effective number of holdings")
axes[1].set_title("the buy-and-hold basket concentrates itself", fontsize=9)
plt.tight_layout(); plt.show()
print(bh.iloc[[0, len(bh)//2, -1]].round(4).to_string())
"""
        ),
        md(
            r"""

### 3.6 The odds for a concentrated book
"""
        ),
        code(
            r"""
rows = []
for hy in (3, 5, 10):
    o = st.concentrated_portfolio_odds(R, cash, sizes=(1, 2, 3, 5, 10, 20, 50),
                                       horizon_years=hy, n_draws=400)
    for n, r in o.iterrows():
        rows.append({"horizon": hy, "n_stocks": n, **r.to_dict()})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for hy, g in d.groupby("horizon"):
    axes[0].plot(g["n_stocks"], g["share_beat_index"] * 100, "o-", lw=2,
                 label=f"{hy} years")
    axes[1].plot(g["n_stocks"], (g["p90"] - g["p10"]) * 100, "o-", lw=2,
                 label=f"{hy} years")
axes[0].axhline(50, color="k", ls="--", lw=1.5)
axes[0].set_xlabel("stocks held"); axes[0].set_ylabel("% beating the index")
axes[0].legend(fontsize=8)
axes[1].set_xlabel("stocks held")
axes[1].set_ylabel("10th-to-90th spread of outcomes (pp)")
axes[1].set_yscale("log"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.pivot(index="n_stocks", columns="horizon",
              values="share_beat_index").round(3).to_string())
"""
        ),
        md(
            r"""

### 3.7 Survivorship, quantified
"""
        ),
        code(
            r"""
rows = []
for vol in (0.25, 0.35, 0.45, 0.55, 0.65):
    for cut in (-0.60, -0.80, -0.90):
        s = st.survivorship_experiment(n_stocks=500, n_days=6000, vol=vol,
                                       delist_at=cut)
        rows.append({"vol": vol, "delist_at": cut, **s})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for cut, g in d.groupby("delist_at"):
    axes[0].plot(g["vol"] * 100, g["delist_rate"] * 100, "o-", lw=2,
                 label=f"delist below {cut:.0%}")
    axes[1].plot(g["vol"] * 100, g["bias"], "o-", lw=2, label=f"delist below {cut:.0%}")
axes[0].set_xlabel("volatility (%)"); axes[0].set_ylabel("% delisted")
axes[0].legend(fontsize=8)
axes[1].axhline(0, color="k", lw=1.5)
axes[1].set_xlabel("volatility (%)")
axes[1].set_ylabel("how much survivorship RAISES the median (x)")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.round(4).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Every bar is positive, so restricting to survivors flatters the
> median. This study's basket is all survivors, and it *still* shows the effect — which is a
> stronger position than replicating the number on a survivorship-free universe would be.
"""
        ),
        md(
            r"""

### 3.8 The control — the whole result from one parameter
"""
        ),
        code(
            r"""
rows = []
for vol in (0.01, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70):
    sim = st.synthetic_cross_section(n_stocks=500, n_days=6000, drift=0.08, vol=vol)
    f = np.expm1(np.log1p(sim).sum())
    simcash = pd.Series(np.full(len(sim), 0.02 / 252), index=sim.index)
    sws = st.horizon_sweep(sim, simcash, horizons_years=(10,), step=252)
    rows.append({"vol": vol, "arith": sim.mean().mean() * 252,
                 "median": f.median(), "mean": f.mean(),
                 "share_beat": sws.loc[10, "share_beat_cash"],
                 "predicted_drag": st.variance_drag(0, vol)})
d = pd.DataFrame(rows).set_index("vol")
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
axes[0].plot(d.index * 100, d["arith"] * 100, "o-", lw=2.5, color="#2ea44f")
axes[0].set_ylim(0, 16)
axes[0].set_xlabel("volatility (%)"); axes[0].set_ylabel("expected return (%)")
axes[0].set_title("held constant by construction", fontsize=10)
axes[1].plot(d.index * 100, d["median"], "o-", lw=2.5, color="#f0b429", label="median")
axes[1].plot(d.index * 100, d["mean"], "s-", lw=2.5, color="#2ea44f", label="mean")
axes[1].set_yscale("log")
axes[1].set_xlabel("volatility (%)"); axes[1].set_ylabel("terminal wealth")
axes[1].legend(fontsize=8)
axes[2].plot(d.index * 100, d["share_beat"] * 100, "o-", lw=2.5, color="#c0392b")
axes[2].axhline(50, color="k", ls="--", lw=1.5)
axes[2].set_xlabel("volatility (%)")
axes[2].set_ylabel("% of 10-year holdings beating cash")
plt.tight_layout(); plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The left panel is flat: expected return never changes. The
> right panel falls from nearly 100% to well under half. Bessembinder's headline needs no
> economics at all — only compounding and a volatility number.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
dt = st.drag_table(R)
sw = st.horizon_sweep(R, cash, horizons_years=(1, 10))
wc = st.wealth_concentration(R, cash)
rec = st.index_reconciliation(R, cash)
odds = st.concentrated_portfolio_odds(R, cash, sizes=(5, 20, 50), horizon_years=10,
                                      n_draws=400)
pd.DataFrame({
    "names (all survivors)": [R.shape[1]],
    "measured drag, mean": [dt["measured_drag"].mean()],
    "predicted drag, sigma^2/2": [dt["predicted_drag"].mean()],
    "% of 1-year holdings beating bills": [sw.loc[1, "share_beat_cash"]],
    "% of 10-year holdings beating bills": [sw.loc[10, "share_beat_cash"]],
    "mean return, 1 year": [sw.loc[1, "mean_return"]],
    "mean return, 10 years": [sw.loc[10, "mean_return"]],
    "top 10% of names' share of excess wealth": [wc["top_10pct_share"]],
    "names that lost money outright": [wc["share_lost_money"]],
    "median single name": [rec["median_single"]],
    "rebalanced equal weight": [rec["rebalanced_equal_weight"]],
    "drag saved by diversifying, per year": [rec["drag_saved"]],
    "5-stock book beats the index": [odds.loc[5, "share_beat_index"]],
    "50-stock book beats the index": [odds.loc[50, "share_beat_index"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Run it on a survivorship-free universe.** CRSP with delisted names is the proper sample;
  §3.7 predicts the effect gets larger, and by roughly how much.
- **Fernholz's stochastic portfolio theory** formalises §3.4: the excess growth rate of a
  rebalanced portfolio over its constituents is exactly half the difference between the average
  constituent variance and the portfolio variance. Deriving it and checking it numerically here
  would be a clean addition.
- **Barberis & Huang (2008) is the counterargument worth taking seriously.** An investor with
  probability weighting may *rationally* prefer the median-losing, tail-winning bet. The finding
  is arithmetic; whether it is a mistake to accept it is a preference question.
- **The size dimension.** Small caps have far higher σ and therefore far more drag, which is
  part of why the small-cap premium is so much weaker in geometric terms than in arithmetic
  ones — a comparison **1004** sets up and this study could complete.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
