"""Headline run for Study 12 (Paper-Prophet) — the numbers behind the verdict.

Runs the article's ARIMA(1,0,1)+GARCH(1,1) stack walk-forward over the full cached SPY tape,
**cold** (refit from scratch every day, exactly as the thread's code does), parallelised across
processes so ~8,000 daily fits finish in minutes. Then it decomposes the result into the
*forecast* (ARIMA direction) and the *sizing* (GARCH vol-targeting), charges costs, and writes a
reproducible docs/results.md pinned by as-of date and a content fingerprint.

    ../../.venv/Scripts/python.exe examples/verify.py
"""

import os
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_ROOT = os.path.abspath(os.path.join(_STUDY, "..", ".."))
sys.path.insert(0, _STUDY)
sys.path.insert(0, _ROOT)
# Point the data layer at the desk's repo-root cache regardless of CWD.
os.environ.setdefault("OVERNIGHT_CACHE", os.path.join(_ROOT, "_cache"))

from paper_prophet import data, decompose          # noqa: E402
from paper_prophet.stack import WalkForward, generate_signals_parallel  # noqa: E402
from quantlab.repro import DEFAULT_AS_OF, fingerprint      # noqa: E402

pd.set_option("display.width", 200)

OUT = os.path.join(_STUDY, "docs", "results.md")
ASOF = DEFAULT_AS_OF


def main():
    prices = data.load_spy(asof=ASOF)["Close"]
    rets = data.log_returns(prices)
    fp = fingerprint(prices.to_frame("Close"), round_dp=4)
    print(f"SPY: {len(prices)} closes {prices.index.min().date()}->{prices.index.max().date()} "
          f"as-of {ASOF} fingerprint={fp}")

    stat = data.stationarity_check(prices)
    print(f"ADF: price p={stat['price_adf_p']:.3f} (unit root), "
          f"returns p={stat['returns_adf_p']:.4f} (stationary)")

    # The walk-forward (~8k cold fits) is the only slow part. Cache it keyed by the data
    # fingerprint so re-running the (instant) decomposition never recomputes it. Pass --refit to
    # force a fresh fit.
    cache = os.path.join(_STUDY, "out", f"walkforward_{fp}.parquet")
    os.makedirs(os.path.dirname(cache), exist_ok=True)
    if os.path.exists(cache) and "--refit" not in sys.argv:
        print(f"loading cached walk-forward {cache}")
        wf = WalkForward(frame=pd.read_parquet(cache), lookback=252, constant_long=False)
    else:
        print("walk-forward (cold, parallel) over the full tape — this takes a few minutes...")
        wf = generate_signals_parallel(rets)
        wf.frame.to_parquet(cache)
    print(f"graded {len(wf.frame)} days")

    de = decompose.directional_edge(wf)
    sd = decompose.sharpe_decomposition(wf)
    ab = decompose.alpha_vs_beta(wf)
    cs = decompose.cost_sweep(wf)
    wr = decompose.win_rate(wf)
    infl = decompose.in_sample_inflation(rets, wf)

    print("\n[directional edge]", de)
    print("[sharpe decomposition]", sd)
    print("[alpha vs beta]", ab)
    print("[win rate]", wr)
    print("[in-sample inflation]", infl)
    print("[cost sweep]\n", cs.round(4).to_string())

    _write_results(OUT, prices, fp, stat, de, sd, ab, cs, wr, infl)
    print(f"\nwrote {OUT}")


def _write_results(path, prices, fp, stat, de, sd, ab, cs, wr, infl):
    lo, hi = prices.index.min().date(), prices.index.max().date()
    inc_lo, inc_hi = sd["arima_increment_ci"]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"""# Results — Study 12 (Paper-Prophet) on the SPY tape

*Generated by [`examples/verify.py`](../examples/verify.py). The article's ARIMA(1,0,1)+GARCH(1,1)
stack, ported faithfully and run **cold** (refit every day) walk-forward over cached daily SPY
(split-only). As-of **{ASOF}**; sample **{len(prices):,}** closes {lo} → {hi}; fingerprint
**`{fp}`**. Returns in percent (the article's scale).*

## Stationarity — the one thing the article gets right
```
ADF p-value, price levels : {stat['price_adf_p']:.3f}   (> 0.05 -> unit root, do NOT model)
ADF p-value, log-returns  : {stat['returns_adf_p']:.4f}   (< 0.05 -> stationary, model THIS)
```
Prices have a unit root; returns don't. We model returns, as the article correctly insists.

## Signal — is the ARIMA direction better than a coin?
```
walk-forward hit-rate     : {de['hit_rate']*100:.2f}%   (n = {de['n_graded']:,} graded days)
directional edge / day    : {de['dir_edge_bps_per_day']:+.3f} bp   (HAC t = {de['dir_edge_hac_t']:+.2f})
```
The one-step direction is a **coin flip**: hit-rate ≈ 50%, HAC t well inside ±2.

## The Sharpe is the sizing, not the forecast
```
Sharpe — full stack (sign x size)        : {sd['sharpe_stack']:+.3f}
Sharpe — constant-long x same GARCH size : {sd['sharpe_voltgt']:+.3f}   (pure vol-targeting)
Sharpe — forecast, flat size (sign only) : {sd['sharpe_flat_forecast']:+.3f}
Sharpe — plain buy & hold                : {sd['sharpe_buyhold']:+.3f}
vol-targeting reproduces                 : {sd['voltgt_reproduces_frac']*100:.0f}% of the stack Sharpe
ARIMA increment (stack - vol-targeting)  : {sd['arima_increment_sharpe']:+.3f}  (boot CI [{inc_lo:+.2f}, {inc_hi:+.2f}], {sd['arima_increment_frac_negative']*100:.0f}% neg)
```

## Alpha vs (managed) beta
```
stack ~ a + b * buy&hold   : beta = {ab['beta_market']:.3f}, alpha = {ab['alpha_vs_market_pct_day']:+.4f}%/day, R2 = {ab['r2_market']:.3f}
stack ~ a + b * vol-managed : beta = {ab['beta_voltgt']:.3f}, alpha = {ab['alpha_vs_voltgt_pct_day']:+.4f}%/day, R2 = {ab['r2_voltgt']:.3f}
```
Against the vol-managed-SPY factor the stack's alpha collapses — it *is* the vol-targeting factor.

## "Win every single trade"?
```
per-day win rate          : {wr['win_rate']*100:.2f}%   (n_active = {wr['n_active']:,})
```
A coin flip. The headline is mathematically impossible and empirically ~50%.

## Costs — the ARIMA increment net of its own turnover
```
{cs.round(4).to_string()}
```

## In-sample inflation — the mistake the article warns about, quantified
```
hit-rate, in-sample fit-then-grade : {infl['hit_rate_in_sample']*100:.2f}%
hit-rate, honest walk-forward      : {infl['hit_rate_walk_forward']*100:.2f}%
inflation handed to a cheater      : {infl['inflation_pp']:+.2f} pp
```
""")


if __name__ == "__main__":
    main()
