"""Notebook builder for Study 1007 — Time Does Not Diversify.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Time Does Not Diversify \U000023F3
### Two charts. Both accurate. Opposite conclusions.

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

Your adviser has a chart showing equity risk shrinking as the horizon lengthens. Paul Samuelson
had one showing it growing. Neither is wrong — they are plotting different things and calling
both of them "risk".

> \U0001F4D3 **This is the plain-language layer.** The variance ratios, the bootstrap null and
> Samuelson's theorem checked numerically are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does annualised return dispersion shrink with time? | Yes. |
| Does the range of possible outcomes shrink? | No — it grows. |
| Is the shrinking part evidence about equities? | No. It is division by √T. |
| Should your horizon change your allocation? | Not through this argument. |
"""
        ),
        md(
            r"""

## 1 · The chart your adviser shows you
"""
        ),
        code(
            r"""
from timediv import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
cash = (px[data.BILLS].pct_change().reindex(r.index).fillna(0.0)
        if data.BILLS in px.columns
        else pd.Series(np.full(len(r), 0.02/252), index=r.index))
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"which is {len(r)/252/30:.1f} independent 30-year periods. Bear that in mind.")
"""
        ),
        code(
            r"""
m = st.horizon_metrics(r, cash, (1, 2, 3, 5, 7, 10, 15, 20, 25, 30))
fig, ax = plt.subplots(figsize=(11, 5))
ax.fill_between(m.index, m["annualised_p05"] * 100, m["annualised_p95"] * 100,
                alpha=0.25, color="#1f6feb", label="5th-95th percentile")
ax.plot(m.index, m["annualised_mean"] * 100, "o-", lw=2.5, color="#1f6feb")
ax.axhline(0, color="k", lw=1.5)
ax.set_xlabel("years held"); ax.set_ylabel("ANNUALISED return (%)")
ax.set_title("Equity risk shrinks with horizon", fontsize=11)
ax.legend(fontsize=9)
plt.show()
print(m[["annualised_sd", "annualised_p05", "annualised_p95"]].round(4).to_string())
"""
        ),
        md(
            r"""

Perfectly true. The average annual return over twenty years varies far less than over one.

## 2 · The chart Samuelson shows you
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 5))
ax.fill_between(m.index, m["terminal_p05"], m["terminal_p95"], alpha=0.25,
                color="#c0392b", label="5th-95th percentile")
ax.plot(m.index, m["terminal_median"], "o-", lw=2.5, color="#c0392b")
ax.axhline(1, color="k", lw=1.5)
ax.set_yscale("log")
ax.set_xlabel("years held"); ax.set_ylabel("what $1 became (log scale)")
ax.set_title("Equity risk grows with horizon", fontsize=11)
ax.legend(fontsize=9)
plt.show()
print(m[["terminal_median", "terminal_p05", "terminal_p95", "terminal_sd"]].round(3)
      .to_string())
"""
        ),
        md(
            r"""

Also perfectly true, and computed from the *same windows*. The first chart divides by the number
of years; the second does not. That is the entire disagreement.
"""
        ),
        md(
            r"""

## 3 · Which chart is telling you something about stocks?
"""
        ),
        code(
            r"""
sim = st.synthetic_iid(n_days=len(r), drift=0.10, vol=0.18)
simc = pd.Series(np.zeros(len(sim)), index=sim.index)
ms = st.horizon_metrics(sim, simc, (1, 2, 3, 5, 7, 10, 15, 20))
fig, ax = plt.subplots(figsize=(11, 5))
ax.loglog(m.index, m["annualised_sd"] * 100, "o-", lw=2.5, color="#1f6feb",
          label="real market")
ax.loglog(ms.index, ms["annualised_sd"] * 100, "s-", lw=2.5, color="#8b949e",
          label="a coin-flip market (cannot mean-revert)")
base = m["annualised_sd"].iloc[0] * 100
ax.loglog(m.index, base / np.sqrt(m.index.to_numpy()), "k--", lw=2,
          label="pure arithmetic: 1/sqrt(T)")
ax.set_xlabel("years held (log)"); ax.set_ylabel("annualised dispersion, % (log)")
ax.legend(fontsize=9)
plt.show()
e = st.excess_convergence(m)
print(f"real market converges at a log-log slope of {e['slope']:.3f}")
print(f"pure arithmetic would give exactly -0.500")
"""
        ),
        md(
            r"""

The grey line is a market of pure coin flips where a bad decade tells you *nothing* about the
next one. It converges just as neatly. So the convergence is not evidence that stocks are safe
in the long run — it is what dividing by T does.
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The next notebook tests whether the real line falls
> *significantly* faster than −0.5, using variance ratios and a block bootstrap that destroys
> multi-year dependence while preserving volatility clustering.
"""
        ),
        md(
            r"""

## 4 · The bit that is genuinely true
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(m.index, m["shortfall_vs_cash"] * 100, "o-", lw=2.5, color="#2ea44f")
axes[0].set_xlabel("years held")
axes[0].set_ylabel("% of windows losing to cash")
axes[0].set_title("less LIKELY to lose", fontsize=10)
axes[1].plot(m.index, m["worst_terminal"], "o-", lw=2.5, color="#c0392b")
axes[1].axhline(1, color="k", ls="--", lw=1.5, label="break even")
axes[1].set_xlabel("years held")
axes[1].set_ylabel("worst outcome observed ($ per $1)")
axes[1].set_title("but the spread of outcomes is wider", fontsize=10)
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(m[["shortfall_vs_cash", "shortfall_vs_zero", "worst_terminal",
         "terminal_sd"]].round(3).to_string())
"""
        ),
        md(
            r"""

Losing becomes *less likely* over long horizons — that part is real and is not just arithmetic.
But the distribution of what you end up with keeps widening. Fewer bad outcomes, and the bad
ones that remain matter more.
"""
        ),
        md(
            r"""

## 5 · So should your horizon change your portfolio?
"""
        ),
        code(
            r"""
ow = st.optimal_weight_by_horizon(r, cash, years_grid=(1, 3, 5, 10, 15, 20),
                                  gammas=(2.0, 3.0, 5.0, 10.0))
piv = ow.pivot(index="years", columns="gamma", values="optimal_weight")
fig, ax = plt.subplots(figsize=(10, 5))
for g in piv.columns:
    ax.plot(piv.index, piv[g] * 100, "o-", lw=2, label=f"risk aversion {g:g}")
ax.set_ylim(-5, 105)
ax.set_xlabel("investment horizon (years)")
ax.set_ylabel("best equity weight (%)"); ax.legend(fontsize=9)
ax.set_title("the lines are flat, which is Samuelson's 1969 result", fontsize=10)
plt.show()
print(piv.round(3).to_string())
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Weak.** Both sides of this argument are quoting true statements about the same windows. On SPY over 33 years: the standard deviation of the **annualised** return falls from 16.7% at one year to 1.6% at 20 — the adviser's chart, and it is correct. Over the same windows the standard deviation of **terminal wealth** rises from 0.17× to 1.48× — Samuelson's point, also correct. The question is whether the first is *more* than arithmetic. Under i.i.d. returns annualised dispersion must fall like 1/√T, a log-log slope of exactly −0.5. Measured here: **-1.003** (±0.147). A block bootstrap that destroys multi-year mean reversion while keeping the short-run dynamics puts the null slope at -0.673 with a 5th percentile of -0.889, so the observed value is inside it (p = 0.660). Lo-MacKinlay variance ratios agree: at 756 days VR = 0.913 with z = -0.20. The convergence is not merely the √T in the denominator.

**Tradability: Mirage.** Which leaves the decision, and there the answer is cleaner than the debate. Maximising CRRA certainty equivalent over the real windows, the optimal equity weight moved by at most **68% across horizons from one to 20 years** — at γ = 3 it went from 98% to 100%. Samuelson's 1969 theorem, that horizon drops out under CRRA and i.i.d. returns, survives contact with the data. The practical reading is not "ignore your horizon" but something more precise: horizon should enter an allocation through **the things that genuinely depend on it** — the size and certainty of future contributions, the flexibility to defer spending, the ability to keep earning through a drawdown — and not through a belief that equities become less risky if you wait. The shortfall probability does fall, from 20% at one year to 0% at 20, but the worst outcome gets worse: the poorest 20-year window ended at 2.52× against 0.55× for the poorest single year. Less likely, more costly, which is precisely the trade the glide-path argument leaves out.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Horizon still matters — for other reasons.** A thirty-year-old can keep earning through a
  crash, keep contributing at low prices, and defer spending. Those are genuine and they have
  nothing to do with equities becoming less risky.
- **Bodie's test is the neatest.** If stocks really got safer with time, insuring against a
  shortfall would get *cheaper* the longer the term. Option prices say it gets more expensive.
- **Japan since 1989** is the objection to any comfortable reading of section 4. One country's
  thirty-three years is not a large sample of thirty-year outcomes.
- **Predictability is the serious version of the argument.** If returns are forecastable from
  valuations, horizon does matter (Campbell & Viceira). That is a different claim from "time
  diversifies", and a much harder one to act on.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Time Does Not Diversify — a quantitative teardown \U0001F52C
### Three risk metrics, one window set · a 1/√T null · Samuelson's theorem, numerically

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The section that
settles the argument is **§3.2b**: on 33 years of data that is i.i.d. *by construction*, the
convergence slope measures around −0.7 rather than −0.5, and log dispersion — a quantity that
cannot fall — appears to peak and decline. Every long-horizon claim in this literature has to
clear that bar, which is why §3.3 uses a resampled null of matching length rather than the
theoretical value.

> ⚠️ **Not investment advice.** Long-horizon rows rest on overlapping windows; the
> `effective_n` column reports what they are really worth. Total-return closes from Yahoo!
> Finance pinned as-of the date in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from timediv import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
cash = (px[data.BILLS].pct_change().reindex(r.index).fillna(0.0)
        if data.BILLS in px.columns
        else pd.Series(np.full(len(r), 0.02/252), index=r.index))
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"which is {len(r)/252/30:.1f} independent 30-year periods. Bear that in mind.")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Both sides of this argument are quoting true statements about the same windows. On SPY over 33 years: the standard deviation of the **annualised** return falls from 16.7% at one year to 1.6% at 20 — the adviser's chart, and it is correct. Over the same windows the standard deviation of **terminal wealth** rises from 0.17× to 1.48× — Samuelson's point, also correct. The question is whether the first is *more* than arithmetic. Under i.i.d. returns annualised dispersion must fall like 1/√T, a log-log slope of exactly −0.5. Measured here: **-1.003** (±0.147). A block bootstrap that destroys multi-year mean reversion while keeping the short-run dynamics puts the null slope at -0.673 with a 5th percentile of -0.889, so the observed value is inside it (p = 0.660). Lo-MacKinlay variance ratios agree: at 756 days VR = 0.913 with z = -0.20. The convergence is not merely the √T in the denominator. |
| **Tradability** | Mirage | Which leaves the decision, and there the answer is cleaner than the debate. Maximising CRRA certainty equivalent over the real windows, the optimal equity weight moved by at most **68% across horizons from one to 20 years** — at γ = 3 it went from 98% to 100%. Samuelson's 1969 theorem, that horizon drops out under CRRA and i.i.d. returns, survives contact with the data. The practical reading is not "ignore your horizon" but something more precise: horizon should enter an allocation through **the things that genuinely depend on it** — the size and certainty of future contributions, the flexibility to defer spending, the ability to keep earning through a drawdown — and not through a belief that equities become less risky if you wait. The shortfall probability does fall, from 20% at one year to 0% at 20, but the worst outcome gets worse: the poorest 20-year window ended at 2.52× against 0.55× for the poorest single year. Less likely, more costly, which is precisely the trade the glide-path argument leaves out. |

> \U0001F4A1 **In plain words.** Dividing by T is not a discovery about equities.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (both true).** On identical windows, annualised dispersion falls with horizon *and*
  terminal-wealth dispersion rises.
- **H₂ (arithmetic).** In an i.i.d. world where mean reversion is impossible, annualised
  dispersion still falls — at a log-log slope of −0.5 **given enough data**. On a sample the
  length of the real one it measures far steeper, which §3.2b quantifies and which invalidates
  comparing an observed slope against the theoretical value.
- **H₃ (the empirical question).** The observed slope is **not** significantly below −0.5 once
  the null is generated by a block bootstrap that destroys multi-year dependence.
- **H₄ (variance ratios).** Lo-MacKinlay VR(q) is not significantly below one at long q, using
  the heteroscedasticity-robust statistic.
- **H₅ (power).** The same machinery *does* detect mean reversion when it is planted.
- **H₆ (decision).** The CRRA-optimal equity weight is roughly flat in horizon.
"""
        ),
        md(
            r"""

## 2 · Sample honesty, first
"""
        ),
        code(
            r"""
m = st.horizon_metrics(r, cash, (1, 2, 3, 5, 7, 10, 15, 20, 25, 30))
print(m[["n_windows", "effective_n"]].round(2).to_string())
print()
print("The second column is what matters. At 30 years there are hundreds of overlapping")
print("windows and roughly ONE independent observation. Anything computed on those rows")
print("is illustration, not inference -- which is why section 3.3 uses a bootstrap.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Three risks, one window set
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
axes[0].plot(m.index, m["annualised_sd"] * 100, "o-", lw=2.5, color="#1f6feb")
axes[0].set_xlabel("years"); axes[0].set_ylabel("annualised SD (%)")
axes[0].set_title("falls", fontsize=10)
axes[1].plot(m.index, m["log_sd"], "o-", lw=2.5, color="#c0392b")
axes[1].set_xlabel("years"); axes[1].set_ylabel("SD of log terminal wealth")
axes[1].set_title("rises", fontsize=10)
axes[2].plot(m.index, m["shortfall_vs_cash"] * 100, "o-", lw=2.5, color="#2ea44f",
             label="vs cash")
axes[2].plot(m.index, m["shortfall_vs_zero"] * 100, "s-", lw=2, color="#f0b429",
             label="vs zero")
axes[2].set_xlabel("years"); axes[2].set_ylabel("shortfall probability (%)")
axes[2].legend(fontsize=8); axes[2].set_title("falls", fontsize=10)
plt.tight_layout(); plt.show()
print(m.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Three panels, one dataset, one set of windows. Any of them can
> be shown alone to support a position, which is exactly what happens in practice.
"""
        ),
        md(
            r"""

### 3.2 Against the 1/√T benchmark
"""
        ),
        code(
            r"""
b = st.sqrt_t_benchmark(m)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].loglog(b.index, b["annualised_sd"] * 100, "o-", lw=2.5, color="#1f6feb",
               label="observed")
axes[0].loglog(b.index, b["iid_annualised_sd"] * 100, "k--", lw=2, label="1/sqrt(T)")
axes[0].set_xlabel("years (log)"); axes[0].set_ylabel("annualised SD, % (log)")
axes[0].legend(fontsize=8)
axes[1].plot(b.index, b["ratio_annualised"], "o-", lw=2.5, color="#c0392b")
axes[1].axhline(1.0, color="k", ls="--", lw=2, label="exactly arithmetic")
axes[1].set_xlabel("years")
axes[1].set_ylabel("observed / 1-over-root-T"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
e = st.excess_convergence(m)
print({k: round(v, 4) if isinstance(v, float) else v for k, v in e.items()})
"""
        ),
        md(
            r"""

### 3.2b The trap: what −0.5 looks like through a 33-year window
"""
        ),
        code(
            r"""
bias = st.small_sample_bias(n_days_grid=(8400, 16800, 40000, 100000, 250000),
                            n_reps=5)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].errorbar(bias["years"], bias["mean_slope"], yerr=bias["sd_slope"],
                 fmt="o-", capsize=4, lw=2, color="#1f6feb")
axes[0].axhline(-0.5, color="k", ls="--", lw=2, label="the TRUE slope (iid by construction)")
axes[0].axvline(len(r) / 252, color="#c0392b", ls=":", lw=2,
                label=f"our sample: {len(r)/252:.0f} years")
axes[0].set_xscale("log"); axes[0].set_xlabel("years of data (log)")
axes[0].set_ylabel("measured convergence slope"); axes[0].legend(fontsize=8)
ms = st.horizon_metrics(st.synthetic_iid(n_days=8400),
                        pd.Series(np.zeros(8400),
                                  index=st.synthetic_iid(n_days=8400).index),
                        (1, 2, 3, 5, 7, 10, 15, 20, 25, 30))
ml = st.horizon_metrics(st.synthetic_iid(n_days=250000),
                        pd.Series(np.zeros(250000),
                                  index=st.synthetic_iid(n_days=250000).index),
                        (1, 2, 3, 5, 7, 10, 15, 20, 25, 30))
axes[1].plot(ms.index, ms["log_sd"], "o-", lw=2.5, color="#c0392b",
             label="33 years of iid data")
axes[1].plot(ml.index, ml["log_sd"], "s-", lw=2.5, color="#2ea44f",
             label="1000 years of iid data")
axes[1].set_xlabel("horizon (years)")
axes[1].set_ylabel("SD of log terminal wealth")
axes[1].set_title("a quantity that CANNOT fall, falling", fontsize=10)
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(bias.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Both panels use data where mean reversion is *impossible*. The
> left one shows the convergence slope measuring around −0.7 at our sample length and only
> reaching −0.5 after centuries. The right one shows a dispersion that must grow appearing to
> shrink past a decade.
>
> The cause is the `effective_n` column from §2: a thirty-year window on a thirty-three-year
> tape is one observation, and the sample standard deviation of one observation is
> meaningless. Any study reporting long-horizon mean reversion from a few decades of data has
> to clear this bar first, and most do not attempt to.
"""
        ),
        md(
            r"""

### 3.3 The bootstrap null — the section that settles it
"""
        ),
        code(
            r"""
bs = st.bootstrap_slope(r, cash, n_boot=300, block=252,
                        years_grid=(1, 2, 3, 5, 7, 10, 15))
rng = np.random.default_rng(1007)
# reconstruct the null draws for a picture
slopes = []
n = len(r); block = 252; n_blocks = int(np.ceil(n / block))
rv = r.to_numpy(); cv = cash.to_numpy()
for _ in range(300):
    starts = rng.integers(0, max(n - block, 1), size=n_blocks)
    idx = (starts[:, None] + np.arange(block)[None, :]).ravel()[:n]
    idx = idx[idx < n]
    sr = pd.Series(rv[idx], index=r.index[:len(idx)])
    sc = pd.Series(cv[idx], index=r.index[:len(idx)])
    ee = st.excess_convergence(st.horizon_metrics(sr, sc, (1, 2, 3, 5, 7, 10, 15)))
    if ee:
        slopes.append(ee["slope"])
fig, ax = plt.subplots(figsize=(11, 5))
ax.hist(slopes, bins=40, color="#8b949e", alpha=0.85,
        label="null: 1-year blocks, no multi-year dependence")
ax.axvline(bs["actual_slope"], color="#c0392b", lw=3,
           label=f"observed {bs['actual_slope']:.3f}")
ax.axvline(-0.5, color="k", ls="--", lw=2, label="pure arithmetic")
ax.set_xlabel("log-log convergence slope"); ax.legend(fontsize=9)
plt.show()
print({k: round(v, 4) if isinstance(v, float) else v for k, v in bs.items()})
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The block bootstrap keeps the market's short-run behaviour —
> volatility clustering, fat tails — and shuffles away any multi-year memory. If the red line
> sits inside the grey histogram, the observed convergence is what a memoryless market produces
> anyway.
"""
        ),
        md(
            r"""

### 3.4 Variance ratios, and why the robust version
"""
        ),
        code(
            r"""
vp = st.variance_ratio_profile(r, qs=(2, 5, 10, 21, 42, 63, 126, 252, 504,
                                        756, 1260))
fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(vp.index, vp["vr"], "o-", lw=2.5, color="#1f6feb")
ax.fill_between(vp.index, vp["vr"] - 1.96 * vp["se"], vp["vr"] + 1.96 * vp["se"],
                alpha=0.2, color="#1f6feb")
ax.axhline(1.0, color="k", ls="--", lw=2, label="random walk")
ax.set_xscale("log"); ax.set_xlabel("q, days (log)")
ax.set_ylabel("variance ratio"); ax.legend(fontsize=9)
plt.show()
print(vp.round(4).to_string())
print()
print("Below 1 = mean reversion, above = momentum. The band is the Lo-MacKinlay")
print("heteroscedasticity-robust interval; the homoscedastic one is much narrower and")
print("rejects constantly on equity data, which would manufacture the finding.")
"""
        ),
        md(
            r"""

### 3.5 Power: does the machinery detect the real thing?
"""
        ),
        code(
            r"""
rows = []
for phi in (-0.10, -0.05, -0.02, 0.0, 0.02, 0.05):
    for k in range(4):
        sim = (st.synthetic_iid(n_days=8400, seed=1007 + k) if phi == 0
               else st.synthetic_mean_reverting(n_days=8400, phi=phi, seed=1007 + k))
        simc = pd.Series(np.zeros(len(sim)), index=sim.index)
        ee = st.excess_convergence(st.horizon_metrics(sim, simc,
                                                      (1, 2, 3, 5, 7, 10, 15)))
        vv = st.variance_ratio(sim, 252)
        rows.append({"phi": phi, "slope": ee["slope"] if ee else np.nan,
                     "vr252": vv.get("vr", np.nan), "z": vv.get("z", np.nan)})
d = pd.DataFrame(rows).groupby("phi").mean()
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(d.index, d["slope"], "o-", lw=2.5, color="#1f6feb")
axes[0].axhline(-0.5, color="k", ls="--", lw=2, label="arithmetic")
axes[0].set_xlabel("planted autocorrelation")
axes[0].set_ylabel("convergence slope"); axes[0].legend(fontsize=8)
axes[1].plot(d.index, d["vr252"], "o-", lw=2.5, color="#c0392b")
axes[1].axhline(1.0, color="k", ls="--", lw=2, label="random walk")
axes[1].set_xlabel("planted autocorrelation")
axes[1].set_ylabel("VR(252)"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Both diagnostics move monotonically with planted mean
> reversion, so a null result on the real data is a genuine null rather than a blind
> instrument.
"""
        ),
        md(
            r"""

### 3.6 Every asset
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    if tk in (data.CASH, data.BILLS) or tk not in px.columns:
        continue
    s = px[tk].dropna().pct_change().dropna()
    if len(s) < 2500:
        continue
    cc = cash.reindex(s.index).fillna(0.0)
    ee = st.excess_convergence(st.horizon_metrics(s, cc, (1, 2, 3, 5, 7, 10, 15)))
    vv = st.variance_ratio(s, 756)
    if ee:
        rows.append({"asset": tk, "slope": ee["slope"], "excess": ee["excess"],
                     "vr756": vv.get("vr", np.nan), "z": vv.get("z", np.nan)})
d = pd.DataFrame(rows).set_index("asset")
fig, ax = plt.subplots(figsize=(10, 5))
ax.bar(d.index, d["excess"], color=["#c0392b" if x < 0 else "#2ea44f"
                                    for x in d["excess"]])
ax.axhline(0, color="k", lw=1.5)
ax.set_ylabel("convergence slope minus -0.5\n(negative = faster than arithmetic)")
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

### 3.7 Samuelson's theorem, numerically
"""
        ),
        code(
            r"""
ow = st.optimal_weight_by_horizon(r, cash, years_grid=(1, 2, 3, 5, 7, 10, 15, 20),
                                  gammas=(1.5, 2.0, 3.0, 5.0, 10.0))
piv = ow.pivot(index="years", columns="gamma", values="optimal_weight")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for g in piv.columns:
    axes[0].plot(piv.index, piv[g] * 100, "o-", lw=2, label=f"gamma {g:g}")
axes[0].set_ylim(-5, 105)
axes[0].set_xlabel("horizon (years)"); axes[0].set_ylabel("optimal equity weight (%)")
axes[0].legend(fontsize=8)
ws = st.weight_stability(ow)
gs = sorted(ws["by_gamma"])
axes[1].bar([f"{g:g}" for g in gs],
            [ws["by_gamma"][g]["range"] * 100 for g in gs], color="#1f6feb")
axes[1].set_xlabel("risk aversion")
axes[1].set_ylabel("range of optimal weight across horizons (pp)")
plt.tight_layout(); plt.show()
print(piv.round(3).to_string())
print({k: round(v, 4) if isinstance(v, float) else v
       for k, v in ws.items() if k != "by_gamma"})
"""
        ),
        md(
            r"""

### 3.8 The certainty-equivalent surface
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 3, figsize=(15, 4.4))
grid = np.linspace(0, 1, 41)
for ax, y in zip(axes, (1, 10, 20)):
    lw = st.horizon_windows(r, y); lc = st.horizon_windows(cash, y)
    k = min(len(lw), len(lc))
    if k < 20:
        continue
    eq, cs = np.exp(lw[-k:]), np.exp(lc[-k:])
    for g in (2.0, 5.0, 10.0):
        ces = [st.certainty_equivalent(w * eq + (1 - w) * cs, g) for w in grid]
        ces = np.array(ces) / max(ces)
        ax.plot(grid * 100, ces, lw=2, label=f"gamma {g:g}")
    ax.set_xlabel("equity weight (%)"); ax.set_title(f"{y}-year horizon", fontsize=10)
    ax.set_ylabel("certainty equivalent (scaled)"); ax.legend(fontsize=7)
plt.tight_layout(); plt.show()
print("The peaks sit in similar places across all three panels. That IS the theorem.")
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
m = st.horizon_metrics(r, cash, (1, 2, 3, 5, 7, 10, 15, 20))
e = st.excess_convergence(m)
bs = st.bootstrap_slope(r, cash, n_boot=200, block=252,
                        years_grid=(1, 2, 3, 5, 7, 10, 15))
vv = st.variance_ratio(r, 1260)
ws = st.weight_stability(st.optimal_weight_by_horizon(
    r, cash, years_grid=(1, 3, 5, 10, 15, 20), gammas=(2.0, 3.0, 5.0, 10.0)))
pd.DataFrame({
    "annualised SD, 1 year": [m.loc[1, "annualised_sd"]],
    "annualised SD, 20 years": [m.loc[20, "annualised_sd"]],
    "terminal SD, 1 year": [m.loc[1, "terminal_sd"]],
    "terminal SD, 20 years": [m.loc[20, "terminal_sd"]],
    "shortfall vs cash, 1 year": [m.loc[1, "shortfall_vs_cash"]],
    "shortfall vs cash, 20 years": [m.loc[20, "shortfall_vs_cash"]],
    "worst 20-year outcome": [m.loc[20, "worst_terminal"]],
    "convergence slope": [e["slope"]],
    "arithmetic requires": [-0.5],
    "bootstrap null mean": [bs["null_mean"]],
    "bootstrap p-value": [bs["p_value"]],
    "VR(1260)": [vv.get("vr", np.nan)],
    "VR z-stat": [vv.get("z", np.nan)],
    "range of optimal weight across horizons": [ws["max_range"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Bodie's (1995) option test** is the cleanest resolution and is not run here: price a
  put guaranteeing a riskless return at maturities from one to thirty years. If time diversified
  risk, the premium would shrink with maturity. It grows roughly like √T, which is §3.2 in
  another currency.
- **Campbell & Viceira's predictability case** is the serious argument for horizon-dependent
  allocation and requires state variables — a dividend yield or CAPE — rather than returns
  alone. Adding one would turn §3.7 into a conditional exercise and is the natural sequel.
- **Parameter uncertainty cuts the other way.** Barberis (2000) shows that not knowing the true
  mean makes long horizons *riskier*, partially offsetting predictability. Both effects belong
  in the same model.
- **The effective-sample problem is not solvable with more computation.** Thirty-three years
  contains what it contains; the only fix is more history or more countries, and the latter is
  where a Japan series would earn its place.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
