"""Build the two narrative notebooks for Study 66 (Inverted).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/inverted_panel.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (inverted/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from inverted import data, strategy as st
d = data.fetch_panel()                         # cache-first
slope = st.curve_slope(d["long_yield"], d["short_yield"])
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Forecasts equity downturns?: Confirmed](https://img.shields.io/badge/Forecasts_equity_downturns%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Inverted 📉\n### When the yield curve inverts, should you sell?\n\n"
           + VERDICT +
           "Every modern recession was preceded by an inverted yield curve — short rates above long ones. "
           "And the signal is real for stocks too: after an inversion, the next 18 months of equities "
           "averaged +1% vs +16% normally. But it's a slow warning, not a sell button — markets often "
           "climb for a year after the curve inverts.\n\n"
           "> 📓 **Plain-language layer.** The horizon split and the variable-lead caveat are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (1985–2026) |\n|---|---|\n"
           "| \"Does inversion forecast weak stocks?\" | Yes: next 18m **+1% vs +16%** normal. |\n"
           "| \"At 2 years?\" | Even starker: **−9% vs +22%**. |\n"
           "| \"So sell on inversion?\" | Near-term it's mild (12m gap −4%); markets often rise first. |"),
        md("## 1 · The claim\n\nThe 10-year-minus-3-month Treasury slope inverts (<0) before recessions "
           "(Estrella & Mishkin). The market lore: when it inverts, brace for a downturn — and weak equity "
           "returns."),
        md("## 2 · So what?\n\nThe inversion is the single most-watched recession signal, and it inverted "
           "in 2022–23. If it genuinely forecasts weak stock returns, it's a real risk-management input — "
           "but only if you understand its (long, variable) lead."),
        md("## 3 · How would we even know?\n\nCompute the curve slope over 40 years, then compare the S&P's "
           "forward return after an *inverted* curve vs a *normal* one — at 12, 18 and 24 months, because "
           "the recession lead is long and the horizon changes the answer."),
        code("rows={}\n"
             "for h in (12,18,24):\n"
             "    c=st.conditional_forward(slope,d['eq'],h); rows[f'{h}m']={'after inverted':c['inverted_fwd'],'after normal':c['normal_fwd']}\n"
             "tbl=pd.DataFrame(rows).T\n"
             "ax=(tbl*100).plot.bar(rot=0,color=['#c0392b','#2ea44f'],title='Forward S&P return: after an inverted vs normal curve')\n"
             "ax.set_ylabel('%'); ax.axhline(0,color='k',lw=.8); plt.show()"),
        md("## 4 · The teardown — the signal strengthens with horizon\n\nAn inversion barely dents the next "
           "year; the 18–24-month window — when the recession bites — is flat-to-negative."),
        code("for h in (12,18,24):\n"
             "    c=st.conditional_forward(slope,d['eq'],h)\n"
             "    print(f\"{h}m: inverted {c['inverted_fwd']:+.1%} vs normal {c['normal_fwd']:+.1%} (gap {c['gap']:+.1%})\")\n"
             "print(f\"curve inverted {st.conditional_forward(slope,d['eq'],18)['inverted_share']:.0%} of months\")"),
        md("**Read it plainly.** The warning is real and large at 18–24 months — but rare and slow. Markets "
           "famously melt up *into* the inversion (1998, 2006, 2019, 2023) before the eventual fall."),
        md("## 5 · The verdict\n\n**Signal: Real** — +1%/−9% vs +16%/+22% at 18–24m. **Tradability: "
           "Fragile** — rare, slow, variable-lag, near-term unreliable. **Forecasts downturns?: Confirmed.**"),
        md("## 6 · Could you actually trade it?\n\nNot as a switch. Selling the day the curve inverts has "
           "you out for a year of gains, on average, before the drop. Its honest use is to *shade your "
           "risk* — trim, hold dry powder — when the odds of a downturn rise, not to time the top."),
        md("## 7 · Going further 🚪\n\nThe macro cousin of [56 Tide-Table](../../56-tide-table/) (CAPE): a "
           "real long-horizon predictor that's a poor short-horizon timer."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Inverted — a quantitative teardown 🔬\n### Conditional forward returns by horizon · the strengthening gap · the variable-lead caveat\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). A real signal "
           "whose power lives at the 18–24-month horizon.\n\n"
           "> ⚠️ **Not investment advice.** ^TNX/^IRX/^GSPC, monthly, 1985–2026 (Yahoo). Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | 18m +1% vs +16%; 24m −9% vs +22% |\n"
           "| Tradability | **Fragile** | rare (~5%), 6–24m variable lead |\n"
           "| Forecasts downturns? | **Confirmed** | the canonical recession barometer |\n\n"
           "> 💡 *In plain words:* a real warning, a terrible sell button."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** equity returns are lower after an inverted curve.\n"
           "- **H₂:** the gap is economically large at the recession-lead horizon (18–24m).\n"
           "- **H₃:** it's a usable *timer* (near-term, reliable)."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂ make it a real risk signal; H₃ decides whether "
           "you can trade it mechanically. A real-but-slow signal argues for posture, not timing."),
        md("## 3 · How we'd know — the protocol\n\nCurve slope → forward S&P return after inverted vs "
           "normal at 12/18/24 months → the inverted share and the lead structure."),
        md("## 4 · The teardown"),
        md("### 4.1 Conditional forward returns by horizon"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({f'{h}m':st.conditional_forward(slope,d['eq'],h) for h in (12,18,24)}).T[['inverted_fwd','normal_fwd','gap','n_inverted']].round(3))"),
        md("> 💡 *In plain words:* the gap widens from −4% (12m) to −15% (18m) to −30% (24m). **H₁, H₂ hold** strongly."),
        md("### 4.2 The variable lead — why H₃ fails"),
        md("The 12-month gap is only −4.2%: in the year after an inversion, markets are usually still "
           "*up*. The damage comes at 18–24 months, but the exact timing varies recession to recession "
           "(6–24m). A mechanical 'sell on inversion' rule therefore sits out a year of gains and may be "
           "wrong-footed by the melt-up (1998, 2019, 2023). **H₃ rejected** — it's not a timer."),
        md("## 5 · The verdict\n\nH₁/H₂ hold, H₃ rejected → Signal `REAL`, Tradability `FRAGILE`, the "
           "forecast `CONFIRMED`."),
        md("## 6 · Could you trade it?\n\nAs a risk-posture input (raise cash / trim beta when the odds "
           "rise), not a dated switch. Combine with a confirming trigger (e.g. price below its 200-day) to "
           "avoid the year-early exit."),
        md("## 7 · Going further\n\nForks: (a) the 10y−2y vs 10y−3m variants; (b) un-inversion (the "
           "*re-steepening* often marks the actual recession start); (c) curve + a trend filter as a "
           "combined timer. Backlog: [`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
