"""Build the two narrative notebooks for Study 88 (Dogs-of-the-Dow).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``dogs_of_the_dow`` package on the cached real panel; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-13).
R = dict(
    as_of="2026-06-13", fp="6dfd9e54cba6", n_years=26, first=2000, last=2025,
    n_tickers=46, n_days=6673,
    dogs_cagr=8.51, dow_cagr=7.54, cagr_gap=0.98, mean_excess=0.87,
    win_rate=54, win_n=14,
    hac_t=0.59, boot_lo=-2.15, boot_hi=3.59, boot_p=0.51,
    alpha=2.58, alpha_t=1.59, beta=0.80, r2=0.72,
    total_dogs=8.36, total_dow=6.61, turnover=23,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (dogs_of_the_dow/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from dogs_of_the_dow import data, strategy

AS_OF = "2026-06-13"
CACHE = os.path.abspath(os.path.join("..", "_cache"))
panel = data.load_panel(end=AS_OF, cache_dir=CACHE)
ann = strategy.annual_returns_from_panel(panel, 2000, 2025, cost_bps=20.0)
summ = strategy.summarize(ann)
exc = ann["excess"].to_numpy()
hac_t = strategy.hac_tstat(exc)
boot = strategy.block_bootstrap_ci(exc)
ab = strategy.alpha_beta(ann)
print(f"Dow panel: {panel['prices'].shape[1]} tickers x {len(panel['prices']):,} days  fingerprint={data.fingerprint(panel)}")
print(f"Dogs CAGR {summ['dogs_cagr']*100:.2f}%  vs Dow {summ['dow_cagr']*100:.2f}%  gap {summ['cagr_gap']*100:+.2f} pts/yr  ({summ['n_years']} yrs)")
print(f"HAC t {hac_t:+.2f}   alpha {ab['alpha']*100:+.2f}%/yr (t {ab['alpha_t']:+.2f})   beta {ab['beta']:.2f}")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# The Dogs of the Dow 🐕\n"
            "### Buy the ten highest-yielding Dow stocks each January — do you really beat the Dow?\n\n"
            + HERO_BADGES +
            "It's the cosiest rule in retail investing: every January, buy the **ten highest-"
            "dividend-yield** stocks in the Dow 30, hold them equal-weight for a year, repeat. "
            "O'Higgins & Downes sold it in *Beating the Dow* (1991) and it never died. We test it "
            "**honestly** — picking each year's Dogs only from the stocks that were *actually in the "
            "Dow that year* — and ask the two questions that matter: does it **beat the Dow** (barely, "
            "and not for real), and **could you keep the gap** (taxes and dividend traps say no).\n\n"
            "> 📓 **This is the plain-language layer.** The *t*-stats, the alpha-vs-beta split and the "
            "capacity maths are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, "
            "deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below is "
            "generated by the code beside it. House style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Did the Dogs beat the Dow over {R['n_years']} honest years? | **Just barely** — "
            f"**{R['dogs_cagr']}%/yr** vs **{R['dow_cagr']}%/yr**, a **+{R['cagr_gap']:.1f} point/yr** edge. |\n"
            f"| Is that edge statistically real? | **No** — the year-to-year gap has *t* = "
            f"**{R['hac_t']}** and a range from **{R['boot_lo']}%** to **+{R['boot_hi']}%** that includes zero. |\n"
            f"| So what *is* it? | A **lower-risk, higher-yield** slice of the Dow (beta **{R['beta']}**) — "
            f"a value tilt, not a Dow secret — and the dividends get **taxed** every year. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Each January, buy the 10 highest-dividend-yield stocks in the Dow 30, equal-weight, "
            "hold a year, repeat. This **Dogs of the Dow** beats the Dow itself.\"* The intuition: a "
            "high yield means a beaten-down blue chip that's due to mean-revert, and you collect fat "
            "dividends while you wait."
        ),
        md(
            "## 2 · So what?\n\n"
            "If a rule a child could follow beat the Dow, the whole edifice of stock-picking would owe "
            "it an apology — and every January article telling you to do it would be right. The stakes "
            "are exactly that simple, so it deserves a fair, *literal*, survivorship-honest test."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "Here's the trap most write-ups fall into: **the Dow's membership changes.** If you build "
            "the Dogs from *today's* 30 names back to 2000, you've quietly deleted the losers that got "
            "kicked out (GM, Kodak) and back-dated the winners that got added (Apple, Nvidia) — that "
            "alone can manufacture a fake win. So we encode a **point-in-time** membership list and "
            "pick each January's Dogs **only from the stocks that were in the Dow that January**. Then "
            "we race the Dogs against the **Dow on the same total-return basis** (the DIA ETF), pay "
            "20 bps on what we trade, and run it over the **26 years (2000–2025)** we can do correctly. "
            "Two members we can't price honestly (Kodak, Walgreens) are **left out and named**, not "
            "swept under the rug."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, $1 in the Dogs vs $1 in the Dow."),
        code(
            "eq_dogs = (1 + ann['dogs']).cumprod()\n"
            "eq_dow = (1 + ann['dow']).cumprod()\n"
            "fig, ax = plt.subplots(figsize=(10, 5.5))\n"
            "ax.plot(eq_dogs.index, eq_dogs.values, marker='o', lw=1.6, label=f\"Dogs of the Dow ({summ['dogs_cagr']*100:.1f}%/yr)\")\n"
            "ax.plot(eq_dow.index, eq_dow.values, marker='s', lw=1.6, alpha=.8, label=f\"Dow / DIA total return ({summ['dow_cagr']*100:.1f}%/yr)\")\n"
            "ax.set_yscale('log'); ax.set_ylabel('Growth of $1 (log)'); ax.set_xlabel('rebalance year')\n"
            "ax.set_title('Dogs of the Dow vs the Dow — point-in-time, total return, net of 20 bps'); ax.legend(); plt.show()"
        ),
        md(
            "The Dogs line ends a little higher — but look how *close* the two lines hug each other for "
            "26 years. This isn't a runaway free lunch; it's a hair's-breadth lead that could easily be "
            "luck. Let's look at the year-by-year gap to feel how noisy it is."
        ),
        code(
            "fig, ax = plt.subplots(figsize=(10, 4.5))\n"
            "colors = ['#2ea44f' if e > 0 else '#c0392b' for e in ann['excess']]\n"
            "ax.bar(ann.index, ann['excess']*100, color=colors)\n"
            "ax.axhline(0, color='k', lw=.8)\n"
            "ax.axhline(ann['excess'].mean()*100, color='C0', ls='--', label=f\"mean {ann['excess'].mean()*100:+.2f}%/yr\")\n"
            "ax.set_ylabel('Dogs - Dow (%)'); ax.set_xlabel('year'); ax.set_title('The yearly edge swings wildly around a tiny average'); ax.legend(); plt.show()\n"
            "print(f\"Dogs won {(ann['excess']>0).sum()}/{len(ann)} years\")"
        ),
        md(
            f"The Dogs won only **{R['win_n']} of {R['n_years']}** years — barely a coin flip — and the "
            "bars swing from **+19%** to **−13%**. A +0.9%/yr *average* sitting inside that much noise "
            "is exactly what 'not statistically real' looks like."
        ),
        md("Now the catch the brochures skip: what does 'highest yield' actually buy you in a crisis?"),
        code(
            "rebal = pd.Timestamp('2008-12-31')\n"
            "members = data.members_asof(rebal)\n"
            "yy = {}\n"
            "for t in members:\n"
            "    if t in panel['prices'].columns:\n"
            "        dv = panel['divs'][t].dropna() if t in panel['divs'].columns else pd.Series(dtype=float)\n"
            "        v = strategy.trailing_yield(panel['prices'][t].dropna(), dv, rebal)\n"
            "        if np.isfinite(v) and v > 0: yy[t] = v\n"
            "top = sorted(yy, key=lambda k: yy[k], reverse=True)[:10]\n"
            "print('Jan-2009 Dogs basket (trailing yield at rebalance):')\n"
            "for t in top: print(f'  {t:5s} {yy[t]*100:5.1f}%')"
        ),
        md(
            "The January-2009 basket is a **dividend trap museum**: Citigroup at ~23% trailing yield, "
            "Bank of America at ~21% — financials that had collapsed and were *about to cut their "
            "dividends to pennies*. The 'highest yield' screen doesn't find bargains here; it finds "
            "the market pricing in a disaster."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Beats the Dow? → barely, and not for real.** +{R['cagr_gap']:.1f} pts/yr, but *t* = "
            f"{R['hac_t']} and the range of the yearly edge ({R['boot_lo']}% to +{R['boot_hi']}%) "
            "straddles zero. **Signal → Weak.**\n"
            f"- **What it really is:** a **lower-beta ({R['beta']}), higher-yield** slice of the Dow — a "
            "value tilt you were always paid for, not a Dow-specific secret.\n"
            f"- **Keep the gap? → no.** Low turnover ({R['turnover']}%/yr) means trading cost barely "
            "bites — but the fat dividends are **taxed every year**, and the screen courts dividend "
            "traps. **Tradability → Fragile.**"
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You can run it in a brokerage account with a spreadsheet — capacity isn't the issue. The "
            "issue is that the product is *a defensive value tilt* whose ~1-point lead isn't even "
            "statistically real, and which you'd hold in a **deliberately high-dividend** basket that a "
            "taxable investor pays income tax on every single year. In a taxable account the after-tax "
            "Dogs and the Dow are a wash or worse."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- The **'Small Dogs'** (the 5 lowest-priced of the 10) — does the smaller-cap tilt add "
            "anything, or just more noise?\n"
            "- Replace trailing yield with a **forward / cut-adjusted** yield — does dodging the "
            "dividend traps (Citi, BofA in 2009) recover a real edge?\n"
            "- Run it on the **S&P 100** instead of the Dow 30 — does a wider high-yield net behave "
            "differently? Fork it and try."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Dogs of the Dow — a quantitative teardown 🔬\n"
            "### Point-in-time universe · HAC + block-bootstrap on the annual excess · alpha-vs-beta\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim now carrying its standard error.* We separate the two things the Dogs do "
            "— **tilt toward cheap, high-yield, lower-beta names** (real, and a known risk premium) and "
            "**beat the Dow** (not certifiable on this tape) — and show the headline gap is a defensive "
            "value tilt the screen can't certify as alpha.\n\n"
            "> ⚠️ **Not investment advice.** Dow components, daily, total-return adjusted + the dividend "
            "stream (`yfinance`), point-in-time membership encoded in `dogs_of_the_dow/data.py`; benchmark "
            "DIA total return; 20 bps/turnover. Sources in [`docs/references.md`](../docs/references.md), "
            "reproducible run in [`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `WEAK` | +{R['cagr_gap']:.1f} pts/yr over {R['n_years']} point-in-time years, "
            f"but **HAC *t* = +{R['hac_t']}** and a block-bootstrap CI **[{R['boot_lo']}%, +{R['boot_hi']}%]** "
            f"(*p* = {R['boot_p']}). Alpha **+{R['alpha']}%/yr** but *t* = **{R['alpha_t']}** (sub-2); "
            f"**beta {R['beta']}** — a defensive value tilt, not certified alpha. |\n"
            f"| **Tradability** | `FRAGILE` | Turnover ~{R['turnover']}%/yr → trading cost barely bites, "
            "but the high-yield basket carries an annual **dividend-tax drag** and **dividend-trap** risk; "
            "a sub-2-*t* ~1-pt gap doesn't survive it. |\n\n"
            "> 💡 **In plain words:** the Dogs are a *value/high-yield tilt that works as a tilt* wearing the "
            "costume of a *Dow-beating secret that the statistics can't confirm*."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (tilt):** the Dogs are a high-yield / value / lower-beta slice of the Dow.\n"
            "- **H₂ (the sold claim):** the Dogs beat the Dow on total return, net, out of sample.\n"
            "- **H₃ (alpha):** the excess survives controlling for the Dow itself (an intercept *t* > 2).\n\n"
            "H₁ can be true while H₂ is only marginal and H₃ fails — which is exactly what we find."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₃ held, a no-skill mechanical screen would "
           "deliver certified alpha over the most-watched index on earth. It doesn't — and seeing *why* "
           "(a sub-2-*t* gap that is mostly sub-1 beta) is the lesson."),
        md("## 3 · How we'd know — the protocol\n\nPoint-in-time universe (no survivorship) · annual "
           "rebalanced total-return engine vs same-basis DIA · HAC *t* and circular block bootstrap on the "
           "annual excess · alpha-vs-beta OLS · cost/turnover/tax capacity read."),
        md("## 4 · The teardown\n\nThe annual table — Dogs, Dow, and the excess, net of 20 bps/turnover:"),
        code(
            "show = ann.copy()\n"
            "for c in ['dogs', 'dow', 'excess']: show[c] = (show[c]*100).round(2)\n"
            "show[['dogs', 'dow', 'excess', 'n_names', 'turnover']]"
        ),
        md("**Inference on the annual excess** — HAC *t* and a circular block bootstrap (26 obs is short, "
           "so the bootstrap is honest about its own power):"),
        code(
            "lo, hi, p = boot\n"
            "print(f'mean annual excess = {exc.mean()*100:+.2f}%/yr   win rate {(exc>0).mean()*100:.0f}%')\n"
            "print(f'HAC t              = {hac_t:+.2f}   (|t| < 2 -> cannot reject zero)')\n"
            "print(f'block-bootstrap 95% CI = [{lo*100:+.2f}%, {hi*100:+.2f}%]   two-sided p = {p:.2f}')\n"
            "print('=> the annual edge is statistically indistinguishable from zero on this tape.')"
        ),
        md(
            "> 💡 **In plain words:** over 26 years the Dogs' lead is small enough, and bounces around "
            "enough, that we can't tell it apart from luck."
        ),
        md("**Alpha vs beta** — regress the Dogs' return on the Dow's. Is any edge real alpha, or just "
           "exposure?"),
        code(
            "x = ann['dow'].to_numpy()*100; y = ann['dogs'].to_numpy()*100\n"
            "xs = np.linspace(x.min(), x.max(), 50)\n"
            "fig, axx = plt.subplots(figsize=(8, 6))\n"
            "axx.scatter(x, y, s=40, alpha=.8)\n"
            "axx.plot(xs, ab['alpha']*100 + ab['beta']*xs, 'C3', lw=2, label=f\"fit: alpha {ab['alpha']*100:+.2f}%/yr (t {ab['alpha_t']:+.2f}), beta {ab['beta']:.2f}\")\n"
            "axx.plot(xs, xs, 'k--', lw=1, alpha=.6, label='y = x (beta 1, alpha 0)')\n"
            "axx.set_xlabel('Dow annual return (%)'); axx.set_ylabel('Dogs annual return (%)')\n"
            "axx.set_title(f\"Alpha-vs-beta: R2 = {ab['r2']:.2f}\"); axx.legend(); plt.show()\n"
            "print(f\"alpha {ab['alpha']*100:+.2f}%/yr (t {ab['alpha_t']:+.2f})   beta {ab['beta']:.2f}   R2 {ab['r2']:.2f}\")"
        ),
        md(
            "> 💡 **In plain words:** the Dogs move with the Dow but a touch *less* violently (beta 0.80) — "
            "they're the defensive, high-yield corner of the index. The bit of return left over after that "
            "(the alpha) is positive but not big enough to be sure it isn't noise."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `WEAK` (gap +{R['cagr_gap']:.1f} pts/yr, HAC *t* {R['hac_t']}, bootstrap CI "
            f"[{R['boot_lo']}%, +{R['boot_hi']}%]; alpha +{R['alpha']}%/yr at *t* {R['alpha_t']}, beta "
            f"{R['beta']}). Tradability `FRAGILE` (low turnover, but annual dividend-tax drag + dividend-trap "
            "risk on a sub-2-*t* gap). The edge is a defensive value tilt, not certified alpha."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            f"Capacity is a non-issue (Dow blue chips, infinite liquidity; ~{R['turnover']}%/yr turnover). "
            "The binding facts are economic, not frictional: (1) the ~1-pt gross gap is **not statistically "
            "real**; (2) what tilt is real is **beta 0.80** value exposure, replicable with any cheap "
            "high-dividend ETF; (3) the basket is built to be **high-yield**, so a taxable investor eats an "
            "annual dividend-income tax the cap-weighted Dow holder largely defers. Net of tax the after-tax "
            "race is a wash."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Re-run on a **forward / cut-adjusted yield** to neutralize the dividend traps the trailing "
            "screen buys (Citi, BofA in Jan-2009) — does a cleaner screen recover a *t* > 2?\n"
            "- **After-tax** backtest: charge qualified-dividend and rebalancing tax explicitly and recompute "
            "the gap.\n"
            "- The **two named omissions** (Kodak 2000-04, Walgreens 2019-24): bound their worst-case impact "
            "by inserting plausible high-yield proxies and re-stamping — does the verdict move?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
