"""Notebook builder for Study 983 — The Weekend Oracle.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Weekend Oracle \U0001F52E
### Bitcoin trades while Wall Street sleeps. Does it know something about Monday?

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)

Every Friday at four o'clock the stock market shuts for sixty-five hours. Bitcoin does not.
Whatever the world learns over a weekend is priced by one of them and cannot be priced by the
other — which makes this the cleanest lead-lag experiment available anywhere in markets.

> \U0001F4D3 **This is the plain-language layer.** The overlap accounting, the regime splits and
> the falsification control are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does the usual "crypto leads stocks" chart prove anything? | No — the two closes are three hours apart and the chart is measuring the clock. |
| Is there a clean version of the question? | Yes: the weekend, when equities cannot trade at all. |
| Does the weekend move predict the next session? | See the regression below — and note the R². |
| Would you trade it? | See the last section, where it is benchmarked against the same sessions held blind. |
"""
        ),
        md(
            r"""

## 1 · The trick the clock plays

Yahoo's Bitcoin daily bar runs midnight to midnight **UTC**. The New York close is at about
**21:00 UTC**. So Bitcoin's "Monday" bar contains three hours of Monday evening that the
American stock market never saw.

That is why "Bitcoin's move today is correlated with stocks tomorrow" is not evidence of
anything: part of "today" for Bitcoin is already "tomorrow" for stocks.
"""
        ),
        code(
            r"""
from weekendoracle import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
eq_px = px[data.EQUITY].dropna()
eq_rets = eq_px.pct_change()
cash_rets = rets[data.CASH].reindex(eq_px.index).fillna(0.0)
panel = st.attach_target(st.weekend_returns(px[data.CRYPTO].dropna(), eq_px.index), eq_rets)
print(f"as-of {data.AS_OF} | {len(panel):,} closed-market windows, "
      f"{panel.index[0].date()} -> {panel.index[-1].date()}")
print(panel.head().to_string())
"""
        ),
        md(
            r"""

## 2 · The one clean window

Sixty-five hours a week, one market is open and the other is shut. There is no overlap to argue
about.
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 3.2))
ax.barh([0], [65.5], left=[0], color="#f0b429", label="market shut — Bitcoin trades alone")
ax.barh([0], [6.5], left=[65.5], color="#2ea44f", label="Monday session")
ax.barh([1], [3], left=[0], color="#c0392b", label="daily bar overlap (3h of contamination)")
ax.barh([1], [21], left=[3], color="#8b949e", alpha=0.4)
ax.set_yticks([0, 1]); ax.set_yticklabels(["weekend design", "daily design"])
ax.set_xlabel("hours"); ax.legend(fontsize=8, loc="lower right")
ax.set_title("Why one of these two designs is an experiment and the other is not")
plt.show()
"""
        ),
        md(
            r"""

## 3 · What the weekend actually says about Monday
"""
        ),
        code(
            r"""
reg = st.monday_regression(panel)
fig, ax = plt.subplots(figsize=(8.5, 6))
ax.scatter(panel["crypto_return"] * 100, panel["equity_return"] * 100, s=14, alpha=0.4,
           color="#2ea44f")
xs = np.linspace(panel["crypto_return"].min(), panel["crypto_return"].max(), 50)
ax.plot(xs * 100, (reg["alpha"] + reg["beta"] * xs) * 100, color="k", lw=1.8)
ax.axhline(0, color="#8b949e", lw=0.8); ax.axvline(0, color="#8b949e", lw=0.8)
ax.set_xlabel(f"{data.CRYPTO} across the closed window (%)")
ax.set_ylabel(f"{data.EQUITY} on the next session (%)")
ax.set_title(f"n={reg['n']}   slope {reg['beta']:+.3f}   t {reg['t']:+.2f}   "
             f"R2 {reg['r2']:.2%}")
plt.show()
print(st.conditional_means(panel).round(5).to_string())
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Look at the R² before the *t*. A slope can be statistically
> distinguishable from zero and still explain almost none of Monday — those are two different
> claims and traders routinely collapse them.
"""
        ),
        md(
            r"""

### A caveat that has to come *before* the answer, not after

Bitcoin's weekend move is a **noisy proxy** for the weekend's news. Most of a 4-5% weekend swing
is Bitcoin's own business — liquidations, a listing, a tweet — and has nothing to do with what
equities will price on Monday. That noise caps how strong a relationship this test can ever
show, whatever the truth is.
"""
        ),
        code(
            r"""
sd = panel["crypto_return"].std()
c = st.detectability_ceiling(len(panel), crypto_noise=sd)
print(f"Bitcoin's weekend move: sd {sd:.1%}")
print(f"Largest |t| this experiment could ever produce over {len(panel)} weekends: "
      f"{c['max_t']:.2f}")
print(f"Weekends that would be needed to see it reliably: ~{c['n_weeks_for_t2']:.0f} "
      f"({c['n_weeks_for_t2'] / 52:.0f} years)")
print(f"Weekends available: {len(panel)} ({len(panel) / 52:.0f} years)")
"""
        ),
        md(
            r"""

So if the number below is small, the right conclusion is *"we cannot tell"*, not *"there is
nothing there"*. That distinction is the difference between a result and a shrug, and most
write-ups of this question skip it.
"""
        ),
        md(
            r"""

## 4 · Before and after Bitcoin grew up
"""
        ),
        code(
            r"""
rs = st.regime_split(panel)
print(rs.round(4).to_string())
fig, ax = plt.subplots(figsize=(9, 4))
rs["beta"].plot.bar(ax=ax, color=["#8b949e", "#2ea44f"])
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("slope: next session per 1 unit of weekend crypto")
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
"""
        ),
        md(
            r"""

## 5 · The gold control

GLD is shut over the weekend too. Its "weekend return" is measured across a window in which it
did not trade — so it must show nothing. If it shows something, the machine is broken.
"""
        ),
        code(
            r"""
for label, tk in (("Bitcoin", data.CRYPTO), ("Ethereum", data.CRYPTO_2),
                  ("Gold (control)", data.GOLD)):
    s = px[tk].dropna()
    p = st.attach_target(st.weekend_returns(s, eq_px.index), eq_rets)
    r = st.monday_regression(p)
    print(f"{label:16s} n {r['n']:4d}  slope {r['beta']:+.4f}  t {r['t']:+.2f}  "
          f"R2 {r['r2']:.2%}")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Real.** Over 646 closed-market windows (2014-09-22 → 2026-06-29), a 1% Bitcoin move across the weekend was followed by a **+4.019%** move in SPY on the next session (*t* = **+3.01**, R² 3.55%). The sign agreed 58.8% of the time against a 50% coin flip (*t* = +4.49), and the average next-session return was +0.242% after an up weekend against -0.187% after a down one (*t* = +4.64). Split at March 2020 the slope was +0.001 before and +0.086 after — the era in which Bitcoin became a high-beta Nasdaq position is doing most of the work. This is the **clean** design: zero hours of overlap, unlike the ordinary daily lead-lag correlation of -0.01, which shares 3 hours of clock with its own target. One thing this stamp must not be read as: Bitcoin's weekend move has a standard deviation of 5.3%, most of it Bitcoin's own business, so even a weekend whose news determined Monday perfectly could only produce a *t* of about **2.8** over 646 windows — a null here is weak evidence of absence, not strong evidence of nothing.

**Tradability: Fragile.** Buying SPY only on the session after an up crypto weekend — 363 of 646 windows, 56% of them — returned **+6.28%/yr** on those same sessions against **+2.64%** for holding every one of them regardless (+3.64%/yr, *t* = +1.72), after 2 bps a side. The rule is in the market about one session a week, so this is a comparison of like with like, not a Sharpe you can put next to a buy-and-hold Sharpe.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Use the Monday open**, not the Monday close. If the weekend news is priced in the first
  minutes, close-to-close hides it.
- **The overnight window on ordinary days** is the same idea thirteen hours long and five times
  a week — but it needs intraday data, because of the clock problem in section 1.
- **Macro weekends specifically**: closures containing an election, an OPEC meeting or a
  banking failure are where the effect, if any, should concentrate.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Weekend Oracle — a quantitative teardown \U0001F52C
### Overlap accounting · closed-window panels · HC1 · a gold falsification control

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The first
section is not about Bitcoin at all; it is about what time Yahoo closes a daily bar, which turns
out to determine whether the rest of the study means anything.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from weekendoracle import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
eq_px = px[data.EQUITY].dropna()
eq_rets = eq_px.pct_change()
cash_rets = rets[data.CASH].reindex(eq_px.index).fillna(0.0)
panel = st.attach_target(st.weekend_returns(px[data.CRYPTO].dropna(), eq_px.index), eq_rets)
print(f"as-of {data.AS_OF} | {len(panel):,} closed-market windows, "
      f"{panel.index[0].date()} -> {panel.index[-1].date()}")
print(panel.head().to_string())
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Over 646 closed-market windows (2014-09-22 → 2026-06-29), a 1% Bitcoin move across the weekend was followed by a **+4.019%** move in SPY on the next session (*t* = **+3.01**, R² 3.55%). The sign agreed 58.8% of the time against a 50% coin flip (*t* = +4.49), and the average next-session return was +0.242% after an up weekend against -0.187% after a down one (*t* = +4.64). Split at March 2020 the slope was +0.001 before and +0.086 after — the era in which Bitcoin became a high-beta Nasdaq position is doing most of the work. This is the **clean** design: zero hours of overlap, unlike the ordinary daily lead-lag correlation of -0.01, which shares 3 hours of clock with its own target. One thing this stamp must not be read as: Bitcoin's weekend move has a standard deviation of 5.3%, most of it Bitcoin's own business, so even a weekend whose news determined Monday perfectly could only produce a *t* of about **2.8** over 646 windows — a null here is weak evidence of absence, not strong evidence of nothing. |
| **Tradability** | Fragile | Buying SPY only on the session after an up crypto weekend — 363 of 646 windows, 56% of them — returned **+6.28%/yr** on those same sessions against **+2.64%** for holding every one of them regardless (+3.64%/yr, *t* = +1.72), after 2 bps a side. The rule is in the market about one session a week, so this is a comparison of like with like, not a Sharpe you can put next to a buy-and-hold Sharpe. |

> \U0001F4A1 **In plain words.** The clean experiment exists, it was run, and the R² is the
> number to read.
"""
        ),
        md(
            r"""

## 1 · Overlap accounting

Before any estimate, an audit of what each design's predictor window shares with its target's.

- Yahoo crypto daily bar: closes 00:00 UTC.
- NYSE: closes ~21:00 UTC.
- A closed-market window: Friday 21:00 UTC → Monday 14:30 UTC, with the target beginning after
  it ends.
"""
        ),
        code(
            r"""
rows = [{"design": a, "overlap_hours": st.overlap_hours(a), "clean": st.is_clean(a)}
        for a in ("same_day", "crypto_lead", "weekend")]
print(pd.DataFrame(rows).to_string(index=False))
grid = st.lead_lag_grid(rets[data.CRYPTO].dropna(), eq_rets.dropna())
print()
print(grid.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Every row of the second table is contaminated. They are printed
> so that the reader can see what the usual version of this study would have concluded.
"""
        ),
        md(
            r"""

## 2 · The closed-window panel
"""
        ),
        code(
            r"""
print(panel.describe().round(5).to_string())
print()
print(panel["gap_days"].value_counts().sort_index().to_string())
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].hist(panel["crypto_return"] * 100, bins=60, color="#f0b429", edgecolor="white")
axes[0].set_title(f"{data.CRYPTO} across the closed window (%)")
axes[1].hist(panel["equity_return"] * 100, bins=60, color="#2ea44f", edgecolor="white")
axes[1].set_title(f"{data.EQUITY} on the next session (%)")
for a in axes:
    a.axvline(0, color="k", lw=1)
plt.show()
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The regression, with HC1 errors
"""
        ),
        code(
            r"""
reg = st.monday_regression(panel)
sa = st.sign_agreement(panel)
print(pd.Series({**{k: v for k, v in reg.items() if k != "alignment"},
                 "hit_rate": sa["hit_rate"],
                 "t_vs_coin_flip": sa["t_vs_coin_flip"]}).round(5).to_string())
print()
print(st.conditional_means(panel).round(5).to_string())
"""
        ),
        md(
            r"""

### 3.2 Regimes and closure lengths
"""
        ),
        code(
            r"""
print(st.regime_split(panel).round(4).to_string())
print()
print(st.gap_length_buckets(panel).round(4).to_string())
roll = pd.Series(
    [st.monday_regression(panel.iloc[i - 156:i])["beta"] if i >= 156 else np.nan
     for i in range(len(panel))], index=panel.index)
fig, ax = plt.subplots(figsize=(11, 4.5))
ax.plot(roll.index, roll, lw=1.4, color="#2ea44f")
ax.axhline(0, color="k", lw=1)
ax.axvline(pd.Timestamp("2020-03-01"), color="#c0392b", ls="--", lw=1, label="March 2020")
ax.set_ylabel("rolling 3-year slope"); ax.legend()
plt.show()
"""
        ),
        md(
            r"""

### 3.3 The falsification control
"""
        ),
        code(
            r"""
rows = []
for label, tk in (("Bitcoin", data.CRYPTO), ("Ethereum", data.CRYPTO_2),
                  ("Gold — shut too, must show nothing", data.GOLD)):
    s = px[tk].dropna()
    if len(s) < 500:
        continue
    p = st.attach_target(st.weekend_returns(s, eq_px.index), eq_rets)
    r = st.monday_regression(p)
    rows.append({"predictor": label, "n": r["n"], "beta": r["beta"], "t": r["t"],
                 "r2": r["r2"]})
d = pd.DataFrame(rows).set_index("predictor")
fig, ax = plt.subplots(figsize=(9, 4))
d["t"].plot.bar(ax=ax, color=["#f0b429", "#8b949e", "#c0392b"])
ax.axhline(0, color="k", lw=1)
for y in (-2, 2):
    ax.axhline(y, ls="--", color="#8b949e", lw=1)
ax.set_ylabel("HC1 t")
plt.setp(ax.get_xticklabels(), rotation=12, ha="right", fontsize=8)
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.4 The rule, and the only fair benchmark for it
"""
        ),
        code(
            r"""
rule = st.monday_rule(panel, eq_rets, cash_rets, cost_bps=2.0)
curve = pd.DataFrame({
    "rule (long only after an up crypto weekend)": (1 + rule["returns"]).cumprod(),
    "hold every post-closure session": (1 + eq_rets.reindex(panel.index)).cumprod(),
})
fig, ax = plt.subplots(figsize=(11, 5))
curve.plot(ax=ax, logy=True, color=["#2ea44f", "#8b949e"])
ax.set_ylabel("growth of $1 on these sessions only (log)"); ax.legend(title="", fontsize=8)
plt.show()
print(pd.Series({k: v for k, v in rule.items() if k != "returns"}).round(5).to_string())
"""
        ),
        code(
            r"""
rows = []
for thr in (-0.05, -0.03, -0.01, 0.0, 0.01, 0.03, 0.05):
    for c in (0.0, 2.0, 10.0):
        r = st.monday_rule(panel, eq_rets, cash_rets, cost_bps=c, threshold=thr)
        rows.append({"threshold": thr, "cost_bps": c, "share_long": r["share_long"],
                     "per_year": r["per_year_rule"], "t": r["t_gap"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 4.5))
d.pivot(index="threshold", columns="cost_bps", values="per_year").mul(100).plot(
    ax=ax, marker="o")
ax.axhline(rule["per_year_always"] * 100, color="k", ls="--", lw=1,
           label="hold every such session")
ax.set_ylabel("rule return on these sessions (%/yr)"); ax.legend(title="cost (bps)", fontsize=8)
plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

### 3.5 The ceiling: what this design could ever have seen

Before reading any null as evidence of absence. Bitcoin's weekend move is a *proxy* for the
weekend's news, and a noisy one; the correlation between proxy and news caps the correlation
between proxy and Monday, no matter how predictable Monday actually is.
"""
        ),
        code(
            r"""
sd = panel["crypto_return"].std()
print(pd.Series(st.detectability_ceiling(len(panel), crypto_noise=sd)).round(4).to_string())
rows = []
for noise in (0.005, 0.01, 0.02, 0.03, sd, 0.08):
    c = st.detectability_ceiling(len(panel), crypto_noise=noise)
    rows.append({"crypto weekend sd": noise, "max correlation": c["max_correlation"],
                 "max |t|": c["max_t"]})
d = pd.DataFrame(rows).set_index("crypto weekend sd")
fig, ax = plt.subplots(figsize=(9, 4.5))
d["max |t|"].plot(ax=ax, marker="o", color="#c0392b")
ax.axhline(2, ls="--", color="#8b949e", lw=1, label="|t| = 2")
ax.axvline(sd, ls=":", color="#f0b429", lw=1.5, label=f"actual: {sd:.1%}")
ax.set_ylabel(f"largest achievable |t| over {len(panel)} windows"); ax.legend()
ax.set_title("The proxy's noise, not the sample size, is what binds")
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** If the vertical marker sits near or below the dashed line, this
> study could not have detected a real weekend effect even if one existed — and the honest
> report of that is a wide confidence interval, not a confident "no".
"""
        ),
        md(
            r"""

### 3.6 Power and size
"""
        ),
        code(
            r"""
rows = []
for info in (0.0, 0.2, 0.4, 0.6, 1.0):
    ts = [st.monday_regression(st.synthetic_world(n_weeks=len(panel),
                                                  weekend_information=info, seed=983 + s))["t"]
          for s in range(10)]
    rows.append({"planted weekend information": info, "mean |t|": np.nanmean(np.abs(ts)),
                 "share significant": np.mean(np.abs(ts) >= 2)})
d = pd.DataFrame(rows).set_index("planted weekend information")
fig, ax = plt.subplots(figsize=(9, 4.5))
d["share significant"].plot(ax=ax, marker="o", color="#2ea44f")
ax.axhline(0.05, ls="--", color="#c0392b", lw=1, label="nominal size")
ax.set_ylabel(f"share of runs with |t| >= 2 (n = {len(panel)})"); ax.legend()
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
reg = st.monday_regression(panel)
rs = st.regime_split(panel)
rule = st.monday_rule(panel, eq_rets, cash_rets, cost_bps=2.0)
pd.DataFrame({
    "closed windows": [len(panel)],
    "slope": [reg["beta"]],
    "HC1 t": [reg["t"]],
    "R2": [reg["r2"]],
    "sign agreement": [st.sign_agreement(panel)["hit_rate"]],
    "slope before 2020-03": [rs.iloc[0]["beta"]],
    "slope since 2020-03": [rs.iloc[1]["beta"]],
    "largest |t| this design could give": [
        st.detectability_ceiling(len(panel), crypto_noise=panel["crypto_return"].std())["max_t"]],
    "rule vs same sessions (pp/yr)": [(rule["per_year_rule"] - rule["per_year_always"]) * 100],
    "t of that gap": [rule["t_gap"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Open-to-close targets.** If the weekend's information is priced at the opening auction, the
  close-to-close target used here measures the wrong thing. Reproducing this with intraday data
  is the single highest-value extension.
- **Event-conditioned weekends.** Restrict to closures containing a scheduled macro event.
- **The reverse direction.** Does Friday's equity session predict the weekend's crypto move?
  That design is also clean, and it is the one the data is most likely to say yes to.
- **Other 24/7 assets.** FX opens Sunday evening; the same experiment runs there with a
  seventeen-hour shorter window.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
