"""Notebook builder for Study 1008 — The Start-Date Lottery.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Start-Date Lottery \U0001F3B0
### Same plan, same discipline, same market. Different birth year.

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Two people save the same amount every month for twenty-five years into the same index fund.
One retires comfortably; the other does not. Neither made a mistake. This measures how big that
gap is, what causes it, and which of the usual fixes is worth its price.

> \U0001F4D3 **This is the plain-language layer.** The shuffle test, the exposure profile and
> the two-column scoring of remedies are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| How big is the start-date gap? | Around twofold, for identical plans. |
| Is monthly saving worse than a lump sum? | No — it is *better*. It damps the lottery. |
| When are you most exposed? | The last few years, not the first. |
| What is the cheapest defence? | De-risking late rather than early. |
"""
        ),
        md(
            r"""

## 1 · The same plan, a different decade
"""
        ),
        code(
            r"""
from startdate import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
bonds = px[data.BONDS].dropna().pct_change()
idx = r.index.intersection(bonds.dropna().index)
e, b = r.reindex(idx), bonds.reindex(idx)
# The bond tape is much shorter than the equity one, so the glide-path sections cannot use
# the same horizon as the equity-only sections. Pick the longest that actually fits.
REMEDY_YEARS = float(min(20.0, np.floor(len(idx) / 252) - 2))
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"stocks+bonds overlap: {len(idx):,} sessions from {idx[0].date()} "
      f"({len(idx)/252:.1f} years)")
print(f"glide-path sections use {REMEDY_YEARS:.0f}-year paths")
"""
        ),
        code(
            r"""
acc = st.accumulation_paths(r, 25)
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(acc["start"], acc["multiple"], lw=2, color="#1f6feb")
ax.axhline(acc["multiple"].median(), color="k", ls="--", lw=1.5,
           label=f"median {acc['multiple'].median():.2f}x")
best = acc.loc[acc["multiple"].idxmax()]
worst = acc.loc[acc["multiple"].idxmin()]
ax.scatter([best["start"]], [best["multiple"]], s=120, color="#2ea44f", zorder=5,
           label=f"best: started {best['start'].date()} -> {best['multiple']:.2f}x")
ax.scatter([worst["start"]], [worst["multiple"]], s=120, color="#c0392b", zorder=5,
           label=f"worst: started {worst['start'].date()} -> {worst['multiple']:.2f}x")
ax.set_xlabel("month you started saving")
ax.set_ylabel("what each $1 contributed became")
ax.legend(fontsize=9)
plt.show()
d = st.path_dispersion(acc, "multiple")
print(f"best/worst = {d['ratio_max_min']:.2f}x for the SAME plan")
print(f"(these {d['n_paths']} start dates overlap; worth ~{d['effective_n']:.1f} "
      f"independent ones)")
"""
        ),
        md(
            r"""

## 2 · Good news nobody mentions
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 5))
lump = acc["lump_sum"] / acc["lump_sum"].median()
contrib = acc["multiple"] / acc["multiple"].median()
ax.hist(lump, bins=30, alpha=0.6, color="#c0392b", label="invested a lump sum")
ax.hist(contrib, bins=30, alpha=0.6, color="#2ea44f", label="saved monthly")
ax.set_xlabel("outcome relative to the median")
ax.set_ylabel("number of start dates"); ax.legend(fontsize=9)
plt.show()
dl = st.path_dispersion(acc, "lump_sum")
dc = st.path_dispersion(acc, "multiple")
print(f"lump sum:     95th/5th = {dl['ratio_95_05']:.2f}x")
print(f"saved monthly: 95th/5th = {dc['ratio_95_05']:.2f}x")
"""
        ),
        md(
            r"""

Saving gradually gives a **narrower** range of outcomes than investing everything at once. The
start-date lottery is worse for someone with a windfall than for a saver — the opposite of how
"sequence risk" is usually described to people paying into a pension.
"""
        ),
        md(
            r"""

## 3 · How much of this is just *the order things happened in*?
"""
        ),
        code(
            r"""
seg = r.to_numpy()[-int(25*252):]
sh = st.shuffle_invariance(seg, contribution=1/21, n_shuffles=500)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.6))
rng = np.random.default_rng(1008)
lumps = [st.terminal_lump_sum(rng.permutation(seg)) for _ in range(300)]
contribs = [st.terminal_with_contributions(rng.permutation(seg), 1/21)
            for _ in range(300)]
# The lump-sum values are identical to machine precision, so a histogram of them has
# no range at all and numpy refuses to bin it. That refusal IS the result, so draw the
# degenerate case deliberately rather than working around it.
lo, hi = min(lumps), max(lumps)
axes[0].axvline(lumps[0], color="#8b949e", lw=6)
axes[0].set_xlim(lumps[0] * 0.5, lumps[0] * 1.5)
axes[0].set_title(f"lump sum: every shuffle identical (range {hi - lo:.2e})",
                  fontsize=10)
axes[0].set_xlabel("terminal value")
axes[1].hist(contribs, bins=30, color="#c0392b")
axes[1].set_title("saving monthly: the order is everything", fontsize=10)
axes[1].set_xlabel("terminal value")
plt.tight_layout(); plt.show()
print(f"lump sum spread:    {sh['lump_cv']:.2e}  (zero, to machine precision)")
print(f"contributor spread: {sh['sequence_spread']:.2f}x between 5th and 95th")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Shuffling holds the mean, the volatility and every other moment
> exactly fixed. Whatever survives is *pure* sequence risk, and it can be separated from the
> fact that the 1990s and the 2000s were simply different markets.
"""
        ),
        md(
            r"""

## 4 · When are you most exposed?
"""
        ),
        code(
            r"""
m = st.sequence_risk_metrics(r, 25, n_buckets=6)
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(m)); w = 0.38
ax.bar(x - w/2, m["corr_contributor"], w, color="#c0392b", label="saving monthly")
ax.bar(x + w/2, m["corr_lump_sum"], w, color="#8b949e", label="lump sum")
ax.set_xticks(x)
ax.set_xticklabels([f"years\n{r0:.0f}-{r1:.0f}" for r0, r1 in
                    zip(m["years_from"], m["years_to"])], fontsize=8)
ax.set_ylabel("how much this period drove the final outcome")
ax.legend(fontsize=9)
plt.show()
print(m.round(3).to_string())
"""
        ),
        md(
            r"""

The grey bars are level, as they must be: for a lump sum every year counts the same. The red
bars climb. By the final years your balance is large and your remaining contributions are
small, so those are the years that decide the outcome.
"""
        ),
        md(
            r"""

## 5 · So what helps, and what does it cost?
"""
        ),
        code(
            r"""
rem = st.remedy_comparison(e, b, REMEDY_YEARS)
fig, ax = plt.subplots(figsize=(11, 5.5))
ax.scatter(rem["median_cost"] * 100, rem["cv_reduction"] * 100, s=140,
           color="#1f6feb")
for name, row in rem.iterrows():
    ax.annotate(name, (row["median_cost"] * 100, row["cv_reduction"] * 100),
                fontsize=8, xytext=(7, 4), textcoords="offset points")
lim = max(rem["median_cost"].max(), rem["cv_reduction"].max()) * 105
ax.plot([0, lim], [0, lim], "k--", lw=1.5, label="break even: 1% saved per 1% given up")
ax.set_xlabel("median wealth given up (%)")
ax.set_ylabel("dispersion removed (%)"); ax.legend(fontsize=9)
plt.show()
print(rem[["median", "cv", "median_cost", "cv_reduction", "efficiency"]].round(3)
      .to_string())
"""
        ),
        md(
            r"""

Everything above the dashed line removes more uncertainty than wealth. The **late** glide sits
highest, because section 4 showed the exposure is late — protection bought early pays for a risk
you do not yet carry, using compounding you cannot get back.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Weak.** Large, and larger than it looks in the usual telling. Contributing the same amount every month into SPY for 25 years, the best available start date turned each unit invested into 5.91× and the worst into 2.85× — a **2.08× gap between two people following an identical plan**, with the 5th-to-95th percentile spanning 1.69×. The best start was 2001-05-25 and the worst 1995-03-30. Two caveats keep that honest: these paths overlap heavily and are worth roughly 1.3 independent observations, and the *lump-sum* spread over the same windows was 1.75× — so much of this is the return distribution rather than sequence. The clean separation is the shuffle test: reordering a single path leaves a lump sum unchanged to 2e-16 relative precision while scattering a contributor's outcome across 2.42×. **That** is pure sequence risk, with the distribution held exactly fixed. And it is not spread evenly: the final sixth of the horizon correlates 0.43 with a contributor's outcome against -0.67 for the first, whereas for a lump sum every period matters equally by construction.

**Tradability: Useful.** Yes, and the profile above says which remedy to reach for. Because the exposure is concentrated late, de-risking late buys most of the protection cheaply. Scoring every rule on the same paths — dispersion removed against median wealth given up — the best was **late glide to 30%**, cutting the coefficient of variation by 40% for a median cost of 22%, an efficiency of **1.81× dispersion removed per unit of wealth sacrificed**. A conventional linear glide managed 1.67×, and simply holding a constant 60/40 throughout 1.68×. The ranking is what matters more than the levels, since the levels inherit the overlapping-window problem. Two things worth saying plainly: none of this eliminates the lottery — the residual spread under the best remedy was still 1.31× — and the largest lever is not on this table at all. Contributing for forty years instead of thirty, or retaining the flexibility to defer retirement by two, moves the distribution more than any asset-allocation rule tested here.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **The biggest levers are not asset allocation.** Saving for forty years instead of thirty, or
  keeping the option to work two more years, moves the distribution more than any glide path
  tested here.
- **Keep contributing through the crash.** A bad decade early is *good* for a saver — it buys
  units cheaply. Section 4 explains why: the exposure comes later, so an early drawdown is an
  opportunity rather than a loss.
- **Retirees face the mirror image.** For them the first five years decide everything, which is
  the real argument for holding a cash buffer at the start of retirement rather than a glide
  path throughout it.
- **Do not over-read the magnitudes.** These windows overlap and are worth about one independent
  observation. The *ranking* of the remedies is far more solid than the sizes.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Start-Date Lottery — a quantitative teardown \U0001F52C
### A shuffle test for pure sequence risk · the exposure profile · remedies scored on two columns

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The load-bearing
construction is **§3.2**: shuffling a path holds every moment of the return distribution exactly
fixed while destroying the ordering, which separates sequence risk from era risk without
assuming a model. **§3.5** then scores every remedy on dispersion removed *and* wealth given up,
because studies that print only the first column are selling something.

> ⚠️ **Not investment advice.** Overlapping windows throughout; the `effective_n` column says
> what they are worth. Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from startdate import data, strategy as st

px = data.load_prices()
r = px[data.EQUITY].dropna().pct_change().dropna()
bonds = px[data.BONDS].dropna().pct_change()
idx = r.index.intersection(bonds.dropna().index)
e, b = r.reindex(idx), bonds.reindex(idx)
# The bond tape is much shorter than the equity one, so the glide-path sections cannot use
# the same horizon as the equity-only sections. Pick the longest that actually fits.
REMEDY_YEARS = float(min(20.0, np.floor(len(idx) / 252) - 2))
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions from "
      f"{r.index[0].date()} ({len(r)/252:.1f} years)")
print(f"stocks+bonds overlap: {len(idx):,} sessions from {idx[0].date()} "
      f"({len(idx)/252:.1f} years)")
print(f"glide-path sections use {REMEDY_YEARS:.0f}-year paths")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Large, and larger than it looks in the usual telling. Contributing the same amount every month into SPY for 25 years, the best available start date turned each unit invested into 5.91× and the worst into 2.85× — a **2.08× gap between two people following an identical plan**, with the 5th-to-95th percentile spanning 1.69×. The best start was 2001-05-25 and the worst 1995-03-30. Two caveats keep that honest: these paths overlap heavily and are worth roughly 1.3 independent observations, and the *lump-sum* spread over the same windows was 1.75× — so much of this is the return distribution rather than sequence. The clean separation is the shuffle test: reordering a single path leaves a lump sum unchanged to 2e-16 relative precision while scattering a contributor's outcome across 2.42×. **That** is pure sequence risk, with the distribution held exactly fixed. And it is not spread evenly: the final sixth of the horizon correlates 0.43 with a contributor's outcome against -0.67 for the first, whereas for a lump sum every period matters equally by construction. |
| **Tradability** | Useful | Yes, and the profile above says which remedy to reach for. Because the exposure is concentrated late, de-risking late buys most of the protection cheaply. Scoring every rule on the same paths — dispersion removed against median wealth given up — the best was **late glide to 30%**, cutting the coefficient of variation by 40% for a median cost of 22%, an efficiency of **1.81× dispersion removed per unit of wealth sacrificed**. A conventional linear glide managed 1.67×, and simply holding a constant 60/40 throughout 1.68×. The ranking is what matters more than the levels, since the levels inherit the overlapping-window problem. Two things worth saying plainly: none of this eliminates the lottery — the residual spread under the best remedy was still 1.31× — and the largest lever is not on this table at all. Contributing for forty years instead of thirty, or retaining the flexibility to defer retirement by two, moves the distribution more than any asset-allocation rule tested here. |

> \U0001F4A1 **In plain words.** A lump sum has no sequence risk. Everyone else does, and how
> much depends on the shape of their cash flows.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (invariance).** A lump sum's terminal value is exactly order-invariant; a contributor's
  is not.
- **H₂ (separation).** Shuffling isolates pure sequence risk from era-to-era differences in the
  return distribution.
- **H₃ (direction).** Regular contributions produce *less* start-date dispersion than a lump
  sum, at every volatility.
- **H₄ (profile).** A contributor's outcome correlates increasingly with later slices of the
  horizon; a lump sum's correlates equally with all of them.
- **H₅ (remedy).** De-risking late dominates de-risking early on dispersion removed per unit of
  median wealth given up.
"""
        ),
        md(
            r"""

## 2 · Effective sample, stated first
"""
        ),
        code(
            r"""
rows = []
for y in (5, 10, 15, 20, 25, 30):
    a = st.accumulation_paths(r, y)
    d = st.path_dispersion(a, "multiple")
    if d:
        rows.append({"years": y, "n_paths": d["n_paths"],
                     "effective_n": d["effective_n"], "cv": d["cv"],
                     "ratio_95_05": d["ratio_95_05"]})
d = pd.DataFrame(rows).set_index("years")
print(d.round(3).to_string())
print()
print("Hundreds of start dates; a couple of independent ones. Every magnitude below")
print("inherits that. The BETWEEN-remedy comparisons in 3.5 share windows and do not.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Order invariance, verified
"""
        ),
        code(
            r"""
rng = np.random.default_rng(1008)
seg = r.to_numpy()[-int(25*252):]
lump = [st.terminal_lump_sum(rng.permutation(seg)) for _ in range(200)]
print(f"lump sum across 200 shuffles: min {min(lump):.10f}, max {max(lump):.10f}")
print(f"relative spread: {(max(lump)-min(lump))/np.mean(lump):.2e}")
print()
up = np.concatenate([np.full(3000, 0.0006), np.full(3000, -0.0002)])
down = up[::-1].copy()
print("A path that rises then falls, versus the same path reversed:")
print(f"  lump sum:    {st.terminal_lump_sum(up):.6f} vs "
      f"{st.terminal_lump_sum(down):.6f}")
print(f"  contributor: {st.terminal_with_contributions(up, 1/21):.2f} vs "
      f"{st.terminal_with_contributions(down, 1/21):.2f}")
print()
print("Identical for one, very different for the other. That gap is the whole study.")
"""
        ),
        md(
            r"""

### 3.2 The shuffle test — separating sequence from era
"""
        ),
        code(
            r"""
rows = []
for y in (10, 15, 20, 25):
    seg = r.to_numpy()[-int(y*252):]
    sh = st.shuffle_invariance(seg, contribution=1/21, n_shuffles=400)
    real = st.path_dispersion(st.accumulation_paths(r, y), "multiple")
    rows.append({"years": y, "pure_sequence_95_05": sh["sequence_spread"],
                 "observed_95_05": real["ratio_95_05"],
                 "sequence_share": (sh["sequence_spread"] - 1) /
                 max(real["ratio_95_05"] - 1, 1e-9)})
d = pd.DataFrame(rows).set_index("years")
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(d)); w = 0.38
ax.bar(x - w/2, d["pure_sequence_95_05"], w, color="#c0392b",
       label="pure sequence risk (distribution held fixed)")
ax.bar(x + w/2, d["observed_95_05"], w, color="#1f6feb",
       label="observed across real start dates")
ax.axhline(1.0, color="k", lw=1.5)
ax.set_xticks(x); ax.set_xticklabels([f"{y}y" for y in d.index])
ax.set_ylabel("95th / 5th percentile of outcomes"); ax.legend(fontsize=8)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The red bar is what remains when the return distribution is
> held *exactly* constant and only the order is scrambled. The gap up to the blue bar is
> different decades genuinely being different, which no glide path can address.
"""
        ),
        md(
            r"""

### 3.3 Contributions damp the lottery
"""
        ),
        code(
            r"""
lv = st.lottery_size_by_volatility(vols=(0.06, 0.10, 0.16, 0.24, 0.32, 0.45),
                                   years=25, n_paths=400)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(lv.index * 100, lv["lump_cv"], "o-", lw=2.5, color="#c0392b",
             label="lump sum")
axes[0].plot(lv.index * 100, lv["contrib_cv"], "s-", lw=2.5, color="#2ea44f",
             label="monthly contributions")
axes[0].set_xlabel("volatility (%)"); axes[0].set_ylabel("coefficient of variation")
axes[0].legend(fontsize=8)
axes[1].plot(lv.index * 100, lv["contrib_cv"] / lv["lump_cv"], "o-", lw=2.5,
             color="#1f6feb")
axes[1].axhline(1.0, color="k", ls="--", lw=1.5, label="no benefit")
axes[1].set_xlabel("volatility (%)")
axes[1].set_ylabel("contributor CV / lump-sum CV"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(lv.round(4).to_string())
"""
        ),
        md(
            r"""

### 3.4 The exposure profile
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for y, col in ((15, "#1f6feb"), (25, "#c0392b")):
    m = st.sequence_risk_metrics(r, y, n_buckets=8)
    if m.empty:
        continue
    axes[0].plot(m["years_to"] / y, m["corr_contributor"], "o-", lw=2,
                 color=col, label=f"{y}-year plan")
    axes[1].plot(m["years_to"] / y, m["corr_lump_sum"], "o-", lw=2, color=col,
                 label=f"{y}-year plan")
axes[0].set_xlabel("fraction of the horizon elapsed")
axes[0].set_ylabel("correlation with the final outcome")
axes[0].set_title("contributor: exposure builds", fontsize=10)
axes[0].legend(fontsize=8)
axes[1].set_xlabel("fraction of the horizon elapsed")
axes[1].set_ylabel("correlation with the final outcome")
axes[1].set_title("lump sum: flat, as arithmetic requires", fontsize=10)
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(st.sequence_risk_metrics(r, 25, n_buckets=8).round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The right-hand panel being flat is the control. If it sloped,
> the measurement would be picking up something other than cash-flow timing and the left-hand
> panel could not be trusted.
"""
        ),
        md(
            r"""

### 3.5 Remedies, scored on both columns
"""
        ),
        code(
            r"""
rows = []
for y in (10, 15, 20):
    t = st.remedy_comparison(e, b, y)
    if t.empty or "100% equity throughout" not in t.index:
        continue
    for name, row in t.iterrows():
        rows.append({"years": y, "remedy": name, **row.to_dict()})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(11, 5.5))
for name, g in d[d["remedy"] != "100% equity throughout"].groupby("remedy"):
    ax.plot(g["median_cost"] * 100, g["cv_reduction"] * 100, "o-", lw=1.5,
            label=name, alpha=0.85)
lim = max(d["median_cost"].max(), d["cv_reduction"].max()) * 105
ax.plot([0, lim], [0, lim], "k--", lw=2, label="one-for-one")
ax.set_xlabel("median wealth given up (%)")
ax.set_ylabel("dispersion removed (%)"); ax.legend(fontsize=8)
plt.show()
print(d.pivot(index="remedy", columns="years", values="efficiency").round(2)
      .to_string())
"""
        ),
        md(
            r"""

### 3.6 Glide-path shapes, and why the shape matters
"""
        ),
        code(
            r"""
h = 25 * 252
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for shape, col in (("constant", "#8b949e"), ("linear", "#1f6feb"),
                   ("late", "#2ea44f"), ("early", "#c0392b")):
    w = st.glide_path(h, 1.0, 0.3, shape)
    axes[0].plot(np.linspace(0, 25, h), w * 100, lw=2.5, color=col, label=shape)
axes[0].set_xlabel("years into the plan"); axes[0].set_ylabel("equity weight (%)")
axes[0].legend(fontsize=8)
m = st.sequence_risk_metrics(r, 25, n_buckets=8)
axes[1].plot(m["years_to"], m["corr_contributor"], "o-", lw=2.5, color="#c0392b")
axes[1].set_xlabel("years into the plan")
axes[1].set_ylabel("exposure to this period")
axes[1].set_title("compare the shapes against WHERE the risk is", fontsize=10)
plt.tight_layout(); plt.show()
print("The 'late' shape holds equity while exposure is low and de-risks where it")
print("is high. The 'early' shape does the reverse, which is why it scores worst.")
"""
        ),
        md(
            r"""

### 3.7 The decumulation mirror
"""
        ),
        code(
            r"""
rows = []
for w in (0.03, 0.04, 0.05, 0.06, 0.07, 0.08):
    dd = st.decumulation_paths(r, 25, w)
    rows.append({"rate": w, "ruin": dd["ruined"].mean(),
                 "median": dd["terminal"].median(),
                 "p05": dd["terminal"].quantile(0.05),
                 "corr_first5": dd["first_5y_cagr"].corr(dd["terminal"])})
d = pd.DataFrame(rows).set_index("rate")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].plot(d.index * 100, d["ruin"] * 100, "o-", lw=2.5, color="#c0392b")
axes[0].set_xlabel("withdrawal rate (%)"); axes[0].set_ylabel("% of start dates ruined")
dd = st.decumulation_paths(r, 25, 0.05)
axes[1].scatter(dd["first_5y_cagr"] * 100, dd["terminal"], s=28, alpha=0.6,
                color="#1f6feb")
axes[1].set_xlabel("return in the FIRST five years (% a year)")
axes[1].set_ylabel("terminal wealth after 25 years")
axes[1].set_title(f"correlation {dd['first_5y_cagr'].corr(dd['terminal']):+.2f}",
                  fontsize=10)
plt.tight_layout(); plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** For a saver the last years decide the outcome; for a retiree the
> first five do. Any glide path that de-risks smoothly across a lifetime is aimed at neither
> concentration.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
acc = st.accumulation_paths(r, 25)
d = st.path_dispersion(acc, "multiple")
dl = st.path_dispersion(acc, "lump_sum")
sh = st.shuffle_invariance(r.to_numpy()[-int(25*252):], 1/21, n_shuffles=400)
m = st.sequence_risk_metrics(r, 25, n_buckets=6)
rem = st.remedy_comparison(e, b, REMEDY_YEARS)
if rem.empty:
    rem = st.remedy_comparison(e, b, 15)
scored = rem.drop(index="100% equity throughout", errors="ignore")
scored = scored[np.isfinite(scored["efficiency"])]
best = scored["efficiency"].idxmax()
pd.DataFrame({
    "start dates tested": [d["n_paths"]],
    "effective independent observations": [d["effective_n"]],
    "best outcome": [d["max"]],
    "worst outcome": [d["min"]],
    "best / worst": [d["ratio_max_min"]],
    "95th / 5th, contributor": [d["ratio_95_05"]],
    "95th / 5th, lump sum": [dl["ratio_95_05"]],
    "pure sequence risk (shuffled)": [sh["sequence_spread"]],
    "exposure, first sixth": [m["corr_contributor"].iloc[0]],
    "exposure, final sixth": [m["corr_contributor"].iloc[-1]],
    "most efficient remedy": [best],
    "its dispersion reduction": [scored.loc[best, "cv_reduction"]],
    "its median cost": [scored.loc[best, "median_cost"]],
    "its efficiency": [scored.loc[best, "efficiency"]],
}).T.rename(columns={0: "value"})
"""
        ),
        md(
            r"""

## 5 · Going further

- **Estrada (2014)** finds conventional declining glide paths dominated across nineteen
  countries once both columns are scored. §3.5 reproduces that logic on one market; running it
  on a multi-country panel is the obvious extension and the one with real evidential weight.
- **Kitces & Pfau (2015)** argue for a *rising* equity glide in retirement, which §3.7's
  first-five-years concentration supports directly. Implementing a rising path in
  `glide_path` and scoring it on the decumulation paths would close that loop.
- **Human capital is the missing asset.** Bodie, Merton & Samuelson (1992): a young saver's
  bond-like future earnings are the real reason to hold equity early, not the horizon. Adding a
  labour-income stream would change §3.5's ranking and is the most important omission here.
- **Valuation-conditioned start dates.** The worst start dates in §1 cluster at high valuations.
  Conditioning the analysis on CAPE would turn a lottery into a partially forecastable one,
  which is either the most useful extension or the most dangerous, depending on how much you
  trust the conditioning.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
