"""Notebook builder for Study 1000 — The Cycle Hunt.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Cycle Hunt \U0001F30A
### Fourier says the market has cycles. Fourier says a coin toss has cycles too.

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Feed a price series into a Fourier transform and peaks come out. They always come out. The
periodogram of pure noise is not a flat line — it is a jagged mess, and its tallest spike is
several times the average by construction. A century of market-cycle theories has been built on
not knowing that.

> \U0001F4D3 **This is the plain-language layer.** Fisher's test, the AR(1) null and the power
> curve are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does a Fourier transform find peaks in the market? | Yes, several. |
| Are they bigger than a random walk's? | Barely, if at all. |
| Does the method work at all? | Yes — it finds natural gas's real annual cycle. |
| Could you trade the market's peak? | No. |
"""
        ),
        md(
            r"""

## 1 · The cycles in the stock market
"""
        ),
        code(
            r"""
from cyclehunt import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1000}
lead = assets[data.EQUITY]
pg = st.periodogram(lead)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(lead):,} sessions -> "
      f"{len(pg):,} frequency bins")
"""
        ),
        code(
            r"""
peaks = st.top_peaks(pg, 8, min_period=5.0, max_period=750.0)
fig, ax = plt.subplots(figsize=(12, 5))
d = pg[(pg["period"] >= 5) & (pg["period"] <= 750)]
ax.semilogx(d["period"], d["power"] / pg["power"].mean(), lw=0.7, color="#1f6feb")
for _, r in peaks.head(4).iterrows():
    ax.annotate(f"{r['period']:.0f}d\n({r['period'] / 252:.1f}y)",
                (r["period"], r["relative_power"]), fontsize=8,
                xytext=(0, 8), textcoords="offset points", ha="center")
ax.set_xlabel("period (trading sessions, log scale)")
ax.set_ylabel("power / average power")
ax.set_title("Peaks. Definitely peaks.")
plt.show()
print(peaks[["period", "relative_power"]].round(2).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** A chart like this, with the periods annotated in years, is how
> most cycle theories are introduced. Nothing on it is wrong. What is missing is the next
> chart.
"""
        ),
        md(
            r"""

## 2 · The same chart, for a coin toss
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(2, 2, figsize=(13, 7))
d = pg[(pg["period"] >= 5) & (pg["period"] <= 750)]
axes[0, 0].semilogx(d["period"], d["power"] / pg["power"].mean(), lw=0.7, color="#c0392b")
axes[0, 0].set_title(f"the real {data.EQUITY}", fontsize=10)
for ax, k in zip(axes.ravel()[1:], range(3)):
    sim = st.synthetic_series(n=len(lead), seed=1000 + k)
    p2 = st.periodogram(sim)
    d2 = p2[(p2["period"] >= 5) & (p2["period"] <= 750)]
    ax.semilogx(d2["period"], d2["power"] / p2["power"].mean(), lw=0.7, color="#8b949e")
    ax.set_title(f"a random walk (run {k})", fontsize=10)
for ax in axes.ravel():
    ax.set_ylim(0, max(12, d["power"].max() / pg["power"].mean() * 1.1))
    ax.set_xlabel("period (sessions)")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

Three of those four panels have no cycles in them whatsoever. Can you tell which one is the
market?
"""
        ),
        md(
            r"""

## 3 · Why noise looks cyclical

There is an exact answer here, not a hand-wave. Each point on a periodogram of white noise is an
independent draw from an exponential distribution. Take the largest of *m* such draws and you
expect about `log(m) + 0.577` times the mean.
"""
        ),
        code(
            r"""
theo = st.expected_max_relative_power(len(pg))
sim = st.spurious_peak_distribution(len(lead), n_sims=300, min_period=5.0)
actual = pg[pg["period"] >= 5]["power"].max() / pg["power"].mean()
fig, ax = plt.subplots(figsize=(10, 5))
rng = np.random.default_rng(1000)
draws = [st.spurious_peak_distribution(len(lead), n_sims=1, seed=2000 + k)["mean_max"]
         for k in range(0)]
ax.axvline(theo, color="#2ea44f", lw=2.5, label=f"theory: log(m)+0.577 = {theo:.1f}x")
ax.axvline(sim["median_max"], color="#8b949e", lw=2, ls="--",
           label=f"simulated median = {sim['median_max']:.1f}x")
ax.axvline(sim["p95_max"], color="#f0b429", lw=2, ls="--",
           label=f"simulated 95th pct = {sim['p95_max']:.1f}x")
ax.axvline(actual, color="#c0392b", lw=3,
           label=f"the actual market = {actual:.1f}x")
ax.set_xlabel("largest peak, as a multiple of average power")
ax.set_yticks([]); ax.legend(fontsize=9)
plt.show()
print(f"the market's best peak is {actual:.2f}x the average power")
print(f"a random walk of the same length gives {sim['median_max']:.2f}x on a typical run")
print(f"and exceeds {sim['p95_max']:.2f}x one time in twenty")
"""
        ),
        md(
            r"""

## 4 · The method is not broken — here is it working
"""
        ),
        code(
            r"""
ctrl = data.SEASONAL
if ctrl in assets:
    cs = assets[ctrl]
    cp = st.periodogram(cs)
    dc = cp[(cp["period"] >= 5) & (cp["period"] <= 750)]
    fig, ax = plt.subplots(figsize=(12, 4.5))
    ax.semilogx(dc["period"], dc["power"] / cp["power"].mean(), lw=0.8, color="#2ea44f")
    ax.axvline(252, color="#c0392b", ls="--", lw=2, label="one year")
    ax.set_xlabel("period (sessions)"); ax.set_ylabel("power / average")
    ax.set_title(f"{ctrl} — natural gas, which really does have an annual cycle")
    ax.legend(fontsize=9)
    plt.show()
    annual = st.top_peaks(cp, 3, min_period=180.0, max_period=400.0)
    print(annual[["period", "relative_power"]].round(2).to_string(index=False))
else:
    print(f"{ctrl} not available in this cache")
"""
        ),
        md(
            r"""

This is the control that makes the negative results mean something. A method that finds nothing
everywhere might simply be blind.
"""
        ),
        md(
            r"""

## 5 · The test that would have saved a century

Ronald Fisher worked out the right answer in 1929: compare the largest peak to the *total*
power, which correctly accounts for having looked at every frequency.
"""
        ),
        code(
            r"""
rows = []
for tk, s in assets.items():
    f = st.fisher_g_test(st.periodogram(s))
    rows.append({"asset": tk, "peak (d)": f["peak_period"],
                 "power": f["relative_power"], "Fisher p": f["p_value"],
                 "significant": f["significant_5pct"]})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 4.5))
colors = ["#2ea44f" if s else "#8b949e" for s in d["significant"]]
ax.bar(range(len(d)), d["Fisher p"], color=colors)
ax.axhline(0.05, ls="--", color="#c0392b", lw=1.5, label="5% level")
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index, rotation=20, ha="right",
                                                 fontsize=8)
ax.set_ylabel("Fisher p-value"); ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

## 6 · And the harder test: does the cycle stay put?
"""
        ),
        code(
            r"""
sp = st.split_sample_peak(lead, 5.0, 750.0)
print(f"best period in the first half:  {sp['period_first']:.1f} sessions")
print(f"best period in the second half: {sp['period_second']:.1f} sessions")
print(f"phase error: {sp['phase_error_fraction']:.0%} of a half-cycle")
print()
print("For comparison, a series that really does contain a 120-day cycle:")
real = st.synthetic_series(n=len(lead), period=120.0, amplitude=0.5)
sr = st.split_sample_peak(real, 5.0, 750.0)
print(f"  first half {sr['period_first']:.1f}, second half {sr['period_second']:.1f}, "
      f"phase error {sr['phase_error_fraction']:.0%}")
"""
        ),
        md(
            r"""

## 7 · The verdict

**Signal: Busted.** Across 7 assets the strongest spectral peak averaged **8.0× the average power**, which sounds like a finding until you compute what noise gives. With 3,882 frequency bins the periodogram ordinates are independent exponentials, so their maximum is expected at **8.8×** the mean — and simulating random walks of the same length put the 95th percentile at **10.3×**. Fisher's *g* test, which has had the correct answer since 1929, rejected the null for **0 of 7** assets against white noise and **1** against an AR(1) null — and the AR(1) column is the honest one, because returns are autocorrelated and a flat null tilts every test toward finding long cycles. The positive control worked: UNG, which has a genuine annual demand cycle, showed a peak at **246 sessions** (0.98 years), so the machinery detects cycles when they exist. On SPY the best period found in the first half of the sample was 14 sessions and in the second half 8, and the phase coherence was **0.49** against the 0.70 needed to call a cycle coherent — which is what no cycle looks like.

**Tradability: Partial.** Trading the best detected period out of sample — fitting the sinusoid on a rolling 1000-session window and taking the next step's sign — returned +2.47%/yr at a Sharpe of **0.22**, with a 52.2% hit rate against the 50% a coin gives, and 108 position changes a year to pay for. Buy-and-hold over the same window returned +9.65%. That is the expected outcome for a peak that is a peak because some bin has to be the largest.
"""
        ),
        md(
            r"""

## 8 · Going further \U0001F6AA

- **Print the noise band on every spectrum.** It costs one simulation and it changes how the
  chart reads entirely.
- **Test against the right null.** Returns are autocorrelated; a flat null makes long "cycles"
  appear that are only the autocorrelation.
- **Look for cycles where there is a mechanism.** Natural gas has weather. Retail has Christmas.
  Equity indices have nothing that would produce a 4.7-year sinusoid, which is a better reason
  to doubt one than any *p*-value.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Cycle Hunt — a quantitative teardown \U0001F52C
### Fisher's exact g test · AR(1) nulls · a natural-gas positive control · phase agreement

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Two corrections
do all the work: the multiple-comparison problem across frequency bins (Fisher solved it in
1929), and the fact that the right null is not white noise but an autocorrelated one.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from cyclehunt import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1000}
lead = assets[data.EQUITY]
pg = st.periodogram(lead)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(lead):,} sessions -> "
      f"{len(pg):,} frequency bins")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Busted | Across 7 assets the strongest spectral peak averaged **8.0× the average power**, which sounds like a finding until you compute what noise gives. With 3,882 frequency bins the periodogram ordinates are independent exponentials, so their maximum is expected at **8.8×** the mean — and simulating random walks of the same length put the 95th percentile at **10.3×**. Fisher's *g* test, which has had the correct answer since 1929, rejected the null for **0 of 7** assets against white noise and **1** against an AR(1) null — and the AR(1) column is the honest one, because returns are autocorrelated and a flat null tilts every test toward finding long cycles. The positive control worked: UNG, which has a genuine annual demand cycle, showed a peak at **246 sessions** (0.98 years), so the machinery detects cycles when they exist. On SPY the best period found in the first half of the sample was 14 sessions and in the second half 8, and the phase coherence was **0.49** against the 0.70 needed to call a cycle coherent — which is what no cycle looks like. |
| **Tradability** | Partial | Trading the best detected period out of sample — fitting the sinusoid on a rolling 1000-session window and taking the next step's sign — returned +2.47%/yr at a Sharpe of **0.22**, with a 52.2% hit rate against the 50% a coin gives, and 108 position changes a year to pay for. Buy-and-hold over the same window returned +9.65%. That is the expected outcome for a peak that is a peak because some bin has to be the largest. |

> \U0001F4A1 **In plain words.** The peaks are real numbers. What they are not is evidence,
> until compared against what noise of the same length produces.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (the null benchmark).** The largest ordinate of a white-noise periodogram over *m* bins
  is distributed with mean ≈ `log(m) + 0.577` times the spectrum.
- **H₂ (Fisher).** The exact test rejects at the nominal rate on white noise and detects a
  planted sinusoid.
- **H₃ (the right null).** Testing against an AR(1) rather than white noise materially changes
  which peaks survive, because returns are autocorrelated.
- **H₄ (positive control).** The method detects a genuine annual cycle where one exists.
- **H₅ (persistence).** A real cycle keeps its period *and phase* across sample halves; a
  spurious one keeps neither.
- **H₆ (power).** State the smallest amplitude the method could have detected, so that "found
  nothing" is a bounded claim.
"""
        ),
        md(
            r"""

## 2 · The periodogram, and the choices inside it
"""
        ),
        code(
            r"""
n = 2048
t = np.arange(n)
clean = pd.Series(np.sin(2 * np.pi * t / 64), index=pd.bdate_range("1993-02-01", periods=n))
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (name, series) in zip(axes, [
        ("pure 64-day sinusoid", clean),
        ("sinusoid + noise", clean + pd.Series(np.random.default_rng(1).normal(0, 3, n),
                                               index=clean.index)),
        ("noise only", pd.Series(np.random.default_rng(2).normal(0, 3, n),
                                 index=clean.index))]):
    p = st.periodogram(series)
    d = p[p["period"] >= 4]
    ax.semilogx(d["period"], d["power"] / p["power"].mean(), lw=0.8, color="#1f6feb")
    ax.axvline(64, color="#c0392b", ls="--", lw=1.5)
    ax.set_title(name, fontsize=10); ax.set_xlabel("period")
plt.tight_layout(); plt.show()
"""
        ),
        code(
            r"""
# detrending: the artefact that makes fake long cycles
rng = np.random.default_rng(1000)
n = 3000
trended = pd.Series(0.001 * np.arange(n) + rng.normal(0, 1, n),
                    index=pd.bdate_range("1993-02-01", periods=n))
fig, ax = plt.subplots(figsize=(11, 4.5))
for detrend, colour, label in ((False, "#c0392b", "not detrended"),
                               (True, "#2ea44f", "detrended")):
    p = st.periodogram(trended, detrend=detrend)
    d = p[p["period"] >= 4]
    ax.loglog(d["period"], d["power"] / p["power"].mean(), lw=0.9, color=colour,
              label=label)
ax.set_xlabel("period (sessions)"); ax.set_ylabel("power / average"); ax.legend(fontsize=9)
ax.set_title("A linear trend manufactures a 'cycle' the length of your sample")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The red line's giant low-frequency peak is not a cycle. It is a
> straight line. Nelson & Kang (1981) is the paper; the artefact is still everywhere.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The noise benchmark, three ways
"""
        ),
        code(
            r"""
rows = []
for n_obs in (500, 1000, 2000, 4000, 8000):
    sim = st.spurious_peak_distribution(n_obs, n_sims=200, min_period=5.0)
    rows.append({"n": n_obs, "bins": n_obs // 2, "theory": sim["theoretical"],
                 "sim mean": sim["mean_max"], "sim median": sim["median_max"],
                 "sim p95": sim["p95_max"]})
d = pd.DataFrame(rows).set_index("n")
fig, ax = plt.subplots(figsize=(9.5, 5))
ax.semilogx(d.index, d["theory"], "s--", lw=2, color="#2ea44f", label="log(m)+0.577")
ax.semilogx(d.index, d["sim mean"], "o-", lw=2, color="#1f6feb", label="simulated mean")
ax.fill_between(d.index, d["sim median"], d["sim p95"], alpha=0.15, color="#1f6feb",
                label="median to 95th pct")
ax.axhline(pg[pg["period"] >= 5]["power"].max() / pg["power"].mean(), color="#c0392b",
           lw=2, label=f"the real {data.EQUITY}")
ax.set_xlabel("observations"); ax.set_ylabel("largest peak / average power")
ax.legend(fontsize=8)
plt.show()
d.round(2)
"""
        ),
        md(
            r"""

### 3.2 Fisher's test: size and power
"""
        ),
        code(
            r"""
rejects = 0
n_runs = 60
for k in range(n_runs):
    x = st.synthetic_series(n=2000, seed=1000 + k)
    rejects += bool(st.fisher_g_test(st.periodogram(x)).get("significant_5pct"))
print(f"size on white noise: rejects in {rejects}/{n_runs} = {rejects / n_runs:.1%} "
      f"(nominal 5%)")
rows = []
for amp in (0.0, 0.05, 0.1, 0.15, 0.2, 0.3, 0.5):
    hits = 0
    for k in range(30):
        x = st.synthetic_series(n=4000, period=126.0, amplitude=amp, seed=1000 + k)
        hits += bool(st.fisher_g_test(st.periodogram(x)).get("significant_5pct"))
    rows.append({"amplitude (sd)": amp, "detection rate": hits / 30})
d = pd.DataFrame(rows).set_index("amplitude (sd)")
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.plot(d.index, d["detection rate"] * 100, "o-", lw=2, color="#2ea44f")
ax.axhline(80, ls="--", color="#8b949e", lw=1, label="80% power")
ax.axhline(5, ls=":", color="k", lw=1, label="nominal size")
ax.set_xlabel("planted amplitude (standard deviations)")
ax.set_ylabel("detected (%)"); ax.legend(fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

### 3.3 The AR(1) null, which is the right one
"""
        ),
        code(
            r"""
rows = []
for tk, s in assets.items():
    p = st.periodogram(s)
    a1 = st.ar1_null(s)
    pa = st.peak_against_ar1(p, a1["phi"])
    rows.append({"asset": tk, "phi": a1["phi"], "tilt": a1["spectrum_tilt"],
                 "peak (white)": pa["peak_period_white"],
                 "power (white)": pa["relative_power_white"],
                 "peak (AR1)": pa["peak_period_ar1"],
                 "power (AR1)": pa["relative_power_ar1"],
                 "same peak": pa["same_peak"]})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(3).to_string())
f = np.linspace(1 / 750, 0.5, 400)
fig, ax = plt.subplots(figsize=(10, 4.8))
for phi, colour in ((0.0, "#8b949e"), (0.1, "#2ea44f"), (0.3, "#f0b429"),
                    (-0.1, "#1f6feb")):
    sd = st.ar1_spectral_density(f, phi)
    ax.semilogx(1 / f, sd / sd.mean(), lw=1.8, color=colour, label=f"phi = {phi:+.1f}")
ax.set_xlabel("period (sessions)"); ax.set_ylabel("null spectrum / its mean")
ax.legend(fontsize=8)
ax.set_title("Even slight autocorrelation tilts the null toward long periods")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** A flat null says every period is equally likely a priori. An
> AR(1) null says long periods should already have more power. Testing a long-period peak
> against a flat null is grading it against the wrong baseline, and it is the reason "we found a
> multi-year cycle" is the most common false positive in this literature.
"""
        ),
        md(
            r"""

### 3.4 The positive control
"""
        ),
        code(
            r"""
ctrl = data.SEASONAL
rows = []
for tk, s in assets.items():
    p = st.periodogram(s)
    ann = st.top_peaks(p, 1, min_period=200.0, max_period=320.0)
    if ann.empty:
        continue
    rows.append({"asset": tk, "best annual-band period": ann.iloc[0]["period"],
                 "power": ann.iloc[0]["relative_power"]})
d = pd.DataFrame(rows).set_index("asset").sort_values("power", ascending=False)
fig, ax = plt.subplots(figsize=(10, 4.5))
colors = ["#2ea44f" if i == ctrl else "#8b949e" for i in d.index]
ax.bar(range(len(d)), d["power"], color=colors)
sim = st.spurious_peak_distribution(len(lead), n_sims=200, min_period=5.0)
ax.axhline(sim["p95_max"], ls="--", color="#c0392b", lw=1.5, label="noise 95th percentile")
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index, rotation=20, ha="right",
                                                 fontsize=8)
ax.set_ylabel("power in the annual band / average"); ax.legend(fontsize=8)
ax.set_title(f"Green = {ctrl}, which has a real annual cycle")
plt.show()
d.round(2)
"""
        ),
        md(
            r"""

### 3.5 Period and phase across sample halves
"""
        ),
        code(
            r"""
rows = []
for tk, s in assets.items():
    o = st.split_sample_peak(s, 5.0, 750.0)
    if "period_ratio" in o:
        rows.append({"asset": tk, **{k: o[k] for k in
                     ("period_first", "period_second", "period_ratio",
                      "amplitude_decay", "phase_error_fraction")}})
for amp, tag in ((0.5, "planted cycle"), (0.0, "planted noise")):
    x = st.synthetic_series(n=len(lead), period=120.0, amplitude=amp)
    o = st.split_sample_peak(x, 5.0, 750.0)
    rows.append({"asset": tag, **{k: o[k] for k in
                 ("period_first", "period_second", "period_ratio",
                  "amplitude_decay", "phase_error_fraction")}})
d = pd.DataFrame(rows).set_index("asset")
print(d.round(3).to_string())
fig, ax = plt.subplots(figsize=(10, 5))
colors = ["#2ea44f" if i == "planted cycle" else
          ("#c0392b" if i == "planted noise" else "#1f6feb") for i in d.index]
ax.barh(range(len(d)), d["phase_error_fraction"], color=colors)
ax.axvline(0.5, ls="--", color="k", lw=1.5, label="a random phase averages here")
ax.set_yticks(range(len(d))); ax.set_yticklabels(d.index, fontsize=8)
ax.set_xlabel("phase error (fraction of a half-cycle)"); ax.legend(fontsize=8)
plt.show()
"""
        ),
        md(
            r"""

### 3.6 Trading the peak, out of sample
"""
        ),
        code(
            r"""
best = st.top_peaks(pg, 1, 5.0, 750.0).iloc[0]["period"]
rows = []
for per in (10.0, 21.0, 42.0, 63.0, 126.0, 252.0, float(best)):
    t2 = st.cycle_trade(lead, per, fit_window=1000, cost_bps=5.0)
    if "sharpe" not in t2:
        continue
    rows.append({"period": per, "cagr": t2["cagr"], "sharpe": t2["sharpe"],
                 "hit rate": t2["hit_rate"], "switches/yr": t2["switches_per_year"]})
# and the same on a series with a genuine cycle
real = st.synthetic_series(n=len(lead), period=63.0, amplitude=1.0)
tr = st.cycle_trade(real, 63.0, fit_window=1000, cost_bps=5.0)
rows.append({"period": "63 (planted, real)", "cagr": tr["cagr"], "sharpe": tr["sharpe"],
             "hit rate": tr["hit_rate"], "switches/yr": tr["switches_per_year"]})
d = pd.DataFrame(rows).set_index("period")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 4.5))
colors = ["#2ea44f" if isinstance(i, str) else "#8b949e" for i in d.index]
ax.bar(range(len(d)), d["sharpe"], color=colors)
ax.axhline(0, color="k", lw=1)
ax.set_xticks(range(len(d)))
ax.set_xticklabels([str(i) if isinstance(i, str) else f"{i:.0f}" for i in d.index],
                   rotation=20, ha="right", fontsize=7)
ax.set_ylabel("out-of-sample Sharpe")
ax.set_title("Green = a cycle that genuinely exists")
plt.show()
"""
        ),
        md(
            r"""

### 3.7 Calibration
"""
        ),
        code(
            r"""
rows = []
for k in range(12):
    sim_x = st.synthetic_series(n=len(lead), seed=1000 + k)
    p2 = st.periodogram(sim_x)
    f2 = st.fisher_g_test(p2)
    pk = st.top_peaks(p2, 1, 5.0, 750.0)
    rows.append({"source": f"noise {k}", "period": pk.iloc[0]["period"],
                 "power": pk.iloc[0]["relative_power"], "fisher_p": f2["p_value"]})
pk_real = st.top_peaks(pg, 1, 5.0, 750.0)
f_real = st.fisher_g_test(pg)
rows.append({"source": f"THE REAL {data.EQUITY}", "period": pk_real.iloc[0]["period"],
             "power": pk_real.iloc[0]["relative_power"], "fisher_p": f_real["p_value"]})
d = pd.DataFrame(rows).set_index("source")
fig, ax = plt.subplots(figsize=(11, 4.8))
colors = ["#8b949e"] * (len(d) - 1) + ["#c0392b"]
ax.bar(range(len(d)), d["power"], color=colors)
ax.axhline(d["power"].iloc[:-1].mean(), ls="--", color="k", lw=1.5,
           label="average on noise")
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index, rotation=40, ha="right",
                                                 fontsize=7)
ax.set_ylabel("best peak / average power"); ax.legend(fontsize=8)
plt.show()
print(d.round(3).to_string())
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
f_real = st.fisher_g_test(pg)
sim = st.spurious_peak_distribution(len(lead), n_sims=250, min_period=5.0)
sp = st.split_sample_peak(lead, 5.0, 750.0)
a1 = st.ar1_null(lead)
pa = st.peak_against_ar1(pg, a1["phi"])
tr = st.cycle_trade(lead, float(st.top_peaks(pg, 1, 5.0, 750.0).iloc[0]["period"]),
                    1000, 5.0)
pd.DataFrame({
    "frequency bins": [len(pg)],
    "best peak (sessions)": [f_real["peak_period"]],
    "its power vs average": [f_real["relative_power"]],
    "noise 95th percentile": [sim["p95_max"]],
    "Fisher p": [f_real["p_value"]],
    "AR(1) coefficient": [a1["phi"]],
    "peak after AR(1) correction": [pa["peak_period_ar1"]],
    "period ratio across halves": [sp["period_ratio"]],
    "phase error": [sp["phase_error_fraction"]],
    "out-of-sample Sharpe": [tr["sharpe"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Multitaper estimation** (Thomson 1982) reduces the periodogram's variance properly instead
  of trading resolution for it the way a single taper does. It would sharpen every peak in
  section 1 and would not change the conclusion.
- **Wavelets.** A business cycle is not a sinusoid — it varies in length, which smears its power
  across bins and can hide it from a Fourier method entirely. A time-frequency decomposition is
  the right tool and would be a genuine follow-up rather than a refinement.
- **Print the null band, always.** The single highest-value change to how spectra are presented
  in finance is one extra line on the chart.
- **Look where there is a mechanism.** Natural gas has weather; retail has Christmas; equity
  indices have nothing that would generate a fixed multi-year sinusoid. A prior beats a
  *p*-value.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
