"""Real-tape runner -- Study 165 (Chinese-Zodiac).

Loads the cached FXI and ^GSPC daily tapes, runs the full analysis, and regenerates
docs/results.md with live numbers and fingerprints. Cache-first; pass --fetch to
hit the network and refresh the parquets.

    python studies/165-chinese-zodiac/examples/verify.py
    python studies/165-chinese-zodiac/examples/verify.py --fetch
"""

from __future__ import annotations

import io
import os
import sys

# Force UTF-8 output on Windows.
if hasattr(sys.stdout, "buffer"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from chinese_zodiac import data, strategy as st  # noqa: E402

_HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(_HERE, "..", "docs")


def main(fetch: bool = False) -> None:
    print("Study 165 -- Chinese-Zodiac -- real-tape verify\n")

    # Primary: FXI (China large-cap ETF, 2004-present)
    print("Loading FXI ...")
    ret_fxi = data.fetch_daily("FXI", fetch=fetch, start="2004-01-01")
    fp_fxi = data.fingerprint(ret_fxi)
    start_fxi = ret_fxi.index.min().date()
    end_fxi = ret_fxi.index.max().date()
    print(f"FXI: {start_fxi} to {end_fxi}  |  n={len(ret_fxi):,}  |  fp={fp_fxi}\n")

    # Secondary: ^GSPC (longer history for pre-CNY test)
    print("Loading ^GSPC ...")
    ret_gspc = data.fetch_daily("^GSPC", fetch=fetch, start="1994-01-01")
    fp_gspc = data.fingerprint(ret_gspc)
    start_gspc = ret_gspc.index.min().date()
    end_gspc = ret_gspc.index.max().date()
    print(f"^GSPC: {start_gspc} to {end_gspc}  |  n={len(ret_gspc):,}  |  fp={fp_gspc}\n")

    # --- (A) Pre-CNY rally on FXI ---
    print("--- Pre-CNY rally (FXI, 10-day window before CNY) ---")
    pre_fxi = st.pre_cny_stats(ret_fxi)
    print(f"  n_events = {pre_fxi['n_events']}")
    print(f"  mean pre-CNY return = {pre_fxi['mean_ret_pct']:+.2f}%")
    print(f"  baseline (random windows) = {pre_fxi['baseline_mean_pct']:+.2f}%")
    print(f"  diff = {pre_fxi['diff_pct']:+.2f}%")
    print(f"  HAC t-stat = {pre_fxi['hac_t']:+.2f}\n")

    print("--- Pre-CNY rally (^GSPC, 10-day window before CNY) ---")
    pre_gspc = st.pre_cny_stats(ret_gspc)
    print(f"  n_events = {pre_gspc['n_events']}")
    print(f"  mean pre-CNY return = {pre_gspc['mean_ret_pct']:+.2f}%")
    print(f"  baseline = {pre_gspc['baseline_mean_pct']:+.2f}%")
    print(f"  HAC t-stat = {pre_gspc['hac_t']:+.2f}\n")

    # --- (B) Zodiac-year effect on FXI ---
    print("--- Zodiac-year effect (FXI) ---")
    zs = st.zodiac_year_stats(ret_fxi)
    for animal, row in zs.iterrows():
        marker = " <-- Dragon" if animal == "Dragon" else ""
        print(
            f"  {animal:8s}: n={int(row['n_years']):2d}  "
            f"mean={row['mean_ret_pct']:+7.1f}%  "
            f"raw_t={row['raw_t']:+5.2f}  "
            f"bonf_p={row['bonferroni_p']:.3f}{marker}"
        )
    print()

    print("--- Dragon vs rest (FXI) ---")
    dr_fxi = st.dragon_vs_rest(ret_fxi)
    print(f"  Dragon: {dr_fxi['dragon_mean_pct']:+.1f}%  n={dr_fxi['n_dragon']}")
    print(f"  Rest:   {dr_fxi['rest_mean_pct']:+.1f}%  n={dr_fxi['n_rest']}")
    print(f"  Diff:   {dr_fxi['diff_pct']:+.1f}%")
    print(f"  Welch-t = {dr_fxi['welch_t']:+.2f}  Bonferroni-p = {dr_fxi['bonferroni_p']:.3f}\n")

    print("--- Permutation null (FXI) ---")
    perm = st.permutation_null(ret_fxi, n_perm=2000, seed=165)
    print(f"  Dragon mean: {perm['dragon_mean_pct']:+.1f}%")
    print(f"  Fraction of random animals as lucky: {perm['pct_as_good']:.2%}\n")

    # Period summaries
    ps_fxi = st.period_summary(ret_fxi)
    ps_gspc = st.period_summary(ret_gspc)

    # Write docs/results.md
    _write_results(
        ret_fxi, fp_fxi, start_fxi, end_fxi, ps_fxi, pre_fxi, zs, dr_fxi, perm,
        ret_gspc, fp_gspc, start_gspc, end_gspc, ps_gspc, pre_gspc,
    )
    print("docs/results.md updated.")


def _write_results(
    ret_fxi, fp_fxi, start_fxi, end_fxi, ps_fxi, pre_fxi, zs, dr_fxi, perm,
    ret_gspc, fp_gspc, start_gspc, end_gspc, ps_gspc, pre_gspc,
) -> None:
    from chinese_zodiac.data import ANIMALS

    os.makedirs(DOCS, exist_ok=True)
    lines = [
        "# Results -- Study 165 (Chinese-Zodiac)\n\n",
        "*Generated by [`examples/verify.py`](../examples/verify.py). "
        "Primary tape: FXI (iShares China Large-Cap ETF) daily returns, Yahoo Finance "
        "(auto-adjusted). Secondary: ^GSPC for pre-CNY context. Chinese New Year dates "
        "hardcoded from the official Chinese lunisolar calendar (1990-2026). "
        "As-of **2026-06-15**.*\n\n",
        "## Data stamp\n\n",
        "| Ticker | Window | n daily obs | Fingerprint |\n|---|---|---|---|\n",
        f"| FXI | {start_fxi} to {end_fxi} | {len(ret_fxi):,} | `{fp_fxi}` |\n",
        f"| ^GSPC | {start_gspc} to {end_gspc} | {len(ret_gspc):,} | `{fp_gspc}` |\n\n",
        "## Period summary (FXI)\n\n",
        "| CAGR | Ann. vol | Sharpe (daily) | Start | End |\n|---|---|---|---|---|\n",
        f"| {ps_fxi['cagr']:.2%} | {ps_fxi['vol_ann']:.2%} | {ps_fxi['sharpe']:.3f} "
        f"| {start_fxi} | {end_fxi} |\n\n",
        "## (A) Pre-CNY rally (10-day window before Chinese New Year)\n\n",
        "| Ticker | n events | Mean pre-CNY ret | Baseline (random) | Diff | HAC t |\n"
        "|---|--:|--:|--:|--:|--:|\n",
        f"| FXI | {pre_fxi['n_events']} | {pre_fxi['mean_ret_pct']:+.2f}% | "
        f"{pre_fxi['baseline_mean_pct']:+.2f}% | {pre_fxi['diff_pct']:+.2f}% | "
        f"{pre_fxi['hac_t']:+.2f} |\n",
        f"| ^GSPC | {pre_gspc['n_events']} | {pre_gspc['mean_ret_pct']:+.2f}% | "
        f"{pre_gspc['baseline_mean_pct']:+.2f}% | {pre_gspc['diff_pct']:+.2f}% | "
        f"{pre_gspc['hac_t']:+.2f} |\n\n",
        "## (B) Zodiac-year returns (FXI)\n\n",
        "| Animal | n years | Mean annual return | Raw Welch t | Bonferroni-p (x12) |\n"
        "|---|--:|--:|--:|--:|\n",
    ]
    for animal in ANIMALS:
        if animal not in zs.index:
            continue
        row = zs.loc[animal]
        flag = " **<-- Dragon**" if animal == "Dragon" else ""
        lines.append(
            f"| **{animal}**{flag} | {int(row['n_years'])} | "
            f"{row['mean_ret_pct']:+.1f}% | {row['raw_t']:+.2f} | "
            f"{row['bonferroni_p']:.3f} |\n"
        )
    lines += [
        "\n**Key findings (zodiac-year effect):**\n\n",
        f"- Dragon years: mean annual return {dr_fxi['dragon_mean_pct']:+.1f}%  "
        f"(n = {dr_fxi['n_dragon']} years, Welch t = {dr_fxi['welch_t']:+.2f}, "
        f"Bonferroni-p = {dr_fxi['bonferroni_p']:.3f}).\n",
        f"- Other 11 animals: mean {dr_fxi['rest_mean_pct']:+.1f}%.\n",
        f"- Permutation null: {perm['pct_as_good']:.1%} of randomly chosen animals "
        f"are as 'lucky' as Dragon.\n",
        "- **Effective n per animal ~3. No test on n=3 is meaningful regardless of the t-stat.**\n\n",
        "## Verdict\n\n",
        "- **Signal -- NONE.** Pre-CNY HAC t indistinguishable from zero on both FXI and ^GSPC. "
        "Zodiac-year effect: n ~3 per animal, no Bonferroni-corrected p clears 0.05. "
        "Tiny n makes any apparent Dragon premium pure noise.\n",
        "- **Tradability -- MIRAGE.** No signal to trade; turnover and spread on pre-CNY "
        "window trades would bury any sub-1% observed premium.\n",
        "- **Lucky Dragon? -- Busted.** 12 animals x ~3 years is structurally too small "
        "to ever clear the inference bar. The permutation null confirms Dragon has no "
        "special standing in a fair draw.\n",
    ]
    with open(os.path.join(DOCS, "results.md"), "w", encoding="utf-8") as f:
        f.writelines(lines)


if __name__ == "__main__":
    fetch = "--fetch" in sys.argv
    main(fetch=fetch)
