"""SCAFFOLD — copy this file to studies/NN-your-idea/notebooks/ and fill it in.

The two narrative notebooks are a *generated artefact*. Edit the cell text here,
then rebuild + execute to embed figures/outputs:

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks follow the SAME seven desk beats (see ../../../METHODOLOGY.md):
  0 Verdict · 1 The Claim · 2 So What? · 3 How We'd Know · 4 The Teardown ·
  5 The Verdict · 6 Could You Trade It? · 7 Going Further
— the same story told at two altitudes:
  01_for_the_curious  — the plain-language layer
  02_for_the_quants   — the deep layer: data, inference, microstructure, capacity

HERO CONVENTION (cell 0 of each notebook): a tight H1 + one-line subtitle, then a
row of shields verdict badges, then a 2–3 sentence lede, then the callout block.
The badge palette is shared with the landing table and the front-card — keep it
consistent (see the VERDICT BADGES note in ../README.md):
  Signal      REAL→2ea44f   WEAK/MIXED→dab617   NONE→c0392b
  Tradability INVESTABLE→2ea44f   FRAGILE→dab617   MIRAGE→c0392b
  3rd "myth-check" axis (BUSTED / NOT SUPPORTED / CONFIRMED / PRE-REG …)→8b949e
  Labelled form in heroes: badge/{Axis}-{Verdict}-{colour}?style=flat-square
  Text encoding: space→_  ·  literal hyphen→--  ·  '?'→%3F

NOTE the _write CONVENTION: each build_*() ends by calling _write(nb, name). The
repo's intro-restyle tooling captures notebooks by monkeypatching _write, so keep
this shape (don't return the notebook and write it in main()).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/ lives there)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
"""


def md(text):
    return new_markdown_cell(text)


def code(text):
    return new_code_cell(text)


# ===========================================================================
# 01 — FOR THE CURIOUS   (the plain-language layer of the seven beats)
# ===========================================================================
def build_curious():
    cells = [
        # ---- HERO (cell 0) ---------------------------------------------------
        md(
            "# {{Study title}} {{emoji}}\n"
            "### {{one-line plain-English hook / question}}\n\n"
            "![Signal: {{S}}](https://img.shields.io/badge/Signal-{{S}}-{{colour}}?style=flat-square)\n"
            "![Tradability: {{T}}](https://img.shields.io/badge/Tradability-{{T}}-{{colour}}?style=flat-square)\n"
            "![{{Axis3}}: {{V}}](https://img.shields.io/badge/{{Axis3}}-{{V}}-8b949e?style=flat-square)\n\n"
            "{{2–3 sentence plain-English lede: the weird fact / the claim, why it's "
            "interesting, what this notebook will do.}}\n\n"
            "> 📓 **This is the plain-language layer.** Want the statistics, the "
            "microstructure and the capacity maths? That's the companion notebook, "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** An educational, reproducible research tool: "
            "every chart below is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        # ---- BEAT 0 — VERDICT, READ FIRST ------------------------------------
        md(
            "## The answer first 🎯\n\n"
            "{{The whole study in one little box; the rest is *why*. A short Q&A table or "
            "the verdict stamps, in plain words.}}"
        ),
        # ---- BEAT 1 — THE CLAIM ----------------------------------------------
        md("## 1 · The claim\n\n{{State it at full strength, the way believers do.}}"),
        # ---- BEAT 2 — SO WHAT? -----------------------------------------------
        md("## 2 · So what?\n\n{{The stakes, concrete: money, meaning, who's right.}}"),
        # ---- BEAT 3 — HOW WE'D KNOW ------------------------------------------
        md("## 3 · How would we even know?\n\n{{The falsifiable test, the data, the traps.}}"),
        # ---- BEAT 4 — THE TEARDOWN -------------------------------------------
        md("## 4 · The teardown — let's actually look\n\n{{Findings in narrative order.}}"),
        # code(...)  # one result, one figure at a time — let the charts carry it
        # ---- BEAT 5 — THE VERDICT --------------------------------------------
        md("## 5 · The verdict\n\n{{Restate each stamp, now earned.}}"),
        # ---- BEAT 6 — COULD YOU TRADE IT? ------------------------------------
        md("## 6 · Could you actually trade it?\n\n{{Costs, capacity, the line where it dies.}}"),
        # ---- BEAT 7 — GOING FURTHER ------------------------------------------
        md("## 7 · Going further 🚪\n\n{{Open threads; what to fork.}}"),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS   (the deep layer of the same seven beats)
# ===========================================================================
def build_quants():
    cells = [
        # ---- HERO (cell 0) ---------------------------------------------------
        md(
            "# {{Study title}} — a quantitative teardown 🔬\n"
            "### {{deck of method keywords, e.g. 'Real data · robust inference · capacity · falsifiability'}}\n\n"
            "![Signal: {{S}}](https://img.shields.io/badge/Signal-{{S}}-{{colour}}?style=flat-square)\n"
            "![Tradability: {{T}}](https://img.shields.io/badge/Tradability-{{T}}-{{colour}}?style=flat-square)\n"
            "![{{Axis3}}: {{V}}](https://img.shields.io/badge/{{Axis3}}-{{V}}-8b949e?style=flat-square)\n\n"
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) "
            "— *same seven beats, every claim now carrying its standard error.* "
            "{{one sentence of this study's framing}}\n\n"
            "> ⚠️ **Not investment advice.** {{data sources + mode + methods + "
            "[`docs/references.md`](../docs/references.md)}}\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into "
            "intuition — so this notebook still reads even if you skim the maths. House "
            "style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT + "\nfrom quantlab import data, decompose, diagnostics, backtest, stats, analytics\n"),

        # ---- BEAT 0 — VERDICT, UP FRONT --------------------------------------
        md(
            "## Verdict, up front\n\n"
            "{{The stamps in a table (Axis · Stamp · Why); the rest of the notebook is the "
            "evidence that earns them. Add a `> 💡 In plain words` gloss.}}"
        ),
        # ---- BEATS 1–7 (deep layer) ------------------------------------------
        md("## 1 · The claim, steelmanned\n\n{{H₁/H₂/H₃ as testable hypotheses.}}"),
        md("## 2 · So what? — what rides on each answer\n\n{{Quantitative stakes.}}"),
        md("## 3 · How we'd know — the protocol\n\n{{Decompose · robust inference · critique · alpha-vs-beta · capacity.}}"),
        md("## 4 · The teardown\n\n{{Each result with its test statistic, CI, the confound ruled out.}}"),
        md("## 5 · The verdict\n\n{{The decisive statistics in one place.}}"),
        md("## 6 · Could you trade it?\n\n{{Break-even cost vs edge, square-root impact capacity, net Sharpe.}}"),
        md("## 7 · Going further\n\n{{Open questions, the next experiment, what to fork.}}"),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
