"""Generate the two narrative notebooks for Study 36 (Greenback) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs OFFLINE on the seeded synthetic FX panel (a carry premium + risk-off crashes + an
independent trend the momentum sleeve rides). The real-tape G10 verdict is **PENDING** one networked FRED
rates fetch (which times out in this sandbox) — see ../docs/results.md. Both notebooks walk the SAME seven
desk beats. Greenback is the dollar-carry / carry⊕momentum-combo companion to Study 27 (Steamroller).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from greenback import data, strategy, costs, extension

# Offline synthetic control: a currency panel with a carry premium + risk-off crashes + an independent
# trend for the momentum sleeve (the machinery) + a full-UIRP carry null. The real G10 verdict is PENDING
# one networked FRED fetch — see ../docs/results.md.
xr, rd, truth = data.synthetic_fx(carry_strength=0.9, trend_strength=0.35, seed=36)
x0, r0, _ = data.synthetic_fx(carry_strength=0.0, trend_strength=0.35, seed=36)
print(f"synthetic control: {truth.n_ccy} currencies x {truth.n_months} months, "
      f"carry_strength {truth.carry_strength} (null=0), trend_strength {truth.trend_strength}")
"""

# Synthetic control numbers (seed 36, net @10 bp) — these match the executed cells; the REAL G10 tape is PENDING.
R = dict(
    hml="5.3", null_hml="0.8",
    carry_sh="1.18", carry_skew="-1.55", carry_dd="-60", carry_worst="-13.7",
    dollar_sh="0.17", mom_sh="1.53", mom_dd="-18",
    combo_sh="1.69", combo_dd="-20", corr="0.26",
    combo_worst5="-9.3", carry_worst5="-11.0",
    mom_be="14.6",
    c0="1.75", c10="1.69", c25="1.59", c50="1.44", c100="1.13",
)

BADGES = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Real-tape run?: Pre-reg](https://img.shields.io/badge/Real--tape_run%3F-Pre--reg-8b949e?style=flat-square)\n\n"
)

PENDING = (
    "> ⚠️ **Real run PENDING one fetch.** The carry signal needs **G10 short rates from FRED**, whose "
    "download **times out** in this sandbox — so this notebook executes OFFLINE on the synthetic control "
    "and the real-tape verdict is *pre-registered* in [`../docs/results.md`](../docs/results.md), awaiting "
    "one networked `python examples/verify.py --fetch`."
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Greenback 💵\n"
            "### \"Borrow cheap, lend dear\" earns a real premium — and rents you a spot in front of a steamroller. The fix isn't a stop-loss; it's a second, decorrelated trade.\n\n"
            + BADGES +
            "This builds on [Steamroller](../../27-steamroller/), which showed the FX **carry** premium is "
            "real but crash-prone, and that vol-targeting *can't* dodge the crash. Greenback asks the next "
            "question — the one carry desks actually trade: pair carry with its natural complement, "
            "**momentum** (ride the trend), and add a **dollar-carry** tilt (long/short the USD basket by "
            "the average rate gap). Because carry and momentum pay at *different times*, the **combo** earns "
            "a higher Sharpe than either alone — and momentum tends to lean the other way exactly when "
            "carry is being run over, cushioning the crash.\n\n"
            "> 📓 **Plain-language layer.** The three sleeves, the combo uplift, the leg correlation and the "
            "crash cushion are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Charts below are generated by the code beside them; the core "
            "runs on a **synthetic** currency panel, so the real G10 numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are PENDING one FRED fetch. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 💵\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Do high-rate currencies out-earn? | 🟩 **Yes.** Carry high-minus-low **+{hml}%/yr**; carry "
            "Sharpe **{cs}** (null is flat at +{nh}%/yr). |\n"
            "| Is there a steamroller? | 🟨 **Yes.** Carry skew **{csk}**, max drawdown **{cdd}%** — the "
            "negative-skew crash carry can't escape. |\n"
            "| Does the carry⊕momentum combo help? | 🟩 **Yes.** Combo Sharpe **{cob}** beats carry **{cs}** "
            "and momentum **{ms}** (legs correlate just **{corr}**), and the drawdown falls **{cdd}% → "
            "{codd}%**. |\n"
            "| Real G10 tape? | ⚪ **Pre-registered.** Needs FRED short rates (times out here) — PENDING one "
            "fetch. |\n\n"
            "> Desk shorthand: **Signal `REAL` · Tradability `FRAGILE` · Real-tape run? `PRE-REG`** — a real "
            "premium, dulled (not de-fanged) by diversification.".format(
                hml=R['hml'], cs=R['carry_sh'], nh=R['null_hml'], csk=R['carry_skew'], cdd=R['carry_dd'],
                cob=R['combo_sh'], ms=R['mom_sh'], corr=R['corr'], codd=R['combo_dd'])
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "The FX carry trade and its complements (Kakushadze-Serur §8.3 dollar carry, §8.4 momentum+carry):\n\n"
            "1. **Carry** — long the high-short-rate currencies, short the low-rate ones, dollar-neutral. "
            "Uncovered interest-rate parity fails, so the rate gap is a paid premium.\n"
            "2. **Dollar carry** — long the whole basket vs USD when foreign rates are high vs the dollar, "
            "short it when they're low (the LRV *dollar factor*).\n"
            "3. **Momentum** — long the currencies trending up, short those trending down.\n"
            "4. **The combo** — blend carry and momentum; the believer's case (Asness-Moskowitz-Pedersen "
            "2013; Koijen et al 2018) is that they pay at different times, so the blend beats either leg."
        ),
        code(
            "carry = strategy.carry_returns(xr, rd, cost_bps=10.0)         # vol-scaled, net @10bp\n"
            "eq = (1+carry).cumprod()\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(eq.index, eq.values, color='#2ea44f', lw=1.1)\n"
            "ax.set_title('Carry on a panel where high rates truly out-earn — steady gains, then a crash')\n"
            "s = strategy.summary(carry); print(f\"synthetic carry Sharpe {s['sharpe']:.2f}, skew {s['skew']:.2f}, max DD {s['max_drawdown']*100:.0f}%\")"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "A real, self-financed premium that diversifies a stock/bond book is worth a lot — carry and "
            "trend are the backbone of every macro and CTA desk. But carry's catch is famous: it drips "
            "nickels and then loses a fortune all at once (1998, 2008). The interesting question isn't "
            "whether carry is real (it is) — it's whether you can hold it through the steamroller. The "
            "believers' answer is *diversification*: pair it with momentum, which tends to be short the "
            "crashing currencies just as carry is long them."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "1. **Real?** Carry premium by rate bucket and gross Sharpe on the panel (flat on a full-UIRP null).\n"
            "2. **Crash?** The carry book's skew, worst month and drawdown.\n"
            "3. **Does the combo help?** Combo Sharpe vs either leg, the leg correlation, and the combo's "
            "drawdown vs carry's.\n\n"
            "**Mirage line:** if the combo *didn't* beat the better leg, or the legs were highly correlated, "
            "the diversification story would be a mirage. (On the real tape, a further fragility line is the "
            "carry crash deepening rather than dulling.)"
        ),

        md("## 4 · The teardown 🔧\n\n### 4a · The premium is real where carry is real (control vs null)"),
        code(
            "for label, (xx, rr) in [('carry panel', (xr, rd)), ('full-UIRP null', (x0, r0))]:\n"
            "    pb = strategy.carry_premium_by_bucket(xx, rr)\n"
            "    s = strategy.summary(strategy.carry_returns(xx, rr, cost_bps=0.0, target_vol_ann=None))\n"
            "    print(f\"{label:16} high-minus-low {pb['hml_ann_pct']:+5.1f}%/yr   carry Sharpe {s['sharpe']:+.2f}\")"
        ),
        md(
            "### 4b · The three sleeves and the combo\n"
            "Net @10 bp on the synthetic control — carry crashes, momentum doesn't, and the combo beats both:"
        ),
        code(
            "carry = strategy.carry_returns(xr, rd, cost_bps=10.0)\n"
            "mom   = strategy.momentum_returns(xr, cost_bps=10.0)\n"
            "combo = strategy.combine(carry, mom)\n"
            "dollar = strategy.dollar_carry_returns(xr, rd, cost_bps=10.0)\n"
            "rows = {}\n"
            "for nm, r in [('carry', carry), ('dollar-carry', dollar), ('momentum', mom), ('COMBO', combo)]:\n"
            "    s = strategy.summary(r); rows[nm] = {'Sharpe': s['sharpe'], 'ret%': s['ann_return']*100, 'skew': s['skew'], 'maxDD%': s['max_drawdown']*100}\n"
            "display(pd.DataFrame(rows).T.round(2))\n"
            "for nm, r, c in [('carry', carry, '#c0392b'), ('momentum', mom, '#8b949e'), ('combo', combo, '#2ea44f')]:\n"
            "    plt.plot((1+r).cumprod(), label=nm, color=c, lw=1.1)\n"
            "plt.legend(); plt.title('Carry crashes, momentum cushions — the combo grows steadier than either leg'); plt.yscale('log')"
        ),

        md("## 5 · The verdict 🧾\n\n"
           f"- **Signal `REAL`** — carry high-minus-low **+{R['hml']}%/yr**, carry Sharpe **{R['carry_sh']}**, "
           f"momentum **{R['mom_sh']}**; the null is flat (**+{R['null_hml']}%/yr**).\n"
           f"- **Tradability `FRAGILE`** — the steamroller: carry skew **{R['carry_skew']}**, drawdown "
           f"**{R['carry_dd']}%**. The combo *dulls* it (DD **{R['carry_dd']}% → {R['combo_dd']}%**) but the "
           "jump never fully goes away.\n"
           "- **Real-tape run? `PRE-REG`** — pre-registered, PENDING one FRED fetch.\n\n"
           "> **The honest fix isn't a stop — it's a second trade.** Study 27 showed vol-targeting can't "
           "dodge the carry crash. Pairing carry with decorrelated momentum can *cushion* it."),

        md("## 6 · Could you trade it? 💸\n\n"
           f"- **Cheap to run.** Carry rebalances slowly (rate gaps crawl), so cost isn't the threat; "
           f"momentum costs more (break-even ≈ {R['mom_be']} bp) but the combo's Sharpe decays gently "
           f"(**{R['c0']} → {R['c100']}** from 0 to 100 bp).\n"
           "- **The threat is the crash, not the cost.** Even diversified, the combo keeps a negative skew — "
           "you must be *willing and able* to hold a crash-prone book through its worst months.\n"
           "- **Capacity** is large (G10 FX is the deepest market on earth); the binding constraint is risk "
           "tolerance, not liquidity. Hence `FRAGILE`, not `INVESTABLE`."),

        md(
            "## 7 · Going further 🚪\n\n"
            "### Worked complement — the carry⊕momentum diversification ([`../docs/extension.md`](../docs/extension.md))\n"
            "The headline of the study, made explicit:\n\n"
            f"- The combo Sharpe **{R['combo_sh']}** beats carry **{R['carry_sh']}** and momentum "
            f"**{R['mom_sh']}**, because the legs correlate only **{R['corr']}**.\n"
            f"- Momentum cushions the steamroller: combo drawdown **{R['combo_dd']}%** vs carry "
            f"**{R['carry_dd']}%**, and in carry's worst 5 months the combo lost **{R['combo_worst5']}%** vs "
            f"carry **{R['carry_worst5']}%**.\n"
            "- But the combo is still negatively skewed — diversification dulls the crash, it doesn't remove it.\n\n"
            "### Other forks\n"
            "- **Optimal combo weight** — sweep `w_carry` and risk-parity vs the realised crisis correlation.\n"
            "- **Dollar-carry as a third leg** — add the LRV dollar factor (real tape, where the USD rate cycles).\n"
            "- **Crisis-conditional tilt** — lean toward momentum when global FX vol is rising.\n\n"
            "PRs welcome — and the real G10 numbers land the moment someone runs `examples/verify.py --fetch` "
            "where FRED is reachable."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Greenback — a quantitative teardown 🔬\n"
            "### The carry premium by bucket · three sleeves · the combo's Sharpe uplift · the leg correlation · the negative-skew crash\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its number.* The steelman: FX carry is a real premium (§8.3/§8.4 of "
            "Kakushadze-Serur), and the **carry⊕momentum combo** beats either leg because the two "
            "decorrelate. We confirm carry is `REAL` (high-minus-low +5.3%/yr, Sharpe +1.18, null flat), "
            "that it carries the `FRAGILE` steamroller (skew −1.55, DD −60%), and that the combo lifts the "
            "Sharpe to +1.69 while halving-plus the drawdown — building on Study 27 (Steamroller), not "
            "repeating it.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on a synthetic FX panel; the real G10 run is "
            "PENDING one FRED fetch in [`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            f"| **Signal** — carry & momentum real? | 🟢 `REAL` | High-minus-low **+{R['hml']}%/yr**, carry "
            f"Sharpe **{R['carry_sh']}**, momentum **{R['mom_sh']}**; null flat (**+{R['null_hml']}%/yr**). |\n"
            f"| **Tradability** | 🟡 `FRAGILE` | Carry skew **{R['carry_skew']}**, DD **{R['carry_dd']}%**; "
            f"the combo dulls it (**{R['carry_dd']}% → {R['combo_dd']}%**) but the jump remains. |\n"
            "| **Real-tape run?** | ⚪ `Pre-reg` | Needs FRED short rates (time out here) — PENDING one fetch. |\n\n"
            "> **In one sentence:** a real FX carry premium with a brutal negative-skew crash, *cushioned* "
            "(not removed) by blending in decorrelated momentum — the combo Sharpe **+1.69** beats either "
            "leg and the drawdown falls to **−20%**.\n\n"
            "*(This notebook executes on the synthetic control; the real G10 numbers are PENDING in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Carry weight $w^{c}_{i,t}\\propto \\text{sign of rank}(r_{i}-\\bar r)$ — long the top, short the "
            "bottom rate-differential quantile, dollar-neutral, lagged. Momentum weight "
            "$w^{m}_{i,t}\\propto \\text{rank of }\\big(\\prod_{k=1}^{12}(1+x_{i,t-k})-1\\big)$. Both legs are "
            "vol-scaled to a common target, then the **combo** is $\\tfrac12 c_t+\\tfrac12 m_t$. Claim: "
            "$\\text{Sharpe}(\\text{combo})>\\max(\\text{Sharpe}(c),\\text{Sharpe}(m))$ and "
            "$\\text{corr}(c,m)$ is low. Null: full UIRP ⇒ no carry premium (the spot exactly offsets the "
            "rate gap)."
        ),
        code(
            "for label, (xx, rr) in [('carry panel', (xr, rd)), ('null', (x0, r0))]:\n"
            "    pb = strategy.carry_premium_by_bucket(xx, rr)\n"
            "    s = strategy.summary(strategy.carry_returns(xx, rr, cost_bps=0.0, target_vol_ann=None))\n"
            "    print(f\"{label:12} high-minus-low {pb['hml_ann_pct']:+5.1f}%/yr   carry Sharpe {s['sharpe']:+.2f}   skew {s['skew']:+.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** When carry is real the high-rate bucket out-earns the low-rate bucket "
            f"(**+{R['hml']}%/yr**) and the carry book makes money with a sharp negative skew; under full "
            f"UIRP it's flat (**+{R['null_hml']}%/yr**). The apparatus sees carry only when it's there — so "
            "the real-tape result is about the *market*."
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Lustig-Roussanov-Verdelhan (2011) show carry and the dollar factor are *priced* currency risk "
            "premia; Asness-Moskowitz-Pedersen (2013) and Koijen et al (2018) show carry/value and momentum "
            "are negatively correlated *everywhere*, so combining them is the single highest-Sharpe move in "
            "factor investing. The pre-registered prediction: the combo beats either leg and momentum leans "
            "*against* the carry crash. Beats 4-7 test that head-on."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Real?** `carry_premium_by_bucket` + `carry_returns` (gross) on control vs null.\n"
            "2. **Crash?** the carry book's `skew`, worst month, `max_drawdown` (`extension.carry_crash`).\n"
            "3. **Combo?** `extension.diversification` — combo Sharpe vs legs, the leg correlation.\n"
            "4. **Costs?** `costs.cost_sweep`, `costs.breakeven_cost_bps`.\n\n"
            "**Mirage line:** combo fails to beat the better leg, or the legs are highly correlated — then "
            "the diversification story is a mirage."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · The three sleeves (net @10 bp)"),
        code(
            "carry = strategy.carry_returns(xr, rd, cost_bps=10.0)\n"
            "mom   = strategy.momentum_returns(xr, cost_bps=10.0)\n"
            "combo = strategy.combine(carry, mom)\n"
            "dollar = strategy.dollar_carry_returns(xr, rd, cost_bps=10.0)\n"
            "rows = {}\n"
            "for nm, r in [('carry', carry), ('dollar-carry', dollar), ('momentum', mom), ('COMBO', combo)]:\n"
            "    s = strategy.summary(r)\n"
            "    rows[nm] = {'Sharpe': s['sharpe'], 'ret%': s['ann_return']*100, 'vol%': s['vol_ann']*100, 'skew': s['skew'], 'maxDD%': s['max_drawdown']*100}\n"
            "display(pd.DataFrame(rows).T.round(2))"
        ),
        md(
            "> 💡 **In plain words.** Carry and momentum both earn — but carry crashes (skew −1.55, DD −60%) "
            "and momentum doesn't (DD −18%). The dollar-carry tilt is weak *on this synthetic* because the "
            "average rate gap is near-constant by construction; on the real tape, where the USD rate cycles, "
            "it's a genuine separate premium (that's what `--fetch` measures)."
        ),

        md("### 4b · The combo beats the legs, and the legs decorrelate (the REAL diversification call)"),
        code(
            "d = extension.diversification(xr, rd, cost_bps=10.0)\n"
            "print(f\"carry Sharpe {d['carry_sharpe']:+.2f}  momentum {d['momentum_sharpe']:+.2f}  combo {d['combo_sharpe']:+.2f}\")\n"
            "print(f\"combo beats both legs: {d['combo_beats_legs']}   carry-momentum correlation {d['leg_correlation']:+.2f}\")\n"
            "fig, ax = plt.subplots()\n"
            "for nm, r, c in [('carry', carry, '#c0392b'), ('momentum', mom, '#8b949e'), ('combo', combo, '#2ea44f')]:\n"
            "    ax.plot((1+r).cumprod(), label=nm, color=c, lw=1.1)\n"
            "ax.legend(); ax.set_yscale('log'); ax.set_title('Equal-risk carry+momentum combo grows steadier than either leg')"
        ),

        md("### 4c · The steamroller, and how momentum cushions it (the FRAGILE call)"),
        code(
            "cc = extension.carry_crash(xr, rd, cost_bps=10.0)\n"
            "print(f\"carry: skew {cc['carry_skew']:+.2f}, worst month {cc['carry_worst_month_pct']:+.1f}%, max DD {cc['carry_max_dd_pct']:.0f}%\")\n"
            "print(f\"combo: skew {cc['combo_skew']:+.2f}, worst month {cc['combo_worst_month_pct']:+.1f}%, max DD {cc['combo_max_dd_pct']:.0f}%\")\n"
            "print(f\"in carry's worst 5 months, combo lost {cc['combo_in_carry_worst5_pct']:+.1f}% vs carry {cc['carry_worst5_mean_pct']:+.1f}%\")\n"
            "fig, ax = plt.subplots()\n"
            "for nm, r, c in [('carry', carry, '#c0392b'), ('combo', combo, '#2ea44f')]:\n"
            "    eq = (1+r).cumprod(); ax.plot(eq/eq.cummax()-1, label=nm, color=c, lw=1.0)\n"
            "ax.legend(); ax.set_title('Drawdown: the combo (green) is dragged far less deep into the steamroller')"
        ),
        md(
            "> 💡 **In plain words.** Diversification is the honest fix Study 27's vol-overlay couldn't "
            "provide: momentum is leaning *against* the crashing carry trade, so the combo's drawdown is "
            f"**{R['combo_dd']}%** versus carry's **{R['carry_dd']}%**. But the combo's skew is still "
            "negative — the jump is *dulled*, not gone. That's exactly why tradability is `FRAGILE`."
        ),

        md("## Beat 5 · The verdict\n\n"
           f"- **`REAL`** (4a/4b): high-minus-low +{R['hml']}%/yr, carry Sharpe {R['carry_sh']}, combo {R['combo_sh']}; null flat.\n"
           f"- **`FRAGILE`** (4c): carry skew {R['carry_skew']}, DD {R['carry_dd']}%; combo dulls to {R['combo_dd']}% but keeps a negative skew.\n"
           "- **Real-tape run? `PRE-REG`**: PENDING one FRED fetch.\n\n"
           "> **Signal `REAL` · Tradability `FRAGILE` · Real-tape run? `PRE-REG`** — the dollar-carry / "
           "carry⊕momentum-combo companion to Study 27."),

        md("## Beat 6 · Could you trade it?\n\n"
           f"- **Cheap to run.** Carry turns over slowly; momentum's break-even is ≈{R['mom_be']} bp; the "
           f"combo's Sharpe decays gently ({R['c0']} → {R['c100']} from 0 to 100 bp).\n"
           "- **The binding risk is the crash, not the cost or the capacity** (G10 FX is the deepest market "
           "on earth). Even diversified, the combo keeps negative skew.\n"
           "- **The real fragility line** (real tape): a 2008-style crash deepening rather than dulling — "
           "tested the moment `--fetch` runs."),

        md("## Beat 7 · Going further\n\n"
           "### 7a · Worked complement — the carry⊕momentum diversification ([`../docs/extension.md`](../docs/extension.md))\n"
           "The cost sweep below confirms the combo survives realistic costs; the diversification itself "
           "(beats 4b/4c) is the complement. Real-tape version PENDING `--fetch`."),
        code(
            "cs = costs.cost_sweep(xr, rd, which='combo')\n"
            "display(cs.round(3))\n"
            "fig, ax = plt.subplots(); ax.axhline(0, color='#999', lw=.8)\n"
            "ax.plot(cs.index, cs['sharpe'], marker='o', color='#2ea44f')\n"
            "ax.set_xlabel('cost (bp per unit traded)'); ax.set_ylabel('net Sharpe'); ax.set_title('The combo survives realistic costs (synthetic) — the threat is the crash, not the spread')\n"
            "print('momentum break-even:', round(costs.breakeven_cost_bps(xr, rd, which='momentum'), 1), 'bp')"
        ),
        md(
            "### 7b · Other forks\n"
            "- **Optimal combo weight** — sweep `w_carry`, risk-parity vs the realised crisis correlation.\n"
            "- **Dollar-carry as a third leg** — add the LRV dollar factor (real tape, where the USD rate cycles).\n"
            "- **Crisis-conditional tilt** — lean toward momentum when global FX vol (Brunnermeier-Nagel-"
            "Pedersen) is rising.\n\n"
            "**The result.** On the synthetic control the carry premium is `REAL` and recovered, the "
            "steamroller is present, and the carry⊕momentum combo `FRAGILE`-but-better lifts the Sharpe and "
            "cushions the crash — exactly the §8.3/§8.4 thesis, building on Study 27. The fingerprinted real "
            "G10 verdict is **PENDING** one `examples/verify.py --fetch`; full writeups in "
            "[`../docs/results.md`](../docs/results.md) and [`../docs/extension.md`](../docs/extension.md)."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
