"""Notebook builder for Study 981 — The Price of Waiting.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Price of Waiting \U000023F3
### "Wait for confirmation" is advice with an invoice attached

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Investable](https://img.shields.io/badge/Tradability-Investable-2ea44f?style=flat-square)

Don't act on the first crossing. Wait for the signal to hold. Everybody says it, nobody prices
it — and it is genuinely two things at once: fewer false starts, and later entries. This
notebook measures both halves separately instead of netting them into one number.

> \U0001F4D3 **This is the plain-language layer.** The grid, the delay accounting and the
> choose-*k*-out-of-sample test are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does waiting reduce whipsaw? | Yes, dramatically, and most on the signals that whipsaw most. |
| Does it improve returns? | Sometimes. Roughly a coin flip across tapes and signals. |
| What does it cost? | Thousands of sessions spent in cash while the signal was already right. |
| Could you pick the right waiting period? | Not reliably — the best *k* on the first half of a tape is rarely the best on the second. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Never act on the first crossing. Wait for two or three closes to confirm — that's how you
> avoid getting chopped up."*

The first half of that is a real, measurable effect. The second half quietly assumes the
avoided trades were the bad ones.
"""
        ),
        code(
            r"""
from confirm_delay import data, strategy as st

px = data.load_prices()
cash = px[data.CASH].dropna()
print(f"as-of {data.AS_OF}")
for tk in data.RISKY:
    s = px[tk].dropna()
    print(f"  {tk:5s} {s.index[0].date()} -> {s.index[-1].date()}  n={len(s):,}")
raw = {s: st.raw_signal(px['SPY'].dropna(), s) for s in st.SIGNALS}
for s, v in raw.items():
    flips = int(v.dropna().astype(int).diff().abs().sum())
    print(f"  SPY {st.SIGNAL_LABEL[s]:34s} {flips:4d} crossings "
          f"({flips / (len(v.dropna()) / 252):.1f} a year)")
"""
        ),
        md(
            r"""

Three signals with very different tempos. The RSI crosses its midpoint dozens of times a year;
the 200-day average crosses a handful. Confirmation should matter enormously for one and barely
at all for the other.
"""
        ),
        md(
            r"""

## 2 · What confirmation does to a signal
"""
        ),
        code(
            r"""
spy = px["SPY"].dropna()
r = st.raw_signal(spy, "rsi14")
win = slice("2018-01-01", "2019-06-30")
fig, axes = plt.subplots(2, 1, figsize=(11, 6), sharex=True,
                         gridspec_kw={"height_ratios": [2, 1]})
axes[0].plot(spy.loc[win].index, spy.loc[win], color="k", lw=1)
axes[0].set_ylabel("SPY"); axes[0].set_title("The same signal, confirmed for 1, 3 and 10 days")
for k, colour, off in ((1, "#c0392b", 0), (3, "#dab617", 1), (10, "#2ea44f", 2)):
    c = st.confirm(r, k).loc[win].astype(int)
    axes[1].fill_between(c.index, off, off + c * 0.9, color=colour, step="mid",
                         label=f"k = {k}")
axes[1].set_yticks([0.45, 1.45, 2.45]); axes[1].set_yticklabels(["k=1", "k=3", "k=10"])
axes[1].legend(ncol=3, fontsize=8)
plt.show()
for k in (1, 3, 10):
    w = st.whipsaw_stats(st.confirm(r, k).shift(1).fillna(False))
    print(f"k={k:2d}: {w['n_trades']:4d} round trips, {w['whipsaw_share']:.0%} closed within a "
          f"month, median length {w['median_length']:.0f} sessions")
"""
        ),
        md(
            r"""

## 3 · Both halves of the trade-off
"""
        ),
        code(
            r"""
grid = st.full_grid(px, cash, data.RISKY, cost_bps=2.0)
ws = grid.pivot_table(index="k", columns="signal", values="ws_whipsaw_share")
delay = grid.pivot_table(index="k", columns="signal", values="delay_cost_bps")
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
(ws * 100).plot(ax=axes[0], marker="o")
axes[0].set_ylabel("% of round trips closed within a month")
axes[0].set_title("What confirmation prevents"); axes[0].legend(fontsize=8, title="")
delay.plot(ax=axes[1], marker="o")
axes[1].axhline(0, color="k", lw=1)
axes[1].set_ylabel("return forgone while waiting (bps, summed)")
axes[1].set_title("What it costs"); axes[1].legend(fontsize=8, title="")
for a in axes:
    a.set_xlabel("confirmation days (k)")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The left panel is monotone and reliable — that is a mechanical
> property of the operator. The right panel is where the money is, and it grows with *k* just
> as reliably. The question is only which grows faster in Sharpe terms.
"""
        ),
        md(
            r"""

## 4 · Did it pay?
"""
        ),
        code(
            r"""
sh = grid.pivot_table(index="k", columns=["ticker", "signal"], values="sharpe")
rel = sh - sh.loc[1]
fig, ax = plt.subplots(figsize=(11, 5))
for col in rel.columns:
    ax.plot(rel.index, rel[col], marker="o", lw=1, alpha=0.8,
            label=f"{col[0]} {col[1]}")
ax.axhline(0, color="k", lw=1.5)
ax.set_xlabel("confirmation days (k)"); ax.set_ylabel("Sharpe minus the unconfirmed rule")
ax.set_title("Every tape and signal: does waiting help?")
ax.legend(ncol=3, fontsize=7)
plt.show()
best = st.best_k(grid)
print(best.round(3).to_string(index=False))
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** Yes, mechanically, and by a lot. Requiring five consecutive days of agreement cuts the share of round trips closed inside a month from **78%** to **30%** and the number of trades from 7.1 to 1.9 a year, across 12 tape × signal cells; the reduction holds on **100%** of them. The fast signal is where it bites: RSI's whipsaw share falls from 84% to 34%, while the 200-day average — which barely whipsaws to begin with — has little to gain.

**Tradability: Investable.** The waiting is not free. Across the grid the confirmed arms spent **3,636 sessions** holding cash while the raw signal was already positive, worth **-216,670 bps** of forgone return, against **+253,703 bps** avoided by exiting late. Some confirmation length beat the unconfirmed rule on Sharpe in **92%** of cells, by **+0.110** on average — and the winning length is different in almost every cell (4 different values of *k* across 12 cells), which is what choosing it in hindsight looks like.
"""
        ),
        md(
            r"""

## 6 · Going further \U0001F6AA

- **A price band** instead of a time delay — require the crossing to exceed the average by x%
  — is the other standard filter and trades off differently.
- **Confirmation on the exit only.** Most of the whipsaw damage is round trips; delaying only
  one leg is a cheaper version of the same idea.
- **Cost sensitivity.** At 2 bps a switch, trading is nearly free. At 25 bps the calculus
  changes and confirmation starts paying for itself.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Price of Waiting — a quantitative teardown \U0001F52C
### A lag-neutral confirmation operator · whipsaw versus delay, priced separately · out-of-sample k

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Investable](https://img.shields.io/badge/Tradability-Investable-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The design
decision that makes the comparison mean anything: **every arm has the same one-day execution
lag**. Without that, a slower rule looks different simply because it acts later, and the study
would be measuring lag rather than confirmation.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date
> in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from confirm_delay import data, strategy as st

px = data.load_prices()
cash = px[data.CASH].dropna()
print(f"as-of {data.AS_OF}")
for tk in data.RISKY:
    s = px[tk].dropna()
    print(f"  {tk:5s} {s.index[0].date()} -> {s.index[-1].date()}  n={len(s):,}")
raw = {s: st.raw_signal(px['SPY'].dropna(), s) for s in st.SIGNALS}
for s, v in raw.items():
    flips = int(v.dropna().astype(int).diff().abs().sum())
    print(f"  SPY {st.SIGNAL_LABEL[s]:34s} {flips:4d} crossings "
          f"({flips / (len(v.dropna()) / 252):.1f} a year)")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Yes, mechanically, and by a lot. Requiring five consecutive days of agreement cuts the share of round trips closed inside a month from **78%** to **30%** and the number of trades from 7.1 to 1.9 a year, across 12 tape × signal cells; the reduction holds on **100%** of them. The fast signal is where it bites: RSI's whipsaw share falls from 84% to 34%, while the 200-day average — which barely whipsaws to begin with — has little to gain. |
| **Tradability** | Investable | The waiting is not free. Across the grid the confirmed arms spent **3,636 sessions** holding cash while the raw signal was already positive, worth **-216,670 bps** of forgone return, against **+253,703 bps** avoided by exiting late. Some confirmation length beat the unconfirmed rule on Sharpe in **92%** of cells, by **+0.110** on average — and the winning length is different in almost every cell (4 different values of *k* across 12 cells), which is what choosing it in hindsight looks like. |

> \U0001F4A1 **In plain words.** Confirmation reliably does the thing it is advertised to do.
> Whether that thing is worth its price is a separate question, and the answer is "sometimes,
> unpredictably".
"""
        ),
        md(
            r"""

## 1 · The claim, made precise

- **H₁ (mechanical).** The share of round trips closed within a month falls monotonically in
  *k*, and falls most for the fastest signal.
- **H₂ (economic).** Some *k* > 1 improves the Sharpe ratio relative to *k* = 1.
- **H₃ (usable).** The *k* that wins on the first half of a sample also wins on the second.
  H₂ without H₃ is a hindsight result.
- **H₄ (context).** The whole exercise only matters if the underlying rule beats buy-and-hold
  in the first place.
"""
        ),
        md(
            r"""

## 2 · The operator, and why the lag is identical everywhere
"""
        ),
        code(
            r"""
idx = pd.bdate_range("2020-01-01", periods=14)
raw = pd.Series([False] * 5 + [True] * 4 + [False] + [True] * 4, index=idx)
tbl = pd.DataFrame({"raw": raw.astype(int)})
for k in (1, 2, 3, 5):
    tbl[f"k={k}"] = st.confirm(raw, k).astype(int)
    tbl[f"pos k={k}"] = st.confirm(raw, k).shift(1).fillna(False).astype(int)
print(tbl.to_string())
print("\nEvery arm's POSITION column is its state shifted by exactly one session:")
print("the confirmation length changes when the state flips, never how fast it is acted on.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The mechanical claim
"""
        ),
        code(
            r"""
grid = st.full_grid(px, cash, data.RISKY, cost_bps=2.0)
ws = grid.pivot_table(index=["ticker", "signal"], columns="k", values="ws_whipsaw_share")
fig, ax = plt.subplots(figsize=(10, 5))
im = ax.imshow(ws.values * 100, cmap="RdYlGn_r", aspect="auto")
ax.set_xticks(range(ws.shape[1])); ax.set_xticklabels([f"k={k}" for k in ws.columns])
ax.set_yticks(range(ws.shape[0]))
ax.set_yticklabels([f"{a} {b}" for a, b in ws.index], fontsize=8)
for i in range(ws.shape[0]):
    for j in range(ws.shape[1]):
        ax.text(j, i, f"{ws.values[i, j] * 100:.0f}", ha="center", va="center", fontsize=8)
ax.set_title("Share of round trips closed within a month (%)")
fig.colorbar(im, ax=ax)
plt.show()
print((ws.diff(axis=1) <= 1e-12).mean().round(3).to_string())
"""
        ),
        md(
            r"""

### 3.2 The price, in basis points
"""
        ),
        code(
            r"""
d = grid[grid["k"] == 5][["ticker", "signal", "days_waiting", "days_late_to_exit",
                          "delay_cost_bps", "late_exit_cost_bps", "share_disagreeing"]]
print(d.round(3).to_string(index=False))
fig, ax = plt.subplots(figsize=(10, 4.5))
x = np.arange(len(d))
ax.bar(x - 0.2, -d["delay_cost_bps"], width=0.4, color="#c0392b", label="forgone by waiting")
ax.bar(x + 0.2, -d["late_exit_cost_bps"], width=0.4, color="#2ea44f",
       label="avoided by exiting late")
ax.set_xticks(x); ax.set_xticklabels([f"{a}\n{b}" for a, b in zip(d['ticker'], d['signal'])],
                                     fontsize=7)
ax.axhline(0, color="k", lw=1); ax.set_ylabel("basis points (k = 5)")
ax.legend(); ax.set_title("Both sides of the ledger")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** A rule that waits misses the start of every rally *and*
> dodges the start of every fall. On a tape that mostly goes up, the first effect is bigger —
> which is why confirmation tends to help most on the assets that trend least.
"""
        ),
        md(
            r"""

### 3.3 Sharpe across the whole grid
"""
        ),
        code(
            r"""
sh = grid.pivot_table(index=["ticker", "signal"], columns="k", values="sharpe")
print(sh.round(3).to_string())
best = st.best_k(grid)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].bar(range(len(best)), best["gain"], color=["#2ea44f" if g > 0 else "#c0392b"
                                                   for g in best["gain"]])
axes[0].set_xticks(range(len(best)))
axes[0].set_xticklabels([f"{r.ticker}\n{r.signal}" for r in best.itertuples()], fontsize=7)
axes[0].axhline(0, color="k", lw=1); axes[0].set_ylabel("best-k Sharpe minus k=1")
axes[0].set_title("What the best confirmation length was worth (in hindsight)")
counts = best["best_k"].value_counts().sort_index()
axes[1].bar(counts.index.astype(str), counts.values, color="#8b949e")
axes[1].set_xlabel("winning k"); axes[1].set_ylabel("cells")
axes[1].set_title("And how consistent that choice was")
plt.show()
"""
        ),
        md(
            r"""

### 3.4 Against buy-and-hold — the context that decides whether any of this matters
"""
        ),
        code(
            r"""
vs = grid.pivot_table(index=["ticker", "signal"], columns="k", values="cagr_vs_hold")
fig, ax = plt.subplots(figsize=(10, 5))
im = ax.imshow(vs.values * 100, cmap="RdYlGn", vmin=-6, vmax=6, aspect="auto")
ax.set_xticks(range(vs.shape[1])); ax.set_xticklabels([f"k={k}" for k in vs.columns])
ax.set_yticks(range(vs.shape[0]))
ax.set_yticklabels([f"{a} {b}" for a, b in vs.index], fontsize=8)
for i in range(vs.shape[0]):
    for j in range(vs.shape[1]):
        ax.text(j, i, f"{vs.values[i, j] * 100:+.1f}", ha="center", va="center", fontsize=8)
ax.set_title("CAGR versus buy-and-hold (pp/yr)")
fig.colorbar(im, ax=ax)
plt.show()
print(f"cells beating buy-and-hold: {(vs > 0).to_numpy().mean():.0%}")
"""
        ),
        md(
            r"""

### 3.5 Could you have chosen k?
"""
        ),
        code(
            r"""
rows = []
for tk in data.RISKY:
    s_px = px[tk].dropna()
    mid = s_px.index[len(s_px) // 2]
    for sig in st.SIGNALS:
        first = st.sweep(s_px.loc[:mid], cash, sig, cost_bps=2.0)
        second = st.sweep(s_px.loc[mid:], cash, sig, cost_bps=2.0)
        k_pick = int(first["sharpe"].idxmax())
        rows.append({"ticker": tk, "signal": sig, "k chosen": k_pick,
                     "second-half Sharpe": second.loc[k_pick, "sharpe"],
                     "second-half k=1": second.loc[1, "sharpe"],
                     "gain": second.loc[k_pick, "sharpe"] - second.loc[1, "sharpe"],
                     "best k in hindsight": int(second["sharpe"].idxmax())})
oos = pd.DataFrame(rows)
print(oos.round(3).to_string(index=False))
print(f"\nchosen k beat k=1 on the second half in {(oos['gain'] > 0).mean():.0%} of cells; "
      f"mean gain {oos['gain'].mean():+.3f}")
print(f"the chosen k was also the hindsight winner "
      f"{(oos['k chosen'] == oos['best k in hindsight']).mean():.0%} of the time")
"""
        ),
        md(
            r"""

### 3.6 Cost sensitivity — the one thing that reliably changes the answer
"""
        ),
        code(
            r"""
rows = []
for cost in (0.0, 2.0, 10.0, 25.0):
    g = st.full_grid(px, cash, data.RISKY, signals=("rsi14",), cost_bps=cost)
    b = st.best_k(g)
    rows.append({"cost_bps": cost, "mean best k": b["best_k"].mean(),
                 "mean Sharpe gain": b["gain"].mean(),
                 "share where waiting wins": (b["gain"] > 0).mean()})
d = pd.DataFrame(rows).set_index("cost_bps")
print(d.round(3).to_string())
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.plot(d.index, d["mean best k"], marker="o", color="#2ea44f")
ax.set_xlabel("cost per switch (bps)"); ax.set_ylabel("average winning confirmation length")
ax.set_title("The more trading costs, the longer it pays to wait (RSI signal)")
plt.show()
"""
        ),
        md(
            r"""

### 3.7 The synthetic controls
"""
        ),
        code(
            r"""
rows = []
for trend, tag in ((1.0, "trending"), (0.0, "random walk"), (-1.0, "choppy")):
    sim = st.synthetic_tape(n=8000, trendiness=trend, seed=981)
    for sig in st.SIGNALS:
        s_ = st.sweep(sim["ASSET"], sim["CASH"], sig, cost_bps=2.0)
        rows.append({"world": tag, "signal": sig,
                     "whipsaw k=1": s_.loc[1, "ws_whipsaw_share"],
                     "whipsaw k=5": s_.loc[5, "ws_whipsaw_share"],
                     "best Sharpe gain": s_["sharpe"].max() - s_.loc[1, "sharpe"],
                     "best k": int(s_["sharpe"].idxmax())})
d = pd.DataFrame(rows)
print(d.round(3).to_string(index=False))
fig, ax = plt.subplots(figsize=(9, 4.5))
d.pivot(index="world", columns="signal", values="best Sharpe gain").plot.bar(ax=ax)
ax.axhline(0, color="k", lw=1); ax.set_ylabel("best Sharpe gain from waiting")
ax.legend(title="", fontsize=8)
ax.set_title("Where confirmation earns its keep")
plt.show()
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
summary = pd.DataFrame({
    "mean whipsaw share, k=1": [ws[1].mean()],
    "mean whipsaw share, k=5": [ws[5].mean()],
    "cells where some k beats k=1": [(best["gain"] > 0).mean()],
    "mean Sharpe gain (hindsight)": [best["gain"].mean()],
    "distinct winning k": [best["best_k"].nunique()],
    "out-of-sample win rate": [(oos["gain"] > 0).mean()],
    "cells beating buy-and-hold": [(vs > 0).to_numpy().mean()],
}).T.rename(columns={0: "value"})
summary.round(3)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Asymmetric confirmation**: wait on entries, act immediately on exits (or the reverse).
  Whipsaw is a round-trip phenomenon, so delaying one leg captures much of the benefit at half
  the cost.
- **Price bands** rather than time delays (Brock, Lakonishok & LeBaron's 1% filter).
- **Cost-aware selection**: section 3.6 suggests the right `k` is largely a function of the
  spread, which would make it choosable in advance after all — the one route to rescuing H₃.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
