"""Real-tape runner — Study 166 (First-Five-Days).

Cache-first.  Loads or downloads the ^GSPC daily history, computes annual
first-five-days and full-year returns, runs the full inference suite, and
prints/regenerates docs/results.md.

Run once to populate the cache and generate results:

    python studies/166-first-five-days/examples/verify.py

Run again any time to regenerate docs/results.md without a network call.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from first_five_days import data, strategy as st  # noqa: E402

DOCS = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "docs"))


def main() -> None:
    # Load real data (cache-first).
    try:
        df = data.fetch_gspc(fetch=False)
    except FileNotFoundError:
        print("No cache found — downloading ^GSPC from yfinance (fetch=True)...")
        df = data.fetch_gspc(fetch=True)

    n = len(df)
    fp = data.fingerprint(df)
    years = f"{df.index.min()}-{df.index.max()}"
    print(f"^GSPC annual series: {n} years ({years}), fingerprint {fp}")

    # Full analysis
    h = st.hit_rate_analysis(df)
    c = st.mean_contrast(df)
    perm = st.random_label_control(df, n_shuffles=5000, seed=166)
    strat = st.f5d_strategy(df, cost_bps=10.0)
    br = st.base_rate(df)

    # Sub-periods
    import pandas as pd
    sub1 = df.loc[1950:1985]
    sub2 = df.loc[1986:2025]

    def sub_stats(sub):
        h_s = st.hit_rate_analysis(sub)
        c_s = st.mean_contrast(sub)
        return h_s, c_s

    h1, c1 = sub_stats(sub1)
    h2, c2 = sub_stats(sub2)

    # Print summary
    print("\n=== Hit-rate analysis ===")
    print(f"  Overall hit-rate: {h['hit_rate']*100:.1f}%  (n={h['n']})")
    print(f"  vs coin (p=0.5):    p = {h['pval_vs_coin']:.4f}")
    print(f"  vs base rate ({br*100:.1f}%): p = {h['pval_vs_base_rate']:.4f}")
    print(f"  Up-F5D hit-rate:  {h['hit_rate_up_f5d']*100:.1f}%  (n={h['n_up_f5d']})")
    print(f"  Dn-F5D hit-rate:  {h['hit_rate_dn_f5d']*100:.1f}%  (n={h['n_dn_f5d']})")

    print("\n=== Mean contrast ===")
    print(f"  Up-F5D mean full-year: {c['mean_yr_up_f5d']*100:+.2f}%")
    print(f"  Dn-F5D mean full-year: {c['mean_yr_dn_f5d']*100:+.2f}%")
    print(f"  Contrast: {c['contrast_pct']:+.2f}%,  HAC t = {c['tstat_hac']:+.3f},  Welsh p = {c['pval_welsh']:.4f}")

    print("\n=== Sub-periods ===")
    print(f"  1950-1985: n={len(sub1)}, hit-rate={h1['hit_rate']*100:.1f}%, gap={c1['contrast_pct']:.1f}%, HAC-t={c1['tstat_hac']:.2f}, p(coin)={h1['pval_vs_coin']:.4f}")
    print(f"  1986-2025: n={len(sub2)}, hit-rate={h2['hit_rate']*100:.1f}%, gap={c2['contrast_pct']:.1f}%, HAC-t={c2['tstat_hac']:.2f}, p(coin)={h2['pval_vs_coin']:.4f}")

    print("\n=== Permutation control ===")
    print(f"  Permutation p-value: {perm['perm_pval']:.4f}")

    print("\n=== Strategy vs buy-and-hold ===")
    print(f"  Strategy (long if up-F5D, flat if dn-F5D, 10bp cost): {strat['strat_mean_ann_pct']:.2f}%/yr  Sharpe {strat['strat_sharpe']:.3f}")
    print(f"  Buy-and-hold: {strat['bah_mean_ann_pct']:.2f}%/yr  Sharpe {strat['bah_sharpe']:.3f}")

    # Write docs/results.md
    os.makedirs(DOCS, exist_ok=True)
    results_path = os.path.join(DOCS, "results.md")
    with open(results_path, "w", encoding="utf-8") as f:
        f.write(f"# Results — Study 166 (First-Five-Days) on real annual ^GSPC tape\n\n")
        f.write(
            f"*Generated by [`examples/verify.py`](../examples/verify.py).  The First-Five-Days "
            f"Early Warning System (Stock Trader's Almanac): does the sign of the S&P 500's return "
            f"over the first 5 trading days of January predict the full-year direction?  ^GSPC daily "
            f"history from 1950, annual first-five-days and full-year returns derived from daily closes "
            f"(log-returns).  As-of **2026-06-15**.  n = **{n} years** ({years}) — tiny effective n, "
            f"a key caveat throughout.*\n\n"
        )
        f.write("## Data stamp\n\n")
        f.write("| Ticker | Window | Fingerprint |\n|---|---|---|\n")
        f.write(f"| ^GSPC (annual series) | {years} ({n} years) | `{fp}` |\n\n")
        f.write(
            "*Derived from daily closes; first-five-days return = log(close on 5th trading day of Jan / "
            "close on last trading day of prior Dec); full-year return = log(Dec year-end close / prior "
            "Dec year-end close).  No look-ahead: F5D signal formed after the 5th trading day.*\n\n"
        )

        f.write("## Test 1 — Hit-rate vs base rate\n\n")
        f.write(
            f"The raw hit-rate (sign(F5D) == sign(full-year)) is **{h['hit_rate']*100:.1f} %** on {h['n']} years.  "
            f"Against a fair-coin null (50 %) that is statistically significant (binomial p = {h['pval_vs_coin']:.4f}).  "
            f"But the market drifts up most years — the **unconditional full-year positive rate is "
            f"{br*100:.1f} %** — so the relevant null is not a coin but *knowing that equity markets "
            f"trend up*.  Against that base rate the hit-rate of {h['hit_rate']*100:.1f} % is *below* it, "
            f"and the one-sided binomial p-value is **{h['pval_vs_base_rate']:.4f}**.  The indicator does not "
            f"beat the base rate.\n\n"
        )
        f.write("| Test | Hit-rate | p-value | Conclusion |\n|---|--:|--:|---|\n")
        f.write(f"| vs a coin (50 %) | **{h['hit_rate']*100:.1f} %** | **{h['pval_vs_coin']:.4f}** | Significant against a coin |\n")
        f.write(f"| vs base rate ({br*100:.1f} %) | {h['hit_rate']*100:.1f} % | {h['pval_vs_base_rate']:.4f} | **Not significant vs base rate** |\n\n")
        f.write(
            f"- Up-F5D hit-rate: **{h['hit_rate_up_f5d']*100:.1f} %** ({h['n_up_f5d']} years) — but the base "
            f"rate for those years is high.\n"
            f"- Down-F5D hit-rate: **{h['hit_rate_dn_f5d']*100:.1f} %** ({h['n_dn_f5d']} years) — the indicator "
            f"correctly calls a down full-year only {h['hit_rate_dn_f5d']*100:.1f} % of the time.\n"
            f"- Permutation p-value (random-label control): **{perm['perm_pval']:.4f}** — borderline.\n\n"
        )

        f.write("## Test 2 — Mean contrast (up-F5D vs down-F5D full-year returns)\n\n")
        f.write("| F5D sign | n | Mean full-year return | HAC t-stat |\n|---|--:|--:|--:|\n")
        f.write(f"| Up F5D | {h['n_up_f5d']} | **{c['mean_yr_up_f5d']*100:+.2f} %** | — |\n")
        f.write(f"| Down F5D | {h['n_dn_f5d']} | **{c['mean_yr_dn_f5d']*100:+.2f} %** | — |\n")
        f.write(f"| **Contrast (up − dn)** | {h['n']} | **{c['contrast_pct']:+.2f} %** | **{c['tstat_hac']:+.2f}** |\n\n")
        f.write(
            f"The contrast is **economically large ({c['contrast_pct']:.2f} %)** and statistically "
            f"significant (HAC *t* = {c['tstat_hac']:.2f}, Welsh p = {c['pval_welsh']:.4f}).  However, this "
            f"reflects two known confounds: (1) the F5D return *is part of* the full-year return (5 days of "
            f"overlap), creating a mechanical correlation; (2) up-F5D years tend to be bull-market regimes "
            f"where both January and December-year-end land high.  Regime correlation, not genuine early-warning.\n\n"
        )

        f.write("## Sub-period stability — the signal weakens post-1985\n\n")
        f.write("| Period | n | Hit-rate | Contrast | HAC t | p (coin) |\n|---|--:|--:|--:|--:|--:|\n")
        f.write(f"| 1950–1985 | {len(sub1)} | {h1['hit_rate']*100:.1f} % | {c1['contrast_pct']:+.1f} % | {c1['tstat_hac']:+.2f} | {h1['pval_vs_coin']:.4f} |\n")
        f.write(f"| 1986–2025 | {len(sub2)} | {h2['hit_rate']*100:.1f} % | {c2['contrast_pct']:+.1f} % | {c2['tstat_hac']:+.2f} | {h2['pval_vs_coin']:.4f} |\n\n")
        f.write(
            f"Post-1985 the hit-rate drops to {h2['hit_rate']*100:.1f} % (not significant vs a coin, "
            f"p = {h2['pval_vs_coin']:.4f}) and the contrast ({c2['contrast_pct']:.1f} %) — while still above "
            f"the inference bar (HAC t = {c2['tstat_hac']:.2f}) — is weaker than the earlier period.  "
            f"The pattern of a pre-publication strong effect that softens post-discovery is consistent "
            f"with either statistical luck in the discovery sample or gradual arbitrage.\n\n"
        )

        f.write("## F5D strategy vs buy-and-hold\n\n")
        f.write("| Arm | Mean/yr | Sharpe |\n|---|--:|--:|\n")
        f.write(f"| F5D strategy (long if up-F5D, flat if dn-F5D), 10 bp cost | {strat['strat_mean_ann_pct']:.2f} % | {strat['strat_sharpe']:.3f} |\n")
        f.write(f"| Buy-and-hold full year | {strat['bah_mean_ann_pct']:.2f} % | {strat['bah_sharpe']:.3f} |\n\n")
        missed_years = int(round((1 - h['hit_rate_dn_f5d']) * h['n_dn_f5d']))
        f.write(
            f"The F5D strategy slightly **outperforms buy-and-hold on mean return** "
            f"({strat['strat_mean_ann_pct']:.2f} % vs {strat['bah_mean_ann_pct']:.2f} %/yr) and on Sharpe.  "
            f"But this edge is largely driven by the pre-1985 data.  The strategy sits flat in {h['n_dn_f5d']} "
            f"out of {h['n']} years; in approximately {missed_years} of those, the full year was still "
            f"positive — the strategy missed real gains.  Post-1985 the tactical value is marginal.\n\n"
        )

        f.write("## Verdict\n\n")
        f.write(
            f"- **Signal — NONE.**  The indicator beats a coin (hit-rate {h['hit_rate']*100:.1f} %, "
            f"p = {h['pval_vs_coin']:.4f}) but **not the base rate** (p = {h['pval_vs_base_rate']:.4f}).  "
            f"The large HAC t = {c['tstat_hac']:.2f} is inflated by mechanical overlap (F5D is part of "
            f"the full year) and regime correlation.  Post-1985 the directional hit-rate ({h2['hit_rate']*100:.1f} %) "
            f"is not significant vs a coin (p = {h2['pval_vs_coin']:.4f}).  Effective n = {n} is tiny.\n"
            f"- **Tradability — MIRAGE.**  The strategy marginally outperforms buy-and-hold "
            f"({strat['strat_mean_ann_pct']:.2f} % vs {strat['bah_mean_ann_pct']:.2f} %/yr) but the signal is not "
            f"robust enough post-1985 and the outperformance is within noise at n = {n}.\n"
            f"- **Beats a coin? — NONE.**  Beats a fair coin (p = {h['pval_vs_coin']:.4f}) but not the "
            f"correct null (base rate {br*100:.1f} %, p = {h['pval_vs_base_rate']:.4f}).  The almanac's "
            f"'famous accuracy' is mostly the equity premium in calendar clothing.\n"
        )

    print(f"\nWrote {results_path}")


if __name__ == "__main__":
    main()
