"""Notebook builder for Study 993 — Down Hurts More.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Down Hurts More \U00002696
### Falls stir up more volatility than rises. The reason everyone gives is wrong.

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Fischer Black spotted it in 1976 and gave it a name that has outlived its explanation. The
"leverage effect" says a falling share price raises a company's debt-to-equity ratio, making
what is left riskier. Neat, intuitive, and testable — because some assets have no debt at all.

> \U0001F4D3 **This is the plain-language layer.** The EGARCH fit, the news-impact curve and the
> lead-lag test are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Do falls raise volatility more than rises? | Yes, clearly, and it survives every control. |
| Is it because of debt? | Almost certainly not. |
| How do we know? | Gold has no debt and shows it too. |
| Does it matter? | Yes — it is why put options cost more than calls. |
"""
        ),
        md(
            r"""

## 1 · The effect
"""
        ),
        code(
            r"""
from downhurts import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
r = assets[data.EQUITY]
ss = st.sign_split(r, 21, 5)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions")
print(f"volatility over the next 5 days after an up day:   {ss['vol_after_up']:.1%}")
print(f"volatility over the next 5 days after a down day:  {ss['vol_after_down']:.1%}")
print(f"ratio: {ss['ratio']:.3f}x")
"""
        ),
        code(
            r"""
nic = st.news_impact_curve(r, 5)
fig, ax = plt.subplots(figsize=(10, 5.5))
ax.plot(nic["mean_return"] * 100, nic["mean_fwd_vol"] * 100, "o-", lw=2, ms=7,
        color="#1f6feb")
ax.axvline(0, color="k", lw=1)
cm = st.curve_minimum(nic)
ax.set_xlabel("today's return (%)")
ax.set_ylabel("volatility over the next 5 days (%, annualised)")
ax.set_title("The news-impact curve: if it were symmetric, this would be centred on zero")
plt.show()
print(f"the curve bottoms out at a return of {cm['vertex_z']:+.2f} standard deviations")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The vertex is the summary statistic worth quoting. An up/down
> mean difference throws away the shape; the vertex uses the whole curve and is far less
> sensitive to where you put the dividing line.
"""
        ),
        md(
            r"""

## 2 · The obvious objection

Down days are *bigger* than up days — markets fall faster than they rise. And big moves are
followed by volatility whatever direction they went. So is this just a size effect wearing a
sign?
"""
        ),
        code(
            r"""
mm = st.magnitude_matched_split(r, 5)
fig, ax = plt.subplots(figsize=(10, 4.5))
w = 0.35
xs = np.arange(len(mm))
ax.bar(xs - w / 2, mm["vol_after_up"] * 100, w, label="after an up day", color="#2ea44f")
ax.bar(xs + w / 2, mm["vol_after_down"] * 100, w, label="after a down day", color="#c0392b")
ax.set_xticks(xs)
ax.set_xticklabels([f"{b}\n{m:.1%}" for b, m in zip(mm.index, mm["mean_abs_move"])],
                   fontsize=8)
ax.set_xlabel("size of today's move (matched)")
ax.set_ylabel("next 5 days' volatility (%)"); ax.legend(fontsize=8)
plt.show()
print(mm[["mean_abs_move", "vol_after_up", "vol_after_down", "ratio"]].round(4).to_string())
print(f"\naverage within-bucket ratio: {mm['ratio'].mean():.3f}x")
"""
        ),
        md(
            r"""

Comparing like with like, the asymmetry is still there. It is smaller than the raw number, which
is exactly what you would expect if part of the raw number was a size effect.
"""
        ),
        md(
            r"""

## 3 · So is it leverage?

Black's story: the share price falls, the company's debt stays the same, so debt-to-equity
rises, so the remaining equity is riskier. That story has a clean, brutal test — find an asset
with no debt.
"""
        ),
        code(
            r"""
p = st.panel(assets, 5, 21)
fig, ax = plt.subplots(figsize=(11, 5))
colors = ["#c0392b" if tk in (data.GOLD, data.CRYPTO, data.CURRENCY) else "#1f6feb"
          for tk in p.index]
ax.bar(range(len(p)), p["ratio"], color=colors)
ax.axhline(1.0, color="k", ls="--", lw=2, label="no asymmetry")
ax.set_xticks(range(len(p))); ax.set_xticklabels(p.index, rotation=20, ha="right", fontsize=8)
ax.set_ylabel("volatility after down ÷ after up")
ax.legend(fontsize=8)
ax.set_title("Red = assets with no balance sheet, so no leverage mechanism is possible")
plt.show()
print(p[["ratio", "corr_r_dvol", "egarch_gamma"]].round(4).to_string())
"""
        ),
        md(
            r"""

Gold is a metal. It has no shareholders, no debt, no capital structure. Bitcoin is a number in a
ledger. Neither of them can possibly have a debt-to-equity ratio that rises when the price
falls — so if they show the effect, the mechanism is something else entirely.

The leading alternative is **volatility feedback**: when volatility rises, investors demand a
higher return to hold the asset, and the only way to offer a higher future return is a lower
price today. Same correlation, opposite direction of causality.
"""
        ),
        md(
            r"""

## 4 · Which way does the arrow point?
"""
        ),
        code(
            r"""
ll = st.lead_lag_asymmetry(r, 21)
fig, ax = plt.subplots(figsize=(11, 5))
colors = ["#2ea44f" if k > 0 else ("#c0392b" if k < 0 else "#8b949e") for k in ll.index]
ax.bar(ll.index, ll["correlation"], color=colors)
ax.axhline(0, color="k", lw=1); ax.axvline(0, color="k", lw=1, ls=":")
ax.set_xlabel("lag (days).  positive = return first, negative = volatility first")
ax.set_ylabel("correlation between return and volatility change")
ax.set_title("Green: the leverage story's territory.  Red: the feedback story's.")
plt.show()
w = st.which_story(ll)
print(f"return leads volatility (leverage): {w['leverage_side']:+.4f}")
print(f"volatility leads return (feedback): {w['feedback_side']:+.4f}")
print(f"-> leans {w['leans']}")
"""
        ),
        md(
            r"""

## 5 · Why you should care anyway
"""
        ),
        code(
            r"""
eg = st.egarch_asymmetry(r)
print(f"EGARCH gamma: {eg['gamma']:+.4f}")
print(f"a -1 sigma day raises volatility {eg['response_ratio']:.2f}x as much as a +1 sigma day")
print()
print("This is why a put costs more than an equally out-of-the-money call: the market")
print("knows that if the price gets there, volatility will be higher when it does.")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Confirmed.** For SPY over 7,764 sessions, volatility over the five days after a down day averaged **15.9%** against **13.5%** after an up day — a ratio of **1.18×**. That survives the obvious objection: matching on the *size* of the move (down days are bigger on average, and big moves are followed by volatility whatever their sign) leaves a ratio of **1.15×**. It survives honest inference too — block-bootstrapping the difference gives *t* = **+7.70** against the naive +9.37. And the parametric version agrees: EGARCH gamma = **-0.110**, implying a down shock raises volatility 1.25× as much as an equal up shock. The news-impact curve bottoms out at **z = +0.28**, shifted toward positive returns exactly as the leverage story predicts.

**Tradability: Partial.** Now the part the name gets wrong. If financial leverage were the mechanism, assets with **no balance sheet** could not show the effect. Gold's ratio is 1.02× and Bitcoin's is 1.03×, against equities' 1.18× — and the effect is materially weaker there, which is at least consistent with the leverage story. The lead-lag test points the same way: the correlation between returns and *subsequent* volatility changes averages -0.051, against +0.015 for volatility leading returns — leaning **leverage**. For a hedger the practical content is the ratio itself: a 1.18× asymmetric response is why put skew exists and why a delta-hedged short-vol book bleeds asymmetrically. The name is wrong; the effect is real and it is priced.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Individual stocks sorted by leverage.** If the mechanism were debt, high-debt firms should
  show a much stronger effect than debt-free ones. Figlewski & Wang (2000) checked; they do not.
- **High-frequency data.** Bollerslev, Litvinova & Tauchen (2006) run the lead-lag test on
  five-minute returns, where realised volatility is far less noisy and the arrow is much easier
  to see.
- **The option surface.** The asymmetry measured here should equal the skew the market is
  charging. Comparing them is a genuine test of whether the effect is fully priced.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Down Hurts More — a quantitative teardown \U0001F52C
### Magnitude-matched splits · news-impact curves · EGARCH γ · lead-lag identification

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The effect is
easy to find and easy to fake; most of this notebook is about telling those apart, and the
cleanest evidence on mechanism comes from an asset with no balance sheet rather than from any
regression.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from downhurts import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
assets = {tk: rets[tk].dropna() for tk in data.TICKERS
          if tk != data.CASH and rets[tk].notna().sum() > 1500}
r = assets[data.EQUITY]
ss = st.sign_split(r, 21, 5)
print(f"as-of {data.AS_OF} | {data.EQUITY}: {len(r):,} sessions")
print(f"volatility over the next 5 days after an up day:   {ss['vol_after_up']:.1%}")
print(f"volatility over the next 5 days after a down day:  {ss['vol_after_down']:.1%}")
print(f"ratio: {ss['ratio']:.3f}x")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | For SPY over 7,764 sessions, volatility over the five days after a down day averaged **15.9%** against **13.5%** after an up day — a ratio of **1.18×**. That survives the obvious objection: matching on the *size* of the move (down days are bigger on average, and big moves are followed by volatility whatever their sign) leaves a ratio of **1.15×**. It survives honest inference too — block-bootstrapping the difference gives *t* = **+7.70** against the naive +9.37. And the parametric version agrees: EGARCH gamma = **-0.110**, implying a down shock raises volatility 1.25× as much as an equal up shock. The news-impact curve bottoms out at **z = +0.28**, shifted toward positive returns exactly as the leverage story predicts. |
| **Tradability** | Partial | Now the part the name gets wrong. If financial leverage were the mechanism, assets with **no balance sheet** could not show the effect. Gold's ratio is 1.02× and Bitcoin's is 1.03×, against equities' 1.18× — and the effect is materially weaker there, which is at least consistent with the leverage story. The lead-lag test points the same way: the correlation between returns and *subsequent* volatility changes averages -0.051, against +0.015 for volatility leading returns — leaning **leverage**. For a hedger the practical content is the ratio itself: a 1.18× asymmetric response is why put skew exists and why a delta-hedged short-vol book bleeds asymmetrically. The name is wrong; the effect is real and it is priced. |

> \U0001F4A1 **In plain words.** The effect is real and survives everything. The *name* does
> not survive a single column of the cross-asset table.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** Forward volatility is higher after down days than after up days.
- **H₂ (size control).** It survives matching on |return| — the asymmetry is about sign, not
  magnitude.
- **H₃ (inference).** It survives a block bootstrap in which the up/down split is re-derived
  inside each resample.
- **H₄ (shape).** The news-impact curve's vertex sits at a positive return, not at zero.
- **H₅ (mechanism).** If the mechanism is financial leverage, assets with no balance sheet show
  no effect.
- **H₆ (direction).** If the mechanism is leverage, returns lead volatility changes; if it is
  volatility feedback, the reverse.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 Four measurements
"""
        ),
        code(
            r"""
ss = st.sign_split(r, 21, 5)
ca = st.correlation_asymmetry(r, 21)
eg = st.egarch_asymmetry(r)
cm = st.curve_minimum(st.news_impact_curve(r, 5))
print("sign split:      ", pd.Series(ss).round(4).to_string().replace("\n", "\n                 "))
print()
print("correlation:     ", pd.Series(ca).round(4).to_dict())
print("EGARCH:          ", {k: round(v, 4) for k, v in eg.items()
                            if isinstance(v, (int, float))})
print("curve vertex:    ", {k: round(v, 4) for k, v in cm.items()
                            if isinstance(v, (int, float))})
"""
        ),
        md(
            r"""

### 2.2 The magnitude-matched control
"""
        ),
        code(
            r"""
for n_b in (3, 5, 10):
    m = st.magnitude_matched_split(r, 5, n_buckets=n_b)
    print(f"{n_b} buckets: mean within-bucket ratio {m['ratio'].mean():.4f}  "
          f"(range {m['ratio'].min():.3f} to {m['ratio'].max():.3f})")
print(f"\nunmatched ratio: {ss['ratio']:.4f}")
m = st.magnitude_matched_split(r, 5, n_buckets=8)
fig, ax = plt.subplots(figsize=(10, 4.8))
ax.plot(m["mean_abs_move"] * 100, m["ratio"], "o-", lw=2, color="#c0392b")
ax.axhline(1.0, color="k", ls="--", lw=1.5)
ax.set_xlabel("size of the move (%)"); ax.set_ylabel("down/up volatility ratio")
ax.set_title("Is the asymmetry bigger for bigger moves?")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** If the curve slopes upward, the asymmetry concentrates in large
> moves — which is what a crash-risk story predicts and what a smooth leverage mechanism does
> not.
"""
        ),
        md(
            r"""

### 2.3 The bootstrap
"""
        ),
        code(
            r"""
rows = []
for hz in (2, 5, 10, 21):
    s2 = st.sign_split(r, 21, hz)
    b2 = st.bootstrap_asymmetry(r, hz, n_boot=500)
    rows.append({"horizon": hz, "ratio": s2["ratio"], "naive_t": s2["naive_t"],
                 "boot_t": b2["t"], "lo": b2["lo"], "hi": b2["hi"]})
d = pd.DataFrame(rows).set_index("horizon")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(9.5, 4.5))
d[["naive_t", "boot_t"]].plot.bar(ax=ax, color=["#c0392b", "#2ea44f"])
ax.axhline(0, color="k", lw=1)
for y in (-2, 2):
    ax.axhline(y, ls="--", color="#8b949e", lw=1)
ax.set_ylabel("t on the up/down difference")
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
"""
        ),
        md(
            r"""

### 2.4 News-impact curves, every asset
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(2, 4, figsize=(16, 7))
for ax, (tk, s) in zip(axes.ravel(), assets.items()):
    nic = st.news_impact_curve(s, 5)
    if nic.empty:
        ax.axis("off"); continue
    cm2 = st.curve_minimum(nic)
    ax.plot(nic["z"], nic["mean_fwd_vol"] * 100, "o-", lw=1.5, ms=4, color="#1f6feb")
    ax.axvline(0, color="k", lw=1)
    if np.isfinite(cm2.get("vertex_z", np.nan)):
        ax.axvline(cm2["vertex_z"], color="#c0392b", ls="--", lw=1.5)
    ax.set_title(f"{tk}  vertex {cm2.get('vertex_z', np.nan):+.2f}", fontsize=9)
    ax.set_xlabel("today's return (sd)", fontsize=8)
for ax in axes.ravel()[len(assets):]:
    ax.axis("off")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.5 The cross-asset table — the mechanism test
"""
        ),
        code(
            r"""
p = st.panel(assets, 5, 21)
print(p.round(4).to_string())
no_balance_sheet = [tk for tk in (data.GOLD, data.CRYPTO, data.CURRENCY) if tk in p.index]
has_balance_sheet = [tk for tk in (data.EQUITY, data.NASDAQ, data.SMALL) if tk in p.index]
print(f"\nmean ratio, assets WITH a balance sheet:    "
      f"{p.loc[has_balance_sheet, 'ratio'].mean():.4f}")
print(f"mean ratio, assets WITHOUT a balance sheet: "
      f"{p.loc[no_balance_sheet, 'ratio'].mean():.4f}")
print(f"mean EGARCH gamma, with:    {p.loc[has_balance_sheet, 'egarch_gamma'].mean():+.4f}")
print(f"mean EGARCH gamma, without: {p.loc[no_balance_sheet, 'egarch_gamma'].mean():+.4f}")
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
cols = ["#c0392b" if tk in no_balance_sheet else "#1f6feb" for tk in p.index]
axes[0].bar(range(len(p)), p["ratio"], color=cols)
axes[0].axhline(1.0, color="k", ls="--", lw=2)
axes[0].set_xticks(range(len(p)))
axes[0].set_xticklabels(p.index, rotation=25, ha="right", fontsize=7)
axes[0].set_ylabel("down/up volatility ratio")
axes[1].bar(range(len(p)), p["egarch_gamma"], color=cols)
axes[1].axhline(0, color="k", ls="--", lw=2)
axes[1].set_xticks(range(len(p)))
axes[1].set_xticklabels(p.index, rotation=25, ha="right", fontsize=7)
axes[1].set_ylabel("EGARCH gamma (negative = asymmetric)")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Red bars are assets where the leverage mechanism is
> *impossible* — no equity, no debt, no capital structure. Whatever the red bars show, financial
> leverage did not cause it. If they look like the blue bars, the name is simply a
> forty-year-old misnomer.
"""
        ),
        md(
            r"""

### 2.6 Leverage or feedback?
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(11, 5.5))
for tk in (data.EQUITY, data.GOLD, data.CRYPTO):
    if tk not in assets:
        continue
    ll2 = st.lead_lag_asymmetry(assets[tk], 21)
    ax.plot(ll2.index, ll2["correlation"], "o-", lw=1.6, ms=4, label=tk)
ax.axhline(0, color="k", lw=1); ax.axvline(0, color="k", lw=1, ls=":")
ax.set_xlabel("lag (days): positive = return leads volatility")
ax.set_ylabel("correlation"); ax.legend(fontsize=8)
plt.show()
rows = []
for tk, s in assets.items():
    w = st.which_story(st.lead_lag_asymmetry(s, 21))
    if w:
        rows.append({"asset": tk, **w})
pd.DataFrame(rows).set_index("asset").round(4)
"""
        ),
        md(
            r"""

### 2.7 Grading against a planted gamma
"""
        ),
        code(
            r"""
rows = []
for gamma in (0.0, -0.05, -0.10, -0.15, -0.25):
    ratios, naive, boot, recov = [], [], [], []
    for k in range(3):
        sim = st.synthetic_returns(n=3000, gamma=gamma, seed=993 + k)
        s2 = st.sign_split(sim, 21, 5)
        ratios.append(s2["ratio"]); naive.append(abs(s2["naive_t"]) >= 2)
        boot.append(abs(st.bootstrap_asymmetry(sim, 5, n_boot=150)["t"]) >= 2)
        recov.append(st.fit_egarch(sim)["gamma"])
    rows.append({"planted gamma": gamma, "ratio": np.mean(ratios),
                 "naive rejects": np.mean(naive), "bootstrap rejects": np.mean(boot),
                 "recovered gamma": np.mean(recov)})
d = pd.DataFrame(rows).set_index("planted gamma")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d[["naive rejects", "bootstrap rejects"]].mul(100).plot.bar(ax=axes[0],
                                                            color=["#c0392b", "#2ea44f"])
axes[0].axhline(5, ls="--", color="k", lw=1, label="nominal 5%")
axes[0].set_ylabel("share declaring asymmetry (%)"); axes[0].legend(fontsize=8)
plt.setp(axes[0].get_xticklabels(), rotation=0)
axes[1].plot(d.index, d["recovered gamma"], "o-", lw=2, color="#1f6feb", label="recovered")
axes[1].plot(d.index, d.index, "k--", lw=2, label="planted")
axes[1].set_xlabel("planted gamma"); axes[1].set_ylabel("EGARCH estimate")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
d.round(4)
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
ss = st.sign_split(r, 21, 5)
mm = st.magnitude_matched_split(r, 5)
bs = st.bootstrap_asymmetry(r, 5, n_boot=500)
eg = st.egarch_asymmetry(r)
cm = st.curve_minimum(st.news_impact_curve(r, 5))
p = st.panel(assets, 5, 21)
w = st.which_story(st.lead_lag_asymmetry(r, 21))
pd.DataFrame({
    "down/up volatility ratio": [ss["ratio"]],
    "matched on move size": [mm["ratio"].mean()],
    "naive t": [ss["naive_t"]],
    "bootstrap t": [bs["t"]],
    "EGARCH gamma": [eg["gamma"]],
    "news-impact vertex (sd)": [cm["vertex_z"]],
    "gold's ratio (no balance sheet)": [
        p.loc[data.GOLD, "ratio"] if data.GOLD in p.index else np.nan],
    "bitcoin's ratio (no balance sheet)": [
        p.loc[data.CRYPTO, "ratio"] if data.CRYPTO in p.index else np.nan],
    "leans": [w.get("leans", "?")],
}).T.rename(columns={0: "value"})
"""
        ),
        md(
            r"""

## 4 · Going further

- **Sort firms by leverage.** The direct version of section 2.5, and the one Figlewski & Wang
  (2000) ran: if debt is the mechanism, the effect must scale with debt. It does not.
- **High-frequency identification.** Realised volatility from daily returns is a noisy proxy,
  and that noise attenuates the lead-lag correlations unevenly. Five-minute data (Bollerslev,
  Litvinova & Tauchen 2006) makes the arrow far easier to see.
- **Compare with the option surface.** The asymmetry measured here has a market price — the
  skew. Whether the physical asymmetry matches the risk-neutral one is a genuine test of
  whether it is fully arbitraged.
- **GJR as a robustness check.** EGARCH's gamma is not comparable across specifications; the
  threshold model would confirm the sign without confirming the magnitude.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
