"""Build the two narrative notebooks for Study 233 (Shareholder-Yield).

    python notebooks/build_notebooks.py

The real numbers below mirror docs/results.md exactly (fingerprint f1b6fc02e713,
~412 S&P 500 names, 2008-2025, buyback-yield-only signal from EDGAR shares).
"""
from __future__ import annotations
import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Numbers from the real run (docs/results.md, fingerprint f1b6fc02e713)
# ---------------------------------------------------------------------------
REAL = {
    "n_names": 412,
    "n_years": 18,
    "years": "2008-2025",
    "fingerprint": "f1b6fc02e713",
    "high_leg": 0.1996,   # high shareholder yield (long)
    "low_leg":  0.2279,   # low shareholder yield (short)
    "market":   0.1957,
    "hedge_mean": -0.0283,
    "sharpe": -0.30,
    "tstat":  -1.3,
    "hit_rate": 0.278,
    "max_dd": -0.533,
}

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (shareholder_yield/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from shareholder_yield import data, strategy as st
total_yield, fwd, comps = data.fetch_panel()   # cache-first (shared EDGAR pull)
h = st.quantile_hedge(total_yield, fwd, q=0.2, long_high=True)
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Shareholder yield predicts outperformance?: Not supported]"
    "(https://img.shields.io/badge/Shareholder_yield_predicts_outperformance%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Shareholder-Yield\n"
            "### Is total shareholder yield (dividends + buybacks) the dividend factor done right?\n\n"
            + VERDICT
            + "The upgraded claim: measure not just dividends but *all* cash returned to shareholders "
            "— dividends plus net share repurchases. Championed by Meb Faber (2007) and Boudoukh et al. "
            "(2007) as a better predictor than dividend yield alone. We built it on real SEC 10-K filings "
            "for the S&P 500 — and it ran **backwards**. The high total-yield names (+20.0%/yr) trailed "
            "the low-yield names (+22.8%).\n\n"
            "> This notebook is the plain-language layer. The detailed teardown is in "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
            "> **Not investment advice.** Every number is generated by the code beside it."
        ),
        code(BOOT),
        md(
            "## The answer first\n\n"
            "| The question | The data (~412 S&P names, 2008-2025) |\n|---|---|\n"
            "| \"Do high total-yield firms outperform?\" | No — they **trailed** by ~3%/yr here. |\n"
            "| \"Is shareholder yield an investable factor on large caps?\" | No: hedge **−2.8%/yr, Sharpe −0.30**. |\n"
            "| \"So where's the real edge?\" | If it exists, it's in smaller, less-traded names — outside this universe. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "Pure dividend yield misses a big chunk of capital return: buybacks now dwarf dividends "
            "for many S&P 500 members. Shareholder yield adds net buyback yield (the year-on-year "
            "fractional decrease in diluted shares outstanding) to dividend yield. Faber (2007) "
            "showed this composite metric predicts returns better than dividends alone."
        ),
        md(
            "## 2 · So what?\n\n"
            "If true and tradable on liquid names, you'd tilt toward firms that are aggressively "
            "buying back shares and paying dividends — a clean signal from freely available EDGAR "
            "filings, no proprietary data needed. The question is whether it survives on the names "
            "you can actually trade in size."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "Pull diluted shares outstanding from EDGAR for the S&P 500, compute net buyback yield "
            "(YoY share decrease), sort every year, go long the top-20% (high yielders) and short "
            "the bottom-20% (low/zero yielders), and measure next year's hedge return over 2008-2025."
        ),
        code(
            "legs = pd.DataFrame({\n"
            "    'high-yield leg (long)': st.summary(h['high'])['mean'],\n"
            "    'low-yield leg (short)': st.summary(h['low'])['mean'],\n"
            "    'market': st.summary(st.market_annual(fwd).reindex(h.index))['mean'],\n"
            "}, index=['annual return'])\n"
            "ax = (legs.T * 100).plot.bar(\n"
            "    rot=0, legend=False,\n"
            "    color=['#2ea44f', '#c0392b', '#8b949e'],\n"
            "    title='Annual return by leg — the low-yield names (red) beat the high-yield names (green)'\n"
            ")\n"
            "ax.set_ylabel('%'); ax.axhline(0, color='k', lw=.8); plt.show()"
        ),
        md(
            "## 4 · The teardown — the sign is backwards\n\n"
            "The hedge (long high yield, short low yield) lost in nearly three-quarters of years. "
            "The low-yield cohort was dominated by the growth/tech names that retained earnings, "
            "issued stock via SBC, and led the market throughout 2009-2024."
        ),
        code(
            "s = st.summary(h['hedge'])\n"
            "print(f\"hedge (long high yield / short low yield): \"\n"
            "      f\"{s['mean']:+.2%}/yr  Sharpe {s['sharpe']:.2f}  \"\n"
            "      f\"(t~{s['tstat']:.1f})  hit {s['hit_rate']:.0%}\")\n"
            "(h['hedge'] * 100).plot.bar(\n"
            "    color=['#2ea44f' if v > 0 else '#c0392b' for v in h['hedge']],\n"
            "    title='Yearly hedge return (long high yield / short low yield) — mostly red'\n"
            ")\n"
            "plt.ylabel('%'); plt.axhline(0, color='k', lw=.8); plt.show()"
        ),
        md(
            "**Read it plainly.** Over 2008-2025, the firms with the *lowest* shareholder yield "
            "— the growth/tech companies retaining cash and diluting through stock-based comp — "
            "beat the high-yield value names. Tilting toward shareholder yield meant betting "
            "against the market's winners."
        ),
        md(
            "## 5 · The verdict\n\n"
            "**Signal: Weak** — it inverts (−2.8%/yr, t −1.3). **Tradability: Mirage** — wrong "
            "sign on liquid names. **Shareholder yield predicts outperformance?: Not supported.** "
            "Right theory, wrong universe."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "Not as built. The published anomaly has never been as clean on large caps as on the "
            "broader market; and post-publication, the shareholder-yield factor has been widely "
            "implemented and arbitraged. The post-2009 growth regime also structurally disadvantaged "
            "any yield-tilt on the S&P 500."
        ),
        md(
            "## 7 · Going further\n\n"
            "The buyback-only predecessor is [64 Share-Shuffle](../../64-share-shuffle/) (same "
            "inverted result). Related fundamental factors: [44 Growth-Spurt](../../44-growth-spurt/) "
            "(asset growth), [52 Smoke-Screen](../../52-smoke-screen/) (accruals — *does* replicate). "
            "Forks: micro-cap universe, value-weighting, adding explicit dividend-yield from yfinance."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Shareholder-Yield — a quantitative teardown\n"
            "### The total-yield long-short · the inverted sign · the growth-regime explanation\n\n"
            + VERDICT
            + "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). "
            "A theoretically sound factor that runs backwards on the tradable end of the market.\n\n"
            "> **Not investment advice.** SEC EDGAR diluted shares + Yahoo annual returns, "
            "~412 current S&P 500 members, 2008-2025. Sources: "
            "[`docs/references.md`](../docs/references.md)."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            "| Signal | **Weak** | hedge −2.8%/yr, Sharpe −0.30, t −1.3 — inverted |\n"
            "| Tradability | **Mirage** | high-yield names trailed low-yield on large caps |\n"
            "| Shareholder yield predicts outperformance? | **Not supported** | growth beat yield |\n\n"
            "> In plain words: a theoretically correct metric, measured in the wrong universe."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H1:** high shareholder yield (div yield + net buyback yield) positively predicts "
            "next-year cross-sectional returns.\n"
            "- **H2:** a long-high-yield / short-low-yield hedge is positive and significant.\n"
            "- **H3:** it's tradable on liquid large caps — not just the micro-cap tail."
        ),
        md(
            "## 2 · So what? — what rides on each\n\n"
            "H1/H2 would make shareholder yield a superior, free, fundamentals-based signal — "
            "pulling from 10-K filings and daily price data. H3 decides whether it works where "
            "you can deploy serious capital. A micro-cap-only effect is real science but useless "
            "to a large-cap manager."
        ),
        md(
            "## 3 · Protocol\n\n"
            "EDGAR diluted shares → net buyback yield (YoY share decrease, sign-flipped from net "
            "issuance) → annual quintile sort → long top-20% (high yielders), short bottom-20% "
            "(low yielders) → next-year hedge, Sharpe, t-stat, hit rate over the XBRL window "
            "(2008-2025)."
        ),
        md("## 4 · The teardown"),
        md("### 4.1 The long-short, year by year"),
        code(
            "disp = h.copy()\n"
            "disp.columns = ['high-yield leg', 'low-yield leg', 'hedge (high-low)']\n"
            "display((disp * 100).round(1))\n"
            "s = st.summary(h['hedge'])\n"
            "print({k: round(v, 3) for k, v in s.items()})"
        ),
        md(
            "> In plain words: the hedge mean is **negative** (−2.8%/yr) and wins only 28% of years. "
            "**H1 and H2 are rejected on this universe** — the sign is backwards."
        ),
        md("### 4.2 Why the sign inverts — H3 fails"),
        md(
            "Three forces flip it on large caps:\n\n"
            "1. **Low yield = growth winners.** 2008-2025's lowest-yield large caps were high-growth "
            "tech companies diluting via stock-based compensation — the market leaders who retained "
            "cash and drove returns.\n"
            "2. **The anomaly may live in smaller names.** Boudoukh et al. (2007) test on the full "
            "market; Hou-Xue-Zhang (2020) show financing anomalies fade with value-weighting and "
            "NYSE breakpoints. The large-cap cohort is likely post-publication and arbitraged.\n"
            "3. **Survivorship.** Current S&P members exclude distressed high-yielders that delisted "
            "— which would have hurt the long leg — yet even this biased test inverts the signal. "
            "**H3 rejected.**"
        ),
        md("### 4.3 Growth vs. yield regime"),
        code(
            "# cumulative wealth of each leg vs market\n"
            "eq_high = (1 + h['high']).cumprod()\n"
            "eq_low  = (1 + h['low']).cumprod()\n"
            "eq_mkt  = (1 + st.market_annual(fwd).reindex(h.index)).cumprod()\n"
            "pd.DataFrame({'high-yield leg': eq_high, 'low-yield leg': eq_low, 'market': eq_mkt}).plot(\n"
            "    title='Cumulative wealth by leg (equal-weight, start=1.0)',\n"
            "    color=['#2ea44f', '#c0392b', '#8b949e']\n"
            ")\n"
            "plt.ylabel('Wealth'); plt.show()"
        ),
        md(
            "## 5 · The verdict\n\n"
            "H1/H2/H3 all rejected on tradable large caps → Signal `WEAK` (inverted at −2.8%/yr, "
            "t −1.3), Tradability `MIRAGE`, shareholder-yield-predicts-outperformance `NOT SUPPORTED`. "
            "The fingerprinted run is in [`docs/results.md`](../docs/results.md)."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Not on this universe. To harvest a genuine premium you'd need: (a) a broader universe "
            "including small caps; (b) value-weighting with NYSE breakpoints; (c) delisting-inclusive "
            "returns. The large-cap S&P 500 is too well-arbitraged and too dominated by the "
            "growth-beats-yield regime to show this factor working."
        ),
        md(
            "## 7 · Going further\n\n"
            "Forks: (a) Russell 2000 / micro-cap universe; (b) add explicit dividend yield (yfinance); "
            "(c) composite with accruals ([52](../../52-smoke-screen/)) and asset growth "
            "([44](../../44-growth-spurt/)) into a quality + capital-discipline factor. "
            "The pure buyback predecessor: [64 Share-Shuffle](../../64-share-shuffle/)."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
