"""Generate the two narrative notebooks for Study 31 (Trade-Winds) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs OFFLINE on the seeded synthetic regime-switching trend panel (the machinery);
the real-tape verdict (18 futures, 2000-2026) is quoted from ../docs/results.md. Both notebooks walk
the SAME seven desk beats.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from trade_winds import data, strategy, costs, extension

# Offline synthetic control: regime-switching trend panel (the machinery) + a random-walk null.
# The real 18-futures verdict is in ../docs/results.md.
r, truth = data.synthetic_trends(trend_strength=0.12, seed=31)
r0, _ = data.synthetic_trends(trend_strength=0.0, seed=31)
print(f"synthetic control: {truth.n_markets} markets x {truth.n_days} days, trend_strength {truth.trend_strength} (null=0)")
"""

# Real-tape numbers (../docs/results.md, 18 futures 2000-2026, as-of 2026-06-10, fp efab160ee1f0)
R = dict(fp="efab160ee1f0", asof="2026-06-10", days="6546", n="18",
         ts_sh="0.30", ts_cagr="2.8", ts_dd="-35", ts_skew="+1.50",
         lob_sh="0.51", b6040_sh="0.48",
         crisis="+23.6", rest="+1.1", corr="-0.07", ncrisis="31",
         eq_sh="0.43", eq_dd="-57", eqtr_sh="0.52", eqtr_dd="-33",
         b_sh="0.48", b_dd="-34", btr_sh="0.56", btr_dd="-20",
         sub1="+0.83", sub2="-0.28", sub3="+0.29",
         syn_prem="2.4", syn_null="0.2",
         wide_n="27", wide_sh="0.55", wide_fp="78f6e1add375",
         br1="0.20", br8="0.46", br16="0.51", br27="0.55")

BADGES = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Crisis alpha?: Confirmed](https://img.shields.io/badge/Crisis_alpha%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Trade-Winds 🌬️\n"
            "### \"The trend is your friend\" — the one trading cliché that actually survives the data. But how do you *get paid* for it?\n\n"
            + BADGES +
            "Almost every clever strategy this desk tests turns out to be a mirage. Here's the exception. "
            "Ask each market — stocks, bonds, oil, gold, the euro — one dumb question: *has it been going "
            "up or down lately?* Ride the ones going up, short the ones going down, spread your risk evenly "
            "across all of them. It's the engine of the entire managed-futures industry, and it has a "
            "century of evidence behind it. The twist: on its own it *won't* beat just owning a basket — "
            "but it makes money exactly when stocks crash, and **that** turns out to be worth a great deal.\n\n"
            "> 📓 **This is the plain-language layer.** The cost & lookback sweeps, the decay, and the "
            "crisis-alpha decomposition are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it; the core "
            "runs on a **synthetic** trend panel, so the real-futures numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Is trend-following real? | ✅ **Yes.** It pays across every lookback, recovers on our control "
            f"(Sharpe {R['syn_prem']} vs the null's {R['syn_null']}), and has a fat *right* tail (skew {R['ts_skew']}). |\n"
            "| Does it beat just owning the basket? | 🟡 **No, on its own.** Net Sharpe **{ts}** trails the "
            "always-long basket (**{lob}**) and 60/40 (**{b}**). |\n"
            "| So why run it? | ⚪ **Crisis alpha.** It makes **{cr}%/yr when stocks crash** (corr **{c}**); "
            "a 30% sleeve lifts a 60/40's Sharpe **{bs}→{bts}** and halves its drawdown **{bd}%→{btd}%**. |\n\n"
            "> Desk shorthand: **Signal `REAL` · Tradability `FRAGILE` · Crisis alpha? `CONFIRMED`** — the "
            "edge isn't prediction, it's diversification.".format(
                ts=R['ts_sh'], lob=R['lob_sh'], b=R['b6040_sh'], cr=R['crisis'], c=R['corr'],
                bs=R['b_sh'], bts=R['btr_sh'], bd=R['b_dd'], btd=R['btr_dd'])
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Time-series momentum, the steelman the academics actually defend (Moskowitz-Ooi-Pedersen 2012; "
            "Hurst-Ooi-Pedersen's *century of evidence* 2017):\n\n"
            "1. **Signal** — for each market, the sign of its own trailing 1/3/12-month return. Long if up, short if down.\n"
            "2. **Equal risk** — divide each position by its own volatility, so a sleepy bond future and a "
            "wild gas future take the *same* risk.\n"
            "3. **Diversify** — hold ~18 markets across four asset classes; the edge is the *portfolio* of "
            "thin trend signals, not any one bet.\n\n"
            "Crucially this is *time-series* (each market vs its own past), **not** the cross-sectional "
            "equity momentum the desk already busted (Studies 24–25) — a different, sturdier animal."
        ),
        code(
            "book = strategy.book_returns(r, cost_bps=2.0)\n"
            "eq = (1+book).cumprod()\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(eq.index, eq.values, color='#2ea44f', lw=1.1)\n"
            "ax.set_yscale('log'); ax.set_title('TSMOM on the synthetic trend panel — the premium is real')\n"
            "s = strategy.summary(book); print(f\"Sharpe {s['sharpe']:.2f}  CAGR {s['cagr']*100:.1f}%  skew {s['skew']:+.2f}\")"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "A real, decorrelated return stream is the holy grail of portfolio construction — far more "
            "useful than yet another thing correlated to stocks. Trend-following is the biggest, oldest "
            "example a retail trader can actually access (via futures or managed-futures ETFs). The desk's "
            "question isn't *'is it real'* (it is) — it's the subtler one: does the *timing* earn its keep, "
            "or is owning a diversified basket already most of the prize?"
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "1. **Real?** Does the book pay on the control and across lookbacks, and stay flat on a random-walk null?\n"
            "2. **Standalone edge?** Net Sharpe vs the *always-long* basket of the same markets, and vs 60/40.\n"
            "3. **Crisis alpha?** Its return in the worst equity months, and its correlation to stocks.\n"
            "4. **The payoff:** does blending a sleeve into a normal portfolio raise Sharpe / cut drawdown?\n\n"
            "**Fragile line:** standalone net Sharpe below the long-only basket — the timing adds nothing alone."
        ),

        md("## 4 · The teardown 🔧\n\n### 4a · Real on the control, nothing on the null"),
        code(
            "for label, rr in [('trend panel', r), ('null (random walk)', r0)]:\n"
            "    s = strategy.summary(strategy.book_returns(rr, cost_bps=2.0))\n"
            "    print(f\"{label:20} Sharpe {s['sharpe']:+.2f}  skew {s['skew']:+.2f}\")"
        ),
        md(
            "### 4b · On the real tape — fragile alone, but real crisis alpha\n"
            "On 18 real futures, 2000–2026 ([`../docs/results.md`](../docs/results.md)):\n\n"
            f"- Standalone net Sharpe **{R['ts_sh']}** — *below* the always-long basket (**{R['lob_sh']}**) "
            f"and 60/40 (**{R['b6040_sh']}**). The timing alone doesn't clear the bar.\n"
            f"- But it earns **{R['crisis']}%/yr in the worst {R['ncrisis']} equity months** vs {R['rest']}% "
            f"the rest of the time, at **{R['corr']}** correlation to stocks — textbook crisis alpha.\n"
            f"- Sub-period Sharpe **{R['sub1']} / {R['sub2']} / {R['sub3']}** — it worked, endured the "
            "2010s drought, then revived. A real premium with real lean years."
        ),

        md("### 4c · The payoff — trend as a portfolio diversifier"),
        code(
            "eqr = r['MKT00'].reindex(book.index)   # a stand-in 'equities' sleeve on the synthetic\n"
            "def st(x):\n"
            "    s = strategy.summary(x); return f\"Sharpe {s['sharpe']:.2f}  maxDD {s['max_drawdown']*100:.0f}%\"\n"
            "print('one market alone       ', st(eqr))\n"
            "print('70% market / 30% trend ', st(0.7*eqr + 0.3*book))\n"
            "print('\\nReal portfolios (../docs/results.md):')\n"
            f"print('  equities only            Sharpe {R['eq_sh']}  maxDD {R['eq_dd']}%')\n"
            f"print('  60% equities / 40% trend Sharpe {R['eqtr_sh']}  maxDD {R['eqtr_dd']}%')\n"
            f"print('  60/40 only               Sharpe {R['b_sh']}  maxDD {R['b_dd']}%')\n"
            f"print('  70% 60/40 / 30% trend    Sharpe {R['btr_sh']}  maxDD {R['btr_dd']}%')"
        ),
        md(
            "> 🔬 **For the quants.** Because the book is ~−0.07 correlated to equities with positive skew, "
            "adding it *raises* a portfolio's Sharpe **and** cuts its drawdown at the same time — the genuine "
            "free-ish lunch of diversification, not a timing miracle."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **Real premium** — control Sharpe {R['syn_prem']} vs null {R['syn_null']}; positive across lookbacks; +skew.\n"
            f"- **Fragile standalone** — net Sharpe {R['ts_sh']} < long-only basket {R['lob_sh']}; a decade-long drought.\n"
            f"- **Crisis alpha confirmed** — {R['crisis']}%/yr in equity crises, corr {R['corr']}; a 30% sleeve "
            f"lifts 60/40 Sharpe {R['b_sh']}→{R['btr_sh']}, drawdown {R['b_dd']}%→{R['btr_dd']}%.\n\n"
            "> **Signal `REAL` · Tradability `FRAGILE` · Crisis alpha? `CONFIRMED`.** Not a standalone money "
            "machine — decorrelated insurance that pays you to hold it."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "- **Yes — but as a *sleeve*, not the whole book.** Run 20–40% trend alongside your stocks/bonds; "
            "the −0.07 correlation does the work. As 100% of your money it under-earns the basket.\n"
            "- **Costs are friendly.** Futures embed carry in the price (no CFD-style full-notional "
            "financing — see Study 30), and the basket is the most liquid stuff alive; the book breaks even "
            "around 5 bp and trades slowly.\n"
            "- **The price of admission is patience.** You must sit through droughts like 2011–2019 to "
            "collect the crisis payoff in 2008, 2020, 2022. Most people can't, which is partly why it persists."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "### Worked complement — breadth is the lever ([`../docs/extension.md`](../docs/extension.md))\n"
            f"We widened from the 18 futures to a **{R['wide_n']}-market** liquid-ETF universe and swept the "
            "Sharpe against the number of markets:\n\n"
            f"- One market trends at Sharpe ~**{R['br1']}**; spreading the same signal over more markets "
            f"lifts it monotonically — **{R['br8']}** at 8, **{R['br16']}** at 16, **{R['br27']}** at all "
            f"{R['wide_n']}.\n"
            f"- The full wider book's standalone Sharpe is **{R['wide_sh']}** — *above* the basket (0.51) "
            "and 60/40 (0.48) that the narrow 18-market book trailed. **The `FRAGILE` standalone verdict "
            "was largely a breadth limitation** — and the curve is still rising at 27, which is why real "
            "managed futures runs 50–100+ markets.\n\n"
            "### Other forks\n"
            "- **More breadth still** — single-stock futures, more rates/FX; the sweep says Sharpe keeps climbing.\n"
            "- **Combine with carry** — trend + carry is the classic two-premium managed-futures core.\n"
            "- **Right-size the sleeve for *your* portfolio** — fork the blend cell and solve the weight.\n\n"
            "PRs welcome — widen the universe further, add a carry sleeve, or optimise the portfolio weight."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Trade-Winds — a quantitative teardown 🔬\n"
            "### TSMOM vs the long-only basket · the cost & lookback sweeps · sub-period decay · crisis-alpha decomposition · the portfolio blend\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its number.* The steelman: cross-asset time-series momentum is a real, "
            "century-tested premium with crisis alpha. We confirm it's real, show it's fragile *standalone*, "
            "and that its value is as a decorrelated portfolio diversifier.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on a synthetic regime-switching trend panel; "
            "the real 18-futures run is in [`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            f"| **Signal** — is TSMOM real? | 🟢 `REAL` | Control Sharpe **{R['syn_prem']}** vs null "
            f"**{R['syn_null']}**; positive across lookbacks; skew **{R['ts_skew']}**. |\n"
            f"| **Tradability** — beats the basket standalone? | 🟡 `FRAGILE` | Net Sharpe **{R['ts_sh']}** < "
            f"long-only basket **{R['lob_sh']}** < ; 2010s drought (**{R['sub2']}**); break-even ~5 bp. |\n"
            f"| **Crisis alpha?** | ⚪ `Confirmed` | **{R['crisis']}%/yr** in worst equity months, corr "
            f"**{R['corr']}**; a 30% sleeve lifts 60/40 Sharpe **{R['b_sh']}→{R['btr_sh']}**. |\n\n"
            "> **In one sentence:** a real, century-tested premium that under-earns a diversified basket on "
            "its own, but is genuinely uncorrelated crisis insurance — its job is to be *in* a portfolio.\n\n"
            "*(This notebook executes on the synthetic control; the real numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Per market $i$: signal $s_{i,t} = \\mathrm{sign}\\!\\big(\\tfrac13\\sum_{L\\in\\{21,63,252\\}}"
            "\\mathrm{sign}(P_{i,t}/P_{i,t-L}-1)\\big)$, lagged. Position $w_{i,t} = s_{i,t}\\cdot"
            "\\min(\\sigma^\\star_{\\text{mkt}}/\\hat\\sigma_{i,t},\\,c)$, then the book is scaled to a "
            "portfolio vol target. Claim: the portfolio $\\sum_i w_{i,t-1} r_{i,t}$ earns a positive, "
            "crisis-robust premium. Null: returns are i.i.d. (no trend) ⇒ no premium."
        ),
        code(
            "for label, rr in [('trend panel', r), ('null', r0)]:\n"
            "    s = strategy.summary(strategy.book_returns(rr, cost_bps=2.0))\n"
            "    print(f\"{label:12} Sharpe {s['sharpe']:+.2f}  CAGR {s['cagr']*100:+.1f}%  skew {s['skew']:+.2f}\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "A −0.07-correlated, positive-skew return stream is worth more to a portfolio than a higher-"
            "Sharpe stream correlated to what you already own: it shifts the efficient frontier out. The "
            "convex (long-volatility) payoff of trend (Fung-Hsieh 2001) is *why* it pays in crashes and *why* "
            "it bleeds in quiet ranges — the same coin. Beats 4–6 quantify both sides."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Real?** `book_returns` on control vs null; `extension.lookback_sweep`.\n"
            "2. **Standalone edge?** vs `costs.long_only_basket` and 60/40.\n"
            "3. **Crisis alpha** (`costs.crisis_alpha`): return in worst equity months, corr to equities.\n"
            "4. **Decay** (`extension.subperiod_sharpe`) + **costs** (`costs.cost_sweep`).\n\n"
            "**Fragile line:** standalone net Sharpe < the long-only basket of the same markets."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · Standalone vs the basket (the FRAGILE call)"),
        code(
            "print('Real tape (../docs/results.md):')\n"
            f"print('  TSMOM           Sharpe {R['ts_sh']}  CAGR {R['ts_cagr']}%  maxDD {R['ts_dd']}%  skew {R['ts_skew']}')\n"
            f"print('  long-only basket Sharpe {R['lob_sh']}')\n"
            f"print('  60/40 (ES/ZN)    Sharpe {R['b6040_sh']}')\n"
            "# on the synthetic control the timing genuinely adds (trends are strong there):\n"
            "print('\\nSynthetic control:')\n"
            "print(f\"  TSMOM            Sharpe {strategy.summary(strategy.book_returns(r))['sharpe']:.2f}\")\n"
            "print(f\"  long-only basket Sharpe {strategy.summary(costs.long_only_basket(r))['sharpe']:.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** Where trends are strong (the control) the timing wins; on the real, "
            "noisier tape the always-long diversified basket already captures most of the Sharpe, so the "
            "timing *alone* is `FRAGILE`. The value has to come from somewhere else — beat 4b."
        ),

        md("### 4b · Crisis alpha and the portfolio blend (the CONFIRMED prize)"),
        code(
            "ca = costs.crisis_alpha(r, equity_cols=['MKT00','MKT01','MKT02'])\n"
            "print('synthetic crisis-alpha shape:', {k:(round(v,3) if isinstance(v,float) else v) for k,v in ca.items()})\n"
            "print('\\nReal tape (../docs/results.md):')\n"
            f"print('  worst {R['ncrisis']} equity months: {R['crisis']}%/yr  | rest: {R['rest']}%/yr  | corr {R['corr']}')\n"
            f"print('  equities only            Sharpe {R['eq_sh']}  maxDD {R['eq_dd']}%')\n"
            f"print('  60% equities / 40% trend Sharpe {R['eqtr_sh']}  maxDD {R['eqtr_dd']}%')\n"
            f"print('  60/40 only               Sharpe {R['b_sh']}  maxDD {R['b_dd']}%')\n"
            f"print('  70% 60/40 / 30% trend    Sharpe {R['btr_sh']}  maxDD {R['btr_dd']}%')"
        ),

        md("## Beat 5 · The verdict\n\n"
           f"- **Real** (4a, Beat 1): control Sharpe {R['syn_prem']} vs null {R['syn_null']}; +skew; lookback-robust.\n"
           f"- **Fragile standalone** (4a): net {R['ts_sh']} < basket {R['lob_sh']}; drought {R['sub2']}.\n"
           f"- **Crisis alpha confirmed** (4b): {R['crisis']}%/yr in crises; blend lifts Sharpe & cuts drawdown.\n\n"
           "> **Signal `REAL` · Tradability `FRAGILE` · Crisis alpha? `CONFIRMED`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           "- **As a 20–40% sleeve, yes.** The diversification raises portfolio Sharpe and halves drawdown; "
           "as a standalone it under-earns the basket.\n"
           "- **Costs are benign** — futures (no full-notional financing, cf. Study 30), break-even ~5 bp, "
           "slow turnover. Capacity is enormous (a multi-hundred-billion industry).\n"
           "- **Behavioural moat:** the 2011–2019 drought is the price of admission; sitting through it is "
           "why the premium survives arbitrage."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — breadth is the lever ([`../docs/extension.md`](../docs/extension.md))\n"
            "The standalone book was `FRAGILE` (Sharpe 0.30) on 18 futures. The literature says that's a "
            "*breadth* artefact. We sweep the Sharpe against the number of markets — on the synthetic here, "
            f"on a {R['wide_n']}-market liquid-ETF universe in [`../docs/extension.md`](../docs/extension.md)."
        ),
        code(
            "bs = extension.breadth_sweep(r, ks=[1,2,4,8,12,18], n_draws=30, seed=31)\n"
            "display(bs.round(3))\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(bs.index, bs['mean_sharpe'], marker='o', color='#2ea44f')\n"
            "ax.fill_between(bs.index, bs['sharpe_p25'], bs['sharpe_p75'], alpha=0.2, color='#2ea44f')\n"
            "ax.set_xlabel('number of markets'); ax.set_ylabel('mean net Sharpe'); ax.set_title('Trend Sharpe scales with breadth')\n"
            f"print('Real wider ETF universe (../docs/extension.md, {R['wide_n']} markets): '\n"
            f"      '1->{R['br1']}, 8->{R['br8']}, 16->{R['br16']}, {R['wide_n']}->{R['wide_sh']} '\n"
            "      '-- standalone Sharpe now ABOVE the basket (0.51) and 60/40 (0.48).')"
        ),
        md(
            "> 💡 **In plain words.** A single market trends at Sharpe ~0.2; spread the same signal over "
            f"more markets and it climbs monotonically. Widening from 18 futures to {R['wide_n']} ETFs "
            f"lifts the standalone book to **{R['wide_sh']}** — *past* the benchmarks the narrow book "
            "trailed. The `FRAGILE` stamp was largely a breadth limit; the curve is still rising at "
            f"{R['wide_n']}, which is why real managed futures runs 50–100+ markets."
        ),
        md(
            "### 7b · The lookback sweep & the honest decay\n"
            "Not a tuned lookback (positive across horizons), and the 2010s drought shown openly."
        ),
        code(
            "print('Lookback sweep (synthetic):'); print(extension.lookback_sweep(r).round(3).to_string())\n"
            f"print('\\nReal sub-period Sharpe (../docs/results.md): {R['sub1']} / {R['sub2']} / {R['sub3']}')\n"
            "print('Real lookback sweep: 1m 0.07, 3m 0.28, 6m 0.39, 12m 0.65, blend 0.30 -- positive across, strongest at 12m.')"
        ),
        md(
            "**The result.** Breadth lifts the standalone Sharpe past the benchmarks (7a); the premium is "
            "positive across every lookback (not a tuned parameter); and the sub-period Sharpe exposes the "
            "real 2010s drought honestly. A real premium with real lean years, whose portfolio value "
            "(crisis alpha) survives both. Full runs in [`../docs/results.md`](../docs/results.md) and "
            "[`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7c · Other forks\n"
            "- **More breadth still** — 50–100 markets; the sweep predicts the Sharpe keeps rising.\n"
            "- **Trend + carry** — the two-premium managed-futures core; do they diversify each other?\n"
            "- **Optimal sleeve weight** — solve the portfolio weight for a given book and risk aversion.\n\n"
            "PRs welcome — widen the universe, add carry, or optimise the blend."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
