"""Generate the two narrative notebooks for Study 02 (Falling-Knife) from source.

Like Study 01, the notebooks are a *generated artefact*: edit the cell text here,
rebuild the skeletons, then execute with nbconvert to embed figures/outputs.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

First execution hits the network (Yahoo! Finance: ^NDX, QQQ, ^GSPC, SPY); later
runs use the local parquet cache.

Both notebooks follow the SAME seven desk beats (see ../../../METHODOLOGY.md):
  0 Verdict · 1 The Claim · 2 So What? · 3 How We'd Know · 4 The Teardown ·
  5 The Verdict · 6 Could You Trade It? · 7 Going Further
  01_for_the_curious  — the plain-language layer
  02_for_the_quants   — the deep layer: event study, random-day null, bootstrap,
                        deflation, capacity, in/out-of-sample
NOTE: we never import falling_knife.plots here — it forces the Agg backend, which
breaks inline rendering. Every figure is drawn inline from the returned data.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))  # study root (falling_knife/ lives there)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from falling_knife import data, triggers, exits, eventstudy, benchmark, backtest, robustness, sweeps
"""


def md(text):
    return new_markdown_cell(text)


def code(text):
    return new_code_cell(text)


# ===========================================================================
# 01 — FOR THE CURIOUS   (the plain-language layer of the seven beats)
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Does buying the dip actually pay? 🔪\n"
            "### \"Buy when there's blood in the streets\" — tested honestly, in plain English\n\n"
            "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
            "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n\n"
            "Everyone *knows* you should buy the dip. The Nasdaq has spent decades making "
            "new highs, so surely buying after a scary **−3% down day** and waiting for the "
            "bounce is free money? This notebook checks that feeling against 40 years of "
            "real data — gently, with code you can run yourself. The twist is a single idea "
            "that flips the whole question on its head. *Spoiler: the famous −3% rule is "
            "folklore; the real story hides somewhere more interesting.*\n\n"
            "> 📓 **This is the plain-language layer.** Want the statistics, the "
            "microstructure and the capacity maths? That's the companion notebook, "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** An educational, reproducible research tool: "
            "every chart below is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        # ---- BEAT 0 — VERDICT -------------------------------------------------
        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does buying the **−3%** Nasdaq dip beat buying a **random day**? | ❌ **No** — it's indistinguishable from buying any day. You just collect the market's drift, with extra drama. |\n"
            "| Is there *any* dip worth buying? | ⚠️ **Only deep panic** (−5% to −7%) leaves a real bounce — but it's rare and crash-dominated. |\n"
            "| Could you build a **strategy** on it? | ❌ **No** — too few events, and a fixed rule flips from winner to loser out-of-sample. |\n\n"
            "> Desk shorthand: **Signal `NONE` at −3% · `WEAK` in deep panic · Tradability "
            "`MIRAGE`**. Let's earn those stamps."
        ),

        # ---- BEAT 1 — THE CLAIM ----------------------------------------------
        md(
            "## 1 · The claim — \"buy the dip\"\n\n"
            "It's the most repeated piece of market folk-wisdom there is: when the index "
            "drops hard, that's your moment — pile in, ride the rebound. On the Nasdaq-100, "
            "the specific version people quote is the **−3% day**: the market closes down "
            "3%, you buy, you wait a few days for the bounce.\n\n"
            "Stated plainly, the claim is: *buying after a −3% close earns you more than "
            "buying on an ordinary day.* That's a precise, checkable statement — so let's "
            "check it."
        ),

        # ---- BEAT 2 — SO WHAT? -----------------------------------------------
        md(
            "## 2 · So what? Why it's worth checking\n\n"
            "Because if it's true, it's a simple, free edge any retail trader could run — "
            "and if it's *false*, a lot of people are taking on **extra fear, extra "
            "drawdown, and extra trading** to earn exactly what they'd have made sitting "
            "still. \"Buy the dip\" isn't harmless folklore if it quietly makes your ride "
            "worse for no extra reward.\n\n"
            "And there's a deeper lesson hiding here that applies to *every* strategy you'll "
            "ever be sold — which is the next beat."
        ),

        # ---- BEAT 3 — HOW WE'D KNOW ------------------------------------------
        md(
            "## 3 · How would we know? (the one trap that matters)\n\n"
            "Here's the idea that flips the question. **The market drifts up anyway.** Over "
            "decades the Nasdaq rises most of the time — so if you buy on *any* random day "
            "and wait a week, you usually make a little money. A green equity curve after "
            "dip-buying therefore proves **nothing** on its own: of course it went up, "
            "everything goes up.\n\n"
            "So the real question is not *\"did it go up after the dip?\"* It's:\n\n"
            "> **Did it go up *more* than on a normal day?**\n\n"
            "That comparison — *the dip vs a random day* — is the heart of everything. Our "
            "plan: **(a)** line up every −3% day and look at the average path afterwards (an "
            "*event study*), **(b)** compare that to a random day to get the true *excess*, "
            "**(c)** try deeper drops to see if anything changes, and **(d)** ask whether "
            "you could actually trade what's left.\n\n"
            "> 🔬 **For the quants** — \"compare to a random day\" is a permutation test for "
            "excess return over the unconditional baseline. The deep notebook adds a block "
            "bootstrap (these events cluster), deflated Sharpe (we scan a whole family of "
            "rules), and an out-of-sample split. See "
            "[`02_for_the_quants.ipynb`](02_for_the_quants.ipynb)."
        ),

        # ---- BEAT 4 — THE TEARDOWN -------------------------------------------
        md(
            "## 4 · The teardown — let's look\n\n"
            "We'll use two faces of the same market: **^NDX**, the spot Nasdaq-100 index "
            "with deep history (since 1985, so it includes the big crashes), and **QQQ**, "
            "the ETF you could actually trade (since 1999). First, line up every −3% close "
            "and watch what happens on average over the next 20 trading days."
        ),
        code(
            "ndx = data.fetch('^NDX', mode='split_only')\n"
            "qqq = data.fetch('QQQ', mode='split_only')\n"
            "ret_ndx = data.daily_returns(ndx)\n"
            "ret_qqq = data.daily_returns(qqq)\n\n"
            "ev_qqq = triggers.first_crossings(triggers.close_to_close(ret_qqq, -0.03), cooldown=20)\n"
            "es = eventstudy.event_study(qqq, ev_qqq, horizon=20, pre=5)\n"
            "summ = es['summary']; n = es['n_events']; se = summ['std'] / np.sqrt(max(n, 1))\n"
            "ax = plt.subplot()\n"
            "ax.axhline(0, color='0.6', lw=.8)\n"
            "ax.axvline(0, color='crimson', ls='--', lw=1, label='you buy (t=0)')\n"
            "ax.plot(summ.index, summ['mean']*100, color='navy', lw=2, label='average path')\n"
            "ax.fill_between(summ.index, (summ['mean']-se)*100, (summ['mean']+se)*100, color='navy', alpha=.15, label='±1 s.e.')\n"
            "ax.set_xlabel('trading days after the dip'); ax.set_ylabel('average return since you bought (%)')\n"
            "ax.set_title(f'QQQ: what happens after a -3% day (n={n} events)')\n"
            "ax.legend(); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "The line sags for a week, then crawls back above zero — by the end of the "
            "month you're up a touch. *Looks* like the bounce eventually shows up! But "
            "remember the trap: the market drifts up after a *random* day too. So is this "
            "recovery actually bigger than normal? Let's run the decisive comparison — the "
            "dip vs a random day:"
        ),
        code(
            "bench = benchmark.conditional_vs_unconditional(qqq, ev_qqq, horizons=(1, 5, 10, 20))\n"
            "view = bench[['n_events', 'mean_cond', 'mean_uncond', 'excess', 'p_greater']].copy()\n"
            "for c in ['mean_cond', 'mean_uncond', 'excess']:\n"
            "    view[c] = (view[c]*100).map('{:+.2f}%'.format)\n"
            "view['p_greater'] = view['p_greater'].map('{:.2f}'.format)\n"
            "view.columns = ['# dips', 'after dip', 'after random day', 'EXCESS', 'p-value']\n"
            "view.index.name = 'days held'\n"
            "view"
        ),
        md(
            "There it is. **\"After dip\" never beats \"after random day\".** The *excess* — "
            "the only thing that matters — sits at zero or **below** at every horizon, and "
            "the p-value is nowhere near significant (you want it below 0.05; here it's "
            "0.5–0.99). Buying the −3% Nasdaq dip earns you, at best, what buying any old "
            "Tuesday earns you. **The famous rule is folklore.**\n\n"
            "But wait — maybe −3% just isn't scary enough. What if we only buy *real* "
            "panic? Let's deepen the drop and overlay the average paths:"
        ),
        code(
            "es_by = {}\n"
            "for thr in (-0.03, -0.05, -0.07):\n"
            "    ev = triggers.first_crossings(triggers.close_to_close(ret_ndx, thr), cooldown=20)\n"
            "    es_by[f'{thr:.0%} day'] = eventstudy.event_study(ndx, ev, horizon=20, pre=3)\n"
            "ax = plt.subplot(); ax.axhline(0, color='0.6', lw=.8); ax.axvline(0, color='0.4', ls='--', lw=1)\n"
            "cmap = plt.get_cmap('viridis'); items = list(es_by.items())\n"
            "for i, (lab, r) in enumerate(items):\n"
            "    s = r['summary']\n"
            "    ax.plot(s.index, s['mean']*100, lw=2, color=cmap(i/max(len(items)-1, 1)), label=f\"{lab}  (n={r['n_events']})\")\n"
            "ax.set_xlabel('trading days after the dip'); ax.set_ylabel('average return since entry (%)')\n"
            "ax.set_title('Nasdaq-100: the deeper the drop, the bigger the bounce'); ax.legend(title='you bought after a...'); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "*Now* something shows up. A −3% day goes basically nowhere, but a **−7% day** — "
            "genuine, gut-wrenching panic — bounces noticeably harder. The effect grows "
            "smoothly as the drop deepens, which is the signature of something **real** "
            "rather than a fluke. So there *is* a dip worth buying — it just isn't the −3% "
            "one everybody quotes. It's the rare, terrifying −7% kind."
        ),

        # ---- BEAT 5 — THE VERDICT --------------------------------------------
        md(
            "## 5 · The verdict — so, does buying the dip pay?\n\n"
            "| | |\n|---|---|\n"
            "| ❌ **The −3% rule is folklore** | no better than buying a random day, on the Nasdaq *and* the S&P 500. |\n"
            "| ✅ **Deep panic is different** | −5% to −7% drops leave a real, statistically visible bounce that grows with depth. |\n"
            "| ⚠️ **But \"real\" ≠ \"tradeable\"** | those crashes are rare and bunched in 2000 / 2008 / 2020 — a handful of events, not a strategy. |\n\n"
            "So the honest answer splits in two: the popular version is a myth, and the one "
            "real version is something you almost never get to use. The next beat makes that "
            "concrete — could you actually run it?"
        ),

        # ---- BEAT 6 — COULD YOU TRADE IT? ------------------------------------
        md(
            "## 6 · Could you actually trade it?\n\n"
            "Suppose you're disciplined and you only buy the real, deep-panic dips. Two "
            "problems make it a non-strategy. **First, they almost never happen** — a −7% "
            "Nasdaq day fires only about three times a *decade*, and most of those cluster "
            "in a couple of historic crashes. **Second, and worse: a fixed deep-dip rule "
            "doesn't survive the future.** Let's split history in half — learn on the first "
            "60%, then test on the unseen 40% — for a \"buy −5%, hold 5 days\" rule:"
        ),
        code(
            "raw5 = triggers.close_to_close(ret_ndx, -0.05)\n"
            "is_o, oos_o = robustness.split_sample(ndx, 0.6)\n"
            "rows = {}\n"
            "for tag, seg in (('In-sample (first 60%)', is_o), ('Out-of-sample (last 40%)', oos_o)):\n"
            "    sig = triggers.first_crossings(raw5.reindex(seg.index), cooldown=20)\n"
            "    r = backtest.run(seg, sig, exits.ExitRule(max_hold=5), backtest.CostModel())\n"
            "    rows[tag] = {'trades': r.stats['n_trades'], 'CAGR': f\"{r.stats['cagr']:+.1%}\", 'Sharpe': f\"{r.stats['sharpe']:+.2f}\"}\n"
            "pd.DataFrame(rows).T"
        ),
        md(
            "The rule that looked like a winner in the first half turns into a **loser** in "
            "the second half — the Sharpe flips sign. That's the classic tell of something "
            "that was never a stable edge: it worked until it didn't. Notice what *isn't* "
            "the problem here — trading **costs**. Because you trade so rarely, fees barely "
            "matter. The thing standing between you and profit isn't the spread; it's that "
            "**there was almost no real edge to begin with**.\n\n"
            "> 🔬 **For the quants** — the deep notebook nails this down: a clustering-aware "
            "block bootstrap whose 95% CI on the excess straddles zero, a family scan whose "
            "flashy Sharpe>2 cells are pure drift (they collapse out-of-sample), and a "
            "capacity count showing ~3 events/decade dominated by 2–3 crashes."
        ),

        # ---- BEAT 7 — GOING FURTHER ------------------------------------------
        md(
            "## 7 · Going further 🚪\n\n"
            "- **Get the rigorous version.** "
            "[`02_for_the_quants.ipynb`](02_for_the_quants.ipynb) runs the full honest "
            "battery: permutation tests, the block bootstrap that respects clustering, "
            "deflated Sharpe over the whole family of rules, the Nasdaq-vs-S&P "
            "generalisation, and the in/out-of-sample collapse.\n"
            "- **Run it offline first.** `python examples/run_synthetic_demo.py` builds two "
            "fake markets — one with a real dip-edge, one without — and shows the tools "
            "correctly telling them apart. That's your proof the measurement works before "
            "you trust it on real data.\n"
            "- **Poke it yourself.** Change the threshold, the holding period, the index — "
            "every cell is yours. What would change the verdict? (A real excess over the "
            "random-day baseline that *survives* out-of-sample. We didn't find one.)\n\n"
            "The one lesson to carry everywhere: **always compare your brilliant strategy to "
            "buying a random day.** Most \"edges\" are just the market's drift wearing a "
            "costume. New studies follow the same seven beats "
            "([METHODOLOGY.md](../../../METHODOLOGY.md))."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS   (the deep layer of the same seven beats)
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Falling-Knife — a quantitative teardown 🔬\n"
            "### Random-day null · block bootstrap · deflated Sharpe · capacity · out-of-sample\n\n"
            "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
            "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n\n"
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) "
            "— *same seven beats, every claim now carrying its standard error.* We don't "
            "test *one* \"buy the −3% dip\" rule; we test a **family** of them and hold each "
            "to the only yardstick that matters: does it beat buying on a **random day**, "
            "after realistic costs, and does it survive out-of-sample?\n\n"
            "> ⚠️ **Not investment advice.** Data: Yahoo! Finance via the study's `data` "
            "module, mode `split_only`. First run hits the network (^NDX, QQQ, ^GSPC, SPY); "
            "later runs use the parquet cache. House style, beats and protocol: "
            "[METHODOLOGY.md](../../../METHODOLOGY.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition "
            "— so this notebook still reads even if you skim the maths. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        # ---- BEAT 0 — VERDICT -------------------------------------------------
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why (one line) |\n"
            "|---|---|---|\n"
            "| **Signal** — is the effect statistically real? | `NONE` @ −3% · `WEAK` deep | At −3% the excess over a random day is ~0 (p≈0.8 on ^NDX); a real bounce only appears at −5%/−7%. |\n"
            "| **Tradability** — survives costs, capacity, scale? | `MIRAGE` | Deep-dip excess straddles zero under a clustering-aware bootstrap; ~3 events/decade dominated by 2–3 crashes; fixed rule flips +1.3→−1.4 Sharpe out-of-sample. |\n\n"
            "> 💡 **In plain words** — the round number is a myth, the one real effect lives "
            "in rare panics you can't build a business on, and every flashy backtest Sharpe "
            "here turns out to be the market's drift in disguise."
        ),

        # ---- BEAT 1 — THE CLAIM ----------------------------------------------
        md(
            "## 1 · The claim, and why it's really a *family* of claims\n\n"
            "\"Buy the −3% Nasdaq dip\" sounds like one rule, but a single threshold is not "
            "a single strategy. There are at least four defensible ways to define \"the "
            "falling knife\", and they can disagree wildly:\n\n"
            "| ID | Definition | Reads as |\n|---|---|---|\n"
            "| **T1** | session **closes** ≤ −3% | the classic down-3%-day |\n"
            "| **T2** | trades ≤ −3% below the open **intraday** | most reactive, same-day fill |\n"
            "| **T3** | close ≥ 3% below a **rolling high** (drawdown) | the slide already started |\n"
            "| **T4** | **cumulative** return over N days ≤ −3% | the slow bleed |\n\n"
            "Multiply by a grid of exits (time / take-profit / stop / hybrid) and you have a "
            "whole **family**. Testing the family — not one lucky member — is the only "
            "honest way, because scanning dozens of rules guarantees one looks great by "
            "chance. The triggers loaded:"
        ),
        code(
            "print('Triggers :', list(triggers.TRIGGERS.keys()))\n"
            "print('Exit grid:', len(exits.default_grid()), 'rules  ->  family =',\n"
            "      len(triggers.TRIGGERS)*len(exits.default_grid()), '(trigger x exit) combos')"
        ),

        # ---- BEAT 2 — SO WHAT? -----------------------------------------------
        md(
            "## 2 · So what? — the absolute-Sharpe trap\n\n"
            "Here's what rides on getting this right, stated as the mistake almost every "
            "dip backtest makes. In a synthetic market with **no dip-edge at all** — just "
            "upward drift and clustered volatility — a family scan still coughs up a rule "
            "with **Sharpe > 2** (run `examples/run_synthetic_demo.py`). It isn't skill; "
            "it's the market's drift, harvested by an asymmetric take-profit/stop and "
            "dressed up as alpha.\n\n"
            "Deflating that Sharpe for the search helps only if you count honestly: use the "
            "**active days actually behind the winner** (these rules are flat >90% of the "
            "time), not the calendar length — inflate `n_obs` to the full sample and even "
            "the drift-harvester \"survives selection\". And deflation at its best only "
            "rules out selection luck, never drift: the tool that exposes the fake is the "
            "conditional-vs-random-day benchmark (excess ≈ 0). So the stakes here are "
            "methodological: *a high backtest Sharpe can be pure beta.* Everything below "
            "is built to not get fooled by it."
        ),

        # ---- BEAT 3 — HOW WE'D KNOW ------------------------------------------
        md(
            "## 3 · How we'd know — the protocol, declared up front\n\n"
            "Announced before we run it. Five methodological commitments, each targeting a "
            "specific way to fool yourself:\n\n"
            "1. **Excess over a random-day null**, by permutation — never absolute return. "
            "*(kills the drift illusion)*\n"
            "2. **Block bootstrap**, because −3% days cluster (2008, 2020, 2022): 60 raw "
            "events may be ~10 independent episodes. *(kills fake significance)*\n"
            "3. **Deflated Sharpe** over the whole (trigger × exit) grid, because scanning "
            "dozens of rules guarantees a lucky winner. *(kills selection bias)*\n"
            "4. **Conservative fills** — when a bar touches both stop and target, the stop "
            "wins. *(kills optimistic backtests)*\n"
            "5. **Panic slippage** — a separate entry-only cost, because you buy into a "
            "crash when spreads gape. *(kills the cost most dip studies forget)*\n\n"
            "**What would make us stamp `MIRAGE`:** an excess that vanishes under the "
            "bootstrap, capacity of a handful of events, or a rule that flips sign "
            "out-of-sample. Let's run it on two faces of the market — **^NDX** (spot, deep "
            "history) and **QQQ** (the tradeable ETF)."
        ),
        code(
            "ndx = data.fetch('^NDX', mode='split_only'); ret_ndx = data.daily_returns(ndx)\n"
            "qqq = data.fetch('QQQ', mode='split_only'); ret_qqq = data.daily_returns(qqq)\n"
            "print(f\"^NDX : {ndx.index[0].date()} -> {ndx.index[-1].date()}  ({len(ndx):,} days)\")\n"
            "print(f\"QQQ  : {qqq.index[0].date()} -> {qqq.index[-1].date()}  ({len(qqq):,} days)\")"
        ),

        # ---- BEAT 4 — THE TEARDOWN -------------------------------------------
        md(
            "## 4 · The teardown\n\n"
            "### 4.1 Event study around the classic −3% close (T1)\n\n"
            "Line up every session that closes ≤ −3% and average the forward path "
            "(CAAR-style), with a ±1 s.e. band. The shape is suggestive but — as always — "
            "proves nothing until benchmarked."
        ),
        code(
            "ev_ndx = triggers.first_crossings(triggers.close_to_close(ret_ndx, -0.03), cooldown=20)\n"
            "es = eventstudy.event_study(ndx, ev_ndx, horizon=20, pre=5)\n"
            "print(f\"T1 close-to-close -3% | {es['n_events']} events\")\n"
            "display(es['summary'].loc[[1,3,5,10,20], ['mean','median','pct_positive','tstat']].round(4))\n"
            "summ = es['summary']; n = es['n_events']; se = summ['std']/np.sqrt(max(n,1))\n"
            "ax = plt.subplot(); ax.axhline(0, color='0.6', lw=.8); ax.axvline(0, color='crimson', ls='--', lw=1, label='entry (t=0)')\n"
            "ax.plot(summ.index, summ['mean']*100, color='navy', lw=2, label='mean path')\n"
            "ax.fill_between(summ.index, (summ['mean']-se)*100, (summ['mean']+se)*100, color='navy', alpha=.15, label='±1 s.e.')\n"
            "ax.plot(summ.index, summ['median']*100, color='seagreen', ls=':', lw=1.2, label='median')\n"
            "ax.set_xlabel('trading days relative to event'); ax.set_ylabel('cumulative return since entry (%)')\n"
            "ax.set_title(f'^NDX: path around a -3% close (n={n})'); ax.legend(fontsize=8); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "### 4.2 The decisive test — conditional vs a random day\n\n"
            "The market drifts up regardless, so absolute forward returns are meaningless. "
            "Permute to get the **excess** of the post-dip return over the unconditional "
            "(random-day) baseline, with a one-sided p-value. Run it on both faces."
        ),
        code(
            "for lab, ohlc, ev in [('^NDX', ndx, ev_ndx),\n"
            "                      ('QQQ', qqq, triggers.first_crossings(triggers.close_to_close(ret_qqq, -0.03), cooldown=20))]:\n"
            "    b = benchmark.conditional_vs_unconditional(ohlc, ev, horizons=(1,5,10,20))\n"
            "    print(f'\\n[{lab}] conditional vs random day (excess>0 & p_greater<0.05 => beats random):')\n"
            "    print(b[['n_events','mean_cond','mean_uncond','excess','p_greater']].to_string(float_format=lambda v: f'{v:+.4f}'))"
        ),
        md(
            "On 40 years of ^NDX the −3% close is **worse** than a random day (negative "
            "excess, p≈0.8). On QQQ the excess is negative at **every** horizon (p≈0.5–0.99) "
            "— if anything the dip day does worse than an ordinary one. (An earlier revision "
            "of the data layer showed QQQ a faint positive lean by +10d; it was an artefact — "
            "a double split-adjustment fabricated a ~+100% overnight gap at QQQ's 2000-03-20 "
            "split, right in the middle of the dot-com events.) **At −3%, there is no edge.**\n\n"
            "> 💡 **In plain words** — buying the −3% dip earns you, at best, what buying any "
            "day earns you. The drama is free; the alpha is not there."
        ),
        md(
            "### 4.3 Clustering-aware: the block bootstrap\n\n"
            "−3% days bunch together (2008, 2020, 2022), so a permutation that assumes "
            "independent draws *overstates* significance. Resample in blocks to respect the "
            "clustering, and read the 95% CI on the +5d excess."
        ),
        code(
            "for lab, ohlc, ev in [('^NDX', ndx, ev_ndx),\n"
            "                      ('QQQ', qqq, triggers.first_crossings(triggers.close_to_close(ret_qqq, -0.03), cooldown=20))]:\n"
            "    bb = robustness.block_bootstrap_excess(ohlc, ev, horizon=5)\n"
            "    print(f\"[{lab}] +5d excess = {bb['mean']:+.4f}  95% CI [{bb['ci_low']:+.4f}, {bb['ci_high']:+.4f}]  P(excess<=0)={bb['p_excess_le_0']:.2f}\")"
        ),
        md(
            "### 4.4 Is −3% special? Sweep the threshold\n\n"
            "A lone threshold that lights up while its neighbours are flat is data-mined. A "
            "*real* effect varies smoothly as you move the knob. Sweep the drop size on the "
            "close-to-close trigger and read the excess vs a random day at each horizon."
        ),
        code(
            "sw = sweeps.threshold_sweep(ndx, ret_ndx, trigger_fn=triggers.close_to_close)\n"
            "exc = sw['excess']*100\n"
            "print('[^NDX] excess vs random day (%), threshold x horizon:')\n"
            "display(exc.round(2))\n"
            "ax = plt.subplot()\n"
            "for col in exc.columns:\n"
            "    ax.plot(range(len(exc.index)), exc[col].values, marker='o', label=f'+{col}d')\n"
            "ax.axhline(0, color='k', lw=.8)\n"
            "ax.set_xticks(range(len(exc.index))); ax.set_xticklabels([str(i) for i in exc.index])\n"
            "ax.set_xlabel('drop threshold'); ax.set_ylabel('excess vs random day (%)')\n"
            "ax.set_title('^NDX: excess rises smoothly with drop depth (real, not a -3% fluke)')\n"
            "ax.legend(title='horizon', fontsize=8); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "The excess climbs **smoothly and monotonically** as the drop deepens — nothing "
            "at −3%, large and significant by −7%. That monotonicity is the fingerprint of "
            "a *real* mean-reversion effect that lives in genuine panic, not in a mild −3% "
            "wobble. The S&P 500 shows the same shape. **Signal: `WEAK` but real, in the "
            "tail.**"
        ),
        md(
            "### 4.5 Panic zoom — overlay the depths\n\n"
            "Visualise the monotonicity directly: overlay the mean forward paths for −3% / "
            "−5% / −7% on the deep-history spot index."
        ),
        code(
            "es_by = {}\n"
            "for thr in (-0.03, -0.05, -0.07):\n"
            "    ev = triggers.first_crossings(triggers.close_to_close(ret_ndx, thr), cooldown=20)\n"
            "    es_by[f'{thr:.0%}'] = eventstudy.event_study(ndx, ev, horizon=20, pre=3)\n"
            "ax = plt.subplot(); ax.axhline(0, color='0.6', lw=.8); ax.axvline(0, color='0.4', ls='--', lw=1)\n"
            "cmap = plt.get_cmap('viridis'); items = list(es_by.items())\n"
            "for i, (lab, r) in enumerate(items):\n"
            "    s = r['summary']\n"
            "    ax.plot(s.index, s['mean']*100, lw=2, color=cmap(i/max(len(items)-1, 1)), label=f\"{lab}  (n={r['n_events']})\")\n"
            "ax.set_xlabel('trading days relative to event'); ax.set_ylabel('mean cumulative return (%)')\n"
            "ax.set_title('^NDX: deeper drops bounce harder'); ax.legend(title='drop threshold'); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "### 4.6 The absolute-Sharpe trap, live — family scan + deflation\n\n"
            "Now the trap from beat 2, on real data. Scan the whole (trigger × exit) family "
            "on QQQ, rank by net Sharpe, and apply the deflated-Sharpe correction for having "
            "searched so many cells."
        ),
        code(
            "sigs = {nm: f(ret_qqq) for nm, f in triggers.TRIGGERS.items()}\n"
            "scan = backtest.family_scan(qqq, ret_qqq, sigs, exits.default_grid(), costs=backtest.CostModel())\n"
            "print(f'{len(scan)} (trigger x exit) combos; top 6 by net Sharpe:')\n"
            "display(scan.head(6).round(3))\n"
            "best = scan.iloc[0]\n"
            "# n_obs = the active days behind the winning Sharpe, NOT the calendar length:\n"
            "# the strategy is flat >90% of the time, and inflating n_obs to the full sample\n"
            "# makes the deflation test trivially easy to pass.\n"
            "dsr = robustness.deflated_sharpe(best['sharpe'], n_trials=len(scan), n_obs=int(best['active_days']))\n"
            "print(f\"best raw Sharpe = {best['sharpe']:.2f} ({best['trigger']}) over {len(scan)} trials, \"\n"
            "      f\"{int(best['active_days'])} active days -> \"\n"
            "      f\"deflated PSR = {dsr:.2f} ({'survives selection' if dsr and dsr>0.95 else 'consistent with luck'})\")\n"
            "pivot = scan.pivot(index='trigger', columns='exit', values='sharpe')\n"
            "vmax = np.nanmax(np.abs(pivot.to_numpy()))\n"
            "fig, ax = plt.subplots(figsize=(min(2+0.7*pivot.shape[1], 15), 2+0.5*pivot.shape[0]))\n"
            "im = ax.imshow(pivot.to_numpy(), aspect='auto', cmap='RdYlGn', vmin=-vmax, vmax=vmax)\n"
            "ax.set_xticks(range(pivot.shape[1])); ax.set_xticklabels(pivot.columns, rotation=45, ha='right', fontsize=7)\n"
            "ax.set_yticks(range(pivot.shape[0])); ax.set_yticklabels(pivot.index, fontsize=8)\n"
            "ax.set_title('QQQ family scan — net Sharpe (a few hot cells in a sea of noise = selection)')\n"
            "fig.colorbar(im, ax=ax, shrink=0.8, label='Sharpe'); plt.show()"
        ),
        md(
            "Counted honestly — `n_obs` = the ~250 days the winner actually spends in the "
            "market, not the ~6,800-day calendar — the best cell **fails deflation** "
            "(PSR far below the 0.95 bar): the prettiest Sharpe in the grid is consistent "
            "with picking the luckiest of 70 coin-flips. And even if it had survived, watch "
            "what a **regime split** does to it. Run the representative tradeable rule and "
            "break the P&L out by era:"
        ),
        code(
            "best_sig = triggers.first_crossings(sigs[best['trigger']], cooldown=20)\n"
            "res = backtest.run(qqq, best_sig, exits.ExitRule(max_hold=5), backtest.CostModel())\n"
            "print(f\"[{best['trigger']}, hold<=5d, retail costs]  trades={res.stats['n_trades']}  \"\n"
            "      f\"CAGR={res.stats['cagr']:+.2%}  Sharpe={res.stats['sharpe']:.2f}  maxDD={res.stats['max_drawdown']:.1%}\")\n"
            "print('\\nRegime split — is it one lucky era?')\n"
            "display(robustness.regime_split(res.daily).round(4))\n"
            "eq = res.equity; dd = eq/eq.cummax()-1\n"
            "fig, (a1, a2) = plt.subplots(2, 1, figsize=(9.5, 6), sharex=True, gridspec_kw={'height_ratios':[3,1]})\n"
            "a1.plot(eq.index, eq.values, color='navy', lw=1.3); a1.set_yscale('log'); a1.set_ylabel('equity (x, log)')\n"
            "a1.set_title(f\"QQQ {best['trigger']} (hold<=5d): Sharpe {res.stats['sharpe']:.2f}, maxDD {res.stats['max_drawdown']:.1%}\")\n"
            "a2.fill_between(dd.index, dd.values*100, 0, color='crimson', alpha=.4); a2.set_ylabel('drawdown (%)'); a2.set_xlabel('date'); plt.show()"
        ),
        md(
            "The headline Sharpe is **leveraged exposure to whether the dip keeps dipping**: "
            "it pays spectacularly when the Fed backstops every selloff and bleeds in the "
            "one bear market without a quick rescue. That's not a stable edge — it's beta to "
            "the \"Fed put.\"\n\n"
            "> 💡 **In plain words** — the great-looking backtest isn't finding a dip edge; "
            "it's just long the market with extra steps, and it only shines in the decades "
            "where the market shot straight up."
        ),
        md(
            "### 4.7 Does it generalise? Nasdaq vs S&P 500, in/out-of-sample\n\n"
            "A genuine mechanism should (a) be significant, (b) appear on **both** indices, "
            "and (c) survive out-of-sample. We pick the best family cell on the first 60% of "
            "history and test it on the unseen tail — for all four faces."
        ),
        code(
            "rows = []\n"
            "for lab, (spot, etf) in data.INDEX_PAIRS.items():\n"
            "    for face, tk in [('spot', spot), ('ETF', etf)]:\n"
            "        o = data.fetch(tk, mode='split_only'); r = data.daily_returns(o)\n"
            "        ev = triggers.first_crossings(triggers.close_to_close(r, -0.03), cooldown=20)\n"
            "        b = benchmark.conditional_vs_unconditional(o, ev, horizons=(1,5,10,20))\n"
            "        sg = {nm: f(r) for nm, f in triggers.TRIGGERS.items()}\n"
            "        oos = robustness.oos_best_cell(o, sg, exits.default_grid())\n"
            "        rows.append({'index': f'{lab} {face}', 'ticker': tk,\n"
            "                     '-3% +5d excess': f\"{b.loc[5,'excess']:+.2%}\" if 5 in b.index else 'na',\n"
            "                     'p': f\"{b.loc[5,'p_greater']:.2f}\" if 5 in b.index else 'na',\n"
            "                     'best cell': oos.get('trigger','?'),\n"
            "                     'Sharpe IS': f\"{oos.get('is_sharpe', float('nan')):.2f}\",\n"
            "                     'Sharpe OOS': f\"{oos.get('oos_sharpe', float('nan')):.2f}\"})\n"
            "pd.DataFrame(rows).set_index('index')"
        ),
        md(
            "The −3% non-edge is identical on both indices. The flashy family-scan Sharpes "
            "survive only on the *spot* faces (that's the persistent market drift); on the "
            "*tradeable* ETFs the winners **collapse out-of-sample** — textbook data-mining. "
            "**Generalisation fails where it has to: on the things you could actually trade.**"
        ),

        # ---- BEAT 5 — THE VERDICT --------------------------------------------
        md(
            "## 5 · The verdict\n\n"
            "1. **−3% is folklore — `NONE`.** Excess over a random day is ~0 on the Nasdaq "
            "*and* the S&P 500; any flattering Sharpe is market beta that dies out-of-sample.\n"
            "2. **Deep panic is real — `WEAK`.** The bounce grows smoothly with depth and is "
            "significant by permutation at −5%/−7% on both indices — a genuine statistical "
            "fingerprint of panic mean-reversion.\n"
            "3. **…but it isn't tradeable — `MIRAGE`.** Under the clustering-aware bootstrap "
            "the deep-dip excess straddles zero (the permutation overstated it), the events "
            "are rare and crash-dominated, and a fixed rule flips sign out-of-sample.\n\n"
            "The round number is a myth; even the panic tail — the one place the effect is "
            "statistically visible — doesn't survive clustering, capacity and out-of-sample "
            "scrutiny. At most it's a *behavioural discipline for deploying long-term capital "
            "into a crash*, never a standalone alpha engine."
        ),

        # ---- BEAT 6 — COULD YOU TRADE IT? ------------------------------------
        md(
            "## 6 · Could you actually harvest it? (capacity, stability, cost)\n\n"
            "The deep-dip bounce is *true* but ask whether it's *bankable*. First, "
            "**capacity** — how often do these events even happen, and how concentrated are "
            "they?"
        ),
        code(
            "def capacity(ev, ohlc):\n"
            "    dates = ev.index[ev.to_numpy()]; years = ohlc.shape[0]/252.0; nn = len(dates)\n"
            "    by_year = pd.Series(dates).dt.year.value_counts().sort_values(ascending=False)\n"
            "    return nn, (10*nn/years if years else np.nan), list(by_year.head(2).index), (by_year.head(2).sum()/nn if nn else np.nan)\n"
            "print('[^NDX] deep-dip capacity:')\n"
            "for thr in (-0.03, -0.05, -0.07):\n"
            "    ev = triggers.first_crossings(triggers.close_to_close(ret_ndx, thr), cooldown=20)\n"
            "    nn, perdec, top2, share = capacity(ev, ndx)\n"
            "    print(f'  {thr:+.0%}: {nn:>3} events | {perdec:>4.1f}/decade | top-2 years {top2} = {share:.0%} of all events')"
        ),
        md(
            "A −7% day fires ~3×/decade and a large share of those sit in 2–3 historic "
            "crashes. You're not running a strategy; you're betting on a handful of "
            "selloffs. Next, **stability** — does a fixed −5% rule survive out-of-sample?"
        ),
        code(
            "raw5 = triggers.close_to_close(ret_ndx, -0.05)\n"
            "is_o, oos_o = robustness.split_sample(ndx, 0.6)\n"
            "rows = {}\n"
            "for tag, seg in (('IS (first 60%)', is_o), ('OOS (last 40%)', oos_o)):\n"
            "    sig = triggers.first_crossings(raw5.reindex(seg.index), cooldown=20)\n"
            "    r = backtest.run(seg, sig, exits.ExitRule(max_hold=5), backtest.CostModel())\n"
            "    rows[tag] = {'trades': r.stats['n_trades'], 'CAGR': r.stats['cagr'], 'Sharpe': r.stats['sharpe'], 'maxDD': r.stats['max_drawdown']}\n"
            "display(pd.DataFrame(rows).T.round(4))"
        ),
        md(
            "In-sample winner, out-of-sample loser — the Sharpe flips sign. Finally, "
            "**cost** — and here's the twist vs the overnight study: because you trade so "
            "rarely, costs are *not* the killer."
        ),
        code(
            "ev5_qqq = triggers.first_crossings(triggers.close_to_close(ret_qqq, -0.05), cooldown=20)\n"
            "sweep = backtest.cost_sweep(qqq, ev5_qqq, exits.ExitRule(max_hold=5))\n"
            "display(sweep.round(4))\n"
            "ax = plt.subplot(); ax.axhline(0, color='0.6', lw=.8)\n"
            "ax.plot(sweep.index, sweep['cagr']*100, 'o-', color='navy', label='CAGR (%)'); ax.set_xlabel('entry panic-slippage (bps)'); ax.set_ylabel('net CAGR (%)', color='navy')\n"
            "ax2 = ax.twinx(); ax2.plot(sweep.index, sweep['sharpe'], 's--', color='darkorange', label='Sharpe'); ax2.set_ylabel('net Sharpe', color='darkorange')\n"
            "ax.set_title('QQQ deep-dip: costs are not the killer (you barely trade)'); ax.grid(alpha=.3); plt.show()"
        ),
        md(
            "Even a brutal entry slippage barely dents the Sharpe — it never flips it "
            "negative. **The thing standing between you and profit isn't transaction cost; "
            "it's that there's little excess edge over plain beta to begin with.** That's "
            "the `MIRAGE` stamp: real in the data, unbankable in practice.\n\n"
            "> 💡 **In plain words** — you can't fix a non-edge with cheaper trading. The "
            "problem was never the toll; it's that the road doesn't go anywhere."
        ),

        # ---- BEAT 7 — GOING FURTHER ------------------------------------------
        md(
            "## 7 · Going further\n\n"
            "**What would change the verdict.** Toward `INVESTABLE`: a deep-dip excess whose "
            "*block-bootstrap* CI clears zero and that survives an honest out-of-sample "
            "split — ideally with enough events to size a real book (these don't). Toward a "
            "richer signal: condition on volatility regime, breadth, or credit stress rather "
            "than price alone; the panic bounce may be a *conditional* effect we've only "
            "measured marginally.\n\n"
            "**Reproducibility.** The package ships a 24-test offline suite "
            "(`pytest -q`) covering the return identities, the conservative intrabar fill "
            "(stop-before-target), cost monotonicity, the single-position no-overlap "
            "guarantee, and — crucially — that the benchmark **detects an injected edge and "
            "stays flat when there is none**. Start with `examples/run_synthetic_demo.py` "
            "(offline) to see the toolchain tell a real edge from a fake one, then "
            "`examples/verify_ndx.py`, `sweep_thresholds.py`, `panic_zoom.py`, "
            "`compare_indices.py` for the live studies.\n\n"
            "**The real deliverable is the method.** Any backtest that skips the random-day "
            "benchmark, the threshold sweep, the block bootstrap and an out-of-sample split "
            "is marketing. New studies follow the same seven beats "
            "([METHODOLOGY.md](../../../METHODOLOGY.md))."
        ),
        md(
            "## Caveats (read before quoting any number)\n\n"
            "1. **Event clustering** shrinks the effective sample far below the raw count.\n"
            "2. **Regime dependence** — dip-buying loves a \"Fed put\" and hates a 2000–2002 "
            "grind. One great decade is not a law.\n"
            "3. **Short-vol profile** — you add risk exactly when volatility peaks; a "
            "positive average can hide an ugly tail. Watch max drawdown, not just CAGR.\n"
            "4. **Execution reality** — the −3% close on a chart is a print you may not get; "
            "modelled `panic_slippage_bps` is a guess, so sweep it.\n\n"
            "MIT licensed, research & teaching only — **not investment advice.** Numbers "
            "extend as new data arrives."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
