"""Beat-7 forks, worked — the obvious 'yes, but did you try…' rescues for the cycle claim.

Killing the adaptive cycle invites four immediate objections; we run each rather than leave
it as homework, all on the real cached VIX/SPX:

    1. **Commit to the tweet's literal clock.** Don't re-tune — hard-wire the named periods
       (VIX 80d, 40d). Maybe the search dilutes a cycle the theorist *knows* is there.
    2. **Amplitude gate.** Only trade when a *strong* cycle is present in-sample — perhaps the
       forecast works in the windows where the oscillation is clearly visible.
    3. **The cycle is in stocks, not vol.** Test the tweet's stock clocks directly — the
       20-week (~100d) and 4-year (~1000d) cycles — for red-noise significance on the S&P.

Each is one change to the baseline. Writes docs/extensions.md.

    python examples/verify_extensions.py
"""

import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from vix_cycles import backtest, data, robustness
from quantlab.repro import DEFAULT_AS_OF, fingerprint

pd.set_option("display.width", 200)
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")

try:                                   # keep em-dashes/≈ printable on a cp1252 console
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

OUT = os.path.join(_STUDY, "docs", "extensions.md")
BAND = (15.0, 400.0)


def _variant(tag, logv, spx, **kw):
    sk = backtest.oos_direction_skill(logv, band=BAND, horizon=20, min_train=750, step=10,
                                      n_null=500, seed=0,
                                      fixed_period=kw.get("fixed_period"))
    tr = backtest.phase_trade(logv, spx, band=BAND, horizon=20, min_train=750, refit=5,
                              cost_bps=1.0, n_null=200, seed=0,
                              fixed_period=kw.get("fixed_period"),
                              amp_gate=kw.get("amp_gate", 0.0))
    return {
        "variant": tag,
        "dir_skill": sk["skill"],
        "skill_p": sk["p_value"],
        "trade_sharpe": tr.stats["sharpe_net"],
        "trade_p": tr.stats["p_value_vs_null"],
        "exposure": tr.stats["exposure"],
        "max_dd": tr.stats["max_drawdown"],
    }


def main():
    asof = DEFAULT_AS_OF
    vix = data.vix_series(asof=asof)
    spx = data.spx_series(asof=asof)
    logv = data.log_signal(vix)
    logs = data.log_signal(spx)

    rows = [
        _variant("baseline (adaptive re-tune)", logv, spx),
        _variant("fixed 80d (tweet VIX clock)", logv, spx, fixed_period=80.0),
        _variant("fixed 40d (tweet VIX clock)", logv, spx, fixed_period=40.0),
        _variant("amplitude-gated (amp ≥ 0.5σ)", logv, spx, amp_gate=0.5),
    ]
    table = pd.DataFrame(rows).set_index("variant")
    print("[VIX cycle rescues — direction skill & trade vs random-phase null]\n",
          table.round(4).to_string())

    # The stock clocks the tweet leans on — tested on the S&P directly.
    spx_pvals = robustness.red_noise_pvalues(logs, targets=(100.0, 250.0, 1000.0),
                                             n_sim=2000, seed=0)
    print("\n[S&P red-noise p-values at the stock clocks (20wk≈100d, 1y≈250d, 4y≈1000d)]\n",
          spx_pvals.round(4).to_string())

    fp = fingerprint(vix.to_frame("Close"), round_dp=4)
    _write(OUT, table, spx_pvals, asof, fp, len(vix))
    print(f"\nwrote {OUT}")


def _write(path, table, spx_pvals, asof, fp, n):
    def md(df):
        return "```\n" + df.round(4).to_string() + "\n```"

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"""# Extensions — Study 06 (Clockwork-Vol): the beat-7 rescues, worked

*Generated by [`examples/verify_extensions.py`](../examples/verify_extensions.py). Real
cached VIX/SPX, as-of **{asof}**, VIX fingerprint **`{fp}`** ({n:,} sessions. Each row is one
change to the baseline adaptive cycle; `dir_skill` is the walk-forward next-20-session
direction hit rate (0.50 = a coin), `*_p` are p-values against the random-phase null,
`trade_*` is the long-S&P-when-vol-projected-to-fall expression.*

## 1 · Do the rescues revive the VIX cycle?
{md(table)}

- **Hard-wiring 40d does nothing; hard-wiring 80d flickers — but fragilely.** Fixing the
  tweet's literal 40-day clock leaves the forecast a coin flip (skill ≈ 0.497, p ≈ 0.52).
  Fixing the **80-day** clock gives a *marginal* tick — direction skill **0.533, p ≈ 0.04**
  against the random-phase null — the one number in the whole study that even approaches
  significance. It does **not** survive scrutiny: (i) it is a **single hand-picked period**
  with no correction for having tried several, (ii) it directly **contradicts the spectral
  test**, where 80-day power sits *inside* the red-noise envelope (p ≈ 0.9995 — there is no
  peak there to forecast from), and (iii) it does **not** carry into a significant trade
  (Sharpe 0.64 but p ≈ 0.13 vs the null, and barely above buy-and-hold's 0.56 on 50%
  exposure). This is the textbook **"significant raw, fragile to method and selection"** —
  a `WEAK` fragment, not a clock.
- **The amplitude gate never even fires.** Requiring the in-sample cycle amplitude to reach
  0.5σ of the level zeroes the position *every day*: the cyclical component is always small
  next to the VIX's own variance. That is itself the verdict in miniature — there is no
  window in 36 years where a "strong, clear cycle" is present to trade.

## 2 · Is the cycle in *stocks* instead? The S&P's own clocks
*The tweet ties the VIX cycle to a stock 20-week (~100d) and 4-year (~1000d) cycle. Tested
directly on log-S&P against AR(1) red noise:*
{md(spx_pvals)}

- None of the named stock clocks clears the red-noise envelope either. The 4-year peak is the
  closest to interesting, but a sample with only a handful of 4-year spans can't separate a
  "cycle" from low-frequency red noise — exactly the trap the test is built to catch.
""")


if __name__ == "__main__":
    main()
