"""Generate the two narrative notebooks for Study 03 (Fear-Gauge) from source.

Like Studies 01–02, the notebooks are a *generated artefact*: edit the cell text
here, rebuild the skeletons, then execute with nbconvert to embed figures/outputs.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

First execution hits the network (Yahoo! Finance: ^GSPC, SPY, ^VIX); later runs use
the local parquet cache under ../_cache/.

Both notebooks follow the SAME seven desk beats (see ../../../METHODOLOGY.md):
  0 Verdict · 1 The Claim · 2 So What? · 3 How We'd Know · 4 The Teardown ·
  5 The Verdict · 6 Could You Trade It? · 7 Going Further
  01_for_the_curious  — the plain-language layer
  02_for_the_quants   — the deep layer: event study, random-day null, the
                        cross-study control vs the price drop, block bootstrap,
                        window-selection test, martingale risk-of-ruin
We never import fear_gauge.plots here (it would force the Agg backend and break
inline rendering). Every figure is drawn inline from the returned data.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))  # study root (fear_gauge/ lives there)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from fear_gauge import data, triggers, exits, eventstudy, benchmark, backtest, robustness

# The headline pair: S&P 500 spot for stats (deep history), aligned with the VIX.
spx, vix = data.aligned("^GSPC")
print(f"{len(spx):,} common sessions  {spx.index.min().date()} -> {spx.index.max().date()}")
"""


def md(text):
    return new_markdown_cell(text)


def code(text):
    return new_code_cell(text)


# ===========================================================================
# 01 — FOR THE CURIOUS   (the plain-language layer of the seven beats)
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Fear-Gauge 🌡️\n"
            "### Does buying stocks when the fear gauge screams actually pay — or just feel brave?\n\n"
            "![Signal: Mixed](https://img.shields.io/badge/Signal-Mixed-dab617?style=flat-square)\n"
            "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
            "![Double--down: Ruin--prone](https://img.shields.io/badge/Double--down-Ruin--prone-8b949e?style=flat-square)\n\n"
            "A chart goes viral every time markets wobble: *the S&P 500 after every VIX "
            "spike, and look — it's green almost every time, +2.66% a month later.* The rule "
            "writes itself: **buy when the VIX hits 30, double down at 50.** Free money for "
            "the brave. This is the twin of our [Falling-Knife](../../02-falling-knife/) "
            "study, but in **fear** instead of **price** — with a twist the dip study didn't "
            "have: this time the signal might be *real*, and that's exactly the trap. "
            "*Spoiler: the gauge really does say something, and that still doesn't make the "
            "tweet's rule a good idea.*\n\n"
            "> 📓 **This is the plain-language layer.** Want the statistics, the "
            "microstructure and the capacity maths? That's the companion notebook, "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** An educational, reproducible research tool: "
            "every chart below is generated by the code beside it. First run downloads from "
            "Yahoo! Finance. House style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        # ---- BEAT 0 — VERDICT ------------------------------------------------
        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does the market really bounce after a VIX spike? | ✅ **Yes, a bit** — unlike the −3% dip, there's a genuine fingerprint. The fear gauge isn't pure noise. |\n"
            "| Is that bounce a free edge? | ⚠️ **No** — it's the *variance risk premium*: you're paid for selling insurance, and the bill comes due in crashes. |\n"
            "| Does \"VIX 30\" beat just \"price down 3%\"? | ❓ **Barely / not really** — strip out the price drop and most of the \"VIX edge\" goes with it. |\n"
            "| Should you \"double down at 50\"? | ❌ **That's a martingale** — fine until the one time it isn't (2008), which the famous chart's window leaves out. |\n\n"
            "> Desk shorthand: **Signal `REAL` (it's a risk premium) · Tradability "
            "`MIRAGE`/`FRAGILE`**. Let's earn those stamps."
        ),

        # ---- BEAT 1 — THE CLAIM ----------------------------------------------
        md(
            "## 1 · The claim 📣\n\n"
            "Two versions float around, and people mix them up constantly:\n\n"
            "- **A level:** *\"Buy when the VIX hits 30, double down at 50.\"*\n"
            "- **A spike:** *\"The S&P rises after every +30% single-day jump in the VIX — "
            "+0.42% the next day, +2.66% the next month, 21 of 23 times positive.\"*\n\n"
            "A *level* (the VIX is high) and a *jump* (the VIX leapt today) are not the same "
            "signal — and the famous chart mixes them anyway: a +46% spike that lands the VIX "
            "at a sleepy **15.6** sits in the same table as one that lands it at a "
            "1987-grade **82.7**. So we don't test one rule; we test the **family**."
        ),
        code(
            "# The family of 'the gauge says buy' triggers (see fear_gauge/triggers.py)\n"
            "fams = {\n"
            "    'V1 · VIX ≥ 30 (level)':      triggers.level(vix, 30),\n"
            "    'V1 · VIX ≥ 50 (deep panic)': triggers.level(vix, 50),\n"
            "    'V2 · VIX +30% (spike)':      triggers.spike(vix),\n"
            "    'V3 · spike from a low base': triggers.spike_from_base(vix, base_max=20),\n"
            "    'V3 · spike from a high base':triggers.spike_from_base(vix, base_min=30),\n"
            "}\n"
            "pd.DataFrame({k: [int(triggers.first_crossings(s, cooldown=21).sum())]\n"
            "              for k, s in fams.items()}, index=['fresh events']).T"
        ),

        # ---- BEAT 2 — SO WHAT ------------------------------------------------
        md(
            "## 2 · So what? 💰\n\n"
            "If the gauge pays, it's the simplest fear-buy a beginner could run — a number on "
            "a screen front-running the market's recovery. But there's a deeper lesson hiding "
            "here, and it's the whole reason this study exists:\n\n"
            "> **\"Real\" and \"worth trading\" are different questions.** A signal can be "
            "genuinely, repeatably positive *and* still be a bad trade — because what you're "
            "being paid is an **insurance premium**, and insurers get wiped out in the "
            "disaster they insured against.\n\n"
            "The Falling-Knife found *nothing*. This one will likely find *something real* — "
            "and then show you why that's not the good news it sounds like."
        ),

        # ---- BEAT 3 — HOW WE'D KNOW ------------------------------------------
        md(
            "## 3 · How we'd know 🔍\n\n"
            "The market drifts up anyway, so a green line after the spike proves nothing. Two "
            "questions, not one:\n\n"
            "1. Did it rise **more than on a random day**? (the same yardstick as the dip study)\n"
            "2. Did the **VIX** add anything **over just the price drop**? (because a high VIX "
            "≈ a red day — they might be the same event in two costumes)\n\n"
            "And one trap to defuse: the viral chart runs **2016–2026**, a decade with no "
            "2008. We'll put the crashes back and watch what happens."
        ),

        # ---- BEAT 4 — THE TEARDOWN -------------------------------------------
        md(
            "## 4 · The teardown 🔬\n\n"
            "First, the picture everyone shares: the average S&P path around a VIX-30 event. "
            "Notice the **left half** — you're buying *into* a selloff already underway."
        ),
        code(
            "sig30 = triggers.first_crossings(triggers.level(vix, 30), cooldown=21)\n"
            "es = eventstudy.event_study(spx, sig30, horizon=21, pre=5)\n"
            "m = es['matrix'].mean()\n"
            "plt.axvline(0, color='0.7', lw=1); plt.axhline(0, color='0.7', lw=1)\n"
            "plt.plot(m.index, 100*m.values, lw=2)\n"
            "plt.title(f\"S&P 500 around a VIX≥30 cross  (n={es['n_events']} events)\")\n"
            "plt.xlabel('trading days from the VIX cross'); plt.ylabel('avg cumulative return (%)')\n"
            "plt.show()\n"
            "es['summary'].loc[[1, 5, 21]]"
        ),
        md(
            "Now the only number that matters — the **excess over a random day**. If it's "
            "near zero, the bounce is just the market's normal drift."
        ),
        code(
            "benchmark.conditional_vs_unconditional(spx, sig30, horizons=(1, 5, 21))"
        ),
        md(
            "And the question unique to this study: **does VIX-30 beat a plain −3% day?** If "
            "the gap is ~0, the \"VIX edge\" is just the falling knife wearing a vol hat."
        ),
        code(
            "price_drop = triggers.first_crossings(spx['r_cc'] <= -0.03, cooldown=21)\n"
            "benchmark.excess_vs_alternative(spx, sig30, price_drop, horizons=(1, 5, 21))"
        ),
        md(
            "Finally the **window trick**. The viral chart's decade conveniently skips 2008. "
            "Watch the excess change when we put the crashes back in."
        ),
        code(
            "robustness.window_sensitivity(spx, sig30, horizon=21)"
        ),

        # ---- BEAT 5 — THE VERDICT --------------------------------------------
        md(
            "## 5 · The verdict ⚖️\n\n"
            "Read the three tables together — they're the whole story:\n\n"
            "- **Signal `REAL`:** after a VIX≥30 cross the S&P beats a random day by about "
            "**+1.0% over a week and +1.3% over a month**, and the p-values clear the bar "
            "(≈0.00 and ≈0.01). Unlike the −3% dip of Study 02, the gauge genuinely "
            "carries information.\n"
            "- **But it's a risk premium, not alpha:** pit VIX-30 against a plain −3% "
            "price day and the gap (≈+0.9–1.3%) **fails significance** (p≈0.13–0.20) — "
            "most of the \"VIX edge\" is the falling knife in vol coordinates. And the "
            "viral chart's 2016–2026 window shows a fatter excess (+1.9%) than the full "
            "history (+1.3%): part of what's being sold is the *window*. What you're "
            "harvesting is the **variance risk premium** — payment for holding the tail.\n\n"
            "Which sets up the only question that decides whether you'd touch it…"
        ),

        # ---- BEAT 6 — COULD YOU TRADE IT -------------------------------------
        md(
            "## 6 · Could you trade it? 🏦\n\n"
            "You can't buy spot VIX — the trade is the S&P (SPY) or a vol product with its own "
            "decay. And the rule's killer is the second half: **\"double down at 50.\"** That's "
            "a *martingale* — you size **up** exactly as the tail fattens. Let's run it through "
            "history: every VIX-30 episode since 1990, doubled at 50 when it got there, held a "
            "quarter, tracking the deepest mark-to-market drawdown along the way (the bar is "
            "−20%, margin-call territory for anyone levered)."
        ),
        code(
            "ruin = robustness.martingale_ruin(spx, vix, rung1=30, rung2=50)  # hold 63d, ruin bar -20%\n"
            "pd.Series(ruin)"
        ),
        md(
            "Read it honestly: **most of the time the martingale is fine.** 30 of 32 episodes "
            "stay above the bar and the average episode ends about **+5%**. The case against "
            "it is the **tail**: the worst episode (2008) sat **−33% under water** before the "
            "quarter was up — stretch the hold to six months and that deepens to about "
            "**−40%** — and still *ended* −21% down. \"It always comes back\" is exactly the "
            "assumption that fails the one time it matters, and doubling down means you "
            "meet that failure with twice the capital.\n\n"
            "> The chart that sells \"double down at 50\" is drawn on the one decade whose "
            "worst episode ended just **−3.6%** down. It's not that the no-2008 window has "
            "fewer scary episodes — it's that it has no *fatal* one. The window hides the "
            "severity, not the frequency."
        ),

        # ---- BEAT 7 — GOING FURTHER ------------------------------------------
        md(
            "## 7 · Going further 🚪\n\n"
            "- **Is the bounce *only* the variance risk premium?** Hedge it out and see if "
            "anything survives.\n"
            "- **Term structure:** does VIX *backwardation* predict the rebound better than the "
            "level alone?\n"
            "- **Cross-asset:** the same claim is made on bonds (MOVE) and crypto (DVOL).\n\n"
            "The deep version of every test above — with t-stats, bootstrap CIs and the full "
            "cross-study control — is in "
            "[`02_for_the_quants.ipynb`](02_for_the_quants.ipynb)."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")
    return nb


# ===========================================================================
# 02 — FOR THE QUANTS   (the rigorous layer of the same seven beats)
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Fear-Gauge — a quantitative teardown 🔬\n"
            "### Random-day null · price-drop control · block bootstrap · window selection · "
            "martingale risk-of-ruin\n\n"
            "![Signal: Mixed](https://img.shields.io/badge/Signal-Mixed-dab617?style=flat-square)\n"
            "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
            "![Double--down: Ruin--prone](https://img.shields.io/badge/Double--down-Ruin--prone-8b949e?style=flat-square)\n\n"
            "The deep companion to the "
            "[notebook for the curious](01_for_the_curious.ipynb) — *same seven beats, every "
            "claim now carrying its standard error.* The thesis we're testing: the post-spike "
            "rebound is **statistically real** (it's the variance risk premium) but "
            "**uninvestable** (short-skew premium + a martingale that ignores 2008).\n\n"
            "> ⚠️ **Not investment advice.** Reproducible research; fixed seeds. Data: "
            "^GSPC, SPY, ^VIX from Yahoo! Finance (first run hits the network, later runs use "
            "the local cache under `../_cache/`). Methods: event study, random-day "
            "permutation null, label-permutation cross-study control, block bootstrap, "
            "window-selection test, martingale risk-of-ruin — see "
            "[`docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into "
            "intuition — so this notebook still reads even if you skim the maths. House "
            "style in [METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        code(
            "# Both faces of the market + the gauge. Spot for stats, ETF for the cost layer.\n"
            "spy, vix_spy = data.aligned('SPY')\n"
            "for nm, (mkt, vx) in {'^GSPC': (spx, vix), 'SPY': (spy, vix_spy)}.items():\n"
            "    print(f\"{nm:6s} {len(mkt):>6,} sessions  {mkt.index.min().date()} -> {mkt.index.max().date()}\")"
        ),

        # ---- BEAT 1 ----------------------------------------------------------
        md(
            "## 1 · The claim, as testable hypotheses\n\n"
            "H₁ (level): E[r_{t→t+h} | VIX_t ≥ 30] > E[r_{t→t+h}] with HAC-robust t > 2.\n"
            "H₁ (spike): same, conditioned on ΔVIX_t ≥ +30%.\n"
            "H₀: excess ≈ 0 — the forward return is drift + beta. Horizons h ∈ {1, 5, 21} to "
            "match the chart's +1d/+1w/+1m exactly."
        ),
        code(
            "FAMILY = {\n"
            "    'V1_level_30': triggers.level(vix, 30),\n"
            "    'V1_level_40': triggers.level(vix, 40),\n"
            "    'V1_level_50': triggers.level(vix, 50),\n"
            "    'V2_spike':    triggers.spike(vix),\n"
            "    'V3_low_base': triggers.spike_from_base(vix, base_max=20),\n"
            "    'V3_high_base':triggers.spike_from_base(vix, base_min=30),\n"
            "}\n"
            "events = {k: triggers.first_crossings(v, cooldown=21) for k, v in FAMILY.items()}\n"
            "pd.Series({k: int(v.sum()) for k, v in events.items()}, name='fresh events').to_frame()"
        ),

        # ---- BEAT 3/4 — the null --------------------------------------------
        md(
            "## 3–4 · The random-day null, across the whole family\n\n"
            "`p_greater` = P(a random basket of the same size beats the conditional mean). "
            "Small ⇒ the gauge adds something beyond drift."
        ),
        code(
            "rows = []\n"
            "for name, sig in events.items():\n"
            "    t = benchmark.conditional_vs_unconditional(spx, sig, horizons=(1, 5, 21), n_iter=2000)\n"
            "    for h, r in t.iterrows():\n"
            "        rows.append({'trigger': name, 'h': h, 'n': int(r.n_events),\n"
            "                     'excess': r.excess, 'p_greater': r.p_greater})\n"
            "null_tbl = pd.DataFrame(rows).set_index(['trigger', 'h'])\n"
            "null_tbl"
        ),

        # ---- BEAT 4 — the cross-study control --------------------------------
        md(
            "## 4 · The cross-study control — does VIX beat the price drop?\n\n"
            "The confound that makes this study hard: VIX-high ≈ price-low. We pit each VIX "
            "trigger against Study 02's T1 (a −3% close) on the *same* forward returns, with a "
            "label-permutation test on the gap. **A VIX trigger that clears the random-day "
            "null but not this control is the falling knife in vol coordinates.**"
        ),
        code(
            "t1 = triggers.first_crossings(spx['r_cc'] <= -0.03, cooldown=21)\n"
            "ctrl = {}\n"
            "for name in ['V1_level_30', 'V2_spike', 'V3_high_base']:\n"
            "    ctrl[name] = benchmark.excess_vs_alternative(spx, events[name], t1, horizons=(1, 5, 21))\n"
            "pd.concat(ctrl, names=['trigger', 'h'])[['mean_signal', 'mean_alt', 'gap', 'p_signal_gt_alt']]"
        ),

        # ---- BEAT 4 — clustering + selection ---------------------------------
        md(
            "## 4 · Clustering and selection — the two ways the chart cheats\n\n"
            "**(a) Clustering.** 4 of the chart's 23 events are Feb–Mar 2020. The iid "
            "permutation overstates significance; a block bootstrap that resamples contiguous "
            "months gives an honest CI on the excess."
        ),
        code(
            "boot = {name: robustness.block_bootstrap_excess(spx, events[name], horizon=21,\n"
            "                                                 block=21, n_iter=2000)\n"
            "        for name in ['V1_level_30', 'V2_spike', 'V3_high_base']}\n"
            "pd.DataFrame(boot).T[['mean', 'ci_low', 'ci_high', 'p_excess_le_0']]"
        ),
        md(
            "**(b) Selection.** The viral chart's window (2016–2026) excludes 2008. Recompute "
            "the same excess on the cherry-picked window vs the full history — if it shrinks or "
            "flips, the edge was a property of the *window*, not the *signal*."
        ),
        code(
            "robustness.window_sensitivity(spx, events['V2_spike'], horizon=21)"
        ),

        # ---- BEAT 5 ----------------------------------------------------------
        md(
            "## 5 · The verdict, with the numbers\n\n"
            "Collate the decisive figures from the executed cells above — random-day "
            "`p_greater`, the price-drop `gap` and its p-value, the block-bootstrap CI, the "
            "window swing. The README's beat-5 stamps are filled from this table."
        ),
        code(
            "# No re-computation: every figure below is pulled from the cells above.\n"
            "verdict = pd.DataFrame([\n"
            "    {'question': 'V1_level_30 beats a random day?  (+1w / +1mo)',\n"
            "     'figure': f\"excess {null_tbl.loc[('V1_level_30',5),'excess']:+.2%} (p={null_tbl.loc[('V1_level_30',5),'p_greater']:.3f})\"\n"
            "               f\"  /  {null_tbl.loc[('V1_level_30',21),'excess']:+.2%} (p={null_tbl.loc[('V1_level_30',21),'p_greater']:.3f})\"},\n"
            "    {'question': 'V2_spike beats a random day?  (+1mo, full history)',\n"
            "     'figure': f\"excess {null_tbl.loc[('V2_spike',21),'excess']:+.2%} (p={null_tbl.loc[('V2_spike',21),'p_greater']:.3f})\"},\n"
            "    {'question': 'V1_level_30 beats the -3% price day?  (gap, +1w / +1mo)',\n"
            "     'figure': f\"gap {ctrl['V1_level_30'].loc[5,'gap']:+.2%} (p={ctrl['V1_level_30'].loc[5,'p_signal_gt_alt']:.3f})\"\n"
            "               f\"  /  {ctrl['V1_level_30'].loc[21,'gap']:+.2%} (p={ctrl['V1_level_30'].loc[21,'p_signal_gt_alt']:.3f})\"},\n"
            "    {'question': 'V1_level_30 survives clustering?  (+1mo excess, block bootstrap)',\n"
            "     'figure': f\"CI [{boot['V1_level_30']['ci_low']:+.2%}, {boot['V1_level_30']['ci_high']:+.2%}]\"\n"
            "               f\"  P(excess<=0)={boot['V1_level_30']['p_excess_le_0']:.3f}\"},\n"
            "]).set_index('question')\n"
            "pd.set_option('display.max_colwidth', 120)\n"
            "verdict"
        ),
        md(
            "Reading the table:\n\n"
            "- **Signal `REAL` on the level, `NONE` on the spike.** VIX≥30 beats a random "
            "day by ~+1.0% at a week (p≈0.00) and ~+1.3% at a month (p≈0.01). The famous "
            "**+30% one-day spike** — the viral chart's trigger — carries **no** "
            "full-history excess at a month (p≈0.5); its entire showing lives inside the "
            "2016–2026 window (see the window-sensitivity table above).\n"
            "- **Tradability `MIRAGE`.** The level does **not** significantly beat the −3% "
            "price day Study 02 already tested (gap p≈0.13–0.20) — most of the \"VIX edge\" "
            "is the same panic, read off a different dial — and once clustering is "
            "respected the month-horizon CI touches zero (P(excess≤0)≈0.05).\n\n"
            "What's left is a **variance risk premium**: real, modest, crisis-clustered — "
            "compensation for holding the tail, not a free lunch."
        ),

        # ---- BEAT 6 — capacity + ruin ----------------------------------------
        md(
            "## 6 · Could you trade it — the martingale's risk of ruin\n\n"
            "Spot VIX isn't investable; the buy side is SPY (or a vol product with roll/decay). "
            "The decisive risk is the sizing rule: **\"double down at 50\"** adds capital as the "
            "tail fattens. We run it through history and report the probability it hits a ruin "
            "drawdown before recovering — on the full sample, and on the no-2008 window that "
            "sells it."
        ),
        md(
            "**First, trade the level honestly,** with buy-and-hold computed on the *same* "
            "sample as the benchmark. Buy at the VIX≥30 cross, hold a month, charge "
            "realistic costs (including entry slippage into the spike). You sit in cash "
            "~88% of the time: the per-active-day Sharpe comes out *above* buy-and-hold's, "
            "but with so little capital at work the strategy compounds a fraction of "
            "buy-and-hold's return — market-timing that underperforms the index it times, "
            "not an edge."
        ),
        code(
            "sig30 = triggers.first_crossings(triggers.level(vix, 30), cooldown=21)\n"
            "res = backtest.run(spx, sig30, exits.ExitRule(max_hold=21), backtest.CostModel())\n"
            "print('VIX>=30, hold<=21d :', {k: (round(v, 4) if isinstance(v, float) else v)\n"
            "      for k, v in res.stats.items()\n"
            "      if k in ('n_trades','cagr','sharpe','max_drawdown','win_rate','exposure')})\n"
            "# Buy-and-hold on the SAME sample — the benchmark the claim must beat.\n"
            "bh = spx['r_cc'].dropna(); eq = (1 + bh).cumprod(); years = len(bh) / 252\n"
            "print('buy-and-hold ^GSPC :', {'cagr': round(float(eq.iloc[-1]**(1/years) - 1), 4),\n"
            "      'sharpe': round(float(bh.mean()/bh.std(ddof=1)*np.sqrt(252)), 4),\n"
            "      'max_drawdown': round(float((eq/eq.cummax() - 1).min()), 4), 'exposure': 1.0})\n"
            "backtest.cost_sweep(spx, sig30, exits.ExitRule(max_hold=21))  # entry-slippage sweep"
        ),
        md(
            "**Then watch the family scan lie.** Scan every (trigger × exit) and the best "
            "cell posts an absurd Sharpe — on a handful of trades. Deflate it for the number "
            "of configs tried and it collapses back into noise. *Never read the best row.*"
        ),
        code(
            "fam = {'V1_30': triggers.level(vix,30), 'V1_50': triggers.level(vix,50),\n"
            "       'V2_spike': triggers.spike(vix), 'V3_high': triggers.spike_from_base(vix, base_min=30)}\n"
            "scan = backtest.family_scan(spx, fam, exits.default_grid())\n"
            "top = scan.iloc[0]\n"
            "dsr = robustness.deflated_sharpe(top.sharpe, n_trials=len(scan), n_obs=int(top.avg_hold_days*top.n_trades))\n"
            "print(f\"best cell: {top.trigger} / {top.exit}  Sharpe={top.sharpe:.1f} on {int(top.n_trades)} trades\")\n"
            "print(f\"deflated Sharpe (P it isn't luck over {len(scan)} configs): {dsr:.3f}\")\n"
            "scan.head(5)"
        ),
        md(
            "**Now the martingale.** \"Double down at 50\", held a fixed quarter (and, as a "
            "stress, a fixed six months), tracking the deepest drawdown along the way — on "
            "the full sample versus the no-2008 window that sells the rule. The ruin bar is "
            "a −20% mark-to-market drawdown: margin-call territory for anyone running this "
            "levered."
        ),
        code(
            "win = spx.index >= '2016-06-01'\n"
            "pd.DataFrame({\n"
            "    'full history':              robustness.martingale_ruin(spx, vix, rung1=30, rung2=50),\n"
            "    'full, 6-month hold':        robustness.martingale_ruin(spx, vix, rung1=30, rung2=50, hold_days=126),\n"
            "    'chart window (2016–2026)':  robustness.martingale_ruin(spx[win], vix[win], rung1=30, rung2=50),\n"
            "})"
        ),
        md(
            "Read the columns honestly — the numbers are more interesting than the slogan:\n\n"
            "- **Breach *frequency* is low everywhere, and the chart window's is actually "
            "the *highest*** (1 of 11 episodes ≈ 9% vs 2 of 32 ≈ 6% full-history — March "
            "2020 is inside the window). The no-2008 decade does **not** look safer by "
            "this measure, and the average episode ends positive in both samples. The "
            "window trick is *not* hiding how often you get hurt.\n"
            "- **What the window hides is severity.** Full history, the worst episode "
            "(2008) sits **−33%** under water on a quarter hold, **−40%** on a six-month "
            "hold, and still *ends* **−21%** (−31% at six months). In the chart window the "
            "worst *terminal* loss is **−3.6%** — every drawdown healed by the bell. "
            "That's the line that sells the rule: *it always came back.* In 2008 it "
            "didn't, and the doubling rule had you meet that one path with twice the "
            "capital.\n\n"
            "A martingale doesn't fail often — that's its sales pitch. It fails *big*, "
            "and only the windows that contain a 2008 let you see it."
        ),

        # ---- BEAT 7 ----------------------------------------------------------
        md(
            "## 7 · Going further\n\n"
            "- **VRP-hedged return** as the dependent variable — does any excess survive once "
            "you strip the variance premium? If not, case closed.\n"
            "- **Term-structure conditioning** (VIX vs VIX3M backwardation at the event).\n"
            "- **Cross-asset replication** on MOVE (bonds) and DVOL (crypto).\n\n"
            "Engine: [`../../../quantlab/`](../../../quantlab/). Method: "
            "[`METHODOLOGY.md`](../../../METHODOLOGY.md)."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")
    return nb


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print(f"wrote {name}  ({len(nb.cells)} cells)")


def main():
    build_curious()
    build_quants()


if __name__ == "__main__":
    main()
