"""Real-tape runner — Study 114 (Dollar-Smile).

Fetches (or reloads from cache) DX-Y.NYB, SPY, and EEM, runs the full regression
suite (contemporaneous, predictive IS, OOS R², momentum signal), and regenerates
docs/results.md. Run once with ``--fetch`` to populate the cache; after that the
cache is used automatically.

    python studies/114-dollar-smile/examples/verify.py           # cache-only
    python studies/114-dollar-smile/examples/verify.py --fetch   # refresh from Yahoo
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

FETCH = "--fetch" in sys.argv

from dollar_smile import data, strategy as st  # noqa: E402

CACHE = os.path.join(os.path.dirname(__file__), "..", "_cache")
DOCS = os.path.join(os.path.dirname(__file__), "..", "docs")


def main() -> None:
    print("Study 114 — Dollar-Smile — real-tape verification\n")

    # ---- load data ----
    panel = data.load_panel(fetch=FETCH, cache_dir=CACHE)
    df = data.build_panel_frame(panel)
    fp = data.fingerprint(df)

    print(f"Aligned panel: {len(df)} rows | {df.index[0].date()} -> {df.index[-1].date()}")
    for t in data.TICKERS:
        b = panel[t]
        print(f"  {t:12s}: {len(b)} rows  {b.index[0].date()} -> {b.index[-1].date()}")
    print(f"Fingerprint (spy close): {fp}\n")

    # ---- weekly ----
    res_w = st.run_all(df, horizon="W")
    nw = res_w["n_periods"]
    cspy = res_w["contemp_spy"]
    ceem = res_w["contemp_eem"]
    ispy = res_w["is_spy"]
    ieem = res_w["is_eem"]
    ospy = res_w["oos_spy"]
    oeem = res_w["oos_eem"]
    sspy = res_w["signal_spy"]
    seem = res_w["signal_eem"]

    print(f"=== WEEKLY ({nw} periods) ===")
    print("\nCONTEMPORANEOUS (same-week regression):")
    print(f"  SPY: beta={cspy['beta']:+.4f}  R2={cspy['r2']*100:.2f}%  HAC t={cspy['tstat']:+.2f}")
    print(f"  EEM: beta={ceem['beta']:+.4f}  R2={ceem['r2']*100:.2f}%  HAC t={ceem['tstat']:+.2f}")
    print("\nPREDICTIVE (lagged dollar -> forward equity return):")
    print(f"  SPY: beta={ispy['beta']:+.4f}  R2={ispy['r2']*100:.3f}%  HAC t={ispy['tstat']:+.2f}")
    print(f"  EEM: beta={ieem['beta']:+.4f}  R2={ieem['r2']*100:.3f}%  HAC t={ieem['tstat']:+.2f}")
    print("\nOOS R² (Goyal-Welch expanding window):")
    print(f"  SPY: OOS R2={ospy['r2_oos']*100:+.2f}%  DM t={ospy['dm_tstat']:+.2f}  n_oos={ospy['n_oos']}")
    print(f"  EEM: OOS R2={oeem['r2_oos']*100:+.2f}%  DM t={oeem['dm_tstat']:+.2f}  n_oos={oeem['n_oos']}")
    print("\nMOMENTUM SIGNAL (dollar-direction timing strategy):")
    print(f"  SPY: mean={sspy['mean_bps']:+.2f} bps/wk  win={sspy['win_rate']*100:.1f}%  t={sspy['tstat']:+.2f}")
    print(f"  EEM: mean={seem['mean_bps']:+.2f} bps/wk  win={seem['win_rate']*100:.1f}%  t={seem['tstat']:+.2f}")

    # ---- monthly ----
    res_m = st.run_all(df, horizon="ME")
    nm = res_m["n_periods"]
    print(f"\n=== MONTHLY ({nm} periods) ===")
    print(f"  CONTEMP SPY: beta={res_m['contemp_spy']['beta']:+.4f}  R2={res_m['contemp_spy']['r2']*100:.2f}%  t={res_m['contemp_spy']['tstat']:+.2f}")
    print(f"  CONTEMP EEM: beta={res_m['contemp_eem']['beta']:+.4f}  R2={res_m['contemp_eem']['r2']*100:.2f}%  t={res_m['contemp_eem']['tstat']:+.2f}")
    print(f"  PRED SPY:    beta={res_m['is_spy']['beta']:+.4f}  R2={res_m['is_spy']['r2']*100:.3f}%  t={res_m['is_spy']['tstat']:+.2f}")
    print(f"  PRED EEM:    beta={res_m['is_eem']['beta']:+.4f}  R2={res_m['is_eem']['r2']*100:.3f}%  t={res_m['is_eem']['tstat']:+.2f}")
    print(f"  OOS SPY: R2={res_m['oos_spy']['r2_oos']*100:+.2f}%  DM t={res_m['oos_spy']['dm_tstat']:+.2f}")
    print(f"  OOS EEM: R2={res_m['oos_eem']['r2_oos']*100:+.2f}%  DM t={res_m['oos_eem']['dm_tstat']:+.2f}")

    # ---- verdict ----
    print("\nVERDICT:")
    print(f"  Contemporaneous link: REAL (weekly SPY t={cspy['tstat']:+.2f}, EEM t={ceem['tstat']:+.2f})")
    print(f"  Predictive link:      NONE (weekly SPY t={ispy['tstat']:+.2f}, EEM t={ieem['tstat']:+.2f})")
    print(f"  OOS R²:               NEGATIVE (SPY {ospy['r2_oos']*100:+.2f}%, EEM {oeem['r2_oos']*100:+.2f}%)")
    print(f"  Signal (SPY):         NONE (t={sspy['tstat']:+.2f})")
    print(f"  => Signal: NONE / Tradability: MIRAGE / Coincident: CONFIRMED")

    # ---- write results.md ----
    results_path = os.path.join(DOCS, "results.md")
    os.makedirs(DOCS, exist_ok=True)
    as_of = df.index[-1].date()
    panel_dx = panel["DX-Y.NYB"]
    panel_spy = panel["SPY"]
    panel_eem = panel["EEM"]

    md = f"""# Results — Study 114 (Dollar-Smile) on real daily tape

*Generated by [`examples/verify.py`](../examples/verify.py). The US Dollar Index
(DX-Y.NYB) as a predictive signal for forward equity returns (SPY, EEM). Tested
as lagged regression and expanding-window OOS R² against the Goyal-Welch (2008)
naive-mean benchmark. Daily data {df.index[0].date()} to {as_of}, weekly and monthly
resampling. As-of **{as_of}**.*

## Data stamp

| Ticker | Window | Rows | Description |
|---|---|---|---|
| DX-Y.NYB | {panel_dx.index[0].date()} -> {panel_dx.index[-1].date()} | {len(panel_dx):,} | US Dollar Index (ICE, nominal) |
| SPY      | {panel_spy.index[0].date()} -> {panel_spy.index[-1].date()} | {len(panel_spy):,} | SPDR S&P 500 ETF (US large-cap equity) |
| EEM      | {panel_eem.index[0].date()} -> {panel_eem.index[-1].date()} | {len(panel_eem):,} | iShares MSCI Emerging Markets ETF |

**Aligned panel:** {len(df):,} daily rows ({df.index[0].date()} -> {as_of})

SPY close fingerprint: `{fp}`

## Weekly regression results

Predictor: dollar log-change at week *t*. Target: equity log-return at week *t+1*
(strictly forward, no look-ahead). Baseline: historical-mean return (Goyal-Welch
benchmark). Sample: **{nw} weekly periods**.

### Contemporaneous (same-week) regression

| Target | β | HAC *t* | R² |
|---|--:|--:|--:|
| **SPY (same week)** | **{cspy['beta']:+.4f}** | **{cspy['tstat']:+.2f}** | **{cspy['r2']*100:.2f}%** |
| **EEM (same week)** | **{ceem['beta']:+.4f}** | **{ceem['tstat']:+.2f}** | **{ceem['r2']*100:.2f}%** |

The contemporaneous link is strong and negative — the dollar moves *against* equities
in the same week (dollar up -> equities down). EEM is substantially more sensitive
than SPY (beta −{abs(ceem['beta']):.2f} vs −{abs(cspy['beta']):.2f}).

### In-sample predictive regression

| Target | β | HAC *t* | R² | n |
|---|--:|--:|--:|--:|
| **Fwd SPY return** | **{ispy['beta']:+.4f}** | **{ispy['tstat']:+.2f}** | **{ispy['r2']*100:.3f}%** | {ispy['n']:,} |
| **Fwd EEM return** | **{ieem['beta']:+.4f}** | **{ieem['tstat']:+.2f}** | **{ieem['r2']*100:.3f}%** | {ieem['n']:,} |

The predictive regressions are statistically indistinguishable from zero for both
SPY (HAC *t* = {ispy['tstat']:+.2f}) and EEM (HAC *t* = {ieem['tstat']:+.2f}). R² is
essentially zero (<0.03%).

### Out-of-sample (expanding window, min 52 weeks training)

| Target | OOS R² | DM *t* | n_oos |
|---|--:|--:|--:|
| **SPY** | **{ospy['r2_oos']*100:+.2f}%** | **{ospy['dm_tstat']:+.2f}** | {ospy['n_oos']:,} |
| **EEM** | **{oeem['r2_oos']*100:+.2f}%** | **{oeem['dm_tstat']:+.2f}** | {oeem['n_oos']:,} |

OOS R² is **negative** for both targets — the dollar model is outperformed by the
simple historical-mean forecast. The DM t-stat is insignificant.

### Momentum signal (dollar-direction timing)

| Target | Mean (bps/wk) | Win rate | HAC *t* |
|---|--:|--:|--:|
| SPY | {sspy['mean_bps']:+.2f} | {sspy['win_rate']*100:.1f}% | {sspy['tstat']:+.2f} |
| EEM | {seem['mean_bps']:+.2f} | {seem['win_rate']*100:.1f}% | {seem['tstat']:+.2f} |

## Monthly regression results

Sample: **{nm} monthly periods**.

| Target | β | HAC *t* | R² | OOS R² |
|---|--:|--:|--:|--:|
| CONTEMP SPY | {res_m['contemp_spy']['beta']:+.4f} | {res_m['contemp_spy']['tstat']:+.2f} | {res_m['contemp_spy']['r2']*100:.2f}% | — |
| CONTEMP EEM | {res_m['contemp_eem']['beta']:+.4f} | {res_m['contemp_eem']['tstat']:+.2f} | {res_m['contemp_eem']['r2']*100:.2f}% | — |
| Fwd SPY return | {res_m['is_spy']['beta']:+.4f} | {res_m['is_spy']['tstat']:+.2f} | {res_m['is_spy']['r2']*100:.3f}% | {res_m['oos_spy']['r2_oos']*100:+.2f}% |
| Fwd EEM return | {res_m['is_eem']['beta']:+.4f} | {res_m['is_eem']['tstat']:+.2f} | {res_m['is_eem']['r2']*100:.3f}% | {res_m['oos_eem']['r2_oos']*100:+.2f}% |

Monthly results confirm the pattern: contemporaneous R² is large (SPY {res_m['contemp_spy']['r2']*100:.1f}%,
EEM {res_m['contemp_eem']['r2']*100:.1f}%) while predictive regressions are near-zero.

## The key contrast: contemporaneous vs predictive

| | Contemporaneous (SPY) | Predictive (weekly) |
|---|--:|--:|
| **β** | {cspy['beta']:+.4f} | {ispy['beta']:+.4f} |
| **R²** | {cspy['r2']*100:.2f}% | {ispy['r2']*100:.3f}% |
| **HAC t** | {cspy['tstat']:+.2f} | {ispy['tstat']:+.2f} |

The dollar and equities move *together* (contemporaneous) but the dollar does not
*lead* equities (predictive). The "strong dollar is bad for stocks" claim is true
as description, not as forecast.

## Verdict

- **Signal — NONE.** IS weekly t SPY = {ispy['tstat']:+.2f}, EEM = {ieem['tstat']:+.2f}; OOS R² negative;
  momentum signal t SPY = {sspy['tstat']:+.2f}. The inference bar is not cleared.
- **Tradability — MIRAGE.** No reliable directional forecast -> no tradable timing edge
  from dollar direction alone.
- **Contemporaneous/Coincident? — CONFIRMED.** The dollar has a strong coincident
  relationship with equities (weekly SPY R² {cspy['r2']*100:.1f}%, t {cspy['tstat']:+.2f}; EEM R² {ceem['r2']*100:.1f}%,
  t {ceem['tstat']:+.2f}) — but it moves *with* markets, not *before* them.
"""
    with open(results_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"\nWrote {results_path}")


if __name__ == "__main__":
    main()
