"""Beat-7 worked complement on the real tape — does risk management dodge the steamroller?

Vol-targeting earned [Study 16](../../16-storm-shy/) the desk's only green and tamed momentum's crash in
[Study 24](../../24-stampede/). Does the same overlay protect the carry trade? This script builds the
vol-managed G10 carry book and compares its crash profile to the plain one, writing `docs/extension.md`.
Needs the cached/fetched G10 data (see examples/verify.py).

    python examples/extension.py --fetch
"""

import argparse
import os
import sys

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from steamroller import data, carry, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")
COST_BPS = 10.0


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    g10 = data.fetch_carry(fetch=args.fetch)
    if not g10:
        print("[skip] no cached G10 data -- run examples/verify.py --fetch first (FRED)."); return
    rates, fx = as_of(g10["rates"], DEFAULT_AS_OF), as_of(g10["fx"], DEFAULT_AS_OF)
    xr = carry.excess_returns(rates, fx)
    rates_aligned = rates[[c for c in xr.columns]].reindex(xr.index)
    fp = fingerprint(xr.round(6))
    cc = extension.crash_comparison(xr, rates_aligned, cost_bps=COST_BPS)
    for k in ("plain", "managed"):
        p = cc[k]; print(f"{k:8s}: Sharpe {p['sharpe']:+.2f}, skew {p['skew']:+.2f}, DD {p['max_drawdown_pct']:.0f}%")
    _write(OUT, cc, fp, DEFAULT_AS_OF, xr.index.min().date(), xr.index.max().date(), xr.shape[1])
    print(f"\nwrote {OUT}")


def _write(path, cc, fp, asof, lo, hi, n_ccy):
    p, m = cc["plain"], cc["managed"]
    text = f"""# Beat 7 — worked complement: can risk management dodge the steamroller? (Study 27)

*Generated by [`examples/extension.py`](../examples/extension.py) on real G10 carry (FRED). As-of
**{asof}**, {n_ccy} currencies, {lo} → {hi}, fingerprint `{fp}`.*

## The overlay that worked elsewhere — and doesn't here

Vol-targeting tamed the crash for equity ([Study 16](../../16-storm-shy/)) and momentum
([Study 24](../../24-stampede/)), because those crashes are preceded by *rising volatility* a trailing
estimate can see. Carry is different.

| | plain carry | vol-managed carry |
|---|---|---|
| Sharpe | {p['sharpe']:+.2f} | {m['sharpe']:+.2f} |
| monthly skew | {p['skew']:+.2f} | {m['skew']:+.2f} |
| worst month | {p['worst_month_pct']:+.1f}% | {m['worst_month_pct']:+.1f}% |
| max drawdown | {p['max_drawdown_pct']:.0f}% | {m['max_drawdown_pct']:.0f}% |

Vol-scaling lifts the standalone Sharpe (**{p['sharpe']:+.2f} → {m['sharpe']:+.2f}**) but does **not**
shrink the drawdown (**{p['max_drawdown_pct']:.0f}% → {m['max_drawdown_pct']:.0f}%**) — and can deepen it,
because in calm times it *levers up* into a carry trade whose crash arrives as a sudden risk-off jump,
not a forecastable vol build-up.

**Takeaway.** `REAL` / `FRAGILE` / `Severe` survives the worked complement — and the complement sharpens
*why* the crash is `Severe`: it is the one tail the desk's usual risk overlay can't forecast. Carry's
premium is real compensation for a jump you have to be willing (and able) to hold through; the honest
fixes are diversification, options-based tail hedges, or conditioning on a risk-off indicator — forks for
the next contributor, not a vol target.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
