"""Notebook builder for Study 1005 — Beta Has a Half-Life.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Beta Has a Half-Life \U0001F4C9
### The number is printed to two decimals. Perhaps one of them is real.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

A beta appears on every risk report, in every cost-of-capital calculation, behind every hedge
ratio. It arrives without a standard error and without an expiry date. This study supplies both.

> \U0001F4D3 **This is the plain-language layer.** The variance decomposition, the forecast
> horse race and the constant-beta control are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does last year's beta predict this year's? | Partly. |
| How long before it is half stale? | Around a year and a half. |
| Is beta really that unstable? | No — the *estimate* is. |
| Should you shrink it toward 1? | Yes, and by about a third. |
"""
        ),
        md(
            r"""

## 1 · One company's beta, year by year
"""
        ),
        code(
            r"""
from betahalflife import data, strategy as st

px = data.load_prices()
cols = [c for c in (data.MARKET,) + data.NAMES if c in px.columns]
R = px[cols].pct_change().dropna()
betas = st.rolling_betas(R, data.MARKET, 252, 252)
lf = st.long_form(betas)
print(f"as-of {data.AS_OF} | {len(cols)-1} names, {len(R):,} sessions from "
      f"{R.index[0].date()}")
print(f"{len(betas)} non-overlapping annual windows -> {len(lf):,} beta estimates")
print(f"mean beta {lf['beta'].mean():.3f}, mean standard error {lf['se'].mean():.4f}")
"""
        ),
        code(
            r"""
fig, ax = plt.subplots(figsize=(12, 5.5))
for nm in ("AAPL", "KO", "JPM", "XOM", "PG"):
    if nm not in betas.columns:
        continue
    ax.errorbar(betas.index, betas[nm], yerr=1.96 * betas[f"{nm}__se"],
                fmt="o-", capsize=3, lw=1.5, label=nm, alpha=0.85)
ax.axhline(1.0, color="k", lw=1.5, ls="--", label="the market")
ax.set_ylabel("beta (annual window, 95% interval)")
ax.legend(fontsize=9, ncol=3)
plt.show()
print("The bars are 95% confidence intervals. Notice how many of the year-to-year")
print("'changes' are comfortably inside them.")
"""
        ),
        md(
            r"""

That last point is the whole study. A beta that "moved from 1.1 to 1.3" may not have moved at
all — you may simply have measured it twice.
"""
        ),
        md(
            r"""

## 2 · Does last year predict this year?
"""
        ),
        code(
            r"""
piv = lf.pivot(index="date", columns="name", values="beta").sort_index()
prev, cur = [], []
for i in range(1, len(piv)):
    a, b = piv.iloc[i-1], piv.iloc[i]
    ok = a.notna() & b.notna()
    prev.extend(a[ok]); cur.extend(b[ok])
p = st.persistence(betas)
fig, ax = plt.subplots(figsize=(7.5, 7))
ax.scatter(prev, cur, s=14, alpha=0.35, color="#1f6feb")
xs = np.linspace(min(prev), max(prev), 50)
ax.plot(xs, p["intercept"] + p["slope"] * xs, color="#c0392b", lw=2.5,
        label=f"fitted: slope {p['slope']:.2f}")
ax.plot(xs, xs, "k--", lw=1.5, label="perfect persistence")
ax.set_xlabel("this year's beta"); ax.set_ylabel("next year's beta")
ax.legend(fontsize=9)
plt.show()
print(f"slope {p['slope']:.3f}, so a deviation from average decays by half in "
      f"{st.half_life(p['slope']):.2f} years")
"""
        ),
        md(
            r"""

The red line is flatter than the dashed one. High-beta names drift down, low-beta names drift
up. That is Blume's 1971 finding and it is why textbooks tell you to shrink toward 1.
"""
        ),
        md(
            r"""

## 3 · But how much of that is real?
"""
        ),
        code(
            r"""
nf = st.noise_floor(betas)
fig, ax = plt.subplots(figsize=(9, 5))
ax.bar(["what you see", "measurement\nerror", "real\nmovement"],
       [nf["observed_sd"], nf["noise_sd"], nf["true_sd"]],
       color=["#8b949e", "#c0392b", "#2ea44f"])
ax.set_ylabel("standard deviation of the year-to-year change in beta")
plt.show()
print(f"observed change:   sd {nf['observed_sd']:.3f}")
print(f"  of which noise:  sd {nf['noise_sd']:.3f}  ({nf['noise_share']:.0%})")
print(f"  genuinely real:  sd {nf['true_sd']:.3f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Two independent estimates of the *same* constant differ by
> their combined sampling error. Subtract 2·mean(se²) from the observed variance of the change
> and what remains is genuine movement. Nothing on a risk report does this.
"""
        ),
        md(
            r"""

## 4 · The proof: measure it better and it stops moving
"""
        ),
        code(
            r"""
pb = st.portfolio_betas(R, data.MARKET, data.NAMES, n_per=10, n_ports=20)
plf = st.long_form(pb)
pp = st.persistence(pb)
pnf = st.noise_floor(pb)
fig, axes = plt.subplots(1, 3, figsize=(14, 4.4))
for ax, vals, title in (
        (axes[0], [lf["se"].mean(), plf["se"].mean()], "standard error"),
        (axes[1], [p["slope"], pp["slope"]], "persistence slope"),
        (axes[2], [nf["noise_share"], pnf["noise_share"]], "share that is noise")):
    ax.bar(["single\nstocks", "10-stock\nportfolios"], vals,
           color=["#c0392b", "#2ea44f"])
    ax.set_title(title, fontsize=10)
plt.tight_layout(); plt.show()
print(f"single names:  se {lf['se'].mean():.4f}, persistence {p['slope']:.3f}")
print(f"portfolios:    se {plf['se'].mean():.4f}, persistence {pp['slope']:.3f}")
"""
        ),
        md(
            r"""

If betas genuinely wandered, diversifying would not stop them. It largely does. So most of what
looked like instability was the measurement, not the thing measured.
"""
        ),
        md(
            r"""

## 5 · So what should you actually use?
"""
        ),
        code(
            r"""
fc = st.forecast_comparison(betas)
opt = st.optimal_shrinkage(betas)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
order = fc.sort_values("rmse")
axes[0].barh(range(len(order)), order["rmse"],
             color=["#2ea44f" if i == 0 else "#8b949e" for i in range(len(order))])
axes[0].set_yticks(range(len(order))); axes[0].set_yticklabels(order.index)
axes[0].set_xlabel("prediction error (RMSE, lower is better)")
c = pd.DataFrame(opt["curve"])
axes[1].plot(c["w"], c["rmse"], lw=2.5, color="#1f6feb")
axes[1].axvline(opt["best_w"], color="#2ea44f", lw=2, label=f"best: {opt['best_w']:.2f}")
axes[1].axvline(0.66, color="#f0b429", lw=2, ls="--", label="Blume's 0.66")
axes[1].axvline(1.0, color="#c0392b", lw=2, ls=":", label="no shrinkage")
axes[1].set_xlabel("shrinkage weight"); axes[1].set_ylabel("RMSE")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(fc.round(4).to_string())
"""
        ),
        md(
            r"""

Look at **always_one** — that is assuming every company has a beta of exactly 1.0 and using no
data whatsoever. Whatever a beta model does, it has to beat that first.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Real.** Partly, and much less than the two decimal places on a risk report imply. Across 40 names over 16 non-overlapping 252-day windows, regressing each period's cross-section of betas on the previous period's gives a slope of **0.802** (±0.027, R² 0.60) — Blume's finding, reproduced. A deviation from the average beta therefore decays by half in **3.1 years**. But the more important number is what that instability is made of. A beta measured over 252 days carries a mean standard error of 0.088, so two consecutive estimates would differ even if the true beta never moved. Decomposing the variance of the observed period-to-period change: **28% is estimation error** and only the remainder is genuine movement — a true standard deviation of 0.227 against an apparent 0.268. Betas move much less than they appear to; the estimates move a lot. The confirmation is the portfolio test: ten-stock portfolios cut the mean standard error from 0.0885 to 0.0317 and the noise share from 28% to 24% — measure beta better and less of its instability survives. Note the slope does **not** confirm this (0.773 against 0.802), and that is a finding in itself: regressing a noisy measure on a noisy measure attenuates the slope by var(true)/[var(true)+var(noise)], and diversification lowers both terms at once. The Blume slope confounds persistence with measurement quality and should not be read as a stability statistic at all — the synthetic control makes the point unanswerable, since a *drifting* beta there produces a **higher** slope than a perfectly constant one.

**Tradability: Useful.** Shrinkage helps, the textbook constant is close to right, and the honest benchmark is harder than it looks. Predicting each period's beta from the previous one, root-mean-square error came to **0.260** using the raw estimate, 0.253 with Blume's 0.66 shrinkage, 0.255 with Vasicek's precision weighting, and **0.393 simply assuming 1.0 for every name**. That last figure is the one worth pausing on: the raw estimate holds it off, which puts a floor under how much any beta model is really contributing. Searching the shrinkage weight directly gives an optimum of **0.80** — against Blume's 0.66, and against the persistence slope of 0.802 that theory says it should equal, a coincidence close enough to be reassuring about the whole framework. Practically: re-estimate no more often than the half-life justifies, shrink toward one, and stop quoting the second decimal.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Stop quoting the second decimal.** With a standard error around 0.06, "beta 1.23" and "beta
  1.19" are the same statement.
- **Shrink toward one.** Roughly a third of the way is close to optimal here, and it is what
  the persistence slope independently implies.
- **Re-estimate on the half-life, not the calendar.** Monthly beta updates on a number with a
  multi-year half-life are mostly re-measuring noise, and acting on those updates means trading
  against your own estimation error.
- **Portfolios are different.** A diversified book's beta is a far more reliable number than any
  single holding's, and can be trusted with more of the weight people place on it.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Beta Has a Half-Life — a quantitative teardown \U0001F52C
### Blume persistence · a noise/movement variance split · four forecasts scored

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The section that
does the work is **§3.2**: apparent beta instability is split into estimation error and genuine
movement using each regression's own standard error. §3.3 confirms it the hard way — measure
beta better, and most of the instability disappears.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from betahalflife import data, strategy as st

px = data.load_prices()
cols = [c for c in (data.MARKET,) + data.NAMES if c in px.columns]
R = px[cols].pct_change().dropna()
betas = st.rolling_betas(R, data.MARKET, 252, 252)
lf = st.long_form(betas)
print(f"as-of {data.AS_OF} | {len(cols)-1} names, {len(R):,} sessions from "
      f"{R.index[0].date()}")
print(f"{len(betas)} non-overlapping annual windows -> {len(lf):,} beta estimates")
print(f"mean beta {lf['beta'].mean():.3f}, mean standard error {lf['se'].mean():.4f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | Partly, and much less than the two decimal places on a risk report imply. Across 40 names over 16 non-overlapping 252-day windows, regressing each period's cross-section of betas on the previous period's gives a slope of **0.802** (±0.027, R² 0.60) — Blume's finding, reproduced. A deviation from the average beta therefore decays by half in **3.1 years**. But the more important number is what that instability is made of. A beta measured over 252 days carries a mean standard error of 0.088, so two consecutive estimates would differ even if the true beta never moved. Decomposing the variance of the observed period-to-period change: **28% is estimation error** and only the remainder is genuine movement — a true standard deviation of 0.227 against an apparent 0.268. Betas move much less than they appear to; the estimates move a lot. The confirmation is the portfolio test: ten-stock portfolios cut the mean standard error from 0.0885 to 0.0317 and the noise share from 28% to 24% — measure beta better and less of its instability survives. Note the slope does **not** confirm this (0.773 against 0.802), and that is a finding in itself: regressing a noisy measure on a noisy measure attenuates the slope by var(true)/[var(true)+var(noise)], and diversification lowers both terms at once. The Blume slope confounds persistence with measurement quality and should not be read as a stability statistic at all — the synthetic control makes the point unanswerable, since a *drifting* beta there produces a **higher** slope than a perfectly constant one. |
| **Tradability** | Useful | Shrinkage helps, the textbook constant is close to right, and the honest benchmark is harder than it looks. Predicting each period's beta from the previous one, root-mean-square error came to **0.260** using the raw estimate, 0.253 with Blume's 0.66 shrinkage, 0.255 with Vasicek's precision weighting, and **0.393 simply assuming 1.0 for every name**. That last figure is the one worth pausing on: the raw estimate holds it off, which puts a floor under how much any beta model is really contributing. Searching the shrinkage weight directly gives an optimum of **0.80** — against Blume's 0.66, and against the persistence slope of 0.802 that theory says it should equal, a coincidence close enough to be reassuring about the whole framework. Practically: re-estimate no more often than the half-life justifies, shrink toward one, and stop quoting the second decimal. |

> \U0001F4A1 **In plain words.** Beta is steadier than beta estimates.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (Blume).** The cross-sectional persistence slope is strictly between zero and one.
- **H₂ (decomposition).** A material share of the observed period-to-period variation is
  attributable to estimation error rather than to movement in the true beta.
- **H₃ (portfolio confirmation).** Diversified portfolios, whose betas are measured more
  precisely, show higher persistence and a lower noise share.
- **H₄ (window length).** Longer estimation windows raise measured persistence, because they
  reduce the noise component rather than because betas become more stable.
- **H₅ (forecasting).** Shrinkage beats the raw estimate out of sample, and the fitted weight
  approximately equals the persistence slope.
- **H₆ (control).** A synthetic world with a perfectly *constant* true beta still produces a
  persistence slope below one — so part of Blume's regression tendency is a statistical
  artefact.
"""
        ),
        md(
            r"""

## 2 · Estimation design

Non-overlapping windows, deliberately. Overlapping ones share observations, which inflates the
apparent persistence — the study would then partly measure its own construction.
"""
        ),
        code(
            r"""
rows = []
for step_frac, label in ((1.0, "non-overlapping"), (0.5, "50% overlap"),
                         (0.25, "75% overlap"), (0.08, "92% overlap")):
    b = st.rolling_betas(R, data.MARKET, 252, max(int(252 * step_frac), 1))
    p = st.persistence(b)
    rows.append({"scheme": label, "step_days": max(int(252 * step_frac), 1),
                 "n_windows": len(b), "slope": p["slope"], "r2": p["r2"]})
d = pd.DataFrame(rows).set_index("scheme")
print(d.round(4).to_string())
print()
print("Overlapping windows manufacture persistence out of shared data. The default is the")
print("first row, and everything below uses it.")
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Persistence, and its own uncertainty
"""
        ),
        code(
            r"""
p = st.persistence(betas)
piv = lf.pivot(index="date", columns="name", values="beta").sort_index()
rows = []
for i in range(1, len(piv)):
    a, b = piv.iloc[i-1], piv.iloc[i]
    ok = a.notna() & b.notna()
    if ok.sum() > 5:
        s, se, r2 = st.beta_with_se(b[ok].to_numpy(), a[ok].to_numpy())
        rows.append({"date": piv.index[i], "slope": s, "se": se, "r2": r2})
d = pd.DataFrame(rows).set_index("date")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].errorbar(d.index, d["slope"], yerr=1.96 * d["se"], fmt="o", capsize=3,
                 color="#1f6feb")
axes[0].axhline(p["slope"], color="#c0392b", lw=2,
                label=f"pooled {p['slope']:.3f}")
axes[0].axhline(1.0, color="k", ls="--", lw=1.5)
axes[0].set_ylabel("persistence slope, year by year"); axes[0].legend(fontsize=8)
axes[1].plot(d.index, d["r2"], "o-", color="#1f6feb")
axes[1].set_ylabel("R² of the persistence regression")
plt.tight_layout(); plt.show()
print({k: round(v, 4) for k, v in p.items()})
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The pooled slope hides a lot of year-to-year variation in the
> slope itself. "Shrink by a third" is a long-run average, not a rule that held every year.
"""
        ),
        md(
            r"""

### 3.2 The decomposition — the load-bearing section
"""
        ),
        code(
            r"""
nf = st.noise_floor(betas)
sn = st.signal_to_noise(betas)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].bar(["observed", "noise", "true"],
            [nf["observed_var"], nf["noise_var"], nf["true_var"]],
            color=["#8b949e", "#c0392b", "#2ea44f"])
axes[0].set_ylabel("variance of the year-to-year change")
axes[0].set_title(f"{nf['noise_share']:.0%} of it is measurement", fontsize=10)
sepiv = lf.pivot(index="date", columns="name", values="se")
cross = lf.pivot(index="date", columns="name", values="beta").var(axis=1, ddof=1)
noise = (sepiv ** 2).mean(axis=1)
axes[1].plot(cross.index, cross, "o-", lw=2, color="#8b949e",
             label="observed cross-sectional variance")
axes[1].plot(cross.index, (cross - noise).clip(lower=0), "s-", lw=2, color="#2ea44f",
             label="after removing estimation error")
axes[1].set_ylabel("variance of beta across names"); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print({k: round(v, 5) for k, v in nf.items()})
print({k: round(v, 4) for k, v in sn.items()})
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The right panel matters for anyone ranking companies by beta:
> a chunk of the spread between "high beta" and "low beta" names in any given year is the
> estimator, not the companies.
"""
        ),
        md(
            r"""

### 3.3 The confirmation, at several portfolio sizes
"""
        ),
        code(
            r"""
rows = [{"n_per": 1, "mean_se": lf["se"].mean(), "slope": p["slope"],
         "noise_share": nf["noise_share"]}]
for n_per in (2, 5, 10, 20):
    pb = st.portfolio_betas(R, data.MARKET, data.NAMES, n_per=n_per, n_ports=25)
    if pb.empty:
        continue
    plf = st.long_form(pb)
    rows.append({"n_per": n_per, "mean_se": plf["se"].mean(),
                 "slope": st.persistence(pb)["slope"],
                 "noise_share": st.noise_floor(pb)["noise_share"]})
d = pd.DataFrame(rows).set_index("n_per")
fig, axes = plt.subplots(1, 3, figsize=(14, 4.4))
for ax, col, lbl in zip(axes, ["mean_se", "slope", "noise_share"],
                        ["mean standard error", "persistence slope",
                         "share that is noise"]):
    ax.plot(d.index, d[col], "o-", lw=2.5, color="#1f6feb")
    ax.set_xlabel("stocks per portfolio"); ax.set_ylabel(lbl)
plt.tight_layout(); plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

### 3.4 Window length
"""
        ),
        code(
            r"""
ph = st.persistence_by_horizon(R, data.MARKET, windows=(63, 126, 252, 504))
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
axes[0].errorbar(ph.index, ph["slope"], yerr=1.96 * ph["slope_se"], fmt="o-",
                 capsize=4, lw=2, color="#1f6feb")
axes[0].axhline(1.0, color="k", ls="--", lw=1.5)
axes[0].set_xlabel("estimation window (days)")
axes[0].set_ylabel("persistence slope")
axes[1].plot(ph.index, ph["half_life_years"], "o-", lw=2, color="#c0392b")
axes[1].set_xlabel("estimation window (days)")
axes[1].set_ylabel("half-life (years)")
plt.tight_layout(); plt.show()
print(ph.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Beta did not become more stable when the window lengthened.
> The measurement became better, and the apparent instability was largely the measurement.
"""
        ),
        md(
            r"""

### 3.5 The forecast horse race
"""
        ),
        code(
            r"""
rows = []
for w in (63, 126, 252, 504):
    b = st.rolling_betas(R, data.MARKET, w, w)
    f = st.forecast_comparison(b)
    if f.empty:
        continue
    for m, r in f.iterrows():
        rows.append({"window": w, "method": m, "rmse": r["rmse"], "mae": r["mae"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(10, 5))
for m, g in d.groupby("method"):
    ax.plot(g["window"], g["rmse"], "o-", lw=2, label=m)
ax.set_xlabel("estimation window (days)"); ax.set_ylabel("out-of-sample RMSE")
ax.legend(fontsize=9)
plt.show()
print(d.pivot(index="window", columns="method", values="rmse").round(4).to_string())
"""
        ),
        md(
            r"""

### 3.6 The optimal weight, and the theoretical prediction
"""
        ),
        code(
            r"""
rows = []
for w in (63, 126, 252, 504):
    b = st.rolling_betas(R, data.MARKET, w, w)
    pp = st.persistence(b)
    oo = st.optimal_shrinkage(b, grid=np.linspace(0, 1.2, 49))
    if pp:
        rows.append({"window": w, "persistence_slope": pp["slope"],
                     "fitted_shrinkage": oo["best_w"],
                     "gap": oo["best_w"] - pp["slope"]})
d = pd.DataFrame(rows).set_index("window")
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(d.index, d["persistence_slope"], "o-", lw=2, color="#1f6feb",
        label="persistence slope (§3.1)")
ax.plot(d.index, d["fitted_shrinkage"], "s-", lw=2, color="#2ea44f",
        label="shrinkage weight that minimises error (§3.5)")
ax.axhline(0.66, color="#f0b429", ls="--", lw=2, label="Blume's constant")
ax.set_xlabel("estimation window (days)"); ax.legend(fontsize=9)
ax.set_title("theory says the blue and green lines should coincide", fontsize=10)
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Two quantities computed by completely different routes — a
> cross-sectional regression and a grid search over prediction error — land close to each
> other. That agreement is worth more than either number alone, because there was no reason for
> a mistake in one to produce a matching mistake in the other.
"""
        ),
        md(
            r"""

### 3.7 The control — a world where beta is nailed down
"""
        ),
        code(
            r"""
rows = []
for drift in (0.0, 0.05, 0.10, 0.20, 0.35, 0.50):
    for idio in (0.15, 0.30, 0.50):
        sim = st.synthetic_panel(n_names=40, n_days=10000, beta_drift=drift,
                                 idio_vol=idio)
        b = st.rolling_betas(sim, "MKT", 252, 252)
        pp = st.persistence(b)
        nn = st.noise_floor(b)
        rows.append({"drift": drift, "idio_vol": idio, "slope": pp["slope"],
                     "noise_share": nn["noise_share"], "true_sd": nn["true_sd"],
                     "observed_sd": nn["observed_sd"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for iv, g in d.groupby("idio_vol"):
    axes[0].plot(g["drift"], g["slope"], "o-", lw=2, label=f"idio vol {iv:.0%}")
    axes[1].plot(g["drift"], g["noise_share"] * 100, "o-", lw=2,
                 label=f"idio vol {iv:.0%}")
axes[0].axhline(st.persistence(betas)["slope"], color="#c0392b", ls="--", lw=2,
                label="the real data")
axes[0].set_xlabel("true beta drift per year"); axes[0].set_ylabel("persistence slope")
axes[0].legend(fontsize=8)
axes[1].axhline(st.noise_floor(betas)["noise_share"] * 100, color="#c0392b", ls="--",
                lw=2, label="the real data")
axes[1].set_xlabel("true beta drift per year")
axes[1].set_ylabel("share of instability that is noise (%)")
axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()
print(d.round(4).to_string(index=False))
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The left edge of both panels is a world where beta is a
> *constant*, exactly. It still shows a persistence slope below one. Blume's regression
> tendency is therefore not, on its own, evidence that betas move — some of it is what happens
> when you regress a noisy measurement on another noisy measurement.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
p = st.persistence(betas)
nf = st.noise_floor(betas)
fc = st.forecast_comparison(betas)
opt = st.optimal_shrinkage(betas)
pb = st.portfolio_betas(R, data.MARKET, data.NAMES, n_per=10, n_ports=20)
pd.DataFrame({
    "persistence slope": [p["slope"]],
    "its standard error": [p["slope_se"]],
    "half-life (years)": [st.half_life(p["slope"])],
    "mean standard error of a beta": [nf["mean_se"]],
    "observed sd of the annual change": [nf["observed_sd"]],
    "of which estimation error": [nf["noise_sd"]],
    "genuine movement": [nf["true_sd"]],
    "share that is noise": [nf["noise_share"]],
    "persistence for 10-stock portfolios": [st.persistence(pb)["slope"]],
    "RMSE, raw estimate": [fc.loc["raw", "rmse"]],
    "RMSE, Blume 0.66": [fc.loc["blume", "rmse"]],
    "RMSE, Vasicek": [fc.loc["vasicek", "rmse"]],
    "RMSE, just assume 1.0": [fc.loc["always_one", "rmse"]],
    "fitted shrinkage weight": [opt["best_w"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Blume (1975) argues the regression tendency is partly economic** — firms' project portfolios
  genuinely mean-revert in risk — rather than purely statistical. §3.7 shows the statistical
  part exists; separating the two properly needs firm-level fundamentals and would be a
  worthwhile extension.
- **Dimson (1979) aggregated coefficients** would correct the non-synchronous trading bias.
  Large caps make it small here, but it would matter on a broader universe and would raise
  measured betas for the least liquid names.
- **Conditional betas.** Lewellen & Nagel (2006) argue the true variation is too small to
  explain pricing anomalies, which is what §3.2 finds from a different direction. Estimating a
  proper conditional model (DCC, or a Kalman filter as in **998**) and comparing its
  out-of-sample RMSE against the flat 1.0 baseline would be the decisive test.
- **The `always_one` baseline deserves wider use.** Any risk model that cannot beat "assume
  everything has a beta of one" on out-of-sample error is not adding information, and the
  comparison costs nothing to run.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
