# Study 904 — Shareholder-Yield + Quality 💰

**Do buybacks pay only when they're *real* — and does a quality screen keep the real ones?**

A raw buyback / shareholder-yield screen (PKW: any firm that cut net shares ≥5% last
year) scoops up every serial repurchaser — including the ones running **dilution
theatre** (buybacks that only mop up option grants, net share count flat) or buying
back stock at rich prices. The pitch: overlay a **quality** screen (QUAL: high ROE,
stable earnings, low leverage) and you keep the *funded, value-accretive* buyers and drop
the theatre — so a **quality-screened shareholder-yield** sleeve should beat both raw
buybacks and the plain market. We race **QSY = PKW + QUAL** against **RAW = PKW** and
against **SPY**, all on monthly total returns, all **excess of cash** (minus BIL), over
the common window 2013-08 → 2026-06 (155 months, QUAL-bound).

*Numbers below are the frozen headline (`docs/results.md`, fingerprint
`6ab3e873ef9c`); the live cells run the fast synthetic control. Short-history /
survivor caveat: QUAL lists 2013-07, so one mostly-bull regime with two drawdowns.*


## 1. The idea in one line

A company can 'return cash to shareholders' by genuinely shrinking its share count with real free cash flow — or it can announce a buyback that barely offsets the stock it prints for executives. A raw buyback screen can't tell the difference; a **quality** overlay (durable ROE, low accruals) is supposed to. If the 'real-buybacks-not-theatre' story is true, the quality-screened sleeve should ride *smoother* than raw buybacks — especially when the market cracks and the theatre gets exposed.

In [1]:
R = {'start': '2013-08', 'end': '2026-06', 'n_months': 155, 'fingerprint': '6ab3e873ef9c', 'qsy_cagr': 12.96, 'qsy_vol': 15.4, 'qsy_sharpe': 0.764, 'qsy_maxdd': -25.1, 'qsy_wealth': 4.83, 'raw_cagr': 12.02, 'raw_vol': 17.0, 'raw_sharpe': 0.657, 'raw_maxdd': -29.3, 'raw_wealth': 4.33, 'spy_cagr': 14.14, 'spy_vol': 14.5, 'spy_sharpe': 0.874, 'spy_maxdd': -23.9, 'spy_wealth': 5.52, 'qr_gap': 0.106, 'qr_diff_bps': 4.94, 'qr_diff_ann': 0.59, 'qr_t1s': 0.55, 'qr_tnw': 0.57, 'qr_ci_lo': -0.013, 'qr_ci_hi': 0.241, 'qr_pneg': 0.04, 'qs_gap': -0.111, 'qs_diff_ann': -0.91, 'qs_diff_bps': -7.62, 'qs_t1s': -0.79, 'qs_tnw': -0.9, 'qs_ci_lo': -0.243, 'qs_ci_hi': 0.013, 'qs_pneg': 0.96, 'rs_gap': -0.217, 'rs_diff_ann': -1.51, 'rs_tnw': -0.79, 'qr_e_gap': 0.163, 'qr_e_diff': 0.92, 'qr_e_t': 1.12, 'qr_e_n': 77, 'qr_l_gap': 0.073, 'qr_l_diff': 0.27, 'qr_l_t': 0.14, 'qr_l_n': 78, 'qs_e_gap': -0.112, 'qs_e_diff': -0.45, 'qs_e_t': -0.55, 'qs_e_n': 77, 'qs_l_gap': -0.117, 'qs_l_diff': -1.37, 'qs_l_t': -0.72, 'qs_l_n': 78, 'qsy_turn': 0.76, 'qsy_drag': 0.3, 'qsy_net': 0.763, 'raw_turn': 0.32, 'raw_drag': 0.1, 'raw_net': 0.657, 'spyd_n': 128, 'spyd_qsy_sh': 0.716, 'spyd_sh': 0.476, 'spyd_gap': 0.24, 'spyd_t': 0.86, 'null_fire': 1, 'null_seed_t': -0.85, 'planted_gap': 20.46, 'planted_t': 168.4, 'cal_years': [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], 'cal_qsy': [-8.1, 34.0, 12.8, 29.8, -15.4, 24.1, 20.0, 15.3], 'cal_raw': [-10.5, 34.1, 8.4, 32.6, -10.2, 17.2, 17.3, 17.9], 'cal_spy': [-4.6, 31.2, 18.3, 28.7, -18.2, 26.2, 24.9, 17.7]}
print('QSY (PKW+QUAL): CAGR %5.2f%%  exSharpe %.3f  maxDD %.1f%%'
      % (R['qsy_cagr'], R['qsy_sharpe'], R['qsy_maxdd']))
print('RAW (PKW)     : CAGR %5.2f%%  exSharpe %.3f  maxDD %.1f%%'
      % (R['raw_cagr'], R['raw_sharpe'], R['raw_maxdd']))
print('SPY           : CAGR %5.2f%%  exSharpe %.3f  maxDD %.1f%%'
      % (R['spy_cagr'], R['spy_sharpe'], R['spy_maxdd']))

QSY (PKW+QUAL): CAGR 12.96%  exSharpe 0.764  maxDD -25.1%
RAW (PKW)     : CAGR 12.02%  exSharpe 0.657  maxDD -29.3%
SPY           : CAGR 14.14%  exSharpe 0.874  maxDD -23.9%


## 2. Where the quality overlay actually helped — the crash tape

The overlay's whole promise is a smoother ride when the market breaks. The cleanest tell is **2020 (COVID)**: raw buyback names carried more junk and fell harder; the quality screen cushioned it. Note the honest twist in **2022** — the rate shock rewarded raw buyback's cheaper value tilt, so the overlay is *not* a free lunch every year:

In [2]:
for yr, q, r, s in zip(R['cal_years'], R['cal_qsy'], R['cal_raw'], R['cal_spy']):
    tag = ''
    if q > r + 3: tag = '  <-- quality overlay cushioned'
    elif r > q + 3: tag = '  <-- raw buyback (value) won'
    print(f'{yr}:  QSY {q:+6.1f}%   RAW {r:+6.1f}%   SPY {s:+6.1f}%{tag}')

2018:  QSY   -8.1%   RAW  -10.5%   SPY   -4.6%
2019:  QSY  +34.0%   RAW  +34.1%   SPY  +31.2%
2020:  QSY  +12.8%   RAW   +8.4%   SPY  +18.3%  <-- quality overlay cushioned
2021:  QSY  +29.8%   RAW  +32.6%   SPY  +28.7%
2022:  QSY  -15.4%   RAW  -10.2%   SPY  -18.2%  <-- raw buyback (value) won
2023:  QSY  +24.1%   RAW  +17.2%   SPY  +26.2%  <-- quality overlay cushioned
2024:  QSY  +20.0%   RAW  +17.3%   SPY  +24.9%
2025:  QSY  +15.3%   RAW  +17.9%   SPY  +17.7%


In **2020** QSY returned **+12.8%** vs raw buyback's **+8.4%**, and over the COVID crash the quality overlay held its worst drawdown to **−25.1%** vs raw buyback's **−29.3%** — a real ~4-point cushion. *But* in the 2022 rate shock raw buyback's value tilt (**−10.2%**) actually beat quality (**−15.4%**). The overlay cleans up the crash, not every down year.

## 3. Is it just luck? A live synthetic control

We plant a real quality-over-raw edge in a seeded toy world (`edge>0`) and check the detector recovers it — and stays *silent* on the null (`edge=0`, no advantage). No network.

In [3]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from sy_quality import data, strategy as st
null = st.synthetic_detect(data.synthetic_world(n_months=150, edge=0.0, seed=904))
planted = st.synthetic_detect(data.synthetic_world(n_months=150, edge=3.0, seed=904))
print('null world   : gap NW t = %+.2f  (should be ~0)' % null['t_nw'])
print('planted world: gap NW t = %+.2f  (should light up)' % planted['t_nw'])

null world   : gap NW t = -0.85  (should be ~0)
planted world: gap NW t = +168.44  (should light up)


## 4. The honest verdict

On the real tape the quality overlay genuinely **improves raw buybacks** — a **-25.1%** vs **-29.3%** shallower crash and a Sharpe gap of **+0.106** (positive in *both* eras, bootstrap 96% positive) — so the 'real buybacks, not dilution theatre' story has real signal in the *right* direction. **But** the edge never clears the bar (HAC *t* = **+0.57**, no single era significant), and — the punchline — **neither buyback sleeve beat plain SPY**: QSY trailed the market by **-0.91 pp/yr** (*t* = -0.90), raw buyback by **-1.51 pp/yr**. **Signal: Weak** (a real but uncertified quality-cleanup of raw buybacks, and no market-beat), **Tradability: Fragile** (cheaply buyable, but a risk-profile tweak, not a bankable premium).