"""Build the two narrative notebooks for Study 101 (Slow-and-Steady).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``slow_and_steady`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=8400, start="1993-01-29", end="2026-06-12", fp="eb1569cc9e97",
    windows=8168, ls_wins=6424, ls_win_rate=78.6, ci_lo=77.7, ci_hi=79.5,
    mean_gap=5.60, median_gap=6.22, hac_t=16.96,
    ls_mean=1.1100, ls_std=0.1587, ls_worst=0.5068, ls_worst_pct=-49.3,
    dca_mean=1.0540, dca_std=0.0850, dca_worst=0.6250, dca_worst_pct=-37.5,
    disp_ratio=0.536,
    syn_neg_win=15.0, syn_pos_win=75.9,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (slow_and_steady/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from slow_and_steady import data, strategy

AS_OF = "2026-06-12"
frame = data.load_real("SPY", mode="total_return").loc[:AS_OF]
close = frame["close"]
race = strategy.rolling_race(close, deploy_months=12, step=1)
s = strategy.win_stats(race)
hac_t = strategy.hac_tstat(race["ls_minus_dca"].to_numpy())
print(f"SPY total return: {len(close):,} rows  {close.index[0].date()} -> {close.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(f"{s['n_windows']:,} rolling windows | lump-sum wins {s['ls_win_rate']*100:.1f}% | mean gap {s['mean_gap']*100:+.2f} cents/$1 | HAC t {hac_t:+.2f}")
print(f"dispersion: LS std {s['ls_std']:.4f} vs DCA std {s['dca_std']:.4f} (ratio {s['dispersion_ratio']:.3f})")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Lowers risk?: Confirmed](https://img.shields.io/badge/Lowers_risk%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# Slow and Steady 💧\n"
            "### Is dollar-cost averaging really safer *and* smarter than investing the lump sum?\n\n"
            + HERO_BADGES +
            "When you come into money — a bonus, an inheritance, a 401(k) rollover — the advice is "
            "almost always *\"don't put it all in at once; spread it in over a year.\"* We take that "
            "literally on 30+ years of SPY and ask the only two questions that matter: does drip-feeding "
            "**lower your risk** (yes), and does it **beat going all-in** (no — by a mile).\n\n"
            "> 📓 **This is the plain-language layer.** The win-rate confidence interval, the overlap-"
            "corrected *t*-stat and the exposure-vs-timing maths are in "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below "
            "is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Does DCA beat investing it all at once? | **No** — across **{R['windows']:,}** rolling "
            f"12-month windows the lump sum finishes richer **{R['ls_win_rate']}%** of the time. |\n"
            f"| By how much? | **+{R['mean_gap']:.1f} cents on every dollar**, on average. |\n"
            f"| Does DCA lower your risk? | **Yes** — its range of outcomes is about **half** as wide "
            f"(spread {R['dca_std']:.3f} vs {R['ls_std']:.3f}), and its worst year loses "
            f"**{R['dca_worst_pct']}%** vs **{R['ls_worst_pct']}%**. |\n"
            f"| So what *is* DCA? | A way to take **less risk** by staying **less invested** — not a "
            f"way to make more money. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Don't invest a windfall all at once. Dollar-cost average it in — buy a fixed amount each "
            "month for a year. You'll buy at a lower average price, you'll lower your risk, and you'll "
            "come out ahead of going all-in.\"* It's the default advice of almost every personal-finance "
            "column and robo-advisor."
        ),
        md(
            "## 2 · So what?\n\n"
            "Trillions of dollars move on this rule — every rollover, every bonus, every inheritance. If "
            "spreading-in really beat lump-summing, you'd be leaving free money on the table by going "
            "all-in. So it deserves a fair, literal test on real data — not a chart cherry-picked to a "
            "crash."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "For **every** day in 30+ years of SPY (dividends included), we run two \\$1 plans starting "
            "that day: **lump-sum** (all in today) and **DCA** (12 equal monthly buys over the next "
            "year, the waiting cash earning 0% — which actually *helps* DCA's case). We value both at "
            "the **same** end date and see who's richer. If DCA were smarter, it would win most of the "
            "time. It doesn't."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, **who finishes richer?** A histogram of "
           "the lump-sum-minus-DCA gap across every window — bars to the right of zero are windows the "
           "lump sum won."),
        code(
            "gap = race['ls_minus_dca'].to_numpy() * 100  # cents per $1\n"
            "ls_wins = (gap > 0).mean() * 100\n"
            "plt.hist(gap, bins=60, alpha=.85)\n"
            "plt.axvline(0, color='k', lw=1)\n"
            "plt.axvline(gap.mean(), color='C3', lw=2, label=f'mean = {gap.mean():+.1f} cents/$1')\n"
            "plt.xlabel('lump-sum minus DCA, terminal wealth (cents per $1)')\n"
            "plt.ylabel('number of windows')\n"
            "plt.title(f'Lump-sum finishes richer on {ls_wins:.0f}% of windows')\n"
            "plt.legend(); plt.show()\n"
            "print(f'lump-sum wins {ls_wins:.1f}% of {len(gap):,} windows')"
        ),
        md(
            f"The mass sits firmly to the **right** of zero: the lump sum wins **{R['ls_win_rate']}%** of "
            "windows. DCA only wins the windows on the left — the ones where the market *fell* over the "
            "deployment year, so buying in slowly happened to buy cheaper."
        ),
        md("Now the **risk** angle — the thing DCA really does buy. Here are the two arms' terminal-"
           "wealth distributions side by side."),
        code(
            "fig, ax = plt.subplots(figsize=(10,5))\n"
            "ax.hist(race['lump_sum'], bins=60, alpha=.6, label=f\"lump-sum (spread {race['lump_sum'].std():.3f})\")\n"
            "ax.hist(race['dca'], bins=60, alpha=.6, label=f\"DCA (spread {race['dca'].std():.3f})\")\n"
            "ax.axvline(1.0, color='k', lw=1, ls=':')\n"
            "ax.set_xlabel('terminal wealth of $1 after the deployment window')\n"
            "ax.set_ylabel('number of windows'); ax.legend()\n"
            "ax.set_title('DCA outcomes are tighter -- but centred lower'); plt.show()\n"
            "print(f\"worst window: lump-sum {race['lump_sum'].min():.3f}  DCA {race['dca'].min():.3f}\")"
        ),
        md(
            f"DCA's bell is **narrower** (spread {R['dca_std']:.3f} vs {R['ls_std']:.3f}) and its worst "
            f"case is shallower ({R['dca_worst_pct']}% vs {R['ls_worst_pct']}%) — that's the real risk "
            "reduction. But the whole curve is shifted **left**: you paid for the calmer ride with "
            "return."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Lowers risk? → Confirmed.** DCA's outcome spread is little over half the lump sum's "
            f"(ratio {R['disp_ratio']}), worst case {R['dca_worst_pct']}% vs {R['ls_worst_pct']}%.\n"
            f"- **Beats a lump sum? → No (Signal: None).** The lump sum wins **{R['ls_win_rate']}%** of "
            f"windows by **+{R['mean_gap']:.1f} cents/\\$1** — overwhelming, not noise.\n"
            f"- **The *smarter* way to invest? → Mirage.** The only thing DCA buys is lower exposure to "
            "the very returns it then misses out on."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "There's nothing to *trade* — it's a deployment schedule, not a strategy. And as a schedule "
            "it loses: the lump sum's average win of **+5.6 cents on the dollar** is exactly the equity "
            "premium your idle cash forfeits while it \"averages in.\" If you genuinely want the calmer "
            "ride, deploy the lump sum and just hold a **smaller stock weight** — same lower risk, no "
            "opportunity cost on cash that's sitting out."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Let the waiting cash earn the **T-bill** instead of 0%. It shrinks the gap a little — but "
            "DCA still loses, because the equity premium beats the bill on average.\n"
            "- Vary the deployment horizon (6, 24 months): does a *longer* drip lose by *more*?\n"
            "- The real DCA most people do is *involuntary* (a paycheck each month) — that's a savings "
            "rate, not a lump-vs-DCA choice. Fork it and separate the two."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# Slow and Steady — a quantitative teardown 🔬\n"
            "### Real total-return tape · 8,168 rolling windows · Wilson CI · overlap-corrected HAC *t* · exposure-vs-timing\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We separate the two things DCA "
            "does — **reduce dispersion** (real) and **beat the lump sum** (it doesn't) — and show the "
            "risk reduction is lower exposure, not better timing.\n\n"
            "> ⚠️ **Not investment advice.** SPY daily, total-return adjusted (`quantlab.data`, Yahoo); "
            "12 equal monthly tranches; waiting cash earns 0% (conservative-to-DCA). Sources in "
            "[`docs/references.md`](../docs/references.md), reproducible run in "
            "[`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** (DCA beats lump sum?) | `NONE` | Lump-sum wins **{R['ls_win_rate']}%** of "
            f"**{R['windows']:,}** windows (Wilson CI {R['ci_lo']}-{R['ci_hi']}%); mean gap "
            f"**+{R['mean_gap']:.1f} cents/\\$1**, HAC *t* = **+{R['hac_t']:.1f}** on the overlapping "
            f"series. DCA loses, decisively. |\n"
            f"| **Tradability** (smarter way?) | `MIRAGE` | The +{R['mean_gap']:.1f}-cent loss *is* the "
            f"forgone equity premium on idle cash; the only benefit (lower dispersion) is reproducible "
            f"more cheaply with a lower stock weight. |\n"
            f"| **Lowers risk?** | `CONFIRMED` | dispersion ratio **{R['disp_ratio']}** (DCA std "
            f"{R['dca_std']:.3f} vs LS {R['ls_std']:.3f}); worst window {R['dca_worst_pct']}% vs "
            f"{R['ls_worst_pct']}%. |\n\n"
            "> 💡 **In plain words:** DCA is a *risk reducer that works* wearing the costume of a "
            "*return booster that doesn't*."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (risk):** DCA lowers the dispersion / worst-case of terminal wealth vs a lump sum.\n"
            "- **H₂ (the sold claim):** DCA beats the lump sum on terminal wealth (\"buy at a lower "
            "average price\").\n"
            "- **H₃ (mechanism):** if H₁ holds and H₂ fails, the risk reduction is just lower average "
            "exposure, not timing skill.\n\n"
            "We find H₁ true, H₂ false, and H₃ the explanation — exactly the Vanguard / Constantinides "
            "result on a fresh tape."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₂ held, every all-in investor would be "
           "leaving free return behind. It doesn't — and seeing *why* (the opportunity cost of un-"
           "deployed cash) is the lesson, and it's the same alpha-vs-beta confusion the desk meets "
           "everywhere."),
        md("## 3 · How we'd know — the protocol\n\nRolling-window race over every start date · win-rate "
           "with a Wilson interval · HAC *t* on the (heavily overlapping) gap series · dispersion ratio "
           "and worst-case for the risk read · exposure decomposition for the mechanism."),
        md("## 4 · The teardown\n\nHeadline win-rate, with a Wilson interval on the proportion:"),
        code(
            "p, lo, hi = strategy.wilson_ci(s['ls_wins'], s['n_windows'])\n"
            "print(f\"lump-sum wins {s['ls_wins']:,}/{s['n_windows']:,} = {p*100:.1f}%  \"\n"
            "      f\"(Wilson 95% CI {lo*100:.1f}-{hi*100:.1f}%)\")\n"
            "print(f\"mean gap {s['mean_gap']*100:+.2f} cents/$1   median gap {s['median_gap']*100:+.2f} cents/$1\")"
        ),
        md("**HAC inference** on the gap series. The windows overlap by ~a full year, so the gaps are "
           "massively autocorrelated and a naive *t* would be absurd — Newey-West with a long lag is the "
           "honest read:"),
        code(
            "g = race['ls_minus_dca'].to_numpy()\n"
            "naive_t = g.mean() / (g.std(ddof=1) / np.sqrt(len(g)))\n"
            "hac = strategy.hac_tstat(g)\n"
            "print(f'mean gap = {g.mean()*100:+.3f} cents/$1')\n"
            "print(f'naive t (ignores overlap) = {naive_t:+.1f}   <- inflated, do not trust')\n"
            "print(f'HAC t   (overlap-robust)  = {hac:+.1f}   <- still overwhelmingly positive')"
        ),
        md(
            "> 💡 **In plain words:** even after honestly discounting the fact that neighbouring windows "
            "are almost the same window, the lump sum's edge is far too large to be luck."
        ),
        md("**Win-rate by deployment horizon** — does drip-feeding *longer* lose by more? (The longer "
           "you sit in cash, the more premium you forgo.)"),
        code(
            "rows = []\n"
            "for m in [6, 12, 18, 24, 36]:\n"
            "    rr = strategy.rolling_race(close, deploy_months=m, step=5)\n"
            "    ss = strategy.win_stats(rr)\n"
            "    rows.append((m, ss['ls_win_rate']*100, ss['mean_gap']*100, ss['dispersion_ratio']))\n"
            "hz = pd.DataFrame(rows, columns=['deploy_months','LS win %','mean gap (cents/$1)','disp ratio']).set_index('deploy_months')\n"
            "fig, ax = plt.subplots(figsize=(9,4.5))\n"
            "ax.plot(hz.index, hz['LS win %'], marker='o')\n"
            "ax.axhline(50, color='k', ls=':', lw=1)\n"
            "ax.set_xlabel('deployment horizon (months)'); ax.set_ylabel('lump-sum win-rate (%)')\n"
            "ax.set_title('The longer you average in, the more the lump sum wins'); plt.show()\n"
            "hz.round(2)"
        ),
        md(
            "> 💡 **In plain words:** stretching the drip-feed only makes it worse — more time in cash is "
            "more premium left on the table."
        ),
        md("**The risk read** — dispersion and worst case, the part that's genuinely DCA's:"),
        code(
            "print(f\"terminal-wealth std : lump-sum {s['ls_std']:.4f}  DCA {s['dca_std']:.4f}  (ratio {s['dispersion_ratio']:.3f})\")\n"
            "print(f\"worst window        : lump-sum {s['ls_worst']:.4f}  DCA {s['dca_worst']:.4f}\")\n"
            "print('=> DCA genuinely narrows the spread and cushions the worst case --')\n"
            "print('   but only by holding ~half its capital out of the market during the year.')"
        ),
        md(
            "> 💡 **In plain words:** the smoother ride is real, but it's *less exposure*, not *better "
            "timing* — and you can get less exposure for free by just holding less stock."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `NONE` (lump-sum wins {R['ls_win_rate']}%, Wilson {R['ci_lo']}-{R['ci_hi']}%, mean "
            f"gap +{R['mean_gap']:.1f} cents/\\$1, HAC *t* +{R['hac_t']:.1f}); Tradability `MIRAGE` (the "
            f"gap is the forgone premium); Lowers risk? `CONFIRMED` (dispersion ratio {R['disp_ratio']}, "
            f"worst {R['dca_worst_pct']}% vs {R['ls_worst_pct']}%). DCA's benefit is exposure, not skill."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Nothing to trade — it's a deployment policy, and the policy loses. The binding fact is "
            "economic: DCA holds, on average, only ~half its capital invested during the deployment "
            "year, so it forfeits ~half a year of the equity premium — which is precisely the +5.6-cent "
            "gap. A risk-averse investor reproduces the lower dispersion with a static lower stock "
            "weight and zero cash drag. Constantinides (1979) makes the sub-optimality formal."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Replace 0% cash with the **T-bill** (`^IRX`) and recompute excess-of-cash for both arms; "
            "the gap narrows but does not flip.\n"
            "- Block-bootstrap the **win-rate** (not just the gap) for a CI that respects the overlap "
            "beyond Wilson's i.i.d. assumption.\n"
            "- Cross-asset: on a fat-left-tail asset (EM, credit) does DCA's worst-case cushion become "
            "worth its return cost?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
