"""Notebook builder for Study 986 — The Rolling Ladder.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Rolling Ladder \U0001FA9C
### A bond fund yielding 4% will not give you 4%. Here is how long it takes to find out.

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Hold a ten-year Treasury to maturity and you earn what you were promised. Hold a ten-year
Treasury *fund* and you do not — because the fund never matures. It sells each bond as it ages
and buys a new one, forever.

> \U0001F4D3 **This is the plain-language layer.** The bond arithmetic, the crossover grid and
> the error decomposition are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does a bond held to maturity earn its yield? | Yes, essentially exactly. |
| Does a bond *fund* with the same yield? | Only after about a duration's worth of years. |
| Is the fund worse? | No. It is slower to be right. |
| Does that matter? | Enormously, if your horizon is shorter than the duration. |
"""
        ),
        md(
            r"""

## 1 · Two instruments that look identical

Both hold ten-year Treasuries. Both yield 4%. One of them matures.
"""
        ),
        code(
            r"""
from ladder import data, strategy as st

px = data.load_prices()
y10 = (px[data.YIELD_10Y] / 1000.0).dropna()      # ^TNX prints 10x the percent yield
print(f"as-of {data.AS_OF} | 10y yield {y10.min():.2%} to {y10.max():.2%}, "
      f"last {y10.iloc[-1]:.2%}")
print(f"a 10-year 4% bond: Macaulay duration {st.macaulay_duration(0.04, 10):.2f}y, "
      f"modified {st.modified_duration(0.04, 10):.2f}")
"""
        ),
        md(
            r"""

## 2 · The experiment

Same interest rates for both. A bond bought at 4% and held for ten years, against a fund that
keeps buying ten-year bonds forever. Rates rise two percentage points after the first year.
"""
        ),
        code(
            r"""
w = st.synthetic_world(n_years=30, shock_bp=200, maturity=10.0)
c = w["comparison"]
yrs = np.arange(len(c)) / 252
fig, axes = plt.subplots(2, 1, figsize=(11, 8), sharex=True,
                         gridspec_kw={"height_ratios": [3, 1]})
axes[0].plot(yrs, (c["bond_value"] - 1) * 100, lw=2, color="#1f6feb",
             label="a 10-year bond, held to maturity")
axes[0].plot(yrs, (c["fund_value"] - 1) * 100, lw=2, color="#c0392b",
             label="a 10-year bond FUND")
axes[0].axvline(1, color="#8b949e", ls="--", lw=1, label="rates rise 2%")
axes[0].set_ylabel("cumulative return (%)"); axes[0].legend()
axes[1].plot(yrs, c["rate"] * 100, lw=1.5, color="k")
axes[1].set_ylabel("yield (%)"); axes[1].set_xlabel("years")
plt.show()
x = st.crossover_horizon(w["rates"], 10.0)
print(f"the fund falls {abs(x['initial_gap']):.1%} behind, and catches up after "
      f"{x['crossover_years']:.1f} years")
print(f"the bond's modified duration at the start was {w['duration']:.2f}")
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Those two numbers — the crossover horizon and the duration —
> are not a coincidence. This is Redington's 1952 immunisation theorem arriving from the other
> direction, and the grid in notebook 2 checks it across every maturity and shock size.
"""
        ),
        md(
            r"""

## 3 · Why the fund falls behind, and why it comes back

**Behind, immediately:** rates rose, so every bond it owns is worth less. The bond you hold
directly lost the same amount — but you know it redeems at 100, so you can ignore the quote.
The fund has no such promise.

**Back, eventually:** every bond the fund buys from now on is bought at the new, higher yield.
The extra income accumulates. Given enough years it exactly repays the price loss — and "enough
years" is the duration.
"""
        ),
        code(
            r"""
rows = []
for m in (2.0, 5.0, 10.0, 20.0, 30.0):
    rates = st.rate_path("shock", n=int(45 * 252), start=0.04, end=0.06, shock_at=252)
    x = st.crossover_horizon(rates, m)
    rows.append({"maturity": m, "duration": st.modified_duration(0.04, m, 0.04),
                 "crossover": x["crossover_years"], "initial gap": x["initial_gap"]})
    rows[-1]["converges after"] = st.convergence_horizon(
        st.rate_path("ramp", n=int(120 * 252), start=0.04, end=0.10), m,
        tol=0.0005)["convergence_years"]
d = pd.DataFrame(rows).set_index("maturity")
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(d["duration"], d["converges after"], "o-", lw=2, color="#2ea44f",
        label="years until the fund delivers its purchase yield")
lim = [0, max(d["duration"].max(), d["converges after"].max()) * 1.1]
ax.plot(lim, lim, "k--", lw=1.5, label="= duration")
ax.set_xlabel("modified duration (years)"); ax.set_ylabel("years"); ax.legend(fontsize=9)
plt.show()
d.round(2)
"""
        ),
        md(
            r"""

## 4 · On the real tape
"""
        ),
        code(
            r"""
for tk in (data.SHORT, data.INTERMEDIATE, data.LONG):
    dur = st.FUND_DURATION[tk]
    conv = st.convergence_by_horizon(px[tk].dropna(), y10, dur)
    if conv.empty:
        continue
    print(f"\n{tk} (duration {dur:.1f} years)")
    print(conv[["n", "mean_promised", "mean_realised", "mean_error", "sd_error",
                "share_within_1pp"]].round(4).to_string())
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Confirmed.** A bond's starting yield is its return; a fund's is a forecast. Over 203 rolling 7.5-year windows — a horizon equal to IEF's own duration, where immunisation theory says the error should have washed out — the realised annualised return missed the starting yield by **+3.46% on average with a standard deviation of 2.32%**, and only 21% of windows landed within a percentage point of what was on offer. The mechanism checks out: regressing the error on **−duration × Δyield ⁄ horizon** gives a slope of 13.34 with R² **91%**, so the shortfall is the refusal to mature and essentially nothing else. At one year the error's standard deviation is 6.4%; it falls to 1.9% at ten years — shrinking, but nothing like a bond's, which is zero at maturity by construction.

**Tradability: Useful.** In the controlled experiment — one rate path, a 10-year bond held to maturity against a 10-year constant-maturity fund, a 200 bp rise a year in — the fund fell 0.5% behind and took **5.6 years** to catch the bond, against a starting duration of 8.2. On a steadily trending rate path the fund's annualised return crossed back through its purchase yield after **11.1 years** — against Leibowitz, Bova & Kogelman's 2D − 1 = 15.4, and *below* it because the fund's duration shrinks as yields rise, so the cumulative price loss is smaller than D₀ × Δy. That is the practical content: the fund is not worse, it is *slower to be right*, and the delay is set by its duration. An investor whose horizon comfortably exceeds it is close to indifferent; one whose horizon is shorter is holding a rate bet they may not know they have taken.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Match your duration to your horizon.** That is the whole practical lesson, and it is a
  hundred years old.
- **Individual bonds or a defined-maturity ETF** (the iBonds and BulletShares ranges) restore
  the pull to par, at the cost of a much less liquid instrument.
- **The curve, not the yield.** This study collapses the whole term structure to one number; a
  steepening and a parallel shift have different consequences and it cannot tell them apart.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Rolling Ladder — a quantitative teardown \U0001F52C
### Duration arithmetic · a one-path controlled experiment · immunisation, measured

![Signal: Confirmed](https://img.shields.io/badge/Signal-Confirmed-2ea44f?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Both instruments
are simulated on the *same* rate path, so every difference between them is the roll — and the
crossover horizon turns out to be Redington's 1952 immunisation theorem seen from the other side.

> ⚠️ **Not investment advice.** Fund closes and the 10-year yield pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from ladder import data, strategy as st

px = data.load_prices()
y10 = (px[data.YIELD_10Y] / 1000.0).dropna()      # ^TNX prints 10x the percent yield
print(f"as-of {data.AS_OF} | 10y yield {y10.min():.2%} to {y10.max():.2%}, "
      f"last {y10.iloc[-1]:.2%}")
print(f"a 10-year 4% bond: Macaulay duration {st.macaulay_duration(0.04, 10):.2f}y, "
      f"modified {st.modified_duration(0.04, 10):.2f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Confirmed | A bond's starting yield is its return; a fund's is a forecast. Over 203 rolling 7.5-year windows — a horizon equal to IEF's own duration, where immunisation theory says the error should have washed out — the realised annualised return missed the starting yield by **+3.46% on average with a standard deviation of 2.32%**, and only 21% of windows landed within a percentage point of what was on offer. The mechanism checks out: regressing the error on **−duration × Δyield ⁄ horizon** gives a slope of 13.34 with R² **91%**, so the shortfall is the refusal to mature and essentially nothing else. At one year the error's standard deviation is 6.4%; it falls to 1.9% at ten years — shrinking, but nothing like a bond's, which is zero at maturity by construction. |
| **Tradability** | Useful | In the controlled experiment — one rate path, a 10-year bond held to maturity against a 10-year constant-maturity fund, a 200 bp rise a year in — the fund fell 0.5% behind and took **5.6 years** to catch the bond, against a starting duration of 8.2. On a steadily trending rate path the fund's annualised return crossed back through its purchase yield after **11.1 years** — against Leibowitz, Bova & Kogelman's 2D − 1 = 15.4, and *below* it because the fund's duration shrinks as yields rise, so the cumulative price loss is smaller than D₀ × Δy. That is the practical content: the fund is not worse, it is *slower to be right*, and the delay is set by its duration. An investor whose horizon comfortably exceeds it is close to indifferent; one whose horizon is shorter is holding a rate bet they may not know they have taken. |

> \U0001F4A1 **In plain words.** Duration is not just a risk number. It is also a *clock*: it
> tells you how long the fund takes to deliver what it advertised.
"""
        ),
        md(
            r"""

## 1 · The arithmetic, checked against its own identities
"""
        ),
        code(
            r"""
rows = []
for m in (1, 2, 5, 10, 20, 30):
    rows.append({"maturity": m, "macaulay": st.macaulay_duration(0.04, float(m)),
                 "modified": st.modified_duration(0.04, float(m)),
                 "price at 6%": st.price_from_yield(0.06, float(m), 0.04),
                 "price at 2%": st.price_from_yield(0.02, float(m), 0.04)})
print(pd.DataFrame(rows).set_index("maturity").round(3).to_string())
# The two identities the module is unit-tested against, restated here as a visible check.
print("\na par bond prices at par:      ", round(st.price_from_yield(0.04, 10, 0.04), 10))
print("a zero's duration is its maturity:",
      round(st.macaulay_duration(0.04, 10.0, coupon=0.0, freq=1), 10))
"""
        ),
        md(
            r"""

## 2 · Hypotheses

- **H₁.** A bond held to maturity realises its purchase yield, whatever the path.
- **H₂.** A constant-maturity fund does not, and the error equals −duration × Δy, annualised.
- **H₃ (immunisation).** The horizon at which the fund catches the bond after a shock is the
  duration.
- **H₄.** On the real tape, the regression of realised error on −D·Δy⁄h has slope 1 and a high
  R² — meaning there is no *second* effect to explain.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The bond does what it promises, on every path
"""
        ),
        code(
            r"""
rows = []
for kind in ("flat", "shock", "ramp", "roundtrip"):
    rates = st.rate_path(kind, n=int(10 * 252), start=0.04, end=0.08)
    b = st.simulate_bond(rates, 10.0)
    cagr = (b["value"].iloc[-1] / b["value"].iloc[0]) ** 0.1 - 1
    rows.append({"path": kind, "start rate": rates[0], "end rate": rates[-1],
                 "realised CAGR": cagr, "error vs promise": cagr - rates[0]})
print(pd.DataFrame(rows).set_index("path").round(5).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Whatever rates did, the bond delivered its purchase yield to
> within a few basis points. The residual is coupon reinvestment — which is the one caveat on
> "hold to maturity and you earn the yield".
"""
        ),
        md(
            r"""

### 3.2 The controlled experiment, both instruments, one path
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(2, 2, figsize=(13, 8))
for ax, kind, end in zip(axes.ravel(), ("shock", "shock", "ramp", "roundtrip"),
                         (0.06, 0.02, 0.08, 0.08)):
    rates = st.rate_path(kind, n=int(30 * 252), start=0.04, end=end, shock_at=252)
    c = st.compare(rates, 10.0)
    yrs = np.arange(len(c)) / 252
    ax.plot(yrs, (c["bond_value"] - 1) * 100, lw=1.8, color="#1f6feb", label="bond")
    ax.plot(yrs, (c["fund_value"] - 1) * 100, lw=1.8, color="#c0392b", label="fund")
    x = st.crossover_horizon(rates, 10.0)
    if np.isfinite(x["crossover_years"]):
        ax.axvline(x["crossover_years"], color="#2ea44f", ls="--", lw=1.5,
                   label=f"crossover {x['crossover_years']:.1f}y")
    ax.set_title(f"{kind}: 4% -> {end:.0%}", fontsize=10)
    ax.set_xlabel("years"); ax.set_ylabel("cumulative (%)"); ax.legend(fontsize=7)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 3.3 Convergence against duration — the immunisation check

Two related numbers, and it is worth keeping them apart.

**Crossover** is when the fund's cumulative return catches the bond's. It is the intuitive
picture, and it is only well defined inside the bond's life: after redemption you are comparing
the fund to whatever you assume the proceeds bought.

**Convergence** is when the fund's own annualised return crosses back through the yield it was
bought at. That is the quantity with a theorem behind it — Leibowitz, Bova & Kogelman (2014) put
it at roughly **2D − 1** years for a fixed duration.
"""
        ),
        code(
            r"""
rows = []
for m in (2.0, 3.0, 5.0, 7.0, 10.0, 15.0, 20.0, 30.0):
    for bp in (-200, -100, -50, 50, 100, 200):
        rates = st.rate_path("shock", n=int(60 * 252), start=0.04, end=0.04 + bp / 1e4,
                             shock_at=252)
        x = st.crossover_horizon(rates, m)
        rows.append({"maturity": m, "shock_bp": bp,
                     "duration": st.modified_duration(0.04, m, 0.04),
                     "crossover": x["crossover_years"], "initial_gap": x["initial_gap"]})
d = pd.DataFrame(rows)
print(f"{d['crossover'].notna().sum()} of {len(d)} shocks cross inside the bond's life")
d = d.dropna(subset=["crossover"])
fig, ax = plt.subplots(figsize=(9, 6))
for bp, sl in d.groupby("shock_bp"):
    ax.plot(sl["duration"], sl["crossover"], "o-", lw=1.2, ms=4, label=f"{bp:+d} bp")
lim = [0, d["duration"].max() * 1.15]
ax.plot(lim, lim, "k--", lw=2, label="crossover = duration")
ax.set_xlabel("modified duration (years)"); ax.set_ylabel("crossover horizon (years)")
ax.legend(fontsize=8)
plt.show()
print(f"mean crossover / duration: {(d['crossover'] / d['duration']).mean():.2f}")
d.round(2).to_string(index=False)
"""
        ),
        code(
            r"""
ramp = st.rate_path("ramp", n=int(120 * 252), start=0.04, end=0.10)
rows = []
for m in (2.0, 3.0, 5.0, 7.0, 10.0, 15.0, 20.0, 30.0):
    c = st.convergence_horizon(ramp, m, tol=0.0005)
    rows.append({"maturity": m, "duration": c["duration"],
                 "convergence": c["convergence_years"],
                 "leibowitz 2D-1": c["leibowitz_2d_minus_1"]})
d = pd.DataFrame(rows).set_index("maturity")
fig, ax = plt.subplots(figsize=(9, 6))
ax.plot(d["duration"], d["convergence"], "o-", lw=2, color="#2ea44f", label="measured")
ax.plot(d["duration"], d["leibowitz 2D-1"], "s--", lw=1.6, color="#c0392b",
        label="Leibowitz 2D - 1 (fixed duration)")
ax.plot(d["duration"], d["duration"], "k:", lw=1.5, label="= duration")
ax.set_xlabel("modified duration (years)")
ax.set_ylabel("years until the fund delivers its purchase yield")
ax.legend(fontsize=8)
plt.show()
d["ratio to duration"] = d["convergence"] / d["duration"]
d.round(2)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The green line sits below the red one, consistently. Leibowitz's
> bound assumes the fund's duration stays put; in reality it **shrinks as yields rise**, so the
> cumulative price loss is smaller than D₀ × Δy and the fund gets back to its purchase yield
> sooner than the fixed-duration algebra predicts. Convexity, quietly helping.
"""
        ),
        md(
            r"""

### 3.4 On the tape: promised versus delivered
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
for ax, tk in zip(axes, (data.SHORT, data.INTERMEDIATE, data.LONG)):
    dur = st.FUND_DURATION[tk]
    t = st.realised_vs_promised(px[tk].dropna(), y10, horizon_y=max(dur / 2, 1.0), duration=dur)
    if t.empty:
        continue
    ax.scatter(t["promised"] * 100, t["realised"] * 100, s=14, alpha=0.4, color="#2ea44f")
    lim = [min(t["promised"].min(), t["realised"].min()) * 100 - 1,
           max(t["promised"].max(), t["realised"].max()) * 100 + 1]
    ax.plot(lim, lim, "k--", lw=1.5)
    ax.set_xlabel("yield when you bought (%)"); ax.set_ylabel("annualised return (%)")
    ax.set_title(f"{tk}, {max(dur / 2, 1.0):.1f}y windows", fontsize=10)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** A bond's version of this chart would be points sitting on the
> diagonal. These are not on the diagonal, and the vertical scatter is the rate move you did not
> know about when you bought.
"""
        ),
        md(
            r"""

### 3.5 The decomposition — is anything else going on?
"""
        ),
        code(
            r"""
rows = []
for tk in (data.SHORT, data.INTERMEDIATE, data.LONG, data.CORPORATE):
    dur = st.FUND_DURATION[tk]
    for hy in (1, 2, 3, 5, 7, 10):
        t = st.realised_vs_promised(px[tk].dropna(), y10, float(hy), dur)
        if len(t) < 30:
            continue
        dd = st.error_decomposition(t, dur, float(hy))
        rows.append({"fund": tk, "horizon": hy, "slope": dd["slope"], "r2": dd["r2"],
                     "sd_error": dd["sd_error"], "n": dd["n"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d.pivot(index="horizon", columns="fund", values="r2").plot(ax=axes[0], marker="o")
axes[0].set_ylabel("R2 of the duration explanation"); axes[0].set_ylim(0, 1)
axes[0].legend(fontsize=8, title="")
d.pivot(index="horizon", columns="fund", values="sd_error").mul(100).plot(ax=axes[1],
                                                                          marker="o")
axes[1].set_ylabel("sd of the annualised error (%)"); axes[1].legend(fontsize=8, title="")
axes[1].set_title("shrinking with horizon — but never to zero")
plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

### 3.6 What each fund actually delivered over its life
"""
        ),
        code(
            r"""
rows = []
for tk in (data.SHORT, data.INTERMEDIATE, data.LONG, data.CORPORATE):
    s = px[tk].dropna()
    r = s.pct_change().dropna()
    yrs = len(r) / 252
    cagr = (s.iloc[-1] / s.iloc[0]) ** (1 / yrs) - 1
    y0 = float(y10.reindex(s.index).ffill().iloc[0])
    rows.append({"fund": tk, "duration": st.FUND_DURATION[tk], "years": yrs,
                 "started at": y0, "delivered": cagr, "gap": cagr - y0,
                 "vol": r.std() * np.sqrt(252),
                 "maxDD": ((1 + r).cumprod() / (1 + r).cumprod().cummax() - 1).min()})
print(pd.DataFrame(rows).set_index("fund").round(4).to_string())
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
w = st.synthetic_world(n_years=30, shock_bp=200, maturity=10.0)
x = st.crossover_horizon(w["rates"], 10.0)
dur = st.FUND_DURATION[data.INTERMEDIATE]
conv = st.convergence_by_horizon(px[data.INTERMEDIATE].dropna(), y10, dur)
t = st.realised_vs_promised(px[data.INTERMEDIATE].dropna(), y10, 7.0, dur)
dd = st.error_decomposition(t, dur, 7.0)
cv = st.convergence_horizon(st.rate_path("ramp", n=int(120 * 252), start=0.04, end=0.10),
                            10.0, tol=0.0005)
pd.DataFrame({
    "modified duration (10y bond)": [w["duration"]],
    "crossover after a 200bp rise": [x["crossover_years"]],
    "convergence to purchase yield": [cv["convergence_years"]],
    "Leibowitz 2D-1": [cv["leibowitz_2d_minus_1"]],
    "initial shortfall": [x["initial_gap"]],
    "IEF sd of 1y error": [conv.loc[1, "sd_error"] if 1 in conv.index else np.nan],
    "IEF sd of 10y error": [conv.loc[10, "sd_error"] if 10 in conv.index else np.nan],
    "duration explanation slope": [dd.get("slope", np.nan)],
    "duration explanation R2": [dd.get("r2", np.nan)],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Why the measured convergence sits below 2D − 1.** Section 3.3 shows it does, and attributes
  the gap to the fund's duration shrinking as yields rise. Deriving the corrected bound
  analytically — Leibowitz's algebra with a yield-dependent duration — is the obvious next step
  and would turn an observation into a result.
- **A real curve.** Every result here uses a single flat yield. A steepening and a parallel
  shift of equal size do different things to a rolling fund, and this cannot tell them apart.
- **Roll costs and fees.** The simulated fund trades for free. A real one pays a spread on every
  roll plus an expense ratio, both of which push the crossover out.
- **Defined-maturity ETFs** (iBonds, BulletShares) restore the pull to par inside a fund
  wrapper, and are the natural control group this study lacks.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
