# Study 928 — Odd-Lot Priority

**The odd-lot holder is filled first and in full. Is that a real retail-only edge?**

Almost every US issuer self-tender carries an **odd-lot priority** clause: tender fewer
than 100 shares — all of them — and you are bought *first and in full*, ahead of the
proration that hits every round-lot holder. The forum conclusion writes itself: buy 99
shares, tender, collect the premium.

We test it on the **same 178 modified-Dutch-auction self-tenders** as Study 927
(2010-01-28 → 2025-11-21, 167 fully covered windows, 128 of
129 issuer tapes recoverable, plus **SPY** and **BIL**), daily total-return
closes. The offer is public at the close of day *t*; the odd lot is bought at the close of
*t+1* — the study's **one** execution lag.

*The clearing price of a tender is not in a price series.* Four inputs are declared
**assumptions** and swept end to end: the clearing premium (13% over the
pre-announcement close), the offer length (21 trading days), the round-lot
proration fill (0.35) and the flat broker corporate-action fee
($30 on a $5,000 lot). Everything else is tape — and where a
number below leans on an assumption, this notebook says so rather than letting the *t*
speak for the tape.

*Numbers below are the frozen headline (`docs/results.md`, Fingerprint `4f4dc9efc748`); the
live cells run the offline synthetic control. As-of 2026-06-30.*


## 1. The trade, as the forums tell it

A company offers to buy back its own shares at a premium. If everyone tenders, each holder is cut back *pro rata* — you offer 1,000 shares and they take 350. But the fine print says a holder of **fewer than 100 shares** who tenders all of them is bought **first and in full**. So: buy 99 shares the morning after the announcement, tender them, take the premium. Free money — allegedly.

## 2. The first problem: you are not the first buyer

The offer is public at the close of the announcement day. The earliest an outside buyer can act is the *next* close. By then the market has already taken **7.41%** of the premium (**6.87%** after subtracting SPY) — with a *t* of **+9.06**, this is about as certain as anything on this desk gets. In **20%** of events the pop *alone* is bigger than the entire assumed 13% premium.

In [1]:
R = dict(runup=7.41, runup_abn=6.87, runup_abn_t=9.06, premium=13.0,
         share=0.2, hedged=3.52, hedged_t=4.32)
print('premium assumed by the study : %5.2f%%' % R['premium'])
print('taken by the pop before you can buy: %5.2f%% (abnormal %.2f%%, t=%+.2f)'
      % (R['runup'], R['runup_abn'], R['runup_abn_t']))
print('left for the odd-lot buyer, hedged and costed: %5.2f%% (t=%+.2f)'
      % (R['hedged'], R['hedged_t']))
print('events where the pop alone beats the whole premium: %.0f%%' % (R['share']*100))

premium assumed by the study : 13.00%
taken by the pop before you can buy:  7.41% (abnormal 6.87%, t=+9.06)
left for the odd-lot buyer, hedged and costed:  3.52% (t=+4.32)
events where the pop alone beats the whole premium: 20%


## 3. The second problem: priority is only worth the give-back

Being filled first only matters if the tender price beats what you could have sold at afterwards. If the stock simply *keeps* the premium, the round-lot holder's un-filled stub is worth as much as your cash — and priority bought you nothing.

On this tape the post-expiry give-back is **-0.50%** with *t* = **-1.17** and a median of exactly **0.00%** — statistically absent. The stock keeps the premium: **+6.23%** abnormal, permanently. In **32%** of events the post-expiry price is *above* the assumed tender price, so priority actively cost you: it forced you out of a stock that kept rising.

## 4. Careful: 'what priority is worth' is a number we assumed

It is tempting to read **+3.39%** per event (*t* = +4.33) as the measured value of the entitlement. It is not. Priority pays you the *tender* price instead of the *post-expiry* price, and we only measured one of those two. Change the premium we assumed and the whole number moves with it:

| assumed premium | 5% | 9% | **13%** | 17% | 25% |
|---|--:|--:|--:|--:|--:|
| value of priority | **-1.49%** | +0.95% | **+3.39%** | +5.83% | +10.72% |

It crosses zero at **7.4%** and is *negative* below that. So the honest version of the sentence is: priority can only ever pay the gap between the tender price and the post-expiry price — and section 3 just showed that gap is missing.

## 5. The one number that needs no premium: how big would it have to be?

Rather than pretend we know each offer's clearing price, we ask the tape the question backwards: **how large would the premium have to be** for the costed, market-hedged odd-lot round trip to merely match the market?

**10.17%** on average (median 7.93%). The typical self-tender premium in the literature is low-teens — so the trade works, *narrowly*, and **30%** of events needed more than the 13% we assumed. Premium-free is not assumption-free: this number still depends on where we anchor the 'pre-announcement' price (9.18% at 2 sessions back, 22.62% at 21) and on the frictions we charge — buying 99 shares of a micro-cap at a 100 bps touch pushes it to **12.91%**, i.e. all the way to the premium we assumed, and the round trip down to +0.97% (*t* = +1.19).

## 6. And the entry price has been getting worse

Split at 2018 — a date fixed in advance, not searched. Two point estimates are not a contrast, so we test the *difference* itself (Welch *t*, late minus early). The announcement pop has grown from **5.29%** to **9.10%** (*t* = +2.63) and the breakeven premium with it, **7.89% → 11.99%** (*t* = +2.49) — both real changes, and the second lands within a point of the premium we assumed.

The profit fell too, from **+5.20%** (*t* = +7.13) to **+2.19%** (*t* = +1.72) — but that *decline* is only *t* = -1.99, so we say it carefully: what has demonstrably deteriorated is the price you pay to get in, and the modern round trip no longer clears *t* = 2 on its own.

## 7. The killer: the rule that gives you the edge also caps it

Ninety-nine shares. That is the whole allowance. At the default assumptions the trade is **$176 per event** and about **$1,859 a year** before tax, per account — and only **$118 a year** on a $10 stock, where the flat broker fee alone is 300 bps and the *t* falls to +1.37. The version with real money in it is the round-lot version — which is exactly the version proration hits.

> 🔬 *For the quants:* scaling it is not a capital constraint but a legal one. The 'if we could do it at size' calendar-time sleeve is priced in notebook 02 and loses the excess-of-cash Sharpe race to SPY anyway, at 66% volatility.

## 8. Live check — the machinery is unbiased (offline synthetic)

Plant a run-up and a post-expiry give-back into a synthetic panel: the estimator must find both. Plant nothing: it must find nothing. This is **synthetic data**, not the tender list — it proves the missing give-back on the real tape is a fact about tenders, not a broken harness.

In [2]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from odd_lot import data, strategy as st
# SYNTHETIC tape only - not the real tender list.
panel_p, ev_p, truth = data.synthetic_panel(n_events=90, signal_strength=1.0, seed=928)
panel_0, ev_0, _     = data.synthetic_panel(n_events=90, signal_strength=0.0, seed=928)
pl = st.synthetic_detect(panel_p, ev_p)
nl = st.synthetic_detect(panel_0, ev_0)
print('planted %+d bps run-up / %+d bps give-back ->  recovered %+.0f bps (t=%+.2f) / '
      '%+.0f bps (t=%+.2f)'
      % (truth['runup_planted_bps'], -truth['giveback_planted_bps'],
         pl['runup_bps'], pl['runup_t'], pl['giveback_bps'], pl['giveback_t']))
print('null (nothing planted)            ->  recovered %+.0f bps (t=%+.2f) / '
      '%+.0f bps (t=%+.2f)'
      % (nl['runup_bps'], nl['runup_t'], nl['giveback_bps'], nl['giveback_t']))

planted +500 bps run-up / -400 bps give-back ->  recovered +512 bps (t=+9.71) / -376 bps (t=-7.67)
null (nothing planted)            ->  recovered -1 bps (t=-0.02) / +17 bps (t=+0.33)


## Verdict

- **Signal — Mixed**, and the split is between what the tape says and what we assumed. **The tape is emphatic about the bad news:** the pop takes **7.41%** before you can buy (*t* = +9.06) and the post-expiry give-back priority feeds on is absent (*t* = -1.17). **Every good number is assumption-carried:** the headline **+3.52%** flips sign at a 9% premium, and even the 'value of priority' **+3.39%** flips at 7.4%. Without a premium the tape says only this: you would need a **10.17%** clearing premium to break even, **11.99%** on modern deals, **12.91%** if the stock is a micro-cap.
- **Tradability — Mirage.** Ninety-nine shares, ~$1,859 a year at best, one flat broker fee at a time. Small, capped by law, and impossible to scale by construction.