"""Real-data verification — the headline tables behind the README verdict.

Downloads ^GSPC + ^VIX (cached after the first run) and prints, in one place, the
numbers that earn each stamp: the random-day null for the level and the spike, the
cross-study control vs a -3% price day, the clustering bootstrap, the window-
selection test, and the martingale ruin sim on the full sample vs the chart window.

    python examples/verify_real.py            # S&P 500 (^GSPC)
    python examples/verify_real.py ndx        # cross-check on the Nasdaq-100

The headline (^GSPC) run also writes the tables to ``docs/results.md`` with the
as-of date and the data fingerprints, so every number quoted in the README traces
to an exact, reproducible run.

Network required on first run (Yahoo! Finance); offline thereafter via ../_cache/.
"""

import os
import sys

import pandas as pd

_STUDY_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY_DIR)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY_DIR, "..", "..")))  # repo root, for quantlab

from fear_gauge import benchmark, data, robustness, triggers
from quantlab.repro import DEFAULT_AS_OF, as_of, data_stamp

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 20)

MARKET = {"spx": "^GSPC", "ndx": "^NDX"}.get(
    (sys.argv[1].lower() if len(sys.argv) > 1 else "spx"), "^GSPC"
)

RESULTS = os.path.join(_STUDY_DIR, "docs", "results.md")


def main():
    mkt, vix = data.aligned(MARKET, end=DEFAULT_AS_OF)
    mkt, vix = as_of(mkt), as_of(vix)  # belt-and-braces: pin the sample to the as-of
    print(f"{MARKET}: {len(mkt):,} sessions  {mkt.index.min().date()} -> {mkt.index.max().date()}")
    # Provenance: paste these fingerprints next to any number quoted from this run.
    stamp_mkt = data_stamp(MARKET, mkt, cols=["Close"])
    stamp_vix = data_stamp("^VIX", vix, cols=["Close"])
    print(stamp_mkt)
    print(stamp_vix)

    fam = {
        "V1_level_30": triggers.first_crossings(triggers.level(vix, 30), cooldown=21),
        "V1_level_50": triggers.first_crossings(triggers.level(vix, 50), cooldown=21),
        "V2_spike": triggers.first_crossings(triggers.spike(vix), cooldown=21),
        "V3_high_base": triggers.first_crossings(triggers.spike_from_base(vix, base_min=30), cooldown=21),
    }
    events = {k: int(v.sum()) for k, v in fam.items()}
    print("\nfresh events:", events)

    null = {}
    for name in ("V1_level_30", "V2_spike"):
        null[name] = benchmark.conditional_vs_unconditional(mkt, fam[name])
        print(f"\n[random-day null] {name}")
        print(null[name].round(4))

    price = triggers.first_crossings(mkt["r_cc"] <= -0.03, cooldown=21)
    ctrl = {}
    for name in ("V1_level_30", "V2_spike"):
        ctrl[name] = benchmark.excess_vs_alternative(mkt, fam[name], price)
        print(f"\n[cross-study control] {name} vs price -3%")
        print(ctrl[name].round(4))

    boot = {}
    for name in ("V1_level_30", "V2_spike"):
        boot[name] = robustness.block_bootstrap_excess(mkt, fam[name])
        print(f"\n[block bootstrap h=21] {name}:", {k: round(v, 4) for k, v in boot[name].items()})

    window = robustness.window_sensitivity(mkt, fam["V2_spike"])
    print("\n[window sensitivity] V2_spike, h=21")
    print(window.round(4))

    win = mkt.index >= "2016-06-01"
    ruin = pd.DataFrame({
        "full (63d hold)": robustness.martingale_ruin(mkt, vix),
        "full (126d hold)": robustness.martingale_ruin(mkt, vix, hold_days=126),
        "window 2016+ (63d hold)": robustness.martingale_ruin(mkt[win], vix[win]),
    })
    print("\n[martingale ruin] full sample (quarter and six-month holds) vs chart window (2016+)")
    print(ruin.round(4))

    if MARKET == "^GSPC":
        _write_results(stamp_mkt, stamp_vix, events, null, ctrl, boot, window, ruin)
        print(f"\nwrote {RESULTS}")


def _write_results(stamp_mkt, stamp_vix, events, null, ctrl, boot, window, ruin):
    """The reproducible results doc behind the README verdict (house pattern)."""
    def md(df):
        return "```\n" + df.round(4).to_string() + "\n```"

    lines = [
        "# Results — Study 03 (Fear-Gauge) on the real S&P 500 / VIX",
        "",
        "*Generated by [`examples/verify_real.py`](../examples/verify_real.py). Triggers:",
        "fresh crossings, 21-session cooldown (see [`fear_gauge/triggers.py`](../fear_gauge/triggers.py)).",
        f"Prices: Yahoo! Finance, mode `split_only` for the market, raw for the VIX. As-of **{DEFAULT_AS_OF}**.*",
        "",
        f"`{stamp_mkt}`",
        f"`{stamp_vix}`",
        "",
        f"Fresh events: `{events}`",
        "",
    ]
    for name in ("V1_level_30", "V2_spike"):
        lines += [f"## {name}",
                  "", "### Random-day null", md(null[name]),
                  "", "### Cross-study control vs the −3% price day", md(ctrl[name]),
                  "", "### Block bootstrap on the +21d excess (clustering-aware)",
                  f"`{ {k: round(v, 4) for k, v in boot[name].items()} }`", ""]
    lines += ["## Window sensitivity — V2_spike, +21d excess", md(window), ""]
    lines += ["## Martingale ruin — \"buy at 30, double at 50\" (ruin bar: −20% intra-hold drawdown)",
              md(ruin), "",
              "The quarter-hold worst episode (2008) sits −33% under water (−40% at a",
              "six-month hold) and still ends −21% (−31% at six months); the 2016–2026",
              "chart window caps the worst *terminal* loss at −3.6%. Breach *frequency* is",
              "low everywhere — and actually highest inside the chart window (1/11 vs 2/32",
              "full-history): the window hides the severity, not the frequency.", ""]
    with open(RESULTS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    main()
