"""Build the two narrative notebooks for Study 42 (Last-Call).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/last_call_gspc.parquet + last_call_spy.parquet,
built by examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (last_call/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from last_call import data, strategy as st
gspc = data.fetch_prices("^GSPC", start_year=1950)   # effect
spy  = data.fetch_prices("SPY", start_year=1993)     # tradable
d = st.tom_vs_rest(gspc)
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Still alive?: Faded](https://img.shields.io/badge/Still_alive%3F-Faded-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Last-Call 🕛\n### The market makes its money in four days a month — so why can't you trade it?\n\n"
           + VERDICT +
           "For decades, stock returns have piled up in a tiny window around month-end — the last trading "
           "day plus the first three of the next. It's one of the most replicated facts in finance. The "
           "twist: a strategy that owns the market *only* in that window **loses to just buying and "
           "holding** — and the effect has quietly died since 2008.\n\n"
           "> 📓 **Plain-language layer.** The t-stats and the decay are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The fact | The catch |\n|---|---|\n"
           "| Turn-of-month days earn **~6×** an ordinary day | But they're only **19%** of days — own just them and you compound *less*. |\n"
           "| \"11 basis points a day!\" | The window-only book makes **4%/yr** vs buy-and-hold's **11%**. |\n"
           "| \"A robust 70-year anomaly\" | Since 2008 it earns what any other day earns. |"),
        md("## 1 · The claim\n\nEquity returns concentrate at the **turn of the month** (Lakonishok & "
           "Smidt 1988; McConnell & Xu 2008): be in the market for the last day and the first three of "
           "each month, and you capture almost all of its drift in a fraction of the days."),
        md("## 2 · So what?\n\nIf nearly all the return happens in a predictable four-day window, you "
           "could be in cash 80% of the time, dodge most of the risk, and keep the return. That's the "
           "dream the effect sells. Does the arithmetic actually work?"),
        md("## 3 · How would we even know?\n\nMark the turn-of-the-month days, compare their average "
           "return to every other day (with a t-stat), then **build the tradable rule** — long the "
           "window, cash otherwise — and race it against simply holding SPY, after costs."),
        code("fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['turn-of-month\\ndays','all other\\ndays'],[d['tom_bp'],d['rest_bp']],color=['#2ea44f','#8b949e'])\n"
             "ax.set_ylabel('mean return (bp/day)'); ax.set_title(f\"S&P 500 1950-2026 — the effect is real (Welch t={d['welch_t']:.1f})\"); plt.show()"),
        md("## 4 · The teardown\n\nThe per-day gap is huge and real. Now watch what happens when you "
           "actually trade it."),
        code("import numpy as np\n"
             "rows={'TOM-only (2bp)':st.summary(st.tom_returns(spy,2.0)),'Buy & hold SPY':st.summary(st.buy_hold(spy))}\n"
             "t=pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown','time_in_market']]\n"
             "display(t.style.format({'cagr':'{:.1%}','sharpe':'{:.2f}','max_drawdown':'{:.0%}','time_in_market':'{:.0%}'}))\n"
             "eqT=(1+st.tom_returns(spy,2.0)).cumprod(); eqB=(1+st.buy_hold(spy)).cumprod()\n"
             "ax=eqB.plot(label='Buy & hold SPY',lw=1.6); eqT.plot(ax=ax,label='TOM-only (cash 81% of the time)',lw=1.8)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, SPY 1993-2026'); ax.legend(); plt.show()"),
        md("**Read it plainly.** A higher return *per day* isn't a higher return — out of the market "
           "four-fifths of the time, the window book ends far behind. Lower drawdown? Only because it's "
           "mostly in cash, the same illusion as [the January Barometer](../../41-hangover/)."),
        md("## 5 · The verdict\n\n**Signal: Real** — the concentration is genuine and huge. **Tradability: "
           "Mirage** — owning only the window underperforms owning the index. **Still alive?: Faded** — "
           "since 2008 the window earns an ordinary day's return."),
        md("## 6 · Could you actually trade it?\n\nYou can (12 round-trips a year, cheap on SPY), but you "
           "shouldn't: you'd hold cash 80% of the time to capture a premium that has largely "
           "disappeared, and underperform a buy-and-hold investor who did nothing."),
        md("## 7 · Going further 🚪\n\nThe quants notebook puts the t-stat on the effect and shows the "
           "decay decade by decade. Next: [Study 43 Free-Lunch](../../43-free-lunch/) — betting against "
           "beta, where the headline alpha needs leverage that quietly eats it."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Last-Call — a quantitative teardown 🔬\n### TOM vs non-TOM with a t-stat · the window-vs-buy-and-hold race · the time-in-market illusion · sub-period decay\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We confirm the "
           "turn-of-the-month effect on the S&P 500 back to 1950, then test whether it pays to trade.\n\n"
           "> ⚠️ **Not investment advice.** ^GSPC daily 1950–2026 (effect) + SPY 1993–2026 (tradable), "
           "Yahoo. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | TOM 11.0 vs non-TOM 1.9 bp/day, Welch t 5.1 |\n"
           "| Tradability | **Mirage** | window-only Sharpe 0.55 < buy-and-hold 0.64 |\n"
           "| Still alive? | **Faded** | 13.8 → 4.8 bp/day; now ≈ an ordinary day |\n\n"
           "> 💡 *In plain words:* real per-day edge, but you can't compound a calendar you're absent from."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** mean return on TOM days exceeds non-TOM days "
           "(significantly).\n- **H₂ (the pitch):** a long-window-else-cash book beats buy-and-hold.\n"
           "- **H₃:** the effect is stable over time."),
        md("## 2 · So what? — what rides on each\n\nIf H₂ holds you get equity returns at a fraction of "
           "the risk-time. If only H₁ holds it's a true fact that doesn't pay; if H₃ fails it's a fact "
           "that *stopped* paying."),
        md("## 3 · How we'd know — the protocol\n\nMark [-1,+3] → TOM vs non-TOM means + Welch t → "
           "tradable rule (lagged position, costs) vs buy-and-hold on SPY → split 1950–87 / 1988–2007 / "
           "2008-on for decay."),
        md("## 4 · The teardown"),
        md("### 4.1 The effect, with a t-stat"),
        code("print({k: (round(v,2) if isinstance(v,float) else v) for k,v in d.items()})\n"
             "print(f\"TOM {d['tom_bp']:.1f} bp/day vs non-TOM {d['rest_bp']:.1f} bp/day — Welch t = {d['welch_t']:.1f}\")"),
        md("> 💡 *In plain words:* t≈5 over 76 years — the concentration is not luck. **H₁ holds.**"),
        md("### 4.2 The window-vs-buy-and-hold race, after costs"),
        code("rows={}\n"
             "for c in (0.0,2.0,5.0): rows[f'TOM-only {c:.0f}bp']=st.summary(st.tom_returns(spy,c))\n"
             "rows['Buy & hold SPY']=st.summary(st.buy_hold(spy))\n"
             "display(pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown','time_in_market']].round(3))"),
        md("> 💡 *In plain words:* even gross, the window book's Sharpe (0.55) trails buy-and-hold (0.64); "
           "costs (12 round-trips/yr) push it lower. **H₂ rejected** — a per-day edge you're absent from "
           "80% of the time doesn't compound."),
        md("### 4.3 The decay"),
        code("import numpy as np\n"
             "labs=[('1950-1987',1950,1987),('1988-2007',1988,2007),('2008-on',2008,2100)]\n"
             "dec=pd.DataFrame({lab: st.tom_vs_rest(gspc[(gspc.index.year>=lo)&(gspc.index.year<=hi)]) for lab,lo,hi in labs}).T[['tom_bp','rest_bp']]\n"
             "display(dec.round(1))\n"
             "ax=dec.plot.bar(rot=0,title='Turn-of-month premium has faded to an ordinary day'); ax.set_ylabel('bp/day'); plt.show()"),
        md("> 💡 *In plain words:* the TOM bar shrinks toward the non-TOM bar; by 2008-on they're level. "
           "**H₃ rejected** — the anomaly was largely arbitraged away."),
        md("## 5 · The verdict\n\nH₁ holds, H₂ and H₃ rejected → Signal `REAL`, Tradability `MIRAGE`, "
           "longevity `FADED`."),
        md("## 6 · Could you trade it?\n\nMechanically yes; economically no — you'd sit in cash to harvest "
           "a vanished premium and trail a do-nothing index investor. The only honest use is as a mild "
           "execution-timing tilt *inside* a position you already hold."),
        md("## 7 · Going further\n\nForks: (a) the [-1,+4] or [-2,+3] windows — is the result window-tuned? "
           "(b) the effect cross-sectionally (small vs large caps); (c) overlay TOM timing on a strategy "
           "that's *already* long. Backlog: [`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
