# Study 941 — Short Both Legs ⚖️

**Short the 3x long *and* the 3x short of the same index — is the decay harvest free money?**

TQQQ (3x long Nasdaq-100) and SQQQ (−3x inverse) both reset their leverage every day, and
both therefore bleed the textbook compounding decay — roughly **13%/yr**
for the 3x and **26%/yr** for the −3x at the index's ~21% volatility.
Short both in equal dollars and the market exposure cancels. The forums call it free money.

We test it on **TQQQ + SQQQ vs BIL** (cash), with **QQQ** as the neutrality check, daily
total-return closes 2010-02-11 → 2026-06-30 (4,120 days), everything
**excess-of-cash**, one execution lag, 2 bps one-way cost, and the borrow fee swept from
0 to 15%/yr because it is an *assumption*, not tape.

**Every harvest number below is before any stock-borrow fee** — no free borrow-fee tape
exists, so the rate is an assumption and the *breakeven* borrow is what the verdict rests on.

*Numbers below are the frozen headline (`docs/results.md`, Fingerprint `8f75619ff8e2`); the
live cells run the fast offline synthetic control. As-of 2026-06-30.*


## 1. The chart that sells the trade

Hold TQQQ and SQQQ together and your money melts — that much is true and easy to chart. The leap the forums make is: *therefore shorting both must print money*. Let's see what the tape actually paid.

In [1]:
R = dict(mean=2.06, sharpe=1.64, t=8.82, vol=1.26, dd=-1.37, beta=0.0032,
         implied_load=2.2, decay_3x=12.9, decay_m3x=25.7)
print('short both legs, daily reset, 2 bps, no borrow:')
print('  excess-of-cash %+.2f%%/yr   Sharpe %+.2f   HAC t %+.2f'
      % (R['mean'], R['sharpe'], R['t']))
print('  volatility %.2f%%   worst drawdown %.2f%%   beta to QQQ %+.4f'
      % (R['vol'], R['dd'], R['beta']))
print()
print('decay supposedly on offer: %.0f%% + %.0f%% per year'
      % (R['decay_3x'], R['decay_m3x']))
print('what actually turned up  : %+.2f%% per year' % R['mean'])

short both legs, daily reset, 2 bps, no borrow:
  excess-of-cash +2.06%/yr   Sharpe +1.64   HAC t +8.82
  volatility 1.26%   worst drawdown -1.37%   beta to QQQ +0.0032

decay supposedly on offer: 13% + 26% per year
what actually turned up  : +2.06% per year


## 2. Where did the other 36 points go?

They were never collectable. The decay is a fact about the *compounded path* of a levered fund, not about its *average daily return*. A short position that is reset to the same dollar size every evening earns the average daily return of what it is short — and on that measure TQQQ is exactly 3x the index and SQQQ exactly −3x, so the index cancels and all that is left is **what the two funds cost you**.

Add up the two legs on the real tape and the leftover is **+2.20%/yr**. Two caveats we owe you, because they are the easiest place in this study to fool yourself:

1. That +2.20% and the +2.06% the backtest earned are **the same arithmetic**, not two independent measurements agreeing. On a daily reset the book's excess return *is* `cash − 0.5×(TQQQ + SQQQ)`, to fifteen decimal places. The backtest earns its keep on everything else — other schedules, borrow, the rebate, costs, compounding, ruin — not here.
2. It is a **residual**, and calling it a fee is a reading. Expense ratios, the financing spread, the funds' own end-of-day trading, tracking error and the cash-proxy basis all land in the same bucket, and this study separates none of them. What *is* established is the negative: it is not the compounding decay.

> 🔬 **For the quants.** Arithmetic vs geometric: `E[r_L] = L*E[r_index] - (L-1)*r_cash - fees` has no σ² term; the `0.5*L*(L-1)*σ²` decay only appears in `E[log r_L]`. A constant-dollar short is an arithmetic-mean bet, which is why it never touches the decay.

## 3. So it *is* a real edge — a small, dull one

+2.06%/yr over cash, at 1.26% volatility, with a worst drawdown of -1.37% and a beta to the Nasdaq of +0.0032. It was positive in **all 17 calendar years** in the sample (2026 is a half-year stub), best in the stressed ones (2020: +6.79%, 2022: +3.63%) because that is when the funds' own trading costs widen. Statistically it is about as solid as this desk ever sees: HAC *t* = +8.82 — though on a series this thin that *t* is really saying **a cost accrual is stable**, not that an anomaly was discovered.

And it is not a tail bet, which for a series with +47 excess kurtosis is worth checking: 55.9% of days are positive, the median day annualises to +1.74%, and throwing away the **50 best days** out of 4,120 still leaves +0.95%/yr. Drop the whole of 2020 and it is +1.77%/yr. (Those are *magnitude* checks. We do not quote a *t* for them: deleting the best observations strips the right tail, so the *t* rises mechanically even as the mean falls — it would look like better evidence when it is less.)

## 4. And then the borrow fee arrives

You have to *borrow* both funds to short them, and the lender charges a fee. Every 1%/yr of blended fee takes 1 pp straight off the top, so the trade dies at a blended borrow of **2.06%/yr**. TQQQ is easy to borrow; SQQQ is the crowded side. The edge and the fee are the same size — which is not a coincidence: a lending fee exists precisely to price the reason someone wants to short a thing. And at exactly that rate, **11 of the 17 calendar years lose money** — 'positive every year' is not 'profitable every year'.

Worse for an ordinary account. A short position generates cash, and a prime broker pays you the cash rate on it; a retail broker pays you nothing. That interest is not a *source* of the edge — the two funds' own financing carry averages to +1x cash on the liability side and the proceeds interest is what offsets it — but **losing** it costs you the cash rate itself, 1.32%/yr on this sample. Without it the trade earned +0.75%/yr over the whole window and **+0.10%/yr (t = +0.22) since 2018** — nothing — because the higher rates went, the more the missing interest cost.

## 5. Can't you just rebalance less often and earn more?

That is the classic response, and the tape does show a bigger headline: monthly resets returned +5.26%/yr instead of +2.06%. But almost all of the extra is an accidental *long Nasdaq* bet (beta +0.190); its market-neutral alpha is only +1.64%/yr with *t* = +0.68. Meanwhile the Sharpe collapses from +1.64 to +0.44 and the worst month goes from -0.23% to -12.1%.

Never rebalancing is not a strategy at all. The 3x leg keeps rising, your short of it keeps growing, and by **2013-08-01** the book is **wiped out** — gross short 51.7x equity at the end. Short-both is a short-gamma position: you must keep feeding it, and the feeding is the strategy.

## 6. Live check — the machinery is unbiased (offline synthetic)

We build two toy worlds with **identical, enormous** decay in their levered legs. In one, the funds charge a fee; in the other they are free. If the trade harvested *decay*, it would pay in both. Watch it pay in one.

In [2]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from short_pair import data, strategy as st
for tag, ss in [('funds charge a fee', 1.0), ('funds are free    ', 0.0)]:
    px, truth = data.synthetic_daily(signal_strength=ss, seed=941)
    d = st.synthetic_detect(px, cost_bps=0.0)
    print('%s | decay in the legs %.1f%%/%.1f%% per yr -> harvest %+.2f%%/yr (t=%+.2f)'
          % (tag, truth['decay_long_ann']*100, truth['decay_short_ann']*100,
             d['ann_mean']*100, d['t_hac']))

funds charge a fee | decay in the legs 14.5%/29.0% per yr -> harvest +2.46%/yr (t=+14.63)


funds are free     | decay in the legs 14.5%/29.0% per yr -> harvest +0.01%/yr (t=+0.05)


## Verdict

- **Signal — Real.** A genuine, market-neutral **+2.06%/yr** over cash **before borrow** (HAC *t* = +8.82, beta +0.0032, positive every year, +0.95% without its 50 best days). It is simply not the effect the folklore names: it is what the two funds cost their holders, and the synthetic control proves the point by paying nothing when identical decay carries no fee.
- **Tradability — Fragile.** Breakeven blended borrow is **2.06%/yr** — the same size as the edge, and at that rate 11 of 17 years are losers. Worse, the crowded SQQQ leg breaks even at only 1.61%/yr on its own; the easy-to-borrow TQQQ leg is paying for it. Without a rebate it is +0.10%/yr since 2018, which for a retail account makes it a Mirage outright. Rebalancing less to earn more just buys residual beta and a -12% month, and not rebalancing at all destroys the account. A prime-brokerage carry trade at best, free money never.