"""Build the two narrative notebooks for Study 56 (Tide-Table).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/tide_table_cape.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (tide_table/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from tide_table import data, strategy as st
d = data.fetch_shiller(start_year=1900)        # cache-first
ten = st.forward_corr(d["cape"], d["fwd10"]); one = st.forward_corr(d["cape"], d["fwd1"])
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Forecasts long-run returns?: Confirmed](https://img.shields.io/badge/Forecasts_long--run_returns%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Tide-Table 🌊\n### The one valuation signal that actually forecasts returns — over a decade\n\n"
           + VERDICT +
           "After a string of valuation 'signals' that didn't work, here's one that does: the Shiller CAPE. "
           "When stocks are cheap relative to a decade of earnings, the next decade's returns are high; "
           "when expensive, low. It explains ~28% of 10-year returns — *real* and useful. The catch is the "
           "horizon: it tells you the tide, not tomorrow's wave.\n\n"
           "> 📓 **Plain-language layer.** The R², the buckets and the timing caveat are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (1900–2016) |\n|---|---|\n"
           "| \"Does CAPE forecast returns?\" | Yes — **R² 0.28** at 10 years, corr **−0.51**. |\n"
           "| \"Cheap vs expensive?\" | Cheap decades **+10.2%/yr** real vs expensive **+4.0%**. |\n"
           "| \"Can I time with it?\" | No — at **1 year** R² is just **0.05**. |"),
        md("## 1 · The claim\n\nCampbell & Shiller (1998): the cyclically-adjusted P/E (price ÷ 10-year "
           "average real earnings) mean-reverts, so a high CAPE precedes low long-run returns and a low "
           "CAPE precedes high ones."),
        md("## 2 · So what?\n\nIf valuation forecasts the next decade, it's the single most useful number "
           "for setting return expectations and asset allocation. But 'forecasts the decade' and 'times "
           "the market' are different claims — and conflating them is how investors get hurt."),
        md("## 3 · How would we even know?\n\nLine up CAPE against the **realised next-10-year real "
           "return**, measure the correlation and R², sort history into cheap/expensive buckets — then "
           "run the *same* test at a 1-year horizon to expose the timing limit."),
        code("fig,ax=plt.subplots(figsize=(7,5))\n"
             "ax.scatter(d['cape'], d['fwd10']*100, s=6, alpha=.4)\n"
             "xs=np.linspace(d['cape'].dropna().min(), d['cape'].dropna().max(), 50)\n"
             "b0,b1=st.implied_return(d['cape'],d['fwd10'])\n"
             "ax.plot(xs,(b0+b1/xs)*100,color='#2ea44f',lw=2,label=f\"fit (R²={ten['r2']:.2f})\")\n"
             "ax.set_xlabel('starting CAPE'); ax.set_ylabel('next-10y real return (%/yr)')\n"
             "ax.set_title('Higher CAPE → lower future returns (corr −0.51)'); ax.legend(); plt.show()"),
        md("## 4 · The teardown\n\nThe scatter slopes clearly down — and the bucket ladder is monotone. "
           "Then watch the same signal fail at one year."),
        code("b=st.bucket_returns(d['cape'],d['fwd10'])\n"
             "ax=(b*100).plot.bar(rot=0,color=['#2ea44f','#dab617','#c0392b'],title='Next-10y real return by starting valuation')\n"
             "ax.set_ylabel('%/yr'); plt.show()\n"
             "print(f\"R²: 10-year {ten['r2']:.2f}  vs  1-year {one['r2']:.2f}  -> a forecaster, not a timer\")"),
        md("**Read it plainly.** Buy cheap, earn ~10%/yr real over the decade; buy expensive, ~4%. But the "
           "1-year R² of 0.05 means CAPE says almost nothing about next year — an expensive market can "
           "keep climbing for years."),
        md("## 5 · The verdict\n\n**Signal: Real** — R² 0.28, monotone ladder. **Tradability: Fragile** — "
           "useless as a timer (1y R² 0.05). **Forecasts long-run returns?: Confirmed** — the valuation "
           "signal the Fed Model wasn't."),
        md("## 6 · Could you actually trade it?\n\nNot as a timer — markets stay expensive for years. Its "
           "real use is **expectations and allocation**: at today's CAPE (~31) the fit implies about "
           "**+3%/yr real** for the next decade — plan accordingly, don't try to jump in and out."),
        md("## 7 · Going further 🚪\n\nThe quants notebook has the implied-return fit and the horizon "
           "contrast. Contrast with [Study 47 Paper-Moon](../../47-paper-moon/): valuation (CAPE/EP) works, "
           "the Fed Model's bond comparison doesn't."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Tide-Table — a quantitative teardown 🔬\n### CAPE vs forward returns · 10y vs 1y R² · the valuation ladder · the implied-return fit\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We quantify "
           "CAPE's long-horizon forecasting power and its short-horizon limit.\n\n"
           "> ⚠️ **Not investment advice.** Shiller CAPE + forward real total returns (datahub mirror), "
           "1900–2016. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | corr −0.51, R² 0.28 at 10y; monotone ladder |\n"
           "| Tradability | **Fragile** | 1y R² 0.05 — not a timer |\n"
           "| Forecasts long-run? | **Confirmed** | valuation carries it (vs Fed Model) |\n\n"
           "> 💡 *In plain words:* the tide is forecastable; the next wave is not."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** CAPE forecasts the next-10y real return (negative, "
           "significant).\n- **H₂:** the cheap/expensive bucket ordering is monotone.\n- **H₃ (the limit):** "
           "the 1-year relationship is far weaker — CAPE is not a timer."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, valuation calibrates decade-ahead "
           "expectations. H₃ keeps us honest: it's an expectation tool, not a market-timing rule."),
        md("## 3 · How we'd know — the protocol\n\ncorr & R² of CAPE vs fwd-10y → valuation buckets → "
           "implied-return fit → the same test at 1 year."),
        md("## 4 · The teardown"),
        md("### 4.1 The forecasting power, by horizon"),
        code("print('10-year:', {k:round(v,3) for k,v in ten.items()})\n"
             "print(' 1-year:', {k:round(v,3) for k,v in one.items()})"),
        md("> 💡 *In plain words:* 10y R² 0.28 (strong), 1y R² 0.05 (weak). **H₁ and H₃ hold.**"),
        md("### 4.2 The valuation ladder"),
        code("display((st.bucket_returns(d['cape'],d['fwd10'],n=5)*100).round(1))"),
        md("> 💡 *In plain words:* monotone from cheap to expensive. **H₂ holds.**"),
        md("### 4.3 The implied-return fit (a concrete forecast)"),
        code("b0,b1=st.implied_return(d['cape'],d['fwd10'])\n"
             "cur=d['cape'].dropna().iloc[-1]\n"
             "print(f'fwd10 = {b0:+.3f} + {b1:.2f}/CAPE')\n"
             "print(f'at CAPE {cur:.0f} -> implied 10y real return {b0+b1/cur:+.1%}')"),
        md("> 💡 *In plain words:* today's rich CAPE implies a modest ~3%/yr real decade — sober expectations, not a crash call."),
        md("## 5 · The verdict\n\nH₁, H₂ hold; H₃ confirms the limit → Signal `REAL`, Tradability "
           "`FRAGILE`, long-run forecasting `CONFIRMED`."),
        md("## 6 · Could you trade it?\n\nAs an allocation/expectations input, yes; as a market timer, no "
           "(1y R² 0.05). 'Sin a little' on valuation (Asness et al. 2017) — tilt slowly, don't switch."),
        md("## 7 · Going further\n\nForks: (a) excess CAPE yield (CAPE earnings yield minus real bond "
           "yield) — the *honest* version of the Fed Model; (b) cross-country CAPE (the PWB entry); "
           "(c) CAPE-tilted allocation vs constant-weight. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
