# Study 829 — Global Sovereign-Bond Momentum 🌍📉

**Does a bond market's own recent *trend* predict its next move?**

Moskowitz, Ooi & Pedersen (2012) *"Time Series Momentum"* find that across asset classes
— **including government bonds** — a market's own past 12-month return positively predicts
its next month. We take the bond sleeve on tradable ground: five global sovereign-bond
ETFs (`BWX`, `IGOV`, `BNDX`, `EMB`, `IEF`), each **signed by its 12-minus-1-month
total-return trend**, long the up-trend / short the down-trend (and a long-only variant),
2007-01-31 → 2026-06-30.

*Numbers below are the frozen headline (`docs/results.md`); the live cells run the fast
synthetic control. Survivorship: currently-listed funds only, tiny 5-ETF panel — an upper
bound with limited power.*


## 1. The idea in one picture

Bond *levels* trend for years — a rate-cutting cycle lifts prices, a hiking cycle sinks them. So the sign of a market's trailing twelve-month total return (skipping the most recent month, the '12-1' window) *should* be an informative state for next month: own the up-trenders, short (or sit out) the down-trenders.

In [1]:
R = dict(ls_bps=0.26, ls_t_nw=0.02, lo_bps=12.27, lo_t_nw=1.75, bh_bps=24.56, bh_t=1.88)
print('LONG-SHORT 12-1 book : %+.2f bps/mo (Newey-West t = %+.2f)' % (R['ls_bps'], R['ls_t_nw']))
print('LONG-ONLY trend timing: %+.2f bps/mo (Newey-West t = %+.2f)' % (R['lo_bps'], R['lo_t_nw']))
print('NAIVE buy-and-hold    : %+.2f bps/mo (Newey-West t = %+.2f)  <- the real yardstick'
      % (R['bh_bps'], R['bh_t']))

LONG-SHORT 12-1 book : +0.26 bps/mo (Newey-West t = +0.02)
LONG-ONLY trend timing: +12.27 bps/mo (Newey-West t = +1.75)
NAIVE buy-and-hold    : +24.56 bps/mo (Newey-West t = +1.88)  <- the real yardstick


## 2. Is the trend real? A live synthetic control

We plant a persistent trend in a seeded toy world (`edge>0`) and check the detector recovers it — and that it stays *silent* on a random walk (`edge=0`, no trend to find). No network.

In [2]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from sovereign_momentum import data, strategy as st
null = st.synthetic_detect(data.synthetic_panel(edge=0.0, seed=829))
planted = st.synthetic_detect(data.synthetic_panel(edge=0.010, seed=829))
print('random-walk world: NW t = %+.2f  (should be ~0)' % null['t_nw'])
print('planted-trend world: NW t = %+.2f  (should light up)' % planted['t_nw'])

random-walk world: NW t = +0.55  (should be ~0)
planted-trend world: NW t = +12.91  (should light up)


## 3. The honest verdict — the trend does *not* pay here

On five global sovereign-bond ETFs the **long-short** 12-1 book is **flat**: **+0.26 bps/mo**, Newey-West *t* = **+0.02** — no predictive sign at all. The **long-only** variant *looks* positive (**+12.27 bps/mo**) but that is just **bond beta**: naive equal-weight buy-and-hold earns **+24.56 bps/mo** — *more* than the timed book — and a block-rotation placebo puts the long-only number *below* its own null mean (+13.57 bps, *p* = 0.53). The trend adds nothing you don't get by simply holding the bonds. **Signal: None** (claimed edge absent), **Tradability: Mirage** (the long-short book loses money after costs; the long-only book is costed bond beta that under-earns buy-and-hold).