"""Generate the two narrative notebooks for Study 22 (Crystal-Ball) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the **offline synthetic tape** (a random-walk null + a mean-reverting tape).
The synthetic *is* the proof here: on a random walk there is nothing to find, so the two-sided HP
book's large Sharpe is by construction pure look-ahead. The **real verdict** (the same fabricated edge
on real ETFs) is quoted from [`docs/results.md`](../docs/results.md). Both notebooks walk the SAME seven
desk beats (see ../../../METHODOLOGY.md).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from crystal_ball import data, hp, strategy, decompose, extension

# Offline synthetic price: a RANDOM-WALK null (nothing to find) and a MEAN-REVERT tape (a real cycle).
# LAM is the HP smoothing. The real ETF verdict is in ../docs/results.md.
LAM = 1e6
close0, _ = data.synthetic_prices(revert_rho=1.0,  seed=22)   # random-walk null
close,  _ = data.synthetic_prices(revert_rho=0.97, seed=22)   # genuine mean reversion
print("two synthetic tapes: a random walk (null) and a mean-reverting cycle")
"""

R = dict(
    n="6", lo="1993", hi="2026", fp="eeaedd53f6d5",
    spy_two="+1.93", spy_two_t="+12.6", spy_one="+0.11", spy_one_t="+0.7",
    leak1_two="-0.18", leak5_two="-0.40", leak5_one="-0.08",
)

BADGES = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Look--ahead bias?: Busted](https://img.shields.io/badge/Look--ahead_bias%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Crystal-Ball 🔮\n"
            "### A textbook detrending filter turns a coin-flip into a Sharpe-2 machine. Is it real?\n\n"
            + BADGES +
            "Here's a strategy that looks *too* good — and that's the point. Take any price, smooth it "
            "with a **Hodrick–Prescott filter** (a standard, respectable tool economists use everywhere) "
            "to get its underlying *trend*, then trade the wiggle around it: when price is **below** its "
            "trend it's 'cheap', so buy; above, sell. Backtest it and you get a glorious equity curve — "
            "Sharpe near 2, on almost anything.\n\n"
            "This is the desk's fifth idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§8.1) — and the first that's a **backtest trap**, not a market effect. The classic HP filter "
            "is *two-sided*: the trend at any day is computed from the **whole** series, the future "
            "included. So 'price is below trend' secretly means 'below where it's *going to* end up' — "
            "you're trading on tomorrow's data. We'll prove it on a **random walk** (where there is "
            "*nothing* to trade) and watch the fake edge appear, then vanish the instant we forbid the "
            "filter from peeking.\n\n"
            "> 📓 **Plain-language layer.** The Newey–West *t*, the future-leakage correlation and the λ "
            "sweep are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** tape, so the real-ETF numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Is the Sharpe-2 backtest real? | 🚫 **No.** On a pure random walk — where nothing is "
            "tradable — the same filter still 'earns' a Sharpe of ~2. It's an artefact. |\n"
            "| Where does the 'edge' come from? | 🔮 **The future.** The two-sided trend uses tomorrow's "
            "prices, so the signal is correlated with returns that haven't happened yet. |\n"
            "| What survives once you stop peeking? | ⚪ **Nothing.** The causal (past-only) version earns "
            f"a real-{R['n']}-ETF Sharpe of about **{R['spy_one']}**. |\n\n"
            "> Desk shorthand: **Signal `NONE` · Tradability `MIRAGE` · Look-ahead bias `BUSTED`** — a "
            "fabricated edge, real only on paper."
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "The HP filter splits a series into a smooth **trend** and a **cycle** (the deviation from "
            "trend). The strategy trades the cycle's mean reversion: long when price sits below its "
            "trend. On our **random-walk** tape — which by construction has *no* tradable structure — "
            "here's the two-sided cycle and the trade it implies:"
        ),
        code(
            "yl = np.log(close0); tau = hp.hp_trend_twosided(yl, LAM); c = yl - tau\n"
            "fig, (a1, a2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)\n"
            "a1.plot(close0.index, close0.values, lw=.8, label='random-walk price'); a1.plot(tau.index, np.exp(tau).values, 'r', lw=1.2, label='two-sided HP trend')\n"
            "a1.legend(); a1.set_title('A smooth trend through pure noise -- fitted with the whole series')\n"
            "a2.fill_between(c.index, c.values, 0, alpha=.5); a2.axhline(0, c='k', lw=.6); a2.set_ylabel('cycle (log)')\n"
            "a2.set_title('Buy when the cycle is below 0 -- but that 0 line knows the future')\n"
            "plt.tight_layout(); plt.show()"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "If it were real, it would be a money machine — a high-Sharpe, market-neutral edge on every "
            "asset, from a respectable off-the-shelf filter. That's exactly why this matters: the trap is "
            "*seductive and respectable*. Thousands of backtests — in papers, in blogs, in pitch decks — "
            "use a full-sample filter, a full-sample z-score, a full-sample normalisation, and quietly "
            "leak the future. Learn to spot this one and you'll spot them all."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Three checks:\n\n"
            "1. **Random-walk control.** Run it where there is *nothing* to find. Any edge is artefact.\n"
            "2. **Go causal.** Recompute the trend from a trailing window (past only) and re-run.\n"
            "3. **The smoking gun.** Correlate today's cycle with *future* returns — a two-sided filter "
            "that peeks will show a correlation it has no honest right to.\n\n"
            "**Busted line:** the edge is huge two-sided, ~0 one-sided, and the two-sided cycle predicts "
            "the future it was built from."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · The same rule, peeking vs honest\n"
            "Run the cycle-reversion book two ways on the **random walk**: two-sided (uses the future) "
            "and one-sided (causal, trailing window)."
        ),
        code(
            "two = strategy.reversion_returns(close0, cost_bps=1.0, lam=LAM, causal=False)\n"
            "one = strategy.reversion_returns(close0, cost_bps=1.0, lam=LAM, causal=True)\n"
            "idx = one.index.intersection(two.index)\n"
            "eq2 = (1+two.reindex(idx)).cumprod(); eq1 = (1+one.reindex(idx)).cumprod()\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(eq2.index, eq2.values, color='#c0392b', label=f\"two-sided (peeking) Sharpe {strategy.summary(two.reindex(idx))['sharpe']:+.2f}\")\n"
            "ax.plot(eq1.index, eq1.values, color='#8b949e', label=f\"one-sided (causal) Sharpe {strategy.summary(one.reindex(idx))['sharpe']:+.2f}\")\n"
            "ax.set_yscale('log'); ax.legend(); ax.set_title('On a RANDOM WALK: the peeking book mints money; the honest one flat-lines')\n"
            "plt.show()"
        ),
        md(
            "There is **nothing to trade** on a random walk — yet the two-sided book climbs relentlessly. "
            "Every cent of it is look-ahead."
        ),

        md(
            "### 4b · The smoking gun — the cycle 'predicts' the future\n"
            "Correlate today's cycle with the return over the next few days. The two-sided cycle was "
            "*built* from those returns, so it 'predicts' them; the causal cycle can't, so it doesn't."
        ),
        code(
            "fl = decompose.future_leakage(close0, lam=LAM)\n"
            "hs = list(fl.keys())\n"
            "two_c = [fl[h]['two_sided_corr'] for h in hs]; one_c = [fl[h]['one_sided_corr'] for h in hs]\n"
            "x = np.arange(len(hs)); w = .38\n"
            "fig, ax = plt.subplots()\n"
            "ax.bar(x-w/2, two_c, w, color='#c0392b', label='two-sided cycle'); ax.bar(x+w/2, one_c, w, color='#8b949e', label='one-sided cycle')\n"
            "ax.axhline(0, c='k', lw=.6); ax.set_xticks(x); ax.set_xticklabels([f'{h}d' for h in hs]); ax.set_ylabel('corr(cycle today, future return)'); ax.legend()\n"
            "ax.set_title('The two-sided cycle is correlated with returns that have not happened yet')\n"
            "plt.show()"
        ),

        md(
            "### 4c · The honest filter isn't broken — it just won't hallucinate\n"
            "Run the causal version on a tape that *does* mean-revert. It finds a small, real edge — "
            "proof the one-sided filter works; it simply refuses to invent one from noise."
        ),
        code(
            "for label, c in [('random walk', close0), ('real mean-reversion', close)]:\n"
            "    he = decompose.honest_edge(c, cost_bps=1.0, lam=LAM)\n"
            "    print(f\"{label:20s}: one-sided (honest) Sharpe {he['sharpe']:+.2f} (HAC t {he['t_stat']:+.1f})\")"
        ),

        md(
            "### 4d · On the real market — same fabricated edge\n"
            "On real ETFs (quoted from [`../docs/results.md`](../docs/results.md)): the two-sided book "
            f"shows a Sharpe of **{R['spy_two']}** on SPY at a *t* of **{R['spy_two_t']}** — and the "
            f"causal version, **{R['spy_one']}** (*t* {R['spy_one_t']}). The cycle's correlation with the "
            f"next 5-day return is **{R['leak5_two']}** two-sided vs **{R['leak5_one']}** one-sided. The "
            "market behaves exactly like the random walk: the 'edge' is the filter peeking."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            "- **Fake on noise** — Sharpe ~2 two-sided on a random walk; ~0 one-sided.\n"
            "- **Caught in the act** — the two-sided cycle correlates with the future it used.\n"
            "- **Nothing survives** — the honest, causal book has no edge on the real tape.\n\n"
            "> **Signal `NONE` · Tradability `MIRAGE` · Look-ahead bias `BUSTED`.** A respectable filter, "
            "used innocently, smuggles the future into the past."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "**No — you can't even compute the signal in real time.** The two-sided HP trend for *today* "
            "needs *all future prices*; live, you'd have to use the causal filter, which earns nothing. "
            "There's no execution detail to optimise, no cost to haggle over — the strategy simply does "
            "not exist outside a full-sample backtest.\n\n"
            "> Tradability **`MIRAGE`** in the purest sense: the paper edge has no live counterpart."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **It survives every check but causality** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): charge more cost, vary the smoothing — the "
            "fake edge laughs them off. The *only* test that kills it is recomputing the filter on past "
            "data.\n"
            "- **The lesson generalises.** Any full-sample transform — a two-sided filter, a "
            "z-score by full-sample mean/vol, a regression fit on all the data — leaks the future. The "
            "universal fix: compute it causally; the universal test: does perturbing a *future* point "
            "move a *past* signal value?\n"
            "- **A causal HP via Kalman.** The one-sided HP is the Kalman-filtered local-linear-trend; a "
            "proper state-space version would be smoother than our rolling-window endpoint — does any "
            "real edge appear then? (We bet not.)\n\n"
            "PRs welcome — find a *causal* HP variant with a real edge, or add the next full-sample-leak "
            "to the desk's trap museum."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Crystal-Ball — a quantitative teardown 🔬\n"
            "### Two-sided vs one-sided HP · the look-ahead Sharpe gap (HAC) · the future-leakage correlation · the λ/cost robustness\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim with its standard error.* The steelman is §8.1 (moving averages on "
            "an HP-detrended price). We show the edge is a **look-ahead artefact** of the two-sided HP "
            "filter, on a random walk (where it cannot be anything else) and on real ETFs.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — is there an edge? | 🔴 `NONE` | The causal (tradable) HP-cycle book earns ~0 "
            f"on real {R['n']} ETFs (SPY Sharpe **{R['spy_one']}**, *t* **{R['spy_one_t']}**); the large "
            "two-sided Sharpe is artefact. |\n"
            "| **Tradability** | 🔴 `MIRAGE` | The two-sided signal needs all future prices to compute "
            "*today's* position — it has no live counterpart. |\n"
            "| **Look-ahead bias?** | ⚪ `BUSTED` | On a random walk the two-sided book earns Sharpe ~2 "
            "(*t* > 10); its cycle correlates "
            f"**{R['leak5_two']}** with the next-5-day return it was built from. |\n\n"
            "> **In one sentence:** the spectacular HP-filter backtest is pure look-ahead — the two-sided "
            "trend uses future prices, so the cycle predicts the returns it contains; go causal and "
            "nothing remains.\n\n"
            "*(This notebook executes on synthetic tapes; the real ETF numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "HP trend: $\\tau = (I + \\lambda D'D)^{-1} y$ with $D$ the second-difference operator — a "
            "**linear smoother of the whole vector $y$**, so $\\partial \\tau_t / \\partial y_s \\neq 0$ "
            "for $s>t$ (future points move the present estimate). The strategy is $w_t = -\\text{sign}"
            "(c_{t-1})$, $c = y - \\tau$. The causal version replaces $\\tau_t$ with the endpoint of an "
            "HP filter on $y_{t-W:t}$, for which $\\partial \\tau_t/\\partial y_s = 0$ for $s>t$. The "
            "synthetic null is a random walk (no tradable $c$); the alt tape has a stationary AR(1) cycle."
        ),
        code(
            "# direct proof of the dependence on the future: perturb a point 200 days ahead\n"
            "yl = np.log(close0); t = 1500\n"
            "base2 = hp.hp_trend_twosided(yl, LAM).iloc[t]; base1 = hp.hp_trend_onesided(yl, LAM, 252).iloc[t]\n"
            "yl2 = yl.copy(); yl2.iloc[t+200] += 0.5\n"
            "p2 = hp.hp_trend_twosided(yl2, LAM).iloc[t]; p1 = hp.hp_trend_onesided(yl2, LAM, 252).iloc[t]\n"
            "print(f\"bump a price 200 days AFTER t -> two-sided trend at t moves by {abs(p2-base2):.2e} (look-ahead)\")\n"
            "print(f\"                                 one-sided trend at t moves by {abs(p1-base1):.2e} (causal: zero)\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "The two-sided HP is one member of a large family of *full-sample* transforms — z-scores by "
            "full-sample mean/vol, two-sided band-pass filters, regressions fit on all data, "
            "winsorisation by full-sample quantiles — every one of which leaks the future into "
            "backtested signals. The HP case is the cleanest to demonstrate because the leakage is large "
            "and the fix (causal recompute) is unambiguous. Beats 4–6 quantify the leak and show nothing "
            "survives it."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Random-walk control + causal recompute** (`decompose.lookahead_bias`): two-sided vs "
            "one-sided Sharpe and HAC t. Pre-registered: two-sided ≫ 0, one-sided ≈ 0 on the null.\n"
            "2. **Future leakage** (`decompose.future_leakage`): corr(cycle_t, forward return). Two-sided "
            "≠ 0, one-sided ≈ 0.\n"
            "3. **Honest edge** (`decompose.honest_edge`): the causal book's own t — nothing on the null, "
            "a little on real reversion.\n"
            "4. **Robustness** (`extension`): the two-sided edge survives λ and cost.\n\n"
            "**Busted line:** large two-sided edge + forward-correlated cycle + ~0 causal edge."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · Two-sided vs one-sided, null and reversion"),
        code(
            "for label, c in [('random walk', close0), ('mean-revert', close)]:\n"
            "    lb = decompose.lookahead_bias(c, cost_bps=1.0, lam=LAM)\n"
            "    print(f\"{label:12s}: two-sided {lb['two_sided_sharpe']:+.2f} (t {lb['two_sided_t']:+.1f}) | \"\n"
            "          f\"one-sided {lb['one_sided_sharpe']:+.2f} (t {lb['one_sided_t']:+.1f}) | gap {lb['lookahead_sharpe_gap']:+.2f}\")"
        ),

        md("### 4b · The future-leakage fingerprint"),
        code(
            "for label, c in [('random walk', close0), ('mean-revert', close)]:\n"
            "    fl = decompose.future_leakage(c, lam=LAM)\n"
            "    print(f\"{label:12s}: corr(cycle, fwd) h=1 two {fl[1]['two_sided_corr']:+.2f}/one {fl[1]['one_sided_corr']:+.2f} | \"\n"
            "          f\"h=5 two {fl[5]['two_sided_corr']:+.2f}/one {fl[5]['one_sided_corr']:+.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** A signal computed *today* should be uncorrelated with what the price "
            "does *next* unless it has real predictive content. The two-sided cycle's strong negative "
            "correlation with future returns isn't prediction — it's memory: those returns are inside the "
            "trend it subtracted."
        ),

        md("### 4c · Nothing survives the peek-stop (real ETFs, quoted)"),
        md(
            f"Across **{R['n']}** real ETFs the one-sided Sharpe is indistinguishable from zero while the "
            f"two-sided is large and 'significant' (SPY: two-sided **{R['spy_two']}**, *t* "
            f"**{R['spy_two_t']}**; one-sided **{R['spy_one']}**, *t* **{R['spy_one_t']}**). The *t*-stat "
            "measures look-ahead, not edge — see [`../docs/results.md`](../docs/results.md)."
        ),

        md("## Beat 5 · The verdict\n\n"
           "- **Artefact on noise** (4a): two-sided Sharpe ~2, *t* > 10 on a random walk; one-sided ~0.\n"
           "- **Caught** (4b): the two-sided cycle is forward-correlated; the causal one isn't.\n"
           "- **Nothing real** (4c): one-sided ≈ 0 across real ETFs.\n\n"
           "> **Signal `NONE` · Tradability `MIRAGE` · Look-ahead bias `BUSTED`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           "**No — the signal is not computable in real time.** Today's two-sided trend needs future "
           "prices; the only live version is the causal filter, which earns nothing. There is no "
           "execution to optimise — the edge has no out-of-sample existence."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — it survives every check but causality\n"
            "Sweep the smoothing λ and the cost; the two-sided edge stays large at every setting, the "
            "one-sided stays ~0. The danger of the trap is that every *ordinary* robustness check passes."
        ),
        code(
            "ls = extension.lam_sweep(close0); cs = extension.cost_robustness(close0)\n"
            "fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 4.2))\n"
            "a1.plot(ls.index, ls['two_sided_sharpe'].values, 'o-', color='#c0392b', label='two-sided')\n"
            "a1.plot(ls.index, ls['one_sided_sharpe'].values, 's--', color='#8b949e', label='one-sided')\n"
            "a1.set_xscale('log'); a1.set_xlabel('HP smoothing λ'); a1.set_ylabel('Sharpe'); a1.axhline(0, c='k', lw=.5); a1.legend(); a1.set_title('survives every λ')\n"
            "a2.plot(cs.index, cs['two_sided_sharpe'].values, 'o-', color='#c0392b', label='two-sided')\n"
            "a2.plot(cs.index, cs['one_sided_sharpe'].values, 's--', color='#8b949e', label='one-sided')\n"
            "a2.set_xlabel('cost (bps/turn)'); a2.axhline(0, c='k', lw=.5); a2.legend(); a2.set_title('survives every cost')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "**The result.** On a random walk the two-sided book clears Sharpe ~1.5–2 at *every* λ and "
            "*every* cost, while the causal book hugs zero throughout. A researcher who only ran the "
            "usual checks — costs, parameter stability — would *validate* a strategy that is 100% "
            "artefact. The one check that matters is the one rarely run: recompute the signal causally. "
            "Full run in [`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **The leak museum.** Add other full-sample transforms (two-sided Butterworth, full-sample "
            "z-score, regression-on-all-data) and measure each leak the same way.\n"
            "- **Causal HP via Kalman.** Replace the rolling-window endpoint with the Kalman-filtered "
            "local-linear-trend — smoother, still causal; does any edge appear? (We bet not.)\n"
            "- **A linter.** Automate the perturbation test — bump a future point, flag any signal whose "
            "past values move — as a CI check for the whole repo.\n\n"
            "PRs welcome — find a causal variant with a real edge, or extend the trap museum."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
