"""Build the two narrative notebooks for Study 55 (Summer-Lull).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/summer_lull_sp500_monthly.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (summer_lull/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from summer_lull import data, strategy as st
ret = data.fetch_index()                       # cache-first
sp = st.seasonal_split(ret)
sim, bh = st.sell_in_may(ret), st.buy_hold(ret)
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Sell in May is good advice?: Not supported](https://img.shields.io/badge/Sell_in_May_is_good_advice%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Summer-Lull ☀️\n### \"Sell in May and go away\" — sound seasonal, terrible advice\n\n"
           + VERDICT +
           "It's the oldest saw on Wall Street: dump your stocks in May, buy back at Halloween. And the "
           "seasonal it's built on is *real* — winter has beaten summer for nearly a century. Yet "
           "following the rule leaves you with **less money** than doing nothing, because summer still "
           "pays. A true pattern, a losing trade.\n\n"
           "> 📓 **Plain-language layer.** The t-stat and the persistence are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The saying | The data (1928–2026) |\n|---|---|\n"
           "| \"Stocks do better in winter\" | True: **+5.3%/yr** winter vs **+2.7%/yr** summer. |\n"
           "| \"So sell in May\" | But summer is **positive** — you'd skip free money. |\n"
           "| \"It beats buy-and-hold\" | Same Sharpe (0.43 vs 0.42), **a third less wealth**. |"),
        md("## 1 · The claim\n\nThe Halloween indicator (Bouman & Jacobsen 2002): hold equities Nov–Apr, "
           "step into cash May–Oct, because the summer months are weak. Quoted every spring."),
        md("## 2 · So what?\n\nIf a calendar rule this simple beat the market, everyone would run it. The "
           "honest question isn't whether winter > summer (it does) but whether *avoiding summer* helps — "
           "and that depends entirely on whether summer returns are negative or merely smaller."),
        md("## 3 · How would we even know?\n\nSplit a century of S&P returns into winter and summer, test "
           "the gap, then run the rule (cash all summer) against buy-and-hold — and check the one number "
           "that decides it: **is the summer return positive?**"),
        code("fig,ax=plt.subplots(figsize=(7,4))\n"
             "ax.bar(['winter\\n(Nov-Apr)','summer\\n(May-Oct)'],[sp['winter_ann']*100,sp['summer_ann']*100],color=['#2ea44f','#dab617'])\n"
             "ax.set_ylabel('annualised return (%)'); ax.axhline(0,color='k',lw=.8)\n"
             "ax.set_title(f\"Winter beats summer (Welch t={sp['welch_t']:.1f}) — but summer is still POSITIVE\"); plt.show()"),
        md("## 4 · The teardown\n\nSummer is the weaker season, not a bad one. So sitting it out just keeps "
           "you out of the market half the year — for no Sharpe gain."),
        code("rows={'Sell-in-May (cash in summer)':st.summary(sim),'Buy & hold':st.summary(bh)}\n"
             "t=pd.DataFrame(rows).T[['cagr','sharpe','max_drawdown']]\n"
             "display(t.style.format({'cagr':'{:.1%}','sharpe':'{:.2f}','max_drawdown':'{:.0%}'}))\n"
             "eqS=(1+sim).cumprod(); eqB=(1+bh).cumprod()\n"
             "ax=eqB.plot(label='buy & hold',lw=1.4); eqS.plot(ax=ax,label='sell in May',lw=1.4)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, 1928-2026'); ax.legend(); plt.show()"),
        md("**Read it plainly.** Two lines, same slope of risk-adjusted return — but the sell-in-May line "
           "ends lower because it skipped a positive season. Same illusion as "
           "[Hangover](../../41-hangover/) and [Last-Call](../../42-last-call/)."),
        md("## 5 · The verdict\n\n**Signal: Weak** — real, persistent, but soft (t 1.3). **Tradability: "
           "Mirage** — same Sharpe, less wealth. **Sell in May good advice?: Not supported** — summer pays."),
        md("## 6 · Could you actually trade it?\n\nYou could, trivially — and you'd underperform a "
           "do-nothing investor. If you genuinely want less risk, hold a bit less equity all year; don't "
           "make a calendar bet that forgoes a positive season."),
        md("## 7 · Going further 🚪\n\nThe quants notebook shows the seasonal persists for a century "
           "(Jacobsen-Zhang 2018) — and why that *still* doesn't make the trade work. Contrast with "
           "[Study 48 Groundhog](../../48-groundhog/), the seasonal that genuinely is tradable."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Summer-Lull — a quantitative teardown 🔬\n### Winter-vs-summer with a Welch t · the sell-in-May-vs-buy-and-hold race · a century of persistence · the exposure illusion\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test the "
           "Halloween seasonal on 98 years and show why even a durable seasonal doesn't justify the rule.\n\n"
           "> ⚠️ **Not investment advice.** S&P 500 (^GSPC) monthly TR, 1928–2026 (Yahoo). Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | winter +5.3% vs summer +2.7%/yr, Welch t 1.3 |\n"
           "| Tradability | **Mirage** | sell-in-May Sharpe 0.43 ≈ buy-and-hold 0.42, less wealth |\n"
           "| Good advice? | **Not supported** | summer is positive; skipping it can't help |\n\n"
           "> 💡 *In plain words:* a real seasonal, a self-defeating rule."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** winter returns exceed summer significantly.\n"
           "- **H₂:** the sell-in-May rule beats buy-and-hold.\n- **H₃:** the seasonal is stable over time."),
        md("## 2 · So what? — what rides on each\n\nH₁ can hold while H₂ fails — that's the whole study. A "
           "weaker-but-positive summer means the rule forgoes return for no Sharpe gain."),
        md("## 3 · How we'd know — the protocol\n\nWinter vs summer means + Welch t → sell-in-May vs "
           "buy-and-hold → pre/post-2000 persistence → confirm summer is positive."),
        md("## 4 · The teardown"),
        md("### 4.1 The seasonal split"),
        code("print({k:(round(v,2) if isinstance(v,float) else v) for k,v in sp.items()})\n"
             "print(f\"winter {sp['winter_ann']:+.1%}/yr vs summer {sp['summer_ann']:+.1%}/yr — Welch t {sp['welch_t']:.2f}\")"),
        md("> 💡 *In plain words:* winter wins, but t 1.3 is soft and summer is **positive**. H₁ weakly holds."),
        md("### 4.2 The rule vs buy-and-hold"),
        code("display(pd.DataFrame({'sell-in-May':st.summary(sim),'buy & hold':st.summary(bh)}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))"),
        md("> 💡 *In plain words:* equal Sharpe, a third less wealth — the rule only cut exposure. **H₂ rejected.**"),
        md("### 4.3 A century of persistence"),
        code("import numpy as np\n"
             "for lab,lo,hi in [('1928-1999',1900,1999),('2000-on',2000,2100)]:\n"
             "    sl=ret[(ret.index.year>=lo)&(ret.index.year<=hi)]; d=st.seasonal_split(sl)\n"
             "    print(f'{lab}: winter {d[\"winter_bp\"]:.0f} bp/mo vs summer {d[\"summer_bp\"]:.0f} bp/mo')"),
        md("> 💡 *In plain words:* the gap survives post-publication (Jacobsen-Zhang 2018) — rare for a "
           "calendar effect. **H₃ holds** — and *still* doesn't rescue the trade."),
        md("## 5 · The verdict\n\nH₁ weak, H₃ holds, H₂ rejected → Signal `WEAK`, Tradability `MIRAGE`, "
           "the advice `NOT SUPPORTED`."),
        md("## 6 · Could you trade it?\n\nNo edge over buy-and-hold. The durable seasonal is a fact about "
           "*when* returns accrue, not a reason to be in cash through a positive season."),
        md("## 7 · Going further\n\nForks: (a) a winter-overweight / summer-underweight tilt (stay "
           "invested, just lean) instead of all-or-nothing; (b) the effect across 65 markets "
           "(Jacobsen-Zhang); (c) combine with a trend filter. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
