# Study 864 — Yield-Curve Twist (Butterfly) — the teardown

The HAC regression *t*, the incremental slope-control dedup, the Q5−Q1 spread, the three-era cut, the permutation placebo, the costed timer, and the synthetic control (with its HAC over-rejection caveat).

In [1]:
R = {'start': '2002-07-31', 'end': '2026-06-30', 'n': 6011, 'fp': '5136638af800', 'ief5_t': 2.13, 'ief5_b': 3.6, 'ief21_t': 2.34, 'ief21_b': 16.9, 'ief21_r2': 1.58, 'ief63_t': 2.42, 'ief63_b': 46.8, 'ief63_r2': 4.04, 'tlt21_t': 1.12, 'tlt21_b': 16.1, 'spy21_t': -1.6, 'spy21_b': -24.7, 'inc_fly_b': 20.2, 'inc_fly_t': 1.98, 'inc_slope_t': 0.25, 'inc_level_t': -0.92, 'q5': 58.5, 'q1': 5.4, 'q_spread': 53.0, 'q_t': 1.66, 'dfly5_t': 0.65, 'dfly21_t': -0.38, 'dfly63_t': 1.56, 'era1_b': 48.7, 'era1_t': 3.32, 'era1_r2': 10.32, 'era1_n': 1782, 'era2_b': -1.8, 'era2_t': -0.18, 'era2_n': 1927, 'era3_b': 7.2, 'era3_t': 0.59, 'era3_n': 2050, 'plac_obs_t': 2.337, 'plac_sd': 1.047, 'plac_p': 0.024, 'plac_n': 500, 'timer1_active': 1.02, 'timer1_passive': 1.41, 'timer1_spread': -0.39, 'timer1_t': -0.96, 'timer1_sh_a': 0.557, 'timer1_sh_p': 0.522, 'timer5_spread': -0.61, 'timer5_sh_a': 0.439, 'sw_yr': 13.5, 'plant_t': 33.99, 'plant_spread_t': 24.7, 'null_mean_t': 0.03, 'null_sd_t': 1.37, 'null_fire': 5, 'null_seeds': 20}

## The headline — forward log return ~ lagged z(fly), HAC(NW) t

In [2]:
print(f"IEF  5d: beta {R['ief5_b']:+6.1f}  t = {R['ief5_t']:+.2f}")
print(f"IEF 21d: beta {R['ief21_b']:+6.1f}  t = {R['ief21_t']:+.2f}  R2 {R['ief21_r2']:.2f}%")
print(f"IEF 63d: beta {R['ief63_b']:+6.1f}  t = {R['ief63_t']:+.2f}  R2 {R['ief63_r2']:.2f}%")
print(f"TLT 21d: beta {R['tlt21_b']:+6.1f}  t = {R['tlt21_t']:+.2f}   (30y wing is IN the fly -> poor belly proxy)")
print(f"SPY 21d: beta {R['spy21_b']:+6.1f}  t = {R['spy21_t']:+.2f}   (insignificant, wrong sign for equities)")

IEF  5d: beta   +3.6  t = +2.13
IEF 21d: beta  +16.9  t = +2.34  R2 1.58%
IEF 63d: beta  +46.8  t = +2.42  R2 4.04%
TLT 21d: beta  +16.1  t = +1.12   (30y wing is IN the fly -> poor belly proxy)
SPY 21d: beta  -24.7  t = -1.60   (insignificant, wrong sign for equities)


## Incremental — is the butterfly just repackaged slope? (dedup)

Joint fit of forward IEF (h=21) on lagged z-scores of `fly`, `slope` (5s10s) and `level`.

In [3]:
print(f"fly  : beta {R['inc_fly_b']:+.1f} bps  t = {R['inc_fly_t']:+.2f}")
print(f"slope: t = {R['inc_slope_t']:+.2f}  (insignificant -> fly is NOT the slope repackaged)")
print(f"level: t = {R['inc_level_t']:+.2f}")
print('-> curvature keeps its loading, but its own t falls to 1.98 once level/slope held fixed.')

fly  : beta +20.2 bps  t = +1.98
slope: t = +0.25  (insignificant -> fly is NOT the slope repackaged)
level: t = -0.92
-> curvature keeps its loading, but its own t falls to 1.98 once level/slope held fixed.


## Quintile spread — Q5(high fly) − Q1(low fly) forward IEF

In [4]:
print(f"h=21: Q5 {R['q5']:+.1f}  Q1 {R['q1']:+.1f}  spread {R['q_spread']:+.1f} bps  t = {R['q_t']:+.2f}  (sub-2)")

h=21: Q5 +58.5  Q1 +5.4  spread +53.0 bps  t = +1.66  (sub-2)


## The twist (the *change* in curvature) — nothing

In [5]:
print(f"dfly -> IEF: t = {R['dfly5_t']:+.2f} / {R['dfly21_t']:+.2f} / {R['dfly63_t']:+.2f} at 5/21/63d -> no forward info")

dfly -> IEF: t = +0.65 / -0.38 / +1.56 at 5/21/63d -> no forward info


## Robustness — three eras (the spine), fly → IEF h=21

In [6]:
print(f"2002-2009: beta {R['era1_b']:+.1f}  t = {R['era1_t']:+.2f}  R2 {R['era1_r2']:.1f}%  (n={R['era1_n']})  <- all the juice")
print(f"2010-2017: beta {R['era2_b']:+.1f}  t = {R['era2_t']:+.2f}  (n={R['era2_n']})  <- dead")
print(f"2018-2026: beta {R['era3_b']:+.1f}  t = {R['era3_t']:+.2f}  (n={R['era3_n']})  <- dead")

2002-2009: beta +48.7  t = +3.32  R2 10.3%  (n=1782)  <- all the juice
2010-2017: beta -1.8  t = -0.18  (n=1927)  <- dead
2018-2026: beta +7.2  t = +0.59  (n=2050)  <- dead


## Placebo — shuffle the signal vs forward returns (500 permutations)

In [7]:
print(f"observed |t| = {R['plac_obs_t']:.3f}; permuted sd {R['plac_sd']:.3f} -> two-sided p = {R['plac_p']:.3f}")
print('  (this null destroys the regressor persistence -> an optimistic floor; see the synthetic null below)')

observed |t| = 2.337; permuted sd 1.047 -> two-sided p = 0.024
  (this null destroys the regressor persistence -> an optimistic floor; see the synthetic null below)


## The timer — can you get paid for it?

Own IEF when the lagged fly rank > 0.5, else cash; one-way cost per switch on the NAV.

In [8]:
print(f"1 bp: active {R['timer1_active']:+.2f} vs passive {R['timer1_passive']:+.2f} bps -> spread {R['timer1_spread']:+.2f} (t={R['timer1_t']:+.2f}); Sharpe {R['timer1_sh_a']:.3f} vs {R['timer1_sh_p']:.3f}")
print(f"5 bp: spread {R['timer5_spread']:+.2f} bps/day; Sharpe {R['timer5_sh_a']:.3f}  ({R['sw_yr']:.1f} switches/yr)")
print('-> loses to buy-and-hold on mean return at every cost; the Sharpe sliver is a cash-parking vol artefact.')

1 bp: active +1.02 vs passive +1.41 bps -> spread -0.39 (t=-0.96); Sharpe 0.557 vs 0.522
5 bp: spread -0.61 bps/day; Sharpe 0.439  (13.5 switches/yr)
-> loses to buy-and-hold on mean return at every cost; the Sharpe sliver is a cash-parking vol artefact.


## Synthetic positive control — unbiased, but a HAC caveat

Live: the detector must recover a planted edge and (near-)silence on the null. The null *t* has sd > 1 — the HAC test over-rejects under a persistent regressor + overlapping returns, so the real full-sample t is discounted.

In [9]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
import numpy as np
from curve_twist import data, strategy as st
planted = st.synthetic_detect(data.synthetic_daily(n_days=4000, fly_signal=0.02, seed=864)[0], 21)
print(f"planted (fly_signal=0.02): reg t = {planted['t']:+.2f}, Q5-Q1 t = {planted['t_spread']:+.2f}")
null_t = np.array([st.synthetic_detect(data.synthetic_daily(n_days=2500, fly_signal=0.0, seed=864+s)[0], 21)['t'] for s in range(8)])
print(f"null (fly_signal=0), 8 seeds: reg t mean {null_t.mean():+.2f} (sd {null_t.std(ddof=1):.2f}), |t|>=2 in {(abs(null_t)>=2).sum()}/8")
print('  sd > 1 -> HAC over-rejects; the real t=2.34 is ~1.8 effective sigma.')

planted (fly_signal=0.02): reg t = +33.99, Q5-Q1 t = +24.70


null (fly_signal=0), 8 seeds: reg t mean -0.09 (sd 1.36), |t|>=2 in 2/8
  sd > 1 -> HAC over-rejects; the real t=2.34 is ~1.8 effective sigma.


## Verdict

- **Signal — Weak.** The butterfly predicts forward belly-Treasury (IEF) returns with the right sign and a full-sample HAC *t* = **+2.34** (β = **+16.9 bps/1σ**), and it is *not* the 2s10s slope repackaged (slope control *t* = +0.25). But it **fails the era bar**: all the juice is in 2002-2009 (*t* = +3.32), dead after (*t* = -0.18 / +0.59); the quintile *t* is 1.66, the incremental *t* is 1.98, the *twist* is null, and the HAC *t* is inflated (~1.8 effective σ).
- **Tradability — Mirage.** The curvature timer loses to buy-and-hold on mean return at every cost (-0.39 to -0.61 bps/day); the Sharpe edge is a cash-parking volatility artefact.
- **Twist beyond level+slope? — Mixed.** Standing curvature holds marginal (unstable) info the slope does not; its *change* holds none.