# Study 929 — Rights Offering 🎟️

**Is the deep subscription discount on a rights issue a gift, or a dilution warning?**

When a listed company or fund runs a **rights offering**, every existing holder is handed
the right to buy new shares at a price well below the market — 20% or more below, in the
small closed-end funds and BDCs that dominate US rights activity. That looks like free
money. It usually isn't: the rights go out *pro rata*, so a holder who subscribes in full
owns the same slice of a slightly larger pie, and the share price mechanically falls by
about the value of the right. The discount is a bookkeeping choice made to guarantee
take-up, not a transfer.

We test both readings on **39 US rights offerings** by **20
issuers** (2013-05 → 2023-09), measuring abnormal returns against
**SPY** around the announcement, across the subscription period and after expiry.

*Real-tape numbers below are the frozen headline (`docs/results.md`, Fingerprint
`9acc9535dfdd`, as-of 2026-06-30); the live cells run the fast **synthetic** control and are
labelled as such.*


## 1. Why a discount you are *given* can't make you richer

Imagine a fund worth £100 a share, and every holder is offered one new share at £80 for each two they own. Afterwards the fund holds more cash per share than before but has more shares outstanding; the price settles near £93. If you subscribed, you paid £80 for something now worth £93 — but your existing two shares each fell from £100 to £93. You are exactly where you started.

The only person the discount actually *costs* is the holder who ignores the letter: they get the price fall without the cheap share. That is the whole economics of a rights issue. The interesting empirical question is what is left over — does the market read the *decision* to raise equity as bad news, and does a deeper discount signal a worse issuer?

> 🔬 **For the quants** — the theoretical ex-rights price is the pre-deal market cap plus the cash raised, divided by the post-deal share count. Yahoo's `auto_adjust` back-adjusts for splits and dividends but **not** for a rights issue, so that mechanical fall stays in the tape as a raw price drop. Any window spanning the ex-rights date therefore mixes news with arithmetic — which is why our verdict is formed on the announcement and post-expiry windows, not the subscription window.

## 2. What the tape says

Three windows around each deal, measured against SPY (so a general market move doesn't count as news):

In [1]:
R = {'start': '2005-01-03', 'end': '2026-06-30', 'n_days': 5406, 'fp': '9acc9535dfdd', 'n_events': 39, 'n_issuers': 20, 'first_deal': '2013-05', 'last_deal': '2023-09', 'ann_mean': 0.27, 'ann_t': 0.34, 'ann_hit': 49, 'ann_lo': -1.2, 'ann_hi': 1.95, 'run_mean': 1.08, 'run_t': 1.2, 'sub_mean': -2.06, 'sub_t': -2.03, 'sub_hit': 41, 'sub_lo': -4.07, 'sub_hi': -0.05, 'post_mean': 0.21, 'post_t': 0.25, 'post_hit': 59, 'post_lo': -1.51, 'post_hi': 1.87, 'deep_n': 18, 'rest_n': 21, 'sub_deep': -2.74, 'sub_rest': -1.47, 'sub_gap': -1.27, 'sub_welch': -0.6, 'sub_perm': 0.53, 'post_deep': -0.09, 'post_rest': 0.48, 'post_gap': -0.57, 'post_welch': -0.31, 'post_perm': 0.751, 'plc_sub_mean': -0.18, 'plc_sub_sd': 2.03, 'plc_sub_z': -0.93, 'plc_sub_p': 0.21, 'plc_ann_z': 0.31, 'plc_ann_p': 0.69, 'plc_post_z': 0.37, 'plc_post_p': 0.68, 'era_plc_sub_sd': 1.28, 'era_plc_sub_z': -1.6, 'era_plc_sub_p': 0.09, 'era_plc_ann_z': 0.46, 'era_plc_ann_p': 0.563, 'era_plc_post_z': 0.25, 'era_plc_post_p': 0.803, 'clu_plc_sub_sd': 2.07, 'clu_plc_sub_z': -0.91, 'clu_plc_sub_p': 0.281, 'clu_plc_ann_z': 0.34, 'clu_plc_ann_p': 0.747, 'clu_plc_post_z': 0.19, 'clu_plc_post_p': 0.768, 'jk_issuer_best': -2.5, 'jk_issuer_best_drop': 'SPE', 'jk_issuer_worst': -1.14, 'jk_issuer_worst_drop': 'CRF', 'era_e_n': 17, 'era_e_mean': -2.65, 'era_e_t': -2.07, 'era_l_n': 22, 'era_l_mean': -1.59, 'era_l_t': -1.05, 'tt28_mean': -1.07, 'tt28_t': -1.43, 'tt40_mean': -2.06, 'tt40_t': -2.03, 'tt55_mean': -1.43, 'tt55_t': -1.29, 'jit_lo_mean': -1.18, 'jit_lo_t': -1.57, 'jit_hi_mean': -2.3, 'jit_hi_t': -1.88, 'long_sharpe': 0.098, 'long_t': 0.44, 'long_cagr': 0.47, 'long_dd': -39.7, 'long_alpha': 0.03, 'long_alpha_t': 0.01, 'long_beta': 0.1, 'long_adv': -0.477, 'long_adv_t': -2.53, 'invested': 25.3, 'avg_names': 1.4, 'short_sharpe': -0.322, 'short_t': -1.43, 'short_cagr': -4.28, 'short_dd': -73.6, 'short_alpha': -2.6, 'short_alpha_t': -1.02, 'cln_long_sharpe': 0.448, 'cln_long_t': 2.03, 'cln_long_cagr': 3.17, 'cln_long_dd': -22.1, 'cln_long_alpha': 2.98, 'cln_long_alpha_t': 1.79, 'cln_long_beta': 0.04, 'cln_long_adv': -0.127, 'cln_long_adv_t': -2.05, 'cln_invested': 13.5, 'cln_avg_names': 1.1, 'cln_short_sharpe': -0.73, 'cln_short_t': -3.24, 'cln_short_dd': -71.4, 'cln_short_alpha': -5.12, 'cln_short_alpha_t': -3.02, 'spy_sharpe': 0.575, 'cost0': 0.168, 'cost10': 0.14, 'cost25': 0.098, 'cost50': 0.028, 'cost100': -0.11, 'borrow0': -0.256, 'borrow100': -0.278, 'borrow300': -0.322, 'borrow800': -0.431, 'cln_borrow0': -0.677, 'cln_borrow800': -0.818, 'syn_ann': -6.62, 'syn_ann_t': -7.88, 'syn_sub': -9.42, 'syn_sub_t': -5.73, 'syn_post': 5.81, 'syn_post_t': 4.96, 'syn_null_post': -0.19, 'syn_null_post_sd': 1.4, 'syn_null_ann': 0.03, 'syn_null_fire': 0, 'dropped_no_tape': 'CUBA, NHF, ENZN, SPLP, TUEM'}
rows = [('announcement (-1..+5)', R['ann_mean'], R['ann_t'], R['ann_hit']),
        ('subscription (+1..+28)', R['sub_mean'], R['sub_t'], R['sub_hit']),
        ('post-expiry (+29..+49)', R['post_mean'], R['post_t'], R['post_hit'])]
print(f"{'window':24s}{'mean':>9s}{'t':>9s}{'hit':>8s}")
for name, m, t, h in rows:
    print(f'{name:24s}{m:+8.2f}%{t:+9.2f}{h:7d}%')
print()
print(f"SPY-relative, {R['n_events']} deals, {R['n_issuers']} issuers, "
      f"as-of {R['end']}")

window                       mean        t     hit
announcement (-1..+5)      +0.27%    +0.34     49%
subscription (+1..+28)     -2.06%    -2.03     41%
post-expiry (+29..+49)     +0.21%    +0.25     59%

SPY-relative, 39 deals, 20 issuers, as-of 2026-06-30


**The announcement is a non-event.** +0.27% with a *t* of +0.34 and a 49% hit rate — a coin toss. The textbook −3% reaction to a seasoned equity issue (Asquith & Mullins, 1986) simply does not show up here, which makes sense: these issuers are portfolios of marked-to-market securities, so there is little private information for the market to be alarmed by.

**And nobody is compensated afterwards.** The 20 sessions after the deal closes return +0.21% (*t* = +0.25). If the discount were a gift, this is where you would collect it.

## 3. Do the *deepest* discounts behave differently?

We hand-labelled each deal `deep`, `moderate` or `shallow`. If a deep discount were a warning, the deep bucket should drift worse; if it were a gift, better.

In [2]:
print('post-expiry return, by discount depth')
print(f"  deep     (n={R['deep_n']}): {R['post_deep']:+.2f}%")
print(f"  the rest (n={R['rest_n']}): {R['post_rest']:+.2f}%")
print(f"  gap: {R['post_gap']:+.2f}%   -- shuffle the labels at random and you "
      f"beat that gap {R['post_perm']*100:.0f}% of the time")

post-expiry return, by discount depth
  deep     (n=18): -0.09%
  the rest (n=21): +0.48%
  gap: -0.57%   -- shuffle the labels at random and you beat that gap 75% of the time


Nothing. A random relabelling of the bands reproduces the gap three times out of four. The depth of the discount carries no information about what happens next.

## 4. The one number that looked real

Across the subscription period the deals lose **-2.06%** against SPY with a *t* of **-2.03** — nominally significant. Two reasons not to believe it.

**First**, that window is exactly where the mechanical ex-rights drop lives (section 1), so a fall there is arithmetic, not news.

**Second**, it is not robust. Drop one issuer's five deals and the *t* falls to -1.14; split the sample at 2018 and the recent half gives -1.05; change the assumed expiry date from 40 to 28 days and it is -1.43; shift the (month-precision) anchors by a fortnight and it never clears −2 with room to spare. A result that needs one issuer, one decade and one guessed date to exist is not a finding.

> 🔬 **For the quants — and a caution about our own favourite chart.** Re-run the study on 300 sets of *random* dates and the mean abnormal return over a 28-day window wanders with a standard deviation of 2.03%, which would make our result a *z* of -0.93 — a nothing. But that placebo draws its dates from the whole 2005-2026 tape, including 2008 and 2020, regimes in which none of these deals was announced: it is a rigged-easy yardstick. Restrict the draws to the years the deals actually happened and the dispersion falls to 1.28%, giving *z* = -1.60 (*p* = 0.09) — still not significant, but not the rout the first version implied. We quote the harder number.

## 5. Could you trade it either way?

Buy every announcing name the day *after* the news and hold 49 sessions, 25 bps one-way, everything else in T-bills. Because that holding period straddles the ex-rights date — where the price mechanically falls for reasons that are arithmetic, not news — we also run the book over the clean stretch *after* the deal closes, which is the version that gives the discount its best shot:

In [3]:
print(f"long,  full  window : excess Sharpe {R['long_sharpe']:+.3f}, "
      f"worst loss {R['long_dd']:.1f}%")
print(f"long,  clean window : excess Sharpe {R['cln_long_sharpe']:+.3f}, "
      f"worst loss {R['cln_long_dd']:.1f}%")
print(f"short, full  window : excess Sharpe {R['short_sharpe']:+.3f}")
print(f"just holding SPY    : excess Sharpe {R['spy_sharpe']:+.3f}")
print()
print('...but strip out the market exposure the long book rents while it is in:')
print(f"   its edge over SPY is {R['cln_long_alpha']:+.2f}%/yr "
      f"(t = {R['cln_long_alpha_t']:+.2f}) -- inside the noise")
print(f"the book is live only {R['cln_invested']:.1f}% of days, "
      f"averaging {R['cln_avg_names']:.1f} names")

long,  full  window : excess Sharpe +0.098, worst loss -39.7%
long,  clean window : excess Sharpe +0.448, worst loss -22.1%
short, full  window : excess Sharpe -0.322
just holding SPY    : excess Sharpe +0.575

...but strip out the market exposure the long book rents while it is in:
   its edge over SPY is +2.98%/yr (t = +1.79) -- inside the noise
the book is live only 13.5% of days, averaging 1.1 names


Neither direction works. On the full window the long book is indistinguishable from cash while carrying a 40% drawdown in a handful of illiquid funds. On the clean window it *looks* better — Sharpe +0.448 — but that is the stock market, not the discount: it is long ordinary equity an eighth of the time, and once you charge it for that borrowed exposure the edge is +2.98% a year with a *t* of +1.79. It still loses to simply owning SPY. The short book just loses money, at every borrow rate we tried, on both windows.

## 6. Live check — the machinery does work (offline **synthetic** data)

Before believing a null result, prove the detector can see something. We plant a rights effect into a synthetic panel — a drop on announcement, a slide through the subscription period, a bounce afterwards — and check the same code finds it. **These are synthetic numbers, not the real tape.**

In [4]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath(os.path.join('..','..','..')))
from rights_offering import data, strategy as st
import numpy as np
px, ev, truth = data.synthetic_panel(signal_strength=1.0, seed=929)
d = st.synthetic_detect(px, ev)
print(f"SYNTHETIC planted world ({d['n']} deals):")
for w in ('announce', 'subscription', 'post_expiry'):
    print(f"   {w:13s}{d[w+'_mean_pct']:+7.2f}%  (t={d[w+'_t']:+6.2f})")
nulls = {w: [] for w in ('announce', 'subscription', 'post_expiry')}
for s in range(8):
    p0, e0, _ = data.synthetic_panel(signal_strength=0.0, seed=929 + s)
    d0 = st.synthetic_detect(p0, e0)
    for w in nulls:
        nulls[w].append(d0[w + '_mean_pct'])
print('SYNTHETIC null world (effect switched off), averaged over 8 seeds:')
for w, vals in nulls.items():
    print(f"   {w:13s}{np.mean(vals):+7.2f}%  (spread {np.std(vals, ddof=1):.2f}%)")

SYNTHETIC planted world (37 deals):
   announce       -6.62%  (t= -7.88)
   subscription   -9.42%  (t= -5.73)
   post_expiry    +5.81%  (t= +4.96)


SYNTHETIC null world (effect switched off), averaged over 8 seeds:
   announce       +0.10%  (spread 0.83%)
   subscription   -0.66%  (spread 1.68%)
   post_expiry    +0.07%  (spread 1.46%)


The detector fires hard on a planted effect and, averaged across seeds, sits on zero when there is none. (Averaging matters: any single null seed can throw a two-sigma window — which is precisely the trap the real tape sets in section 4.) So the flat real-tape result is a fact about rights offerings, not a broken harness.

## Verdict

- **Signal — None.** No announcement reaction (+0.27%, *t* = +0.34), no post-expiry compensation (+0.21%, *t* = +0.25), no gradient in the depth of the discount (permutation *p* = 0.75). The single significant number lives in the window contaminated by mechanical dilution, misses the fair placebo (*p* = 0.09) and does not survive a jackknife, an era cut, a timetable sweep or a fortnight of anchor jitter.
- **Tradability — Mirage.** Long excess Sharpe +0.098 on the full window, +0.448 on the clean one — but the clean version's edge over the market is +2.98%/yr (*t* +1.79), and both lose to SPY's +0.575. The short is negative at every borrow rate.
- **Three honest caveats, and they all cut the same way.** The event list is hand-compiled and **month-precision** — which means the book is sometimes long *before* the news is public, a look-ahead that can only help it. Five further deals (CUBA, NHF, ENZN, SPLP, TUEM) have no retrievable tape at all, so the sample is **survivor-biased towards deals that ended well**. And the dilution artefact sits inside the only negative window. Every bias we know of pushes towards finding an effect, and there is still none.