"""Beat-7 worked complement on the real tape — the parameter-robustness test.

A folk rule that only pays at one hand-picked parameter pair, on one hand-picked asset, is a data-mined
artefact. So we sweep the (fast, slow) grid on every instrument and report the fraction of pairs that
beat buy-and-hold — the spread between the cherry-picked S&P and the rest is the whole story. Writes
`docs/extension.md`.

    python examples/extension.py            # cache-only
    python examples/extension.py --fetch    # populate the close cache first (network)
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from fools_gold import data, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()

    closes = data.fetch_closes(fetch=args.fetch)
    if not closes:
        print("[skip] no cached closes -- run with --fetch first.")
        return
    closes = {tk: as_of(c.to_frame(), DEFAULT_AS_OF)["close"] for tk, c in closes.items()}
    allc = pd.DataFrame(closes)
    fp = fingerprint(allc.round(6))

    rows = []
    for tk, c in closes.items():
        pg = extension.param_grid(c, cost_bps=2.0)
        rows.append((tk, pg["frac_beat_buy_hold"], pg["best_pair"], pg["best_gain"], pg["mean_gain"]))
        print(f"{tk}: {pg['frac_beat_buy_hold']:.0%} of pairs beat B&H, mean gain {pg['mean_gain']:+.3f}")
    rows.sort(key=lambda r: -r[1])

    _write(OUT, rows, fp, DEFAULT_AS_OF, allc.index.min().date(), allc.index.max().date())
    print(f"\nwrote {OUT}")


def _write(path, rows, fp, asof, lo, hi):
    body = "\n".join(
        f"| {tk} | {frac:.0%} | {best} | {bg:+.2f} | {mg:+.3f} |"
        for (tk, frac, best, bg, mg) in rows
    )
    fracs = np.array([r[1] for r in rows])
    text = f"""# Beat 7 — worked complement: the parameter-robustness test (Study 21, Fools-Gold)

*Generated by [`examples/extension.py`](../examples/extension.py) on the cached ETF closes. As-of
**{asof}**, {lo} → {hi}, fingerprint `{fp}`.*

## Was 50/200 informative — or just the luckiest cell?

For each instrument we sweep a grid of (fast, slow) crossover pairs and ask how many beat buy-and-hold
on a net-of-cost Sharpe basis. A real edge would help across most pairs and most assets; a data-mined
one helps only where a strong trend happened to live.

| asset | % of pairs beating B&H | best pair | best gain | mean gain |
|---|---|---|---|---|
{body}

The beat-rate swings from near-total on the trending US equity index to **zero** on others — a range
of **{fracs.min():.0%}–{fracs.max():.0%}**. That spread is the tell: the crossover isn't an edge, it's
a trend filter that looks brilliant on whatever asset trended hardest over the sample. Pick the asset
and the parameters after the fact and you can always tell a golden-cross success story; ask it to work
*out of sample, across instruments, at an unchosen parameter*, and it's a coin flip.

**Takeaway.** `WEAK` / `MIRAGE` / `Not supported` survives the worked complement — the complement is
what exposes the cherry-pick behind the folklore.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
