"""Real-data run — does the golden cross beat buy-and-hold, and does it generalise?

One rule, four questions (the offline core proves the machine; this points it at the market):

  * **Is the crossover informative?** A Newey-West t on the golden-minus-death next-day spread.
  * **Does it beat buy-and-hold?** Net-of-cost Sharpe of the long/flat timing book vs simply holding —
    across a basket, not just the one asset everyone quotes.
  * **Is it more than de-risking?** Alpha & beta vs buy-and-hold, and a risk-matched cash-blend control.
  * **Does it generalise?** The fraction of assets (and of parameter pairs) where it actually helps.

    python examples/verify.py --fetch     # populate the close cache (network)
    python examples/verify.py             # offline, cache-only

Network lives only behind `--fetch`. The sample is pinned with `quantlab.repro.as_of` and fingerprinted.
Data choice: split-only closes (the crossover acts on the price path; the benchmark is charged the same
series) — stated, not hidden.
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from fools_gold import data, cross, strategy, decompose, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "results.md")
COST_BPS = 2.0
HEADLINE = "SPY"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()

    closes = data.fetch_closes(fetch=args.fetch)
    if not closes:
        print("[skip] no cached closes -- run with --fetch first.")
        return
    closes = {tk: as_of(c.to_frame(), DEFAULT_AS_OF)["close"] for tk, c in closes.items()}

    per = {}
    for tk, c in closes.items():
        cmp = strategy.compare(c, cost_bps=COST_BPS)
        sp = decompose.spread_tstat(c)
        per[tk] = {"timing": cmp["timing"]["sharpe"], "bh": cmp["buy_hold"]["sharpe"],
                   "gain": cmp["sharpe_gain"], "expo": cmp["avg_exposure"], "t": sp["t_stat"]}
    gains = np.array([v["gain"] for v in per.values()])

    head = closes[HEADLINE]
    sp_h = decompose.spread_tstat(head)
    vb_h = decompose.vs_buy_hold(head, cost_bps=COST_BPS)
    rm_h = decompose.risk_matched(head, cost_bps=COST_BPS)
    pg_h = extension.param_grid(head, cost_bps=COST_BPS)
    # generalization: worst asset's grid
    worst_tk = min(per, key=lambda k: per[k]["gain"])
    pg_w = extension.param_grid(closes[worst_tk], cost_bps=COST_BPS)

    df = pd.DataFrame({tk: head.loc[head.index] for tk in [HEADLINE]})  # for fingerprint of headline
    allc = pd.DataFrame({tk: c for tk, c in closes.items()})
    fp = fingerprint(allc.round(6))

    print(f"cross-asset: {(gains>0).sum()}/{len(gains)} beat B&H, median gain {np.median(gains):+.3f}")
    print(f"{HEADLINE} spread t {sp_h['t_stat']:+.1f}, grid beat-rate {pg_h['frac_beat_buy_hold']:.0%}; "
          f"{worst_tk} grid beat-rate {pg_w['frac_beat_buy_hold']:.0%}")

    _write(OUT, dict(per=per, gains=gains, head=HEADLINE, sp=sp_h, vb=vb_h, rm=rm_h,
                     pg=pg_h, worst_tk=worst_tk, pg_w=pg_w, fp=fp,
                     lo=allc.index.min().date(), hi=allc.index.max().date(), n=len(allc)), DEFAULT_AS_OF)
    print(f"\nwrote {OUT}")


def _verdict(d):
    beat = (d["gains"] > 0).mean()
    sig = "REAL" if (d["sp"]["t_stat"] > 2 and beat > 0.6) else "WEAK"
    trad = "INVESTABLE" if (np.median(d["gains"]) > 0.1 and beat > 0.6) else "MIRAGE"
    generalises = "CONFIRMED" if beat > 0.6 else "Not supported"
    return sig, trad, generalises


def _write(path, d, asof):
    sig, trad, gen = _verdict(d)
    per_rows = "\n".join(
        f"| {tk} | {v['timing']:+.2f} | {v['bh']:+.2f} | {v['gain']:+.2f} | {v['expo']:.0%} | {v['t']:+.1f} |"
        for tk, v in sorted(d["per"].items(), key=lambda kv: -kv[1]["gain"])
    )
    beat = int((d["gains"] > 0).sum()); n = len(d["gains"])
    text = f"""# Results — Study 21 (Fools-Gold) on real ETFs

*Generated by [`examples/verify.py`](../examples/verify.py). Daily split-only closes; the strategy is
the long/flat 50/200 moving-average crossover (long while the 50-day MA is above the 200-day, cash
otherwise) vs buy-and-hold, {COST_BPS:.0f} bp per position change. The offline core proves the machinery
on a synthetic trending tape (and a driftless null); this is the measurement on the market. As-of
**{asof}**; match the fingerprint below. Split-only closes — stated, not hidden.*

## The verdict, earned — Signal `{sig}` · Tradability `{trad}` · Generalises? `{gen}`

On the one asset everyone quotes — the S&P 500 — the golden cross looks plausible: golden-state days do
out-return death-state days (Newey-West *t* = **{d['sp']['t_stat']:+.1f}**) and the timing book edges
buy-and-hold. But it is **fool's gold**. Across **{n}** liquid instruments it beats buy-and-hold on only
**{beat}/{n}** (median Sharpe gain **{np.median(d['gains']):+.2f}**); on {d['head']} the win is mostly
*less exposure* (beta **{d['vb']['beta']:.2f}**, alpha *t* = **{d['vb']['alpha_t']:+.1f}**), and a plain
cash blend at the same average exposure captures most of it. And it does not generalise: **{d['pg']['frac_beat_buy_hold']:.0%}**
of (fast, slow) pairs beat buy-and-hold on {d['head']} but **{d['pg_w']['frac_beat_buy_hold']:.0%}** on
{d['worst_tk']}. The "golden cross signals a bull market" folklore is a crude trend filter that
de-risks — re-discovered on the one trending index people cherry-pick.

## Data stamp

- **Basket** ({n} ETFs): {d['lo']} → {d['hi']}, fingerprint `{d['fp']}`

## Crossover timing vs buy-and-hold, per instrument

| asset | timing Sharpe | buy-&-hold Sharpe | gain | avg exposure | golden−death *t* |
|---|---|---|---|---|---|
{per_rows}

Only **{beat} of {n}** beat buy-and-hold; the median gain is **{np.median(d['gains']):+.2f}** — a coin
flip, slightly negative. The significant golden−death spread shows up on the big US equity indices (a
strong secular uptrend) and vanishes elsewhere.

## On {d['head']}: is it skill or just less exposure?

- Golden−death spread Newey-West *t* = **{d['sp']['t_stat']:+.1f}** (real on this index).
- vs buy-and-hold: beta **{d['vb']['beta']:.2f}** (out of the market a lot), alpha
  **{d['vb']['alpha_ann_pct']:+.1f}%/yr** (*t* = {d['vb']['alpha_t']:+.1f}).
- Risk-matched: a constant cash blend at the timing book's average exposure
  (**{d['rm']['avg_exposure']:.0%}**) has Sharpe **{d['rm']['cash_blend_sharpe']:+.2f}** vs the timing
  book's **{d['rm']['timing_sharpe']:+.2f}** — an edge of only **{d['rm']['sharpe_edge_over_blend']:+.2f}**.

## Does it generalise? (parameter grid)

- {d['head']}: **{d['pg']['frac_beat_buy_hold']:.0%}** of (fast, slow) pairs beat buy-and-hold, best
  {d['pg']['best_pair']} (gain {d['pg']['best_gain']:+.2f}).
- {d['worst_tk']}: **{d['pg_w']['frac_beat_buy_hold']:.0%}** beat buy-and-hold (best gain
  {d['pg_w']['best_gain']:+.2f}).

A rule that works on 76% of parameters for one asset and 0% for another isn't an edge — it's a strong
trend on that one asset, found by a filter. Signal `{sig}`, Tradability `{trad}`, Generalises? `{gen}`.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
