"""Notebook builder for Study 987 — Gold's Loud Cousin.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Gold's Loud Cousin \U0001F948
### If silver is just gold on leverage, why not hold more gold instead?

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

Everyone in the metals trade says it: silver is gold with the volume turned up. That is a
checkable claim, and it has a sharp consequence — if it is exactly true then silver is
redundant, and you should hold gold and size it up instead.

> \U0001F4D3 **This is the plain-language layer.** The rolling betas, the residual factor
> loadings and the drag arithmetic are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is silver correlated with gold? | Strongly. |
| Is its beta about 1.7-1.8? | On average, yes. |
| Is that beta *stable*? | No — it roams across a range wider than the number itself. |
| Would levered gold have replaced silver? | No. The tracking error is bigger than most people's whole risk budget. |
"""
        ),
        md(
            r"""

## 1 · The claim
"""
        ),
        code(
            r"""
from loudcousin import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
common = rets[[data.GOLD, data.SILVER, data.DOLLAR, data.TIPS, data.INDUSTRIAL,
               data.CASH]].dropna()
g, s = common[data.GOLD], common[data.SILVER]
b = st.full_sample_beta(s, g)
print(f"as-of {data.AS_OF} | {len(common):,} sessions, "
      f"{common.index[0].date()} -> {common.index[-1].date()}")
print(f"gold vol {g.std() * np.sqrt(252):.1%}   silver vol {s.std() * np.sqrt(252):.1%}")
print(f"silver = {b['alpha_ann']:+.2%}/yr + {b['beta']:.3f} x gold   R2 {b['r2']:.1%}")
"""
        ),
        md(
            r"""

An R² in the sixties sounds like a lot. Turn it around: roughly a third of silver's movement has
nothing to do with gold at all. That third is the whole study.
"""
        ),
        md(
            r"""

## 2 · The beta will not sit still
"""
        ),
        code(
            r"""
rb = st.rolling_beta(s, g, 252).dropna()
fig, ax = plt.subplots(figsize=(12, 4.5))
ax.plot(rb.index, rb, lw=1.3, color="#2ea44f")
ax.axhline(b["beta"], color="k", ls="--", lw=1.5,
           label=f"full-sample beta {b['beta']:.2f}")
ax.fill_between(rb.index, rb.min(), rb.max(), alpha=0.05, color="#2ea44f")
ax.set_ylabel("trailing 1-year beta of silver on gold"); ax.legend()
ax.set_title(f"Range {rb.min():.2f} to {rb.max():.2f} — wider than the average itself")
plt.show()
print(st.rolling_beta_table(s, g).round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Anyone quoting "silver's beta is 1.8" is quoting the midpoint of
> that band, which is a fact about the sample rather than a property of the asset.
"""
        ),
        md(
            r"""

## 3 · What is the other third made of?
"""
        ),
        code(
            r"""
resid = st.residuals(s, g)
factors = pd.DataFrame({"dollar": common[data.DOLLAR], "real_rates": common[data.TIPS],
                        "industrial": common[data.INDUSTRIAL]}).reindex(resid.index)
load = st.residual_loadings(resid, factors)
print(load.round(4).to_string())
uni = load[~load.index.str.contains(r"\(joint\)")]
fig, ax = plt.subplots(figsize=(9, 4))
uni["t"].plot.bar(ax=ax, color="#2ea44f")
ax.axhline(0, color="k", lw=1)
for y in (-2, 2):
    ax.axhline(y, ls="--", color="#c0392b", lw=1)
ax.set_ylabel("t of the loading on silver's non-gold residual")
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
"""
        ),
        md(
            r"""

About half of silver demand is industrial. None of gold's is. That is the most plausible place
for the leverage story to break, and it is where this chart is looking.
"""
        ),
        md(
            r"""

## 4 · The thing nobody accounts for

Holding "2× gold" is not holding gold and doubling the return. You rebalance to 2× every day, so
you compound twice the *daily* move — and that costs you, mechanically, `β(β−1)σ²/2` a year.
"""
        ),
        code(
            r"""
gv = g.std() * np.sqrt(252)
for beta in (1.0, 1.5, 1.75, 2.0, 2.5, 3.0):
    print(f"{beta:.2f}x gold: volatility drag {st.leverage_drag(beta, gv):.2%} per year")
print(f"\n(gold's volatility over this sample: {gv:.1%})")
"""
        ),
        md(
            r"""

## 5 · So would the replication have worked?
"""
        ),
        code(
            r"""
rep = st.replication_backtest(s, g, common[data.CASH], financing_spread=0.005,
                              cost_bps=1.0)
curves = (1 + rep["returns"]).cumprod()
fig, ax = plt.subplots(figsize=(11, 5))
curves.plot(ax=ax, logy=True, color=["#8b949e", "#2ea44f"])
ax.set_ylabel("growth of $1 (log scale)")
ax.legend(["silver", f"{rep['beta_used']:.2f}x gold, financed"], title="")
ax.set_title(f"correlation {rep['correlation']:.2f}, tracking error "
             f"{rep['tracking_error_ann']:.1%}/yr")
plt.show()
for k in ("silver", "replica"):
    st_ = rep[k]
    print(f"{k:8s} CAGR {st_['cagr']:+.2%}  vol {st_['vol']:.1%}  "
          f"Sharpe {st_['sharpe']:+.2f}  maxDD {st_['max_dd']:.1%}")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Busted.** Regressed on gold over 4,801 sessions, silver's beta is **1.45** (±0.03) with an R² of 62% — so about 38% of silver's variance is *not* gold. That leftover is not noise. Its annualised volatility is 20.3%, and it loads on outside factors with a largest |*t*| of **10.58** (on industrial). Nor is the beta a constant: over rolling one-year windows it ranges 0.94 to 2.15, a spread of **86% of its own mean**, and it is 1.29 on gold's up days against 1.57 on its down days. 'Silver is levered gold' is a reasonable first approximation and a poor second one.

**Tradability: Useful.** Holding a 1.45× daily-rebalanced gold position instead of silver, financed at cash plus 0.5%, tracked it with a correlation of 0.79 and an annualised tracking error of **20.3%** — which is not tracking, it is a different asset. Over 19 years silver compounded at +7.7% against the replica's +11.9% (Sharpe 0.39 vs 0.56). Part of that gap is pure arithmetic: levering a 18%-vol asset 1.45× costs about **1.1% a year** in volatility drag, before financing and before costs.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Physical demand data.** The *World Silver Survey* splits demand into industrial, investment
  and jewellery. Photovoltaics went from a rounding error to a fifth of silver demand across
  this sample — a daily price feed cannot see that, and it is probably the main story.
- **Monthly rebalancing** instead of daily would cut the volatility drag substantially and is
  the fairer version of the replication.
- **The miners lever it again.** GDX and SIL are levered bets on levered bets, with their own
  residual — a natural next study.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Gold's Loud Cousin — a quantitative teardown \U0001F52C
### Rolling and regime betas · residual factor hunt · β(β−1)σ²/2 · a financed replication

![Signal: Busted](https://img.shields.io/badge/Signal-Busted-c0392b?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Three separate
questions get collapsed into one in most versions of this argument: whether the beta is stable,
whether the residual is an asset, and whether the replication survives contact with financing
and volatility drag.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from loudcousin import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
common = rets[[data.GOLD, data.SILVER, data.DOLLAR, data.TIPS, data.INDUSTRIAL,
               data.CASH]].dropna()
g, s = common[data.GOLD], common[data.SILVER]
b = st.full_sample_beta(s, g)
print(f"as-of {data.AS_OF} | {len(common):,} sessions, "
      f"{common.index[0].date()} -> {common.index[-1].date()}")
print(f"gold vol {g.std() * np.sqrt(252):.1%}   silver vol {s.std() * np.sqrt(252):.1%}")
print(f"silver = {b['alpha_ann']:+.2%}/yr + {b['beta']:.3f} x gold   R2 {b['r2']:.1%}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Busted | Regressed on gold over 4,801 sessions, silver's beta is **1.45** (±0.03) with an R² of 62% — so about 38% of silver's variance is *not* gold. That leftover is not noise. Its annualised volatility is 20.3%, and it loads on outside factors with a largest |*t*| of **10.58** (on industrial). Nor is the beta a constant: over rolling one-year windows it ranges 0.94 to 2.15, a spread of **86% of its own mean**, and it is 1.29 on gold's up days against 1.57 on its down days. 'Silver is levered gold' is a reasonable first approximation and a poor second one. |
| **Tradability** | Useful | Holding a 1.45× daily-rebalanced gold position instead of silver, financed at cash plus 0.5%, tracked it with a correlation of 0.79 and an annualised tracking error of **20.3%** — which is not tracking, it is a different asset. Over 19 years silver compounded at +7.7% against the replica's +11.9% (Sharpe 0.39 vs 0.56). Part of that gap is pure arithmetic: levering a 18%-vol asset 1.45× costs about **1.1% a year** in volatility drag, before financing and before costs. |

> \U0001F4A1 **In plain words.** Silver is levered gold in roughly the sense that a dog is a
> levered cat: correlated, similar in outline, and not a substitute.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁ (the folklore).** `silver = β × gold + ε` with β constant and ε white noise.
- **H₂ (stability).** β's rolling range is small relative to β.
- **H₃ (residual).** ε loads on nothing observable — not the dollar, not real rates, not
  industrial activity.
- **H₄ (replication).** A financed β× gold position tracks silver closely enough to substitute
  for it, after the `β(β−1)σ²/2` drag.
"""
        ),
        md(
            r"""

## 2 · The teardown

### 2.1 Beta, four windows and five regimes
"""
        ),
        code(
            r"""
print(st.rolling_beta_table(s, g).round(3).to_string())
print()
print(st.beta_by_regime(s, g).round(3).to_string())
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
for w, c in zip((63, 252, 756), ("#c0392b", "#2ea44f", "#1f6feb")):
    st.rolling_beta(s, g, w).dropna().plot(ax=axes[0], lw=1.1, color=c, label=f"{w}d",
                                           alpha=0.8)
axes[0].axhline(b["beta"], color="k", ls="--", lw=1.5)
axes[0].set_ylabel("beta"); axes[0].legend(fontsize=8, title="window")
reg = st.beta_by_regime(s, g)
reg["beta"].plot.bar(ax=axes[1], color="#2ea44f", yerr=reg["se"] * 2)
axes[1].axhline(b["beta"], color="k", ls="--", lw=1.5)
axes[1].set_ylabel("beta"); plt.setp(axes[1].get_xticklabels(), rotation=20, ha="right",
                                     fontsize=8)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.2 The residual, diagnosed
"""
        ),
        code(
            r"""
resid = st.residuals(s, g)
print(pd.Series(st.residual_diagnostics(resid)).round(4).to_string())
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
axes[0].plot(resid.index, (1 + resid).cumprod(), lw=1.3, color="#2ea44f")
axes[0].set_ylabel("cumulative non-gold part of silver")
axes[0].set_title("If this were noise it would be a flat, aimless line")
axes[1].hist(resid * 100, bins=120, color="#2ea44f", edgecolor="white")
axes[1].axvline(0, color="k", lw=1)
axes[1].set_xlabel("daily residual (%)")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

### 2.3 Does it load on anything?
"""
        ),
        code(
            r"""
factors = pd.DataFrame({"dollar": common[data.DOLLAR],
                        "real_rates": common[data.TIPS],
                        "industrial": common[data.INDUSTRIAL]})
if data.COPPER in rets.columns and rets[data.COPPER].notna().sum() > 1000:
    factors["copper"] = rets[data.COPPER]
load = st.residual_loadings(resid, factors.reindex(resid.index))
print(load.round(4).to_string())
"""
        ),
        code(
            r"""
# the same question through time, since silver's industrial share has grown a lot
ind = common[data.INDUSTRIAL]
roll = pd.Series(
    [st.full_sample_beta(resid.iloc[i - 504:i],
                         ind.reindex(resid.index).iloc[i - 504:i]).get("t_vs_zero", np.nan)
     if i >= 504 else np.nan for i in range(len(resid))], index=resid.index)
fig, ax = plt.subplots(figsize=(12, 4.5))
ax.plot(roll.index, roll, lw=1.3, color="#2ea44f")
ax.axhline(0, color="k", lw=1)
for y in (-2, 2):
    ax.axhline(y, ls="--", color="#c0392b", lw=1)
ax.set_ylabel("rolling 2-year t: residual on industrials")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Photovoltaic demand went from negligible to about a fifth of
> silver consumption across this sample. If the industrial loading strengthens over time, that
> is the most likely reason — and it means the "levered gold" description was more accurate
> twenty years ago than it is now.
"""
        ),
        md(
            r"""

### 2.4 Volatility drag, in closed form and in the data
"""
        ),
        code(
            r"""
gv = g.std() * np.sqrt(252)
betas = np.linspace(0.5, 3.0, 26)
predicted = [st.leverage_drag(bb, gv) for bb in betas]
actual = []
for bb in betas:
    lev = st.levered_position(g, bb, common[data.CASH], financing_spread=0.0, cost_bps=0.0)
    yrs = len(lev) / 252
    realised = (1 + lev).prod() ** (1 / yrs) - 1
    naive = bb * ((1 + g).prod() ** (1 / yrs) - 1)
    actual.append(naive - realised)
fig, ax = plt.subplots(figsize=(9.5, 5))
ax.plot(betas, np.array(predicted) * 100, lw=2, color="#c0392b",
        label="closed form: beta(beta-1)sigma^2/2")
ax.plot(betas, np.array(actual) * 100, "o", ms=4, color="#2ea44f",
        label="measured on gold's actual path")
ax.axhline(0, color="k", lw=1); ax.axvline(1, color="#8b949e", lw=1)
ax.set_xlabel("leverage"); ax.set_ylabel("annual drag (%)"); ax.legend()
plt.show()
"""
        ),
        md(
            r"""

### 2.5 The replication, swept over leverage and financing
"""
        ),
        code(
            r"""
rows = []
for beta in (1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5):
    for fin in (0.0, 0.005, 0.015):
        r = st.replication_backtest(s, g, common[data.CASH], beta=beta,
                                    financing_spread=fin, cost_bps=1.0)
        rows.append({"beta": beta, "financing": fin, "cagr": r["replica"]["cagr"],
                     "sharpe": r["replica"]["sharpe"], "te": r["tracking_error_ann"],
                     "corr": r["correlation"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d.pivot(index="beta", columns="financing", values="cagr").mul(100).plot(ax=axes[0], marker="o")
rep = st.replication_backtest(s, g, common[data.CASH], financing_spread=0.005, cost_bps=1.0)
axes[0].axhline(rep["silver"]["cagr"] * 100, color="k", ls="--", lw=1.5, label="silver")
axes[0].set_ylabel("replica CAGR (%)"); axes[0].legend(fontsize=8, title="financing spread")
d.pivot(index="beta", columns="financing", values="te").mul(100).plot(ax=axes[1], marker="o")
axes[1].set_ylabel("tracking error vs silver (%/yr)"); axes[1].legend(fontsize=8, title="")
plt.tight_layout(); plt.show()
d.round(4).to_string(index=False)
"""
        ),
        md(
            r"""

### 2.6 The ratio trade
"""
        ),
        code(
            r"""
ratio = st.gold_silver_ratio(px[data.GOLD], px[data.SILVER])
fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
axes[0].plot(ratio.index, ratio, lw=1.3, color="#f0b429")
axes[0].axhline(1.0, color="k", lw=1)
axes[0].set_ylabel("gold / silver (indexed)")
z = ((np.log(ratio) - np.log(ratio).rolling(252).mean())
     / np.log(ratio).rolling(252).std())
axes[1].plot(z.index, z, lw=1.1, color="#2ea44f")
for y in (-2, 0, 2):
    axes[1].axhline(y, color="k" if y == 0 else "#c0392b", lw=1,
                    ls="-" if y == 0 else "--")
axes[1].set_ylabel("1-year z-score")
plt.tight_layout(); plt.show()
print(st.ratio_mean_reversion(ratio).round(4).to_string())
"""
        ),
        md(
            r"""

### 2.7 The synthetic control
"""
        ),
        code(
            r"""
rows = []
for tag, kw in (("silver IS levered gold", {}),
                ("+ industrial driver", {"industrial_load": 1.5}),
                ("+ drifting beta", {"beta_drift": 0.8}),
                ("both", {"industrial_load": 1.5, "beta_drift": 0.8})):
    sw = st.synthetic_world(n=6000, true_beta=1.8, **kw)
    rr = st.residuals(sw["silver"], sw["gold"])
    lt = st.residual_loadings(rr, sw[["industrial"]])
    rb = st.rolling_beta_table(sw["silver"], sw["gold"], windows=(252,))
    rows.append({"world": tag, "residual t on industrial": lt.loc["industrial", "t"],
                 "beta range / mean": rb.loc[252, "range_over_mean"],
                 "R2 of silver on gold": st.full_sample_beta(sw["silver"], sw["gold"])["r2"]})
d = pd.DataFrame(rows).set_index("world")
print(d.round(3).to_string())
print(f"\nfor comparison, the real tape: residual t "
      f"{load['t'].abs().max():.2f}, beta range/mean "
      f"{st.rolling_beta_table(s, g, windows=(252,)).loc[252, 'range_over_mean']:.2f}, "
      f"R2 {b['r2']:.2f}")
"""
        ),
        md(
            r"""

## 3 · The verdict
"""
        ),
        code(
            r"""
rep = st.replication_backtest(s, g, common[data.CASH], financing_spread=0.005,
                              cost_bps=1.0)
rbt = st.rolling_beta_table(s, g, windows=(252,))
uni = load[~load.index.str.contains(r"\(joint\)")]
pd.DataFrame({
    "beta of silver on gold": [b["beta"]],
    "R2": [b["r2"]],
    "residual vol (ann)": [b["resid_vol_ann"]],
    "rolling beta min": [rbt.loc[252, "min"]],
    "rolling beta max": [rbt.loc[252, "max"]],
    "largest residual |t|": [uni["t"].abs().max()],
    "replication correlation": [rep["correlation"]],
    "replication tracking error": [rep["tracking_error_ann"]],
    "predicted volatility drag": [rep["predicted_drag"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 4 · Going further

- **Physical demand.** The single biggest missing variable. Silver's industrial share, and
  photovoltaics inside it, moved enormously across this sample and no price series contains it.
- **Cointegration, not just beta.** Escribano & Granger (1998) treat the two metals as
  cointegrated with a slowly-moving relationship; an error-correction model would handle the
  drifting beta properly rather than describing it.
- **Rebalancing frequency.** Daily is the worst case for drag. Monthly, or a buy-and-hold
  levered position, would be the fairer replication and would narrow the gap.
- **Asymmetric betas properly.** Section 2.1 splits on the sign of gold's move, which is a crude
  version of what Ang & Chen (2002) do with exceedance correlations.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
