"""Build the two narrative notebooks for Study 43 (Free-Lunch).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/free_lunch_etf_panel.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (free_lunch/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from free_lunch import data, strategy as st
from quantlab import repro
assets, market, rf_ann = data.fetch_etf_panel()  # cache-first; built by examples/verify.py --fetch
cut = pd.Timestamp(repro.DEFAULT_AS_OF)          # pin: complete months strictly before the desk as-of
assets, market, rf_ann = assets[assets.index < cut], market[market.index < cut], rf_ann[rf_ann.index < cut]
rf_m = data.monthly_rf(rf_ann)
gross, lev = st.bab_returns(assets, market, rf_m, return_leverage=True)
mkt = st.market_monthly(market).loc[gross.index]
rf = rf_m.reindex(gross.index).fillna(0.0)       # the cash hurdle every Sharpe is measured against
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Free lunch?: Busted](https://img.shields.io/badge/Free_lunch%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Free-Lunch 🍽️\n### \"Safe stocks beat risky ones\" — so where's the catch?\n\n"
           + VERDICT +
           "One of finance's favourite anomalies: low-risk (low-beta) assets earn more *per unit of "
           "risk* than high-risk ones. The strategy that harvests it — betting against beta — has a "
           "famous Sharpe. The catch hides in one word: **leverage**. To make the safe-stock bet "
           "market-sized you have to borrow ~3× your capital, and once the borrowing is priced "
           "honestly — every dollar charged or credited exactly once — the famous edge trails the "
           "market it claims to beat.\n\n"
           "> 📓 **Plain-language layer.** The financing ledger, the sweep and the bond-bull confound "
           "are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The pitch | The catch |\n|---|---|\n"
           "| \"Low-beta beats high-beta risk-adjusted\" | Priced like-for-like (everything excess of the T-bill), the book's gross Sharpe (0.32) is **below** just owning the market (0.48). |\n"
           "| \"A market-neutral free lunch\" | It runs the safe leg at **2.8×** — borrowed money, billed at T-bill *plus* a spread. |\n"
           "| \"Great Sharpe, and it used to be even better!\" | The great early years were mostly a **levered bond trade** — the 'low-beta half' of this panel is Treasuries and gold. |"),
        md("## 1 · The claim\n\nBetting against beta (Frazzini & Pedersen 2014): leverage-constrained "
           "investors overpay for high-beta assets, so you can earn a premium by going **long low-beta "
           "(levered up to beta 1)** and **short high-beta**. Market-neutral, positive expected return."),
        md("## 2 · So what?\n\nIf true and tradable, it's a low-risk way to beat the market — the holy "
           "grail. But \"levered up to beta 1\" is doing enormous work in that sentence. We make the "
           "leverage explicit and price it."),
        md("## 3 · How would we even know?\n\nBuild the beta-neutral book on a liquid-ETF cross-section "
           "with a real cash rate (the 13-week T-bill): the borrowed slice pays T-bill + spread, the "
           "short's proceeds earn T-bill − fee, and **every Sharpe — book and market alike — is measured "
           "over the same T-bill**, so the race is fair. Then sweep the financing spread and watch the "
           "edge."),
        code("print(f'Average leverage on the low-beta (long) leg: {lev:.2f}x   (avg T-bill {rf.mean()*12:.1%}/yr)')\n"
             "rows={'BAB gross (self-financed)':st.summary(gross+rf,rf=rf),'SPY (market)':st.summary(mkt,rf=rf)}\n"
             "display(pd.DataFrame(rows).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))"),
        md("**Already, before any friction:** the safe-stock book earns a *lower* Sharpe than simply "
           "owning the market, once both are measured against the same cash hurdle. The old pitch "
           "compared a long-short return that quietly enjoyed free funding to a market return that "
           "didn't — that's where the apparent near-tie came from."),
        md("## 4 · The teardown — price the leverage\n\nNow charge a realistic *spread* over the T-bill "
           "on the borrowed 1.8× and watch what's left dissolve."),
        code("spreads=np.linspace(0,0.04,9)\n"
             "shp=[st.summary(st.bab_returns(assets,market,rf_m,financing_spread_ann=s,borrow_fee_ann=s/4))['sharpe'] for s in spreads]\n"
             "fig,ax=plt.subplots()\n"
             "ax.plot(spreads*100, shp, marker='o')\n"
             "ax.axhline(st.summary(mkt,rf=rf)['sharpe'],color='#2ea44f',ls='--',label='just own SPY (excess of T-bill)')\n"
             "ax.axhline(0,color='k',lw=.8)\n"
             "ax.set_xlabel('financing spread over the T-bill (%/yr)'); ax.set_ylabel('BAB net Sharpe (excess of cash)')\n"
             "ax.set_title('The \"free lunch\" is the leverage bill'); ax.legend(); plt.show()"),
        md("**Read it plainly.** At a zero spread the line already starts below \"just own SPY\" — and "
           "every realistic borrow cost drags it lower, through zero around 3.5%. The premium was rent "
           "on leverage. (Same lesson as [Study 30 House-Edge](../../30-house-edge/).)"),
        md("## 5 · The verdict\n\n**Signal: Weak** — the tilt exists but doesn't beat the market gross. "
           "**Tradability: Mirage** — financing erases it. **Free lunch?: Busted** — you pay for it in "
           "borrow, and the best years were mostly a bond-bull trade (the quants notebook shows the "
           "receipts)."),
        md("## 6 · Could you actually trade it?\n\nOnly if you can borrow ~1.8× of your capital at the "
           "T-bill flat, indefinitely — which retail can't, and which is precisely the constraint the "
           "anomaly claims to exploit in *others*. Charge yourself a real spread and the edge is gone."),
        md("## 7 · Going further 🚪\n\nThe quants notebook shows the 2.77× construction, the ledger, and "
           "why the apparent decay was duration in disguise. Next: [Study 44 Growth-Spurt](../../44-growth-spurt/) "
           "— the asset-growth anomaly, the highest headline Sharpe on the vendor's list, on real "
           "balance-sheet data."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Free-Lunch — a quantitative teardown 🔬\n### The self-financing ledger · the 2.77× leverage · the excess-of-cash race · the financing sweep · the duration confound\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We build BAB "
           "on a tradable ETF cross-section, finance it explicitly, and check what its long leg really is.\n\n"
           "> ⚠️ **Not investment advice.** 13 ETFs + SPY + ^IRX, daily, 2000–2026 (Yahoo). ETFs keep it "
           "survivorship-free at the cost of coarser beta dispersion. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | gross excess Sharpe 0.32 < market 0.48 |\n"
           "| Tradability | **Mirage** | 2.77× leverage; net Sharpe 0.32→0.23→0.09, negative past ~3.5% spread |\n"
           "| Free lunch? | **Busted** | the premium is the leverage rent; the 'decay' is the bond bull ending |\n\n"
           "> 💡 *In plain words:* the headline lives in a free-funding assumption, and the glory years "
           "lived in TLT."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** the beta-neutral low-minus-high book earns a "
           "positive gross premium (excess of cash, the F&P construction).\n- **H₂ (the pitch):** it "
           "beats the market risk-adjusted after the financing its leverage requires.\n- **H₃:** the "
           "edge is a stable intra-equity anomaly, not an artifact of what's in the low-beta bucket."),
        md("## 2 · So what? — what rides on each\n\nIf H₂ holds it's a low-risk market-beater. If only H₁ "
           "holds, the premium is real but captured by the lender, not you. If H₃ fails, even the gross "
           "premium is a different trade wearing BAB's label."),
        md("## 3 · How we'd know — the protocol\n\nTrailing betas → median split → lever each leg to "
           "beta 1 (record the long-leg leverage) → **self-financing ledger**: borrowed slice at "
           "rf + spread, short rebate at rf − fee, capital at rf, every dollar once → excess-of-cash "
           "race vs SPY → financing-spread sweep → decompose the long leg (TLT correlation; intra-equity-"
           "only rebuild)."),
        md("## 4 · The teardown"),
        md("### 4.1 The construction, its leverage, and the fair race"),
        code("print(f'avg long-leg leverage = {lev:.2f}x  (low-beta leg β≈{1/lev:.2f} levered to 1); avg T-bill {rf.mean()*12:.1%}/yr')\n"
             "display(pd.DataFrame({'BAB gross (self-financed)':st.summary(gross+rf,rf=rf),'SPY':st.summary(mkt,rf=rf)}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))"),
        md("> 💡 *In plain words:* both lines are measured over the same T-bill (the BAB row is the "
           "funded book, rf + long-short P&L, so the CAGRs are comparable too). Even at zero frictions "
           "BAB's Sharpe trails the market's. **H₁ holds only weakly** — there's a tilt, but it doesn't "
           "clear the bar. Note what changed vs the naive comparison: a raw long-short return pockets "
           "free funding on its net-long notional (≈ rf × (w_L − w_H) ≈ 3.6%/yr here); the F&P excess "
           "construction strips that subsidy."),
        md("### 4.2 The financing sweep — where the residual edge goes"),
        code("spreads=np.linspace(0,0.04,9)\n"
             "tbl=pd.DataFrame({'spread %':spreads*100,\n"
             "  'BAB net Sharpe':[st.summary(st.bab_returns(assets,market,rf_m,financing_spread_ann=s,borrow_fee_ann=s/4))['sharpe'] for s in spreads]})\n"
             "display(tbl.round(3).set_index('spread %'))\n"
             "print('market Sharpe (excess of T-bill) for reference:', round(st.summary(mkt,rf=rf)['sharpe'],2))"),
        md("> 💡 *In plain words:* a cheap institutional spread (1%) keeps Sharpe 0.23; a retail margin "
           "markup (~2.5%, the Study 30 central case) keeps 0.09; past ~3.5% the book loses money. "
           "**H₂ rejected** — the leverage rent is the premium."),
        md("### 4.3 What the long leg actually is — the duration confound"),
        code("tlt=(1+assets['TLT']).resample('ME').prod()-1\n"
             "eq_gross,eq_lev=st.bab_returns(assets[data.EQUITY_ONLY],market,rf_m,return_leverage=True)\n"
             "print(f'corr(BAB gross, TLT) = {gross.corr(tlt.loc[gross.index]):+.2f}   corr(BAB gross, SPY) = {gross.corr(mkt):+.2f}')\n"
             "print(f'intra-equity book (drop TLT/IEF/GLD): gross Sharpe {st.summary(eq_gross)[\"sharpe\"]:.2f}, leverage {eq_lev:.2f}x')\n"
             "rows={}\n"
             "for lab,lo,hi in [('2000-2012',None,'2012'),('2013-on','2013',None)]:\n"
             "    rows[lab]={'full book':st.summary(gross.loc[lo:hi])['sharpe'],'intra-equity':st.summary(eq_gross.loc[lo:hi])['sharpe']}\n"
             "display(pd.DataFrame(rows).T.round(2))\n"
             "ax=((1+gross).cumprod()).plot(label='BAB full book',lw=1.6)\n"
             "(1+tlt.loc[gross.index]).cumprod().plot(ax=ax,label='TLT',lw=1.2)\n"
             "(1+eq_gross).cumprod().plot(ax=ax,label='BAB intra-equity only',lw=1.6)\n"
             "ax.set_title('The \"decay\" was the bond bull ending'); ax.set_ylabel('growth of $1 (excess of cash)'); ax.legend(); plt.show()"),
        md("> 💡 *In plain words:* on a cross-asset panel the 'low-beta half' is mostly **Treasuries and "
           "gold**, so the levered long leg is half a duration trade — gross book corr +0.55 with TLT. "
           "The full book's apparent decay (Sharpe 0.56 → 0.12 around 2013) is the bond bull ending, "
           "capped by 2022; the intra-equity rebuild never had it (0.23 → 0.20, flat and small). F&P "
           "sort *within* an asset class for exactly this reason. **H₃ rejected** — the early glory was "
           "a different trade."),
        md("## 5 · The verdict\n\nH₁ weak, H₂ and H₃ rejected → Signal `WEAK`, Tradability `MIRAGE`, free "
           "lunch `BUSTED`."),
        md("## 6 · Could you trade it?\n\nOnly with permanent ~1.8× borrow at the T-bill flat — the very "
           "thing the anomaly says constrained investors *lack*. Price your own borrow honestly and "
           "there is no edge; price your long leg honestly and half of it was TLT."),
        md("## 7 · Going further\n\nForks: (a) a single-stock universe for genuine intra-equity beta "
           "dispersion (more headroom gross, same financing kill); (b) the international BAB variant; "
           "(c) a borrow spread that widens exactly when vol spikes — financing is procyclical. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md). "
           "Mechanism twin: [Study 30 House-Edge](../../30-house-edge/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
