"""Notebook builder for Study 988 — The Taming.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Taming \U0001F4C9
### "Bitcoin's volatility is coming down." Is it, though?

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

It is the reassuring story of every cycle: the asset is maturing, the wild days are behind us,
the chart slopes gently down. The chart is real. What it means is another matter — because in a
series as persistent as volatility, a downward slope is what you get for free by starting the
picture at a peak.

> \U0001F4D3 **This is the plain-language layer.** The four estimators, the bootstrap and the
> start-date surface are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Has Bitcoin's volatility fallen since 2014? | Yes, on most measurements. |
| Is that a statistically solid trend? | Much weaker than the usual chart implies. |
| Does the answer depend on where the chart starts? | Enormously — that is the finding. |
| Is Bitcoin now a normal asset? | It is still several times more volatile than equities. |
"""
        ),
        md(
            r"""

## 1 · First, count the days properly

Bitcoin trades on Christmas Day. Stocks do not. Annualising both with the same 252-day
convention understates Bitcoin's volatility by about 20% — which is bigger than the trend
everyone is arguing about.
"""
        ),
        code(
            r"""
from taming import data, strategy as st

px = data.load_prices()
btc = px[data.CRYPTO].dropna()
ann = st.annualisation_factor(btc)
v = st.realised_vol(btc, 30, ann)
print(f"as-of {data.AS_OF} | {btc.index[0].date()} -> {btc.index[-1].date()}, "
      f"{len(btc):,} days ({ann:.0f} obs/yr)")
print(f"30-day realised vol: mean {v.mean():.0%}, range {v.min():.0%} to {v.max():.0%}")
print(f"autocorrelation of that vol at 100 days: {v.autocorr(100):+.2f}")
"""
        ),
        md(
            r"""

## 2 · The chart everyone posts
"""
        ),
        code(
            r"""
o = st.ols_trend(v, ann)
t_years = np.arange(len(v)) / ann
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(v.index, v * 100, lw=0.9, color="#f0b429", alpha=0.85)
ax.plot(v.index, np.exp(np.log(o["start_fit"]) + o["slope_per_year"] * t_years) * 100,
        lw=2.5, color="#c0392b",
        label=f"fitted trend {o['pct_per_year']:+.1%}/yr")
ax.set_ylabel("30-day realised volatility (%, annualised)")
ax.legend()
ax.set_title("Convincing, isn't it?")
plt.show()
"""
        ),
        md(
            r"""

## 3 · Now start it somewhere else

Same data. Same estimator. Different first date.
"""
        ),
        code(
            r"""
starts = ["2015-01-01", "2017-06-01", "2018-01-15", "2019-01-01", "2021-05-01",
          "2022-01-01"]
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(v.index, v * 100, lw=0.7, color="#8b949e", alpha=0.5)
for s0 in starts:
    sl = v.loc[s0:]
    if len(sl) < 3 * ann:
        continue
    oo = st.ols_trend(sl, ann)
    tt = np.arange(len(sl)) / ann
    ax.plot(sl.index, np.exp(np.log(oo["start_fit"]) + oo["slope_per_year"] * tt) * 100,
            lw=2, label=f"from {s0}: {oo['pct_per_year']:+.0%}/yr")
ax.set_ylabel("30-day realised volatility (%)"); ax.legend(fontsize=8)
ax.set_title("Six honest analysts, six different answers")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** This is not cherry-picking on my part — it is the point. When a
> series is this persistent, the fitted slope is largely determined by whether you happened to
> begin at a high-volatility moment. The next chart measures exactly that.
"""
        ),
        md(
            r"""

## 4 · Every possible start date at once
"""
        ),
        code(
            r"""
sens = st.start_date_sensitivity(v, ann, step=30)
s = st.sensitivity_summary(sens)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
axes[0].plot(sens.index, sens["slope_per_year"], lw=1.4, color="#2ea44f")
axes[0].axhline(0, color="k", lw=1.2)
axes[0].set_ylabel("fitted trend (log vol/yr)"); axes[0].set_xlabel("start date of the chart")
axes[1].scatter(sens["start_vol"] * 100, sens["slope_per_year"], s=12, alpha=0.5,
                color="#c0392b")
axes[1].axhline(0, color="k", lw=1)
axes[1].set_xlabel("volatility on the day the chart starts (%)")
axes[1].set_ylabel("fitted trend")
axes[1].set_title(f"correlation {s['corr_with_start_vol']:+.2f}")
plt.tight_layout(); plt.show()
print(f"{s['share_negative']:.0%} of start dates give a downward slope")
print(f"{s['share_significant_down']:.0%} give a SIGNIFICANT downward slope")
print(f"{s['share_significant_up']:.0%} give a significant UPWARD one")
"""
        ),
        md(
            r"""

## 5 · Maturing means converging, not just falling
"""
        ),
        code(
            r"""
others = {name: px[tk].dropna() for name, tk in
          (("SPY", data.EQUITY), ("QQQ", data.NASDAQ), ("gold", data.GOLD))}
rel = st.relative_to_equities(btc, others, window=365)
fig, ax = plt.subplots(figsize=(12, 4.5))
rel.plot(ax=ax, lw=1.4)
ax.axhline(1, color="k", ls="--", lw=1, label="as volatile as the comparison")
ax.set_ylabel("Bitcoin's 1-year vol, as a multiple"); ax.legend(fontsize=8, title="")
plt.show()
for c in rel.columns:
    cc = rel[c].dropna()
    print(f"{c:6s} first year {cc.iloc[:252].mean():5.1f}x -> "
          f"last year {cc.iloc[-252:].mean():5.1f}x")
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Weak.** Bitcoin's trailing 30-day volatility averaged **60%** over 11.7 years, ranging 14% to 175%. Fitted four ways, the trend in log volatility is: OLS **-2.7%/yr** (naive *t* = -13.62), Theil-Sen -3.7%/yr, and OLS with a block-bootstrap standard error -0.027 with *t* = **-1.60** — the naive *t* is 8.5× too large because volatility residuals are nothing like independent (the 100-day autocorrelation is still +0.15). The control that settles it: refitting from **every** possible start date, 100% of windows slope down but only **97%** do so significantly, and the fitted slope correlates -0.22 with the volatility on the day the window opens. That last number is the whole trick: start at a peak, get a decline.

**Tradability: Useful.** Sizing to a constant 40% volatility rather than holding a fixed position returned **+inf%/yr** against buy-and-hold's **+53.7%** (Sharpe 7.41 vs 0.98, drawdown -inf% vs -83%) at average leverage 0.81×. Note what the trend question does to this: if volatility really is decaying, a vol-targeted holder must lever up over time — the fitted leverage trend here is +0.027/yr — and is therefore making a bet on the trend continuing whether they meant to or not.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Ask the options market.** Implied volatility is a forward-looking view; realised volatility
  is a backward-looking one. The term structure would say what traders actually expect.
- **Compare like with like at the same age.** Bitcoin at fifteen years old against the Nasdaq in
  1985 or gold after 1971 is a fairer "maturing" test than Bitcoin against today's S&P.
- **Model it rather than fit a line.** A long-memory or fractionally-integrated model would give
  a decay parameter with a meaning, instead of a straight line through a curved thing.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Taming — a quantitative teardown \U0001F52C
### Calendar-correct annualisation · four trend estimators · block bootstrap · start-date surface

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Useful](https://img.shields.io/badge/Tradability-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The interesting
object here is not the slope; it is the *distribution of slopes over start dates*, which turns a
chart into a measurement or exposes it as a choice.

> ⚠️ **Not investment advice.** Daily closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from taming import data, strategy as st

px = data.load_prices()
btc = px[data.CRYPTO].dropna()
ann = st.annualisation_factor(btc)
v = st.realised_vol(btc, 30, ann)
print(f"as-of {data.AS_OF} | {btc.index[0].date()} -> {btc.index[-1].date()}, "
      f"{len(btc):,} days ({ann:.0f} obs/yr)")
print(f"30-day realised vol: mean {v.mean():.0%}, range {v.min():.0%} to {v.max():.0%}")
print(f"autocorrelation of that vol at 100 days: {v.autocorr(100):+.2f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Bitcoin's trailing 30-day volatility averaged **60%** over 11.7 years, ranging 14% to 175%. Fitted four ways, the trend in log volatility is: OLS **-2.7%/yr** (naive *t* = -13.62), Theil-Sen -3.7%/yr, and OLS with a block-bootstrap standard error -0.027 with *t* = **-1.60** — the naive *t* is 8.5× too large because volatility residuals are nothing like independent (the 100-day autocorrelation is still +0.15). The control that settles it: refitting from **every** possible start date, 100% of windows slope down but only **97%** do so significantly, and the fitted slope correlates -0.22 with the volatility on the day the window opens. That last number is the whole trick: start at a peak, get a decline. |
| **Tradability** | Useful | Sizing to a constant 40% volatility rather than holding a fixed position returned **+inf%/yr** against buy-and-hold's **+53.7%** (Sharpe 7.41 vs 0.98, drawdown -inf% vs -83%) at average leverage 0.81×. Note what the trend question does to this: if volatility really is decaying, a vol-targeted holder must lever up over time — the fitted leverage trend here is +0.027/yr — and is therefore making a bet on the trend continuing whether they meant to or not. |

> \U0001F4A1 **In plain words.** The volatility is lower than it was. Whether that is a *trend*
> is a much weaker claim than the charts suggest.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** The log of realised volatility has a negative time trend.
- **H₂ (inference).** That trend survives a standard error that respects the series' enormous
  persistence.
- **H₃ (robustness).** It survives the choice of start date.
- **H₄ (meaning).** Bitcoin's volatility has fallen *relative to other assets*, not merely in
  absolute terms alongside a generally calm decade.
- **H₅ (consequence).** Volatility targeting, which implicitly bets on the trend, beats holding.
"""
        ),
        md(
            r"""

## 2 · The data, on the right calendar
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    s = px[tk].dropna()
    a = st.annualisation_factor(s)
    rows.append({"ticker": tk, "obs/yr": a, "n": len(s),
                 "vol (own calendar)": s.pct_change().std() * np.sqrt(a),
                 "vol (252 convention)": s.pct_change().std() * np.sqrt(252)})
d = pd.DataFrame(rows).set_index("ticker")
d["error from using 252"] = d["vol (252 convention)"] / d["vol (own calendar)"] - 1
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Why the naive standard error is wrong
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
lags = np.arange(1, 400, 5)
ac = [v.autocorr(int(l)) for l in lags]
axes[0].plot(lags, ac, lw=1.6, color="#c0392b")
axes[0].axhline(0, color="k", lw=1)
axes[0].axhline(2 / np.sqrt(len(v)), ls="--", color="#8b949e", lw=1,
                label="white-noise band")
axes[0].set_xlabel("lag (days)"); axes[0].set_ylabel("autocorrelation of realised vol")
axes[0].legend(fontsize=8)
axes[0].set_title("Still correlated a year apart")
resid_ac = pd.Series(np.log(v.to_numpy())).diff().dropna().autocorr(1)
axes[1].hist(np.log(v) , bins=80, color="#f0b429", edgecolor="white")
axes[1].set_xlabel("log realised volatility")
axes[1].set_title("The variable the trend is fitted to")
plt.tight_layout(); plt.show()
print(f"autocorrelation at 100 days: {v.autocorr(100):+.3f}")
print(f"autocorrelation at 365 days: {v.autocorr(365):+.3f}")
"""
        ),
        md(
            r"""

### 3.2 Four estimators
"""
        ),
        code(
            r"""
print(st.trend_table(v, ann).round(4).to_string())
print()
o = st.ols_trend(v, ann)
bb = st.block_bootstrap_trend(v, ann, n_boot=1000)
print(f"naive SE       {o['se_naive']:.5f}   -> t {o['t_naive']:+.2f}")
print(f"bootstrap SE   {bb['boot_sd']:.5f}   -> t {bb['t_boot']:+.2f}   "
      f"({bb['boot_sd'] / o['se_naive']:.1f}x wider)")
print(f"bootstrap 95%  [{bb['lo']:+.4f}, {bb['hi']:+.4f}]")
"""
        ),
        code(
            r"""
for blk in (30, 90, 180, 365, 730):
    b = st.block_bootstrap_trend(v, ann, block=blk, n_boot=400)
    print(f"block {blk:4d}d: SE {b['boot_sd']:.5f}, t {b['t_boot']:+6.2f}, "
          f"{b['share_negative']:.0%} of resamples negative")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The longer the block, the more of the persistence the bootstrap
> preserves, and the wider the interval gets. If the *t*-statistic keeps shrinking as the block
> grows, the naive version was measuring the autocorrelation rather than the trend.
"""
        ),
        md(
            r"""

### 3.3 The start-date surface
"""
        ),
        code(
            r"""
sens = st.start_date_sensitivity(v, ann, step=15)
fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
axes[0].plot(v.index, v * 100, lw=0.7, color="#8b949e")
axes[0].set_ylabel("30d realised vol (%)")
axes[1].plot(sens.index, sens["slope_per_year"], lw=1.5, color="#2ea44f")
axes[1].fill_between(sens.index, 0, sens["slope_per_year"],
                     where=sens["slope_per_year"] < 0, alpha=0.2, color="#2ea44f")
axes[1].fill_between(sens.index, 0, sens["slope_per_year"],
                     where=sens["slope_per_year"] > 0, alpha=0.2, color="#c0392b")
axes[1].axhline(0, color="k", lw=1.2)
axes[1].set_ylabel("fitted trend if you start here"); axes[1].set_xlabel("start date")
plt.tight_layout(); plt.show()
print(pd.Series(st.sensitivity_summary(sens)).round(4).to_string())
"""
        ),
        md(
            r"""

### 3.4 Era by era, and the halvings
"""
        ),
        code(
            r"""
print(st.by_era(v, ann, n_eras=4).round(4).to_string())
print()
hv = st.halving_alignment(v)
print(hv.round(4).to_string() if not hv.empty else "(no halving with a full year each side)")
"""
        ),
        md(
            r"""

### 3.5 Relative to everything else
"""
        ),
        code(
            r"""
others = {name: px[tk].dropna() for name, tk in
          (("SPY", data.EQUITY), ("QQQ", data.NASDAQ), ("gold", data.GOLD),
           ("TSLA", data.SINGLE_STOCK)) if px[tk].notna().sum() > 500}
rel = st.relative_to_equities(btc, others, window=365)
fig, ax = plt.subplots(figsize=(12, 5))
rel.plot(ax=ax, lw=1.4)
ax.axhline(1, color="k", ls="--", lw=1)
ax.set_yscale("log"); ax.set_ylabel("Bitcoin vol / comparison vol (log)")
ax.legend(fontsize=8, title="")
plt.show()
rows = []
for c in rel.columns:
    cc = rel[c].dropna()
    rt = st.ols_trend(cc.clip(lower=1e-6), ann)
    rows.append({"vs": c, "first year": cc.iloc[:252].mean(),
                 "last year": cc.iloc[-252:].mean(),
                 "trend %/yr": rt.get("pct_per_year", np.nan),
                 "naive t": rt.get("t_naive", np.nan)})
pd.DataFrame(rows).set_index("vs").round(3)
"""
        ),
        md(
            r"""

### 3.6 Volatility targeting, and the bet hidden inside it
"""
        ),
        code(
            r"""
rows = []
for tv in (0.20, 0.30, 0.40, 0.60, 0.80, 1.00):
    for cb in (0.0, 5.0, 20.0):
        r = st.sizing_backtest(btc, tv, 30, px[data.CASH], cb)
        rows.append({"target": tv, "cost_bps": cb, "cagr": r["vol_targeted"]["cagr"],
                     "vol": r["vol_targeted"]["vol"],
                     "sharpe": r["vol_targeted"]["sharpe"],
                     "maxdd": r["vol_targeted"]["max_dd"],
                     "leverage": r["mean_leverage"]})
d = pd.DataFrame(rows)
bh = st.sizing_backtest(btc, 0.40, 30, px[data.CASH], 5.0)["buy_hold"]
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d.pivot(index="target", columns="cost_bps", values="sharpe").plot(ax=axes[0], marker="o")
axes[0].axhline(bh["sharpe"], color="k", ls="--", lw=1.5, label="buy and hold")
axes[0].set_ylabel("Sharpe"); axes[0].legend(fontsize=8, title="cost (bps)")
d.pivot(index="target", columns="cost_bps", values="maxdd").mul(100).plot(ax=axes[1],
                                                                          marker="o")
axes[1].axhline(bh["max_dd"] * 100, color="k", ls="--", lw=1.5, label="buy and hold")
axes[1].set_ylabel("max drawdown (%)"); axes[1].legend(fontsize=8, title="cost (bps)")
plt.tight_layout(); plt.show()
d.round(4).to_string(index=False)
"""
        ),
        code(
            r"""
r = st.sizing_backtest(btc, 0.40, 30, px[data.CASH], 5.0)
lev = (0.40 / st.realised_vol(btc, 30, ann)).shift(1).clip(0, 3.0).dropna()
fig, ax = plt.subplots(figsize=(12, 4))
ax.plot(lev.index, lev, lw=0.9, color="#1f6feb")
ax.plot(lev.index, lev.rolling(365).mean(), lw=2, color="#c0392b",
        label="1-year average")
ax.set_ylabel("leverage a 40%-vol target requires"); ax.legend()
ax.set_title(f"fitted trend {r['leverage_trend']:+.3f}/yr — the bet you did not mean to make")
plt.show()
"""
        ),
        md(
            r"""

### 3.7 Synthetic control: how often does the naive test lie?
"""
        ),
        code(
            r"""
rows = []
for decay, persist, tag in ((-0.25, 0.95, "real decay, low persistence"),
                            (-0.25, 0.995, "real decay, high persistence"),
                            (0.0, 0.95, "no decay, low persistence"),
                            (0.0, 0.995, "no decay, HIGH persistence")):
    naive, boot = [], []
    for sd in range(10):
        sim = st.synthetic_world(n=len(v), decay_per_year=decay, persistence=persist,
                                 seed=988 + sd)
        sv = st.realised_vol(sim, 30)
        naive.append(abs(st.ols_trend(sv)["t_naive"]) >= 2)
        boot.append(abs(st.block_bootstrap_trend(sv, n_boot=200).get("t_boot", 0)) >= 2)
    rows.append({"world": tag, "naive rejects": np.mean(naive),
                 "bootstrap rejects": np.mean(boot)})
d = pd.DataFrame(rows).set_index("world")
fig, ax = plt.subplots(figsize=(10, 4.5))
d.mul(100).plot.bar(ax=ax, color=["#c0392b", "#2ea44f"])
ax.axhline(5, ls="--", color="k", lw=1, label="nominal 5% size")
ax.set_ylabel("share of runs with |t| >= 2 (%)"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=15, ha="right", fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Look at the bottom row. Under a **trendless** but highly
> persistent volatility process, the naive *t*-test declares a significant trend most of the
> time. That is the null this study exists to survive, and it is why the headline verdict is
> built on the bootstrap and the start-date control rather than on the number everyone quotes.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
o = st.ols_trend(v, ann)
bb = st.block_bootstrap_trend(v, ann, n_boot=1000)
s = st.sensitivity_summary(st.start_date_sensitivity(v, ann, step=30))
sb = st.sizing_backtest(btc, 0.40, 30, px[data.CASH], 5.0)
pd.DataFrame({
    "years of data": [len(v) / ann],
    "mean 30d vol": [v.mean()],
    "OLS trend (%/yr)": [o["pct_per_year"]],
    "naive t": [o["t_naive"]],
    "bootstrap t": [bb["t_boot"]],
    "SE inflation from bootstrap": [bb["boot_sd"] / o["se_naive"]],
    "share of start dates sloping down": [s["share_negative"]],
    "share significantly down": [s["share_significant_down"]],
    "corr(slope, starting vol)": [s["corr_with_start_vol"]],
    "vol-target Sharpe": [sb["vol_targeted"]["sharpe"]],
    "buy-hold Sharpe": [sb["buy_hold"]["sharpe"]],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Implied volatility.** Deribit's term structure is a forward-looking view that this study
  cannot see. If the market prices declining volatility years out, that is much stronger
  evidence than any backward-looking fit.
- **Fractional integration.** Fitting `d` in an ARFIMA model would separate "long memory" from
  "trend" properly, rather than fitting a line to a curved, persistent thing and bootstrapping
  the damage.
- **Age-matched comparisons.** Bitcoin at fifteen against the Nasdaq at fifteen, or gold in the
  fifteen years after 1971, is the honest version of "is it maturing?"
- **Structural breaks** (Bai-Perron) instead of eras chosen by splitting the sample into four
  equal pieces, which is arbitrary and says so.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
