"""Build the two narrative notebooks for Study 69 (Safe-Haven).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (shared cross-asset + macro pulls)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (safe_haven/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from safe_haven import data, strategy as st
gold_m, eq_ret, cpi_m = data.fetch_panel()     # cache-first (shared pulls)
ih = st.inflation_hedge(gold_m, cpi_m)
cb = st.crisis_ballast(gold_m.pct_change(), eq_ret)
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Gold hedges inflation?: Not supported](https://img.shields.io/badge/Gold_hedges_inflation%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Safe-Haven 🪙\n### Does gold really hedge inflation and protect you in a crash?\n\n"
           + VERDICT +
           "Gold's whole reputation rests on two promises: it protects against inflation, and it's a safe "
           "haven when markets crash. We checked both on 20 years of data. The inflation promise simply "
           "isn't there — gold's return barely budges with inflation. The crisis promise is half-true: "
           "gold doesn't *fall* with stocks, but it only *rises* half the time.\n\n"
           "> 📓 **Plain-language layer.** The inflation correlation, the high/low split and the crash "
           "behaviour are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every number is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (GLD/SPY/CPI, 2005–2025) |\n|---|---|\n"
           "| \"Does gold track inflation?\" | No: correlation **+0.09**; no premium when inflation is high. |\n"
           "| \"Does it protect in a crash?\" | Partly: **−0.2% vs SPY −10%**, but up only **50%** of the time. |\n"
           "| \"So what is gold good for?\" | A real **diversifier** that doesn't fall with stocks. |"),
        md("## 1 · The claim\n\nTwo folk beliefs: *(a)* gold preserves purchasing power — when inflation "
           "rises, gold rises; *(b)* gold is a safe haven — when stocks crash, gold rallies. Together they "
           "make gold the classic 'store of value' and portfolio insurance."),
        md("## 2 · So what?\n\nIf both held, gold would be a uniquely valuable holding — insurance that "
           "also beats inflation. If they don't, then gold's role is narrower (and its high average return "
           "may be just a price trend, not a hedge). Worth knowing before you size it."),
        md("## 3 · How would we even know?\n\nFor inflation: correlate gold's yearly return with yearly "
           "CPI, and compare gold in high- vs low-inflation months. For crisis: measure gold's stock "
           "correlation and its return in the worst equity months (SPY down >8%)."),
        code("split=pd.Series({'high-inflation months':ih['gold_hi_infl'],'low-inflation months':ih['gold_lo_infl']})*100\n"
             "ax=split.plot.bar(rot=0,color=['#c0392b','#8b949e'],title='Gold YoY return by inflation regime — no difference')\n"
             "ax.set_ylabel('% YoY'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print(f\"corr(gold YoY, inflation YoY) = {ih['corr']:+.2f}  |  high-minus-low gap {ih['hi_minus_lo']:+.1%}\")"),
        md("## 4 · The teardown — no inflation link, unreliable in a crash\n\nGold earned ~the same when "
           "inflation was hot or cold; and in the worst equity months it was flat, not soaring."),
        code("bars=pd.Series({'gold in crashes':cb['gold_in_crash'],'stocks in crashes':cb['eq_in_crash']})*100\n"
             "ax=bars.plot.bar(rot=0,color=['#dab617','#c0392b'],title='Average return in equity-crash months (SPY < -8%)')\n"
             "ax.set_ylabel('%/month'); ax.axhline(0,color='k',lw=.8); plt.show()\n"
             "print(f\"corr(gold, stocks) = {cb['stock_corr']:+.2f}  |  gold rose in {cb['gold_up_share']:.0%} of {cb['n_crash']} crash months\")"),
        md("**Read it plainly.** Gold's +10%/yr over this window was a price bull market (real rates, the "
           "dollar) — *not* an inflation response: it was just as strong when inflation was low. And while "
           "it didn't add to the pain in crashes, it rallied in only half of them. Useful ballast; not the "
           "inflation hedge or sure-thing haven of the legend."),
        md("## 5 · The verdict\n\n**Signal: None** (inflation hedge) — corr +0.09, no high-inflation "
           "premium. **Tradability: Fragile** (crisis hedge) — flat but up only half the time. **Gold "
           "hedges inflation?: Not supported.**"),
        md("## 6 · Could you actually trade it?\n\nOwn gold as a *diversifier* — a sleeve that's "
           "uncorrelated with stocks and tends not to fall when they do (see [68 "
           "All-Weather](../../68-all-weather/)). Just don't buy it *for* inflation protection or as "
           "guaranteed crash insurance; the data won't back you up."),
        md("## 7 · Going further 🚪\n\nThe diversifier cousin of [68 All-Weather](../../68-all-weather/) "
           "(gold as a risk-parity sleeve) and [70 Digital-Gold](../../70-digital-gold/) (bitcoin's "
           "identical pitch). Forks: very-long-horizon real gold price (Erb-Harvey), real-rate / dollar "
           "drivers, gold vs TIPS as the true inflation hedge."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Safe-Haven — a quantitative teardown 🔬\n### The inflation correlation · the high/low split · the crash-month behaviour\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Gold's two "
           "folk jobs, measured — a real diversifier oversold as an inflation hedge and a sure haven.\n\n"
           "> ⚠️ **Not investment advice.** GLD / SPY monthly returns + US CPI, 2005–2025 (Yahoo + FRED). "
           "Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal (inflation) | **None** | corr +0.09; high−low gap +0.4% |\n"
           "| Tradability (crisis) | **Fragile** | crash-flat (−0.2% vs −10%) but up 50% |\n"
           "| Hedges inflation? | **Not supported** | a price bull, not an inflation response |\n\n"
           "> 💡 *In plain words:* a diversifier, not the insurance it's sold as."),
        md("## 1 · The claims, steelmanned\n\n- **H₁:** YoY gold returns are positively correlated with "
           "YoY inflation.\n- **H₂:** gold earns more in high-inflation months.\n- **H₃:** gold is a safe "
           "haven — it rises (not just holds) when equities crash."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂ are the inflation-hedge case; H₃ is the "
           "safe-haven case. Failing them doesn't make gold useless — a low/zero correlation is itself "
           "valuable for diversification — but it reframes *why* you'd hold it."),
        md("## 3 · How we'd know — the protocol\n\nInflation: corr(YoY gold, YoY CPI) and a high/low "
           "(>4%) inflation split. Crisis: corr(gold, stocks) and gold's mean return + up-share in "
           "equity-crash months (SPY < −8%)."),
        md("## 4 · The teardown"),
        md("### 4.1 The inflation hedge — H₁/H₂"),
        code("print({k:(round(v,3) if isinstance(v,float) else v) for k,v in ih.items()})"),
        md("> 💡 *In plain words:* corr +0.09, and high-inflation gold (+10.6%) ≈ low-inflation gold "
           "(+10.2%). **H₁ and H₂ rejected** — no month-to-month inflation hedge (Erb-Harvey 2013)."),
        md("### 4.2 The safe haven — H₃"),
        code("print({k:(round(v,3) if isinstance(v,float) else v) for k,v in cb.items()})"),
        md("> 💡 *In plain words:* gold is near-uncorrelated with stocks (+0.08) and *flat* in the 10 "
           "worst equity months (−0.2% vs −10.1%) — but it rose in only **50%** of them. **H₃ partly "
           "rejected:** gold is a *hedge* (uncorrelated ballast) but not a reliable *safe haven* "
           "(Baur-Lucey 2010's distinction)."),
        md("## 5 · The verdict\n\nH₁/H₂ rejected, H₃ partly rejected → Signal `NONE` (inflation), "
           "Tradability `FRAGILE` (crisis), hedges-inflation `NOT SUPPORTED`. The fingerprinted run is in "
           "[`docs/results.md`](../docs/results.md)."),
        md("## 6 · Could you trade it?\n\nHold gold for *diversification* — the +0.08 stock correlation "
           "and crash-flat behaviour are genuinely useful in a portfolio (it earns its place in risk "
           "parity, [68](../../68-all-weather/)). But size it as a diversifier, not as inflation insurance "
           "or guaranteed crisis alpha."),
        md("## 7 · Going further\n\nForks: (a) the very-long-horizon real gold price (Erb-Harvey's "
           "mean-reversion); (b) gold vs TIPS as the real inflation hedge; (c) real-rate and dollar "
           "drivers; (d) safe-haven behaviour conditioned on crisis *type*. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
