"""Notebook builder for Study 970 — Root Time.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Root Time √
### The most-used formula in finance, and the assumption nobody checks

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

Daily volatility times √252 is annual volatility. One-day VaR times √10 is the regulator's
ten-day VaR. It is on every fact sheet and in every risk system, and it is exactly right only
if today's return tells you nothing about tomorrow's. This notebook measures how untrue that is,
and what the untruth costs.

> \U0001F4D3 **This is the plain-language layer.** Variance ratios, robust test statistics and
> the closed-form validation are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Is √T right for the S&P? | Very nearly. Which is why nobody questions it. |
| Is it right for a bond fund? | No. Their returns are strongly autocorrelated and the rule understates the long-horizon risk. |
| Does the error reach the risk report? | Yes — a 10-day VaR built by the √10 rule inherits it directly. |
| Is the error random? | No. Wherever it is large, it points the same way: the book looks calmer than it is. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Volatility scales with the square root of time."*

It is not a claim about markets; it is a theorem about **independent** random variables. The
variance of a sum of independent things is the sum of their variances, so standard deviation
grows like √T. Everything hinges on the word *independent*.
"""
        ),
        md(
            r"""

## 2 · So what?

The rule sits underneath the annualised volatility on every fact sheet, the 10-day VaR in every
bank's regulatory return, the Sharpe ratio in every pitch deck, and the position sizing in most
systematic strategies. If it is wrong by 20% somewhere, that 20% propagates everywhere.
"""
        ),
        code(
            r"""
from sqrt_time import data, strategy as st

px = data.load_prices()
rets = {tk: px[tk].dropna().pct_change().dropna() for tk in data.TICKERS}
print(f"as-of {data.AS_OF}")
for tk, r in rets.items():
    print(f"  {tk:8s} n={len(r):6,}  daily vol {r.std():.4f}  "
          f"annualised (sqrt rule) {r.std() * np.sqrt(252):6.2%}  AR(1) {r.autocorr(1):+.3f}")
"""
        ),
        md(
            r"""

Look at the AR(1) column. SPY is ~0. SHY — a short-Treasury fund — is not remotely 0. Those two
assets sit in the same risk report, scaled by the same formula.
"""
        ),
        md(
            r"""

## 3 · How would we even know?

Two ways, and we do both. The clever way is a **variance ratio**: compare the variance of
21-day returns with 21 times the variance of daily returns. The blunt way is to chop the tape
into non-overlapping blocks and just measure. If they agree, there is nothing left to argue
about.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 The variance-ratio curve, tape by tape
"""
        ),
        code(
            r"""
curves = {tk: st.vr_curve(r) for tk, r in rets.items()}
fig, ax = plt.subplots(figsize=(11, 5.5))
for tk, c in curves.items():
    ax.plot(c.index, c["vr"], marker="o", lw=1.3, label=tk)
ax.axhline(1.0, color="k", lw=1.5, ls="--")
ax.set_xscale("log"); ax.set_xticks(list(st.HORIZONS))
ax.set_xticklabels([str(q) for q in st.HORIZONS])
ax.set_xlabel("horizon (trading days)"); ax.set_ylabel("variance ratio")
ax.set_title("VR = 1 is the textbook. Above: trending. Below: mean-reverting.")
ax.legend(ncol=5, fontsize=8)
plt.show()
pd.DataFrame({tk: c["vr"] for tk, c in curves.items()}).T.round(2)
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The equity indices hug 1.0 across every horizon. The bond and
> bill funds sit above it. That is not a market inefficiency — it is the yield process being
> persistent, plus a dose of stale pricing.
"""
        ),
        md(
            r"""

### 4.2 The blunt check
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    rs = st.realised_scaling(px[tk].dropna())
    for q, r in rs.iterrows():
        rows.append({"ticker": tk, "q": q, "ratio": r["ratio"], "blocks": r["n_blocks"]})
d = pd.DataFrame(rows).pivot(index="ticker", columns="q", values="ratio")
fig, ax = plt.subplots(figsize=(10, 4.5))
im = ax.imshow(d.values, cmap="RdYlGn_r", vmin=0.7, vmax=1.3, aspect="auto")
ax.set_xticks(range(d.shape[1])); ax.set_xticklabels([f"{q}d" for q in d.columns])
ax.set_yticks(range(d.shape[0])); ax.set_yticklabels(d.index)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        if np.isfinite(d.values[i, j]):
            ax.text(j, i, f"{d.values[i, j]:.2f}", ha="center", va="center", fontsize=8)
ax.set_title("Actual volatility of non-overlapping blocks / the sqrt-rule prediction")
fig.colorbar(im, ax=ax)
plt.show()
"""
        ),
        md(
            r"""

### 4.3 What it costs where it matters
"""
        ),
        code(
            r"""
rows = []
for tk, r in rets.items():
    vr_a = curves[tk].loc[252, "vr"]
    vr_21 = curves[tk].loc[21, "vr"]
    ve = st.vol_scaling_error(vr_a)
    var_e = st.var_scaling_error(float(r.std(ddof=1)), vr_21)["error_pct"]
    sh = st.sharpe_scaling_error(r)
    rows.append({"ticker": tk, "vol error": ve, "10d VaR error": var_e,
                 "Sharpe error": sh["relative_error"]})
d = pd.DataFrame(rows).set_index("ticker")
fig, ax = plt.subplots(figsize=(11, 4.5))
(d * 100).plot.bar(ax=ax)
ax.axhline(0, color="k", lw=1)
ax.set_ylabel("error from using the sqrt rule (%)")
ax.set_title("The formula's error, in the three numbers people report")
ax.legend(title="", fontsize=8)
plt.show()
(d * 100).round(1)
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Weak.** Yes, and not subtly. At the annual horizon **2 of 10** tapes reject VR = 1 with a heteroskedasticity-robust |z| >= 2. The extremes are **SHY** at VR = **2.54** (trending: sqrt(T) *understates* its annual volatility by 59%) and **TQQQ** at VR = **0.54** (mean-reverting: it *overstates* by 27%). Equity indices sit close to 1, which is why the rule survived: it is nearly right for the one asset class everybody tests it on.

**Usefulness: Useful.** On a 10-day 99% VaR — the Basel horizon, computed by exactly this rule — the correction reaches **-19%** on EEM. An annualised Sharpe moves too: Lo's (2002) factor differs from sqrt(252) by up to **+42%** — though that correction carries a 12% standard deviation of its own on i.i.d. data, so the variance ratio, not the Sharpe factor, is the load-bearing number. On SPY the whole correction is -15.7% — invisible, and that is precisely why nobody checks it on anything else.
"""
        ),
        md(
            r"""

## 6 · Does it change a decision?

For an equity index: no, and you can keep using the rule with a clear conscience. For anything
with a slow-moving underlying — bond funds, credit, anything whose NAV is priced off a matrix
rather than a trade — the correction is the difference between a limit that binds and one that
does not.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Jumps** break the rule in the *opposite* direction from mean reversion (Danielsson &
  Zigrand 2006): a fat-tailed tape can need *more* than √T even with zero autocorrelation.
- **Stale pricing** (Getmansky, Lo & Makarov 2004) manufactures autocorrelation out of nothing
  — the hedge-fund version of the bond-fund result above.
- **Intraday scaling**: the same question inside the day, where the U-shaped volume pattern
  makes √t fail before lunch.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Root Time — a quantitative teardown \U0001F52C
### Lo-MacKinlay variance ratios · robust z · non-overlapping cross-check · VaR and Sharpe consequences

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The one
methodological point that decides whether this study says anything at all: the variance-ratio
test **must** be the heteroskedasticity-robust version, because volatility clustering alone
will reject the random walk and hand you a spurious answer with a beautiful *z*-statistic.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date
> in [`docs/results.md`](../docs/results.md); literature map in
> [`docs/references.md`](../docs/references.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from sqrt_time import data, strategy as st

px = data.load_prices()
rets = {tk: px[tk].dropna().pct_change().dropna() for tk in data.TICKERS}
print(f"as-of {data.AS_OF}")
for tk, r in rets.items():
    print(f"  {tk:8s} n={len(r):6,}  daily vol {r.std():.4f}  "
          f"annualised (sqrt rule) {r.std() * np.sqrt(252):6.2%}  AR(1) {r.autocorr(1):+.3f}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Yes, and not subtly. At the annual horizon **2 of 10** tapes reject VR = 1 with a heteroskedasticity-robust |z| >= 2. The extremes are **SHY** at VR = **2.54** (trending: sqrt(T) *understates* its annual volatility by 59%) and **TQQQ** at VR = **0.54** (mean-reverting: it *overstates* by 27%). Equity indices sit close to 1, which is why the rule survived: it is nearly right for the one asset class everybody tests it on. |
| **Usefulness** | Useful | On a 10-day 99% VaR — the Basel horizon, computed by exactly this rule — the correction reaches **-19%** on EEM. An annualised Sharpe moves too: Lo's (2002) factor differs from sqrt(252) by up to **+42%** — though that correction carries a 12% standard deviation of its own on i.i.d. data, so the variance ratio, not the Sharpe factor, is the load-bearing number. On SPY the whole correction is -15.7% — invisible, and that is precisely why nobody checks it on anything else. |

> \U0001F4A1 **In plain words.** √T is not an approximation that gets better with more data —
> it is exactly right or exactly wrong depending on one property of the series, and that
> property is measurable.
"""
        ),
        md(
            r"""

## 1 · The claim, steelmanned

For a sum of *T* returns,

    Var(sum) = T · Var(r) · [1 + 2 · Σ_{k=1..T-1} (1 − k/T) · ρ_k]

- **H₁.** The bracket — the variance ratio VR(T) — equals 1 for equity indices, so √T is right
  where it is most used.
- **H₂.** It exceeds 1 for instruments whose underlying moves slowly (bills, bonds), so √T
  understates their long-horizon risk.
- **H₃.** The deviations are large enough to matter in a 10-day VaR and in an annualised
  Sharpe ratio.
"""
        ),
        md(
            r"""

## 2 · So what? — the quantitative stakes

Basel's market-risk framework instructs banks to scale a one-day VaR by √10. If the true 10-day
variance ratio is 1.4, that instruction understates the capital requirement by
√1.4 − 1 ≈ 18%, on every position of that type, permanently.
"""
        ),
        md(
            r"""

## 3 · How we'd know — the protocol

1. **Overlapping variance ratios** with the Lo-MacKinlay bias constants (without them the
   estimator drifts below 1 in small samples and invents mean reversion).
2. **Heteroskedasticity-robust z-statistics** — the non-robust version rejects the random walk
   on any GARCH tape, which is most of them.
3. **A non-overlapping cross-check** with no estimator at all.
4. **A closed-form validation**: an AR(1) with known φ has a known VR(q), and the estimator is
   checked against it before it is trusted on real data.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 Validating the estimator before using it
"""
        ),
        code(
            r"""
rows = []
for phi in (-0.10, 0.0, 0.05, 0.10, 0.20):
    r, truth = data.synthetic_ar1(n_years=30, ar1=phi, signal_strength=1.0, seed=970)
    for q in (5, 21, 63):
        rows.append({"phi": phi, "q": q, "closed form": truth["vr_closed_form"][q],
                     "estimated": st.variance_ratio(r, q),
                     "robust z": st.lo_mackinlay_test(r, q)["z"]})
v = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(9, 4.5))
for q, sub in v.groupby("q"):
    ax.plot(sub["phi"], sub["closed form"], ls="--", lw=1, color="k")
    ax.plot(sub["phi"], sub["estimated"], marker="o", label=f"q = {q}")
ax.axhline(1, color="#8b949e", lw=1)
ax.set_xlabel("planted AR(1) coefficient"); ax.set_ylabel("variance ratio")
ax.set_title("Estimator (markers) against closed form (dashed)")
ax.legend()
plt.show()
v.round(3)
"""
        ),
        md(
            r"""

### 4.2 Why the robust statistic is not optional
"""
        ),
        code(
            r"""
rng = np.random.default_rng(970)
n = 6000
v_ = np.empty(n); e = np.empty(n); v_[0] = 1e-4; e[0] = 0.0
for t in range(1, n):
    v_[t] = 1e-6 + 0.10 * e[t - 1] ** 2 + 0.88 * v_[t - 1]
    e[t] = np.sqrt(v_[t]) * rng.normal()
garch = pd.Series(e, index=pd.bdate_range("2000-01-03", periods=n))
print(f"planted autocorrelation: exactly zero (returns are a GARCH martingale difference)")
print(f"measured AR(1): {garch.autocorr(1):+.4f}")
out = st.lo_mackinlay_test(garch, 21)
naive_z = (out["vr"] - 1) / np.sqrt(2 * (2 * 21 - 1) * (21 - 1) / (3 * 21 * len(garch)))
print(f"VR(21) = {out['vr']:.3f}")
print(f"  homoskedastic z (WRONG here): {naive_z:+.2f}")
print(f"  heteroskedasticity-robust z : {out['z']:+.2f}")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Both statistics are computed from the same variance ratio. The
> naive one thinks any wobble is evidence of trending; the robust one knows that fat tails and
> clustering produce wobble on their own.
"""
        ),
        md(
            r"""

### 4.3 The real tapes, with the full curve and its uncertainty
"""
        ),
        code(
            r"""
curves = {tk: st.vr_curve(r) for tk, r in rets.items()}
tbl = pd.DataFrame({tk: c["vr"] for tk, c in curves.items()}).T
z = pd.DataFrame({tk: c["z"] for tk, c in curves.items()}).T
fig, ax = plt.subplots(figsize=(11, 5))
im = ax.imshow(tbl.values, cmap="RdYlGn_r", vmin=0.6, vmax=1.6, aspect="auto")
ax.set_xticks(range(tbl.shape[1])); ax.set_xticklabels([f"q={q}" for q in tbl.columns])
ax.set_yticks(range(tbl.shape[0])); ax.set_yticklabels(tbl.index)
for i in range(tbl.shape[0]):
    for j in range(tbl.shape[1]):
        star = "*" if abs(z.values[i, j]) >= 2 else " "
        ax.text(j, i, f"{tbl.values[i, j]:.2f}{star}", ha="center", va="center", fontsize=8)
ax.set_title("Variance ratios (* = robust |z| >= 2)")
fig.colorbar(im, ax=ax)
plt.show()
z.round(2)
"""
        ),
        md(
            r"""

### 4.4 Overlapping versus non-overlapping: do they agree?
"""
        ),
        code(
            r"""
rows = []
for tk in data.TICKERS:
    rs = st.realised_scaling(px[tk].dropna())
    for q in st.HORIZONS:
        if q in rs.index:
            rows.append({"ticker": tk, "q": q, "overlapping": curves[tk].loc[q, "vr"],
                         "non-overlapping": rs.loc[q, "implied_vr"],
                         "blocks": rs.loc[q, "n_blocks"]})
d = pd.DataFrame(rows)
fig, ax = plt.subplots(figsize=(7, 6.5))
sc = ax.scatter(d["overlapping"], d["non-overlapping"], c=d["q"], cmap="viridis",
                s=40, norm=plt.matplotlib.colors.LogNorm())
lim = [0.4, 2.2]
ax.plot(lim, lim, color="k", lw=1, ls="--")
ax.set_xlim(lim); ax.set_ylim(lim)
ax.set_xlabel("VR from overlapping sums (Lo-MacKinlay)")
ax.set_ylabel("VR implied by non-overlapping blocks")
fig.colorbar(sc, ax=ax, label="horizon (days)")
ax.set_title("Two estimators, one conclusion")
plt.show()
print(f"correlation between the two: {d['overlapping'].corr(d['non-overlapping']):.3f}")
"""
        ),
        md(
            r"""

### 4.5 The consequences, priced
"""
        ),
        code(
            r"""
rows = []
for tk, r in rets.items():
    vr_a, vr_21 = curves[tk].loc[252, "vr"], curves[tk].loc[21, "vr"]
    var_e = st.var_scaling_error(float(r.std(ddof=1)), vr_21)
    sh = st.sharpe_scaling_error(r)
    rows.append({"ticker": tk, "VR(252)": vr_a, "vol error": st.vol_scaling_error(vr_a),
                 "1d VaR (99%)": var_e["var_sqrt_rule"] / np.sqrt(10),
                 "10d VaR sqrt-rule": var_e["var_sqrt_rule"],
                 "10d VaR corrected": var_e["var_corrected"],
                 "Lo factor": sh["factor"], "sqrt(252)": sh["sqrt_factor"],
                 "Sharpe naive": sh["sharpe_naive"], "Sharpe Lo": sh["sharpe_lo"]})
d = pd.DataFrame(rows).set_index("ticker")
print(d.round(4).to_string())
fig, ax = plt.subplots(figsize=(10, 4.5))
x = np.arange(len(d))
ax.bar(x - 0.2, d["10d VaR sqrt-rule"] * 100, width=0.4, color="#8b949e", label="sqrt rule")
ax.bar(x + 0.2, d["10d VaR corrected"] * 100, width=0.4, color="#c0392b", label="corrected")
ax.set_xticks(x); ax.set_xticklabels(d.index, rotation=20, ha="right")
ax.set_ylabel("10-day 99% VaR (%)"); ax.legend()
ax.set_title("The regulator's number, before and after the correction")
plt.show()
"""
        ),
        md(
            r"""

### 4.6 Has it changed over time?
"""
        ),
        code(
            r"""
rows = []
for tk, r in rets.items():
    early, late = r.loc[:"2009-12-31"], r.loc["2010-01-01":]
    rows.append({"ticker": tk,
                 "pre-2010": st.variance_ratio(early, 21) if len(early) > 500 else np.nan,
                 "2010+": st.variance_ratio(late, 21) if len(late) > 500 else np.nan})
d = pd.DataFrame(rows).set_index("ticker")
fig, ax = plt.subplots(figsize=(10, 4.5))
d.plot.bar(ax=ax, color=["#8b949e", "#2ea44f"])
ax.axhline(1, color="k", lw=1, ls="--")
ax.set_ylabel("VR(21)"); ax.set_title("Is the dependence a fossil?")
ax.legend(title="")
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

## 5 · The verdict
"""
        ),
        code(
            r"""
summary = pd.DataFrame({
    "VR(252)": {tk: curves[tk].loc[252, "vr"] for tk in data.TICKERS},
    "robust z": {tk: curves[tk].loc[252, "z"] for tk in data.TICKERS},
    "vol error": {tk: st.vol_scaling_error(curves[tk].loc[252, "vr"]) for tk in data.TICKERS},
})
summary["rejects VR=1"] = summary["robust z"].abs() >= 2
print(summary.round(3).to_string())
print(f"\n{int(summary['rejects VR=1'].sum())}/{len(summary)} tapes reject the random walk "
      f"at the annual horizon")
"""
        ),
        md(
            r"""

## 6 · What to do about it

Use √T where VR ≈ 1 and say so. Where it is not, either scale by the measured √VR or report
the horizon you actually measured. The one thing not to do is scale a bond book by √10 and
call the result a ten-day risk number.
"""
        ),
        md(
            r"""

## 7 · Going further

- **Jump-diffusion scaling** (Danielsson & Zigrand 2006): the opposite failure, and it applies
  to the equity indices that pass every test here.
- **Multiple variance-ratio tests** (Chow-Denning) to control the family-wise error across
  horizons — this study reports each horizon separately.
- **Wild bootstrap** variance-ratio tests, which behave better than the asymptotic z in small
  samples.
- **Getmansky-Lo-Makarov unsmoothing** applied to the bond funds, to separate genuine
  persistence from stale NAVs.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
