"""Generate the two narrative notebooks for Study 32 (Rip-Tide) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs OFFLINE on the seeded synthetic Ornstein-Uhlenbeck mean-reverting panel (the
machinery); the real-tape verdict (18 futures, 2000-2026) is quoted from ../docs/results.md. Both
notebooks walk the SAME seven desk beats. Rip-Tide is the deliberate mirror of Study 31 (Trade-Winds).
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from rip_tide import data, strategy, costs, extension

# Offline synthetic control: an Ornstein-Uhlenbeck mean-reverting panel (the machinery) + a random-walk null.
# The real 18-futures verdict is in ../docs/results.md.
r, truth = data.synthetic_reversion(revert_strength=0.06, seed=32)
r0, _ = data.synthetic_reversion(revert_strength=0.0, seed=32)
print(f"synthetic control: {truth.n_markets} markets x {truth.n_days} days, revert_strength {truth.revert_strength} (null=0)")
"""

# Real-tape numbers (../docs/results.md, 18 futures 2000-2026, as-of 2026-06-10, fp efab160ee1f0)
R = dict(fp="efab160ee1f0", asof="2026-06-10", days="6546", n="18",
         gross_sh="0.08", net_sh="-0.56", gross_cagr="0.2", net_cagr="-6.5",
         gross_dd="-51", net_dd="-88", skew="-1.03",
         lob_sh="0.51", lob_cagr="7.7", lob_dd="-55",
         turn="1.38", be="0.24",
         c0="0.075", c1="-0.241", c2="-0.557", c5="-1.497", c10="-3.026",
         h1="-0.56", h2="-0.17", h5="-0.18", h10="-0.16", h21="-0.20", h2g="0.20",
         lb1="-1.01", lb3="-0.57", lb5="-0.26", lb10="-0.41", lbb="-0.56",
         sub1="-0.39", sub2="-0.89", sub3="-0.42",
         syn_gross="2.90", syn_net="2.08", syn_null="-0.09", syn_h21="1.75")

BADGES = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Rescue by slowing down?: Busted](https://img.shields.io/badge/Rescue_by_slowing_down%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [
        md(
            "# Rip-Tide 🌊\n"
            "### \"Buy the dip, sell the rip.\" It works for stocks. Does it work for oil, gold and the euro? No — and turnover is why.\n\n"
            + BADGES +
            "This is the mirror of [Trade-Winds](../../31-trade-winds/), where *riding* the trend turned "
            "out to be a real premium. Here we do the opposite: **fade** the move — short whatever just "
            "rose, buy whatever just fell — on the very same 18 futures, with the very same machinery. "
            "Short-term reversion is a famous, real anomaly… *in individual stocks*, where it's the rent "
            "paid to whoever provides liquidity. On the world's deepest futures there's nothing to fade to "
            "begin with, and the frantic daily trading it demands turns even that nothing into a loss.\n\n"
            "> 📓 **This is the plain-language layer.** The cost wall, the break-even, the holding-period "
            "rescue and the horizon decay are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it; the core "
            "runs on a **synthetic** mean-reverting panel, so the real-futures numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Is short-term reversion real on futures? | 🟥 **No.** Gross of *all* costs the book Sharpes "
            f"**{R['gross_sh']}** — a coin flip — and loses money in every sub-period. |\n"
            "| Could you trade it anyway? | 🟥 **No.** It flips almost daily (turnover **{t}**), so it "
            "**breaks even at {be} bp** — cheaper than it costs to trade. Net of 2 bp: Sharpe **{ns}**. |\n"
            "| Can you save it by trading slower? | ⚪ **No.** Holding longer cuts the cost *and* the "
            "(tiny) edge in lockstep — net Sharpe never gets above zero. |\n\n"
            "> Desk shorthand: **Signal `NONE` · Tradability `MIRAGE` · Rescue? `BUSTED`** — same markets "
            "as Trade-Winds, opposite sign, opposite verdict.".format(t=R['turn'], be=R['be'], ns=R['net_sh'])
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "The contrarian, stated at full strength (Kakushadze-Serur *151 Trading Strategies* §10.3; the "
            "academic lineage is Jegadeesh 1990, Lehmann 1990):\n\n"
            "1. **Signal** — for each market, the *negative* sign of its own trailing 1/3/5-day return. "
            "Short if it just rose, long if it just fell.\n"
            "2. **Equal risk** — divide each position by its own volatility, exactly as the trend book does.\n"
            "3. **Diversify** — hold all ~18 markets across four asset classes.\n\n"
            "The believer's case: markets overreact to short-term news and snap back, so fading the move "
            "harvests the correction. We give it the strongest possible apparatus — the one that *worked* "
            "for trend — and only flip the sign."
        ),
        code(
            "book = strategy.book_returns(r, cost_bps=0.0)   # GROSS, on the synthetic control\n"
            "eq = (1+book).cumprod()\n"
            "fig, ax = plt.subplots()\n"
            "ax.plot(eq.index, eq.values, color='#2ea44f', lw=1.1)\n"
            "ax.set_yscale('log'); ax.set_title('Contrarian book on a TRULY mean-reverting panel — the machinery works')\n"
            "s = strategy.summary(book); print(f\"synthetic gross Sharpe {s['sharpe']:.2f}  (null would be ~0)\")"
        ),
        md(
            "> 🔬 **For the quants.** On the synthetic control the price genuinely overshoots and drifts "
            f"back over ~12 days, so the book earns a gross Sharpe of **{R['syn_gross']}** (and **{R['syn_null']}** "
            "on the random-walk null). The apparatus is sound — which is what makes the real-tape result "
            "a statement about *markets*, not about our code."
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "If liquid futures reliably overshot and snapped back, you'd have a high-Sharpe, "
            "market-neutral money machine that works in any regime — the dream of every stat-arb desk. "
            "And reversion genuinely *is* one of the most robust anomalies in equities. So the question "
            "isn't a strawman: it's whether that well-documented stock effect carries over to the deepest, "
            "most-arbitraged instruments on earth. If it doesn't, that tells you *where* the premium "
            "actually lives — in illiquidity, not in reversion per se."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "1. **Real?** Does the book pay *gross* of costs on the real tape, and stay flat on a random-walk null?\n"
            "2. **Tradable?** Its turnover, its break-even cost, and its net Sharpe vs the dumb always-long basket.\n"
            "3. **Saveable?** If it's too fast, does holding positions longer ever lift the *net* Sharpe above zero?\n\n"
            "**Mirage line:** break-even cost below ~1 bp (what it actually costs to trade ES) — then no "
            "real account could ever collect it."
        ),

        md("## 4 · The teardown 🔧\n\n### 4a · The machinery works where reversion is real (control vs null)"),
        code(
            "for label, rr in [('reverting panel', r), ('null (random walk)', r0)]:\n"
            "    s = strategy.summary(strategy.book_returns(rr, cost_bps=0.0))\n"
            "    print(f\"{label:22} gross Sharpe {s['sharpe']:+.2f}  turnover/day {strategy.turnover(rr):.2f}\")"
        ),
        md(
            "### 4b · On the real tape — nothing to fade, and turnover finishes the job\n"
            "On 18 real futures, 2000–2026 ([`../docs/results.md`](../docs/results.md)):\n\n"
            f"- **Gross** of all costs the book Sharpes just **{R['gross_sh']}** (CAGR {R['gross_cagr']}%) — "
            f"a coin flip. The dumb always-long basket of the same markets Sharpes **{R['lob_sh']}**.\n"
            f"- It flips almost every day: **turnover {R['turn']}/unit per day**, so the **break-even cost "
            f"is {R['be']} bp** — below the ~1 bp it costs to trade the most liquid future alive.\n"
            f"- Net of a realistic 2 bp the Sharpe is **{R['net_sh']}** with an **{R['net_dd']}%** drawdown. "
            "A real account doesn't lose slowly here — it bleeds."
        ),
        code(
            "print('Real tape (../docs/results.md):')\n"
            f"print('  contrarian gross   Sharpe {R['gross_sh']}   CAGR {R['gross_cagr']}%   maxDD {R['gross_dd']}%')\n"
            f"print('  contrarian net@2bp Sharpe {R['net_sh']}   CAGR {R['net_cagr']}%   maxDD {R['net_dd']}%')\n"
            f"print('  long-only basket   Sharpe {R['lob_sh']}   CAGR {R['lob_cagr']}%   maxDD {R['lob_dd']}%')\n"
            f"print('  turnover/day {R['turn']}   break-even cost {R['be']} bp')\n"
            "# the cost wall, drawn on the synthetic where there IS an edge to erode:\n"
            "cs = costs.cost_sweep(r); \n"
            "fig, ax = plt.subplots(); ax.axhline(0, color='#999', lw=.8)\n"
            "ax.plot(cs.index, cs['sharpe'], marker='o', color='#c0392b')\n"
            "ax.set_xlabel('cost (bp per unit traded)'); ax.set_ylabel('net Sharpe'); ax.set_title('The cost wall — reversion trades too fast to survive it')"
        ),

        md("## 5 · The verdict 🧾\n\n"
           f"- **Signal `NONE`** — gross Sharpe {R['gross_sh']} on the real tape, negative in all three "
           f"sub-periods ({R['sub1']} / {R['sub2']} / {R['sub3']}). No premium to begin with.\n"
           f"- **Tradability `MIRAGE`** — turnover {R['turn']}/day, break-even {R['be']} bp, net Sharpe "
           f"{R['net_sh']}. Gone before the first commission.\n"
           f"- **Rescue `BUSTED`** — see beat 7: slowing down never lifts the net Sharpe above zero.\n\n"
           "> **The mirror of Trade-Winds.** Same 18 futures, same machinery, opposite sign — trend is a "
           "real (fragile) premium; short-term reversion on deep futures simply is not."),

        md("## 6 · Could you trade it? 💸\n\n"
           "- **No.** The break-even cost (0.24 bp) is *below* the real cost of trading even ES, the "
           "single most liquid future on the planet. Every realistic account loses money from day one.\n"
           "- **Why it's real in stocks but not here.** Short-term reversal pays for *providing "
           "liquidity* — and it concentrates in illiquid single stocks (Avramov–Chordia–Goyal 2006; Nagel "
           "2012). Futures this deep have no such premium left to hand out.\n"
           "- **The honest takeaway.** 'Buy the dip' as a systematic, high-frequency strategy is a "
           "stock-market, small-cap phenomenon — not something you bolt onto a futures book."),

        md(
            "## 7 · Going further 🚪\n\n"
            "### Worked complement — \"slow it down to beat the cost\" ([`../docs/extension.md`](../docs/extension.md))\n"
            "The book dies on turnover, so the obvious fix is to hold each position longer. We swept the "
            "holding period from 1 to 21 days on the real tape:\n\n"
            f"- Turnover falls >10× (from {R['turn']}/day to ~0.13/day) — the cost side works perfectly.\n"
            f"- But the **net Sharpe never crosses zero** ({R['h1']} → {R['h2']} → {R['h21']}). The gross "
            "edge fades exactly as fast as the cost, because there was no slow-moving reversion to harvest. "
            "`BUSTED`.\n"
            f"- On the synthetic control the *same* rescue keeps a net Sharpe above **{R['syn_h21']}** even "
            "at a 21-day hold — proof the method would work if a real slow reversion existed.\n\n"
            "### Other forks\n"
            "- **Cross-sectional reversion** — fade relative winners *within* an asset class, not each market vs itself.\n"
            "- **Illiquid universe** — re-run on single-stock futures / small-caps, where the liquidity premium lives.\n"
            "- **Crisis-conditional** — trade reversion only when liquidity evaporates (Nagel 2012), the one time it's rich.\n\n"
            "PRs welcome — try the cross-sectional cut, swap in an illiquid universe, or gate it on a stress signal."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [
        md(
            "# Rip-Tide — a quantitative teardown 🔬\n"
            "### Gross-vs-net Sharpe · the cost wall & break-even · turnover · the holding-period rescue · horizon & sub-period decay\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its number.* The steelman: short-horizon contrarian trading is a "
            "robust, real anomaly. We confirm the apparatus captures it where it exists (synthetic "
            "control), then show that on deep liquid futures there is **no gross premium** and the "
            "turnover makes the net **a `MIRAGE`** — the exact mirror of Study 31's trend result.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on a synthetic Ornstein-Uhlenbeck reverting "
            "panel; the real 18-futures run is in [`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            f"| **Signal** — reversion real on futures? | 🔴 `NONE` | Gross Sharpe **{R['gross_sh']}**; "
            f"negative in all 3 sub-periods (**{R['sub1']}/{R['sub2']}/{R['sub3']}**). |\n"
            f"| **Tradability** | 🔴 `MIRAGE` | Turnover **{R['turn']}**/day ⇒ break-even **{R['be']} bp**; "
            f"net @2 bp Sharpe **{R['net_sh']}**, DD **{R['net_dd']}%**. |\n"
            f"| **Rescue by slowing down?** | ⚪ `Busted` | Net Sharpe across holds 1→21d never > 0 "
            f"(**{R['h1']}→{R['h2']}→{R['h21']}**). |\n\n"
            "> **In one sentence:** a real stock-market anomaly that has no counterpart on the deepest "
            "futures — gross-zero, and turnover-killed net — and that no amount of slowing down can save.\n\n"
            "*(This notebook executes on the synthetic control; the real numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Per market $i$: signal $s_{i,t} = -\\mathrm{sign}\\!\\big(\\tfrac13\\sum_{L\\in\\{1,3,5\\}}"
            "\\mathrm{sign}(P_{i,t}/P_{i,t-L}-1)\\big)$, lagged. Position $w_{i,t} = s_{i,t}\\cdot"
            "\\min(\\sigma^\\star_{\\text{mkt}}/\\hat\\sigma_{i,t},\\,c)$, then the book is scaled to a "
            "portfolio vol target. *Identical to Study 31 except for the leading minus sign.* Claim: the "
            "portfolio earns a positive premium from fading short-horizon moves. Null: i.i.d. returns ⇒ "
            "no autocorrelation to fade."
        ),
        code(
            "for label, rr in [('reverting panel', r), ('null', r0)]:\n"
            "    g = strategy.summary(strategy.book_returns(rr, cost_bps=0.0))\n"
            "    print(f\"{label:16} gross Sharpe {g['sharpe']:+.2f}  CAGR {g['cagr']*100:+.1f}%  turnover/day {strategy.turnover(rr):.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** The control has a genuine multi-day overshoot, so the book makes "
            f"money gross (**{R['syn_gross']}**); the null has none (**{R['syn_null']}**). The machine can "
            "see reversion when it's there. Now point it at the real market."
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Reversion is the canonical *liquidity-provision* premium: Lo–MacKinlay (1990) decompose "
            "contrarian profit into own- and cross-autocorrelation and a cross-sectional variance term; "
            "Nagel (2012) shows the payoff is the expected return on supplying liquidity, spiking when it "
            "evaporates. The pre-registered prediction, then, is that on the *deepest* instruments — where "
            "liquidity is never scarce — the premium should be smallest. Beats 4–6 test exactly that."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Real?** `book_returns(cost_bps=0)` on control vs null and on the real tape (gross).\n"
            "2. **Tradable?** `strategy.turnover`, `costs.breakeven_cost_bps`, `costs.cost_sweep`, vs `costs.long_only_basket`.\n"
            "3. **Saveable?** `extension.holding_period_sweep` — net Sharpe as a function of holding period.\n"
            "4. **Robust?** `extension.horizon_sweep` + `extension.subperiod_sharpe`.\n\n"
            "**Mirage line:** break-even cost < ~1 bp (the real cost of trading ES)."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · Gross-zero on the real tape (the NONE call)"),
        code(
            "print('Real tape (../docs/results.md):')\n"
            f"print('  contrarian gross   Sharpe {R['gross_sh']}  CAGR {R['gross_cagr']}%  maxDD {R['gross_dd']}%  skew {R['skew']}')\n"
            f"print('  contrarian net@2bp Sharpe {R['net_sh']}  CAGR {R['net_cagr']}%  maxDD {R['net_dd']}%')\n"
            f"print('  long-only basket   Sharpe {R['lob_sh']}  CAGR {R['lob_cagr']}%  maxDD {R['lob_dd']}%')\n"
            "# on the synthetic control the timing genuinely adds (reversion is strong there):\n"
            "print('\\nSynthetic control:')\n"
            "print(f\"  contrarian gross  Sharpe {strategy.summary(strategy.book_returns(r, cost_bps=0.0))['sharpe']:.2f}\")\n"
            "print(f\"  long-only basket  Sharpe {strategy.summary(costs.long_only_basket(r))['sharpe']:.2f}\")"
        ),
        md(
            "> 💡 **In plain words.** Where overshoot is real (the control) fading it beats owning the "
            "basket; on the real, efficient futures tape there's no overshoot left, so the always-long "
            "basket wins even *before* costs. The signal is `NONE` on the thing we actually care about."
        ),

        md("### 4b · The cost wall and the break-even (the MIRAGE call)"),
        code(
            "print('Real cost sweep (net Sharpe, ../docs/results.md):')\n"
            f"print('  0bp {R['c0']}   1bp {R['c1']}   2bp {R['c2']}   5bp {R['c5']}   10bp {R['c10']}')\n"
            f"print(f'  turnover/day {R['turn']}   break-even {R['be']} bp  (ES costs ~1 bp to trade)')\n"
            "# drawn on the synthetic, where there is an edge for cost to erode:\n"
            "cs = costs.cost_sweep(r)\n"
            "fig, ax = plt.subplots(); ax.axhline(0, color='#999', lw=.8)\n"
            "ax.plot(cs.index, cs['sharpe'], marker='o', color='#c0392b')\n"
            "ax.set_xlabel('cost (bp/unit)'); ax.set_ylabel('net Sharpe'); ax.set_title('Cost wall (synthetic control)')\n"
            "print('\\nsynthetic break-even:', round(costs.breakeven_cost_bps(r), 2), 'bp')"
        ),

        md("## Beat 5 · The verdict\n\n"
           f"- **`NONE`** (4a, Beat 1): real gross Sharpe {R['gross_sh']}; control {R['syn_gross']} vs null {R['syn_null']}.\n"
           f"- **`MIRAGE`** (4b): break-even {R['be']} bp < real cost; net @2 bp {R['net_sh']}, DD {R['net_dd']}%.\n"
           f"- **Rescue `BUSTED`** (Beat 7): net Sharpe across holds never > 0.\n\n"
           "> **Signal `NONE` · Tradability `MIRAGE` · Rescue? `BUSTED`** — the exact mirror of Trade-Winds."),

        md("## Beat 6 · Could you trade it?\n\n"
           "- **No.** Break-even 0.24 bp is below the real cost of trading even ES. There is no account "
           "structure — retail or institutional — that nets a positive return here.\n"
           "- **Capacity is irrelevant** when the gross edge is zero; you can't scale nothing.\n"
           "- **Where the premium actually lives:** illiquid single stocks and crisis windows "
           "(Avramov–Chordia–Goyal 2006; Nagel 2012), not deep futures. That's the constructive lesson."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — the holding-period rescue ([`../docs/extension.md`](../docs/extension.md))\n"
            "The book dies on turnover, so we slow it down: hold each position $h$ days and re-measure the "
            "*net* Sharpe. On the synthetic here, on the real tape in [`../docs/extension.md`](../docs/extension.md)."
        ),
        code(
            "hp = extension.holding_period_sweep(r, holds=[1,2,5,10,21], cost_bps=2.0)\n"
            "display(hp.round(3))\n"
            "fig, ax = plt.subplots(); ax.axhline(0, color='#999', lw=.8)\n"
            "ax.plot(hp.index, hp['gross_sharpe'], marker='o', label='gross', color='#2ea44f')\n"
            "ax.plot(hp.index, hp['net_sharpe'], marker='o', label='net @2bp', color='#c0392b')\n"
            "ax.set_xlabel('holding period (days)'); ax.set_ylabel('Sharpe'); ax.legend(); ax.set_title('Holding-period rescue (synthetic — it WORKS when reversion is real)')\n"
            "print('Real tape net Sharpe by hold (../docs/extension.md): '\n"
            f"      '1d {R['h1']}, 2d {R['h2']}, 5d {R['h5']}, 10d {R['h10']}, 21d {R['h21']} -- never > 0. BUSTED.')"
        ),
        md(
            "> 💡 **In plain words.** On the synthetic, slowing down keeps the net Sharpe high (>"
            f"{R['syn_h21']} even at 21 days) because the overshoot persists for weeks. On the real tape "
            "the same knob does nothing useful — the edge and the cost vanish together. That contrast is "
            "the cleanest possible evidence that the *market*, not the method, lacks the premium."
        ),
        md(
            "### 7b · The horizon sweep & the honest sub-period decay\n"
            "Not a mis-tuned lookback (negative across every short horizon), and negative in every epoch."
        ),
        code(
            "print('Real horizon sweep (net Sharpe @2bp, ../docs/results.md):')\n"
            f"print('  1d {R['lb1']}   3d {R['lb3']}   5d {R['lb5']}   10d {R['lb10']}   blend {R['lbb']}')\n"
            f"print('\\nReal sub-period Sharpe: {R['sub1']} / {R['sub2']} / {R['sub3']} -- negative in all three.')\n"
            "print('\\nSynthetic horizon sweep (where the edge IS there):')\n"
            "print(extension.horizon_sweep(r).round(3).to_string())"
        ),
        md(
            "**The result.** The apparatus captures reversion wherever it exists (synthetic control, every "
            "horizon, every holding period) — and finds **none** on 18 deep futures, at any horizon, in "
            "any epoch, gross or net. A clean, durable `NONE`/`MIRAGE`, and a `BUSTED` rescue. Full runs "
            "in [`../docs/results.md`](../docs/results.md) and [`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7c · Other forks\n"
            "- **Cross-sectional reversion** — relative winners within an asset class vs each market's own past.\n"
            "- **Illiquid universe** — single-stock futures / small-caps, where the liquidity premium survives.\n"
            "- **Crisis-conditional sizing** — trade it only when liquidity evaporates (Nagel 2012).\n\n"
            "PRs welcome — try the cross-sectional cut, an illiquid universe, or a stress gate."
        ),
    ]
    nb = new_notebook(cells=cells, metadata=_meta())
    _write(nb, "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
