"""Notebook builder for Study 976 — The Family Tree.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# The Family Tree \U0001F333
### Cluster the assets, split risk down the branches, never invert a matrix

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

A portfolio optimiser inverts the covariance matrix, and inverting a badly estimated matrix is
how you end up 40% long one stock and short three others. Hierarchical risk parity refuses to
invert anything: it draws a family tree of the assets and divides risk down the branches. This
notebook builds it from scratch and asks what the tree is actually worth.

> \U0001F4D3 **This is the plain-language layer.** The linkage algebra, the paired tests and
> the Monte Carlo are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does HRP beat the optimiser out of sample? | On the wide panel, yes — quieter, steadier, no shorts. |
| Is that because of the clustering? | Mostly not. Plain inverse-variance weighting gets nearly all of it. |
| So is the tree useless? | No — it moves a measurable share of the book and it is what stops a crowded cluster dominating. Just do not credit it with the whole gain. |
| Would you run it? | For a long-only book with a thin covariance matrix, it is a reasonable default that cannot blow up. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Markowitz's curse: the more correlated the assets, the more unstable the optimiser's
> weights. Hierarchical clustering solves it by never inverting the matrix at all."*

That is López de Prado's argument, and the first half of it is unambiguously true.
"""
        ),
        code(
            r"""
from hrp import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
panels = {
    "sectors": [c for c in data.SECTORS if rets[c].notna().sum() > 1500],
    "names": [c for c in data.NAMES if rets[c].notna().sum() > 3000],
    "multi-asset": [c for c in data.MULTI if rets[c].notna().sum() > 3000],
}
print(f"as-of {data.AS_OF}")
for tag, cols in panels.items():
    print(f"  {tag:12s} {len(cols):3d} assets")
"""
        ),
        md(
            r"""

## 2 · The tree, drawn
"""
        ),
        code(
            r"""
cols = panels["multi-asset"]
sub = rets[cols].dropna(how="any")
cov = np.cov(sub.iloc[-756:].to_numpy(), rowvar=False, ddof=1)
order = st.cluster_order(cov)
sd = np.sqrt(np.diag(cov)); corr = cov / np.outer(sd, sd)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, idx, title in ((axes[0], list(range(len(cols))), "as listed"),
                       (axes[1], order, "after clustering")):
    im = ax.imshow(corr[np.ix_(idx, idx)], cmap="RdYlGn", vmin=-1, vmax=1)
    ax.set_xticks(range(len(cols))); ax.set_xticklabels([cols[i] for i in idx], rotation=90, fontsize=8)
    ax.set_yticks(range(len(cols))); ax.set_yticklabels([cols[i] for i in idx], fontsize=8)
    ax.set_title(f"correlation matrix, {title}")
fig.colorbar(im, ax=axes, shrink=0.7)
plt.show()
print("leaf order:", ", ".join(cols[i] for i in order))
"""
        ),
        md(
            r"""

The right-hand panel is the same matrix with the rows and columns permuted so relatives sit
together — bonds with bonds, equities with equities. That reordering is the whole of step two,
and everything HRP does afterwards reads the matrix as if it were block-diagonal.
"""
        ),
        md(
            r"""

## 3 · The weights it produces
"""
        ),
        code(
            r"""
cols = panels["names"]
sub = rets[cols].dropna(how="any")
cov = np.cov(sub.iloc[-252:].to_numpy(), rowvar=False, ddof=1)
W = pd.DataFrame({st.METHOD_LABEL[m]: st.weights_for(m, cov) for m in st.METHODS}, index=cols)
fig, ax = plt.subplots(figsize=(12, 4.5))
W[[st.METHOD_LABEL[m] for m in ("hrp", "min_var", "inv_var")]].plot.bar(
    ax=ax, color=["#2ea44f", "#c0392b", "#8b949e"])
ax.axhline(0, color="k", lw=1); ax.set_ylabel("weight")
ax.set_title("Forty names, one year of data")
ax.legend(title=""); plt.setp(ax.get_xticklabels(), fontsize=7)
plt.show()
print(W.agg(["max", "min"]).round(3).to_string())
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The optimiser's bar chart is the one with negative bars and a
> couple of very tall ones. HRP's is flat, positive and boring — which is the point, and also
> the reason it is hard to tell apart from inverse variance.
"""
        ),
        md(
            r"""

## 4 · Out of sample
"""
        ),
        code(
            r"""
wf = st.walk_forward(sub, window=252, step=63, cost_bps=5.0)
s = st.summarise(wf)
fig, ax = plt.subplots(figsize=(10, 4.5))
colors = {"hrp": "#2ea44f", "min_var": "#c0392b", "inv_var": "#8b949e",
          "risk_parity": "#dab617", "equal": "#4c6ef5"}
ax.bar([st.METHOD_LABEL[m] for m in s.index], s["realised_vol"] * 100,
       color=[colors[m] for m in s.index])
ax.set_ylabel("realised volatility (%)")
ax.set_title("Forty names, rolling out-of-sample")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
s[["realised_vol", "sharpe", "turnover", "max_weight", "effective_n", "short"]].round(3)
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** The tree is not decoration: HRP's weights differ from plain inverse-variance weights by **16.7%** of the book on the 40-name panel and 9.3% on the multi-asset one, and the clustering changes the ordering on 3 of 3 panels. What it buys is a different question: HRP holds an effective **26.5** positions against 3.3 for the optimiser, with a maximum weight of 8.4% against 31.6% and no shorts at all.

**Usefulness: Fragile.** On the wide panel HRP realises **13.47%** annualised against **13.07%** for minimum variance (paired *t* = -1.01) and **16.20%** for 1/N (*t* = +11.20). Against the control that matters — inverse variance, which is HRP without the tree — the difference is -0.527% (*t* = +6.50). Turnover is 0.27 a rebalance against 1.54, which is where the practical case for it is strongest.
"""
        ),
        md(
            r"""

## 6 · Going further \U0001F6AA

- **HRP against a *shrunk* optimiser** (study 975) is the comparison the literature usually
  avoids, and the one that decides whether the tree or the estimator is doing the work.
- **Other linkages** (average, Ward) and other distances change the tree; Raffinot (2017)
  found the choice matters less than the clustering itself.
- **Tail dependence** instead of correlation as the distance — Lohre et al. (2020).
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# The Family Tree — a quantitative teardown \U0001F52C
### Single linkage · quasi-diagonalisation · recursive bisection · four controls · planted blocks

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Fragile](https://img.shields.io/badge/Usefulness-Fragile-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). The control
that carries this study is **inverse variance** — HRP with the hierarchy deleted. Any advantage
shared with it is an argument for risk-weighting a long-only book, not for clustering, and
separating the two is most of the work.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date
> in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from hrp import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
panels = {
    "sectors": [c for c in data.SECTORS if rets[c].notna().sum() > 1500],
    "names": [c for c in data.NAMES if rets[c].notna().sum() > 3000],
    "multi-asset": [c for c in data.MULTI if rets[c].notna().sum() > 3000],
}
print(f"as-of {data.AS_OF}")
for tag, cols in panels.items():
    print(f"  {tag:12s} {len(cols):3d} assets")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | The tree is not decoration: HRP's weights differ from plain inverse-variance weights by **16.7%** of the book on the 40-name panel and 9.3% on the multi-asset one, and the clustering changes the ordering on 3 of 3 panels. What it buys is a different question: HRP holds an effective **26.5** positions against 3.3 for the optimiser, with a maximum weight of 8.4% against 31.6% and no shorts at all. |
| **Usefulness** | Fragile | On the wide panel HRP realises **13.47%** annualised against **13.07%** for minimum variance (paired *t* = -1.01) and **16.20%** for 1/N (*t* = +11.20). Against the control that matters — inverse variance, which is HRP without the tree — the difference is -0.527% (*t* = +6.50). Turnover is 0.27 a rebalance against 1.54, which is where the practical case for it is strongest. |

> \U0001F4A1 **In plain words.** HRP is three good ideas stacked: risk weighting, no shorts,
> and clustering. Two of them are free elsewhere.
"""
        ),
        md(
            r"""

## 1 · The claim, decomposed

- **H₁.** The clustering step changes the weights materially versus inverse variance.
- **H₂.** HRP realises lower out-of-sample volatility than minimum variance.
- **H₃.** HRP beats 1/N, which is the benchmark that usually wins.
- **H₄.** The advantage over *inverse variance* — the same method minus the hierarchy — is
  positive. If H₄ fails while H₂ and H₃ hold, the correct conclusion is that risk weighting a
  long-only book is what works, and the tree is decoration.
"""
        ),
        md(
            r"""

## 2 · The algorithm, step by step
"""
        ),
        code(
            r"""
cols = panels["multi-asset"]
sub = rets[cols].dropna(how="any")
cov = np.cov(sub.iloc[-756:].to_numpy(), rowvar=False, ddof=1)
sd = np.sqrt(np.diag(cov)); corr = cov / np.outer(sd, sd)
d = st.correlation_distance(corr)
links = st.single_linkage(d)
print("first five merges (left, right, distance, size):")
for lk in links[:5]:
    a = cols[lk[0]] if lk[0] < len(cols) else f"cluster{lk[0]}"
    b = cols[lk[1]] if lk[1] < len(cols) else f"cluster{lk[1]}"
    print(f"  {a:6s} + {b:10s} at distance {lk[2]:.3f} -> size {lk[3]}")
order = st.quasi_diagonal_order(links, len(cols))
print("\nquasi-diagonal order:", ", ".join(cols[i] for i in order))
w = st.hrp_weights(cov, order)
print("\nHRP weights:")
print(pd.Series(w, index=cols).round(4).to_string())
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 Does the hierarchy move the book?
"""
        ),
        code(
            r"""
rows = []
for tag, cs in panels.items():
    s_ = rets[cs].dropna(how="any")
    c = np.cov(s_.iloc[-252:].to_numpy(), rowvar=False, ddof=1)
    w_hrp, w_iv = st.hrp_weights(c), st.inverse_variance_weights(c)
    rows.append({"panel": tag, "assets": len(cs),
                 "share of book moved": np.abs(w_hrp - w_iv).sum() / 2,
                 "max single-name difference": np.abs(w_hrp - w_iv).max(),
                 "corr(HRP, inv-var)": np.corrcoef(w_hrp, w_iv)[0, 1]})
pd.DataFrame(rows).set_index("panel").round(4)
"""
        ),
        md(
            r"""

### 3.2 The full scoreboard, three panels
"""
        ),
        code(
            r"""
all_wf = {}
for tag, cs in panels.items():
    all_wf[tag] = st.walk_forward(rets[cs].dropna(how="any"), window=252, step=63, cost_bps=5.0)
    print(f"--- {tag} ---")
    print(st.summarise(all_wf[tag])[["realised_vol", "sharpe", "turnover", "max_weight",
                                     "effective_n", "short"]].round(4).to_string())
    print()
vols = pd.DataFrame({tag: st.summarise(wf)["realised_vol"] for tag, wf in all_wf.items()})
vols.index = [st.METHOD_LABEL[m] for m in vols.index]
fig, ax = plt.subplots(figsize=(10, 4.5))
(vols * 100).plot.bar(ax=ax)
ax.set_ylabel("realised volatility (%)"); ax.legend(title="")
ax.set_title("Every method, every panel")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
"""
        ),
        md(
            r"""

### 3.3 Paired tests — and the control
"""
        ),
        code(
            r"""
rows = []
for tag, wf in all_wf.items():
    for other in ("min_var", "inv_var", "risk_parity", "equal"):
        p = st.paired_test(wf, "hrp", other)
        rows.append({"panel": tag, "vs": st.METHOD_LABEL[other], "vol diff": p["diff"],
                     "t (HRP quieter > 0)": -p["t"], "HRP wins": p["win_rate"], "n": p["n"]})
d = pd.DataFrame(rows)
print(d.round(4).to_string(index=False))
fig, ax = plt.subplots(figsize=(10, 4.5))
piv = d.pivot(index="vs", columns="panel", values="t (HRP quieter > 0)")
piv.plot.bar(ax=ax)
ax.axhline(0, color="k", lw=1); ax.axhline(2, color="#c0392b", ls="--", lw=1)
ax.set_ylabel("paired t (positive = HRP quieter)"); ax.legend(title="")
plt.setp(ax.get_xticklabels(), rotation=15, ha="right")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Read the `Inverse variance` row first. That is HRP minus the
> tree. Whatever HRP achieves that inverse variance does not is the value of the hierarchy;
> everything else is the value of not shorting and of weighting by risk.
"""
        ),
        md(
            r"""

### 3.4 Stability of the weights
"""
        ),
        code(
            r"""
wf = all_wf["names"]
piv = wf.pivot(index="date", columns="method", values="turnover")
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
for m in st.METHODS:
    axes[0].plot(piv.index, piv[m], lw=1, label=st.METHOD_LABEL[m])
axes[0].set_ylabel("turnover per rebalance"); axes[0].legend(fontsize=7)
axes[0].set_title("How much each method trades")
mw = wf.pivot(index="date", columns="method", values="max_weight")
for m in st.METHODS:
    axes[1].plot(mw.index, mw[m] * 100, lw=1, label=st.METHOD_LABEL[m])
axes[1].set_ylabel("largest single weight (%)"); axes[1].set_title("How concentrated it gets")
plt.show()
print(piv.describe().round(3).to_string())
"""
        ),
        md(
            r"""

### 3.5 Monte Carlo with planted structure
"""
        ),
        code(
            r"""
rows = []
for rho_in, rho_out, tag in ((0.7, 0.1, "strong blocks"), (0.5, 0.2, "moderate"),
                             (0.3, 0.25, "weak blocks"), (0.3, 0.3, "none")):
    acc = {m: [] for m in st.METHODS}
    for seed in range(10):
        X, _ = st.block_panel(n_per_block=10, n_blocks=2, n_obs=250, rho_in=rho_in,
                              rho_out=rho_out, seed=976 + seed)
        Y, _ = st.block_panel(n_per_block=10, n_blocks=2, n_obs=250, rho_in=rho_in,
                              rho_out=rho_out, seed=7000 + seed)
        cov_hat = np.cov(X, rowvar=False, ddof=1)
        for m in st.METHODS:
            acc[m].append(np.std(Y @ st.weights_for(m, cov_hat), ddof=1) * np.sqrt(252))
    rows.append({"world": tag, **{st.METHOD_LABEL[m]: float(np.mean(v)) for m, v in acc.items()}})
d = pd.DataFrame(rows).set_index("world")
fig, ax = plt.subplots(figsize=(10, 4.5))
(d * 100).plot.bar(ax=ax)
ax.set_ylabel("out-of-sample volatility (%)"); ax.legend(title="", fontsize=8)
ax.set_title("Weights fitted on one draw, priced on an independent one")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.6 Window sensitivity
"""
        ),
        code(
            r"""
rows = []
sub = rets[panels["names"]].dropna(how="any")
for w in (126, 252, 504, 756):
    s = st.summarise(st.walk_forward(sub, window=w, step=63, cost_bps=5.0))
    rows.append({"window": w, **{st.METHOD_LABEL[m]: s.loc[m, "realised_vol"]
                                 for m in st.METHODS}})
d = pd.DataFrame(rows).set_index("window")
fig, ax = plt.subplots(figsize=(9, 4.5))
(d * 100).plot(ax=ax, marker="o")
ax.set_ylabel("realised volatility (%)"); ax.legend(fontsize=8, title="")
ax.set_title("Does the ranking depend on how much history the matrix saw?")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
summary = {}
for tag, wf in all_wf.items():
    s = st.summarise(wf)
    summary[tag] = {
        "HRP vol": s.loc["hrp", "realised_vol"],
        "min-var vol": s.loc["min_var", "realised_vol"],
        "inv-var vol": s.loc["inv_var", "realised_vol"],
        "1/N vol": s.loc["equal", "realised_vol"],
        "t vs min-var": -st.paired_test(wf, "hrp", "min_var")["t"],
        "t vs inv-var": -st.paired_test(wf, "hrp", "inv_var")["t"],
        "t vs 1/N": -st.paired_test(wf, "hrp", "equal")["t"],
    }
pd.DataFrame(summary).T.round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **HRP on a shrunk covariance matrix**: the two remedies are not exclusive, and stacking them
  is the obvious experiment neither literature runs.
- **Nested clustered optimisation** (López de Prado 2019) is the successor, and it does invert
  matrices — inside clusters, where they are small and well conditioned.
- **Ward or average linkage**, and correlation distances built on tail dependence rather than
  Pearson correlation.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
