"""Build the two narrative notebooks for Study 90 (Weekend / day-of-week effect).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``weekend`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=8400, start="1993-01-29", end="2026-06-12", fp="eb1569cc9e97",
    mon_mean=5.64, tue_mean=7.17, wed_mean=6.20, thu_mean=1.46, fri_mean=3.32,
    mon_t=2.06, tue_t=2.64,
    mon_diff=1.08, mon_diff_t=0.36, tue_diff=3.03, tue_diff_t=1.00,
    mon_pre=4.78, mon_post=0.09, mon_change=-4.69, mon_change_t=-0.77,
    tue_pre=1.77, tue_post=3.36, tue_change=1.59, tue_change_t=0.23,
    tue_cagr=2.36, tue_sharpe=0.320, tue_dd=-37.4, tue_tim=21,
    skip_cagr=7.30, skip_sharpe=0.512, skip_dd=-48.9, skip_tim=81,
    b_cagr=10.82, b_sharpe=0.646, b_dd=-55.2,
    tue_cagr_gap=-8.46, skip_cagr_gap=-3.52,
    tue_sharpe_gap=-0.326, skip_sharpe_gap=-0.133,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (weekend/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from weekend import data, strategy

AS_OF = "2026-06-12"
frame = data.load_real("SPY", mode="total_return").loc[:AS_OF]
close = frame["close"]
wm = strategy.weekday_means(close)
bh = strategy.buy_and_hold(close)
tue_only = strategy.backtest(close, strategy.tuesday_only_position(close), cost_bps=1.0)
skip_mon = strategy.backtest(close, strategy.skip_monday_position(close), cost_bps=1.0)
print(f"SPY total return: {len(close):,} rows  {close.index[0].date()} -> {close.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(wm.round(2))
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Weekend effect still there?: Busted](https://img.shields.io/badge/Weekend_effect_still_there%3F-Busted-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# The Weekend Effect 📆\n"
            "### Are Mondays really negative, and does buying Tuesday beat the market?\n\n"
            + HERO_BADGES +
            "For decades the folklore has said the market falls over the weekend — a *negative "
            "Monday* — and bounces on *turnaround Tuesday*, so you should avoid Monday and buy "
            "Tuesday. We measure the average return on each weekday of SPY (dividends included) "
            "and ask the only two questions that matter: is the pattern **really there** (barely, "
            "and not the part everyone repeats), and could you **trade it** (no).\n\n"
            "> 📓 **This is the plain-language layer.** The HAC *t*-stats, the five-test selection "
            "problem and the pre/post-2000 split are in "
            "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below "
            "is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Is Monday negative (the weekend effect)? | **No** — Monday averages "
            f"**+{R['mon_mean']} bps**, *positive*. The famous part of the story isn't in the data. |\n"
            f"| Does Tuesday beat the other days? | **A little** — Tuesday is the best weekday "
            f"(+{R['tue_mean']} bps), but only **+{R['tue_diff']} bps** more than the rest, which "
            f"isn't statistically convincing. |\n"
            f"| Can you trade it? | **No** — \"buy Tuesday\" earns **{R['tue_cagr']}%/yr** vs "
            f"**{R['b_cagr']}%/yr** for just holding — about **{abs(R['tue_cagr_gap']):.0f} points/yr "
            f"less**, because you sit in cash four days out of five. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"Mondays are negative — the **weekend effect** — and Tuesday rebounds "
            "(**turnaround Tuesday**). Avoid Monday / buy Tuesday and you beat buy-and-hold.\"* "
            "It really was true once: Kenneth French's 1980 paper found significantly negative "
            "Mondays on 1953–1977 index data. The question is whether it's still true today."
        ),
        md(
            "## 2 · So what?\n\n"
            "If a calendar this simple beat the market, you'd just trade the days of the week and "
            "ignore everything else. And if a *published* anomaly quietly disappears once everyone "
            "knows it, that tells you something deep about how markets absorb information. Both are "
            "worth checking honestly rather than repeating the slogan."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We take SPY (dividends included), 1993 to today, and average the daily return on each "
            "weekday. Then we line Tuesday and Monday up against *all the other days*. Finally we "
            "build the two literal rules — **buy only on Tuesday** and **skip Monday** — and race "
            "them against simply holding SPY, paying **1 bp** every time we switch in or out. If "
            "the pattern is real and tradable, a rule should win. If it's a leftover slogan, it won't."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the average return on each weekday."),
        code(
            "fig, ax = plt.subplots(figsize=(9, 5))\n"
            "colors = ['C3' if d=='Mon' else ('C2' if d=='Tue' else 'C0') for d in wm.index]\n"
            "ax.bar(wm.index, wm['mean_bps'], color=colors, alpha=.85)\n"
            "ax.axhline(0, color='k', lw=.8)\n"
            "for d, v in wm['mean_bps'].items():\n"
            "    ax.text(d, v + .15, f'{v:+.1f}', ha='center', fontsize=10)\n"
            "ax.set_ylabel('Mean daily return (bps)'); ax.set_title('SPY total return — average return by weekday (1993-2026)')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            f"**Monday is the third-best day, not a negative one** (+{R['mon_mean']} bps). Tuesday "
            f"*is* the tallest bar (+{R['tue_mean']} bps) — the folklore got the *direction* of "
            "turnaround Tuesday right — but every weekday's average is positive. The defining "
            "feature of the weekend effect, a down-Monday, simply isn't here."
        ),
        md("Now the only test that matters for trading: do the literal rules beat just holding SPY?"),
        code(
            "fig, ax = plt.subplots(figsize=(10, 5.5))\n"
            "ax.plot(bh['equity'], label=f\"Buy & hold (CAGR {bh['cagr']*100:.1f}%)\", lw=1.4)\n"
            "ax.plot(skip_mon['equity'], label=f\"Skip Monday (CAGR {skip_mon['cagr']*100:.1f}%)\", lw=1.2, alpha=.85)\n"
            "ax.plot(tue_only['equity'], label=f\"Buy Tuesday only (CAGR {tue_only['cagr']*100:.1f}%)\", lw=1.2, alpha=.85)\n"
            "ax.set_yscale('log'); ax.set_ylabel('Growth of $1 (log)'); ax.legend()\n"
            "ax.set_title('Calendar rules vs simply holding SPY'); plt.tight_layout(); plt.show()"
        ),
        md(
            f"It isn't close. **Buy-Tuesday ends far below buy-and-hold** "
            f"({R['tue_cagr']}% vs {R['b_cagr']}% a year) because it's in cash ~79% of the time and "
            f"misses the upward drift on every other day. **Skip-Monday** does better but still "
            f"trails by ~{abs(R['skip_cagr_gap']):.0f} points/yr. You can't beat the market by "
            "sitting out part of it."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Weekend effect still there? → Busted.** Monday is *positive* (+{R['mon_mean']} bps), "
            "not negative — across the whole record, before and after 2000.\n"
            f"- **Signal → Weak.** Tuesday is the best day but only +{R['tue_diff']} bps above the "
            "rest, which isn't statistically convincing once you remember you're testing five days.\n"
            f"- **Trade it? → Mirage.** Every literal rule loses to buy-and-hold by "
            f"{abs(R['skip_cagr_gap']):.0f}–{abs(R['tue_cagr_gap']):.0f} points a year."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "Mechanically, yes — it's just SPY on a calendar, infinitely liquid. The problem is "
            "economic: a weekday rule keeps you out of the market on the days it doesn't favour, "
            "and the equity premium you forfeit on those days **dwarfs** any weekday tilt. As "
            "*\"a calendar that beats the index,\"* it's a mirage — and that's before taxes on "
            "thousands of switches."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Does the weekend effect survive on a **longer, pre-1993** index (price-only `^GSPC` "
            "back to the 1950s)? That's the window French studied — fork it and check.\n"
            "- Other calendar lore: turn-of-the-month, the Santa-Claus rally, sell-in-May.\n"
            "- Is there a *Monday-after-a-down-Friday* conditional effect hiding inside the flat "
            "unconditional Monday? Test it (with a Wilson interval on the conditional mean)."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# The Weekend Effect — a quantitative teardown 🔬\n"
            "### Real total-return tape · per-weekday HAC inference · five-test selection · pre/post-2000 difference\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We separate the three things "
            "the folklore asserts — **Monday is negative**, **Tuesday beats the rest**, and **a "
            "calendar rule beats the index** — and find the first is false, the second weak, the "
            "third a mirage.\n\n"
            "> ⚠️ **Not investment advice.** SPY daily, total-return adjusted (`quantlab.data`, Yahoo); "
            "cash earns 0% (conservative); 1 bp/switch; day-of-week is calendar-known so there is "
            "**no execution lag**. Sources in [`docs/references.md`](../docs/references.md), "
            "reproducible run in [`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `WEAK` | Tuesday's *own* mean clears the bar (+{R['tue_mean']} bps, HAC "
            f"*t* +{R['tue_t']}), but the *claim* (Tuesday − rest) is +{R['tue_diff']} bps, HAC *t* "
            f"**+{R['tue_diff_t']:.2f}** (\\|t\\| < 2); the Monday claim is the wrong sign. Five "
            f"weekday tests in play — no contrast survives a snooping-aware read. |\n"
            f"| **Tradability** | `MIRAGE` | Buy-Tuesday **{R['tue_cagr']}%** CAGR vs B&H "
            f"**{R['b_cagr']}%** ({R['tue_cagr_gap']} pts/yr); Skip-Monday {R['skip_cagr']}% "
            f"({R['skip_cagr_gap']} pts/yr). Both Sharpes below B&H. The tilt is dwarfed by lost beta. |\n"
            f"| **Weekend effect still there?** | `BUSTED` | Monday − rest **+{R['mon_diff']} bps** "
            f"(positive!), pre-2000 +{R['mon_pre']} and post-2000 +{R['mon_post']}; the change is "
            f"−{abs(R['mon_change']):.2f} bps, HAC *t* {R['mon_change_t']}. No negative Monday to find. |\n\n"
            "> 💡 **In plain words:** the one part of the slogan that's directionally true (Tuesday is "
            "best) is too weak to bank, and the headline part (down-Monday) isn't true on this tape at all."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (weekend effect):** Monday's mean return is significantly *negative* vs the rest.\n"
            "- **H₂ (turnaround Tuesday):** Tuesday's mean return is significantly *higher* than the rest.\n"
            "- **H₃ (tradable):** a literal weekday rule beats buy-and-hold on return / risk-adjusted return.\n\n"
            "French (1980) found H₁ on 1953–1977; the modern literature reports it decayed. SPY starts "
            "in 1993, so this is squarely a *post-publication* sample."
        ),
        md(
            "## 2 · So what? — what rides on each answer\n\n"
            "If H₃ held, the day of the week would dominate stock selection. It doesn't. And the "
            "*disappearance* of a once-real H₁ is a clean case study in how publishing an anomaly "
            "arbitrages it away — the more interesting finding than a fresh 'edge.'"
        ),
        md(
            "## 3 · How we'd know — the protocol\n\n"
            "Per-weekday mean with **HAC** *t* (daily returns are mildly autocorrelated) · the two "
            "contrasts as differences of means with HAC SEs combined in quadrature · a **pre-2000 vs "
            "post-2000** split with an explicit **test of the change** (not two separate means) on the "
            "pre-registered millennium cut · literal timers net of cost. **Mirage trigger:** no "
            "contrast clears |*t*| = 2 and every rule trails buy-and-hold."
        ),
        md("## 4 · The teardown\n\nPer-weekday means with HAC *t*-stats:"),
        code("wm.round(3)"),
        md("The two headline **contrasts** — each weekday vs all the others, HAC *t* on the difference:"),
        code(
            "mon = strategy.contrast(close, 0)\n"
            "tue = strategy.contrast(close, 1)\n"
            "print(f\"Monday  - rest: {mon['diff_bps']:+.2f} bps   HAC t {mon['hac_t']:+.2f}\")\n"
            "print(f\"Tuesday - rest: {tue['diff_bps']:+.2f} bps   HAC t {tue['hac_t']:+.2f}\")\n"
            "print('=> Monday claim has the wrong sign; Tuesday claim is right-signed but |t| < 2.')"
        ),
        md(
            "> 💡 **In plain words:** Tuesday genuinely is the best day, but 'best of five' is "
            "significant by construction unless you correct for running five tests — and the honest "
            "difference-from-the-rest doesn't clear the bar."
        ),
        md("**The decay story** — the *change* in each effect across the 2000 cut, with its own HAC *t*:"),
        code(
            "for wd, name in [(0,'Monday'),(1,'Tuesday')]:\n"
            "    sp = strategy.subperiod_effect(close, wd, cut='2000-01-01')\n"
            "    print(f\"{name:8s} pre {sp['pre_diff_bps']:+.2f}  post {sp['post_diff_bps']:+.2f}  \"\n"
            "          f\"change {sp['change_bps']:+.2f} bps  HAC t(change) {sp['hac_t_change']:+.2f}\")\n"
            "print('=> Monday is positive in BOTH halves; the change is not significant. Nothing decayed because nothing was there.')"
        ),
        md(
            "> 💡 **In plain words:** you can't certify a 'decay' on this tape — there was no "
            "significant down-Monday in the first half to decay from. The negative weekend effect "
            "predates the SPY era entirely."
        ),
        md("**The literal timers**, net of 1 bp/switch — the tradability read:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':  [tue_only['cagr']*100, skip_mon['cagr']*100, bh['cagr']*100],\n"
            "  'Vol %':   [tue_only['vol']*100, skip_mon['vol']*100, bh['vol']*100],\n"
            "  'Sharpe':  [tue_only['sharpe'], skip_mon['sharpe'], bh['sharpe']],\n"
            "  'MaxDD %': [tue_only['max_dd']*100, skip_mon['max_dd']*100, bh['max_dd']*100],\n"
            "  'TiM %':   [tue_only['time_in_market']*100, skip_mon['time_in_market']*100, bh['time_in_market']*100],\n"
            "}, index=['Buy Tuesday only', 'Skip Monday', 'Buy & hold'])\n"
            "tbl.round(2)"
        ),
        md(
            "> 💡 **In plain words:** the lost equity premium on the sat-out days swamps any weekday "
            "tilt. This is the same lesson as the death-cross study — *less time in market is less "
            "return*, dressed up as a calendar edge."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `WEAK` (Tuesday − rest +{R['tue_diff']} bps, HAC *t* +{R['tue_diff_t']:.2f}; "
            f"Monday wrong-signed), Tradability `MIRAGE` (buy-Tuesday {R['tue_cagr_gap']} pts/yr, "
            f"skip-Monday {R['skip_cagr_gap']} pts/yr vs B&H), Weekend effect still there? `BUSTED` "
            f"(Monday +{R['mon_diff']} bps, change HAC *t* {R['mon_change_t']}). The literature's "
            "1980 effect is not certifiable on the 1993–2026 SPY tape."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (SPY). The binding fact is economic: any weekday filter forfeits "
            "the equity premium on the days it sits out, and that lost beta is an order of magnitude "
            "larger than the ~3 bps/day Tuesday tilt. Net of tax on thousands of round-trips the gap "
            "only widens. There is no residual edge to size."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Extend to **price-only `^GSPC`** back to the 1950s (label it price-only — no dividends) "
            "to test French's *original* window and date the effect's disappearance.\n"
            "- Apply a **data-snooping correction** (White Reality Check / stationary bootstrap) over "
            "the five weekday rules to put a snooping-aware *p* on 'best weekday'.\n"
            "- **Conditional** weekend effect: Monday return given a down Friday, with a Wilson "
            "interval on the conditional mean — does the unconditional flat hide a state-dependent tilt?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
