"""Build the two narrative notebooks for Study 51 (Blue-Chip).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the shared EDGAR cache (_cache/_edgar_GrossProfit.parquet + _edgar_Assets + _edgar_yrret)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (blue_chip/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from blue_chip import data, strategy as st
sig, fwd = data.fetch_panel()                  # cache-first (shared EDGAR pull)
h = st.quantile_hedge(sig, fwd, q=0.2, long_high=True)
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Quality premium is real?: Supported](https://img.shields.io/badge/Quality_premium_is_real%3F-Supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Blue-Chip 💎\n### The quality premium — the factor that survived, glimpsed through a short window\n\n"
           + VERDICT +
           "After size and value faded, one factor kept working: **quality** — profitable firms out-earn "
           "unprofitable ones. On real SEC balance-sheet data it points the right way (profitable beats "
           "unprofitable by ~3 pts/year), but we can only see ~18 years of machine-readable filings, too "
           "few to confirm the strong premium the long history shows.\n\n"
           "> 📓 **Plain-language layer.** The t-stat and the sample limit are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The claim | The data (~2007–2025) |\n|---|---|\n"
           "| \"Profitable firms out-earn\" | True direction: **+3.3%/yr**, hit **61%**. |\n"
           "| \"A strong premium\" | Modest here: **Sharpe 0.20 (t ≈ 0.8)**. |\n"
           "| \"Confirmed\" | The strong decades pre-date machine-readable filings. |"),
        md("## 1 · The claim\n\nNovy-Marx (2013): gross profitability — gross profit over total assets — "
           "is the cleanest quality signal; high-GP firms out-earn low-GP firms, about as strongly as "
           "value, and the premium survived where others decayed."),
        md("## 2 · So what?\n\nIf quality pays, you can tilt to profitable, blue-chip firms and earn a "
           "premium with *lower* risk than value or small-cap bets. It's the rare factor with a clean "
           "economic story — and the one most likely to be real."),
        md("## 3 · How would we even know?\n\nPull gross profit and assets straight from SEC filings, sort "
           "firms by GP/assets, go long the most profitable and short the least, and measure the annual "
           "hedge — while being honest that machine-readable filings only start ~2007."),
        code("disp = h[['high','low','hedge']].rename(columns={'high':'high-GP (long)','low':'low-GP (short)'})\n"
             "ax=(disp*100).plot(title='Annual returns: high-GP vs low-GP, and the hedge',lw=1.4)\n"
             "ax.axhline(0,color='k',lw=.8); ax.set_ylabel('%/yr'); plt.show()\n"
             "s=st.summary(h['hedge']); print(f\"hedge mean {s['mean']:+.2%}/yr, Sharpe {s['sharpe']:.2f}, t≈{s['tstat']:.1f}, hit {s['hit_rate']:.0%}\")"),
        md("## 4 · The teardown\n\nThe high-GP leg edges out the low-GP leg most years — the right sign — "
           "but the gap is small and the sample short, so the Sharpe is modest."),
        code("eq=(1+h['hedge']).cumprod()\n"
             "ax=eq.plot(title='Growth of $1 in the quality long-short (annual)',lw=1.8)\n"
             "ax.axhline(1.0,color='k',lw=.8,ls='--'); ax.set_ylabel('growth of $1'); plt.show()"),
        md("**Read it plainly.** Quietly upward — quality *did* pay, just modestly on the ~18 years SEC "
           "data lets us see. The famous strong premium lives in the pre-2007 decades we can't reach for free."),
        md("## 5 · The verdict\n\n**Signal: Weak** — positive, right sign, but t ≈ 0.8. **Tradability: "
           "Fragile** — short, survivorship-biased sample. **Quality premium real?: Supported** by sign + literature."),
        md("## 6 · Could you actually trade it?\n\nQuality is the most defensible factor to tilt toward — "
           "and tradable via low-cost ETFs (QUAL, etc.). Our caution is about *confirmation* on free data, "
           "not about the factor: unlike the inverted lottery/idio-vol studies, quality points the right way."),
        md("## 7 · Going further 🚪\n\nThe companion fundamental study is [Study 52 Smoke-Screen](../../52-smoke-screen/) "
           "(accruals), which replicates more strongly on the same data. Contrast with the inverted "
           "[53 Jackpot](../../53-jackpot/) / [54 Static](../../54-static/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Blue-Chip — a quantitative teardown 🔬\n### The quality long-short on real EDGAR data · the t-stat · the two legs · why ~18 years under-powers it\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We build "
           "gross-profitability quality on SEC data and show it points right but can't be confirmed here.\n\n"
           "> ⚠️ **Not investment advice.** EDGAR GrossProfit/Assets + Yahoo annual returns, current "
           "S&P 500 members, ~2007–2025 (survivorship-biased, large-cap, short). Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | hedge +3.3%/yr, Sharpe 0.20, t ≈ 0.8 |\n"
           "| Tradability | **Fragile** | ~18 XBRL years, survivorship, large-cap |\n"
           "| Quality real? | **Supported** | right sign + Novy-Marx (2013) |\n\n"
           "> 💡 *In plain words:* a real factor we can only glimpse on free data."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** high-GP firms out-earn low-GP firms (positive "
           "hedge).\n- **H₂:** it's significant.\n- **H₃:** it's a known, durable factor."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold on free data, quality is a confirmed, "
           "tradable tilt. If only H₁/H₃ hold, the factor is real but our window is too short to prove it."),
        md("## 3 · How we'd know — the protocol\n\nGP/Assets → annual long-high/short-low → the hedge's "
           "mean, Sharpe, t-stat and hit rate → the two legs vs the universe."),
        md("## 4 · The teardown"),
        md("### 4.1 The hedge"),
        code("display(h.round(3))\n"
             "s=st.summary(h['hedge']); print(f\"hedge: mean {s['mean']:+.2%}/yr  Sharpe {s['sharpe']:.2f}  t≈{s['tstat']:.1f}  hit {s['hit_rate']:.0%}  n={s['n']}\")"),
        md("> 💡 *In plain words:* positive (+3.3%/yr, hit 61%) — **H₁ holds** — but t ≈ 0.8, **H₂ rejected** on this sample."),
        md("### 4.2 The two legs vs the universe"),
        code("print('high-GP leg : %+.2f%%' % (st.summary(h['high'])['mean']*100))\n"
             "print('low-GP leg  : %+.2f%%' % (st.summary(h['low'])['mean']*100))\n"
             "print('universe    : %+.2f%%' % (st.summary(st.market_annual(fwd).reindex(h.index))['mean']*100))"),
        md("> 💡 *In plain words:* high-GP beats low-GP by ~3 pts/yr, both near the universe — a mild tilt, the right way."),
        md("### 4.3 Why ~18 years under-powers a real effect"),
        md("SEC machine-readable (XBRL) filings start ~2007, so we miss the 1963–2007 decades where "
           "Novy-Marx documents the strong quality premium. With ~18 annual observations, even a genuine "
           "effect carries a t near 0.8. Add survivorship (current members) and a large-cap-only universe "
           "(quality's short leg is often smaller, distressed names), and the *test* is under-powered — "
           "not the factor. **H₃ supported by sign + literature.**"),
        md("## 5 · The verdict\n\nH₁ holds, H₂ rejected (sample), H₃ supported → Signal `WEAK`, "
           "Tradability `FRAGILE`, quality premium `SUPPORTED`."),
        md("## 6 · Could you trade it?\n\nYes, via low-cost quality ETFs — it's the most defensible factor "
           "tilt. The honest caveat is confirmation power on free data, not the premium's existence."),
        md("## 7 · Going further\n\nForks: (a) a longer Compustat-style history (paywalled) to recover the "
           "pre-2007 premium; (b) the full QMJ composite (profitability + growth + safety + payout); "
           "(c) value-weighted, broader universe. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
