"""Build the two narrative notebooks for Study 64 (Share-Shuffle).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (shared EDGAR pull)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (share_shuffle/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from share_shuffle import data, strategy as st
sig, fwd = data.fetch_panel()                  # cache-first (shared EDGAR pull)
h = st.quantile_hedge(sig, fwd, q=0.2, long_high=False)   # long low-issuance / buyback
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Issuance anomaly on large caps?: Not supported](https://img.shields.io/badge/Issuance_anomaly_on_large_caps%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Share-Shuffle 🔀\n### Do companies that issue stock underperform the ones buying it back?\n\n"
           + VERDICT +
           "The textbook anomaly: firms that print new shares go on to lag, firms that buy back their own "
           "stock go on to win. It's one of the best-documented effects in academic finance. So we built it "
           "on real SEC filings for the S&P 500 — and it ran **backwards**. The big *issuers* "
           "(+22.8%/yr) actually *beat* the buyback names (+20.0%).\n\n"
           "> 📓 **Plain-language layer.** The long-short, the backwards sign, and the small-cap explanation "
           "are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every number is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The question | The data (~412 S&P names, ~2010–2025) |\n|---|---|\n"
           "| \"Do issuers underperform buyback firms?\" | No — they **beat** them by ~3%/yr here. |\n"
           "| \"Is the famous anomaly tradable on large caps?\" | No: hedge **−2.8%/yr, Sharpe −0.30**. |\n"
           "| \"So where is the real effect?\" | In small caps — the wrong universe for a free EDGAR pull. |"),
        md("## 1 · The claim\n\nNet share issuance — the year-on-year change in shares outstanding — "
           "negatively predicts returns (Pontiff & Woodgate 2008; Daniel & Titman 2006). Issue stock, "
           "underperform; retire stock, outperform. The folk version: *buybacks are a vote of confidence, "
           "dilution is a warning.*"),
        md("## 2 · So what?\n\nIf true and tradable, you'd tilt toward the disciplined cannibals and away "
           "from the diluters — a clean fundamental signal you can pull straight from 10-K filings for free. "
           "The question is whether it survives on the names you can actually trade in size."),
        md("## 3 · How would we even know?\n\nPull diluted shares outstanding from EDGAR for the S&P 500, "
           "compute each firm's net issuance, sort every year, go long the bottom-20% (buyers) and short the "
           "top-20% (issuers), and measure next year's hedge return over the XBRL era."),
        code("legs = pd.DataFrame({'buyback leg (long)': st.summary(h['low'])['mean'],\n"
             "                     'issuer leg (short)': st.summary(h['high'])['mean'],\n"
             "                     'market': st.summary(st.market_annual(fwd).reindex(h.index))['mean']},\n"
             "                    index=['annual return'])\n"
             "ax=(legs.T*100).plot.bar(rot=0,legend=False,color=['#2ea44f','#c0392b','#8b949e'],\n"
             "    title='Annual return by leg — the issuers (red) beat the buyers (green)')\n"
             "ax.set_ylabel('%'); ax.axhline(0,color='k',lw=.8); plt.show()"),
        md("## 4 · The teardown — the sign is backwards\n\nThe hedge that's *supposed* to pay (long buyers, "
           "short issuers) lost money, and lost it in nearly three-quarters of years."),
        code("s=st.summary(h['hedge'])\n"
             "print(f\"hedge (long buyback, short issuer): {s['mean']:+.2%}/yr  Sharpe {s['sharpe']:.2f}  (t~{s['tstat']:.1f})  hit {s['hit_rate']:.0%}\")\n"
             "(h['hedge']*100).plot.bar(color=['#2ea44f' if v>0 else '#c0392b' for v in h['hedge']],\n"
             "    title='Yearly hedge return (long buyback / short issuer) — mostly red')\n"
             "plt.ylabel('%'); plt.axhline(0,color='k',lw=.8); plt.show()"),
        md("**Read it plainly.** Over 2010–2025 the heaviest large-cap \"issuers\" were the growth/tech "
           "winners diluting through stock-based comp and acquisitions — exactly the names that led the "
           "market. Punishing dilution meant shorting the winners."),
        md("## 5 · The verdict\n\n**Signal: Weak** — it inverts (−2.8%/yr, t −1.3). **Tradability: Mirage** "
           "— wrong sign on liquid names. **Issuance anomaly on tradable large caps?: Not supported.** The "
           "real effect lives in small caps."),
        md("## 6 · Could you actually trade it?\n\nNot as built. The published anomaly is strongest in small, "
           "illiquid names (secondary offerings, distressed dilution) — the untradable end of the market. On "
           "the large caps you can size into, survivorship and the post-2009 growth regime flip its sign. "
           "A real factor, in the wrong universe."),
        md("## 7 · Going further 🚪\n\nThe issuance sibling of [44 Growth-Spurt](../../44-growth-spurt/) "
           "(asset growth) and a fundamental cousin of [52 Smoke-Screen](../../52-smoke-screen/) (accruals, "
           "which *does* replicate). Forks: micro-cap universe, value-weighting, composite issuance."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Share-Shuffle — a quantitative teardown 🔬\n### The net-issuance long-short · the inverted sign · the small-cap / survivorship explanation\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). A real "
           "academic anomaly that runs backwards on the tradable end of the market.\n\n"
           "> ⚠️ **Not investment advice.** SEC EDGAR diluted shares + Yahoo annual returns, ~412 current "
           "S&P 500 members, XBRL era. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | hedge −2.8%/yr, Sharpe −0.30, t −1.3 — inverted |\n"
           "| Tradability | **Mirage** | issuers beat buyers on large caps |\n"
           "| Anomaly on large caps? | **Not supported** | the real effect is a small-cap one |\n\n"
           "> 💡 *In plain words:* a genuine factor, measured in the wrong universe."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** high net issuance predicts low forward returns.\n"
           "- **H₂:** the long-buyback / short-issuer hedge is positive and significant.\n"
           "- **H₃:** it's tradable on liquid large caps (not just micro-caps)."),
        md("## 2 · So what? — what rides on each\n\nH₁/H₂ would make issuance a free, fundamentals-based "
           "signal straight from 10-Ks. H₃ decides whether it survives where you can actually trade. A "
           "small-cap-only effect is real science but useless to a large-cap book."),
        md("## 3 · How we'd know — the protocol\n\nEDGAR diluted shares → net issuance (YoY change) → annual "
           "quintile sort → long bottom-20% (buyers), short top-20% (issuers) → next-year hedge, Sharpe, "
           "t-stat, hit rate over the XBRL window."),
        md("## 4 · The teardown"),
        md("### 4.1 The long-short, year by year"),
        code("disp=h.copy(); disp.columns=['issuer leg','buyer leg','hedge (buyer-issuer)']\n"
             "display((disp*100).round(1))\n"
             "s=st.summary(h['hedge']); print({k:round(v,3) for k,v in s.items()})"),
        md("> 💡 *In plain words:* the hedge mean is **negative** (−2.8%/yr) and wins only ~28% of years. "
           "**H₁ and H₂ are rejected on this universe** — the sign is backwards."),
        md("### 4.2 Why the sign inverts — H₃ fails"),
        md("Three forces flip it on large caps:\n\n"
           "1. **Issuers were the winners.** 2010–2025's heavy large-cap issuers were high-growth tech "
           "diluting via stock-based comp and M&A — the market leaders.\n"
           "2. **The anomaly lives in small caps.** Pontiff-Woodgate's effect concentrates in small, "
           "illiquid names; Hou-Xue-Zhang (2020) show financing anomalies fade with value-weighting and "
           "NYSE breakpoints.\n"
           "3. **Survivorship.** Current members exclude the dilutive blow-ups that delisted — which would "
           "have helped the short — yet even this biased test can't find the effect. **H₃ rejected.**"),
        md("## 5 · The verdict\n\nH₁/H₂/H₃ all rejected on tradable large caps → Signal `WEAK` (inverted), "
           "Tradability `MIRAGE`, anomaly-on-large-caps `NOT SUPPORTED`. The fingerprinted run is in "
           "[`docs/results.md`](../docs/results.md)."),
        md("## 6 · Could you trade it?\n\nNot on this universe. To harvest the real premium you'd need a "
           "small-cap, value-weighted, NYSE-breakpoint book with the delisted names included — outside what "
           "a free EDGAR pull on current S&P members can offer, and outside what most large books can size."),
        md("## 7 · Going further\n\nForks: (a) a Russell 2000 / micro-cap universe; (b) composite issuance "
           "(Daniel-Titman) vs raw share count; (c) combine with accruals ([52](../../52-smoke-screen/)) and "
           "asset growth ([44](../../44-growth-spurt/)) into a financing factor. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
