"""Notebook builder for Study 995 — Whose Sharpe Is It?.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Whose Sharpe Is It? \U0001F310
### The same fund. The same shares. Six different answers.

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

Every performance statistic you have ever read was computed in some currency, almost always
dollars, almost always without saying so. If you do not spend dollars, the number is not about
you — and the gap is bigger than most people would guess.

> \U0001F4D3 **This is the plain-language layer.** The variance identity, the three-way
> decomposition and the hedge ratios are in
> **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Does your currency change a fund's Sharpe? | Substantially. |
| Is that just the exchange rate drifting? | No — a third of it is pure added risk. |
| Does it change which fund looks best? | Sometimes, yes. |
| Should you hedge? | For the risk reduction, usually. For the return, no. |
"""
        ),
        md(
            r"""

## 1 · One fund, six investors
"""
        ),
        code(
            r"""
from whosesharpe import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
fx_rets = {k: rets[v].dropna() for k, v in data.FX.items()
           if v in rets.columns and rets[v].notna().sum() > 1000}
asset = rets[data.ASSET].dropna()
common = asset.index
for f in fx_rets.values():
    common = common.intersection(f.index)
asset = asset.reindex(common).dropna()
usd_rf = rets[data.CASH].reindex(asset.index).fillna(0.0)
fx_rets = {k: v.reindex(asset.index).dropna() for k, v in fx_rets.items()}
tbl = st.sharpe_by_currency(asset, fx_rets, usd_rf)
print(f"as-of {data.AS_OF} | {data.ASSET}, {asset.index[0].date()} -> "
      f"{asset.index[-1].date()} ({len(asset) / 252:.1f} years)")
print(tbl[["cagr", "vol", "rf_ann", "sharpe"]].round(4).to_string())
"""
        ),
        code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
tbl["sharpe"].plot.bar(ax=axes[0], color=["#1f6feb"] + ["#2ea44f"] * (len(tbl) - 1))
axes[0].axhline(tbl.loc["USD", "sharpe"], color="k", ls="--", lw=1.5,
                label="the number everyone quotes")
axes[0].set_ylabel("Sharpe ratio"); axes[0].legend(fontsize=8)
plt.setp(axes[0].get_xticklabels(), rotation=0)
axes[1].scatter(tbl["vol"] * 100, tbl["cagr"] * 100, s=90, color="#2ea44f")
for cur, row in tbl.iterrows():
    axes[1].annotate(cur, (row["vol"] * 100, row["cagr"] * 100), fontsize=8,
                     xytext=(5, 3), textcoords="offset points")
axes[1].set_xlabel("volatility (%)"); axes[1].set_ylabel("CAGR (%)")
axes[1].set_title("same shares, different experience")
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** Note the `rf_ann` column in the table above. Each investor's
> Sharpe is computed against *their own* cash rate, not the US Treasury bill. That correction is
> almost never made and it matters by tenths of a Sharpe point.
"""
        ),
        md(
            r"""

## 2 · Why the volatility goes up

This part is arithmetic, not opinion. If you hold a dollar asset and spend euros, your return is
the asset minus the currency — and the variance of a difference is

`var(a − c) = var(a) + var(c) − 2·cov(a, c)`

Unless the currency reliably rises when the asset rises, you have just added risk.
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    d = st.variance_decomposition(asset, f)
    rows.append({"currency": k, "correlation": d["corr"], "vol in USD": d["vol_asset"],
                 "vol at home": d["vol_converted"], "ratio": d["vol_ratio"]})
d = pd.DataFrame(rows).set_index("currency")
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.bar(range(len(d)), (d["ratio"] - 1) * 100, color="#c0392b")
ax.axhline(0, color="k", lw=1.5)
ax.set_xticks(range(len(d))); ax.set_xticklabels(d.index)
ax.set_ylabel("extra volatility from the currency (%)")
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

## 3 · Drift, variance, or rates?

Three different reasons a currency changes your Sharpe, and only one of them is durable.
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    dd = st.decompose_sharpe_gap(asset, f, usd_rf)
    rows.append({"currency": k, "drift (luck)": dd["drift_term"],
                 "variance (permanent)": dd["variance_term"],
                 "rates (persistent)": dd["rate_term"], "total": dd["gap"]})
d = pd.DataFrame(rows).set_index("currency")
fig, ax = plt.subplots(figsize=(11, 5))
d[["drift (luck)", "variance (permanent)", "rates (persistent)"]].plot.bar(
    ax=ax, stacked=True, color=["#8b949e", "#c0392b", "#f0b429"])
ax.plot(range(len(d)), d["total"], "ko-", lw=2, ms=7, label="total gap")
ax.axhline(0, color="k", lw=1.5)
ax.set_ylabel("change in Sharpe vs a US investor"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

The grey bars are the dollar's wanderings over one particular eighteen years. Nobody should plan
around them. The red bars are arithmetic and will be there next decade too.
"""
        ),
        md(
            r"""

## 4 · Does it change which fund wins?
"""
        ),
        code(
            r"""
assets = {tk: rets[tk].reindex(asset.index).dropna()
          for tk in (data.ASSET,) + data.ALT_ASSETS if tk in rets.columns}
assets = {k: v for k, v in assets.items() if len(v) > 1000}
rank = st.ranking_stability(assets, fx_rets, usd_rf)
body = rank.drop("_rank_spread")
fig, ax = plt.subplots(figsize=(11, 5))
im = ax.imshow(body.rank(ascending=False).values, cmap="RdYlGn_r", aspect="auto")
ax.set_xticks(range(body.shape[1])); ax.set_xticklabels(body.columns)
ax.set_yticks(range(body.shape[0])); ax.set_yticklabels(body.index)
for i in range(body.shape[0]):
    for j in range(body.shape[1]):
        ax.text(j, i, f"{body.values[i, j]:.2f}", ha="center", va="center", fontsize=8)
ax.set_title("Sharpe by asset (rows) and home currency (columns); colour = rank")
plt.show()
print("best asset by home currency:")
for c in body.columns:
    print(f"  {c}: {body[c].idxmax()}")
"""
        ),
        md(
            r"""

## 5 · Should you hedge?
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    ha = st.hedge_analysis(asset, f, usd_rf, cost_bps=3.0)
    t = ha["table"]
    rows.append({"currency": k, "unhedged": ha["unhedged"]["sharpe"],
                 "hedged": t.loc[1.0, "sharpe"], "gain": ha["sharpe_gain"],
                 "vol saved": ha["unhedged"]["vol"] - t.loc[1.0, "vol"],
                 "optimal ratio": ha["optimal_ratio"]})
d = pd.DataFrame(rows).set_index("currency")
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
d[["unhedged", "hedged"]].plot.bar(ax=axes[0], color=["#8b949e", "#2ea44f"])
axes[0].set_ylabel("Sharpe ratio"); axes[0].legend(fontsize=8)
plt.setp(axes[0].get_xticklabels(), rotation=0)
axes[1].bar(range(len(d)), d["vol saved"] * 100, color="#1f6feb")
axes[1].set_xticks(range(len(d))); axes[1].set_xticklabels(d.index)
axes[1].set_ylabel("volatility removed by hedging (%)")
plt.tight_layout(); plt.show()
print(d.round(4).to_string())
"""
        ),
        md(
            r"""

The hedge reliably removes volatility. Whether it improves the *return* depends on which way the
currency went, which is exactly the thing nobody can forecast — so the honest case for hedging
is the risk one, not the return one.
"""
        ),
        md(
            r"""

## 6 · The verdict

**Signal: Weak.** Over 19 years, SPY delivered a Sharpe of **0.46** to a dollar-based investor and anywhere from **0.35** (CHF) to **0.50** (CAD) to investors based elsewhere — a spread of **0.15**, on the identical shares. Three separate channels do the work and they behave differently. The **variance** channel is mechanical: adding a currency leg raised volatility from 19.7% to a median 19.4% because var(a−c) = var(a) + var(c) − 2cov, and the median correlation between SPY and these currencies was only +0.27. The **drift** channel is luck: the dollar happened to move. The **rate** channel is the one nobody adjusts for — each investor's cash leg is their own, and using the US bill rate for everyone (the standard shortcut) biases every high-rate country's Sharpe downward. Across 5 assets the currency moved at least one pair's ranking by **1 places**.

**Tradability: Partial.** Hedging is priced here rather than assumed, because a rolling forward hedge earns the **interest-rate differential** and not zero — selling dollars forward while US rates exceed yours costs you the gap, which is the charge hedged share classes pass on quietly. After that charge, a full hedge raised the Sharpe for **50%** of the currencies here, by a median -0.00. The variance-minimising ratio is not 1.0 either: its median across currencies is **1.57**, because SPY itself co-moves with risk-off currencies, so a full hedge is close to right. The practical reading is that the hedge buys volatility reduction reliably and return unreliably — which is the right way round for a long-horizon holder and the wrong way round for anyone hoping the hedge pays for itself.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Check the horizon.** Froot (1993) argues real exchange rates mean-revert over decades, so
  the hedge matters far less to a thirty-year holder than to a three-year one.
- **Hedge partially.** The variance-minimising ratio is not 1.0 and is not 0. Campbell et al.
  (2010) compute it properly across a whole portfolio rather than asset by asset.
- **Watch the tax.** Currency gains are taxed differently in every jurisdiction here, sometimes
  as income, which can outweigh everything above.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Whose Sharpe Is It? — a quantitative teardown \U0001F52C
### Exact conversion · the variance identity · drift/variance/rate decomposition · hedge carry

![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)
![Tradability: Partial](https://img.shields.io/badge/Tradability-Partial-dab617?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Three channels
move a Sharpe ratio when you change currency, and they have completely different half-lives.
Separating them is the study.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance pinned as-of the date in
> [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from whosesharpe import data, strategy as st

px = data.load_prices()
rets = px.pct_change()
fx_rets = {k: rets[v].dropna() for k, v in data.FX.items()
           if v in rets.columns and rets[v].notna().sum() > 1000}
asset = rets[data.ASSET].dropna()
common = asset.index
for f in fx_rets.values():
    common = common.intersection(f.index)
asset = asset.reindex(common).dropna()
usd_rf = rets[data.CASH].reindex(asset.index).fillna(0.0)
fx_rets = {k: v.reindex(asset.index).dropna() for k, v in fx_rets.items()}
tbl = st.sharpe_by_currency(asset, fx_rets, usd_rf)
print(f"as-of {data.AS_OF} | {data.ASSET}, {asset.index[0].date()} -> "
      f"{asset.index[-1].date()} ({len(asset) / 252:.1f} years)")
print(tbl[["cagr", "vol", "rf_ann", "sharpe"]].round(4).to_string())
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Weak | Over 19 years, SPY delivered a Sharpe of **0.46** to a dollar-based investor and anywhere from **0.35** (CHF) to **0.50** (CAD) to investors based elsewhere — a spread of **0.15**, on the identical shares. Three separate channels do the work and they behave differently. The **variance** channel is mechanical: adding a currency leg raised volatility from 19.7% to a median 19.4% because var(a−c) = var(a) + var(c) − 2cov, and the median correlation between SPY and these currencies was only +0.27. The **drift** channel is luck: the dollar happened to move. The **rate** channel is the one nobody adjusts for — each investor's cash leg is their own, and using the US bill rate for everyone (the standard shortcut) biases every high-rate country's Sharpe downward. Across 5 assets the currency moved at least one pair's ranking by **1 places**. |
| **Tradability** | Partial | Hedging is priced here rather than assumed, because a rolling forward hedge earns the **interest-rate differential** and not zero — selling dollars forward while US rates exceed yours costs you the gap, which is the charge hedged share classes pass on quietly. After that charge, a full hedge raised the Sharpe for **50%** of the currencies here, by a median -0.00. The variance-minimising ratio is not 1.0 either: its median across currencies is **1.57**, because SPY itself co-moves with risk-off currencies, so a full hedge is close to right. The practical reading is that the hedge buys volatility reduction reliably and return unreliably — which is the right way round for a long-horizon holder and the wrong way round for anyone hoping the hedge pays for itself. |

> \U0001F4A1 **In plain words.** One of the three channels is arithmetic, one is a coin flip, and
> one is a rate differential nobody adjusts for. They are usually reported as a single number.
"""
        ),
        md(
            r"""

## 1 · Hypotheses

- **H₁.** The Sharpe of one asset differs materially across home currencies.
- **H₂ (variance).** Volatility rises for every currency whose correlation with the asset is
  below `σ_c / (2σ_a)`, exactly as `var(a−c) = var(a) + var(c) − 2cov` requires.
- **H₃ (rates).** Using the US risk-free rate for all investors biases high-rate countries'
  Sharpe downward by a measurable amount.
- **H₄ (ranking).** The currency does more than shift every Sharpe equally — it reorders assets.
- **H₅ (hedging).** After charging the interest-rate differential, hedging raises the Sharpe for
  most currencies, and the variance-minimising ratio is not 1.0.
"""
        ),
        md(
            r"""

## 2 · The conversion, done exactly
"""
        ),
        code(
            r"""
# the difference between the exact form and the usual approximation, compounded
n = len(asset)
k = list(fx_rets)[0]
f = fx_rets[k]
exact = st.convert_return(asset, f)
naive = (asset - f).reindex(exact.index)
fig, ax = plt.subplots(figsize=(11, 4.5))
ax.plot(exact.index, (1 + exact).cumprod(), lw=1.8, color="#2ea44f",
        label="(1+r)/(1+f) - 1  (exact)")
ax.plot(naive.index, (1 + naive).cumprod(), lw=1.8, ls="--", color="#c0392b",
        label="r - f  (the usual shortcut)")
ax.set_yscale("log"); ax.set_ylabel(f"growth of 1 {k}"); ax.legend(fontsize=9)
plt.show()
print(f"terminal difference: {(1 + exact).prod() / (1 + naive).prod() - 1:+.2%} over "
      f"{len(exact) / 252:.0f} years")
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The shortcut is fine for a day and wrong for a decade. Every
> conversion in this study uses the exact form.
"""
        ),
        md(
            r"""

## 3 · The teardown

### 3.1 The full table, with each investor's own cash rate
"""
        ),
        code(
            r"""
print(st.sharpe_by_currency(asset, fx_rets, usd_rf).round(4).to_string())
print()
print("implied local risk-free rates (annualised, from covered interest parity):")
for k, f in fx_rets.items():
    rf_l = st.implied_foreign_rate(f, usd_rf)
    print(f"  {k}: {rf_l.mean() * 252:.2%}   vs USD {usd_rf.mean() * 252:.2%}")
"""
        ),
        code(
            r"""
# how much the rate correction alone is worth
rows = []
for k, f in fx_rets.items():
    conv = st.convert_return(asset, f)
    loc = st.implied_foreign_rate(f, usd_rf).reindex(conv.index).fillna(0.0)
    usd = usd_rf.reindex(conv.index).fillna(0.0)
    rows.append({"currency": k,
                 "Sharpe using US rate": st.sharpe(conv - usd),
                 "Sharpe using own rate": st.sharpe(conv - loc)})
d = pd.DataFrame(rows).set_index("currency")
d["error from the shortcut"] = d["Sharpe using US rate"] - d["Sharpe using own rate"]
fig, ax = plt.subplots(figsize=(10, 4.5))
d[["Sharpe using US rate", "Sharpe using own rate"]].plot.bar(ax=ax,
                                                              color=["#c0392b", "#2ea44f"])
ax.set_ylabel("Sharpe ratio"); ax.legend(fontsize=8)
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 3.2 The variance identity, checked
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    d = st.variance_decomposition(asset, f)
    rows.append({"currency": k, **{kk: d[kk] for kk in
                 ("corr", "var_asset", "var_fx", "cov", "predicted_var", "realised_var",
                  "vol_ratio", "approximation_error")}})
d = pd.DataFrame(rows).set_index("currency")
print(d.round(8).to_string())
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(d["predicted_var"] * 1e4, d["realised_var"] * 1e4, s=90, color="#2ea44f")
lim = [0, max(d["realised_var"].max(), d["predicted_var"].max()) * 1e4 * 1.1]
ax.plot(lim, lim, "k--", lw=1.5)
for cur, r in d.iterrows():
    ax.annotate(cur, (r["predicted_var"] * 1e4, r["realised_var"] * 1e4), fontsize=8,
                xytext=(5, 3), textcoords="offset points")
ax.set_xlabel("var(a) + var(c) - 2cov  (x1e4)")
ax.set_ylabel("realised variance of the converted return (x1e4)")
ax.set_title("The identity holds; the gap is the simple-vs-log approximation")
plt.show()
"""
        ),
        md(
            r"""

### 3.3 The three-way decomposition
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    dd = st.decompose_sharpe_gap(asset, f, usd_rf)
    rows.append({"currency": k, **{kk: dd[kk] for kk in
                 ("sharpe_home", "sharpe_foreign", "gap", "drift_term", "variance_term",
                  "rate_term", "vol_ratio", "rate_gap_ann")}})
d = pd.DataFrame(rows).set_index("currency")
print(d.round(4).to_string())
print()
print(f"variance term: median {d['variance_term'].median():+.3f}, "
      f"{(d['variance_term'] < 0).sum()} of {len(d)} negative  <- systematic")
print(f"drift term:    median {d['drift_term'].median():+.3f}, "
      f"{(d['drift_term'] > 0).sum()} positive / {(d['drift_term'] < 0).sum()} negative "
      f"  <- coin flip")
print(f"rate term:     median {d['rate_term'].median():+.3f}")
"""
        ),
        md(
            r"""

### 3.4 Ranking stability
"""
        ),
        code(
            r"""
assets = {tk: rets[tk].reindex(asset.index).dropna()
          for tk in (data.ASSET,) + data.ALT_ASSETS if tk in rets.columns}
assets = {k: v for k, v in assets.items() if len(v) > 1000}
rank = st.ranking_stability(assets, fx_rets, usd_rf)
body = rank.drop("_rank_spread")
ranks = body.rank(ascending=False)
print(body.round(3).to_string())
print()
print(ranks.astype(int).to_string())
fig, ax = plt.subplots(figsize=(10, 5))
for a in body.index:
    ax.plot(range(len(body.columns)), ranks.loc[a], "o-", lw=1.8, ms=6, label=a)
ax.set_xticks(range(len(body.columns))); ax.set_xticklabels(body.columns)
ax.invert_yaxis(); ax.set_ylabel("rank by Sharpe (1 = best)")
ax.legend(fontsize=8)
ax.set_title("Lines that cross are assets whose ranking depends on where you live")
plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Parallel lines would mean the currency shifts everything
> equally and an allocator can ignore it. Crossing lines mean "which fund has the better
> risk-adjusted return" genuinely has a different answer in different countries.
"""
        ),
        md(
            r"""

### 3.5 Hedging, with the carry
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    ha = st.hedge_analysis(asset, f, usd_rf, cost_bps=3.0)
    for hr, row in ha["table"].iterrows():
        rows.append({"currency": k, "hedge_ratio": round(float(hr), 2),
                     "sharpe": row["sharpe"], "vol": row["vol"], "cagr": row["cagr"]})
d = pd.DataFrame(rows)
fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
for cur, g in d.groupby("currency"):
    g = g.sort_values("hedge_ratio")
    axes[0].plot(g["hedge_ratio"], g["sharpe"], "o-", lw=1.5, ms=4, label=cur)
    axes[1].plot(g["hedge_ratio"], g["vol"] * 100, "o-", lw=1.5, ms=4, label=cur)
axes[0].set_xlabel("hedge ratio"); axes[0].set_ylabel("Sharpe"); axes[0].legend(fontsize=7)
axes[1].set_xlabel("hedge ratio"); axes[1].set_ylabel("volatility (%)")
axes[1].legend(fontsize=7)
plt.tight_layout(); plt.show()
d.round(4).to_string(index=False)
"""
        ),
        code(
            r"""
rows = []
for k, f in fx_rets.items():
    h_star = st.hedge_ratio_that_minimises_variance(asset, f)
    corr = asset.reindex(f.index).corr(f)
    rows.append({"currency": k, "corr with asset": corr, "optimal hedge ratio": h_star})
d = pd.DataFrame(rows).set_index("currency")
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(d["corr with asset"], d["optimal hedge ratio"], s=100, color="#1f6feb")
for cur, r in d.iterrows():
    ax.annotate(cur, (r["corr with asset"], r["optimal hedge ratio"]), fontsize=9,
                xytext=(6, 3), textcoords="offset points")
ax.axhline(1.0, color="k", ls="--", lw=1.5, label="a full hedge")
ax.axvline(0, color="#8b949e", lw=1)
ax.set_xlabel(f"correlation of the currency with {data.ASSET}")
ax.set_ylabel("variance-minimising hedge ratio"); ax.legend(fontsize=8)
plt.show()
d.round(3)
"""
        ),
        md(
            r"""

### 3.6 Is it the window?
"""
        ),
        code(
            r"""
rows = []
n = len(asset)
for label, sl in (("2007-2013", slice(0, n // 3)), ("2013-2019", slice(n // 3, 2 * n // 3)),
                  ("2019-", slice(2 * n // 3, n))):
    a2 = asset.iloc[sl]
    f2 = {k: v.reindex(a2.index).dropna() for k, v in fx_rets.items()}
    t2 = st.sharpe_by_currency(a2, f2, usd_rf.reindex(a2.index).fillna(0.0))
    for cur, r in t2.iterrows():
        rows.append({"period": label, "currency": cur, "sharpe": r["sharpe"]})
d = pd.DataFrame(rows)
piv = d.pivot(index="currency", columns="period", values="sharpe")
fig, ax = plt.subplots(figsize=(10, 5))
piv.plot.bar(ax=ax)
ax.set_ylabel("Sharpe"); ax.legend(fontsize=8, title="")
plt.setp(ax.get_xticklabels(), rotation=0)
plt.show()
print(piv.round(3).to_string())
print(f"\nspread within each period: "
      + ", ".join(f"{c} {piv[c].max() - piv[c].min():.2f}" for c in piv.columns))
"""
        ),
        md(
            r"""

### 3.7 Synthetic control
"""
        ),
        code(
            r"""
rows = []
for corr in (-0.4, 0.0, 0.4):
    for drift in (-0.03, 0.0, 0.03):
        for gap in (0.0, 0.03):
            w = st.synthetic_world(n=8000, corr=corr, fx_drift=drift, rate_gap=gap)
            dd = st.decompose_sharpe_gap(w["asset"], w["fx"], w["usd_rf"], w["local_rf"])
            rows.append({"corr": corr, "fx drift": drift, "rate gap": gap,
                         "gap": dd["gap"], "drift term": dd["drift_term"],
                         "variance term": dd["variance_term"], "rate term": dd["rate_term"]})
d = pd.DataFrame(rows)
print(d.round(3).to_string(index=False))
fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))
for ax, (driver, term) in zip(axes, (("fx drift", "drift term"),
                                     ("corr", "variance term"),
                                     ("rate gap", "rate term"))):
    g = d.groupby(driver)[term].mean()
    ax.plot(g.index, g.values, "o-", lw=2, color="#2ea44f")
    ax.axhline(0, color="k", lw=1)
    ax.set_xlabel(driver); ax.set_ylabel(term)
plt.tight_layout(); plt.show()
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Each panel varies one driver and plots the term it should move.
> All three slope the right way, which is the evidence that the decomposition is attributing
> correctly rather than shuffling numbers between columns.
"""
        ),
        md(
            r"""

## 4 · The verdict
"""
        ),
        code(
            r"""
tbl = st.sharpe_by_currency(asset, fx_rets, usd_rf)
rank = st.ranking_stability(assets, fx_rets, usd_rf)
gains = [st.hedge_analysis(asset, f, usd_rf, cost_bps=3.0)["sharpe_gain"]
         for f in fx_rets.values()]
ratios = [st.hedge_ratio_that_minimises_variance(asset, f) for f in fx_rets.values()]
pd.DataFrame({
    "Sharpe, US investor": [tbl.loc["USD", "sharpe"]],
    "Sharpe, best home currency": [tbl["sharpe"].max()],
    "Sharpe, worst home currency": [tbl["sharpe"].min()],
    "spread": [tbl["sharpe"].max() - tbl["sharpe"].min()],
    "median volatility increase": [
        tbl.drop("USD")["vol"].median() / tbl.loc["USD", "vol"] - 1],
    "largest ranking move (places)": [rank.loc["_rank_spread"].iloc[0]],
    "share of currencies hedging helps": [float(np.mean([g > 0 for g in gains]))],
    "median optimal hedge ratio": [float(np.median(ratios))],
}).T.rename(columns={0: "value"}).round(4)
"""
        ),
        md(
            r"""

## 5 · Going further

- **Observed rates, not implied ones.** The local risk-free rates here come from covered
  interest parity applied to ETF drift. Actual deposit rates (EURIBOR, SONIA, TONAR) would
  remove the largest approximation in the study — and CIP itself broke down after 2008 (Du,
  Tepper & Verdelhan 2018), which is exactly when the sample starts.
- **Portfolio-level hedging.** Campbell et al. (2010) solve for the hedge ratios of a whole
  portfolio jointly; doing it asset by asset, as here, ignores that currencies hedge each other.
- **Long horizons.** Froot (1993): real exchange rates mean-revert over decades, so a thirty-year
  holder faces far less currency risk than the daily volatility suggests. Measuring the variance
  ratio of the currency across horizons would quantify it.
- **Tax.** Currency gains are treated differently in all six jurisdictions and can dominate
  everything measured here.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
