"""Build the two narrative notebooks for Study 91 (Death-Cross).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both walk the seven desk beats at two altitudes. Figures are computed live from the
``death_cross`` package on the cached real tape; the frozen ``R`` dict mirrors
``docs/results.md`` for the verdict prose so the two never drift.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

# Frozen real-tape headline numbers — mirror of docs/results.md (as-of 2026-06-12).
R = dict(
    n=8400, start="1993-01-29", end="2026-06-12", fp="eb1569cc9e97",
    t_cagr=9.64, t_vol=13.7, t_sharpe=0.743, t_dd=-33.7, t_tim=75, t_sw=31,
    b_cagr=10.82, b_vol=18.6, b_sharpe=0.646, b_dd=-55.2,
    r_cagr=8.05, r_sharpe=0.564, r_dd=-51.0,
    sharpe_edge=0.097, beats=195, beats_n=200, beats_pct=98,
    hac_t=-0.99, dd_cut=21.5, cagr_gap=-1.18,
)

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))          # study root (death_cross/)
sys.path.insert(0, os.path.abspath("../../.."))    # repo root (quantlab/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.3f}")
from death_cross import data, strategy

AS_OF = "2026-06-12"
frame = data.load_real("SPY", mode="total_return").loc[:AS_OF]
close = frame["close"]
pos = strategy.crossover_position(close, 50, 200, lag=1)
timer = strategy.backtest(close, pos, cost_bps=5.0)
bh = strategy.buy_and_hold(close)
print(f"SPY total return: {len(close):,} rows  {close.index[0].date()} -> {close.index[-1].date()}  fingerprint={data.fingerprint(frame)}")
print(f"timer  Sharpe {timer['sharpe']:.3f}  maxDD {timer['max_dd']*100:.1f}%  CAGR {timer['cagr']*100:.2f}%  TiM {timer['time_in_market']*100:.0f}%")
print(f"B&H    Sharpe {bh['sharpe']:.3f}  maxDD {bh['max_dd']*100:.1f}%  CAGR {bh['cagr']*100:.2f}%")
"""


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


HERO_BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Dodges crashes?: Confirmed](https://img.shields.io/badge/Dodges_crashes%3F-Confirmed-8b949e?style=flat-square)\n\n"
)


def build_curious():
    cells = [
        md(
            "# The Death Cross ✝️\n"
            "### When the 50-day average drops below the 200-day, is it really time to sell?\n\n"
            + HERO_BADGES +
            "Every time the 50-day moving average crosses below the 200-day, financial TV calls it "
            "a *death cross* and asks whether the crash has begun. We take the rule literally — out "
            "of the market below the cross, back in above it — and ask the only two questions that "
            "matter: does it **dodge the crashes** (yes), and does it **beat just holding the "
            "index** (no).\n\n"
            "> 📓 **This is the plain-language layer.** The statistics, the matched-coin control and "
            "the capacity maths are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)** — same "
            "story, deeper.\n>\n"
            "> ⚠️ **Not investment advice.** Educational, reproducible research — every chart below "
            "is generated by the code beside it. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),
        md(
            "## The answer first 🎯\n\n"
            f"| Question | Answer |\n|---|---|\n"
            f"| Does the death cross dodge the big crashes? | **Yes** — worst drop **{R['t_dd']}%** vs "
            f"**{R['b_dd']}%** for buy-and-hold (a **{R['dd_cut']:.0f}-point** cut). |\n"
            f"| Does it beat just holding the index? | **No** — it earns **{R['t_cagr']}%/yr** vs "
            f"**{R['b_cagr']}%/yr**, about **{abs(R['cagr_gap']):.1f} points/yr less**. |\n"
            f"| So what *is* it? | A way to hold **less stock** ({R['t_tim']}% of the time invested), "
            f"i.e. less risk — not a way to make more money. |"
        ),
        md(
            "## 1 · The claim\n\n"
            "*\"When the 50-day average crosses below the 200-day — the **death cross** — get out. "
            "Re-enter on the **golden cross**. You'll sidestep the bear markets and beat buy-and-hold.\"* "
            "It's one of the most-repeated rules in market commentary."
        ),
        md(
            "## 2 · So what?\n\n"
            "If a rule this simple really beat the index, indexing would be a mistake and every "
            "investor should run it. The stakes are exactly that big — so it deserves a fair, "
            "literal test rather than a cherry-picked chart of 2008."
        ),
        md(
            "## 3 · How would we even know?\n\n"
            "We hold SPY (dividends included) while the 50-day SMA is above the 200-day, sit in cash "
            "otherwise, act **one day after** each cross (no peeking), and pay **5 bps** per switch. "
            "Then we line it up against two yardsticks: **buy-and-hold**, and a **random coin** that "
            "is out of the market for the *same total time, in similar-length stretches*, but on "
            "random dates. If the cross is just *\"be in cash sometimes\"*, it won't beat the coin."
        ),
        md("## 4 · The teardown — let's actually look\n\nFirst, the equity curves and the drawdowns."),
        code(
            "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True, height_ratios=[2, 1])\n"
            "ax1.plot(timer['equity'], label=f\"Death-cross timer (Sharpe {timer['sharpe']:.2f})\", lw=1.3)\n"
            "ax1.plot(bh['equity'], label=f\"Buy & hold (Sharpe {bh['sharpe']:.2f})\", lw=1.3, alpha=.8)\n"
            "ax1.set_yscale('log'); ax1.set_ylabel('Growth of $1 (log)'); ax1.legend(); ax1.set_title('SPY total return — timer vs buy-and-hold')\n"
            "for d, lab in [(timer, 'timer'), (bh, 'B&H')]:\n"
            "    eq = d['equity']; dd = eq/eq.cummax()-1\n"
            "    ax2.plot(dd, label=f\"{lab} (max {dd.min()*100:.0f}%)\", lw=1.1)\n"
            "ax2.set_ylabel('Drawdown'); ax2.legend(); ax2.set_xlabel('')\n"
            "plt.tight_layout(); plt.show()"
        ),
        md(
            "The timer's line is *smoother* — it ducks the 2000–02 and 2008 craters. But look at the "
            "**end point**: buy-and-hold finishes higher. You paid for the calmer ride with return."
        ),
        md("Now the **matched random coin** — is the cross better than random in/out of the same amount?"),
        code(
            "rand = []\n"
            "for s in range(200):\n"
            "    rp = strategy.matched_random_position(pos, seed=s)\n"
            "    rand.append(strategy.backtest(close, rp, cost_bps=5.0)['sharpe'])\n"
            "rand = np.array(rand)\n"
            "plt.hist(rand, bins=30, alpha=.8, label='random-timing coin (matched exposure)')\n"
            "plt.axvline(timer['sharpe'], color='C3', lw=2, label=f\"death-cross timer = {timer['sharpe']:.3f}\")\n"
            "plt.axvline(bh['sharpe'], color='C2', lw=2, ls='--', label=f\"buy & hold = {bh['sharpe']:.3f}\")\n"
            "plt.xlabel('Sharpe ratio'); plt.ylabel('count'); plt.legend()\n"
            "plt.title(f\"Timer beats {(timer['sharpe']>rand).sum()}/200 random coins on Sharpe\"); plt.show()\n"
            "print(f\"timer beats {(timer['sharpe']>rand).sum()}/200 matched random coins\")"
        ),
        md(
            f"The timer beats **{R['beats']}/{R['beats_n']}** random coins ({R['beats_pct']}%): the "
            "crossover *dates* genuinely carry information — it's not luck and it's not merely being in "
            "cash. The crash-dodging is **real**."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"- **Dodges crashes? → Confirmed.** Drawdown {R['t_dd']}% vs {R['b_dd']}%, vol "
            f"{R['t_vol']}% vs {R['b_vol']}%, and it beats a matched coin {R['beats_pct']}% of the time.\n"
            f"- **Signal → Weak.** The Sharpe edge over buy-and-hold is only **+{R['sharpe_edge']:.3f}** "
            f"and the return *difference* isn't statistically distinguishable from zero (HAC *t* = {R['hac_t']}).\n"
            f"- **Beats the market? → Mirage.** It earns **{abs(R['cagr_gap']):.1f} pts/yr less**. What "
            "you're really buying is lower exposure — less beta — not skill."
        ),
        md(
            "## 6 · Could you actually trade it?\n\n"
            "You can — it's just SPY, infinitely liquid. The problem isn't capacity, it's that the "
            "product is *less return for less risk*, which you can get more cheaply by simply holding "
            "less stock and more cash (or bonds). Add the **taxes** on 31 taxable switches and the "
            "gap widens. As *\"a rule that beats the index,\"* it's a mirage."
        ),
        md(
            "## 7 · Going further 🚪\n\n"
            "- Does earning the **T-bill** in cash (instead of 0%) close the return gap? (It helps, "
            "but it's still de-risking, not alpha.)\n"
            "- Other pairs (20/100, 100/200) — do faster crosses whipsaw more?\n"
            "- Is the drawdown cut worth more in a **leveraged** sleeve? Fork it and try."
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md(
            "# The Death Cross — a quantitative teardown 🔬\n"
            "### Real total-return tape · HAC inference · exposure-matched placebo · alpha-vs-beta\n\n"
            + HERO_BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same "
            "seven beats, every claim now carrying its standard error.* We separate the two things the "
            "death cross does — **reduce risk** (real) and **forecast return** (not certifiable) — and "
            "show the Sharpe gain is exposure, not skill.\n\n"
            "> ⚠️ **Not investment advice.** SPY daily, total-return adjusted (`quantlab.data`, Yahoo); "
            "cash earns 0% (conservative); 5 bps/switch; one-day execution lag. Sources in "
            "[`docs/references.md`](../docs/references.md), reproducible run in "
            "[`docs/results.md`](../docs/results.md).\n>\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back into intuition."
        ),
        code(BOOT),
        md(
            "## Verdict, up front\n\n"
            "| Axis | Stamp | Why |\n|---|---|---|\n"
            f"| **Signal** | `WEAK` | Sharpe edge over buy-and-hold **+{R['sharpe_edge']:.3f}**, but HAC "
            f"*t* on the daily return difference = **{R['hac_t']}** (\\|t\\| < 2). It does beat a matched "
            f"random coin {R['beats_pct']}% of the time, so the dates aren't pure noise. |\n"
            f"| **Tradability** | `MIRAGE` | Trails buy-and-hold by **{abs(R['cagr_gap']):.1f} pts/yr** "
            f"({R['t_cagr']}% vs {R['b_cagr']}%); the Sharpe gain is lower beta, obtainable more cheaply. |\n"
            f"| **Dodges crashes?** | `CONFIRMED` | maxDD **{R['t_dd']}%** vs **{R['b_dd']}%**, vol "
            f"**{R['t_vol']}%** vs **{R['b_vol']}%**. |\n\n"
            "> 💡 **In plain words:** the death cross is a *risk reducer that works* wearing the costume "
            "of a *return booster that doesn't*."
        ),
        md(
            "## 1 · The claim, steelmanned\n\n"
            "- **H₁ (risk):** the 50/200 filter lowers drawdown and volatility vs buy-and-hold.\n"
            "- **H₂ (skill):** the crossover *dates* beat an exposure-matched random schedule.\n"
            "- **H₃ (the sold claim):** the timer beats buy-and-hold on *return* / risk-adjusted return.\n\n"
            "H₁ and H₂ can be true while H₃ is false — that is exactly the split we find."
        ),
        md("## 2 · So what? — what rides on each answer\n\nIf H₃ held, cap-weighted indexing would be "
           "dominated by a two-line rule. It doesn't — and seeing *why* (beta, not alpha) is the lesson."),
        md("## 3 · How we'd know — the protocol\n\nDecompose exposure vs timing · HAC inference on the "
           "return difference · exposure-matched placebo · alpha-vs-beta read on the Sharpe gap."),
        md("## 4 · The teardown\n\nHeadline stats, all net of 5 bps/switch:"),
        code(
            "tbl = pd.DataFrame({\n"
            "  'CAGR %':   [timer['cagr']*100, bh['cagr']*100],\n"
            "  'Vol %':    [timer['vol']*100, bh['vol']*100],\n"
            "  'Sharpe':   [timer['sharpe'], bh['sharpe']],\n"
            "  'MaxDD %':  [timer['max_dd']*100, bh['max_dd']*100],\n"
            "  'TiM %':    [timer['time_in_market']*100, bh['time_in_market']*100],\n"
            "}, index=['Death-cross timer', 'Buy & hold'])\n"
            "tbl.round(2)"
        ),
        md("**HAC inference** on the daily return difference (timer − buy-and-hold) — is the edge real?"),
        code(
            "diff = (timer['net'] - bh['net']).to_numpy()\n"
            "t = strategy.hac_tstat(diff)\n"
            "print(f'mean daily diff = {diff.mean()*1e4:+.3f} bps/day   HAC t = {t:+.2f}')\n"
            "print('=> cannot reject zero: the return difference is not statistically distinguishable from 0.')"
        ),
        md(
            "> 💡 **In plain words:** day to day, the timer and buy-and-hold are statistically the same "
            "bet; the timer just turns itself off during long declines."
        ),
        md("**Exposure-matched placebo** — the same time in cash, random dates (200 seeds):"),
        code(
            "rand_s = np.array([strategy.backtest(close, strategy.matched_random_position(pos, seed=s), cost_bps=5.0)['sharpe'] for s in range(200)])\n"
            "rand_dd = np.array([strategy.backtest(close, strategy.matched_random_position(pos, seed=s), cost_bps=5.0)['max_dd'] for s in range(200)])\n"
            "print(f\"timer Sharpe {timer['sharpe']:.3f} beats {(timer['sharpe']>rand_s).sum()}/200 coins (mean coin {rand_s.mean():.3f})\")\n"
            "print(f\"timer maxDD  {timer['max_dd']*100:.1f}% vs mean coin {rand_dd.mean()*100:.1f}%\")\n"
            "fig, ax = plt.subplots(figsize=(10,4))\n"
            "ax.hist(rand_s, bins=30, alpha=.8, label='matched random coin')\n"
            "ax.axvline(timer['sharpe'], color='C3', lw=2, label='death-cross timer')\n"
            "ax.axvline(bh['sharpe'], color='C2', ls='--', lw=2, label='buy & hold')\n"
            "ax.set_xlabel('Sharpe'); ax.legend(); plt.show()"
        ),
        md(
            "> 💡 **In plain words:** the cross beats random in/out — so the *timing* adds something. "
            "But what it adds is risk reduction, and it still can't out-*earn* simply staying invested."
        ),
        md(
            "## 5 · The verdict\n\n"
            f"Signal `WEAK` (Sharpe +{R['sharpe_edge']:.3f}, HAC *t* {R['hac_t']}; beats coin "
            f"{R['beats_pct']}%), Tradability `MIRAGE` (−{abs(R['cagr_gap']):.1f} pts/yr), Dodges "
            f"crashes? `CONFIRMED` ({R['t_dd']}% vs {R['b_dd']}%). The Sharpe gain is exposure, not alpha."
        ),
        md(
            "## 6 · Could you trade it?\n\n"
            "Capacity is a non-issue (SPY). The binding fact is economic, not frictional: the strategy "
            "delivers **less return for less risk** — a lower-beta portfolio — which a 75/25 stock/cash "
            "blend reproduces without 31 taxable switches. Net of tax the gap to buy-and-hold widens."
        ),
        md(
            "## 7 · Going further\n\n"
            "- Replace 0% cash with the **T-bill** (`^IRX`) and recompute excess-of-cash for both arms.\n"
            "- Bootstrap the Sharpe **difference** (stationary bootstrap) for a CI on +0.097.\n"
            "- Cross-asset: does the filter earn its keep on assets with fatter left tails (EM, credit)?"
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
