"""Build the two narrative notebooks for Study 58 (Bunker).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/bunker_pairs.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (bunker/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from bunker import data, strategy as st
ret = data.fetch_pairs()                       # cache-first
al = ret[["USMV","SPY"]].dropna()              # common window (USMV starts 2011)
sp = st.spread(ret, "USMV", "SPY")
"""

VERDICT = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Delivers the low-vol Sharpe edge?: Not supported](https://img.shields.io/badge/Delivers_the_low--vol_Sharpe_edge%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Bunker 🛡️\n### The minimum-volatility ETF — a calmer ride, but a better one?\n\n"
           + VERDICT +
           "The low-volatility anomaly says boring, stable stocks earn *better risk-adjusted* returns. "
           "The product that sells it is the min-vol ETF. It does deliver the calm — 20% less volatility, "
           "a shallower drawdown — but over 2011–2026 it didn't beat the market on Sharpe. A good bunker, "
           "not a free lunch.\n\n"
           "> 📓 **Plain-language layer.** The numbers and the regime caveat are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The promise | The data (2011–2026) |\n|---|---|\n"
           "| \"Lower risk\" | True: vol **11.4% vs 14.3%**, drawdown **−20% vs −24%**. |\n"
           "| \"Better risk-adjusted returns\" | No: Sharpe **0.99 vs 1.05**. |\n"
           "| \"A free Sharpe edge\" | It trailed on return (−3.5%/yr spread). |"),
        md("## 1 · The claim\n\nThe low-vol anomaly (Baker-Bradley-Wurgler 2011; the desk's "
           "[Study 18 Dull-Roar](../../18-dull-roar/)): calm stocks earn higher *risk-adjusted* returns. "
           "USMV is the min-vol ETF that packages it for investors."),
        md("## 2 · So what?\n\nMin-vol products gather tens of billions on the promise of equity returns "
           "with bond-like calm. If they only cut risk *proportionally* — same Sharpe — that's a fine "
           "defensive tool but not the anomaly's free lunch. Worth checking which it is."),
        md("## 3 · How would we even know?\n\nCompare USMV to SPY over USMV's life, leg by leg: does it "
           "cut volatility and drawdown (risk), *and* does it beat the market on Sharpe (the anomaly)?"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'USMV (min-vol)':st.leg_summary(al,'USMV'),'SPY (market)':st.leg_summary(al,'SPY')}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "print('vol reduction USMV/SPY =', round(st.vol_reduction(al,'USMV','SPY'),2))"),
        md("## 4 · The teardown\n\nUSMV is genuinely calmer — lower vol, shallower drawdown. But the lower "
           "risk came with lower return, so the Sharpe landed just below the market's."),
        code("eqU=(1+al['USMV']).cumprod(); eqS=(1+al['SPY']).cumprod()\n"
             "ax=eqS.plot(label='SPY (market)',lw=1.6); eqU.plot(ax=ax,label='USMV (min-vol)',lw=1.6)\n"
             "ax.set_yscale('log'); ax.set_title('Growth of $1, 2011-2026'); ax.legend(); plt.show()\n"
             "s=st.spread_stats(sp); print(f\"spread USMV-SPY: {s['mean_ann']:+.2%}/yr, Sharpe {s['sharpe']:.2f}\")"),
        md("**Read it plainly.** A smoother but lower line. Min-vol bought you calm, not extra "
           "risk-adjusted return — at least in this bull-heavy stretch. Its edge lives in the bear markets "
           "this sample mostly lacked."),
        md("## 5 · The verdict\n\n**Signal: Weak** — cuts risk, not a Sharpe edge. **Tradability: Fragile** "
           "— a defensive tool, trailed the market. **Delivers the low-vol Sharpe edge?: Not supported** here."),
        md("## 6 · Could you actually trade it?\n\nYes — and as a *defensive* holding it does its job "
           "(less volatility, smaller drawdowns). Just don't expect it to beat the market; the anomaly's "
           "risk-adjusted edge shows up over full cycles and in bear markets, not a 2011–2026 bull run."),
        md("## 7 · Going further 🚪\n\nCompare with the academic long-short in "
           "[Study 18 Dull-Roar](../../18-dull-roar/), and the high-risk-won mirror in "
           "[43 Free-Lunch](../../43-free-lunch/) / [53 Jackpot](../../53-jackpot/)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Bunker — a quantitative teardown 🔬\n### Leg comparison · the vol-reduction ratio · the spread · the bull-regime caveat\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). USMV cuts risk "
           "but didn't beat the market risk-adjusted over 2011–2026.\n\n"
           "> ⚠️ **Not investment advice.** USMV vs SPY, monthly total return (Yahoo), 2011–2026. Sources "
           "in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Weak** | vol 0.80×, DD −20% vs −24%; Sharpe 0.99 < 1.05 |\n"
           "| Tradability | **Fragile** | trailed return (−3.5%/yr); defensive only |\n"
           "| Sharpe edge? | **Not supported** | absent in a bull sample |\n\n"
           "> 💡 *In plain words:* it delivers calm, not a free Sharpe."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** USMV cuts volatility/drawdown vs the market.\n"
           "- **H₂:** USMV beats the market on Sharpe.\n- **H₃:** USMV beats it on return."),
        md("## 2 · So what? — what rides on each\n\nH₁ is the defensive case; H₂ is the anomaly's promise. "
           "If only H₁ holds, USMV is risk management, not alpha."),
        md("## 3 · How we'd know — the protocol\n\nLeg CAGR/Sharpe/vol/drawdown over the common window → "
           "vol-reduction ratio → the spread and its t-stat."),
        md("## 4 · The teardown"),
        md("### 4.1 The two legs"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'USMV':st.leg_summary(al,'USMV'),'SPY':st.leg_summary(al,'SPY')}).T[['cagr','sharpe','vol_ann','max_drawdown']].round(3))\n"
             "print('vol reduction:', round(st.vol_reduction(al,'USMV','SPY'),2))"),
        md("> 💡 *In plain words:* **H₁ holds** (0.80× vol, shallower DD) but **H₂ and H₃ rejected** (Sharpe 0.99 < 1.05, less return)."),
        md("### 4.2 The spread"),
        code("print({k:round(v,3) for k,v in st.spread_stats(sp).items()})"),
        md("> 💡 *In plain words:* −3.5%/yr — USMV trailed; the low-vol Sharpe edge is absent here."),
        md("### 4.3 The regime caveat"),
        md("2011–2026 was largely a strong-market, high-beta regime. The low-vol anomaly historically "
           "earns its keep in **bear markets and over full cycles** (it loses less when stocks fall). A "
           "sample without a sustained bear under-states it — the same regime that made high-beta *win* in "
           "[43 Free-Lunch](../../43-free-lunch/) and [53 Jackpot](../../53-jackpot/). Stated, not hidden."),
        md("## 5 · The verdict\n\nH₁ holds, H₂/H₃ rejected → Signal `WEAK`, Tradability `FRAGILE`, the "
           "Sharpe edge `NOT SUPPORTED` (this sample)."),
        md("## 6 · Could you trade it?\n\nAs a defensive sleeve, yes — lower volatility and drawdown are "
           "real and useful. As a market-beater, no, at least not in a bull-dominated window."),
        md("## 7 · Going further\n\nForks: (a) a sample spanning a full cycle / a sustained bear (2000–02); "
           "(b) min-vol vs a simple low-beta tilt; (c) blend min-vol with momentum (the classic "
           "defensive-plus-trend pair). Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
