"""Build the two narrative notebooks for Study 63 (Free-Fall).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/free_fall_pair.parquet)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (free_fall/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from free_fall import data, strategy as st
ret = data.fetch_pair()                        # cache-first
c = st.carry_vs_crash(ret["SVXY"])
"""

VERDICT = (
    "![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)\n"
    "![Tradability: Fragile](https://img.shields.io/badge/Tradability-Fragile-dab617?style=flat-square)\n"
    "![Naive short-vol survives?: Busted](https://img.shields.io/badge/Naive_short--vol_survives%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Free-Fall 🪂\n### Selling volatility: pennies in front of a steamroller\n\n"
           + VERDICT +
           "Shorting volatility earns a steady premium — implied vol usually exceeds what actually "
           "happens, so the seller gets paid. SVXY compounded +12%/yr doing it. The catch is the tail: a "
           "single −83% day in February 2018 ('Volmageddon') wiped out years of carry and liquidated the "
           "1× inverse-VIX funds entirely.\n\n"
           "> 📓 **Plain-language layer.** The carry-vs-crash maths and the skew are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The carry | The catch |\n|---|---|\n"
           "| \"Sell vol, collect premium\" | Real: SVXY **+11.8%/yr** (+10% post-2018). |\n"
           "| \"Steady income\" | Skew **−4.8**, a **−95% drawdown**. |\n"
           "| \"Just hold it\" | **−83% in one day**; the 1× funds were *liquidated*. |"),
        md("## 1 · The claim\n\nThe volatility risk premium: option-implied volatility tends to exceed "
           "realised, so selling volatility (short VIX futures, SVXY) earns a carry — one of the most "
           "documented real premia in markets."),
        md("## 2 · So what?\n\nShort-vol products and strategies manage billions on that real carry. But "
           "the premium is compensation for a catastrophic left tail — and whether you can *hold* it "
           "depends entirely on surviving the tail, which the 2018 blow-up showed most couldn't."),
        md("## 3 · How would we even know?\n\nCompare SVXY to SPY on return *and* the tail (skew, worst "
           "day, drawdown), and decompose: how much do you collect on a normal day versus how much the few "
           "crash days take?"),
        code("rows={'SVXY (short-vol)':st.summary(ret['SVXY']),'SPY (market)':st.summary(ret['SPY'])}\n"
             "display(pd.DataFrame(rows).T[['cagr','sharpe','vol_ann','max_drawdown','skew','worst_day']].round(3))\n"
             "eqV=(1+ret['SVXY']).cumprod()\n"
             "ax=eqV.plot(title='Growth of $1 in SVXY (short-vol) — the Volmageddon cliff',lw=1.5)\n"
             "ax.set_yscale('log'); ax.set_ylabel('growth of $1 (log)'); plt.show()"),
        md("## 4 · The teardown — the steamroller\n\nA little every day; then a handful of days take "
           "almost everything."),
        code("wd,wdt=st.worst_day(ret['SVXY'])\n"
             "print(f\"median day: {c['median_day_bp']:+.0f} bp (the carry)\")\n"
             "print(f\"worst day:  {wd:+.0%} on {wdt.date()} (Volmageddon)\")\n"
             "print(f\"{c['n_crash_days']} crash days (<-20%) wiped {c['crash_days_total']:+.0%} between them\")\n"
             "post=ret.loc['2018-05-01':]; s=st.summary(post['SVXY'])\n"
             "print(f\"post-Volmageddon (de-levered): CAGR {s['cagr']:+.1%}, Sharpe {s['sharpe']:.2f} — the carry resumes\")"),
        md("**Read it plainly.** You collect ~40 bp on a quiet day and hand back 95% across five bad ones. "
           "The carry is real; the tail is total. That's the steamroller."),
        md("## 5 · The verdict\n\n**Signal: Real** — the vol premium pays. **Tradability: Fragile** — "
           "skew −4.8, −95% drawdown. **Naive short-vol survives?: Busted** (the 1× funds were liquidated)."),
        md("## 6 · Could you actually trade it?\n\nOnly *sized small and tail-hedged* — never bought and "
           "held. The premium is genuine, but it compensates a catastrophe; harvest it like insurance "
           "underwriting (small line, capped loss), not like a yield product. See [27 Steamroller](../../27-steamroller/)."),
        md("## 7 · Going further 🚪\n\nThe carry-with-a-tail sibling of [27 Steamroller](../../27-steamroller/) "
           "(FX) and [59 Downhill](../../59-downhill/) (duration); the *honest* version of the income story "
           "[62 Premium-Seller](../../62-premium-seller/) sells badly."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Free-Fall — a quantitative teardown 🔬\n### The carry-vs-crash decomposition · the −4.8 skew · the −83% day · the post-2018 resumption\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). A real carry "
           "with a ruinous tail.\n\n"
           "> ⚠️ **Not investment advice.** SVXY vs SPY, daily total return (Yahoo), 2018–2026. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **Real** | SVXY +11.8%/yr; post-2018 +10%/yr |\n"
           "| Tradability | **Fragile** | skew −4.8, −95% DD, −83% day |\n"
           "| Naive hold survives? | **Busted** | 1× inverse-VIX ETPs liquidated 2018 |\n\n"
           "> 💡 *In plain words:* real pennies, real steamroller."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** short-vol earns a positive carry (the variance risk "
           "premium).\n- **H₂:** the left tail is survivable for a buy-and-hold.\n- **H₃:** the premium "
           "persists after the crash."),
        md("## 2 · So what? — what rides on each\n\nH₁ is the premium; H₂ decides whether you can hold it; "
           "H₃ whether it's still there. A real premium you can't hold is a trap."),
        md("## 3 · How we'd know — the protocol\n\nReturn/Sharpe/skew/drawdown vs SPY → worst day → "
           "carry-vs-crash decomposition → post-Volmageddon sub-period."),
        md("## 4 · The teardown"),
        md("### 4.1 The carry and the tail"),
        code("import pandas as pd\n"
             "display(pd.DataFrame({'SVXY':st.summary(ret['SVXY']),'SPY':st.summary(ret['SPY'])}).T[['cagr','sharpe','vol_ann','max_drawdown','skew','worst_day']].round(3))"),
        md("> 💡 *In plain words:* +11.8%/yr (**H₁ holds**) but skew −4.8 and −95% drawdown (**H₂ rejected**)."),
        md("### 4.2 Carry vs crash"),
        code("print({k:(round(v,4) if isinstance(v,float) else v) for k,v in c.items()})\n"
             "wd,wdt=st.worst_day(ret['SVXY']); print(f'worst day {wd:+.0%} on {wdt.date()}')"),
        md("> 💡 *In plain words:* +40 bp on a normal day; five crash days take −95%. The premium is rent "
           "on a catastrophe."),
        md("### 4.3 The premium persists"),
        code("post=ret.loc['2018-05-01':]; s=st.summary(post['SVXY'])\n"
             "print(f\"post-Volmageddon (de-levered -0.5x): CAGR {s['cagr']:+.1%}, Sharpe {s['sharpe']:.2f}, maxDD {s['max_drawdown']:.0%}\")"),
        md("> 💡 *In plain words:* +10%/yr resumes — **H₃ holds**. The premium didn't die; the 2018 "
           "holders did. The tail is the whole story."),
        md("## 5 · The verdict\n\nH₁/H₃ hold, H₂ rejected → Signal `REAL`, Tradability `FRAGILE`, naive "
           "hold `BUSTED`."),
        md("## 6 · Could you trade it?\n\nSized small with an explicit tail hedge (long deep OTM puts / "
           "VIX calls), like insurance underwriting — never as a buy-and-hold yield product. The premium "
           "is the wage; the −83% day is the job."),
        md("## 7 · Going further\n\nForks: (a) a vol-targeted / tail-hedged short-vol overlay (does "
           "managing the tail rescue the Sharpe?); (b) the variance-swap carry vs the ETF; (c) short-vol "
           "blended into a 60/40 as a small sleeve. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
