"""Notebook builder for Study 969 — Log or Simple.

The two narrative notebooks are a *generated artefact*: edit the cell text here, then

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Both notebooks walk the same seven desk beats (METHODOLOGY.md) at two altitudes:
01 is the plain-language layer, 02 carries the inference, the confounds and the costs.
The verdict badges in the heroes are the ones the real run earned — they are pasted
here from `docs/results.md`, never chosen by hand.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""


def md(text):
    return new_markdown_cell(text.strip("\n").rstrip())


def code(text):
    return new_code_cell(text.strip("\n").rstrip())


# ===========================================================================
# 01 — FOR THE CURIOUS
# ===========================================================================
def build_curious():
    cells = [

        md(
            r"""
# Log or Simple \U0001F4D0
### Two definitions of "the return". Both correct. Not interchangeable.

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

One adds up across time. The other adds up across assets. No definition does both, every
codebase mixes them somewhere, and the mistake is invisible on a bond fund and enormous on
bitcoin. This notebook measures the damage.

> \U0001F4D3 **This is the plain-language layer.** The expansion, the Jensen argument and the
> terminal-wealth accounting are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.
>
> ⚠️ **Not investment advice.** Every chart below is generated by the code beside it.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        md(
            r"""

## The answer first \U0001F3AF

| Question | Answer |
|---|---|
| Are the two returns different? | By about **half the variance** per period — nothing on bills, a fortune on bitcoin. |
| Does it change a headline number? | Yes: the "average annual return" of a volatile asset can be strongly positive while its holders lost money. |
| Where is the actual bug? | Building a **portfolio** by weighting *log* returns. It always understates, never warns you, and compounds. |
| What is the rule? | Logs across time. Simple across assets. Say which one you are quoting. |
"""
        ),
        md(
            r"""

## 1 · The claim

> *"Just use log returns — they're additive, they're symmetric, and everyone in academia uses
> them."*

Half right. Log returns are additive **across time**. They are not additive across *assets*,
and a portfolio is an average across assets.
"""
        ),
        md(
            r"""

## 2 · So what?

Because the difference is second-order in the return, it hides in exactly the places where
returns are large — leveraged funds, emerging markets, crypto — which are also the places
where people most want a headline number to quote.
"""
        ),
        code(
            r"""
from log_vs_simple import data, strategy as st

px = data.load_prices()
print(f"as-of {data.AS_OF}")
for tk in data.TICKERS:
    s = px[tk].dropna()
    v = s.pct_change().std() * np.sqrt(252)
    print(f"  {tk:8s} {s.index[0].date()} -> {s.index[-1].date()}  "
          f"n={len(s):6,}  annualised vol {v:6.1%}")
"""
        ),
        md(
            r"""

## 3 · How would we even know?

There is nothing to estimate. `ln(1+R) ≤ R` always, with the gap growing like `R²/2`. The only
question is how big that gap is on real tapes, so we measure it.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 The gap, tape by tape
"""
        ),
        code(
            r"""
dt = st.drag_table(px).sort_values("vol_ann")
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(dt))
ax.bar(x - 0.2, dt["mean_simple_ann"] * 100, width=0.4, color="#2ea44f", label="mean simple return")
ax.bar(x + 0.2, dt["mean_log_ann"] * 100, width=0.4, color="#c0392b", label="mean log return")
ax.set_xticks(x); ax.set_xticklabels(dt.index, rotation=20, ha="right")
ax.set_ylabel("annualised (%)"); ax.axhline(0, color="k", lw=0.8)
ax.set_title("The same tapes, two averages")
ax.legend()
plt.show()
dt[["vol_ann", "mean_simple_ann", "mean_log_ann", "gap_ann", "half_var_ann", "cagr"]].round(4)
"""
        ),
        md(
            r"""

> \U0001F52C **For the quants.** The `half_var_ann` column is the σ²/2 prediction. It tracks
> the gap closely at low volatility and starts to under-explain it once skewness and kurtosis
> matter, which is the third and fourth term of the expansion showing up.
"""
        ),
        md(
            r"""

### 4.2 Why "average annual return" is a trick question
"""
        ),
        code(
            r"""
wild = dt["gap_ann"].idxmax()
R = px[wild].dropna().pct_change().dropna()
t = st.annualisation_table(R)
print(f"{wild}: four ways to state one 'average annual return'\n")
print(t.round(4).to_string())
print(f"\nAnd the number an actual holder experienced (CAGR): "
      f"{dt.loc[wild, 'cagr']:+.2%}/yr")
"""
        ),
        md(
            r"""

### 4.3 The volatility that eats everything
"""
        ),
        code(
            r"""
curve = st.drag_curve(vols=np.linspace(0, 1.2, 61), mu_ann=0.08)
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(curve.index * 100, curve["arithmetic"] * 100, lw=2, color="#2ea44f",
        label="arithmetic mean (8%/yr)")
ax.plot(curve.index * 100, curve["geometric_approx"] * 100, lw=2, color="#c0392b",
        label="geometric mean = arithmetic - sigma^2/2")
ax.axhline(0, color="k", lw=1)
be = np.sqrt(2 * 0.08) * 100
ax.axvline(be, color="#8b949e", ls=":", lw=1.5)
ax.annotate(f"all of it gone at {be:.0f}% vol", (be, 4), xytext=(be + 5, 5), fontsize=9,
            arrowprops=dict(arrowstyle="->", lw=0.8))
for tk, row in dt.iterrows():
    ax.plot(row["vol_ann"] * 100, 8 - (row["vol_ann"] ** 2 / 2) * 100, "o", color="k", ms=4)
    ax.annotate(tk, (row["vol_ann"] * 100, 8 - (row["vol_ann"] ** 2 / 2) * 100),
                fontsize=7, xytext=(3, 3), textcoords="offset points")
ax.set_xlabel("annualised volatility (%)"); ax.set_ylabel("annualised return (%)")
ax.set_title("An 8%/yr arithmetic return, as the volatility around it grows")
ax.legend()
plt.show()
"""
        ),
        md(
            r"""

### 4.4 The bug worth grepping for
"""
        ),
        code(
            r"""
universe = tuple(tk for tk in data.TICKERS if tk != "BIL")
err = st.portfolio_error(px, universe)
sub = px[list(universe)].dropna()
R = sub.pct_change().dropna()
L = np.log(sub / sub.shift(1)).dropna()
w = np.full(len(universe), 1 / len(universe))
right = (1 + st.portfolio_simple(R, w)).cumprod()
wrong = (1 + np.expm1(st.portfolio_from_logs(L, w))).cumprod()
fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(right.index, right, lw=1.6, color="#2ea44f", label="weights x simple returns (correct)")
ax.plot(wrong.index, wrong, lw=1.6, color="#c0392b", label="weights x log returns (the bug)")
ax.set_yscale("log"); ax.set_ylabel("growth of $1 (log scale)")
ax.set_title(f"Equal-weight book of {len(universe)} tapes: {err['terminal_ratio']:.2f}x apart")
ax.legend()
plt.show()
print(f"correct CAGR {err['cagr_correct']:+.2%} | wrong CAGR {err['cagr_wrong']:+.2%} | "
      f"gap {err['cagr_gap']:+.2%}/yr over {err['years']:.1f} years")
"""
        ),
        md(
            r"""

## 5 · The verdict

**Signal: Real.** It scales with the square of volatility, so it is invisible at one end of the tape and enormous at the other. On **BIL** (0% annualised vol) the mean simple and mean log returns differ by **0.00%/yr**; on **TQQQ** (61% vol) they differ by **18.9%/yr**, and the sigma-squared-over-two prediction accounts for 99% of it. The Sharpe ratio moves too: up to **0.31** between the two conventions.

**Usefulness: Useful.** Yes, and it is two lines. **Across time, use logs** (they add, and their mean exponentiates to the CAGR the path delivered). **Across assets, use simple returns** (a portfolio's return is a weighted average of them, exactly). The failure mode is weighting log returns: on an equal-weight book of 7 tapes it understated the CAGR by **6.11%/yr** — 1.80x of terminal wealth over 12 years — and it understated on **essentially every day**, because Jensen's inequality only points one way.
"""
        ),
        md(
            r"""

## 6 · What to do about it

Three lines, and they settle every case:

1. Compounding a single asset through time → **log returns**.
2. Combining assets into a portfolio → **simple returns**.
3. Publishing "the average return" → say **arithmetic** or **geometric**, and if you only have
   room for one, publish the geometric, because that is the one your investor experienced.
"""
        ),
        md(
            r"""

## 7 · Going further \U0001F6AA

- **Continuous rebalancing** turns the portfolio gap into Fernholz's excess growth rate — the
  same number, derived from stochastic portfolio theory rather than from Jensen.
- **Leveraged funds** (studies 942-944) are this effect industrialised: 3× daily exposure
  multiplies the variance by nine and the drag with it.
- **Currency conversion** stacks another log/simple decision on top; a EUR investor in a USD
  fund has two conventions to get right, not one.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


# ===========================================================================
# 02 — FOR THE QUANTS
# ===========================================================================
def build_quants():
    cells = [

        md(
            r"""
# Log or Simple — a quantitative teardown \U0001F52C
### Jensen · the σ²/2 expansion and its residual · terminal-wealth cost · Sharpe vs beta sensitivity

![Signal: Real](https://img.shields.io/badge/Signal-Real-2ea44f?style=flat-square)
![Usefulness: Useful](https://img.shields.io/badge/Usefulness-Useful-2ea44f?style=flat-square)

The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). Unusually for
this desk there is nothing to *test* here — the results are identities — so the study is about
**magnitudes** and about the one place the identity becomes a bug that ships.

> ⚠️ **Not investment advice.** Total-return closes from Yahoo! Finance, pinned as-of the date
> in [`docs/results.md`](../docs/results.md).
>
> \U0001F4A1 **The `\U0001F4A1 In plain words` notes** translate each result back into intuition.
"""
        ),
        code(
            r"""
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))   # repo root (quantlab/ lives there)
sys.path.insert(0, os.path.abspath(".."))          # the study package
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.25
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
"""
        ),
        code(
            r"""
from log_vs_simple import data, strategy as st

px = data.load_prices()
print(f"as-of {data.AS_OF}")
for tk in data.TICKERS:
    s = px[tk].dropna()
    v = s.pct_change().std() * np.sqrt(252)
    print(f"  {tk:8s} {s.index[0].date()} -> {s.index[-1].date()}  "
          f"n={len(s):6,}  annualised vol {v:6.1%}")
"""
        ),
        md(
            r"""

## Verdict, up front

| Axis | Stamp | Why |
|---|---|---|
| **Signal** | Real | It scales with the square of volatility, so it is invisible at one end of the tape and enormous at the other. On **BIL** (0% annualised vol) the mean simple and mean log returns differ by **0.00%/yr**; on **TQQQ** (61% vol) they differ by **18.9%/yr**, and the sigma-squared-over-two prediction accounts for 99% of it. The Sharpe ratio moves too: up to **0.31** between the two conventions. |
| **Usefulness** | Useful | Yes, and it is two lines. **Across time, use logs** (they add, and their mean exponentiates to the CAGR the path delivered). **Across assets, use simple returns** (a portfolio's return is a weighted average of them, exactly). The failure mode is weighting log returns: on an equal-weight book of 7 tapes it understated the CAGR by **6.11%/yr** — 1.80x of terminal wealth over 12 years — and it understated on **essentially every day**, because Jensen's inequality only points one way. |

> \U0001F4A1 **In plain words.** Two conventions, one rule each, and one bug that silently
> costs you the rebalancing bonus.
"""
        ),
        md(
            r"""

## 1 · The claim, stated as identities

- **I₁.** `sum_t r_t = ln(P_T/P_0)` exactly. Log returns aggregate across time.
- **I₂.** `R_p = sum_i w_i R_i` exactly. Simple returns aggregate across assets.
- **I₃.** `E[ln(1+R)] = E[R] - Var(R)/2 + E[R³]/3 - ...` — the drag, with the terms nobody
  quotes made explicit.
- **I₄.** `ln(sum_i w_i (1+R_i)) ≥ sum_i w_i ln(1+R_i)` (Jensen). The portfolio mistake is a
  one-sided error, with equality only when all assets move identically.
"""
        ),
        md(
            r"""

## 2 · So what? — the quantitative stakes

I₄ is the interesting one, because it is a *bug pattern*: it produces a plausible-looking
number that is always too low, on every day, forever, and nothing in a test suite catches it
unless someone thought to compare against the compounded simple path.
"""
        ),
        md(
            r"""

## 3 · How we'd know — the protocol

Nothing to estimate; everything to measure. The tapes span 0.3% to 65% annualised volatility on
purpose, because the effect is quadratic in exactly that number. The σ²/2 approximation is
scored against the *realised* gap so its own error is visible rather than assumed away.
"""
        ),
        md(
            r"""

## 4 · The teardown

### 4.1 The expansion, and what it misses
"""
        ),
        code(
            r"""
dt = st.drag_table(px).sort_values("vol_ann")
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].scatter(dt["vol_ann"] ** 2 * 100, dt["gap_ann"] * 100, s=60, color="#2ea44f")
lim = np.linspace(0, (dt["vol_ann"] ** 2).max() * 100, 20)
axes[0].plot(lim, lim / 2, color="k", ls="--", lw=1, label="the sigma^2/2 prediction")
for tk, r in dt.iterrows():
    axes[0].annotate(tk, (r["vol_ann"] ** 2 * 100, r["gap_ann"] * 100), fontsize=7,
                     xytext=(4, 2), textcoords="offset points")
axes[0].set_xlabel("annualised variance (%)"); axes[0].set_ylabel("observed gap (%/yr)")
axes[0].legend(); axes[0].set_title("Gap versus variance")
axes[1].scatter(dt["excess_kurtosis"], dt["residual_ann"] * 100, s=60, color="#c0392b")
for tk, r in dt.iterrows():
    axes[1].annotate(tk, (r["excess_kurtosis"], r["residual_ann"] * 100), fontsize=7,
                     xytext=(4, 2), textcoords="offset points")
axes[1].axhline(0, color="k", lw=1)
axes[1].set_xlabel("excess kurtosis"); axes[1].set_ylabel("residual after sigma^2/2 (%/yr)")
axes[1].set_title("What the second-order term does not explain")
plt.show()
dt[["vol_ann", "gap_ann", "half_var_ann", "residual_ann", "skew", "excess_kurtosis"]].round(4)
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** The textbook formula is a two-term Taylor expansion. On a
> tape with fat tails, the terms it drops are not negligible — the residual column is the size
> of the mistake made by people who quote σ²/2 as if it were exact.
"""
        ),
        md(
            r"""

### 4.2 Jensen, measured
"""
        ),
        code(
            r"""
universe = tuple(tk for tk in data.TICKERS if tk != "BIL")
sub = px[list(universe)].dropna()
R = sub.pct_change().dropna()
L = np.log(sub / sub.shift(1)).dropna()
w = np.full(len(universe), 1 / len(universe))
diff = (st.portfolio_simple(R, w) - np.expm1(st.portfolio_from_logs(L, w))) * 1e4
print(f"daily gap (bps): mean {diff.mean():+.2f}, median {diff.median():+.2f}, "
      f"min {diff.min():+.2f}, max {diff.max():+.2f}")
print(f"share of days where the log-weighted version is lower: {(diff >= -1e-9).mean():.4%}")
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.hist(diff, bins=100, color="#c0392b", alpha=0.85)
ax.axvline(0, color="k", lw=1)
ax.set_xlabel("correct minus log-weighted, daily (bps)"); ax.set_ylabel("sessions")
ax.set_title("A one-sided error: the histogram never crosses zero")
plt.show()
"""
        ),
        md(
            r"""

### 4.3 The error IS the rebalancing bonus
"""
        ),
        code(
            r"""
err = st.portfolio_error(px, universe)
bonus = st.rebalancing_bonus(px, universe)
print(f"log-weighting error : {err['cagr_gap']:+.3%}/yr")
print(f"rebalancing bonus   : {bonus['bonus']:+.3%}/yr")
print(f"  rebalanced CAGR {bonus['rebalanced_cagr']:+.2%} vs average buy-and-hold "
      f"{bonus['buy_hold_avg_cagr']:+.2%}")
print()
print(pd.Series(bonus["per_asset_cagr"], name="buy-and-hold CAGR by asset").round(4).to_string())
"""
        ),
        md(
            r"""

### 4.4 How the error scales with the dispersion of the book
"""
        ),
        code(
            r"""
rows = []
for tk in ("TLT", "GLD", "QQQ", "TQQQ", "BTC-USD"):
    e = st.portfolio_error(px, ("SPY", tk))
    pair = px[["SPY", tk]].dropna().pct_change().dropna()
    rows.append({"pair": f"SPY+{tk}", "cagr_gap": e["cagr_gap"],
                 "avg vol": pair.std().mean() * np.sqrt(252),
                 "correlation": pair.corr().iloc[0, 1], "years": e["years"]})
d = pd.DataFrame(rows).set_index("pair")
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.scatter(d["avg vol"] * 100, d["cagr_gap"] * 100, s=80, color="#2ea44f")
for name, r in d.iterrows():
    ax.annotate(name, (r["avg vol"] * 100, r["cagr_gap"] * 100), fontsize=8,
                xytext=(4, 3), textcoords="offset points")
ax.set_xlabel("average annualised volatility of the pair (%)")
ax.set_ylabel("CAGR gap from the log-weighting bug (%/yr)")
ax.set_title("The bug's cost grows with volatility and with dispersion")
plt.show()
d.round(4)
"""
        ),
        md(
            r"""

### 4.5 Sharpe moves; beta does not
"""
        ),
        code(
            r"""
sg = st.sharpe_gap(px).sort_values("vol_ann")
betas = pd.DataFrame([dict(ticker=tk, **st.beta_gap(px, tk, "SPY"))
                      for tk in ("QQQ", "EEM", "TLT", "GLD", "TQQQ")]).set_index("ticker")
fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].scatter(sg["vol_ann"] * 100, sg["gap"], s=60, color="#2ea44f")
for tk, r in sg.iterrows():
    axes[0].annotate(tk, (r["vol_ann"] * 100, r["gap"]), fontsize=7, xytext=(4, 2),
                     textcoords="offset points")
axes[0].axhline(0, color="k", lw=1); axes[0].set_xlabel("annualised vol (%)")
axes[0].set_ylabel("Sharpe(simple) - Sharpe(log)"); axes[0].set_title("The Sharpe ratio moves")
axes[1].bar(betas.index, betas["relative_gap"] * 100, color="#8b949e")
axes[1].axhline(0, color="k", lw=1)
axes[1].set_ylabel("relative difference in beta (%)"); axes[1].set_title("Beta barely does")
plt.show()
print(sg.round(4).to_string())
print()
print(betas.round(4).to_string())
"""
        ),
        md(
            r"""

> \U0001F4A1 **In plain words.** Beta survives the convention change because it is a ratio in
> which the second-order corrections appear in both the numerator and the denominator and
> largely cancel. Sharpe does not, because the drag hits the numerator only.
"""
        ),
        md(
            r"""

## 5 · The verdict
"""
        ),
        code(
            r"""
summary = pd.DataFrame({
    "largest mean gap (%/yr)": [dt["gap_ann"].max() * 100],
    "on": [dt["gap_ann"].idxmax()],
    "largest Sharpe gap": [sg["gap"].abs().max()],
    "portfolio bug (%/yr)": [err["cagr_gap"] * 100],
    "terminal wealth ratio": [err["terminal_ratio"]],
    "one-sided?": [err["always_understates"]],
}).T.rename(columns={0: "value"})
summary
"""
        ),
        md(
            r"""

## 6 · The rule, restated as code review

```python
# WRONG — log returns are not linear across assets
port = (log_rets * weights).sum(axis=1)

# RIGHT
port = (simple_rets * weights).sum(axis=1)
# and if you then need to compound it through time:
log_port = np.log1p(port)
```
"""
        ),
        md(
            r"""

## 7 · Going further

- **Continuous-time**: Fernholz's excess growth rate derives the same gap from stochastic
  portfolio theory, and generalises it to non-equal weights.
- **Higher moments**: the residual column in 4.1 is a Cornish-Fisher expansion waiting to
  happen.
- **Currency and leverage** stack the same second-order term twice; studies 995 and 942-944 on
  this desk are the two directions.
"""
        ),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
