"""Generate the two narrative notebooks for Study 28 (Carousel) from source.

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

The executed path runs on the offline synthetic sector panel (baked momentum + a null). The synthetic
proves the machinery; the real verdict (rotation does NOT beat holding all sectors) is quoted from
[`docs/results.md`](../docs/results.md). Both notebooks walk the SAME seven desk beats.
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../../.."))
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (9.5, 5.2)
import numpy as np, pandas as pd
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")
from carousel import data, rotation, strategy, decompose, extension

# Offline synthetic sectors: a MOMENTUM panel (leaders persist) and a no-momentum NULL. The real SPDR
# verdict is in ../docs/results.md.
panel,  truth = data.synthetic_sectors(mom_strength=0.0011, seed=28)   # the momentum panel
panel0, _     = data.synthetic_sectors(mom_strength=0.0,    seed=28)   # the null
print(f"{truth.n_sectors} synthetic sectors x {truth.n_bars} days | baked mom_strength={truth.mom_strength} | null=0")
"""

R = dict(
    n_sec="11", lo="1998", hi="2026", fp="14d15151ea57",
    rot_sr="+0.43", ew_sr="+0.45", gain="-0.02", turn="7.3",
    alpha="+0.4", alpha_t="+0.3", beta="0.92", ls="-1.5", ls_t="-0.5",
    topk_frac="33", best_k="1", sub1="+0.42", sub2="+0.33", sub3="+0.53",
)

BADGES = (
    "![Signal: Weak](https://img.shields.io/badge/Signal-Weak-dab617?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Beats the basket?: Not supported](https://img.shields.io/badge/Beats_the_basket%3F-Not_supported-8b949e?style=flat-square)\n\n"
)


def md(t): return new_markdown_cell(t)
def code(t): return new_code_cell(t)


def build_curious():
    cells = [
        md(
            "# Carousel 🎠\n"
            "### Rotate into whichever sectors are hottest. Does chasing the leaders beat just owning them all?\n\n"
            + BADGES +
            "Sector rotation is the strategy your uncle explains over Thanksgiving: tech is leading, so "
            "buy tech; energy is rolling over, so dump it; keep spinning into whatever's hot. The premise "
            "is **sector momentum** — a sector that's been winning keeps winning (Moskowitz–Grinblatt "
            "1999). It feels obviously smart. But there's a quiet benchmark it has to clear: just holding "
            "*all* the sectors, equal-weight, and never trading.\n\n"
            "This is the desk's eleventh idea from Kakushadze & Serur's *151 Trading Strategies* (strategy "
            "§4.1). We prove the engine on a synthetic market where sector momentum is baked in (and a "
            "null), then run the real SPDR sector ETFs — and find the carousel spins you right back to "
            "where you started, minus the cost of the ride.\n\n"
            "> 📓 **Plain-language layer.** The alpha-over-the-basket, the long-short factor *t* and the "
            "top-k sweep are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n"
            ">\n"
            "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it; the core runs "
            "on a **synthetic** panel, so the real-sector numbers (from "
            "[`../docs/results.md`](../docs/results.md)) are a measurement. House style in "
            "[METHODOLOGY.md](../../../METHODOLOGY.md)."
        ),
        code(BOOT),

        md(
            "## The answer first 🎯\n\n"
            "| What we asked | The honest answer |\n"
            "|---|---|\n"
            "| Does the hot sector stay hot? | 🟡 **Not enough to matter** — the real-sector long-short "
            f"momentum factor is flat-to-negative (**{R['ls']}%/yr**, *t* **{R['ls_t']}**). |\n"
            "| Does rotation beat holding all sectors? | 🚫 **No** — Sharpe **{R0}** vs the basket's "
            f"**{R['ew_sr']}** (gain **{R['gain']}**), alpha over the basket *t* = **{R['alpha_t']}**. |\n"
            "| Is it at least robust? | ⚪ **No** — it beats the basket on only **{R1}%** of "
            "\"how-many-sectors\" choices, a coin flip. |\n\n"
            "> Desk shorthand: **Signal `WEAK` · Tradability `MIRAGE` · Beats the basket? `NOT SUPPORTED`** "
            "— concentration risk and turnover, for nothing.".replace("{R0}", R["rot_sr"]).replace("{R1}", R["topk_frac"])
        ),

        md(
            "## 1 · The claim 📣\n\n"
            "Rank the sectors by their trailing return, hold the top few, refresh monthly. The claim is "
            "that the leaders keep leading. On our synthetic market we baked exactly that in — sort by "
            "momentum and the top sectors out-earn the bottom over the next month:"
        ),
        code(
            "rs = rotation.rotation_strength(panel)\n"
            "fig, ax = plt.subplots()\n"
            "ax.bar(['bottom-3', 'top-3'], [rs['bottom_ann_pct'], rs['top_ann_pct']], color=['#c0392b','#2ea44f'], alpha=.85)\n"
            "ax.set_ylabel('next-month return (annualised %)')\n"
            "ax.set_title(f\"Baked sector momentum: leaders out-earn laggards by {rs['top_minus_bottom_ann_pct']:+.0f}%/yr\")\n"
            "plt.show()"
        ),

        md(
            "## 2 · So what? 💰\n\n"
            "If sector momentum were real and harvestable, rotation would be a cheap, liquid way to beat "
            "the market — every robo-advisor and tactical-allocation fund would (and does) sell it. But "
            "concentrating into a few sectors is a *cost*: more idiosyncratic risk, more turnover, more "
            "drawdown when the hot sector turns. The only honest question is whether the momentum pays "
            "more than that diversification you gave up."
        ),

        md(
            "## 3 · How we'd know 🔬\n\n"
            "Three checks:\n\n"
            "1. **Does the hot sector stay hot?** The top-minus-bottom momentum spread and its *t*.\n"
            "2. **Does rotation beat the equal-weight basket** (alpha over it, net of cost)?\n"
            "3. **Does it generalise** across how many sectors you hold? And the **null:** no persistence "
            "⇒ no edge.\n\n"
            "**Mirage line:** rotation ties (or loses to) the basket, the long-short factor is "
            "insignificant, and the win is one cherry-picked concentration."
        ),

        md(
            "## 4 · The teardown 🔧\n\n"
            "### 4a · Momentum tape vs the null\n"
            "Run rotation on both synthetic panels, against the equal-weight basket."
        ),
        code(
            "for label, p in [('momentum', panel), ('null', panel0)]:\n"
            "    cmp = strategy.compare(p, cost_bps=3.0); a = decompose.vs_equal_weight(p, cost_bps=3.0)\n"
            "    print(f\"{label:9s}: rotation Sharpe {cmp['rotation']['sharpe']:+.2f} vs basket {cmp['equal_weight']['sharpe']:+.2f} \"\n"
            "          f\"(gain {cmp['rotation_minus_ew_sharpe']:+.2f}), alpha {a['alpha_ann_pct']:+.1f}%/yr (HAC t {a['alpha_t']:+.1f})\")"
        ),

        md(
            "### 4b · On the real market — the carousel goes nowhere\n"
            "On the 11 real SPDR sectors (quoted from [`../docs/results.md`](../docs/results.md)):\n\n"
            f"- Rotation Sharpe **{R['rot_sr']}** vs the equal-weight basket **{R['ew_sr']}** — a gain of "
            f"**{R['gain']}**, i.e. *worse*.\n"
            f"- Alpha over the basket **{R['alpha']}%/yr** (*t* **{R['alpha_t']}**), beta **{R['beta']}** — "
            "you basically held the market with extra steps.\n"
            f"- The pure sector-momentum factor is **{R['ls']}%/yr** (*t* **{R['ls_t']}**) — no premium.\n"
            f"- And it churns **{R['turn']}×/yr** for the privilege."
        ),

        md(
            "## 5 · The verdict 🧾\n\n"
            f"- **No sector-momentum premium** — long-short factor {R['ls']}%/yr (*t* {R['ls_t']}).\n"
            f"- **Doesn't beat the basket** — gain {R['gain']}, alpha *t* {R['alpha_t']}.\n"
            f"- **Doesn't generalise** — beats the basket on {R['topk_frac']}% of top-k choices.\n\n"
            "> **Signal `WEAK` · Tradability `MIRAGE` · Beats the basket? `NOT SUPPORTED`.** The carousel "
            "spins; you end up where you started, lighter by the cost of the ride."
        ),

        md(
            "## 6 · Could you trade it? 💸\n\n"
            "- **It ties the do-nothing basket** before you even worry about taxes on "
            f"**{R['turn']}×/yr** turnover.\n"
            "- **You paid in risk** — a 3-sector book is far more concentrated than holding all 11, for no "
            "return.\n"
            "- **The 'winning' setup is hindsight** — change how many sectors you hold and the edge "
            "vanishes.\n\n"
            "> Tradability **`MIRAGE`**; the top-k sweep ([`../docs/extension.md`](../docs/extension.md)) "
            "shows the cherry-pick."
        ),

        md(
            "## 7 · Going further 🚪\n\n"
            "- **The top-k sweep** (beat 7 of the quants notebook + "
            "[`../docs/extension.md`](../docs/extension.md)): rotation's gain over the basket across the "
            "number of sectors held — a coin flip.\n"
            "- **A bigger, finer universe.** 11 sectors is a tiny cross-section; sector momentum is "
            "studied on industries (49 Fama-French industries). Does it survive there, where the diversity "
            "is real?\n"
            "- **Dual momentum** (absolute + relative): only rotate when the leaders also beat cash — does "
            "the trend filter add anything, or just more parameters?\n\n"
            "PRs welcome — give rotation a real cross-section, or find the variant that beats buy-the-basket out of sample."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def build_quants():
    cells = [
        md(
            "# Carousel — a quantitative teardown 🔬\n"
            "### Sector-momentum spread · rotation alpha over the equal-weight basket (HAC) · the long-short factor · the top-k sweep\n\n"
            + BADGES +
            "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb) — *same seven "
            "beats, every claim with its standard error.* The steelman is §4.1 sector momentum rotation. "
            "We prove the engine on a synthetic sector panel with baked momentum, then show the real SPDR "
            "sectors carry no rotation edge over the basket.\n\n"
            "> ⚠️ **Not investment advice.** The core executes on synthetic data; the real run is in "
            "[`../docs/results.md`](../docs/results.md), sources in "
            "[`../docs/references.md`](../docs/references.md).\n"
            ">\n"
            "> 💡 **The `💡 In plain words` notes** translate each result back to intuition."
        ),
        code(BOOT),

        md(
            "## Beat 0 · Verdict\n\n"
            "| Axis | Stamp | Why |\n"
            "|---|---|---|\n"
            "| **Signal** — does the hot sector stay hot? | 🟡 `WEAK` | Strong on the control (alpha HAC "
            f"*t* ≈ 7.6); on the 11 real SPDR sectors the long-short momentum factor is **{R['ls']}%/yr** "
            f"(*t* **{R['ls_t']}**) — no premium. |\n"
            "| **Tradability** | 🔴 `MIRAGE` | Rotation Sharpe "
            f"**{R['rot_sr']}** ties the equal-weight basket (**{R['ew_sr']}**, gain **{R['gain']}**) at "
            f"**{R['turn']}×/yr** turnover and extra concentration. |\n"
            "| **Beats the basket?** | ⚪ `Not supported` | Beats the basket on only "
            f"**{R['topk_frac']}%** of top-k choices; alpha over the basket *t* = **{R['alpha_t']}**. |\n\n"
            "> **In one sentence:** sector momentum is real and recoverable on a synthetic control, but the "
            "11-sector SPDR cross-section carries no momentum premium and rotation merely re-buys the market "
            "with turnover and concentration.\n\n"
            "*(This notebook executes on the synthetic control; the real SPDR numbers are in "
            "[`../docs/results.md`](../docs/results.md).)*"
        ),

        md(
            "## Beat 1 · The claim, precisely\n\n"
            "Momentum score $m_i = \\prod_{t-126}^{t-21}(1+r_i)-1$ per sector; the long-only book holds the "
            "top-$k$, the long-short is top-minus-bottom-$k$, monthly. The test is the rotation alpha "
            "against the **equal-weight basket** $\\bar r_t = \\frac1N\\sum_i r_{i,t}$ — concentration is "
            "only worth it if $\\alpha>0$. The synthetic bakes a persistent per-sector drift; "
            "$\\text{mom\\_strength}=0$ is the null."
        ),
        code(
            "rs = rotation.rotation_strength(panel)\n"
            "print(f\"top-minus-bottom sector spread {rs['top_minus_bottom_ann_pct']:+.1f}%/yr (synthetic); \"\n"
            "      f\"null {rotation.rotation_strength(panel0)['top_minus_bottom_ann_pct']:+.1f}%/yr\")"
        ),

        md(
            "## Beat 2 · So what?\n\n"
            "Sector rotation trivially *looks* active and clever, but a long-only book of a few sectors "
            "has a beta near 1 to the basket, so most of its return is just the market. The decisive "
            "tests are therefore relative: the alpha *over* the equal-weight basket, the sign of the "
            "long-short factor, and whether any of it survives out of the cherry-picked concentration. "
            "Beats 4–6 run all three."
        ),

        md(
            "## Beat 3 · Pre-registered protocol\n\n"
            "1. **Spread** (`rotation.rotation_strength`): top-minus-bottom forward return.\n"
            "2. **Alpha over basket** (`decompose.vs_equal_weight`): HAC *t*.\n"
            "3. **Long-short factor** (`decompose.long_short_tstat`): the pure momentum premium.\n"
            "4. **Generalisation** (`extension.topk_sweep`); **null** collapses.\n\n"
            "**Mirage line:** alpha over basket insignificant, long-short flat, and a coin-flip top-k win-rate."
        ),

        md("## Beat 4 · The teardown\n\n### 4a · Rotation vs basket, momentum vs null"),
        code(
            "for label, p in [('momentum', panel), ('null', panel0)]:\n"
            "    a = decompose.vs_equal_weight(p, cost_bps=3.0); ls = decompose.long_short_tstat(p, cost_bps=3.0)\n"
            "    print(f\"{label:9s}: alpha over basket {a['alpha_ann_pct']:+.1f}%/yr (HAC t {a['alpha_t']:+.1f}), beta {a['beta']:.2f}; \"\n"
            "          f\"long-short {ls['mean_ann_pct']:+.1f}%/yr (t {ls['t_stat']:+.1f})\")"
        ),

        md("### 4b · The top-k sweep — robustness or cherry-pick"),
        code(
            "sw = extension.topk_sweep(panel, cost_bps=3.0)\n"
            "display(sw['matrix'].round(3))\n"
            "print(f\"synthetic: {sw['frac_beat_ew']:.0%} of top-k beat the basket, mean gain {sw['mean_gain']:+.2f}\")\n"
            f"print('Real SPDR sectors: only {R['topk_frac']}% of top-k beat the basket -- a coin flip (best k={R['best_k']}).')"
        ),
        md(
            "> 💡 **In plain words.** If rotation were a real edge it would help whether you held the top 2 "
            "sectors or the top 5. On the real sectors it helps at one number and hurts at the others — the "
            "signature of fitting the past, not finding a signal."
        ),

        md("## Beat 5 · The verdict\n\n"
           f"- **No premium** (4a): real long-short {R['ls']}%/yr (*t* {R['ls_t']}).\n"
           f"- **Ties the basket** (4a): alpha over basket *t* {R['alpha_t']}.\n"
           f"- **Cherry-picked** (4b): {R['topk_frac']}% of top-k beat the basket.\n\n"
           "> **Signal `WEAK` · Tradability `MIRAGE` · Beats the basket? `Not supported`.**"),

        md("## Beat 6 · Could you trade it?\n\n"
           f"- **Ties do-nothing** before taxes/{R['turn']}×-turnover.\n"
           "- **Paid in concentration risk** for no return.\n"
           "- **The win is hindsight** — fragile to the number of sectors held.\n\n"
           "Tradability **`MIRAGE`**; beats-the-basket **`Not supported`**."),

        md(
            "## Beat 7 · Going further\n\n"
            "### 7a · Worked complement — the top-k sweep\n"
            "Rotation's gain over the equal-weight basket across the number of sectors held."
        ),
        code(
            "sw = extension.topk_sweep(panel, cost_bps=3.0)\n"
            "print(f\"synthetic momentum: {sw['frac_beat_ew']:.0%} of top-k beat the basket (best k={sw['best_k']}).\")\n"
            f"print('Real SPDR sectors (../docs/extension.md): {R['topk_frac']}% beat the basket -- a rule that helps')\n"
            "print('at one concentration and not the others is a coin flip with extra turnover, not an edge.')"
        ),
        md(
            "**The result.** On the real sectors the rotation-minus-basket gain swings around zero as you "
            "vary how many sectors you hold, beating the basket only "
            f"**{R['topk_frac']}%** of the time. Pick the number after seeing the result and you can always "
            "tell a sector-rotation success story; demand it work *out of sample, at an unchosen "
            "concentration*, and it's a coin flip. That cherry-pick is exactly what the `Not supported` "
            "stamp records. Full run in [`../docs/extension.md`](../docs/extension.md).\n\n"
            "### 7b · Other forks\n"
            "- **A real cross-section** — 49 Fama-French industries instead of 11 SPDRs; sector momentum "
            "may need genuine breadth to exist.\n"
            "- **Dual momentum** — gate rotation on an absolute-momentum (vs cash) filter; does the trend "
            "filter help or just add parameters?\n"
            "- **Risk-parity sectors** vs equal-weight as the benchmark — a fairer bar.\n\n"
            "PRs welcome — give rotation breadth, or find the variant that beats buy-the-basket out of sample."
        ),
    ]
    return new_notebook(cells=cells, metadata=_meta())


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def main():
    nbf.write(build_curious(), os.path.join(HERE, "01_for_the_curious.ipynb"))
    nbf.write(build_quants(), os.path.join(HERE, "02_for_the_quants.ipynb"))
    print("wrote 01_for_the_curious.ipynb and 02_for_the_quants.ipynb")


if __name__ == "__main__":
    main()
