"""Build the two narrative notebooks for Study 45 (Vanishing-Act).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/vanishing_act_pairs.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (vanishing_act/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from vanishing_act import data, strategy as st
ret = data.fetch_pairs()                       # cache-first; built by examples/verify.py --fetch
smb_long = st.smb(ret, "^RUT", "^GSPC")        # the long-history spread
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Survived publication?: Busted](https://img.shields.io/badge/Survived_publication%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Vanishing-Act 🎩\n### \"Small-caps beat large-caps\" — the factor that launched an industry, on the tape\n\n"
           + VERDICT +
           "The size premium is finance's oldest factor: Banz showed in 1981 that small companies "
           "out-earn big ones, and a thousand small-cap funds followed. We test it on the longest free "
           "data — the Russell 2000 vs the S&P 500 back to 1987. Over 39 years the premium is **zero**, "
           "small-caps actually *trail* on a risk-adjusted basis, and since 2010 the effect has flipped sign.\n\n"
           "> 📓 **Plain-language layer.** The t-stats and the sign reversal are in "
           "**[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The belief | The tape |\n|---|---|\n"
           "| \"Small-caps earn a premium\" | Russell 2000 − S&P 500 = **+0.1%/yr over 39 years** (t = 0.05). |\n"
           "| \"…for taking more risk\" | Small-caps' **Sharpe is lower** (0.47 vs 0.61). |\n"
           "| \"A timeless factor\" | Positive before 2010, **negative since.** |"),
        md("## 1 · The claim\n\nBanz (1981): the smallest stocks earn higher returns than the largest, "
           "even after adjusting for market risk — the **size premium**, the SMB factor in every "
           "textbook model, the rationale for small-cap allocations everywhere."),
        md("## 2 · So what?\n\nIf small beats big, every investor should tilt small. If the premium has "
           "decayed to nothing — or reversed — then a core piece of portfolio orthodoxy is anchored on a "
           "fact that stopped being true decades ago."),
        md("## 3 · How would we even know?\n\nTake the longest free proxy — Russell 2000 minus S&P 500, "
           "1987–2026 — measure the spread and its t-stat, compare each side's standalone Sharpe, and "
           "split the sample at 2010 to see whether the premium survived its own publication."),
        code("eq=(1+smb_long).cumprod()\n"
             "ax=eq.plot(title='Cumulative size premium: Russell 2000 minus S&P 500, 1987-2026',lw=1.8)\n"
             "ax.axhline(1.0,color='k',lw=.8,ls='--'); ax.set_ylabel('growth of $1 (long small / short large)'); plt.show()\n"
             "s=st.smb_stats(smb_long); print(f\"39-year SMB: {s['mean_ann']:+.2%}/yr, Sharpe {s['sharpe']:.2f}, Lo t={s['tstat']:.2f}\")"),
        md("## 4 · The teardown\n\nA line that wanders up in the 80s–90s and gives it all back. The decade "
           "split shows the turn."),
        code("pairs={'^RUT−^GSPC':('^RUT','^GSPC'),'IWM−SPY':('IWM','SPY'),'IJR−IVV':('IJR','IVV')}\n"
             "dec={k: st.decay_split(st.smb(ret,a,b))['mean_ann'] for k,(a,b) in pairs.items() if a in ret and b in ret}\n"
             "D=pd.DataFrame(dec).T*100\n"
             "ax=D.plot.bar(rot=0,color=['#2ea44f','#c0392b'],title='Size premium per year: positive before 2010, negative since')\n"
             "ax.set_ylabel('SMB mean (%/yr)'); ax.axhline(0,color='k',lw=.8); ax.legend(['pre-2010','2010-on']); plt.show()"),
        md("**Read it plainly.** Green before 2010, red after — on every pair. The premium didn't just "
           "shrink; it changed sign. That's what an arbitraged-away anomaly looks like."),
        md("## 5 · The verdict\n\n**Signal: None** — zero over 39 years, small-caps even trailing on "
           "Sharpe. **Tradability: Mirage** — nothing to harvest. **Survived publication?: Busted** — the "
           "premium reversed after Banz."),
        md("## 6 · Could you actually trade it?\n\nYou can buy a small-cap ETF cheaply — but you'd be "
           "buying a *lower* Sharpe than the S&P 500, not a premium. The only version with a faint pulse "
           "(the S&P 600) earns it by screening for profitable companies — that's a quality bet, not a size one."),
        md("## 7 · Going further 🚪\n\nThe quants notebook adds the Lo t-stats and the quality caveat "
           "(Asness et al. 2018, *Size Matters, If You Control Your Junk*). This closes the five-study "
           "debunk bench from the [paperswithbacktest backlog](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Vanishing-Act — a quantitative teardown 🔬\n### SMB with a Lo t-stat · small-vs-large Sharpe · the sign reversal since 2010 · quality-not-size\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test the "
           "size premium on three pairs and find it statistically zero and decaying to negative.\n\n"
           "> ⚠️ **Not investment advice.** ^RUT/^GSPC (1987–2026) + IWM/SPY + IJR/IVV total return "
           "(2000–2026), Yahoo. Sources in [`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | 39-yr SMB Sharpe 0.01, Lo t 0.05 |\n"
           "| Tradability | **Mirage** | ETF SMB insignificant; small Sharpe < large |\n"
           "| Survived publication? | **Busted** | positive pre-2010, negative since, every pair |\n\n"
           "> 💡 *In plain words:* the original factor is the clearest decay case on the bench."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** SMB > 0 with |t| > 2 over the long sample.\n"
           "- **H₂:** small-caps deliver a higher Sharpe than large-caps.\n- **H₃:** the premium is "
           "stable (didn't decay after Banz 1981)."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, a size tilt is a free risk-adjusted "
           "gain. If they fail, the SMB factor and small-cap allocations rest on a dead premium."),
        md("## 3 · How we'd know — the protocol\n\nSMB spread per pair → Lo (2002) t-stat → each leg's "
           "standalone Sharpe → pre/post-2010 decay split → the quality caveat (S&P 600 vs Russell 2000)."),
        md("## 4 · The teardown"),
        md("### 4.1 The spread, with a t-stat, across pairs"),
        code("rows={}\n"
             "for k,(a,b) in {'^RUT−^GSPC':('^RUT','^GSPC'),'IWM−SPY':('IWM','SPY'),'IJR−IVV':('IJR','IVV')}.items():\n"
             "    if a in ret and b in ret:\n"
             "        s=st.smb_stats(st.smb(ret,a,b)); rows[k]={'SMB %/yr':s['mean_ann']*100,'Sharpe':s['sharpe'],'Lo t':s['tstat'],'n':s['n']}\n"
             "display(pd.DataFrame(rows).T.round(3))"),
        md("> 💡 *In plain words:* not one |t| reaches 2. **H₁ rejected** — no detectable premium."),
        md("### 4.2 Small-caps trail on Sharpe"),
        code("for a,b in [('^RUT','^GSPC'),('IWM','SPY'),('IJR','IVV')]:\n"
             "    if a in ret and b in ret:\n"
             "        print(f'{a} Sharpe {st.leg_summary(ret,a)[\"sharpe\"]:.2f}  vs  {b} Sharpe {st.leg_summary(ret,b)[\"sharpe\"]:.2f}')"),
        md("> 💡 *In plain words:* the 'risk premium' delivers *less* risk-adjusted return than the "
           "large-cap index. **H₂ rejected.**"),
        md("### 4.3 The decay — positive then negative"),
        code("pairs={'^RUT−^GSPC':('^RUT','^GSPC'),'IWM−SPY':('IWM','SPY'),'IJR−IVV':('IJR','IVV')}\n"
             "dec=pd.concat({k: st.decay_split(st.smb(ret,a,b))['mean_ann'] for k,(a,b) in pairs.items() if a in ret and b in ret}, axis=1).T\n"
             "display((dec*100).round(2))"),
        md("> 💡 *In plain words:* every pair's premium is positive before 2010 and negative after. "
           "**H₃ rejected** — the cleanest post-publication reversal on the bench (van Dijk 2011)."),
        md("### 4.4 What survives is quality, not size"),
        md("The one pair with a faint positive tilt is **IJR − IVV** (S&P SmallCap 600 vs S&P 500). The "
           "S&P 600, unlike the Russell 2000, **screens constituents for positive earnings** — so its "
           "edge is a *profitability* screen, exactly the Asness et al. (2018) *\"Size Matters, If You "
           "Control Your Junk\"* result. Strip the quality and the size premium is gone."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all rejected → Signal `NONE`, Tradability `MIRAGE`, "
           "survived-publication `BUSTED`."),
        md("## 6 · Could you trade it?\n\nA size *tilt* buys a lower Sharpe than the S&P 500. The only "
           "live version is a quality screen in disguise. There is no size premium to harvest on tradable proxies."),
        md("## 7 · Going further\n\nForks: (a) Ken French's SMB back to 1926 — confirm the pre-1981 "
           "premium and the post-1981 fade on the academic series; (b) double-sort size × profitability "
           "to isolate the quality driver; (c) micro-cap SMB, where survivorship and illiquidity inflate "
           "the headline. Backlog: [`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
