"""Build the two narrative notebooks for Study 45 (Vanishing-Act).

    python notebooks/build_notebooks.py
    jupyter nbconvert --to notebook --execute --inplace \
        notebooks/01_for_the_curious.ipynb notebooks/02_for_the_quants.ipynb

Figures inline from the cached real run (_cache/vanishing_act_pairs.parquet, built by
examples/verify.py --fetch)."""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))

BOOT = """\
import sys, os
sys.path.insert(0, os.path.abspath("../../.."))  # repo root (quantlab/)
sys.path.insert(0, os.path.abspath(".."))        # study package (vanishing_act/)
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 5.5); plt.rcParams["axes.grid"] = True
import numpy as np, pandas as pd
from vanishing_act import data, strategy as st
from quantlab import repro
ret = repro.as_of(data.fetch_pairs())          # cache-first, pinned to the desk as-of
smb_long = st.smb(ret, "^RUT", "^GSPC")        # the long-history spread (price indices — conservative)
"""

VERDICT = (
    "![Signal: None](https://img.shields.io/badge/Signal-None-c0392b?style=flat-square)\n"
    "![Tradability: Mirage](https://img.shields.io/badge/Tradability-Mirage-c0392b?style=flat-square)\n"
    "![Survived publication?: Busted](https://img.shields.io/badge/Survived_publication%3F-Busted-8b949e?style=flat-square)\n\n"
)


def md(t):
    return new_markdown_cell(t)


def code(t):
    return new_code_cell(t)


def build_curious():
    cells = [
        md("# Vanishing-Act 🎩\n### \"Small-caps beat large-caps\" — the factor that launched an industry, on the tape\n\n"
           + VERDICT +
           "The size premium is finance's oldest factor: Banz showed in 1981 that small companies "
           "out-earn big ones, and a thousand small-cap funds followed. We test it on the longest free "
           "data — the Russell 2000 vs the S&P 500 back to 1987. Over 39 years the premium is **zero**, "
           "small-caps actually *trail* on a risk-adjusted basis, and the sign of any \"decade of "
           "small-cap outperformance\" depends entirely on which decade you pick. And note the dates: "
           "the data starts six years *after* the paper — everything you're about to see is "
           "post-publication.\n\n"
           "> 📓 **Plain-language layer.** The t-stats, the aligned-sample discipline and the "
           "window-split bootstrap are in **[02_for_the_quants.ipynb](02_for_the_quants.ipynb)**.\n>\n"
           "> ⚠️ **Not investment advice.** Every chart is generated by the code beside it."),
        code(BOOT),
        md("## The answer first 🎯\n\n"
           "| The belief | The tape |\n|---|---|\n"
           "| \"Small-caps earn a premium\" | Russell 2000 − S&P 500 = **+0.03%/yr over 39 years** (t = 0.02). |\n"
           "| \"…for taking more risk\" | On the same months, small-caps' **Sharpe is lower** (0.47 vs 0.62). |\n"
           "| \"It worked until everyone piled in\" | The whole sample is *post*-publication — and it never worked in it. The sign flips with the window. |"),
        md("## 1 · The claim\n\nBanz (1981): the smallest stocks earn higher returns than the largest, "
           "even after adjusting for market risk — the **size premium**, the SMB factor in every "
           "textbook model, the rationale for small-cap allocations everywhere."),
        md("## 2 · So what?\n\nIf small beats big, every investor should tilt small. If the premium "
           "can't be found in four decades of post-publication data, then a core piece of portfolio "
           "orthodoxy is anchored on a result nobody has been able to reproduce out of sample."),
        md("## 3 · How would we even know?\n\nTake the longest free proxy — Russell 2000 minus S&P 500, "
           "1987–2026 — measure the spread and its t-stat, compare each side's standalone Sharpe **on "
           "the same months**, and ask whether any sub-period 'premium' survives an honest test of "
           "window luck. (The index pair is price-only; large caps pay more dividends, so a "
           "total-return spread would look *worse* for size — the test is tilted in the premium's favour.)"),
        code("eq=(1+smb_long).cumprod()\n"
             "ax=eq.plot(title='Cumulative size premium: Russell 2000 minus S&P 500, 1987-2026',lw=1.8)\n"
             "ax.axhline(1.0,color='k',lw=.8,ls='--'); ax.set_ylabel('growth of $1 (long small / short large)'); plt.show()\n"
             "s=st.smb_stats(smb_long); print(f\"39-year SMB: {s['mean_ann']:+.2%}/yr, Sharpe {s['sharpe']:.2f}, Lo t={s['tstat']:.2f}\")"),
        md("## 4 · The teardown\n\nA line that wanders for four decades and ends where it started. And "
           "because \"it worked before 2010\" is the usual rescue, here is the trailing ten-year "
           "premium — the thing a fund brochure would show you — for every possible ending month."),
        code("roll=st.rolling_mean_ann(smb_long,120).dropna()\n"
             "ax=(roll*100).plot(lw=1.6,title='The \"10-year size premium\" depends on when you ask')\n"
             "ax.axhline(0,color='k',lw=.8); ax.set_ylabel('trailing 10y SMB (%/yr)'); plt.show()\n"
             "print(f'range {roll.min():+.1%} to {roll.max():+.1%}/yr; positive in {(roll>0).mean():.0%} of windows')"),
        md("**Read it plainly.** The \"premium\" swings from −5%/yr to +7%/yr and crosses zero again and "
           "again. Pick an ending month and you can prove smallness pays, or that it costs you — which "
           "is another way of saying there is no premium, just windows."),
        md("## 5 · The verdict\n\n**Signal: None** — zero over 39 years, small-caps even trailing on "
           "Sharpe. **Tradability: Mirage** — nothing to harvest. **Survived publication?: Busted** — "
           "every month of this sample postdates Banz 1981, and the premium never showed."),
        md("## 6 · Could you actually trade it?\n\nYou can buy a small-cap ETF cheaply — but you'd be "
           "buying a *lower* Sharpe than the S&P 500, not a premium. The only version with a faint pulse "
           "(the S&P 600) earns it by screening for profitable companies — that's a quality bet, not a size one."),
        md("## 7 · Going further 🚪\n\nThe quants notebook adds the Lo t-stats, the aligned-sample "
           "discipline, the bootstrap on the 2010 split, and the quality caveat (Asness et al. 2018, "
           "*Size Matters, If You Control Your Junk*). This closes the five-study debunk bench from the "
           "[paperswithbacktest backlog](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "01_for_the_curious.ipynb")


def build_quants():
    cells = [
        md("# Vanishing-Act — a quantitative teardown 🔬\n### SMB with a Lo t-stat · aligned leg Sharpes · the window-split bootstrap · the sign-flip exhibit · quality-not-size\n\n"
           + VERDICT +
           "The deep companion to the [notebook for the curious](01_for_the_curious.ipynb). We test the "
           "size premium on three pairs and find it statistically zero — with the famous 'turn in 2010' "
           "dissolving into window noise on the only long series.\n\n"
           "> ⚠️ **Not investment advice.** ^RUT/^GSPC 1987–2026 (price indices — no dividends; since "
           "large caps yield more, a total-return spread would be *more* negative, so the long history "
           "is conservative) + IWM/SPY + IJR/IVV total return, 2000–2026, Yahoo. Sources in "
           "[`docs/references.md`](../docs/references.md)."),
        code(BOOT),
        md("## Verdict, up front\n\n| Axis | Stamp | Why |\n|---|---|---|\n"
           "| Signal | **None** | 39-yr SMB Sharpe 0.00, Lo t 0.02 |\n"
           "| Tradability | **Mirage** | ETF SMB insignificant; small Sharpe < large on the same months |\n"
           "| Survived publication? | **Busted** | the whole sample is post-Banz and the premium never showed; the 2010 'turn' is window noise (p = 0.45 on the long series) |\n\n"
           "> 💡 *In plain words:* the original factor isn't a decay story — there was nothing on this "
           "tape to decay."),
        md("## 1 · The claim, steelmanned\n\n- **H₁:** SMB > 0 with |t| > 2 over the long sample.\n"
           "- **H₂:** small-caps deliver a higher Sharpe than large-caps (same months, same bar).\n"
           "- **H₃:** sub-period structure — the 'positive then negative around 2010' shape — reflects "
           "a real regime change, not window luck."),
        md("## 2 · So what? — what rides on each\n\nIf H₁/H₂ hold, a size tilt is a free risk-adjusted "
           "gain. If they fail, the SMB factor and small-cap allocations rest on a premium nobody can "
           "find in 39 years of out-of-sample data. (One thing no split of this sample can test: "
           "*post-publication decay* — Banz published in 1981, the data starts in 1987, so there is no "
           "'before' to compare against. McLean–Pontiff needs a pre-publication window; we don't have one.)"),
        md("## 3 · How we'd know — the protocol\n\nSMB spread per pair → Lo (2002) t-stat → each leg's "
           "standalone Sharpe **on the pair's common months** (aligned by construction in "
           "`leg_summary`) → the trailing-10y sign-flip exhibit → the post-hoc 2010 split scored with a "
           "circular-block-bootstrap p-value on the pre/post difference → the quality caveat (S&P 600 "
           "vs Russell 2000)."),
        md("## 4 · The teardown"),
        md("### 4.1 The spread, with a t-stat, across pairs"),
        code("rows={}\n"
             "for k,(a,b) in data.PAIRS.items():\n"
             "    if a in ret and b in ret:\n"
             "        s=st.smb_stats(st.smb(ret,a,b)); rows[f'{a}−{b}']={'SMB %/yr':s['mean_ann']*100,'Sharpe':s['sharpe'],'Lo t':s['tstat'],'n':s['n']}\n"
             "display(pd.DataFrame(rows).T.round(3))"),
        md("> 💡 *In plain words:* not one |t| reaches 2 — the longest series sits at 0.02. **H₁ "
           "rejected** — no detectable premium."),
        md("### 4.2 Small-caps trail on Sharpe — on the same months"),
        code("for a,b in data.PAIRS.values():\n"
             "    if a in ret and b in ret:\n"
             "        L=st.leg_summary(ret,a,b)\n"
             "        print(f\"{L['start'].date()}..{L['end'].date()} ({L['n']} mo)  {a} Sharpe {L['small']['sharpe']:.2f}  vs  {b} Sharpe {L['large']['sharpe']:.2f}\")"),
        md("> 💡 *In plain words:* every leg pair is compared on its intersection — aligning samples "
           "matters (SPY's Sharpe is 0.77 from its 1993 inception but 0.61 on IWM's 2000–2026 months; "
           "only the latter is a fair comparison). On equal footing the 'risk premium' delivers *less* "
           "risk-adjusted return than the large-cap index. **H₂ rejected.**"),
        md("### 4.3 The 2010 split, scored honestly"),
        code("rows={}\n"
             "for k,(a,b) in data.PAIRS.items():\n"
             "    if a in ret and b in ret:\n"
             "        d=st.split_difference(st.smb(ret,a,b),cut_year=2010)\n"
             "        rows[f'{a}−{b}']={'pre %/yr':d['pre_ann']*100,'post %/yr':d['post_ann']*100,'diff %/yr':d['diff_ann']*100,'bootstrap p':d['p_value']}\n"
             "display(pd.DataFrame(rows).T.round(2))\n"
             "roll=st.rolling_mean_ann(smb_long,120).dropna()\n"
             "ax=(roll*100).plot(lw=1.6,title='Trailing 10y SMB (^RUT−^GSPC): the sign is a window choice')\n"
             "ax.axhline(0,color='k',lw=.8); ax.set_ylabel('%/yr'); plt.show()"),
        md("> 💡 *In plain words:* the split at 2010 is post-hoc, and on the long series it fails its "
           "own test — pre-2010 SMB was +1.1%/yr at Sharpe 0.09 (itself ≈ 0) and the pre/post "
           "difference has p = 0.45. The ETF pairs' gap is detectable (p ≈ 0.02–0.03), but both start "
           "in 2000 — 19 years *after* publication — so what it captures is one good small-cap decade "
           "(the post-dot-com 2000s) followed by a bad one: regime dependence, not a publication "
           "event. **H₃ rejected** — and with it the romantic 'arbitraged away after Banz' story; the "
           "data can't even show it was there to arbitrage."),
        md("### 4.4 What survives is quality, not size"),
        md("The one pair with a faint positive tilt is **IJR − IVV** (S&P SmallCap 600 vs S&P 500). The "
           "S&P 600, unlike the Russell 2000, **screens constituents for positive earnings** — so its "
           "edge is a *profitability* screen, exactly the Asness et al. (2018) *\"Size Matters, If You "
           "Control Your Junk\"* result. Strip the quality and the size premium is gone."),
        md("## 5 · The verdict\n\nH₁, H₂, H₃ all rejected → Signal `NONE`, Tradability `MIRAGE`, "
           "survived-publication `BUSTED` — zero over 39 post-publication years."),
        md("## 6 · Could you trade it?\n\nA size *tilt* buys a lower Sharpe than the S&P 500. The only "
           "live version is a quality screen in disguise. There is no size premium to harvest on tradable proxies."),
        md("## 7 · Going further\n\nForks: (a) Ken French's SMB back to 1926 — the only data that *can* "
           "run a real pre/post-1981 publication test (our proxies can't); (b) double-sort size × "
           "profitability to isolate the quality driver; (c) micro-cap SMB, where survivorship and "
           "illiquidity inflate the headline. Backlog: "
           "[`docs/pwb_strategies_inventory.md`](../../../docs/pwb_strategies_inventory.md)."),
    ]
    _write(new_notebook(cells=cells, metadata=_meta()), "02_for_the_quants.ipynb")


def _meta():
    return {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}}


def _write(nb, name):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("wrote", path)


if __name__ == "__main__":
    build_curious()
    build_quants()
