"""Beat-7 worked complement on the real tape — the tether drifts, and the in-sample winners don't last.

The headline reports how few pairs survive out of sample. This complement shows *why*: the hedge ratio
that defines each pair quietly drifts, so the spread is measured against a moving anchor, and the pairs
that looked best in the first half are not the ones that work in the second. Writes `docs/extension.md`.

    python examples/extension.py            # cache-only
    python examples/extension.py --fetch
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from broken_tether import data, extension
from quantlab.repro import DEFAULT_AS_OF, as_of, fingerprint

OUT = os.path.join(_STUDY, "docs", "extension.md")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()

    closes = data.fetch_closes(fetch=args.fetch)
    if not closes:
        print("[skip] no cached closes -- run with --fetch first.")
        return
    closes = {tk: as_of(c.to_frame(), DEFAULT_AS_OF)[tk] for tk, c in closes.items()}
    fp = fingerprint(pd.DataFrame(closes).round(6))

    scan = extension.oos_scan(closes, cost_bps=2.0, max_pairs=45)
    # rank correlation between first-half and second-half Sharpe (does the in-sample order carry over?)
    fh = scan["first_half"].astype(float); sh = scan["second_half"].astype(float)
    rank_corr = float(fh.rank().corr(sh.rank()))
    # drift across pairs
    names = list(closes)
    import itertools
    drifts = []
    for a, b in itertools.islice(itertools.combinations(names, 2), 45):
        drifts.append(extension.hedge_ratio_drift(closes[a], closes[b])["beta_rel_drift"])
    drifts = np.array([d for d in drifts if np.isfinite(d)])

    print(f"first-half/second-half rank corr {rank_corr:+.2f}; median beta drift {np.median(drifts):.0%}")
    _write(OUT, scan, rank_corr, float(np.median(drifts)), fp, DEFAULT_AS_OF,
           pd.DataFrame(closes).index.min().date(), pd.DataFrame(closes).index.max().date())
    print(f"\nwrote {OUT}")


def _write(path, scan, rank_corr, med_drift, fp, asof, lo, hi):
    n_surv = int(scan["survives"].sum()); n = len(scan)
    text = f"""# Beat 7 — worked complement: the tether drifts (Study 23, Broken-Tether)

*Generated by [`examples/extension.py`](../examples/extension.py) on the cached ETF pairs. As-of
**{asof}**, {lo} → {hi}, fingerprint `{fp}`.*

## The in-sample winners are not the out-of-sample ones

If pair cointegration were stable, the pairs that worked in the first half would work in the second.
They don't. The Spearman rank correlation between first-half and second-half Sharpe across **{n}** pairs
is **{rank_corr:+.2f}** — essentially no carry-over. Picking pairs on in-sample performance is picking
noise: only **{n_surv}/{n}** survive.

## Why — the hedge ratio won't sit still

The trade assumes a stable relationship ``log A ≈ β·log B``. But the trailing β drifts by a median of
**{med_drift:.0%}** of its own level across these pairs — so the "spread" each trade reverts toward is
measured against a moving anchor. That is the slow death of a pairs trade: not a single dramatic break,
but a tether that stretches until the relationship the trade was built on no longer holds.

**Takeaway.** `WEAK` / `MIRAGE` / `Breaks` survives the worked complement. Pairs trading is real on a
*stable* cointegrated pair — but stable cointegration among liquid, already-arbitraged ETFs is rare,
unstable, and mostly an artefact of selection. The classic statistical-arbitrage edge, competed down and
fragile to the one assumption it can't do without: that the relationship stays put.
"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
