"""Beat-7 worked complement — can a jump-robust vol rescue AS's collapsing "production fix"?

The base study (docs/results.md) found the first adaptation the viral write-up recommends —
feed a rolling realised volatility into the spread — *collapses* in the jumpy World B: naive
realised variance inhales the jump variance, the spread blows out, and the book stops trading
(Sharpe 2.15 -> 0.18). The obvious repair is a **jump-robust** vol estimator. This script swaps
the naive estimator for **bipower variation** (Barndorff-Nielsen & Shephard 2004) and asks
whether the fix is salvageable. Deterministic, offline.

    python examples/extension.py

Writes docs/extension.md with seed-fixed numbers and a content fingerprint.
"""

import os
import sys

import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from phantom_kernel import experiments as ex, sim
from quantlab.repro import fingerprint

pd.set_option("display.width", 220)
pd.set_option("display.float_format", lambda v: f"{v:,.4f}")

OUT = os.path.join(_STUDY, "docs", "extension.md")
SEED = 0


def main():
    tB = ex.extension_rescue(sim.WORLD_B, seed=SEED)       # the hostile world (where it collapses)
    tA = ex.extension_rescue(sim.WORLD_A, seed=SEED)       # calm control (estimator should be a no-op)
    msB = ex.extension_rescue_multiseed(sim.WORLD_B)
    fp = fingerprint(msB.reset_index(drop=True).set_axis(
        pd.RangeIndex(len(msB)).map(lambda i: pd.Timestamp("2000-01-01") + pd.Timedelta(days=i))
    ), round_dp=4)

    print("[World B — the rescue attempt]\n", tB.to_string())
    print("\n[World A — calm control]\n", tA.to_string())
    print("\n[World B — Sharpe across seeds]\n", msB.round(3).to_string())
    print("\nfingerprint:", fp)
    _write(tB, tA, msB, fp)
    print(f"\nwrote {OUT}")


def _write(tB, tA, msB, fp):
    def md(df):
        return "```\n" + df.to_string() + "\n```"

    naive = tB.loc["AS (naive RV)", "pnl_sharpe"]
    robust = tB.loc["AS (jump-robust BV)", "pnl_sharpe"]
    fixed = tB.loc["AS (fixed sigma)", "pnl_sharpe"]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(f"""# Extension — Study 09 (Phantom-Kernel): does a jump-robust vol rescue the "production fix"?

*The beat-7 worked complement. Generated by [`examples/extension.py`](../examples/extension.py)
on the seed-fixed simulator. Seed {SEED}; fingerprint **`{fp}`**.*

| Axis | Stamp | Why |
|---|---|---|
| **The rolling-vol "production fix", made jump-robust** | ![Not rescued](https://img.shields.io/badge/Not--rescued-8b949e?style=flat-square) | Bipower variation **mitigates** the collapse (World-B Sharpe **{naive} → {robust}**, ~2× the fills) but stays a fraction of plain fixed-σ AS (**{fixed}**). Removing jumps from the estimate isn't enough: in a stochastic-vol regime the *robust* vol still rises and widens the spread, so the book still under-trades. **Adapting spread width is the wrong lever — not just jump contamination.** |

## What the base study found
The article's first recommended adaptation is to feed a **rolling realised volatility** into the
AS spread. In the jumpy World B that fix **collapses**: naive realised variance `Σ rᵢ²` inhales
the jump variance, one jump spikes `σ̂`, the spread blows out, and almost nothing fills
(Sharpe **{fixed} → {naive}**). See [`docs/results.md`](results.md).

## The repair under test
Replace the naive estimator with **bipower variation** (Barndorff-Nielsen & Shephard 2004),

    BV = (π/2) · mean(|rᵢ| · |rᵢ₋₁|),

which estimates the *diffusive* variance: a lone jump enters only ~two terms and is dominated,
so `σ̂` tracks the genuine volatility regime without spiking on a jump
([`JumpRobustASQuoter`](../phantom_kernel/strategies.py)). Three AS variants — fixed σ, naive
rolling vol, jump-robust rolling vol — face the **identical** order flow.

## World B (jumps + stochastic vol + informed flow) — where the fix was needed
{md(tB)}

Jump-robustness **helps** — it roughly doubles the collapsed Sharpe and the fill count — but the
patient is still on the floor: **{robust}** vs fixed-σ's **{fixed}**. The reason is structural:
World B also has *genuine* stochastic volatility, and bipower variation faithfully tracks it, so
in high-vol stretches the spread still widens and the book still under-fills. The damage was
never only jump contamination — it is that **adapting the spread width at all** sacrifices the
spread capture that fixed-σ AS keeps harvesting while the (k-free) inventory skew does the real
work.

## World A (calm, no jumps) — the control
{md(tA)}

With no jumps the estimator choice is a **no-op**: all three AS variants land in the same place.
The jump-robust machinery costs nothing when there's nothing to be robust to — it simply fails
to add the value the fix was hoping for.

## Seed-robustness (World B P&L Sharpe)
{md(msB.round(3))}

## Read
The article frames rolling realised vol as a clean upgrade; jump-robustness is the textbook way
to make it behave. It **isn't enough** — the fix is mitigated, not rescued. This *sharpens* the
study's core verdict rather than overturning it: the value in Avellaneda-Stoikov is the
**k-free inventory skew**, and every attempt to make the **spread-width** machinery smart (a
data-driven `k`, a rolling σ, now a jump-robust rolling σ) either misprices it or trades away
the edge. Keep the skew; quote the width with a fixed, sensible heuristic.

> Base verdict: [README](../README.md) · [`docs/results.md`](results.md). Real-data heavy-tail
> confirmation: [`docs/results_real.md`](results_real.md).
""")


if __name__ == "__main__":
    main()
