"""Empirical leg (runnable harness) — does *real* order flow have an exponential kernel?

This is the open thread of Study 09 (beat 7). The verdict in the README is earned on the
simulator + the heavy-tail literature; this script lets anyone confront the load-bearing
assumption with real market data, and writes ``docs/results_real.md`` with the same
exponential-vs-power-law goodness-of-fit the simulator uses.

It is **cache-only and degrades gracefully**: with no data it prints exactly how to get some
and exits 0 (it never fabricates a number). Point it at a parquet of executed trades with a
contemporaneous mid:

    _cache/trades.parquet  with columns:  price (float), qty (float), mid (float)

where ``mid`` is the order-book mid at the moment of each trade. The empirical arrival kernel
is then ``lambda(delta) = #{trades with |price - mid| >= delta}`` over a distance grid — the
real-data analogue of the simulator's fill counts.

How to get the data (Binance spot, free, no key):
  * Trades + book ticker: https://data.binance.vision/ (aggTrades and bookTicker daily zips),
    e.g. BTCUSDT. Join each trade to the prevailing bookTicker mid = (bid+ask)/2, write the
    three columns above to _cache/trades.parquet, then re-run this script.

    python examples/verify_real.py
"""

import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from phantom_kernel.estimator import goodness_of_fit
from quantlab.repro import fingerprint

CACHE = os.path.join(_STUDY, "_cache", "trades.parquet")
OUT = os.path.join(_STUDY, "docs", "results_real.md")


def _fetch_instructions():
    print("No cached trades found at", CACHE)
    print("This is the empirical leg and needs real order flow. To run it:")
    print("  1. Download Binance spot aggTrades + bookTicker for a symbol from")
    print("     https://data.binance.vision/ (free, no API key).")
    print("  2. Join each trade to the prevailing mid = (bid+ask)/2.")
    print("  3. Write columns [price, qty, mid] to", CACHE)
    print("  4. Re-run: python examples/verify_real.py")
    print("\nThe README verdict stands on the simulator + the heavy-tail literature; this")
    print("script is the open invitation to confirm it on a market of your choice.")


def main():
    if not os.path.exists(CACHE):
        _fetch_instructions()
        return

    trades = pd.read_parquet(CACHE)
    for col in ("price", "mid"):
        if col not in trades.columns:
            raise SystemExit(f"trades.parquet must contain a {col!r} column")

    dist = (trades["price"] - trades["mid"]).abs().to_numpy()
    dist = dist[np.isfinite(dist) & (dist >= 0)]
    if dist.size < 1000:
        raise SystemExit("need >= 1000 trades to fit a kernel")

    # Distance grid out to the 99.9th percentile so the tail (the discriminating region) shows.
    hi = float(np.quantile(dist, 0.999))
    deltas = np.linspace(hi / 80.0, hi, 80)
    dist_sorted = np.sort(dist)
    counts = (dist.size - np.searchsorted(dist_sorted, deltas, side="left")).astype(float)

    g = goodness_of_fit(deltas, counts)
    fp = fingerprint(pd.DataFrame({"d": deltas, "c": counts},
                                  index=pd.bdate_range("2000-01-03", periods=len(deltas))), round_dp=4)

    print(f"[real order flow] {dist.size:,} trades   fingerprint={fp}")
    print(f"  exponential fit: R^2={g['r2_exp']:.4f}  k={g['k_exp']:.4f}")
    print(f"  power-law  fit : R^2={g['r2_pow']:.4f}  alpha={g['alpha_pow']:.4f}")
    print(f"  AIC gap (exp - pow) = {g['aic_gap']:,.0f}  ->  winner: {g['winner']}")

    verdict = ("the exponential AS kernel is REJECTED on this market (a power law fits better)"
               if g["winner"] == "power-law"
               else "the exponential AS kernel is NOT rejected on this market")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(f"""# Real-data leg — Study 09 (Phantom-Kernel)

*Generated by [`examples/verify_real.py`](../examples/verify_real.py) on {dist.size:,} real
trades. Empirical kernel: `lambda(delta) = #{{trades with |price - mid| >= delta}}`.
Fingerprint **`{fp}`**.*

| fit | R^2 | parameter |
|---|---|---|
| exponential `A e^(-k d)` (AS) | {g['r2_exp']:.4f} | k = {g['k_exp']:.4f} |
| power law `A' d^(-alpha)` | {g['r2_pow']:.4f} | alpha = {g['alpha_pow']:.4f} |

AIC gap (exp - pow) = **{g['aic_gap']:,.0f}** -> winner: **{g['winner']}**.

**Read:** {verdict}.
""")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
