"""Empirical leg — generic harness: does *real* order flow have an exponential kernel?

The committed real-data confirmation lives in ``examples/confirm_heavy_tail.py`` (four Binance
markets → ``docs/results_real.md``). This script is the **bring-your-own-data** version: point it
at any parquet of executed trades and it runs the same rigorous Clauset/Vuong tail test
(power-law vs exponential) on the price-distance ``|price - mid|`` and, if present, on order
size — then writes ``docs/results_real.md``.

    _cache/trades.parquet  with columns:  price (float), [qty (float),] mid (float)

where ``mid`` is the order-book mid at the moment of each trade. It is **cache-only and degrades
gracefully**: with no data it prints how to build some (via ``fetch_binance.py``) and exits 0 —
it never fabricates a number.

    python examples/fetch_binance.py        # builds _cache/trades.parquet from real data
    python examples/verify_real.py          # then fits the tail on it
"""

import os
import sys

import numpy as np
import pandas as pd

_STUDY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _STUDY)
sys.path.insert(0, os.path.abspath(os.path.join(_STUDY, "..", "..")))

from phantom_kernel.estimator import tail_test
from quantlab.repro import fingerprint

CACHE = os.path.join(_STUDY, "_cache", "trades.parquet")
OUT = os.path.join(_STUDY, "docs", "results_real.md")


def _fetch_instructions():
    print("No cached trades found at", CACHE)
    print("This generic harness fits the tail on any trades.parquet with [price, qty, mid].")
    print("To build one from real Binance futures (free, no key) just run:")
    print("    python examples/fetch_binance.py [SYMBOL] [YYYY-MM-DD]")
    print("then re-run this script. For the committed multi-market confirmation, run:")
    print("    python examples/confirm_heavy_tail.py   ->  docs/results_real.md")


def main():
    if not os.path.exists(CACHE):
        _fetch_instructions()
        return

    trades = pd.read_parquet(CACHE)
    for col in ("price", "mid"):
        if col not in trades.columns:
            raise SystemExit(f"trades.parquet must contain a {col!r} column")

    dist = (trades["price"] - trades["mid"]).abs().to_numpy()
    dist = dist[np.isfinite(dist) & (dist >= 0)]
    if dist.size < 1000:
        raise SystemExit("need >= 1000 trades to fit a kernel")

    # Rigorous power-law-vs-exponential tail test (Clauset/Vuong), not binned regression.
    gd = tail_test(dist)
    gs = tail_test(trades["qty"].to_numpy()) if "qty" in trades.columns else None
    fp = fingerprint(trades.reset_index(drop=True).set_axis(
        pd.RangeIndex(len(trades)).map(lambda i: pd.Timestamp("2000-01-01") + pd.Timedelta(seconds=i))
    ), cols=[c for c in ("price", "qty", "mid") if c in trades.columns], round_dp=8)

    print(f"[real order flow] {dist.size:,} trades   fingerprint={fp}")
    print(f"  |price-mid| tail: alpha={gd['alpha']}  V={gd['V']}  p={gd['p']:.1e}  -> {gd['winner']}")
    if gs:
        print(f"  order-size  tail: alpha={gs['alpha']}  V={gs['V']}  p={gs['p']:.1e}  -> {gs['winner']}")

    def verdict(g):
        return {"power-law": "REJECTS the exponential AS kernel (heavy-tailed)",
                "exponential": "is consistent with the exponential AS kernel",
                "inconclusive": "is inconclusive (neither tail wins)"}[g["winner"]]

    size_line = (f"| order size | alpha = {gs['alpha']} | V = {gs['V']} | {gs['p']:.1e} | **{gs['winner']}** |\n"
                 if gs else "")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(f"""# Real-data leg — Study 09 (Phantom-Kernel)

*Generated by [`examples/verify_real.py`](../examples/verify_real.py) on {dist.size:,} real
trades. Test: Clauset-Shalizi-Newman power-law fit + Vuong likelihood ratio (`V > 0` favours a
power-law tail; winner declared at `p < 0.05`). Fingerprint **`{fp}`**.*

| quantity | power-law exponent | Vuong V | p | tail |
|---|---|---|---|---|
| \\|price - mid\\| | alpha = {gd['alpha']} | V = {gd['V']} | {gd['p']:.1e} | **{gd['winner']}** |
{size_line}
**Read:** the price-distance tail {verdict(gd)}{(' ; order size ' + verdict(gs)) if gs else ''}.
""")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
