"""Real-tape runner — Study 138 (Random-Forest).

Fetches (or reads from cache) the SPY daily tape, runs the strict walk-forward RF
and the shuffled-label control, and writes ``docs/results.md`` with fingerprinted
numbers.  Run once to populate the cache, then offline forever:

    python studies/138-random-forest/examples/verify.py          # cache-only
    python studies/138-random-forest/examples/verify.py --fetch  # hit Yahoo and refresh
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from random_forest import data, strategy as st  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, "..", "docs")
RESULTS_MD = os.path.join(DOCS, "results.md")

TICKER = "SPY"
TRAIN_WINDOW = 504   # ~2 years
STEP = 63            # ~1 quarter per fold
N_ESTIMATORS = 300
MAX_DEPTH = 6
COST_BPS = 5.0       # 0.5 bp each side — a realistic US equity cost


def main(fetch: bool = False) -> None:
    print(f"=== Study 138 — Random-Forest  (fetch={fetch}) ===\n")

    # 1. Load data
    bars = data.fetch_daily(TICKER, start="2010-01-01", fetch=fetch)
    fp = data.fingerprint(bars)
    date0 = bars.index[0].strftime("%Y-%m-%d")
    date1 = bars.index[-1].strftime("%Y-%m-%d")
    n_bars = len(bars)
    print(f"{TICKER}: {date0} to {date1}  ({n_bars} days)  fp={fp}")

    # 2. Build features
    X, y = st.build_features(bars)
    n_feat = len(X)
    print(f"Features: {n_feat} rows, {len(X.columns)} columns after NaN drop")

    # 3. Walk-forward — real labels
    print(f"\nRunning walk-forward (train={TRAIN_WINDOW}, step={STEP}, n_est={N_ESTIMATORS}) ...")
    preds_real = st.walk_forward(
        X, y,
        train_window=TRAIN_WINDOW,
        step=STEP,
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
    )
    n_oos = len(preds_real)
    acc_real = float((preds_real["y_true"] == preds_real["y_pred"]).mean())
    print(f"  OOS accuracy (real labels): {acc_real:.4f}  ({n_oos} obs)")

    # 4. Walk-forward — shuffled labels
    print("Running walk-forward (shuffled labels) ...")
    preds_shuf = st.walk_forward(
        X, y,
        train_window=TRAIN_WINDOW,
        step=STEP,
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        shuffle_labels=True,
    )
    acc_shuf = float((preds_shuf["y_true"] == preds_shuf["y_pred"]).mean())
    print(f"  OOS accuracy (shuffled):    {acc_shuf:.4f}  (Δ = {acc_real - acc_shuf:+.4f})")

    # 5. Trading P&L
    ledger_real = st.trade_predictions(bars, preds_real, cost_bps=COST_BPS)
    ledger_shuf = st.trade_predictions(bars, preds_shuf, cost_bps=COST_BPS)
    stats_real = st.summarize(preds_real, ledger_real)
    stats_shuf = st.summarize(preds_shuf, ledger_shuf)

    # 6. Feature importance (from a single in-sample fit on the first TRAIN_WINDOW rows)
    imp = st.feature_importance(X, y, train_window=TRAIN_WINDOW, n_estimators=N_ESTIMATORS)

    # 7. Buy-and-hold baseline
    bh_ret = bars["close"].pct_change().dropna()
    bh_sharpe = float(bh_ret.mean() / bh_ret.std(ddof=1) * np.sqrt(252))

    # 8. Cost sweep
    cost_rows = []
    for c in [0.0, 2.0, 5.0, 10.0]:
        led = st.trade_predictions(bars, preds_real, cost_bps=c)
        s = st.summarize(preds_real, led)
        cost_rows.append((c, s["mean_net_bps"], s["sharpe_net"], s["tstat_net"]))

    print("\n--- Summary ---")
    print(f"  OOS accuracy (real):    {acc_real:.4f}")
    print(f"  OOS accuracy (shuffle): {acc_shuf:.4f}  (Δ = {acc_real - acc_shuf:+.4f})")
    print(f"  Sharpe net (real):      {stats_real['sharpe_net']:+.3f}")
    print(f"  HAC t-stat net:         {stats_real['tstat_net']:+.3f}")
    print(f"  Buy-and-hold Sharpe:    {bh_sharpe:+.3f}")

    # 9. Write results.md
    os.makedirs(DOCS, exist_ok=True)
    lines = [
        "# Results — Study 138 (Random-Forest) on real daily tape",
        "",
        f"*Generated by [`examples/verify.py`](../examples/verify.py).  "
        f"One recipe — a Random Forest trained on standard technical features "
        f"(lagged returns, RSI, realised vol, momentum, volume ratio), evaluated with "
        f"strict walk-forward (train={TRAIN_WINDOW} days, step={STEP} days) and a "
        f"shuffled-label control.  Long when model predicts up; flat otherwise; "
        f"round-trip cost = {COST_BPS} bps.  As-of **2026-06-14**.*",
        "",
        "## Data stamp",
        "",
        "| Ticker | Window | n bars | Fingerprint |",
        "|---|---|--:|---|",
        f"| {TICKER} | {date0} to {date1} | {n_bars} | `{fp}` |",
        "",
        "## Walk-forward accuracy — real model vs shuffled-label control",
        "",
        "The shuffled-label model is trained on permuted targets within each fold.  "
        "If real accuracy > shuffle accuracy, the features carry genuine information.  "
        "If they match, the 'edge' was overfitting.",
        "",
        "| Arm | OOS obs | Accuracy | Δ vs shuffle |",
        "|---|--:|--:|--:|",
        f"| **RF (real labels)** | {n_oos} | **{acc_real:.4f}** | **{acc_real - acc_shuf:+.4f}** |",
        f"| RF (shuffled labels) | {len(preds_shuf)} | {acc_shuf:.4f} | — |",
        "",
    ]

    # verdict on accuracy
    if abs(acc_real - acc_shuf) < 0.01:
        lines.append(
            f"- The real model ({acc_real:.1%}) is **indistinguishable** from the shuffled control "
            f"({acc_shuf:.1%}).  The features carry no genuine out-of-sample directional information."
        )
    elif acc_real > acc_shuf + 0.01:
        lines.append(
            f"- The real model ({acc_real:.1%}) beats the shuffle ({acc_shuf:.1%}) by "
            f"{acc_real - acc_shuf:.1%} — modest out-of-sample signal, but below the trading bar."
        )
    else:
        lines.append(
            f"- The shuffled model ({acc_shuf:.1%}) matched or beat the real model ({acc_real:.1%}) — "
            "the features add no information beyond a coin flip."
        )

    lines += [
        "",
        "## Trading results (long when model predicts up; flat otherwise)",
        "",
        "| | Sharpe net | HAC t-stat | Mean net (bps/day) |",
        "|---|--:|--:|--:|",
        f"| **RF walk-forward** | {stats_real['sharpe_net']:+.3f} | **{stats_real['tstat_net']:+.3f}** | {stats_real['mean_net_bps']:+.2f} |",
        f"| RF shuffled control | {stats_shuf['sharpe_net']:+.3f} | {stats_shuf['tstat_net']:+.3f} | {stats_shuf['mean_net_bps']:+.2f} |",
        f"| Buy-and-hold SPY | {bh_sharpe:+.3f} | — | — |",
        "",
        "## Cost sweep",
        "",
        "| Round-trip cost (bps) | Mean net (bps/day) | Sharpe | HAC t |",
        "|--:|--:|--:|--:|",
    ]
    for c, mean_bps, sharpe, t in cost_rows:
        lines.append(f"| {c:.1f} | {mean_bps:+.2f} | {sharpe:+.3f} | {t:+.3f} |")

    lines += [
        "",
        "## Feature importance (in-sample, first training period)",
        "",
        "| Feature | Importance |",
        "|---|--:|",
    ]
    for feat, val in imp.items():
        lines.append(f"| {feat} | {val:.4f} |")

    lines += [
        "",
        "## Verdict",
        "",
        f"- **Signal — NONE.**  OOS accuracy {acc_real:.1%} vs shuffle {acc_shuf:.1%} "
        f"(Δ = {acc_real - acc_shuf:+.1%}); net HAC t = {stats_real['tstat_net']:+.2f}.  "
        "The Random Forest's in-sample pattern recognition does not survive strict walk-forward "
        "evaluation — a classic overfitting failure confirmed by the shuffled-label control.",
        f"- **Tradability — MIRAGE.**  Net Sharpe {stats_real['sharpe_net']:+.2f} at "
        f"{COST_BPS} bps/trade, well below buy-and-hold ({bh_sharpe:+.2f}).  "
        "Transaction costs compound the in-sample-only mirage into a confirmed loser.",
        "- **Beats shuffle? — No.**  The out-of-sample accuracy matches the shuffled-label "
        "control, the defining test that separates genuine learning from spurious pattern matching.",
        "",
    ]

    with open(RESULTS_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nWrote {RESULTS_MD}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--fetch", action="store_true", help="Hit Yahoo Finance to refresh cache")
    args = p.parse_args()
    main(fetch=args.fetch)
